test: add rpma_ep_listen multithreaded test
pmem/rpma pull request #1017
Opened 2021-04-22 09:58 UTC by ewanglong

2021-04-22 12:38 UTC, ldorau reviewed
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 1 of 9 files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-22 23:45 UTC, janekmi requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvrYzC3b2FRV5cDVsl:-MYvrYzC3b2FRV5cDVsm:bcegea8) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/cmake/ctest_helpers.cmake#L248)):*
> ```CMake
> 	endif()
> 
> 	add_test_generic(NAME ${target} CASE ${MULTITHREADED_CASE} GROUP_SCRIPT TRACERS none drd helgrind)
> ```

.

Please see other comments.
___
*[tests/multithreaded/run_group_1.cmake, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvqUfv4XjWnRw8vcjm:-MYvqUfv4XjWnRw8vcjn:bqf1264) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/run_group_1.cmake#L1)):*
> ```CMake
> #
> ```

I think it will be a lot easier to assume all the MT tests got both address and port and some of them just ignore them instead of building all this machinery.
I recommend adding SOFT_ROCE_PORT to `run_group.cmake`.
___
*[tests/multithreaded/common/mtt.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvtCOC36yFig2G1ng_:-MYvtCOC36yFig2G1nga:b-cp8olo) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.h#L17)):*
> ```objc
> 	unsigned threads_num;
> 	char *addr;
> 	char *port;
> ```

I think it will be a little bit easier to follow and reuse code having here:

```c
unsigned port
```

So, in the `mtt_parse_args()` you need something like:

```c
args->port = strtoul(argv[3], NULL, 10);
```

Additionally, it would be nice to have a few helpers in here:

```c
#define MTT_PORT_STR _mtt_port_str
#define MTT_PORT_INIT char MTT_PORT[MTT_PORT_STR_MAX]

#define MTT_PORT_SET(base_port, thread_id) \
    snprintf(MTT_PORT_STR, MTT_PORT_STR_MAX, "%u", (base_port) + (thread_id))
```

So, where you need to have a part you can just do:

```c
MTT_PORT_INIT;

MTT_PORT_SET(ps->port, id);

int ret = rpma_ep_listen(pr->peer, pr->addr, MTT_PORT_STR, &st->ep);
...

Please keep all these new defines after the `mtt_parse_args()` bet separate to `MTT_ERRMSG_MAX`
```
___
*[tests/multithreaded/common/mtt.h, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvuj6j9tIgg6BOuYBN:-MYvuj6j9tIgg6BOuYBO:b-ami76r) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.h#L22)):*
> ```objc
> int mtt_parse_args(int argc, char *argv[], struct mtt_args *args);
> 
> #define MTT_PORTDIGITS_MAX 5
> ```

We need a place for 65535 and one character for '\0'.

`MTT_PORT_STR_MAX 6`
___
*[tests/multithreaded/common/mtt.c, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvrGja9_NIsjWQuHND:-MYvrGjbA-V9xnotqE5b:bn6yu1) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.c#L205)):*
> ```C
> {
> 	if (argc < 3) {
> 		fprintf(stderr, "usage: %s <threads_num> <addr>\n", argv[0]);
> ```

<threads_num> <addr> [<base_port>]
___
*[tests/multithreaded/ep/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvrRpTAUjd-EOFPQ_B:-MYvrRpTAUjd-EOFPQ_C:bk4cj3h) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/CMakeLists.txt#L12)):*
> ```CMake
> 
> add_multithreaded(NAME ep BIN rpma_ep_listen
> 	CASE 1 SRCS rpma_ep_listen.c)
> ```

I believe `CASE 1` won't be needed here. Please see other comments.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvxMNA1s4tHG8Rtr_2:-MYvxMNBDS2DnB-N46iT:b-f7a7yl) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L34)):*
> ```C
> {
> 	struct prestate *pr = (struct prestate *)prestate;
> 	struct state *st = (struct state *)calloc(1, sizeof(struct state));
> ```

State, in this case, can be allocated in parallel. See the comment below.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvwlSlC3H451bFyxom:-MYvwlSmE7RSKPwbyvD_:b-mlp1on) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L49)):*
> ```C
> 
> 	/* create a new peer object */
> 	ret = rpma_peer_new(pr->dev, &pr->peer);
> ```

Both `dev` and `peer` are set multiple times. Please create them before the test.

I see it will be handy to have a common init/fini for prestate. You have to write initialize and clean up the prestate for yourself for now before and after calling `mtt_run()`.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvxiTB9OSa9ocluKOW:-MYvxiTC03pW8E1E-Z6S:b-xx7073) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L60)):*
> ```C
> /*
>  * thread -- try to start a listening endpoint at addr:port
>  * (input port + thread id)
> ```

`start a listening endpoint`

Since the port calculation method will be common there is no point in writing it down right here.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvyEtu6teUcyFaC4aM:-MYvyEtu6teUcyFaC4aN:b-3om20i) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L82)):*
> ```C
> 
> /*
>  * fini -- a parallel step of cleanup
> ```

shutdown the endpoint and free the state
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvy3nZA4VkV61Ve9Sb:-MYvy3nZA4VkV61Ve9Sc:bty8v5j) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L85)):*
> ```C
>  *
>  * Everything that can be cleaned up after the test in a thread-safe manner
>  * should go here.
> ```

No generic comments.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvyMeDBezHCNZak2rC:-MYvyMeDBezHCNZak2rD:b-1kbylq) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L110)):*
> ```C
> static void
> seq_fini(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *tr)
> ```

I think this step won't be needed. Please see other comments.
___
*[tests/multithreaded/peer/CMakeLists.txt, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvpfuHANFTjeEDu0XI:-MYvpfuI28SPfYxaqEJ9:b-8s6w22) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/peer/CMakeLists.txt#L1)):*
> ```CMake
> #
> ```

This is not part of this PR. If you do not have any particular reason please remove the commit we already know from #1008.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvq78HBtYbRl285a9F:-MYvq78HBtYbRl285a9G:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/peer/rpma_peer_new.c#L1)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> ```

Please remove.


<!-- Sent from Reviewable.io -->

2021-04-23 00:22 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvwlSlC3H451bFyxom:-MYw5KU10y-vk1tdMaLf:b7b2cu) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Both `dev` and `peer` are set multiple times. Please create them before the test.

I see it will be handy to have a common init/fini for prestate. You have to write initialize and clean up the prestate for yourself for now before and after calling `mtt_run()`.
</blockquote></details>

Please take a look at #1019. I think if that one will be merged sooner than this PR it will make this PR a little simpler.


<!-- Sent from Reviewable.io -->

2021-04-23 07:48 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 1 of 10 files reviewed, 14 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvrYzC3b2FRV5cDVsl:-MYxgdFW8X99zqWxkBQi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.

Please see other comments.
</blockquote></details>

Done.
___
*[tests/multithreaded/run_group_1.cmake, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvqUfv4XjWnRw8vcjm:-MYxgeVrEJ9A9ZuAYgkx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/run_group_1.cmake#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be a lot easier to assume all the MT tests got both address and port and some of them just ignore them instead of building all this machinery.
I recommend adding SOFT_ROCE_PORT to `run_group.cmake`.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvtCOC36yFig2G1ng_:-MYxgfk15cvVTrax9u8j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.h#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be a little bit easier to follow and reuse code having here:

```c
unsigned port
```

So, in the `mtt_parse_args()` you need something like:

```c
args->port = strtoul(argv[3], NULL, 10);
```

Additionally, it would be nice to have a few helpers in here:

```c
#define MTT_PORT_STR _mtt_port_str
#define MTT_PORT_INIT char MTT_PORT[MTT_PORT_STR_MAX]

#define MTT_PORT_SET(base_port, thread_id) \
    snprintf(MTT_PORT_STR, MTT_PORT_STR_MAX, "%u", (base_port) + (thread_id))
```

So, where you need to have a part you can just do:

```c
MTT_PORT_INIT;

MTT_PORT_SET(ps->port, id);

int ret = rpma_ep_listen(pr->peer, pr->addr, MTT_PORT_STR, &st->ep);
...

Please keep all these new defines after the `mtt_parse_args()` bet separate to `MTT_ERRMSG_MAX`
```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvuj6j9tIgg6BOuYBN:-MYxggOQ273K-GLatdF6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.h#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We need a place for 65535 and one character for '\0'.

`MTT_PORT_STR_MAX 6`
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvrGja9_NIsjWQuHND:-MYxgh1_-PsxSWFRHQwk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.c#L205)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

<threads_num> <addr> [<base_port>]
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/CMakeLists.txt, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvrRpTAUjd-EOFPQ_B:-MYxghimCmCrdl0qGzDP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/CMakeLists.txt#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe `CASE 1` won't be needed here. Please see other comments.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvxMNA1s4tHG8Rtr_2:-MYxgiu_03tExbrhgaAN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

State, in this case, can be allocated in parallel. See the comment below.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvxiTB9OSa9ocluKOW:-MYxgn57-9j-UFoaLpuG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`start a listening endpoint`

Since the port calculation method will be common there is no point in writing it down right here.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvyEtu6teUcyFaC4aM:-MYxgo_T24OlejhIRaQj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

shutdown the endpoint and free the state
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvy3nZA4VkV61Ve9Sb:-MYxgnwQE8OPTAgVegRK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No generic comments.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvyMeDBezHCNZak2rC:-MYxgqS8Ao8uKqdcwSB5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/ep/rpma_ep_listen.c#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this step won't be needed. Please see other comments.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/CMakeLists.txt, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvpfuHANFTjeEDu0XI:-MYxgrFZDhz2mVyRprRt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/peer/CMakeLists.txt#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is not part of this PR. If you do not have any particular reason please remove the commit we already know from #1008.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvq78HBtYbRl285a9F:-MYxgroy7OGOoEYfy_tr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/peer/rpma_peer_new.c#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 10:08 UTC, ldorau requested changes
> Reviewed 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 9 of 10 files reviewed, 16 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/run_group.cmake, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYyAPUZDjGVsfB7DRO1:-MYyAPU_A5eTUENIQPjk:b-g2z992) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/run_group.cmake#L19)):*
> ```
> "4791"
> ```

Please use 7204 instead. The 4791 port can be used: https://www.speedguide.net/port.php?port=4791
We are using the 7204 port which is unassigned: https://www.speedguide.net/port.php?port=7204
___
*[tests/multithreaded/common/mtt.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvtCOC36yFig2G1ng_:-MYyBblWEzY34l7nqqA4:bebdodd) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.h#L17)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

port is still of `char *` type, not `unsigned.`
___
*[tests/multithreaded/ep/CMakeLists.txt, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYyBFAMDW4M_qbNZgR5:-MYyBFAMDW4M_qbNZgR6:bn8j30y) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/ep/CMakeLists.txt#L3)):*
> ```
> 2020-2021
> ```

2021 is enough


<!-- Sent from Reviewable.io -->

2021-04-23 10:51 UTC, janekmi reviewed
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-23 13:24 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYytgPX9QUZqDHBI8K_:-MYytgPX9QUZqDHBI8Ka:b-3b34ok) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/ep/rpma_ep_listen.c#L100)):*
> ```C
> 		fprintf(stderr, "rpma_peer_new failed\n");
> 		return;
> 	}
> ```

You can now make use of prestate_init callback.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYytl8_1UExpcHJRcO-:-MYytl8_1UExpcHJRcO0:bsggud6) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/ep/rpma_ep_listen.c#L116)):*
> ```C
> 	/* delete the peer object */
> 	if ((ret = rpma_peer_delete(&prestate.peer)))
> 		fprintf(stderr, "rpma_peer_delete failed\n");
> ```

You can now make use of prestate_fini callback.


<!-- Sent from Reviewable.io -->

2021-04-23 13:53 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/run_group.cmake, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYyAPUZDjGVsfB7DRO1:-MYz-PW83fC5upDuS5ul:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/run_group.cmake#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "4791"
> ```

Please use 7204 instead. The 4791 port can be used: https://www.speedguide.net/port.php?port=4791
We are using the 7204 port which is unassigned: https://www.speedguide.net/port.php?port=7204

</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1017#-MYvtCOC36yFig2G1ng_:-MYz-UKL5poqJ06bdirD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6ede63e7434be84c4e69c812be52c0ce73f5e1fe/tests/multithreaded/common/mtt.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

port is still of `char *` type, not `unsigned.`
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/CMakeLists.txt, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYyBFAMDW4M_qbNZgR5:-MYz-V9GDKzjW5iX21CA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/ep/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 2020-2021
> ```

2021 is enough
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYytgPX9QUZqDHBI8K_:-MYz-M7J9FqQH2_wOLt-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/ep/rpma_ep_listen.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can now make use of prestate_init callback.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1017#-MYytl8_1UExpcHJRcO-:-MYz-OQ59tsmYR4ffcVG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe06f8d8116a2274250822133064faac172c960d/tests/multithreaded/ep/rpma_ep_listen.c#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can now make use of prestate_fini callback.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-23 14:20 UTC, ldorau reviewed
> Reviewed 6 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-23 14:30 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1017#-MYz7sNc9ITQ1xgekszF:-MYz7sNc9ITQ1xgekszG:b-90ypq5) ([raw file](https://github.com/pmem/rpma/blob/a45647b2383f6cf360396516fc2de0036015513e/tests/multithreaded/ep/rpma_ep_listen.c#L14)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> #include <errno.h>
> #include <inttypes.h>
> #include <stdint.h>
> #include <stdio.h>
> #include <stdlib.h>
> #include <string.h>
> #include <librpma.h>
> ```
</details>


Those two should be enough:
```
#include <stdlib.h>
#include <librpma.h>
```


<!-- Sent from Reviewable.io -->

2021-04-23 14:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1017#-MYzA8Yc0YPgYB--IbVc:-MYzA8YdEi9Iuf7ePKg8:b-n6khor) (no related file):*
Please rebase

---


<!-- Sent from Reviewable.io -->

2021-04-23 14:45 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1017#-MYzA8Yc0YPgYB--IbVc:-MYzB7Rt8wFGZy_k2y10:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1017#-MYz7sNc9ITQ1xgekszF:-MYzB8J0-1ZiGXNTzKS3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a45647b2383f6cf360396516fc2de0036015513e/tests/multithreaded/ep/rpma_ep_listen.c#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #include <errno.h>
> #include <inttypes.h>
> #include <stdint.h>
> #include <stdio.h>
> #include <stdlib.h>
> #include <string.h>
> #include <librpma.h>
> ```

Those two should be enough:
```
#include <stdlib.h>
#include <librpma.h>
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-26 10:38 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1017#-MZCih_H8fDXIp8z7F0K:-MZCih_H8fDXIp8z7F0L:b-8qlhr2) (no related file):*
Missing suppressions have to be added also, because the `70 - multithreaded-ep-rpma_ep_listen_0_helgrind (Failed)`  test is failing on Circle CI:
https://app.circleci.com/pipelines/github/pmem/rpma/91/workflows/2a6f9c37-dfc8-4055-9b76-2cff35f95fde/jobs/94

---
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZCk0Qw-fa7l5h4iTnI:-MZCk0Qw-fa7l5h4iTnJ:bd8usuz) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L36)):*
> ```
> MTT_RPMA_ERR(tr, "rpma_utils_get_ibv_context", ret);
> ```

There should be `return` after it, because the next call can overwrite the current error information.


<!-- Sent from Reviewable.io -->

2021-04-27 01:42 UTC, janekmi requested changes
> Reviewed 4 of 7 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZCR4L08pnlPQykdSYz:-MZCR4L08pnlPQykdSZ-:byme3df) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L35)):*
> ```C
> 
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_REMOTE, &pr->dev)))
> ```

Since this `ibv_context` is used to create a listening endpoint I think it is more natural to use here `_CONTEXT_LOCAL`.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZCk0Qw-fa7l5h4iTnI:-MZFz-KK7SoF-tTt0NW2:b-tnmtz0) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MTT_RPMA_ERR(tr, "rpma_utils_get_ibv_context", ret);
> ```

There should be `return` after it, because the next call can overwrite the current error information.
</blockquote></details>

What is even worse a peer object will be created which won't be cleaned up since this step will be considered failed.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 74 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZFzLHf0e4ZIOQHwKXi:-MZFzLHf0e4ZIOQHwKXj:b-uphd0z) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L74)):*
> ```C
> 	if (ret) {
> 		MTT_RPMA_ERR(result, "rpma_ep_listen", ret);
> 		return;
> ```

Not needed. Please remove.


<!-- Sent from Reviewable.io -->

2021-04-27 02:58 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZCR4L08pnlPQykdSYz:-MZGFg2w4217B4H24XP2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since this `ibv_context` is used to create a listening endpoint I think it is more natural to use here `_CONTEXT_LOCAL`.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZCk0Qw-fa7l5h4iTnI:-MZGFh7e3873azjmSWgH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is even worse a peer object will be created which won't be cleaned up since this step will be considered failed.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_listen.c, line 74 at r4](https://reviewable.io/reviews/pmem/rpma/1017#-MZFzLHf0e4ZIOQHwKXi:-MZGFhwJEZu0Je5HJC38:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b2d8e0c5cb64397000beee60c86148c0ba80fec4/tests/multithreaded/ep/rpma_ep_listen.c#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed. Please remove.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-27 04:41 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-27 12:12 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1017#-MZCih_H8fDXIp8z7F0K:-MZHroJTEvbKw7EicKuq:b8z1nvv) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Missing suppressions have to be added also, because the `70 - multithreaded-ep-rpma_ep_listen_0_helgrind (Failed)`  test is failing on Circle CI:
https://app.circleci.com/pipelines/github/pmem/rpma/91/workflows/2a6f9c37-dfc8-4055-9b76-2cff35f95fde/jobs/94
</blockquote></details>

I'm not sure but it seems the CircleCI fail was related to some kind of an issue in the implementation. It is hard to track it down now. I have made a rerun and the current result seems legit. Nothing more in suppressions is missing.

---


<!-- Sent from Reviewable.io -->

2021-04-27 12:12 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017#-:-MZIEaPJ58KVOD_C946u:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-04-27 12:36 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1017#-MZCih_H8fDXIp8z7F0K:-MZIK-Lw2BiqN29klOZV:b32w0x) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure but it seems the CircleCI fail was related to some kind of an issue in the implementation. It is hard to track it down now. I have made a rerun and the current result seems legit. Nothing more in suppressions is missing.
</blockquote></details>

OK

---


<!-- Sent from Reviewable.io -->

2021-04-27 12:37 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-27 12:37 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017#-:-MZIKTluDAcQpV2s6d0M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-27 12:56 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1017)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-27 12:56 UTC, merged