Separate recv cq
pmem/rpma pull request #1035
Opened 2021-04-29 09:02 UTC by yangx-jy

2021-05-05 07:50 UTC, janekmi requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 1 of 37 files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

___
*[src/cq.h, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvTQ6n8pzQeRh2R9GX:-MZvTQ6n8pzQeRh2R9GY:b-spcrdm) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L19)):*
> ```objc
> 	struct ibv_comp_channel *channel; /* completion event channel */
> 	struct ibv_cq *cq; /* completion queue */
> };
> ```

We do not endorse public structures. So far we managed to keep all modules self-contained. Providing a public structure allows thinking of cutting the corners by changing the structure directly instead of allowing the module to solely manage its objects.
___
*[src/cq.h, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvVIlmB94qtUmd0dBJ:-MZvVIlmB94qtUmd0dBK:b-forn9p) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L70)):*
> ```objc
>  * failed with a provider error
>  */
> int rpma_cq_destroy(struct rpma_cq **cq_ptr);
> ```

So far, we follow the new/delete naming convention.


<!-- Sent from Reviewable.io -->

2021-05-05 09:24 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 1 of 37 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/cq.h, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvTQ6n8pzQeRh2R9GX:-MZvouITCOAPOkLAkxVP:b-346gp0) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We do not endorse public structures. So far we managed to keep all modules self-contained. Providing a public structure allows thinking of cutting the corners by changing the structure directly instead of allowing the module to solely manage its objects.
</blockquote></details>

Do you mean that we should move the definition of `struct rpma_cq` to cq.c and provide APIs (e.g. `rpma_cq_get_cq()`) to access the member of `struct rpma_cq`?
___
*[src/cq.h, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvVIlmB94qtUmd0dBJ:-MZvpvM41uu2bb6cFvpr:bqitfoy) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So far, we follow the new/delete naming convention.
</blockquote></details>

OK, I will rename them.


<!-- Sent from Reviewable.io -->

2021-05-05 09:32 UTC, janekmi requested changes
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 3 of 37 files reviewed, 23 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 489 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvWTN32EfGV5HDktul:-MZvWTN32EfGV5HDktum:b-l9ixq) ([raw file](https://github.com/pmem/rpma/blob/239477aaf3998c04b4bce818129f05373cb18bef/src/conn.c#L489)):*
> ```C
> rpma_conn_get_completion_fd(const struct rpma_conn *conn, int *fd)
> {
> 	if (conn == NULL || fd == NULL)
> ```

`fd == NULL` validation should stay where it is. Validation should take place as quick as possible. No point going furhter.
___
*[src/conn.c, line 538 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvpRZx8Uc5v5by5Edo:-MZvpRZx8Uc5v5by5Edp:bbylef0) ([raw file](https://github.com/pmem/rpma/blob/239477aaf3998c04b4bce818129f05373cb18bef/src/conn.c#L538)):*
> ```C
> 		struct rpma_completion *cmpl)
> {
> 	if (conn == NULL || cmpl == NULL)
> ```

`cmpl == NULL` should stay here.
___
*[src/cq.h, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvTQ6n8pzQeRh2R9GX:-MZvqZDYBnZdPmdTT3S7:b-s73to1) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L19)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Do you mean that we should move the definition of `struct rpma_cq` to cq.c and provide APIs (e.g. `rpma_cq_get_cq()`) to access the member of `struct rpma_cq`?
</blockquote></details>

I see the only place where it is needed is in the `rpma_peer_create_qp()`. Since both `send_cq` and `recv_cq` will be two different CQs in the near future I think what you propose is the best way of covering this use case. Maybe I would name the function `rpma_cq_get_ibv_cq()`. But I will leave it up to you.
___
*[src/cq.h, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvj2iY95MJPs--6O-W:-MZvj2iY95MJPs--6O-X:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L33)):*
> ```objc
>  * rpma_cq_wait() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - cq is NULL
> ```

Please remove.
___
*[src/cq.h, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvq2ph4xW1ToMkj8oR:-MZvq2ph4xW1ToMkj8oS:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L43)):*
> ```objc
>  * rpma_cq_get() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - cq or cmpl is NULL
> ```

Please remove.
___
*[src/cq.h, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvZMrh1bvWtfPG-ose:-MZvZMrh1bvWtfPG-osf:b-l5z3i) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L55)):*
> ```objc
>  * rpma_cq_create() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - verbs or cq_ptr is NULL
> ```

Please delete.
___
*[src/cq.h, line 60 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZv_HBb2KLh2TMQTy80:-MZv_HBcDsEvGP3QDYDq:b-forn9p) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L60)):*
> ```objc
>  * - RPMA_E_NOMEM - out of memory
>  */
> int rpma_cq_create(struct ibv_context *verbs, int cqe, struct rpma_cq **cq_ptr);
> ```

So far, we follow the new/delete naming convention.
___
*[src/cq.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvq5TT4aXtpaFyL9Ut:-MZvq5TT4aXtpaFyL9Uu:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L66)):*
> ```objc
>  * rpma_cq_destroy() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - cq_ptr is NULL
> ```

Please remove.
___
*[src/cq.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvdAwPAz7SEwSpoq5v:-MZvdAwPAz7SEwSpoq5w:b-wkr15u) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L24)):*
> ```C
> 
> /*
>  * rpma_cq_get_fd -- get a file descriptor of the completion event
> ```

Please call this channel consequently either 'a completion event channel' or 'a completion channel'.
___
*[src/cq.c, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvW6WABbO1UCCWDP5Z:-MZvW6WABbO1UCCWDP5_:b-364pro) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L25)):*
> ```C
> /*
>  * rpma_cq_get_fd -- get a file descriptor of the completion event
>  * channel associated with completion queue object
> ```

... the completion...
___
*[src/cq.c, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvdPIlBaJiLHZZKunM:-MZvdPIm2lpoUucVGVeu:bampjcx) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L25)):*
> ```C
> /*
>  * rpma_cq_get_fd -- get a file descriptor of the completion event
>  * channel associated with completion queue object
> ```

By 'the completion queue object' you mean the ibv_cq or rpma_cq?
___
*[src/cq.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvWlNoCA7eJngGzCwF:-MZvWlNpE7ueiJ4VXTLM:b-bc3fmy) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L30)):*
> ```C
> rpma_cq_get_fd(struct rpma_cq *cq, int *fd)
> {
> 	if (cq == NULL || fd == NULL)
> ```

`fd` should be validated in the `rpma_conn_get_completion_fd()` so you should have here what we call **an assumption**.
This idea aimed to keep separate the modules as far as possible but do not have everywhere code doing simple validation.
Because of this, we have agreed to define a protocol of expectations about the arguments being feed to any particular API.
You can see an example of assumptions here: https://github.com/pmem/rpma/blob/master/src/conn_req.c#L47
___
*[src/cq.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvYFkp3vm8k0QA_Umn:-MZvYFkp3vm8k0QA_Umo:b-gm2uuf) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L30)):*
> ```C
> rpma_cq_get_fd(struct rpma_cq *cq, int *fd)
> {
> 	if (cq == NULL || fd == NULL)
> ```

`cq` comes from the connection. Assuming you do not expect having a valid connection without `cq` `cq != NULL` is another assumption.
___
*[src/cq.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvfKGD1G2ct8dg_SpE:-MZvfKGD1G2ct8dg_SpF:b4rqapu) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L39)):*
> ```C
> 
> /*
>  * rpma_cq_wait -- wait for completions from completion queue object
> ```

wait for completions from completion queue object
___
*[src/cq.c, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvfCI66wFpE6XtzbYo:-MZvfCI66wFpE6XtzbYp:b5s8rat) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L45)):*
> ```C
> {
> 	if (cq == NULL)
> 		return RPMA_E_INVAL;
> ```

An assumption.
___
*[src/cq.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvp_K09pxnUZ0l1NX0:-MZvp_K09pxnUZ0l1NX1:bkshq5o) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L78)):*
> ```C
> {
> 	if (cq == NULL || cmpl == NULL)
> 		return RPMA_E_INVAL;
> ```

Both are assumptions.
___
*[src/cq.c, line 147 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvb7hyB9Sy7MLhoLJ-:-MZvb7hz21kWAJkiiAEA:b-rswaw9) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L147)):*
> ```C
> 
> /*
>  * rpma_cq_create -- create a completion queue object
> ```

Comments inside the module are intended to describe in more detail what the function really does e.g.:
`create a completion channel and CQ and encapsulate both in the common object`
___
*[src/cq.c, line 150 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvYtWH4-Btu9QuTYhI:-MZvYtWH4-Btu9QuTYhJ:b-7uiwuf) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L150)):*
> ```C
>  * [...]

2021-05-05 09:58 UTC, janekmi requested changes
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 6 of 37 files reviewed, 26 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 273 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvu0rIEieBRfu8cqYs:-MZvtwm_7N6W8UCFUAKf:b-rtagwg) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/conn.c#L273)):*
> ```C
> 	return 0;
> 
> err_rpma_cq_destroy:
> ```

delete
___
*[src/conn_req.c, line 64 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvuyGME23PVdsKWEA9:-MZvuyGME23PVdsKWEAA:b-id5qng) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/conn_req.c#L64)):*
> ```C
> 
> 	/* create a QP */
> 	ret = rpma_peer_create_qp(peer, id, cq->cq, cfg);
> ```

I think `rpma_peer_create_qp` should accept `rpma_cq`. The `rpma_cq_get_ibv_cq()` would be called internally.
___
*[src/conn_req.c, line 86 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvwgrB83Ti9Si9t2-U:-MZvwgrB83Ti9Si9t2-V:b-rtagwg) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/conn_req.c#L86)):*
> ```C
> 	rdma_destroy_qp(id);
> 
> err_rpma_cq_destroy:
> ```

delete
___
*[src/cq.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvWlNoCA7eJngGzCwF:-MZvxVe23z00CK02eVg0:b-q4ijy8) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`fd` should be validated in the `rpma_conn_get_completion_fd()` so you should have here what we call **an assumption**.
This idea aimed to keep separate the modules as far as possible but do not have everywhere code doing simple validation.
Because of this, we have agreed to define a protocol of expectations about the arguments being feed to any particular API.
You can see an example of assumptions here: https://github.com/pmem/rpma/blob/master/src/conn_req.c#L47
</blockquote></details>

**Note**: Assumptions does not require tests but you have to assert them on the mock level.


<!-- Sent from Reviewable.io -->

2021-05-06 12:18 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 2 of 43 files reviewed, 26 unresolved discussions (waiting on @janekmi)

___
*[src/conn.c, line 273 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvu0rIEieBRfu8cqYs:-M_0_cjYCSGgd1x6LgxD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/conn.c#L273)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[src/conn.c, line 489 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvWTN32EfGV5HDktul:-M_0_gtG-UBzq7dkykBs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/239477aaf3998c04b4bce818129f05373cb18bef/src/conn.c#L489)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`fd == NULL` validation should stay where it is. Validation should take place as quick as possible. No point going furhter.
</blockquote></details>

Done.
___
*[src/conn.c, line 538 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvpRZx8Uc5v5by5Edo:-M_0_iyG0I7d8rH4sDNj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/239477aaf3998c04b4bce818129f05373cb18bef/src/conn.c#L538)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cmpl == NULL` should stay here.
</blockquote></details>

Done.
___
*[src/conn_req.c, line 64 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvuyGME23PVdsKWEA9:-M_0_mcB-z-4XXWniBec:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/conn_req.c#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think `rpma_peer_create_qp` should accept `rpma_cq`. The `rpma_cq_get_ibv_cq()` would be called internally.
</blockquote></details>

Done.
___
*[src/conn_req.c, line 86 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvwgrB83Ti9Si9t2-U:-M_0_o4R380___PdEb2a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/conn_req.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[src/cq.h, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvTQ6n8pzQeRh2R9GX:-M_0_sBQAYwBel3qpjgx:btz9im8) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I see the only place where it is needed is in the `rpma_peer_create_qp()`. Since both `send_cq` and `recv_cq` will be two different CQs in the near future I think what you propose is the best way of covering this use case. Maybe I would name the function `rpma_cq_get_ibv_cq()`. But I will leave it up to you.
</blockquote></details>

I have named the function `rpma_cq_get_ibv_cq()`, done.
___
*[src/cq.h, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvj2iY95MJPs--6O-W:-M_0a2sR8o13-PWLr0jv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/cq.h, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvq2ph4xW1ToMkj8oR:-M_0a3uW5e2DmCq5YQfJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/cq.h, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvZMrh1bvWtfPG-ose:-M_0a6O19RR28fiGgBt9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please delete.
</blockquote></details>

Done.
___
*[src/cq.h, line 60 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZv_HBb2KLh2TMQTy80:-M_0a7M37XcgXKs_O_tK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So far, we follow the new/delete naming convention.
</blockquote></details>

Done.
___
*[src/cq.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvq5TT4aXtpaFyL9Ut:-M_0a8Np96TATvuugfjb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/cq.h, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvVIlmB94qtUmd0dBJ:-M_0a9ooDQrmTau47yqW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.h#L70)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

OK, I will rename them.
</blockquote></details>

Done.
___
*[src/cq.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvdAwPAz7SEwSpoq5v:-M_0aEfzCoQbs7Jk8XT0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please call this channel consequently either 'a completion event channel' or 'a completion channel'.
</blockquote></details>

Done.
___
*[src/cq.c, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvW6WABbO1UCCWDP5Z:-M_0aFgs84NOwAshbDy7:br7pq09) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... the completion...
</blockquote></details>

How about the change?
```
rpma_cq_get_fd -- get a file descriptor of the completion event channel
from the rpma_cq object
```
___
*[src/cq.c, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvdPIlBaJiLHZZKunM:-M_0aQaU28NkyM8wstr7:b-1om5ah) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

By 'the completion queue object' you mean the ibv_cq or rpma_cq?
</blockquote></details>

I think rpma_cq is better.
___
*[src/cq.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvWlNoCA7eJngGzCwF:-M_0aWMWBuZ9j6W35iO1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Note**: Assumptions does not require tests but you have to assert them on the mock level.
</blockquote></details>

Done.
___
*[src/cq.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvYFkp3vm8k0QA_Umn:-M_0aZp7Dd_lyWwqIvDq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cq` comes from the connection. Assuming you do not expect having a valid connection without `cq` `cq != NULL` is another assumption.
</blockquote></details>

Done.
___
*[src/cq.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvfKGD1G2ct8dg_SpE:-M_0aasID1ClJSd9CATt:bgfx5wp) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

wait for completions from completion queue object
</blockquote></details>

How about the change?
```
rpma_cq_wait -- wait for completions from the  [...]

2021-05-11 21:33 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 2 of 43 files reviewed, 1 unresolved discussion (waiting on @janekmi and @yangx-jy)

___
*[src/cq.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvfKGD1G2ct8dg_SpE:-M_SKuLUBh2I6m-XEKRk:b-nvfyz9) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L39)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

How about the change?
```
rpma_cq_wait -- wait for completions from the rpma_cq object
```
</blockquote></details>

I think `... a completion from...` is more accurate since even a single one is enough.


<!-- Sent from Reviewable.io -->

2021-05-12 01:39 UTC, yangx-jy commented
___
*[src/cq.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1035#-MZvfKGD1G2ct8dg_SpE:-M_TDSdL3JV4suw9HhYW:b-fjbin2) ([raw file](https://github.com/pmem/rpma/blob/750f4113d42fc789f1d834367703cf501f8649b7/src/cq.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think `... a completion from...` is more accurate since even a single one is enough.
</blockquote></details>

Done.

I also update the description for rpma_conn_completion_wait.


<!-- Sent from Reviewable.io -->

2021-05-12 06:17 UTC, janekmi requested changes
> Reviewed 4 of 29 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 9 of 44 files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[src/conn_req.c, line 186 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_U8nXK-Qqgx_Nc-q7L:-M_U8nXK-Qqgx_Nc-q7M:bjkhkfu) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/conn_req.c#L186)):*
> ```C
> 	int ret = 0;
> 
> 	ret = rpma_cq_delete(&req->cq);
> ```

I think we can join both lines:

```c
int ret = rpma_cq_delete(&req->cq);
```
___
*[src/conn_req.c, line 218 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_U8wnK8dbgHSnkOeYv:-M_U8wnK8dbgHSnkOeYw:bjkhkfu) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/conn_req.c#L218)):*
> ```C
> 	int ret = 0;
> 
> 	ret = rpma_cq_delete(&req->cq);
> ```

I think we can join both lines:

```c
int ret = rpma_cq_delete(&req->cq);
```
___
*[src/cq.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UCRMU9XBlTta_uzYl:-M_UCRMU9XBlTta_uzYm:b-ggn1ns) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.h#L18)):*
> ```objc
> struct rpma_cq;
> 
> int rpma_cq_get_fd(struct rpma_cq *cq, int *fd);
> ```

```c
/*
 * ERRORS
 * rpma_cq_get_fd() cannot fail.
 */
```
___
*[src/cq.h, line 59 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UCYqyCBUiiuECK-ye:-M_UCYqyCBUiiuECK-yf:b8wfiw6) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.h#L59)):*
> ```objc
> int rpma_cq_delete(struct rpma_cq **cq_ptr);
> 
> int rpma_cq_get_ibv_cq(struct rpma_cq *cq, struct ibv_cq **ibv_cq_ptr);
> ```

```c
/*
 * ERRORS
 * rpma_cq_get_ibv_cq() cannot fail.
 */
```
___
*[src/cq.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UBOafA3J_EE50nqqv:-M_UBOafA3J_EE50nqqw:bj0q11q) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.c#L30)):*
Please add a comment here just in case something will happen between this PR and the future one e.g.:

> XXX This function does not follow the rpma_cq_get_ibv_cq() schema because it is planned to be made public in the near future so it will have to handle cq and fd validation on its own.
___
*[src/cq.c, line 210 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UAvKf80d3_360B4aT:-M_UAvKf80d3_360B4aU:blpw2p4) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.c#L210)):*
> ```C
> 
> /*
>  * rpma_cq_delete -- destroy the CQ and completion channel and then
> ```

... the completion channel... ?
___
*[src/cq.c, line 252 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_U9a9aBT-kLU8Erl58:-M_U9a9aBT-kLU8Erl59:b2eqqf5) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.c#L252)):*
> ```C
> 
> 	return 0;
> }
> ```

Since this getter is and will be internal and it cannot fail I think we can make it simpler:

```c
struct ibv_cq *rpma_cq_get_ibv_cq(struct rpma_cq *cq);
```
___
*[src/peer.c, line 103 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UA2gj-pNEGLIqv5HB:-M_UA2gj-pNEGLIqv5HC:bsla0nb) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/peer.c#L103)):*
> ```C
> 
> 	struct ibv_cq *ibv_cq = NULL;
> 	(void) rpma_cq_get_ibv_cq(cq, &ibv_cq);
> ```

To be simplified?

```c
struct ibv_cq *ibv_cq = rpma_cq_get_ibv_cq(cq, &ibv_cq);
```

Please see other comments.
___
*[src/include/librpma.h, line 2493 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UAJla71aX0uoXYZvE:-M_UAJla71aX0uoXYZvF:ba2sjwo) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/include/librpma.h#L2493)):*
> ```objc
> 
> /** 3
>  * rpma_conn_completion_wait - wait for a completion
> ```

Good catch. ;-)


<!-- Sent from Reviewable.io -->

2021-05-12 06:35 UTC, janekmi requested changes
> Reviewed 8 of 31 files at r2, 9 of 29 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 26 of 44 files reviewed, 10 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UE8TbAxWPxfeLMhUJ:-M_UE8TbAxWPxfeLMhUK:b-tbihaw) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/tests/unit/peer/CMakeLists.txt#L3)):*
> ```CMake
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020, Intel Corporation
> ```

.

Please verify you haven't missed adding Fujitsu copyrights.
___
*[tests/unit/peer/peer-create_qp.c, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UEXtyC61Sha3Xxm5e:-M_UEXtyC61Sha3Xxm5f:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/tests/unit/peer/peer-create_qp.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

.


<!-- Sent from Reviewable.io -->

2021-05-12 07:42 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 19 of 44 files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[src/conn_req.c, line 186 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_U8nXK-Qqgx_Nc-q7L:-M_UVpBoAUvCFF2VEtBU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/conn_req.c#L186)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can join both lines:

```c
int ret = rpma_cq_delete(&req->cq);
```
</blockquote></details>

Done.
___
*[src/conn_req.c, line 218 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_U8wnK8dbgHSnkOeYv:-M_UVqPxA-9TAGExcdaK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/conn_req.c#L218)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can join both lines:

```c
int ret = rpma_cq_delete(&req->cq);
```
</blockquote></details>

Done.
___
*[src/cq.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UCRMU9XBlTta_uzYl:-M_UW1D14r9qg-JgL6YB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.h#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/*
 * ERRORS
 * rpma_cq_get_fd() cannot fail.
 */
```
</blockquote></details>

Done.
___
*[src/cq.h, line 59 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UCYqyCBUiiuECK-ye:-M_UW1y312ipHl7LAXH4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.h#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/*
 * ERRORS
 * rpma_cq_get_ibv_cq() cannot fail.
 */
```
</blockquote></details>

Done.
___
*[src/cq.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UBOafA3J_EE50nqqv:-M_UW6io2d0pOU6S0Ov6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a comment here just in case something will happen between this PR and the future one e.g.:

> XXX This function does not follow the rpma_cq_get_ibv_cq() schema because it is planned to be made public in the near future so it will have to handle cq and fd validation on its own.
</blockquote></details>

Done.
___
*[src/cq.c, line 210 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UAvKf80d3_360B4aT:-M_UW8AnEqqxEmlWo-eZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.c#L210)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... the completion channel... ?
</blockquote></details>

Done.
___
*[src/cq.c, line 252 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_U9a9aBT-kLU8Erl58:-M_UWAuI-l8Tw4wIKe8Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/cq.c#L252)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since this getter is and will be internal and it cannot fail I think we can make it simpler:

```c
struct ibv_cq *rpma_cq_get_ibv_cq(struct rpma_cq *cq);
```
</blockquote></details>

Done.
___
*[src/peer.c, line 103 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UA2gj-pNEGLIqv5HB:-M_UWCdC1mhjp5irStza:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/src/peer.c#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To be simplified?

```c
struct ibv_cq *ibv_cq = rpma_cq_get_ibv_cq(cq, &ibv_cq);
```

Please see other comments.

</blockquote></details>

Done.
___
*[tests/unit/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UE8TbAxWPxfeLMhUJ:-M_UWGI3ClhLBpXucjUG:b-hvwasd) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/tests/unit/peer/CMakeLists.txt#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.

Please verify you haven't missed adding Fujitsu copyrights.
</blockquote></details>

Done.

Sorry, I have checked all changed files and added missing Fujitsu copyrights.
___
*[tests/unit/peer/peer-create_qp.c, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1035#-M_UEXtyC61Sha3Xxm5e:-M_UWGqZBhHFdb6OcjEk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d01040b92391fa440e6980ab81858c6bdccb5165/tests/unit/peer/peer-create_qp.c#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-13 13:40 UTC, janekmi reviewed
> Reviewed 1 of 31 files at r2, 1 of 29 files at r3, 10 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 31 of 44 files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-05-13 13:44 UTC, janekmi requested changes
> Reviewed 1 of 31 files at r2, 1 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 33 of 44 files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/common/mocks-rpma-cq.c, line 24 at r5](https://reviewable.io/reviews/pmem/rpma/1035#-M__xIiH3uh9TaY6tDy5:-M__xIiH3uh9TaY6tDy6:b-t3tcnd) ([raw file](https://github.com/pmem/rpma/blob/f1aca0d1f5509579c681872433dc0761613f0f96/tests/unit/common/mocks-rpma-cq.c#L24)):*
> ```C
> 	*fd = mock_type(int);
> 
> 	return 0;
> ```

```
XXX so far this function cannot fail. It will when it will become public.
```
___
*[tests/unit/common/mocks-rpma-cq.c, line 86 at r5](https://reviewable.io/reviews/pmem/rpma/1035#-M__xufKChXv7l_HuN74:-M__xufL8WVB6Y7G1OPH:b-hddhmg) ([raw file](https://github.com/pmem/rpma/blob/f1aca0d1f5509579c681872433dc0761613f0f96/tests/unit/common/mocks-rpma-cq.c#L86)):*
> ```C
> 	if (result == RPMA_E_PROVIDER)
> 		errno = mock_type(int);
> ```

The `*cq_ptr` final value is not verified?


<!-- Sent from Reviewable.io -->

2021-05-13 15:47 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 32 of 44 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/common/mocks-rpma-cq.c, line 24 at r5](https://reviewable.io/reviews/pmem/rpma/1035#-M__xIiH3uh9TaY6tDy5:-M_aNkHP6zm-gHhrZqwg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f1aca0d1f5509579c681872433dc0761613f0f96/tests/unit/common/mocks-rpma-cq.c#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
XXX so far this function cannot fail. It will when it will become public.
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-cq.c, line 86 at r5](https://reviewable.io/reviews/pmem/rpma/1035#-M__xufKChXv7l_HuN74:-M_aNvqpDd5o11oyZjK4:b-i6npsv) ([raw file](https://github.com/pmem/rpma/blob/f1aca0d1f5509579c681872433dc0761613f0f96/tests/unit/common/mocks-rpma-cq.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The `*cq_ptr` final value is not verified?
</blockquote></details>

Done.

Check *cp_ptr at the beginning and free it at the end. 


<!-- Sent from Reviewable.io -->

2021-05-13 23:40 UTC, janekmi requested changes
> Reviewed 1 of 31 files at r2, 7 of 29 files at r3, 3 of 14 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 20 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-completion_get.c, line 50 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzP6m-OWYB29MHexw:-M_bzP6m-OWYB29MHexx:b-ghsqfj) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L50)):*
> ```C
> /*
>  * completion_get__success - handling ibv_poll_cq() successfully
>  * with all possible values of opcode
> ```

`happy day scenario`
___
*[tests/unit/conn/conn-completion_get.c, line 50 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzRYm9Xfxhyyk1oug:-M_bzRYm9Xfxhyyk1ouh:b-fai7p9) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L50)):*
> ```C
> /*
>  * completion_get__success - handling ibv_poll_cq() successfully
>  * with all possible values of opcode
> ```

You are missing a negative error case when `rpma_cq_get()` will fail.
___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_bzeetCzmgMlokTH2h:b-ktkth8) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
> ```C
> 
> 	/* verify the results */
> 	assert_int_equal(ret, MOCK_OK);
> ```

`cmpl` is not verified.
___
*[tests/unit/conn/conn-completion_wait.c, line 37 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c-ykX7518f4EQmegm:-M_c-ykY6VlppA6EvOVz:b-vwroa2) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_wait.c#L37)):*
> ```C
> 
> 	/* configure mocks */
> 	will_return(rpma_cq_wait, MOCK_OK);
> ```

`rpma_cq_wait()` can fail. Missing test case. ;-)
___
*[tests/unit/conn/conn-get_completion_fd.c, line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c0aQp0qH_1Sufx1cW:-M_c0aQp0qH_1Sufx1cX:b-m4iihb) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-get_completion_fd.c#L54)):*
> ```C
> 
> 	/* configure mocks */
> 	will_return(rpma_cq_get_fd, MOCK_COMPLETION_FD);
> ```

`rpma_cq_get_fd()` can fail. Missing test case.
___
*[tests/unit/cq/cq-common.c, line 5 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c5J2s1Yk5WIMiyOPd:-M_c5J2s1Yk5WIMiyOPe:b-o5g5av) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-common.c#L5)):*
> ```C
> 
> /*
>  * cq-common.c -- the completion queue unit tests common functions
> ```

rpma_cq?
___
*[tests/unit/cq/cq-get.c, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c4-hHA4qmVRMR0EtG:-M_c4-hHA4qmVRMR0EtH:b2nhal1) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get.c#L7)):*
> ```C
>  * cq-get.c -- the rpma_cq_get() unit tests
>  *
>  * APIs covered:
> ```

API
___
*[tests/unit/cq/cq-get.c, line 211 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c5D3kDth0-5CRNEX7:-M_c5D3kDth0-5CRNEX8:b7r657z) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get.c#L211)):*
> ```C
> 
> 	return 0;
> }
> ```

Common?
___
*[tests/unit/cq/cq-get_fd.c, line 46 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c5TEqCj18GvO-HlgH:-M_c3l5W0itrXbEMHPhE:b7r657z) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get_fd.c#L46)):*
> ```C
> 
> 	return 0;
> }
> ```

Common?
___
*[tests/unit/cq/cq-get_ibv_cq.c, line 39 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3uoaCc3Wi5Dsu6pb:-M_c3uoaCc3Wi5Dsu6pc:b7r657z) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get_ibv_cq.c#L39)):*
> ```C
> 
> 	return 0;
> }
> ```

Common?
___
*[tests/unit/cq/cq-wait.c, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3793DR6X0bCE8QWo:-M_c3793DR6X0bCE8QWp:b2nhal1) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-wait.c#L7)):*
> ```C
>  * cq-wait.c -- the rpma_cq_wait() unit tests
>  *
>  * APIs covered:
> ```

API
___
*[tests/unit/cq/cq-wait.c, line 90 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3VHVAuGxkpLNX5zJ:-M_c3VHVAuGxkpLNX5zK:b-9yhicy) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-wait.c#L90)):*
> ```C
> 
> 	return 0;
> }
> ```

I have seen a similar function in another test. Maybe it can be moved to the common?
___
*[tests/unit/cq/cq-new_delete.c, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c39I7BRwLyuhXuNDf:-M_c39I7BRwLyuhXuNDg:bb6s27y) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L7)):*
> ```C
>  * cq-new_delete.c -- the rpma_cq_new/delete() unit tests
>  *
>  * API covered:
> ```

APIs
___
*[tests/unit/cq/cq-new_delete.c, line 52 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c1wgf97EyEe_k5lES:-M_c1wgf97EyEe_k5lET:bgzffxl) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L52)):*
> ```C
> 	expect_value(ibv_create_cq, cqe, MOCK_CQ_SIZE_DEFAULT);
> 	will_return(ibv_create_cq, NULL);
> 	will_return(ibv_create_cq, EAGAIN);
> ```

MOCK_ERRNO?
___
*[tests/unit/cq/cq-new_delete.c, line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c1WvLCCTS-D5jpCeS:-M_c1WvLCCTS-D5jpCeT:b-sfhfgv) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L53)):*
> ```C
> 	will_return(ibv_create_cq, NULL);
> 	will_return(ibv_create_cq, EAGAIN);
> 	will_return(ibv_destroy_comp_channel, MOCK_OK);
> ```

Error handling path can also fail. I think you also need test when:
- ibv_create_comp_channel - OK
- ibv_create_cq - EAGAIN
- ibv_destroy_comp_channel - EIO

Just in case.
___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_c2A3XAX2vRSfCak6M:blqp7vv) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
> ```C
> 
> 	/* verify the result */
> 	assert_int_equal(ret, RPMA_E_PROVIDER);
> ```

@grom72 @osalyk any of you remember why we have decided to not verify the errno value?
___
*[tests/unit/cq/cq-new_delete.c, line 76 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c1qTXDGgELdu4YMzu:-M_c1qTXDGgELdu4YMzv:b4u711l) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L76)):*
> ```C
> 	will_return(ibv_req_notify_cq_mock, MOCK_ERRNO);
> 	will_return(ibv_destroy_cq, MOCK_OK);
> 	will_return(ibv_destroy_comp_channel, MOCK_OK);
> ```

Error handling path can also fail. I think you also need test when:
- ibv_create_comp_channel - OK
- ibv_create_cq - OK
- ibv_req_notify_cq_mock - MOCK_ERRNO
- ibv_destroy_cq - EIO
- ibv_destroy_comp_channel - EIO

Just in case.
___
*[tests/unit/cq/cq-new_delete.c, line 100 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2c-H9rwCbOMpULJ4:-M_c2c-H9rwCbOMpULJ5:b-4qqa67) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L100)):*
> ```C
> 	will_return(__wrap__test_malloc, ENOMEM);
> 	will_return(ibv_destroy_cq, MOCK_OK);
> 	will_return(ibv_destroy_comp_channel, MOCK_OK);
> ```

Error handling path can also fail. I think you also need test when:
- ibv_create_comp_channel - OK
- ibv_create_cq - OK
- ibv_req_notify_cq_mock - OK
- malloc - ENOMEM
- ibv_destroy_cq - EIO
- ibv_destroy_comp_channel - EIO

Just in case.
___
*[tests/unit/cq/cq-new_delete.c, line 129 at r6](htt [...]

2021-05-14 02:05 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_cX9IcEu0zUPphPJE9:b-6vb7ba) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cmpl` is not verified.
</blockquote></details>

Verify some members of cmpl? (e.g. cmpl.op and cmpl.op_status)
___
*[tests/unit/conn/conn-get_completion_fd.c, line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c0aQp0qH_1Sufx1cW:-M_cY-uV225KbusAkPDI:b-ivecl0) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-get_completion_fd.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_cq_get_fd()` can fail. Missing test case.
</blockquote></details>

It seems that rpma_cq_get_fd() cannot fail.  Did I miss something?
___
*[tests/unit/cq/cq-wait.c, line 90 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3VHVAuGxkpLNX5zJ:-M_cYN1DDS349NDwQdFZ:b-ys7bu9) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-wait.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have seen a similar function in another test. Maybe it can be moved to the common?
</blockquote></details>

Their settings are a bit different , but we still can move it into common as you suggested.
___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_cYyn80YnoRTj3J3tZ:b-jn0id5) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@grom72 @osalyk any of you remember why we have decided to not verify the errno value?
</blockquote></details>

Do you mean that RPMA_E_PROVIDER should be removed?  I saw a lot of tests verify RPMA_E_PROVIDER .

Why do we have two kinds of errno (real errno:  EIO, EAGAIN and simulated errno: MOCK_ERRNO)?
I am confused about the usage of errno?  where to use real errno and where to use simulated errno?


<!-- Sent from Reviewable.io -->

2021-05-14 05:13 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 20 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_dHaEZ9CKAPDNJpQwx:bqhastn) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Do you mean that RPMA_E_PROVIDER should be removed?  I saw a lot of tests verify RPMA_E_PROVIDER .

Why do we have two kinds of errno (real errno:  EIO, EAGAIN and simulated errno: MOCK_ERRNO)?
I am confused about the usage of errno?  where to use real errno and where to use simulated errno?

</blockquote></details>

Is it so that the librpma API fully covers errno? I mean it is library's responsibility to convert errno to prepper RPMA_E_XXX return value.


<!-- Sent from Reviewable.io -->

2021-05-14 05:15 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 20 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_dI4b51Dxtk-WTsFdt:b2i6ilw) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it so that the librpma API fully covers errno? I mean it is library's responsibility to convert errno to prepper RPMA_E_XXX return value.
</blockquote></details>

Or in other words: we do not have control on providers and how they behave.


<!-- Sent from Reviewable.io -->

2021-05-14 06:00 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 20 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_dM6fJEns9ejZFCgS7:b-lh8fpc) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Or in other words: we do not have control on providers and how they behave.
</blockquote></details>

Hi @grom72 

Sorry, I think I misunderstood Janekmi's comment.  He means why we don't verify both return value and errno.
Currently, we just verify return value(e.g. RPMA_E_PROVIDER).

My question is why we use two kinds of errno?
Should we unify the usage of errno? for eample, remove simulated errno(MOCK_ERRNO) and use real errno(EIO, EAGAIN)?


<!-- Sent from Reviewable.io -->

2021-05-14 11:24 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 28 of 44 files reviewed, 20 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tests/unit/conn/conn-completion_get.c, line 50 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzP6m-OWYB29MHexw:-M_eYyps4F_VbX3Hi3vK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`happy day scenario`
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-completion_get.c, line 50 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzRYm9Xfxhyyk1oug:-M_eZ5T95CuuS6ay-jbJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing a negative error case when `rpma_cq_get()` will fail.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_eZ6rw472CxnRYUlCk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Verify some members of cmpl? (e.g. cmpl.op and cmpl.op_status)
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-completion_wait.c, line 37 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c-ykX7518f4EQmegm:-M_eZBcw9-NGObPMWACK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_wait.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_cq_wait()` can fail. Missing test case. ;-)
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-get_completion_fd.c, line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c0aQp0qH_1Sufx1cW:-M_eZMzT7tBa8r5bo0Nu:b-jb7nzy) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-get_completion_fd.c#L54)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It seems that rpma_cq_get_fd() cannot fail.  Did I miss something?
</blockquote></details>

waiting for your reply.
___
*[tests/unit/cq/cq-common.c, line 5 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c5J2s1Yk5WIMiyOPd:-M_eZOiO6s_1yRLDCvz1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-common.c#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_cq?
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get.c, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c4-hHA4qmVRMR0EtG:-M_eZPY94s3wSp61EdgB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get.c#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

API
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get.c, line 211 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c5D3kDth0-5CRNEX7:-M_eZQvXDbq9Ye9nUqfb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get.c#L211)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Common?
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get_fd.c, line 46 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c5TEqCj18GvO-HlgH:-M_eZS-wCAPvZSLEXuyD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get_fd.c#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Common?
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get_ibv_cq.c, line 39 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3uoaCc3Wi5Dsu6pb:-M_eZSuP6NR00t8eJWOg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-get_ibv_cq.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Common?
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-wait.c, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3793DR6X0bCE8QWo:-M_eafqo7ExCsXPhax7R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-wait.c#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

API
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-wait.c, line 90 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c3VHVAuGxkpLNX5zJ:-M_eahGW8OT-yZYz7th1:bv1xfi2) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-wait.c#L90)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Their settings are a bit different , but we still can move it into common as you suggested.
</blockquote></details>

I  factor out the common code and keep private code in respective files. For example
```
int group_setup_common_cq(void **unused)
{
	/* set the req_notify_cq callback in mock of IBV CQ */
	MOCK_VERBS->ops.req_notify_cq = ibv_req_notify_cq_mock;
	Ibv_cq.context = MOCK_VERBS;

	return 0;
}

static int
group_setup_get(void **unused)
{
	/* set the poll_cq callback in mock of IBV CQ */
	MOCK_VERBS->ops.poll_cq = poll_cq;

	return group_setup_common_cq(NULL);
}
``` 
___
*[tests/unit/cq/cq-new_delete.c, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c39I7BRwLyuhXuNDf:-M_eZTl1BhT3IFg6B2Av:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

APIs
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 52 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c1wgf97EyEe_k5lES:-M_eZUjl1IHuooH37L2n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MOCK_ERRNO?
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c1WvLCCTS-D5jpCeS:-M_eZgPaDRHInaxYlBop:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Error handling path can also fail. I think you also need test when:
- ibv_create_comp_channel - OK
- ibv_create_cq - EAGAIN
- ibv_destroy_comp_channel - EIO

Just in case.
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_eZnQU2H3eaNClw90r:b-z26pg4) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

Sorry, I think I misunderstood Janekmi's comment.  He means why we don't verify both return value and errno.
Currently, we just verify return value(e.g. RPMA_E_PROVIDER).

My question is why we use two kinds of errno?
Should we unify the usage of errno? for eample, remove simulated errno(MOCK_ERRNO) and use real errno(EIO, EAGAIN)?
</blockquote></details>

As Jan suggested, I add the unit tests for rpma_cq by the following rule for now:
1) MOCK_ERRNO [...]

2021-05-14 11:47 UTC, janekmi requested changes
> Reviewed 16 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/common/mocks-rpma-cq.c, line 54 at r7](https://reviewable.io/reviews/pmem/rpma/1035#-M_ef16wA8K6QGb4vUqZ:-M_ef16x6lc3fl_gZYC2:b-h9ee6h) ([raw file](https://github.com/pmem/rpma/blob/04a2b16bd3b03c5c2dd3ce90445e4f90364a4e98/tests/unit/common/mocks-rpma-cq.c#L54)):*
> ```C
> 	int result = mock_type(int);
> 	if (result == MOCK_OK)
> 		cmpl->op = RPMA_OP_SEND;
> ```

```c
memcpy(&cmpl, MOCK_COMPLETION, sizeof(struct rpma_completion));
```
___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_edIkW2pxXW0MJPRrC:bjr72pi) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can go more complete e.g.:

```c

static struct rpma_completion Completion = { /* any specific values */ };

#define MOCK_COMPLETION &Completion

assert_int_equal(memcmp(&cmpl, MOCK_COMPLETION, sizeof(struct rpma_completion));
```
___
*[tests/unit/conn/conn-completion_get.c, line 65 at r7](https://reviewable.io/reviews/pmem/rpma/1035#-M_eccs5193_npOVWM4O:-M_eccs5193_npOVWM4P:bgabnr3) ([raw file](https://github.com/pmem/rpma/blob/04a2b16bd3b03c5c2dd3ce90445e4f90364a4e98/tests/unit/conn/conn-completion_get.c#L65)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, RPMA_E_PROVIDER);
> 	assert_int_equal(cmpl.op, 0);
> ```

We do not declare any specific completion value on error. This step is unnecessary.
___
*[tests/unit/conn/conn-get_completion_fd.c, line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c0aQp0qH_1Sufx1cW:-M_egxvC3Kgq6m5AOxCy:b6x3p35) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-get_completion_fd.c#L54)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

waiting for your reply.
</blockquote></details>

Nope. My bad. Sorry.
___
*[tests/unit/cq/cq-new_delete.c, line 59 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_c2ObjEv-CWHPQbaEs:-M_efxALBr9Dm6vT8w0M:b-xh4vh7) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/cq/cq-new_delete.c#L59)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

As Jan suggested, I add the unit tests for rpma_cq by the following rule for now:
1) MOCK_ERRNO - the first error to happen in the test
2) EIO - the second and all proceeding errors in the test

Note: 
For other unit tests(e.g. rpma_conn and rpma_conn_req), I keep them because I will unify the usage of errno for all existing unit tests by the following rule after this PR is merged:
1) MOCK_ERRNO - the first error to happen in the test
2) MOCK_ERRNO2 - the second and all proceeding errors in the test
</blockquote></details>

@yangx-jy: :+1: 

@grom72: Got it.


<!-- Sent from Reviewable.io -->

2021-05-14 13:30 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 42 of 44 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/common/mocks-rpma-cq.c, line 54 at r7](https://reviewable.io/reviews/pmem/rpma/1035#-M_ef16wA8K6QGb4vUqZ:-M_f-hbs9StrLg1Uf7gx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/04a2b16bd3b03c5c2dd3ce90445e4f90364a4e98/tests/unit/common/mocks-rpma-cq.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
memcpy(&cmpl, MOCK_COMPLETION, sizeof(struct rpma_completion));
```
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_f3YONAUUM8pnI-p4Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can go more complete e.g.:

```c

static struct rpma_completion Completion = { /* any specific values */ };

#define MOCK_COMPLETION &Completion

assert_int_equal(memcmp(&cmpl, MOCK_COMPLETION, sizeof(struct rpma_completion));
```
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-completion_get.c, line 65 at r7](https://reviewable.io/reviews/pmem/rpma/1035#-M_eccs5193_npOVWM4O:-M_f-iyg9PBuplt1sFj7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/04a2b16bd3b03c5c2dd3ce90445e4f90364a4e98/tests/unit/conn/conn-completion_get.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We do not declare any specific completion value on error. This step is unnecessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-15 16:19 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_koaGD4XWDl0AAVzgG:b-f3lzra) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You don't think it will be easier to just have `struct rpma_completion Completion` and `MOCK_COMPLETION` defined in the `mocks-rpma-cq.h` header? And have here just `memcmp()` instead of all of these?


<!-- Sent from Reviewable.io -->

2021-05-16 15:58 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 36 of 44 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/conn/conn-completion_get.c, line 64 at r6](https://reviewable.io/reviews/pmem/rpma/1035#-M_bzeetCzmgMlokTH2g:-M_pnP3r0hRtNqH75mOd:b2dcsyt) ([raw file](https://github.com/pmem/rpma/blob/d89af13dcae473d5d25480fee88662bd31da0a99/tests/unit/conn/conn-completion_get.c#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You don't think it will be easier to just have `struct rpma_completion Completion` and `MOCK_COMPLETION` defined in the `mocks-rpma-cq.h` header? And have here just `memcmp()` instead of all of these?
</blockquote></details>

Done.

Ah, it is actually easier.  sorry, I changed the code roughly.


<!-- Sent from Reviewable.io -->

2021-05-17 01:35 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 36 of 44 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1035#-M_ru8lKBU0qcItwiUzZ:-M_ru8lKBU0qcItwiUz_:bap0mf6) (no related file):*
Hi,

Circleci always failed when installing packages yesterday. (Perhaps, GPG error is caused by the obsolete public key.)

Best Regards,
Xiao Yang

---


<!-- Sent from Reviewable.io -->

2021-05-18 23:29 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 8 files at r9, 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035#-:-Ma0o-579AfVb-Kfm8OM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-05-19 07:38 UTC, grom72 reviewed
> Reviewed 2 of 6 files at r1, 6 of 31 files at r2, 3 of 29 files at r3, 1 of 3 files at r4, 3 of 14 files at r5, 8 of 16 files at r7, 7 of 8 files at r9, 5 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

___
*[src/cq.h, line 42 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2UhvU9p6VL84wM9Ro:-Ma2UhvV1OfBJ7cQzrzV:b-vqsw9i) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.h#L42)):*
> ```
> rpma_cq_get
> ```
rpma_cq_get_cmpl
___
*[src/cq.c, line 48 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2NUIT7Qc-BOutfkZY:-Ma2NUIT7Qc-BOutfkZZ:b-5ph7hw) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.c#L48)):*
> ```
> wait for a completion from the rpma_cq object
> ```
 wait for completion from the rpma_cq object and ack completion event
___
*[src/cq.c, line 163 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2OkBw977EyCaDxhxc:-Ma2OkBw977EyCaDxhxd:bwtdc9s) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.c#L163)):*
> ```
> verbs
> ```
dev
___
*[tests/unit/cq/cq-new_delete.c, line 125 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2XdQJ2dEXL3hBTqqI:-Ma2XdQJ2dEXL3hBTqqJ:bbnnxpp) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/tests/unit/cq/cq-new_delete.c#L125)):*
> ```
> EIO
> ```
The same value not should be used in both cases
```EIO_2```


<!-- Sent from Reviewable.io -->

2021-05-19 07:39 UTC, grom72 reviewed
> Reviewed 1 of 8 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-05-19 07:48 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[src/cq.h, line 42 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2UhvU9p6VL84wM9Ro:-Ma2_7JN7nGKP5hXFAtR:b-xnrw0w) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.h#L42)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_cq_get
> ```
rpma_cq_get_cmpl
</blockquote></details>

I don't think it is a good idea to introduce a new abbreviation. I am voting for `rpma_cq_get_completion()`.
___
*[tests/unit/cq/cq-new_delete.c, line 125 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2XdQJ2dEXL3hBTqqI:-Ma2_RbT5UUJGLZkuwgk:bgidm57) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/tests/unit/cq/cq-new_delete.c#L125)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> EIO
> ```
The same value not should be used in both cases
```EIO_2```
</blockquote></details>

Negative. It is ok. It is not important which API call will fail with any specific error code. The only important differentiation is between the first and any other consecutive API call.


<!-- Sent from Reviewable.io -->

2021-05-19 07:52 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/cq.h, line 42 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2UhvU9p6VL84wM9Ro:-Ma2b2P6C5LFgegTgBzE:b-kpmoq) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.h#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't think it is a good idea to introduce a new abbreviation. I am voting for `rpma_cq_get_completion()`.
</blockquote></details>

yes ```rpma_cq_get_completion()``` is OK


<!-- Sent from Reviewable.io -->

2021-05-19 08:57 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 37 of 44 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/cq.h, line 42 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2UhvU9p6VL84wM9Ro:-Ma2lxQUCmslIivBmA8r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.h#L42)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes ```rpma_cq_get_completion()``` is OK
</blockquote></details>

Done.
___
*[src/cq.c, line 48 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2NUIT7Qc-BOutfkZY:-Ma2ly3sD2LmZRg5S1Pn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.c#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> wait for a completion from the rpma_cq object
> ```
 wait for completion from the rpma_cq object and ack completion event
</blockquote></details>

Done.
___
*[src/cq.c, line 163 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2OkBw977EyCaDxhxc:-Ma2lyXa7MTDA6oPHc07:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/src/cq.c#L163)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> verbs
> ```
dev
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 125 at r10](https://reviewable.io/reviews/pmem/rpma/1035#-Ma2XdQJ2dEXL3hBTqqI:-Ma2c6kyERb4GnD2zzVg:bbmyd8s) ([raw file](https://github.com/pmem/rpma/blob/83505ca2c089b0983d62c27525dd07b57a56a682/tests/unit/cq/cq-new_delete.c#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Negative. It is ok. It is not important which API call will fail with any specific error code. The only important differentiation is between the first and any other consecutive API call.
</blockquote></details>

Yes.  It is not important so I keep it.

BTW:  EIO will be replaced by MOCK_ERRNO2 in future.


<!-- Sent from Reviewable.io -->

2021-05-19 11:38 UTC, janekmi approved these changes
> Reviewed 7 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-05-24 04:47 UTC, grom72 reviewed
> Reviewed 1 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-05-25 03:49 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 43 of 44 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tests/unit/conn/conn-new.c, line 290 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-MaWcWyy5G_NhhC36m-A:-MaWcWyy5G_NhhC36m-B:b-d0he22) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/conn/conn-new.c#L290)):*
> ```C
> 
> /*
>  * delete__cq_delete_EAGAIN - rpma_cq_delete() fails with EAGAIN
> ```

Only fix a typo here(delete__cq_detele_cq_EAGAIN => delete__cq_detele_EAGAIN).


<!-- Sent from Reviewable.io -->

2021-05-25 04:34 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 43 of 44 files reviewed, all discussions resolved (waiting on @grom72 and @janekmi)

___
*[tests/unit/conn/conn-new.c, line 290 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-MaWcWyy5G_NhhC36m-A:-MaWmtQF88SL8GKq76pq:b-iyyatm) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/conn/conn-new.c#L290)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Only fix a typo here(delete__cq_detele_cq_EAGAIN => delete__cq_detele_EAGAIN).
</blockquote></details>

Sorry, delete__cq_delete_cq_EAGAIN => delete__cq_delete_EAGAIN.


<!-- Sent from Reviewable.io -->

2021-05-26 21:19 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-05-28 09:28 UTC, janekmi commented
@ldorau

2021-05-31 14:25 UTC, ldorau reviewed
> Reviewed 2 of 6 files at r1, 1 of 3 files at r4, 1 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-06-01 09:33 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1035#-Mb5ufvf1pJgszy0GdQ9:-Mb5ufvf1pJgszy0GdQA:b-xx4jz9) (no related file):*
Hi @yangx-jy , could you check why some of tests fail on CentOS?:
https://github.com/ldorau/rpma/actions/runs/893153236

---


<!-- Sent from Reviewable.io -->

2021-06-01 10:48 UTC, ldorau requested changes
> Reviewed 1 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[src/cq.c, line 138 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6A7FPA-NjpifnLvrv:-Mb6A7FPA-NjpifnLvrw:b-hhvnzh) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/src/cq.c#L138)):*
> ```
> can only be placed in ...
> ```

can be placed only in ...
___
*[src/cq.c, line 253 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6AzU47A3No0DFc_Il:-Mb6AzU47A3No0DFc_Im:bvqdcw3) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/src/cq.c#L253)):*
> ```C
>  */
> struct ibv_cq *
> rpma_cq_get_ibv_cq(const struct rpma_cq *cq)
> ```

Please move it next to `rpma_cq_get_fd()`


<!-- Sent from Reviewable.io -->

2021-06-01 10:57 UTC, ldorau reviewed
> Reviewed 4 of 31 files at r2, 1 of 29 files at r3, 1 of 14 files at r5, 1 of 5 files at r10, 1 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-06-01 12:07 UTC, ldorau requested changes
> Reviewed 3 of 31 files at r2, 1 of 14 files at r5, 1 of 16 files at r7, 6 of 8 files at r9, 1 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/common/mocks-rpma-cq.c, line 26 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6SPAeDK8T27Ct6l4X:-Mb6SPAf03ndH3FFALZI:b-s9qpci) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/common/mocks-rpma-cq.c#L26)):*
> ```
>  It will fail when it will become public.
> ```

I hope it will not ;-) :-D

I believe you meant: 

"` It will be able to fail when it becomes public.`"


<!-- Sent from Reviewable.io -->

2021-06-01 13:07 UTC, ldorau requested changes
> Reviewed 2 of 29 files at r3, 3 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/cq/cq-new_delete.c, line 275 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6b95g3g6Vbbb_7sDk:-Mb6b95hEqsM71wIP5Wu:b3s6k55) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/cq/cq-new_delete.c#L275)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
> 	/* rpma_cq_delete() unit tests */
> 	cmocka_unit_test_setup_teardown(delete__destroy_cq_ERRNO,
> 		setup__cq_new, NULL),
> 	cmocka_unit_test_setup_teardown(
> 		delete__destroy_cq_ERRNO_subsequent_EIO,
> 		setup__cq_new, NULL),
> 	cmocka_unit_test_setup_teardown(delete__destroy_comp_channel_ERRNO,
> 		setup__cq_new, NULL),
> ```
</details>


Those three tests can segfault:

```
[ RUN      ] delete__destroy_cq_ERRNO
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] delete__destroy_cq_ERRNO
[ RUN      ] delete__destroy_cq_ERRNO_subsequent_EIO
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] delete__destroy_cq_ERRNO_subsequent_EIO
[ RUN      ] delete__destroy_comp_channel_ERRNO
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] delete__destroy_comp_channel_ERRNO
```

because of the following issue in the cmocka framework:
https://gitlab.com/cmocka/cmocka/-/issues/47

`setup__cq_new()` allocates memory which can be freed only in the teardown step, but it is freed in the test now, what is wrong.

Unit tests of `rpma_cq_delete()` should be moved to the teardown step to fix it.

Probably that is why builds on CentOS fail.


<!-- Sent from Reviewable.io -->

2021-06-01 13:10 UTC, ldorau reviewed
> Reviewed 1 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-06-01 16:13 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: 40 of 44 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1035#-Mb5ufvf1pJgszy0GdQ9:-Mb7LC3uCzzR9URmQcrE:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Hi @yangx-jy , could you check why some of tests fail on CentOS?:
https://github.com/ldorau/rpma/actions/runs/893153236
</blockquote></details>

Done.

---
___
*[src/cq.c, line 138 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6A7FPA-NjpifnLvrv:-Mb7J_en2hY5iNRjyV_d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/src/cq.c#L138)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> can only be placed in ...
> ```

can be placed only in ...
</blockquote></details>

Done.
___
*[src/cq.c, line 253 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6AzU47A3No0DFc_Il:-Mb7JdGKBojxKHR3uKFK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/src/cq.c#L253)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move it next to `rpma_cq_get_fd()`
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-cq.c, line 26 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6SPAeDK8T27Ct6l4X:-Mb7Je2Z84qp1HcAtKW2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/common/mocks-rpma-cq.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  It will fail when it will become public.
> ```

I hope it will not ;-) :-D

I believe you meant: 

"` It will be able to fail when it becomes public.`"

</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 275 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6b95g3g6Vbbb_7sDk:-Mb7JgXbEvUmhyC0g2fj:bqg6jmy) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/cq/cq-new_delete.c#L275)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* rpma_cq_delete() unit tests */
> 	cmocka_unit_test_setup_teardown(delete__destroy_cq_ERRNO,
> 		setup__cq_new, NULL),
> 	cmocka_unit_test_setup_teardown(
> 		delete__destroy_cq_ERRNO_subsequent_EIO,
> 		setup__cq_new, NULL),
> 	cmocka_unit_test_setup_teardown(delete__destroy_comp_channel_ERRNO,
> 		setup__cq_new, NULL),
> ```

Those three tests can segfault:

```
[ RUN      ] delete__destroy_cq_ERRNO
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] delete__destroy_cq_ERRNO
[ RUN      ] delete__destroy_cq_ERRNO_subsequent_EIO
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] delete__destroy_cq_ERRNO_subsequent_EIO
[ RUN      ] delete__destroy_comp_channel_ERRNO
[  ERROR   ] --- Test failed with exception: Segmentation fault(11)
[  FAILED  ] delete__destroy_comp_channel_ERRNO
```

because of the following issue in the cmocka framework:
https://gitlab.com/cmocka/cmocka/-/issues/47

`setup__cq_new()` allocates memory which can be freed only in the teardown step, but it is freed in the test now, what is wrong.

Unit tests of `rpma_cq_delete()` should be moved to the teardown step to fix it.

Probably that is why builds on CentOS fail.

</blockquote></details>

I recall that conn_req-delete.c has mentioned issue #47 so I call setup__cq_new() in tests as conn_req-delete.c does.

Could you confirm if my change can fix the failure? Thanks a lot.


<!-- Sent from Reviewable.io -->

2021-06-01 19:50 UTC, ldorau approved these changes
> Reviewed 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

___
*[tests/unit/cq/cq-new_delete.c, line 275 at r12](https://reviewable.io/reviews/pmem/rpma/1035#-Mb6b95g3g6Vbbb_7sDk:-Mb86OJb1dzSaMiJMUp_:bmfq2bg) ([raw file](https://github.com/pmem/rpma/blob/f1312009ee93a4abf0667fdd1853663d8a5b756d/tests/unit/cq/cq-new_delete.c#L275)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I recall that conn_req-delete.c has mentioned issue #47 so I call setup__cq_new() in tests as conn_req-delete.c does.

Could you confirm if my change can fix the failure? Thanks a lot.
</blockquote></details>

Yes, exactly! :-) That is the right fix :-) It was my mistake.


<!-- Sent from Reviewable.io -->

2021-06-01 19:51 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 29 files at r3, 11 of 16 files at r7, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1035#-:-Mb87JX34y7uf_V23SdE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-06-01 19:52 UTC, merged