test: add the rpma_conn_get_private_data MT test
pmem/rpma pull request #1037
Opened 2021-04-29 09:58 UTC by ldorau

Requires:
- [ ] #1036

2021-04-29 17:37 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZTZiFW01yNpFnR-AXO:-MZTZiFW01yNpFnR-AXP:b-fj3feh) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L52)):*
> ```C
> 
> 	/* establish a new connection to a server listening at addr:port */
> 	ret = client_connect(pr->peer, pr->addr, MTT_PORT_STR, NULL, &pr->conn);
> ```

I have a very bad feeling about reusing the parts from the examples.
If I will ask you to break this dependency, how will you respond?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZTYoXpCKCOeceItA3q:-MZTYoXqCAVlp8UMhU-r:b-isrgln) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L86)):*
> ```C
> 
> 	/* receive a memory info from the server */
> 	int ret = rpma_conn_get_private_data(pr->conn, &st->pdata);
> ```

This test to really test MT access to the private should use the same connection for all threads. Otherwise, it tests only if the implementation does not use some kind of static/global which will be used for processing the requests coming from all threads.

It is not incorrect, but it is a weaker type of thread safety if we have to say the API call is thread-safe but the connection has to be different for every thread.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZT_DTA3Bp86qEMUhKC:-MZT_DTA3Bp86qEMUhKD:bqxaeab) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L153)):*
> ```C
> {
> 	struct server_prestate *pst = prestate;
> 	return server_main(pst->argc, pst->argv);
> ```

This freaks me out. How do you feel about providing a handy implementation but MT-testing-dedicated?
Maybe this implementation simply lacks elasticity. I can imagine different API calls may require the other side to do something differently, in this case, we could e.g. agree to provide a function pointer `sever_do_before_connect()` and `server_do_after_connect()`. We can not do this now.  Having this test is intended to be a role model it may be proved not useful pretty quickly. E.g. what if the test-initiator-side will need the test-helper-side posting a RECV before accepting a connection? Should the developer pick the right example to connect with?


<!-- Sent from Reviewable.io -->

2021-04-29 19:21 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZU3poD9Vg2nTmJVwPp:-MZU3poD9Vg2nTmJVwPq:b-fzx3yt) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L66)):*
> ```C
> 		struct mtt_result *tr)
> {
> 	struct state *st = (struct state *)calloc(1, sizeof(struct state));
> ```

This state seems to serve no purpose.
You can obtain the private data in the `prestate_init()` step and compare the value you got during the `thread()` step to the expected value.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZTYoXpCKCOeceItA3q:-MZU3lzMDK_KQgDybfXT:bg0tm9k) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This test to really test MT access to the private should use the same connection for all threads. Otherwise, it tests only if the implementation does not use some kind of static/global which will be used for processing the requests coming from all threads.

It is not incorrect, but it is a weaker type of thread safety if we have to say the API call is thread-safe but the connection has to be different for every thread.
</blockquote></details>

My bad.


<!-- Sent from Reviewable.io -->

2021-04-30 09:08 UTC, janekmi requested changes
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: all files reviewed, 13 unresolved discussions (waiting on @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 222 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZWzdoqAeniJXFZk5dE:-MZWzdoqAeniJXFZk5dF:b-l2suri) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/cmake/ctest_helpers.cmake#L222)):*
> ```CMake
> 
> function(add_multithreaded)
> 	set(options USE_LIBIBVERBS USE_EXAMPLES)
> ```

`XXX required only as a proof of concept please do not use examples for any other future tests`?
___
*[tests/cmake/ctest_helpers.cmake, line 248 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-4G9-LkOdZOkm8Ne:-MZX-4G9-LkOdZOkm8Nf:b-7ylqbj) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/cmake/ctest_helpers.cmake#L248)):*
> ```CMake
> 	endif()
> 
> 	if(MULTITHREADED_USE_EXAMPLES)
> ```

XXX .
___
*[tests/multithreaded/common/mtt.h, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZWyygl46FXzEdl9qX4:-MZWyygl46FXzEdl9qX5:ba0so8b) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/common/mtt.h#L73)):*
> ```objc
> 			mtt_base_file_name(__FILE__), __LINE__, __func__, \
> 			msg); \
> 	} while (0)
> ```

Please put it before MTT_ERR. Because it is of more general use.

In the future PR I will rename these macros as follow:
- MTT_ERR -> MTT_ERR_FUNC
- MTT_RPMA_ERR -> MTT_ERR_RPMA
___
*[tests/multithreaded/conn/CMakeLists.txt, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-8FICB6IdDmGBH8u:-MZX-8FICB6IdDmGBH8v:b-7ylqbj) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/CMakeLists.txt#L13)):*
> ```CMake
> add_multithreaded(NAME conn BIN rpma_conn_get_private_data
> 	SRCS rpma_conn_get_private_data.c
> 		${CMAKE_SOURCE_DIR}/examples/02-read-to-volatile/server.c
> ```

XXX .
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZTZiFW01yNpFnR-AXO:-MZX-QPxBkHpfcyLSA1R:bkm2cf4) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have a very bad feeling about reusing the parts from the examples.
If I will ask you to break this dependency, how will you respond?
</blockquote></details>

XXX . ?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-TEP4fyI8vQOmI-l:-MZX-TEP4fyI8vQOmI-m:b-fv3rsb) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L54)):*
> ```C
> 	ret = client_connect(pr->peer, pr->addr, MTT_PORT_STR, NULL, &pr->conn);
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "client_connect", ret);
> ```

FYI: Yeah. This is also a part of the problem with reusing the examples' source code.
Error handling, in this case, will be messed up. We will straight these things up in the future PRs. ;-)
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-lsQ2m300uCEDqFi:-MZX-lsQ2m300uCEDqFj:b-ja4g74) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L54)):*
> ```C
> 	ret = client_connect(pr->peer, pr->addr, MTT_PORT_STR, NULL, &pr->conn);
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "client_connect", ret);
> ```

ret is a librpma error code?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 99 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX07RbAAfKK6qrmXHx:-MZX07RbAAfKK6qrmXHy:bev6sj1) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L99)):*
> ```C
> 	/* read the received private data */
> 	struct common_data *dst_data = st->pdata.ptr;
> 	memcpy(&st->dst_data, dst_data, sizeof(st->dst_data));
> ```

What for?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0EIqCtF_G7CXqDCN:-MZX0EIqCtF_G7CXqDCO:bnwaz97) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L103)):*
> ```C
> 
> /*
>  * fini -- shutdown the endpoint and free the state
> ```

No shooting here.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 124 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0Nr_0GNyZHjVLD-m:-MZX0Nr_0GNyZHjVLD-n:bkdv8ru) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L124)):*
> ```C
> 	int ret;
> 
> 	if (pr->conn &&
> ```

Is the `prestate_fini()` step called when the `prestate_init()` failed?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0VQI9AtwfcLOaVjv:-MZX0VQI9AtwfcLOaVjw:b-ja4g74) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L127)):*
> ```C
> 	    (ret = common_disconnect_and_wait_for_conn_close(&pr->conn)))
> 		MTT_RPMA_ERR(tr, "common_disconnect_and_wait_for_conn_close",
> 				ret);
> ```

ret is a librpma error code?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 129 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0Z_xEXnmIe-dFxyo:-MZX0Z_xEXnmIe-dFxyp:bkdv8ru) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L129)):*
> ```C
> 				ret);
> 
> 	if (pr->peer && (ret = rpma_peer_delete(&pr->peer)))
> ```

Is the `prestate_fini()` step called when the `prestate_init()` failed?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 133 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0dOb8BCoLYrPe6ls:-MZX0dOb8BCoLYrPe6lt:b3v6sb2) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L133)):*
> ```C
> }
> 
> /* the server part */
> ```

I think you can add `/* the client part */` at the beginning to indicate there are more parts down the road.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 146 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0tZF4xDvZ5A0FGFP:-MZX0tZF4xDvZ5A0FGFQ:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L146)):*
> ```C
>  * XXX Temporarily and for the simplicity sake
>  * the server is taken directly
>  * from the 02-read-to-volatile example.
> ```

:+1: 
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 168 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX14ykC0i7uYO9h0m8:-MZX14ykC0i7uYO9h0m9:b-gh3l53) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L168)):*
> ```C
> 		return -1;
> 
> 	/* skip the 1st argument (<threads_num>) */
> ```

Clever. ;-)


<!-- Sent from Reviewable.io -->

2021-04-30 12:25 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: 1 of 6 files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[tests/cmake/ctest_helpers.cmake, line 222 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZWzdoqAeniJXFZk5dE:-MZXbeNW5anZrypuoYXm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/cmake/ctest_helpers.cmake#L222)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`XXX required only as a proof of concept please do not use examples for any other future tests`?
</blockquote></details>

Done.
___
*[tests/cmake/ctest_helpers.cmake, line 248 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-4G9-LkOdZOkm8Ne:-MZXbf3D6YcOQnGQLEcz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

XXX .
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZWyygl46FXzEdl9qX4:-MZXbg1mAG51GhCONmLC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/common/mtt.h#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please put it before MTT_ERR. Because it is of more general use.

In the future PR I will rename these macros as follow:
- MTT_ERR -> MTT_ERR_FUNC
- MTT_RPMA_ERR -> MTT_ERR_RPMA
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/CMakeLists.txt, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-8FICB6IdDmGBH8u:-MZXbwz17zHt1MyY43ok:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/CMakeLists.txt#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

XXX .
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZTZiFW01yNpFnR-AXO:-MZXjMMH1vkhMwxcmo5Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

XXX . ?
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZU3poD9Vg2nTmJVwPp:-MZXhFhRDghijSC1iwIt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This state seems to serve no purpose.
You can obtain the private data in the `prestate_init()` step and compare the value you got during the `thread()` step to the expected value.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1037#-MZT_DTA3Bp86qEMUhKC:-MZWw070ADLYiD2HpOjj:bo6lz9q) ([raw file](https://github.com/pmem/rpma/blob/b17135d139993e436b911431af19c1b2951ece5f/tests/multithreaded/conn/rpma_conn_get_private_data.c#L153)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This freaks me out. How do you feel about providing a handy implementation but MT-testing-dedicated?
Maybe this implementation simply lacks elasticity. I can imagine different API calls may require the other side to do something differently, in this case, we could e.g. agree to provide a function pointer `sever_do_before_connect()` and `server_do_after_connect()`. We can not do this now.  Having this test is intended to be a role model it may be proved not useful pretty quickly. E.g. what if the test-initiator-side will need the test-helper-side posting a RECV before accepting a connection? Should the developer pick the right example to connect with?
</blockquote></details>

I will change that in a separate PR.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX-lsQ2m300uCEDqFi:-MZXhEqg8F-yCn4JzFog:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ret is a librpma error code?
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 99 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX07RbAAfKK6qrmXHx:-MZXhOAh2fePR7b_WHgv:b-scs783) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What for?
</blockquote></details>

In order to verify it later.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0EIqCtF_G7CXqDCN:-MZXhP2Z6McWCAdDiKlG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No shooting here.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 124 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0Nr_0GNyZHjVLD-m:-MZXi4O66S7OmZuRA7b1:b32w12) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is the `prestate_fini()` step called when the `prestate_init()` failed?
</blockquote></details>

No
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0VQI9AtwfcLOaVjv:-MZXi7NF8WtWxMcbnw3b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ret is a librpma error code?
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 129 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0Z_xEXnmIe-dFxyo:-MZXi9IO7spsGCCRXeVG:b32w12) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L129)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is the `prestate_fini()` step called when the `prestate_init()` failed?
</blockquote></details>

No
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 133 at r2](https://reviewable.io/reviews/pmem/rpma/1037#-MZX0dOb8BCoLYrPe6ls:-MZXiCrJEffViHL8j51F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51d32d737d14b35cd73cc92973d3418aaa2ca8a3/tests/multithreaded/conn/rpma_conn_get_private_data.c#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you can add `/* the client part */` at the beginning to indicate there are more parts down the road.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-30 12:56 UTC, janekmi requested changes
> Reviewed 4 of 5 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXou-o6hQ7gIA9lU7i:-MZXou-o6hQ7gIA9lU7j:b-yn53e0) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L21)):*
> ```C
> 	struct rpma_peer *peer;
> 	struct rpma_conn *conn;
> 	struct common_data dst_data;
> ```

`void *pdata_exp` stands for the expected private data value.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 79 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXnq-b1DPCElCM-4yY:-MZXnq-b1DPCElCM-4yZ:b5cmuac) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L79)):*
> ```C
> 	}
> 
> 	struct rpma_conn_private_data pdata;
> ```

Take it to the beginning of the function.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 81 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXnzrO1XnsBsYgEVjv:-MZXnzrO1XnsBsYgEVjw:b-t2m45o) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L81)):*
> ```C
> 	struct rpma_conn_private_data pdata;
> 
> 	/* receive a memory info from the server */
> ```

For the sake of this test, it is irrelevant what is the content of the private data.

`get a connection private data`
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 85 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXofAC4orVBICYCwCN:-MZXofAC4orVBICYCwCO:b43fojh) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L85)):*
> ```C
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "rpma_conn_get_private_data", ret);
> 		return;
> ```

Cleanup is missing.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 90 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXogn58BZOEXyi8yKh:-MZXogn58BZOEXyi8yKi:b43fojh) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L90)):*
> ```C
> 			"The server has not provided the connection's private data",
> 			-1);
> 		return;
> ```

Cleanup is missing.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 98 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXoktb08tCMh5IOesf:-MZXoktb08tCMh5IOesg:bblovb1) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L98)):*
> ```C
> 	 */
> 	struct common_data *dst_data = pdata.ptr;
> 	memcpy(&pr->dst_data, dst_data, sizeof(pr->dst_data));
> ```

`pdata.len`. `struct common_data` is not needed.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 147 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXphFpBkxpHEqID3C3:-MZXphFpBkxpHEqID3C4:b-iggvyx) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L147)):*
> ```C
> 
> 	if ((ret = rpma_conn_disconnect(pr->conn)))
> 		MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
> ```

rpma_conn_disconnect
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 149 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXpnGyEFz2e7NJYCEW:-MZXpnGyEFz2e7NJYCEX:b-7r316n) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L149)):*
> ```C
> 		MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
> 
> 	if (ret == 0) {
> ```

else?
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 150 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXpui89a6Lv14DI4i8:-MZXpui89a6Lv14DI4i9:b-pmfcsv) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L150)):*
> ```C
> 
> 	if (ret == 0) {
> 		enum rpma_conn_event conn_event = RPMA_CONN_UNDEFINED;
> ```

Put this at the beginning of the function.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 157 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXq7F92spJ0VWew-fZ:-MZXq3p89w1pULFehVSW:b-tzx26z) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L157)):*
> ```C
> 			MTT_ERR_MSG(tr,
> 				"rpma_conn_next_event returned an unexpected event",
> 				-1);
> ```

In case `rpma_conn_next_event()` will fail we won't get any message.


<!-- Sent from Reviewable.io -->

2021-04-30 20:07 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXou-o6hQ7gIA9lU7i:-MZZKL_m7ciPsrG4Di3q:bqz43oj) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`void *pdata_exp` stands for the expected private data value.
</blockquote></details>

The length has to be saved too. Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 79 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXnq-b1DPCElCM-4yY:-MZZKWAr-NzmodGfjW8d:ba3dfob) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Take it to the beginning of the function.
</blockquote></details>

Removed
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 81 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXnzrO1XnsBsYgEVjv:-MZZKk6QDE8S-Vn-J2Ur:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For the sake of this test, it is irrelevant what is the content of the private data.

`get a connection private data`
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 85 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXofAC4orVBICYCwCN:-MZZKwr34JLyFufKun5K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Cleanup is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 90 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXogn58BZOEXyi8yKh:-MZZKxJJ0-56okzPCbB4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Cleanup is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 98 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXoktb08tCMh5IOesf:-MZZL3E04u45lwth04b-:b6env6l) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`pdata.len`. `struct common_data` is not needed.
</blockquote></details>

Copying is also not needed. Removed.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 147 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXphFpBkxpHEqID3C3:-MZZLIG1-eIT1iNmnIPL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L147)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_conn_disconnect
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 149 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXpnGyEFz2e7NJYCEW:-MZZLTqu99dO-go8CA7Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L149)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

else?
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 150 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXpui89a6Lv14DI4i8:-MZZLYGJ2XeBZXdjf14A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Put this at the beginning of the function.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 157 at r4](https://reviewable.io/reviews/pmem/rpma/1037#-MZXq7F92spJ0VWew-fZ:-MZZNWzlCbKF0wW0kueZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/792e0116eccc98fdd989c66311b50576eca47f52/tests/multithreaded/conn/rpma_conn_get_private_data.c#L157)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In case `rpma_conn_next_event()` will fail we won't get any message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-30 22:44 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 22 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZvX8N1bwLgsjpIyAV:-MZZvX8N1bwLgsjpIyAW:birhvc2) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L22)):*
> ```C
> 	struct rpma_conn *conn;
> 
> 	/* expected value of the private data */
> ```

the expected...
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 112 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZw3ka1atbrrph3l2b:-MZZw3ka1atbrrph3l2c:b-tcpv8x) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L112)):*
> ```C
> 	struct rpma_conn_private_data pdata;
> 
> 	/* receive a memory info from the server */
> ```

get a connection's private data
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 124 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZwImh6wjJrVZPUkn2:-MZZwImh6wjJrVZPUkn3:b-4qz7pi) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L124)):*
> ```C
> 	}
> 
> 	/* verify a length of the received private data */
> ```

the length
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 126 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZwS5N7OlF_EcCEuGF:-MZZwS5N7OlF_EcCEuGG:b7icxfb) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L126)):*
> ```C
> 	/* verify a length of the received private data */
> 	if (pdata.len != pr->pdata_exp.len)
> 		MTT_ERR_MSG(result, "Wrong length of the private data", -1);
> ```

The `return` is missing. Otherwise, you will overwrite the error message. No point to continue.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 128 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZwd3dAdsBpgpIq4lj:-MZZwd3dAdsBpgpIq4lk:b9j88th) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L128)):*
> ```C
> 		MTT_ERR_MSG(result, "Wrong length of the private data", -1);
> 
> 	/* verify a content of the received private data */
> ```

the content


<!-- Sent from Reviewable.io -->

2021-05-03 20:03 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 22 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZvX8N1bwLgsjpIyAV:-MZnoTtw5ZxWf1ec8e0j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the expected...
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 112 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZw3ka1atbrrph3l2b:-MZnodeJAyuL5joxSPPI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get a connection's private data
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 124 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZwImh6wjJrVZPUkn2:-MZnoiOE6YKyDX88ppu0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the length
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 126 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZwS5N7OlF_EcCEuGF:-MZnorzJ2hmCklc2hsf7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The `return` is missing. Otherwise, you will overwrite the error message. No point to continue.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_get_private_data.c, line 128 at r5](https://reviewable.io/reviews/pmem/rpma/1037#-MZZwd3dAdsBpgpIq4lj:-MZnotR4-2JSuhtMIWC6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/95d2c58ca3322efdbe24822ca2c7e87ca782942b/tests/multithreaded/conn/rpma_conn_get_private_data.c#L128)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the content
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-04 15:56 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037#-:-MZs52zjDvYTqIRbEB7O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-05-05 06:54 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037#-:-MZvIYTKBizA-A5W9GeB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-05-05 07:34 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1037)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-05-05 07:35 UTC, merged