test: add rpma_mr_get_descriptor multithreaded test
pmem/rpma pull request #1038
Opened 2021-04-29 10:00 UTC by ewanglong

2021-04-30 11:42 UTC, janekmi requested changes
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong)

___
*[tests/drd.supp, line 222 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXPSvsCzD3fr6Vac-R:-MZXPSvt8DFn0yxD3VZe:bf3uis6) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/drd.supp#L222)):*
> ```
> #
> # Probably these suppressions do not indicate a lack of MT safety.
> #
> ```

We don't know yet. Please remove.
___
*[tests/drd.supp, line 242 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXR1X-66opAyXYNgh2:-MZXR1X-66opAyXYNgh3:b2ifwlw) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/drd.supp#L242)):*
> ```
>    fun:rpma_mr_dereg
>    ...
> }
> ```

Can you provide a valgrind log?
___
*[tests/helgrind.supp, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXRJ8r8FSnhATujtqs:-MZXRJ8r8FSnhATujtqt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/helgrind.supp#L179)):*
> ```
> #
> # Probably these suppressions do not indicate a lack of MT safety.
> #
> ```

.
___
*[tests/helgrind.supp, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXRUAP2P1TkeS_qJUE:-MZXRUAP2P1TkeS_qJUF:b-fdgmql) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/helgrind.supp#L210)):*
> ```
>    fun:rpma_mr_dereg
>    ...
> }
> ```

Valgrind log?
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXTNsP0VkU0Yn6zbN-:-MZXTNsP0VkU0Yn6zbN0:b-up4ta6) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L13)):*
> ```C
> #include "mtt.h"
> 
> #define KILOBYTE 1024
> ```

It will probably common for multiple tests. I recommend moving it to the mtt.h header.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZX_Xsl6KnCs762nozw:-MZX_XsmAM733dZ-iGem:bfr5hxb) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L18)):*
> ```C
> struct prestate {
> 	char *addr;
> 	unsigned port;
> ```

Not used.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZX_7EGDhArfcdLx-ym:-MZX_7EGDhArfcdLx-yn:b-h3oe1a) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L28)):*
> ```C
> 	void *mr_ptr;
> 	struct rpma_mr_local *mr;
> };
> ```

Not needed at all?
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXZ0og48gkW6Wi343Z:-MZXZ0og48gkW6Wi343_:bvat4qj) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L54)):*
> ```C
> 	if (pr->mr_ptr == NULL) {
> 		MTT_ERR(tr, "mtt_malloc_aligned", errno);
> 		return;
> ```

You have to delete the peer.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXTofp3T8VTomq3Fc7:-MZXTofp3T8VTomq3Fc8:b-w2i3em) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L55)):*
> ```C
> 		MTT_ERR(tr, "mtt_malloc_aligned", errno);
> 		return;
> 	}
> ```

Please adjust to the mtt_malloc_aligned() signature.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXZ5ZW5o8NhB7kdIpR:-MZXZ5ZW5o8NhB7kdIpS:b-k07qkn) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L59)):*
> ```C
> 	if ((ret = rpma_mr_reg(pr->peer, pr->mr_ptr, KILOBYTE,
> 			RPMA_MR_USAGE_READ_SRC, &pr->mr)))
> 		MTT_RPMA_ERR(tr, "rpma_mr_reg", ret);
> ```

You have to delete the mr_ptr and the peer.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXUqGXA9An5n26XIK8:-MZXUqGXA9An5n26XIK9:b-5hifju) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L73)):*
> ```C
> 
> 	size_t mr_desc_size;
> 	ret = rpma_mr_get_descriptor_size(pr->mr, &mr_desc_size);
> ```

Redundant.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXVSqk30GKXKSfxidd:-MZXVSqk30GKXKSfxide:b-afey5r) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L79)):*
> ```C
> 	}
> 
> 	char descriptors[DESCRIPTORS_MAX_SIZE];
> ```

```c
char descriptor[KILOBYTE];
if (mr_desc_size > KILOBYTE) {
    MTT_ERR_MSG(tr, "mr_desc_size  > KILOBYTE", -1);
    return;
}
```
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXVzle3iscC5DlZOdc:-MZXVzle3iscC5DlZOdd:b-3j90kl) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L79)):*
> ```C
> 	}
> 
> 	char descriptors[DESCRIPTORS_MAX_SIZE];
> ```

`descriptor` instead of `descriptors`
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZX_Ckx3EC035xGoTfC:-MZX_Ckx3EC035xGoTfD:bf1dfp2) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L94)):*
> ```C
> 	int ret;
> 
> 	if (pr->mr) {
> ```

Not needed. I assume the `prestate_fini()` is not called if `presatete_init()` have failed.


<!-- Sent from Reviewable.io -->

2021-05-06 02:53 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038)* status: 1 of 8 files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[tests/drd.supp, line 222 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXPSvsCzD3fr6Vac-R:-MZzW3_I2TdKN7e36YVb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/drd.supp#L222)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We don't know yet. Please remove.
</blockquote></details>

Done.
___
*[tests/drd.supp, line 242 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXR1X-66opAyXYNgh2:-MZzW53a-7gNGSAoNiEA:b-5dfryo) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/drd.supp#L242)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you provide a valgrind log?
</blockquote></details>

removed it
___
*[tests/helgrind.supp, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXRJ8r8FSnhATujtqs:-MZzW8Yq6kfe5tZoJYTR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/helgrind.supp#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/helgrind.supp, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXRUAP2P1TkeS_qJUE:-MZzW9Cr-76cqqT9WylF:b-oicyv6) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/helgrind.supp#L210)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Valgrind log?
</blockquote></details>

removed it.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXTNsP0VkU0Yn6zbN-:-MZzWBbk4y3EK-daroun:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It will probably common for multiple tests. I recommend moving it to the mtt.h header.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZX_Xsl6KnCs762nozw:-MZz_kFO6658THQ_B041:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZX_7EGDhArfcdLx-ym:-MZz_lhwBowdSQ_Ht3s0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed at all?
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXZ0og48gkW6Wi343Z:-MZz_qrm3-wuNErxJXqb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to delete the peer.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXTofp3T8VTomq3Fc7:-MZzWCSZAfrmT-trAxzx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please adjust to the mtt_malloc_aligned() signature.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXZ5ZW5o8NhB7kdIpR:-MZz_rpZEc8cqA2Bl4jJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to delete the mr_ptr and the peer.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXUqGXA9An5n26XIK8:-MZzWDTi8xRd-Mk8Te2t:b-oicyv6) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Redundant.
</blockquote></details>

removed it.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXVSqk30GKXKSfxidd:-MZz_hWI3ydNoMVlsyh2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
char descriptor[KILOBYTE];
if (mr_desc_size > KILOBYTE) {
    MTT_ERR_MSG(tr, "mr_desc_size  > KILOBYTE", -1);
    return;
}
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZXVzle3iscC5DlZOdc:-MZz_iI929d-wEc3ld2T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`descriptor` instead of `descriptors`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1038#-MZX_Ckx3EC035xGoTfC:-MZz_jHB0HUmCvY_tUSf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/baa1f7f805922d2f53c111cf2bff344a9b059922/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed. I assume the `prestate_fini()` is not called if `presatete_init()` have failed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-06 08:07 UTC, janekmi requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-fquAAQtb4-QOCrXz:-M_-fquAAQtb4-QOCrY-:b-mgbyxn) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L8)):*
> ```C
>  */
> 
> #include <stdlib.h>
> ```

I'm not sure if it still needed here.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-fv4DDwPgyF2hcUdw:-M_-fv4DDwPgyF2hcUdx:bdyheid) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L44)):*
> ```C
> 	pr->mr_ptr = mtt_malloc_aligned(KILOBYTE, tr);
> 	if (pr->mr_ptr == NULL) {
> 		MTT_ERR(tr, "mtt_malloc_aligned()", errno);
> ```

If an error occurred `tr` already has it stored. It is not needed. Please remove.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-gXjk7u1m32e_Xq4x:-M_-gXjk7u1m32e_Xq4y:b-mdejo1) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L47)):*
> ```C
> 		if ((ret = rpma_peer_delete(&pr->peer)))
> 			MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
> 		return;
> ```

Since it is a quick exit cleanup on error you should just delete the peer. No error handling since an error has already happened. ;-)

```c
(void) rpma_peer_delete(&pr->peer);
return;
```
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-gi2B05KEgzdVEQ64:-M_-gi2B05KEgzdVEQ65:b-fb2go8) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L55)):*
> ```C
> 		free(pr->mr_ptr);
> 		if ((ret = rpma_peer_delete(&pr->peer)))
> 			MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
> ```

Same here:

```c
(void) rpma_peer_delete(&pr->peer);
return;
```
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-gwK11Lbe9ssTklIb:-M_-gwK11Lbe9ssTklIc:bjspjwu) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L78)):*
> ```C
> 		MTT_ERR_MSG(result, "mr_desc_size > KILOBYTE", -1);
> 		return;
> 	}
> ```

I think we can do one more thing in this test: collect a `mr_desc_size_exp`.
This way this check `if (mr_desc_size_exp > KILOBYTE) {` will go to the `prestate_init()` step.
Whereas here we will have a check `if (mr_desc_size == pr->mr_desc_size_exp)`.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 82 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-hPh6E3pEzAjj1tfX:-M_-hPh6E3pEzAjj1tfY:b641khc) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L82)):*
> ```C
> 	char descriptor[KILOBYTE];
> 	if ((ret = rpma_mr_get_descriptor(pr->mr, &descriptor[0])))
> 		MTT_RPMA_ERR(result, "rpma_mr_get_descriptor", ret);
> ```

... TBH we can also have `pr->descriptor_exp` prepared in the `prestate_init()` step.
So we will have here also a nice validation of the outcome e.g. `memcmp(descriptor, pr->descriptor_exp, mr_desc_size);`
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-fX5l7FdXy0rkqxUa:-M_-fX5m8b_sIS-CUyML:b-lxdlke) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L112)):*
> ```C
> 		return -1;
> 
> 	struct prestate prestate = {args.addr, args.port, NULL, NULL};
> ```

Please adjust to the current prestate structure.
e.g. you do not have a port here any longer.


<!-- Sent from Reviewable.io -->

2021-05-06 17:15 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-fquAAQtb4-QOCrXz:-M_1f6NCChuPLquM48dh:b-iqci1) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure if it still needed here.
</blockquote></details>

free() function need it.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-fv4DDwPgyF2hcUdw:-M_1f9kvBHJ1qHF7xfmR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If an error occurred `tr` already has it stored. It is not needed. Please remove.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-gXjk7u1m32e_Xq4x:-M_1fAUw0CKZDGVPyBHH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it is a quick exit cleanup on error you should just delete the peer. No error handling since an error has already happened. ;-)

```c
(void) rpma_peer_delete(&pr->peer);
return;
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-gi2B05KEgzdVEQ64:-M_1fB-C1kJ1O3lMPNv4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here:

```c
(void) rpma_peer_delete(&pr->peer);
return;
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-gwK11Lbe9ssTklIb:-M_1fBe9BAgzAPOddFQY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can do one more thing in this test: collect a `mr_desc_size_exp`.
This way this check `if (mr_desc_size_exp > KILOBYTE) {` will go to the `prestate_init()` step.
Whereas here we will have a check `if (mr_desc_size == pr->mr_desc_size_exp)`.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 82 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-hPh6E3pEzAjj1tfX:-M_1fCFy86rGc-vaqdm8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... TBH we can also have `pr->descriptor_exp` prepared in the `prestate_init()` step.
So we will have here also a nice validation of the outcome e.g. `memcmp(descriptor, pr->descriptor_exp, mr_desc_size);`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1038#-M_-fX5l7FdXy0rkqxUa:-M_1fDU1-35Nb8dGa2rx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/410b11d8bd13c4cffbd9689061abee00cef4dbc0/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please adjust to the current prestate structure.
e.g. you do not have a port here any longer.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-09 23:17 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_INvlwD1bBmGDZDIwC:-M_INvlwD1bBmGDZDIwD:beg25ir) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L25)):*
> ```C
> /*
>  * prestate_init -- obtain an ibv_context for a local IP address,
>  * create a new peer object, allocate and register memory region
> ```

... and prepare an expected descriptor value for the memory region.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_INNrp7iIEzA39-HnG:-M_INNrp7iIEzA39-HnH:bm92q2o) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L34)):*
> ```C
> 
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_LOCAL, &pr->dev))) {
> ```

`pr->dev` can be kept locally. No need to store it in the prestate.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 59 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IMpDG7ad3Fct3R8r-:-M_IMpDG7ad3Fct3R8r0:bns4rel) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L59)):*
> ```C
> 		goto err_mr_dereg;
> 	}
> ```

You have to validate if `mr_desc_size_exp <= KILOBYTE`.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 76 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IOOaQ5KgEgWk0oWzE:-M_IOOaQ5KgEgWk0oWzF:b-mkkje3) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L76)):*
> ```C
> 
> /*
>  * thread -- get the memory region's descriptor
> ```

... and validate it
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 85 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IOUBG-ZdL9hD1Tubj:-M_IOUBG-ZdL9hD1Tubk:bssl7z5) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L85)):*
> ```C
> 	int ret;
> 
> 	size_t mr_desc_size;
> ```

According to the C standard, all variables should be defined at the beginning of the function.

```c
	struct prestate *pr = (struct prestate *)prestate;
	size_t mr_desc_size;
	char descriptor[KILOBYTE];
	int ret;

/* the rest goes after a newline */
```
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IOiT9C37gNnHqrNZ7:-M_IOiT9C37gNnHqrNZ8:b-m3xfsb) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L94)):*
> ```C
> 		MTT_ERR_MSG(result, "mr_desc_size > KILOBYTE", -1);
> 		return;
> 	}
> ```

This validation should be part of the `prestate_init()`.


<!-- Sent from Reviewable.io -->

2021-05-10 03:36 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_INvlwD1bBmGDZDIwC:-M_JL0JtEta0FyyCHCeU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... and prepare an expected descriptor value for the memory region.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_INNrp7iIEzA39-HnG:-M_JL3jl1owiLy7O1aXX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`pr->dev` can be kept locally. No need to store it in the prestate.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 59 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IMpDG7ad3Fct3R8r-:-M_JL56H3xjqUN917OI0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to validate if `mr_desc_size_exp <= KILOBYTE`.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 76 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IOOaQ5KgEgWk0oWzE:-M_JL5srAG6zxz4VqDTY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... and validate it
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 85 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IOUBG-ZdL9hD1Tubj:-M_JL7Q_C6oXI_Hxdkyb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

According to the C standard, all variables should be defined at the beginning of the function.

```c
	struct prestate *pr = (struct prestate *)prestate;
	size_t mr_desc_size;
	char descriptor[KILOBYTE];
	int ret;

/* the rest goes after a newline */
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_descriptor.c, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/1038#-M_IOiT9C37gNnHqrNZ7:-M_JL8WN2t6NwLR4EASq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fd784467db5512819f423dc44cc8712a143f629/tests/multithreaded/mr/rpma_mr_get_descriptor.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This validation should be part of the `prestate_init()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-12 05:33 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038#-:-M_U39IOCWdaEW0P37Ta:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-05-12 08:56 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1038#-:-M_Umkj123FssqbDhznO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-05-12 13:06 UTC, merged