test: add rpma_conn_req_new multithreaded test
pmem/rpma pull request #1058
Opened 2021-05-17 08:03 UTC by ewanglong

2021-05-21 04:47 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-05-28 07:45 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/drd.supp, line 226 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malpn8oDFrhiphycJUq:-Malpn8oDFrhiphycJUr:b-f7wrq6) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/drd.supp#L226)):*
> ```
>    fun:_execute_ioctl_fallback
>    ...
> }
> ```

Please provide Valgrind logs for both drd and helgrind.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-MaltV2t3It5nigXoTJ1:-MaltV2t3It5nigXoTJ2:b-mdqas3) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/multithreaded/conn/rpma_conn_req_new.c#L33)):*
> ```C
> 	struct prestate *pr = (struct prestate *)prestate;
> 	int ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_REMOTE, &pr->dev);
> ```

`dev` should be local.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malro5U1t8ZIGKD7Lme:-Malro5U1t8ZIGKD7Lmf:bt2mhg4) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/multithreaded/conn/rpma_conn_req_new.c#L73)):*
> ```C
> 	MTT_PORT_SET(pr->port, id);
> 	if ((ret = rpma_conn_req_new(pr->peer, pr->addr,
> 				MTT_PORT_STR, NULL, &st->req)))
> ```

I think we need to create two connection requests:
- one without rpma_conn_cfg (as it is above) and
- one with rpma_conn_cfg (optimally the same connection configuration object for all threads)


<!-- Sent from Reviewable.io -->

2021-05-28 08:33 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Mam5YvKBu0p4sVt2Nbd:-Mam5YvL5gTwtK5nBxOe:b5xxsub) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/multithreaded/conn/rpma_conn_req_new.c#L34)):*
> ```C
> 	int ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_REMOTE, &pr->dev);
> 	if (ret) {
> ```

Please apply consistently.

```c
int ret;

if ((ret = rpma_utils_get_ibv_context(/* ... */))) {
    /* ... */
}
```


<!-- Sent from Reviewable.io -->

2021-05-31 05:55 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ewanglong, @grom72, and @janekmi)

___
*[tests/drd.supp, line 226 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malpn8oDFrhiphycJUq:-Mb-a4omECCTteMoIZME:ba5u0yh) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/drd.supp#L226)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please provide Valgrind logs for both drd and helgrind.
</blockquote></details>

drd log:
==810687== drd, a thread error detector
==810687== Copyright (C) 2006-2017, and GNU GPL'd, by Bart Van Assche.
==810687== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==810687== Command: ./rpma_conn_req_new 32 10.239.173.56 7204
==810687== Parent PID: 4672
==810687==
==810687== Thread 26:
==810687== Conflicting load by thread 26 at 0x04b763f0 size 8
==810687==    at 0x4A82CF1: bitmap_test_bit (bitmap.h:71)
==810687==    by 0x4A82CF1: _execute_ioctl_fallback (cmd_fallback.c:90)
==810687==    by 0x4A80C5D: ibv_icmd_create_cq (cmd_cq.c:70)
==810687==    by 0x4A80F2E: ibv_cmd_create_cq (cmd_cq.c:137)
==810687==    by 0x4870CD0: rxe_create_cq (rxe.c:177)
==810687==    by 0x4A8CE03: ibv_create_cq@@IBVERBS_1.1 (verbs.c:509)
==810687==    by 0x485ED60: rpma_conn_req_from_id (conn_req.c:68)
==810687==    by 0x485F969: rpma_conn_req_new (conn_req.c:361)
==810687==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==810687==    by 0x401581: mtt_thread_main (mtt.c:89)
==810687==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==810687==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==810687==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)
==810687== Address 0x4b763f0 is at offset 0 from 0x4b763f0. Allocation context:
==810687==    at 0x483FB95: calloc (vg_replace_malloc.c:762)
==810687==    by 0x4A87286: verbs_init_context (device.c:246)
==810687==    by 0x4A873BA: _verbs_init_and_alloc_context (device.c:282)
==810687==    by 0x4870407: rxe_alloc_context (rxe.c:874)
==810687==    by 0x4A8743A: verbs_open_device (device.c:343)
==810687==    by 0x4A9C419: ucma_init_device.part.0 (cma.c:437)
==810687==    by 0x4A9CABF: ucma_init_device (cma.c:628)
==810687==    by 0x4A9CABF: ucma_get_device (cma.c:631)
==810687==    by 0x4A9CC18: ucma_query_addr (cma.c:888)
==810687==    by 0x4A9F218: ucma_process_addr_resolved (cma.c:2245)
==810687==    by 0x4A9F218: rdma_get_cm_event (cma.c:2532)
==810687==    by 0x4A9FB3E: ucma_complete (cma.c:1111)
==810687==    by 0x4A9FC3A: rdma_resolve_addr2 (cma.c:1148)
==810687==    by 0x4860832: rpma_info_resolve_addr (info.c:113)
==810687== Other segment start (thread 18)
==810687==    at 0x4844EF5: pthread_mutex_unlock_intercept (drd_pthread_intercepts.c:978)
==810687==    by 0x4844EF5: pthread_mutex_unlock (drd_pthread_intercepts.c:991)
==810687==    by 0x4A9E370: ucma_complete_event (cma.c:2212)
==810687==    by 0x4A9E370: rdma_ack_cm_event (cma.c:2237)
==810687==    by 0x4A9FB23: ucma_complete (cma.c:1107)
==810687==    by 0x4A9FEAE: rdma_resolve_route (cma.c:1235)
==810687==    by 0x485F8D3: rpma_conn_req_new (conn_req.c:353)
==810687==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==810687==    by 0x401581: mtt_thread_main (mtt.c:89)
==810687==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==810687==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==810687==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)
==810687== Other segment end (thread 18)
==810687==    at 0x4843ED5: pthread_mutex_lock_intercept (drd_pthread_intercepts.c:888)
==810687==    by 0x4843ED5: pthread_mutex_lock (drd_pthread_intercepts.c:898)
==810687==    by 0x4A87174: verbs_init_cq (device.c:168)
==810687==    by 0x4A8CE1C: ibv_create_cq@@IBVERBS_1.1 (verbs.c:512)
==810687==    by 0x485ED60: rpma_conn_req_from_id (conn_req.c:68)
==810687==    by 0x485F969: rpma_conn_req_new (conn_req.c:361)
==810687==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==810687==    by 0x401581: mtt_thread_main (mtt.c:89)
==810687==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==810687==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==810687==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)

helgrind log:
==805182== ----------------------------------------------------------------
==805182==
==805182== Possible data race during read of size 8 at 0x4B6A8C0 by thread #13
==805182== Locks held: none
==805182==    at 0x4A75CF1: bitmap_test_bit (bitmap.h:71)
==805182==    by 0x4A75CF1: _execute_ioctl_fallback (cmd_fallback.c:90)
==805182==    by 0x4A73C5D: ibv_icmd_create_cq (cmd_cq.c:70)
==805182==    by 0x4A73F2E: ibv_cmd_create_cq (cmd_cq.c:137)
==805182==    by 0x4863CD0: rxe_create_cq (rxe.c:177)
==805182==    by 0x4A7FE03: ibv_create_cq@@IBVERBS_1.1 (verbs.c:509)
==805182==    by 0x4851D60: rpma_conn_req_from_id (conn_req.c:68)
==805182==    by 0x4852969: rpma_conn_req_new (conn_req.c:361)
==805182==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==805182==    by 0x401581: mtt_thread_main (mtt.c:89)
==805182==    by 0x4841536: mythread_wrapper (hg_intercepts.c:389)
==805182==    by 0x4888431: start_thread (in /usr/lib64/libpthread-2.31.so)
==805182==    by 0x49A29D2: clone (in /usr/lib64/libc-2.31.so)
==805182==
==805182== This conflicts with a previous write of size 8 by thread #33
==805182== Locks held: none
==805182==    at 0x4A75D30: bitmap_set_bit (bitmap.h:56)
==805182==    by 0x4A75D30: _execute_ioctl_fallback (cmd_fallback.c:109)
==805182==    by 0x4A77373: ibv_icmd_create_qp (cmd_qp.c:211)
==805182==    by 0x4A77B62: ibv_cmd_create_qp (cmd_qp.c:388)
==805182==    by 0x4863B0D: rxe_create_qp (rxe.c:452)
==805182==    by 0x4A90CCC: ibv_create_qp_ex (verbs.h:2973)
==805182==    by 0x4A90CCC: rdma_create_qp_ex (cma.c:1663)
==805182==    by 0x4A90E60: rdma_create_qp (cma.c:1702)
==805182==    by 0x4855069: rpma_peer_create_qp (peer.c:127)
==805182==    by 0x4851E85: rpma_conn_req_from_id (conn_req.c:87)
==805182==  Address 0x4b6a8c0 is 0 bytes inside a block of size 608 alloc'd
==805182==    at 0x483D9C5: calloc (vg_replace_malloc.c:762)
==805182==    by 0x4A7A286: verbs_init_context (device.c:246)
==805182==    by 0x4A7A3BA: _verbs_init_and_alloc_context (device.c:282)
==805182==    by 0x4863407: rxe_alloc_context (rxe.c:874)
==805182==    by 0x4A7A43A: verbs_open_device (device.c:343)
==805182==    by 0x4A8F419: ucma_init_device.part.0 (cma.c:437)
==805182==    by 0x4A8FABF: ucma_init_device (cma.c:628)
==805182==    by 0x4A8FABF: ucma_get_device (cma.c:631)
==805182==    by 0x4A8FC18: ucma_query_addr (cma.c:888)
==805182==    by 0x4A92218: ucma_process_addr_resolved (cma.c:2245)
==805182==    by 0x4A92218: rdma_get_cm_event (cma.c:2532)
==805182==    by 0x4A92B3E: ucma_complete (cma.c:1111)
==805182==    by 0x4A92C3A: rdma_resolve_addr2 (cma.c:1148)
==805182==    by 0x4853832: rpma_info_resolve_addr (info.c:113)
==805182==  Block was alloc'd by thread #1
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-MaltV2t3It5nigXoTJ1:-Mb-yspS7rvPzT81qpXR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/multithreaded/conn/rpma_conn_req_new.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`dev` should be local.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Mam5YvKBu0p4sVt2Nbd:-Mb-zQ7v4oYhs0kmqZuU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/multithreaded/conn/rpma_conn_req_new.c#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please apply consistently.

```c
int ret;

if ((ret = rpm [...]

2021-05-31 09:43 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/drd.supp, line 226 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malpn8oDFrhiphycJUq:-Mb0mTuh0rhitPeEVkCO:b5pcx7b) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/drd.supp#L226)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

drd log:
==810687== drd, a thread error detector
==810687== Copyright (C) 2006-2017, and GNU GPL'd, by Bart Van Assche.
==810687== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==810687== Command: ./rpma_conn_req_new 32 10.239.173.56 7204
==810687== Parent PID: 4672
==810687==
==810687== Thread 26:
==810687== Conflicting load by thread 26 at 0x04b763f0 size 8
==810687==    at 0x4A82CF1: bitmap_test_bit (bitmap.h:71)
==810687==    by 0x4A82CF1: _execute_ioctl_fallback (cmd_fallback.c:90)
==810687==    by 0x4A80C5D: ibv_icmd_create_cq (cmd_cq.c:70)
==810687==    by 0x4A80F2E: ibv_cmd_create_cq (cmd_cq.c:137)
==810687==    by 0x4870CD0: rxe_create_cq (rxe.c:177)
==810687==    by 0x4A8CE03: ibv_create_cq@@IBVERBS_1.1 (verbs.c:509)
==810687==    by 0x485ED60: rpma_conn_req_from_id (conn_req.c:68)
==810687==    by 0x485F969: rpma_conn_req_new (conn_req.c:361)
==810687==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==810687==    by 0x401581: mtt_thread_main (mtt.c:89)
==810687==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==810687==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==810687==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)
==810687== Address 0x4b763f0 is at offset 0 from 0x4b763f0. Allocation context:
==810687==    at 0x483FB95: calloc (vg_replace_malloc.c:762)
==810687==    by 0x4A87286: verbs_init_context (device.c:246)
==810687==    by 0x4A873BA: _verbs_init_and_alloc_context (device.c:282)
==810687==    by 0x4870407: rxe_alloc_context (rxe.c:874)
==810687==    by 0x4A8743A: verbs_open_device (device.c:343)
==810687==    by 0x4A9C419: ucma_init_device.part.0 (cma.c:437)
==810687==    by 0x4A9CABF: ucma_init_device (cma.c:628)
==810687==    by 0x4A9CABF: ucma_get_device (cma.c:631)
==810687==    by 0x4A9CC18: ucma_query_addr (cma.c:888)
==810687==    by 0x4A9F218: ucma_process_addr_resolved (cma.c:2245)
==810687==    by 0x4A9F218: rdma_get_cm_event (cma.c:2532)
==810687==    by 0x4A9FB3E: ucma_complete (cma.c:1111)
==810687==    by 0x4A9FC3A: rdma_resolve_addr2 (cma.c:1148)
==810687==    by 0x4860832: rpma_info_resolve_addr (info.c:113)
==810687== Other segment start (thread 18)
==810687==    at 0x4844EF5: pthread_mutex_unlock_intercept (drd_pthread_intercepts.c:978)
==810687==    by 0x4844EF5: pthread_mutex_unlock (drd_pthread_intercepts.c:991)
==810687==    by 0x4A9E370: ucma_complete_event (cma.c:2212)
==810687==    by 0x4A9E370: rdma_ack_cm_event (cma.c:2237)
==810687==    by 0x4A9FB23: ucma_complete (cma.c:1107)
==810687==    by 0x4A9FEAE: rdma_resolve_route (cma.c:1235)
==810687==    by 0x485F8D3: rpma_conn_req_new (conn_req.c:353)
==810687==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==810687==    by 0x401581: mtt_thread_main (mtt.c:89)
==810687==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==810687==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==810687==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)
==810687== Other segment end (thread 18)
==810687==    at 0x4843ED5: pthread_mutex_lock_intercept (drd_pthread_intercepts.c:888)
==810687==    by 0x4843ED5: pthread_mutex_lock (drd_pthread_intercepts.c:898)
==810687==    by 0x4A87174: verbs_init_cq (device.c:168)
==810687==    by 0x4A8CE1C: ibv_create_cq@@IBVERBS_1.1 (verbs.c:512)
==810687==    by 0x485ED60: rpma_conn_req_from_id (conn_req.c:68)
==810687==    by 0x485F969: rpma_conn_req_new (conn_req.c:361)
==810687==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==810687==    by 0x401581: mtt_thread_main (mtt.c:89)
==810687==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==810687==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==810687==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)

helgrind log:
==805182== ----------------------------------------------------------------
==805182==
==805182== Possible data race during read of size 8 at 0x4B6A8C0 by thread #13
==805182== Locks held: none
==805182==    at 0x4A75CF1: bitmap_test_bit (bitmap.h:71)
==805182==    by 0x4A75CF1: _execute_ioctl_fallback (cmd_fallback.c:90)
==805182==    by 0x4A73C5D: ibv_icmd_create_cq (cmd_cq.c:70)
==805182==    by 0x4A73F2E: ibv_cmd_create_cq (cmd_cq.c:137)
==805182==    by 0x4863CD0: rxe_create_cq (rxe.c:177)
==805182==    by 0x4A7FE03: ibv_create_cq@@IBVERBS_1.1 (verbs.c:509)
==805182==    by 0x4851D60: rpma_conn_req_from_id (conn_req.c:68)
==805182==    by 0x4852969: rpma_conn_req_new (conn_req.c:361)
==805182==    by 0x4022BD: thread (rpma_conn_req_new.c:72)
==805182==    by 0x401581: mtt_thread_main (mtt.c:89)
==805182==    by 0x4841536: mythread_wrapper (hg_intercepts.c:389)
==805182==    by 0x4888431: start_thread (in /usr/lib64/libpthread-2.31.so)
==805182==    by 0x49A29D2: clone (in /usr/lib64/libc-2.31.so)
==805182==
==805182== This conflicts with a previous write of size 8 by thread #33
==805182== Locks held: none
==805182==    at 0x4A75D30: bitmap_set_bit (bitmap.h:56)
==805182==    by 0x4A75D30: _execute_ioctl_fallback (cmd_fallback.c:109)
==805182==    by 0x4A77373: ibv_icmd_create_qp (cmd_qp.c:211)
==805182==    by 0x4A77B62: ibv_cmd_create_qp (cmd_qp.c:388)
==805182==    by 0x4863B0D: rxe_create_qp (rxe.c:452)
==805182==    by 0x4A90CCC: ibv_create_qp_ex (verbs.h:2973)
==805182==    by 0x4A90CCC: rdma_create_qp_ex (cma.c:1663)
==805182==    by 0x4A90E60: rdma_create_qp (cma.c:1702)
==805182==    by 0x4855069: rpma_peer_create_qp (peer.c:127)
==805182==    by 0x4851E85: rpma_conn_req_from_id (conn_req.c:87)
==805182==  Address 0x4b6a8c0 is 0 bytes inside a block of size 608 alloc'd
==805182==    at 0x483D9C5: calloc (vg_replace_malloc.c:762)
==805182==    by 0x4A7A286: verbs_init_context (device.c:246)
==805182==    by 0x4A7A3BA: _verbs_init_and_alloc_context (device.c:282)
==805182==    by 0x4863407: rxe_alloc_context (rxe.c:874)
==805182==    by 0x4A7A43A: verbs_open_device (device.c:343)
==805182==    by 0x4A8F419: ucma_init_device.part.0 (cma.c:437)
==805182==    by 0x4A8FABF: ucma_init_device (cma.c:628)
==805182==    by 0x4A8FABF: ucma_get_device (cma.c:631)
==805182==    by 0x4A8FC18: ucma_query_addr (cma.c:888)
==805182==    by 0x4A92218: ucma_process_addr_resolved (cma.c:2245)
==805182==    by 0x4A92218: rdma_get_cm_event (cma.c:2532)
==805182==    by 0x4A92B3E: ucma_complete (cma.c:1111)
==805182==    by 0x4A92C3A: rdma_resolve_addr2 (cma.c:1148)
==805182==    by 0x4853832: rpma_info_resolve_addr (info.c:113)
==805182==  Block was alloc'd by thread #1
</blockquote></details>

Based on what we got here I think we should suppress it as follows:

```c
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Conflicting load/store of size 8
   drd:ConflictingAccess
   fun:bitmap_set_bit
   fun:_execute_ioctl_fallback
   ...
}
```
___
*[tests/helgrind.supp, line 195 at r4](https://reviewable.io/reviews/pmem/rpma/1058#-Mb0nZcq0b_VA7hfM56X:-Mb0nLZ26zOvQlr5TLgY:b2esjh4) ([raw file](https://github.com/pmem/rpma/blob/4516d537e68b1e69f3660fe30db1f59960cff481/tests/helgrind.supp#L195)):*
> ```
>    fun:_execute_ioctl_fallback
>    ...
> }
> ```

```c
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Possible data race during read/write of size 8
   Helgrind:Race
   fun:bitmap_set_bit
   fun:_execute_ioctl_fallback
   ...
}
```


<!-- Sent from Reviewable.io -->

2021-06-02 08:03 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 115 at r4](https://reviewable.io/reviews/pmem/rpma/1058#-MbAjfKu3HyRbkTNbqBJ:-MbAjfKvA7z9ByUd27xR:b46tefs) ([raw file](https://github.com/pmem/rpma/blob/4516d537e68b1e69f3660fe30db1f59960cff481/tests/multithreaded/conn/rpma_conn_req_new.c#L115)):*
> ```C
> 		return -1;
> 
> 	struct prestate prestate = {args.addr, args.port, NULL, NULL};
> ```

There is a compilation error on GCC v11.1.0 here:

```
/home/ldorau/work/rpma/tests/multithreaded/conn/rpma_conn_req_new.c: In function ‘main’:
/home/ldorau/work/rpma/tests/multithreaded/conn/rpma_conn_req_new.c:115:65: error: excess elements in struct initializer [-Werror]
  115 |         struct prestate prestate = {args.addr, args.port, NULL, NULL};
      |                                                                 ^~~~
/home/ldorau/work/rpma/tests/multithreaded/conn/rpma_conn_req_new.c:115:65: note: (near initialization for ‘prestate’)
cc1: all warnings being treated as errors
```


<!-- Sent from Reviewable.io -->

2021-06-02 08:50 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/drd.supp, line 226 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malpn8oDFrhiphycJUq:-MbAoAcM0De4TMQ2F1LN:b-y2uq6l) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/drd.supp#L226)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Based on the suppress, the drd log is output as below.
==1925011== drd, a thread error detector
==1925011== Copyright (C) 2006-2017, and GNU GPL'd, by Bart Van Assche.
==1925011== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==1925011== Command: ./rpma_conn_req_new 32 10.239.173.56 7204
==1925011==
==1925011== Thread 8:
==1925011== Conflicting load by thread 8 at 0x04b763f0 size 8
==1925011==    at 0x4A82CF1: bitmap_test_bit (bitmap.h:71)
==1925011==    by 0x4A82CF1: _execute_ioctl_fallback (cmd_fallback.c:90)
==1925011==    by 0x4A80C5D: ibv_icmd_create_cq (cmd_cq.c:70)
==1925011==    by 0x4A80F2E: ibv_cmd_create_cq (cmd_cq.c:137)
==1925011==    by 0x4870CD0: rxe_create_cq (rxe.c:177)
==1925011==    by 0x4A8CE03: ibv_create_cq@@IBVERBS_1.1 (verbs.c:509)
==1925011==    by 0x485ED60: rpma_conn_req_from_id (conn_req.c:68)
==1925011==    by 0x485F969: rpma_conn_req_new (conn_req.c:361)
==1925011==    by 0x4022B5: thread (rpma_conn_req_new.c:73)
==1925011==    by 0x401581: mtt_thread_main (mtt.c:89)
==1925011==    by 0x4840EC6: vgDrd_thread_wrapper (drd_pthread_intercepts.c:444)
==1925011==    by 0x4895431: start_thread (in /usr/lib64/libpthread-2.31.so)
==1925011==    by 0x49AF9D2: clone (in /usr/lib64/libc-2.31.so)
==1925011== Address 0x4b763f0 is at offset 0 from 0x4b763f0. Allocation context:
==1925011==    at 0x483FB95: calloc (vg_replace_malloc.c:762)
==1925011==    by 0x4A87286: verbs_init_context (device.c:246)
==1925011==    by 0x4A873BA: _verbs_init_and_alloc_context (device.c:282)
==1925011==    by 0x4870407: rxe_alloc_context (rxe.c:874)
==1925011==    by 0x4A8743A: verbs_open_device (device.c:343)
==1925011==    by 0x4A9C419: ucma_init_device.part.0 (cma.c:437)
==1925011==    by 0x4A9CABF: ucma_init_device (cma.c:628)
==1925011==    by 0x4A9CABF: ucma_get_device (cma.c:631)
==1925011==    by 0x4A9CC18: ucma_query_addr (cma.c:888)
==1925011==    by 0x4A9F218: ucma_process_addr_resolved (cma.c:2245)
==1925011==    by 0x4A9F218: rdma_get_cm_event (cma.c:2532)
==1925011==    by 0x4A9FB3E: ucma_complete (cma.c:1111)
==1925011==    by 0x4A9FC3A: rdma_resolve_addr2 (cma.c:1148)
==1925011==    by 0x4860832: rpma_info_resolve_addr (info.c:113)
</blockquote></details>

It has to look like this:

```
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Conflicting load/store of size 8
   drd:ConflictingAccess
   ...
   fun:_execute_ioctl_fallback
   ...
}
```

because the @janekmi 's one does not suppress the following one:

```
==35618== Thread 24:
==35618== Conflicting load by thread 24 at 0x04b7b900 size 8
==35618==    at 0x4A9A2D2: _execute_ioctl_fallback (cmd_fallback.c:90)
==35618==    by 0x4A98CCB: ibv_icmd_create_cq (cmd_cq.c:61)
==35618==    by 0x4A98FEF: ibv_cmd_create_cq (cmd_cq.c:128)
==35618==    by 0x5040324: rxe_create_cq (rxe.c:174)
```
___
*[tests/helgrind.supp, line 195 at r4](https://reviewable.io/reviews/pmem/rpma/1058#-Mb0nZcq0b_VA7hfM56X:-MbAouUDEG1X5zy22axd:b-fdn5px) ([raw file](https://github.com/pmem/rpma/blob/4516d537e68b1e69f3660fe30db1f59960cff481/tests/helgrind.supp#L195)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Possible data race during read/write of size 8
   Helgrind:Race
   fun:bitmap_set_bit
   fun:_execute_ioctl_fallback
   ...
}
```
</blockquote></details>

It has to look like this:

```
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Possible data race during read/write of size 8
   Helgrind:Race
   ...
   fun:_execute_ioctl_fallback
   ...
}
```

because the @janekmi 's one does not suppress the following one:

```
==35690== Possible data race during read of size 8 at 0x4B70BB0 by thread #19
==35690== Locks held: none
==35690==    at 0x4A8E2D2: _execute_ioctl_fallback (cmd_fallback.c:90)
==35690==    by 0x4A8CCCB: ibv_icmd_create_cq (cmd_cq.c:61)
==35690==    by 0x4A8CFEF: ibv_cmd_create_cq (cmd_cq.c:128)
==35690==    by 0x5034324: rxe_create_cq (rxe.c:174)
```


<!-- Sent from Reviewable.io -->

2021-06-02 10:43 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-02 10:44 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/drd.supp, line 226 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malpn8oDFrhiphycJUq:-MbBJcnJ50mOCIDG4lGr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/drd.supp#L226)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has to look like this:

```
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Conflicting load/store of size 8
   drd:ConflictingAccess
   ...
   fun:_execute_ioctl_fallback
   ...
}
```

because the @janekmi 's one does not suppress the following one:

```
==35618== Thread 24:
==35618== Conflicting load by thread 24 at 0x04b7b900 size 8
==35618==    at 0x4A9A2D2: _execute_ioctl_fallback (cmd_fallback.c:90)
==35618==    by 0x4A98CCB: ibv_icmd_create_cq (cmd_cq.c:61)
==35618==    by 0x4A98FEF: ibv_cmd_create_cq (cmd_cq.c:128)
==35618==    by 0x5040324: rxe_create_cq (rxe.c:174)
```

</blockquote></details>

Done.
___
*[tests/helgrind.supp, line 195 at r4](https://reviewable.io/reviews/pmem/rpma/1058#-Mb0nZcq0b_VA7hfM56X:-MbBJdv12RLmPNmR8fK2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4516d537e68b1e69f3660fe30db1f59960cff481/tests/helgrind.supp#L195)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has to look like this:

```
# Occurs in traces of:
# - rpma_conn_req_new
# - rpma_conn_req_from_id
{
   Possible data race during read/write of size 8
   Helgrind:Race
   ...
   fun:_execute_ioctl_fallback
   ...
}
```

because the @janekmi 's one does not suppress the following one:

```
==35690== Possible data race during read of size 8 at 0x4B70BB0 by thread #19
==35690== Locks held: none
==35690==    at 0x4A8E2D2: _execute_ioctl_fallback (cmd_fallback.c:90)
==35690==    by 0x4A8CCCB: ibv_icmd_create_cq (cmd_cq.c:61)
==35690==    by 0x4A8CFEF: ibv_cmd_create_cq (cmd_cq.c:128)
==35690==    by 0x5034324: rxe_create_cq (rxe.c:174)
```

</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 115 at r4](https://reviewable.io/reviews/pmem/rpma/1058#-MbAjfKu3HyRbkTNbqBJ:-MbBJfKkEyJbt-13oGdb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4516d537e68b1e69f3660fe30db1f59960cff481/tests/multithreaded/conn/rpma_conn_req_new.c#L115)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is a compilation error on GCC v11.1.0 here:

```
/home/ldorau/work/rpma/tests/multithreaded/conn/rpma_conn_req_new.c: In function ‘main’:
/home/ldorau/work/rpma/tests/multithreaded/conn/rpma_conn_req_new.c:115:65: error: excess elements in struct initializer [-Werror]
  115 |         struct prestate prestate = {args.addr, args.port, NULL, NULL};
      |                                                                 ^~~~
/home/ldorau/work/rpma/tests/multithreaded/conn/rpma_conn_req_new.c:115:65: note: (near initialization for ‘prestate’)
cc1: all warnings being treated as errors
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-02 10:44 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-04 03:46 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1058#-Malro5U1t8ZIGKD7Lme:-MbK7NBu5DbUN-5O0Fbm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89dc9ac3080c3b973d25bf90599c7ae38014f236/tests/multithreaded/conn/rpma_conn_req_new.c#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we need to create two connection requests:
- one without rpma_conn_cfg (as it is above) and
- one with rpma_conn_cfg (optimally the same connection configuration object for all threads)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-04 04:51 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-06-04 09:41 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r5, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLM9rS1dE2wIjV8tbF:-MbLM9rT67QpQpulygOG:b-e852lf) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L17)):*
> ```C
> 	unsigned port;
> 	struct rpma_peer *peer;
> };
> ```

I believe this one is not needed. Please see other comments.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 140 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLMIJJEBjjOcAQLv8D:-MbLMIJJEBjjOcAQLv8E:buq0skh) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L140)):*
> ```C
> 		(void) rpma_peer_delete(&pr->peer);
> 	}
> }
> ```

Too much code duplicated.

```c
static void
prestate_init_with_conn_cfg(void *prestate, struct mtt_result *tr)
{
    struct prestate2 *pr = (struct prestate2 *)prestate;
    int ret;

    prestate_init(prestate, tr);
    if (tr->ret)
        return;

    if ((ret = rpma_conn_cfg_new(&pr->cfg))) {
	MTT_RPMA_ERR(tr, "rpma_conn_cfg_new", ret);
	(void) rpma_peer_delete(&pr->peer);
    }
}
```
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 159 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLN2R5-d6phNGpnRFf:-MbLN2R5-d6phNGpnRFg:b1u3hzp) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L159)):*
> ```C
> 				MTT_PORT_STR, pr->cfg, &st->req)))
> 		MTT_RPMA_ERR(result, "rpma_conn_req_new", ret);
> }
> ```

This is the only thread variant that is necessary.

1. For a test with `prestate_init()` `pr->cfg == NULL`
2. For a test with `prestate_init_with_conn_cfg()` `pr->cfg != NULL`.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 174 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLNbEg8fplZ1UE4Sck:-MbLNbEg8fplZ1UE4Scl:bthiant) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L174)):*
> ```C
> 
> 	if ((ret = rpma_conn_cfg_delete(&pr->cfg)))
> 		MTT_RPMA_ERR(tr, "rpma_conn_cfg_delete", ret);
> ```

You do not need two variants of prestate_fini either.

```c
if (pr->cfg) {
    if ((ret = rpma_conn_cfg_delete(&pr->cfg)))
        MTT_RPMA_ERR(tr, "rpma_conn_cfg_delete", ret);
}
```
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 187 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLO8SWA5wD2yF70JY-:-MbLO8SWA5wD2yF70JY0:bkk9aq3) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L187)):*
> ```C
> 
> 	struct prestate prestate = {args.addr, args.port, NULL};
> 	struct prestate2 prestate2 = {args.addr, args.port, NULL};
> ```

You have 4 fields in this structure.


<!-- Sent from Reviewable.io -->

2021-06-04 09:51 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-06-07 02:50 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLM9rS1dE2wIjV8tbF:-MbZN6ca5Y-qaPw2ptsX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe this one is not needed. Please see other comments.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 140 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLMIJJEBjjOcAQLv8D:-MbZN7O98GmaE-wVTs9H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L140)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too much code duplicated.

```c
static void
prestate_init_with_conn_cfg(void *prestate, struct mtt_result *tr)
{
    struct prestate2 *pr = (struct prestate2 *)prestate;
    int ret;

    prestate_init(prestate, tr);
    if (tr->ret)
        return;

    if ((ret = rpma_conn_cfg_new(&pr->cfg))) {
	MTT_RPMA_ERR(tr, "rpma_conn_cfg_new", ret);
	(void) rpma_peer_delete(&pr->peer);
    }
}
```

</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 159 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLN2R5-d6phNGpnRFf:-MbZN8jkEfsbBFtPDQ5K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L159)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is the only thread variant that is necessary.

1. For a test with `prestate_init()` `pr->cfg == NULL`
2. For a test with `prestate_init_with_conn_cfg()` `pr->cfg != NULL`.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 174 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLNbEg8fplZ1UE4Sck:-MbZN9Pm50fmsGjor947:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not need two variants of prestate_fini either.

```c
if (pr->cfg) {
    if ((ret = rpma_conn_cfg_delete(&pr->cfg)))
        MTT_RPMA_ERR(tr, "rpma_conn_cfg_delete", ret);
}
```

</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_req_new.c, line 187 at r7](https://reviewable.io/reviews/pmem/rpma/1058#-MbLO8SWA5wD2yF70JY-:-MbZNA6HAn8xxtkP3t7z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77bc1557e9aeec0a81cf026cf9329feb34a89977/tests/multithreaded/conn/rpma_conn_req_new.c#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have 4 fields in this structure.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-07 07:49 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-07 07:52 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058#-:-Mb_SGci44_Z9ymBlFIE:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-09 05:13 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1058#-:-MbjBDLC9WBkpckRfFL5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-06-09 05:14 UTC, merged