tools: perf: new benchmarking scaffolding
pmem/rpma pull request #1065
Opened 2021-05-18 07:20 UTC by janekmi

2021-05-18 12:46 UTC, grom72 reviewed
> Reviewed 6 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-18 13:22 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 5 of 13 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/.gitignore, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zbvvY43YZANtOXRTK:-M_zbvvY43YZANtOXRTL:b-tjzlyg) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/.gitignore#L4)):*
> ```
> !report_bench.py
> ```
do we need ```report_``` prefix
___
*[tools/perf/.gitignore, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zc-xxDv-y-OozR4b2:-M_zc-xxDv-y-OozR4b3:b-1udvur) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/.gitignore#L6)):*
> ```
> !report_figures.py
> ```
.
___
*[tools/perf/config.json, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zceSu3hdwG2WkAHmb:-M_zceSu3hdwG2WkAHmc:b2fep9) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/config.json#L1)):*
> ```JSON
> {
> ```

any comment describing the purpose of this file?
```"_comment: This is a general description of this file ...",```
___
*[tools/perf/config.json, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zd0Hw13PD_2moIM1d:-M_zd0Hw13PD_2moIM1e:b-3fpm9y) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/config.json#L1)):*
> ```JSON
> {
> ```

do we need a license to be mentioned here?


<!-- Sent from Reviewable.io -->

2021-05-18 13:25 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/read.json, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zdPw-BGSEcP95WjWH:-M_zdPw-BGSEcP95WjWI:b-dhhmy7) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/figures/read.json#L22)):*
> ```
> "tool": "fio/rpma",
> ```
shall this be split into tool and tool_mode?


<!-- Sent from Reviewable.io -->

2021-05-18 13:53 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/.gitignore, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zbvvY43YZANtOXRTK:-M_zk-PK2NC2NQtGrsNN:ba7n43z) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/.gitignore#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> !report_bench.py
> ```
do we need ```report_``` prefix
</blockquote></details>

I like to have some kind of prefix because it nicely groups all tools working hand-in-hand. It is just useful.
___
*[tools/perf/.gitignore, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zc-xxDv-y-OozR4b2:-M_zkB_z9lUoptP04PC2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/.gitignore#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> !report_figures.py
> ```
.
</blockquote></details>

.
___
*[tools/perf/config.json, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zd0Hw13PD_2moIM1d:-M_zjA3gEoANfgaARdRP:bqwtdjp) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/config.json#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we need a license to be mentioned here?
</blockquote></details>

Nope. It is against the JSON standard.
___
*[tools/perf/figures/read.json, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zdPw-BGSEcP95WjWH:-M_zjKHT1YhXs_GSVyXZ:b14g72s) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/figures/read.json#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> "tool": "fio/rpma",
> ```
shall this be split into tool and tool_mode?
</blockquote></details>

It is only a shortcut for `rpma_fio_bench.sh`. I don't think so we will ever use from this level any other FIO engine, do you?


<!-- Sent from Reviewable.io -->

2021-05-18 13:57 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 5 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[tools/perf/config.json, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zceSu3hdwG2WkAHmb:-M_zl8wdBVpSmLmlJzk7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/config.json#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

any comment describing the purpose of this file?
```"_comment: This is a general description of this file ...",```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-18 14:39 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 5 of 13 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/config.json, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zceSu3hdwG2WkAHmb:-M_ztg-CAzTBVdYCFmDa:bxkf7qf) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/config.json#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```"_comment"``` - ```_``` as a prefix to indicate that it is metadata 
___
*[tools/perf/figures/read.json, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zdPw-BGSEcP95WjWH:-M_zu358BQw1kQESOeXA:b-ziby5j) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/figures/read.json#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is only a shortcut for `rpma_fio_bench.sh`. I don't think so we will ever use from this level any other FIO engine, do you?
</blockquote></details>

why we do not use the full tools name instead?


<!-- Sent from Reviewable.io -->

2021-05-18 14:42 UTC, grom72 reviewed
> Reviewed 1 of 13 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/.gitignore, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zbvvY43YZANtOXRTK:-M_zvExm5Hv1d6oGj-ib:biahamk) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/.gitignore#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like to have some kind of prefix because it nicely groups all tools working hand-in-hand. It is just useful.
</blockquote></details>

Let's talk when we have more files.


<!-- Sent from Reviewable.io -->

2021-05-18 14:45 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 7 of 13 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/figures/read.json, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zdPw-BGSEcP95WjWH:-M_zvVMx4x-uLo_y4HPu:bsxdrtm) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/figures/read.json#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why we do not use the full tools name instead?
</blockquote></details>

For simplicity's sake. It also makes this definition independent from the actual name of the tool and its location relative to this JSON file location and your current working directory.


<!-- Sent from Reviewable.io -->

2021-05-18 14:50 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 6 of 13 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/config.json, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zceSu3hdwG2WkAHmb:-M_zx9I46i6y0p9UjW-I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/config.json#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```"_comment"``` - ```_``` as a prefix to indicate that it is metadata 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-19 12:50 UTC, grom72 reviewed
> Reviewed 1 of 13 files at r1, 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/perf/figures/read.json, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zdPw-BGSEcP95WjWH:-Ma3f-FS6bxMSOINwYZm:b-1uw66s) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/figures/read.json#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For simplicity's sake. It also makes this definition independent from the actual name of the tool and its location relative to this JSON file location and your current working directory.
</blockquote></details>

It does not make the solution easy to follow.
And it requires a vocabulary that translates "key" to real tool name.


<!-- Sent from Reviewable.io -->

2021-05-19 22:57 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 6 of 15 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/figures/read.json, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1065#-M_zdPw-BGSEcP95WjWH:-Ma5q7uI3AoY2_c4ivqD:b-sd700b) ([raw file](https://github.com/pmem/rpma/blob/0ac6435deb6e75ee1761e28f48129f4d8e3cb8b2/tools/perf/figures/read.json#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It does not make the solution easy to follow.
And it requires a vocabulary that translates "key" to real tool name.
</blockquote></details>

Yes. Both approaches have pros and cons. Let's try your way. We will see how it will go.


<!-- Sent from Reviewable.io -->

2021-05-20 07:41 UTC, grom72 reviewed
> Reviewed 2 of 10 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 328 at r4](https://reviewable.io/reviews/pmem/rpma/1065#-Ma797BdDlD0tq_RjT8w:-Ma797BdDlD0tq_RjT8x:b-9rsf3w) ([raw file](https://github.com/pmem/rpma/blob/9bb981a11a72a579b90965ca7b7b7b4469974336/tools/perf/rpma_fio_bench.sh#L328)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 			# prepare output file name
> 			output_file=${OUTPUT_FILE-${OUTPUT[i]}}
> 			# convert to standardized-CSV/JSON
> 			./csv2standardized.py --csv_type fio --output_file $output_file ${OUTPUT[i]}
> 			if [ "$output_file" != "${OUTPUT[i]}" ]; then
> 				rm -f ${OUTPUT[i]}
> 			fi
> ```
</details>

Shall we split rpma_fio_bench into the old and new versions at this time?
Fio produces JSON output and the "standardization" process should be moved to a place where the "hash" file is created/updated


<!-- Sent from Reviewable.io -->

2021-05-20 09:41 UTC, grom72 reviewed
> Reviewed 1 of 13 files at r1, 3 of 10 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-20 10:41 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 9 of 15 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/rpma_fio_bench.sh, line 328 at r4](https://reviewable.io/reviews/pmem/rpma/1065#-Ma797BdDlD0tq_RjT8w:-Ma8LO6m2EOyYodYkPt7:brmeumw) ([raw file](https://github.com/pmem/rpma/blob/9bb981a11a72a579b90965ca7b7b7b4469974336/tools/perf/rpma_fio_bench.sh#L328)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			# prepare output file name
> 			output_file=${OUTPUT_FILE-${OUTPUT[i]}}
> 			# convert to standardized-CSV/JSON
> 			./csv2standardized.py --csv_type fio --output_file $output_file ${OUTPUT[i]}
> 			if [ "$output_file" != "${OUTPUT[i]}" ]; then
> 				rm -f ${OUTPUT[i]}
> 			fi
> ```
Shall we split rpma_fio_bench into the old and new versions at this time?
Fio produces JSON output and the "standardization" process should be moved to a place where the "hash" file is created/updated
</blockquote></details>

The standardization process has to take place at the level of benchmarking tools (both `rpma_fio_bench.sh` and `ib_read.lat`) because otherwise, these tools won't be standalone anymore. Because processing their results (without involving any other tools we are introducing in this PR) will be a mess where the user has to know the schema of an output they have generated. Whereas now there is one schema to rule them all.


<!-- Sent from Reviewable.io -->

2021-05-21 04:40 UTC, grom72 reviewed
> Reviewed 1 of 13 files at r1, 3 of 10 files at r3, 2 of 3 files at r4, 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/Figure.py, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1065#-MaCDHy20CLtk_bkA1C5:-MaCDHy327V5m6CGBp2i:bgren5i) ([raw file](https://github.com/pmem/rpma/blob/8ef19e8ab8129081578c9d2066d4b898ce6343d8/tools/perf/lib/Figure.py#L21)):*
> ```
>     _figure_kwargs = {'figsize': [6.4, 4.8], 'dpi': 200, \
>         'tight_layout': {'pad': 6}}
> ```
Should it be a part of some configuration file?


<!-- Sent from Reviewable.io -->

2021-05-21 18:29 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/Figure.py, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1065#-MaCDHy20CLtk_bkA1C5:-MaFB2db71__7An3fn-W:b-2qn4d9) ([raw file](https://github.com/pmem/rpma/blob/8ef19e8ab8129081578c9d2066d4b898ce6343d8/tools/perf/lib/Figure.py#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>     _figure_kwargs = {'figsize': [6.4, 4.8], 'dpi': 200, \
>         'tight_layout': {'pad': 6}}
> ```
Should it be a part of some configuration file?
</blockquote></details>

Maybe someday.


<!-- Sent from Reviewable.io -->

2021-05-24 12:37 UTC, grom72 reviewed
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-26 12:59 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065#-:-MackLNTAG7TBt2o3DmE:bnfp4nl)* status: 14 of 16 files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-05-28 09:29 UTC, janekmi commented
@ldorau

2021-05-31 11:01 UTC, ldorau requested changes
> Reviewed 1 of 13 files at r1, 2 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/perf/config.json, line 6 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb14EjS4yBrE7M4tKre:-Mb14EjS4yBrE7M4tKrf:bfrmwr6) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/config.json#L6)):*
> ```
>  "XXX": "XXX"
> ```

Is it necessary here? Maybe add a comment?


<!-- Sent from Reviewable.io -->

2021-05-31 11:22 UTC, ldorau reviewed
> Reviewed 2 of 13 files at r1, 4 of 10 files at r3, 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-31 11:56 UTC, ldorau requested changes
> Reviewed 2 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 12 of 16 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/Figure.py, line 8 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1AUAu3LseeePYSPEu:-Mb1AUAu3LseeePYSPEv:b-ra30hv) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L8)):*
> ```
> generating a figure related products 
> ```

generate figure related products 
___
*[tools/perf/lib/Figure.py, line 59 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1GbvU5_sc13MWCDwC:-Mb1GbvU5_sc13MWCDwD:b3rxgul) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L59)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>         """Flatten the descriptors list to a list of figures"""
>         # - Prepare an empty set B == all benchmarks to be run
>         # - Loop over all figure files provided
>         #     - Loop over all figures in each of the files
>         #         - Loop over all possible combinations of layout and arg_axis
>         #             - Generate output_title and output_file (if required)
>         #             - Generate filter (if required)
>         #             - Loop over all data points defined for the figure
>         #                 - Create all possible combinations of the data point keys
>         #                 - Loop over all data combinations
>         #                     - Populate the B set
> ```
</details>


Is it all being done only by this one instruction `output.append(cls(f))` ?
What library does `append()` come from?


<!-- Sent from Reviewable.io -->

2021-05-31 12:04 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 12 of 16 files reviewed, 10 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/Figure.py, line 67 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1H7V-32gQ3phCzl3L:-Mb1H7V-32gQ3phCzl3M:b-fzc87e) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L67)):*
> ```
>  and store
> ```

store what and where? I do not understand ...
___
*[tools/perf/lib/Figure.py, line 77 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1HU-g4MtKo2ejctQ8:-Mb1HU-g4MtKo2ejctQ9:b-ia7cbx) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L77)):*
> ```
> rows[0]
> ```

Should it always be `0`?
___
*[tools/perf/lib/Figure.py, line 93 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1Huk44h19f0nlfumM:-Mb1Huk44h19f0nlfumN:b-52vuuk) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L93)):*
> ```
> output['done']
> ```

Where is `output['done']` defined ?
___
*[tools/perf/lib/Figure.py, line 101 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1IBcJ9wk45LMdKk3T:-Mb1IBcJ9wk45LMdKk3U:b6i1zhg) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L101)):*
> ```
>         # XXX
>         return arg
> ```

What should be here? Please add a comment.
___
*[tools/perf/lib/Figure.py, line 107 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1INag1uz3QXn1tRCD:-Mb1INag1uz3QXn1tRCE:b-ttdfrz) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L107)):*
> ```
> suptitle
> ```

Do you mean `subtitle`?
___
*[tools/perf/lib/Figure.py, line 108 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1IXXaCY-pxjSf3nZI:-Mb1IXXaCY-pxjSf3nZJ:b-8i04u3) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L108)):*
> ```
> suptitle(suptitle
> ```

.
___
*[tools/perf/lib/Figure.py, line 137 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1Is4U2NDCorNrUh1b:-Mb1Is4U2NDCorNrUh1c:b6k9b0l) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L137)):*
> ```
>     def to_html(self, result_dir):
>         # XXX
>         pass
> ```

What should be here? Please add a comment.


<!-- Sent from Reviewable.io -->

2021-05-31 12:49 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 9 of 16 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/Figure.py, line 8 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1AUAu3LseeePYSPEu:-Mb1NXWfClQp5t3nvaRE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> generating a figure related products 
> ```

generate figure related products 
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 59 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1GbvU5_sc13MWCDwC:-Mb1O1D66DbKOYQPJpHW:b-gxxo97) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         """Flatten the descriptors list to a list of figures"""
>         # - Prepare an empty set B == all benchmarks to be run
>         # - Loop over all figure files provided
>         #     - Loop over all figures in each of the files
>         #         - Loop over all possible combinations of layout and arg_axis
>         #             - Generate output_title and output_file (if required)
>         #             - Generate filter (if required)
>         #             - Loop over all data points defined for the figure
>         #                 - Create all possible combinations of the data point keys
>         #                 - Loop over all data combinations
>         #                     - Populate the B set
> ```

Is it all being done only by this one instruction `output.append(cls(f))` ?
What library does `append()` come from?
</blockquote></details>

Nope. Most of these are provided by another PR: https://github.com/pmem/rpma/pull/1068

The `output` list is a simple built-in Python list: https://docs.python.org/3/tutorial/datastructures.html#more-on-lists
___
*[tools/perf/lib/Figure.py, line 67 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1H7V-32gQ3phCzl3L:-Mb1P_KA4wrMfQg7jq1P:b-uohjwt) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  and store
> ```

store what and where? I do not understand ...
</blockquote></details>

Done.

How about now?
___
*[tools/perf/lib/Figure.py, line 77 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1HU-g4MtKo2ejctQ8:-Mb1Q3ik0OcDR_jrxLcQ:b-yz7iuv) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rows[0]
> ```

Should it always be `0`?
</blockquote></details>

Please see the comment for the explanation.
___
*[tools/perf/lib/Figure.py, line 93 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1Huk44h19f0nlfumM:-Mb1QfQZ1wpt6sisfAKH:b-30qa0e) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> output['done']
> ```

Where is `output['done']` defined ?
</blockquote></details>

In line 28.
___
*[tools/perf/lib/Figure.py, line 101 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1IBcJ9wk45LMdKk3T:-Mb1RP89B3LzjmRYS5ah:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         # XXX
>         return arg
> ```

What should be here? Please add a comment.
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 107 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1INag1uz3QXn1tRCD:-Mb1RZeeDnnz6UY4UEIP:bbpi39d) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> suptitle
> ```

Do you mean `subtitle`?
</blockquote></details>

Nope. This is exactly what I meant. Please see the reference below.
___
*[tools/perf/lib/Figure.py, line 108 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1IXXaCY-pxjSf3nZI:-Mb1RYH3DpQyR4TgHX9Z:bbmfu35) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> suptitle(suptitle
> ```

.
</blockquote></details>

Ref: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.suptitle.html
___
*[tools/perf/lib/Figure.py, line 137 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1Is4U2NDCorNrUh1b:-Mb1SYYP-WxZTShmm2Pf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     def to_html(self, result_dir):
>         # XXX
>         pass
> ```

What should be here? Please add a comment.
</blockquote></details>

Done.
___
*[tools/perf/config.json, line 6 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb14EjS4yBrE7M4tKre:-Mb1NKIJ82z2AQBI53Q5:b-gdj8nj) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/config.json#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "XXX": "XXX"
> ```

Is it necessary here? Maybe add a comment?
</blockquote></details>

Done.

It is a comment JSON standard allows.


<!-- Sent from Reviewable.io -->

2021-05-31 13:18 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 10 of 16 files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/report_bench.py, line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1YimM7Y9cevozjkzY:-Mb1YimN-bxpU4IDPyQQ:b41vjgx) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/report_bench.py#L23)):*
> ```
> # Python >= 3.7 accepts 'required' kwarg. For older versions, it is validated
> # manually.
> subparsers.require = True
> ```

`require` or `required` ? - there are both versions here
___
*[tools/perf/report_bench.py, line 24 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1YrA89r-j-CSaunbI:-Mb1YrA89r-j-CSaunbJ:b72tfae) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/report_bench.py#L24)):*
> ```
> a fresh benchmark
> ```

a new benchmark ? E.g. vegetables can be fresh ;-)
___
*[tools/perf/report_bench.py, line 28 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1ZPDfDJD2v0ycPnIx:-Mb1ZPDfDJD2v0ycPnIy:b-77fn77) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/report_bench.py#L28)):*
> ```
> ... to perform
> ```

... to be run? 


<!-- Sent from Reviewable.io -->

2021-05-31 13:29 UTC, ldorau requested changes
> Reviewed 2 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 12 of 16 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/Figure.py, line 8 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1AUAu3LseeePYSPEu:-Mb1ZrA73z7mYFO83_JA:b-7epktf) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not all yet, the undefined article `a` cannot be used in plural.
___
*[tools/perf/lib/Figure.py, line 59 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1GbvU5_sc13MWCDwC:-Mb1_NKq3TW6T91sYRht:b-feo69g) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope. Most of these are provided by another PR: https://github.com/pmem/rpma/pull/1068

The `output` list is a simple built-in Python list: https://docs.python.org/3/tutorial/datastructures.html#more-on-lists
</blockquote></details>

I see, so it is a kind of a TODO list ... I didn't notice `XXX` ...
___
*[tools/perf/lib/Figure.py, line 67 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1H7V-32gQ3phCzl3L:-Mb1_kB40njY3M163gW6:b-8pczgr) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.

How about now?
</blockquote></details>

It is OK now, thanks
___
*[tools/perf/lib/Figure.py, line 77 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1HU-g4MtKo2ejctQ8:-Mb1_q0480eTBUMH5gtQ:bdaqdn5) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please see the comment for the explanation.
</blockquote></details>

OK, but `each row HAS ...`
___
*[tools/perf/lib/Figure.py, line 93 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1Huk44h19f0nlfumM:-Mb1aBZMAaNTEJqVzTit:blw2ri9) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In line 28.
</blockquote></details>

Ah, I haven't got used to Python's definitions yet ;-)
___
*[tools/perf/lib/Figure.py, line 101 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1IBcJ9wk45LMdKk3T:-Mb1aPWHA_eJsGkuz80x:b6x97de) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`a unit` (because it is pronounced like 'junit')


<!-- Sent from Reviewable.io -->

2021-05-31 13:36 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 10 of 16 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/report_bench.py, line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1YimM7Y9cevozjkzY:-Mb1b8uI10dlp8Ni-_iu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/report_bench.py#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # Python >= 3.7 accepts 'required' kwarg. For older versions, it is validated
> # manually.
> subparsers.require = True
> ```

`require` or `required` ? - there are both versions here
</blockquote></details>

Done.
___
*[tools/perf/report_bench.py, line 24 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1YrA89r-j-CSaunbI:-Mb1bGs2EGNu2Z5__1K9:bg88v8p) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/report_bench.py#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a fresh benchmark
> ```

a new benchmark ? E.g. vegetables can be fresh ;-)
</blockquote></details>

Haha. Growing benchmarks like vegetables.

Done.
___
*[tools/perf/report_bench.py, line 28 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1ZPDfDJD2v0ycPnIx:-Mb1c83X9XbET5hKnII8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/report_bench.py#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ... to perform
> ```

... to be run? 
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 8 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1AUAu3LseeePYSPEu:-Mb1cHHE0OuhUkg9BaOM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not all yet, the undefined article `a` cannot be used in plural.
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 59 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1GbvU5_sc13MWCDwC:-Mb1cJd00Rxk-SDOKyX1:bj2fuq0) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I see, so it is a kind of a TODO list ... I didn't notice `XXX` ...
</blockquote></details>

Because I have just added it. ;-)
___
*[tools/perf/lib/Figure.py, line 77 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1HU-g4MtKo2ejctQ8:-Mb1cdznEw3xvxsnY-ws:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, but `each row HAS ...`
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 101 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1IBcJ9wk45LMdKk3T:-Mb1coNzB5yKGY-cL3IA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`a unit` (because it is pronounced like 'junit')
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-31 13:40 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r6, 1 of 3 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/Figure.py, line 59 at r7](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1GbvU5_sc13MWCDwC:-Mb1dXpaEJwQMa6Ve4J8:b2nh4jw) ([raw file](https://github.com/pmem/rpma/blob/5f762b4bb607a6fbca952f40255e222d1b31e11c/tools/perf/lib/Figure.py#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Because I have just added it. ;-)
</blockquote></details>

:-D
___
*[tools/perf/lib/Requirement.py, line 97 at r8](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1d5kmBRaVBOHcgPIH:-Mb1d5kmBRaVBOHcgPII:b-cuy01i) ([raw file](https://github.com/pmem/rpma/blob/6b05ea479a7735ee6abfaa59d39ac6db22b994f6/tools/perf/lib/Requirement.py#L97)):*
> ```
>             ctx.cache()
>         self.req['done'] = True
>         ctx.cache()
> ```

Could you add a comment explaining what `ctx.cache()` is doing?


<!-- Sent from Reviewable.io -->

2021-05-31 13:59 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/Benchmark.py, line 38 at r8](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1h_ca615J2uDAEV1U:-Mb1h_cb83wAmpfoCW3L:bpqe5nc) ([raw file](https://github.com/pmem/rpma/blob/6b05ea479a7735ee6abfaa59d39ac6db22b994f6/tools/perf/lib/Benchmark.py#L38)):*
> ```
> instance specific
> ```

`instance-specific`
___
*[tools/perf/lib/Benchmark.py, line 61 at r8](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1hsYL8a4MnEj2hU1v:-Mb1hsYL8a4MnEj2hU1w:btpgo0) ([raw file](https://github.com/pmem/rpma/blob/6b05ea479a7735ee6abfaa59d39ac6db22b994f6/tools/perf/lib/Benchmark.py#L61)):*
> ```
>     def set_requirements(self):
>         return self.req
> ```

It does not set, but it gets the requirement.


<!-- Sent from Reviewable.io -->

2021-05-31 14:00 UTC, ldorau reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065#-:-Mb1iOIjC8y5cIKVbm6S:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-31 14:19 UTC, ldorau reviewed
> Reviewed 4 of 5 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-31 14:19 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/lib/Benchmark.py, line 38 at r8](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1h_ca615J2uDAEV1U:-Mb1iifP6yC7u-klm491:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b05ea479a7735ee6abfaa59d39ac6db22b994f6/tools/perf/lib/Benchmark.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> instance specific
> ```

`instance-specific`
</blockquote></details>

Done.
___
*[tools/perf/lib/Benchmark.py, line 61 at r8](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1hsYL8a4MnEj2hU1v:-Mb1j3mj2NOXPVcJ-HW4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b05ea479a7735ee6abfaa59d39ac6db22b994f6/tools/perf/lib/Benchmark.py#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     def set_requirements(self):
>         return self.req
> ```

It does not set, but it gets the requirement.
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 97 at r8](https://reviewable.io/reviews/pmem/rpma/1065#-Mb1d5kmBRaVBOHcgPIH:-Mb1mn8L3LlepFjv4Ml0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b05ea479a7735ee6abfaa59d39ac6db22b994f6/tools/perf/lib/Requirement.py#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             ctx.cache()
>         self.req['done'] = True
>         ctx.cache()
> ```

Could you add a comment explaining what `ctx.cache()` is doing?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-31 14:21 UTC, ldorau reviewed
Something is wrong with the `config.json` file - I cannot mark it as reviewed.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065#-:-Mb1n9OuDKH4JKNoIooJ:b262c8p)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-31 14:21 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1065#-:-Mb1nL1b7ESwvkE3c3AS:bnfp4nl)* status: 16 of 17 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-05-31 14:28 UTC, merged