Update txt2man version requirement in INSTALL.md
pmem/rpma pull request #1070
Opened 2021-05-26 02:19 UTC by mengxinayan

Hello.

I found when txt2man == 1.7.1 rpma can works, while txt2man == 1.7.0 it cause errors in `make` process. See issue #1069 for details.

So I update txt2man version requirement in INSTALL.md.

Thanks!

2021-06-11 07:33 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1070#-:-MbtzOhFBUGKbhjisVQ_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mengxinayan)



<!-- Sent from Reviewable.io -->

2021-06-11 08:30 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1070)* status: all files reviewed, 1 unresolved discussion (waiting on @mengxinayan)

___
*[INSTALL.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1070#-Mbu8tKh8pE3mNCcFzsn:-Mbu8tKh8pE3mNCcFzso:b-5bm6r2) ([raw file](https://github.com/pmem/rpma/blob/077bf93843795574bd2331d72581e516fe32c406/INSTALL.md#L21)):*
> ```Markdown
> - find
> - groff
> - txt2man >= 1.7.0 (please see https://github.com/pmem/rpma/blob/master/utils/docker/images/install-txt2man.sh to install the verified revision)
> ```

1. The issue does not reproduce on another Ubuntu 20.04: https://github.com/pmem/rpma/runs/2798685748?check_suite_focus=true so we need to understand deeper what are the conditions required for the issue to reproduce.
2. If we agree the fix is to upgrade the txt2man to 1.7.1 the correct PR will be `txt2man == 1.7.1` + you have to change it here: https://github.com/pmem/rpma/blob/master/utils/docker/images/install-txt2man.sh so the solution will be applied across our CIs.


<!-- Sent from Reviewable.io -->

2021-06-11 08:32 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1070)* status: all files reviewed, 1 unresolved discussion (waiting on @mengxinayan)

___
*[INSTALL.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1070#-Mbu8tKh8pE3mNCcFzsn:-MbuBecr72HUZH0tbiBR:bo7a9p7) ([raw file](https://github.com/pmem/rpma/blob/077bf93843795574bd2331d72581e516fe32c406/INSTALL.md#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. The issue does not reproduce on another Ubuntu 20.04: https://github.com/pmem/rpma/runs/2798685748?check_suite_focus=true so we need to understand deeper what are the conditions required for the issue to reproduce.
2. If we agree the fix is to upgrade the txt2man to 1.7.1 the correct PR will be `txt2man == 1.7.1` + you have to change it here: https://github.com/pmem/rpma/blob/master/utils/docker/images/install-txt2man.sh so the solution will be applied across our CIs.
</blockquote></details>

Thank you @grom72  for your insight. ;-)


<!-- Sent from Reviewable.io -->

2021-06-11 08:54 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1070)* status: all files reviewed, 1 unresolved discussion (waiting on @mengxinayan)



<!-- Sent from Reviewable.io -->

2021-06-15 06:22 UTC, mengxinayan commented
Thanks, I know which file to change if fix it. But we should know the deeper condition for it firstly.

2021-07-08 11:00 UTC, ldorau reviewed
@mengxinayan   Which file? Any update?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1070#-:-Me4l4tREUX6Ew_bgENr:b-3w8s7c)* status: all files reviewed, 1 unresolved discussion (waiting on @mengxinayan)



<!-- Sent from Reviewable.io -->

2021-07-26 16:37 UTC, janekmi commented
@mengxinayan I will be happy to reopen this PR when we will have more knowledge about the root cause. Closing for now.

2021-07-26 16:37 UTC, closed without merging