implement separate recviving CQ
pmem/rpma pull request #1080
Opened 2021-06-03 12:53 UTC by yangx-jy

2021-06-11 09:42 UTC, janekmi requested changes
> Reviewed 23 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 7 of 59 files reviewed, 10 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 258 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuJf7xDSvDs4x8b9Ob:-MbuJf7xDSvDs4x8b9Oc:bv5bhw6) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L258)):*
> ```C
> 	rdma_destroy_qp(conn->id);
> 
> 	ret = rpma_cq_delete(&conn->rcq);
> ```

`cq` first before `rcq`.
___
*[src/conn.c, line 479 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKGKKAuu7hmpB5iEJ:-MbuKGKKAuu7hmpB5iEK:b-u0uhiq) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L479)):*
> ```C
> 
> /*
>  * rpma_conn_get_cq -- get a rpma_cq object from the connection
> ```

get the connection's send CQ
___
*[src/conn.c, line 493 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKcnv5cruGMTIIcci:-MbuKcnv5cruGMTIIccj:baqf8cj) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L493)):*
> ```C
> 
> /*
>  * rpma_conn_get_rcq -- get a receiving rpma_cq object from the connection
> ```

get the connection's receive CQ
___
*[src/conn_cfg.c, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuOA66BCkNhX6-vkGV:-MbuOA67-sdtVruKdH7G:bkp16dn) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L62)):*
> ```C
> 
> /*
>  * Round down the cq_size when it is too big for storing
> ```

```c
/*
 * rpma_conn_cfg... -- ...
```
___
*[src/conn_cfg.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuNiRACyt1VPjtFiah:-MbuNiRACyt1VPjtFiai:brukviw) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L65)):*
> ```C
>  * into an int type of value. Convert otherwise.
>  */
> static int rpma_round_down_size(uint32_t size)
> ```

```c
static int
rpma_conn_cfg_...
```
___
*[src/conn_cfg.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuOZpz7bal7aaJeAtV:-MbuOZpz7bal7aaJeAtW:bjr3uea) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L71)):*
> ```C
> 
> 	return (int)size;
> }
> ```

It is not on the internal API of this unit so it should go above the internal API boundary.

TBH I think it may be an even better fit into `common.h` as a simple macro? Up to you.
___
*[src/conn_cfg.c, line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuP6DD7wkMOCQF9IvW:-MbuP6DD7wkMOCQF9IvX:b12wt79) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L78)):*
> ```C
>  */
> int
> rpma_conn_cfg_get_cqe(const struct rpma_conn_cfg *cfg, int *cqe, int *recv_cqe)
> ```

I know it is tiresome to have getters and setters for each of the fields separately but I believe it makes the API easier to maintain in the future. The `rpma_conn_cfg_get_cqe()` function is a variant of `rpma_conn_cfg_get_cq_size()` and I think it should stay this way. Instead, I think you should introduce something like `rpma_conn_cfg_get_rcqe()` (following the naming conventions).
___
*[src/cq.c, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu1TgVAcMIy8ZUuZ8g:-Mbu1TgVAcMIy8ZUuZ8h:b2a6t5o) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/cq.c#L165)):*
> ```C
> {
> 	return cq->cq;
> }
> ```

We tend to keep the internal API calls first in the *.c files before the public API.
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQPfs0IBlfYgd41ZW:-MbuQPfs0IBlfYgd41ZX:b-sh6msu) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, 0);
> 	assert_ptr_equal(rcq, NULL);
> ```

You are missing a test case when `rcq != NULL`.
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQW_u39xlrMpEYf-Y:-MbuQW_u39xlrMpEYf-Z:b-48h6ls) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, 0);
> 	assert_ptr_equal(rcq, NULL);
> ```

I see you have assumed when the rcq_size == 0 the separate CQ for receives does not exist so the `_get_rcq()` will return NULL.
I am considering an alternative proposition when`_get_rcq()` returns a CQ for receives no matter if it is created separate or it is common with sends.
What do you think?


<!-- Sent from Reviewable.io -->

2021-06-11 10:27 UTC, janekmi requested changes
> Reviewed 15 of 59 files at r1, 16 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 38 of 59 files reviewed, 26 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/common/mocks-rpma-conn.c, line 27 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuYUng66CFb4XCJc-f:-MbuYUnh7ivweouHKe4Y:b-hg4ljm) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-conn.c#L27)):*
> ```C
> 	check_expected_ptr(id);
> 	assert_ptr_equal(cq, MOCK_RPMA_CQ);
> 	assert_true(rcq == MOCK_RPMA_CQ || rcq == NULL);
> ```

I believe such an assertion is too wide. This way you have no way to distinguish and validate both cases. You can use `mock_type(struct rpma_cq *)` or any other technique we have already used.
___
*[tests/unit/common/mocks-rpma-conn_cfg.h, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuUZEu-r6YlhQCYzuG:-MbuUZEu-r6YlhQCYzuH:b2nicts) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-conn_cfg.h#L16)):*
> ```objc
> #define MOCK_CONN_CFG_CUSTOM	(struct rpma_conn_cfg *)0xCF6C
> 
> #define MOCK_RCQ_SIZE_DEFAULT   0
> ```

tab
___
*[tests/unit/common/mocks-rpma-conn_cfg.h, line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuUa-E0MpsMevPosf4:-MbuUa-E0MpsMevPosf5:b-3c4n2t) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-conn_cfg.h#L17)):*
> ```objc
> 
> #define MOCK_RCQ_SIZE_DEFAULT   0
> #define MOCK_CQ_SIZE_DEFAULT	10
> ```

I want to keep the order: CQ, RCQ.
___
*[tests/unit/common/mocks-rpma-conn_cfg.h, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuUnPN4rC0qdOM75ql:-MbuUnPN4rC0qdOM75qm:bijneac) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-conn_cfg.h#L22)):*
> ```objc
> 
> #define MOCK_TIMEOUT_MS_CUSTOM	4034
> #define MOCK_RCQ_SIZE_CUSTOM    12
> ```

== MOCK_RQ_SIZE_DEFAULT. Please reassign the values to make them unique across the board.
___
*[tests/unit/common/mocks-rpma-conn_cfg.h, line 23 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuUiNSBBqnLF-CujeH:-MbuUiNSBBqnLF-CujeI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-conn_cfg.h#L23)):*
> ```objc
> #define MOCK_TIMEOUT_MS_CUSTOM	4034
> #define MOCK_RCQ_SIZE_CUSTOM    12
> #define MOCK_CQ_SIZE_CUSTOM	13
> ```

.
___
*[tests/unit/common/mocks-rpma-cq.c, line 91 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuZ6ZPA5RblgdeK3In:-MbuZ6ZPA5RblgdeK3Io:bxv144h) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-cq.c#L91)):*
> ```C
> 
> 	struct rpma_cq *cq = *cq_ptr;
> 	assert_true(cq == MOCK_RPMA_CQ || cq == MOCK_RPMA_RCQ || cq == NULL);
> ```

Too permissive. Please use e.g. `mock_type()`.
___
*[tests/unit/common/mocks-rpma-cq.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuZGDaBaNnHC2soZRm:-MbuZGDaBaNnHC2soZRn:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-cq.c#L109)):*
> ```C
> rpma_cq_get_ibv_cq(const struct rpma_cq *cq)
> {
> 	assert_true(cq == MOCK_RPMA_CQ || cq == MOCK_RPMA_RCQ);
> ```

.
___
*[tests/unit/common/mocks-rpma-peer.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuZMLcDz-LaPXtCoh7:-MbuZMLcDz-LaPXtCoh8:byogydn) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/common/mocks-rpma-peer.c#L22)):*
> ```C
> int
> rpma_peer_create_qp(struct rpma_peer *peer, struct rdma_cm_id *id,
> 		struct rpma_cq *cq, struct rpma_cq *rcq,
> ```

The validation is missing.
___
*[tests/unit/conn/conn-new.c, line 319 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_8YFEaCBxieYG79e:-Mbu_8YFEaCBxieYG79f:bgzffxl) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-new.c#L319)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	will_return(rpma_cq_delete, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_delete, EAGAIN);
> ```

MOCK_ERRNO?
___
*[tests/unit/conn/conn-new.c, line 353 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_EYbCgAPtBeDgQ0P:-Mbu_EYbCgAPtBeDgQ0Q:bgzffxl) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-new.c#L353)):*
> ```C
> 	will_return(rpma_cq_delete, MOCK_OK);
> 	will_return(rpma_cq_delete, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_delete, EAGAIN);
> ```

MOCK_ERRNO?
___
*[tests/unit/conn/conn-new.c, line 387 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_UGeDjDxzPdKAHvg:-Mbu_UGeDjDxzPdKAHvh:bgzffxl) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-new.c#L387)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	will_return(rpma_cq_delete, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_delete, EAGAIN); /* first error */
> ```

MOCK_ERRNO?
___
*[tests/unit/conn/conn-new.c, line 389 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_W1X3mGUsi_cun-O:-Mbu_W1X3mGUsi_cun-P:btaibtv) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-new.c#L389)):*
> ```C
> 	will_return(rpma_cq_delete, EAGAIN); /* first error */
> 	will_return(rpma_cq_delete, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_delete, EIO); /* second error */
> ```

MOCK_ERRNO2?
___
*[tests/unit/conn/conn-new.c, line 391 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_Z6c9dijOy6ZiPVW:-Mbu_Z6c9dijOy6ZiPVX:btaibtv) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-new.c#L391)):*
> ```C
> 	will_return(rpma_cq_delete, EIO); /* second error */
> 	expect_value(rdma_destroy_id, id, MOCK_CM_ID);
> 	will_return(rdma_destroy_id, EIO); /* third error */
> ```

MOCK_ERRNO2?
___
*[tests/unit/conn_cfg/CMakeLists.txt, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_wu5-54InoksVq7N:-Mbu_wu5-54InoksVq7O:b4nehfw) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_cfg/CMakeLists.txt#L31)):*
> ```CMake
> add_test_conn_cfg(new)
> add_test_conn_cfg(rcq_size)
> add_test_conn_cfg(rq_size)
> ```

I believe the alphabetical order is:
- rq_size
- rcq_size
___
*[tests/unit/conn_req/conn_req-common.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbuam4i6x67QrsJ_gqr:-Mbuam4i6x67QrsJ_gqs:b-frwkkw) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-common.c#L22)):*
> ```C
> prestate_init(struct conn_req_new_test_state *prestate,
> 		struct rpma_conn_cfg *cfg, int timeout_ms,
> 		uint32_t cq_size, uint32_t rcq_size)
> ```

cq_size should still be in the previous line.
___
*[tests/unit/cq/cq-new_delete.c, line 203 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuWrLo7wN3V1jACMXa:-MbuWrLo7wN3V1jACMXb:b-sexnd3) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/cq/cq-new_delete.c#L203)):*
> ```C
> 
> 	/* run test */
> 	int ret = rpma_cq_delete(&cq);
> ```

You are missing the case when cq_ptr == NULL.


<!-- Sent from Reviewable.io -->

2021-06-11 10:34 UTC, janekmi requested changes
> Reviewed 1 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 39 of 59 files reviewed, 27 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/peer/peer-create_qp.c, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbubf1y9yE53N5CWoY2:-Mbubf1y9yE53N5CWoY3:bwcn7jd) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/peer/peer-create_qp.c#L40)):*
> ```C
> 
> static void
> setup_create_qp(struct rpma_cq *rcq)
> ```

Since setup/teardown are reserved for the cmocka steps I think the right word here is `configure_create_qp`.


<!-- Sent from Reviewable.io -->

2021-06-11 10:37 UTC, janekmi reviewed
> Reviewed 1 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 40 of 59 files reviewed, 22 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-06-11 10:53 UTC, janekmi reviewed
> Reviewed 4 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 44 of 59 files reviewed, 22 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-06-11 12:52 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 44 of 59 files reviewed, 23 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv763S1NPNwzVuDN0Q:-Mbv763S1NPNwzVuDN0R:b-7q8tga) (no related file):*
You should merge these two PRs:
- rpma: implement separate receiving CQ 
- test: add and refactor unit tests for seperate receiving CQ

By modifying code without changing the tests you making bisection impossible.

---


<!-- Sent from Reviewable.io -->

2021-06-11 14:11 UTC, janekmi requested changes
> Reviewed 9 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 53 of 59 files reviewed, 33 unresolved discussions (waiting on @yangx-jy)

___
*[src/conn_req.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv84MV4cwaRipAwwWJ:-Mbv84MV4cwaRipAwwWK:b-ihu68b) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/conn_req.c#L204)):*
> ```C
> 		ret = rpma_cq_delete(&req->cq);
> 	else
> 		(void) rpma_cq_delete(&req->cq);
> ```

```
	int ret2;

	int ret = rpma_cq_delete(&req->rcq);
	if ((ret2 = rpma_cq_delete(&req->cq)) {
		if (!ret)
			ret = ret2;
	}
```
___
*[src/conn_req.c, line 239 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv8PRbA0EOS8L4-9nA:-Mbv8PRcEAAt6bx0sOfv:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/conn_req.c#L239)):*
> ```C
> 		ret = rpma_cq_delete(&req->cq);
> 	else
> 		(void) rpma_cq_delete(&req->cq);
> ```

.
___
*[src/peer.c, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv8YAJ5Fx_JsQ8BoMT:-Mbv8YAK7nzUss5XLC36:b-3axcsp) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/peer.c#L112)):*
> ```C
> 	qp_init_attr.qp_context = NULL;
> 	qp_init_attr.send_cq = ibv_cq;
> 	qp_init_attr.recv_cq = ibv_rcq ? ibv_rcq : ibv_cq;
> ```

```c
... = rcq ? rpma_cq_get_ibv_cq(rcq) : ibv_cq;
```
___
*[tests/unit/conn_req/conn_req-delete.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvCY4M9ZFL-45Lm1rW:-MbvCY4M9ZFL-45Lm1rX:b-l10ocb) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-delete.c#L77)):*
> rpma_cq_delete(&req->cq) return RPMA_E_PROVIDER whereas rdma_ack_cm_event() and rdma_reject() fail with EIO after rpma_cq_delete(&req->rcq) returned RPMA_E_PROVIDER (a fail with EAGAIN)

I know, a little bit complicated.
___
*[tests/unit/conn_req/conn_req-delete.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvELA8EOzunUOCR5nO:-MbvELA8EOzunUOCR5nP:b9z83ii) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-delete.c#L106)):*
> ```C
> 	assert_null(cstate->req);
> }
> ```

You are missing here two cases for the delete_via_reject:

- when the second rpma_cq_delete() fail + all subsequent pass
- when the second rpma_cq_delete() fail + all subsequent fail
___
*[tests/unit/conn_req/conn_req-delete.c, line 227 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvDQiUCjdJll4eHsNm:-MbvDQiUCjdJll4eHsNn:bcew3gv) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-delete.c#L227)):*
> rpma_cq_delete(&req->rcq) returns RPMA_E_PROVIDER whereas rdma_destroy_id() fails with EIO after rpma_cq_delete(&req->cq) returned RPMA_E_PROVIDER (a fail with EAGAIN)
___
*[tests/unit/conn_req/conn_req-delete.c, line 253 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvHA0d-R-UxK38YUyY:-MbvHA0d-R-UxK38YUyZ:b6ywwsx) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-delete.c#L253)):*
> ```C
> 	assert_int_equal(ret, RPMA_E_PROVIDER);
> 	assert_null(cstate->req);
> }
> ```

You are missing here two cases for the delete_via_destroy:

- when the second rpma_cq_delete() fail + all subsequent pass
- when the second rpma_cq_delete() fail + all subsequent fail
___
*[tests/unit/conn_req/conn_req-delete.c, line 308 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvHIts48nSQo0A35TV:-MbvHIts48nSQo0A35TW:bx0nelp) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-delete.c#L308)):*
> ```C
> 	prestate_init(&prestate_conn_cfg_default, MOCK_CONN_CFG_DEFAULT,
> 			RPMA_DEFAULT_TIMEOUT_MS, MOCK_CQ_SIZE_DEFAULT,
> 			MOCK_RCQ_SIZE_DEFAULT);
> ```

Having the default RCQ size will cause the receive CQ to be nonexistent, am I right?
___
*[tests/unit/conn_req/conn_req-delete.c, line 308 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvHYXL-oofaYsn-tdD:-MbvHYXL-oofaYsn-tdE:b9sb27d) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-delete.c#L308)):*
> ```C
> 	prestate_init(&prestate_conn_cfg_default, MOCK_CONN_CFG_DEFAULT,
> 			RPMA_DEFAULT_TIMEOUT_MS, MOCK_CQ_SIZE_DEFAULT,
> 			MOCK_RCQ_SIZE_DEFAULT);
> ```

We have to think if we need all of these to run in two flavours:
- without the RCQ
- with the RCQ
___
*[tests/unit/conn_req/conn_req-new.c, line 386 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvOlTm4h3G9m4NuoYu:-MbvOlTm4h3G9m4NuoYv:b69kckh) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_req/conn_req-new.c#L386)):*
> ```C
> 	will_return(__wrap__test_malloc, ENOMEM); /* first error */
> 	expect_value(rdma_destroy_qp, id, &id);
> 	will_return(rpma_cq_delete, MOCK_OK);
> ```

Here the first call to `rpma_cq_delete()` should also fail.


<!-- Sent from Reviewable.io -->

2021-06-11 14:18 UTC, janekmi requested changes
> Reviewed 1 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 56 of 59 files reviewed, 36 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-get_cq_rcq.c, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvQz-X1_oBBJCtutt3:-MbvQz-X1_oBBJCtutt4:b2nibej) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L93)):*
> ```C
> 
> /*
>  * get_cq__success -- happy day scenario
> ```

rcq


<!-- Sent from Reviewable.io -->

2021-06-11 14:53 UTC, janekmi requested changes
> Reviewed 1 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 57 of 59 files reviewed, 50 unresolved discussions (waiting on @yangx-jy)

___
*[src/conn.c, line 479 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKGKKAuu7hmpB5iEJ:-MbvSuv08m7uokMblSg0:bmchntw) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L479)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get the connection's send CQ
</blockquote></details>

get the main connection's CQ?
___
*[src/include/librpma.h, line 1335 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvUfJN0Ot-1boE-xup:-MbvUfJN0Ot-1boE-xuq:br977rl) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1335)):*
> ```objc
> 
> /** 3
>  * rpma_conn_cfg_set_rcq_size - set receiving CQ size for the connection
> ```

set receive CQ size for the connection
___
*[src/include/librpma.h, line 1346 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvTynyA4Swe5mmUMOP:-MbvTynyA4Swe5mmUMOQ:b-w7tmt2) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1346)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_cfg_set_rcq_size() sets the receiving CQ size for the connection.
> ```

Please see the rpma_conn_get_recq() for details about the receive CQ.
___
*[src/include/librpma.h, line 1346 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvUhOy2TngU77qj0Yf:-MbvUhOy2TngU77qj0Yg:b7wdvbz) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1346)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_cfg_set_rcq_size() sets the receiving CQ size for the connection.
> ```

~~the~~ receive CQ
___
*[src/include/librpma.h, line 1372 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvRdcC18MYFCobJQLJ:-MbvRdcC18MYFCobJQLK:bb7ozr7) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1372)):*
> ```objc
>  *      struct rpma_conn_cfg;
>  *      int rpma_conn_cfg_get_rcq_size(const struct rpma_conn_cfg *cfg,
>  *                      uint32_t *rcq_size);
> ```

tabs
___
*[src/include/librpma.h, line 1706 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvT7cuDEql0p5mH3MX:-MbvT7cvC57g4YoLD3oW:bs7sukb) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1706)):*
> ```objc
> 
> /** 3
>  * rpma_conn_get_cq -- get a rpma_cq object from the connection
> ```

get the main connection's CQ
___
*[src/include/librpma.h, line 1718 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvTAe73lOGLOPsQHDU:-MbvTAe73lOGLOPsQHDV:b8y6whx) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1718)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_get_cq() gets a rpma_cq object from the connection.
> ```

... get the main connection's CQ. When the receive CQ is not present the main connection's CQ allows handling all completions. When the receive CQ is present the main connection's CQ allows handling all completions except `rpma_recv()` completions. Please see `rpma_conn_get_rcq()` for details about the receive CQ.
___
*[src/include/librpma.h, line 1737 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvVW7cDMda4WksG414:-MbvVW7cDMda4WksG415:b-5adm8k) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1737)):*
> ```objc
> 
> /** 3
>  * rpma_conn_get_rcq -- get a receiving rpma_cq object from the connection
> ```

get the receive CQ from the connection
___
*[src/include/librpma.h, line 1749 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvV_TU11zxoXKwTo-t:-MbvV_TU11zxoXKwTo-u:b-olxco6) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1749)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_get_rcq() gets a receiving rpma_cq object from the connection.
> ```

... the receive CQ from the connection.
___
*[src/include/librpma.h, line 1749 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvVeH70C3AQazIzpHx:-MbvVeH70C3AQazIzpHy:bakjzmx) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1749)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_get_rcq() gets a receiving rpma_cq object from the connection.
> ```

The receive CQ allows handling all receive completion within the connection. It allows separating receive completion processing path from any other completion. The receive CQ is created only if the receive CQ size in the provided connection configuration is greater than 0. When the receive CQ does not exist for a given connection the `*rcq_ptr == NULL`.
___
*[src/include/librpma.h, line 1762 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvWaGtD6yGyn-SAQKv:-MbvWaGtD6yGyn-SAQKw:b-u90dwl) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1762)):*
> ```objc
>  * SEE ALSO
>  * rpma_conn_req_connect(3), rpma_conn_get_cq(3), rpma_cq_wait(3),
>  * rpma_cq_get_completion(3), rpma_cq_get_fd(3), librpma(7) and
> ```

rpma_conn_cfg_set_rcq_size(3)
___
*[src/include/librpma.h, line 2716 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvXSikBHJ84ErbCChq:-MbvXSikBHJ84ErbCChr:b-3vawhy) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2716)):*
> from CQ.

I do not like 'the rpma_cq object' because it conveys no meaning. Do you think we can refer to it directly as CQ?

@grom72 @yangx-jy 
___
*[src/include/librpma.h, line 2716 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvXqqj0N3AftHZeeoW:-MbvXqqj0N3AftHZeeoX:b-czp1eb) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2716)):*
> ```objc
>  * DESCRIPTION
>  * rpma_cq_get_fd() gets a file descriptor of the completion event channel
>  * from the rpma_cq object.
> ```

This documentation is way too short to inform the end-user what they can do with this file descriptor. I think it deserves at least a new issue so we can handle this issue in the future.
___
*[src/include/librpma.h, line 2796 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvYSw5-TvpdrGfAeCP:-MbvYSw6BfIWP19lQRZd:b1c9yp7) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2796)):*
> ```objc
>  * - RPMA_OP_RECV - messaging receive operation
>  * - RPMA_OP_RECV_RDMA_WITH_IMM - messaging receive operation for
>  *   RMA write operation with immediate data
> ```

Note that if the provided `cq` is the main CQ and the receive CQ is present this function won't return at any time RPMA_OP_RECV and RPMA_OP_RECV_RDMA_WITH_IMM. To collect these completions the receive CQ has to be used instead.
___
*[src/include/librpma.h, line 2814 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvZ-ZUEMQahHb7li-i:-MbvZ-ZUEMQahHb7li-j:b-56dvmy) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2814)):*
> ```objc
>  * rpma_conn_get_cq(3), rpma_conn_get_rcq(3), rpma_cq_wait(3),
>  * rpma_cq_get_fd(3), rpma_flush(3), rpma_read(3), rpma_recv(3),
>  * rpma_send(3), rpma_write(3), rpma_write_atomic(3), librpma(7)
> ```

You are missing the immediate variants here.


<!-- Sent from Reviewable.io -->

2021-06-11 15:01 UTC, janekmi requested changes
> Reviewed 2 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 53 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv_cAe1i3Yx8pH79eU:-Mbv_cAe1i3Yx8pH79eV:bhfzy9k) (no related file):*
I like this example so much. :grin: 

---
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 189 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvZj8t1tmhYW7bx6Ax:-MbvZj8u6nQZCsBtw-Be:blem95d) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/examples/09-flush-to-persistent-GPSPM/client.c#L189)):*
> ```C
> 		goto err_free;
> 
> 	if ((ret = rpma_conn_cfg_set_rcq_size(cfg, 10)))
> ```

You can add a define in the flush-to-persistent-GPSPM.h file:

```c
/* only a single receive completion is expected */
#define RCQ_SIZE 1
```
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 202 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv_6rd3R2e-JvGgu2i:-Mbv_6rd3R2e-JvGgu2j:bfgw5wz) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/examples/09-flush-to-persistent-GPSPM/server.c#L202)):*
> ```C
> 		goto err_mr_dereg;
> 
> 	if ((ret = rpma_conn_cfg_set_rcq_size(cfg, 10)))
> ```

10 -> RCQ_SIZE
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 248 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv_DsbCaYNEkLGiIhN:-Mbv_DsbCaYNEkLGiIhO:b-yvk8z8) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/examples/09-flush-to-persistent-GPSPM/server.c#L248)):*
> ```C
> 		goto err_conn_delete;
> 
> 	/* validate the receiving completion */
> ```

@grom72 do you know how completion of the RECV operation is referred to in the RDMA documentation? It is called a receive completion or a receiving completion? Any thoughts?


<!-- Sent from Reviewable.io -->

2021-06-15 06:53 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 53 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 248 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv_DsbCaYNEkLGiIhN:-McDPmS56AI6y8Lmk6Y_:bogz9ka) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/examples/09-flush-to-persistent-GPSPM/server.c#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@grom72 do you know how completion of the RECV operation is referred to in the RDMA documentation? It is called a receive completion or a receiving completion? Any thoughts?
</blockquote></details>

It seems that only `receive completion` and `receive CQ` appear on IB Specification, so I perfer to replace `receiving` with `receive`.
___
*[src/conn.c, line 479 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKGKKAuu7hmpB5iEJ:-McDQMbW2cZ9gLXsT0uc:barfyfa) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L479)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get the main connection's CQ?
</blockquote></details>

get the main connection's CQ? or get the connection's main CQ?
___
*[src/conn_req.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv84MV4cwaRipAwwWJ:-McDQUKz3NF_NlzQcT9J:b-c951ri) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/conn_req.c#L204)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
	int ret2;

	int ret = rpma_cq_delete(&req->rcq);
	if ((ret2 = rpma_cq_delete(&req->cq)) {
		if (!ret)
			ret = ret2;
	}
```

</blockquote></details>

How about
```
int ret = rpma_cq_delete(&req->rcq);
int ret2 = rpma_cq_delete(&req->cq);

if (!ret && ret2)
	ret = ret2;
```
___
*[src/peer.c, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv8YAJ5Fx_JsQ8BoMT:-McDQjsz0U3Uvn9q5ejq:b-ovwaw7) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/peer.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
... = rcq ? rpma_cq_get_ibv_cq(rcq) : ibv_cq;
```
</blockquote></details>

Good idea.
___
*[src/include/librpma.h, line 1346 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvUhOy2TngU77qj0Yf:-McDQozDCpCxikBTa42v:bne87tk) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1346)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~the~~ receive CQ
</blockquote></details>

Other APIs all use `the` in DESCRIPTION.
___
*[src/include/librpma.h, line 2716 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvXSikBHJ84ErbCChq:-McDR0d8EKGbzpRiAKXK:b-qz47db) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2716)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> from CQ.

I do not like 'the rpma_cq object' because it conveys no meaning. Do you think we can refer to it directly as CQ?

@grom72 @yangx-jy 
</blockquote></details>

It is fine to me.
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQW_u39xlrMpEYf-Y:-McDR6rBB807-IrqhK12:b-9czb90) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I see you have assumed when the rcq_size == 0 the separate CQ for receives does not exist so the `_get_rcq()` will return NULL.
I am considering an alternative proposition when`_get_rcq()` returns a CQ for receives no matter if it is created separate or it is common with sends.
What do you think?
</blockquote></details>

I perfer the current implementation.
It is easy for applications to know if separate receive CQ is used by `_get_rcq` (non-NULL or NULL).
___
*[tests/unit/conn/conn-new.c, line 319 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_8YFEaCBxieYG79e:-McDOOU_0Bx2u9G0Mm-U:b-6j9sxg) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-new.c#L319)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MOCK_ERRNO?
</blockquote></details>

I want to make this PR clear and simple so I don't apply simulated errno in this PR.
I have applied  simulated errno for all unit tests in separate #1093.  Perhaps, we needs to review it first.


<!-- Sent from Reviewable.io -->

2021-06-30 07:48 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 29 of 63 files reviewed, 53 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv763S1NPNwzVuDN0Q:-MdQkrU6AhGjkb8B_-8Y:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You should merge these two PRs:
- rpma: implement separate receiving CQ 
- test: add and refactor unit tests for seperate receiving CQ

By modifying code without changing the tests you making bisection impossible.
</blockquote></details>

Done.

---
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 189 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvZj8t1tmhYW7bx6Ax:-MdQsTitCSSvgt3Bcy7l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/examples/09-flush-to-persistent-GPSPM/client.c#L189)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can add a define in the flush-to-persistent-GPSPM.h file:

```c
/* only a single receive completion is expected */
#define RCQ_SIZE 1
```
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 202 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv_6rd3R2e-JvGgu2i:-MdQsVYh1LOBABrNJSQS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/examples/09-flush-to-persistent-GPSPM/server.c#L202)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

10 -> RCQ_SIZE
</blockquote></details>

Done.
___
*[src/conn.c, line 258 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuJf7xDSvDs4x8b9Ob:-MdQsXFS7x2obvfR5B7k:b-d0m3ha) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L258)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cq` first before `rcq`.
</blockquote></details>

No, keep it.
___
*[src/conn.c, line 479 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKGKKAuu7hmpB5iEJ:-MdQscUI8rLX2HqluDG-:boopb46) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L479)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

get the main connection's CQ? or get the connection's main CQ?
</blockquote></details>

Done.

Use ` get the connection's main CQ`.
___
*[src/conn.c, line 493 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKcnv5cruGMTIIcci:-MdQsbtXACD6qRuCPFje:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L493)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get the connection's receive CQ
</blockquote></details>

Done.
___
*[src/conn_cfg.c, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuOA66BCkNhX6-vkGV:-MdQlVhY8DMwbAgcXvD3:bjymyi1) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/*
 * rpma_conn_cfg... -- ...
```
</blockquote></details>

Done.

Use `ROUND_DOWN()` macro in src/common.h instead.
___
*[src/conn_cfg.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuNiRACyt1VPjtFiah:-MdQlXIb70n1ZWuX8HRU:bjymyi1) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
static int
rpma_conn_cfg_...
```
</blockquote></details>

Done.

Use `ROUND_DOWN()` macro in src/common.h instead.
___
*[src/conn_cfg.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuOZpz7bal7aaJeAtV:-MdQl_iN0yg37g5gdGNo:bjymyi1) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not on the internal API of this unit so it should go above the internal API boundary.

TBH I think it may be an even better fit into `common.h` as a simple macro? Up to you.
</blockquote></details>

Done.

Use `ROUND_DOWN()` macro in src/common.h instead.
___
*[src/conn_cfg.c, line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuP6DD7wkMOCQF9IvW:-MdQlc06A9mxNEfzhWVq:bp3ug0m) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn_cfg.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know it is tiresome to have getters and setters for each of the fields separately but I believe it makes the API easier to maintain in the future. The `rpma_conn_cfg_get_cqe()` function is a variant of `rpma_conn_cfg_get_cq_size()` and I think it should stay this way. Instead, I think you should introduce something like `rpma_conn_cfg_get_rcqe()` (following the naming conventions).
</blockquote></details>

Done.

Add `rpma_conn_cfg_get_rcqe()`
___
*[src/conn_req.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv84MV4cwaRipAwwWJ:-MdQlimj0xL3FW1Alv2S:b-6z9hx7) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/conn_req.c#L204)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

How about
```
int ret = rpma_cq_delete(&req->rcq);
int ret2 = rpma_cq_delete(&req->cq);

if (!ret && ret2)
	ret = ret2;
```

</blockquote></details>

Done.

Use my above logic instead.
___
*[src/conn_req.c, line 239 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbv8PRbA0EOS8L4-9nA:-MdQm5z6DesPUxPrvz-E:b-6z9hx7) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/conn_req.c#L239)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

Use my above logic instead.
___
*[src/cq.c, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu1TgVAcMIy8ZUuZ8g:-MdQm9vc-8adXZ0ojhmF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/cq.c#L165)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We tend to keep the internal API calls first in the *.c files before the public API.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1335 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvUfJN0Ot-1boE-xup:-MdQsyl14F5mQTo2p5O-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1335)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

set receive CQ size for the connection
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1346 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvTynyA4Swe5mmUMOP:-MdQshYR8AxNm6CUVc5k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1346)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please see the rpma_conn_get_recq() for details about the receive CQ.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1346 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvUhOy2TngU77qj0Yf:-MdQsiSe4slvz4aFqhgM:bg8vw46) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1346)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Other APIs all use `the` in DESCRIPTION.
</blockquote></details>

Keep `the` for now.
___
*[src/include/librpma.h, line 1372 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvRdcC18MYFCobJQLJ:-MdQmHqw8-4GX2ex [...]

2021-07-09 13:44 UTC, ldorau reviewed
> Reviewed 3 of 59 files at r1, 3 of 34 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 33 of 63 files reviewed, 53 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[tests/unit/conn_cfg/CMakeLists.txt, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_wu5-54InoksVq7N:-MeAVfweBNMbVHnAetDB:bo0pbb6) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_cfg/CMakeLists.txt#L31)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

No.  The correct one is `rcq_size, rq_szie`.  See the output of sort:
```
# grep '^add_test_conn_cfg' CMakeLists.txt | sort -d
add_test_conn_cfg(cqe)
add_test_conn_cfg(cq_size)
add_test_conn_cfg(delete)
add_test_conn_cfg(new)
add_test_conn_cfg(rcqe)
add_test_conn_cfg(rcq_size)
add_test_conn_cfg(rq_size)
add_test_conn_cfg(sq_size)
add_test_conn_cfg(timeout)
```
</blockquote></details>

It is OK


<!-- Sent from Reviewable.io -->

2021-07-09 14:26 UTC, ldorau reviewed
> Reviewed 1 of 59 files at r1, 2 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 35 of 63 files reviewed, 53 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-22 16:15 UTC, janekmi requested changes
> Reviewed 8 of 34 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 42 of 63 files reviewed, 19 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/conn.c, line 479 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKGKKAuu7hmpB5iEJ:-MfDuhCh6tyrTJQQN1BY:b-5mkg3e) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L479)):*
> Use 'get the connection's main CQ'.

I do agree. 
___
*[src/include/librpma.h, line 1706 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvT7cuDEql0p5mH3MX:-MfDvpQV05B1alC0j8bi:b-10lgn9) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1706)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After reconsideration, I think `the connection's main CQ` is correct. Please apply.
___
*[src/include/librpma.h, line 2716 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvXqqj0N3AftHZeeoW:-MfDwpeY9U0oCKvWRm67:b-sfi87n) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2716)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Agreed, I will add a new issue about it.
</blockquote></details>

Please add a reference when it will be ready.
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQW_u39xlrMpEYf-Y:-MfDyCZqCGVo-9pg8Nsy:bhvx9if) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 @ldorau @osalyk @janekmi 

We have to disscuss which implementation should be selected.
</blockquote></details>

I like your argument. I think I am for returning NULL when the receive CQ is missing.
But I will just leave the issue to keep track of important API decisions I have to discuss with @grom72.
___
*[tests/unit/conn_cfg/CMakeLists.txt, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-Mbu_wu5-54InoksVq7N:-MfDzmFyATMROqpZofn_:b-oyngte) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn_cfg/CMakeLists.txt#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is OK
</blockquote></details>

It must have been very late when I have written this nonsense. xD Sorry. Of course, you are right.


<!-- Sent from Reviewable.io -->

2021-07-22 16:53 UTC, janekmi requested changes
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 43 of 63 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/conn.c, line 258 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuJf7xDSvDs4x8b9Ob:-MfE6NW38dsCC9jDB4RQ:b-3m8tyx) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L258)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

No, keep it.
</blockquote></details>

I know these two are not created in a strict order but, since we have agreed so far to delete in the reverse order to what the items have been created, I will ask you one more time to switch these to in places. Please. :grin: 


<!-- Sent from Reviewable.io -->

2021-07-23 02:41 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 42 of 63 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[src/conn.c, line 258 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuJf7xDSvDs4x8b9Ob:-MfGAeST2uGu9QL_F555:b6ua7ne) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L258)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know these two are not created in a strict order but, since we have agreed so far to delete in the reverse order to what the items have been created, I will ask you one more time to switch these to in places. Please. :grin: 
</blockquote></details>

Hi Jan,

I checked all code and I think these two CQs in all place are deleted in the  reverse order (i.e. `rcq -> cq`).
Did I miss anything?
___
*[src/conn.c, line 479 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuKGKKAuu7hmpB5iEJ:-MfGCigrBsb4eVcQqt21:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L479)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Use 'get the connection's main CQ'.

I do agree. 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1706 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvT7cuDEql0p5mH3MX:-MfGCjnn6NKp_fAuAM4s:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L1706)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

After reconsideration, I think `the connection's main CQ` is correct. Please apply.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2716 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbvXqqj0N3AftHZeeoW:-MfGDcde5ugEGC9EAToE:bszm7tq) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/src/include/librpma.h#L2716)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a reference when it will be ready.
</blockquote></details>

https://github.com/pmem/rpma/issues/1112
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQW_u39xlrMpEYf-Y:-MfGDgcxEieBfBnFEZKQ:b-esrm6j) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like your argument. I think I am for returning NULL when the receive CQ is missing.
But I will just leave the issue to keep track of important API decisions I have to discuss with @grom72.
</blockquote></details>

Sure, we should discuss it with @grom72.

By the way, I have rebased this PR.  ^_^


<!-- Sent from Reviewable.io -->

2021-07-23 08:58 UTC, janekmi requested changes
> Reviewed 3 of 34 files at r3, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 45 of 63 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/common.h, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1080#-MfHXn0cEVMlHP0lgViv:-MfHXn0d7an-C-V0HHvx:b50nn6y) ([raw file](https://github.com/pmem/rpma/blob/ba2b96abe80cb5bf6adb40d91d89a308cae16c56/src/common.h#L14)):*
> ```objc
> #define STR(x) STR_HELPER(x)
> 
> #define ROUND_DOWN(size)	((size) > INT_MAX ? INT_MAX : (int)(size))
> ```

CLIP_TO_INT?
___
*[src/conn.c, line 258 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MbuJf7xDSvDs4x8b9Ob:-MfHYH2g6EpkMKsc1NXQ:b9ge3kv) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/src/conn.c#L258)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi Jan,

I checked all code and I think these two CQs in all place are deleted in the  reverse order (i.e. `rcq -> cq`).
Did I miss anything?
</blockquote></details>

Nope. I have missed it. Sorry.


<!-- Sent from Reviewable.io -->

2021-07-23 09:26 UTC, ldorau requested changes
> Reviewed 4 of 59 files at r1, 9 of 34 files at r3, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 51 of 63 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/common.h, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1080#-MfHXn0cEVMlHP0lgViv:-MfHcJtY-i7n49uPLPIr:b32v57) ([raw file](https://github.com/pmem/rpma/blob/ba2b96abe80cb5bf6adb40d91d89a308cae16c56/src/common.h#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

CLIP_TO_INT?
</blockquote></details>

+1
___
*[src/include/librpma.h, line 1759 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHeE5VCkwPXUvI29xW:-MfHeE5VCkwPXUvI29xX:blm9doy) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/src/include/librpma.h#L1759)):*
> ```objc
>  * The receive CQ is created only if the receive CQ size in the provided
>  * connection configuration is greater than 0. When the receive CQ does not
>  * exist for a given connection the *rcq_ptr == NULL.
> ```

for the given


<!-- Sent from Reviewable.io -->

2021-07-23 09:44 UTC, janekmi requested changes
> Reviewed 6 of 34 files at r3, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 56 of 63 files reviewed, 18 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn/conn-common.c, line 113 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHekNmDTgVU2LmY1pw:-MfHekNmDTgVU2LmY1px:by9snbg) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-common.c#L113)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq ?
> 		MOCK_RPMA_RCQ : NULL);
> ```

```c
expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq);
```
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 107 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHetBm9Y27_96sFwfB:-MfHetBm9Y27_96sFwfC:bybzrjl) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-get_cq_rcq.c#L107)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, 0);
> 	assert_ptr_equal(rcq, cstate->rcq ? MOCK_RPMA_RCQ : NULL);
> ```

```c
assert_ptr_equal(rcq, cstate->rcq);
```
___
*[tests/unit/conn/conn-new.c, line 71 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfaE-1A0W39EocMkI:-MfHfaE-1A0W39EocMkJ:bupx73o) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L71)):*
> ```C
> 	/* run test */
> 	int ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID, MOCK_RPMA_CQ, NULL,
> 			NULL);
> ```

Does not fit into a single line?
___
*[tests/unit/conn/conn-new.c, line 106 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfiGf94TTYQcXqldo:-MfHfiGf94TTYQcXqldp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L106)):*
> ```C
> 	struct rpma_conn *conn = NULL;
> 	int ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID, MOCK_RPMA_CQ, NULL,
> 			&conn);
> ```

.
___
*[tests/unit/conn/conn-new.c, line 129 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfkJ8106LMv3exR48:-MfHfkJ8106LMv3exR49:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L129)):*
> ```C
> 	struct rpma_conn *conn = NULL;
> 	int ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID, MOCK_RPMA_CQ, NULL,
> 			&conn);
> ```

.
___
*[tests/unit/conn/conn-new.c, line 151 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHflkW8QsklGb-pNU2:-MfHflkW8QsklGb-pNU3:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L151)):*
> ```C
> 	struct rpma_conn *conn = NULL;
> 	int ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID, MOCK_RPMA_CQ, NULL,
> 			&conn);
> ```

.
___
*[tests/unit/conn/conn-new.c, line 175 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfmdADNt8mfipmfDJ:-MfHfmdADNt8mfipmfDK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L175)):*
> ```C
> 	struct rpma_conn *conn = NULL;
> 	int ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID, MOCK_RPMA_CQ, NULL,
> 			&conn);
> ```

.
___
*[tests/unit/conn/conn-new.c, line 252 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHftvV1SdflR-a7DdX:-MfHftvV1SdflR-a7DdY:bqeqtrp) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L252)):*
> ```C
> 	will_return(rpma_flush_delete, MOCK_ERRNO);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

You should use `cstate->rcq` unconditionally.
___
*[tests/unit/conn/conn-new.c, line 288 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHg0_63MYoo4G1STfn:-MfHg0_63MYoo4G1STfo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L288)):*
> ```C
> 	will_return(rpma_flush_delete, RPMA_E_INVAL);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn/conn-new.c, line 323 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHgfP6-kG36jSj_WrG:-MfHgfP6-kG36jSj_WrH:b5qiibp) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L323)):*
> ```C
> 	will_return(rpma_flush_delete, MOCK_OK);
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_RCQ);
> ```

`cstate->rcq`?
___
*[tests/unit/conn/conn-new.c, line 327 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHhClZ-rV-jXAt6jT_:-MfHhClZ-rV-jXAt6jTa:b-ih2mi6) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L327)):*
> ```C
> 	will_return(rpma_cq_delete, MOCK_ERRNO);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_delete, MOCK_ERRNO);
> ```

The test description suggests only the first `rpma_cq_delete()` will fail.
___
*[tests/unit/conn/conn-new.c, line 361 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHhMToBdU0DF0zsJtl:-MfHhMToBdU0DF0zsJtm:b5qiibp) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L361)):*
> ```C
> 	will_return(rpma_flush_delete, MOCK_OK);
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_RCQ);
> ```

`cstate->rcq`?
___
*[tests/unit/conn/conn-new.c, line 399 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHj9JO9KZ9I1N_LHpV:-MfHj9JO9KZ9I1N_LHpW:b-6pn6km) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L399)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

`cstate->rcq` unconditionally.
___
*[tests/unit/conn/conn-new.c, line 437 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHjIIlD_qpfda-xsuc:-MfHjIIlD_qpfda-xsud:b-6pn6km) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L437)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

`cstate->rcq` unconditionally.
___
*[tests/unit/conn/conn-new.c, line 474 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHjPE--a-oprXQ9SLj:-MfHjPE--a-oprXQ9SLk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L474)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, MOCK_CM_ID);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.


<!-- Sent from Reviewable.io -->

2021-07-23 10:03 UTC, ldorau reviewed
> Reviewed 2 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 56 of 63 files reviewed, 18 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-23 10:59 UTC, janekmi requested changes
> Reviewed 4 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 58 of 63 files reviewed, 23 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-common.c, line 44 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHzHvq8wOQcPEpGJOW:-MfHzHvq8wOQcPEpGJOX:b-z4c0cn) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-common.c#L44)):*
> ```C
> };
> 
> void
> ```

A comment is missing.
___
*[tests/unit/conn_req/conn_req-common.c, line 57 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHzLlt5PfpL3z5YcNW:-MfHzLlt5PfpL3z5YcNX:b-z4c0cn) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-common.c#L57)):*
> ```C
> }
> 
> void
> ```

A comment is missing.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 27 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHyfTE1fwsTrd8zCPe:-MfHyfTE1fwsTrd8zCPf:b5qiibp) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-private_data.c#L27)):*
> ```C
> 	/* configure mocks */
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, NULL);
> ```

`cstate->rcq`?
___
*[tests/unit/conn_req/conn_req-private_data.c, line 77 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHyhaq6mOGS0kTwSd3:-MfHyhaq6mOGS0kTwSd4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-private_data.c#L77)):*
> ```C
> 	/* configure mocks */
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, NULL);
> ```

.
___
*[tests/unit/peer/peer-create_qp.c, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHnIXR-Z8p667NRPeU:-MfHnIXR-Z8p667NRPeV:b-z4c0cn) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/peer/peer-create_qp.c#L39)):*
> ```C
> static int num_rcqs = sizeof(rcqs) / sizeof(rcqs[0]);
> 
> static void
> ```

A comment is missing.


<!-- Sent from Reviewable.io -->

2021-07-23 11:04 UTC, ldorau reviewed
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 59 of 63 files reviewed, 23 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-23 11:26 UTC, janekmi requested changes
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 60 of 63 files reviewed, 39 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-delete.c, line 49 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI3YEj7z3HfUZ534tt:-MfI3YEj7z3HfUZ534tu:b-2cxo4z) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L49)):*
> ```C
> {
> 	/* WA for cmocka/issues#47 */
> 	struct conn_req_test_state *cstate = &Conn_req_conn_cfg_custom;
> ```

If it is non-null so why it is not provided as a regular prestate?
___
*[tests/unit/conn_req/conn_req-delete.c, line 55 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI3ppv6FwjjyGfAC6-:-MfI3ppv6FwjjyGfAC60:b-oduz3q) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L55)):*
> ```C
> 	/* configure mocks */
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_RCQ);
> ```

`cstate` does not provide it?
___
*[tests/unit/conn_req/conn_req-delete.c, line 84 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI3w5-14AX39t36GLv:-MfI3w5-14AX39t36GLw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L84)):*
> ```C
> {
> 	/* WA for cmocka/issues#47 */
> 	struct conn_req_test_state *cstate = &Conn_req_conn_cfg_custom;
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 90 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI3wlf8AJv7nE6mSS9:-MfI3wlf8AJv7nE6mSSA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L90)):*
> ```C
> 	/* configure mocks */
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_RCQ);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 125 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI457c99gZljkgTZt3:-MfI457c99gZljkgTZt4:bj99jbi) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L125)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

This inline condition is copied multiple times. Maybe since it is so abundant we should make a macro for it?
___
*[tests/unit/conn_req/conn_req-delete.c, line 160 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI4tXJ97uhDIXaDr0Z:-MfI4tXJ97uhDIXaDr0_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L160)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 193 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI50Wy6W5w6Y4wCLl2:-MfI50Wy6W5w6Y4wCLl3:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L193)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 226 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI542yArXHwD-uKaM4:-MfI542yArXHwD-uKaM5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L226)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 258 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI56UJ9UvdBokI8D8v:-MfI56UJ9UvdBokI8D8w:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L258)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 284 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5ASgE6CFpNFPDJbK:-MfI5ASgE6CFpNFPDJbL:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L284)):*
> ```C
> {
> 	/* WA for cmocka/issues#47 */
> 	struct conn_req_new_test_state *cstate = &Conn_req_new_conn_cfg_custom;
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 290 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5BDY-TwbjpRCPwN3:-MfI5BDY-TwbjpRCPwN4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L290)):*
> ```C
> 	/* configure mocks */
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_RCQ);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 316 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5D4Q0FiYgL-hUoUW:-MfI5D4Q0FiYgL-hUoUX:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L316)):*
> ```C
> {
> 	/* WA for cmocka/issues#47 */
> 	struct conn_req_new_test_state *cstate = &Conn_req_new_conn_cfg_custom;
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 322 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5Dv_93gif5dFq-BM:-MfI5Dv_93gif5dFq-BN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L322)):*
> ```C
> 	/* configure mocks */
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_RCQ);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 355 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5Fbp2Uxpsr427k3M:-MfI5Fbp2Uxpsr427k3N:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L355)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 388 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5IXr4qVk9LqzKzCb:-MfI5IXr4qVk9LqzKzCc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L388)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-delete.c, line 420 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfI5UBu9aaKxLrxh6eZ:-MfI5UBu9aaKxLrxh6e_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-delete.c#L420)):*
> ```C
> 	expect_value(rdma_destroy_qp, id, &cstate->id);
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.


<!-- Sent from Reviewable.io -->

2021-07-23 13:09 UTC, ldorau requested changes
> Reviewed 3 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 61 of 63 files reviewed, 41 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-new.c, line 328 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfISQf7E233qWjSjuod:-MfISQf7E233qWjSjuoe:b-d4og7l) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-new.c#L328)):*
> ```
> 	expect_value(rpma_peer_create_qp, rcq, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

You can use a macro for it : 
```
expect_value(rpma_peer_create_qp, rcq, RCQ(cstate);
```
because it occurs many times (at least 37 times)
___
*[tests/unit/conn_req/conn_req-new.c, line 466 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfITuDO8udsgkUMg1xO:-MfITuDO8udsgkUMg1xP:b-n3m6ks) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-new.c#L466)):*
> ```
> 			(cstate->get_cqe.cfg == MOCK_CONN_CFG_DEFAULT ?
> 				NULL : cstate->get_cqe.cfg);
> ```

You can use a macro for it, because it occurs many times.


<!-- Sent from Reviewable.io -->

2021-07-23 13:16 UTC, ldorau requested changes
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 62 of 63 files reviewed, 42 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-connect.c, line 139 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIU7y35GPpd4iOu3Ks:-MfIU7y35GPpd4iOu3Kt:bdqwbjr) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-connect.c#L139)):*
> ```
> 	cstate->get_cqe.rcq_size ? MOCK_RPMA_RCQ : NULL
> ```

A macro?


<!-- Sent from Reviewable.io -->

2021-07-23 13:30 UTC, ldorau requested changes
> Reviewed 1 of 34 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 49 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 176 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYH599ByjfJmD_Bya:-MfIYH5A7Fm2q9NtYkr2:b-uejd) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L176)):*
> ```
> 	cstate->get_cqe.rcq_size ? MOCK_RPMA_RCQ : NULL
> ```

A macro ?
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 182 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYNdd1J38mmbK3Mu4:-MfIYNdd1J38mmbK3Mu5:b8x6xh3) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L182)):*
> ```
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 266 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYZ11BmrXy48-CFhn:-MfIYZ11BmrXy48-CFho:b-3rahzq) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L266)):*
> ```
> 	expect_value(rpma_peer_create_qp, rcq, cstate->get_cqe.rcq_size ?
> 		MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 272 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYa5MCucEKGoPBmAV:-MfIYa5MCucEKGoPBmAW:b8x6xh3) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L272)):*
> ```
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 309 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYdFI8UrPcyEAxGfd:-MfIYdFI8UrPcyEAxGfe:bbgc05v) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L309)):*
> ```
> 	expect_value(rpma_peer_create_qp, rcq, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 358 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYfto8QhuAB7mdP9l:-MfIYfto8QhuAB7mdP9m:bbgc05v) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L358)):*
> ```
> 	expect_value(rpma_peer_create_qp, rcq, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 365 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfIYhmP5QhD-KolzsYK:-MfIYhmP5QhD-KolzsYL:b8x6xh3) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-from_cm_event.c#L365)):*
> ```
> 	expect_value(rpma_cq_delete, *cq_ptr, cstate->get_cqe.rcq_size ?
> 			MOCK_RPMA_RCQ : NULL);
> ```

.


<!-- Sent from Reviewable.io -->

2021-07-23 17:26 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 49 of 63 files reviewed, 49 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/common.h, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1080#-MfHXn0cEVMlHP0lgViv:-MfJJ-eC6_IUDvEyfw5F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ba2b96abe80cb5bf6adb40d91d89a308cae16c56/src/common.h#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1759 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHeE5VCkwPXUvI29xW:-MfJJ2ITE49kfAklMzvW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/src/include/librpma.h#L1759)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

for the given
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-common.c, line 113 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHekNmDTgVU2LmY1pw:-MfJJ46x6dAl8h18Kf8u:b-hgb8qc) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-common.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
expect_value(rpma_cq_delete, *cq_ptr, cstate->rcq);
```
</blockquote></details>

Done.  Good catch. ^_^
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 107 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHetBm9Y27_96sFwfB:-MfJJC5_4cF_5NYF_Mac:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-get_cq_rcq.c#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
assert_ptr_equal(rcq, cstate->rcq);
```
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-new.c, line 71 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfaE-1A0W39EocMkI:-MfJJGST2TRfR7qlN8t4:b-4uw6i5) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Does not fit into a single line?
</blockquote></details>

No, it threw "line > 80 characters" error.
Keep it.
___
*[tests/unit/conn/conn-new.c, line 106 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfiGf94TTYQcXqldo:-MfJJf3V2Q8x28j8Pmun:b-yqcxhv) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Keep it.
___
*[tests/unit/conn/conn-new.c, line 129 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfkJ8106LMv3exR48:-MfJJhFA4mc42kewIzFK:b-yqcxhv) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L129)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Keep it.
___
*[tests/unit/conn/conn-new.c, line 151 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHflkW8QsklGb-pNU2:-MfJJhtd4bfci358DhCW:b-yqcxhv) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Keep it.
___
*[tests/unit/conn/conn-new.c, line 175 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHfmdADNt8mfipmfDJ:-MfJJjJe6dMs001Cu6ct:b-yqcxhv) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L175)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Keep it.
___
*[tests/unit/conn/conn-new.c, line 252 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHftvV1SdflR-a7DdX:-MfJJl3h1Fp4EVDYjEkF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L252)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You should use `cstate->rcq` unconditionally.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-new.c, line 288 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHg0_63MYoo4G1STfn:-MfJJmip0E2bW9TlUQP4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L288)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-new.c, line 323 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHgfP6-kG36jSj_WrG:-MfJJoAd5hAHAcJzosl2:buc5abh) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L323)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cstate->rcq`?
</blockquote></details>

No, I think only `rpma_cq_delete()` with non-null rcq can have a chance to get error.
`rpma_cq_delete()`  with null rcq always succeeds (in other words, always return 0).
___
*[tests/unit/conn/conn-new.c, line 327 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHhClZ-rV-jXAt6jT_:-MfJKgfLEuWkwXau-3dC:be9l2sn) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L327)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The test description suggests only the first `rpma_cq_delete()` will fail.
</blockquote></details>

Done.  Change the second MOCK_ERRNO to MOCK_OK.
___
*[tests/unit/conn/conn-new.c, line 361 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHhMToBdU0DF0zsJtl:-MfJKxvRD0c7KCbYD1Oa:buc5abh) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L361)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cstate->rcq`?
</blockquote></details>

No, I think only `rpma_cq_delete()` with non-null rcq can have a chance to get error.
`rpma_cq_delete()`  with null rcq always succeeds (in other words, always return 0).
___
*[tests/unit/conn/conn-new.c, line 399 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHj9JO9KZ9I1N_LHpV:-MfJL3CpEr7ET5_RYqfK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L399)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cstate->rcq` unconditionally.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-new.c, line 437 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHjIIlD_qpfda-xsuc:-MfJL4439oGtO3poT9J3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L437)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`cstate->rcq` unconditionally.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-new.c, line 474 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHjPE--a-oprXQ9SLj:-MfJL5B9-w0kt7_eTo3Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn/conn-new.c#L474)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-common.c, line 44 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHzHvq8wOQcPEpGJOW:-MfJL8fCAUhvNVy-_Xhz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/conn_req/conn_req-common.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></ [...]

2021-07-23 17:53 UTC, janekmi reviewed
> Reviewed 4 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 53 of 63 files reviewed, 25 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-23 20:16 UTC, janekmi requested changes
> Reviewed 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 54 of 63 files reviewed, 52 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 187 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJVgq4AlcX3iLnEmz1:-MfJVgq4AlcX3iLnEmz2:bz9p3h0) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L187)):*
> ```C
> 	struct rpma_conn_cfg *cfg = NULL;
> 	if ((ret = rpma_conn_cfg_new(&cfg)))
> 		goto err_free;
> ```

`goto err_peer_delete`
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 273 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJWJ5o8NA89SeZy6JX:-MfJWJ5o8NA89SeZy6JY:b8e9o7m) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L273)):*
> ```C
> 		goto err_mr_remote_delete;
> 
> 	/* validate the sending completion */
> ```

Since we have a receive CQ I am voting for `the send completion`.  What do you think?
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 294 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJWkpd3jPlQ9ip3i7B:-MfJWkpe3Rw2ubTnvwmm:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L294)):*
> ```C
> 		goto err_mr_remote_delete;
> 
> 	/* validate the receive completion */
> ```

:+1: 
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 352 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJVqlEDSz3HcfmruDi:-MfJVqlEDSz3HcfmruDj:b-yogf31) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L352)):*
> ```C
> 
> err_cfg_delete:
> 	(void) rpma_conn_cfg_delete(&cfg);
> ```

The config is created **after** the peer. So it has to be destroyed **before** it.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 215 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJXO9D0QiUU7iKlVH4:-MfJXO9D0QiUU7iKlVH5:b-yntu5e) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/server.c#L215)):*
> ```C
> 	/* receive an incoming connection request */
> 	if ((ret = rpma_ep_next_conn_req(ep, cfg, &req)))
> 		goto err_mr_dereg;
> ```

`goto err_cfg_delete`
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 297 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJXZmcAQl8s1liXdrb:-MfJXZmcAQl8s1liXdrc:bjh0pqh) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/server.c#L297)):*
> ```C
> 		goto err_conn_delete;
> 
> 	/* wait for the sending completion to be ready */
> ```

`the send completion`?
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 306 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJXdM5BjrMV3BCZQmo:-MfJXdM5BjrMV3BCZQmp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/server.c#L306)):*
> ```C
> 		goto err_conn_delete;
> 
> 	/* validate the sending completion */
> ```

.
___
*[src/conn.c, line 26 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJcsiM5FIFC_Gnk7-u:-MfJcsiM5FIFC_Gnk7-v:b1yivo8) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn.c#L26)):*
> ```C
> 	struct rdma_cm_id *id; /* a CM ID of the connection */
> 	struct rdma_event_channel *evch; /* event channel of the CM ID */
> 	struct rpma_cq *cq; /* rpma_cq object */
> ```

`the main CQ` to follow the documentation.
___
*[src/conn.c, line 27 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJcvogAghWdTzqgp_9:-MfJcvogAghWdTzqgp_A:b-tt6sef) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn.c#L27)):*
> ```C
> 	struct rdma_event_channel *evch; /* event channel of the CM ID */
> 	struct rpma_cq *cq; /* rpma_cq object */
> 	struct rpma_cq *rcq; /* receive rpma_cq object */
> ```

`the receive CQ` .
___
*[src/conn.c, line 285 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJdoYqDOwBzGy3HNfw:-MfJdoYqDOwBzGy3HNfx:b-512tfv) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn.c#L285)):*
> ```C
> 	(void) rpma_cq_delete(&conn->cq);
> err_destroy_id:
> 	(void) rdma_destroy_id(conn->id);
> ```

It seems we attempt to destroy the ID without even trying to call `rdma_destroy_qp()` in case of an error. Despite it is required.

Ref: https://linux.die.net/man/3/rdma_destroy_id

We need an issue for this and a fix soon afterwards. ;-)
___
*[src/conn_cfg.h, line 28 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJeYNn-7aKmQrHnn2v:-MfJeYNn-7aKmQrHnn2w:bq6t9lr) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.h#L28)):*
> ```objc
> int rpma_conn_cfg_get_cqe(const struct rpma_conn_cfg *cfg, int *cqe);
> ```

Too many new lines.
___
*[src/conn_cfg.c, line 29 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJewT_0cpu7fXxFqxp:-MfJewT_0cpu7fXxFqxq:b-72r49c) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.c#L29)):*
> The default size of the receive CQ is 0, which means no receive CQ is created for the connection.

- **Note** the full stop at the end of the sentence. ;-)
___
*[src/conn_cfg.c, line 30 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJf9XXBEpHwOlY22DD:-MfJf9XY5hFDWKnOeDVj:b-xeq71e) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.c#L30)):*
> ```C
> /*
>  * The default size of rcq is 0 - no separate receive CQ
>  */
> ```

This comment fits into a single line. At least before my comment. ;-)
___
*[src/conn_cfg.c, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJfoXE48AqRJONrbgb:-MfJfoXE48AqRJONrbgc:b-oe2n2f) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.c#L35)):*
> ```C
> struct rpma_conn_cfg {
> 	int timeout_ms;	/* connection establishment timeout */
> 	uint32_t cq_size;	/* CQ size */
> ```

`main CQ size`
___
*[src/conn_req.c, line 31 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgR6a5kSulMy0Ke3G:-MfJgR6b2UOwl5OG5-2v:b-lr1bow) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L31)):*
> ```C
> 	/* CM ID of the connection request */
> 	struct rdma_cm_id *id;
> 	/* rpma_cq object */
> ```

main CQ
___
*[src/conn_req.c, line 33 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgT1a8P2bgxpXOyvh:-MfJgT1a8P2bgxpXOyvi:b-k36zxs) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L33)):*
> ```C
> 	/* rpma_cq object */
> 	struct rpma_cq *cq;
> 	/* receive rpma_cq object */
> ```

receive CQ
___
*[src/conn_req.c, line 57 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgf7l91JzpxwmrV2A:-MfJgf7l91JzpxwmrV2B:b-lr1bow) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L57)):*
> ```C
> 
> 	int cqe, rcqe;
> 	/* read CQ size from the configuration */
> ```

main CQ
___
*[src/conn_req.c, line 205 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJkgcu1XcL3rztFtRv:-MfJkgcu1XcL3rztFtRw:b-9scoig) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L205)):*
> ```C
> 
> 	if (!ret && ret2)
> 		ret = ret2;
> ```

I think these lines should be grouped as follow:

```c
	int ret = rpma_cq_delete(&req->rcq);

	int ret2 = rpma_cq_delete(&req->cq);
	if (!ret && ret2)
		ret = ret2;
```

Because the first `rpma_cq_delete()` stands on its own. The return value is stored. The processing should be continued no matter what.
Whereas the second call to  [...]

2021-07-23 22:09 UTC, janekmi requested changes
> Reviewed 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 55 of 63 files reviewed, 59 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn/conn-get_cq_rcq.c, line 116 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfK37ex2kjc2xaGwy20:-MfK37ex2kjc2xaGwy21:b-wjmuyq) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-get_cq_rcq.c#L116)):*
> ```C
> 		setup__conn_new, teardown__conn_delete),
> 	cmocka_unit_test_setup_teardown(get_cq__success,
> 		setup__conn_new, teardown__conn_delete),
> ```

To be on the safe side I think we need two test cases: with and without rcq. Just in case the implementation would mess up both of them.
___
*[tests/unit/conn/conn-get_cq_rcq.c, line 123 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfK4a194xgazfwMlLnz:-MfK4a194xgazfwMlLo-:b-114dsi) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-get_cq_rcq.c#L123)):*
> ```C
> 		setup__conn_new, teardown__conn_delete),
> 	{"get_rcq__without_rcq", get_rcq__success,
> 		setup__conn_new, teardown__conn_delete, NULL},
> ```

I like more to provide `Conn_without_rcq` instead of NULL. Of course, when the definition does not have prestate having an implicit default is fine.
___
*[tests/unit/conn/conn-new.c, line 498 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfK6GtZ6VTrmqws_zSX:-MfK6GtZ6VTrmqws_zSY:b-mdn83w) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L498)):*
> ```C
> 	/* rpma_conn_new()/_delete() lifecycle */
> 	{"new_delete__without_rcq", conn_test_lifecycle,
> 		setup__conn_new, teardown__conn_delete, NULL},
> ```

Conn_without_rcq? I think have an explicit NULL here provides no information and takes more or less the same s
___
*[tests/unit/conn/conn-new.c, line 506 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKNsbkDn9d8HsMi81o:-MfKNsbkDn9d8HsMi81p:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L506)):*
> ```C
> 	cmocka_unit_test(delete__conn_NULL),
> 	{"delete__flush_delete_ERRNO__without_rcq",
> 		delete__flush_delete_ERRNO, NULL, NULL, NULL},
> ```

.
___
*[tests/unit/conn/conn-new.c, line 510 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKNt_k6JUBZuRsPOw7:-MfKNt_k6JUBZuRsPOw8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L510)):*
> ```C
> 		delete__flush_delete_ERRNO, NULL, NULL, &Conn_with_rcq},
> 	{"delete__flush_delete_E_INVAL__without_rcq",
> 		delete__flush_delete_E_INVAL, NULL, NULL, NULL},
> ```

.
___
*[tests/unit/conn/conn-new.c, line 513 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKO2aiBuxdse3fdF5j:-MfKO2aiBuxdse3fdF5k:b-8ujvta) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L513)):*
> ```C
> 	{"delete__flush_delete_E_INVAL__with_rcq",
> 		delete__flush_delete_E_INVAL, NULL, NULL, &Conn_with_rcq},
> 	cmocka_unit_test_prestate_setup_teardown(delete__rcq_delete_ERRNO,
> ```

Please put the name of the function in the next line. It will be easier to follow.
___
*[tests/unit/conn/conn-new.c, line 519 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKNw77Dui_megqmJjL:-MfKNw77Dui_megqmJjM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L519)):*
> ```C
> 		&Conn_with_rcq),
> 	{"delete__cq_delete_ERRNO__without_rcq",
> 		delete__cq_delete_ERRNO, NULL, NULL, NULL},
> ```

.
___
*[tests/unit/conn/conn-new.c, line 523 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKNxke6s72Wom7N7uy:-MfKNxke6s72Wom7N7uz:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L523)):*
> ```C
> 		delete__cq_delete_ERRNO, NULL, NULL, &Conn_with_rcq},
> 	{"delete__cq_delete_ERRNO_subsequent_ERRNO2__without_rcq",
> 		delete__cq_delete_ERRNO_subsequent_ERRNO2, NULL, NULL, NULL},
> ```

.
___
*[tests/unit/conn/conn-new.c, line 528 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKNz4O-CiYov4mQgBP:-MfKNz4O-CiYov4mQgBQ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn/conn-new.c#L528)):*
> ```C
> 		&Conn_with_rcq},
> 	{"delete__destroy_id_ERRNO__without_rcq",
> 		delete__destroy_id_ERRNO, NULL, NULL, NULL},
> ```

.


<!-- Sent from Reviewable.io -->

2021-07-23 22:30 UTC, janekmi requested changes
> Reviewed 1 of 34 files at r3, 2 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 57 of 63 files reviewed, 62 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-common.h, line 19 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKQuBw64cgbdarA4zn:-MfKQuBw64cgbdarA4zo:b3umiq) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn_req/conn_req-common.h#L19)):*
> ```objc
> #define MOCK_CONN_REQ		(struct rpma_conn_req *)0xC410
> #define MOCK_GET_RCQ(cstate)	((cstate)->get_cqe.rcq_size ? MOCK_RPMA_RCQ : \
> 				NULL)
> ```

I think it will be easier to follow this way:

```c
#define MOCK_GET_RCQ(cstate) \
	((cstate)->get_cqe.rcq_size ? MOCK_RPMA_RCQ : NULL)
```
___
*[tests/unit/conn_req/conn_req-common.h, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKRLB2-tHXCNMUd7Ly:-MfKRLB2-tHXCNMUd7Lz:b-p3rp6m) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn_req/conn_req-common.h#L22)):*
> ```objc
> #define MOCK_GET_CONN_CFG(cstate)	((cstate)->get_cqe.cfg == \
> 					MOCK_CONN_CFG_DEFAULT ? NULL : \
> 					(cstate)->get_cqe.cfg)
> ```

```c
#define MOCK_GET_CONN_CFG(cstate) \
	((cstate)->get_cqe.cfg == MOCK_CONN_CFG_DEFAULT ? \
			NULL : (cstate)->get_cqe.cfg)
```
?
___
*[tests/unit/conn_req/conn_req-common.c, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKTAnI2WevsaWW9JsC:-MfKTAnI2WevsaWW9JsD:b-gxc7e8) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn_req/conn_req-common.c#L45)):*
> ```C
> 
> /*
>  * configure_conn_req_new -- configure a conn_req_new_test_state object
> ```

configure prestate for rpma_conn_req_new()
___
*[tests/unit/conn_req/conn_req-common.c, line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKTJcx6WCwmIC1Fw4V:-MfKTJcx6WCwmIC1Fw4W:b-e2mb6u) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn_req/conn_req-common.c#L61)):*
> ```C
> 
> /*
>  * configure_conn_req -- configure a conn_req_test_state object
> ```

configure prestate for rpma_conn_req_connect()
___
*[tests/unit/conn_req/conn_req-common.c, line 191 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfKUKDf5GfLZFHt3MKX:-MfKUKDf5GfLZFHt3MKY:bkt2oop) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/tests/unit/conn_req/conn_req-common.c#L191)):*
> ```C
> 	assert_non_null(cstate->req);
> 
> 	*cstate_ptr = cstate;
> ```

Is it really needed?


<!-- Sent from Reviewable.io -->

2021-07-26 06:19 UTC, ldorau reviewed
> Reviewed 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 47 of 63 files reviewed, 51 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 06:27 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 47 of 63 files reviewed, 52 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 187 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJVgq4AlcX3iLnEmz1:-MfW4_OlCYhE_DhfbPnP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`goto err_peer_delete`
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 273 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJWJ5o8NA89SeZy6JX:-MfW4ayQDlSnsa7rSwHS:b-g4p7ox) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L273)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since we have a receive CQ I am voting for `the send completion`.  What do you think?
</blockquote></details>

Done.  Agreed.
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 352 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJVqlEDSz3HcfmruDi:-MfW4fYhAWx1oCsJcW8s:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/client.c#L352)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The config is created **after** the peer. So it has to be destroyed **before** it.
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 215 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJXO9D0QiUU7iKlVH4:-MfW4ghq4ooLOegAHUEx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/server.c#L215)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`goto err_cfg_delete`
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 297 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJXZmcAQl8s1liXdrb:-MfW4hHJ83BgkfQ0QM6E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/server.c#L297)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`the send completion`?
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 306 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJXdM5BjrMV3BCZQmo:-MfW4iXLCR4jRiBBdg7_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/examples/09-flush-to-persistent-GPSPM/server.c#L306)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/conn.c, line 26 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJcsiM5FIFC_Gnk7-u:-MfW4k6z2vrPbBHamVqR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn.c#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`the main CQ` to follow the documentation.
</blockquote></details>

Done.
___
*[src/conn.c, line 27 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJcvogAghWdTzqgp_9:-MfW4kP87J71t-CHilp6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn.c#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`the receive CQ` .
</blockquote></details>

Done.
___
*[src/conn.c, line 285 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJdoYqDOwBzGy3HNfw:-MfW4lv29tokOhIuoHpf:b-j6yrpl) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn.c#L285)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems we attempt to destroy the ID without even trying to call `rdma_destroy_qp()` in case of an error. Despite it is required.

Ref: https://linux.die.net/man/3/rdma_destroy_id

We need an issue for this and a fix soon afterwards. ;-)
</blockquote></details>

Done.  See #1160 
___
*[src/conn_cfg.h, line 28 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJeYNn-7aKmQrHnn2v:-MfW4quq7aDol9ix0Z2j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.h#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too many new lines.
</blockquote></details>

Done.
___
*[src/conn_cfg.c, line 29 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJewT_0cpu7fXxFqxp:-MfW4sGv6e_1rC6FngMO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> The default size of the receive CQ is 0, which means no receive CQ is created for the connection.

- **Note** the full stop at the end of the sentence. ;-)
</blockquote></details>

Done.
___
*[src/conn_cfg.c, line 30 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJf9XXBEpHwOlY22DD:-MfW4tIA1WDe9g4_GBf1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment fits into a single line. At least before my comment. ;-)
</blockquote></details>

Done.
___
*[src/conn_cfg.c, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJfoXE48AqRJONrbgb:-MfW4uKRCAQwhxj_Zwjd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_cfg.c#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`main CQ size`
</blockquote></details>

Done.
___
*[src/conn_req.c, line 31 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgR6a5kSulMy0Ke3G:-MfW4vBK7VOvXhYvfKAw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

main CQ
</blockquote></details>

Done.
___
*[src/conn_req.c, line 33 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgT1a8P2bgxpXOyvh:-MfW4vRf8aIItRu3xTWq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

receive CQ
</blockquote></details>

Done.
___
*[src/conn_req.c, line 57 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgf7l91JzpxwmrV2A:-MfW4wKsDyiLi9Br--Au:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

main CQ
</blockquote></details>

Done.
___
*[src/conn_req.c, line 205 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJkgcu1XcL3rztFtRv:-MfW4yIy3v-3bBr5a6GI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L205)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think these lines should be grouped as follow:

```c
	int ret = rpma_cq_delete(&req->rcq);

	int ret2 = rpma_cq_delete(&req->cq);
	if (!ret && ret2)
		ret = ret2;
```

Because the first `rpma_cq_delete()` stands on its own. The return value is stored. The processing should be continued no matter what.
Whereas the second call to `rpma_cq_delete()` stores the result in a separate variable to follow the  [...]

2021-07-26 06:28 UTC, ldorau reviewed
> Reviewed 2 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 49 of 63 files reviewed, 52 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/conn_req.c, line 57 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgf7l91JzpxwmrV2A:-MfWTsvU0k0kEE9l82dP:bw6016j) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L57)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

read **the** main ...


<!-- Sent from Reviewable.io -->

2021-07-26 06:30 UTC, ldorau reviewed
> Reviewed 1 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 50 of 63 files reviewed, 52 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-26 07:50 UTC, janekmi requested changes
> Reviewed 1 of 14 files at r6, 10 of 11 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 59 of 63 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[src/conn_req.c, line 57 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgf7l91JzpxwmrV2A:-MfWiA2o1RCsWiFody-f:bh98lhs) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

read **the** main ...
</blockquote></details>

:+1:  @ldorau 
___
*[src/conn_req.c, line 59 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWiCFS5qZB8ZfqmiTb:-MfWiCFS5qZB8ZfqmiTc:bjojqoc) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/src/conn_req.c#L59)):*
> ```C
> 	/* read main CQ size from the configuration */
> 	(void) rpma_conn_cfg_get_cqe(cfg, &cqe);
> 	/* read receive CQ size from the configuration */
> ```

the receive CQ size...
___
*[src/include/librpma.h, line 2694 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJzib-DEwMXUwSZVQE:-MfWijr11zYhf2haISU8:b-fqpmt1) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/include/librpma.h#L2694)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry. I mean all:

```
 * All operations generate completion on error. The operations
 * posted with the **RPMA_F_COMPLETION_ALWAYS** flag also generate a completion
 * on success.
 * The following operations are available:
 * - RPMA_OP_READ - RMA read operation
 * - RPMA_OP_WRITE - RMA write operation
 * - RPMA_OP_FLUSH - RMA flush operation
 * - RPMA_OP_SEND - messaging send operation
 * - RPMA_OP_RECV - messaging receive operation
 * - RPMA_OP_RECV_RDMA_WITH_IMM - messaging receive operation for
 *   RMA write operation with immediate data

```
___
*[src/include/librpma.h, line 2731 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJvbkv3-ZkbBnCXcfh:-MfWlePVCmW6pfiz741i:b7gq2ri) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/include/librpma.h#L2731)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.  not only main CQ but also receive CQ so use `gets the completion file descriptor of the connection` instead.
</blockquote></details>

You are right. But I would say:

... the completion file descriptor of the CQ, either for the connection's main CQ or the receive CQ. For details please see rpma_conn_get_cq(3) and rpma_conn_get_rcq(3).
___
*[tests/unit/conn_req/conn_req-common.h, line 18 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWh0HT62zZRMHguw2g:-MfWh0HT62zZRMHguw2h:bsa7dqc) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-common.h#L18)):*
> ```objc
> 
> #define MOCK_CONN_REQ		(struct rpma_conn_req *)0xC410
> #define MOCK_GET_RCQ(cstate)	\
> ```

Space instead of a tab.
___
*[tests/unit/conn_req/conn_req-common.h, line 20 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWh7U851vhunYUIMck:-MfWh7U851vhunYUIMcl:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-common.h#L20)):*
> ```objc
> #define MOCK_GET_RCQ(cstate)	\
> 	((cstate)->get_cqe.rcq_size ? MOCK_RPMA_RCQ : NULL)
> #define MOCK_GET_CONN_CFG(cstate)	\
> ```

.
___
*[tests/unit/conn_req/conn_req-new.c, line 487 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWTxM_BpnPaG-7NBGN:-MfWmXvKDEluNy3mMMmP:bllzzok) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-new.c#L487)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

Do you want to use `&Conn_req_new_conn_cfg_default` instead of NULL here? 
</blockquote></details>

Yes, please. :-)
___
*[tests/unit/peer/peer-create_qp.c, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHnIXR-Z8p667NRPeU:-MfWmkxj7IRmeguJq2dh:bocqgy7) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/peer/peer-create_qp.c#L39)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

rdma_create_qp()


<!-- Sent from Reviewable.io -->

2021-07-26 08:33 UTC, ldorau reviewed
> Reviewed 1 of 14 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 60 of 63 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 08:57 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 54 of 63 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/conn_req.c, line 57 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJgf7l91JzpxwmrV2A:-MfX0nu00s5VqkCr1-nQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/conn_req.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1:  @ldorau 
</blockquote></details>

Done.
___
*[src/conn_req.c, line 59 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWiCFS5qZB8ZfqmiTb:-MfX0oPz6lE98nVYPOo8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/src/conn_req.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the receive CQ size...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2694 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJzib-DEwMXUwSZVQE:-MfX0r6J2dKCBsYvda4O:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/include/librpma.h#L2694)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sorry. I mean all:

```
 * All operations generate completion on error. The operations
 * posted with the **RPMA_F_COMPLETION_ALWAYS** flag also generate a completion
 * on success.
 * The following operations are available:
 * - RPMA_OP_READ - RMA read operation
 * - RPMA_OP_WRITE - RMA write operation
 * - RPMA_OP_FLUSH - RMA flush operation
 * - RPMA_OP_SEND - messaging send operation
 * - RPMA_OP_RECV - messaging receive operation
 * - RPMA_OP_RECV_RDMA_WITH_IMM - messaging receive operation for
 *   RMA write operation with immediate data

```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2731 at r6](https://reviewable.io/reviews/pmem/rpma/1080#-MfJvbkv3-ZkbBnCXcfh:-MfX0tuw5yxGWW0Oa1PB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8959792e55a10af7a7254bd7622025bf56b54361/src/include/librpma.h#L2731)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are right. But I would say:

... the completion file descriptor of the CQ, either for the connection's main CQ or the receive CQ. For details please see rpma_conn_get_cq(3) and rpma_conn_get_rcq(3).
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-common.h, line 18 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWh0HT62zZRMHguw2g:-MfX0uww2j4vW47keXM3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-common.h#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Space instead of a tab.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-common.h, line 20 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWh7U851vhunYUIMck:-MfX0vNW6HgThgUoNYQK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-common.h#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 487 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWTxM_BpnPaG-7NBGN:-MfX0wWo1S_m-l7_BBtT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-new.c#L487)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes, please. :-)
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-create_qp.c, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1080#-MfHnIXR-Z8p667NRPeU:-MfX0zFG2cawNdl2hxia:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c02296e4c1333b0dfd8a549ac5e3e189362755ff/tests/unit/peer/peer-create_qp.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rdma_create_qp()
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 08:58 UTC, ldorau reviewed
> Reviewed 3 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 57 of 63 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-26 09:00 UTC, ldorau reviewed
> Reviewed 3 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 60 of 63 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-26 10:44 UTC, ldorau requested changes
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 61 of 63 files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-new.c, line 214 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXPI1X2xa8SActgbTM:-MfXPI1X2xa8SActgbTN:b-duo32l) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L214)):*
> ```
> *cstate = &Conn_req_new_conn_cfg_default;
> ```

It should be done via prestate like in `new__rcq_new_ERRNO` for example


<!-- Sent from Reviewable.io -->

2021-07-26 10:47 UTC, ldorau requested changes
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 62 of 63 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-private_data.c, line 104 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXQ1WxDLVq7vFPCSia:-MfXQ1Wy3MRbyjwLtpLy:beed95e) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-private_data.c#L104)):*
> ```
> cmocka_unit_test(get_private_data__conn_req_NULL),
> ```

Make it the first one (move it to the beginning), please.


<!-- Sent from Reviewable.io -->

2021-07-26 11:03 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 62 of 63 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-connect.c, line 592 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWsQhO3yXfQBT_sRak:-MfWsQhO3yXfQBT_sRal:b-d2y1ul) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-connect.c#L592)):*
> ```C
> 		teardown__conn_req_from_cm_event),
> 	/* connect via rdma_accept() */
> 	{"connect_via_accept__accept_ERRNO__withou_rcq",
> ```

without
___
*[tests/unit/conn_req/conn_req-connect.c, line 593 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWsC3y-hMd-okna-5k:-MfWsC3y-hMd-okna-5l:b-odn8s2) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-connect.c#L593)):*
> ```C
> 	/* connect via rdma_accept() */
> 	{"connect_via_accept__accept_ERRNO__withou_rcq",
> 		connect_via_accept__accept_ERRNO, NULL, NULL, NULL},
> ```

`&Conn_req_conn_cfg_default`

Please apply to all.
___
*[tests/unit/conn_req/conn_req-connect.c, line 634 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWsdqC9adPJrW-MeVW:-MfWsdqC9adPJrW-MeVX:bb7r32j) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-connect.c#L634)):*
> ```C
> 	{"connect_via_connect__connect_ERRNO__without_rcq",
> 		connect_via_connect__connect_ERRNO, NULL, NULL, NULL},
> 	{"connect_via_connect__connect_ERRNO__without_rcq",
> ```

with


<!-- Sent from Reviewable.io -->

2021-07-26 11:14 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 62 of 63 files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-connect.c, line 598 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXW5J46iJV5Whr3Hg2:-MfXW5J46iJV5Whr3Hg3:b-xpjcgn) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L598)):*
> ```C
> 	{"connect_via_accept__accept_ERRNO__with_rcq",
> 		connect_via_accept__accept_ERRNO, NULL, NULL,
> 		&Conn_req_conn_cfg_custom},
> ```

I think we can make use of small macro-magic and increase readability and maintainability. What do you think?

```c
#define CONN_REQ_TEST_WITH_AND_WITHOUT_RCQ(test_func) \
	{#test_func "__without_rcq", \
		(test_func), NULL, NULL, &Conn_req_conn_cfg_default}, \
	{#test_func "__with_rcq", \
		(test_func), NULL, NULL, &Conn_req_conn_cfg_custom}
```


<!-- Sent from Reviewable.io -->

2021-07-26 11:41 UTC, ldorau reviewed
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 11:46 UTC, ldorau reviewed
> Reviewed 1 of 59 files at r1, 2 of 34 files at r3, 2 of 14 files at r6, 2 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 11:47 UTC, janekmi requested changes
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 23 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-connect.c, line 178 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXaIcq0Zq1qvcZKjPL:-MfXaIcq0Zq1qvcZKjPM:bb70gss) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L178)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

NULL
___
*[tests/unit/conn_req/conn_req-connect.c, line 178 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXc4eP2nbe9ieef1mT:-MfXaL8I4dD0lsdaqoNa:b-lvupuf) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L178)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

`can not fail` ?
___
*[tests/unit/conn_req/conn_req-connect.c, line 256 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXabCy9FR6CEpgnKAd:-MfXabCy9FR6CEpgnKAe:bb70gss) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L256)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

NULL
___
*[tests/unit/conn_req/conn_req-connect.c, line 256 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXac9k57YWv36Ox6Rp:-MfXac9k57YWv36Ox6Rq:b-bmvm3q) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L256)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

an error
___
*[tests/unit/conn_req/conn_req-connect.c, line 262 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXcU2c28ySFd1O6KOd:-MfXcU2c28ySFd1O6KOe:b-o6tqb2) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L262)):*
> ```C
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_delete, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> ```

or fourth
___
*[tests/unit/conn_req/conn_req-connect.c, line 345 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXb1FF5bUpsL3fGEl4:-MfXb1FF5bUpsL3fGEl5:b2ngvbr) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L345)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

. .
___
*[tests/unit/conn_req/conn_req-connect.c, line 351 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXcf6kBqpRe5NXVeo3:-MfXcf6kBqpRe5NXVeo4:b-qpj9nl) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L351)):*
> ```C
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_delete, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_delete, MOCK_ERRNO2); /* third or fouth error */
> ```

fourth
___
*[tests/unit/conn_req/conn_req-connect.c, line 523 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXbGIU-Pv8iv05qz_V:-MfXbGIU-Pv8iv05qz_W:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L523)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* second error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

.


<!-- Sent from Reviewable.io -->

2021-07-26 11:48 UTC, ldorau reviewed
> Reviewed 3 of 59 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 23 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 11:49 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 25 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-connect.c, line 256 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdEL-0vor6Ztaybah:-MfXdEL-0vor6Ztaybai:b-lvupuf) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L256)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

`can not fail` ?
___
*[tests/unit/conn_req/conn_req-connect.c, line 345 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdK2Q4FeBAl96KmhS:-MfXdK2Q4FeBAl96KmhT:b-lvupuf) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L345)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* third error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

`can not fail` ?
___
*[tests/unit/conn_req/conn_req-connect.c, line 523 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdMFx1Omz0apUqazI:-MfXdMFx1Omz0apUqazJ:b-lvupuf) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L523)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* second error */
> 	} else {
> 		/* rcq == NULl has no chance to get a error */
> ```

`can not fail` ?


<!-- Sent from Reviewable.io -->

2021-07-26 11:51 UTC, janekmi requested changes
> Reviewed 4 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-delete.c, line 441 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdpgm6Ug9nrWq-Nxi:-MfXdpgn9shpQU_IRQRH:bwd6lqv) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-delete.c#L441)):*
> ```C
> 	{"delete_via_reject__cq_delete_ERRNO__with_rcq",
> 		delete_via_reject__cq_delete_ERRNO, NULL, NULL,
> 		&Conn_req_conn_cfg_custom},
> ```

Can we use a small macro-magic? :-)


<!-- Sent from Reviewable.io -->

2021-07-26 11:52 UTC, janekmi reviewed
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 12:23 UTC, ldorau requested changes
> Reviewed 1 of 59 files at r1, 2 of 11 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 19 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 413 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXkALD3aqrDKQNjCQJ:-MfXkALD3aqrDKQNjCQK:blilpkg) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn/conn-new.c#L413)):*
> ```
> rdma_destroy_id())
> ```

`rdma_destroy_id()`


<!-- Sent from Reviewable.io -->

2021-07-26 12:43 UTC, ldorau reviewed
> Reviewed 2 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 19 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 12:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 19 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-connect.c, line 178 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXc4eP2nbe9ieef1mT:-MfXqHfI0ChhBgTQEDmc:bppqty8) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L178)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`can not fail` ?
</blockquote></details>

`cannot fail`
___
*[tests/unit/conn_req/conn_req-connect.c, line 256 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdEL-0vor6Ztaybah:-MfXqPq7Ch8cwZIp1eQB:bppqty8) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L256)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`can not fail` ?
</blockquote></details>

`cannot fail`
___
*[tests/unit/conn_req/conn_req-connect.c, line 345 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdK2Q4FeBAl96KmhS:-MfXqVN_38wUpph8PqDI:bppqty8) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L345)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`can not fail` ?
</blockquote></details>

`cannot fail`
___
*[tests/unit/conn_req/conn_req-connect.c, line 523 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdMFx1Omz0apUqazI:-MfXqY7R2fz1ktPHX716:bppqty8) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L523)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`can not fail` ?
</blockquote></details>

`cannot fail`


<!-- Sent from Reviewable.io -->

2021-07-26 13:08 UTC, janekmi requested changes
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 27 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-common.c, line 64 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXsCGGBlozz6GIN-fM:-MfXsCGGBlozz6GIN-fN:b-fgh441) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L64)):*
> ```C
>  */
> void
> configure_conn_req(void **cstate_ptr)
> ```

It is not common. It is a part of `conn_req-from_cm_event.c`.
___
*[tests/unit/conn_req/conn_req-common.c, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXqPQNBMXM6-spJptm:-MfXqPQO3OJS2612TAAv:b-lhhwai) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L70)):*
> ```C
> 			*cstate_ptr : &Conn_req_conn_cfg_default;
> 
> 	cstate->event.event = RDMA_CM_EVENT_CONNECT_REQUEST;
> ```

Is this variable set to any other value?
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 303 at r1](https://reviewable.io/reviews/pmem/rpma/1080#-MfXvN3m9Aq6ms25IRsk:-MfXvN3m9Aq6ms25IRsl:b-sqjcki) ([raw file](https://github.com/pmem/rpma/blob/07c8d2da13207682529a3cb2e985520dd377ac3a/tests/unit/conn_req/conn_req-from_cm_event.c#L303)):*
> ```C
> 	assert_int_equal(ret, RPMA_E_NOMEM);
> 	assert_null(req);
> }
> ```

A test case where subsequent will fail is missing.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 104 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXp41_2GCnr02AcGgm:-MfXp41_2GCnr02AcGgn:bfabvkx) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-from_cm_event.c#L104)):*
> ```C
> from_cm_event__cq_new_ERRNO(void **unused)
> {
> 	struct conn_req_test_state *cstate = &Conn_req_conn_cfg_default;
> ```

I think this test should be run in both variants. I can imagine an implementation that will mess up both cqe values.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 131 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXrTOt1QvQX0A2Gncy:-MfXrTOt1QvQX0A2Gncz:bjl5b7) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-from_cm_event.c#L131)):*
> ```C
> from_cm_event__rcq_new_ERRNO(void **unused)
> {
> 	struct conn_req_test_state *cstate = &Conn_req_conn_cfg_custom;
> ```

I know it is obvious now but I think it may somebody save some time in the future if you put here a comment e.g.
`rpma_cq_new(rcqe) is called only when rcqe > 0`
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 225 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXqdxG9imquTEFP5Vt:-MfXqdxG9imquTEFP5Vu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-from_cm_event.c#L225)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* second error */
> 	} else {
> 		/* rcq == NULL has no chance to get a error */
> ```

.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 355 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXuwkFEnWCb44mDEs9:-MfXuwkFEnWCb44mDEsA:b-oyfr25) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-from_cm_event.c#L355)):*
> ```C
> 	will_return(rpma_peer_create_qp, MOCK_OK);
> 	will_return(__wrap__test_malloc, MOCK_OK);
> 	will_return(rpma_private_data_store, NULL);
> ```

`/* RPMA_E_NOMEM */` Please give here a comment. It took me some time to understand what is going on here. ;-)
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 403 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXhy_vDMP5UrROKyZY:-MfXhy_vDMP5UrROKyZZ:b-obu3wa) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-from_cm_event.c#L403)):*
> ```C
> 	{"from_cm_event__peer_create_qp_ERRNO__with_rcq",
> 		from_cm_event__peer_create_qp_ERRNO, NULL, NULL,
> 		&Conn_req_conn_cfg_custom},
> ```

A small macro-magic? :-)


<!-- Sent from Reviewable.io -->

2021-07-26 15:01 UTC, janekmi requested changes
> Reviewed 1 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 54 of 63 files reviewed, 37 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-common.c, line 48 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXw2GF8pRPZPzYFSJ8:-MfXw2GGBe7CNOMWNH1l:bvmf75k) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L48)):*
> ```C
>  */
> void
> configure_conn_req_new(void **cstate_ptr)
> ```

It belongs to `conn_req-new.c`.
___
*[tests/unit/conn_req/conn_req-common.c, line 55 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXwRRR11BL5TEGiQTp:-MfXwRRR11BL5TEGiQTq:b-q3ang6) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L55)):*
> ```C
> 
> 	cstate->id.verbs = MOCK_VERBS;
> 	cstate->id.qp = MOCK_QP;
> ```

It seems it is achievable during the initialization. :thinking: 
___
*[tests/unit/conn_req/conn_req-common.c, line 72 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXwej2AbS1AGnNR-qO:-MfXwej2AbS1AGnNR-qP:b-criodp) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L72)):*
> ```C
> 	cstate->event.event = RDMA_CM_EVENT_CONNECT_REQUEST;
> 	cstate->id.verbs = MOCK_VERBS;
> 	cstate->event.id = &cstate->id;
> ```

Same here. Why it is a function? Except for providing a default prestate object.
___
*[tests/unit/conn_req/conn_req-new.c, line 161 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfY-PLs6n0E6jL8n0Zv:-MfY-PLs6n0E6jL8n0Zw:b-ugaivz) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L161)):*
> ```C
> 	will_return(rpma_info_resolve_addr, RPMA_E_PROVIDER);
> 	will_return(rpma_info_resolve_addr, MOCK_ERRNO);
> 	will_return(rdma_destroy_id, MOCK_OK);
> ```

A subsequent fail test case is missing.
___
*[tests/unit/conn_req/conn_req-new.c, line 196 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfY-aG-2oEVQmc4zLWv:-MfY-aG-2oEVQmc4zLWw:b-ugaivz) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L196)):*
> ```C
> 	expect_value(rdma_resolve_route, timeout_ms, RPMA_DEFAULT_TIMEOUT_MS);
> 	will_return(rdma_resolve_route, MOCK_ERRNO);
> 	will_return(rdma_destroy_id, MOCK_OK);
> ```

A subsequent fail test case is missing.
___
*[tests/unit/conn_req/conn_req-new.c, line 214 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXPI1X2xa8SActgbTM:-MfXx875Ac7ppfOz8sxx:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L214)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> *cstate = &Conn_req_new_conn_cfg_default;
> ```

It should be done via prestate like in `new__rcq_new_ERRNO` for example
</blockquote></details>

:+1: 
___
*[tests/unit/conn_req/conn_req-new.c, line 237 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxO10E-6UGzWbteHR:-MfXxO11DXDly9pHl-pR:bdajxbf) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L237)):*
> ```C
> 	will_return(rpma_cq_new, RPMA_E_PROVIDER);
> 	will_return(rpma_cq_new, MOCK_ERRNO);
> 	will_return(rdma_destroy_id, MOCK_OK);
> ```

A test where subsequent fails is missing.
___
*[tests/unit/conn_req/conn_req-new.c, line 282 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxTjx5GCHH2CfniEd:-MfXxTjx5GCHH2CfniEe:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L282)):*
> ```C
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_delete, MOCK_OK);
> 	will_return(rdma_destroy_id, MOCK_OK);
> ```

.
___
*[tests/unit/conn_req/conn_req-new.c, line 335 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxdadCF2qQ1YQ95X3:-MfXxdadCF2qQ1YQ95X4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L335)):*
> ```C
> 	expect_value(rpma_cq_delete, *cq_ptr, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_delete, MOCK_OK);
> 	will_return(rdma_destroy_id, MOCK_OK);
> ```

.
___
*[tests/unit/conn_req/conn_req-new.c, line 443 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxuraEGn4fYjstVsE:-MfXxuraEGn4fYjstVsF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L443)):*
> ```C
> 		will_return(rpma_cq_delete, MOCK_ERRNO2); /* second error */
> 	} else {
> 		/* rcq == NULL has no chance to get a error */
> ```

.
___
*[tests/unit/conn_req/conn_req-new.c, line 491 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxziT2O3JvX_vgAZ_:-MfXxziT2O3JvX_vgAZa:b-jzlbow) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L491)):*
> ```C
> 	{"new__peer_create_qp_ERRNO__with_rcq",
> 		new__peer_create_qp_ERRNO, NULL, NULL,
> 		&Conn_req_new_conn_cfg_custom},
> ```

A small macro-magic?


<!-- Sent from Reviewable.io -->

2021-07-26 15:21 UTC, janekmi requested changes
> Reviewed 6 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 60 of 63 files reviewed, 18 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn/conn-common.h, line 21 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYLOmcCip9h-opyvI8:-MfYLOmcCip9h-opyvI9:bix9qyx) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn/conn-common.h#L21)):*
> ```objc
> 		RPMA_ATOMIC_WRITE_ALIGNMENT) * RPMA_ATOMIC_WRITE_ALIGNMENT)
> #define MOCK_FD			0x00FD
> #define CONN_TEST_WITH_AND_WITHOUT_RCQ(test_func, setup_func, teardown_func) \
> ```

Do `setup_func` or `teardown_func` can be anything else than NULL?
___
*[tests/unit/conn_req/conn_req-common.h, line 24 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYLlHH4dJu9RtMcTnL:-MfYLlHH4dJu9RtMcTnM:b-nsovui) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-common.h#L24)):*
> ```objc
> 			NULL : (cstate)->get_cqe.cfg)
> #define CONN_REQ_NEW_TEST_WITH_AND_WITHOUT_RCQ(test_func, setup_func, \
> 		teardown_func) \
> ```

Can setup_func or teardown_func be anything else than NULL?
___
*[tests/unit/conn_req/conn_req-common.h, line 34 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYMVuQ4QzCXRlmKG3X:-MfYMVuQ4QzCXRlmKG3Y:b-tn44av) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-common.h#L34)):*
> ```objc
> 		(teardown_func), &Conn_req_conn_cfg_default}, \
> 	{#test_func "__with_rcq", (test_func), (setup_func), \
> 		(teardown_func), &Conn_req_conn_cfg_custom}
> ```

Same here. If I see correctly, there is one place where these functions are != NULL.
So for this macro I recommend doing something like this:

```c
#define CONN_REQ_SETUP_TEST_TEARDOWN_WITH_AND_WITHOUT_RCQ(test_func, setup_func, \
		teardown_func) \
	{#test_func "__without_rcq", (test_func), (setup_func), \
		(teardown_func), &Conn_req_conn_cfg_default}, \
	{#test_func "__with_rcq", (test_func), (setup_func), \
		(teardown_func), &Conn_req_conn_cfg_custom}
#define CONN_REQ_TEST_WITH_AND_WITHOUT_RCQ(test_func) \
	CONN_REQ_SETUP_TEST_TEARDOWN_WITH_AND_WITHOUT_RCQ(test_func, NULL, NULL)
```

Where `CONN_REQ_TEST_WITH_AND_WITHOUT_RCQ()` is used pretty much everywhere and `CONN_REQ_SETUP_TEST_TEARDOWN_WITH_AND_WITHOUT_RCQ()` is used in this single place where it is needed.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 362 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYO2sH1biZZr7S7Dsp:-MfYO2sH1biZZr7S7Dsq:b-un2b6y) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-from_cm_event.c#L362)):*
> ```C
> 	expect_value(rdma_destroy_id, id, &cstate->id);
> 	will_return(rdma_destroy_id, MOCK_OK);
> 	expect_function_call(rpma_private_data_discard);
> ```

A new line is missing.


<!-- Sent from Reviewable.io -->

2021-07-26 15:24 UTC, janekmi reviewed
> Reviewed 1 of 34 files at r3, 3 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72, @ldorau, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 15:33 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 413 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXkALD3aqrDKQNjCQJ:-MfYRoZbEVTud7yVn-Pk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn/conn-new.c#L413)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rdma_destroy_id())
> ```

`rdma_destroy_id()`
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-common.h, line 34 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYMVuQ4QzCXRlmKG3X:-MfYREbY1rC1rEpEyb_9:bvovf4g) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-common.h#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. If I see correctly, there is one place where these functions are != NULL.
So for this macro I recommend doing something like this:

```c
#define CONN_REQ_SETUP_TEST_TEARDOWN_WITH_AND_WITHOUT_RCQ(test_func, setup_func, \
		teardown_func) \
	{#test_func "__without_rcq", (test_func), (setup_func), \
		(teardown_func), &Conn_req_conn_cfg_default}, \
	{#test_func "__with_rcq", (test_func), (setup_func), \
		(teardown_func), &Conn_req_conn_cfg_custom}
#define CONN_REQ_TEST_WITH_AND_WITHOUT_RCQ(test_func) \
	CONN_REQ_SETUP_TEST_TEARDOWN_WITH_AND_WITHOUT_RCQ(test_func, NULL, NULL)
```

Where `CONN_REQ_TEST_WITH_AND_WITHOUT_RCQ()` is used pretty much everywhere and `CONN_REQ_SETUP_TEST_TEARDOWN_WITH_AND_WITHOUT_RCQ()` is used in this single place where it is needed.
</blockquote></details>

We need to define four macros? is it too many?
___
*[tests/unit/conn_req/conn_req-common.c, line 48 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXw2GF8pRPZPzYFSJ8:-MfYNi0r28v3MYGtpiuT:b-2lrwfz) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It belongs to `conn_req-new.c`.
</blockquote></details>

No, It is used by conn_req-new.c and conn_req-common.c.
___
*[tests/unit/conn_req/conn_req-common.c, line 55 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXwRRR11BL5TEGiQTp:-MfYO0nR2OJs932cyYLN:b5q7m6i) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems it is achievable during the initialization. :thinking: 
</blockquote></details>

What do you want to do?
___
*[tests/unit/conn_req/conn_req-common.c, line 64 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXsCGGBlozz6GIN-fM:-MfYO8jH2M7mp-BBWT6s:b8xhzqf) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not common. It is a part of `conn_req-from_cm_event.c`.
</blockquote></details>

No, It is used by conn_req-from_cm_event.c and conn_req-common.c.
___
*[tests/unit/conn_req/conn_req-common.c, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXqPQNBMXM6-spJptm:-MfYOD1L7GEjvm0495Q1:bx6eqil) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is this variable set to any other value?
</blockquote></details>

We have two different prestate objects(with and without rcq), I don't want to set these value twice. I can do it if you want.
___
*[tests/unit/conn_req/conn_req-common.c, line 72 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXwej2AbS1AGnNR-qO:-MfYQ40AD47hvCtGdEX6:b7lxuhz) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L72)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. Why it is a function? Except for providing a default prestate object.
</blockquote></details>

We have two different prestate objects(with and without rcq), I don't want to set these value twice.
I can do it if you want.
___
*[tests/unit/conn_req/conn_req-connect.c, line 592 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWsQhO3yXfQBT_sRak:-MfYOofQ4XgGX5JP5s2f:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-connect.c#L592)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

without
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 593 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWsC3y-hMd-okna-5k:-MfYOp5aCbDLPeZwyH1d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-connect.c#L593)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`&Conn_req_conn_cfg_default`

Please apply to all.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 634 at r8](https://reviewable.io/reviews/pmem/rpma/1080#-MfWsdqC9adPJrW-MeVW:-MfYP0Y60goJFqBZ6jLX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8151125e30dda6c8e2b70613ee3434bd198bbde3/tests/unit/conn_req/conn_req-connect.c#L634)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

with
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 178 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXaIcq0Zq1qvcZKjPL:-MfYOgUp25t-H8ZZrkQq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L178)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

NULL
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 178 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXc4eP2nbe9ieef1mT:-MfYOgpCCzfTgYjT9Xqb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L178)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`cannot fail`
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 256 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXabCy9FR6CEpgnKAd:-MfYOhidBYjrBAAONBRZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L256)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

NULL
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 256 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXdEL-0vor6Ztaybah:-MfYOiZ_AbcsMdKHZFyA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L256)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`cannot fail`
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 262 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXcU2c28ySFd1O6KOd:-MfYOjM42FirKq7bh6g6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-connect.c#L262)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

or fourth
</blockquote></details>

Done.
_ [...]

2021-07-26 16:14 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-common.h, line 34 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYMVuQ4QzCXRlmKG3X:-MfY_5uOAlvXydF5hiFE:bw7pub7) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-common.h#L34)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

We need to define four macros? is it too many?
</blockquote></details>

I prefer having four macros (where two of them are really small) than having `NULL, NULL` all over the place. ;-)
___
*[tests/unit/conn_req/conn_req-common.c, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXqPQNBMXM6-spJptm:-MfY_e76-MztwUH_vzjT:bm3jn2n) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L70)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

We have two different prestate objects(with and without rcq), I don't want to set these value twice. I can do it if you want.
</blockquote></details>

If `RDMA_CM_EVENT_CONNECT_REQUEST` is the only value there is no point in passing it by prestate, isn't it?


<!-- Sent from Reviewable.io -->

2021-07-27 03:31 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[tests/unit/conn_req/conn_req-common.c, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXqPQNBMXM6-spJptm:-Mfa-lAT5B69mNkpPvLu:b6xjx2z) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If `RDMA_CM_EVENT_CONNECT_REQUEST` is the only value there is no point in passing it by prestate, isn't it?
</blockquote></details>

Where do you want to define/set it?
___
*[tests/unit/conn_req/conn_req-new.c, line 237 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxO10E-6UGzWbteHR:-Mf_vBzwAjzmERXzf8ce:b8nhppr) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L237)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A test where subsequent fails is missing.
</blockquote></details>

These unit tests are missing for a long time and they are not related to seperate receive CQ.
I would like to add them on the seperate PR.  Do you think so?


<!-- Sent from Reviewable.io -->

2021-07-27 03:50 UTC, yangx-jy commented
___
*[tests/unit/conn_req/conn_req-new.c, line 237 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxO10E-6UGzWbteHR:-Mfa3qSP4oHAm24_pXcK:bqai6xw) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L237)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

These unit tests are missing for a long time and they are not related to seperate receive CQ.
I would like to add them on the seperate PR.  Do you think so?
</blockquote></details>

Sorry, only unit tests about `resolve_addr` and `resolve_route` are not related to seperate receive CQ.


<!-- Sent from Reviewable.io -->

2021-07-27 05:36 UTC, ldorau reviewed
> Reviewed 9 of 9 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-27 05:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1080#-MfaSp_89JURvQWsQHA0:-MfaSp_89JURvQWsQHA1:bcjzgpl) (no related file):*
Please rebase - there is a merge conflict.

---


<!-- Sent from Reviewable.io -->

2021-07-27 06:37 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 53 of 63 files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1080#-MfaSp_89JURvQWsQHA0:-MfaeXYJ5j3_xgPIH6I9:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase - there is a merge conflict.
</blockquote></details>

Done.

---
___
*[tests/unit/conn/conn-common.h, line 21 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYLOmcCip9h-opyvI8:-Mfae_Wi1Ql5hnezpD6X:blno2xb) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn/conn-common.h#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do `setup_func` or `teardown_func` can be anything else than NULL?
</blockquote></details>

Done. Define four macros as you suggested.
___
*[tests/unit/conn_req/conn_req-common.h, line 24 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYLlHH4dJu9RtMcTnL:-MfaedHG-NKSUhLwISOG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-common.h#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can setup_func or teardown_func be anything else than NULL?
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-common.h, line 34 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYMVuQ4QzCXRlmKG3X:-Mfaeeip2hARw-4yUmJC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-common.h#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I prefer having four macros (where two of them are really small) than having `NULL, NULL` all over the place. ;-)
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 362 at r10](https://reviewable.io/reviews/pmem/rpma/1080#-MfYO2sH1biZZr7S7Dsp:-MfaehR6-yb8FW_nr_9d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d991461e17e7eb93f7282831d111141202c8fade/tests/unit/conn_req/conn_req-from_cm_event.c#L362)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A new line is missing.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 161 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfY-PLs6n0E6jL8n0Zv:-MfaeoCL1Wm1dRaP064w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L161)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A subsequent fail test case is missing.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 196 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfY-aG-2oEVQmc4zLWv:-Mfaeu1M1uqML6sFSEC9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L196)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A subsequent fail test case is missing.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 214 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXPI1X2xa8SActgbTM:-Mfaez9X7HdjeVpzRpU2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L214)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 237 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxO10E-6UGzWbteHR:-Mfaf-5R4ATIiKIAggkG:b-dchv0h) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L237)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Sorry, only unit tests about `resolve_addr` and `resolve_route` are not related to seperate receive CQ.
</blockquote></details>

Done.  Added them in the PR.
___
*[tests/unit/conn_req/conn_req-new.c, line 282 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxTjx5GCHH2CfniEd:-Mfaf9fdAPl3MMWt8Br7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L282)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 335 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxdadCF2qQ1YQ95X3:-MfafD7J7LfdiUcw20mD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L335)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 443 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXxuraEGn4fYjstVsE:-MfafO2H4Aq-KPKC6bmw:b-2t5b0a) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-new.c#L443)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

? I think the comment has been updated.


<!-- Sent from Reviewable.io -->

2021-07-27 07:43 UTC, ldorau reviewed
> Reviewed 10 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-06 08:12 UTC, janekmi reviewed
> Reviewed 10 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[tests/unit/conn_req/conn_req-common.c, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/1080#-MfXqPQNBMXM6-spJptm:-MgL5mTB1iWal3xyscP3:bu43x4g) ([raw file](https://github.com/pmem/rpma/blob/0ffd45a9d6dad50b479e09671935ece45d6f56d8/tests/unit/conn_req/conn_req-common.c#L70)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Where do you want to define/set it?
</blockquote></details>

After rethinking my approach does not make much sense. It is fine.


<!-- Sent from Reviewable.io -->

2021-08-06 08:16 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080#-:-MgPXB897sP81j9sbUG-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-16 11:01 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-19 09:04 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080#-:-MhSdrhE63lnhYHb9rDz:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-23 18:25 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[src/include/librpma.h, line 1720 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho1y3S1jWepuKY-BHg:-Mho1y3S1jWepuKY-BHh:b-kgpr0o) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1720)):*
> ```
> rpma_conn_get_cq
> ```
completion queue has two meanings:
- main completion queue of connection
- any completion queue (main or recv)
Shall we distinguish this in the API names?
```rpma_conn_get_main_cq```?
___
*[src/include/librpma.h, line 1723 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho0K2p7YbfGDluWGl0:-Mho0K2p7YbfGDluWGl1:b-78q4z8) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1723)):*
> ```
> rpma_recv()
> ```
please harmonize this with  ```rpma_conn_get_rcq``` description, where rpma_recv() is not mentioned.
___
*[src/include/librpma.h, line 2691 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho3FlQDDIFw9anDI49:-Mho3FlQDDIFw9anDI4A:b-jlchog) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L2691)):*
> ```
> ERRORS
> ```
shall we refer here to rpma_cq_get_completion errors - instead of repeating errors values?
___
*[src/include/librpma.h, line 2786 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho5YjN8X2sY3DsaH5D:-Mho5YjN8X2sY3DsaH5E:bv4gfvg) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L2786)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>  *	enum rpma_op {
>  *		RPMA_OP_READ,
>  *		RPMA_OP_WRITE,
>  *		RPMA_OP_FLUSH,
>  *		RPMA_OP_SEND,
>  *		RPMA_OP_RECV,
>  *		RPMA_OP_RECV_RDMA_WITH_IMM,
>  *	};
> ```
</details>

do we need this to be documented twice?


<!-- Sent from Reviewable.io -->

2021-08-24 06:25 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 1720 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho1y3S1jWepuKY-BHg:-MhqDTVT6Bqu9s9xxPGS:b-u5u0t) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1720)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_conn_get_cq
> ```
completion queue has two meanings:
- main completion queue of connection
- any completion queue (main or recv)
Shall we distinguish this in the API names?
```rpma_conn_get_main_cq```?
</blockquote></details>

@grom72 @janekmi @ldorau @osalyk 

Is the following design clear and more readable?
Change `rpma_conn_get_cq` to `rpma_conn_get_main_cq`
Change `rpma_conn_get_rcq` to `rpma_conn_get_recv_cq`


<!-- Sent from Reviewable.io -->

2021-08-24 07:28 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 58 of 63 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/include/librpma.h, line 1720 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho1y3S1jWepuKY-BHg:-Mhr2PmO3VszlkmO2bDq:b-wkro6g) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1720)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 @janekmi @ldorau @osalyk 

Is the following design clear and more readable?
Change `rpma_conn_get_cq` to `rpma_conn_get_main_cq`
Change `rpma_conn_get_rcq` to `rpma_conn_get_recv_cq`
</blockquote></details>

When we  reach an agreement, I will change the name of API. (kepp it for now)
___
*[src/include/librpma.h, line 1723 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho0K2p7YbfGDluWGl0:-Mhr28J19XHulUzLp7go:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1723)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_recv()
> ```
please harmonize this with  ```rpma_conn_get_rcq``` description, where rpma_recv() is not mentioned.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2691 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho3FlQDDIFw9anDI49:-Mhr2A40D4JRpSskE06s:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L2691)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ERRORS
> ```
shall we refer here to rpma_cq_get_completion errors - instead of repeating errors values?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2786 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho5YjN8X2sY3DsaH5D:-Mhr2DCX06p3m1RzLraT:b-mm2rsq) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L2786)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  *	enum rpma_op {
>  *		RPMA_OP_READ,
>  *		RPMA_OP_WRITE,
>  *		RPMA_OP_FLUSH,
>  *		RPMA_OP_SEND,
>  *		RPMA_OP_RECV,
>  *		RPMA_OP_RECV_RDMA_WITH_IMM,
>  *	};
> ```
do we need this to be documented twice?
</blockquote></details>

Done.  Remove the same lines in `rpma_conn_completion_get.3`


<!-- Sent from Reviewable.io -->

2021-08-24 11:58 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 58 of 63 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/include/librpma.h, line 1720 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho1y3S1jWepuKY-BHg:-Mhqu4JgEQB7_VZWEqSO:b-niacqf) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1720)):*
> Change rpma_conn_get_cq to rpma_conn_get_main_cq
> Change rpma_conn_get_rcq to rpma_conn_get_recv_cq
Let's keep old names. 


<!-- Sent from Reviewable.io -->

2021-08-24 12:00 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: 58 of 63 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1080#-Mhs0jV89mUmgiljF3Bu:-Mhs0jV91uNJS4Pn2z6C:bu2mj1s) (no related file):*
We will mark "old" connection API as deprecated in a separate PR and will remove all conn_completion related calls in the following release.

---


<!-- Sent from Reviewable.io -->

2021-08-24 12:03 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080#-:-Mhs11HO4fS7IGEYQ2JB:bnfp4nl)* status: 58 of 63 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-24 12:14 UTC, grom72 reviewed
> Reviewed 8 of 59 files at r1, 8 of 34 files at r3, 1 of 1 files at r4, 2 of 14 files at r6, 2 of 11 files at r7, 1 of 9 files at r9, 4 of 10 files at r11, 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQW_u39xlrMpEYf-Y:-Mhs230O0_dbw8JtU0zM:b92wd0n) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Sure, we should discuss it with @grom72.

By the way, I have rebased this PR.  ^_^
</blockquote></details>

+1 to return null


<!-- Sent from Reviewable.io -->

2021-08-24 12:15 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/conn/conn-get_cq_rcq.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1080#-MbuQW_u39xlrMpEYf-Y:-Mhs4XVk32dZRTSzlxAe:b2nhksp) ([raw file](https://github.com/pmem/rpma/blob/7c524d989a1edf139e32e85bcabc93df8acea58f/tests/unit/conn/conn-get_cq_rcq.c#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1 to return null
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-08-24 12:31 UTC, janekmi requested changes
> Reviewed 5 of 5 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 1723 at r11](https://reviewable.io/reviews/pmem/rpma/1080#-Mho0K2p7YbfGDluWGl0:-Mhs6O1J5SU2_z3JCcgK:b-m5t4o5) ([raw file](https://github.com/pmem/rpma/blob/7349e3379dde49c83b6586aa6cbe68a73ae82db3/src/include/librpma.h#L1723)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`receive completion` is a not defined term. I think it will be easier to follow as `rpma_recv(3)`.
Please also add to the `SEE ALSO` section.
___
*[src/include/librpma.h, line 1756 at r12](https://reviewable.io/reviews/pmem/rpma/1080#-Mhs6zIFBDAYob7I79tJ:-Mhs6zIFBDAYob7I79tK:b-c233n8) ([raw file](https://github.com/pmem/rpma/blob/8c76ff99c46c848f35f86ae17748bf2edafa4bf5/src/include/librpma.h#L1756)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_get_rcq() gets the receive CQ from the connection. The receive
>  * CQ allows handling all receive completion within the connection. It allows
> ```

`rpma_recv(3) completions` + SEE ALSO

Note: Plural.
___
*[src/include/librpma.h, line 1757 at r12](https://reviewable.io/reviews/pmem/rpma/1080#-Mhs75V25gr75BmyzY--:-Mhs75V25gr75BmyzY-0:bojba8z) ([raw file](https://github.com/pmem/rpma/blob/8c76ff99c46c848f35f86ae17748bf2edafa4bf5/src/include/librpma.h#L1757)):*
> ```objc
>  * rpma_conn_get_rcq() gets the receive CQ from the connection. The receive
>  * CQ allows handling all receive completion within the connection. It allows
>  * separating receive completion processing path from any other completion.
> ```

`rpma_recv(3) completions`
___
*[src/include/librpma.h, line 1757 at r12](https://reviewable.io/reviews/pmem/rpma/1080#-Mhs7CKXAgH_hothL3y3:-Mhs7CKXAgH_hothL3y4:bkctwxj) ([raw file](https://github.com/pmem/rpma/blob/8c76ff99c46c848f35f86ae17748bf2edafa4bf5/src/include/librpma.h#L1757)):*
> ```objc
>  * rpma_conn_get_rcq() gets the receive CQ from the connection. The receive
>  * CQ allows handling all receive completion within the connection. It allows
>  * separating receive completion processing path from any other completion.
> ```

from all other completions.
___
*[src/include/librpma.h, line 2785 at r12](https://reviewable.io/reviews/pmem/rpma/1080#-Mhs7vsv9KZ10JGDRKL7:-Mhs7vsv9KZ10JGDRKL8:b-h99qbd) ([raw file](https://github.com/pmem/rpma/blob/8c76ff99c46c848f35f86ae17748bf2edafa4bf5/src/include/librpma.h#L2785)):*
> ```objc
>  * an already posted operation. All operations generate completion on error.
>  * The operations posted with the RPMA_F_COMPLETION_ALWAYS flag also
>  * generate a completion on success.  The following operations are available:
> ```

One space too much before `The following...`.


<!-- Sent from Reviewable.io -->

2021-08-24 13:52 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1080#-:-MhsQfdA7LcMKElkeaON:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-24 13:56 UTC, merged