common: add circleci nop build
pmem/rpma pull request #1085
Opened 2021-06-08 16:00 UTC by janekmi

To prevent gh-pages CircleCI builds from failing.
Lack of the CircleCI configuration causes a fail.

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1085)

2021-06-11 05:13 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1085#-MbtUE9uCZtLxxDeX8a_:-MbtUE9uCZtLxxDeX8aa:b3miz3h) (no related file):*
Why? What is it for?

---


<!-- Sent from Reviewable.io -->

2021-06-11 06:50 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1085#-MbtUE9uCZtLxxDeX8a_:-MbtpCBP5YPw1Y3ETna5:bub7igp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? What is it for?
</blockquote></details>

All gh-pages PRs fail:

```
No configuration was found in your project.
```

Ref: https://github.com/pmem/rpma/pull/1084

---


<!-- Sent from Reviewable.io -->

2021-06-11 07:17 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1085#-MbtUE9uCZtLxxDeX8a_:-MbtvZLe3Z9Ag9JCpEks:b-4jlfnh) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All gh-pages PRs fail:

```
No configuration was found in your project.
```

Ref: https://github.com/pmem/rpma/pull/1084
</blockquote></details>

Please add the above information to the commit message?

---


<!-- Sent from Reviewable.io -->

2021-06-11 07:28 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1085#-MbtUE9uCZtLxxDeX8a_:-Mbty8we9XZEPSbEINFH:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the above information to the commit message?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-06-11 08:20 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-11 08:20 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085#-:-Mbu9ASWC0bNY31DN5b2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-24 10:39 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085#-:-McxaSFr0FFXWWJQMU-a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-24 10:40 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1085)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-24 10:40 UTC, merged