tools: add write.json
pmem/rpma pull request #1090
Opened 2021-06-09 13:14 UTC by osalyk

2021-06-14 15:13 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090)* status: all files reviewed, 32 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/write.json, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8dAF17iBR-Mc2tdBe:-Mc8dAF17iBR-Mc2tdBf:b-u3uio5) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L7)):*
> ```JSON
>             "x": "bs",
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "_comment": "Figure 9-10",
> ```

Effectively figures numbering needs a complete overhaul. Please drop.
___
*[tools/perf/figures/write.json, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8bHIG39942blZJt_y:-Mc8bHIG39942blZJt_z:bgz5b1h) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L8)):*
> ```JSON
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "_comment": "Figure 9-10",
>             "file": "APM to DRAM (DDIO=ON) vs PMEM",
> ```

Since, indirectly, it is also a file name I recommend keeping it as simple as it can gets e.g. 'apm_dram_vs_pmem'

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L577
___
*[tools/perf/figures/write.json, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8ecQjEkPagwy2sAJ4:-Mc8ecQjEkPagwy2sAJ5:b-x2lblm) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L17)):*
> ```JSON
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
>             "label": "rpma_write() {rw_order}"
> ```

We can not have a common "label" here.
___
*[tools/perf/figures/write.json, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8l0U1-4pA-lO_CN6X:-Mc8l0U29lutL3X4d_Af:bje0u0n) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L24)):*
> ```JSON
>                 "requirements": {
>                     "direct_write_to_pmem": false
>                 },
> ```

```json
"label": "DRAM {rw_order}"
```
___
*[tools/perf/figures/write.json, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8f0Qt6ALzGlxXiyZS:-Mc8f0Qt6ALzGlxXiyZT:bkpv2yl) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L28)):*
> ```JSON
>             },
>             {
>                 "filetype": "path/to/dev/dax",
> ```

I think we will have to **filetype**'s: `malloc` and `pmem`.
___
*[tools/perf/figures/write.json, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lCxV-zOOVTwCMiKS:-Mc8lCxV-zOOVTwCMiKT:bd5nk0y) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L31)):*
> ```JSON
>                 "requirements": {
>                     "direct_write_to_pmem": true
>                 },
> ```

```json
"label": "PMEM {rw_order}"
```
___
*[tools/perf/figures/write.json, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fVOBDVZcp4LWQ8m5:-Mc8fVOBDVZcp4LWQ8m6:b-894hk6) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L41)):*
> ```JSON
>             "x": "bs",
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "_comment": "Figure 11-12",
> ```

Drop.
___
*[tools/perf/figures/write.json, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fMWTABp7BAIG68p2:-Mc8fMWTABp7BAIG68p3:bgcfrrs) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L42)):*
> ```JSON
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "_comment": "Figure 11-12",
>             "file": "APM to PMEM vs GPSPM(-RT) to PMEM",
> ```

`apm_pmem_vs_gpspm_pmem`

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L584
___
*[tools/perf/figures/write.json, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fXXE1SvYUwDQKk8C:-Mc8fXXF7toeolSTG7O0:b-tjel4w) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L47)):*
> ```JSON
>         },
>         "series_common": {
>             "filetype": "path/to/dev/dax",
> ```

`pmem`
___
*[tools/perf/figures/write.json, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8kp8q8tzk33ZG-0-1:-Mc8fadz7yttjEpLe16v:bcecfhp) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L51)):*
> ```JSON
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
>             "label": "rpma_write() {rw_order}"
> ```

We can not heave a common"label" here.
___
*[tools/perf/figures/write.json, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fwQsA_0DH4XCN6D_:-Mc8fwQsA_0DH4XCN6Da:b-894hk6) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L59)):*
> ```JSON
>                     "direct_write_to_pmem": true
>                 },
>                 "fstrings": ["label"]
> ```

Drop.
___
*[tools/perf/figures/write.json, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8iRuo2ZrmipBiR_MQ:-Mc8iRuo2ZrmipBiR_MR:baf1i2s) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L65)):*
> ```JSON
>                 "requirements": {
>                     "direct_write_to_pmem": false,
>                     "busy_wait_polling": true
> ```

It is not a requirement. It is just an option. So, it should be outside the `requirements` section.
___
*[tools/perf/figures/write.json, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lfumC5gGxi6vwR1u:-Mc8lfumC5gGxi6vwR1v:b-571ssb) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L66)):*
> ```JSON
>                     "direct_write_to_pmem": false,
>                     "busy_wait_polling": true
>                 },
> ```

```json
"label": "GPSPM-RT {rw_order}"
```
___
*[tools/perf/figures/write.json, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lp_60DQDpY5wKfeQ:-Mc8lp_77qczCtCcg5rJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L73)):*
> ```JSON
>                 "requirements": {
>                     "direct_write_to_pmem": false,
>                     "busy_wait_polling": false
> ```

.
___
*[tools/perf/figures/write.json, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lqBcCU9vV8MOZb7-:-Mc8lqBcCU9vV8MOZb70:bkc5x6m) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L74)):*
> ```JSON
>                     "direct_write_to_pmem": false,
>                     "busy_wait_polling": false
>                 },
> ```

```json
"label": "GPSPM {rw_order}"
```
___
*[tools/perf/figures/write.json, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8mOld1h_6CRIjtZvk:-Mc8mOld1h_6CRIjtZvl:b-894hk6) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L84)):*
> ```JSON
>             "x": ["bs", "threads"],
>             "y": "bw",
>             "_comment": "Figure 13-14",
> ```

Drop.
___
*[tools/perf/figures/write.json, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8mMD45Rm0v_hhZ5vr:-Mc8mMD5E2CnT_vA59K8:br9ih36) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L85)):*
> ```JSON
>             "y": "bw",
>             "_comment": "Figure 13-14",
>             "file": "APM to DRAM [...]

2021-06-14 15:48 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090)* status: 0 of 1 files reviewed, 32 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/write.json, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8dAF17iBR-Mc2tdBe:-McA7ov4-X3nO1LlXZO_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Effectively figures numbering needs a complete overhaul. Please drop.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8bHIG39942blZJt_y:-McA84hY5g0AOcNN3e_R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since, indirectly, it is also a file name I recommend keeping it as simple as it can gets e.g. 'apm_dram_vs_pmem'

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L577
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8ecQjEkPagwy2sAJ4:-McA9b9DC-JgFTXvzcBM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can not have a common "label" here.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8l0U1-4pA-lO_CN6X:-McA9uNN3TTgMphtnWO_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"label": "DRAM {rw_order}"
```
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8f0Qt6ALzGlxXiyZS:-McAA9k5E_8ABs74qlgo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we will have to **filetype**'s: `malloc` and `pmem`.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lCxV-zOOVTwCMiKS:-McAAGsUCn8o7QE9ONlR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"label": "PMEM {rw_order}"
```
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fVOBDVZcp4LWQ8m5:-McAAIy7BRL4tq2LsVBk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Drop.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fMWTABp7BAIG68p2:-McAAND-2A3R9YzLBs3n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`apm_pmem_vs_gpspm_pmem`

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L584
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fXXE1SvYUwDQKk8C:-McAAOR-7V60GyOuxMLZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`pmem`
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8kp8q8tzk33ZG-0-1:-McAAQOz6FpV4Tl3a5Ft:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can not heave a common"label" here.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8fwQsA_0DH4XCN6D_:-McAA_SqA76S9xvyQMXw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Drop.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8iRuo2ZrmipBiR_MQ:-McAAeDiBNHquQZiYLc5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a requirement. It is just an option. So, it should be outside the `requirements` section.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lfumC5gGxi6vwR1u:-McAAswD1U_A3a9c0Oka:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"label": "GPSPM-RT {rw_order}"
```
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lp_60DQDpY5wKfeQ:-McAAzxM32EHrDZVfEQT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8lqBcCU9vV8MOZb7-:-McAB1C_2tBFUx8Nu47p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"label": "GPSPM {rw_order}"
```
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8mOld1h_6CRIjtZvk:-McAB3Y4CjLg8i1r3JuH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Drop.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-Mc8mMD45Rm0v_hhZ5vr:-McAB7GX0MARQoQOVY1Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`apm_dram_vs_pmem`
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/1090#-McA3hN59OuvpG3CRByy:-McABAnDELEHcpw7_uUU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/022f5017e602befdac797d7c49875f43481e313c/tools/perf/figures/write.json#L90)):*
<details><summary><i>Pre [...]

2021-06-15 07:21 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090)* status: all files reviewed, 17 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/write.json, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWyNS0C0ytwr4aOq_:-McDWyNS0C0ytwr4aOqa:bh5kt77) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L15)):*
> ```JSON
>             "tool_mode": "apm",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"]
> ```

TBH you can make use of the fact `fstrings` are processed at the end so you can put it here:

```json
"fstrings": ["label"]
```

and remove it from the detailed definitions below.
___
*[tools/perf/figures/write.json, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDX8xD-ezqP38os3eF:-McDX8xD-ezqP38os3eG:bhofehq) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L24)):*
> ```JSON
>                 },
>                 "label": "DRAM {rw_order}",
>                 "fstrings": ["label"]
> ```

Delete.
___
*[tools/perf/figures/write.json, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXA1qEPbZgpIKLCs9:-McDXA1qEPbZgpIKLCsA:bhofehq) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L32)):*
> ```JSON
>                 },
>                 "label": "PMEM {rw_order}",
>                 "fstrings": ["label"]
> ```

Delete.
___
*[tools/perf/figures/write.json, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWADI1xxccngDDGpU:-McDWADI1xxccngDDGpV:bpbcvcd) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L49)):*
> ```JSON
>             "mode": "lat",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
> ```

A hanging comma.
___
*[tools/perf/figures/write.json, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXQTO9b3Q5Viau3kE:-McDXQTO9b3Q5Viau3kF:b-30rkk1) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L49)):*
> ```JSON
>             "mode": "lat",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
> ```

fstrings .
___
*[tools/perf/figures/write.json, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXSAw8bssc7-MZQee:-McDXSAw8bssc7-MZQef:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L58)):*
> ```JSON
>                 },
>                 "label": "APM {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 67 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXT-uCjXmIJgOutCY:-McDXT-vDd-H4d0QUziy:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L67)):*
> ```JSON
>                 },
>                 "label": "GPSPM-RT {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 76 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXWwM7GKGtXLKNKnj:-McDXWwM7GKGtXLKNKnk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L76)):*
> ```JSON
>                 },
>                 "label": "GPSPM {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWIyI-t1sRVNSB5gj:-McDWIyI-t1sRVNSB5gk:bpbcvcd) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L93)):*
> ```JSON
>             "tool_mode": "apm",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
> ```

A hanging comma.
___
*[tools/perf/figures/write.json, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXm050is_ePt6FgGA:-McDXm050is_ePt6FgGB:b-30rkk1) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L93)):*
> ```JSON
>             "tool_mode": "apm",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
> ```

fstrings .
___
*[tools/perf/figures/write.json, line 102 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXnQl-tltW_lqHuxl:-McDXnQl-tltW_lqHuxm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L102)):*
> ```JSON
>                 },
>                 "label": "DRAM {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 110 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXo2DECAAFirCIgT5:-McDXo2DECAAFirCIgT6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L110)):*
> ```JSON
>                 },
>                 "label": "PMEM {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWOS6EGE2J4JA9f01:-McDWOS6EGE2J4JA9f02:bpbcvcd) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L127)):*
> ```JSON
>             "mode": "bw",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
> ```

A hanging comma.
___
*[tools/perf/figures/write.json, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY0-_3EDeMdLeuDLu:-McDY0-_3EDeMdLeuDLv:b-30rkk1) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L127)):*
> ```JSON
>             "mode": "bw",
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
> ```

fstrings .
___
*[tools/perf/figures/write.json, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY1H0C6HoYXZpWWCv:-McDY1H0C6HoYXZpWWCw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L136)):*
> ```JSON
>                 },
>                 "label": "APM {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 145 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY1uDBAZgU9c_PD3S:-McDY1uDBAZgU9c_PD3T:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L145)):*
> ```JSON
>                 },
>                 "label": "GPSPM-RT {rw_order}",
>                 "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/write.json, line 154 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY2cD-lLVeNnRESEY:-McDY2cD-lLVeNnRESEZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L154)):*
> ```JSON
>                 },
>                 "label": "GPSPM {rw_order}",
>                 "fstrings": ["label"]
> ```

.


<!-- Sent from Reviewable.io -->

2021-06-15 07:33 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/write.json, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWyNS0C0ytwr4aOq_:-McDZow4D9VNHqb648L9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH you can make use of the fact `fstrings` are processed at the end so you can put it here:

```json
"fstrings": ["label"]
```

and remove it from the detailed definitions below.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDX8xD-ezqP38os3eF:-McDZplMAqyGkL_0TzY9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Delete.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXA1qEPbZgpIKLCs9:-McDZrYx6p2a5YQc0_Xe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Delete.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWADI1xxccngDDGpU:-McDZsrUEhiN3v_OXRN4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A hanging comma.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXQTO9b3Q5Viau3kE:-McDZzRo-K9bQiU4D8gd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

fstrings .
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXSAw8bssc7-MZQee:-McD_-BrAxUNa16dOsHh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 67 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXT-uCjXmIJgOutCY:-McD_-nbBlpipu5k73Sf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 76 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXWwM7GKGtXLKNKnj:-McD_0PSEStdVoGvTSah:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWIyI-t1sRVNSB5gj:-McD_5fY8Csz5vOVrE5d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A hanging comma.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXm050is_ePt6FgGA:-McD_69z-SQH8xqqMkNr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

fstrings .
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 102 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXnQl-tltW_lqHuxl:-McD_6lG5WQBmG86ufLw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L102)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 110 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDXo2DECAAFirCIgT5:-McD_7Hi7XxxFU-OUiW6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDWOS6EGE2J4JA9f01:-McD_DLZ8MfyeVEtsbJc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A hanging comma.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY0-_3EDeMdLeuDLu:-McD_DaIBdVlMmZ3gwpP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

fstrings .
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY1H0C6HoYXZpWWCv:-McD_E9Z9l6Ja_5O9RGZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L136)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 145 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY1uDBAZgU9c_PD3S:-McD_EgpE86ppb4lZjh5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L145)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 154 at r2](https://reviewable.io/reviews/pmem/rpma/1090#-McDY2cD-lLVeNnRESEY:-McD_FEb0JAozcO0Rc8z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/645ba110a6c3308ad21c31847f4ac461117ff1ec/tools/perf/figures/write.json#L154)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-24 10:32 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-06-24 12:10 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090#-:-McxvLQ42nt7-hVnx28N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-06-24 13:10 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-06-25 11:26 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1090#-:-Md1ur5SElVP5MGxPyzx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-06-25 12:48 UTC, merged