tools: improve read/write.json
pmem/rpma pull request #1117
Opened 2021-07-01 15:20 UTC by osalyk

2021-07-02 08:37 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-02 12:21 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/read.json, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9MefBKyP1M0hUiBq:-Mdb9MefBKyP1M0hUiBr:b7f8vhx) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L26)):*
> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

Can order of those two be changed? 

```
                "tool": "rpma_fio_bench.sh",
                "tool_mode": "apm",
```
___
*[tools/perf/figures/read.json, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9c1C70M6K37se_Eh:-Mdb9c1C70M6K37se_Ei:befmi7s) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L36)):*
> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

.
___
*[tools/perf/figures/read.json, line 103 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9g1q5OtNZmR68-nU:-Mdb9g1q5OtNZmR68-nV:befmi7s) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L103)):*
> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

.
___
*[tools/perf/figures/read.json, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9hoR6wf33uhsYfLX:-Mdb9hoR6wf33uhsYfLY:befmi7s) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L113)):*
> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

.


<!-- Sent from Reviewable.io -->

2021-07-02 14:29 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/figures/read.json, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9MefBKyP1M0hUiBq:-MdbaYvi-FNgsGnGidce:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

Can order of those two be changed? 

```
                "tool": "rpma_fio_bench.sh",
                "tool_mode": "apm",
```
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9c1C70M6K37se_Eh:-Mdbad8EBpnzR5I7TGRT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 103 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9g1q5OtNZmR68-nU:-MdbaqfR4nwukvPw_ay3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L103)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/1117#-Mdb9hoR6wf33uhsYfLX:-Mdbat7NB9EbH_BgPQus:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9eb1ac0e3c5c2b0739c15da0453065a61ee71153/tools/perf/figures/read.json#L113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>                 "tool_mode": "apm",
>                 "tool": "rpma_fio_bench.sh",
> ```

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-02 14:50 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-06 09:04 UTC, ldorau approved these changes
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-06 09:04 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117#-:-Mdv30WCEq1lrbrxEUsw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-06 12:26 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/figures/read.json, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/1117#-Mdvm8-oErC9rFeWyyUb:-Mdvm8-oErC9rFeWyyUc:b-8egqx) ([raw file](https://github.com/pmem/rpma/blob/dccad3a946b1add0c87320ada30566d5b44d1046/tools/perf/figures/read.json#L19)):*
> ```JSON
>                 "tool": "ib_read.sh",
>                 "rw": "read",
>                 "requirements": {
> ```

`"filetype": "malloc",` is missing here


<!-- Sent from Reviewable.io -->

2021-07-06 12:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/read.json, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1117#-Mdvmlvi2uNFmekVU3no:-Mdvmlvi2uNFmekVU3np:b-wxcxuz) ([raw file](https://github.com/pmem/rpma/blob/dccad3a946b1add0c87320ada30566d5b44d1046/tools/perf/figures/read.json#L18)):*
> ```
> "rw": "read",
> ```

There is no such mode


<!-- Sent from Reviewable.io -->

2021-07-06 12:31 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/read.json, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1117#-MdvnChP3PAxuOWAjk5W:-MdvnChP3PAxuOWAjk5X:bxgx76s) ([raw file](https://github.com/pmem/rpma/blob/dccad3a946b1add0c87320ada30566d5b44d1046/tools/perf/figures/read.json#L32)):*
> ```
> "DRAM {rw_order}"
> ```

Where is `rw_order` defined ?

I got:
```
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_bench.py", line 55, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_bench.py", line 42, in main
    bench = Bench.new(args.config, args.figure, args.result_dir)
  File "/mnt/files/repos/rpma/tools/perf/lib/Bench.py", line 32, in new
    figures = Figure.flatten(figures['json'])
  File "/mnt/files/repos/rpma/tools/perf/lib/Figure.py", line 83, in flatten
    f['series'] = process_fstrings(f['series'], cls.get_oneseries_desc,
  File "/mnt/files/repos/rpma/tools/perf/lib/flat.py", line 60, in process_fstrings
    out[fstring] = out[fstring].format(**out, **derivatives(out))
KeyError: 'rw_order'
```


<!-- Sent from Reviewable.io -->

2021-07-07 07:21 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/figures/read.json, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1117#-Mdvmlvi2uNFmekVU3no:-MdvoKZM4_2oOabDV6XE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dccad3a946b1add0c87320ada30566d5b44d1046/tools/perf/figures/read.json#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "rw": "read",
> ```

There is no such mode
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/1117#-Mdvm8-oErC9rFeWyyUb:-Mdvo_Q74atqHd2_VqZl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dccad3a946b1add0c87320ada30566d5b44d1046/tools/perf/figures/read.json#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`"filetype": "malloc",` is missing here
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1117#-MdvnChP3PAxuOWAjk5W:-MdzphE359OqwfPHA1MQ:b-r7ja8e) ([raw file](https://github.com/pmem/rpma/blob/dccad3a946b1add0c87320ada30566d5b44d1046/tools/perf/figures/read.json#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "DRAM {rw_order}"
> ```

Where is `rw_order` defined ?

I got:
```
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_bench.py", line 55, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_bench.py", line 42, in main
    bench = Bench.new(args.config, args.figure, args.result_dir)
  File "/mnt/files/repos/rpma/tools/perf/lib/Bench.py", line 32, in new
    figures = Figure.flatten(figures['json'])
  File "/mnt/files/repos/rpma/tools/perf/lib/Figure.py", line 83, in flatten
    f['series'] = process_fstrings(f['series'], cls.get_oneseries_desc,
  File "/mnt/files/repos/rpma/tools/perf/lib/flat.py", line 60, in process_fstrings
    out[fstring] = out[fstring].format(**out, **derivatives(out))
KeyError: 'rw_order'
```
</blockquote></details>

This was a problem with ib_read.sh, there is no **rw** argument


<!-- Sent from Reviewable.io -->

2021-07-07 08:09 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-07-07 08:42 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-07 16:58 UTC, janekmi requested changes
> Reviewed 1 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 18 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/read.json, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0quCJ3fQbqEnCvLyD:-Me0quCK7OvAkBAGulBD:blbwjip) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L13)):*
> ```JSON
>         "series_common": {
>             "mode": "lat",
>             "fstrings": ["label"]
> ```

It is only a part of the apm/randread+read.
___
*[tools/perf/figures/read.json, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0qpYw3CLDu7CxdLco:-Me0qpYw3CLDu7CxdLcp:b927dfb) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L22)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM read"
> ```

ib_read_lat
___
*[tools/perf/figures/read.json, line 28 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r-SdCouatWgznij0:-Me0r-SdCouatWgznij1:b-ig72yq) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L28)):*
> ```JSON
>                 "tool_mode": "apm",
>                 "rw": ["randread", "read"],
>                 "filetype": "malloc",
> ```

It is common for both series definitions.
___
*[tools/perf/figures/read.json, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r6oG3O0ZLTaSrc-_:-Me0r6oG3O0ZLTaSrc-a:b7r657i) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L31)):*
> ```JSON
>                 "requirements": {
>                     "direct_write_to_pmem": false
>                 },
> ```

Common.
___
*[tools/perf/figures/read.json, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r8th9kHLyp7MU4Fm:-Me0r8th9kHLyp7MU4Fn:b-d34u5t) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L32)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

rpma_read() {rw_order}
___
*[tools/perf/figures/read.json, line 43 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0qg2d4to5-bE_ms5V:-Me0qg2d4to5-bE_ms5W:bmxsity) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L43)):*
> ```JSON
>                 },
>                 "label": "PMEM {rw_order}"
>             }
> ```

It is not a part of the old Figure no. 1.
___
*[tools/perf/figures/read.json, line 85 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0s9wm1AK-_lN7-xxt:-Me0s9wm1AK-_lN7-xxu:b3ksz) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L85)):*
> ```JSON
>             "y": "bw",
>             "file": "ib_read_bw_vs_rpma_read",
>             "key": "{y}",
> ```

x
___
*[tools/perf/figures/read.json, line 90 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rkSo0mSxBlFm3KyF:-Me0rkSo0mSxBlFm3KyG:bys5bnz) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L90)):*
> ```JSON
>         "series_common": {
>             "mode": ["bw-bs", "bw-th"],
>             "fstrings": ["label"]
> ```

Only for the apm/readread+read
___
*[tools/perf/figures/read.json, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r_r_ECRZo_Atp6iE:-Me0r_r_ECRZo_Atp6iF:bu2uypp) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L99)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM read"
> ```

ib_read_bw
___
*[tools/perf/figures/read.json, line 105 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rq5T35lg3uDv8D3t:-Me0rq5T35lg3uDv8D3u:b7r657i) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L105)):*
> ```JSON
>                 "tool_mode": "apm",
>                 "rw": ["randread", "read"],
>                 "filetype": "malloc",
> ```

Common.
___
*[tools/perf/figures/read.json, line 108 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rrl24S_BDaO9Uia0:-Me0rrl24S_BDaO9Uia1:b7r657i) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L108)):*
> ```JSON
>                 "requirements": {
>                     "direct_write_to_pmem": false
>                 },
> ```

Common.
___
*[tools/perf/figures/read.json, line 109 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rtkkEgcQtEts0kjP:-Me0rtkkEgcQtEts0kjQ:b-d34u5t) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L109)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

rpma_read() {rw_order}
___
*[tools/perf/figures/read.json, line 120 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rf-49UmP50Hhf3dO:-Me0rf-49UmP50Hhf3dP:b-9hq8f9) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L120)):*
> ```JSON
>                 },
>                 "label": "PMEM {rw_order}"
>             }
> ```

It is not a part of Figure no. 4.
___
*[tools/perf/figures/read.json, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0sQlAD4L2B61SoyPp:-Me0sQlAD4L2B61SoyPq:b7a68rk) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L126)):*
> ```JSON
>         "output": {
>             "title": "Bandwidth ({x}): rpma_read() from DRAM vs from PMEM",
>             "x": ["bs", "threads"],
> ```

I'm pretty sure it won't simply work.
Note: you have two outputs: bw(bs) and be(threads) but both of them have series: bw-bs and bw-th.
It would be nice to simply have a mode that takes into account the chosen {x} axis but we are not there yet.
So, sadly, you probably have to duplicate this definitions just to accommodate both outputs. Sorry.
___
*[tools/perf/figures/read.json, line 128 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0s4f42N0c0TctB5NP:-Me0s4f42N0c0TctB5NQ:b-abyz7h) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L128)):*
> ```JSON
>             "x": ["bs", "threads"],
>             "y": "bw",
>             "file": "apm_dram_vs_pmem",
> ```

rpma_read_dram_vs_pmem
___
*[tools/perf/figures/read.json, line 129 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0sCB7Elyc0gfvRFBS:-Me0sCB7Elyc0gfvRFBT:b3ksz) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L129)):*
> ```JSON
>             "y": "bw",
>             "file": "apm_dram_vs_pmem",
>             "key": "{y}",
> ```

x
___
*[tools/perf/figures/write.json, line 87 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0tp_jEGGupX1RCvsd:-Me0tp_jEGGupX1RCvse:b-ylhj0w) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/write.json#L87)):*
> ```JSON
>         },
>         "series_common": {
>             "mode": ["bw-bs", "bw-th"],
> ```

Won't work just like that. Sorry. Please see the comment above.
___
*[tools/perf/figures/write.json, line 121 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0ttt9AETd0qnHBLaj:-Me0ttt9AETd0qnHBLak:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/write.json#L121)):*
> ```JSON
>         "series_common": {
>             "filetype": "pmem",
>             [...]

2021-07-08 10:31 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 1 of 3 files reviewed, 18 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/read.json, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0quCJ3fQbqEnCvLyD:-Me4NkqH6qZ-sc6Uobxc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is only a part of the apm/randread+read.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0qpYw3CLDu7CxdLco:-Me4NpIv5v_f1Y14E7DR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ib_read_lat
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 28 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r-SdCouatWgznij0:-Me4OENb9XQTI45x5hqz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is common for both series definitions.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r6oG3O0ZLTaSrc-_:-Me4OMmC5he2vkevo8CV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Common.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r8th9kHLyp7MU4Fm:-Me4OXGs0EnWXDL3npJm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_read() {rw_order}
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 43 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0qg2d4to5-bE_ms5V:-Me4OY6k3NadxFgQgu5c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a part of the old Figure no. 1.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 85 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0s9wm1AK-_lN7-xxt:-Me4OksW4SVh3W7A0St2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

x
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 90 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rkSo0mSxBlFm3KyF:-Me4OpBxEX8Ew9gopp2i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Only for the apm/readread+read
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0r_r_ECRZo_Atp6iE:-Me4Osre5-u7uUhhpwYm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ib_read_bw
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 105 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rq5T35lg3uDv8D3t:-Me4PCVnDDD4szLKN3Vb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L105)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Common.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 108 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rrl24S_BDaO9Uia0:-Me4PDKv1W5MFWLsypcw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Common.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 109 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rtkkEgcQtEts0kjP:-Me4PG8U6MCbHulfv_1e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_read() {rw_order}
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 120 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0rf-49UmP50Hhf3dO:-Me4PHZrBlduOKTMwapj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a part of Figure no. 4.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0sQlAD4L2B61SoyPp:-Me4f2Wp41TcJoFy6oq0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm pretty sure it won't simply work.
Note: you have two outputs: bw(bs) and be(threads) but both of them have series: bw-bs and bw-th.
It would be nice to simply have a mode that takes into account the chosen {x} axis but we are not there yet.
So, sadly, you probably have to duplicate this definitions just to accommodate both outputs. Sorry.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 128 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0s4f42N0c0TctB5NP:-Me4PRnT7HnrJWH-rktp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L128)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_read_dram_vs_pmem
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 129 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0sCB7Elyc0gfvRFBS:-Me4PTf88sUc3R0qWOCA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/read.json#L129)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

x
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 87 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0tp_jEGGupX1RCvsd:-Me4f0_Q22CFwCiD_BeY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/write.json#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Won't work just like that. Sorry. Please see the comment above.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 121 at r4](https://reviewable.io/reviews/pmem/rpma/1117#-Me0ttt9AETd0qnHBLaj:-Me4f1Xh2fU00JRXNC1G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3333b3fc3b1dfb9ff0068ab34cf7ff43b7655076/tools/perf/figures/write.json#L121)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Se [...]

2021-07-08 10:38 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 18 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-07-09 09:42 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 18 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-07-09 10:59 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: all files reviewed, 27 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/read.json, line 21 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9ZGKs01SqM8dS7Wnb:-Me9ZGKt4bt-7imY1hYr:b-k5efs6) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L21)):*
> ```JSON
>             {
>                 "tool": "ib_read.sh",
>                 "label": "ib_read_lat()"
> ```

It is not a function. Drop `()`.
___
*[tools/perf/figures/read.json, line 67 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9bwrP8GYfHiE9B-9A:-Me9bwrQBk_6eFyLNk2G:b-xhtgo2) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L67)):*
> ```JSON
>     {
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
> ```

XXX combine bw-bs and bw-th definitions
___
*[tools/perf/figures/read.json, line 68 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9c7MbBwDFMaDXGyZP:-Me9c7MbBwDFMaDXGyZQ:bfvj9w0) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L68)):*
> ```JSON
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
>             "title": "Bandwidth (bs) ({x}): ib_read_bw() vs rpma_read() from DRAM",
> ```

You will get `Bandwidth (bs) (bs)...`. ;-)
___
*[tools/perf/figures/read.json, line 71 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9cQwh0144cvjSQFQR:-Me9cQwh0144cvjSQFQS:bxsveki) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L71)):*
> ```JSON
>             "x": "bs",
>             "y": "bw_avg",
>             "file": "bs_ib_read_bw_vs_rpma_read",
> ```

Both bs and thread output can be stored in a single file (`ib_read_bw_vs_rpma_read`) but under different keys (`bs` and `threads`).
___
*[tools/perf/figures/read.json, line 98 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9culb78EJAR4hYCTY:-Me9culb78EJAR4hYCTZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L98)):*
> ```JSON
>     {
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
> ```

.
___
*[tools/perf/figures/read.json, line 99 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9cvg86hLAqz90Stxt:-Me9cvg86hLAqz90Stxu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L99)):*
> ```JSON
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
>             "title": "Bandwidth (threads) ({x}): ib_read_bw() vs rpma_read() from DRAM",
> ```

.
___
*[tools/perf/figures/read.json, line 102 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9d2S3C6oiVdrXoPec:-Me9d2S3C6oiVdrXoPed:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L102)):*
> ```JSON
>             "x": "threads",
>             "y": "bw_avg",
>             "file": "th_ib_read_bw_vs_rpma_read",
> ```

.
___
*[tools/perf/figures/read.json, line 129 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9dK1Y7Au6OEL38K60:-Me9dK1Y7Au6OEL38K61:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L129)):*
> ```JSON
>     {
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
> ```

.
___
*[tools/perf/figures/read.json, line 130 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9dL4K68zqEorQQAs9:-Me9dL4K68zqEorQQAsA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L130)):*
> ```JSON
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
>             "title": "Bandwidth (bs) ({x}): rpma_read() from DRAM vs from PMEM",
> ```

.
___
*[tools/perf/figures/read.json, line 133 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9dMGO9Qa2gFwMP3_t:-Me9dMGO9Qa2gFwMP3_u:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L133)):*
> ```JSON
>             "x": "bs",
>             "y": "bw_avg",
>             "file": "bs_rpma_read_dram_vs_pmem",
> ```

.
___
*[tools/perf/figures/read.json, line 163 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9d_-cDtcSqA3B7wvf:-Me9d_-cDtcSqA3B7wvg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L163)):*
> ```JSON
>     {
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
> ```

.
___
*[tools/perf/figures/read.json, line 164 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9d_u3AnULiCQAWlh0:-Me9d_u3AnULiCQAWlh1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L164)):*
> ```JSON
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
>             "title": "Bandwidth (threads) ({x}): rpma_read() from DRAM vs from PMEM",
> ```

.
___
*[tools/perf/figures/read.json, line 167 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9db9TD95KJw7DEWLe:-Me9db9TD95KJw7DEWLf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L167)):*
> ```JSON
>             "x": "threads",
>             "y": "bw_avg",
>             "file": "th_rpma_read_dram_vs_pmem",
> ```

.
___
*[tools/perf/figures/write.json, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e-0vC_UvuWBbOGY2:-Me9e-0w2_lNYZJ5ZNh1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L7)):*
> ```JSON
>             "x": "bs",
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "file": "lat_apm_dram_vs_pmem",
> ```

.
___
*[tools/perf/figures/write.json, line 40 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e0Xo7f_eQizCz6pD:-Me9e0Xo7f_eQizCz6pE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L40)):*
> ```JSON
>             "x": "bs",
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "file": "lat_apm_pmem_vs_gpspm_pmem",
> ```

.
___
*[tools/perf/figures/write.json, line 79 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e1IL307_PlwXwTSJ:-Me9e1IL307_PlwXwTSK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L79)):*
> ```JSON
>     {
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
> ```

.
___
*[tools/perf/figures/write.json, line 80 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e22l3oAs0gWiZ6Rp:-Me9e22l3oAs0gWiZ6Rq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L80)):*
> ```JSON
>         "output": {
>             "_comment": "In the next step, combine the bw-bs series with the bw-th series",
>             "title": "Bandwidth (bs) ({x}): APM to DRAM (DDIO=ON) vs to PMEM",
> ```

.
___
*[tools/perf/figures/write.json, line 83 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9eUP-2uOU3lIN93Tj:-Me9eUP-2uOU3lIN93Tk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1b [...]

2021-07-09 11:11 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: 1 of 3 files reviewed, 27 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/read.json, line 21 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9ZGKs01SqM8dS7Wnb:-Me9vtjU1od7-aSMmZle:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a function. Drop `()`.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 67 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9bwrP8GYfHiE9B-9A:-Me9w7ZQ1bhteDt5FHIb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

XXX combine bw-bs and bw-th definitions
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 68 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9c7MbBwDFMaDXGyZP:-Me9wJXM4TpbtDCTCi3c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You will get `Bandwidth (bs) (bs)...`. ;-)
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 71 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9cQwh0144cvjSQFQR:-Me9wU2b0_xcKUtBNolT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Both bs and thread output can be stored in a single file (`ib_read_bw_vs_rpma_read`) but under different keys (`bs` and `threads`).
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 98 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9culb78EJAR4hYCTY:-Me9wUsw-bZQPQSzZ-N4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 99 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9cvg86hLAqz90Stxt:-Me9wVSW148hkxHhFHSV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 102 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9d2S3C6oiVdrXoPec:-Me9wVyACtfhPFA7MjkS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L102)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 129 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9dK1Y7Au6OEL38K60:-Me9wWg23Wzx8o6_hTKy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L129)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 130 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9dL4K68zqEorQQAs9:-Me9wXLl58lubAHEf_M0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L130)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 133 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9dMGO9Qa2gFwMP3_t:-Me9wXuA6OwoAYDI7k5a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 163 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9d_-cDtcSqA3B7wvf:-Me9wYUB89BaXjYPGeBG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L163)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 164 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9d_u3AnULiCQAWlh0:-Me9wZ0SCcEG34M0l03A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/read.json, line 167 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9db9TD95KJw7DEWLe:-Me9wZ_66JxhpOcknOuM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/read.json#L167)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e-0vC_UvuWBbOGY2:-Me9wxu_1Uco6ZxuxxqM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 40 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e0Xo7f_eQizCz6pD:-Me9wygwBIGU3N1acxfw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 79 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e1IL307_PlwXwTSJ:-Me9wzJ2CpD_woBP9ba8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 80 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9e22l3oAs0gWiZ6Rp:-Me9x0of2T9kiuk_1IGw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 83 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9eUP-2uOU3lIN93Tj:-Me9x1bW1BMvA7cfBJhx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L83)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 113 at r6](https://reviewable.io/reviews/pmem/rpma/1117#-Me9eZXc75XVcBhiTrsS:-Me9x29O0VN59fcWTf5F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/300a0d3377340c709af1b79b5c9e1bf5d58d91c2/tools/perf/figures/write.json#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/write.json, line 114 at r6](ht [...]

2021-07-09 11:31 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117#-:-MeA1EEB1ycgUeTFdBLP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-09 12:55 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-09 12:56 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1117#-:-MeAKhZcAv4l0pwXgsg6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-07-09 12:56 UTC, merged