common: add "-Werror=discarded-qualifiers" for both gcc and cc
pmem/rpma pull request #1139
Opened 2021-07-13 05:01 UTC by yangx-jy

For the default C compiler ("cc"), check_signature_rdma_getaddrinfo()
doesn't catch it and doesn't add "-Werror=discarded-qualifiers" to
check the version of rdma_getaddrinfo().  In this case,
RDMA_GETADDRINFO_NEW_SIGNATURE cannot show the correct value.

Ref: #1138

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

2021-07-20 12:18 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139#-:-Mf2qaGHCNvaEnbsZX24:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-23 05:43 UTC, ldorau requested changes
@yangx-jy `cc` is just a symbolic link to the default compiler (gcc or clang), just like the environment variable `CC`, so `CMAKE_C_COMPILER` has to be set explicitly to gcc or clang <img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139#-:-MfGrpVnD_gyAWZj6Q_x:bfceuox)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-23 08:00 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[cmake/functions.cmake, line 200 at r1](https://reviewable.io/reviews/pmem/rpma/1139#-MfHNIIk2Avzp8PDl4HW:-MfHNIIl14xuKLS3Q6ps:b-7l60rx) ([raw file](https://github.com/pmem/rpma/blob/58096580b80d45214fc5f9029037503c87c8e092/cmake/functions.cmake#L200)):*
> ```
> if(${CMAKE_C_COMPILER} MATCHES "cc")
> ```

If `CMAKE_C_COMPILER` is set to `cc`, you should check if it is a symbolic link and if it points to `gcc` or `clang`


<!-- Sent from Reviewable.io -->

2021-07-23 09:16 UTC, yangx-jy commented
___
*[cmake/functions.cmake, line 200 at r1](https://reviewable.io/reviews/pmem/rpma/1139#-MfHNIIk2Avzp8PDl4HW:-MfHdNdx3IaDLiuAYSnh:b-qcsvvo) ([raw file](https://github.com/pmem/rpma/blob/58096580b80d45214fc5f9029037503c87c8e092/cmake/functions.cmake#L200)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if(${CMAKE_C_COMPILER} MATCHES "cc")
> ```

If `CMAKE_C_COMPILER` is set to `cc`, you should check if it is a symbolic link and if it points to `gcc` or `clang`
</blockquote></details>

Good catch, but I perfer to get the realpath of `cc` directly. ^_^


<!-- Sent from Reviewable.io -->

2021-07-23 09:37 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139#-:-MfHiSezBYFAzfFLEVpw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 10:46 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[cmake/functions.cmake, line 202 at r2](https://reviewable.io/reviews/pmem/rpma/1139#-MfXPcK11Va4set32I5K:-MfXPcK11Va4set32I5L:bywymrn) ([raw file](https://github.com/pmem/rpma/blob/e31693d9eb2f7c8c23dcedd82edd1e0b9258f6b1/cmake/functions.cmake#L202)):*
> ```CMake
> 	execute_process(COMMAND realpath ${CMAKE_C_COMPILER}
> 			OUTPUT_VARIABLE REAL_CMAKE_C_COMPILER
> 			OUTPUT_STRIP_TRAILING_WHITESPACE)
> ```

Can we make use of something standard to cmake like `get_filename_component()`?

@ldorau I believe it does not affects our cmake release dependency?

Ref: https://cmake.org/cmake/help/v3.0/command/get_filename_component.html


<!-- Sent from Reviewable.io -->

2021-07-26 11:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/functions.cmake, line 202 at r2](https://reviewable.io/reviews/pmem/rpma/1139#-MfXPcK11Va4set32I5K:-MfXaGPw3CjqXiKWiCBy:bl6kxu3) ([raw file](https://github.com/pmem/rpma/blob/e31693d9eb2f7c8c23dcedd82edd1e0b9258f6b1/cmake/functions.cmake#L202)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we make use of something standard to cmake like `get_filename_component()`?

@ldorau I believe it does not affects our cmake release dependency?

Ref: https://cmake.org/cmake/help/v3.0/command/get_filename_component.html
</blockquote></details>

Yes, `get_filename_component()` is much better! +1


<!-- Sent from Reviewable.io -->

2021-07-26 12:04 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[cmake/functions.cmake, line 202 at r2](https://reviewable.io/reviews/pmem/rpma/1139#-MfXPcK11Va4set32I5K:-MfXgtnQ6ow7EifYI7h-:b-ol1vxs) ([raw file](https://github.com/pmem/rpma/blob/e31693d9eb2f7c8c23dcedd82edd1e0b9258f6b1/cmake/functions.cmake#L202)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, `get_filename_component()` is much better! +1
</blockquote></details>

Done. It is actually better. ^_^


<!-- Sent from Reviewable.io -->

2021-07-26 12:05 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-07-26 12:07 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139#-:-MfXhgR55V4GsJjcR292:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 12:09 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1139#-:-MfXhzixDPaLtdjrYhYW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 12:09 UTC, merged