rpma_info_new: log the real error message
pmem/rpma pull request #1141
Opened 2021-07-14 10:42 UTC by zhijianli88

Per rdma_getaddrinfo man page
```
RETURN VALUE
       Returns 0 on success, or -1 on error (errno will be set to indicate the failure reason), or one of the following nonzero error codes:
...
EAI_SYSTEM  Other system error, check errno for details.  The gai_strerror() function translates these error codes to a human readable string, suitable for error reporting.
```
errno will be used when -1 or EAI_SYSTEM is returned.

Before:
$ build/examples/03-read-to-persistent/client r92.168.1.10 9999
Next value: Hello world!
Jul 14 18:33:16.543688 [93128] *ERROR* info.c:  60: rpma_info_new: rdma_getaddrinfo(node=r92.168.1.10, service=(null), ai_flags=active, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): No such file or directory

After:
$ build/examples/03-read-to-persistent/client r92.168.1.10 9999
Next value: Hello world!
Jul 14 18:40:34.806909 [99115] *ERROR* info.c:  59: rpma_info_new: rdma_getaddrinfo(node=r92.168.1.10, service=(null), ai_flags=active, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): Name or service not known

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>

2021-07-20 12:24 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf2rorR3xYoupmfdquN:-Mf2rorR3xYoupmfdquO:b-2rmtv4) (no related file):*
The builds fail - please fix errors.

---


<!-- Sent from Reviewable.io -->

2021-07-20 15:11 UTC, zhijianli88 commented
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf2rorR3xYoupmfdquN:-Mf2rorR3xYoupmfdquO:b-2rmtv4) (no related file):_
> The builds fail - please fix errors.

Fixed, CI builds passed.

2021-07-21 05:12 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 2 unresolved discussions (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf2rorR3xYoupmfdquN:-Mf6RIsY3qUXDb-91v6a:bwcu71) (no related file):*
<details><summary><i>Previously, zhijianli88 (Li Zhijian) wrote…</i></summary><blockquote>

Fixed, CI builds passed.
</blockquote></details>

Not yet, they needed approval to be started and failed afterwards: https://github.com/pmem/rpma/pull/1141

Please read `CONTRIBUTING.md` and then run cmake with `CHECK_CSTYLE=ON` and `DEVELOPER_MODE=ON` to see all errors:

```
cmake .. -DCHECK_CSTYLE=ON -DDEVELOPER_MODE=ON
```

and then build the code.

---
___
*[src/info.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6T1D4CRHGZ0EOAgjg:-Mf6T1D4CRHGZ0EOAgjh:b-cfdy4g) ([raw file](https://github.com/pmem/rpma/blob/97aac662228122ecf79cad3c9958f9314d10363d/src/info.c#L61)):*
> ```
> 			"rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s, "
> 			"ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): %s",
> ```

The string message should not be broken into parts, but it should stay in one line as it was before:

```
"rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): %s"
```


<!-- Sent from Reviewable.io -->

2021-07-21 06:04 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 2 unresolved discussions (waiting on @zhijianli88)



<!-- Sent from Reviewable.io -->

2021-07-21 06:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 3 unresolved discussions (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf6hknnEmWlEXeq7ujv:b-e9edhe) (no related file):*
Please fix the coverage to not introduce new misses.

---


<!-- Sent from Reviewable.io -->

2021-07-21 06:27 UTC, zhijianli88 commented
> > Reviewed 1 of 1 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 2 unresolved discussions (waiting on @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf2rorR3xYoupmfdquN:-Mf6RIsY3qUXDb-91v6a:bwcu71) (no related file):_
> 
> Previously, zhijianli88 (Li Zhijian) wrote…
> Not yet, they needed approval to be started and failed afterwards: #1141
> 
> Please read `CONTRIBUTING.md` and then run cmake with `CHECK_CSTYLE=ON` and `DEVELOPER_MODE=ON` to see all errors:
> 
> ```
> cmake .. -DCHECK_CSTYLE=ON -DDEVELOPER_MODE=ON
> ```
> 
> and then build the code.

It helps a lots, thanks.

> 
> _[src/info.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6T1D4CRHGZ0EOAgjg:-Mf6T1D4CRHGZ0EOAgjh:b-cfdy4g) ([raw file](https://github.com/pmem/rpma/blob/97aac662228122ecf79cad3c9958f9314d10363d/src/info.c#L61)):_
> 
> > ```
> > 			"rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s, "
> > 			"ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): %s",
> > ```
> 
> The string message should not be broken into parts, but it should stay in one line as it was before:
> 
> ```
> "rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): %s"
> ```

Sound good, updated.

BTW:  build with above option you mentioned, it also complain line is too long in my commit message, so i have to break them down as it suggests.

2021-07-21 06:33 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 2 unresolved discussions (waiting on @zhijianli88)

___
*[src/info.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6T1D4CRHGZ0EOAgjg:-Mf6kHcN6zoLgIpyPR7f:brryjxh) ([raw file](https://github.com/pmem/rpma/blob/97aac662228122ecf79cad3c9958f9314d10363d/src/info.c#L61)):*
<details><summary><i>Previously, zhijianli88 (Li Zhijian) wrote…</i></summary><blockquote>

Sound good, updated.

BTW:  build with above option you mentioned, it also complain line is too long in my commit message, so i have to break them down as it suggests.

</blockquote></details>

Yes, that's right
___
*[src/info.c, line 62 at r4](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6k_rq9bTN_zVg6dGa:-Mf6k_rq9bTN_zVg6dGb:b66jk3r) ([raw file](https://github.com/pmem/rpma/blob/28d0f0b03e093706874c1c4b02aeef5d1571d06a/src/info.c#L62)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		    RPMA_LOG_ERROR(
> 		    "rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): %s",
> 		    addr, port,
> 		    (hints.ai_flags & RAI_PASSIVE) ? "passive" : "active", err);
> ```
</details>


The alignment of these lines is wrong now - please use tabs instaed of spaces and the first line (`RPMA_LOG_ERROR(`) should be aligned the same as `const char *err = (ret == -1 || ret == EAI_SYSTEM) ?`.


<!-- Sent from Reviewable.io -->

2021-07-21 06:41 UTC, zhijianli88 commented
> The alignment of these lines is wrong now - please use tabs instaed of spaces and the first line (`RPMA_LOG_ERROR(`) should be aligned the same as `const char *err = (ret == -1 || ret == EAI_SYSTEM) ?`.

Fixed, then let me take a look the coverage problem.

2021-07-21 07:16 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf6uQWN5wNaYTN_2iPc:b-lzvghv) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix the coverage to not introduce new misses.
</blockquote></details>

See: https://app.codecov.io/gh/pmem/rpma/compare/1141/tree/src/info.c
Two new misses are in these 2 lines:
```
57		const char *err = (ret == -1 || ret == EAI_SYSTEM) ?
58			strerror(errno) : gai_strerror(ret);
```

---
___
*[src/info.c, line 62 at r4](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6k_rq9bTN_zVg6dGa:-Mf6tkJU1BTMdg_25O1y:bml4hmh) ([raw file](https://github.com/pmem/rpma/blob/28d0f0b03e093706874c1c4b02aeef5d1571d06a/src/info.c#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		    RPMA_LOG_ERROR(
> 		    "rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s, ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP): %s",
> 		    addr, port,
> 		    (hints.ai_flags & RAI_PASSIVE) ? "passive" : "active", err);
> ```

The alignment of these lines is wrong now - please use tabs instaed of spaces and the first line (`RPMA_LOG_ERROR(`) should be aligned the same as `const char *err = (ret == -1 || ret == EAI_SYSTEM) ?`.

</blockquote></details>

This is OK now, thanks!


<!-- Sent from Reviewable.io -->

2021-07-21 07:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf6vKkq9c2h92C_hGNS:b-92zaij) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See: https://app.codecov.io/gh/pmem/rpma/compare/1141/tree/src/info.c
Two new misses are in these 2 lines:
```
57		const char *err = (ret == -1 || ret == EAI_SYSTEM) ?
58			strerror(errno) : gai_strerror(ret);
```
</blockquote></details>

If you need help with this issue, please let me know.

---


<!-- Sent from Reviewable.io -->

2021-07-21 09:31 UTC, zhijianli88 commented
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf6vKkq9c2h92C_hGNS:b-92zaij) (no related file):_
> 
> Previously, ldorau (Lukasz Dorau) wrote…
> If you need help with this issue, please let me know.



> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf6vKkq9c2h92C_hGNS:b-92zaij) (no related file):_
> 
> Previously, ldorau (Lukasz Dorau) wrote…
> If you need help with this issue, please let me know.

Well, thank you.  Indeed, i'm new to mock testing framwork, So i asked @yangx-jy  for some help first.

2021-07-21 09:34 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf7OLB17ozu9SZWyUSx:byehkq) (no related file):*
<details><summary><i>Previously, zhijianli88 (Li Zhijian) wrote…</i></summary><blockquote>

Well, thank you.  Indeed, i'm new to mock testing framwork, So i asked @yangx-jy  for some help first.
</blockquote></details>

Hi @zhijianli88 

You should update the related unit tests, like this:
```
 tests/unit/common/mocks-rdma_cm.c |  3 +-
 tests/unit/info/info-new.c        | 58 ++++++++++++++++++-------------
 2 files changed, 36 insertions(+), 25 deletions(-)

diff --git a/tests/unit/common/mocks-rdma_cm.c b/tests/unit/common/mocks-rdma_cm.c
index ea25587..09b9e7e 100644
--- a/tests/unit/common/mocks-rdma_cm.c
+++ b/tests/unit/common/mocks-rdma_cm.c
@@ -318,8 +318,9 @@ rdma_getaddrinfo(const char *node, const char *port,
 		return 0;
 
 	errno = mock_type(int);
+	int ret = mock_type(int);
 
-	return -1;
+	return ret;
 }
 
 /*
diff --git a/tests/unit/info/info-new.c b/tests/unit/info/info-new.c
index 457fa73..929eb96 100644
--- a/tests/unit/info/info-new.c
+++ b/tests/unit/info/info-new.c
@@ -21,6 +21,10 @@
 #include "mocks-rdma_cm.h"
 
 #include <infiniband/verbs.h>
+#include <netdb.h>
+
+static int rets[] = {-1, EAI_SYSTEM, EAI_AGAIN};
+static int num_rets = sizeof(rets) / sizeof(rets[0]);
 
 /*
  * new__addr_NULL -- NULL addr is not valid
@@ -92,19 +96,22 @@ new__getaddrinfo_ERRNO_ACTIVE(void **unused)
 	 * rdma_getaddrinfo() has failed.
 	 */
 	struct rdma_addrinfo_args get_args = {MOCK_VALIDATE, NULL};
-	will_return(rdma_getaddrinfo, &get_args);
-	expect_value(rdma_getaddrinfo, hints->ai_flags, 0);
-	will_return(rdma_getaddrinfo, MOCK_ERRNO);
 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
-
-	/* run test */
-	struct rpma_info *info = NULL;
-	int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_ACTIVE,
-			&info);
-
-	/* verify the results */
-	assert_int_equal(ret, RPMA_E_PROVIDER);
-	assert_null(info);
+	for (int i = 0; i < num_rets; i++) {
+		will_return(rdma_getaddrinfo, &get_args);
+		expect_value(rdma_getaddrinfo, hints->ai_flags, 0);
+		will_return(rdma_getaddrinfo, MOCK_ERRNO);
+		will_return(rdma_getaddrinfo, rets[i]);
+
+		/* run test */
+		struct rpma_info *info = NULL;
+		int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_ACTIVE,
+				&info);
+
+		/* verify the results */
+		assert_int_equal(ret, RPMA_E_PROVIDER);
+		assert_null(info);
+	}
 }
 
 /*
@@ -120,19 +127,22 @@ new__getaddrinfo_ERRNO_PASSIVE(void **unused)
 	 * rdma_getaddrinfo() has failed.
 	 */
 	struct rdma_addrinfo_args get_args = {MOCK_VALIDATE, NULL};
-	will_return(rdma_getaddrinfo, &get_args);
-	expect_value(rdma_getaddrinfo, hints->ai_flags, RAI_PASSIVE);
-	will_return(rdma_getaddrinfo, MOCK_ERRNO);
 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
-
-	/* run test */
-	struct rpma_info *info = NULL;
-	int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_PASSIVE,
-			&info);
-
-	/* verify the results */
-	assert_int_equal(ret, RPMA_E_PROVIDER);
-	assert_null(info);
+	for (int i = 0; i < num_rets; i++) {
+		will_return(rdma_getaddrinfo, &get_args);
+		expect_value(rdma_getaddrinfo, hints->ai_flags, RAI_PASSIVE);
+		will_return(rdma_getaddrinfo, MOCK_ERRNO);
+		will_return(rdma_getaddrinfo, rets[i]);
+
+		/* run test */
+		struct rpma_info *info = NULL;
+		int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_PASSIVE,
+				&info);
+
+		/* verify the results */
+		assert_int_equal(ret, RPMA_E_PROVIDER);
+		assert_null(info);
+	}
 }
 
 /*
```

@ldorau

Do you know why we cannot call `will_return_maybe()` in loops?
It will shows the following error when I put `will_return_maybe(__wrap__test_malloc)` into loops:
```
[  ERROR   ] --- %s() has remaining non-returned values.
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
```
```


---


<!-- Sent from Reviewable.io -->

2021-07-21 09:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy and @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf7QyVv9-KgZf23EzGw:b-9eylb7) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @zhijianli88 

You should update the related unit tests, like this:
``
 tests/unit/common/mocks-rdma_cm.c |  3 +-
 tests/unit/info/info-new.c        | 58 ++++++++++++++++++-------------
 2 files changed, 36 insertions(+), 25 deletions(-)

diff --git a/tests/unit/common/mocks-rdma_cm.c b/tests/unit/common/mocks-rdma_cm.c
index ea25587..09b9e7e 100644
--- a/tests/unit/common/mocks-rdma_cm.c
+++ b/tests/unit/common/mocks-rdma_cm.c
@@ -318,8 +318,9 @@ rdma_getaddrinfo(const char *node, const char *port,
 		return 0;
 
 	errno = mock_type(int);
+	int ret = mock_type(int);
 
-	return -1;
+	return ret;
 }
 
 /*
diff --git a/tests/unit/info/info-new.c b/tests/unit/info/info-new.c
index 457fa73..929eb96 100644
--- a/tests/unit/info/info-new.c
+++ b/tests/unit/info/info-new.c
@@ -21,6 +21,10 @@
 #include "mocks-rdma_cm.h"
 
 #include <infiniband/verbs.h>
+#include <netdb.h>
+
+static int rets[] = {-1, EAI_SYSTEM, EAI_AGAIN};
+static int num_rets = sizeof(rets) / sizeof(rets[0]);
 
 /*
  * new__addr_NULL -- NULL addr is not valid
@@ -92,19 +96,22 @@ new__getaddrinfo_ERRNO_ACTIVE(void **unused)
 	 * rdma_getaddrinfo() has failed.
 	 */
 	struct rdma_addrinfo_args get_args = {MOCK_VALIDATE, NULL};
-	will_return(rdma_getaddrinfo, &get_args);
-	expect_value(rdma_getaddrinfo, hints->ai_flags, 0);
-	will_return(rdma_getaddrinfo, MOCK_ERRNO);
 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
-
-	/* run test */
-	struct rpma_info *info = NULL;
-	int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_ACTIVE,
-			&info);
-
-	/* verify the results */
-	assert_int_equal(ret, RPMA_E_PROVIDER);
-	assert_null(info);
+	for (int i = 0; i < num_rets; i++) {
+		will_return(rdma_getaddrinfo, &get_args);
+		expect_value(rdma_getaddrinfo, hints->ai_flags, 0);
+		will_return(rdma_getaddrinfo, MOCK_ERRNO);
+		will_return(rdma_getaddrinfo, rets[i]);
+
+		/* run test */
+		struct rpma_info *info = NULL;
+		int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_ACTIVE,
+				&info);
+
+		/* verify the results */
+		assert_int_equal(ret, RPMA_E_PROVIDER);
+		assert_null(info);
+	}
 }
 
 /*
@@ -120,19 +127,22 @@ new__getaddrinfo_ERRNO_PASSIVE(void **unused)
 	 * rdma_getaddrinfo() has failed.
 	 */
 	struct rdma_addrinfo_args get_args = {MOCK_VALIDATE, NULL};
-	will_return(rdma_getaddrinfo, &get_args);
-	expect_value(rdma_getaddrinfo, hints->ai_flags, RAI_PASSIVE);
-	will_return(rdma_getaddrinfo, MOCK_ERRNO);
 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
-
-	/* run test */
-	struct rpma_info *info = NULL;
-	int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_PASSIVE,
-			&info);
-
-	/* verify the results */
-	assert_int_equal(ret, RPMA_E_PROVIDER);
-	assert_null(info);
+	for (int i = 0; i < num_rets; i++) {
+		will_return(rdma_getaddrinfo, &get_args);
+		expect_value(rdma_getaddrinfo, hints->ai_flags, RAI_PASSIVE);
+		will_return(rdma_getaddrinfo, MOCK_ERRNO);
+		will_return(rdma_getaddrinfo, rets[i]);
+
+		/* run test */
+		struct rpma_info *info = NULL;
+		int ret = rpma_info_new(MOCK_ADDR, MOCK_PORT, RPMA_INFO_PASSIVE,
+				&info);
+
+		/* verify the results */
+		assert_int_equal(ret, RPMA_E_PROVIDER);
+		assert_null(info);
+	}
 }
 
 /*
```

@ldorau

Do you know why we cannot call `will_return_maybe()` in loops?
It will shows the following error when I put `will_return_maybe(__wrap__test_malloc)` into loops:
```
[  ERROR   ] --- %s() has remaining non-returned values.
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
```
</blockquote></details>

Please let us know the link to the branch with your test code.

And for the future - please do not paste so much code into comments, because it is unreadable, but a link to the branch with this code instead.

---


<!-- Sent from Reviewable.io -->

2021-07-21 09:51 UTC, zhijianli88 commented
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy and @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf7QyVv9-KgZf23EzGw:b-9eylb7) (no related file):_
> 
> Previously, yangx-jy (Xiao Yang) wrote…


Looks the *Reviewable* doesn't support markdonw well as the github

I have folded his patch to this PR, PTAL.

2021-07-21 10:07 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-Mf7X89bEIXdUuu-U76p:b-73tlq0) (no related file):*
<details><summary><i>Previously, zhijianli88 (Li Zhijian) wrote…</i></summary><blockquote>

Looks the *Reviewable* doesn't support markdonw well as the github

I have folded his patch to this PR, PTAL.

</blockquote></details>

The coverage is fixed, thanks!

---


<!-- Sent from Reviewable.io -->

2021-07-22 02:20 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-MfB-hCkC6noSW9xKhTL:b-c9bzyr) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The coverage is fixed, thanks!
</blockquote></details>

@ldorau 

Do you know why we cannot call `will_return_maybe()` in loops?
It will shows the following error when I put `will_return_maybe(__wrap__test_malloc)` into loops:
```
[ ERROR ] --- %s() has remaining non-returned values.
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
```

---


<!-- Sent from Reviewable.io -->

2021-07-22 06:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-MfBxmV59yCEzHMm7V46:bnme1ru) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

Do you know why we cannot call `will_return_maybe()` in loops?
It will shows the following error when I put `will_return_maybe(__wrap__test_malloc)` into loops:
```
[ ERROR ] --- %s() has remaining non-returned values.
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
/home/yangx/rpma/tests/unit/info/info-new.c:104: note: remaining item was declared here
```
</blockquote></details>

Where do you want to use it? The current code compiles without any errors ...

---


<!-- Sent from Reviewable.io -->

2021-07-22 06:52 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @zhijianli88)

___
*[tests/unit/common/mocks-rdma_cm.c, line 321 at r6](https://reviewable.io/reviews/pmem/rpma/1141#-MfByx1g5A-HFF9bvOha:-MfByx1g5A-HFF9bvOhb:bn6ex7j) ([raw file](https://github.com/pmem/rpma/blob/890e3b74a2f9c44d734859801c5f6f4d61ad64b2/tests/unit/common/mocks-rdma_cm.c#L321)):*
> ```
> 	errno = mock_type(int);
> 	int ret = mock_type(int);
> ```

```c
	int ret = mock_type(int);
	if (ret)
		errno = mock_type(int);
```


<!-- Sent from Reviewable.io -->

2021-07-22 07:10 UTC, yangx-jy commented
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-MfC1Z481fOJsM-XTF0s:b-cp6fwq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Where do you want to use it? The current code compiles without any errors ...
</blockquote></details>

Hi @ldorau 

Current code calls will_return_maybe() once outside the loop.
In fact, I want to move it into the loop before, but running tests will report above error in this case.

---


<!-- Sent from Reviewable.io -->

2021-07-22 07:35 UTC, yangx-jy commented
___
*[tests/unit/common/mocks-rdma_cm.c, line 321 at r6](https://reviewable.io/reviews/pmem/rpma/1141#-MfByx1g5A-HFF9bvOha:-MfC67tz7Hvmw2zdL3Qw:b-wc815c) ([raw file](https://github.com/pmem/rpma/blob/890e3b74a2f9c44d734859801c5f6f4d61ad64b2/tests/unit/common/mocks-rdma_cm.c#L321)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	errno = mock_type(int);
> 	int ret = mock_type(int);
> ```

```c
	int ret = mock_type(int);
	if (ret)
		errno = mock_type(int);
```
</blockquote></details>

Hi @ldorau 

It seems wrong.  `ret` always means the invalid return value because we check if `rdma_getaddrinfo()` succeeds by `args->res` instead of `ret`

I think we just need to do the following steps:
```
errno = mock_type(int);
return mock_type(int);
``` 


<!-- Sent from Reviewable.io -->

2021-07-22 07:48 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-Mf6hknnEmWlEXeq7uju:-MfCA38M9qk14HSEjPyt:bh704qf) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 

Current code calls will_return_maybe() once outside the loop.
In fact, I want to move it into the loop before, but running tests will report above error in this case.
</blockquote></details>

See https://api.cmocka.org/group__cmocka__mock.html#ga73ef52ccf68061b759746f9a51d1e419

will_return_maybe() "stores a value which will **always** be returned by mock() but is not required to be returned by at least one call to mock()."  - If it will **always** be returned by mock(), it seems it should be called only once ...

---


<!-- Sent from Reviewable.io -->

2021-07-22 08:14 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/common/mocks-rdma_cm.c, line 321 at r6](https://reviewable.io/reviews/pmem/rpma/1141#-MfByx1g5A-HFF9bvOha:-MfCGXZYCMvUZzjHwpUa:bb1nusu) ([raw file](https://github.com/pmem/rpma/blob/890e3b74a2f9c44d734859801c5f6f4d61ad64b2/tests/unit/common/mocks-rdma_cm.c#L321)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 

It seems wrong.  `ret` always means the invalid return value because we check if `rdma_getaddrinfo()` succeeds by `args->res` instead of `ret`

I think we just need to do the following steps:
```
errno = mock_type(int);
return mock_type(int);
``` 
</blockquote></details>

`errno` should not be set if `ret == 0`, so it should be rather:

```
	int ret = mock_type(int);
	assert_int_not_equal(ret, 0);
	errno = mock_type(int);
```


<!-- Sent from Reviewable.io -->

2021-07-22 08:32 UTC, yangx-jy commented
___
*[tests/unit/common/mocks-rdma_cm.c, line 321 at r6](https://reviewable.io/reviews/pmem/rpma/1141#-MfByx1g5A-HFF9bvOha:-MfCKya19JM4aEIbfZ3g:b-ow0zhn) ([raw file](https://github.com/pmem/rpma/blob/890e3b74a2f9c44d734859801c5f6f4d61ad64b2/tests/unit/common/mocks-rdma_cm.c#L321)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`errno` should not be set if `ret == 0`, so it should be rather:

```
	int ret = mock_type(int);
	assert_int_not_equal(ret, 0);
	errno = mock_type(int);
```
</blockquote></details>

It looks good to me. ^_^


<!-- Sent from Reviewable.io -->

2021-07-22 08:41 UTC, zhijianli88 commented
> _[tests/unit/common/mocks-rdma_cm.c, line 321 at r6](https://reviewable.io/reviews/pmem/rpma/1141#-MfByx1g5A-HFF9bvOha:-MfCKya19JM4aEIbfZ3g:b-ow0zhn) ([raw file](https://github.com/pmem/rpma/blob/890e3b74a2f9c44d734859801c5f6f4d61ad64b2/tests/unit/common/mocks-rdma_cm.c#L321)):_
> 
> Previously, ldorau (Lukasz Dorau) wrote…
> It looks good to me. ^_^

just updated, thank you all.

2021-07-22 08:46 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)



<!-- Sent from Reviewable.io -->

2021-07-22 08:48 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141#-:-MfCOcxu3sDhktj_-Iyj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)



<!-- Sent from Reviewable.io -->

2021-07-26 11:35 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141#-:-MfXaKXVCYDV7DdU-JC6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)



<!-- Sent from Reviewable.io -->

2021-07-26 11:37 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)



<!-- Sent from Reviewable.io -->

2021-07-26 16:21 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 2 unresolved discussions (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-MfYYHVi90n4p_4p9dOW:-MfYYHVjAfSxjCtbG_Vh:ba0gy9w) (no related file):*
Changes in implementation and in tests have to be in the same commit. Otherwise, bisection would be impossible.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-MfYbjTV1ZDypF-e64oq:-MfYbjTV1ZDypF-e64or:b-1lb2jb) (no related file):*
Where those it come from? I can not find a recommendation to process the output in the way you have proposed.
Can you provide any references for this?

Ref: https://linux.die.net/man/3/rdma_getaddrinfo

---


<!-- Sent from Reviewable.io -->

2021-07-27 01:05 UTC, zhijianli88 commented
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 2 unresolved discussions (waiting on @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-MfYYHVi90n4p_4p9dOW:-MfYYHVjAfSxjCtbG_Vh:ba0gy9w) (no related file):_
> Changes in implementation and in tests have to be in the same commit. Otherwise, bisection would be impossible.

Understood

> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1141#-MfYbjTV1ZDypF-e64oq:-MfYbjTV1ZDypF-e64or:b-1lb2jb) (no related file):_
> Where those it come from? I can not find a recommendation to process the output in the way you have proposed.
> Can you provide any references for this?
> 
> Ref: https://linux.die.net/man/3/rdma_getaddrinfo

Looks we have to look over the source code for the latest manpage:
https://raw.githubusercontent.com/linux-rdma/rdma-core/master/librdmacm/man/rdma_getaddrinfo.3
https://github.com/linux-rdma/rdma-core/commit/cb9ff9f20e23016ddddda2114ebe6963c4052b62

2021-08-09 15:39 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)

___
*[tests/unit/info/info-new.c, line 104 at r7](https://reviewable.io/reviews/pmem/rpma/1141#-MgfRwKo4yQa-wv_o17y:-MgfRwKo4yQa-wv_o17z:b-dwfaka) ([raw file](https://github.com/pmem/rpma/blob/f1659d9fb382dc145219c9453c1f9d9c76b93115/tests/unit/info/info-new.c#L104)):*
> ```C
> 		expect_value(rdma_getaddrinfo, hints->ai_flags, 0);
> 		will_return(rdma_getaddrinfo, rets[i]);
> 		will_return(rdma_getaddrinfo, MOCK_ERRNO);
> ```

TBH the implementation may only take care of an errno value and it will pass this test no matter what return value you provide.

If you want to test if the implementation reacts accordingly to the return value you should also mock `strerror()` and `gai_strerror()`. So, you will have a few testcases:

- `ret = -1` + `errno = MOCK_ERRNO` + `expect_value(strerror, errnum, MOCK_ERRNO)`
- `ret = EAI_SYSTEM` + `errno = MOCK_ERRNO` + `expect_value(strerror, errnum, MOCK_ERRNO)`
- `ret = MOCK_EAI_ERROR` + `expect_value(gai_strerror, ecode, MOCK_EAI_ERROR)`


<!-- Sent from Reviewable.io -->

2021-08-16 02:49 UTC, zhijianli88 commented
> > Reviewed 1 of 1 files at r5, 2 of 2 files at r7.
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)
> 
> _[tests/unit/info/info-new.c, line 104 at r7](https://reviewable.io/reviews/pmem/rpma/1141#-MgfRwKo4yQa-wv_o17y:-MgfRwKo4yQa-wv_o17z:b-dwfaka) ([raw file](https://github.com/pmem/rpma/blob/f1659d9fb382dc145219c9453c1f9d9c76b93115/tests/unit/info/info-new.c#L104)):_
> 
> > ```c
> > 		expect_value(rdma_getaddrinfo, hints->ai_flags, 0);
> > 		will_return(rdma_getaddrinfo, rets[i]);
> > 		will_return(rdma_getaddrinfo, MOCK_ERRNO);
> > ```
> 
> TBH the implementation may only take care of an errno value and it will pass this test no matter what return value you provide.
> 
> If you want to test if the implementation reacts accordingly to the return value you should also mock `strerror()` and `gai_strerror()`. So, you will have a few testcases:
> 
> * `ret = -1` + `errno = MOCK_ERRNO` + `expect_value(strerror, errnum, MOCK_ERRNO)`
> * `ret = EAI_SYSTEM` + `errno = MOCK_ERRNO` + `expect_value(strerror, errnum, MOCK_ERRNO)`
> * `ret = MOCK_EAI_ERROR` + `expect_value(gai_strerror, ecode, MOCK_EAI_ERROR)`

added more cases, and thank @yangx-jy for your help.

2021-08-19 10:17 UTC, ldorau requested changes
> Reviewed 9 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy and @zhijianli88)

___
*[tests/unit/info/info-new.c, line 111 at r8](https://reviewable.io/reviews/pmem/rpma/1141#-MhSsOt6-Kd5rWbTWzZd:-MhSsOt79c0ULrRUaUfy:bs8wio1) ([raw file](https://github.com/pmem/rpma/blob/b8762e4ab1688783e13d7589f7a9a19aac963422/tests/unit/info/info-new.c#L111)):*
> ```
> expect_value(__wrap_gai_strerror, errcode, rets[i]);
> ```

expect_value(__wrap_gai_strerror, errcode, MOCK_EAI_ERRNO);
___
*[tests/unit/info/info-new.c, line 149 at r8](https://reviewable.io/reviews/pmem/rpma/1141#-MhSslaiCmoblUHcAtYg:-MhSslaiCmoblUHcAtYh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b8762e4ab1688783e13d7589f7a9a19aac963422/tests/unit/info/info-new.c#L149)):*
> ```C
> 			will_return(__wrap_strerror, MOCK_ERROR);
> 		} else {
> 			expect_value(__wrap_gai_strerror, errcode, rets[i]);
> ```

.


<!-- Sent from Reviewable.io -->

2021-08-20 03:04 UTC, zhijianli88 commented
> > Reviewed 9 of 9 files at r8.
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)_ status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy and @zhijianli88)
> 
> _[tests/unit/info/info-new.c, line 111 at r8](https://reviewable.io/reviews/pmem/rpma/1141#-MhSsOt6-Kd5rWbTWzZd:-MhSsOt79c0ULrRUaUfy:bs8wio1) ([raw file](https://github.com/pmem/rpma/blob/b8762e4ab1688783e13d7589f7a9a19aac963422/tests/unit/info/info-new.c#L111)):_
> 
> > ```
> > expect_value(__wrap_gai_strerror, errcode, rets[i]);
> > ```
> 
> expect_value(__wrap_gai_strerror, errcode, MOCK_EAI_ERRNO);
> 
> _[tests/unit/info/info-new.c, line 149 at r8](https://reviewable.io/reviews/pmem/rpma/1141#-MhSslaiCmoblUHcAtYg:-MhSslaiCmoblUHcAtYh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b8762e4ab1688783e13d7589f7a9a19aac963422/tests/unit/info/info-new.c#L149)):_
> 
> > ```c
> > 			will_return(__wrap_strerror, MOCK_ERROR);
> > 		} else {
> > 			expect_value(__wrap_gai_strerror, errcode, rets[i]);
> > ```
> 
> .

fixed

2021-08-20 05:15 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-20 05:15 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141#-:-MhWz6yn40SmFFDutxo-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-20 07:33 UTC, yangx-jy reviewed
> Reviewed 1 of 1 files at r5, 8 of 9 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-08-23 12:28 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 9 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1141#-:-Mhmyyps08PpO-32asuq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)

___
*[tests/unit/info/info-new.c, line 104 at r7](https://reviewable.io/reviews/pmem/rpma/1141#-MgfRwKo4yQa-wv_o17y:-MhmyI1xE-19ESzcbwZT:b2ayrwd) ([raw file](https://github.com/pmem/rpma/blob/f1659d9fb382dc145219c9453c1f9d9c76b93115/tests/unit/info/info-new.c#L104)):*
<details><summary><i>Previously, zhijianli88 (Li Zhijian) wrote…</i></summary><blockquote>

added more cases, and thank @yangx-jy for your help.
</blockquote></details>

Kudos to @yangx-jy. :-)
___
*[tests/unit/info/info-new.c, line 102 at r9](https://reviewable.io/reviews/pmem/rpma/1141#-MhmyPgO-E2CJxaNPgRG:-MhmyPgO-E2CJxaNPgRH:bw3n4rw) ([raw file](https://github.com/pmem/rpma/blob/014dcd01680a88151558aac3a6bfd188a3a3e4bf/tests/unit/info/info-new.c#L102)):*
> ```C
> 	struct rdma_addrinfo_args get_args = {MOCK_VALIDATE, NULL};
> 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
> 	for (int i = 0; i < num_rets; i++) {
> ```

I do not want to postpone this PR anymore. But if you are feeling fancy you can try to rework this loop into a test case without a loop but using a prestate instead. It will be more aligned to the unit test API.


<!-- Sent from Reviewable.io -->

2021-08-23 12:29 UTC, merged