tools: add --create_on_open=1 for the DRAM mode
pmem/rpma pull request #1157
Opened 2021-07-22 06:53 UTC by yangx-jy

When we run server ioengine with DRAM, setup_files() in fio will create the unused 'malloc' file by some operations (e.g. fallocate, ftruncate). This behavior makes server spend more time to prepare the connection so that client always triggers the "The maximum number of retries exceeded" error.  See the detailed output:
```
Thread [7]: The maximum number of retries exceeded. Closing. IOPS][eta 01m:00s]
Thread [7]: Connected after retry #10
Thread [29]: Connected after retry #9
Thread [2]: The maximum number of retries exceeded. Closing.
Thread [9]: The maximum number of retries exceeded. Closing.
Thread [2]: Connected after retry #10
Thread [9]: Connected after retry #10
Thread [15]: The maximum number of retries exceeded. Closing.
Thread [15]: Connected after retry #10
Thread [19]: The maximum number of retries exceeded. Closing.
Thread [19]: Connected after retry #10
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15279, err=-1/
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15284, err=-1/
fio: pid=15292, err=-1/
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15286, err=-1/
fio: pid=15296, err=-1/
Thread [30]: The maximum number of retries exceeded. Closing.
Thread [30]: Connected after retry #10
fio: io engine librpma_apm_client init failed. Perhaps try reducing io depth?
fio: pid=15307, err=-1/
```

disallow setup_files() to create the unused 'malloc' file by adding --create_on_open=1.

Ref: https://github.com/pmem/fio/pull/257

Note: This path is based on #1144

2021-07-22 09:15 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157#-:-MfCUxTu10ZXaXKycuJA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 08:22 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157#-:-MfWu1LXAQXP1GHAsZKN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-07-26 08:29 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-06 08:57 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/perf/rpma_fio_bench.sh, line 291 at r1](https://reviewable.io/reviews/pmem/rpma/1157#-MgPfTS1EgZY0Kk0NzC9:-MgPfTS1EgZY0Kk0NzCA:bb6fzh9) ([raw file](https://github.com/pmem/rpma/blob/b1352f80355a06db323b1bc78918f773d677f34a/tools/perf/rpma_fio_bench.sh#L291)):*
> ```Shell
> 		else
> 			CREATE_ON_OPEN=""
> 		fi
> ```

Can we find a way to not create this file at all?


<!-- Sent from Reviewable.io -->

2021-08-06 09:19 UTC, yangx-jy commented
___
*[tools/perf/rpma_fio_bench.sh, line 291 at r1](https://reviewable.io/reviews/pmem/rpma/1157#-MgPfTS1EgZY0Kk0NzC9:-MgPgu_wCVibJb9vnHCb:b-y0ea11) ([raw file](https://github.com/pmem/rpma/blob/b1352f80355a06db323b1bc78918f773d677f34a/tools/perf/rpma_fio_bench.sh#L291)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we find a way to not create this file at all?
</blockquote></details>

Hi @janekmi 

create_on_open=1 disallows common setup_files() to create this file and then lets engines's `.open_file` to process this file.
For rpma server engine, it doesn't create this file and just allocates dram by checking the filename.
For file create engine, it actually creates this file.


<!-- Sent from Reviewable.io -->

2021-08-09 14:43 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1157#-MgfLjyf5jb3OBPa2mMS:-MgfLjyf5jb3OBPa2mMT:b-ik0nha) ([raw file](https://github.com/pmem/rpma/blob/b1352f80355a06db323b1bc78918f773d677f34a/tools/perf/rpma_fio_bench.sh#L279)):*
> ```Shell
> 		case "$REMOTE_JOB_DEST" in
> 			malloc|/dev/dax*)
> 				FILE_NAME="--filename=${REMOTE_JOB_DEST}"
> ```

It seems the same case is both for DRAM and DeviceDAX. The only case where creating files by FIO is truly desired is in the case of FileSystemDAX. The solution you have proposed won't work the same if merged with this case statement? e.g.

```sh
		# pick either a DRAM/DeviceDAX or a FileSystemDAX mode
		case "$REMOTE_JOB_DEST" in
			malloc|/dev/dax*)
                                # create_on_open prevents FIO from pre-creating files
				FILE_NAME="--filename=${REMOTE_JOB_DEST} --create_on_open=1"
				;;
			*)
				FILE_NAME="--filename_format=${REMOTE_JOB_DEST}.\\\$jobnum"
				;;
		esac
```


<!-- Sent from Reviewable.io -->

2021-08-10 14:50 UTC, yangx-jy commented
___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1157#-MgfLjyf5jb3OBPa2mMS:-MgkW-6T0hgRHpZjyP05:b-20160e) ([raw file](https://github.com/pmem/rpma/blob/b1352f80355a06db323b1bc78918f773d677f34a/tools/perf/rpma_fio_bench.sh#L279)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems the same case is both for DRAM and DeviceDAX. The only case where creating files by FIO is truly desired is in the case of FileSystemDAX. The solution you have proposed won't work the same if merged with this case statement? e.g.

```sh
		# pick either a DRAM/DeviceDAX or a FileSystemDAX mode
		case "$REMOTE_JOB_DEST" in
			malloc|/dev/dax*)
                                # create_on_open prevents FIO from pre-creating files
				FILE_NAME="--filename=${REMOTE_JOB_DEST} --create_on_open=1"
				;;
			*)
				FILE_NAME="--filename_format=${REMOTE_JOB_DEST}.\\\$jobnum"
				;;
		esac
```
</blockquote></details>

DeviceDAX doesn't need the `--create_on_open=1` option becuase fio will skip creating files automatically when finding that filename is a character device.

By the way, I am thinking about if there is a better fix.


<!-- Sent from Reviewable.io -->

2021-08-23 12:36 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1157#-MgfLjyf5jb3OBPa2mMS:-MhmztbgAMSn1Vnn2dpB:b-2arzpk) ([raw file](https://github.com/pmem/rpma/blob/b1352f80355a06db323b1bc78918f773d677f34a/tools/perf/rpma_fio_bench.sh#L279)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

DeviceDAX doesn't need the `--create_on_open=1` option becuase fio will skip creating files automatically when finding that filename is a character device.

By the way, I am thinking about if there is a better fix.
</blockquote></details>

Got it. So the full case-in-statement will look as follows:

```sh
		# pick either a DRAM/DeviceDAX or a FileSystemDAX mode
		case "$REMOTE_JOB_DEST" in
			malloc)
                                # create_on_open prevents FIO from creating files
                                # where the engines won't make use of them anyways since they are using DRAM instead
				FILE_NAME="--filename=${REMOTE_JOB_DEST} --create_on_open=1"
				;;
			/dev/dax*)
				FILE_NAME="--filename=${REMOTE_JOB_DEST}"
				;;
			*)
				FILE_NAME="--filename_format=${REMOTE_JOB_DEST}.\\\$jobnum"
				;;
		esac
```

**Note**: I have proposed a more descriptive comment for future generations.


<!-- Sent from Reviewable.io -->

2021-08-30 05:03 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-30 05:03 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-02 22:58 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1157#-:-Miciuh-5Krm8VLoDqnM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-02 22:58 UTC, merged