Print message in case no pmem detected in examples
pmem/rpma pull request #1185
Opened 2021-08-03 12:03 UTC by Patryk717

2021-08-03 12:26 UTC, PatKamin reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 4 unresolved discussions (waiting on @Patryk717)

___
*[examples/03-read-to-persistent/client.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAx2x16VANsY4Sm5ny:-MgAx2x16VANsY4Sm5nz:b-c2g5er) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/03-read-to-persistent/client.c#L131)):*
> ```C
> 	/* if no pmem support or it is not provided */
> 	if (mr_ptr == NULL) {
> 		
> ```

No need for adding this empty line.
___
*[examples/03-read-to-persistent/client.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAwqe-EXK_3nQWRvNC:-MgAwqe-EXK_3nQWRvND:b-xsa1dx) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/03-read-to-persistent/client.c#L132)):*
> ```C
> 	if (mr_ptr == NULL) {
> 		
> 		printer(); /*add printf */
> ```

Rename this method to sth more informative, ie. print_no_pmem_detected or sth like that.
___
*[examples/common/common-conn.h, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAxExB1UhwopbOF4eg:-MgAxExB1UhwopbOF4eh:b-xilquu) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.h#L64)):*
> ```objc
> int common_wait_for_conn_close_and_disconnect(struct rpma_conn **conn_ptr);
> int common_disconnect_and_wait_for_conn_close(struct rpma_conn **conn_ptr);
> void printer(); 
> ```

Add an extra line below.
___
*[examples/common/common-conn.c, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAxI2lCxGCd0maWa3D:-MgAxI2lCxGCd0maWa3E:b-k3alqu) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.c#L201)):*
> ```C
> printer()
> {
> 	printf("No pmem supportt or pow to pmem no provity \n"); /*add printf */
> ```

Perhaps "PMEM not detected or a path to PMEM not provided. Example usage of functions using PMEM skipped.", or sth similar.


<!-- Sent from Reviewable.io -->

2021-08-04 07:32 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 5 unresolved discussions (waiting on @Patryk717)

___
*[examples/common/common-conn.h, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgF3j-LCrxHOLgueIKE:-MgF3j-LCrxHOLgueIKF:b-7k8v93) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright 2020, Intel Corporation */
> ```

2020-2021


<!-- Sent from Reviewable.io -->

2021-08-06 17:51 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 8 unresolved discussions (waiting on @PatKamin and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1185#-MgRFOPR3uOGMKifijG0:-MgRFOPR3uOGMKifijG1:bgte9nd) (no related file):*
1. You have to add a prefix at the beginning of the commit:

```
FAIL: subject line in commit message does not contain valid area name

commit eb67b0572a4d7b2ee21f57aad5f84210488b1328
Author: Patryk717 <patrykzbierski717@wp.pl>
Date:   Sun Aug 1 21:28:27 2021 +0200

    Print message in case no pmem detected in examples

Modified files:
examples/03-read-to-persistent/client.c
examples/common/common-conn.c
examples/common/common-conn.h

Areas computed basing on the list of modified files: (see utils/check-area.sh for full algorithm)
examples
```

Ref: https://github.com/pmem/rpma/pull/1185/checks?check_run_id=3239654329

2. Please add to the commit message:

```
Ref: #1089
```

So, effectively the commit message will look as follow:

```
examples: print a message in case no pmem provided or able to be used

Ref: #1089
```

---
___
*[examples/03-read-to-persistent/client.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgR_BZpAdQxVHQDUe8e:-MgR_BZpAdQxVHQDUe8f:b-lyc5wb) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/03-read-to-persistent/client.c#L132)):*
> ```C
> 	if (mr_ptr == NULL) {
> 		
> 		printer(); /*add printf */
> ```

```c
(void) fprintf(stderr, NO_PMEM_MSG);
```

The `NO_PMEM_MSG` will describe the situation precisely, because of the way it is defined. Please see other comments.
___
*[examples/common/common-conn.h, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgRWb4k1JRTA29w670V:-MgRWb4k1JRTA29w670W:bnph463) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.h#L20)):*
> ```objc
> #define SIGNATURE_LEN (strlen(SIGNATURE_STR) + 1)
> 
> #endif
> ```

```c
#if

#define NO_PMEM_MSG "No <pmem-path> provided. Using DRAM instead."
/* ... */

#else

#define NO_PMEM_MSG "The example is unable to use libpmem. If unintended please check the build log. Using DRAM instead."

#endif
```

**Note**:

1. When `USE_LIBPMEM` is not defined it means the example binary won't even try to use PMEM because this capability was turned off during the build process. So, we can just say the example is unable to use libpmem and refer the end-user to the build log.
2. When `USE_LIBPMEM` is set there are two possibilities:
    - a) the end-user will provide a `<pmem-path>` OR
    - b) he won't provide a `<pmem-path>`

When `<pmem-path>` is provided (2a) it will be mapped. If the mapping process succeeds we have nothing to do. The PMEM is there. If any error occurs during the mapping process it will be printed where it happens and the process will be terminated. So, nothing to do for us.
The only interesting case is 2b where `<pmem-path>` is not provided. And only this case is covered in the proposition above.
___
*[examples/common/common-conn.c, line 199 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgRVhJOA5mmJdIz-Yrp:-MgRVhJOA5mmJdIz-Yrq:bu9wxue) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.c#L199)):*
> ```C
> 
> void
> printer()
> ```

FYI Having a function to just call printf() is overkill.
___
*[examples/common/common-conn.c, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAxI2lCxGCd0maWa3D:-MgRVSfc4NuF3xbLtukD:bw02yed) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.c#L201)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Perhaps "PMEM not detected or a path to PMEM not provided. Example usage of functions using PMEM skipped.", or sth similar.
</blockquote></details>

I don't like the idea of having 'A or B' message. I think we can do better. Please see other comments.


<!-- Sent from Reviewable.io -->

2021-08-09 10:36 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 8 unresolved discussions (waiting on @PatKamin and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1185#-MgeT_uyD-X2C_0G0dDL:-MgeT_uzEt8q2lV1MDsD:b3su9u7) (no related file):*
Please squash all commits to a single one.

---
___
*[examples/common/common-conn.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgeTiod36GBZXsdGfSV:-MgeTiod36GBZXsdGfSW:b-583n8u) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/common/common-conn.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright 2020-2021	, Intel Corporation */
> ```

No tab after `2021`. Please remove.
___
*[examples/common/common-conn.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgeTrt68vOGQrVPbN_z:-MgeTrt68vOGQrVPbNa-:b-uud9ir) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/common/common-conn.h#L66)):*
> ```objc
> int common_wait_for_conn_close_and_disconnect(struct rpma_conn **conn_ptr);
> int common_disconnect_and_wait_for_conn_close(struct rpma_conn **conn_ptr);
> ```

This newline is not needed here.


<!-- Sent from Reviewable.io -->

2021-08-09 12:19 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 12 unresolved discussions (waiting on @PatKamin and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1185#-Mgep5FLDo0fHBkmkx11:-Mgep5FM9dIoEuqsVKX4:bgznnri) (no related file):*
You have a few cstyle issues:

```
/rpma/examples/common/common-conn.h:21: line > 80 characters
/rpma/examples/03-read-to-persistent/client.c:132: continuation line not indented by 4 spaces
/rpma/examples/03-read-to-persistent/client.c:133: continuation line not indented by 4 spaces
/rpma/examples/03-read-to-persistent/client.c:133: left brace starting a line
```

Ref: https://github.com/pmem/rpma/pull/1185/checks?check_run_id=3280142304

---
___
*[examples/03-read-to-persistent/client.c, line 130 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgeqQTAEsfNFN6Aju8z:-MgeqQTB3mgE39KPu3oZ:b-3n4cxg) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/03-read-to-persistent/client.c#L130)):*
> ```C
> 
> 	/* if no pmem support or it is not provided */
> 	 if (mr_ptr == NULL)
> ```

What this new space is doing here? ;-)
___
*[examples/03-read-to-persistent/client.c, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgepiF72tRZzmEdHdH0:-MgepiF804Xv6BvoSlT3:b-fdqysz) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/03-read-to-persistent/client.c#L131)):*
> ```C
> 	/* if no pmem support or it is not provided */
> 	 if (mr_ptr == NULL)
> 	 {
> ```

What has happened with this brace? ;-)
___
*[examples/common/common-conn.h, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgepNqN3WX9q3YTe_Ud:-MgepNqN3WX9q3YTe_Ue:b-mwecjw) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/common/common-conn.h#L21)):*
> ```objc
> #define NO_PMEM_MSG "No <pmem-path> provided. Using DRAM instead. \n"
> #else
> #define NO_PMEM_MSG "The example is unable to use libpmem. If unintended please check the build log. Using DRAM instead. \n"
> ```

You have to break this line as follow:

```c
#define NO_PMEM_MSG \
    "The example is unable to use libpmem. If unintended please check the build log. Using DRAM instead.\n"
```

**Note**: Spaces and indentations are important. ;-)


<!-- Sent from Reviewable.io -->

2021-08-09 12:37 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @janekmi, @osalyk, @PatKamin, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1185#-MgeT_uyD-X2C_0G0dDL:-Mges1u4Cr95omSlqccJ:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please squash all commits to a single one.
</blockquote></details>

Done.

---
___
*[examples/03-read-to-persistent/client.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAx2x16VANsY4Sm5ny:-MgessgQAlp77Z31xsaT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/03-read-to-persistent/client.c#L131)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

No need for adding this empty line.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAwqe-EXK_3nQWRvNC:-Mgesx2X1taQWPMTtaEk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/03-read-to-persistent/client.c#L132)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Rename this method to sth more informative, ie. print_no_pmem_detected or sth like that.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 130 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgeqQTAEsfNFN6Aju8z:-MgesvjyDEhM0y_dFHac:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/03-read-to-persistent/client.c#L130)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What this new space is doing here? ;-)
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgepiF72tRZzmEdHdH0:-Mgesv-x0Uie4pcR5D6D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/03-read-to-persistent/client.c#L131)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What has happened with this brace? ;-)
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgF3j-LCrxHOLgueIKE:-MgetVE7Ci4bbonkdJcN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.h#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2020-2021
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAxExB1UhwopbOF4eg:-MgetAaC3UuPS-CuQNaq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.h#L64)):*
<details><summary><i>Previously, PatKamin (Patryk Kaminski) wrote…</i></summary><blockquote>

Add an extra line below.
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgeTiod36GBZXsdGfSV:-MgetVhjBnYJeQtVgBsU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/common/common-conn.h#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No tab after `2021`. Please remove.
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgeTrt68vOGQrVPbN_z:-MgetAxwAFiWFZRLNq60:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/common/common-conn.h#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This newline is not needed here.
</blockquote></details>

Done.
___
*[examples/common/common-conn.c, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/1185#-MgAxI2lCxGCd0maWa3D:-MgetCME2u4FcflphlY_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb67b0572a4d7b2ee21f57aad5f84210488b1328/examples/common/common-conn.c#L201)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like the idea of having 'A or B' message. I think we can do better. Please see other comments.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 12:40 UTC, PatKamin reviewed
> Reviewed 1 of 2 files at r3, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi, @osalyk, and @Patryk717)



<!-- Sent from Reviewable.io -->

2021-08-09 12:42 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1185#-Mgep5FLDo0fHBkmkx11:-Mgevr5MDCG74cN0gp5f:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have a few cstyle issues:

```
/rpma/examples/common/common-conn.h:21: line > 80 characters
/rpma/examples/03-read-to-persistent/client.c:132: continuation line not indented by 4 spaces
/rpma/examples/03-read-to-persistent/client.c:133: continuation line not indented by 4 spaces
/rpma/examples/03-read-to-persistent/client.c:133: left brace starting a line
```

Ref: https://github.com/pmem/rpma/pull/1185/checks?check_run_id=3280142304

</blockquote></details>

Done.

---
___
*[examples/common/common-conn.h, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1185#-MgepNqN3WX9q3YTe_Ud:-MgevXExAKJmTIQWyiyu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b326df467ea48b8bdea664da04ea93e4c449b4ca/examples/common/common-conn.h#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to break this line as follow:

```c
#define NO_PMEM_MSG \
    "The example is unable to use libpmem. If unintended please check the build log. Using DRAM instead.\n"
```

**Note**: Spaces and indentations are important. ;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 12:45 UTC, PatKamin reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185#-:-MgewAHq0g0vbnM70Hf2:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-09 14:30 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1185#-:-MgfJZLb2JWeuKUUCSFw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-09 14:31 UTC, merged