tools: add cpuload.json figure
pmem/rpma pull request #1187
Opened 2021-08-04 10:30 UTC by osalyk

2021-08-04 12:58 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: all files reviewed, 34 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/cpuload.json, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGBiDME_PM-0K5b7o5:-MgGBiDME_PM-0K5b7o6:b-xgia8t) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L4)):*
> ```JSON
>     {
>         "output": {
>             "title": "Latency ({y}): APM to PMEM vs GPSPM(-RT) to PMEM",
> ```

... with the target CPU under load
___
*[tools/perf/figures/cpuload.json, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGBkUC8uJCFDLvtdn3:-MgGBkUC8uJCFDLvtdn4:b-d9qied) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L8)):*
> ```JSON
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "file": "lat_cpu_00_99_apm_vs_gpspm",
>             "key": "{y_key}",
> ```

I like more the idea of keeping all inside a single file under various keys e.g.:

```json
"file": "lat_apm_vs_gpspm_cpu",
"key": "cpu_00_99_{y_key}",
```
___
*[tools/perf/figures/cpuload.json, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGD52i3YjBOnOelf-v:-MgGD52i3YjBOnOelf-w:b2nhal5) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L25)):*
> ```JSON
>                     "direct_write_to_pmem": true
>                 },
>                 "label": "DRAM {rw_order}"
> ```

APM
___
*[tools/perf/figures/cpuload.json, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGD65AD1fra4eiQph5:-MgGD65AD1fra4eiQph6:btyyggd) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L33)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

GPSPM-RT
___
*[tools/perf/figures/cpuload.json, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGD8GWDx1CrfRcSTtH:-MgGD8GWDx1CrfRcSTtI:b-883eu6) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L41)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

GPSPM
___
*[tools/perf/figures/cpuload.json, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCE7P6B2fzRUpvIpe:-MgGCE7P6B2fzRUpvIpf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L47)):*
> ```JSON
>     {
>         "output": {
>             "title": "Latency ({y}): APM to PMEM vs GPSPM(-RT) to PMEM",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCJdB7qlPyH-tGR9y:-MgGCJdCBpgAYMCnBKzz:bhgkz77) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L51)):*
> ```JSON
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "file": "lat_cpu_75_99_apm_vs_gpspm",
>             "key": "{y_key}",
> ```

```json
"file": "lat_apm_vs_gpspm_cpu",
"key": "cpu_75_99_{y_key}",
```
___
*[tools/perf/figures/cpuload.json, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDCbl51DMp9_QKqh3:-MgGDCbl51DMp9_QKqh4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L68)):*
> ```JSON
>                     "direct_write_to_pmem": true
>                 },
>                 "label": "DRAM {rw_order}"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDDHs1STPaSV_wJYT:-MgGDDHs1STPaSV_wJYU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L76)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDDpL9SsZKPjLWxVr:-MgGDDpL9SsZKPjLWxVs:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L84)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCb0b5253Z8OufB95:-MgGCb0b5253Z8OufB96:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L90)):*
> ```JSON
>     {
>         "output": {
>             "title": "Bandwidth: APM to PMEM vs GPSPM(-RT) to PMEM",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCenzC08Kv0TwWON4:-MgGCenzC08Kv0TwWON5:b952exl) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L94)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_cpu_00_99_apm_vs_gpspm",
>             "key": "{x_key}",
> ```

```json
"file": "bw_apm_vs_gpspm_cpu",
"key": "cpu_00_99_{y_key}",
```
___
*[tools/perf/figures/cpuload.json, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCotl2cpjc5Tew0LE:-MgGCotl2cpjc5Tew0LF:bic92jg) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L95)):*
> ```JSON
>             "file": "bw_cpu_00_99_apm_vs_gpspm",
>             "key": "{x_key}",
>             "fstrings": ["title", "key"]
> ```

It is not true for `title`.
___
*[tools/perf/figures/cpuload.json, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDFbp0Wvpp3ljKxpG:-MgGDFbp0Wvpp3ljKxpH:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L111)):*
> ```JSON
>                     "direct_write_to_pmem": true
>                 },
>                 "label": "DRAM {rw_order}"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDGMs9Aaya4DWIU9_:-MgGDGMs9Aaya4DWIU9a:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L119)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 127 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDGqWDyBu7CG25ZbT:-MgGDGqWDyBu7CG25ZbU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L127)):*
> ```JSON
>                     "direct_write_to_pmem": false
>                 },
>                 "label": "DRAM {rw_order}"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDNG-DWpeXhrBl7dt:-MgGDNG-DWpeXhrBl7du:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L133)):*
> ```JSON
>     {
>         "output": {
>             "title": "Bandwidth: APM to PMEM vs GPSPM(-RT) to PMEM",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDKnv0ZFlrClhPfNn:-MgGDKnv0ZFlrClhPfNo:b-t0atj9) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L137)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_cpu_75_99_apm_vs_gpspm",
>             "key": "{x_key}",
> ```

```json
"file": "bw_apm_v [...]

2021-08-04 19:01 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: 0 of 1 files reviewed, 34 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/cpuload.json, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGBiDME_PM-0K5b7o5:-MgHUelt5RPOdt_mlj3G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... with the target CPU under load
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGBkUC8uJCFDLvtdn3:-MgHUx0s2oM8xBFPMw3-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like more the idea of keeping all inside a single file under various keys e.g.:

```json
"file": "lat_apm_vs_gpspm_cpu",
"key": "cpu_00_99_{y_key}",
```
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGD52i3YjBOnOelf-v:-MgHV0is6jO9b-YSTw_I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

APM
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGD65AD1fra4eiQph5:-MgHV6o19oajZHqxy7rK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

GPSPM-RT
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGD8GWDx1CrfRcSTtH:-MgHVAsoD-iYqqGNI-q2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

GPSPM
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCE7P6B2fzRUpvIpe:-MgHV_8b0YQoXddb6WgO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCJdB7qlPyH-tGR9y:-MgHVkSe9l5NbC_0TuY0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"file": "lat_apm_vs_gpspm_cpu",
"key": "cpu_75_99_{y_key}",
```
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDCbl51DMp9_QKqh3:-MgHVnt85ROWiWb5OFq9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDDHs1STPaSV_wJYT:-MgHVt8n-YOqlUijTHPO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDDpL9SsZKPjLWxVr:-MgHVttl5mHmaikDUP0e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCb0b5253Z8OufB95:-MgHVu_P9Mxmvtj4maBr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCenzC08Kv0TwWON4:-MgHW1MNBMvdxZ4aW9rT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"file": "bw_apm_vs_gpspm_cpu",
"key": "cpu_00_99_{y_key}",
```
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGCotl2cpjc5Tew0LE:-MgHWN7Q7nLLwZWQI5JN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not true for `title`.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDFbp0Wvpp3ljKxpG:-MgHWVgjBwy6aC9IY6Yu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L111)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDGMs9Aaya4DWIU9_:-MgHWWI84G853kkBBwdG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 127 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDGqWDyBu7CG25ZbT:-MgHWX4yAiHp6-M39ziV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDNG-DWpeXhrBl7dt:-MgHWZEO-v9CjvZ0WRVV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDKnv0ZFlrClhPfNn:-MgHWe165XdiX_uY-dPn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7c9549b71b14dafe56fe2e4baa9d185719d79f0b/tools/perf/figures/cpuload.json#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```json
"file": "bw_apm_vs_gpspm_cpu",
"key": "cpu_75_99_{y_key}",
```
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1187#-MgGDMUM0yV_N_kK7N6t:-MgHWifZ0a1crUwh_IBK:b-896fix) ([raw file](https://github.com [...]

2021-08-04 22:34 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/cpuload.json, line 94 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgII5sZ3NUnWjRjfKrv:-MgII5sZ3NUnWjRjfKrw:bcv4620) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L94)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu",
>             "key": "cpu_00_99_{x_key}",
> ```

I think `{x_key}` does not introduce much value in this case. Please drop it.
___
*[tools/perf/figures/cpuload.json, line 95 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHDlu8zJRicyELan_:-MgIHDlv8dukgRq2oDRB:bqg50o6) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L95)):*
> ```JSON
>             "file": "bw_apm_vs_gpspm_cpu",
>             "key": "cpu_00_99_{x_key}",
>             "fstrings": "key"
> ```

I suppose it won't work. You have to have a list here: `["key"]`
___
*[tools/perf/figures/cpuload.json, line 137 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIIEEcDeXySqELFhUD:-MgIIEEcDeXySqELFhUE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L137)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu",
>             "key": "cpu_75_99_{x_key}",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 138 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHXpY1_DOAzeEFSBs:-MgIHXpY1_DOAzeEFSBt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L138)):*
> ```JSON
>             "file": "bw_apm_vs_gpspm_cpu",
>             "key": "cpu_75_99_{x_key}",
>             "fstrings": "key"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 180 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIIGV07ObEoJAotv7Y:-MgIIGV07ObEoJAotv7Z:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L180)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu_mt",
>             "key": "cpu_00_99_{x_key}",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 181 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHgDU6H5WZ8WWxEnN:-MgIHgDU6H5WZ8WWxEnO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L181)):*
> ```JSON
>             "file": "bw_apm_vs_gpspm_cpu_mt",
>             "key": "cpu_00_99_{x_key}",
>             "fstrings": "key"
> ```

.
___
*[tools/perf/figures/cpuload.json, line 223 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIIJ2--F40R5JDwvzo:-MgIIJ2--F40R5JDwvzp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L223)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu_mt",
>             "key": "cpu_75_99_{x_key}",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 224 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHmhg9eFqhDJjXyH9:-MgIHmhg9eFqhDJjXyHA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L224)):*
> ```JSON
>             "file": "bw_apm_vs_gpspm_cpu_mt",
>             "key": "cpu_75_99_{x_key}",
>             "fstrings": "key"
> ```

.


<!-- Sent from Reviewable.io -->

2021-08-05 06:30 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/figures/cpuload.json, line 94 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgII5sZ3NUnWjRjfKrv:-MgK-E05BwGy5Yv9ru8e:b-v77yf9) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think `{x_key}` does not introduce much value in this case. Please drop it.
</blockquote></details>

how about "00_99_{x_key}" ?


<!-- Sent from Reviewable.io -->

2021-08-05 10:51 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/cpuload.json, line 94 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgII5sZ3NUnWjRjfKrv:-MgKvjlq9_F-CjW3TWpf:bi5fcb9) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L94)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

how about "00_99_{x_key}" ?
</blockquote></details>

"cpu_00_99". Please. :pray: 


<!-- Sent from Reviewable.io -->

2021-08-06 06:53 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/cpuload.json, line 94 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgII5sZ3NUnWjRjfKrv:-MgPEDhh3ICCUM305vaw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

"cpu_00_99". Please. :pray: 
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 95 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHDlu8zJRicyELan_:-MgPEEVe66vcGbucHo6C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I suppose it won't work. You have to have a list here: `["key"]`
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 137 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIIEEcDeXySqELFhUD:-MgPE6TY8tpWHViTMMpu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 138 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHXpY1_DOAzeEFSBs:-MgPEFDs7ChxLb6mXzDa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L138)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 180 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIIGV07ObEoJAotv7Y:-MgPEAGR4huEv7DVHJYt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L180)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 181 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHgDU6H5WZ8WWxEnN:-MgPEBBX-H2PAy3Dyvbf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L181)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 223 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIIJ2--F40R5JDwvzo:-MgPEC2XAvkzUCL1no9D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L223)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 224 at r2](https://reviewable.io/reviews/pmem/rpma/1187#-MgIHmhg9eFqhDJjXyH9:-MgPECoV1rVG1BXIK4QB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e756638e06a8fcd2ca44de78025ac13bfb0f883c/tools/perf/figures/cpuload.json#L224)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 08:51 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/cpuload.json, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPdmppBFi4__2VPIIl:-MgPdmppBFi4__2VPIIm:b5l3jwe) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L18)):*
> ```JSON
>             "rw": ["randwrite", "write"],
>             "cpu_load_range": "{var}",
>             "fstrings": ["label"]
> ```

`"cpu_load_range"` is missing.
___
*[tools/perf/figures/cpuload.json, line 60 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPdsiWDLIT3bwWZvoG:-MgPdsiWDLIT3bwWZvoH:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L60)):*
> ```JSON
>             "rw": ["randwrite", "write"],
>             "cpu_load_range": "{key}",
>             "fstrings": ["label"]
> ```

.
___
*[tools/perf/figures/cpuload.json, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPeAmEBKNlFqU1qNCT:-MgPeAmEBKNlFqU1qNCU:bc0irgz) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L94)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu_mt",
>             "key": ["00_75", "00_99"]
> ```

:clap: 
___
*[tools/perf/figures/cpuload.json, line 102 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPeDCq0zbNQpGGprdp:-MgPeDCq0zbNQpGGprdq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L102)):*
> ```JSON
>             "rw": ["randwrite", "write"],
>             "cpu_load_range": "{key}",
>             "fstrings": ["label"]
> ```

.


<!-- Sent from Reviewable.io -->

2021-08-06 09:30 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/cpuload.json, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPdmppBFi4__2VPIIl:-MgPn-FN2-sC2ZtNVX8Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`"cpu_load_range"` is missing.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 60 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPdsiWDLIT3bwWZvoG:-MgPn19g9H74VOfIdkud:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPeAmEBKNlFqU1qNCT:-MgPn7PA7f8AiAwqF8sf:b-nvrvxh) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:clap: 
</blockquote></details>

Not in this PR
___
*[tools/perf/figures/cpuload.json, line 102 at r3](https://reviewable.io/reviews/pmem/rpma/1187#-MgPeDCq0zbNQpGGprdp:-MgPn0NN4UtJNBz6zmiD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/196c615ef94b7da9644db5f70f724706580e7825/tools/perf/figures/cpuload.json#L102)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 10:05 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/figures/cpuload.json, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPuhuC50FDUAfhslI6:-MgPuhuC50FDUAfhslI7:bhofehq) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L51)):*
> ```JSON
>             "y": ["lat_avg", "lat_pctl_99.9", "lat_pctl_99.99"],
>             "file": "lat_apm_vs_gpspm_cpu",
>             "var": ["00_99", "75_99"],
> ```

Delete.
___
*[tools/perf/figures/cpuload.json, line 52 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPupIh2jaAwR9fc9cR:-MgPupIh2jaAwR9fc9cS:b-8hd4n8) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L52)):*
> ```JSON
>             "file": "lat_apm_vs_gpspm_cpu",
>             "var": ["00_99", "75_99"],
>             "key": "00_75_{y_key}",
> ```

75_99
___
*[tools/perf/figures/cpuload.json, line 60 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPuqXV9Bfr4LYHqHnR:-MgPuqXV9Bfr4LYHqHnS:b-8hd4n8) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L60)):*
> ```JSON
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
>             "cpu_load_range": "00_75",
> ```

75_99
___
*[tools/perf/figures/cpuload.json, line 137 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPv2d012HkxIj4E9iL:-MgPv2d012HkxIj4E9iM:b-8hd4n8) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L137)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu",
>             "key": "00_75"
> ```

75_99
___
*[tools/perf/figures/cpuload.json, line 144 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPv4ESCK59wTqL4LLp:-MgPv4ESCK59wTqL4LLq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L144)):*
> ```JSON
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
>             "cpu_load_range": "00_75",
> ```

.
___
*[tools/perf/figures/cpuload.json, line 221 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPvAC-CZ1xtfcgWd9K:-MgPvAC04yc_ECWVXcBB:b-8hd4n8) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L221)):*
> ```JSON
>             "y": "bw_avg",
>             "file": "bw_apm_vs_gpspm_cpu_mt",
>             "key": "00_75"
> ```

75_99
___
*[tools/perf/figures/cpuload.json, line 228 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPvBjZCuRr_HyPne80:-MgPvBjZCuRr_HyPne81:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L228)):*
> ```JSON
>             "tool": "rpma_fio_bench.sh",
>             "rw": ["randwrite", "write"],
>             "cpu_load_range": "00_75",
> ```

.


<!-- Sent from Reviewable.io -->

2021-08-06 10:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/cpuload.json, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPuhuC50FDUAfhslI6:-MgPwmxQ4OWOE3lTBCCq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Delete.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 52 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPupIh2jaAwR9fc9cR:-MgPwptFED7dd-KAzOos:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

75_99
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 60 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPuqXV9Bfr4LYHqHnR:-MgPwsAU46B1Wpap7c8T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

75_99
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 137 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPv2d012HkxIj4E9iL:-MgPyf9S6wbt53ncGxmZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

75_99
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 144 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPv4ESCK59wTqL4LLp:-MgPyiQQ4tFVJfwPzxQ4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L144)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 221 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPvAC-CZ1xtfcgWd9K:-MgPyogGAKs3yCaakBCn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L221)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

75_99
</blockquote></details>

Done.
___
*[tools/perf/figures/cpuload.json, line 228 at r4](https://reviewable.io/reviews/pmem/rpma/1187#-MgPvBjZCuRr_HyPne80:-MgPypfW0ZGYS2eeWAeZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d948138961ccdfc3a94982514c072aebd58cba6/tools/perf/figures/cpuload.json#L228)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 10:36 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1187#-:-MgQ1EJW-z_90OouwN9Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-08-06 10:46 UTC, merged