rpma: describe structure rpma_completion
pmem/rpma pull request #1214
Opened 2021-08-24 15:15 UTC by yangx-jy

1) add structure rpma_completion to the documentation
2) describe fields of the structure rpma_completion

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

2021-08-30 05:27 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 2621 at r1](https://reviewable.io/reviews/pmem/rpma/1214#-MiKWA0Q9bsKbOh6FfhZ:-MiKWA0Q9bsKbOh6Ffh_:bga288x) ([raw file](https://github.com/pmem/rpma/blob/314c1bd514269807acaa41fcaae2acfed1aad7bb/src/include/librpma.h#L2621)):*
> ```
> /* context of the completion */
> ```
/* user context of the completion */
shall we refer here to the source of this value i.e. op_context arg in rpma_write(...)?


<!-- Sent from Reviewable.io -->

2021-08-30 05:28 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-30 05:31 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-08-30 07:19 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 2621 at r1](https://reviewable.io/reviews/pmem/rpma/1214#-MiKWA0Q9bsKbOh6FfhZ:-MiKuOqhB5zO6qMXhlt_:b3x7ckb) ([raw file](https://github.com/pmem/rpma/blob/314c1bd514269807acaa41fcaae2acfed1aad7bb/src/include/librpma.h#L2621)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> /* context of the completion */
> ```
/* user context of the completion */
shall we refer here to the source of this value i.e. op_context arg in rpma_write(...)?
</blockquote></details>

Hi @grom72 

Do you want to explain where the value of every member comes from?
I think it seems too detailed.

@janekmi @ldorau
What do you think?


<!-- Sent from Reviewable.io -->

2021-08-30 09:00 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 2621 at r1](https://reviewable.io/reviews/pmem/rpma/1214#-MiKWA0Q9bsKbOh6FfhZ:-MiLHFRl3H7L_wUh2pzv:buiicx0) ([raw file](https://github.com/pmem/rpma/blob/314c1bd514269807acaa41fcaae2acfed1aad7bb/src/include/librpma.h#L2621)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

Do you want to explain where the value of every member comes from?
I think it seems too detailed.

@janekmi @ldorau
What do you think?
</blockquote></details>

@grom72 do you mean every member or `op_context` only?


<!-- Sent from Reviewable.io -->

2021-08-31 17:44 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 2621 at r1](https://reviewable.io/reviews/pmem/rpma/1214#-MiKWA0Q9bsKbOh6FfhZ:-MiSIRu38hc3YRcRd7Jh:be90mhi) ([raw file](https://github.com/pmem/rpma/blob/314c1bd514269807acaa41fcaae2acfed1aad7bb/src/include/librpma.h#L2621)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 do you mean every member or `op_context` only?
</blockquote></details>

@ldorau I mean op_context only to show that this is the value provided by the user when calling rpma_read/write/etc operations


<!-- Sent from Reviewable.io -->

2021-09-01 05:01 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 2621 at r1](https://reviewable.io/reviews/pmem/rpma/1214#-MiKWA0Q9bsKbOh6FfhZ:-MiUibdn6v1V1nt_AZbc:b-q6psr8) ([raw file](https://github.com/pmem/rpma/blob/314c1bd514269807acaa41fcaae2acfed1aad7bb/src/include/librpma.h#L2621)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau I mean op_context only to show that this is the value provided by the user when calling rpma_read/write/etc operations
</blockquote></details>

@yangx-jy  so not every member but op_context only


<!-- Sent from Reviewable.io -->

2021-09-02 04:42 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2634 at r3](https://reviewable.io/reviews/pmem/rpma/1214#-MiZo8QLApX005dyPyoi:-MiZo8QLApX005dyPyoj:b6aqpay) ([raw file](https://github.com/pmem/rpma/blob/4b5390542968d2b97a64662292f4328c223b7695/src/include/librpma.h#L2634)):*
> ```
> immediate data
> ```
what about ordering information?


<!-- Sent from Reviewable.io -->

2021-09-02 05:08 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 2634 at r3](https://reviewable.io/reviews/pmem/rpma/1214#-MiZo8QLApX005dyPyoi:-MiZt7s3-wMQWA3F4Tj0:bpmypq) ([raw file](https://github.com/pmem/rpma/blob/4b5390542968d2b97a64662292f4328c223b7695/src/include/librpma.h#L2634)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> immediate data
> ```
what about ordering information?
</blockquote></details>

Hi @grom72 

I removed the wrong `(in network byte order)` because rpma_cq_get_completion() has converted it to host byte order by `ntohl()`


<!-- Sent from Reviewable.io -->

2021-09-02 05:08 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 2634 at r3](https://reviewable.io/reviews/pmem/rpma/1214#-MiZo8QLApX005dyPyoi:-MiZu3_IA_b5nSuUlKPi:b-p8xf1b) ([raw file](https://github.com/pmem/rpma/blob/4b5390542968d2b97a64662292f4328c223b7695/src/include/librpma.h#L2634)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

I removed the wrong `(in network byte order)` because rpma_cq_get_completion() has converted it to host byte order by `ntohl()`
</blockquote></details>

Perhaps, I should add the `(in host byte order)` comment.


<!-- Sent from Reviewable.io -->

2021-09-02 07:47 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 2634 at r3](https://reviewable.io/reviews/pmem/rpma/1214#-MiZo8QLApX005dyPyoi:-Mi_TX-E7es3DI5w6Z7r:b32v57) ([raw file](https://github.com/pmem/rpma/blob/4b5390542968d2b97a64662292f4328c223b7695/src/include/librpma.h#L2634)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Perhaps, I should add the `(in host byte order)` comment.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-09-02 08:11 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 2634 at r3](https://reviewable.io/reviews/pmem/rpma/1214#-MiZo8QLApX005dyPyoi:-Mi_YudO4rJ0FwgUwHWd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4b5390542968d2b97a64662292f4328c223b7695/src/include/librpma.h#L2634)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-02 13:41 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-02 23:07 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 2636 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-MickgjQEfMUlh_sHcom:-MickgjQEfMUlh_sHcon:bx1rb41) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2636)):*
> ```objc
> 	/* immediate data (in host byte order) */
> 	uint32_t imm;
> };
> ```

Nice. But this part does not show up in the documentation. I think we can keep this structure simple whereas document all of these fields down below so the description will show up on the man pages.


<!-- Sent from Reviewable.io -->

2021-09-03 02:34 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 2636 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-MickgjQEfMUlh_sHcom:-MidU4IGCVH-Y0lrC73B:b96ajyq) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2636)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nice. But this part does not show up in the documentation. I think we can keep this structure simple whereas document all of these fields down below so the description will show up on the man pages.
</blockquote></details>

Hi @janekmi 

Do you know how to add comments in SYNOPSIS? The following method is wrong:
```
 * SYNOPSIS
 *
 *	#include <librpma.h>
 *
 *	struct rpma_cq;
 *	struct rpma_completion {
 *		void *op_context;
 *		/* operation type of the completion */
 *		enum rpma_op op;
 *		uint32_t byte_len;
 *		enum ibv_wc_status op_status;
 *		unsigned flags;
 *		uint32_t imm;
 *	};
 *	enum rpma_op {
 *		RPMA_OP_READ,
 *		RPMA_OP_WRITE,
 *		RPMA_OP_FLUSH,
 *		RPMA_OP_SEND,
 *		RPMA_OP_RECV,
 *		RPMA_OP_RECV_RDMA_WITH_IMM,
 *	};

```

Perhaps， we can only add comments by `//`, like this:
```
 * SYNOPSIS
 *
 *	#include <librpma.h>
 *
 *	struct rpma_cq;
 *	struct rpma_completion {
 *		void *op_context;
 *		// operation type of the completion
 *		enum rpma_op op;
 *		uint32_t byte_len;
 *		enum ibv_wc_status op_status;
 *		unsigned flags;
 *		uint32_t imm;
 *	};
 *	enum rpma_op {
 *		RPMA_OP_READ,
 *		RPMA_OP_WRITE,
 *		RPMA_OP_FLUSH,
 *		RPMA_OP_SEND,
 *		RPMA_OP_RECV,
 *		RPMA_OP_RECV_RDMA_WITH_IMM,
 *	};

```


<!-- Sent from Reviewable.io -->

2021-09-08 09:50 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 2636 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-MickgjQEfMUlh_sHcom:-Mj3nqwA94PcUKzHEnMJ:bn8tmsf) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2636)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

Do you know how to add comments in SYNOPSIS? The following method is wrong:
```
 * SYNOPSIS
 *
 *	#include <librpma.h>
 *
 *	struct rpma_cq;
 *	struct rpma_completion {
 *		void *op_context;
 *		/* operation type of the completion */
 *		enum rpma_op op;
 *		uint32_t byte_len;
 *		enum ibv_wc_status op_status;
 *		unsigned flags;
 *		uint32_t imm;
 *	};
 *	enum rpma_op {
 *		RPMA_OP_READ,
 *		RPMA_OP_WRITE,
 *		RPMA_OP_FLUSH,
 *		RPMA_OP_SEND,
 *		RPMA_OP_RECV,
 *		RPMA_OP_RECV_RDMA_WITH_IMM,
 *	};

```

Perhaps， we can only add comments by `//`, like this:
```
 * SYNOPSIS
 *
 *	#include <librpma.h>
 *
 *	struct rpma_cq;
 *	struct rpma_completion {
 *		void *op_context;
 *		// operation type of the completion
 *		enum rpma_op op;
 *		uint32_t byte_len;
 *		enum ibv_wc_status op_status;
 *		unsigned flags;
 *		uint32_t imm;
 *	};
 *	enum rpma_op {
 *		RPMA_OP_READ,
 *		RPMA_OP_WRITE,
 *		RPMA_OP_FLUSH,
 *		RPMA_OP_SEND,
 *		RPMA_OP_RECV,
 *		RPMA_OP_RECV_RDMA_WITH_IMM,
 *	};

```

</blockquote></details>

I think you can add `struct rpma_completion` and `enum rpma_op` to the SYNOPSIS without any comments and describe all of their fields in the DESCRIPTION.


<!-- Sent from Reviewable.io -->

2021-09-08 09:55 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2624 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-Mj3p9jl-NkLXj2LSFNX:-Mj3p9jm5HPUumknfyVn:b6elbu7) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2624)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	/*
> 	 * user context of the completion, which comes from
> 	 * the op_context argument in rpma_send(), rpma_write(), etc
> 	 */
> ```
</details>


```
	/*
	 * User context of the completion, which comes from
	 * the op_context argument in rpma_send(), rpma_write() etc.
	 */
```


<!-- Sent from Reviewable.io -->

2021-09-09 01:47 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 2624 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-Mj3p9jl-NkLXj2LSFNX:-Mj7CqnnBUdQNdO-8HMY:b86pwrp) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2624)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/*
> 	 * user context of the completion, which comes from
> 	 * the op_context argument in rpma_send(), rpma_write(), etc
> 	 */
> ```

```
	/*
	 * User context of the completion, which comes from
	 * the op_context argument in rpma_send(), rpma_write() etc.
	 */
```
</blockquote></details>

Done.  I removed the comments here.
BTW，I think I use the tab as indentation indeed.
___
*[src/include/librpma.h, line 2636 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-MickgjQEfMUlh_sHcom:-Mj7ClHs-eQ3V6ooeHtt:b9z35em) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2636)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think you can add `struct rpma_completion` and `enum rpma_op` to the SYNOPSIS without any comments and describe all of their fields in the DESCRIPTION.
</blockquote></details>

Done.  Good idea, I have updated the PR.


<!-- Sent from Reviewable.io -->

2021-09-09 07:19 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2624 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-Mj3p9jl-NkLXj2LSFNX:-Mj8CkCc8wdt_nZ_1h_I:b-l3w03y) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2624)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.  I removed the comments here.
BTW，I think I use the tab as indentation indeed.
</blockquote></details>

I didn't mean the tabs. I meant that multi line comments should be full sentences starting with a capital letter and ending with the full stop.
___
*[src/include/librpma.h, line 2620 at r5](https://reviewable.io/reviews/pmem/rpma/1214#-Mj8O_jD0JAuzZKjdZJf:-Mj8O_jD0JAuzZKjdZJg:bhu31o3) ([raw file](https://github.com/pmem/rpma/blob/0adf2aaf5046b7417f9f4a5ee2d4604ce4db073a/src/include/librpma.h#L2620)):*
> ```objc
> };
> 
> struct rpma_completion {
> ```

Please add before `struct rpma_completion {`:
```
/*
 * For the description of all fields of 'struct rpma_completion'
 * see the DESCRIPTION section of the rpma_cq_get_completion()'s manual.
 */
```
___
*[src/include/librpma.h, line 2802 at r5](https://reviewable.io/reviews/pmem/rpma/1214#-Mj8Pvmm80a6HRaLvwGK:-Mj8Pvmm80a6HRaLvwGL:bshhjuk) ([raw file](https://github.com/pmem/rpma/blob/0adf2aaf5046b7417f9f4a5ee2d4604ce4db073a/src/include/librpma.h#L2802)):*
> ```
>  * The argument cmpl is a pointer to struct rpma_completion, see the following
>  * description on all fields of struct rpma_completion:
> ```

Please replace it with just:
```
 * The fields of 'struct rpma_completion' have the following meaning:
```


<!-- Sent from Reviewable.io -->

2021-09-09 07:31 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 2624 at r4](https://reviewable.io/reviews/pmem/rpma/1214#-Mj3p9jl-NkLXj2LSFNX:-Mj8SkUh-P1PFY9z2ei6:b-9h68zq) ([raw file](https://github.com/pmem/rpma/blob/5ac73eb75ae428b08716cf9bd65909a9d0ee1c9e/src/include/librpma.h#L2624)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I didn't mean the tabs. I meant that multi line comments should be full sentences starting with a capital letter and ending with the full stop.
</blockquote></details>

Sorry, I missed the difference("user -> User").
___
*[src/include/librpma.h, line 2620 at r5](https://reviewable.io/reviews/pmem/rpma/1214#-Mj8O_jD0JAuzZKjdZJf:-Mj8StnUC5r_MhPZ1hCF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0adf2aaf5046b7417f9f4a5ee2d4604ce4db073a/src/include/librpma.h#L2620)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add before `struct rpma_completion {`:
```
/*
 * For the description of all fields of 'struct rpma_completion'
 * see the DESCRIPTION section of the rpma_cq_get_completion()'s manual.
 */
```

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2802 at r5](https://reviewable.io/reviews/pmem/rpma/1214#-Mj8Pvmm80a6HRaLvwGK:-Mj8SuXLBtvORiDlXN7b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0adf2aaf5046b7417f9f4a5ee2d4604ce4db073a/src/include/librpma.h#L2802)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * The argument cmpl is a pointer to struct rpma_completion, see the following
>  * description on all fields of struct rpma_completion:
> ```

Please replace it with just:
```
 * The fields of 'struct rpma_completion' have the following meaning:
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-09 07:34 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-10 06:37 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-10 07:05 UTC, ldorau approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-10 07:05 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214#-:-MjDWhpMC0zZ8qj5dQZj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-16 12:58 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 9 unresolved discussions (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 2623 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjiazaU9t2y3UMUe4RP:-MjiazaU9t2y3UMUe4RQ:b2soubc) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2623)):*
> ```objc
>  * For the description of all fields of 'struct rpma_completion'
>  * see the DESCRIPTION section of the rpma_cq_get_completion()'s manual.
>  */
> ```

`/* For details please see rpma_cq_get_completion(3). */`
___
*[src/include/librpma.h, line 2787 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjibFHUCqvAahwFRBUu:-MjibFHUCqvAahwFRBUv:bf8bzrv) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2787)):*
> ```objc
>  *		RPMA_OP_RECV,
>  *		RPMA_OP_RECV_RDMA_WITH_IMM,
>  *	};
> ```

Since `struct rpma_completion` refers `enum rpma_op` I think you should reorder them.
___
*[src/include/librpma.h, line 2803 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjichdxB7EP-kBMzUlV:-MjichdxB7EP-kBMzUlW:bjaycik) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2803)):*
> ```objc
>  * - RPMA_OP_RECV - messaging receive operation
>  * - RPMA_OP_RECV_RDMA_WITH_IMM - messaging receive operation for
>  *   RMA write operation with immediate data
> ```

I think all of these should go after the `struct rpma_completion` since it describes possible values of one of its fields.
Starting from `The following operations are available:` which I will rephrase as: `The available op values are:`
___
*[src/include/librpma.h, line 2805 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjidVdaAbbTxFf8pRAd:-MjidVdb5pJH9twEZf_a:b-w4yk4z) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2805)):*
> ```objc
>  *   RMA write operation with immediate data
>  *
>  * The fields of 'struct rpma_completion' have the following meaning:
> ```

The rpma_completion structure provides the following fields:
___
*[src/include/librpma.h, line 2807 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjie5Ia4qfDQyOBx0tg:-Mjie5Ia4qfDQyOBx0th:b-s5i3l6) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2807)):*
> ```objc
>  * The fields of 'struct rpma_completion' have the following meaning:
>  * - op_context - user context of the completion, which comes from
>  *   the op_context argument in rpma_send(), rpma_write(), etc
> ```

context of the operation provided by the user to either rpma_flush(3), rpma_read(3), rpma_recv(3)...

**Note**: Please enumerate all of them from the SEE ALSO section. I think we can afford it.
___
*[src/include/librpma.h, line 2808 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjieyG53NT6s4ccqfJQ:-MjieyG53NT6s4ccqfJR:btoe1d1) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2808)):*
> ```objc
>  * - op_context - user context of the completion, which comes from
>  *   the op_context argument in rpma_send(), rpma_write(), etc
>  * - op - operation type of the completion
> ```

type of the operation. For available values please see the description below.
___
*[src/include/librpma.h, line 2810 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjif6L15us2jLiawUe4:-Mjif6L15us2jLiawUe5:bmz0jbr) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2810)):*
> ```objc
>  * - op - operation type of the completion
>  * - byte_len - number of bytes transferred
>  * - op_status - status of the completion
> ```

completion -> operation
___
*[src/include/librpma.h, line 2811 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjifgtx36AIOOhk4srq:-Mjifgtx36AIOOhk4srr:b11qsay) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2811)):*
> ```objc
>  * - byte_len - number of bytes transferred
>  * - op_status - status of the completion
>  * - flags - flags of the completion
> ```

flags of the operation. For available values please see ibv_poll_cq(3).
___
*[src/include/librpma.h, line 2812 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjifpqp8K6wRW0EcCA5:-Mjifpqp8K6wRW0EcCA6:b-4j7rlc) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2812)):*
> ```objc
>  * - op_status - status of the completion
>  * - flags - flags of the completion
>  * - imm - immediate data (in host byte order)
> ```

in network byte order?

Ref: https://man7.org/linux/man-pages/man3/ibv_poll_cq.3.html


<!-- Sent from Reviewable.io -->

2021-09-17 03:42 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 2623 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjiazaU9t2y3UMUe4RP:-Mjlnv3l9NKu7oijC1yt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2623)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* For details please see rpma_cq_get_completion(3). */`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2787 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjibFHUCqvAahwFRBUu:-MjloRPT9r0BS-kHc37e:bq0qkj6) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2787)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since `struct rpma_completion` refers `enum rpma_op` I think you should reorder them.
</blockquote></details>

I didn't reorder them becasue I want to make it be consistent with the content of `DESCRIPTION`.
___
*[src/include/librpma.h, line 2803 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjichdxB7EP-kBMzUlV:-MjlpCNl0wjqen8XFM84:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2803)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think all of these should go after the `struct rpma_completion` since it describes possible values of one of its fields.
Starting from `The following operations are available:` which I will rephrase as: `The available op values are:`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2805 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjidVdaAbbTxFf8pRAd:-MjlpLMU-PbzezEw8Ho5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2805)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The rpma_completion structure provides the following fields:
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2807 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjie5Ia4qfDQyOBx0tg:-MjlpNxqAa08cea5zaWJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2807)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

context of the operation provided by the user to either rpma_flush(3), rpma_read(3), rpma_recv(3)...

**Note**: Please enumerate all of them from the SEE ALSO section. I think we can afford it.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2808 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjieyG53NT6s4ccqfJQ:-MjlpRGyDixBcVqnKLdM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2808)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

type of the operation. For available values please see the description below.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2810 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjif6L15us2jLiawUe4:-MjlpUNU2Q4tIgOjj2_X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2810)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

completion -> operation
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2811 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjifgtx36AIOOhk4srq:-MjlpWDi5dIC1KUijKiT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2811)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

flags of the operation. For available values please see ibv_poll_cq(3).
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2812 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-Mjifpqp8K6wRW0EcCA5:-MjlbzBV7HDkgBjFJD5X:bqlxm8g) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2812)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

in network byte order?

Ref: https://man7.org/linux/man-pages/man3/ibv_poll_cq.3.html
</blockquote></details>

No, `host byte order` is correct because rpma will convert `network byte order` to `host byte order`:
```
cmpl->imm = ntohl(wc.imm_data);
```


<!-- Sent from Reviewable.io -->

2021-09-17 06:08 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-17 10:27 UTC, janekmi approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 2787 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjibFHUCqvAahwFRBUu:-MjnHIRO2Ng8YtOxzAOy:b-2fywx8) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2787)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I didn't reorder them becasue I want to make it be consistent with the content of `DESCRIPTION`.
</blockquote></details>

It is an argument. My argument is: it is a C code snippet. The way it is written now makes it incorrect.

I leave it to your consideration.


<!-- Sent from Reviewable.io -->

2021-09-17 10:27 UTC, janekmi approved these changes
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214#-:-MjnHup39cXPok5v3S7h:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-17 11:25 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2787 at r7](https://reviewable.io/reviews/pmem/rpma/1214#-MjibFHUCqvAahwFRBUu:-MjnV6zR8WVz0JZU52nY:b-j3by4v) ([raw file](https://github.com/pmem/rpma/blob/31557b8cefd144b5904c2d1dad02981a5b3553c4/src/include/librpma.h#L2787)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is an argument. My argument is: it is a C code snippet. The way it is written now makes it incorrect.

I leave it to your consideration.
</blockquote></details>

IMHO it should be reordered, because it is a code snippet.


<!-- Sent from Reviewable.io -->

2021-09-17 13:56 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-20 07:26 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-23 09:32 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-23 10:29 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-27 07:46 UTC, ldorau reviewed
@janekmi Is anything missing here?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214#-:-MkaCz1B81raH6prP6CX:bbqt3rz)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-29 01:15 UTC, yangx-jy commented
@janekmi ping.

I hope some of my PRs (e.g. #1214, #1087) can be merged recently so that I can continue implementing SRQ.

Thanks a lot.





<!-- Sent from Reviewable.io -->

2021-09-29 06:34 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-30 08:57 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1214#-:-Mkpv3QwDX0kpZdH-aVf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-30 08:58 UTC, merged