rpma: add rpma_mr_advise()
pmem/rpma pull request #1220
Opened 2021-08-26 08:21 UTC by ewanglong

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1220)

2021-08-30 10:05 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/mr.c, line 564 at r1](https://reviewable.io/reviews/pmem/rpma/1220#-Mi121GA6wRISPo_-B6M:-MiLWBL03V8B_5Bl7uPd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91f11d74c6dfc91b796f5cd0934f4134f39d44c6/src/mr.c#L564)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

> memory region
I saw "memory region" in those APIs of rpma_mr_remote_get_size, rpma_mr_remote_delete and rpma_mr_remote_get_flush_type and also in kernel introducing ibv_advise_mr pages. How can keey them all consistent?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1150 at r1](https://reviewable.io/reviews/pmem/rpma/1220#-Mi14bKX9YroQ7guMsIM:-MiLWC1VAWOSqunmvjV9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91f11d74c6dfc91b796f5cd0934f4134f39d44c6/src/include/librpma.h#L1150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1174 at r1](https://reviewable.io/reviews/pmem/rpma/1220#-Mi1EKX88yLg7eFaZ_HO:-MiLWCPZ32M7ahgXI8H1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91f11d74c6dfc91b796f5cd0934f4134f39d44c6/src/include/librpma.h#L1174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Assuming, we can just pass `advice` and `flags` directly to `ibv_advise_mr(3)` I prefer to refer the end-user directly to the `ibv_advise_mr(3)` manual for details. Instead, here I think we should describe what is the impact of this API call to FileSystemDAX performance. But this part of the documentation may appear after collecting some performance numbers.

Credit: @grom72 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1189 at r1](https://reviewable.io/reviews/pmem/rpma/1220#-Mi14DAM-bmbsjhLbtul:-MiLWCzZ3JO73Y6-4MRd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91f11d74c6dfc91b796f5cd0934f4134f39d44c6/src/include/librpma.h#L1189)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

If so, why need this encapulate-only API? For the code of advice determining,  may we hide a few ibv logic and make things easy to call for user?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-01 06:33 UTC, janekmi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1220#-MiV2Yy4A9a7K2bmqEGh:-MiV2Yy4A9a7K2bmqEGi:b8loxc3) (no related file):*
I think we are on the same page now. So you can focus on polishing things up: unit tests etc.
I will think a little bit more about the documentation in the meantime.

---
___
*[src/mr.c, line 520 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiTP0_Q1xTCQZNywhGm:-MiTP0_Q1xTCQZNywhGn:b-6qwh51) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L520)):*
> ```C
>  */
> static int
> rpma_mr_usage_to_access(struct rpma_mr_local *mr)
> ```

Please remove. I belive it is not needed any more.


<!-- Sent from Reviewable.io -->

2021-09-01 08:09 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-MiV4iZgCbKsrQZmeBLv:b-vize66) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
> ```C
> 	sg_list.lkey = mr->ibv_mr->lkey;
> 	sg_list.addr = (uint64_t)((char *)mr->ibv_mr->addr + offset);
> 	sg_list.length = len;
> ```

So far it seems we have used an explicit cast `(uint32_t)`.
___
*[src/mr.c, line 578 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiVOSi08DD4_W6LPOZK:-MiVBeL1-vQePzVgODUD:bktgyum) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L578)):*
> ```C
> 		RPMA_LOG_ERROR_WITH_ERRNO(errno,
> 			"ibv_advise_mr failed: "
> 			"ibv_reg_mr(addr=%p, length=%zu, advice=%i, flags=%d)",
> ```

We do not log failed call arguments. Please see other uses of the `RPMA_LOG_ERROR_WITH_ERRNO()` macro.


<!-- Sent from Reviewable.io -->

2021-09-03 08:05 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-09-03 08:35 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/mr.c, line 520 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiTP0_Q1xTCQZNywhGm:-Miems7YAVuuxNe28CZZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L520)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove. I belive it is not needed any more.
</blockquote></details>

Done.
___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-Miemwso3dQj1l7rtfab:b-5i433k) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So far it seems we have used an explicit cast `(uint32_t)`.
</blockquote></details>

Using uintptr_t now.
___
*[src/mr.c, line 578 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiVOSi08DD4_W6LPOZK:-Miemzm48HeQE6DjolQt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L578)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We do not log failed call arguments. Please see other uses of the `RPMA_LOG_ERROR_WITH_ERRNO()` macro.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-06 04:56 UTC, grom72 reviewed
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/include/librpma.h, line 1180 at r3](https://reviewable.io/reviews/pmem/rpma/1220#-MitRuPO3Nm8HMh68Kw6:-MitRuPO3Nm8HMh68Kw7:bxc6n4h) ([raw file](https://github.com/pmem/rpma/blob/255ce0aea3a87bf4e1fa7d255c9b6c52c870f090/src/include/librpma.h#L1180)):*
> ```
> memory registration failed
> ```
ibv_advise_mr() failed, the exact cause of the error can be read from the log


<!-- Sent from Reviewable.io -->

2021-09-06 05:40 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 1180 at r3](https://reviewable.io/reviews/pmem/rpma/1220#-MitRuPO3Nm8HMh68Kw6:-MitbnjM73yIEL-eRBkU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/255ce0aea3a87bf4e1fa7d255c9b6c52c870f090/src/include/librpma.h#L1180)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> memory registration failed
> ```
ibv_advise_mr() failed, the exact cause of the error can be read from the log
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-06 12:33 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-06 18:58 UTC, janekmi requested changes
> Reviewed 4 of 6 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 16 unresolved discussions (waiting on @ewanglong and @grom72)

___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-MivJASl4t2j7siiXeme:bxzo62o) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Using uintptr_t now.
</blockquote></details>

I think the change in the line above is good. :+1: 

But I was thinking about this one:

```c
sg_list.length = len;
```

I think you should be consistent with all other places where we accept a length of a memory region.
___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-MivJ8FsCxk_D5UZn9gn:bb76mu4) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
> ```C
> int
> rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len,
> 		uint32_t advice, uint32_t flags)
> ```

Why?
___
*[src/include/librpma.h, line 1180 at r3](https://reviewable.io/reviews/pmem/rpma/1220#-MitRuPO3Nm8HMh68Kw6:-MivNkFw2w4tDocbIHks:b-fl4d95) ([raw file](https://github.com/pmem/rpma/blob/255ce0aea3a87bf4e1fa7d255c9b6c52c870f090/src/include/librpma.h#L1180)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```
ibv_advise_mr() failed
```
___
*[src/include/librpma.h, line 1171 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivK79IAdgAIeu3kOpH:-MivK79IAdgAIeu3kOpI:b-9jlaim) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/include/librpma.h#L1171)):*
> ```objc
>  * the flags
>  * - IBV_ADVISE_MR_FLAG_FLUSH - the underlying pages are guaranteed to be
>  *   updated in the HCA before returning SUCCESS
> ```

I do not like making a copy of the ibv_advise_mr(3) manual. I think we should just refer the user to the place where it is documented. Please add to the previous paragraph e.g.:

```
For available advice and flags values please see ibv_advise_mr(3).
```
___
*[tests/unit/common/mocks-ibverbs.h, line 70 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivQKfK433D-dXdQYBB:-MivQKfK433D-dXdQYBC:bu7rlwe) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.h#L70)):*
> ```objc
> 	uint32_t num_sge;
> 	int ret;
> };
> ```

I think this structure, despite being convenient, goes against the cmocka mechanics. Please see other comments for my proposal.
___
*[tests/unit/common/mocks-ibverbs.c, line 352 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivOYA1E1KeWnf4n-ec:-MivOYA1E1KeWnf4n-ed:bj8d4r8) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L352)):*
> ```C
> 
> /*
>  * ibv_post_send_mock -- mock of ibv_advise_mr()
> ```

ibv_advise_mr_mock
___
*[tests/unit/common/mocks-ibverbs.c, line 364 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivUBOu6pPW2zrHO_rb:-MivUBOu6pPW2zrHO_rc:b-3uc350) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L364)):*
> ```C
> 		mock_type(struct ibv_advise_mr_mock_args *);
> 
> 	assert_non_null(pd);
> ```

It seems unnecessary. Its value is checked a few lines below.
___
*[tests/unit/common/mocks-ibverbs.c, line 367 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwQePC7hJY61hiw5ab:-MiwQePC7hJY61hiw5ac:b-n95fxx) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L367)):*
> ```C
> 	assert_non_null(sg_list);
> 
> 	assert_int_equal(pd, args->pd);
> ```

`check_expected_ptr(pd);`
___
*[tests/unit/common/mocks-ibverbs.c, line 374 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwQiBrDLnRC416lEbt:-MiwQiBrDLnRC416lEbu:b-d1y4de) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L374)):*
> ```C
> 	assert_int_equal(sg_list->addr, args->local_addr);
> 	assert_int_equal(sg_list->length, args->length);
> 	assert_int_equal(num_sge, args->num_sge);
> ```

I believe you can apply `check_expected_ptr()` to all of the checks above.
___
*[tests/unit/common/mocks-ibverbs.c, line 376 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwQopC33UhBHtJELkP:-MiwQopC33UhBHtJELkQ:b-saop3k) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L376)):*
> ```C
> 	assert_int_equal(num_sge, args->num_sge);
> 
> 	return args->ret;
> ```

```c
return mock_type(int);
```
___
*[tests/unit/mr/mr-advise.c, line 12 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwRON3Agboxe1FdqSB:-MiwRON3Agboxe1FdqSC:b24q6hj) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L12)):*
> ```C
> 
> #include "cmocka_headers.h"
> #include "mr.h"
> ```

Is this header really needed?
___
*[tests/unit/mr/mr-advise.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwT8mW78qM1-HpAfCe:-MiwT8mW78qM1-HpAfCf:bwii9ww) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L30)):*
> ```C
> 	/* configure mocks */
> 	struct ibv_advise_mr_mock_args args;
> 	args.pd = MOCK_IBV_PD;
> ```

```c
expect_value(pd, MOCK_IBV_PD);
```
___
*[tests/unit/mr/mr-advise.c, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwTFQgAOxNJc3siz9w:-MiwTFQgAOxNJc3siz9x:bvjs2mm) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L37)):*
> ```C
> 	args.lkey = MOCK_LKEY;
> 	args.num_sge = 1;
> 	args.ret = RPMA_E_PROVIDER;
> ```

I think you can apply `expect_value()` to all of them.
___
*[tests/unit/mr/mr-advise.c, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwSxGj4BJoZSKo1vum:-MiwSxGj4BJoZSKo1vun:b-vzkrwh) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L38)):*
> ```C
> 	args.num_sge = 1;
> 	args.ret = RPMA_E_PROVIDER;
> 	will_return(ibv_advise_mr_mock, &args);
> ```

`will_return(ibv_advise_mr_mock, RPMA_E_PROVIDER);`
___
*[tests/unit/mr/mr-advise.c, line 45 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwTMWm0bIf6F0m0l5-:-MiwTMWm0bIf6F0m0l50:b-x95rwd) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L45)):*
> ```C
> 				IB_UVERBS_ADVISE_MR_FLAG_FLUSH);
> ```

A redundant new line.
___
*[tests/unit/mr/mr-advise.c, line 68 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwTSA3-XQOejttqahh:-MiwTSA3-XQOejttqahi:brhumzt) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L68)):*
> ```C
> 	args.num_sge = 1;
> 	args.ret = MOCK_OK;
> 	will_return(ibv_advise_mr_mock, &args);
> ```

Same here.
___
*[tests/unit/mr/mr-advise.c, line 97 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwSMXe3NzsQoJvM1xh:-MiwSMXe3NzsQoJvM1xi:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L97)):*
> ```C
> 	 * }
> 	 * so we can set the advise_mr function pointer to our mock function.
> 	 */
> ```

:+1: 


<!-- Sent from Reviewable.io -->

2021-09-07 06:43 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 6 of 8 files reviewed, 16 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-MiypbWtDJx3tQPwDQO7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the change in the line above is good. :+1: 

But I was thinking about this one:

```c
sg_list.length = len;
```

I think you should be consistent with all other places where we accept a length of a memory region.
</blockquote></details>

Done.
___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-MiyoYxYEUbQNPrHgqXA:b-94qfl2) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Chanaged it back. But it show warning as error as below.
/rpma/src/include/librpma.h:1186:8: error: 'enum ibv_advise_mr_advice' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
___
*[src/include/librpma.h, line 1171 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivK79IAdgAIeu3kOpH:-MiyqMHp24D-TPLAwXqC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/include/librpma.h#L1171)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like making a copy of the ibv_advise_mr(3) manual. I think we should just refer the user to the place where it is documented. Please add to the previous paragraph e.g.:

```
For available advice and flags values please see ibv_advise_mr(3).
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.h, line 70 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivQKfK433D-dXdQYBB:-MiywQT52Hame_rO46KX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.h#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this structure, despite being convenient, goes against the cmocka mechanics. Please see other comments for my proposal.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 352 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivOYA1E1KeWnf4n-ec:-Miyqjfi8rJc9uXFnzK6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L352)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ibv_advise_mr_mock
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 364 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivUBOu6pPW2zrHO_rb:-Miywh0dEOea1UsdQEzX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L364)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems unnecessary. Its value is checked a few lines below.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 367 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwQePC7hJY61hiw5ab:-MiywiWA1mX3mKa0ONRz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L367)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`check_expected_ptr(pd);`
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 374 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwQiBrDLnRC416lEbt:-Miywjxd9XxagY2j0R92:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L374)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe you can apply `check_expected_ptr()` to all of the checks above.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 376 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwQopC33UhBHtJELkP:-MiyxMi-4ePG8FO_C_nE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/common/mocks-ibverbs.c#L376)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
return mock_type(int);
```
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 12 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwRON3Agboxe1FdqSB:-Miyxg8sAsKYPEc0863J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is this header really needed?
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwT8mW78qM1-HpAfCe:-MiyxhPO4P_b9HwPi0Em:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
expect_value(pd, MOCK_IBV_PD);
```
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwTFQgAOxNJc3siz9w:-MiyxiIzEcuzGtoG9d8q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you can apply `expect_value()` to all of them.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwSxGj4BJoZSKo1vum:-Miyxjj36EwsOMRqXNpc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`will_return(ibv_advise_mr_mock, RPMA_E_PROVIDER);`
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 45 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwTMWm0bIf6F0m0l5-:-Miyxthe04S0jiDovb2P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A redundant new line.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 68 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MiwTSA3-XQOejttqahh:-MiyxwzsBAf9n1tKyJm1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/tests/unit/mr/mr-advise.c#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-07 10:23 UTC, janekmi requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong, @grom72, and @janekmi)

___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-MizSFgPC75fublKL1V-:b-jncj55) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I thought about something like this:

```c
sge.length = (uint32_t)len;
```
___
*[tests/unit/common/mocks-ibverbs.c, line 371 at r6](https://reviewable.io/reviews/pmem/rpma/1220#-MizQwP7C0YLrR7ylQrQ:-MizQwP7C0YLrR7ylQrR:b-2umdl5) ([raw file](https://github.com/pmem/rpma/blob/ac0751ec4fe7e26c4707d76eb919deb8261a6a88/tests/unit/common/mocks-ibverbs.c#L371)):*
> ```C
> 	check_expected(num_sge);
> 
> 	return mock_type(int); /* errno */
> ```

It is not an `errno`. I think we can drop this comment at all.


<!-- Sent from Reviewable.io -->

2021-09-07 10:36 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong, @grom72, @ldorau, and @osalyk)

___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-MizmnEbBUlD5jI1tOCs:b-3otv3e) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Chanaged it back. But it show warning as error as below.
/rpma/src/include/librpma.h:1186:8: error: 'enum ibv_advise_mr_advice' declared inside parameter list will not be visible outside of this definition or declaration [-Werror]
</blockquote></details>

It seems `enum ibv_advise_mr_advice` is not available on all our docker images because it was introduced along the way. So, I think it was a very good idea to replace it with an appropriate integer replacement. :clap: 

After my short research, I am pretty sure that `enum` can be as large as `uint32_t` but not bigger.

@grom72 @ldorau @osalyk Any thoughts on this?


<!-- Sent from Reviewable.io -->

2021-09-08 01:59 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-Mj266rf4HpbadDd4G8B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I thought about something like this:

```c
sge.length = (uint32_t)len;
```
</blockquote></details>

Done.
___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj256pI4o1KA9T8ZDH1:bnr3oxo) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems `enum ibv_advise_mr_advice` is not available on all our docker images because it was introduced along the way. So, I think it was a very good idea to replace it with an appropriate integer replacement. :clap: 

After my short research, I am pretty sure that `enum` can be as large as `uint32_t` but not bigger.

@grom72 @ldorau @osalyk Any thoughts on this?
</blockquote></details>

Seems it's better to replace it with "int". There is enum definition from the current C Standard (C99)(http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf)
6.7.2.2 Enumeration specifiers
The  expression  that  defines  the  value  of  an  enumeration  constant  shall  be  an  integer
constant expression that has a value representable as an int.
___
*[tests/unit/common/mocks-ibverbs.c, line 371 at r6](https://reviewable.io/reviews/pmem/rpma/1220#-MizQwP7C0YLrR7ylQrQ:-Mj2746r1Lr0mYdIZ99r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ac0751ec4fe7e26c4707d76eb919deb8261a6a88/tests/unit/common/mocks-ibverbs.c#L371)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not an `errno`. I think we can drop this comment at all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 06:55 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 5 of 8 files reviewed, 6 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, and @osalyk)

___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj3AvMe4QmXo6JdiIu0:b-nyliib) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Seems it's better to replace it with "int". There is enum definition from the current C Standard (C99)(http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf)
6.7.2.2 Enumeration specifiers
The  expression  that  defines  the  value  of  an  enumeration  constant  shall  be  an  integer
constant expression that has a value representable as an int.
</blockquote></details>

Yes, according to C99 Standard it should be `int`.
___
*[src/mr.c, line 526 at r7](https://reviewable.io/reviews/pmem/rpma/1220#-Mj37A_R567CaF7qfYLZ:-Mj37A_R567CaF7qfYL_:b-opmwqn) ([raw file](https://github.com/pmem/rpma/blob/1a1b8fa8372689e99538e63ac197cf62cfdd7044/src/mr.c#L526)):*
> ```C
> 	sg_list.length = (uint32_t)length;
> 
> 	int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
> ```

```
/rpma/src/mr.c:526:42: error: implicit conversion changes signedness: 'int' to 'enum ib_uverbs_advise_mr_advice' [-Werror,-Wsign-conversion]
        int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
```
https://github.com/ldorau/rpma/runs/3541507648
___
*[src/mr.c, line 526 at r7](https://reviewable.io/reviews/pmem/rpma/1220#-Mj37wJL4WbYWKcY7fa2:-Mj37wJL4WbYWKcY7fa3:b6pxidn) ([raw file](https://github.com/pmem/rpma/blob/1a1b8fa8372689e99538e63ac197cf62cfdd7044/src/mr.c#L526)):*
> ```C
> 	sg_list.length = (uint32_t)length;
> 
> 	int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
> ```

```
/rpma/src/mr.c:526:12: error: implicit declaration of function 'ibv_advise_mr' [-Werror=implicit-function-declaration]
  int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
```
https://github.com/ldorau/rpma/runs/3541507648


<!-- Sent from Reviewable.io -->

2021-09-08 06:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3BCvZ2L2rNDvY6pjR:-Mj3BCvZ2L2rNDvY6pjS:b7187it) (no related file):*
Please rebase on the current master - there are new versions of OSes now.

---


<!-- Sent from Reviewable.io -->

2021-09-08 07:29 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r4, 1 of 5 files at r6, 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 526 at r7](https://reviewable.io/reviews/pmem/rpma/1220#-Mj37wJL4WbYWKcY7fa2:-Mj3IgYXDLozIQBkTTsm:b-d5rfrp) ([raw file](https://github.com/pmem/rpma/blob/1a1b8fa8372689e99538e63ac197cf62cfdd7044/src/mr.c#L526)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
/rpma/src/mr.c:526:12: error: implicit declaration of function 'ibv_advise_mr' [-Werror=implicit-function-declaration]
  int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
```
https://github.com/ldorau/rpma/runs/3541507648

</blockquote></details>

shall we have here conditional compilation and return an error if OS does not support this feature?


<!-- Sent from Reviewable.io -->

2021-09-08 07:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, and @osalyk)

___
*[src/mr.c, line 526 at r7](https://reviewable.io/reviews/pmem/rpma/1220#-Mj37wJL4WbYWKcY7fa2:-Mj3OoiCBNXQd3Ir0CiH:b-5fba3l) ([raw file](https://github.com/pmem/rpma/blob/1a1b8fa8372689e99538e63ac197cf62cfdd7044/src/mr.c#L526)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we have here conditional compilation and return an error if OS does not support this feature?
</blockquote></details>

It is enough to add:
```
#include <infiniband/verbs.h>
```
at the beginning.


<!-- Sent from Reviewable.io -->

2021-09-08 07:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-08 08:14 UTC, ldorau requested changes
> Reviewed 1 of 6 files at r3, 1 of 5 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, and @osalyk)

___
*[src/include/librpma.h, line 1161 at r8](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3SUpL68HWlHKjNKlL:-Mj3SUpMDIfBCkC5G-gr:btepm2y) ([raw file](https://github.com/pmem/rpma/blob/461330c5df2cd39d2212148e8373fe2a6634e876/src/include/librpma.h#L1161)):*
> ```
> give
> ```

gives


<!-- Sent from Reviewable.io -->

2021-09-08 09:01 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 3 of 10 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj3cHN78gupUk30qTxf:bs0tjya) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
> enum ibv_advise_mr_advice
Changed back to enum ibv_advise_mr_advice since condition compilation is executed.
___
*[src/mr.c, line 526 at r7](https://reviewable.io/reviews/pmem/rpma/1220#-Mj37A_R567CaF7qfYLZ:-Mj3cZit6SE1XCNKHJ0M:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a1b8fa8372689e99538e63ac197cf62cfdd7044/src/mr.c#L526)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
/rpma/src/mr.c:526:42: error: implicit conversion changes signedness: 'int' to 'enum ib_uverbs_advise_mr_advice' [-Werror,-Wsign-conversion]
        int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
```
https://github.com/ldorau/rpma/runs/3541507648

</blockquote></details>

Done.
___
*[src/mr.c, line 526 at r7](https://reviewable.io/reviews/pmem/rpma/1220#-Mj37wJL4WbYWKcY7fa2:-Mj3caqX8T_HgO50bYuC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a1b8fa8372689e99538e63ac197cf62cfdd7044/src/mr.c#L526)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is enough to add:
```
#include <infiniband/verbs.h>
```
at the beginning.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1180 at r3](https://reviewable.io/reviews/pmem/rpma/1220#-MitRuPO3Nm8HMh68Kw6:-Mj3cjnS22aRR4ALXZgy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/255ce0aea3a87bf4e1fa7d255c9b6c52c870f090/src/include/librpma.h#L1180)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
ibv_advise_mr() failed
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1161 at r8](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3SUpL68HWlHKjNKlL:-Mj3chlv8wmzJ8gkIlEK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/461330c5df2cd39d2212148e8373fe2a6634e876/src/include/librpma.h#L1161)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> give
> ```

gives
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 09:18 UTC, ldorau requested changes
> Reviewed 1 of 5 files at r6, 5 of 7 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

___
*[CMakeLists.txt, line 124 at r11](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3fvo5AFvIAxU3yzKT:-Mj3fvo5AFvIAxU3yzKU:bpanfbe) ([raw file](https://github.com/pmem/rpma/blob/97088b69db31e5b1b1e854b71d692d3a3a156c37/CMakeLists.txt#L124)):*
> ```
> "ibv_advise_mr in libibverbs supported - Success"
> ```

`"ibv_advise_mr() supported in libibverbs - Success"`
___
*[CMakeLists.txt, line 127 at r11](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3fU6f5_R3Hqcr8yEi:-Mj3fU6f5_R3Hqcr8yEj:b-a6qe52) ([raw file](https://github.com/pmem/rpma/blob/97088b69db31e5b1b1e854b71d692d3a3a156c37/CMakeLists.txt#L127)):*
> ```
> ibv_advise_mr
> ```

`ibv_advise_mr()`


<!-- Sent from Reviewable.io -->

2021-09-08 09:50 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[CMakeLists.txt, line 124 at r11](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3fvo5AFvIAxU3yzKT:-Mj3oFbl2AQHQTENvwZQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97088b69db31e5b1b1e854b71d692d3a3a156c37/CMakeLists.txt#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "ibv_advise_mr in libibverbs supported - Success"
> ```

`"ibv_advise_mr() supported in libibverbs - Success"`
</blockquote></details>

Done.
___
*[CMakeLists.txt, line 127 at r11](https://reviewable.io/reviews/pmem/rpma/1220#-Mj3fU6f5_R3Hqcr8yEi:-Mj3oGGBEW2wgojCIwEb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97088b69db31e5b1b1e854b71d692d3a3a156c37/CMakeLists.txt#L127)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ibv_advise_mr
> ```

`ibv_advise_mr()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-08 09:52 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-08 12:29 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 07:21 UTC, janekmi requested changes
> Reviewed 4 of 7 files at r9, 1 of 2 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @osalyk)

___
*[CMakeLists.txt, line 121 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8Ouhm8FjqlXgIrdLp:-Mj8Ouhm8FjqlXgIrdLq:bi13is5) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/CMakeLists.txt#L121)):*
> ```CMake
> endif()
> 
> # check if libibverbs has ibv_advise_mr support
> ```

`ibv_advise_mr()` I think it may increase comprehensibility if you point out it is a function.
___
*[cmake/functions.cmake, line 198 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PJzD783QiRb0v1cn:-Mj8PJzD783QiRb0v1co:bb7b0dg) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/cmake/functions.cmake#L198)):*
> ```CMake
> endfunction()
> 
> # check if libibverbs has ibv_advise_mr support
> ```

`()`
___
*[cmake/functions.cmake, line 202 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PRvi36y832YRPKem:-Mj8PRvi36y832YRPKen:b-5kn7n6) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/cmake/functions.cmake#L202)):*
> ```CMake
> 	CHECK_C_SOURCE_COMPILES("
> 		#include <infiniband/verbs.h>
> 		/* check if 'ibv_advise_mr is defined */
> ```

`'` what is it?
___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-Mj8NRzBD5cPujcJj0eD:b-q3hd5r) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

xD So far, we are using `len` instead of `length`. I know it is not so much important but I very like things to be consistent. Please rename.
___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj8OUuc3lFLNrHMNszN:b75o0j5) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

> enum ibv_advise_mr_advice
Changed back to enum ibv_advise_mr_advice since condition compilation is executed.
</blockquote></details>

Thank you for confirming we should use an `int` here. :+1: 

Sorry, you have to go back to `int`. Please see my other comments about the ifdef location.
___
*[src/mr.c, line 535 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8NjiD5kzFOtb7KZ9A:-Mj8NjiD5kzFOtb7KZ9B:b415t60) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/mr.c#L535)):*
> ```C
> 	return 0;
> }
> #endif
> ```

It is undesirable to put the whole definition inside an ifdef. Because this way all the user applications with have to adjust also and either use or not use this function. I think:

1. Only the internals of the function should be inside an ifdef
2. When `ibv_advise_mr()` is not supported we can just return an error like `RPMA_E_NOSUPP`.
___
*[src/include/librpma.h, line 1180 at r3](https://reviewable.io/reviews/pmem/rpma/1220#-MitRuPO3Nm8HMh68Kw6:-Mj8PdN80yS0E_r-o024:b-83og3x) ([raw file](https://github.com/pmem/rpma/blob/255ce0aea3a87bf4e1fa7d255c9b6c52c870f090/src/include/librpma.h#L1180)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope.
___
*[src/include/librpma.h, line 1149 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8Q68e1aIeDgRZg4RW:-Mj8Q68e1aIeDgRZg4RX:b-4a7wt6) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/include/librpma.h#L1149)):*
> ```objc
> int rpma_mr_remote_delete(struct rpma_mr_remote **mr_ptr);
> 
> #ifdef IBV_ADVISE_MR_SUPPORTED
> ```

Please remove. Please see my other comments for the justification.
___
*[src/include/librpma.h, line 1174 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PeJ5Eky8VRouFRdY:-Mj8PeJ5Eky8VRouFRdZ:b18s8d3) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/include/librpma.h#L1174)):*
> ```objc
>  * rpma_mr_advise() can fail with the following errors:
>  *
>  * - RPMA_E_PROVIDER - memory registration failed
> ```

Please also add:

```
- RPMA_E_NOSUPP - the operation is not supported by the system
```
___
*[tests/unit/common/mocks-ibverbs.h, line 76 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QF9y9ZdxDYBWtHn6:-Mj8QF9y9ZdxDYBWtHn7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.h#L76)):*
> ```objc
> int ibv_req_notify_cq_mock(struct ibv_cq *cq, int solicited_only);
> 
> #ifdef IBV_ADVISE_MR_SUPPORTED
> ```

.
___
*[tests/unit/common/mocks-ibverbs.c, line 351 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QIUr-TEKyKeLm3Mi:-Mj8QIUr-TEKyKeLm3Mj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.c#L351)):*
> ```C
> }
> 
> #ifdef IBV_ADVISE_MR_SUPPORTED
> ```

.
___
*[tests/unit/mr/CMakeLists.txt, line 29 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QNJeDpRuLFD9bTt-:-Mj8QNJeDpRuLFD9bTt0:b5ria3n) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/mr/CMakeLists.txt#L29)):*
> ```CMake
> endfunction()
> 
> if(IBV_ADVISE_MR_SUPPORTED)
> ```

Please remove this if.

Additionally, I think we need one additional test to test the `RPMA_E_NOSUPP` condition.


<!-- Sent from Reviewable.io -->

2021-09-09 07:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj8SBj63SG-FcVWL7eT:b-18vu8u) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Thank you for confirming we should use an `int` here. :+1: 

Sorry, you have to go back to `int`. Please see my other comments about the ifdef location.
</blockquote></details>

@janekmi We have gone back to `enum ibv_advise_mr_advice` finally
___
*[src/mr.c, line 535 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8NjiD5kzFOtb7KZ9A:-Mj8RyBi9W917NMJ8MRu:b2wnxz9) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/mr.c#L535)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is undesirable to put the whole definition inside an ifdef. Because this way all the user applications with have to adjust also and either use or not use this function. I think:

1. Only the internals of the function should be inside an ifdef
2. When `ibv_advise_mr()` is not supported we can just return an error like `RPMA_E_NOSUPP`.
</blockquote></details>

+1 good idea


<!-- Sent from Reviewable.io -->

2021-09-09 07:31 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

___
*[cmake/functions.cmake, line 202 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PRvi36y832YRPKem:-Mj8SnuN4NncMg7AjOW_:b-itzyzj) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/cmake/functions.cmake#L202)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`'` what is it?
</blockquote></details>

Should be  `ibv_advise_mr()` anyway


<!-- Sent from Reviewable.io -->

2021-09-09 07:31 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 08:56 UTC, ldorau reviewed
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj8koP88FlLHrxpElu5:b-kg8b45) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi We have gone back to `enum ibv_advise_mr_advice` finally
</blockquote></details>

... but if the 'ifdef' is moved, we have to go back to 'int' :-) Right :-)


<!-- Sent from Reviewable.io -->

2021-09-09 08:57 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

___
*[src/mr.c, line 527 at r13](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8lWDP-UdlL3qyuYFZ:-Mj8lWDP-UdlL3qyuYF_:b-n5ugvu) ([raw file](https://github.com/pmem/rpma/blob/6a8b09b9d591f4681b309e1f366635bad3c8aa7d/src/mr.c#L527)):*
> ```
> nt ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
> ```

```
/rpma/src/mr.c:527:42: error: implicit conversion changes signedness: 'int' to 'enum ib_uverbs_advise_mr_advice' [-Werror,-Wsign-conversion]
        int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
```


<!-- Sent from Reviewable.io -->

2021-09-09 09:22 UTC, ldorau reviewed
> Reviewed 6 of 6 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 09:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8rYWdBH85OpYksVV-:-Mj8rYWdBH85OpYksVV0:b-v3kov0) (no related file):*
CI builds fail

---


<!-- Sent from Reviewable.io -->

2021-09-09 09:30 UTC, grom72 reviewed
> Reviewed 2 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 8 of 10 files reviewed, 14 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 535 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8NjiD5kzFOtb7KZ9A:-Mj8suS91anof7GTzPPo:b32v57) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/mr.c#L535)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1 good idea
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-09-09 09:30 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 9 of 10 files reviewed, 14 unresolved discussions (waiting on @ewanglong, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 09:30 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 09:38 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8rYWdBH85OpYksVV-:-Mj8ux7Q8wA7xQlLS1rW:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds fail
</blockquote></details>

Done.

---
___
*[CMakeLists.txt, line 121 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8Ouhm8FjqlXgIrdLp:-Mj8uXpM7RVd1RU-rfG7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/CMakeLists.txt#L121)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`ibv_advise_mr()` I think it may increase comprehensibility if you point out it is a function.
</blockquote></details>

Done.
___
*[cmake/functions.cmake, line 198 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PJzD783QiRb0v1cn:-Mj8uYuj3H2Z3VgBkX-p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/cmake/functions.cmake#L198)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`()`
</blockquote></details>

Done.
___
*[cmake/functions.cmake, line 202 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PRvi36y832YRPKem:-Mj8uZep3xD8nTYR8KLL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/cmake/functions.cmake#L202)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Should be  `ibv_advise_mr()` anyway
</blockquote></details>

Done.
___
*[src/mr.c, line 573 at r2](https://reviewable.io/reviews/pmem/rpma/1220#-MiV4iZgCbKsrQZmeBLu:-Mj8uyLiCuDViNqnXy2Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/689deaa7e4c4082fc027a0fb98cce3291b289f38/src/mr.c#L573)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

xD So far, we are using `len` instead of `length`. I know it is not so much important but I very like things to be consistent. Please rename.
</blockquote></details>

Done.
___
*[src/mr.c, line 519 at r4](https://reviewable.io/reviews/pmem/rpma/1220#-MivJ8FsCxk_D5UZn9gm:-Mj8uj7A24bv1x6zHNhn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55acfa3456fd0a67911c01978acb26dabd6aa98a/src/mr.c#L519)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... but if the 'ifdef' is moved, we have to go back to 'int' :-) Right :-)
</blockquote></details>

Done.
___
*[src/mr.c, line 535 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8NjiD5kzFOtb7KZ9A:-Mj8upXV9frhYQNJv8TZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/mr.c#L535)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/mr.c, line 527 at r13](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8lWDP-UdlL3qyuYFZ:-Mj8uoa50bwLM1vfjlzv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a8b09b9d591f4681b309e1f366635bad3c8aa7d/src/mr.c#L527)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> nt ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
> ```

```
/rpma/src/mr.c:527:42: error: implicit conversion changes signedness: 'int' to 'enum ib_uverbs_advise_mr_advice' [-Werror,-Wsign-conversion]
        int ret = ibv_advise_mr(mr->ibv_mr->pd, advice, flags, &sg_list, 1);
```

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1180 at r3](https://reviewable.io/reviews/pmem/rpma/1220#-MitRuPO3Nm8HMh68Kw6:-Mj8uqVG-vzVW5bVZPQ_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/255ce0aea3a87bf4e1fa7d255c9b6c52c870f090/src/include/librpma.h#L1180)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1149 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8Q68e1aIeDgRZg4RW:-Mj8fUIhDAxkl1qlxN-q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/include/librpma.h#L1149)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove. Please see my other comments for the justification.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1174 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8PeJ5Eky8VRouFRdY:-Mj8fkWh2GEvZJicUePP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/src/include/librpma.h#L1174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please also add:

```
- RPMA_E_NOSUPP - the operation is not supported by the system
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.h, line 76 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QF9y9ZdxDYBWtHn6:-Mj8uuJfDV3aLz9a1laA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.h#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 351 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8hRb34Sn9ToHN0dz2:-Mj8hRb34Sn9ToHN0dz3:brl3mwr) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.c#L351)):*
> ```
> fdef IBV_ADVISE_MR_SUPPORTED
> ```
___
*[tests/unit/common/mocks-ibverbs.c, line 351 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QIUr-TEKyKeLm3Mi:-Mj8uvFs52mHsLhxNDOE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.c#L351)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/mr/CMakeLists.txt, line 29 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QNJeDpRuLFD9bTt-:-Mj8uw8S0ExxtGjX86-I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/mr/CMakeLists.txt#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove this if.

Additionally, I think we need one additional test to test the `RPMA_E_NOSUPP` condition.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-09 09:50 UTC, grom72 reviewed
> Reviewed 1 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 09:50 UTC, grom72 reviewed
> Reviewed 3 of 4 files at r13, 2 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-09 09:56 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 16 unresolved discussions (waiting on @ewanglong, @janekmi, @ldorau, and @osalyk)

___
*[tests/unit/common/mocks-ibverbs.h, line 82 at r15](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8yhWW5HxYYl8oCGAT:-Mj8yhWW5HxYYl8oCGAU:bp4olm1) ([raw file](https://github.com/pmem/rpma/blob/5f1612f451cd4ac40b299159d2f972045a20f0ca/tests/unit/common/mocks-ibverbs.h#L82)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> #ifdef IBV_ADVISE_MR_SUPPORTED
> int ibv_advise_mr_mock(struct ibv_pd *pd, enum ibv_advise_mr_advice advice,
> 		uint32_t flags, struct ibv_sge *sg_list, uint32_t num_sge);
> #else
> int ibv_advise_mr_mock(struct ibv_pd *pd, int advice,
> 		uint32_t flags, struct ibv_sge *sg_list, uint32_t num_sge);
> #endif
> ```
</details>


The 'else' part is not needed, please remove it.
This is enough:
```
#ifdef IBV_ADVISE_MR_SUPPORTED
int ibv_advise_mr_mock(struct ibv_pd *pd, enum ibv_advise_mr_advice advice,
		uint32_t flags, struct ibv_sge *sg_list, uint32_t num_sge);
#endif
```

See:
https://github.com/ldorau/rpma/commit/90b97648d0606cb95bfb65a7977bcd979204de4f
https://github.com/ldorau/rpma/actions/runs/1216804162
___
*[tests/unit/common/mocks-ibverbs.c, line 379 at r15](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8yunN2uZmlahG2wRt:-Mj8yunN2uZmlahG2wRu:bojql1n) ([raw file](https://github.com/pmem/rpma/blob/5f1612f451cd4ac40b299159d2f972045a20f0ca/tests/unit/common/mocks-ibverbs.c#L379)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> #else
> int
> ibv_advise_mr_mock(struct ibv_pd *pd,
> 				int advice,
> 				uint32_t flags,
> 				struct ibv_sge *sg_list,
> 				uint32_t num_sge)
> {
> 	return mock_type(int);
> }
> ```
</details>


The 'else' part is not needed, please remove it.
See:
https://github.com/ldorau/rpma/commit/90b97648d0606cb95bfb65a7977bcd979204de4f
https://github.com/ldorau/rpma/actions/runs/1216804162


<!-- Sent from Reviewable.io -->

2021-09-10 01:43 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 8 of 10 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[tests/unit/common/mocks-ibverbs.h, line 82 at r15](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8yhWW5HxYYl8oCGAT:-MjCMQV5DHg3F_FCLJS6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f1612f451cd4ac40b299159d2f972045a20f0ca/tests/unit/common/mocks-ibverbs.h#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #ifdef IBV_ADVISE_MR_SUPPORTED
> int ibv_advise_mr_mock(struct ibv_pd *pd, enum ibv_advise_mr_advice advice,
> 		uint32_t flags, struct ibv_sge *sg_list, uint32_t num_sge);
> #else
> int ibv_advise_mr_mock(struct ibv_pd *pd, int advice,
> 		uint32_t flags, struct ibv_sge *sg_list, uint32_t num_sge);
> #endif
> ```

The 'else' part is not needed, please remove it.
This is enough:
```
#ifdef IBV_ADVISE_MR_SUPPORTED
int ibv_advise_mr_mock(struct ibv_pd *pd, enum ibv_advise_mr_advice advice,
		uint32_t flags, struct ibv_sge *sg_list, uint32_t num_sge);
#endif
```

See:
https://github.com/ldorau/rpma/commit/90b97648d0606cb95bfb65a7977bcd979204de4f
https://github.com/ldorau/rpma/actions/runs/1216804162


</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 379 at r15](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8yunN2uZmlahG2wRt:-MjCMgrJ9eTUJM5kus3Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f1612f451cd4ac40b299159d2f972045a20f0ca/tests/unit/common/mocks-ibverbs.c#L379)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #else
> int
> ibv_advise_mr_mock(struct ibv_pd *pd,
> 				int advice,
> 				uint32_t flags,
> 				struct ibv_sge *sg_list,
> 				uint32_t num_sge)
> {
> 	return mock_type(int);
> }
> ```

The 'else' part is not needed, please remove it.
See:
https://github.com/ldorau/rpma/commit/90b97648d0606cb95bfb65a7977bcd979204de4f
https://github.com/ldorau/rpma/actions/runs/1216804162
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-10 06:23 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-09-13 08:04 UTC, janekmi requested changes
> Reviewed 3 of 4 files at r13, 4 of 6 files at r14, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)

___
*[src/mr.c, line 536 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT6eMPB7b03M95lpQD:-MjT6eMPB7b03M95lpQE:b-9p17xl) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/src/mr.c#L536)):*
> ```C
> 	return 0;
> #else
> 	RPMA_LOG_ERROR_WITH_ERRNO(RPMA_E_NOSUPP, "ibv_advise_mr()");
> ```

```c
RPMA_LOG_ERROR("ibv_advise_mr() is not supported by the system");
```
___
*[src/mr.c, line 537 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT7EAg3Mqydyi6TRDB:-MjT7EAg3Mqydyi6TRDC:b-i00bct) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/src/mr.c#L537)):*
> ```C
> #else
> 	RPMA_LOG_ERROR_WITH_ERRNO(RPMA_E_NOSUPP, "ibv_advise_mr()");
> 	return RPMA_E_NOSUPP;
> ```

Please put a new line between these two new lines.
___
*[tests/unit/common/mocks-ibverbs.h, line 76 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QF9y9ZdxDYBWtHn6:-MjT7wEkDz4FTbw00ZA2:bak8f40) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.h#L76)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please remove the ifdef.
___
*[tests/unit/common/mocks-ibverbs.h, line 77 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT7mlf4qSpQwOsn1pI:-MjT7mlf4qSpQwOsn1pJ:boz5iai) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/common/mocks-ibverbs.h#L77)):*
> ```objc
> 
> #ifdef IBV_ADVISE_MR_SUPPORTED
> int ibv_advise_mr_mock(struct ibv_pd *pd, enum ibv_advise_mr_advice advice,
> ```

enum -> int
___
*[tests/unit/common/mocks-ibverbs.c, line 351 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QIUr-TEKyKeLm3Mi:-MjT86gyCCrqgJt9E3G7:b-xbe2us) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.c#L351)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please remove the ifdef here.
___
*[tests/unit/mr/mr-advise.c, line 160 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT8ZMX1X0YDLSeZI6t:-MjT8ZMX1X0YDLSeZI6u:b-3l82hq) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-advise.c#L160)):*
> ```C
> 		NULL, NULL);
> }
> #endif
> ```

I prefer to put both `test_mr_advise[]` definitions under the ifdef because the main is exactly the same.
So this file will look like:

```c
#ifdef IBV_ADVISE_MR_SUPPORTED

/* tests when ibv_advise_mr() is available */

#else

/* tests when ibv_advise_mr() is NOT available */

#endif

#ifdef IBV_ADVISE_MR_SUPPORTED
static const struct CMUnitTest test_mr_advise[] = {
	/* rpma_mr_adivse() unit tests */
	cmocka_unit_test_setup_teardown(advise__failed_E_PROVIDER,
			setup__mr_local_and_remote,
			teardown__mr_local_and_remote),
	cmocka_unit_test_setup_teardown(advise__success,
			setup__mr_local_and_remote,
			teardown__mr_local_and_remote),
	cmocka_unit_test(NULL)
};
#else
static const struct CMUnitTest test_mr_advise[] = {
	/* rpma_mr_adivse() unit tests */
	cmocka_unit_test_setup_teardown(advise__failed_E_NOSUPP,
			setup__mr_local_and_remote,
			teardown__mr_local_and_remote),
	cmocka_unit_test(NULL)
};
#endif

int
main(int argc, char *argv[])
{
	return cmocka_run_group_tests(test_mr_advise,
		NULL, NULL);
}
```
___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjT9sVn6ppTMIz-LUtZ:b-burd36) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
> ```objc
> #define MOCK_LKEY		(uint32_t)0x20212223
> #define MOCK_ADVICE		1
> #define MOCK_MR_FLAG		1
> ```

Please remove one tab from this line.
___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjTAMyN2tw_BoCl9nHH:-MjTAMyN2tw_BoCl9nHI:b-gfx77r) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
> ```objc
> #define MOCK_LKEY		(uint32_t)0x20212223
> #define MOCK_ADVICE		1
> #define MOCK_MR_FLAG		1
> ```

```c
#define MOCK_MR_FLAG	(1 << 1)
```

Just to differentiate these two.


<!-- Sent from Reviewable.io -->

2021-09-13 08:32 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-09-13 08:58 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r17, 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220#-:-MjTNKNZ5LENC8iRnbHR:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-09-13 09:06 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/common/mocks-ibverbs.h, line 76 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QF9y9ZdxDYBWtHn6:-MjTOBE2EqFtUksxF9rd:bii27md) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.h#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove the ifdef.
</blockquote></details>

it's needed.
___
*[tests/unit/common/mocks-ibverbs.h, line 77 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT7mlf4qSpQwOsn1pI:-MjTOESq1eNEdRCv_dQY:bii27md) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/common/mocks-ibverbs.h#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

enum -> int
</blockquote></details>

it's needed.
___
*[tests/unit/common/mocks-ibverbs.c, line 351 at r12](https://reviewable.io/reviews/pmem/rpma/1220#-Mj8QIUr-TEKyKeLm3Mi:-MjTOHRU09ajATi4bILp:bii27md) ([raw file](https://github.com/pmem/rpma/blob/c0ff613c658dc6d61443c428d72660079787bd3e/tests/unit/common/mocks-ibverbs.c#L351)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove the ifdef here.
</blockquote></details>

it's needed.
___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjTAMyN2tw_BoCl9nHH:-MjTOiJXCg1UGRyqJNjS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
#define MOCK_MR_FLAG	(1 << 1)
```

Just to differentiate these two.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjTOsDO8D5xflkB6oOF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove one tab from this line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-13 09:51 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjTYsLI6wZmOJwtDZ6I:b8ya6qk) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, this tab is needed here. 
@janekmi please check it under vim. 
@ewanglong please revert.


<!-- Sent from Reviewable.io -->

2021-09-13 09:52 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjTZLvR40IW1j7cvSPG:b-w1fepi) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, this tab is needed here. 
@janekmi please check it under vim. 
@ewanglong please revert.
</blockquote></details>

@janekmi only reviewable.io displays it in a wrong way. 


<!-- Sent from Reviewable.io -->

2021-09-13 09:53 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjTZa7o1nxkQrjXDsPx:b-3eswwu) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi only reviewable.io displays it in a wrong way. 
</blockquote></details>

@ewanglong please add one tab only, `(1 << 1)` should stay of course.


<!-- Sent from Reviewable.io -->

2021-09-13 10:05 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjTbJJ39MmS7wovepOc:bkqkd14) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@ewanglong please add one tab only, `(1 << 1)` should stay of course.
</blockquote></details>

I have checked it under VSC. Sorry. vim is obviously better. ;-)


<!-- Sent from Reviewable.io -->

2021-09-13 12:46 UTC, grom72 reviewed
> Reviewed 2 of 4 files at r17, 2 of 2 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-09-14 03:06 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/mr/mr-common.h, line 54 at r16](https://reviewable.io/reviews/pmem/rpma/1220#-MjT9sVn6ppTMIz-LUtY:-MjXG1tj58IT9gXsAeu0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b091b80200352d0f4b17b1a54c799f8033258328/tests/unit/mr/mr-common.h#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have checked it under VSC. Sorry. vim is obviously better. ;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-14 06:03 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1220#-:-MjXtgrA2o78k8ulSvic:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-09-14 06:03 UTC, merged