Update doc for the deprecated APIs
pmem/rpma pull request #1267
Opened 2021-09-08 03:07 UTC by yangx-jy

Ref #1212

2021-09-08 06:29 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj33cDOCHKhg1HsQV8V:-Mj33cDOCHKhg1HsQV8W:b-goajl3) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
> ```
> connection.
> ```

comma instead of full stop at the end, please
___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34A5X-jdGCdQGLdah:-Mj34A5X-jdGCdQGLdai:b-gaa49q) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
> ```
> from the connection.
> ```

```
of the connection,
```
___
*[src/include/librpma.h, line 222 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34K9tAYhRUnNyPSlE:-Mj34K9tAYhRUnNyPSlF:b-fuk88u) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L222)):*
> ```
>  from the connection.
> ```

.
___
*[src/include/librpma.h, line 225 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34arwC9_qaeRuafN2:-Mj34arwC9_qaeRuafN3:b-durx3v) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L225)):*
> ```
> rpma_cq_get_completion().
> ```

comma instead of full stop at the end, please
___
*[src/include/librpma.h, line 247 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34q8R6IjCjn9QVB8C:-Mj34q8R6IjCjn9QVB8D:b-x0x3vf) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L247)):*
> ```
> rpma_ep_next_conn_req()
> ```

Comma at the end, please:
```
rpma_ep_next_conn_req(),
```
___
*[src/include/librpma.h, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj350zH2cXUK0sikRee:-Mj350zH2cXUK0sikRef:b7daohk) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L248)):*
> ```
> rpma_cq_wait()
> ```

```
rpma_cq_wait() and
```
___
*[src/include/librpma.h, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj31BHPAXCCwOwul4rD:-Mj31BHPAXCCwOwul4rE:b5kp26b) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L409)):*
> ```
> becasue
> ```

because
___
*[src/include/librpma.h, line 410 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj31Eye9Ft3ItnxyV1U:-Mj31Eye9Ft3ItnxyV1V:b-6uw0jz) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L410)):*
> ```
> 
>  * We should avoid using the APIs which are marked as deprecated becasue
>  * they will be deleted later.
> ```

```
 * Using of the API functions that are marked as deprecated should be avoided,
 * because they can be removed from the API in any moment.
```


<!-- Sent from Reviewable.io -->

2021-09-08 07:00 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj33cDOCHKhg1HsQV8V:-Mj39crr2GwsX5B-4MM9:b7z1vh2) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> connection.
> ```

comma instead of full stop at the end, please
</blockquote></details>

Hi @ldorau 

Thanks for your review.

It seems the previous `rpma_conn_completion_wait()` and `rpma_conn_completion_get` also use full stop.
Is there any rule? I saw full stop was used in some place.


<!-- Sent from Reviewable.io -->

2021-09-08 07:22 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj33cDOCHKhg1HsQV8V:-Mj3GG6w0j9HgDQnXvvp:bwxbb70) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 

Thanks for your review.

It seems the previous `rpma_conn_completion_wait()` and `rpma_conn_completion_get` also use full stop.
Is there any rule? I saw full stop was used in some place.
</blockquote></details>

Elements of a list should be separated by commas, full stop should be used at the end of a sentence. You enumerate elements of a list here:
```
You have a list of elements here:
- element #1,
- element #2,
- element #3 (no comma after the last element)
which should be ended by the full stop.
```


<!-- Sent from Reviewable.io -->

2021-09-08 07:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj33cDOCHKhg1HsQV8V:-Mj3HWdE78-f65ehIYZe:b-h7cv5f) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Elements of a list should be separated by commas, full stop should be used at the end of a sentence. You enumerate elements of a list here:
```
You have a list of elements here:
- element #1,
- element #2,
- element #3 (no comma after the last element)
which should be ended by the full stop.
```

</blockquote></details>

Or like that:
```
You have a list of elements here:
- element #1,
- element #2,
- the last element #3.
```


<!-- Sent from Reviewable.io -->

2021-09-08 07:40 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 9 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1267#-Mj3L7v75rhMEPzBO-B1:-Mj3L7v75rhMEPzBO-B2:b-bm94rf) (no related file):*
> ```
> rpma_conn_get_completion_fd
> ```
@janekmi @ldorau shall we add information to all deprecated functions on how applications shall be adapted to use new API?

---


<!-- Sent from Reviewable.io -->

2021-09-08 08:00 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1267#-Mj3L7v75rhMEPzBO-B1:-Mj3PvuI-RQeaO9kjvWB:b-2qhc0y) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_conn_get_completion_fd
> ```
@janekmi @ldorau shall we add information to all deprecated functions on how applications shall be adapted to use new API?
</blockquote></details>

A reference to an example can be added.

---


<!-- Sent from Reviewable.io -->

2021-09-08 08:01 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj33cDOCHKhg1HsQV8V:-Mj3NsHa2iVWliRp-e5D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or like that:
```
You have a list of elements here:
- element #1,
- element #2,
- the last element #3.
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 221 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34A5X-jdGCdQGLdah:-Mj3NsqxEfZ3di1q-0IM:bqqox1m) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L221)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> from the connection.
> ```

```
of the connection,
```

</blockquote></details>

Done.  Use `the connection's main CQ,` instead.
___
*[src/include/librpma.h, line 222 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34K9tAYhRUnNyPSlE:-Mj3O-LV35B--zrnKvla:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L222)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  from the connection.
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 225 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34arwC9_qaeRuafN2:-Mj3O0JlEMtj0IX77ftt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L225)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_cq_get_completion().
> ```

comma instead of full stop at the end, please
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 247 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj34q8R6IjCjn9QVB8C:-Mj3O1C05cfe9hQsCGdg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L247)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_ep_next_conn_req()
> ```

Comma at the end, please:
```
rpma_ep_next_conn_req(),
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj350zH2cXUK0sikRee:-Mj3O1bvE7G7pdCXD5Xm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L248)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_cq_wait()
> ```

```
rpma_cq_wait() and
```

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj31BHPAXCCwOwul4rD:-Mj3O2BG0H1w7Mh16EHg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L409)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> becasue
> ```

because
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 410 at r1](https://reviewable.io/reviews/pmem/rpma/1267#-Mj31Eye9Ft3ItnxyV1U:-Mj3O2bB21Kmvg07trXh:b-8wzkod) ([raw file](https://github.com/pmem/rpma/blob/8284b4e8f6b18911c631f97ef515b47ff10cb638/src/include/librpma.h#L410)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 
>  * We should avoid using the APIs which are marked as deprecated becasue
>  * they will be deleted later.
> ```

```
 * Using of the API functions that are marked as deprecated should be avoided,
 * because they can be removed from the API in any moment.
```
</blockquote></details>

Done.  Use the `API calls` which is the unified name in librpma(7).


<!-- Sent from Reviewable.io -->

2021-09-08 08:01 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-09-08 12:30 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-08 12:36 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267#-:-Mj4PIZI1NjHwgOeFlEj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-09 03:52 UTC, yangx-jy commented
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1267#-Mj3L7v75rhMEPzBO-B1:-Mj7d27q5pt0KFUeVutL:b-k7ka0l) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

A reference to an example can be added.
</blockquote></details>

I think we can add a reference to an example after my PR #1271 is merged.

---


<!-- Sent from Reviewable.io -->

2021-09-09 06:19 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-09 13:49 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267#-:-Mj9oUEt8NkXLuaYIFgZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-10 07:04 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-09-17 10:04 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 407 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn3HGP6GzjQsn5r7WK:-Mjn3HGP6GzjQsn5r7WL:bvesjd5) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L407)):*
> ```objc
>  * librpma is built on the top of libibverbs and librdmacm APIs.
>  *
>  * DEPRECATED
> ```

DEPRECATING
___
*[src/include/librpma.h, line 410 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn36T14xX_sQVUM_0_:-Mjn36T29xuGboyWWvHG:b-jcxfk9) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L410)):*
> ```objc
>  *
>  * Using of the API calls which are marked as deprecated should be avoided,
>  * because they can be removed in any moment.
> ```

```
Some API calls are explicitly marked as deprecated. This is because it is planned to remove them in a new major release.

NOTE: API calls deprecated in 0.X release is planned to remove in 0.(X+1) release.
```

@grom72 please take a look.
___
*[src/include/librpma.h, line 1968 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-MjnB14cBANOh3BUOa64:-MjnB14cBANOh3BUOa65:b3vwawx) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L1968)):*
> ```objc
>  * rpma_conn_disconnect(3), rpma_conn_get_completion_fd(3),
>  * rpma_conn_get_event_fd(3), rpma_conn_get_private_data(3),
>  * rpma_conn_completion_get(3), rpma_conn_next_event(3),
> ```

Please:

- add rpma_conn_get_cq(3) and rpma_conn_get_rcq(3) and
- remove rpma_conn_completion_get(3)
- remove rpma_conn_completion_wait(3)
- rpma_conn_get_completion_fd(3)
___
*[src/include/librpma.h, line 2559 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-MjnBK2NBMAsYraPAKu7:-MjnBK2NBMAsYraPAKu8:bcxucxu) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2559)):*
> ```objc
>  *
>  * The order of buffers in the set does not affect the order of completions of
>  * receive operations get via rpma_conn_completion_get(3).
> ```

rpma_cq_completion_get(3)
___
*[src/include/librpma.h, line 2587 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjml7tkDIQ9_Q5kKr_r:-Mjml7tkDIQ9_Q5kKr_s:b-yfwlwu) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2587)):*
> ```objc
> 
> /** 3
>  * rpma_conn_get_completion_fd (deprecated) - get the completion file descriptor
> ```

I have found a few examples of deprecation:

```
cups-lpd(8) - receive print jobs and report printer status to lpd clients (deprecated)
cups-snmp(8) - cups snmp backend (deprecated)
cupsd-helper(8) - cupsd helper programs (deprecated)
cupsfilter(8) - convert a file to another format using cups filters (deprecated)
lpc(8) - line printer control program (deprecated)
lpinfo(8) - show available devices or drivers (deprecated)
snmp(8) - cups snmp backend (deprecated)
dh_installmanpages(1) - old-style man page installer (deprecated)
```

I recommend aligning to this unwritten schema.

Ref: https://man7.org/linux/man-pages/dir_all_by_section.html
___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-Mjn5vys7bsG0DvGWjZS:bj3vq7c) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
> ```objc
>  * the rpma_cq_get_fd(3) for the connection's main CQ available via
>  * rpma_conn_get_cq(3).
>  *
> ```

```
DEPRECATING

Please use rpma_cq_get_completion_fd(3) instead.
```
___
*[src/include/librpma.h, line 2649 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn6NLSBLikCX9RCrCp:-Mjn6NLSBLikCX9RCrCq:bvesjd5) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2649)):*
> ```objc
>  * rpma_conn_completion_wait() waits for an incoming completion. If it
>  * succeeds the completion can be collected using rpma_conn_completion_get().
>  *
> ```

DEPRECATING
___
*[src/include/librpma.h, line 2685 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn6PUxDoF7hy9jj8Fr:-Mjn6PUxDoF7hy9jj8Fs:bvesjd5) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2685)):*
> ```objc
>  * directly using rpma_conn_get_cq(3). Please see rpma_cq_get_completion(3)
>  * for details.
>  *
> ```

DEPRECATING


<!-- Sent from Reviewable.io -->

2021-09-18 09:49 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 407 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn3HGP6GzjQsn5r7WK:-MjsGmU39_cecbHkV-Vg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L407)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

DEPRECATING
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 410 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn36T14xX_sQVUM_0_:-MjsGnDQ0hAwt2zFA9dz:bqs2fw8) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L410)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
Some API calls are explicitly marked as deprecated. This is because it is planned to remove them in a new major release.

NOTE: API calls deprecated in 0.X release is planned to remove in 0.(X+1) release.
```

@grom72 please take a look.
</blockquote></details>

Done. I did some minor change.
___
*[src/include/librpma.h, line 1968 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-MjnB14cBANOh3BUOa64:-MjsGsOmAjj9g9aa_W5W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L1968)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please:

- add rpma_conn_get_cq(3) and rpma_conn_get_rcq(3) and
- remove rpma_conn_completion_get(3)
- remove rpma_conn_completion_wait(3)
- rpma_conn_get_completion_fd(3)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2559 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-MjnBK2NBMAsYraPAKu7:-MjsGu3f6s3VFesuxy6p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2559)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_cq_completion_get(3)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2587 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjml7tkDIQ9_Q5kKr_r:-MjsH-erCoqsskqObIZZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2587)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have found a few examples of deprecation:

```
cups-lpd(8) - receive print jobs and report printer status to lpd clients (deprecated)
cups-snmp(8) - cups snmp backend (deprecated)
cupsd-helper(8) - cupsd helper programs (deprecated)
cupsfilter(8) - convert a file to another format using cups filters (deprecated)
lpc(8) - line printer control program (deprecated)
lpinfo(8) - show available devices or drivers (deprecated)
snmp(8) - cups snmp backend (deprecated)
dh_installmanpages(1) - old-style man page installer (deprecated)
```

I recommend aligning to this unwritten schema.

Ref: https://man7.org/linux/man-pages/dir_all_by_section.html
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-MjsHSzNE96tKnrmNl4h:bmu5zl7) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
DEPRECATING

Please use rpma_cq_get_completion_fd(3) instead.
```
</blockquote></details>

I think `rpma_conn_get_completion_fd()` is replaced by `rpma_conn_get_cq` and `rpma_cq_get_fd`.
I prefer to reference an example here after #1271 is merged.

Ref: #1274 

One question:
Why do you want to add `DEPRECATING` section here? I think `DEPRECATING` is to explain `deprecated` flag.
How about adding a NOTE?
___
*[src/include/librpma.h, line 2649 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn6NLSBLikCX9RCrCp:-MjsIj_kAQlaO_VQgEh-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2649)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

DEPRECATING
</blockquote></details>

.
___
*[src/include/librpma.h, line 2685 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn6PUxDoF7hy9jj8Fr:-MjsIkCY0NXPZGqoGwyo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2685)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

DEPRECATING
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-09-20 08:19 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-09-28 09:33 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-10-01 07:00 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-MkudGLxAuyYw1CBE26I:b-nvjj76) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
> Why do you want to add DEPRECATING section here? I think DEPRECATING is to explain deprecated flag.
> How about adding a NOTE?

I agree. IMHO it could be `NOTE` or `DEPRECATED`.
___
*[src/include/librpma.h, line 410 at r4](https://reviewable.io/reviews/pmem/rpma/1267#-MkubwRw3Lk3NX0r4Ecu:-MkubwRw3Lk3NX0r4Ecv:bjmu8l4) ([raw file](https://github.com/pmem/rpma/blob/1ba7fb47348fe1617889c551e55ebbc10ec1728d/src/include/librpma.h#L410)):*
> ```
>  in a new major release.
> ```

> ```
>  * NOTE: API calls deprecated in 0.X release will be removed in 0.(X+1) release
>  * usually.
> ```

... so **minor**, not major ?


<!-- Sent from Reviewable.io -->

2021-10-01 08:00 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-10-01 08:30 UTC, janekmi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-MkuwVnZD4WdTNYcWvke:bxc2ryz) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
Examples are not installed in the system. So effectively, if one will find a system with installed librpma within it the reference you want to put here will be hard to follow.

It doesn't matter if it is a NOTE or DEPRECATED or DEPRECATING as long as it is a distinctive section clearly stating you should consider using other functions since this one will be removed soon. ;-)

> I think rpma_conn_get_completion_fd() is replaced by rpma_conn_get_cq and rpma_cq_get_fd.

I do agree.

@yangx-jy Taking all of this into consideration, please write in the comment or in the pull request what is your proposition.
___
*[src/include/librpma.h, line 410 at r4](https://reviewable.io/reviews/pmem/rpma/1267#-MkubwRw3Lk3NX0r4Ecu:-Mkuxv4PADF_U7u9Cbv-:b-gnbvv0) ([raw file](https://github.com/pmem/rpma/blob/1ba7fb47348fe1617889c551e55ebbc10ec1728d/src/include/librpma.h#L410)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  in a new major release.
> ```

> ```
>  * NOTE: API calls deprecated in 0.X release will be removed in 0.(X+1) release
>  * usually.
> ```

... so **minor**, not major ?
</blockquote></details>

The note here is to describe a special case that is deprecating a function before the 1.0 release (0.X release).


<!-- Sent from Reviewable.io -->

2021-10-01 08:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-Mkv0zP-9P3lHMGrR2F6:b-6a9t57) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Examples are not installed in the system. So effectively, if one will find a system with installed librpma within it the reference you want to put here will be hard to follow.

It doesn't matter if it is a NOTE or DEPRECATED or DEPRECATING as long as it is a distinctive section clearly stating you should consider using other functions since this one will be removed soon. ;-)

> I think rpma_conn_get_completion_fd() is replaced by rpma_conn_get_cq and rpma_cq_get_fd.

I do agree.

@yangx-jy Taking all of this into consideration, please write in the comment or in the pull request what is your proposition.
</blockquote></details>

I agree (but DEPRECATING is not correct in this case in my opinion).
___
*[src/include/librpma.h, line 410 at r4](https://reviewable.io/reviews/pmem/rpma/1267#-MkubwRw3Lk3NX0r4Ecu:-Mkv0c9U9tLb8fqWM7Hi:b-7vo826) ([raw file](https://github.com/pmem/rpma/blob/1ba7fb47348fe1617889c551e55ebbc10ec1728d/src/include/librpma.h#L410)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The note here is to describe a special case that is deprecating a function before the 1.0 release (0.X release).
</blockquote></details>

Ah, I see.


<!-- Sent from Reviewable.io -->

2021-10-01 10:55 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-MkvURfjBJPchC40da1e:b-qud5k2) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I agree (but DEPRECATING is not correct in this case in my opinion).
</blockquote></details>

DEPRECATED :+1: 


<!-- Sent from Reviewable.io -->

2021-10-01 10:57 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-MkvV2rq31oU5EJfMmQd:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

DEPRECATED :+1: 
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-10-01 13:10 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-10-01 14:24 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 2601 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn5vys7bsG0DvGWjZR:-MkwDr3k9idpinhX49cQ:b25uzvt) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2601)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done. Use DEPRECATED section instead.

I add some description in commit message:
```
1) mark rpma_conn_completion_get(), rpma_conn_completion_wait()
   and rpma_conn_get_completion_fd() as deprecated.
2) add DEPRECATING section to explain the deprecated tag.
3) add DEPRECATED section to explain how to use new functions instead.
```
___
*[src/include/librpma.h, line 2649 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn6NLSBLikCX9RCrCp:-MkwDuT26lRMWiRCx5XP:bnj20ki) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2649)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done. Use DEPRECATED section instead.
___
*[src/include/librpma.h, line 2685 at r3](https://reviewable.io/reviews/pmem/rpma/1267#-Mjn6PUxDoF7hy9jj8Fr:-MkwEUlG1P7Hin2V_J-a:bnj20ki) ([raw file](https://github.com/pmem/rpma/blob/03e177bfe14acc375046dda74f7cd1ef1d9f220f/src/include/librpma.h#L2685)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done. Use DEPRECATED section instead.


<!-- Sent from Reviewable.io -->

2021-10-04 06:46 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-10-04 06:47 UTC, ldorau approved these changes
@janekmi ping

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267#-:-Ml92Xa_1NBkQCJoCj0u:b-3p17t8)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-10-05 18:01 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-10-15 11:17 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1267#-:-Mm2eym162ao3fIbc_Ip:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-10-15 11:17 UTC, merged