common: move the last Fedora Rawhide CI build to Nightly_Experimental
pmem/rpma pull request #1277
Opened 2021-09-13 07:35 UTC by ldorau

Move the last Fedora Rawhide CI build
from Nightly_Rebuild to Nightly_Experimental.

See: 1275

2021-09-13 13:53 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1277#-:-MjUQlLq2lmK--zKC5Ob:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-09-13 16:30 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1277#-MjUzZnp-ZYug9squ6e3:-MjUzZnp-ZYug9squ6e4:b-xpy4v0) (no related file):*
Please add the rationale to the commit message.

---
___
*[.github/workflows/nightly_rebuild.yml, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1277#-MjUz5HQ-9Q3iF8l8jt7:-MjUz5HQ-9Q3iF8l8jt8:b-lfyzma) ([raw file](https://github.com/pmem/rpma/blob/52cea7b4ffcb0990d278fb84e3207a709c45abb3/.github/workflows/nightly_rebuild.yml#L2)):*
> ```YAML
> 
> # This build is run at 00:00 UTC every day
> ```

TBH We have so many builds I forgot what this is all about. Can you add a line of comment what is the purpose for each of them?
It may be a separate PR if you will.


<!-- Sent from Reviewable.io -->

2021-09-14 05:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1277#-MjUzZnp-ZYug9squ6e3:-MjXjZ6Z6ZaIdeKsiXzJ:b-3i92lo) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add the rationale to the commit message.
</blockquote></details>

It has been already added (See: #1275) - do you want me to copy the old commit message here?

---
___
*[.github/workflows/nightly_rebuild.yml, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1277#-MjUz5HQ-9Q3iF8l8jt7:-MjXjpJh9ItLkCFUXC0L:b-aj7nab) ([raw file](https://github.com/pmem/rpma/blob/52cea7b4ffcb0990d278fb84e3207a709c45abb3/.github/workflows/nightly_rebuild.yml#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH We have so many builds I forgot what this is all about. Can you add a line of comment what is the purpose for each of them?
It may be a separate PR if you will.
</blockquote></details>

OK, it will be a separate PR.


<!-- Sent from Reviewable.io -->

2021-09-14 06:34 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1277#-:-MjY-n7M19km9DRafSds:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1277#-MjUzZnp-ZYug9squ6e3:-MjY-dp3BnhW_OwTY6_Q:b4kzwd1) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has been already added (See: #1275) - do you want me to copy the old commit message here?
</blockquote></details>

I see now. The reference is enough I think. Thank you.

---


<!-- Sent from Reviewable.io -->

2021-09-14 06:39 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1277)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1277#-MjUzZnp-ZYug9squ6e3:-MjY0wM95m07ek9APWNv:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I see now. The reference is enough I think. Thank you.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-09-14 07:21 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1277)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-09-14 07:21 UTC, merged