common: disable consider-using-f-string in pylint
pmem/rpma pull request #1287
Opened 2021-09-17 09:23 UTC by ldorau

Disable the pylint 'consider-using-f-string' warning, see:
https://github.com/pmem/rpma/runs/3627503704

We cannot use f-strings, because they are not supported
on Debian 9 with python v3.5.3 and pylint3 v1.6.5.

2021-09-17 09:26 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/pylint.rc, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1287#-Mjn3o_43EO3jw3EWedR:-Mjn3o_43EO3jw3EWedS:bm490w) ([raw file](https://github.com/pmem/rpma/blob/406f7c58400a64e780f390355c33fff010a9d633/utils/pylint.rc#L9)):*
> ```
> # too-many-arguments - (X>5) XXX requires consideration
> # too-many-instance-attributes - (X>7) XXX requires consideration
> # no-self-use - XXX requires consideration
> ```

Please add a note here in the style introduced above with the abbreviated description you have put in the commit message.


<!-- Sent from Reviewable.io -->

2021-09-17 09:30 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1287)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/pylint.rc, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1287#-Mjn3o_43EO3jw3EWedR:-Mjn4pqo5hTt5zCYhSMg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/406f7c58400a64e780f390355c33fff010a9d633/utils/pylint.rc#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a note here in the style introduced above with the abbreviated description you have put in the commit message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 09:47 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/pylint.rc, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1287#-Mjn8Wi7Co2zvZDHBidz:-Mjn8Wi7Co2zvZDHBie-:b-z3exb3) ([raw file](https://github.com/pmem/rpma/blob/88f04b33d2f358e35c3adde1c53d09a816800d16/utils/pylint.rc#L10)):*
> ```
> # too-many-instance-attributes - (X>7) XXX requires consideration
> # no-self-use - XXX requires consideration
> # consider-using-f-string - we cannot use f-strings, because they are not supported on Debian 9 with python v3.5.3 and pylint3 v1.6.5
> ```

I do like the `we` part. I think it is unnecessary e.g.:

```
f-string is not supported on Debian 9 with python v3.5.3 and pylint3 v1.6.5
```


<!-- Sent from Reviewable.io -->

2021-09-17 09:48 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1287)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/pylint.rc, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1287#-Mjn8Wi7Co2zvZDHBidz:-Mjn92kEBfi9GUR6NQRc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88f04b33d2f358e35c3adde1c53d09a816800d16/utils/pylint.rc#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do like the `we` part. I think it is unnecessary e.g.:

```
f-string is not supported on Debian 9 with python v3.5.3 and pylint3 v1.6.5
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-17 09:48 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1287#-:-Mjn986QEaGdF7GWXc9b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-09-20 06:19 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1287#-:-Mk0qsGrEC3cKurcybEz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-09-20 07:07 UTC, merged