common: add libpmem2 to docker images
pmem/rpma pull request #1306
Opened 2021-10-13 11:18 UTC by Patryk717

use of libpmem2 instead of libpmem for mapping PMem allows decreasing number of resources needed to run examples

Ref: #991

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1306)

2021-10-15 11:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1306#-Mm2_Eou3KT37CJ2a_Ya:-Mm2gHU-DJWHFYoXG7EX:bwiak5h) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why should it have? None of our OSes has pmdk installed.
</blockquote></details>

Ah, to have libpmem ...

---


<!-- Sent from Reviewable.io -->

2021-10-15 13:17 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1306#-Mm2_Eou3KT37CJ2a_Ya:-Mm35K414fibvu21AVOF:b-42o5tx) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is an error in the package
</blockquote></details>

BTW @janekmi this is not an issue for this PR

---


<!-- Sent from Reviewable.io -->

2021-10-15 14:15 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1306#-Mm2_Eou3KT37CJ2a_Ya:-Mm3IcneBVRqp0Fh-Frm:b-4kk1x) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

BTW @janekmi this is not an issue for this PR
</blockquote></details>

Done: https://github.com/pmem/rpma/pull/1310

---


<!-- Sent from Reviewable.io -->

2021-10-18 11:38 UTC, janekmi requested changes
> Reviewed 6 of 7 files at r3, 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1306#-MmIBLTz6p0hthVC5D3Y:-MmIBLTz6p0hthVC5D3Z:b-ft0v4t) ([raw file](https://github.com/pmem/rpma/blob/92a6d9a2f5abbb91caa27bf8918164cc14752318/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L33)):*
> ```
> ENV TOOLS_DEPS "\
> 	python3-Jinja2"
> ```

libpmem2 is still missing.


<!-- Sent from Reviewable.io -->

2021-10-18 11:42 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @Patryk717)



<!-- Sent from Reviewable.io -->

2021-10-18 13:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @Patryk717)

___
*[utils/docker/images/Dockerfile.debian-stable, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1306#-Mm2aQsB27OpLEAIbJHw:-MmIbCR77xvV2hqteEOl:b-m7e3f5) ([raw file](https://github.com/pmem/rpma/blob/ef9b6ad34bee0499013f48b4aada437b97d105ca/utils/docker/images/Dockerfile.debian-stable#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you post the link to this build here?
</blockquote></details>

Both Debian experimental and testing have the libpmem2-dev package:
https://github.com/ldorau/rpma/actions/runs/1354818763
https://github.com/ldorau/rpma/commit/fb0e1032490c82beab8f3d904ddce0e076f8241c


<!-- Sent from Reviewable.io -->

2021-10-21 09:48 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1306)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1306#-MmISMCn93fxiRhIXU8i:-MmXFAHB3uu_mCPfB8TO:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@patryk717  It still exists
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-10-21 11:29 UTC, merged