tools: perf: introduce report_figures.py compare mode
pmem/rpma pull request #1319
Opened 2021-11-15 13:00 UTC by osalyk

Continuation #1298

2021-11-15 13:29 UTC, janekmi requested changes
> Reviewed 29 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 29 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/1319#-MoYl-Ek3YeI4eKSffWA:-MoYl-Ek3YeI4eKSffWB:b-hvyj8j) ([raw file](https://github.com/pmem/rpma/blob/42b3b7e2c190d18aaf0227ce081632493054e1fa/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
> ```
> 	matplotlib \
> 	pandas \
> 	deepdiff"
> ```

Has to be added also to BENCHMARKING.md.
___
*[utils/docker/images/Dockerfile.centos-7, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1319#-MoYlEFQ-VFYo28yFEWQ:-MoYlEFQ-VFYo28yFEWR:b-1uh4wi) ([raw file](https://github.com/pmem/rpma/blob/42b3b7e2c190d18aaf0227ce081632493054e1fa/utils/docker/images/Dockerfile.centos-7#L93)):*
> ```
> # install python modules for the default user
> RUN pip3 install --user $PYTHON_DEPS	deepdiff
> deepdiff
> ```

What it is for?


<!-- Sent from Reviewable.io -->

2021-11-15 15:39 UTC, ldorau requested changes
> Reviewed 28 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDlCLCZwV0IcY0ya0:-MoZDlCLCZwV0IcY0ya1:b-j8ssxv) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
> ```
> 	matplotlib \
> 	pandas \
> 	deepdiff"
> ```

I think that all changes to Docker files should be made in a separate PR.
___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDzARB0QoNp2-N-mW:-MoZDzARB0QoNp2-N-mX:bck68yn) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
> ```
> 	matplotlib \
> 	pandas \
> 	deepdiff"
> ```

Alphabetical order please


<!-- Sent from Reviewable.io -->

2021-11-15 16:01 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDzARB0QoNp2-N-mW:-MoZKEY02C97EkqQC34m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Alphabetical order please
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDlCLCZwV0IcY0ya0:-MoZKEpf7NkEVCZMdvzA:b-8sgh9d) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think that all changes to Docker files should be made in a separate PR.
</blockquote></details>

#1321


<!-- Sent from Reviewable.io -->

2021-11-15 16:10 UTC, janekmi reviewed
> Reviewed 28 of 29 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-16 07:35 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, all discussions resolved (waiting on @janekmi and @ldorau)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDlCLCZwV0IcY0ya0:-Mobej0e7LbiGhN6nufv:b-xuvm4g) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

#1321
</blockquote></details>

OK, so remove it from the current one, please


<!-- Sent from Reviewable.io -->

2021-11-16 07:39 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDlCLCZwV0IcY0ya0:-MobfoC67k45cX0zWHJC:b2j31on) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, so remove it from the current one, please
</blockquote></details>

Rebase, please


<!-- Sent from Reviewable.io -->

2021-11-16 07:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDzARB0QoNp2-N-mW:-Mobg-PrEnSD0NSVphLE:b-u1vy19) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not in this PR.


<!-- Sent from Reviewable.io -->

2021-11-16 08:10 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 0 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDzARB0QoNp2-N-mW:-Mobmuu3Aw_2JJk7fl7m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not in this PR.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.archlinux-latest, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1319#-MoZDlCLCZwV0IcY0ya0:-Mobmvu_5usbCq0gVr-h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8716af5f7916f179a70ef7ddb331a55234ebb765/utils/docker/images/Dockerfile.archlinux-latest#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase, please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-16 10:00 UTC, janekmi reviewed
> Reviewed 28 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-16 10:01 UTC, janekmi reviewed
> Reviewed 1 of 29 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 29 of 34 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-16 10:03 UTC, ldorau reviewed
> Reviewed 1 of 29 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 29 of 34 files reviewed, all discussions resolved (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-16 12:06 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 30 of 34 files reviewed, 13 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/compare.py, line 125 at r8](https://reviewable.io/reviews/pmem/rpma/1319#-MoccrItE0q1rf11eHuc:-MoccrItE0q1rf11eHud:b-atf74a) ([raw file](https://github.com/pmem/rpma/blob/39a7a3385192976df4da720c9cc7ca69eb2341f8/tools/perf/lib/compare.py#L125)):*
> ```Python
>         keycontent = data.get(self._figure.key)
>         output_path = self.png_path()
>         # XXX - add setters to yaxis_max for bw and lat
> ```

`- ` seems redundant.


<!-- Sent from Reviewable.io -->

2021-11-16 12:34 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 28 of 35 files reviewed, 12 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/report_figures.py, line 23 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocJxrf072JM9oYzb_K:-Mocgi4YBreoXeTSb7X_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/report_figures.py#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This change requires an update to BENCHMARKING.md

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/BENCHMARKING.md#3-generate-figures
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 36 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocKj_W7OZrXoLlYvvh:-MocehQ58G4iE4fB3CDt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/report_figures.py#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

of completed benchmarks
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 33 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocOxApA8FIX3IHLjuZ:-Moch0QV6Ru_CVAKirts:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... (both JSON and PNG files)
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 48 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocQKXJ7BUBhnX0iE-7:-Moch6DA8yK_9szN9eJf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... to bench.json file
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 49 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocUpSzETXgD8Gk6ukG:-MociLL1AhDFCCOJw1mC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
# XXX assuming the first benchmark covers all figures of the comparison which may not always be true
```
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 57 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocVe9C6O0cOdUwlLg3:-MociQ731YeC9eY0Pr6y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please indent this line.
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 71 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-MocWAvJBVpR9KEck5Nr:-MociaJx751FAbdy5sPP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please put this comment above the `self._figures = {}`. I think it will be easier to follow that way.
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 78 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-Moc_DEi4l42NW0GUKaF:-MocilUp8aRG-U5vZt7j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A docstring is missing. :-)

e.g.

> Combine series from all figures involved into a single figure
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 94 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-Moc_Olr6wpAf0E9s4vS:-MocissR6OKIyTFfeJa_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Unnecessary spaces at the end of the line.
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 108 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-Moc_wMK75kDob1Iffud:-Mocixfs1IMiDB0IeKgN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Commented out. Please remove.
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 128 at r6](https://reviewable.io/reviews/pmem/rpma/1319#-Mocavvb9S-8_co8n0t0:-MocjSv53f6oWVEQ3JmO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/474011c424fd8216c14fef58bc626a31ab84c9eb/tools/perf/lib/compare.py#L128)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This `None` should fit into the previous line.
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 125 at r8](https://reviewable.io/reviews/pmem/rpma/1319#-MoccrItE0q1rf11eHuc:-Mocj1v9Dv-6IG8PLwb3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39a7a3385192976df4da720c9cc7ca69eb2341f8/tools/perf/lib/compare.py#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`- ` seems redundant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-16 12:46 UTC, janekmi reviewed
> Reviewed 1 of 2 files at r7, 2 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 31 of 35 files reviewed, all discussions resolved (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-16 12:48 UTC, ldorau requested changes
> Reviewed 1 of 5 files at r1, 1 of 4 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 34 of 35 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-MocmLKnELXQhBTb7b33:b-n0vnvu) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
> ```
> report
> ```

Maybe `create` ?
___
*[tools/perf/BENCHMARKING.md, line 157 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmVAi5-4rbWVKLWmv:-MocmVAi5-4rbWVKLWmw:b-zmw5p) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L157)):*
> ```
> report
> ```

.


<!-- Sent from Reviewable.io -->

2021-11-16 12:56 UTC, janekmi requested changes
> Reviewed 1 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 34 of 35 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-MocnpXl2-B_yPtcduVq:b-7qjvwj) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> report
> ```

Maybe `create` ?
</blockquote></details>

I agree `report` is unfortunate. But I'm not sure having a choice between `create` and `compare`... I'm not sure.
___
*[tools/perf/BENCHMARKING.md, line 171 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKy0G_sGoOe6jyC:-MocmLKy0G_sGoOe6jyD:b-p5jr5d) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L171)):*
> ```Markdown
> ```sh
> $ ./report_figures.py compare -h
> ```
> ```

What you have called step number 4 is not yet another step in this process. It is a separate thing to do. If you will I recommend calling it a separate section e.g.

```
## Comparing
```

and add it at the end of this file.


<!-- Sent from Reviewable.io -->

2021-11-16 12:56 UTC, janekmi reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-16 13:00 UTC, janekmi requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/tests/lib/report/test_init.py, line 46 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocpLqf7xa6dIy7SXtv:-MocpLqf7xa6dIy7SXtw:b-lgerv8) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/tests/lib/report/test_init.py#L46)):*
> ```Python
> class BenchMock:
>     """a lib.Bench.Bench mock"""
>     config = CONFIG_DUMMY
> ```

Why it is needed?


<!-- Sent from Reviewable.io -->

2021-11-16 13:09 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1319#-MocqTQd41hibGsE8Vrw:-MocqTQd41hibGsE8Vrx:b7gl650) (no related file):*
I think all the commits should be squashed into a single commit:

- most of them overwrites each other
- the change to pylint.rc "fixes" the build "broken" by all of the changes you do which obviously has to go in the same commit otherwise bisection won't be possible.

---


<!-- Sent from Reviewable.io -->

2021-11-16 13:09 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-16 13:27 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1319#-MocqTQd41hibGsE8Vrw:-MoctkMNEDOEC3vDGap4:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think all the commits should be squashed into a single commit:

- most of them overwrites each other
- the change to pylint.rc "fixes" the build "broken" by all of the changes you do which obviously has to go in the same commit otherwise bisection won't be possible.
</blockquote></details>

Done.

---
___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-Mocv_zLCJZOM_RpkaUy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I agree `report` is unfortunate. But I'm not sure having a choice between `create` and `compare`... I'm not sure.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-16 13:29 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 157 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmVAi5-4rbWVKLWmv:-MocvcAFB4n321RvamSx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> report
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 171 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKy0G_sGoOe6jyC:-MocvtOr16ohvogjF4bw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L171)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What you have called step number 4 is not yet another step in this process. It is a separate thing to do. If you will I recommend calling it a separate section e.g.

```
## Comparing
```

and add it at the end of this file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-16 13:31 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 32 of 35 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/tests/lib/report/test_init.py, line 46 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocpLqf7xa6dIy7SXtv:-MocwQPT0VXVe_FbZh9-:b-42euo1) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/tests/lib/report/test_init.py#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why it is needed?
</blockquote></details>

    def _load_parts(self, loader, env, bench):
        self.parts = []
        if not bench.config.get('compare', False):


<!-- Sent from Reviewable.io -->

2021-11-16 13:35 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 33 of 35 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-16 20:33 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1319#-MocqTQd41hibGsE8Vrw:-MoePIb641N2oykwQZgA:bhklqw5) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope. I mean to squash all of them including the change to pylint.rc into a single commit.

---
___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-MoePwf52xHHb6-N54AU:b-qbdbh8) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe:

- `report_figures.py single ...` for generating figures for a single, you know where it comes from, benchmark
- `report_figures.py compare ...` for generating figures comparing results coming from multiple benchmarks

What do you think?
___
*[tools/perf/BENCHMARKING.md, line 189 at r12](https://reviewable.io/reviews/pmem/rpma/1319#-MoeQzMf0iho5dKDM_Aw:-MoeQzMf0iho5dKDM_Ax:b-fi9kt) ([raw file](https://github.com/pmem/rpma/blob/b20317e4e1ac203ad114ae3a5ee643b15f1fb2c1/tools/perf/BENCHMARKING.md#L189)):*
> ```Markdown
> $ pdftk report.pdf stamp watermark.pdf output report_with_watermark.pdf
> ```
> ### 6) Generate comparison figures (optional)
> ```

`## Comparing`
___
*[tools/perf/BENCHMARKING.md, line 200 at r12](https://reviewable.io/reviews/pmem/rpma/1319#-MoeR4vx6hdaCUHbIY78:-MoeR4vx6hdaCUHbIY79:bqyppsh) ([raw file](https://github.com/pmem/rpma/blob/b20317e4e1ac203ad114ae3a5ee643b15f1fb2c1/tools/perf/BENCHMARKING.md#L200)):*
> ```Markdown
> ```sh
> $ ./report_figures.py compare -h
> ```
> ```

The end of the line is missing.
___
*[tools/perf/tests/lib/report/test_init.py, line 46 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocpLqf7xa6dIy7SXtv:-MoeRfaABzjAMd9Dyj2S:b-63px68) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/tests/lib/report/test_init.py#L46)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

    def _load_parts(self, loader, env, bench):
        self.parts = []
        if not bench.config.get('compare', False):

</blockquote></details>

So, these two are not needed:

```
    'REMOTE_USER': 'user',
    'REMOTE_PASS': 'pass'
```

you can replace this custom made dictionary with an empty one e.g.

```python
config = {}
```


<!-- Sent from Reviewable.io -->

2021-11-17 07:39 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 33 of 35 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1319#-MocqTQd41hibGsE8Vrw:-Mognfl46WydcUerx7kT:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope. I mean to squash all of them including the change to pylint.rc into a single commit.
</blockquote></details>

Done.

---
___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-MogoAzK8or9WCvV3VhJ:b-hkso8q) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe:

- `report_figures.py single ...` for generating figures for a single, you know where it comes from, benchmark
- `report_figures.py compare ...` for generating figures comparing results coming from multiple benchmarks

What do you think?
</blockquote></details>

Instead of **single** perhaps **make** or **generate**?
___
*[tools/perf/BENCHMARKING.md, line 189 at r12](https://reviewable.io/reviews/pmem/rpma/1319#-MoeQzMf0iho5dKDM_Aw:-Mogp-tR23R6DGotJ5g_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b20317e4e1ac203ad114ae3a5ee643b15f1fb2c1/tools/perf/BENCHMARKING.md#L189)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`## Comparing`
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 200 at r12](https://reviewable.io/reviews/pmem/rpma/1319#-MoeR4vx6hdaCUHbIY78:-Mogp3Fp1_RYUDuOrSSO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b20317e4e1ac203ad114ae3a5ee643b15f1fb2c1/tools/perf/BENCHMARKING.md#L200)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The end of the line is missing.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/report/test_init.py, line 46 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocpLqf7xa6dIy7SXtv:-MogpVKy6AoKQ4HhsjB8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/tests/lib/report/test_init.py#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So, these two are not needed:

```
    'REMOTE_USER': 'user',
    'REMOTE_PASS': 'pass'
```

you can replace this custom made dictionary with an empty one e.g.

```python
config = {}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 08:39 UTC, ldorau requested changes
> Reviewed 2 of 29 files at r6, 1 of 1 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-Moh1kTy6S1BspnxR3VM:b-iwg020) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Instead of **single** perhaps **make** or **generate**?
</blockquote></details>

I'm for `generate`


<!-- Sent from Reviewable.io -->

2021-11-17 09:37 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 33 of 35 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 151 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocmLKm49hZ-mrLXrCe:-MohFVZP8duVDJ0oObKX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I'm for `generate`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 11:17 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r13, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 189 at r12](https://reviewable.io/reviews/pmem/rpma/1319#-MoeQzMf0iho5dKDM_Aw:-MohagNp5SOaV8LtI4UM:b-uk773u) ([raw file](https://github.com/pmem/rpma/blob/b20317e4e1ac203ad114ae3a5ee643b15f1fb2c1/tools/perf/BENCHMARKING.md#L189)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`## Comparing`

 :rofl: 
___
*[tools/perf/tests/lib/report/test_init.py, line 46 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocpLqf7xa6dIy7SXtv:-Mohb8lV9uEk5u0UHsXt:b-5312vc) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/tests/lib/report/test_init.py#L46)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`CONFIG_DUMMY` is sooooo not needed.


<!-- Sent from Reviewable.io -->

2021-11-17 11:36 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 33 of 35 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 189 at r12](https://reviewable.io/reviews/pmem/rpma/1319#-MoeQzMf0iho5dKDM_Aw:-MoheqAE9xAf9ZhpLMmS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b20317e4e1ac203ad114ae3a5ee643b15f1fb2c1/tools/perf/BENCHMARKING.md#L189)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`## Comparing`

 :rofl: 
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/report/test_init.py, line 46 at r10](https://reviewable.io/reviews/pmem/rpma/1319#-MocpLqf7xa6dIy7SXtv:-Mohf9jI2WTpUI0u2CkP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c9b99cebe4ab86ef5ba72ec2a761bc554264333/tools/perf/tests/lib/report/test_init.py#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`CONFIG_DUMMY` is sooooo not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-17 11:58 UTC, ldorau requested changes
> Reviewed 1 of 5 files at r1, 10 of 29 files at r6, 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 34 of 35 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1319#-MohkdF83S_6ZMfVktcB:-MohkdF83S_6ZMfVktcC:b-n6khor) (no related file):*
Please rebase

---


<!-- Sent from Reviewable.io -->

2021-11-17 12:02 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 33 of 35 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1319#-MohkdF83S_6ZMfVktcB:-MohlhGbAM4WHuNABUZr:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-11-17 12:07 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-17 12:56 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319#-:-Mohxye51QPN49g5Z_ts:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-17 14:59 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r9, 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report_figures.py, line 63 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiLQpkAhEAqOWueUhx:-MoiLQpkAhEAqOWueUhy:bbwllei) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/report_figures.py#L63)):*
> ```
> generate a comparison figures
> ```

`generate comparative figures`
___
*[tools/perf/lib/compare.py, line 63 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiMfoMBoTZBxDX1MZi:-MoiMfoMBoTZBxDX1MZj:b-1ptpnz) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/compare.py#L63)):*
> ```
> "utf-8"
> ```

`'utf-8'`
___
*[tools/perf/lib/compare.py, line 67 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiMmzlExKn1hHG_34g:-MoiMmzlExKn1hHG_34h:bbn4ucb) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/compare.py#L67)):*
> ```
> a comparison among
> ```

`a comparison between`
___
*[tools/perf/lib/compare.py, line 112 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiNjyXA2tPy3M_cBpr:-MoiNjyXA2tPy3M_cBps:b-sc2hz9) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/compare.py#L112)):*
> ```
> "utf-8"
> ```

.
___
*[tools/perf/lib/figure.py, line 34 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiOG6g0FmdgoZsBhHi:-MoiOG6g0FmdgoZsBhHj:bqmwvk8) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L34)):*
> ```
> 'pad': 2
> ```

Are you sure the padding equal 2 will be good?
We have decreased it from 6 to 1 - see: 2bdacc16ceb45cd25c0735a51be5a88d05347787
___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-MoiP80Q0HWQ268FOiQp:b-vabi1b) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
> ```Python
>                 line_style = group_to_line_styles[group]
>             else:
>                 if len(line_styles) > 0:
> ```

```
/rpma/tools/perf/lib/figure.py:300:19: C1801: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
```

See https://github.com/ldorau/rpma/runs/4239593859


<!-- Sent from Reviewable.io -->

2021-11-17 15:02 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-18 07:51 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/report_figures.py, line 63 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiLQpkAhEAqOWueUhx:-Molwx8h9VVOOigRuggn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/report_figures.py#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> generate a comparison figures
> ```

`generate comparative figures`
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 63 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiMfoMBoTZBxDX1MZi:-Molx6ry9KHZN9obtdZc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/compare.py#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "utf-8"
> ```

`'utf-8'`
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 67 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiMmzlExKn1hHG_34g:-MolxC9z9t8MT_ii3BJ1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/compare.py#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a comparison among
> ```

`a comparison between`
</blockquote></details>

Done.
___
*[tools/perf/lib/compare.py, line 112 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiNjyXA2tPy3M_cBpr:-MolxKyS-PLJsYPugxzY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/compare.py#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "utf-8"
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 34 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiOG6g0FmdgoZsBhHi:-Mom0IIf7c7o_lcDTqPc:b1zjhic) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 'pad': 2
> ```

Are you sure the padding equal 2 will be good?
We have decreased it from 6 to 1 - see: 2bdacc16ceb45cd25c0735a51be5a88d05347787
</blockquote></details>

It looks good in my opinion.
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/n7dVq_DIN5FuHKWVl92zWWnY/image.png)
___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-Molznrk3rmlsS8Qh28-:bh83r7) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
/rpma/tools/perf/lib/figure.py:300:19: C1801: Do not use `len(SEQUENCE)` to determine if a sequence is empty (len-as-condition)
```

See https://github.com/ldorau/rpma/runs/4239593859
</blockquote></details>

This is a bug in Pylint (https://github.com/PyCQA/pylint/issues/2684), fixed as of Pylint 2.4 (https://github.com/PyCQA/pylint/pull/2815)


<!-- Sent from Reviewable.io -->

2021-11-18 08:00 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 31 of 35 files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure.py, line 34 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiOG6g0FmdgoZsBhHi:-Mom2oPU-5Y23yfniYG6:bxt1q04) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L34)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It looks good in my opinion.
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/n7dVq_DIN5FuHKWVl92zWWnY/image.png)

</blockquote></details>

Sorry, wrong image ;)
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/8hcJMCnRu3KknkNnCFn6plWd/image.png)


<!-- Sent from Reviewable.io -->

2021-11-18 09:36 UTC, janekmi approved these changes
> Reviewed 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-18 09:44 UTC, ldorau requested changes
> Reviewed 14 of 29 files at r6, 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 34 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiOG6g0FmdgoZsBhHi:-MomQ-nLECg3cCtVLq3W:b-yxq3cr) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L34)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Sorry, wrong image ;)
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/8hcJMCnRu3KknkNnCFn6plWd/image.png)

</blockquote></details>

It has to be checked how it looks in the report, since the padding was decreased, because the distance between a text and a picture was too huge.
___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-MomOND50mXuoQILq3RX:b-g17zvu) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This is a bug in Pylint (https://github.com/PyCQA/pylint/issues/2684), fixed as of Pylint 2.4 (https://github.com/PyCQA/pylint/pull/2815)
</blockquote></details>

So we have to use a workaround here, because those builds should not fail.


<!-- Sent from Reviewable.io -->

2021-11-18 09:45 UTC, ldorau reviewed
> Reviewed 1 of 29 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-18 09:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-MomT2gd71mykhPpW8K9:bnihv9m) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So we have to use a workaround here, because those builds should not fail.
</blockquote></details>

So we have to use a workaround here, because those builds should not fail:
https://stackoverflow.com/questions/43121340/why-is-the-use-of-lensequence-in-condition-values-considered-incorrect-by-pyli

```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false.

Yes: if not seq:
     if seq:

No:  if len(seq):
     if not len(seq):
```


<!-- Sent from Reviewable.io -->

2021-11-18 11:11 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 33 of 35 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure.py, line 34 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiOG6g0FmdgoZsBhHi:-MomjKJK4Rx4BBM8UfMD:b-dlx033) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has to be checked how it looks in the report, since the padding was decreased, because the distance between a text and a picture was too huge.
</blockquote></details>

I've deleted this change.
___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-MomjVpd11IhniyR7zYg:b-16u5ko) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So we have to use a workaround here, because those builds should not fail:
https://stackoverflow.com/questions/43121340/why-is-the-use-of-lensequence-in-condition-values-considered-incorrect-by-pyli

```
For sequences, (strings, lists, tuples), use the fact that empty sequences are false.

Yes: if not seq:
     if seq:

No:  if len(seq):
     if not len(seq):
```

</blockquote></details>

I turned that check off.


<!-- Sent from Reviewable.io -->

2021-11-18 11:14 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-Momje2T03KXmerC3zSE:b-l49rfy) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I turned that check off.
</blockquote></details>

And I have submitted the issue: https://github.com/pmem/rpma/issues/1329

I will run again all our nightly builds now...


<!-- Sent from Reviewable.io -->

2021-11-18 11:20 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 291 at r18](https://reviewable.io/reviews/pmem/rpma/1319#-MomlUjvEyfyQ2tARr8d:-MomlUjw1VzuWDLzLi_R:b-6w0yzo) ([raw file](https://github.com/pmem/rpma/blob/244822311abc3e74425ff2d85b51e36c1cc3e401/tools/perf/lib/figure.py#L291)):*
> ```
> group_to_line_styles.keys():
> ```

There is another error here:
```
/rpma/tools/perf/lib/figure.py:291:24: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
```

See: https://github.com/ldorau/rpma/runs/4250502093?check_suite_focus=true


<!-- Sent from Reviewable.io -->

2021-11-18 12:18 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: 34 of 35 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-Momyz4j2_TMbefJjO5k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

And I have submitted the issue: https://github.com/pmem/rpma/issues/1329

I will run again all our nightly builds now...
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 291 at r18](https://reviewable.io/reviews/pmem/rpma/1319#-MomlUjvEyfyQ2tARr8d:-Momz-Ld3mAg31XmDstq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/244822311abc3e74425ff2d85b51e36c1cc3e401/tools/perf/lib/figure.py#L291)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> group_to_line_styles.keys():
> ```

There is another error here:
```
/rpma/tools/perf/lib/figure.py:291:24: C0201: Consider iterating the dictionary directly instead of calling .keys() (consider-iterating-dictionary)
```

See: https://github.com/ldorau/rpma/runs/4250502093?check_suite_focus=true
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-18 13:01 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-18 14:27 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 300 at r16](https://reviewable.io/reviews/pmem/rpma/1319#-MoiP80Q0HWQ268FOiQo:-MonRVc34p84qpg-NH1e:bgswke0) ([raw file](https://github.com/pmem/rpma/blob/e02a20870a847decdc7c8db895d899d7a12f0293/tools/perf/lib/figure.py#L300)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It is OK now


<!-- Sent from Reviewable.io -->

2021-11-18 14:27 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1319#-:-MonRZVv6baLR2WT5tj4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-18 14:28 UTC, merged