tools: running commands on remote node over SSH
pmem/rpma pull request #1339
Opened 2021-11-22 14:47 UTC by osalyk

2021-11-22 14:52 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-22 14:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp77hpP3PdI2UfHy6vQ:-Mp77hpP3PdI2UfHy6vR:by3aqio) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L12)):*
> ```
> side
> ```

node
___
*[tools/perf/lib/remote_cmd.py, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp78CkG1BP6YBqcqqkk:-Mp78CkG1BP6YBqcqqkl:b-s6tqub) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L29)):*
> ```
> RemoteCmd.run_async(
> ```

`cls.run_async(`


<!-- Sent from Reviewable.io -->

2021-11-22 15:05 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79NoH5r0bmtM4Gu28:-Mp79NoH5r0bmtM4Gu29:b64ey) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L39)):*
> ```
> username = None
> ```

It should be an error.
___
*[tools/perf/lib/remote_cmd.py, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79sIbDlPBKORspn6M:-Mp79sIbDlPBKORspn6N:b8lxiyd) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L47)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>             userpass = None
>         if 'key_filename' in config:
>             key_filename = config['key_filename']
>         else:
>             key_filename = None
> ```
</details>


`userpass` or `key_filename` should be set.


<!-- Sent from Reviewable.io -->

2021-11-22 16:32 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-22 17:29 UTC, haichangsi reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-23 07:23 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79NoH5r0bmtM4Gu28:-MpAfOD1A7s5EhVtqyrt:bnzmsbs) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> username = None
> ```

It should be an error.
</blockquote></details>

username (str) – the username to authenticate as (defaults to the current local username)
___
*[tools/perf/lib/remote_cmd.py, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79sIbDlPBKORspn6M:-MpAen4A0AiK10JAKT0d:bw2aeo5) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             userpass = None
>         if 'key_filename' in config:
>             key_filename = config['key_filename']
>         else:
>             key_filename = None
> ```

`userpass` or `key_filename` should be set.
</blockquote></details>

key_filename (str) – the filename, or list of filenames, of optional private key(s) and/or certs to try for authentication.
If we have the keys in the default location, we do not need to set this parameter.


<!-- Sent from Reviewable.io -->

2021-11-23 07:32 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79NoH5r0bmtM4Gu28:-MpAg1ihEuP75NeDwHw8:bhu5f7d) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L39)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

username (str) – the username to authenticate as (defaults to the current local username)
</blockquote></details>

Have you tried if it works?
___
*[tools/perf/lib/remote_cmd.py, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79sIbDlPBKORspn6M:-MpAgi9IAHxyDlvlPip1:bhu5f7d) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L47)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

key_filename (str) – the filename, or list of filenames, of optional private key(s) and/or certs to try for authentication.
If we have the keys in the default location, we do not need to set this parameter.
</blockquote></details>

Have you tried if it works?


<!-- Sent from Reviewable.io -->

2021-11-23 07:37 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79NoH5r0bmtM4Gu28:-MpAiY4r5ckCRhYzg-P8:bo8dl6a) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Have you tried if it works?
</blockquote></details>

It works
___
*[tools/perf/lib/remote_cmd.py, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79sIbDlPBKORspn6M:-MpAiaxm9zvfizcxwN59:bo8dl6a) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Have you tried if it works?
</blockquote></details>

It works


<!-- Sent from Reviewable.io -->

2021-11-23 07:42 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339#-:-MpAjpoSA6izv0miJMIN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79NoH5r0bmtM4Gu28:-MpAjcmJ3fVSoa0tUSvL:bhzz3gv) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L39)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It works
</blockquote></details>

Great! :-)
___
*[tools/perf/lib/remote_cmd.py, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1339#-Mp79sIbDlPBKORspn6M:-MpAjirbEB_PxM12nRMB:bhzz3gv) ([raw file](https://github.com/pmem/rpma/blob/f05970164c392e3158ac8fdf0c07affb906cf334/tools/perf/lib/remote_cmd.py#L47)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It works
</blockquote></details>

Great! :-)


<!-- Sent from Reviewable.io -->

2021-11-23 07:49 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1339#-MpAl81-83z10jWi3Xe3:-MpAl81-83z10jWi3Xe4:bqow18e) ([raw file](https://github.com/pmem/rpma/blob/bd898004b7c94ee7d43b97496c71197dfec29451/tools/perf/lib/remote_cmd.py#L9)):*
> ```
> paramiko
> ```

I suppose `paramiko`  should be added to the documentation and all Docker images, right ? 


<!-- Sent from Reviewable.io -->

2021-11-23 07:57 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1339#-MpAmjmM9a6-qXkSyDSo:-MpAmjmM9a6-qXkSyDSp:b-k6i75x) (no related file):*
Please add the `remote_cmd.py` file to `tools/perf/CMakeLists.txt` and fix all errors:
```
************* Module lib.remote_cmd
rpma/tools/perf/lib/remote_cmd.py:56:0: C0301: Line too long (98/80) (line-too-long)
rpma/tools/perf/lib/remote_cmd.py:58:0: C0301: Line too long (84/80) (line-too-long)
rpma/tools/perf/lib/remote_cmd.py:60:0: C0301: Line too long (91/80) (line-too-long)
rpma/tools/perf/lib/remote_cmd.py:9:0: E0401: Unable to import 'paramiko' (import-error)
rpma/tools/perf/lib/remote_cmd.py:29:8: C0103: Variable name "remoteCmd" doesn't conform to snake_case naming style (invalid-name) 
rpma/tools/perf/lib/remote_cmd.py:56:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
rpma/tools/perf/lib/remote_cmd.py:57:8: C0103: Variable name "sshException" doesn't conform to snake_case naming style (invalid-name)
rpma/tools/perf/lib/remote_cmd.py:58:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
rpma/tools/perf/lib/remote_cmd.py:59:8: C0103: Variable name "badHostKeyException" doesn't conform to snake_case naming style (invalid-name)
rpma/tools/perf/lib/remote_cmd.py:60:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)

-------------------------------------------------------------------
Your code has been rated at 9.77/10 (previous run: 10.00/10, -0.23)

```

---


<!-- Sent from Reviewable.io -->

2021-11-23 08:17 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1339#-MpAl81-83z10jWi3Xe3:-MpArGZw6Vpo2rSBWa1K:btrfdef) ([raw file](https://github.com/pmem/rpma/blob/bd898004b7c94ee7d43b97496c71197dfec29451/tools/perf/lib/remote_cmd.py#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> paramiko
> ```

I suppose `paramiko`  should be added to the documentation and all Docker images, right ? 
</blockquote></details>

Of course all changes in Docker images should go in a separate PR, which should be merged before this one, but changes in documentation should go in this PR.


<!-- Sent from Reviewable.io -->

2021-11-23 08:43 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1339#-MpAmjmM9a6-qXkSyDSo:-MpAvvu-A60idBOzZeOL:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the `remote_cmd.py` file to `tools/perf/CMakeLists.txt` and fix all errors:
```
************* Module lib.remote_cmd
rpma/tools/perf/lib/remote_cmd.py:56:0: C0301: Line too long (98/80) (line-too-long)
rpma/tools/perf/lib/remote_cmd.py:58:0: C0301: Line too long (84/80) (line-too-long)
rpma/tools/perf/lib/remote_cmd.py:60:0: C0301: Line too long (91/80) (line-too-long)
rpma/tools/perf/lib/remote_cmd.py:9:0: E0401: Unable to import 'paramiko' (import-error)
rpma/tools/perf/lib/remote_cmd.py:29:8: C0103: Variable name "remoteCmd" doesn't conform to snake_case naming style (invalid-name) 
rpma/tools/perf/lib/remote_cmd.py:56:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
rpma/tools/perf/lib/remote_cmd.py:57:8: C0103: Variable name "sshException" doesn't conform to snake_case naming style (invalid-name)
rpma/tools/perf/lib/remote_cmd.py:58:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)
rpma/tools/perf/lib/remote_cmd.py:59:8: C0103: Variable name "badHostKeyException" doesn't conform to snake_case naming style (invalid-name)
rpma/tools/perf/lib/remote_cmd.py:60:12: W0707: Consider explicitly re-raising using the 'from' keyword (raise-missing-from)

-------------------------------------------------------------------
Your code has been rated at 9.77/10 (previous run: 10.00/10, -0.23)

```

</blockquote></details>

Done.

---
___
*[tools/perf/lib/remote_cmd.py, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1339#-MpAl81-83z10jWi3Xe3:-MpAq8_p3KS0YEM1y23G:b43il45) ([raw file](https://github.com/pmem/rpma/blob/bd898004b7c94ee7d43b97496c71197dfec29451/tools/perf/lib/remote_cmd.py#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Of course all changes in Docker images should go in a separate PR, which should be merged before this one, but changes in documentation should go in this PR.
</blockquote></details>

Documentation done,
changes to the Docker images in a separate PR (#1340).


<!-- Sent from Reviewable.io -->

2021-11-23 09:38 UTC, ldorau requested changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/1339#-MpB93NR6fs1XIAOEuau:-MpB93NR6fs1XIAOEuav:b-h6bvh6) ([raw file](https://github.com/pmem/rpma/blob/9052611480e44e4d978d75589ea7eb3b4091f61a/tools/perf/lib/remote_cmd.py#L61)):*
> ```
> server's 
> ```

`the server's ...`
___
*[tools/perf/lib/remote_cmd.py, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/1339#-MpB9B-38_kM6qOxKlOP:-MpB9B-38_kM6qOxKlOQ:bmalbug) ([raw file](https://github.com/pmem/rpma/blob/9052611480e44e4d978d75589ea7eb3b4091f61a/tools/perf/lib/remote_cmd.py#L65)):*
> ```
> SSH connection
> ```

`the SSH connection`


<!-- Sent from Reviewable.io -->

2021-11-23 10:01 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/1339#-MpB93NR6fs1XIAOEuau:-MpBA4MI2_qum2NCTkGJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9052611480e44e4d978d75589ea7eb3b4091f61a/tools/perf/lib/remote_cmd.py#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> server's 
> ```

`the server's ...`
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/1339#-MpB9B-38_kM6qOxKlOP:-MpBAklu6kzKZyfAcsr4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9052611480e44e4d978d75589ea7eb3b4091f61a/tools/perf/lib/remote_cmd.py#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> SSH connection
> ```

`the SSH connection`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-23 10:06 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-23 12:26 UTC, Patryk717 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339#-:-MpBki-c1ob-v64hyq6Z:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-23 12:28 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-23 15:48 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 11 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/CMakeLists.txt, line 17 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCD5tK0M2SSxpu5Bf_:-MpCD5tK0M2SSxpu5Bfa:bgc7vqv) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/CMakeLists.txt#L17)):*
> ```CMake
> 	${CMAKE_CURRENT_SOURCE_DIR}/lib/bench.py
> 	${CMAKE_CURRENT_SOURCE_DIR}/lib/figure.py
> 	${CMAKE_CURRENT_SOURCE_DIR}/lib/remote_cmd.py
> ```

:heart: 
___
*[tools/perf/lib/remote_cmd.py, line 9 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCD_Zt00ntJpkoRHgt:-MpCD_Zt00ntJpkoRHgu:biapyi2) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L9)):*
> ```Python
> """remote_cmd.py -- running commands on remote node over SSH (EXPERIMENTAL)"""
> 
> import paramiko as p
> ```

I don't like so short mnemonics. Looking for a replacement. Anybody?
___
*[tools/perf/lib/remote_cmd.py, line 14 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCSjKhEIsg0A9HfF-V:-MpCSjKhEIsg0A9HfF-W:bw3yuyb) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L14)):*
> ```Python
>     """run a command on a remote node over SSH"""
> 
>     def __init__(self, ssh_client, stdout, stderr, exit_status):
> ```

`exit_status` is never used. Drop it.
___
*[tools/perf/lib/remote_cmd.py, line 23 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCTkzCByJDPkoLp197:-MpCTkzCByJDPkoLp198:b-zam8un) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L23)):*
> ```Python
>         """wait for the command to finish"""
>         self.exit_status = self.stdout.channel.recv_exit_status()
>         self.ssh_client.close()
> ```

Are you sure stdout and stdin are valid after closing the SSH client?
___
*[tools/perf/lib/remote_cmd.py, line 28 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCTI-u7Xp8U0qEy1Hq:-MpCTI-u7Xp8U0qEy1Hr:b-5ms2yl) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L28)):*
> ```Python
>     @classmethod
>     def run_sync(cls, config, cmd):
>         """run a remote command and return a control object"""
> ```

... and wait till it is done
___
*[tools/perf/lib/remote_cmd.py, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCDqVUCKm9QhgooiRk:-MpCDqVY7wdp6nWPiFrT:b-j0k42b) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L39)):*
> ```Python
>             username = config['REMOTE_USER']
>         else:
>             username = None
> ```

```python
username = config.get('REMOTE_USER', None)
```
___
*[tools/perf/lib/remote_cmd.py, line 43 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCE-359b1JUjksavbN:-MpCE-359b1JUjksavbO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L43)):*
> ```Python
>             userpass = config['REMOTE_PASS']
>         else:
>             userpass = None
> ```

.
___
*[tools/perf/lib/remote_cmd.py, line 51 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCExnv49JJm2p_XLZa:-MpCExnv49JJm2p_XLZb:boslrx) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L51)):*
> ```Python
>         try:
>             ssh_client = p.SSHClient()
>             ssh_client.set_missing_host_key_policy(p.AutoAddPolicy())
> ```

I think `WarningPolicy` is safer, so we won't modify the environment.

Ref: https://docs.paramiko.org/en/stable/api/client.html#paramiko.client.WarningPolicy
___
*[tools/perf/lib/remote_cmd.py, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCEEuAB6UM5oLKMbgL:-MpCEEuAB6UM5oLKMbgM:b-benxqk) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L54)):*
> ```Python
>             ssh_client.connect(hostname=config['server_ip'],
>                                username=username, password=userpass,
>                                key_filename=key_filename)
> ```

`key_filename` is needed in order to try the default keys from the default location `~/.ssh/`?
___
*[tools/perf/lib/remote_cmd.py, line 58 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCGhNq9kUAOrHmhwkJ:-MpCGhNq9kUAOrHmhwkK:b616ql6) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L58)):*
> ```Python
>             raise Exception(
>                 "Authentication failed, please verify your credentials: %s"
>                 %username) from None
> ```

We cannot handle this exception in any way. No point in covering its appearance. In my opinion, this `except` is not needed and misleading.

The one possible reason to have it is to add more information to the message but without covering it, so `from None` is not needed.
How looks the default message in this case?
___
*[tools/perf/lib/remote_cmd.py, line 62 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCJjtBCh5iL1v3fSti:-MpCJjtBCh5iL1v3fStj:b-ye2lpc) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L62)):*
> ```Python
>             raise Exception(
>                 "Unable to verify the server's host key: %s"
>                 % host_key_exception) from host_key_exception
> ```

Same here. Do we add anything to the default message?
___
*[tools/perf/lib/remote_cmd.py, line 66 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCJrz_ASKEmQUHct0C:-MpCJrz_ASKEmQUHct0D:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L66)):*
> ```Python
>             raise Exception(
>                 "Unable to establish the SSH connection: %s"
>                 % ssh_exception) from ssh_exception
> ```

.


<!-- Sent from Reviewable.io -->

2021-11-23 16:09 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCYM3Y6Ij8yHwI7kWr:-MpCYM3Y6Ij8yHwI7kWs:bdnvgp6) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L68)):*
> ```Python
>                 % ssh_exception) from ssh_exception
> 
>         _, stdout, stderr = ssh_client.exec_command(cmd)
> ```

I believe we need also make use of the `environment` argument of the `exec_command()` command. ;-)


<!-- Sent from Reviewable.io -->

2021-11-24 07:49 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 9 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCD_Zt00ntJpkoRHgt:-MpFuI1q2N9qbMWI8Co0:b-m6uhmk) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like so short mnemonics. Looking for a replacement. Anybody?
</blockquote></details>

para ?


<!-- Sent from Reviewable.io -->

2021-11-24 09:42 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 14 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCSjKhEIsg0A9HfF-V:-MpFw4O84pAGMFfwMTCc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`exit_status` is never used. Drop it.
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 23 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCTkzCByJDPkoLp197:-MpGIP9m1vyjWp11pBBs:b2kmqne) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Are you sure stdout and stdin are valid after closing the SSH client?
</blockquote></details>

Yes, empirically tested.
___
*[tools/perf/lib/remote_cmd.py, line 28 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCTI-u7Xp8U0qEy1Hq:-MpG0_FV7Kvh8uN5xErS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... and wait till it is done
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCDqVUCKm9QhgooiRk:-MpG0m1jC3DfMw1GrkfE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
username = config.get('REMOTE_USER', None)
```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 43 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCE-359b1JUjksavbN:-MpG0mWYBRhZn93BSkDR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 51 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCExnv49JJm2p_XLZa:-MpG1fl94sUYwb0YdD8Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think `WarningPolicy` is safer, so we won't modify the environment.

Ref: https://docs.paramiko.org/en/stable/api/client.html#paramiko.client.WarningPolicy
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCEEuAB6UM5oLKMbgL:-MpG1735AUJ6l1lyFFpk:b2nhky0) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`key_filename` is needed in order to try the default keys from the default location `~/.ssh/`?
</blockquote></details>

No.
___
*[tools/perf/lib/remote_cmd.py, line 58 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCGhNq9kUAOrHmhwkJ:-MpGIQcw1mJHX8Sj5SAE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We cannot handle this exception in any way. No point in covering its appearance. In my opinion, this `except` is not needed and misleading.

The one possible reason to have it is to add more information to the message but without covering it, so `from None` is not needed.
How looks the default message in this case?
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 62 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCJjtBCh5iL1v3fSti:-MpGIR6W1JTvCEMVp3uO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. Do we add anything to the default message?
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 66 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCJrz_ASKEmQUHct0C:-MpGIRe56gPjwxqU6EfB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCYM3Y6Ij8yHwI7kWr:-MpG8RzG2_z28_uO-LYh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe we need also make use of the `environment` argument of the `exec_command()` command. ;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-24 10:00 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-24 10:09 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1339#-MpGPe4e9qLNI8FGXkqP:-MpGPe4fDh7nWlaATGff:bh97yru) (no related file):*
Is it correct usage of this module? Do I understand it correctly?

```
server = remote_cmd.run_async(config, cmd_server, env)
client = remote_cmd.run_sync(config, cmd_client, env)
server.wait()
```

---
___
*[tools/perf/lib/remote_cmd.py, line 31 at r6](https://reviewable.io/reviews/pmem/rpma/1339#-MpGNOkL5CcHQpIGMuf8:-MpGNOkL5CcHQpIGMuf9:b368m27) ([raw file](https://github.com/pmem/rpma/blob/fed6d5e7859008539663cb457680255c8e800a8a/tools/perf/lib/remote_cmd.py#L31)):*
> ```
> return remote_cmd
> ```

What can `remote_cmd` be used for later? What is it needed for?


<!-- Sent from Reviewable.io -->

2021-11-24 10:14 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1339#-MpGPe4e9qLNI8FGXkqP:-MpGR-2IBnQ-jfWAPlPP:bnssgvj) (no related file):*
> Is it correct usage of this module? Do I understand it correctly?
That's the idea

---
___
*[tools/perf/lib/remote_cmd.py, line 31 at r6](https://reviewable.io/reviews/pmem/rpma/1339#-MpGNOkL5CcHQpIGMuf8:-MpGQn4L1dEbLINkKmhU:b-azfdwf) ([raw file](https://github.com/pmem/rpma/blob/fed6d5e7859008539663cb457680255c8e800a8a/tools/perf/lib/remote_cmd.py#L31)):*
> What can remote_cmd be used for later? What is it needed for?
To read stdout and stderr.


<!-- Sent from Reviewable.io -->

2021-11-24 10:15 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1339#-MpGPe4e9qLNI8FGXkqP:-MpGRIaK8pd9dOkbAIUF:b32wtd) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

> Is it correct usage of this module? Do I understand it correctly?
That's the idea
</blockquote></details>

ok

---


<!-- Sent from Reviewable.io -->

2021-11-24 10:19 UTC, haichangsi reviewed
<img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339#-:-MpGSAB53KFnhLfpXx2o:b-uwkowd)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-24 10:38 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-24 10:44 UTC, janekmi approved these changes
:goat: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339#-:-MpGXrwK9bqVldFfTGFA:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 51 at r5](https://reviewable.io/reviews/pmem/rpma/1339#-MpCExnv49JJm2p_XLZa:-MpGU5Gh1L3WSC0pPi3b:bycue13) ([raw file](https://github.com/pmem/rpma/blob/0d2027a41a1dc5070908772d946015fbd9f09374/tools/perf/lib/remote_cmd.py#L51)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

W have agreed offline `RejectPolicy` is even more rational. Done.
___
*[tools/perf/lib/remote_cmd.py, line 42 at r6](https://reviewable.io/reviews/pmem/rpma/1339#-MpGV0IZ7yhP15az7Lcs:-MpGV0IZ7yhP15az7Lct:bijof6q) ([raw file](https://github.com/pmem/rpma/blob/fed6d5e7859008539663cb457680255c8e800a8a/tools/perf/lib/remote_cmd.py#L42)):*
> ```Python
>         ssh_client.set_missing_host_key_policy(para.RejectPolicy())
>         ssh_client.connect(hostname=config['server_ip'], username=username,
>                            password=userpass)
> ```

You can use dict unpacking in order to provide a set of named arguments to a function call instead of writing `a=a, b=b, c=c`.

```python
kwargs['username'] = config.get('REMOTE_USER', None)
kwargs['password'] = config.get('REMOTE_PASS', None)

# ...

ssh_client.connect(hostname=config['server_ip'], **kwargs)
```


<!-- Sent from Reviewable.io -->

2021-11-24 10:44 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-24 11:06 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 42 at r6](https://reviewable.io/reviews/pmem/rpma/1339#-MpGV0IZ7yhP15az7Lcs:-MpGbmJH8_e9W09zvepS:b-uxvmcp) ([raw file](https://github.com/pmem/rpma/blob/fed6d5e7859008539663cb457680255c8e800a8a/tools/perf/lib/remote_cmd.py#L42)):*
> You can use dict unpacking in order to provide a set of named arguments to a function call instead of writing a=a, b=b, c=c.
Done.


<!-- Sent from Reviewable.io -->

2021-11-24 11:28 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-24 12:09 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-25 14:10 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339#-:-MpMQgyEDowXPTU0xcdn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-25 14:36 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1339)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-11-25 14:37 UTC, merged