tools: ib_read.py, SETTINGS_BY_MODE filled up
pmem/rpma pull request #1360
Opened 2021-11-26 21:32 UTC by haichangsi

2021-11-26 21:33 UTC, haichangsi reviewed
There is no default value here. I don't know if there is a try catch somewhere else to check potentially occurring KeyError. I found defaultdict imported from collections but it adds every key that doesn't exist in the dict so it has no sense to use it here

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360#-:-MpT9bnHAO7jMIW1Il0t:b-awm70z)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-28 01:21 UTC, janekmi requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ53-Z7UMRdtejdGmG:-MpZ53-Z7UMRdtejdGmH:b2a1x47) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L138)):*
> ```Python
>             },
>             'args': ['--perform_warm_up']},
> ```

TBH the formatting of these dicts you have proposed here looks somewhat odd to me. I mean:

```python
    'a': {
        'b': 'c'},

    'd': {
        # ...
```

I would rather expect something like:

```python
    'a': {
        'b': 'c'
    },
    'd': {
        # ...
```

But I'm always open to discussion. :-)

As for arguments, I do accept: documented experiences, references showing it is a viable way of doing things, style guides and well build pros vs cons lists.


<!-- Sent from Reviewable.io -->

2021-11-28 01:33 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ8DnkDhySGfGO04sZ:-MpZ8DnkDhySGfGO04s_:bn43dvp) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L187)):*
> ```Python
>                 128: 100000000
>             },
>             'args': ['--report_gbits']},
> ```

I really, really don't like maintaining duplicates. When we know cases for both `bw-dp-lin` and `bw-dp-exp` are exactly the same you can reuse a single definition e.g.

```python
BW_DP_SETTINGS = {
    # ...
}
SETTINGS_BY_MODE = {
    # ...
    'bw_dp_lin': BW_DP_SETTINGS,
    'bw_dp_exp': BW_DP_SETTINGS,
    # ...
}
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ97941s3EPGFYm3nL:-MpZ97941s3EPGFYm3nM:b-z0xmln) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L192)):*
> ```Python
>             'ib_tool': 'ib_read_bw',
>             'threads': 1,
>             'bs': [256, 1024, 4096, 8192, 16384, 32768, 65536, 131072, 262144],
> ```

Please use the `BS_VALUES` instead.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ9a9ABGTfMf97-4db:-MpZ9a9ABGTfMf97-4dc:b-mv372b) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L205)):*
> ```Python
>                 262144: 2600000
>             },
>             'args': ['--report_gbits']},
> ```

Thinking out loud. @ldorau doesn't you think `--report_gbits` should be a part of your #1351?
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 207 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ9zYLCOQ2rEA6tAvy:-MpZ9zYLCOQ2rEA6tAvz:byazzr1) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L207)):*
> ```Python
>             'args': ['--report_gbits']},
>     }
>     # XXX TBD
> ```

Along with providing all these definitions, this comment should be removed.


<!-- Sent from Reviewable.io -->

2021-11-28 01:34 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpZADs43lEY5j5WG_Ba:-MpZADs5-0JSd-J9AVB8:bner4si) (no related file):*
> There is no default value here. I don't know if there is a try catch somewhere else to check potentially occurring KeyError. I found defaultdict imported from collections but it adds every key that doesn't exist in the dict so it has no sense to use it here

You fear getting a value of which key may end up with KeyError?

---


<!-- Sent from Reviewable.io -->

2021-11-29 08:42 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpepXw3Bz_jBzDlfHsN:-MpepXw4Drl5D6CReMns:bmzqe6w) (no related file):*
Please fix all errors in builds:
https://github.com/pmem/rpma/runs/4337809432?check_suite_focus=true
```
************* Module lib.benchmark.runner.ib_read
C:141, 0: No space allowed before comma
            'threads': [1, 2, 4, 8 ,12],
                                   ^ (bad-whitespace)
C:141, 0: Exactly one space required after comma
            'threads': [1, 2, 4, 8 ,12],
                                   ^ (bad-whitespace)
```

---
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ53-Z7UMRdtejdGmG:-MpepjKg8m3WXaT5UaeJ:b32v57) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L138)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH the formatting of these dicts you have proposed here looks somewhat odd to me. I mean:

```python
    'a': {
        'b': 'c'},

    'd': {
        # ...
```

I would rather expect something like:

```python
    'a': {
        'b': 'c'
    },
    'd': {
        # ...
```

But I'm always open to discussion. :-)

As for arguments, I do accept: documented experiences, references showing it is a viable way of doing things, style guides and well build pros vs cons lists.
</blockquote></details>

+1
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ8DnkDhySGfGO04sZ:-MpepqY4ECl5Wqwmq23k:b32v57) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I really, really don't like maintaining duplicates. When we know cases for both `bw-dp-lin` and `bw-dp-exp` are exactly the same you can reuse a single definition e.g.

```python
BW_DP_SETTINGS = {
    # ...
}
SETTINGS_BY_MODE = {
    # ...
    'bw_dp_lin': BW_DP_SETTINGS,
    'bw_dp_exp': BW_DP_SETTINGS,
    # ...
}
```
</blockquote></details>

+1
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ97941s3EPGFYm3nL:-Mpepw-b7cm2S3E9K7j8:b32v57) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use the `BS_VALUES` instead.
</blockquote></details>

+1
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ9a9ABGTfMf97-4db:-MpeqRpM5_lxHqKPEs7P:b-q92674) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L205)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Thinking out loud. @ldorau doesn't you think `--report_gbits` should be a part of your #1351?
</blockquote></details>

Right, since `--perform_warm_up` is used only in case of `lat` and `--report_gbits` only in case of `bw` I will incorporate it into #1351 .

@haichangsi Please remove all `'args'` - from `lat` too.


<!-- Sent from Reviewable.io -->

2021-11-29 08:44 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpZADs43lEY5j5WG_Ba:-MperFk24gREUpUjqfMo:b-5x818f) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> There is no default value here. I don't know if there is a try catch somewhere else to check potentially occurring KeyError. I found defaultdict imported from collections but it adds every key that doesn't exist in the dict so it has no sense to use it here

You fear getting a value of which key may end up with KeyError?
</blockquote></details>

@haichangsi  We do not have to prevent this error

---


<!-- Sent from Reviewable.io -->

2021-11-29 13:03 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @haichangsi, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpepXw3Bz_jBzDlfHsN:-MpfmaUZ0QFiYHHPsINj:b-avrs1x) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix all errors in builds:
https://github.com/pmem/rpma/runs/4337809432?check_suite_focus=true
```
************* Module lib.benchmark.runner.ib_read
C:141, 0: No space allowed before comma
            'threads': [1, 2, 4, 8 ,12],
                                   ^ (bad-whitespace)
C:141, 0: Exactly one space required after comma
            'threads': [1, 2, 4, 8 ,12],
                                   ^ (bad-whitespace)
```

</blockquote></details>

One issue left:
```
************* Module lib.benchmark.runner.ib_read
/rpma/tools/perf/lib/benchmark/runner/ib_read.py:207:0: C0303: Trailing whitespace (trailing-whitespace)
```

---


<!-- Sent from Reviewable.io -->

2021-11-29 13:06 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpZADs43lEY5j5WG_Ba:-MpfevmPDyjb4_Ur49Ga:b32wtd) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi  We do not have to prevent this error
</blockquote></details>

ok

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpepXw3Bz_jBzDlfHsN:-MpfnLV_Ec_uTPavAj7j:b-teqagj) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

One issue left:
```
************* Module lib.benchmark.runner.ib_read
/rpma/tools/perf/lib/benchmark/runner/ib_read.py:207:0: C0303: Trailing whitespace (trailing-whitespace)
```
</blockquote></details>

I saw that, already changed it

---
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ53-Z7UMRdtejdGmG:-MpffA_B4Ih9z9gaWGMy:b-wjgmju) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L138)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

I 100% agree with you. 'lat' was already done by somebody and he/she did this kinda formatting so I tried to follow this way of formatting. Changed.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ8DnkDhySGfGO04sZ:-MpfhF_r0Q0mmEkihrO3:b-azphtq) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L187)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Most of the lines are not the same, iterations and iodepth are different so we will stick with this version as we discussed today
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ97941s3EPGFYm3nL:-MpfirxBA8Eq7KUInySJ:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L192)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ9a9ABGTfMf97-4db:-Mpfiu-X3WfSSZs8Ff0h:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L205)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right, since `--perform_warm_up` is used only in case of `lat` and `--report_gbits` only in case of `bw` I will incorporate it into #1351 .

@haichangsi Please remove all `'args'` - from `lat` too.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 207 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ9zYLCOQ2rEA6tAvy:-Mpfiv9e58qpIgIAXDWs:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L207)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Along with providing all these definitions, this comment should be removed.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-11-29 13:07 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 137 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnOUn1k-shITMw5tH:-MpfnOUn1k-shITMw5tI:b-rpr84d) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L137)):*
> ```
>         },
> 
>         'bw-th': {
> ```

Please remove all empty line in-between.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnVwr0SEMWFFnSQYJ:-MpfnVwr0SEMWFFnSQYK:b-us90s7) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L153)):*
> ```
>         },
> 
>         'bw-dp-lin': {
> ```

.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 172 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnZdo9wVqKyiI2fw6:-MpfnZdo9wVqKyiI2fw7:buf9lfh) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L172)):*
> ```
>         },
> 
>         'bw-dp-exp': {
> ```

.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 189 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfncOYBdtUGwu_GqKV:-MpfncOYBdtUGwu_GqKW:bw8ad7s) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L189)):*
> ```
>         },
> 
>         'bw-bs': {
> ```

.


<!-- Sent from Reviewable.io -->

2021-11-29 13:09 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 206 at r3](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnsAt-Niz4pqaFVi_:-MpfnsAu9pQaPNNWDWNS:b-ynqod0) ([raw file](https://github.com/pmem/rpma/blob/f1c5deeb7d6b7a08787c1ecc66898ab2c5a247e0/tools/perf/lib/benchmark/runner/ib_read.py#L206)):*
> ```
>     }
> ```

'\n' is missing here


<!-- Sent from Reviewable.io -->

2021-11-29 13:10 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-29 13:12 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 206 at r3](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnsAt-Niz4pqaFVi_:-Mpfoji9CIvJNyY4ubF8:b-2ics7) ([raw file](https://github.com/pmem/rpma/blob/f1c5deeb7d6b7a08787c1ecc66898ab2c5a247e0/tools/perf/lib/benchmark/runner/ib_read.py#L206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     }
> ```

'\n' is missing here
</blockquote></details>

```
************* Module lib.benchmark.runner.ib_read
rpma/tools/perf/lib/benchmark/runner/ib_read.py:202:0: C0304: Final newline missing (missing-final-newline)

```


<!-- Sent from Reviewable.io -->

2021-11-29 13:19 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 206 at r3](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnsAt-Niz4pqaFVi_:-MpfqLtpANpqcoOEXWYc:b1429zc) ([raw file](https://github.com/pmem/rpma/blob/f1c5deeb7d6b7a08787c1ecc66898ab2c5a247e0/tools/perf/lib/benchmark/runner/ib_read.py#L206)):*
> ```
> ·····
> ```

The last line has to be empty.


<!-- Sent from Reviewable.io -->

2021-11-29 13:21 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 137 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnOUn1k-shITMw5tH:-MpfpTLkEP-uCnOQ79h0:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         },
> 
>         'bw-th': {
> ```

Please remove all empty line in-between.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnVwr0SEMWFFnSQYJ:-MpfpUNy-EJ6F6hPt7hn:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         },
> 
>         'bw-dp-lin': {
> ```

.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 172 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnZdo9wVqKyiI2fw6:-MpfqXTn9Z9bFecDdSZ1:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L172)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         },
> 
>         'bw-dp-exp': {
> ```

.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 189 at r2](https://reviewable.io/reviews/pmem/rpma/1360#-MpfncOYBdtUGwu_GqKV:-MpfqB-RBUcS01YMWt9E:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/c6937703dc4c234b6d1ca344f1a5e36de38df068/tools/perf/lib/benchmark/runner/ib_read.py#L189)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         },
> 
>         'bw-bs': {
> ```

.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 206 at r3](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnsAt-Niz4pqaFVi_:-MpfqDuu332fuxf4KmHT:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/f1c5deeb7d6b7a08787c1ecc66898ab2c5a247e0/tools/perf/lib/benchmark/runner/ib_read.py#L206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
************* Module lib.benchmark.runner.ib_read
rpma/tools/perf/lib/benchmark/runner/ib_read.py:202:0: C0304: Final newline missing (missing-final-newline)

```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-11-29 13:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 206 at r3](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnsAt-Niz4pqaFVi_:-MpfrFYJ624VhWiBBJZj:b-z5asu4) ([raw file](https://github.com/pmem/rpma/blob/f1c5deeb7d6b7a08787c1ecc66898ab2c5a247e0/tools/perf/lib/benchmark/runner/ib_read.py#L206)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

done
</blockquote></details>

The last line is not empty still.


<!-- Sent from Reviewable.io -->

2021-11-29 13:47 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360#-:-MpfwmFUBdhbkIXrIkQm:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-29 13:48 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 206 at r3](https://reviewable.io/reviews/pmem/rpma/1360#-MpfnsAt-Niz4pqaFVi_:-MpfwxIR30JAl5HNdS6h:bhj0brm) ([raw file](https://github.com/pmem/rpma/blob/f1c5deeb7d6b7a08787c1ecc66898ab2c5a247e0/tools/perf/lib/benchmark/runner/ib_read.py#L206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The last line is not empty still.
</blockquote></details>

now it is done


<!-- Sent from Reviewable.io -->

2021-11-29 13:48 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-29 13:55 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ53-Z7UMRdtejdGmG:-MpfybIU96u84VDIfw5B:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L138)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I 100% agree with you. 'lat' was already done by somebody and he/she did this kinda formatting so I tried to follow this way of formatting. Changed.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/1360#-MpZ8DnkDhySGfGO04sZ:-MpfycktD-pvwvLE2kJ1:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/2f5da9ddfe668aa01c6e52179d50020f39c5bf08/tools/perf/lib/benchmark/runner/ib_read.py#L187)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Most of the lines are not the same, iterations and iodepth are different so we will stick with this version as we discussed today
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-11-29 14:14 UTC, janekmi requested changes
:goat:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360#-:-Mpg1vLi-dJDSYKdRocA:bnd2vnu)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 125 at r6](https://reviewable.io/reviews/pmem/rpma/1360#-Mpg1PYl3mSJalicQVz9:-Mpg1PYl3mSJalicQVzA:b2bocdn) ([raw file](https://github.com/pmem/rpma/blob/0c4c6c459021bb37f0700258844c6b7f5c14865f/tools/perf/lib/benchmark/runner/ib_read.py#L125)):*
> ```Python
>             'bs': BS_VALUES,
>             'iodepth': 1,
>             # values measured empirically, so that duration was ~60s
> ```

This comment should be copied before each and every `iterations`. We introduce here a lot of magic numbers. We have to explain them.


<!-- Sent from Reviewable.io -->

2021-11-29 15:26 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 125 at r6](https://reviewable.io/reviews/pmem/rpma/1360#-Mpg1PYl3mSJalicQVz9:-MpgISCYAsgGF_36sIsi:b32v57) ([raw file](https://github.com/pmem/rpma/blob/0c4c6c459021bb37f0700258844c6b7f5c14865f/tools/perf/lib/benchmark/runner/ib_read.py#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment should be copied before each and every `iterations`. We introduce here a lot of magic numbers. We have to explain them.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-11-29 16:12 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpgSvSSCCj1EpH3QvY_:-MpgSvST7M9bUwbt3vzZ:b4jd6kk) (no related file):*
@haichangsi Please rebase - master has been updated and there is a conflict.

---


<!-- Sent from Reviewable.io -->

2021-11-29 16:13 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2021-11-29 21:31 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 155 at r7](https://reviewable.io/reviews/pmem/rpma/1360#-MphawlPDiYNHnI3I_rt:-MphawlPDiYNHnI3I_ru:b-9bez8u) ([raw file](https://github.com/pmem/rpma/blob/3c19b2132652bbaa42d0a6d2bffd6512598af22a/tools/perf/lib/benchmark/runner/ib_read.py#L155)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> <<<<<<< HEAD
>             }
>         }
> ||||||| parent of 0c4c6c4... tools: ib_read.py, SETTINGS_BY_MODE filled up
>             },
>             'args': ['--perform_warm_up']}
> =======
> ```
</details>


Merge conflict committed.


<!-- Sent from Reviewable.io -->

2021-11-29 21:31 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 226 at r7](https://reviewable.io/reviews/pmem/rpma/1360#-Mphb4V5CJGwZlx99CF-:-Mphb4V5CJGwZlx99CF0:b-87m7ew) ([raw file](https://github.com/pmem/rpma/blob/3c19b2132652bbaa42d0a6d2bffd6512598af22a/tools/perf/lib/benchmark/runner/ib_read.py#L226)):*
> ```
> >>>>>>> 0c4c6c4... tools: ib_read.py, SETTINGS_BY_MODE filled up
> ```


Merge conflict committed.


<!-- Sent from Reviewable.io -->

2021-11-29 21:32 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2021-11-29 21:51 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1360#-MpgSvSSCCj1EpH3QvY_:-MphfKuEC9-OjLqGOjpX:b-gab63y) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi Please rebase - master has been updated and there is a conflict.
</blockquote></details>

done, I hope so 

---
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 125 at r6](https://reviewable.io/reviews/pmem/rpma/1360#-Mpg1PYl3mSJalicQVz9:-MphfQTa24U588S3fmO5:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/0c4c6c459021bb37f0700258844c6b7f5c14865f/tools/perf/lib/benchmark/runner/ib_read.py#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 155 at r7](https://reviewable.io/reviews/pmem/rpma/1360#-MphawlPDiYNHnI3I_rt:-MphfRP16EJuhQP0yRss:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/3c19b2132652bbaa42d0a6d2bffd6512598af22a/tools/perf/lib/benchmark/runner/ib_read.py#L155)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> <<<<<<< HEAD
>             }
>         }
> ||||||| parent of 0c4c6c4... tools: ib_read.py, SETTINGS_BY_MODE filled up
>             },
>             'args': ['--perform_warm_up']}
> =======
> ```

Merge conflict committed.
</blockquote></details>

done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 226 at r7](https://reviewable.io/reviews/pmem/rpma/1360#-Mphb4V5CJGwZlx99CF-:-MphfGODBlBHOX1Kov2f:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/3c19b2132652bbaa42d0a6d2bffd6512598af22a/tools/perf/lib/benchmark/runner/ib_read.py#L226)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> >>>>>>> 0c4c6c4... tools: ib_read.py, SETTINGS_BY_MODE filled up
> ```


Merge conflict committed.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-11-29 22:18 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 122 at r8](https://reviewable.io/reviews/pmem/rpma/1360#-MphlPAk5DYob11iESDL:-MphlPAlBkTa1QDYRpVI:by7br9a) ([raw file](https://github.com/pmem/rpma/blob/fedf5686feb68db2ca9ce9b6c577252262a6ac19/tools/perf/lib/benchmark/runner/ib_read.py#L122)):*
> ```Python
>                 raise NotImplementedError(
>                     "settings['iterations'][{}] is missing".format(x_value))
>             settings['args'] = self.__common_args(settings)
> ```

You have reverted @ldorau change with your PR. ;-)
Try again. I know it is tricky doing it for the first time.
If the issue will remain ask any of us for support. :crossed_fingers: 


<!-- Sent from Reviewable.io -->

2021-11-30 08:33 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360#-:-MpjyZY9AyBUsYrOOaJ1:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-30 08:38 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2021-11-30 08:38 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1360#-:-Mpjzdjs7XYQZn6h1aB7:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2021-11-30 08:43 UTC, merged