tools: perf: document the lib.bench module
pmem/rpma pull request #1361
Opened 2021-11-29 09:02 UTC by janekmi

I highly recommend generating HTML documentation. It is a lot more functional and better looking comparing to the PDF I have attached below.

[lib.bench API documentation.pdf](https://github.com/pmem/rpma/files/7616881/lib.bench.API.documentation.pdf)

2021-11-29 12:53 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-29 13:43 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1361#-MpfvVg57vsl6qmZdef7:-MpfvVg57vsl6qmZdef8:b-7mv650) (no related file):*
What will be the main documentation entry? 
Bench or Requirements or Figure?
The main documentation entry shall have high-level introduction of all elements.
Every documentation entry shall refer to the main documentation entry.

---
___
*[tools/perf/lib/bench.py, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1361#-MpfugFbAamF3zN_3XM2:-MpfugFc6axSfjSGXVUJ:b-xfcfcy) ([raw file](https://github.com/pmem/rpma/blob/521617eb21438431611da32991ceceb0abfce932/tools/perf/lib/bench.py#L32)):*
> ```
> part
> ```
the part definition will be very helpful here (or as some kind of reference)
___
*[tools/perf/lib/bench.py, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1361#-MpfvExZ1GJdAwi0He3-:-MpfvExZ1GJdAwi0He30:b-txoag4) ([raw file](https://github.com/pmem/rpma/blob/521617eb21438431611da32991ceceb0abfce932/tools/perf/lib/bench.py#L37)):*
> ```
> requirements
> ```
a requirement example will help a lot
___
*[tools/perf/lib/bench.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1361#-Mpfutbz94VotrModdTd:-Mpfutbz94VotrModdTe:b-cj09lg) ([raw file](https://github.com/pmem/rpma/blob/521617eb21438431611da32991ceceb0abfce932/tools/perf/lib/bench.py#L39)):*
> ```
> series
> ```


<!-- Sent from Reviewable.io -->

2021-11-29 15:12 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1361#-MpfvVg57vsl6qmZdef7:-MpgF7oj5TbdC_susTFg:b-ts63i6) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What will be the main documentation entry? 
Bench or Requirements or Figure?
The main documentation entry shall have high-level introduction of all elements.
Every documentation entry shall refer to the main documentation entry.
</blockquote></details>

I proposed to document the core ideas in the `lib` module docstring.

---
___
*[tools/perf/lib/bench.py, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1361#-MpfugFbAamF3zN_3XM2:-MpgDXH2BZoRlD2_Dw-T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/521617eb21438431611da32991ceceb0abfce932/tools/perf/lib/bench.py#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> part
> ```
the part definition will be very helpful here (or as some kind of reference)
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1361#-MpfvExZ1GJdAwi0He3-:-MpgEOSO3jH1dMH2HnY2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/521617eb21438431611da32991ceceb0abfce932/tools/perf/lib/bench.py#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> requirements
> ```
a requirement example will help a lot
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1361#-Mpfutbz94VotrModdTd:-MpgEd6P97s8mL2DCYWc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/521617eb21438431611da32991ceceb0abfce932/tools/perf/lib/bench.py#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> series
> ```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 15:24 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-29 16:41 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/__init__.py, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/1361#-MpgXb1r4xZNKWa2B3SU:-MpgXb1r4xZNKWa2B3SV:b-1mjdq6) ([raw file](https://github.com/pmem/rpma/blob/d188c7413df45df22ce5bac4dba06319cb724e52/tools/perf/lib/__init__.py#L19)):*
> ```
> Tou 
> ```
You


<!-- Sent from Reviewable.io -->

2021-11-29 16:51 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1361#-MpgTO_R1hYkg_gKnqeN:-MpgaX0m20ph6rsLR3Mz:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[tools/perf/lib/__init__.py, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/1361#-MpgXb1r4xZNKWa2B3SU:-Mpgag4y5RDYJqC9HhAu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d188c7413df45df22ce5bac4dba06319cb724e52/tools/perf/lib/__init__.py#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Tou 
> ```
You
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-29 17:05 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/__init__.py, line 49 at r3](https://reviewable.io/reviews/pmem/rpma/1361#-Mpg_Qk22FGI6qlAHO7u:-Mpg_Qk22FGI6qlAHO7v:b-7vxnts) ([raw file](https://github.com/pmem/rpma/blob/d188c7413df45df22ce5bac4dba06319cb724e52/tools/perf/lib/__init__.py#L49)):*
> ```
> `report_create` to generate a report including your custom part. It will end up
> with an error.
> ```
What shall be used instead?


<!-- Sent from Reviewable.io -->

2021-11-29 17:07 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1361#-MpfvVg57vsl6qmZdef7:-MpgeHnV3cwOR0PclN5w:b9m9vt8) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I proposed to document the core ideas in the `lib` module docstring.
</blockquote></details>

Shall we then point to this location from report_bench.py, report_figures.py, report_create.py?

---


<!-- Sent from Reviewable.io -->

2021-11-29 17:18 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/bench.py, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfC8b52VzE_1YBbqV:-MpgfC8b52VzE_1YBbqW:bkmtxk5) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L31)):*
> ```
> Bench.config
> ```
config
___
*[tools/perf/lib/bench.py, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfFvN2sqyoHaUhv1d:-MpgfFvN2sqyoHaUhv1e:bp4mtq1) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L32)):*
> ```
> Bench.parts
> ```
parts
___
*[tools/perf/lib/bench.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfLrA7ZJ49a3Bhf1f:-MpgfLrA7ZJ49a3Bhf1g:bm0gdva) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L35)):*
> ```
> Bench.figures
> ```
.
___
*[tools/perf/lib/bench.py, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfQiE-gdCuBorR4UW:-MpgfQiE-gdCuBorR4UX:b-pdojd3) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L39)):*
> ```
> Bench.requirements
> ```
.
___
*[tools/perf/lib/bench.py, line 45 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfT3e6AJ2ZHj2DqI6:-MpgfT3e6AJ2ZHj2DqI7:bvrppn8) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L45)):*
> ```
> Bench.result_dir
> ```
.
___
*[tools/perf/lib/bench.py, line 48 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpggXES5P_WAkoimpgM:-MpggXES5P_WAkoimpgN:bk89cpx) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L48)):*
> ```
> its `Bench.run()`
> ```
`run()`
___
*[tools/perf/lib/bench.py, line 116 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpggDXL9Nsi_Clf4kOs:-MpggDXL9Nsi_Clf4kOt:b-yn3d3y) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L116)):*
> ```
> all
> ```
all defined / all specified


<!-- Sent from Reviewable.io -->

2021-11-29 17:24 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 1 of 5 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/bench.py, line 138 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-Mpghrxj9chhv8RjIldH:-Mpghrxk9z729AICUkXz:b-6txl2v) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L138)):*
> ```
> bench
> ```
cache
___
*[tools/perf/lib/bench.py, line 140 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpghuVM4YOegIs8Ckhv:-MpghuVM4YOegIs8Ckhw:b-qsz6x7) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L140)):*
> ```
> bench
> ```
.
___
*[tools/perf/lib/bench.py, line 171 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgiGuL9mbJA9YarD09:-MpgiGuL9mbJA9YarD0A:b-aywgkb) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L171)):*
> ```
> bench.json
> ```
cache.json? but most probably it is not part of this PR ;)


<!-- Sent from Reviewable.io -->

2021-11-29 17:26 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-29 19:58 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-29 20:29 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 18 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/__init__.py, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphLqv4EeDbG2zSrwGm:-MphLqv4EeDbG2zSrwGn:bzdg7aj) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L13)):*
> ```
> On the input
> ```

Maybe `As the input` ?
___
*[tools/perf/lib/__init__.py, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphM8Gd1AHR38QGHYq2:-MphM8Gd1AHR38QGHYq3:b8lopnl) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L21)):*
> ```
> two means where:
> ```

`two means, where:` (add a comma before `where`)
___
*[tools/perf/lib/__init__.py, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphMIXV3Jkq51NY3VXw:-MphMIXV3Jkq51NY3VXx:bjsdkjp) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L22)):*
> ```
> as a JSON file
> ```

`as JSON files`
___
*[tools/perf/lib/__init__.py, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNOPn4NNUY1gVnnsN:-MphNOPn4NNUY1gVnnsO:b4dqbls) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L24)):*
> ```
> pair of a Markdown and a JSON files
> ```

What is the purpose of these two files?
___
*[tools/perf/lib/__init__.py, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphMqLoE5C9RTV5y5fX:-MphMqLoE5C9RTV5y5fY:b-yokxjg) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L36)):*
> ```
> consist
> ```

consists
___
*[tools/perf/lib/__init__.py, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphN-cP-uf4nxXnmpC6:-MphN-cP-uf4nxXnmpC7:bgfid2z) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L37)):*
> ```
> points each of which is ...
> ```

`points, where each of them is ...`
___
*[tools/perf/lib/__init__.py, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNByt9jpV-TeU_kNU:-MphNByt9jpV-TeU_kNV:b-vny2ke) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L38)):*
> ```
> impose
> ```

imposes
___
*[tools/perf/lib/__init__.py, line 48 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphN_Tz6rVEqElPlfJD:-MphN_Tz6rVEqElPlfJE:b-bw48ux) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L48)):*
> ```
> can not
> ```

cannot


<!-- Sent from Reviewable.io -->

2021-11-29 20:42 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 28 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/bench.py, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfC8b52VzE_1YBbqV:-MphO75yAv93doX55iSw:bpnuuwe) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Bench.config
> ```
config
</blockquote></details>

-1

`Bench.config` is more clear for me
___
*[tools/perf/lib/bench.py, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOeTL3na0zxfg3Ehy:-MphOeTL3na0zxfg3Ehz:b-tw6795) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L31)):*
> ```
> `Bench.config` the configuration
> ```

``Bench.config` - the configuration` (add the dash)
___
*[tools/perf/lib/bench.py, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfFvN2sqyoHaUhv1d:-MphOCW_1-kGq8duJB2c:b-nc8zi) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Bench.parts
> ```
parts
</blockquote></details>

-1

`Bench.parts` is more clear for me
___
*[tools/perf/lib/bench.py, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOlEE6kDNmRixmuC5:-MphOlEF2Zxm_mV14uIT:b-11sm13) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L32)):*
> ```
> - `Bench.parts` the list of
> ```

`- `Bench.parts` - the list of` (add the dash)
___
*[tools/perf/lib/bench.py, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOSos-XemK9onY6nu:-MphOSos-XemK9onY6nv:bcm7fj7) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L33)):*
> ```
>  a part the `Bench`
> ```

` a part, the `Bench`` (add the comma)
___
*[tools/perf/lib/bench.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOr1LCRLOUysoTMY2:-MphOr1LCRLOUysoTMY3:b-g3e6p1) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L35)):*
> ```
> - `Bench.figures` the combined list
> ```

`- `Bench.figures` - the combined list` (add the dash)
___
*[tools/perf/lib/bench.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfLrA7ZJ49a3Bhf1f:-MphOvgqDym5zbC0TiSR:b-8mzeor) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Bench.figures
> ```
.
</blockquote></details>

-1

.
___
*[tools/perf/lib/bench.py, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphP6KT83ZzQcsE-Nqg:-MphP6KT83ZzQcsE-Nqh:bi9lnbd) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L36)):*
> ```
> To cover a figure the `Bench` object
> ```

`To cover a figure, the `Bench` object`
___
*[tools/perf/lib/bench.py, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphPH069GICSXEE2vTC:-MphPH069GICSXEE2vTD:b-tmidk) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L39)):*
> ```
> - `Bench.requirements` the dict 
> ```

`- `Bench.requirements` - the dictionary ...`
___
*[tools/perf/lib/bench.py, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfQiE-gdCuBorR4UW:-MphPL4O2tOubjBKN-qS:bb6elxp) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Bench.requirements
> ```
.
</blockquote></details>

-1
.
___
*[tools/perf/lib/bench.py, line 44 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphPXT78hXlE5znaH7Q:-MphPXT78hXlE5znaH7R:b-xq243p) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L44)):*
> ```
>           ... may be later on used ...
> ```

`... may be used later on ...`
___
*[tools/perf/lib/bench.py, line 45 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphPnAE07LevyfX17GZ:-MphPnAE07LevyfX17G_:b-xgmq6c) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L45)):*
> ```
> - `Bench.result_dir` a directory 
> ```

`- `Bench.result_dir` - a directory `
___
*[tools/perf/lib/bench.py, line 45 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfT3e6AJ2ZHj2DqI6:-MphPpI77GDHo-Vh7z1O:bb6elxp) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L45)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Bench.result_dir
> ```
.
</blockquote></details>

-1
.
___
*[tools/perf/lib/bench.py, line 48 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpggXES5P_WAkoimpgM:-MphPuBs686nENmyjlp2:bb6elxp) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> its `Bench.run()`
> ```
`run()`
</blockquote></details>

-1
.
___
*[tools/perf/lib/bench.py, line 49 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphQ57BDHfdXydxYjnJ:-MphQ57BDHfdXydxYjnK:bvmclwk) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L49)):*
> ```
> When it will return `True` 
> ```

`When it returns True`
___
*[tools/perf/lib/bench.py, line 76 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphQVZHD7R0DHAcknAm:-MphQVZHD7R0DHAcknAn:b-6u1i7f) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L76)):*
> ```
> The 'flat' list is of all figures coming from 
> ```

`The 'flat' list of all figures comes from `


<!-- Sent from Reviewable.io -->

2021-11-29 21:04 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 36 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/bench.py, line 89 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphQxu5-1h9wqyEAiPY:-MphQxu5-1h9wqyEAiPZ:bl5sa3e) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L89)):*
> ```
> identifier
> ```

identifiers
___
*[tools/perf/lib/bench.py, line 110 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphRJL73z-4Ho2djICj:-MphRJL73z-4Ho2djICk:b-he2289) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L110)):*
> ```
> exptected
> ```

expected
___
*[tools/perf/lib/bench.py, line 111 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphROom02uLZHjuC8Eu:-MphROon3hQte2NqJfnL:bg77o8) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L111)):*
> ```
> exptect
> ```

expected
___
*[tools/perf/lib/bench.py, line 122 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphRipx5bRsGg0j2NzZ:-MphRipx5bRsGg0j2Nz_:bp9k5g2) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L122)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         figures = Figure.flatten([
>             figure
>             for part in parts
>             for figure in part['json']])
> ```
</details>


Are those snippets (the old and the new one) equal/the same ? What is the difference?

```
        figures = Figure.flatten([
            figure
            for figure_file in figures
            for figure in figure_file['json']])
```
___
*[tools/perf/lib/bench.py, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphS4z15b5TSiu7FrZB:-MphS4z15b5TSiu7FrZC:b-1htdv3) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L125)):*
> ```
>  to meet
> ```

to be met
___
*[tools/perf/lib/bench.py, line 169 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphTk7X0cPaSkTFPy2U:-MphTk7X0cPaSkTFPy2V:bt460hi) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L169)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         - `cache['config']` which store the `Bench.config` property
>         - `cache['parts']` which store the `Bench.parts` property
>         - `cache['figures']` which store the `Bench.figures` property
>         - `cache['requirements']` which store the `Bench.requirements` property
> ```
</details>


4 x (`which store` -> `which stores`)
___
*[tools/perf/lib/bench.py, line 189 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUB7iCtpl1FhdDD09:-MphUB7iCtpl1FhdDD0A:b-nqtzdm) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L189)):*
> ```
> run all series one-by-one & collect all series
> ```

"run all series and collect all series" ? - I do not understand this. I suppose it needs rephrasing or more details, for example:
"run all series of <x1> and collect all series of <x2>" ?
___
*[tools/perf/lib/bench.py, line 193 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUuL9-IddREj2KH87:-MphUuL9-IddREj2KH88:bfx5d5d) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L193)):*
> ```
>         it executes all series forcing
>         the given requirement 
> ```

Does it really force (=change?) the requirement?


<!-- Sent from Reviewable.io -->

2021-11-29 21:36 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 3 of 8 files reviewed, 36 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/__init__.py, line 49 at r3](https://reviewable.io/reviews/pmem/rpma/1361#-Mpg_Qk22FGI6qlAHO7u:-MphZ-e8588Qp2EMEW_0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d188c7413df45df22ce5bac4dba06319cb724e52/tools/perf/lib/__init__.py#L49)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> `report_create` to generate a report including your custom part. It will end up
> with an error.
> ```
What shall be used instead?
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphLqv4EeDbG2zSrwGm:-MphTjcl5djKHnf8DXI0:bz5kc6x) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> On the input
> ```

Maybe `As the input` ?
</blockquote></details>

TBH I like more `On the input`. Both seem correct. Can I keep it?
___
*[tools/perf/lib/__init__.py, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphM8Gd1AHR38QGHYq2:-MphU6J_C3l86WMSdjF0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> two means where:
> ```

`two means, where:` (add a comma before `where`)
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphMIXV3Jkq51NY3VXw:-MphUGCT6sfsoGW33FTx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> as a JSON file
> ```

`as JSON files`
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNOPn4NNUY1gVnnsN:-MphW75cEI3W3T2APj06:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> pair of a Markdown and a JSON files
> ```

What is the purpose of these two files?
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphMqLoE5C9RTV5y5fX:-MphYWjD41VJ4kcyCuDA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> consist
> ```

consists
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphN-cP-uf4nxXnmpC6:-MphYfZnClZnl7jtKL74:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> points each of which is ...
> ```

`points, where each of them is ...`
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNByt9jpV-TeU_kNU:-MphYj6U5H2a9spa2dw0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> impose
> ```

imposes
</blockquote></details>

Done.
___
*[tools/perf/lib/__init__.py, line 48 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphN_Tz6rVEqElPlfJD:-MphYlWB93QhxDJNsnri:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> can not
> ```

cannot
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfC8b52VzE_1YBbqV:-MphZQBu8FzTXvrn9VmW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

-1

`Bench.config` is more clear for me
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOeTL3na0zxfg3Ehy:-MphZZf395Z-U6har2MA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> `Bench.config` the configuration
> ```

``Bench.config` - the configuration` (add the dash)
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfFvN2sqyoHaUhv1d:-MphZ_P2ALVdHBhUg-vT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

-1

`Bench.parts` is more clear for me
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOlEE6kDNmRixmuC5:-MphZaAA4SezGr4HlGN_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> - `Bench.parts` the list of
> ```

`- `Bench.parts` - the list of` (add the dash)
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOSos-XemK9onY6nu:-MphZlHl9inn_AhArKNw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  a part the `Bench`
> ```

` a part, the `Bench`` (add the comma)
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfLrA7ZJ49a3Bhf1f:-MphZlrB9Yt6BfBv7-Ds:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

-1

.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphOr1LCRLOUysoTMY2:-MphZm_kA53kTjDsy34n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> - `Bench.figures` the combined list
> ```

`- `Bench.figures` - the combined list` (add the dash)
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphP6KT83ZzQcsE-Nqg:-MphZnKdCqqX-HPlhZA3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> To cover a figure the `Bench` object
> ```

`To cover a figure, the `Bench` object`
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MpgfQi [...]

2021-11-29 21:40 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 3 of 8 files reviewed, 36 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/bench.py, line 122 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphRipx5bRsGg0j2NzZ:-MphcN9U22nBD4uhwlh7:bqqo7je) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L122)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         figures = Figure.flatten([
>             figure
>             for part in parts
>             for figure in part['json']])
> ```

Are those snippets (the old and the new one) equal/the same ? What is the difference?

```
        figures = Figure.flatten([
            figure
            for figure_file in figures
            for figure in figure_file['json']])
```
</blockquote></details>

Syntactically it is exactly the same. I have just renamed the argument of the function from `figures` to `parts` which made following how entities unwrap a little bit easier in my opinion:

- it was: figures -> figure_file -> figure :-1: 
- it is: parts -> part -> figure :+1:

I hope you like it. ;-)


<!-- Sent from Reviewable.io -->

2021-11-29 21:56 UTC, grom72 reviewed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-29 22:10 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/__init__.py, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphN-cP-uf4nxXnmpC6:-Mphj3aB5wapd-OYOQR1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

each of them
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 49 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphQ57BDHfdXydxYjnJ:-MphjJcfEL4MrEaJGhmx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Quotes are OK, I meant only the tense:

`it will return` -> `it returns`

</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 76 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphQVZHD7R0DHAcknAm:-MphjON86xFoyKN2Bvvy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L76)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`coming` -> `comes`
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 189 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUB7iCtpl1FhdDD09:-MphirbICmJ_61C5RRwN:b-yw8ca2) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L189)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> run all series one-by-one & collect all series
> ```

"run all series and collect all series" ? - I do not understand this. I suppose it needs rephrasing or more details, for example:
"run all series of <x1> and collect all series of <x2>" ?
</blockquote></details>

Any better?
___
*[tools/perf/lib/bench.py, line 193 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUuL9-IddREj2KH87:-Mphisfw0OT4PibO7R4u:b-yw8ca2) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L193)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         it executes all series forcing
>         the given requirement 
> ```

Does it really force (=change?) the requirement?
</blockquote></details>

Any better?


<!-- Sent from Reviewable.io -->

2021-11-29 22:14 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1361#-MpfvVg57vsl6qmZdef7:-MphksYeC1shIfmwQ1FX:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we then point to this location from report_bench.py, report_figures.py, report_create.py?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-11-30 07:09 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/bench.py, line 189 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUB7iCtpl1FhdDD09:-MpjaAjb3YjwI5b94mjG:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L189)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Any better?
</blockquote></details>

OK
___
*[tools/perf/lib/bench.py, line 193 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUuL9-IddREj2KH87:-MpjaaZKDuWgGNKH7-sq:bzd1k30) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L193)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Any better?
</blockquote></details>

Maybe `making requirement` -> `executing requirement` ?


<!-- Sent from Reviewable.io -->

2021-11-30 07:53 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-30 08:32 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/bench.py, line 193 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUuL9-IddREj2KH87:-Mpjxc0R0SswjVc5K4GG:b-h9nwza) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L193)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe `making requirement` -> `executing requirement` ?
</blockquote></details>

I don't like `executing requirement`. I do not consider a requirement as something which is executed.
By `make` in this context, I understand that a given series expects that it will be executed in presence of the given requirement applied to the system configuration.


<!-- Sent from Reviewable.io -->

2021-11-30 08:51 UTC, ldorau requested changes
> Reviewed 2 of 3 files at r4, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/bench.py, line 193 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUuL9-IddREj2KH87:-Mpk114q1UNmFrv78snX:bpcqf19) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L193)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like `executing requirement`. I do not consider a requirement as something which is executed.
By `make` in this context, I understand that a given series expects that it will be executed in presence of the given requirement applied to the system configuration.
</blockquote></details>

Ah, I understand now what you meant. I think it would be more clear to rephrase it in this way:

"it executes all series **which make** the given requirement one-by-one"


<!-- Sent from Reviewable.io -->

2021-11-30 08:56 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/__init__.py, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNOPn4NNUY1gVnnsN:-Mpk2BkE74hbUBkAQsHh:b-rniwko) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It doesn't answer my question: what is the purpose of these two files? - especially the JSON one. What is this contents for? What are those key-value pairs?


<!-- Sent from Reviewable.io -->

2021-11-30 09:03 UTC, ldorau requested changes
> Reviewed 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.py, line 21 at r7](https://reviewable.io/reviews/pmem/rpma/1361#-Mpk4K7D-wmJZTYH_UpI:-Mpk4K7D-wmJZTYH_UpJ:bjiz9cv) ([raw file](https://github.com/pmem/rpma/blob/dea7bfb3371bc0d40f7738f615a293da495fee70/tools/perf/report_bench.py#L21)):*
> ```
> together please 
> ```

`together, please`
___
*[tools/perf/report_create.py, line 27 at r7](https://reviewable.io/reviews/pmem/rpma/1361#-Mpk4OhB4EY0uq9sZAhC:-Mpk4OhB4EY0uq9sZAhD:b14ht95) ([raw file](https://github.com/pmem/rpma/blob/dea7bfb3371bc0d40f7738f615a293da495fee70/tools/perf/report_create.py#L27)):*
> ```
> together please
> ```

`together, please`
___
*[tools/perf/report_figures.py, line 20 at r7](https://reviewable.io/reviews/pmem/rpma/1361#-Mpk4Sg32E3qq3l0cb9N:-Mpk4Sg32E3qq3l0cb9O:b-hox5gj) ([raw file](https://github.com/pmem/rpma/blob/dea7bfb3371bc0d40f7738f615a293da495fee70/tools/perf/report_figures.py#L20)):*
> ```
> together please
> ```

.
___
*[tools/perf/lib/bench.py, line 122 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphRipx5bRsGg0j2NzZ:-Mpk49rG0v2s8zTZkHS5:bcc8kgj) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Syntactically it is exactly the same. I have just renamed the argument of the function from `figures` to `parts` which made following how entities unwrap a little bit easier in my opinion:

- it was: figures -> figure_file -> figure :-1: 
- it is: parts -> part -> figure :+1:

I hope you like it. ;-)
</blockquote></details>

Yes, I like it now :-)


<!-- Sent from Reviewable.io -->

2021-11-30 09:09 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/__init__.py, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNOPn4NNUY1gVnnsN:-Mpk58NeE3RB_bsoIhhc:b-bj64lg) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L24)):*
> ```
>         - The JSON file provides the contents as key-value pairs.
>         - The Markdown file contains a `jinja2` template referencing contents
>           from both the JSON file and figures.
> ```

The JSON file provides contents that are referenced by the Markdown template which together...

>```
> - all the request parts will be combined into an HTML report file referencing
>  all the figure files and combining all the collected data into easily
>  consumable form.
>```

... make an HTML output for hassle-free consumption of the benchmarking results.


<!-- Sent from Reviewable.io -->

2021-11-30 09:16 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/__init__.py, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphNOPn4NNUY1gVnnsN:-Mpk7KMy5mQauFj1NxMb:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/__init__.py#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ```
>         - The JSON file provides the contents as key-value pairs.
>         - The Markdown file contains a `jinja2` template referencing contents
>           from both the JSON file and figures.
> ```

The JSON file provides contents that are referenced by the Markdown template which together...

>```
> - all the request parts will be combined into an HTML report file referencing
>  all the figure files and combining all the collected data into easily
>  consumable form.
>```

... make an HTML output for hassle-free consumption of the benchmarking results.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-11-30 09:29 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/report_bench.py, line 21 at r7](https://reviewable.io/reviews/pmem/rpma/1361#-Mpk4K7D-wmJZTYH_UpI:-Mpk9Rud99D675c9Ihcu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dea7bfb3371bc0d40f7738f615a293da495fee70/tools/perf/report_bench.py#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> together please 
> ```

`together, please`
</blockquote></details>

Done.
___
*[tools/perf/report_create.py, line 27 at r7](https://reviewable.io/reviews/pmem/rpma/1361#-Mpk4OhB4EY0uq9sZAhC:-Mpk9UIp5zMaVLNcyHmL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dea7bfb3371bc0d40f7738f615a293da495fee70/tools/perf/report_create.py#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> together please
> ```

`together, please`
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 20 at r7](https://reviewable.io/reviews/pmem/rpma/1361#-Mpk4Sg32E3qq3l0cb9N:-Mpk9Wm6EViB-ewh8Ii_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dea7bfb3371bc0d40f7738f615a293da495fee70/tools/perf/report_figures.py#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> together please
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 193 at r4](https://reviewable.io/reviews/pmem/rpma/1361#-MphUuL9-IddREj2KH87:-MpkA5Wl2Saw6fxmpvmT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/264f85c94b4f51df3ceb558aa535887a7e234d83/tools/perf/lib/bench.py#L193)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, I understand now what you meant. I think it would be more clear to rephrase it in this way:

"it executes all series **which make** the given requirement one-by-one"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 09:33 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361#-:-MpkBIiY4O-11Ha9wh-a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 09:35 UTC, grom72 reviewed
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 09:40 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/report_figures.py, line 15 at r8](https://reviewable.io/reviews/pmem/rpma/1361#-MpkCgT7EKUs5nxsPop7:-MpkCgT7EKUs5nxsPop8:b-fflpwk) ([raw file](https://github.com/pmem/rpma/blob/b47d7cb4a2199b84c7cb91ed424631f64ded5689/tools/perf/report_figures.py#L15)):*
> ```
> JSON file
> ```
JSON file (bench.json)


<!-- Sent from Reviewable.io -->

2021-11-30 09:41 UTC, grom72 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361#-:-MpkD1fC2ckf4KlYOIY6:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 09:46 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 09:53 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/report_figures.py, line 15 at r8](https://reviewable.io/reviews/pmem/rpma/1361#-MpkCgT7EKUs5nxsPop7:-MpkFu-k7fHDSqsbkZZP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b47d7cb4a2199b84c7cb91ed424631f64ded5689/tools/perf/report_figures.py#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> JSON file
> ```
JSON file (bench.json)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 09:54 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361#-:-MpkG9J7B9HFp_L6L8by:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 09:56 UTC, Patryk717 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361#-:-MpkGVaE2gwGFVnrm5VE:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 10:12 UTC, ldorau approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 10:13 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1361#-:-MpkKKyCC3LsU1i20xRX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 10:13 UTC, merged