tools: perf: document lib.figure.flat module
pmem/rpma pull request #1366
Opened 2021-11-29 12:58 UTC by janekmi

Requires:

- [ ] #1358
- [ ] #1361
- [ ] #1364

2021-11-29 12:59 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-29 21:29 UTC, ldorau commented on tools/perf/lib/figure/flat.py
> +A 'flat' list a figures is a list where a single element on this list represents
Maybe:
A 'flat' list of figures is ... ?

2021-11-30 10:39 UTC, grom72 reviewed
@janekmi please rebase with #1358 and #1361

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366#-:-MpkQ9sG5EbAcshUc22z:bd30pot)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-30 11:49 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/figure/flat.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1366#-MpflcGB6RTTuFOJh47v-r1-13:-MpkfTgm0QH3w0BYLn_v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a781821124a6bfef8a56db23f682e60743f0ab16/tools/perf/lib/figure/flat.py#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe:
A 'flat' list of figures is ... ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 12:22 UTC, ldorau requested changes
> Reviewed 1 of 12 files at r1, 10 of 10 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/figure/flat.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1366#-MpkmsN_BNahMZQ4qjJq:-MpkmsN_BNahMZQ4qjJr:b-aih6db) ([raw file](https://github.com/pmem/rpma/blob/e277f650148a95b35155e8a4ee93b2c1e56c5662/tools/perf/lib/figure/flat.py#L17)):*
> ```
> figures are they are described
> ```

??? "figures described" ?


<!-- Sent from Reviewable.io -->

2021-11-30 12:25 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/figure/flat.py, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1366#-MpknO4C3VeJAAq-584L:-MpknO4C3VeJAAq-584M:b-ykst13) ([raw file](https://github.com/pmem/rpma/blob/e277f650148a95b35155e8a4ee93b2c1e56c5662/tools/perf/lib/figure/flat.py#L14)):*
> ```
> represents exactly one output figure with all series representing
> ```

I do not understand that ("represents ... representing ... ")


<!-- Sent from Reviewable.io -->

2021-11-30 12:48 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/figure/flat.py, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1366#-MpknO4C3VeJAAq-584L:-Mpksvhm9B0mMlLBa9Il:b-k6olmy) ([raw file](https://github.com/pmem/rpma/blob/e277f650148a95b35155e8a4ee93b2c1e56c5662/tools/perf/lib/figure/flat.py#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> represents exactly one output figure with all series representing
> ```

I do not understand that ("represents ... representing ... ")
</blockquote></details>

What do you think now?
___
*[tools/perf/lib/figure/flat.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1366#-MpkmsN_BNahMZQ4qjJq:-Mpksz250H_t2q5aDIFN:b-yw8ca2) ([raw file](https://github.com/pmem/rpma/blob/e277f650148a95b35155e8a4ee93b2c1e56c5662/tools/perf/lib/figure/flat.py#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> figures are they are described
> ```

??? "figures described" ?
</blockquote></details>

Any better?


<!-- Sent from Reviewable.io -->

2021-11-30 13:02 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure/flat.py, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1366#-MpknO4C3VeJAAq-584L:-Mpkw6ubCoMTegS3XeEY:bgswke0) ([raw file](https://github.com/pmem/rpma/blob/e277f650148a95b35155e8a4ee93b2c1e56c5662/tools/perf/lib/figure/flat.py#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What do you think now?
</blockquote></details>

It is OK now
___
*[tools/perf/lib/figure/flat.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1366#-MpkmsN_BNahMZQ4qjJq:-MpkvcanB6GNUrfsaoTJ:b-1ctm1u) ([raw file](https://github.com/pmem/rpma/blob/e277f650148a95b35155e8a4ee93b2c1e56c5662/tools/perf/lib/figure/flat.py#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Any better?
</blockquote></details>

Much better
___
*[tools/perf/lib/figure/flat.py, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1366#-MpkvuAa3OBQqZrBHK-w:-MpkvuAa3OBQqZrBHK-x:b5fxonb) ([raw file](https://github.com/pmem/rpma/blob/96ecc00870b2241a355b2fc8fce7443aa0c4b54a/tools/perf/lib/figure/flat.py#L17)):*
> ```
> - a single element on this list represents exactly one output figure and
> - all elements on `figure['series']` lists represent exactly one series of
>   benchmarks.
> ```

2 x (`on the list` -> `in the list`)


<!-- Sent from Reviewable.io -->

2021-11-30 13:07 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366#-:-MpkxAV_Eso3HHR_PY8i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 13:08 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366#-:-MpkxTeGETiA3lJD5SbV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 13:08 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-11-30 13:21 UTC, merged

2021-11-30 13:27 UTC, grom72 reviewed
> Reviewed 1 of 10 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1366)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->