tools: read CPULIST and CORES_PER_SOCKET from the remote node
pmem/rpma pull request #1370
Opened 2021-11-30 09:00 UTC by osalyk

2021-11-30 09:13 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-11-30 10:18 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/bench.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkBXNT3_Aj-db1yoVk:-MpkBXNT3_Aj-db1yoVl:b-8lre6n) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L69)):*
> ```Python
> 
>         # get cpulist of the remote NUMA node (REMOTE_JOB_NUMA)
>         cpulist_path = "/sys/devices/system/node/node" +\
> ```

Please put a space between `+` and `\`.
___
*[tools/perf/lib/bench.py, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGQwm5hpVINpjZuaj:-MpkGQwm5hpVINpjZuak:b-1zk8a4) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L70)):*
> ```Python
>         # get cpulist of the remote NUMA node (REMOTE_JOB_NUMA)
>         cpulist_path = "/sys/devices/system/node/node" +\
>             str(config['REMOTE_JOB_NUMA']) + "/cpulist"
> ```

```python
"/sys/devices/system/node/node{}/cpulist".format(str(config['REMOTE_JOB_NUMA']))
```
___
*[tools/perf/lib/bench.py, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGfOCAF6ipbYwQ7UL:-MpkGfOCAF6ipbYwQ7UM:bfjdlgd) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L71)):*
> ```Python
>         cpulist_path = "/sys/devices/system/node/node" +\
>             str(config['REMOTE_JOB_NUMA']) + "/cpulist"
>         cpulist = RemoteCmd.run_sync(config, ['cat', cpulist_path], None)
> ```

~~None~~
___
*[tools/perf/lib/bench.py, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGuq98r554ZkiGxF5:-MpkGuq98r554ZkiGxF6:bcxsyay) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L73)):*
> ```Python
>         cpulist = RemoteCmd.run_sync(config, ['cat', cpulist_path], None)
>         if cpulist.exit_status != 0:
>             raise ValueError(cpulist.stderr.readline())
> ```

Isn't it typical behaviour? Maybe it can become a part of the `RemoteCmd.run_(a)sync()`? e.g.

```python
_ = RemoteCmd.run_sync(config, cmd, raise_on_error=True)
```
___
*[tools/perf/lib/bench.py, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkHFTX3n0ceLcuX5B0:-MpkHFTX3n0ceLcuX5B1:b-6l2dcs) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L73)):*
> ```Python
>         cpulist = RemoteCmd.run_sync(config, ['cat', cpulist_path], None)
>         if cpulist.exit_status != 0:
>             raise ValueError(cpulist.stderr.readline())
> ```

Shouldn't we use `.read()` instead? `.readline()` will read only the first line I suppose.
___
*[tools/perf/lib/bench.py, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkHgDZ6fCB7cMFa38V:-MpkHgDZ6fCB7cMFa38W:b-bejre8) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L74)):*
> ```Python
>         if cpulist.exit_status != 0:
>             raise ValueError(cpulist.stderr.readline())
>         cpulist_value = cpulist.stdout.readline().replace('\n', '')
> ```

You got `\n` when you use `.readline()`? :thinking: 
___
*[tools/perf/lib/bench.py, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkIZzhB78KyP4z28WW:-MpkIZzhB78KyP4z28WX:b-19p5bw) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L80)):*
> ```Python
>         else:
>             raise ValueError("Invalid value REMOTE_JOB_NUMA_CPULIST={}"
>                              .format(cpulist_value))
> ```

I think you can put all of these into an accessory function used as follows:

```python
config['REMOTE_JOB_NUMA_CPULIST'] = self.__get_remote_job_numa_cpulist()
```
___
*[tools/perf/lib/bench.py, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkJ3FA1ZqYNYbA9oQS:-MpkJ3FA1ZqYNYbA9oQT:be55jaa) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L83)):*
> ```Python
> 
>         # get cores per socket
>         cmd = "lscpu | egrep 'Core\(s\) per socket:' | sed 's/[^0-9]*//g'"
> ```

Quick and dirty. :p Working on an alternative... it should:

**(pseudo-code)**

```
output = stdout.read_lines()
filtered = [line for line in lines if line.matches('Core per socket')]
if len(filtered) != 1:
    raise ShouldBeOnlyOneError()
return filtered[0].regex('Cores per socket: ([0-9]+)') # raise something if no match found
```
___
*[tools/perf/lib/bench.py, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkJ7vf7ftKeTCLHyOr:-MpkJ7vf7ftKeTCLHyOs:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L86)):*
> ```Python
>         cores = RemoteCmd.run_sync(config, cmd, None)
>         if cores.exit_status != 0:
>             raise ValueError(cpulist.stderr.readline())
> ```

.
___
*[tools/perf/lib/bench.py, line 93 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkJ9ulBDoW2gsTfgi4:-MpkJ9ulBDoW2gsTfgi5:bcqs0xi) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L93)):*
> ```Python
>         else:
>             raise ValueError("Invalid value CORES_PER_SOCKET={}"
>                              .format(cores_value))
> ```

```python
config['CORES_PER_SOCKET'] = self.__get_cores_per_socket()
```
___
*[tools/perf/lib/remote_cmd.py, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGcy9CXN2H-S-yIvA:-MpkGcy9CXN2H-S-yIvB:bfaqvel) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/remote_cmd.py#L58)):*
> ```Python
> 
>     @classmethod
>     def run_async(cls, config, cmd, env):
> ```

`env=None`
___
*[tools/perf/lib/remote_cmd.py, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkC6jN4YIOiwybGd5y:-MpkC6jN4YIOiwybGd5z:b-h9czqo) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/remote_cmd.py#L63)):*
> ```Python
>         if isinstance(cmd, list):
>             cmd = ' '.join(cmd)
>         _, stdout, stderr = ssh_client.exec_command(cmd, environment=env)
> ```

It looks like at least a separate commit.
___
*[utils/pylint.rc, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkICCWCKCU8-RnoV47:-MpkICCWCKCU8-RnoV48:bdk9835) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/utils/pylint.rc#L15)):*
> ```
> # len-as-condition - bug in Pylint, fixed as of Pylint 2.4 (https://github.com/PyCQA/pylint/pull/2815)
> # duplicate-code - XXX requires consideration
> # anomalous-backslash-in-string - XXX requires consideration
> ```

Which lines cause this?
Maybe you can use some of this: https://pylint.pycqa.org/en/latest/user_guide/message-control.html


<!-- Sent from Reviewable.io -->

2021-11-30 11:34 UTC, ldorau requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkC6jN4YIOiwybGd5y:-MpkbxKSCDyVIyCqVkUg:b-217ktf) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/remote_cmd.py#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It looks like at least a separate commit.
</blockquote></details>

Yeah, it could be even a separate PR ...
___
*[utils/pylint.rc, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkICCWCKCU8-RnoV47:-Mpkb96K05pAdkmleEuV:b2o5h1u) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/utils/pylint.rc#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Which lines cause this?
Maybe you can use some of this: https://pylint.pycqa.org/en/latest/user_guide/message-control.html
</blockquote></details>

You can probably add prefix 'r'  before the string - it should silent this error:
`r'string-wth-\-backslash'`


<!-- Sent from Reviewable.io -->

2021-12-01 09:13 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 0 of 5 files reviewed, 12 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/bench.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkBXNT3_Aj-db1yoVk:-Mpl9hQ9AMm4_rHxdUaj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please put a space between `+` and `\`.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGQwm5hpVINpjZuaj:-MplAEXd5IAgVCrIDHBS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
"/sys/devices/system/node/node{}/cpulist".format(str(config['REMOTE_JOB_NUMA']))
```
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGfOCAF6ipbYwQ7UL:-MplLFJOCapbYyd5Ivhp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~None~~
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGuq98r554ZkiGxF5:-MplMBeT4fSCuhbEZ8RZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Isn't it typical behaviour? Maybe it can become a part of the `RemoteCmd.run_(a)sync()`? e.g.

```python
_ = RemoteCmd.run_sync(config, cmd, raise_on_error=True)
```
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkIZzhB78KyP4z28WW:-MppFWgX9rkj5X50VD7-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you can put all of these into an accessory function used as follows:

```python
config['REMOTE_JOB_NUMA_CPULIST'] = self.__get_remote_job_numa_cpulist()
```
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkJ7vf7ftKeTCLHyOr:-Mpp5cJV-lxyLq9CZ-aO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 93 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkJ9ulBDoW2gsTfgi4:-MppFRiB6PiRw29_1O6w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
config['CORES_PER_SOCKET'] = self.__get_cores_per_socket()
```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkGcy9CXN2H-S-yIvA:-MplLYHjAvANjx8GMBze:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/remote_cmd.py#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`env=None`
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkC6jN4YIOiwybGd5y:-MplBZ2tD8BMEjDB7Kcd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/remote_cmd.py#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yeah, it could be even a separate PR ...
</blockquote></details>

Done.
___
*[utils/pylint.rc, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkICCWCKCU8-RnoV47:-Mpp6HZ02dYyxEYWqqq3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/utils/pylint.rc#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You can probably add prefix 'r'  before the string - it should silent this error:
`r'string-wth-\-backslash'`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-01 09:15 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 1 of 5 files reviewed, 12 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-01 09:16 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 2 of 5 files reviewed, 12 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-01 09:17 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 3 of 5 files reviewed, 12 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-01 10:23 UTC, janekmi reviewed
> Reviewed 1 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-01 12:09 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/bench.py, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkHFTX3n0ceLcuX5B0:-Mppb5Yh-T1YqtPRgCqS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Shouldn't we use `.read()` instead? `.readline()` will read only the first line I suppose.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/1370#-MpkHgDZ6fCB7cMFa38V:-Mppb62yE0pv59VG3epc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed10520b523ec85a3036071172ad998f1a752966/tools/perf/lib/bench.py#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You got `\n` when you use `.readline()`? :thinking: 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-01 15:27 UTC, janekmi requested changes
> Reviewed 1 of 5 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/bench.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_IgXCDzyGb8Nz30Q:-Mpq_IgXCDzyGb8Nz30R:b14hef9) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L25)):*
> ```Python
> def get_remote_job_numa_cpulist(config):
>     """get cpulist of the remote NUMA node (REMOTE_JOB_NUMA)"""
>     cpulist_path = "/sys/devices/system/node/node{}/cpulist"\
> ```

A space before `\` please.
___
*[tools/perf/lib/bench.py, line 27 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_Tpf6XDfrSXUTwKN:-Mpq_Tpf6XDfrSXUTwKO:b-87g6vx) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L27)):*
> ```Python
>     cpulist_path = "/sys/devices/system/node/node{}/cpulist"\
>         .format(str(config['REMOTE_JOB_NUMA']))
>     cpulist = RemoteCmd.run_sync(config, ['cat', cpulist_path],
> ```

cpulist_cmd?
___
*[tools/perf/lib/bench.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_VXb5abJ1rf37AlP:-Mpq_VXb5abJ1rf37AlQ:b-j6hxlr) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L29)):*
> ```Python
>     cpulist = RemoteCmd.run_sync(config, ['cat', cpulist_path],
>                                  raise_on_error=True)
>     cpulist_value = cpulist.stdout.read().decode('utf8').replace('\n', '')
> ```

cpulist
___
*[tools/perf/lib/bench.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_Xf_CWqk_jMylUv9:-Mpq_Xf_CWqk_jMylUvA:b-h7l36t) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L29)):*
> ```Python
>     cpulist = RemoteCmd.run_sync(config, ['cat', cpulist_path],
>                                  raise_on_error=True)
>     cpulist_value = cpulist.stdout.read().decode('utf8').replace('\n', '')
> ```

Do we really need `.decode()` here?
___
*[tools/perf/lib/bench.py, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_fde5f76JvzWJ-M5:-Mpq_fde5f76JvzWJ-M6:bkvn3ir) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L34)):*
> ```Python
>         raise ValueError("Invalid value REMOTE_JOB_NUMA_CPULIST={}"
>                          .format(cpulist_value))
> ```

Not needed newline.
___
*[tools/perf/lib/bench.py, line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpqa1SECPyP4ayUD4Or:-Mpqa1SECPyP4ayUD4Os:b-tu6krh) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L43)):*
> ```Python
>     output = cores.stdout.readlines()
>     filtered = [line for line in output if re.match(r'Core\(s\) per socket',
>                                                     line)]
> ```

```python
    filtered = [line \
        for line in output if re.match(r'Core\(s\) per socket', line)]
```

Won't be nicer?
___
*[tools/perf/lib/bench.py, line 45 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-MpqaN657RJ1fo6dANFM:-MpqaN657RJ1fo6dANFN:bj4rsnb) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L45)):*
> ```Python
>                                                     line)]
>     if not filtered:
>         raise ValueError("Cannot find value CORES_PER_SOCKET")
> ```

```python
"...\n{}".format("\n".join(output))
```
___
*[tools/perf/lib/bench.py, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpqap7NEvF3t_1IEp3S:-Mpqap7NEvF3t_1IEp3T:b-scsoza) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L50)):*
> ```Python
>     if not re.match(r"^[0-9]+$", cores_value):
>         raise ValueError("Invalid value CORES_PER_SOCKET={}"
>                          .format(cores_value))
> ```

Just a reminder for me to analyze this part in depth. ;-)


<!-- Sent from Reviewable.io -->

2021-12-01 17:05 UTC, ldorau requested changes
> Reviewed 1 of 5 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 67 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-MpqxH_R8P8Y_WLhCVGa:-MpqxH_R8P8Y_WLhCVGb:b836npx) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/remote_cmd.py#L67)):*
> ```
>         if raise_on_error:
>             if stdout.channel.recv_exit_status() != 0:
>                 raise ValueError(stderr.read())
> ```

Again, all changes in this module should be made in a separate PR ...


<!-- Sent from Reviewable.io -->

2021-12-01 17:09 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/bench.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_Xf_CWqk_jMylUv9:-MpqxqtSA1nTTO-Me6gx:b-5xamn2) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we really need `.decode()` here?
</blockquote></details>

AFAIR it is a sequence of bytes without decoding


<!-- Sent from Reviewable.io -->

2021-12-02 07:18 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/bench.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_IgXCDzyGb8Nz30Q:-Mptx_Nm23iBi-kRGadV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A space before `\` please.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 27 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_Tpf6XDfrSXUTwKN:-Mptxeiw9oC2LjPfQARd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cpulist_cmd?
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_VXb5abJ1rf37AlP:-MptxweW8QM67hUI42d4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cpulist
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_Xf_CWqk_jMylUv9:-MptyP0k5E7YewS2vKw1:bpqopi4) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

AFAIR it is a sequence of bytes without decoding
</blockquote></details>

Yes, we need.
___
*[tools/perf/lib/bench.py, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpq_fde5f76JvzWJ-M5:-MptyU1KEg2SFR0k-oV8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed newline.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-Mpqa1SECPyP4ayUD4Or:-Mptz1iP3CD-efiyR7Yq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
    filtered = [line \
        for line in output if re.match(r'Core\(s\) per socket', line)]
```

Won't be nicer?
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 45 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-MpqaN657RJ1fo6dANFM:-MptzR3U4J7NUywest81:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/bench.py#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
"...\n{}".format("\n".join(output))
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 07:36 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 67 at r3](https://reviewable.io/reviews/pmem/rpma/1370#-MpqxH_R8P8Y_WLhCVGa:-Mpu3eT75VsLTjstJp1s:b-8sgh41) ([raw file](https://github.com/pmem/rpma/blob/061efc6f9b6c9255d1f4aa5a03b5eb9d8b76ef0f/tools/perf/lib/remote_cmd.py#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         if raise_on_error:
>             if stdout.channel.recv_exit_status() != 0:
>                 raise ValueError(stderr.read())
> ```

Again, all changes in this module should be made in a separate PR ...
</blockquote></details>

#1387


<!-- Sent from Reviewable.io -->

2021-12-02 07:59 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 56 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-Mpu8o7781uRJyBqDmbY:-Mpu8o7781uRJyBqDmbZ:b-km21u9) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/remote_cmd.py#L56)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>     @classmethod
>     def run_sync(cls, config, cmd, env=None, raise_on_error=False):
>         """run a remote command and wait till it is done"""
>         remote_cmd = cls.run_async(config, cmd, env)
>         remote_cmd.wait()
>         if raise_on_error:
>             if remote_cmd.exit_status != 0:
>                 raise ValueError(remote_cmd.stderr.read())
>         return remote_cmd
> 
>     @classmethod
>     def run_async(cls, config, cmd, env=None):
>         """run a remote command and return a control object"""
> ```
</details>


... all changes in this module ...


<!-- Sent from Reviewable.io -->

2021-12-02 08:01 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 56 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-Mpu8o7781uRJyBqDmbY:-Mpu9FitDTaTde_-QHbn:bkm7803) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/remote_cmd.py#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     @classmethod
>     def run_sync(cls, config, cmd, env=None, raise_on_error=False):
>         """run a remote command and wait till it is done"""
>         remote_cmd = cls.run_async(config, cmd, env)
>         remote_cmd.wait()
>         if raise_on_error:
>             if remote_cmd.exit_status != 0:
>                 raise ValueError(remote_cmd.stderr.read())
>         return remote_cmd
> 
>     @classmethod
>     def run_async(cls, config, cmd, env=None):
>         """run a remote command and return a control object"""
> ```

... all changes in this module ...
</blockquote></details>

I meant this PR should not modify this file at all.


<!-- Sent from Reviewable.io -->

2021-12-02 08:03 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 56 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-Mpu8o7781uRJyBqDmbY:-Mpu9VICCTripGgKDXAF:b-vym1fg) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/remote_cmd.py#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant this PR should not modify this file at all.
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/6TXkuey3CnzUZ0Ig7nJ0rH2-/image.png)
These changes are from PR #1387 


<!-- Sent from Reviewable.io -->

2021-12-02 08:05 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 56 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-Mpu8o7781uRJyBqDmbY:-MpuAEkE7euF6GhZO9Rz:bqnpvto) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/remote_cmd.py#L56)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/6TXkuey3CnzUZ0Ig7nJ0rH2-/image.png)
These changes are from PR #1387 
</blockquote></details>

Ah, OK


<!-- Sent from Reviewable.io -->

2021-12-02 08:06 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-02 08:18 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/bench.py, line 31 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-MpuDBMj68_P97dr0hCh:-MpuDBMj68_P97dr0hCi:b-qbhho1) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/bench.py#L31)):*
> ```
>  re.match(r"^[0-9,\-]+$", cpulist):
> ```

I think `re.fullmatch()` should be used in this case.
___
*[tools/perf/lib/bench.py, line 45 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-MpuBeQu1mXSZjBlpJnj:-MpuBeQu1mXSZjBlpJnk:b29m26y) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/bench.py#L45)):*
> ```
> str(filtered)
> ```

Can we call str() on a list?
I think this is better: `' '.join(filtered)`
___
*[tools/perf/lib/bench.py, line 47 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-MpuCaCVBmMAFlSyoNJF:-MpuCaCWC0ZkzaB-qswj:b-i9jf0y) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/bench.py#L47)):*
> ```
> re.match(r"^[0-9]+$", cores)
> ```

I think `re.fullmatch()` should be used in this case.


<!-- Sent from Reviewable.io -->

2021-12-02 08:35 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 10 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/bench.py, line 31 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-MpuDBMj68_P97dr0hCh:-MpuFNDB740_1EPrBWeI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/bench.py#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  re.match(r"^[0-9,\-]+$", cpulist):
> ```

I think `re.fullmatch()` should be used in this case.
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 45 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-MpuBeQu1mXSZjBlpJnj:-MpuGLY9ADRam0NvYkI0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/bench.py#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> str(filtered)
> ```

Can we call str() on a list?
I think this is better: `' '.join(filtered)`
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 47 at r5](https://reviewable.io/reviews/pmem/rpma/1370#-MpuCaCVBmMAFlSyoNJF:-MpuGM_38AL8zQFpYWjH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96738ee1da3599cb1e9b08144307598bee845de7/tools/perf/lib/bench.py#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> re.match(r"^[0-9]+$", cores)
> ```

I think `re.fullmatch()` should be used in this case.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 08:55 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/bench.py, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1370#-MpuKeQ8BWicaYBjabU9:-MpuKeQ9B0AondGlAxWN:bsb5jfg) ([raw file](https://github.com/pmem/rpma/blob/05dd91579021afd5c9fb6472ccacedc6ce1c65ef/tools/perf/lib/bench.py#L45)):*
> ```
>  cores = ' '.join(re.findall(r'\d+', ' '.join(filtered)))
> ```

I just realized it is not correct.
We should:
1) verify that `filtered` contains exactly one line
2) sth like that: `cores = re.match('[0-9]+', filtered[0])`


<!-- Sent from Reviewable.io -->

2021-12-02 09:09 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/bench.py, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1370#-MpuKeQ8BWicaYBjabU9:-MpuOubM3tYLlwXBr3ap:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/05dd91579021afd5c9fb6472ccacedc6ce1c65ef/tools/perf/lib/bench.py#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  cores = ' '.join(re.findall(r'\d+', ' '.join(filtered)))
> ```

I just realized it is not correct.
We should:
1) verify that `filtered` contains exactly one line
2) sth like that: `cores = re.match('[0-9]+', filtered[0])`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 09:46 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/bench.py, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1370#-MpuKeQ8BWicaYBjabU9:-MpuWrjjCvn3NDucrrm8:bho16z4) ([raw file](https://github.com/pmem/rpma/blob/05dd91579021afd5c9fb6472ccacedc6ce1c65ef/tools/perf/lib/bench.py#L45)):*
Not done - this is wrong:

> ```
> ''.join(re.findall(r'\d+',
> ```

`findall()` return **all non-overlapping matches** of pattern in string - we do not want that.

We need exactly **one single match**:
`cores = re.match('[0-9]+', filtered[0])`


<!-- Sent from Reviewable.io -->

2021-12-02 09:46 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-02 09:49 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/bench.py, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1370#-MpuKeQ8BWicaYBjabU9:-MpuXyNX2kVoBl7ntn17:b8xbesm) ([raw file](https://github.com/pmem/rpma/blob/05dd91579021afd5c9fb6472ccacedc6ce1c65ef/tools/perf/lib/bench.py#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not done - this is wrong:

> ```
> ''.join(re.findall(r'\d+',
> ```

`findall()` return **all non-overlapping matches** of pattern in string - we do not want that.

We need exactly **one single match**:
`cores = re.match('[0-9]+', filtered[0])`

</blockquote></details>

We do not want to join together many numbers, we want to extract exactly one number


<!-- Sent from Reviewable.io -->

2021-12-02 10:28 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/bench.py, line 42 at r7](https://reviewable.io/reviews/pmem/rpma/1370#-MpufZpfCLodRELgqoye:-MpufZpfCLodRELgqoyf:b-1i9qnc) ([raw file](https://github.com/pmem/rpma/blob/8e7dab9193b5d9049badfdf5540c3d7cfff9687b/tools/perf/lib/bench.py#L42)):*
> ```Python
>     filtered = [line \
>         for line in output if re.match(r'Core\(s\) per socket', line)]
>     if not filtered or len(filtered) != 1:
> ```

The second part does the charm.


<!-- Sent from Reviewable.io -->

2021-12-02 10:37 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/bench.py, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1370#-MpuKeQ8BWicaYBjabU9:-Mpui0k3CT58_K6SVcvJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/05dd91579021afd5c9fb6472ccacedc6ce1c65ef/tools/perf/lib/bench.py#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We do not want to join together many numbers, we want to extract exactly one number
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 10:49 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-02 11:15 UTC, janekmi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-02 11:25 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/bench.py, line 42 at r7](https://reviewable.io/reviews/pmem/rpma/1370#-MpufZpfCLodRELgqoye:-Mput6oR07D2tppPK8w5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e7dab9193b5d9049badfdf5540c3d7cfff9687b/tools/perf/lib/bench.py#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The second part does the charm.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 12:02 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370#-:-Mpv0_wWBkNzLXCn7RZA:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-02 12:10 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1370#-:-Mpv2Ixw3ivB2K8K_mbe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-02 12:10 UTC, merged