tools: unit tests for runners initialization
pmem/rpma pull request #1452
Opened 2021-12-27 16:10 UTC by grom72

introduce unit tests for fio and ib_read runner
several fixes related to unhandled inputs errors to run all tests smoothly

2021-12-28 10:04 UTC, Patryk717 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452#-:-Ms-UtMR8plKK8y8oZ8n:bdycpsm)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-29 07:53 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 11:59 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-Ms52GH9EFoexshm9ltc:-Ms52GH9EFoexshm9ltd:b-6uoijy) (no related file):*
Please divide this PR into two:
1) fixes
2) unit tests

This one should add only unit tests.

---
___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms52ao-6vEOr2nyyZMi):*
This part of a commit should be a full English sentence.



_Code quote:_
```
  introduce unit tests for fio and ib_read runner
  several fixes to run all tests
```


<!-- Sent from Reviewable.io -->

2021-12-29 12:15 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 103 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms54-hz6Ir1Jv8ZiQ59:-Ms54-hz6Ir1Jv8ZiQ5A:bj8hqun) ([raw file](https://github.com/pmem/rpma/blob/409bacf9687b57d7f85ffe0bfb2e04fdc66b8441/tools/perf/lib/benchmark/runner/fio.py#L103)):*
> ```Python
>         self.__set_settings_by_mode()
> 
>         # path to the local fio
> ```

Please leave this empty line



_Code quote:_
```Python
        self.__set_settings_by_mode()

        # path to the local fio
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56CYb5WLeceG3DgYi:-Ms56CYb5WLeceG3DgYj:b8tu6z2) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L61)):*
> ```Python
>         # pick the settings predefined for the chosen mode
>         if 'tool' not in self.__benchmark.oneseries:
>             raise ValueError(MISSING_KEY_MSG.format('tool'))
> ```

It is checked twice: here and in  `__ONESERIES_REQUIRED`



_Code quote:_
```Python
        if 'tool' not in self.__benchmark.oneseries:
            raise ValueError(MISSING_KEY_MSG.format('tool'))
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56Le5D4MzvWeDyps2:-Ms56Le6Dzlx7iho0y9O:b-w52y80) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
> ```Python
>         self.__tool = self.__benchmark.oneseries['tool']
>         if 'mode' not in self.__benchmark.oneseries:
>             raise ValueError(MISSING_KEY_MSG.format('mode'))
> ```

This check should be moved to ` __ONESERIES_REQUIRED` too



_Code quote:_
```Python
        if 'mode' not in self.__benchmark.oneseries:
            raise ValueError(MISSING_KEY_MSG.format('mode'))
```


<!-- Sent from Reviewable.io -->

2021-12-29 12:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 24 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57BRb77qkXOIeAUpP:-Ms57BRb77qkXOIeAUpQ:b-swlk2z) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L24)):*
> ```Python
> 
> def test_FioRunner_init(monkeypatch):
>     """test proper initialization of FioRunner object with all mandatory param"""
> ```

`all mandatory parameters`



_Code quote:_
```Python
all mandatory param
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57um20Ccp8RbC-wxZ:-Ms57um3D3Dv6ASFWVWK:b-kuhqzh) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L25)):*
> ```Python
> def test_FioRunner_init(monkeypatch):
>     """test proper initialization of FioRunner object with all mandatory param"""
>     def which_mock(path: str) ->str:
> ```

`-> str:`



_Code quote:_
```Python
->str:
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57ISnBPoqnb_7bFtW:-Ms57ISnBPoqnb_7bFtX:b-whk1h0) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L26)):*
> ```Python
>     """test proper initialization of FioRunner object with all mandatory param"""
>     def which_mock(path: str) ->str:
>         assert path == '/tmp/fio'
> ```

We use the following order:
```
    def which_mock(path: str) ->str:
        assert path == '/tmp/fio'
        return path
    def run_sync_mock(arg1, arg2) ->RemoteCmd:
        remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
        return remoteCmd
    monkeypatch.setattr(shutil, 'which', which_mock)
    monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)

```



_Code quote:_
```Python
    def which_mock(path: str) ->str:
        assert path == '/tmp/fio'
        return path
    monkeypatch.setattr(shutil, 'which', which_mock)

    def run_sync_mock(arg1, arg2) ->RemoteCmd:
        remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
        return remoteCmd
    monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57dmP5fq50LLKXATm:-Ms57dmP5fq50LLKXATn:b-a0y7gb) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L29)):*
> ```Python
>         return path
>     monkeypatch.setattr(shutil, 'which', which_mock)
>     
> ```

redundant spaces



_Code quote:_
```Python
·····
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 30 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms582hQ94kZDaBmukqo:-Ms582hQ94kZDaBmukqp:b-o3l49c) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L30)):*
> ```Python
>     monkeypatch.setattr(shutil, 'which', which_mock)
>     
>     def run_sync_mock(arg1, arg2) ->RemoteCmd:
> ```

` -> RemoteCmd:`



_Code quote:_
```Python
 ->RemoteCmd:
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms586VD9beSCSOv261S:-Ms586VD9beSCSOv261T:bu9xmvs) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L32)):*
> ```Python
>     def run_sync_mock(arg1, arg2) ->RemoteCmd:
>         remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
>         return remoteCmd
> ```

```
        return RemoteCmd(None, None, None, exit_status = 0)
```



_Code quote:_
```Python
        remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
        return remoteCmd
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57gpa-XNwdl70Zsqr:-Ms57gpa-XNwdl70Zsqs:b-a0y7gb) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L34)):*
> ```Python
>         return remoteCmd
>     monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)
>     
> ```

redundant spaces



_Code quote:_
```Python
·····
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 36 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms58ONWApHz2EvFZb6q:-Ms58ONWApHz2EvFZb6r:b-u17ie2) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L36)):*
> ```Python
>     
>     oneseries = {'tool': 'fio', 'mode': 'lat', 'tool_mode': 'apm',
>                 'rw': 'readwrite', 'busy_wait_polling': True, 
> ```

redundant two spaces at the end



_Code quote:_
```Python
True,··
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 47 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms58aXo1ZlAIghB9kN0:-Ms58aXo1ZlAIghB9kN1:b-qun9a4) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L47)):*
> ```Python
>     """failed initialization of FioRunner object - no tool param provided """
>     oneseries = {}
>     config = {'server_ip':'server_ip', 'FIO_PATH' : '/tmp'}
> ```

A common constant should be defined only once at the top of the file.



_Code quote:_
```Python
config = {'server_ip':'server_ip', 'FIO_PATH' : '/tmp'}
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 148 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57koV9fZdAdSdBQGf:-Ms57koV9fZdAdSdBQGg:bfrjpvz) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L148)):*
> ```Python
>     with pytest.raises(ValueError) as excinfo:
>         runner = FioRunner(benchmark,config, 'idfile')
>     
> ```

redundant spaces and no new line



_Code quote:_
```Python
·····
```


<!-- Sent from Reviewable.io -->

2021-12-29 12:34 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56CYb5WLeceG3DgYi:-Ms5AJ0J1D7PPrWqHk6v:b-bfnnyc) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is checked twice: here and in  `__ONESERIES_REQUIRED`
</blockquote></details>

it is moved later to Runner class in #1454 
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56Le5D4MzvWeDyps2:-Ms5Al6L0j2RmeifcsU_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This check should be moved to ` __ONESERIES_REQUIRED` too
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-12-29 12:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56CYb5WLeceG3DgYi:-Ms5FL0XCNFWoqlfZb7S:bw41vej) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

it is moved later to Runner class in #1454 
</blockquote></details>

It is wrong, so it should be fixed here, not later.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56Le5D4MzvWeDyps2:-Ms5F_eeEOE7bK5AWRnh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-12-29 13:13 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 0 of 4 files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-Ms52GH9EFoexshm9ltc:-Ms5ByYI5a-Vc_Iz_IzJ:bbma2tg) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please divide this PR into two:
1) fixes
2) unit tests

This one should add only unit tests.
</blockquote></details>

#1461 

---
___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms52ao-6vEOr2nyyZMi):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This part of a commit should be a full English sentence.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 103 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms54-hz6Ir1Jv8ZiQ59:-Ms5D-399flnWeH0zXSu:b-i776zl) ([raw file](https://github.com/pmem/rpma/blob/409bacf9687b57d7f85ffe0bfb2e04fdc66b8441/tools/perf/lib/benchmark/runner/fio.py#L103)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please leave this empty line
</blockquote></details>

Done in #1461
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56CYb5WLeceG3DgYi:-Ms5IW2Y4dblDjdTOk1J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is wrong, so it should be fixed here, not later.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56Le5D4MzvWeDyps2:-Ms5JHP8DWGeIDfzRiH0:bbhknrh) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

No, as __ONESERIES_REQUIRED in ib_read_runner requires also value
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 24 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57BRb77qkXOIeAUpP:-Ms5D_Y18hcKsGZ9kR1G:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`all mandatory parameters`
</blockquote></details>

Done
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57um20Ccp8RbC-wxZ:-Ms5DavsBDhRAH9Ehc1m:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`-> str:`
</blockquote></details>

Done
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57ISnBPoqnb_7bFtW:-Ms5DnDJ2hR7w1C4PIat:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use the following order:
```
    def which_mock(path: str) ->str:
        assert path == '/tmp/fio'
        return path
    def run_sync_mock(arg1, arg2) ->RemoteCmd:
        remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
        return remoteCmd
    monkeypatch.setattr(shutil, 'which', which_mock)
    monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)

```
</blockquote></details>

Done
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57dmP5fq50LLKXATm:-Ms5JWGN38vXbrJoL1l3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant spaces
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 30 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms582hQ94kZDaBmukqo:-Ms5DyZ6CHnHUeqbPQ5m:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

` -> RemoteCmd:`
</blockquote></details>

Done
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms586VD9beSCSOv261S:-Ms5E6g96mGXYg38QWdM:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
        return RemoteCmd(None, None, None, exit_status = 0)
```
</blockquote></details>

Done
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57gpa-XNwdl70Zsqr:-Ms5JXTyBAmQ0_RW4KhP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant spaces
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 36 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms58ONWApHz2EvFZb6q:-Ms5JYij44xkUPuFCXa5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant two spaces at the end
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 47 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms58aXo1ZlAIghB9kN0:-Ms5Hwqb221ZCSsSKPOn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

A common constant should be defined only once at the top of the file.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 148 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms57koV9fZdAdSdBQGf:-Ms5ELRI49Lf5ZGSoODb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant spaces and no new line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-29 13:14 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 1 of 4 files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 13:17 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 15 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 14:03 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/1452#-Ms56Le5D4MzvWeDyps2:-Ms5TjUpBHiK4J_Db4vL:b-8or0ia) ([raw file](https://github.com/pmem/rpma/blob/37bfe1954bcbdb44e465bb420d184519702bf07a/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

No, as __ONESERIES_REQUIRED in ib_read_runner requires also value
</blockquote></details>

See: https://github.com/ldorau/rpma/commit/12d6a947fdc48ba0599b3e93b5b189dc1bcfde03
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 27 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5UFXN-zvV6JlyZC3K:-Ms5UFXN-zvV6JlyZC3L:bwwsizi) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L27)):*
> ```Python
> def test_FioRunner_init(monkeypatch):
>     """test proper initialization of FioRunner object
>         with all mandatory parameters"""
> ```

We use the following style:
```
"""test proper initialization of FioRunner object
   with all mandatory parameters
"""
```

Mind that `with` is exactly under `test`



_Code quote:_
```Python
    """test proper initialization of FioRunner object
        with all mandatory parameters"""
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5V5pz97B7D_53mIMl:-Ms5V5pz97B7D_53mIMm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L22)):*
> ```Python
> 
> def test_IbReadRunner_init(monkeypatch):
>     """test proper initialization of IbReadRunner object with all mandatory param"""
> ```

.



_Code quote:_
```Python
all mandatory param
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 30 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5V8Ar3Hsx4MfYSzq4:-Ms5V8Ar3Hsx4MfYSzq5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L30)):*
> ```Python
>     def run_sync_mock(arg1, arg2) ->RemoteCmd:
>         remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
>         return remoteCmd
> ```

.



_Code quote:_
```Python
    def which_mock(path: str) ->str:
        assert path == 'ib_read_lat'
        return path
    monkeypatch.setattr(shutil, 'which', which_mock)

    def run_sync_mock(arg1, arg2) ->RemoteCmd:
        remoteCmd = RemoteCmd(None, None, None, exit_status = 0)
        return remoteCmd
    monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 36 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5VBcE-Eox0tKmiHT0:-Ms5VBcE-Eox0tKmiHT1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L36)):*
> ```Python
>                 'rw': 'read', 'filetype': 'malloc',
>                 'requirements' : {'direct_write_to_pmem': True}}
>     config = {'server_ip':'server_ip'}
> ```

.



_Code quote:_
```Python
 config = {'server_ip':'server_ip'}
```


<!-- Sent from Reviewable.io -->

2021-12-29 14:17 UTC, grom72 reviewed
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 27 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5UFXN-zvV6JlyZC3K:-Ms5WqM4Ct1yAYfCQCG2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use the following style:
```
"""test proper initialization of FioRunner object
   with all mandatory parameters
"""
```

Mind that `with` is exactly under `test`
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5V5pz97B7D_53mIMl:-Ms5YG356e4MhFYwuGwp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 30 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5V8Ar3Hsx4MfYSzq4:-Ms5XcrqBIk0dXalSm9U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 36 at r6](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5VBcE-Eox0tKmiHT0:-Ms5XdN25iGsdSpqQ9VL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fcfc9bacaeea66cae1874ff2787edf905ce37981/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-29 14:17 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 14:20 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 5 at r7](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5Yrrh6-2pc5OH1yyI):*
Something is wrong here (3 commits instead of 2)



_Code quote:_
```
- f05e9f2: tools: small fixes in runners initialization

- e1ce6ca: tools: small fixes in runners initialization
```


<!-- Sent from Reviewable.io -->

2021-12-29 14:21 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-29 14:22 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 31 at r7](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5ZW2b2dXJouIj0gK7:-Ms5ZW2b2dXJouIj0gK8:bsme79d) ([raw file](https://github.com/pmem/rpma/blob/7a7aee843fcf9b8e88bdad6fd367a18586698dd6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L31)):*
> ```Python
>         return path
>     def run_sync_mock(arg1, arg2) -> RemoteCmd:
>         return = RemoteCmd(None, None, None, exit_status = 0)
> ```

`return RemoteCmd`



_Code quote:_
```Python
return = RemoteCmd
```


<!-- Sent from Reviewable.io -->

2021-12-29 14:26 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 5 at r7](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5Yrrh6-2pc5OH1yyI):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Something is wrong here (3 commits instead of 2)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-29 14:27 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 31 at r7](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5ZW2b2dXJouIj0gK7:-Ms5_kLZ-FjN8fGKlv_U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a7aee843fcf9b8e88bdad6fd367a18586698dd6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`return RemoteCmd`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-29 14:28 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 15:09 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452#-:-Ms5jKaO5jBS0Ei8fATK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-29 15:20 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-29 15:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5uVq-AG4J2Ep77V4Q:-Ms5uVq-AG4J2Ep77V4R:bb0g7ut) (no related file):*
Rebase please (the commit "`tools: run pylint on the tests of the runners`" is required)

---


<!-- Sent from Reviewable.io -->

2021-12-29 15:59 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-29 16:14 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5uVq-AG4J2Ep77V4Q:-Ms5y7G419jaBNqt7-jM:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please (the commit "`tools: run pylint on the tests of the runners`" is required)
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-12-29 16:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5z6nN2RI36TNkgg2l:-Ms5z6nO9O-iYAq9y4m_:b-v3kov0) (no related file):*
CI builds fail

---


<!-- Sent from Reviewable.io -->

2021-12-30 08:11 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 7 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9MKR1-FNgQb6PgLhk:-Ms9MKR1-FNgQb6PgLhl:br2st3j) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L7)):*
> ```Python
> #
> 
> """test_fiorunner_init.py -- lib.benchmark.runner.FioRunner init tests"""
> ```

`test_ib_read_runner_init.py` and `test_fio_runner_init.py`

or

`test_ibreadrunner_init.py` and `test_fiorunner_init.py`



_Code quote:_
```Python
test_fiorunner_init.py
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 11 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9Iq0V1LMnBA8PtLGE:-Ms9Iq0WEggUQka2YlC-:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L11)):*
> ```Python
> import shutil
> 
> import pytest
> ```

redundant empty line



_Code quote:_
```Python
import shutil

import pytest
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 20 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9KmwIA0RhQVMwpQio:-Ms9KmwIA0RhQVMwpQip:b-gkrwgt) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L20)):*
> ```Python
> from lib.benchmark.runner.fio import FioRunner
> 
> CONFIG_MINI = {'server_ip':'server_ip', 'FIO_PATH' : '/tmp'}
> ```

a space between `:` or not ? - please be consistent



_Code quote:_
```Python
{'server_ip':'server_ip', 'FIO_PATH' : '/tmp'}
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 30 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9NYw-8w-VJrxuiWNX:-Ms9NYw-8w-VJrxuiWNY:bn5yqyd) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L30)):*
> ```Python
>         return path
> 
>     #pylint: disable=unused-argument
> ```

not needed, please use `_arg1, _arg2` and `_self` instead



_Code quote:_
```Python
#pylint: disable=unused-argument
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 36 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9Nlct0uSIW1qhQD8M:-Ms9Nlct0uSIW1qhQD8N:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L36)):*
> ```Python
>     def run_mock(self) -> None:
>         pass
>     #pylint: enable=unused-argument
> ```

.



_Code quote:_
```Python
 #pylint: enable=unused-argument
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 7 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9Mh4D-89qlg-ARV8H:-Ms9Mh4D-89qlg-ARV8I:br2st3j) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L7)):*
> ```Python
> #
> 
> """test_ib_read_runner_init.py -- lib.benchmark.runner.ib_read init tests"""
> ```

`test_ib_read_runner_init.py` and `test_fio_runner_init.py`

or

`test_ibreadrunner_init.py` and `test_fiorunner_init.py`



_Code quote:_
```Python
test_ib_read_runner_init.py
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 30 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9O8Xn20pbVhg4Gf50:-Ms9O8Xn20pbVhg4Gf51:bn5yqyd) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L30)):*
> ```Python
>         return path
> 
>     #pylint: disable=unused-argument
> ```

not needed, please use `_arg1, _arg2` and `_self` instead



_Code quote:_
```Python
#pylint: disable=unused-argument
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 36 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9OAVLCeH2AWT2pf9t:-Ms9OAVLCeH2AWT2pf9u:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L36)):*
> ```Python
>     def run_mock(self) -> None:
>         pass
>     #pylint: enable=unused-argument
> ```

.



_Code quote:_
```Python
 #pylint: enable=unused-argument
```


<!-- Sent from Reviewable.io -->

2021-12-30 09:50 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 7 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9Mh4D-89qlg-ARV8H:-Ms9hMtvCLiVTtLfYY5c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`test_ib_read_runner_init.py` and `test_fio_runner_init.py`

or

`test_ibreadrunner_init.py` and `test_fiorunner_init.py`

</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 30 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9O8Xn20pbVhg4Gf50:-Ms9hNjNC62VOpu95HgV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed, please use `_arg1, _arg2` and `_self` instead
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 36 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9OAVLCeH2AWT2pf9t:-Ms9hODP39UU0R5nZo_6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 7 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9MKR1-FNgQb6PgLhk:-Ms9gRp82_TzrWuPc1z-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`test_ib_read_runner_init.py` and `test_fio_runner_init.py`

or

`test_ibreadrunner_init.py` and `test_fiorunner_init.py`

</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 11 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9Iq0V1LMnBA8PtLGE:-Ms9g_D71dJ2x75H3ZPY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 20 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9KmwIA0RhQVMwpQio:-Ms9jtJc5JxoXy54AgDm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a space between `:` or not ? - please be consistent
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 30 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9NYw-8w-VJrxuiWNX:-Ms9hD1y0ISvTAwcGuP7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed, please use `_arg1, _arg2` and `_self` instead
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py, line 36 at r11](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9Nlct0uSIW1qhQD8M:-Ms9hLek20-r28w_j8jZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b54228b61384f96d1f487c9030d7a2fe6a4dab6/tools/perf/tests/lib/benchmark/runner/test_fiorunner_init.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-30 09:54 UTC, ldorau requested changes

2021-12-30 09:54 UTC, ldorau commented on tools/perf/lib/benchmark/runner/fio.py
> -
This line should be left

2021-12-30 09:54 UTC, ldorau commented on tools/perf/lib/benchmark/runner/fio.py
>          self.__direct_write_to_pmem = \
There should be no changes in this file in this commit. This commit only adds unit tests.

2021-12-30 09:54 UTC, ldorau commented on tools/perf/lib/benchmark/runner/ib_read.py
> +        if 'mode' not in self.__benchmark.oneseries:
There should be no changes in this file in this commit. This commit only adds unit tests.

2021-12-30 09:56 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-Ms5z6nN2RI36TNkgg2l:-Ms9lJt21sdHf3DF8vgu:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds fail
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-12-30 09:59 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 20 at r12](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lk2H9GkmTGr1WXOn:-Ms9lk2H9GkmTGr1WXOo:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/45df20dd3e3b91adbb326f7dca7e1ddd5508c678/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L20)):*
> ```Python
> from lib.benchmark.runner.ib_read import IbReadRunner
> 
> CONFIG_MINI = {'server_ip':'server_ip'}
> ```

missing space



_Code quote:_
```Python
{'server_ip':'server_ip'}
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 81 at r12](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9loSqAjBNIsg6v6Mt:-Ms9loSqAjBNIsg6v6Mu:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/45df20dd3e3b91adbb326f7dca7e1ddd5508c678/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L81)):*
> ```Python
> def test_ib_read_runner_init_oneserises_no_filetype():
>     """failed initialization of IbReadRunner object - no mode rw provided """
>     oneseries = {'tool': 'ib_read', 'mode': 'lat', 'rw':'read'}
> ```

missing space



_Code quote:_
```Python
'rw':'read'
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 90 at r12](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lpwfEl-C7-3GBUsS:-Ms9lpwfEl-C7-3GBUsT:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/45df20dd3e3b91adbb326f7dca7e1ddd5508c678/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L90)):*
> ```Python
>     """failed initialization of IbReadRunner object - no config provided """
>     oneseries = {'tool': 'ib_read', 'mode': 'lat',
>                  'rw':'read', 'filetype': 'malloc',
> ```

missing space



_Code quote:_
```Python
'rw':'read'
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 92 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lc0gAqRdKhJaOeCP:-Ms9lc0gAqRdKhJaOeCQ:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/86758da54bd61053321a8dc8c80acfdbdb0f47dc/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L92)):*
> ```Python
>     """failed initialization of FioRunner object - no requirements provided """
>     oneseries = {'tool': 'fio', 'tool_mode': 'apm', 'mode': 'lat',
>                  'rw':'readwrite', 'filetype': 'malloc'}
> ```

missing space



_Code quote:_
```Python
'rw':'readwrite'
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 102 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9ldy6-Ilt0C7TzJFU:-Ms9ldy7DtC1P7ufZSfC:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/86758da54bd61053321a8dc8c80acfdbdb0f47dc/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L102)):*
> ```Python
>     oneseries = {'tool': 'fio', 'tool_mode': 'apm', 'mode': 'lat',
>                  'rw':'readwrite', 'filetype': 'malloc',
>                  'requirements': {}}
> ```

missing space



_Code quote:_
```Python
'rw':'readwrite'
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 111 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lfgC-rNKUxFAAgGA:-Ms9lfgC-rNKUxFAAgGB:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/86758da54bd61053321a8dc8c80acfdbdb0f47dc/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L111)):*
> ```Python
>     """failed initialization of FioRunner object - no config provided """
>     oneseries = {'tool': 'fio', 'tool_mode': 'apm', 'mode': 'lat',
>                  'rw':'readwrite', 'filetype': 'malloc',
> ```

missing space



_Code quote:_
```Python
'rw':'readwrite',
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 122 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lhVw64E_d7ZWzP60:-Ms9lhVw64E_d7ZWzP61:b-6fac61) ([raw file](https://github.com/pmem/rpma/blob/86758da54bd61053321a8dc8c80acfdbdb0f47dc/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L122)):*
> ```Python
>        - no server_ip in config provided """
>     oneseries = {'tool': 'fio', 'tool_mode': 'apm', 'mode': 'lat',
>                  'rw':'readwrite', 'filetype': 'malloc',
> ```

missing space



_Code quote:_
```Python
'rw':'readwrite'
```


<!-- Sent from Reviewable.io -->

2021-12-30 11:13 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 2 of 11 files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 20 at r12](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lk2H9GkmTGr1WXOn:-MsA1h_P7tMuokB8yjB0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45df20dd3e3b91adbb326f7dca7e1ddd5508c678/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 81 at r12](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9loSqAjBNIsg6v6Mt:-MsA1i8S3A0YrZz8Ik89:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45df20dd3e3b91adbb326f7dca7e1ddd5508c678/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 90 at r12](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lpwfEl-C7-3GBUsS:-MsA1iiX5k4-PqUupVyj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45df20dd3e3b91adbb326f7dca7e1ddd5508c678/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 92 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lc0gAqRdKhJaOeCP:-MsA1dyE5YMTl1GTeh2h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63dbc67aafaa394e80633ca8345ad6390f781348/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 102 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9ldy6-Ilt0C7TzJFU:-MsA1f8rC3fr99_SqOJr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63dbc67aafaa394e80633ca8345ad6390f781348/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 111 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lfgC-rNKUxFAAgGA:-MsA1fjiCWPpcHZFWKED:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63dbc67aafaa394e80633ca8345ad6390f781348/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L111)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 122 at r13](https://reviewable.io/reviews/pmem/rpma/1452#-Ms9lhVw64E_d7ZWzP60:-MsA1gL--WuhSAGFYk2g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63dbc67aafaa394e80633ca8345ad6390f781348/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L122)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-30 11:49 UTC, ldorau approved these changes
> Reviewed 2 of 9 files at r14, 7 of 7 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-30 12:07 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-30 13:00 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAQ9eZ9Mrxcd_aH_Sb:-MsAQ9eZ9Mrxcd_aH_Sc:brqqfkz) (no related file):*
Please rebase and change an author, this commit is a merge commit:
```
commit fccbb6fd99640e4b54679b1ba4f31e89fbde9f80 (HEAD -> ut-for-runners-init)
Merge: ce77c752 5371f2be
Author: Lukasz Dorau <lukasz.dorau@intel.com>
Date:   Thu Dec 30 12:55:51 2021 +0100

    tools: runners initialization unit tests
```

---


<!-- Sent from Reviewable.io -->

2021-12-30 13:09 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAQ9eZ9Mrxcd_aH_Sb:-MsASKm3CGcYtCU8lp1M:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase and change an author, this commit is a merge commit:
```
commit fccbb6fd99640e4b54679b1ba4f31e89fbde9f80 (HEAD -> ut-for-runners-init)
Merge: ce77c752 5371f2be
Author: Lukasz Dorau <lukasz.dorau@intel.com>
Date:   Thu Dec 30 12:55:51 2021 +0100

    tools: runners initialization unit tests
```
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-12-30 13:16 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsATpSY1bpk8UW7BoVi:-MsATpSY1bpk8UW7BoVj:b8il7hb) (no related file):*
There are more pylint errors:
https://github.com/ldorau/rpma/runs/4666907767
```
************* Module tests.lib.benchmark.runner.test_fio_runner_init
C: 26, 4: Missing function docstring (missing-docstring)
C: 30, 4: Missing function docstring (missing-docstring)
C: 33, 4: Missing function docstring (missing-docstring)
C: 49, 0: Function name "test_fio_runner_init_oneserises_no_tool" doesn't conform to snake_case naming style (invalid-name)
C: 57, 0: Function name "test_fio_runner_init_oneserises_no_toolmode" doesn't conform to snake_case naming style (invalid-name)
C: 65, 0: Function name "test_fio_runner_init_oneserises_no_mode" doesn't conform to snake_case naming style (invalid-name)
C: 73, 0: Function name "test_fio_runner_init_oneserises_no_rw" doesn't conform to snake_case naming style (invalid-name)
C: 81, 0: Function name "test_fio_runner_init_oneserises_no_filetype" doesn't conform to snake_case naming style (invalid-name)
C: 89, 0: Function name "test_fio_runner_init_oneserises_no_requirements" doesn't conform to snake_case naming style (invalid-name)
C: 98, 0: Function name "test_fio_runner_init_oneserises_no_requirements_direct_write_to_pmem" doesn't conform to snake_case naming style (invalid-name)
C:118, 0: Function name "test_fio_runner_init_config_no_fio_path" doesn't conform to snake_case naming style (invalid-name)
C:130, 0: Function name "test_fio_runner_init_config_no_server_ip" doesn't conform to snake_case naming style (invalid-name)
C:133, 4: Missing function docstring (missing-docstring)
************* Module tests.lib.benchmark.runner.test_ib_read_runner_init
C: 26, 4: Missing function docstring (missing-docstring)
C: 30, 4: Missing function docstring (missing-docstring)
C: 33, 4: Missing function docstring (missing-docstring)
C: 48, 0: Function name "test_ib_read_runner_init_oneserises_no_tool" doesn't conform to snake_case naming style (invalid-name)
C: 55, 0: Function name "test_ib_read_runner_init_oneserises_no_toolmode" doesn't conform to snake_case naming style (invalid-name)
C: 63, 0: Function name "test_ib_read_runner_init_oneserises_no_mode" doesn't conform to snake_case naming style (invalid-name)
C: 71, 0: Function name "test_ib_read_runner_init_oneserises_no_rw" doesn't conform to snake_case naming style (invalid-name)
C: 79, 0: Function name "test_ib_read_runner_init_oneserises_no_filetype" doesn't conform to snake_case naming style (invalid-name)
C: 87, 0: Function name "test_ib_read_runner_init_no_config" doesn't conform to snake_case naming style (invalid-name)
C: 97, 0: Function name "test_ib_read_runner_init_config_no_server_ip" doesn't conform to snake_case naming style (invalid-name)
C:100, 4: Missing function docstring (missing-docstring)

-----------------------------------
Your code has been rated at 9.85/10
```

---


<!-- Sent from Reviewable.io -->

2021-12-30 13:21 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 82 at r20](https://reviewable.io/reviews/pmem/rpma/1452#-MsAV-fQD355goQ8sIrl:-MsAV-fQD355goQ8sIrm:bk3cstv) ([raw file](https://github.com/pmem/rpma/blob/28691d14452bca0446d719c758a15ab6013d4eaa/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L82)):*
> ```Python
> 
> def test_fio_runner_init_oneserises_no_filetype():
>     """failed initialization of FioRunner object - no mode rw provided """
> ```

no filetype provided
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 83 at r20](https://reviewable.io/reviews/pmem/rpma/1452#-MsAUphb3nnF9sjJW_4i:-MsAUphcAgaVIIL1yiqI:b8x54vu) ([raw file](https://github.com/pmem/rpma/blob/28691d14452bca0446d719c758a15ab6013d4eaa/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L83)):*
> ```Python
> def test_fio_runner_init_oneserises_no_filetype():
>     """failed initialization of FioRunner object - no mode rw provided """
>     oneseries = {'tool': 'fio', 'tool_mode': 'apm', 'mode': 'lat'}
> ```

missing 'rw'


<!-- Sent from Reviewable.io -->

2021-12-30 13:59 UTC, grom72 reviewed
> Reviewed 1 of 9 files at r14, 3 of 7 files at r15, 2 of 2 files at r18, 1 of 2 files at r22, 1 of 1 files at r23, 1 of 1 files at r24.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsATpSY1bpk8UW7BoVi:-MsAWtRR5uGVnssUsDnt:bqqoqh3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There are more pylint errors:
https://github.com/ldorau/rpma/runs/4666907767
```
************* Module tests.lib.benchmark.runner.test_fio_runner_init
C: 26, 4: Missing function docstring (missing-docstring)
C: 30, 4: Missing function docstring (missing-docstring)
C: 33, 4: Missing function docstring (missing-docstring)
C: 49, 0: Function name "test_fio_runner_init_oneserises_no_tool" doesn't conform to snake_case naming style (invalid-name)
C: 57, 0: Function name "test_fio_runner_init_oneserises_no_toolmode" doesn't conform to snake_case naming style (invalid-name)
C: 65, 0: Function name "test_fio_runner_init_oneserises_no_mode" doesn't conform to snake_case naming style (invalid-name)
C: 73, 0: Function name "test_fio_runner_init_oneserises_no_rw" doesn't conform to snake_case naming style (invalid-name)
C: 81, 0: Function name "test_fio_runner_init_oneserises_no_filetype" doesn't conform to snake_case naming style (invalid-name)
C: 89, 0: Function name "test_fio_runner_init_oneserises_no_requirements" doesn't conform to snake_case naming style (invalid-name)
C: 98, 0: Function name "test_fio_runner_init_oneserises_no_requirements_direct_write_to_pmem" doesn't conform to snake_case naming style (invalid-name)
C:118, 0: Function name "test_fio_runner_init_config_no_fio_path" doesn't conform to snake_case naming style (invalid-name)
C:130, 0: Function name "test_fio_runner_init_config_no_server_ip" doesn't conform to snake_case naming style (invalid-name)
C:133, 4: Missing function docstring (missing-docstring)
************* Module tests.lib.benchmark.runner.test_ib_read_runner_init
C: 26, 4: Missing function docstring (missing-docstring)
C: 30, 4: Missing function docstring (missing-docstring)
C: 33, 4: Missing function docstring (missing-docstring)
C: 48, 0: Function name "test_ib_read_runner_init_oneserises_no_tool" doesn't conform to snake_case naming style (invalid-name)
C: 55, 0: Function name "test_ib_read_runner_init_oneserises_no_toolmode" doesn't conform to snake_case naming style (invalid-name)
C: 63, 0: Function name "test_ib_read_runner_init_oneserises_no_mode" doesn't conform to snake_case naming style (invalid-name)
C: 71, 0: Function name "test_ib_read_runner_init_oneserises_no_rw" doesn't conform to snake_case naming style (invalid-name)
C: 79, 0: Function name "test_ib_read_runner_init_oneserises_no_filetype" doesn't conform to snake_case naming style (invalid-name)
C: 87, 0: Function name "test_ib_read_runner_init_no_config" doesn't conform to snake_case naming style (invalid-name)
C: 97, 0: Function name "test_ib_read_runner_init_config_no_server_ip" doesn't conform to snake_case naming style (invalid-name)
C:100, 4: Missing function docstring (missing-docstring)

-----------------------------------
Your code has been rated at 9.85/10
```

</blockquote></details>

All "Missing function docstring (missing-docstring) " fixed.
The rest fixed in #1465 

---
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 82 at r20](https://reviewable.io/reviews/pmem/rpma/1452#-MsAV-fQD355goQ8sIrl:-MsAXWZBDMRqziiwYWV6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28691d14452bca0446d719c758a15ab6013d4eaa/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L82)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

no filetype provided
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 83 at r20](https://reviewable.io/reviews/pmem/rpma/1452#-MsAUphb3nnF9sjJW_4i:-MsAXX-i-ZmKdxDzcpXo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28691d14452bca0446d719c758a15ab6013d4eaa/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L83)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

missing 'rw'
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-30 14:05 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-30 14:15 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfWTn7ra5T8qpqma6:-MsAfWTn7ra5T8qpqma7:b-49dczg) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L8)):*
> ```Python
> 
> """test_ib_read_runner_init.py
>    -- lib.benchmark.runner.ib_read.IBReadRunner init tests"""
> ```

IbReadRunner
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 74 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAg9wfAXHqPSnSr7Tm:-MsAg9wfAXHqPSnSr7Tn:b-1lt7lh) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L74)):*
> ```Python
> def test_ib_read_runner_init_oneserises_no_rw():
>     """failed initialization of IbReadRunner object - no rw provided """
>     oneseries = {'tool': 'ib_read', 'mode': 'lat'}
> ```

missing tool_mode
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 82 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAgEpO4_Id7-ClaGN-:-MsAgEpO4_Id7-ClaGN0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L82)):*
> ```Python
> def test_ib_read_runner_init_oneserises_no_filetype():
>     """failed initialization of IbReadRunner object - no filetype provided """
>     oneseries = {'tool': 'ib_read', 'mode': 'lat', 'rw': 'read'}
> ```

.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 90 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAgNxl50hRW6TR31q2:-MsAgNxl50hRW6TR31q3:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L90)):*
> ```Python
> def test_ib_read_runner_init_no_config():
>     """failed initialization of IbReadRunner object - no config provided """
>     oneseries = {'tool': 'ib_read', 'mode': 'lat',
> ```

.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 103 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAgP9J0ilXkVt4Ln8w:-MsAgP9J0ilXkVt4Ln8x:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L103)):*
> ```Python
>     monkeypatch.setattr(shutil, 'which', which_mock)
> 
>     oneseries = {'tool': 'ib_read', 'mode': 'lat',
> ```

.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 123 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfAuE-UHUvNm6Udmr:-MsAfAuE-UHUvNm6Udms:boepzum) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L123)):*
> ```Python
> def test_fio_runner_init_config_no_fio_path():
>     """failed initialization of FioRunner object -
>        - no server_ip in config provided """
> ```

fio path


<!-- Sent from Reviewable.io -->

2021-12-30 14:22 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-30 14:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAiJbb3M2x4E8MDp71:-MsAiJbb3M2x4E8MDp72:b-ujmq67) (no related file):*
Rebase please

---


<!-- Sent from Reviewable.io -->

2021-12-30 14:29 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfWTn7ra5T8qpqma6:-MsAjaJC5mSnozOgOkCn:b3kre) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L8)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

IbReadRunner
</blockquote></details>

?


<!-- Sent from Reviewable.io -->

2021-12-30 14:37 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-30 14:40 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfWTn7ra5T8qpqma6:-MsAm3336qj1O4P3OKAl:b-pwygtb) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

?
</blockquote></details>

lib.benchmark.runner.ib_read.**IBReadRunner** init tests



_Code quote:_
```Python
lib.benchmark.runner.ib_read.IBReadRunner init tests
```


<!-- Sent from Reviewable.io -->

2021-12-30 14:41 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfWTn7ra5T8qpqma6:-MsAmNLz3BKTbKHW8tme:b-hxu4a) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L8)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

lib.benchmark.runner.ib_read.**IBReadRunner** init tests
</blockquote></details>

IB -> Ib


<!-- Sent from Reviewable.io -->

2021-12-30 14:46 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-30 14:51 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r27.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAiJbb3M2x4E8MDp71:-MsAlDSKAI5tr5OcY33G:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfWTn7ra5T8qpqma6:-MsAmw697EhNH2Pbamay:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IB -> Ib
</blockquote></details>

Done.



_Code quote (from -- commits):_
```
runners initialization unit tests
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 74 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAg9wfAXHqPSnSr7Tm:-MsAmztGEyxv5XHvzUa0:b-k3phah) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L74)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

missing tool_mode
</blockquote></details>

tool _mode removed as not needed yet
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 82 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAgEpO4_Id7-ClaGN-:-MsAjiX0CwDcxu4sTA9V:bpv8bmv) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L82)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

tool_mode is not required
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 90 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAgNxl50hRW6TR31q2:-MsAjn-T-fO8bP88krL_:bkjxeyr) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L90)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

tool_mode is not required
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 103 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAgP9J0ilXkVt4Ln8w:-MsAjo074ZjCobBOAI92:bpv8bmv) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L103)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

tool_mode is not required


<!-- Sent from Reviewable.io -->

2021-12-30 14:51 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 123 at r24](https://reviewable.io/reviews/pmem/rpma/1452#-MsAfAuE-UHUvNm6Udmr:-MsAokkc-PmtjVEE3ADJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a5d5a24993211f1f79dea5696f3597275725a400/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L123)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

fio path
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-30 14:52 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-30 14:53 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r28, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-12-30 14:59 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452#-:-MsAqav9DmJ-yQdlcwlj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-30 15:01 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-12-30 15:35 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAxdFU0l5efxK7N3nR:-MsAxdFU0l5efxK7N3nS:b-gvq1yq) (no related file):*
Most of the unit tests can be defined as a one `def` using `@pytest.mark.parametrize()`:
1) all `*_no_*` tests can be defined using only one `def`
2) `*_wrong_*` tests (defined using only one `def`) should be added to test incorrect values of keys (they are missing now)

---


<!-- Sent from Reviewable.io -->

2021-12-30 15:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAxdFU0l5efxK7N3nR:-MsAz2Sl6Rvrwh9YeLMC:b8y8nel) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Most of the unit tests can be defined as a one `def` using `@pytest.mark.parametrize()`:
1) all `*_no_*` tests can be defined using only one `def`
2) `*_wrong_*` tests (defined using only one `def`) should be added to test incorrect values of keys (they are missing now)
</blockquote></details>

Please see https://github.com/pmem/rpma/pull/1448 for details

---


<!-- Sent from Reviewable.io -->

2021-12-30 18:16 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsAxdFU0l5efxK7N3nR:-MsBYZ6R4VRUUR3XJgLE:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please see https://github.com/pmem/rpma/pull/1448 for details
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-12-31 17:12 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r29, 3 of 4 files at r30, 2 of 2 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-03 13:01 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r29, 1 of 1 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-03 13:47 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsVAxz22Llz0tQQYeaO:-MsVAxz22Llz0tQQYeaP:bofmlb3) (no related file):*
It seems that the last 3 commits should be squashed, because the commits:
- https://github.com/pmem/rpma/pull/1452/commits/472c9dc3812c7009733d22209a14b2d7b4330ccb and
- https://github.com/pmem/rpma/pull/1452/commits/16882b96b79f9e6b8f17bb2155efa1d70e6714db

are fixes to https://github.com/pmem/rpma/pull/1452/commits/456b86de2a9e4621f5316e163a050c39c44e6009

---


<!-- Sent from Reviewable.io -->

2022-01-03 13:52 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-03 13:54 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 88 at r32](https://reviewable.io/reviews/pmem/rpma/1452#-MsVCj2L3mHPNMvR9rVm:-MsVCj2L3mHPNMvR9rVn:b-w00mrj) ([raw file](https://github.com/pmem/rpma/blob/16882b96b79f9e6b8f17bb2155efa1d70e6714db/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L88)):*
> ```Python
> 
> @pytest.mark.parametrize('key', ['server_ip', 'FIO_PATH'])
> def test_fio_runner_init_config_incomplete(oneseries_fio, config_fio, key):
> ```

```
FAILED tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py::test_fio_runner_init_config_incomplete[FIO_PATH] - socket.gaierror: [Errno -2] Name or service not known
```



_Code quote:_
```Python
@pytest.mark.parametrize('key', ['server_ip', 'FIO_PATH'])
def test_fio_runner_init_config_incomplete(oneseries_fio, config_fio, key):
```


<!-- Sent from Reviewable.io -->

2022-01-03 15:25 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r30, 1 of 2 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 13 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsVX5Hv9dDLwzlXHkAj:-MsVX5Hv9dDLwzlXHkAk:b8sursm) (no related file):*
CI builds errors: https://github.com/ldorau/rpma/runs/4692493486

---
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 122 at r34](https://reviewable.io/reviews/pmem/rpma/1452#-MsVXi-vDNMD_bktp_zS:-MsVXi-vDNMD_bktp_zT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/513201f00343136d98270c9e0b887094433e6834/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L122)):*
> ```Python
>     oneseries.pop(key)
>     oneseries[key] = '!@#$%^)(*&dsaf;a;ljka;sdfja'
>     benchmark = lib.benchmark.Benchmark(oneseries)
> ```

.



_Code quote:_
```Python
'!@#$%^)(*&dsaf;a;ljka;sdfja'
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 60 at r34](https://reviewable.io/reviews/pmem/rpma/1452#-MsVXG7GAwkqp-ewT3LX:-MsVXG7GAwkqp-ewT3LY:b-g513v8) ([raw file](https://github.com/pmem/rpma/blob/513201f00343136d98270c9e0b887094433e6834/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L60)):*
> ```Python
> 
> @pytest.mark.parametrize('key', ['tool', 'tool_mode', 'mode', 'rw', \
>                          'busy_wait_polling', 'filetype', 'requirements'])
> ```

'busy_wait_polling' is not required



_Code quote:_
```Python
'busy_wait_polling'
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 102 at r34](https://reviewable.io/reviews/pmem/rpma/1452#-MsVXLzUCG2s6HMERP2v:-MsVXLzUCG2s6HMERP2w:bpxjij1) ([raw file](https://github.com/pmem/rpma/blob/513201f00343136d98270c9e0b887094433e6834/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L102)):*
> ```Python
>        - no fio_path in config provided """
>     oneseries_fio.pop(key)
>     oneseries_fio[key] = '!@#$%^)(*&dsaf;a;ljka;sdfja'
> ```

please use just `'an incorrect value'`



_Code quote:_
```Python
'!@#$%^)(*&dsaf;a;ljka;sdfja'
```


<!-- Sent from Reviewable.io -->

2022-01-03 15:25 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r31, 2 of 2 files at r33.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 16:29 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 122 at r34](https://reviewable.io/reviews/pmem/rpma/1452#-MsVXi-vDNMD_bktp_zS:-MsVlT4N7HqjgsrRjq3_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/513201f00343136d98270c9e0b887094433e6834/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L122)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 60 at r34](https://reviewable.io/reviews/pmem/rpma/1452#-MsVXG7GAwkqp-ewT3LX:-MsVjSQq-K_-pGAn8K1I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/513201f00343136d98270c9e0b887094433e6834/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

'busy_wait_polling' is not required
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 102 at r34](https://reviewable.io/reviews/pmem/rpma/1452#-MsVXLzUCG2s6HMERP2v:-MsVlS-K3yuPPNSqJp_n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/513201f00343136d98270c9e0b887094433e6834/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

please use just `'an incorrect value'`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-03 17:21 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r35, 1 of 1 files at r36, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsVX5Hv9dDLwzlXHkAj:-MsVwn5u02RfeidrXn95:b-uaq83e) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds errors: https://github.com/ldorau/rpma/runs/4692493486
</blockquote></details>

Should work now.
If not we should reconsider old OS support with pylint

---
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 88 at r32](https://reviewable.io/reviews/pmem/rpma/1452#-MsVCj2L3mHPNMvR9rVm:-MsVsC_q6LfXhiTd7-Zg:bkbkkdf) ([raw file](https://github.com/pmem/rpma/blob/16882b96b79f9e6b8f17bb2155efa1d70e6714db/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L88)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
FAILED tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py::test_fio_runner_init_config_incomplete[FIO_PATH] - socket.gaierror: [Errno -2] Name or service not known
```

</blockquote></details>

Done.
FIO_PATH testing moved to test_fio_runner_init()


<!-- Sent from Reviewable.io -->

2022-01-04 07:07 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsVX5Hv9dDLwzlXHkAj:-MsYqfWu0BO4qI391jLy:bre2d37) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Should work now.
If not we should reconsider old OS support with pylint
</blockquote></details>

One fix is required: https://github.com/pmem/rpma/pull/1473

It works now: https://github.com/ldorau/rpma/actions/runs/1652441839

---
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 60 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYjmC81q7n9JMwb_D3:-MsYjmC81q7n9JMwb_D4:b-eu27xz) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L60)):*
> ```Python
>     #pylint: enable=protected-access
> 
> # XXX 'requirements' and 'tool_mode' are not yet suported by ib_read_runner
> ```

supported



_Code quote:_
```Python
suported 
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 97 at r31](https://reviewable.io/reviews/pmem/rpma/1452#-MsYuC3H69RCmGg6xSBn:-MsYuC3I1gtoyNvmMqRy:b-hf43ng) ([raw file](https://github.com/pmem/rpma/blob/cbbaef0187d4dc25b28f1043ef8eb4634df7bf6a/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L97)):*
> ```Python
> 
> @pytest.mark.parametrize('key', ['tool', 'tool_mode', 'mode', 'rw',
>                                  'filetype'])
> ```

```
FAILED tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py::test_fio_runner_init_wrong_value[tool] - socket.gaierror: [Errno -2] Name or service not known
```

This test runs real `RemoteCmd.run_sync` with `host = 'server_ip'`



_Code quote:_
```Python
@pytest.mark.parametrize('key', ['tool', 'tool_mode', 'mode', 'rw',
                                 'filetype'])
def test_fio_runner_init_wrong_value(oneseries_fio, config_fio, key):
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 31 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYkaJK2obDhM5HZlRu:-MsYkaJK2obDhM5HZlRv:bpeqajl) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L31)):*
> ```Python
> def test_fio_runner_init(oneseries_fio, config_fio, fio_path, monkeypatch):
>     """test proper initialization of FioRunner object
>        with all mandatory parameters"""
> ```

```
    """test proper initialization of FioRunner object
       with all mandatory parameters
    """
```



_Code quote:_
```Python
    """test proper initialization of FioRunner object
       with all mandatory parameters"""
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 39 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYiyd-0Y5BrLio7j2D:-MsYiyd-0Y5BrLio7j2E:b-kuhqzh) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L39)):*
> ```Python
>         """mock of IbReadRunner.run()"""
> 
>     def which_mock(path: str) ->str:
> ```

`-> str:`



_Code quote:_
```Python
->str:
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 53 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYknkl4ApQoxymIiKh:-MsYknkl4ApQoxymIiKi:b-h4wb03) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L53)):*
> ```Python
>     monkeypatch.setattr(shutil, 'which', which_mock)
>     monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)
>     monkeypatch.setattr(FioRunner, 'run', run_mock)
> ```

Please move these lines just after mocks



_Code quote:_
```Python
    monkeypatch.setattr(shutil, 'which', which_mock)
    monkeypatch.setattr(RemoteCmd, 'run_sync', run_sync_mock)
    monkeypatch.setattr(FioRunner, 'run', run_mock)
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 73 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYjfagDrAQUHl-6fXz:-MsYjfagDrAQUHl-6fY-:bus13j7) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L73)):*
> ```Python
>                          'filetype', 'requirements'])
> def test_fio_runner_init_oneserises_incomplete(oneseries_fio, config_fio, key):
>     """failed initialization of FioRunner object - incomlete oneseries """
> ```

incomplete



_Code quote:_
```Python
incomlete
```


<!-- Sent from Reviewable.io -->

2022-01-04 07:12 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 49 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYvGSk-RR84mExEie4:-MsYvGSlE08pweBUM0A0:bepbkel) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L49)):*
> ```Python
>         config_fio.pop('FIO_PATH')
>         config_fio['FIO_PATH'] = fio_path
>         fio_path_full = join(fio_path, 'fio')
> ```

I do not understand the purpose of this code.
1) I suppose it should be moved to `which_mock`
2) You should NOT modify config_fio['FIO_PATH']



_Code quote:_
```Python
    if fio_path == '':
        fio_path_full = 'fio'
    else:
        config_fio.pop('FIO_PATH')
        config_fio['FIO_PATH'] = fio_path
        fio_path_full = join(fio_path, 'fio')
```


<!-- Sent from Reviewable.io -->

2022-01-04 07:23 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r36.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 76 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYxPfF58k512DRh6om:-MsYxPfF58k512DRh6on:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L76)):*
> ```Python
>     oneseries_fio.pop(key)
>     benchmark = lib.benchmark.Benchmark(oneseries_fio)
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 82 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYx8QF1uAuzXWRxe2r:-MsYx8QF1uAuzXWRxe2s:b-ov9rlo) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L82)):*
> ```Python
> def test_fio_runner_init_no_direct_write_to_pmem(oneseries_fio, config_fio):
>     """failed initialization of FioRunner object
>        - no direct_write_to_pmem provided"""
> ```

```
    """failed initialization of FioRunner object
       - no direct_write_to_pmem provided
    """
```



_Code quote:_
```Python
    """failed initialization of FioRunner object
       - no direct_write_to_pmem provided"""
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 85 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYxSYt-RLIkex6IXCk:-MsYxSYt-RLIkex6IXCl:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L85)):*
> ```Python
>     oneseries_fio.pop('requirements')
>     oneseries_fio['requirements'] = {}
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 87 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYxU-M9X2WjC4tsqm6:-MsYxU-N3GXZgot5vEGG:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L87)):*
> ```Python
> 
>     benchmark = lib.benchmark.Benchmark(oneseries_fio)
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 94 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYxVJL6memOV9Kan3y:-MsYxVJL6memOV9Kan3z:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L94)):*
> ```Python
>     """failed initialization of FioRunner object - no config provided """
>     benchmark = lib.benchmark.Benchmark(oneseries_fio)
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 102 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYxZbKAXJn7AyQbibN:-MsYxZbKAXJn7AyQbibO:b8o2p8f) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L102)):*
> ```Python
>                                            monkeypatch):
>     """failed initialization of FioRunner object -
>        - incomplete config provided"""
> ```

```
    """failed initialization of FioRunner object -
       - incomplete config provided
    """
```



_Code quote:_
```Python
    """failed initialization of FioRunner object -
       - incomplete config provided"""
```


<!-- Sent from Reviewable.io -->

2022-01-04 07:29 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r35.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 23 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 34 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzSP1CAWe6sOdzCjT:-MsYzSP1CAWe6sOdzCjU:brahhpl) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L34)):*
> ```Python
> def test_ib_read_runner_init(oneseries_ib_read, config_ib_read, monkeypatch):
>     """test proper initialization of IbReadRunner object
>        with all mandatory parameters"""
> ```

```
""".....
"""
```



_Code quote:_
```Python
    """test proper initialization of IbReadRunner object
       with all mandatory parameters"""
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 67 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYyq1e9y7H1fbRdK2c:-MsYyq1e9y7H1fbRdK2d:bus13j7) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L67)):*
> ```Python
> def test_ib_read_runner_init_oneserises_incomplete(oneseries_ib_read,
>         config_ib_read, key):
>     """failed initialization of IbReadRunner object - incomlete oneseries"""
> ```

incomplete



_Code quote:_
```Python
incomlete 
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 71 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz29o9_pGnLos0Rck:-MsYz29o9_pGnLos0Rcl:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L71)):*
> ```Python
>     oneseries.pop(key)
>     benchmark = lib.benchmark.Benchmark(oneseries)
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 80 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzPpJ3jYGV6c0Ocb0:-MsYzPpJ3jYGV6c0Ocb1:brahhpl) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L80)):*
> ```Python
>          config_ib_read, monkeypatch):
>     """failed initialization of IbReadRunner object
>        - no direct_write_to_pmem provided"""
> ```

```
""".....
"""
```



_Code quote:_
```Python
    """failed initialization of IbReadRunner object
       - no direct_write_to_pmem provided"""
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 90 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz6S4DwQweDGnFU-O:-MsYz6S4DwQweDGnFU-P:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L90)):*
> ```Python
>     oneseries.pop('requirements')
>     oneseries['requirements'] = {}
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 92 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz7PX9HztMTNxdVkI:-MsYz7PX9HztMTNxdVkJ:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L92)):*
> ```Python
> 
>     benchmark = lib.benchmark.Benchmark(oneseries)
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 100 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz8He-qzPZVWw1gvo:-MsYz8He-qzPZVWw1gvp:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L100)):*
> ```Python
>     oneseries = {**oneseries_ib_read}
>     benchmark = lib.benchmark.Benchmark(oneseries)
> ```

redundant empty line
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 108 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzK2L-yi3mwmSO0no:-MsYzK2M6FGiVcalP8E2:brahhpl) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L108)):*
> ```Python
>         config_ib_read, key):
>     """failed initialization of IbReadRunner object -
>        - incomplete config provided """
> ```

```
""".....
"""
```



_Code quote:_
```Python
    """failed initialization of IbReadRunner object -
       - incomplete config provided """
```
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 120 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzBJkCJhsdjCraGzv:-MsYzBJkCJhsdjCraGzw:brahhpl) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L120)):*
> ```Python
>         config_ib_read, key):
>     """failed initialization of IbReadRunner object -
>        - invalid value provided"""
> ```

```
""".....
"""
```



_Code quote:_
```Python
    """failed initialization of IbReadRunner object -
       - invalid value provided"""
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 119 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYyIpr7urCoxfY-wOX:-MsYyIpr7urCoxfY-wOY:bohtbc2) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L119)):*
> ```Python
> def test_fio_runner_init_wrong_value(oneseries_fio, config_fio, key):
>     """failed initialization of IbReadRunner object -
>        - incorrect onseries values """
> ```

```
    """failed initialization of IbReadRunner object -
       - incorrect onseries values
    """
```



_Code quote:_
```Python
    """failed initialization of IbReadRunner object -
       - incorrect onseries values """
```


<!-- Sent from Reviewable.io -->

2022-01-04 07:32 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 24 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 116 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsZ-8pGAhz2ij99Ugqx:-MsZ-8pGAhz2ij99Ugqy:b1ctauk) ([raw file](https://github.com/pmem/rpma/blob/16604f0a953661bad57a9fa018d86c2f4556bfd2/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L116)):*
> ```Python
>         IbReadRunner(benchmark, config, 'idfile')
> 
> @pytest.mark.parametrize('key', ['rw', 'filetype', 'tool'])
> ```

What about `'mode'` ?



_Code quote:_
```Python
@pytest.mark.parametrize('key', ['rw', 'filetype', 'tool'])
```


<!-- Sent from Reviewable.io -->

2022-01-04 07:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 24 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 97 at r31](https://reviewable.io/reviews/pmem/rpma/1452#-MsYuC3H69RCmGg6xSBn:-MsZ0npQ5MiLSMiSorQT:bxdd733) ([raw file](https://github.com/pmem/rpma/blob/cbbaef0187d4dc25b28f1043ef8eb4634df7bf6a/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
FAILED tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py::test_fio_runner_init_wrong_value[tool] - socket.gaierror: [Errno -2] Name or service not known
```

This test runs real `RemoteCmd.run_sync` with `host = 'server_ip'`
</blockquote></details>

It seems that a value of ``tool`` is not verified by `FioRunner`


<!-- Sent from Reviewable.io -->

2022-01-04 08:18 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r37, 1 of 1 files at r38.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 11 of 13 files reviewed, 24 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1452#-MsVX5Hv9dDLwzlXHkAj:-MsZ236hBjaRyymTd9w3:b9x2p3v) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

One fix is required: https://github.com/pmem/rpma/pull/1473

It works now: https://github.com/ldorau/rpma/actions/runs/1652441839
</blockquote></details>

Rebased

---
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 34 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzSP1CAWe6sOdzCjT:-MsZ5MKI6xoo_UdJSC0C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
""".....
"""
```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 60 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYjmC81q7n9JMwb_D3:-MsZ5M2SEaN4VnOzvaJY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

supported
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 67 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYyq1e9y7H1fbRdK2c:-MsZ8llf6OnStl5QMFhK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

incomplete
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 71 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz29o9_pGnLos0Rck:-MsZ5fJDDdQ4XSzhTNBp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 80 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzPpJ3jYGV6c0Ocb0:-MsZ5fqr0w3PwIdcxLXD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
""".....
"""
```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 90 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz6S4DwQweDGnFU-O:-MsZ8jfg5NtLyB5fr7x4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 92 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz7PX9HztMTNxdVkI:-MsZ8iya0LB2xGt2I13X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 100 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYz8He-qzPZVWw1gvo:-MsZ8i__-sUcVxpoRSvC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L100)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 108 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzK2L-yi3mwmSO0no:-MsZ8hGN1NbJuEqv4KO7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
""".....
"""
```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 116 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsZ-8pGAhz2ij99Ugqx:-MsZ80Sx0GLd1DdD1eNN:b-wfg7kl) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What about `'mode'` ?
</blockquote></details>

Mode is only verified in test_ib_read_runner_init_oneserises_incomplete
IbReadRunner expects mode but does not verify its value yet.
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 120 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYzBJkCJhsdjCraGzv:-MsZ7mp2DMYjhm_IRX1C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
""".....
"""
```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 97 at r31](https://reviewable.io/reviews/pmem/rpma/1452#-MsYuC3H69RCmGg6xSBn:-MsZ7iZa6-s7786xe_g4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cbbaef0187d4dc25b28f1043ef8eb4634df7bf6a/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems that a value of ``tool`` is not verified by `FioRunner`
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 31 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYkaJK2obDhM5HZlRu:-MsZ2IK04fTSJDht0hAF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
    """test proper initialization of FioRunner object
       with all mandatory parameters
    """
```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 39 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYiyd-0Y5BrLio7j2D:-MsZ2Ha25S-zeNnwVVyM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`-> str:`
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 49 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsYvGSk-RR84mExEie4:-MsZ6WqJ8xVTV6Wdwn2W:b-g081nr) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L49)):*
<details><summary><i> [...]

2022-01-04 08:39 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r39, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 24 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-04 09:34 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r39, 1 of 1 files at r40, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 116 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsZ-8pGAhz2ij99Ugqx:-MsZGZxk8qKfeJ0FIHEM:b-f8c9ck) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L116)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Mode is only verified in test_ib_read_runner_init_oneserises_incomplete
IbReadRunner expects mode but does not verify its value yet.
</blockquote></details>

It does:
```python
        self.__mode = self.__benchmark.oneseries['mode']
        self.__settings = self.__SETTINGS_BY_MODE.get(self.__mode, None)
        if not isinstance(self.__settings, dict):
            raise ValueError(UNKNOWN_VALUE_MSG.format('mode', self.__mode))
```

Please add `'mode'` here
___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 77 at r40](https://reviewable.io/reviews/pmem/rpma/1452#-MsZQm2MDbwvvrCODfkW:-MsZQm2MDbwvvrCODfkX:bpl7n5f) ([raw file](https://github.com/pmem/rpma/blob/4e791c8da1c116b9abd6a4fcc93681b7cdf31815/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L77)):*
> ```Python
> # XXX shall IbReadRunner anyhow control direct_write_to_pmem
> @pytest.mark.skip(reason="ib_read does not control direct_write_to_pmem")
> def test_ib_read_runner_init_no_direct_write_to_pmem(oneseries_ib_read,
> ```

Why ?
I think `IbReadRunner` should not control `direct_write_to_pmem` and this test should be removed



_Code quote:_
```Python
# XXX shall IbReadRunner anyhow control direct_write_to_pmem
@pytest.mark.skip(reason="ib_read does not control direct_write_to_pmem")
def test_ib_read_runner_init_no_direct_write_to_pmem(oneseries_ib_read,
```
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 53 at r39](https://reviewable.io/reviews/pmem/rpma/1452#-MsZEhOs3CD7BmxCSCP7:-MsZEhOs3CD7BmxCSCP8:b-r9aw7n) ([raw file](https://github.com/pmem/rpma/blob/24407aec83674cd30d0f6d90bc6e7dda74b50bde/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L53)):*
> ```Python
>     monkeypatch.setattr(FioRunner, 'run', run_mock)
> 
>     if not fio_path is None:
> ```

```python
if fio_path is not None:
```



_Code quote:_
```Python
if not fio_path is None:
```


<!-- Sent from Reviewable.io -->

2022-01-04 09:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 45 at r40](https://reviewable.io/reviews/pmem/rpma/1452#-MsZTvCzEREs-4nnpokv:-MsZTvCzEREs-4nnpokw:b-sa07e3) ([raw file](https://github.com/pmem/rpma/blob/4e791c8da1c116b9abd6a4fcc93681b7cdf31815/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L45)):*
> ```Python
>             fio_path_full = 'fio'
>         else:
>             fio_path_full = join(config_fio['FIO_PATH'] , 'fio')
> ```

```
rpma/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py:45:56: C0326: No space allowed before comma
            fio_path_full = join(config_fio['FIO_PATH'] , 'fio')
                                                        ^ (bad-whitespace)
```



_Code quote:_
```Python
            fio_path_full = join(config_fio['FIO_PATH'] , 'fio')
```


<!-- Sent from Reviewable.io -->

2022-01-04 10:06 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r41, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-04 10:06 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 53 at r39](https://reviewable.io/reviews/pmem/rpma/1452#-MsZEhOs3CD7BmxCSCP7:-MsZYLXHCUuvGwhYqzXN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/24407aec83674cd30d0f6d90bc6e7dda74b50bde/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```python
if fio_path is not None:
```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py, line 45 at r40](https://reviewable.io/reviews/pmem/rpma/1452#-MsZTvCzEREs-4nnpokv:-MsZYEs29XguQqjrfddP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4e791c8da1c116b9abd6a4fcc93681b7cdf31815/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
rpma/tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py:45:56: C0326: No space allowed before comma
            fio_path_full = join(config_fio['FIO_PATH'] , 'fio')
                                                        ^ (bad-whitespace)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 10:19 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r33, 1 of 1 files at r41.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 116 at r36](https://reviewable.io/reviews/pmem/rpma/1452#-MsZ-8pGAhz2ij99Ugqx:-MsZ_kOA4Av5adLVjd0Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/425e323876a29ddc20c7b5732e4cf371f2ba1fad/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does:
```python
        self.__mode = self.__benchmark.oneseries['mode']
        self.__settings = self.__SETTINGS_BY_MODE.get(self.__mode, None)
        if not isinstance(self.__settings, dict):
            raise ValueError(UNKNOWN_VALUE_MSG.format('mode', self.__mode))
```

Please add `'mode'` here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 10:29 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r43.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py, line 77 at r40](https://reviewable.io/reviews/pmem/rpma/1452#-MsZQm2MDbwvvrCODfkW:-MsZclcvEWGI25dPHtmH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4e791c8da1c116b9abd6a4fcc93681b7cdf31815/tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why ?
I think `IbReadRunner` should not control `direct_write_to_pmem` and this test should be removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 10:30 UTC, grom72 reviewed
> Reviewed 3 of 7 files at r15, 1 of 2 files at r20, 1 of 2 files at r33.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-04 10:42 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-04 10:44 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-04 10:58 UTC, ldorau approved these changes
All the CI builds pass now:
https://github.com/ldorau/rpma/actions/runs/1653236319

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1452#-:-MsAyxdi49OJUETu87Uv:b-ak0zri)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-04 10:59 UTC, merged