ib_read_[lat|bw] defined in figure
pmem/rpma pull request #1455
Opened 2021-12-27 19:22 UTC by grom72

to avoid hardcoded tool name settings in the code and to have a common definition of settings for fio and ib_read

2021-12-28 11:14 UTC, Patryk717 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455#-:-Ms-jlsb3_L05XjZ5K2B:bdycpsm)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-12-29 07:53 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 17:30 UTC, grom72 reviewed
> Reviewed 2 of 9 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-12-29 17:30 UTC, grom72 reviewed
> Reviewed 1 of 9 files at r1, 1 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 13:03 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 1 of 12 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-04 09:49 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 1 of 12 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-04 11:51 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1455#-MsZvNlKEKvyySk7mAJ0:-MsZvNlKEKvyySk7mAJ1:b3tciiv) (no related file):*
@grom72  Rebase please

---


<!-- Sent from Reviewable.io -->

2022-01-04 13:20 UTC, ldorau requested changes
> Reviewed 1 of 9 files at r1, 6 of 11 files at r4, 2 of 4 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/__init__.py, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/1455#-Ms_90wWAZEOV-0Ry9-A:-Ms_90wWAZEOV-0Ry9-B:b-x9332z) ([raw file](https://github.com/pmem/rpma/blob/a4d8e7d57bd58b2b30607ced8a524bd80e3456da/tools/perf/lib/benchmark/runner/__init__.py#L22)):*
> ```Python
> from .dummy import Dummy
> from .fio import FioRunner
> from .ib_read import IbReadRunner
> ```

Please revert:
1) we cannot do that (`FioRunner` and `IbReadRunner` can be accessed only via the `Executor` class)
2) it is not needed



_Code quote:_
```Python
from .fio import FioRunner
from .ib_read import IbReadRunner
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 69 at r6](https://reviewable.io/reviews/pmem/rpma/1455#-Ms_DFEEEXLTmDMrp7mz:-Ms_DFEEEXLTmDMrp7n-:b-bxxiro) ([raw file](https://github.com/pmem/rpma/blob/a4d8e7d57bd58b2b30607ced8a524bd80e3456da/tools/perf/lib/benchmark/runner/ib_read.py#L69)):*
> ```Python
>         # path to the local ib tool
>         ib_name = self.__benchmark.oneseries.get('tool', '') + '_' + \
>             self.__benchmark.oneseries.get('tool_mode', '')
> ```

```
        ib_name = self.__benchmark.oneseries['tool'] + '_' + \
            self.__benchmark.oneseries['tool_mode']
```



_Code quote:_
```Python
        ib_name = self.__benchmark.oneseries.get('tool', '') + '_' + \
            self.__benchmark.oneseries.get('tool_mode', '')
```


<!-- Sent from Reviewable.io -->

2022-01-04 17:34 UTC, grom72 reviewed
> Reviewed 3 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1455#-MsZvNlKEKvyySk7mAJ0:-MsZyZNi6u9bm4Aqy7UU:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72  Rebase please
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-01-04 17:34 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 69 at r6](https://reviewable.io/reviews/pmem/rpma/1455#-Ms_DFEEEXLTmDMrp7mz:-Msa90AK4i_Ak05b5XVC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a4d8e7d57bd58b2b30607ced8a524bd80e3456da/tools/perf/lib/benchmark/runner/ib_read.py#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
        ib_name = self.__benchmark.oneseries['tool'] + '_' + \
            self.__benchmark.oneseries['tool_mode']
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 17:36 UTC, grom72 reviewed
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/__init__.py, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/1455#-Ms_90wWAZEOV-0Ry9-A:-Msa9KdZ8L4LzDnhxhSM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a4d8e7d57bd58b2b30607ced8a524bd80e3456da/tools/perf/lib/benchmark/runner/__init__.py#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please revert:
1) we cannot do that (`FioRunner` and `IbReadRunner` can be accessed only via the `Executor` class)
2) it is not needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 17:36 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-04 17:37 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-04 17:41 UTC, grom72 reviewed
> Reviewed 3 of 11 files at r4, 2 of 4 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-05 07:13 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-05 08:07 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455#-:-MsdGjnl6ldH0C2rYxIL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-05 09:34 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 9 files at r1, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455#-:-Msd_cFg6-xaN-3GWqVc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-05 09:36 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1455)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-05 09:37 UTC, merged