tools: disable bad-continuation pylint warning
pmem/rpma pull request #1468
Opened 2021-12-30 18:47 UTC by grom72

bad-continuation has been removed from pylint
https://github.com/PyCQA/pylint/pull/3571

It is still enabled in old releases producing a lot of
false warnings.

2021-12-31 09:15 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468#-:-MsElTkD2w-6KyZ0mUt7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 09:12 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 09:13 UTC, haichangsi reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468#-:-MsUCnm-5A_1fauEVC6J:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 11:23 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[utils/pylint.rc, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1468#-MsUfCNz88FmfJtsdKhZ:-MsUfCNz88FmfJtsdKh_:b-djwckv) ([raw file](https://github.com/pmem/rpma/blob/bfbf667f4704302ade1bd0e1f8b7ddb85fd2557a/utils/pylint.rc#L15)):*
> ```
> # len-as-condition - bug in Pylint, fixed as of Pylint 2.4 (https://github.com/PyCQA/pylint/pull/2815)
> # duplicate-code - XXX requires consideration
> # bad-continuation - still enabled by default on old releases https://github.com/PyCQA/pylint/pull/3571
> ```

```
# bad-continuation - removed from pylint (https://github.com/PyCQA/pylint/pull/3571), but still enabled by default in old releases
```



_Code quote:_
```
# bad-continuation - still enabled by default on old releases https://github.com/PyCQA/pylint/pull/3571
```


<!-- Sent from Reviewable.io -->

2022-01-03 11:26 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[utils/pylint.rc, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1468#-MsUfCNz88FmfJtsdKhZ:-MsUgINE8EaifZLNb9mV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bfbf667f4704302ade1bd0e1f8b7ddb85fd2557a/utils/pylint.rc#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
# bad-continuation - removed from pylint (https://github.com/PyCQA/pylint/pull/3571), but still enabled by default in old releases
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-03 11:32 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 11:32 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1468#-:-MsUhdaU8s54TA1xWk8Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-03 11:33 UTC, merged