tools: improve run mode
pmem/rpma pull request #1471
Opened 2022-01-03 13:53 UTC by osalyk

2022-01-03 14:04 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-01-03 14:15 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVDrbR5SBWHueIdMxE):*
Please add details about this improvement



_Code quote:_
```
 tools: improve run mode
```
___
*[tools/perf/lib/bench.py, line 155 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVEB3z6K4EGAUNXz8-:-MsVEB3z6K4EGAUNXz80:b8ywod0) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/bench.py#L155)):*
> ```Python
>         # generate a list of unique benchmarks to execute
>         benchmarks = Benchmark.uniq(figures)
>         # generate a list of unique requirements to be met
> ```

Please fix the comment



_Code quote:_
```Python
        # generate a list of unique requirements to be met
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHDGe2ipcaQm6HN9M:-MsVHDGe2ipcaQm6HN9N:b-p1pfsp) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/benchmark/runner/fio.py#L102)):*
> ```Python
>         self.__tool = self.__benchmark.oneseries['tool']
>         self.__tool_mode = self.__benchmark.oneseries['tool_mode']
>         self.__mode = self.__benchmark.oneseries['mode']
> ```

```
        if 'REMOTE_DIRECT_WRITE_TO_PMEM' not in self.__config:
            raise ValueError('the following key is missing in the config: {}'
                             .format('REMOTE_DIRECT_WRITE_TO_PMEM'))
        self.__direct_write_to_pmem = int(self.__config['REMOTE_DIRECT_WRITE_TO_PMEM'])
```



_Code quote:_
```Python
        self.__direct_write_to_pmem = \
            int(self.__benchmark.requirements['direct_write_to_pmem'])
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHqFSAwJTZFY02GVO:-MsVHqFSAwJTZFY02GVP:b-3y8d4a) ([raw file](https://github.com/pmem/rpma/blob/5e81884dc2a5e1abe7c9cc3f77c7c9eb5207a7d7/tools/perf/lib/benchmark/runner/fio.py#L161)):*
> ```Python
>                'numjobs={}'.format(settings['threads']),
>                'iodepth={}'.format(settings['iodepth']),
>                'direct_write_to_pmem={}'.format(self.__direct_write_to_pmem),
> ```

... and it can stay as is



_Code quote:_
```Python
 'direct_write_to_pmem={}'.format(self.__direct_write_to_pmem),
```


<!-- Sent from Reviewable.io -->

2022-01-03 14:16 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-03 17:25 UTC, grom72 requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsVyL9KBBZwlt5sGHWM:-MsVyL9KBBZwlt5sGHWN:brv2q6s) (no related file):*
What is the purpose of this PR?

---


<!-- Sent from Reviewable.io -->

2022-01-04 09:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHDGe2ipcaQm6HN9M:-MsZV_QSACJ5Jrg5LNC4:b-gzsbnp) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/benchmark/runner/fio.py#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
        if 'REMOTE_DIRECT_WRITE_TO_PMEM' not in self.__config:
            raise ValueError('the following key is missing in the config: {}'
                             .format('REMOTE_DIRECT_WRITE_TO_PMEM'))
        self.__direct_write_to_pmem = int(self.__config['REMOTE_DIRECT_WRITE_TO_PMEM'])
```

</blockquote></details>

Since `'REMOTE_DIRECT_WRITE_TO_PMEM'` is not always present in `config`, can it be read from `req['direct_write_to_pmem']` ?


<!-- Sent from Reviewable.io -->

2022-01-04 10:35 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsVyL9KBBZwlt5sGHWM:-MsZdyNi7ykFgvOYssHA:b77rw5y) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is the purpose of this PR?
</blockquote></details>

Details in commit message

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVDrbR5SBWHueIdMxE):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add details about this improvement
</blockquote></details>

Done.
___
*[tools/perf/lib/bench.py, line 155 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVEB3z6K4EGAUNXz8-:-MsVO9TK3Xt04RnH4b2V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/bench.py#L155)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix the comment
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHDGe2ipcaQm6HN9M:-MsZ_n6W1bqRkflImGuw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/benchmark/runner/fio.py#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Since `'REMOTE_DIRECT_WRITE_TO_PMEM'` is not always present in `config`, can it be read from `req['direct_write_to_pmem']` ?
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHqFSAwJTZFY02GVO:-MsVOUoP8mM8i-GQKCCx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5e81884dc2a5e1abe7c9cc3f77c7c9eb5207a7d7/tools/perf/lib/benchmark/runner/fio.py#L161)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... and it can stay as is
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 10:36 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHDGe2ipcaQm6HN9M:-MsZe9tj9Xr5dA3edz9E:bb6qfd1) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/benchmark/runner/fio.py#L102)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

????


<!-- Sent from Reviewable.io -->

2022-01-04 10:48 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 0 of 5 files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 168 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgW_dA-lai50CI8xz:-MsZgW_dA-lai50CI8y-:b84qfhe) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L168)):*
> ```Python
>                     "'{}' is missing in the config".format(required))
> 
>     def run(self, config: dict, result_dir: str, req: dict) -> None:
> ```

```direct_write_to_pmem: bool```



_Code quote:_
```Python
req: dict
```
___
*[tools/perf/lib/benchmark/base.py, line 190 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZge9TEf916qpp3KN2:-MsZge9TEf916qpp3KN3:b-xsvery) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L190)):*
> ```Python
>              of the benchmarking process will be stored.
>         """
>         self.__req['direct_write_to_pmem'] = req
> ```

```direct_write_to_pmem```



_Code quote:_
```Python
req
```
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgosBCAGAa8P89HO0:-MsZgosBCAGAa8P89HO1:b-l6mwxj) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L23)):*
> ```Python
>     oneseries_dummy.pop(key, None)
>     benchmark = lib.benchmark.Benchmark(oneseries_dummy)
>     req = {'direct_write_to_pmem': False}
> ```

remove



_Code quote:_
```Python
req = {'direct_write_to_pmem': False}
```
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgtWY270IhTlsvdKt:-MsZgtWY270IhTlsvdKu:b-juhxvv) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L25)):*
> ```Python
>     req = {'direct_write_to_pmem': False}
>     with pytest.raises(ValueError):
>         benchmark.run(CONFIG_DUMMY, str(tmpdir), req)
> ```

```, False)
```




_Code quote:_
```Python
, req)
```
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgxIm-j1v5t6eGN1E:-MsZgxIm-j1v5t6eGN1F:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L32)):*
> ```Python
>     config = {**CONFIG_DUMMY}
>     config.pop('server_ip', None)
>     req = {'direct_write_to_pmem': False}
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgy7d2cFEhrFem7bi:-MsZgy7d2cFEhrFem7bj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L34)):*
> ```Python
>     req = {'direct_write_to_pmem': False}
>     with pytest.raises(ValueError):
>         benchmark_dummy.run(config, str(tmpdir), req)
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 39 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh0RT1pNRihV6Y5q5:-MsZh0RT1pNRihV6Y5q6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L39)):*
> ```Python
> def test_dummy_runner(benchmark_dummy, tmpdir, monkeypatch):
>     """a simple Dummy runner call"""
>     req = {'direct_write_to_pmem': False}
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh0xoD55wyD0QdQro:-MsZh0xoD55wyD0QdQrp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L48)):*
> ```Python
>     output = lib.benchmark.get_result_path(str(tmpdir),
>                                            benchmark_dummy.identifier)
>     benchmark_dummy.run(CONFIG_DUMMY, str(tmpdir), req)
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 54 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh1rp8pPfAaH68lRw:-MsZh1rp8pPfAaH68lRx:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L54)):*
> ```Python
> def test_bash_runner(benchmark_bash, tmpdir, monkeypatch):
>     """a simple Bash runner call"""
>     req = {'direct_write_to_pmem': False}
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh2UuEtO4XWh9RZD-:-MsZh2UuEtO4XWh9RZD0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L63)):*
> ```Python
>     output = lib.benchmark.get_result_path(str(tmpdir),
>                                            benchmark_bash.identifier)
>     benchmark_bash.run(CONFIG_DEFAULT, str(tmpdir), req)
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh3956pUnKJyP1-Ox:-MsZh3956pUnKJyP1-Oy:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L69)):*
> ```Python
> def test_base_runner(benchmark_base, tmpdir, monkeypatch):
>     """a simple base runner call"""
>     req = {'direct_write_to_pmem': False}
> ```

.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh3ov8dDmHPlAFcVv:-MsZh3ov8dDmHPlAFcVw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L78)):*
> ```Python
>     output = lib.benchmark.get_result_path(str(tmpdir),
>                                            benchmark_base.identifier)
>     benchmark_base.run(CONFIG_DEFAULT, str(tmpdir), req)
> ```

.


<!-- Sent from Reviewable.io -->

2022-01-04 10:57 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 1 of 5 files reviewed, 15 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-04 11:30 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 1 of 5 files reviewed, 15 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/benchmark/base.py, line 168 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgW_dA-lai50CI8xz:-MsZo7j48p1gGdjuYJaI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L168)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```direct_write_to_pmem: bool```
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/base.py, line 190 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZge9TEf916qpp3KN2:-MsZoJb351HVdlHLJ9Hd:bgt06mu) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```direct_write_to_pmem```
</blockquote></details>

It's okay here.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHDGe2ipcaQm6HN9M:-MsZonQh67qn1ot6HjEa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/benchmark/runner/fio.py#L102)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

????
</blockquote></details>

Done.



_Code quote:_
```Python
        if 'direct_write_to_pmem' not in self.__benchmark.requirements:
            raise ValueError(MISSING_KEY_MSG.format('direct_write_to_pmem'))
```
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgosBCAGAa8P89HO0:-MsZph1sDhmSPe5B6vOV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgtWY270IhTlsvdKt:-MsZpi395A3K8pj7z-IH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```, False)
```

</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgxIm-j1v5t6eGN1E:-MsZpip51YM7TJKMCB8o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 34 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgy7d2cFEhrFem7bi:-MsZpjaG5d4S5izzLlQJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L34)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 39 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh0RT1pNRihV6Y5q5:-MsZpkA19RqqmKK0KVXc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh0xoD55wyD0QdQro:-MsZplDo4eJWo2oI5g_E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 54 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh1rp8pPfAaH68lRw:-MsZpluC-Hogw7d_SdW_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh2UuEtO4XWh9RZD-:-MsZpmY4D8dH_jk6VAxR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L63)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh3956pUnKJyP1-Ox:-MsZpnIUEcBpG5INwUca:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L69)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/test_run.py, line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZh3ov8dDmHPlAFcVv:-MsZpo1UCciMfnCwm8Lu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/tests/lib/benchmark/test_run.py#L78)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 11:46 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 4 of 5 files reviewed, 13 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[-- commits, line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1471#-MsZrdnLAsBD8fH1lJyO):*
Please elaborate ;-)



_Code quote:_
```
bench.json is not overwritten.
```
___
*[tools/perf/lib/benchmark/base.py, line 168 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgW_dA-lai50CI8xz:-MsZs6zv1bpOpLHm9m7A:b-c1fu43) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L168)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`reqs: dict` - we can need more requirements in the future.
___
*[tools/perf/lib/benchmark/base.py, line 190 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZge9TEf916qpp3KN2:-MsZsVsb2m2daFI1-GsS:b-p1pdh) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L190)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It's okay here.
</blockquote></details>

Copy all items from `reqs` to `self.__req` here



_Code quote:_
```Python
self.__req[
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1471#-MsVHDGe2ipcaQm6HN9M:-MsZrW6x3SZC6JsAtw_O:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/ebad90b4de0b3fd1b0a774119df397678fad3d6b/tools/perf/lib/benchmark/runner/fio.py#L102)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2022-01-04 11:47 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 4 of 5 files reviewed, 14 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/Requirement.py, line 179 at r5](https://reviewable.io/reviews/pmem/rpma/1471#-MsZuZGE04ZA62PidDn2:-MsZuZGE04ZA62PidDn3:b-ofqahj) ([raw file](https://github.com/pmem/rpma/blob/31d0e09397173b28fc9bd145a5920258db543387/tools/perf/lib/Requirement.py#L179)):*
> ```Python
>             if b.is_done():
>                 continue
>             b.run(config, result_dir, self.__req['direct_write_to_pmem'])
> ```

`self.__req`



_Code quote:_
```Python
self.__req['direct_write_to_pmem']
```


<!-- Sent from Reviewable.io -->

2022-01-04 11:47 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 14 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-04 13:03 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 14 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 168 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgW_dA-lai50CI8xz:-Ms_AFlZ-rTQ5qxeXY9_:b-9a1cw2) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L168)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`reqs: dict` - we can need more requirements in the future.
</blockquote></details>

But we call run with only one item from req['direct_write_to_pmem'] not with dict.


<!-- Sent from Reviewable.io -->

2022-01-04 13:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 14 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 168 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgW_dA-lai50CI8xz:-Ms_CVYP-97CBXu8gaWI:b-dcvj9a) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L168)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But we call run with only one item from req['direct_write_to_pmem'] not with dict.
</blockquote></details>

We should call with dict to enable passing more requirements


<!-- Sent from Reviewable.io -->

2022-01-04 13:20 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1471#-MsZrdnLAsBD8fH1lJyO):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please elaborate ;-)
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 179 at r5](https://reviewable.io/reviews/pmem/rpma/1471#-MsZuZGE04ZA62PidDn2:-Ms_CV8c----ztD-ZQLo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31d0e09397173b28fc9bd145a5920258db543387/tools/perf/lib/Requirement.py#L179)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`self.__req`
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/base.py, line 168 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZgW_dA-lai50CI8xz:-Ms_ClOhBlUC4h9rHWDs:b-gomqd0) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L168)):*
> But we call run with only one item from req['direct_write_to_pmem'] not with dict.
There may be more requirements in the future
___
*[tools/perf/lib/benchmark/base.py, line 190 at r3](https://reviewable.io/reviews/pmem/rpma/1471#-MsZge9TEf916qpp3KN2:-Ms_C9OV641phLAnGCAr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/124fb6bb6f22f046a2ab27eba4e9c1e7a78018f3/tools/perf/lib/benchmark/base.py#L190)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Copy all items from `reqs` to `self.__req` here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 13:29 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[-- commits, line 4 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_F6G-3pYNGyUx4g__):*
a new one



_Code quote:_
```
new one
```
___
*[-- commits, line 4 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_FAxJ6KxM9sQlgCwm):*
a state from the file



_Code quote:_
```
state from file
```
___
*[tools/perf/lib/benchmark/base.py, line 192 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_GTbe8E6C6PiGyvYr:-Ms_GTbe8E6C6PiGyvYs:b-rt5vub) ([raw file](https://github.com/pmem/rpma/blob/31779847b826dbfacd4af4d7fcdb61ffaa0bf799/tools/perf/lib/benchmark/base.py#L192)):*
> ```Python
>              of the benchmarking process will be stored.
>         """
>         self.__req = deepcopy(req)
> ```

Can we overwrite `self.__req` here?

We could just copy `req` to `self.__req` and do not overwrite it.



_Code quote:_
```Python
self.__req
```


<!-- Sent from Reviewable.io -->

2022-01-04 14:35 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 4 of 5 files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 4 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_F6G-3pYNGyUx4g__):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a new one
</blockquote></details>

Done.
___
*[-- commits, line 4 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_FAxJ6KxM9sQlgCwm):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a state from the file
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/base.py, line 192 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_GTbe8E6C6PiGyvYr:-Ms_UMm80R-ZZ1lePp-o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31779847b826dbfacd4af4d7fcdb61ffaa0bf799/tools/perf/lib/benchmark/base.py#L192)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Can we overwrite `self.__req` here?

We could just copy `req` to `self.__req` and do not overwrite it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 14:48 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 192 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_GTbe8E6C6PiGyvYr:-Ms_XtP2CfW3AMs2SSHv:bb0c75k) ([raw file](https://github.com/pmem/rpma/blob/31779847b826dbfacd4af4d7fcdb61ffaa0bf799/tools/perf/lib/benchmark/base.py#L192)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is 
```python
    self.__req = oneseries.pop('requirements', {})
```

in `__init__` so we should use

```python
    self.__req.update(req)
```

here.



_Code quote:_
```Python
self.__req = req
```


<!-- Sent from Reviewable.io -->

2022-01-04 14:52 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 4 of 5 files reviewed, 13 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/base.py, line 192 at r6](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_GTbe8E6C6PiGyvYr:-Ms_Zs9a4ElLCzqysu8V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31779847b826dbfacd4af4d7fcdb61ffaa0bf799/tools/perf/lib/benchmark/base.py#L192)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is 
```python
    self.__req = oneseries.pop('requirements', {})
```

in `__init__` so we should use

```python
    self.__req.update(req)
```

here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 14:53 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-04 15:07 UTC, ldorau requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471#-:-Ms_cMujDRrqhOErpuCy:bnfp4nl)* status: 4 of 5 files reviewed, 13 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_cNOA7ztY3oP9sv6J:-Ms_cNOA7ztY3oP9sv6K:b-ujmq67) (no related file):*
Rebase please

---


<!-- Sent from Reviewable.io -->

2022-01-04 15:07 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 4 of 5 files reviewed, 13 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-Ms_cNOA7ztY3oP9sv6J:-Ms_cRm77aLRiPjNdVzv:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-01-04 15:08 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-04 17:26 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 110 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-Msa78jH8j2g9wpFyw7S:-Msa78jH8j2g9wpFyw7T:b-lkbl8l) ([raw file](https://github.com/pmem/rpma/blob/e44bf00c7e14616c457dc045c73a947d1e35e853/tools/perf/lib/benchmark/runner/fio.py#L110)):*
> ```Python
>         if not isinstance(self.__settings, dict):
>             raise ValueError(UNKNOWN_VALUE_MSG.format('mode', self.__mode))
>         if 'direct_write_to_pmem' not in self.__benchmark.requirements:
> ```

What is the purpose to remove this part of code?



_Code quote:_
```Python
        if 'direct_write_to_pmem' not in self.__benchmark.requirements:
            raise ValueError(MISSING_KEY_MSG.format('direct_write_to_pmem'))
        self.__direct_write_to_pmem = \
            int(self.__benchmark.requirements['direct_write_to_pmem'])
```


<!-- Sent from Reviewable.io -->

2022-01-04 17:27 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-04 19:57 UTC, grom72 requested changes
> Reviewed 1 of 5 files at r3, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsadQQGEgpRnIkWuGXp:-MsadQQGEgpRnIkWuGXq:bqfpvsg) (no related file):*
Would it be better to extend ```continue``` mode with additional parameter ```--config config.json```?



_Code quote (from tools/perf/lib/bench.py):_
```Python
        return cls(cache['config'], cache['parts'], figures, requirements, \
            result_dir)
```

---


<!-- Sent from Reviewable.io -->

2022-01-04 19:57 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r5, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-04 23:23 UTC, janekmi requested changes
> Reviewed 1 of 5 files at r3, 1 of 3 files at r5, 1 of 3 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsbNk-o0A6VwuirYx6t:-MsbNk-o0A6VwuirYx6u:bhwm9p) (no related file):*
1. A lot of effort to introduce a feature merely for convenience.
2. This change is blurring a difference between the `run` command and the `continue` command. Never a good thing to do.
3. I simply can't believe it is your sprint goal. Seriously?

What is the rationale behind this change?

---
___
*[tools/perf/lib/bench.py, line 156 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-MsbJw727rPrW2aY3D-l:-MsbJw727rPrW2aY3D-m:buvn5e8) ([raw file](https://github.com/pmem/rpma/blob/96c914cbd72eccc8fcf0522f6c6f4905baf92c93/tools/perf/lib/bench.py#L156)):*
> ```Python
>         benchmarks = Benchmark.uniq(figures)
>         # generate a list of unique requirements to be met
>         # if bench.json exists, restore the dictionary of requirements
> ```

If bench.json exists why do you choose only to reuse the requirements leaving behind everything else? e.g. by calling `carry_on()`?
___
*[tools/perf/lib/Requirement.py, line 179 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-MsbKJbB1NTr6Apg1ai0:-MsbKJbB1NTr6Apg1ai1:bwm47e3) ([raw file](https://github.com/pmem/rpma/blob/96c914cbd72eccc8fcf0522f6c6f4905baf92c93/tools/perf/lib/Requirement.py#L179)):*
> ```Python
>             if b.is_done():
>                 continue
>             self.__req.pop('benchmarks', None)
> ```

You are repeatedly modifying in the for-loop the internal state of the object. What is the point?
___
*[tools/perf/lib/benchmark/base.py, line 192 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-MsbN0fY6nqEvZoNveAN:-MsbN0fY6nqEvZoNveAO:b402imd) ([raw file](https://github.com/pmem/rpma/blob/96c914cbd72eccc8fcf0522f6c6f4905baf92c93/tools/perf/lib/benchmark/base.py#L192)):*
> ```Python
>              of the benchmarking process will be stored.
>         """
>         self.__req.update(req)
> ```

The constructor of this object has the handling of the requirements built-in. Why do you think an object will need to update its requirements?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 110 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-Msa78jH8j2g9wpFyw7S:-MsbL0MP8cOBu_2TPUF9:b-1emzxz) ([raw file](https://github.com/pmem/rpma/blob/e44bf00c7e14616c457dc045c73a947d1e35e853/tools/perf/lib/benchmark/runner/fio.py#L110)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is the purpose to remove this part of code?
</blockquote></details>

It was a duplicate.


<!-- Sent from Reviewable.io -->

2022-01-05 10:47 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsdqQ5p01GBIoLrbpRV:-MsdqQ5p01GBIoLrbpRW:b-5mybg5) (no related file):*
Work on fixing the continue option is in PR #1478  

---


<!-- Sent from Reviewable.io -->

2022-01-05 10:53 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsadQQGEgpRnIkWuGXp:-MsdrmzcB22IixBHpKqx:b-8sgge6) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would it be better to extend ```continue``` mode with additional parameter ```--config config.json```?
</blockquote></details>

#1478

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1471#-MsbNk-o0A6VwuirYx6t:-MsdroD6AC6xBJckKw0r:b-8sgge6) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. A lot of effort to introduce a feature merely for convenience.
2. This change is blurring a difference between the `run` command and the `continue` command. Never a good thing to do.
3. I simply can't believe it is your sprint goal. Seriously?

What is the rationale behind this change?
</blockquote></details>

#1478

---
___
*[tools/perf/lib/bench.py, line 156 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-MsbJw727rPrW2aY3D-l:-MsdrhkE947GjvFcyfAC:b-8sgge6) ([raw file](https://github.com/pmem/rpma/blob/96c914cbd72eccc8fcf0522f6c6f4905baf92c93/tools/perf/lib/bench.py#L156)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If bench.json exists why do you choose only to reuse the requirements leaving behind everything else? e.g. by calling `carry_on()`?
</blockquote></details>

#1478
___
*[tools/perf/lib/Requirement.py, line 179 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-MsbKJbB1NTr6Apg1ai0:-MsdrkZr4uMMzFOrjYrS:b-8sgge6) ([raw file](https://github.com/pmem/rpma/blob/96c914cbd72eccc8fcf0522f6c6f4905baf92c93/tools/perf/lib/Requirement.py#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are repeatedly modifying in the for-loop the internal state of the object. What is the point?
</blockquote></details>

#1478
___
*[tools/perf/lib/benchmark/base.py, line 192 at r10](https://reviewable.io/reviews/pmem/rpma/1471#-MsbN0fY6nqEvZoNveAN:-MsdrlZ6B5dTWyd80nmk:b-8sgge6) ([raw file](https://github.com/pmem/rpma/blob/96c914cbd72eccc8fcf0522f6c6f4905baf92c93/tools/perf/lib/benchmark/base.py#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The constructor of this object has the handling of the requirements built-in. Why do you think an object will need to update its requirements?
</blockquote></details>

#1478


<!-- Sent from Reviewable.io -->

2022-01-05 11:11 UTC, ldorau approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-05 11:33 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471#-:-Mse-sRuBn6Et2FtxpRK:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-05 12:42 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471#-:-MseFf_W3ftlloF_PRjd:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-05 14:05 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1471)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-05 14:08 UTC, merged