tools: set timeout
pmem/rpma pull request #1480
Opened 2022-01-05 15:29 UTC by osalyk

If the server fails while running,
the client crashes while waiting for completion.
To get logs from the server we kill the client process
after the timeout

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1480)

2022-01-05 15:35 UTC, grom72 requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1480#-Mseryvm7NeGhBOP7Iou:-Mseryvm7NeGhBOP7Iov:bta9tdx) (no related file):*
Would 10 minutes be enough as the default value?



_Code quote (from tools/perf/lib/benchmark/runner/fio.py):_
```Python
            timeout = 3600 # default timeout 1h
```

---
___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-Mses8HA2Y61beDArs8W:-Mses8HA2Y61beDArs8X:b-810btu) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L64)):*
> ```Markdown
> 
> ```json
>     "TIMEOUT": 300
> ```

Should we use here default value?
300 s == 5 minutes



_Code quote:_
```Markdown
TIMEOUT": 300
```


<!-- Sent from Reviewable.io -->

2022-01-05 15:38 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-Mses8HA2Y61beDArs8W:-Msesmqd30AWlYUHW-ve:brmaqmh) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Should we use here default value?
300 s == 5 minutes
</blockquote></details>

+1

`"TIMEOUT": 3600`


<!-- Sent from Reviewable.io -->

2022-01-05 17:31 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/CONFIG.JSON.md, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHf4QB2U4oL0FZecS:-MsfHf4QB2U4oL0FZecT:b-jk6qgh) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L61)):*
> ```Markdown
> ```
> 
> Set timeout in seconds, default value 1 hour
> ```

5 minutes



_Code quote:_
```Markdown
1 hour
```
___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-Mses8HA2Y61beDArs8W:-MsfGU5MBDA_2c2zTc9L:b-x96ddr) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1

`"TIMEOUT": 3600`
</blockquote></details>

"TIMEOUT": 300 
5 minutes should be long enough to cover all known use-cases as the fio runer implements a 15s ramp and 60s run time.
There is no point to wait for 1h to learn that something went wrong.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 228 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHmv-2CpddKO665a4:-MsfHmv-2CpddKO665a5:bsk4dpr) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/lib/benchmark/runner/fio.py#L228)):*
> ```Python
>             timeout = self.__config['TIMEOUT']
>         else:
>             timeout = 3600 # default timeout 1h
> ```

```300 # default timeout 5 minutes```



_Code quote:_
```Python
3600 # default timeout 1h
```


<!-- Sent from Reviewable.io -->

2022-01-10 08:01 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1480#-Mseryvm7NeGhBOP7Iou:-Mt1zxmGACgrOXsZW_Zu:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would 10 minutes be enough as the default value?
</blockquote></details>

Done.

---
___
*[tools/perf/CONFIG.JSON.md, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHf4QB2U4oL0FZecS:-Mt1zx-l6N6u-EJmo2A7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

5 minutes
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-Mses8HA2Y61beDArs8W:-Mt1zWBZC5-hHnNfNIVM:b-z2etxv) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

"TIMEOUT": 300 
5 minutes should be long enough to cover all known use-cases as the fio runer implements a 15s ramp and 60s run time.
There is no point to wait for 1h to learn that something went wrong.
</blockquote></details>

In order to reach a compromise, I propose 10 min.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 228 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHmv-2CpddKO665a4:-Mt1zt2Q51xXYUK_RQE1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/lib/benchmark/runner/fio.py#L228)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```300 # default timeout 5 minutes```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 08:19 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt21k_w8KXp8PeXIGB1):*
hangs on waiting



_Code quote:_
```
crashes while waiting
```
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt21sH1-ySAxiVIcf8A):*
timeout.



_Code quote:_
```
timeout
```
___
*[tools/perf/CONFIG.JSON.md, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHf4QB2U4oL0FZecS:-Mt22_-S1wKSq3TA_9st:b-1v9mv1) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L61)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

5 minutes, see the explanation below.
___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-Mses8HA2Y61beDArs8W:-Mt21yJH2g0LXcqJTLOb:b4e3vll) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L64)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

In order to reach a compromise, I propose 10 min.
</blockquote></details>

Tomek is right. The full run time is 1 minute for a single run, so 5 minutes is long enough.
I was mistaken, excuse me @osalyk .
___
*[tools/perf/CONFIG.JSON.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt22hekAjEg0hqO5A0X:-Mt22hekAjEg0hqO5A0Y:b-rxk1gz) ([raw file](https://github.com/pmem/rpma/blob/94959d5deb213b4e03ad907c8b2f4cbf31a8df75/tools/perf/CONFIG.JSON.md#L61)):*
> ```Markdown
> ```
> 
> Set timeout in seconds, default value 10 minutes
> ```

the timeout



_Code quote:_
```Markdown
timeout
```
___
*[tools/perf/CONFIG.JSON.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt22s9r7S021ejTAmmf:-Mt22s9r7S021ejTAmmg:bjcg5f1) ([raw file](https://github.com/pmem/rpma/blob/94959d5deb213b4e03ad907c8b2f4cbf31a8df75/tools/perf/CONFIG.JSON.md#L61)):*
> ```Markdown
> ```
> 
> Set timeout in seconds, default value 10 minutes
> ```

the default



_Code quote:_
```Markdown
default
```
___
*[tools/perf/CONFIG.JSON.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt22vL04HG1rI696_h3:-Mt22vL1E1_qXrpgFPhC:bnzn3wy) ([raw file](https://github.com/pmem/rpma/blob/94959d5deb213b4e03ad907c8b2f4cbf31a8df75/tools/perf/CONFIG.JSON.md#L61)):*
> ```Markdown
> ```
> 
> Set timeout in seconds, default value 10 minutes
> ```

value **is** 5 minutes



_Code quote:_
```Markdown
value 10 minutes
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 228 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHmv-2CpddKO665a4:-Mt23CnG1dYvsGAGr5T6:b-f6cvgf) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/lib/benchmark/runner/fio.py#L228)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1) 300
2) the default
3) is 5 minutes


<!-- Sent from Reviewable.io -->

2022-01-10 08:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1480#-Mseryvm7NeGhBOP7Iou:-Mt24QM40I0uHQyy_i3c:bfw58a9) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

5 minutes should be enough

---


<!-- Sent from Reviewable.io -->

2022-01-10 08:36 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: 0 of 2 files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1480#-Mseryvm7NeGhBOP7Iou:-Mt26ujY261YBmfw7WX4:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

5 minutes should be enough
</blockquote></details>

Done.

---
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt21k_w8KXp8PeXIGB1):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

hangs on waiting
</blockquote></details>

Done.
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt21sH1-ySAxiVIcf8A):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

timeout.
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHf4QB2U4oL0FZecS:-Mt26ZDoCqKhum2zd23C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

5 minutes, see the explanation below.
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-Mses8HA2Y61beDArs8W:-Mt26jm1C5SvuG6oR1_Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/CONFIG.JSON.md#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Tomek is right. The full run time is 1 minute for a single run, so 5 minutes is long enough.
I was mistaken, excuse me @osalyk .
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt22hekAjEg0hqO5A0X:-Mt26azS0LzqxxX_TW34:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94959d5deb213b4e03ad907c8b2f4cbf31a8df75/tools/perf/CONFIG.JSON.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the timeout
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt22s9r7S021ejTAmmf:-Mt26dTaEWPk4CVUTm9t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94959d5deb213b4e03ad907c8b2f4cbf31a8df75/tools/perf/CONFIG.JSON.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the default
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1480#-Mt22vL04HG1rI696_h3:-Mt26flHAXINDGblxvu2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94959d5deb213b4e03ad907c8b2f4cbf31a8df75/tools/perf/CONFIG.JSON.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

value **is** 5 minutes
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 228 at r1](https://reviewable.io/reviews/pmem/rpma/1480#-MsfHmv-2CpddKO665a4:-Mt26sN5Ekv_JyH0lvBd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7b5703fb5373c1c62d40e71344bf68f0e3610cc2/tools/perf/lib/benchmark/runner/fio.py#L228)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) 300
2) the default
3) is 5 minutes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 09:10 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480#-:-Mt2FGaj5nhHhQLqG_JD:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-10 09:32 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480#-:-Mt2KIYNCr3NSFAsSmG2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-10 09:58 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1480)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-10 09:58 UTC, merged