common: add coverage library to docker images
pmem/rpma pull request #1502
Opened 2022-01-18 10:17 UTC by haichangsi

2022-01-18 11:50 UTC, ldorau requested changes
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 31 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-Mth-yUr6HJZktdEqawo:-Mth-yUr6HJZktdEqawp:b9meuc7) (no related file):*
Please keep alphabetical order of packages in all Dockerfiles

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth-_4z54lhz2rTkkUi):*
package



_Code quote:_
```
library
```
___
*[utils/docker/images/Dockerfile.archlinux-latest, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth-g21-sujyMEh_MVp:-Mth-g21-sujyMEh_MVq:blzun65) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.archlinux-latest#L54)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

Please keep alphabetical order in all Dockerfiles



_Code quote:_
```
	scp \
	coverage"
```
___
*[utils/docker/images/Dockerfile.centos-7, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth01q_E5a4yQZBuvnH:-Mth01q_E5a4yQZBuvnI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.centos-7#L44)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.centos-8, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth03ATBOg59-Gp1NtC:-Mth03ATBOg59-Gp1NtD:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.centos-8#L47)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.centos-stream, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth046yEkwKVP3t_SFV:-Mth046yEkwKVP3t_SFW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.centos-stream#L48)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.debian-10, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth050d-yrs_G1nLYgi:-Mth050d-yrs_G1nLYgj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-10#L52)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.debian-11, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth05wb-aNI9aIHFTdq:-Mth05wb-aNI9aIHFTdr:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-11#L53)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.debian-9, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth06rS5mrrxngK2Edz:-Mth06rS5mrrxngK2Ee-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-9#L52)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.debian-experimental, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth08234bavtQXb0toV:-Mth08234bavtQXb0toW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-experimental#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.debian-stable, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth08sX1xj2Va4FNiMg:-Mth08sX1xj2Va4FNiMh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-stable#L53)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.debian-testing, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth09jYEdC4CZTmYJDJ:-Mth09jYEdC4CZTmYJDK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-testing#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-26, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0AWk85MTmJ2whJDF:-Mth0AWlB3afshsLPsrB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-26#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-27, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0Bfc2EkUOVmGLcFf:-Mth0Bfc2EkUOVmGLcFg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-27#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-28, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0CcH9ITmmZeYfV7C:-Mth0CcH9ITmmZeYfV7D:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-28#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-29, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0DJpA54kUST3NCeL:-Mth0DJpA54kUST3NCeM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-29#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-30, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0EB68TOZBhEZj9D5:-Mth0EB68TOZBhEZj9D6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-30#L48)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-31, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0Eyy9yS9r65XAXtk:-Mth0Eyy9yS9r65XAXtl:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-31#L48)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-32, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0FjUDLs8Y7T49MYj:-Mth0FjUDLs8Y7T49MYk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-32#L48)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-33, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0GRG4NPPAkPH3KEo:-Mth0GRG4NPPAkPH3KEp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-33#L48)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-34, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0HGB0FSOWdrpNWr3:-Mth0HGB0FSOWdrpNWr4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-34#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-rawhide, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0I0R-kN2GdB6vVJv:-Mth0I0R-kN2GdB6vVJw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-rawhide#L49)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.opensuse-leap-latest, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0IlXCRJeGlyt4cKp:-Mth0IlXCRJeGlyt4cKq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.opensuse-leap-latest#L47)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

.
___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-la [...]

2022-01-18 12:05 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 32 unresolved discussions (waiting on @haichangsi)

___
*[utils/docker/images/Dockerfile.debian-10, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth3fRj1wuNXzsAuZWQ:-Mth3fRj1wuNXzsAuZWR:bsksfm4) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-10#L52)):*
> ```
> 	paramiko \
> 	scp \
> 	coverage"
> ```

It looks like the coverage package does not provide the coverage command:
https://github.com/pmem/rpma/runs/4851807050?check_suite_focus=true
```
./run-build.sh: line 152: coverage: command not found
Error: Process completed with exit code 127.
```


<!-- Sent from Reviewable.io -->

2022-01-18 12:08 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 33 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-Mth4GZ7BUHc_ZVS2v78:-Mth4GZ7BUHc_ZVS2v79:bjiym60) (no related file):*
For the following OSes (failing builds) the coverage package does not provide the coverage command:
https://github.com/ldorau/rpma/actions/runs/1712587495
```
./run-build.sh: line 152: coverage: command not found
Error: Process completed with exit code 127.
```

---


<!-- Sent from Reviewable.io -->

2022-01-26 08:37 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 32 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-Mth4GZ7BUHc_ZVS2v78:-MuKWrRV4HVrEut87miB:b-jcx7zd) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

For the following OSes (failing builds) the coverage package does not provide the coverage command:
https://github.com/ldorau/rpma/actions/runs/1712587495
```
./run-build.sh: line 152: coverage: command not found
Error: Process completed with exit code 127.
```
</blockquote></details>

@haichangsi  I was wrong.  The coverage package does provide the coverage command, but it just wasn't in the `PATH` ... :-)

---


<!-- Sent from Reviewable.io -->

2022-01-27 09:02 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: 0 of 29 files reviewed, 32 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-Mth-yUr6HJZktdEqawo:-MuPlGd90tbTgcK3mblZ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please keep alphabetical order of packages in all Dockerfiles
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth-_4z54lhz2rTkkUi):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

package
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-27 09:04 UTC, ldorau requested changes
> Reviewed 15 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: 15 of 29 files reviewed, 15 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-MuPlbLB8kjOL7GoSAxI:-MuPlbLC6KoHlELtxwKB:bq6himo) (no related file):*
Please rebase it on the current master - many Dockerfiles have been removed.

---


<!-- Sent from Reviewable.io -->

2022-01-27 09:06 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: 15 of 29 files reviewed, 15 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth-g21-sujyMEh_MVp:-MuPlMB0DRSyYIwswHDV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.archlinux-latest#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please keep alphabetical order in all Dockerfiles
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-7, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth01q_E5a4yQZBuvnH:-MuPlReS88i243oLO-yl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.centos-7#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-8, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth03ATBOg59-Gp1NtC:-MuPlS9VEwxDPp3uDVUn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.centos-8#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-stream, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth046yEkwKVP3t_SFV:-MuPlSVs3ymvE1uoUcid:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.centos-stream#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-10, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth050d-yrs_G1nLYgi:-MuPlSs_AcxDWoIA6ar9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-10#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-10, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth3fRj1wuNXzsAuZWQ:-MuPlTzy5ZOk4T03Wtdb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-10#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It looks like the coverage package does not provide the coverage command:
https://github.com/pmem/rpma/runs/4851807050?check_suite_focus=true
```
./run-build.sh: line 152: coverage: command not found
Error: Process completed with exit code 127.
```
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-11, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth05wb-aNI9aIHFTdq:-MuPlUJO4z5ftL-rrR2V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-11#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-9, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth06rS5mrrxngK2Edz:-MuPlUgD2EGTo3OgJCpd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-9#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-experimental, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth08234bavtQXb0toV:-MuPlV3v7VB9VXqhr3Sx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-experimental#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-stable, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth08sX1xj2Va4FNiMg:-MuPlVTC9Tk4zl3q7Ckh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-stable#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-testing, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth09jYEdC4CZTmYJDJ:-MuPlVyG-kfTzSwSGHL4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.debian-testing#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-26, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0AWk85MTmJ2whJDF:-MuPlWLe0rm6qXza7sif:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-26#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-27, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0Bfc2EkUOVmGLcFf:-MuPlWce6WHHQvnhWhUZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-27#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-28, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0CcH9ITmmZeYfV7C:-MuPlX-_6WtW1BYq_hu_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-28#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-29, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0DJpA54kUST3NCeL:-MuPlXN48rxb6yyd9Tji:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-29#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-30, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0EB68TOZBhEZj9D5:-MuPlXzfEi0O-a6gGQ-Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-30#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-31, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0Eyy9yS9r65XAXtk:-MuPlYMd3uUy0ccpCE73:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-31#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-32, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1502#-Mth0FjUDLs8Y7T49MYj:-MuPlYo16Pnh3axLJUoC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc40200bdd5834aacc941fdc567fbd28fb2e55de/utils/docker/images/Dockerfile.fedora-32#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

 [...]

2022-01-27 09:06 UTC, ldorau reviewed
> Reviewed 14 of 29 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-01-27 09:11 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-MuPlbLB8kjOL7GoSAxI:-MuPmyzw4_wYY0hjV1ax:b-pvpbfr) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase it on the current master - many Dockerfiles have been removed.
</blockquote></details>

As you said pr is on the devel branch and it should stay like that

---


<!-- Sent from Reviewable.io -->

2022-01-27 09:20 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1502#-MuPlbLB8kjOL7GoSAxI:-MuPpLBg5ejy5-42vNN6:bf41gt0) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

As you said pr is on the devel branch and it should stay like that
</blockquote></details>

Yes, it is OK, excuse me.

---


<!-- Sent from Reviewable.io -->

2022-01-27 09:22 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-01-27 09:24 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502#-:-MuPqPvp155QF-WLFzaR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-01-27 10:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1502#-MuQ0jUZ9PdO28gyCgWW:-MuQ0jUZ9PdO28gyCgWX:blkhyx0) ([raw file](https://github.com/pmem/rpma/blob/3662706a628f73638e6dba0f579360371c0d15f0/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L43)):*
> ```
> 
> ENV PYTHON_DEPS "\
> 	coverage \
> ```

See: https://github.com/ldorau/rpma/runs/4964338087
```
Traceback (most recent call last):
  File "/home/user/.local/bin/coverage", line 5, in <module>
    from coverage.cmdline import main
  File "/home/user/.local/lib/python3.8/site-packages/coverage/__init__.py", line 15, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/user/.local/lib/python3.8/site-packages/coverage/control.py", line 22, in <module>
    from coverage.data import CoverageData, combine_parallel_data
  File "/home/user/.local/lib/python3.8/site-packages/coverage/data.py", line 18, in <module>
    from coverage.sqldata import CoverageData
  File "/home/user/.local/lib/python3.8/site-packages/coverage/sqldata.py", line 18, in <module>
    import sqlite3
  File "/usr/lib64/python3.8/_import_failed/sqlite3.py", line 16, in <module>
    raise ImportError(f"""Module '{failed_name}' is not installed.
ImportError: Module 'sqlite3' is not installed.
Use:
  sudo zypper install python38
to install it.
```


<!-- Sent from Reviewable.io -->

2022-01-27 11:09 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: 28 of 29 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1502#-MuQ0jUZ9PdO28gyCgWW:-MuQDQhI9bGk3Eh8NzlU:brt56zc) ([raw file](https://github.com/pmem/rpma/blob/3662706a628f73638e6dba0f579360371c0d15f0/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See: https://github.com/ldorau/rpma/runs/4964338087
```
Traceback (most recent call last):
  File "/home/user/.local/bin/coverage", line 5, in <module>
    from coverage.cmdline import main
  File "/home/user/.local/lib/python3.8/site-packages/coverage/__init__.py", line 15, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/user/.local/lib/python3.8/site-packages/coverage/control.py", line 22, in <module>
    from coverage.data import CoverageData, combine_parallel_data
  File "/home/user/.local/lib/python3.8/site-packages/coverage/data.py", line 18, in <module>
    from coverage.sqldata import CoverageData
  File "/home/user/.local/lib/python3.8/site-packages/coverage/sqldata.py", line 18, in <module>
    import sqlite3
  File "/usr/lib64/python3.8/_import_failed/sqlite3.py", line 16, in <module>
    raise ImportError(f"""Module '{failed_name}' is not installed.
ImportError: Module 'sqlite3' is not installed.
Use:
  sudo zypper install python38
to install it.
```

</blockquote></details>

I added python38 to TOOLS_DEBS


<!-- Sent from Reviewable.io -->

2022-01-27 11:51 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-01-27 12:06 UTC, ldorau approved these changes
All CI builds passed: https://github.com/ldorau/rpma/runs/4965585048?check_suite_focus=true

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1502#-:-MuQQTAaDS48K2675-3H:b7ogrin)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-01-27 12:06 UTC, merged