rpma: Tally APIs
pmem/rpma pull request #1504
Opened 2022-01-20 00:56 UTC by Patryk717

PR  #1271

2022-01-20 08:58 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2823 at r1](https://reviewable.io/reviews/pmem/rpma/1504#-Mtqh0CYB4l8Xd5dqjUf:-Mtqh0CYB4l8Xd5dqjUg:b-8jphnh) ([raw file](https://github.com/pmem/rpma/blob/f72eb37ebff706a6746a725e2261619a04eb5814/src/include/librpma.h#L2823)):*
> ```objc
>  * CODE BEFORE CHANGING
>  * if (ret)
>  * goto err_mr_remote_delete;
> ```

to be removed



_Code quote:_
```objc
 * if (ret)
 * goto err_mr_remote_delete;
 *
```
___
*[src/include/librpma.h, line 2837 at r1](https://reviewable.io/reviews/pmem/rpma/1504#-MtqhIh6AVSKItoooyiY:-MtqhIh6AVSKItoooyiZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f72eb37ebff706a6746a725e2261619a04eb5814/src/include/librpma.h#L2837)):*
> ```objc
>  * CODE AFTER CHANGING
>  * if (ret)
>  * goto err_mr_remote_delete;
> ```

.



_Code quote:_
```objc
 * if (ret)
 * goto err_mr_remote_delete;
 *
```


<!-- Sent from Reviewable.io -->

2022-01-20 08:59 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2681 at r1](https://reviewable.io/reviews/pmem/rpma/1504#-MtqhQle-38A5E1GaeIv:-MtqhQlf9y0TQeghJo0j:b-mzmx8a) ([raw file](https://github.com/pmem/rpma/blob/f72eb37ebff706a6746a725e2261619a04eb5814/src/include/librpma.h#L2681)):*
> ```objc
>  *
>  * DEPRECATED
>  * CODE BEFORE CHANGES ( examples/06-multiple-connections/server.c )
> ```

too long

In my opinion it will be enough what is written in next change below


<!-- Sent from Reviewable.io -->

2022-01-20 09:02 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2681 at r1](https://reviewable.io/reviews/pmem/rpma/1504#-MtqhQle-38A5E1GaeIv:-MtqiCtR9ys97wACmpnG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f72eb37ebff706a6746a725e2261619a04eb5814/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

too long

In my opinion it will be enough what is written in next change below
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2823 at r1](https://reviewable.io/reviews/pmem/rpma/1504#-Mtqh0CYB4l8Xd5dqjUf:-MtqhhVM0jHkzpMkqPn4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f72eb37ebff706a6746a725e2261619a04eb5814/src/include/librpma.h#L2823)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

to be removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 10:09 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[src/include/librpma.h, line 2837 at r1](https://reviewable.io/reviews/pmem/rpma/1504#-MtqhIh6AVSKItoooyiY:-MtqxaAD8nUzVHyafJFL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f72eb37ebff706a6746a725e2261619a04eb5814/src/include/librpma.h#L2837)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 10:13 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-01-20 11:43 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHaf--CAqWoQn5Y56:-MtrHaf--CAqWoQn5Y57:bfgzk90) ([raw file](https://github.com/pmem/rpma/blob/7a706baf34fed4d8bc5723af174313621870ffc4/src/include/librpma.h#L2681)):*
> ```objc
>  *
>  * DEPRECATED
>  * Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
> ```

This line should be left here.



_Code quote:_
```objc
Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
```
___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHkP642sQWHQrT5GO:-MtrHkP642sQWHQrT5GP:b4o62an) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2681)):*
> ```objc
>  *
>  * DEPRECATED
>  * CODE TO BE REMOVED
> ```

Not needed, please remove



_Code quote:_
```objc
CODE TO BE REMOVED
```
___
*[src/include/librpma.h, line 2689 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHsMSAotRPSCc61v8:-MtrHsMSAotRPSCc61v9:brp72vi) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2689)):*
> ```objc
>  * / resources - memory regions /
>  * size_t offset;
>  * (line 151)
> ```

Such comments are not needed, it should pure C code.



_Code quote:_
```objc
(line 151)
```
___
*[src/include/librpma.h, line 2696 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrI1-vCq3c2lsMYcQI:-MtrI1-vCq3c2lsMYcQJ:b7r1mkk) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2696)):*
> ```objc
>  * if (ret) {
>  * epoll_delete(epoll, &clnt->ev_conn_event);
>  * return ret;
> ```

It should be indented like a real C code. It is unreadable in the current form.



_Code quote:_
```objc
 *
 * / get the connection's completion fd and add it to epoll /
 * ret = rpma_conn_get_completion_fd(clnt->conn, &fd);
 * if (ret) {
 * epoll_delete(epoll, &clnt->ev_conn_event);
 * return ret;
 * (line 206)
 * struct client_res *clnt = (struct client_res *)ce->arg;
 * const struct server_res *svr = clnt->svr;
```


<!-- Sent from Reviewable.io -->

2022-01-20 11:52 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHaf--CAqWoQn5Y56:-MtrJ4C87oHcseqxl9_i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a706baf34fed4d8bc5723af174313621870ffc4/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This line should be left here.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHkP642sQWHQrT5GO:-MtrJ52DBO942bCt3wkL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed, please remove
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2689 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHsMSAotRPSCc61v8:-MtrK5qC0JDR08-gS74s:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2689)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Such comments are not needed, it should pure C code.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2696 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrI1-vCq3c2lsMYcQI:-MtrK87N0EIXs7Rz5Cwe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2696)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be indented like a real C code. It is unreadable in the current form.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 11:55 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHaf--CAqWoQn5Y56:-MtrKPqc5ShcY5c8QSys:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/7a706baf34fed4d8bc5723af174313621870ffc4/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.
___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHkP642sQWHQrT5GO:-MtrKS9v2ASTg5jkgJCr:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.
___
*[src/include/librpma.h, line 2696 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrI1-vCq3c2lsMYcQI:-MtrKhBEDBvAaRBDkYSe:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2696)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.


<!-- Sent from Reviewable.io -->

2022-01-20 11:58 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1504#-MtrLRFe82ZoJ-iYtvB6):*
Please add `Ref: #1271` to the commit message



_Code quote:_
```
pma: comparison of old and new API
```


<!-- Sent from Reviewable.io -->

2022-01-20 12:25 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1504#-MtrLRFe82ZoJ-iYtvB6):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add `Ref: #1271` to the commit message
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHkP642sQWHQrT5GO:-MtrR4UX0Tx2MeW3JGJr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2681 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrHaf--CAqWoQn5Y56:-MtrRQmUA80BUggAuZJj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a706baf34fed4d8bc5723af174313621870ffc4/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2696 at r3](https://reviewable.io/reviews/pmem/rpma/1504#-MtrI1-vCq3c2lsMYcQI:-MtrR6HL3tgw2VN8oBOv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be1f8717fc63a0ecce934cfd4ef04f37fdfa25cd/src/include/librpma.h#L2696)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 12:33 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2681 at r6](https://reviewable.io/reviews/pmem/rpma/1504#-MtrS5EH21YFXToaJi9l:-MtrS5EH21YFXToaJi9m:b-agjebv) ([raw file](https://github.com/pmem/rpma/blob/f6ad980970a145e16a315ccff087fccf52be84da/src/include/librpma.h#L2681)):*
> ```objc
>  *
>  * DEPRECATED
>  * Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
> ```

```
 * Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
 * This is an example snippet of code using old API:
 * 
 * [snippet with old API]
 * 
 * The above snippet should be replaced with the following one using the new API:
 * 
 * [snippet with new API]
 * 
```



_Code quote:_
```objc
 * Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
```
___
*[src/include/librpma.h, line 2688 at r6](https://reviewable.io/reviews/pmem/rpma/1504#-MtrRvu5Bf6KJsxNR7DC:-MtrRvu5Bf6KJsxNR7DD:bqfmj6m) ([raw file](https://github.com/pmem/rpma/blob/f6ad980970a145e16a315ccff087fccf52be84da/src/include/librpma.h#L2688)):*
> ```objc
>  *     size_t offset;
>  *
>  *         return ret;
> ```

It does not look like a correct C code ;-) 



_Code quote:_
```objc
 * struct client_res {
 *     struct rpma_conn *conn;
 *
 *     size_t offset;
 *
 *         return ret;
```


<!-- Sent from Reviewable.io -->

2022-01-20 12:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2691 at r6](https://reviewable.io/reviews/pmem/rpma/1504#-MtrTsnt5AwP-29ctsaj:-MtrTsnt5AwP-29ctsak:b-ghr0la) ([raw file](https://github.com/pmem/rpma/blob/f6ad980970a145e16a315ccff087fccf52be84da/src/include/librpma.h#L2691)):*
> ```objc
>  *
>  *     ret = rpma_conn_get_completion_fd(clnt->conn, &fd);
>  *     if (ret) {
> ```

The example code has to be a correct and complete C code (there should be both: `{` and `}` for example) ....



_Code quote:_
```objc
 *     ret = rpma_conn_get_completion_fd(clnt->conn, &fd);
 *     if (ret) {
 *         epoll_delete(epoll, &clnt->ev_conn_event);
 *         return ret;
 *
 *     struct client_res *clnt = (struct client_res *)ce->arg;
 *     const struct server_res *svr = clnt->svr;
 *
 *     int ret = rpma_conn_completion_wait(clnt->conn);
 *     if (ret) {
 *          if (ret == RPMA_E_NO_COMPLETION)
 *
 *     struct rpma_completion cmpl;
 *     ret = rpma_conn_completion_get(clnt->conn, &cmpl);
```


<!-- Sent from Reviewable.io -->

2022-01-20 12:36 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-20 13:34 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-20 15:41 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2695 at r8](https://reviewable.io/reviews/pmem/rpma/1504#-Mts8VZnBxfMmwF5X13Y:-Mts8VZnBxfMmwF5X13Z:bd4btah) ([raw file](https://github.com/pmem/rpma/blob/95d78ad91523f4adf29806666dd1cf6668b49d4b/src/include/librpma.h#L2695)):*
> ```objc
>  * ret = rpma_conn_completion_get(conn);
>  * if (ret) {
>  *     error handling code
> ```

`/* error handling code */` in all places, please.



_Code quote:_
```objc
error handling code
```


<!-- Sent from Reviewable.io -->

2022-01-20 15:42 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1504#-Mts8ldD4xBr2y94_Cgk:-Mts8ldD4xBr2y94_Cgl:bhfcs0d) (no related file):*
Builds fail:
```
/rpma/src/include/librpma.h:2714: improper block comment
/rpma/src/include/librpma.h:2714: indent by spaces instead of tabs
```

---


<!-- Sent from Reviewable.io -->

2022-01-20 20:57 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2770 at r8](https://reviewable.io/reviews/pmem/rpma/1504#-MttGuCz6Rwbq0mGZHXO:-MttGuCz6Rwbq0mGZHXP:b-7ao9aw) ([raw file](https://github.com/pmem/rpma/blob/95d78ad91523f4adf29806666dd1cf6668b49d4b/src/include/librpma.h#L2770)):*
> ```objc
>  *
>  * DEPRECATED
>  * CODE TO BE REMOVED
> ```

Please use the same format as suggested by @ldorau above.



_Code quote:_
```objc
CODE TO BE REMOVED
```


<!-- Sent from Reviewable.io -->

2022-01-21 11:16 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ldorau and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-21 11:16 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2681 at r6](https://reviewable.io/reviews/pmem/rpma/1504#-MtrS5EH21YFXToaJi9l:-MtwLMtA4i5T3PvLrCo6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f6ad980970a145e16a315ccff087fccf52be84da/src/include/librpma.h#L2681)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
 * Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
 * This is an example snippet of code using old API:
 * 
 * [snippet with old API]
 * 
 * The above snippet should be replaced with the following one using the new API:
 * 
 * [snippet with new API]
 * 
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2688 at r6](https://reviewable.io/reviews/pmem/rpma/1504#-MtrRvu5Bf6KJsxNR7DC:-MtwLN_w5CXrAEDrP50N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f6ad980970a145e16a315ccff087fccf52be84da/src/include/librpma.h#L2688)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does not look like a correct C code ;-) 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2770 at r8](https://reviewable.io/reviews/pmem/rpma/1504#-MttGuCz6Rwbq0mGZHXO:-MtwL_vo9FDaNx0Ngzop:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/95d78ad91523f4adf29806666dd1cf6668b49d4b/src/include/librpma.h#L2770)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please use the same format as suggested by @ldorau above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 11:18 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2691 at r6](https://reviewable.io/reviews/pmem/rpma/1504#-MtrTsnt5AwP-29ctsaj:-MtwLo8389RIzKkUsL9I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f6ad980970a145e16a315ccff087fccf52be84da/src/include/librpma.h#L2691)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The example code has to be a correct and complete C code (there should be both: `{` and `}` for example) ....
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-21 11:33 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1504#-Mts8ldD4xBr2y94_Cgk:-MtwPNtd65YynqjRHCpJ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds fail:
```
/rpma/src/include/librpma.h:2714: improper block comment
/rpma/src/include/librpma.h:2714: indent by spaces instead of tabs
```

</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-01-21 12:09 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[src/include/librpma.h, line 2684 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwUGlf-oufCZKbv3ta:-MtwUGlf-oufCZKbv3tb:b-4gnwgg) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2684)):*
> ```objc
>  * This is an example snippet of code using old API:
>  *
>  * ret = rpma_conn_get_completion_fd(conn);
> ```

int fd;
int ret;

ret = rpma_conn_get_completion_fd(conn, &fd);



_Suggestion:_
```objc
ret = rpma_conn_get_completion_fd(conn);
```
___
*[src/include/librpma.h, line 2689 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwW_0T29fh8kUFPUhX:-MtwW_0T29fh8kUFPUhY:b-i8vu9y) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2689)):*
> ```objc
>  * }
>  *
>  * int ret = rpma_conn_completion_wait(conn);
> ```

Remove ```int```



_Code quote:_
```objc
int
```
___
*[src/include/librpma.h, line 2694 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwXAq13pGVBIbz5EEG:-MtwXAq13pGVBIbz5EEH:b-8sk36u) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2694)):*
> ```objc
>  * }
>  *
>  * ret = rpma_conn_completion_get(conn);
> ```

struct rpma_completion cmpl;
rpma_conn_completion_get(conn, **&cmpl**)



_Suggestion:_
```objc
rpma_conn_completion_get(conn)
```
___
*[src/include/librpma.h, line 2704 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwTS6e60jBQR4vUjhY:-MtwTS6e60jBQR4vUjhZ:b-wlgopw) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2704)):*
> ```objc
>  * ret = rpma_cq_get_fd(cq);
>  * if (ret) {
>  *     / error handling code /
> ```

Change the order of API calls:
-  start w/ obtaining cq as the first step
- _get_fd(cq, **&fd**)
- _wait(cq)
- struct rpma_completion cmpl;
- _get_completion(cq, **&comp**)



_Code quote:_
```objc
 * ret = rpma_cq_get_fd(cq);
 * if (ret) {
 *     / error handling code /
 * }
 *
 * int ret = rpma_cq_wait(cq);
 * if (ret) {
 *    / error handling code /
 * }
 *
 * ret = rpma_cq_get_completion(cq);
 * if (ret) {
 *    / error handling code /
 * }
 *
 * if (rpma_conn_get_cq(conn,cq)) {
 *    / error handling code /
 * }
```


<!-- Sent from Reviewable.io -->

2022-01-22 13:55 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[src/include/librpma.h, line 2695 at r8](https://reviewable.io/reviews/pmem/rpma/1504#-Mts8VZnBxfMmwF5X13Y:-Mu13OhrB8TxlNtAnDdE:b58655v) ([raw file](https://github.com/pmem/rpma/blob/95d78ad91523f4adf29806666dd1cf6668b49d4b/src/include/librpma.h#L2695)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`/* error handling code */` in all places, please.
</blockquote></details>

Not: 
```
 / error handling code /
```
but, as I wrote:
```
/* error handling code */
```



_Code quote:_
```objc
 / error handling code /
```


<!-- Sent from Reviewable.io -->

2022-01-22 13:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[src/include/librpma.h, line 2715 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-Mu13x-2-YTGhp8EzgDN:-Mu13x-2-YTGhp8EzgDO:b-kb8pzp) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2715)):*
> ```objc
>  * if (ret) {
>  *    / error handling code /
>  * }
> ```

@grom72 what do you think about replacing it with:
```
 * if (ret) { /* error handling code */ }
```
or even:
```
 * if (ret) { /* ... */ }
```
?
It would be much shorter.



_Code quote:_
```objc
 * if (ret) {
 *    / error handling code /
 * }
```


<!-- Sent from Reviewable.io -->

2022-01-22 14:16 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 6 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-22 21:01 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[src/include/librpma.h, line 2715 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-Mu13x-2-YTGhp8EzgDN:-Mu2_OCw9eWw5XzT-qCc:b39qwx) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2715)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 what do you think about replacing it with:
```
 * if (ret) { /* error handling code */ }
```
or even:
```
 * if (ret) { /* ... */ }
```
?
It would be much shorter.
</blockquote></details>

Yes, but I propose to left ```{ /* error handling code */ }``` as it is in the first example above. ret <> 0 means error


<!-- Sent from Reviewable.io -->

2022-01-24 08:08 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2715 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-Mu13x-2-YTGhp8EzgDN:-MuA7CD62yhRjSIQ0781:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2715)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Yes, but I propose to left ```{ /* error handling code */ }``` as it is in the first example above. ret <> 0 means error
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2022-01-24 12:01 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2695 at r11](https://reviewable.io/reviews/pmem/rpma/1504#-MuAxL1134n3l4goIB5o:-MuAxL1134n3l4goIB5p:b2gxg01) ([raw file](https://github.com/pmem/rpma/blob/1674290c08f89f46aad1b25a75731142a199fc51/src/include/librpma.h#L2695)):*
> ```objc
>  * struct rpma_completion cmpl;
>  * ret = rpma_conn_completion_get(conn,&cmpl);
>  * if (ret) { error_handling_code() }
> ```

Replace all:
```
{ error_handling_code() }
```
with:
```
{ /* error handling code */ }
```
please



_Code quote:_
```objc
{ error_handling_code() }
```


<!-- Sent from Reviewable.io -->

2022-01-24 12:04 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2695 at r8](https://reviewable.io/reviews/pmem/rpma/1504#-Mts8VZnBxfMmwF5X13Y:-MuAyIRK6T2gjBxb9Etr:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/95d78ad91523f4adf29806666dd1cf6668b49d4b/src/include/librpma.h#L2695)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not: 
```
 / error handling code /
```
but, as I wrote:
```
/* error handling code */
```

</blockquote></details>

OK
___
*[src/include/librpma.h, line 2695 at r11](https://reviewable.io/reviews/pmem/rpma/1504#-MuAxL1134n3l4goIB5o:-MuAyMxjEAg4YqXueqDq:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/1674290c08f89f46aad1b25a75731142a199fc51/src/include/librpma.h#L2695)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Replace all:
```
{ error_handling_code() }
```
with:
```
{ /* error handling code */ }
```
please
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2022-01-24 12:08 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[src/include/librpma.h, line 2694 at r11](https://reviewable.io/reviews/pmem/rpma/1504#-MuAb0jw8dmosV_HbI4i:-MuAb0jw8dmosV_HbI4j:b-2tijkv) ([raw file](https://github.com/pmem/rpma/blob/1674290c08f89f46aad1b25a75731142a199fc51/src/include/librpma.h#L2694)):*
> ```objc
>  *
>  * struct rpma_completion cmpl;
>  * ret = rpma_conn_completion_get(conn,&cmpl);
> ```

```conn, &cmpl```
<SPACE> between



_Code quote:_
```objc
conn,&cmpl
```


<!-- Sent from Reviewable.io -->

2022-01-24 12:10 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 4 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 12:11 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 12:58 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/include/librpma.h, line 2695 at r8](https://reviewable.io/reviews/pmem/rpma/1504#-Mts8VZnBxfMmwF5X13Y:-MuAKjf72FZrXTVwza0S:b-7rl0jd) ([raw file](https://github.com/pmem/rpma/blob/95d78ad91523f4adf29806666dd1cf6668b49d4b/src/include/librpma.h#L2695)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not: 
```
 / error handling code /
```
but, as I wrote:
```
/* error handling code */
```

</blockquote></details>

done.
___
*[src/include/librpma.h, line 2684 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwUGlf-oufCZKbv3ta:-MuAKDQS2-fHf-UlKVaN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2684)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

int fd;
int ret;

ret = rpma_conn_get_completion_fd(conn, &fd);
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2689 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwW_0T29fh8kUFPUhX:-MuAKDiW3SyjBnixhEBz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2689)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Remove ```int```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2694 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwXAq13pGVBIbz5EEG:-MuAOx1wDJ-MF_E6v8aC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2694)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

struct rpma_completion cmpl;
rpma_conn_completion_get(conn, **&cmpl**)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2704 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-MtwTS6e60jBQR4vUjhY:-MuAQONYAeEesv-MSnL5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2704)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Change the order of API calls:
-  start w/ obtaining cq as the first step
- _get_fd(cq, **&fd**)
- _wait(cq)
- struct rpma_completion cmpl;
- _get_completion(cq, **&comp**)

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2715 at r10](https://reviewable.io/reviews/pmem/rpma/1504#-Mu13x-2-YTGhp8EzgDN:-MuAQNfI-7V7gbkMnuyW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39ee16baf84e334415b93c1a864bbc4a0bdafd29/src/include/librpma.h#L2715)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2694 at r11](https://reviewable.io/reviews/pmem/rpma/1504#-MuAb0jw8dmosV_HbI4i:-MuB9eATAYFE83hUEka9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88e3750c918d25536b5b476fabce2cc69db2d797/src/include/librpma.h#L2694)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```conn, &cmpl```
<SPACE> between
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-24 13:00 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[src/include/librpma.h, line 2694 at r11](https://reviewable.io/reviews/pmem/rpma/1504#-MuAb0jw8dmosV_HbI4i:-MuB9v1d9d5eP65Geupe:b-dwivl5) ([raw file](https://github.com/pmem/rpma/blob/88e3750c918d25536b5b476fabce2cc69db2d797/src/include/librpma.h#L2694)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

<SPACE> between


<!-- Sent from Reviewable.io -->

2022-01-24 13:04 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-24 13:04 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504#-:-MuBAxLCEOwM5Qchpqqh:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-01-24 13:18 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @Patryk717)

___
*[-- commits, line 3 at r12](https://reviewable.io/reviews/pmem/rpma/1504#-MuBE5GtBMcZjE8lC_zr):*
There has to be one empty line between commit's title and body:
```
rpma: comparison of old and new API

Ref: #1271
```



_Code quote:_
```
- d099c1c: rpma: comparison of old and new API
  Ref: #1271
```


<!-- Sent from Reviewable.io -->

2022-01-24 13:21 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2682 at r12](https://reviewable.io/reviews/pmem/rpma/1504#-MuBElc814zX6hhCAhpm:-MuBElc814zX6hhCAhpn:b-t1hpw3) ([raw file](https://github.com/pmem/rpma/blob/d099c1c74a9d615fe628b7e07d7c4333cc4cf223/src/include/librpma.h#L2682)):*
> ```objc
>  * DEPRECATED
>  * Please use rpma_conn_get_cq(3) and rpma_cq_get_fd(3) instead.
>  * This is an example snippet of code using old API:
> ```

the old API



_Code quote:_
```objc
old API
```
___
*[src/include/librpma.h, line 2765 at r12](https://reviewable.io/reviews/pmem/rpma/1504#-MuBEoqK3Bw-U-Ln8Rad:-MuBEoqK3Bw-U-Ln8Rae:b-t1hpw3) ([raw file](https://github.com/pmem/rpma/blob/d099c1c74a9d615fe628b7e07d7c4333cc4cf223/src/include/librpma.h#L2765)):*
> ```objc
>  *
>  * DEPRECATED
>  * This is an example snippet of code using old API:
> ```

the old API



_Code quote:_
```objc
old API
```


<!-- Sent from Reviewable.io -->

2022-01-24 13:35 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1504#-MuBHpHCCCOn8W6SvPOX:-MuBHpHCCCOn8W6SvPOY:bbxkx3x) (no related file):*
every new line to be marked with addidtional separate line
instead of:
```
* int ret;
* int fd;
```

should be:
```
* int ret;
*
* int fd;
```

---


<!-- Sent from Reviewable.io -->

2022-01-24 13:45 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[src/include/librpma.h, line 2 at r12](https://reviewable.io/reviews/pmem/rpma/1504#-MuBKRBn9ZDmaKIYlTK9:-MuBKRBn9ZDmaKIYlTKA:bb6ht37) ([raw file](https://github.com/pmem/rpma/blob/d099c1c74a9d615fe628b7e07d7c4333cc4cf223/src/include/librpma.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright 2019-2021, Intel Corporation */
> ```

2022



_Code quote:_
```objc
2021
```


<!-- Sent from Reviewable.io -->

2022-01-24 13:49 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 4 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 13:50 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: all files reviewed, 4 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 14:13 UTC, ldorau commented
It looks like that now:
![1](https://user-images.githubusercontent.com/8492895/150798705-54ba1b32-78d0-4a62-a9aa-b08653628c4e.png)

2022-01-24 14:14 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504#-:-MuBR8BG3OwjpYTGJv7A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 14:38 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504#-:-MuBWZ82BMLwATbKgkWv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 14:39 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1504)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-01-24 14:40 UTC, merged