examples: add the example_12 receive_completion_queue
pmem/rpma pull request #1528
Opened 2022-01-31 13:09 UTC by osalyk

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1528)

2022-01-31 14:27 UTC, ldorau requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/12-receive-completion-queue/README.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1528#-MukUBgU8FCggyW2pRZN:-MukUBgU8FCggyW2pRZO:b-37eh9c) ([raw file](https://github.com/pmem/rpma/blob/7e7fe9d14ee5e52ff2330c340b5dc8f1313cd24a/examples/12-receive-completion-queue/README.md#L1)):*
> ```Markdown
> Example of using receive completion queue
> ```

receive completion queue (RCQ)



_Code quote:_
```Markdown
receive completion queue
```
___
*[examples/12-receive-completion-queue/README.md, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1528#-MukUKeR5LJ8BC9DfaZ6:-MukUKeR5LJ8BC9DfaZ7:bycqp1w) ([raw file](https://github.com/pmem/rpma/blob/7e7fe9d14ee5e52ff2330c340b5dc8f1313cd24a/examples/12-receive-completion-queue/README.md#L4)):*
> ```Markdown
> ===
> 
> The messages ping pong example implements two parts of the messaging process:
> ```

Please update or change the description



_Code quote:_
```Markdown
ping pong example 
```


<!-- Sent from Reviewable.io -->

2022-01-31 14:28 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-31 14:31 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/12-receive-completion-queue/README.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1528#-MukUBgU8FCggyW2pRZN:-MukY1mDABSlT5c0y6AU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7fe9d14ee5e52ff2330c340b5dc8f1313cd24a/examples/12-receive-completion-queue/README.md#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

receive completion queue (RCQ)
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/README.md, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1528#-MukUKeR5LJ8BC9DfaZ6:-MukY20H76o5pwoOHrJz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7fe9d14ee5e52ff2330c340b5dc8f1313cd24a/examples/12-receive-completion-queue/README.md#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please update or change the description
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-31 14:32 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-01 09:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1528#-MuodEje6EcVbEc_SVKG:-MuodEjf8EDJUUR3XE0m:bcarc9t) (no related file):*
Please add this example to examples/run-all-on-SoftRoCE.sh and make sure the CircleCI build passes.

---


<!-- Sent from Reviewable.io -->

2022-02-02 20:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 5 of 7 files reviewed, 11 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw77GeBCJI2WtXlJ8w:-Muw77GeBCJI2WtXlJ8x:bqkk0y2) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L51)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	uint64_t cntr = strtoul_noerror(argv[3]);
> ```

What does it mean? What is the connection between `seed` and `cntr` ?



_Code quote:_
```C
cntr
```


<!-- Sent from Reviewable.io -->

2022-02-02 21:03 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 5 of 7 files reviewed, 15 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 130 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEcgi2cK6UFhxnzpq:-MuwEcgi2cK6UFhxnzpr:b7xpofd) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L130)):*
> ```C
> 			break;
> 
> 		/* prepare send completions, get one and validate it */
> ```

/* get one send completion and validate it */



_Code quote:_
```C
/* prepare send completions, get one and validate it */
```
___
*[examples/12-receive-completion-queue/client.c, line 162 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEsSk5IXD6Asp9Bmb:-MuwEsSk5IXD6Asp9Bmc:b-j5w70k) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L162)):*
> ```C
> 		}
> 
> 		/* prepare receive completions, get one and validate it */
> ```

/* get one receive completion and validate it */



_Code quote:_
```C
/* prepare receive completions, get one and validate it */
```
___
*[examples/12-receive-completion-queue/server.c, line 128 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEfjmC7255O_qbe3d:-MuwEfjmC7255O_qbe3e:b7xpofd) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L128)):*
> ```C
> 
> 	while (1) {
> 		/* prepare send completions, get one and validate it */
> ```

/* get one send completion and validate it */



_Code quote:_
```C
/* prepare send completions, get one and validate it */
```
___
*[examples/12-receive-completion-queue/server.c, line 164 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEpuf0sbGGxnCrhHC:-MuwEpuf0sbGGxnCrhHD:b-j5w70k) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L164)):*
> ```C
> 		}
> 
> 		/* prepare receive completions, get one and validate it */
> ```

/* get one receive completion and validate it */



_Code quote:_
```C
/* prepare receive completions, get one and validate it */
```


<!-- Sent from Reviewable.io -->

2022-02-03 07:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 5 of 7 files reviewed, 17 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw77GeBCJI2WtXlJ8w:-MuyWcQlCiH4TBnawbs2:b1nm78q) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What does it mean? What is the connection between `seed` and `cntr` ?
</blockquote></details>

I meant that names of variables should reflect their purpose/meaning.
___
*[examples/12-receive-completion-queue/client.c, line 133 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyXDJf-Gfci097k-xO:-MuyXDJf-Gfci097k-xP:b-o2t7fu) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L133)):*
> ```C
> 		ret = rpma_cq_get_wc(cq, 1, &wc, NULL);
> 		if (ret && ret != RPMA_E_NO_COMPLETION)
> 			break;
> ```

The whole part of code starting here at line no 131 and ending with ending at line no 195 is duplicated here. Please make a function:

```c
int get_wc_and_validate(struct rpma_cq *cq, enum ibv_wc_opcode opcode, char *func_name)
```

 and replace it with:

```c
		/* get one send completion and validate it */
		if (get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()"))
			break;

		/* get one receive completion and validate it */
		if (get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()"))
			break;
```



_Code quote:_
```C
		ret = rpma_cq_get_wc(cq, 1, &wc, NULL);
		if (ret && ret != RPMA_E_NO_COMPLETION)
			break;
```
___
*[examples/12-receive-completion-queue/client.c, line 194 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyYrwq2Wi7EObPE9D9:-MuyYrwq2Wi7EObPE9DA:b47zdq8) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L194)):*
> ```C
> 		}
> 
> 		if (ret)
> ```

This is the end of replaced code (see above) - it will not be needed any more.



_Code quote:_
```C
		if (ret)
			break;
```


<!-- Sent from Reviewable.io -->

2022-02-03 07:52 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 6 of 7 files reviewed, 17 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 08:11 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 4 of 7 files reviewed, 17 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muvznn18V_-68R9H7NL):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
examples: add example 12-receive-completion-queue

Add the example 12-receive-completion-queue for receive completion queue (RCQ).
```
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/client.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw3VPv2OLR6EpF4lLI:-MuyXodP9D9WzrKDeqMg:b-9gvgxj) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
#define USAGE_STR \
	"usage: %s <server_address> <port> <seed> <rounds> [<sleep>]\n"
```
</blockquote></details>

line > 80 characters
___
*[examples/12-receive-completion-queue/client.c, line 55 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw3o520LHhHjPKnE70:-MuyYMJPBFseVcrp54Wz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`if (argc >= 6)`
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/client.c, line 109 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw4SREBQSKopuYKZDC:-MuyYSrD4pGI-Q4aGKak:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L109)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

connection's RCQ
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/client.c, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw4b6bAJHH-wLio0an:-Muya4Ap2h5O9s96lX7i:b-71k5y0) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Have you checked is it still valid using RCQ?
</blockquote></details>

This is an example that demonstrates the use of CQ and RCQ. The comment should be removed 
___
*[examples/12-receive-completion-queue/client.c, line 130 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEcgi2cK6UFhxnzpq:-MuyYgoOC1Eyk6sTI27o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L130)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

/* get one send completion and validate it */
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/client.c, line 162 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEsSk5IXD6Asp9Bmb:-MuyYmrR5hl3uS9F0wm2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

/* get one receive completion and validate it */
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/README.md, line 15 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw-aHw6_s0JPL1yFyN:-MuyYssA4k-DpCe8gnef:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/README.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

we use **two** separate
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/README.md, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw-elT7V9Ci4xiHJDM:-MuyYxKi7sKH1XWdBhdW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/README.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
 - CQ for completions of sends and
 - RCQ for completions of receives.
```
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/README.md, line 26 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw5bsL0aJaGnFDL4fn:-MuyZPIa55dw_XgAkpVh:b-o5whyv) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/README.md#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is `$seed` used for? What does it mean?
</blockquote></details>

$seed is the value that we send.
___
*[examples/12-receive-completion-queue/server.c, line 119 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw2BRCEMY3hqNPR_H9:-MuyZoWt8hRYiuQbxBVc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`get the connection's RCQ` (remove main)
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/server.c, line 128 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEfjmC7255O_qbe3d:-MuyZtNA14kdsEYqhLYw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L128)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

/* get one send completion and validate it */
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/server.c, line 164 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuwEpuf0sbGGxnCrhHC:-MuyZytQ3iTZG5BjQTDT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

/* get one receive completion and validate it */
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 08:11 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 4 of 7 files reviewed, 19 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/server.c, line 92 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyZgc_7ZVi9C0AkaZ3:-MuyZgc_7ZVi9C0AkaZ4:bb72b0l) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L92)):*
> ```C
> 
> 	/*
> 	 * Put an initial receive to be prepared for the first message of
> ```

Post



_Code quote:_
```C
Put
```
___
*[examples/12-receive-completion-queue/server.c, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuycZZTCMLJMqessDdw:-MuycZZTCMLJMqessDdx:b-z1vxlb) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L125)):*
> ```C
> 
> 	/* IBV_WC_SEND completion in the first round is not present */
> 	int send_cmpl = 1;
> ```

This and the whole `while` can be replaced with (`int send_cmpl ` is not needed):
```c
	while (1) {
		/* get one receive completion and validate it */
		if (get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()"))
			break;

		if (*recv == I_M_DONE)
			break;

		/* print the received old value of the client's counter */
		(void) printf("SERVER: Value received: %" PRIu64 "\n", *recv);

		/* calculate a new counter's value */
		*send = *recv + 1;

		/* prepare a receive for the client's response */
		if ((ret = rpma_recv(conn, recv_mr, 0, MSG_SIZE, recv)))
			break;

		/* send the new value to the client */
		(void) printf("SERVER: Value sent: %" PRIu64 "\n", *send);
		if ((ret = rpma_send(conn, send_mr, 0, MSG_SIZE,
				/*
				 * XXX when using RPMA_F_COMPLETION_ON_ERROR
				 * after few rounds rpma_send() returns ENOMEM.
				 */
				RPMA_F_COMPLETION_ALWAYS, NULL)))
			break;

		/* get one send completion and validate it */
		if (get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()"))
			break;
	}
```



_Code quote:_
```C
	/* IBV_WC_SEND completion in the first round is not present */
	int send_cmpl = 1;

	while (1) {
		/* prepare send completions, get one and validate it */
```


<!-- Sent from Reviewable.io -->

2022-02-03 08:18 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw3VPv2OLR6EpF4lLI:-MuydgTR9ii_RGcuuG4O:b9ycnw0) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L22)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

line > 80 characters
</blockquote></details>

It is OK, please change
___
*[examples/12-receive-completion-queue/README.md, line 26 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw5bsL0aJaGnFDL4fn:-Muye7Zj8ffTJTxr0ZjR:bhmi69i) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/README.md#L26)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

$seed is the value that we send.
</blockquote></details>

I know :-) but a user does not - it should be explained here what it is for :-)


<!-- Sent from Reviewable.io -->

2022-02-03 08:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 133 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyXDJf-Gfci097k-xO:-MuyjNT06Hi6O5lmPpXI:b-cudx5s) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The whole part of code starting here at line no 131 and ending with ending at line no 195 is duplicated here. Please make a function:

```c
int get_wc_and_validate(struct rpma_cq *cq, enum ibv_wc_opcode opcode, char *func_name)
```

 and replace it with:

```c
		/* get one send completion and validate it */
		if (get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()"))
			break;

		/* get one receive completion and validate it */
		if (get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()"))
			break;
```

</blockquote></details>

It should be rather:
```c
		/* get one send completion and validate it */
		ret = get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()");
		if (ret)			
			break;

		/* get one receive completion and validate it */
		ret = get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()");
		if (ret)			
			break;
```


<!-- Sent from Reviewable.io -->

2022-02-03 08:42 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[examples/12-receive-completion-queue/server.c, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuycZZTCMLJMqessDdw:-MuyjleK4ckGlWm1jHVR:b4ssqc1) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This and the whole `while` can be replaced with (`int send_cmpl ` is not needed):
```c
	while (1) {
		/* get one receive completion and validate it */
		if (get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()"))
			break;

		if (*recv == I_M_DONE)
			break;

		/* print the received old value of the client's counter */
		(void) printf("SERVER: Value received: %" PRIu64 "\n", *recv);

		/* calculate a new counter's value */
		*send = *recv + 1;

		/* prepare a receive for the client's response */
		if ((ret = rpma_recv(conn, recv_mr, 0, MSG_SIZE, recv)))
			break;

		/* send the new value to the client */
		(void) printf("SERVER: Value sent: %" PRIu64 "\n", *send);
		if ((ret = rpma_send(conn, send_mr, 0, MSG_SIZE,
				/*
				 * XXX when using RPMA_F_COMPLETION_ON_ERROR
				 * after few rounds rpma_send() returns ENOMEM.
				 */
				RPMA_F_COMPLETION_ALWAYS, NULL)))
			break;

		/* get one send completion and validate it */
		if (get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()"))
			break;
	}
```

</blockquote></details>

It should be rather:
```c
	while (1) {
		/* get one receive completion and validate it */
		ret = get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()");
		if (ret)			
			break;

[...]
		/* get one send completion and validate it */
		ret = get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()");
		if (ret)			
			break;
	}
```


<!-- Sent from Reviewable.io -->

2022-02-03 08:48 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 133 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyXDJf-Gfci097k-xO:-MuylBfY4jz0S_pg87o5:b-6swd7q) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be rather:
```c
		/* get one send completion and validate it */
		ret = get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()");
		if (ret)			
			break;

		/* get one receive completion and validate it */
		ret = get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()");
		if (ret)			
			break;
```
</blockquote></details>

An implementation of `int get_wc_and_validate(struct rpma_cq *cq, enum ibv_wc_opcode opcode, char *func_name)` should be placed in `receive-completion-queue-common.c`.


<!-- Sent from Reviewable.io -->

2022-02-03 09:19 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 3 of 8 files reviewed, 8 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw3VPv2OLR6EpF4lLI:-MuygMLNDzWhHFxT93QT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is OK, please change
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/client.c, line 133 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyXDJf-Gfci097k-xO:-MuyiQDB7cNv-N1P5dnP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The whole part of code starting here at line no 131 and ending with ending at line no 195 is duplicated here. Please make a function:

```c
int get_wc_and_validate(struct rpma_cq *cq, enum ibv_wc_opcode opcode, char *func_name)
```

 and replace it with:

```c
		/* get one send completion and validate it */
		if (get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()"))
			break;

		/* get one receive completion and validate it */
		if (get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()"))
			break;
```

</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/client.c, line 194 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyYrwq2Wi7EObPE9D9:-MuyiT771Dg3CmeeJxwI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L194)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This is the end of replaced code (see above) - it will not be needed any more.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 10:19 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 1 of 8 files reviewed, 8 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 133 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyXDJf-Gfci097k-xO:-Muz3yBQCTPyjVtZDd0x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L133)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/README.md, line 26 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw0VA34C7p86auKOMl:-Muz4dAQBq1EEmkCG5AW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/README.md#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`#` seems not needed here
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/server.c, line 92 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuyZgc_7ZVi9C0AkaZ3:-Muys_iX0O-UKisK6iai:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Post
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/server.c, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-MuycZZTCMLJMqessDdw:-Muz3shw5V0_9XC0UQza:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/server.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be rather:
```c
	while (1) {
		/* get one receive completion and validate it */
		ret = get_wc_and_validate(rcq, IBV_WC_RECV, "rpma_recv()");
		if (ret)			
			break;

[...]
		/* get one send completion and validate it */
		ret = get_wc_and_validate(cq, IBV_WC_SEND, "rpma_send()");
		if (ret)			
			break;
	}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 10:20 UTC, ldorau requested changes
> Reviewed 3 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 4 of 8 files reviewed, 9 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw3VPv2OLR6EpF4lLI:-Muz3vAO2Rf-QwXXZ7TT:bl3117f) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L22)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I wrote something different - a long message has to be the first token in the line.
___
*[examples/12-receive-completion-queue/client.c, line 126 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz4eEn4CO0_vXAKAiC:-Muz4eEn4CO0_vXAKAiD:bhqzqhg) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/client.c#L126)):*
> ```C
> 
> 		/* get one send completion and validate it */
> 		if ((ret = get_wc_and_validate(wc, cq, IBV_WC_SEND, "rpma_send()")))
> ```

`wc` is not needed as a parameter in this function



_Code quote:_
```C
(wc,
```
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.h, line 21 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz50Hr8zi5UkWx0VRM:-Muz50Hr8zi5UkWx0VRN:bk1qt75) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/receive-completion-queue-common.h#L21)):*
> ```objc
> #define I_M_DONE	(uint64_t)UINT64_MAX
> 
> int get_wc_and_validate(struct ibv_wc wc, struct rpma_cq *cq,
> ```

It is not needed as a parameter - it can be defined inside the function.



_Code quote:_
```objc
struct ibv_wc wc,
```
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 14 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5ATcCD-b6RY4zOAI:-Muz5ATcCD-b6RY4zOAJ:bk1qt75) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/receive-completion-queue-common.c#L14)):*
> ```C
> 
> int
> get_wc_and_validate(struct ibv_wc wc, struct rpma_cq *cq,
> ```

It is not needed as a parameter - it can be defined inside the function.



_Code quote:_
```C
struct ibv_wc wc
```


<!-- Sent from Reviewable.io -->

2022-02-03 10:21 UTC, ldorau reviewed
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 10:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 11 unresolved discussions (waiting on @osalyk)

___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 22 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5tBoCEW-l03R1ppv:-Muz5tBoCEW-l03R1ppw:b-oc9hmx) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L22)):*
> ```C
> 	if ((ret = rpma_cq_get_wc(cq, 1,
> 				&wc, NULL)))
> 			return ret;
> ```

```
	int ret;

	if ((ret = rpma_cq_wait(cq)))
			return ret;

	if ((ret = rpma_cq_get_wc(cq, 1, &wc, NULL)))
			return ret;
```



_Code quote:_
```C
	int ret = 0;
	if ((ret = rpma_cq_wait(cq)))
			return ret;
	if ((ret = rpma_cq_get_wc(cq, 1,
				&wc, NULL)))
			return ret;
```
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 26 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz61Vp1bAEIVrvy05R:-Muz61Vp1bAEIVrvy05S:b-x4a7ai) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L26)):*
> ```C
> 	if (wc.status != IBV_WC_SUCCESS) {
> 		(void) fprintf(stderr,
> 			"%s failed: %s\n",
> ```

```
		(void) fprintf(stderr, "%s failed: %s\n",
```



_Code quote:_
```C
		(void) fprintf(stderr,
			"%s failed: %s\n",
```
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 29 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz66FF-yvQ17iW5Rma:-Muz66FF-yvQ17iW5Rmb:b4pmm18) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L29)):*
> ```C
> 			func_name, ibv_wc_status_str(wc.status));
> 		ret = -1;
> 		return ret;
> ```

```
		return -1;
```



_Code quote:_
```C
		ret = -1;
		return ret;
```
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 36 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz6CHsC8NZq328I6Qs:-Muz6CHsC8NZq328I6Qt:b8us0s5) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L36)):*
> ```C
> 			"unexpected wc.opcode value "
> 			"(0x%" PRIXPTR " != 0x%" PRIXPTR ")\n",
> 			(uintptr_t)wc.opcode,
> ```

Please make less lines.



_Code quote:_
```C
		(void) fprintf(stderr,
			"unexpected wc.opcode value "
			"(0x%" PRIXPTR " != 0x%" PRIXPTR ")\n",
			(uintptr_t)wc.opcode,
			(uintptr_t)opcode);
```
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 39 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz6AaD4g_Csy4_9S6A:-Muz6AaD4g_Csy4_9S6B:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L39)):*
> ```C
> 			(uintptr_t)opcode);
> 		ret = -1;
> 		return ret;
> ```

.



_Code quote:_
```C
		ret = -1;
		return ret;
```


<!-- Sent from Reviewable.io -->

2022-02-03 10:34 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 10 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 10:50 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 2 of 8 files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[examples/12-receive-completion-queue/client.c, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw77GeBCJI2WtXlJ8w:-MuzC97m7aPgZU0oMLwT:b2b0lym) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant that names of variables should reflect their purpose/meaning.
</blockquote></details>

cntr == counter
___
*[examples/12-receive-completion-queue/client.c, line 126 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz4eEn4CO0_vXAKAiC:-Muz98r_89np9fqVBYvs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/client.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`wc` is not needed as a parameter in this function
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/README.md, line 26 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw5bsL0aJaGnFDL4fn:-MuzCDPg6Lpg6ghGqFP0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/README.md#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I know :-) but a user does not - it should be explained here what it is for :-)
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.h, line 21 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz50Hr8zi5UkWx0VRM:-Muz9GLGEUVAyX0pdO97:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/receive-completion-queue-common.h#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not needed as a parameter - it can be defined inside the function.
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 14 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5ATcCD-b6RY4zOAI:-Muz9IWE8bcG_4o2S57i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/receive-completion-queue-common.c#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not needed as a parameter - it can be defined inside the function.
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 22 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5tBoCEW-l03R1ppv:-Muz9Ns-9IGCquuqn_we:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
	int ret;

	if ((ret = rpma_cq_wait(cq)))
			return ret;

	if ((ret = rpma_cq_get_wc(cq, 1, &wc, NULL)))
			return ret;
```
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 26 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz61Vp1bAEIVrvy05R:-Muz9TYiAwl4KnnB7spQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
		(void) fprintf(stderr, "%s failed: %s\n",
```
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 29 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz66FF-yvQ17iW5Rma:-Muz9_pgBW4xZNqgVCBa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
		return -1;
```
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 36 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz6CHsC8NZq328I6Qs:-Muz9p265kOHPIszooce:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please make less lines.
</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 39 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz6AaD4g_Csy4_9S6A:-Muz9qQB1xPjD3UMDtKB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 10:53 UTC, ldorau requested changes
> Reviewed 4 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/12-receive-completion-queue/client.c, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw77GeBCJI2WtXlJ8w:-MuzCUl2589j-Vc_i5xG:b9vaua8) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L51)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

cntr == counter
</blockquote></details>

Will a user know that? ;-)
Please replace `cntr` with `counter`.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 14 at r6](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5ATcCD-b6RY4zOAI:-MuzCuaj0F8SzJSZRYOC:bn9zzic) ([raw file](https://github.com/pmem/rpma/blob/62afeb07a2cb25e8df144ac5f400e6378d0a3057/examples/12-receive-completion-queue/receive-completion-queue-common.c#L14)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

inside the function, please


<!-- Sent from Reviewable.io -->

2022-02-03 10:54 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 22 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5tBoCEW-l03R1ppv:-MuzD7TdEksyWWfdLRoB:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L22)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.


<!-- Sent from Reviewable.io -->

2022-02-03 10:55 UTC, ldorau reviewed
> Reviewed 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 10:55 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 11:03 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/12-receive-completion-queue/client.c, line 51 at r4](https://reviewable.io/reviews/pmem/rpma/1528#-Muw77GeBCJI2WtXlJ8w:-MuzEJsa0gUAaP9TzW5o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/33c1c7c8217d98037ba65305083b834fb7a5051a/examples/12-receive-completion-queue/client.c#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Will a user know that? ;-)
Please replace `cntr` with `counter`.

</blockquote></details>

Done.
___
*[examples/12-receive-completion-queue/receive-completion-queue-common.c, line 22 at r7](https://reviewable.io/reviews/pmem/rpma/1528#-Muz5tBoCEW-l03R1ppv:-MuzE_pk02dECIJ9Otte:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/087787914a709689ef87f18dcca15e0cfba3138a/examples/12-receive-completion-queue/receive-completion-queue-common.c#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 11:08 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 11:08 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528#-:-MuzGSc_CWfuj1-9CaHp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 13:11 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528#-:-MuzhXqXET6KYQSjks-g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 07:49 UTC, Patryk717 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528#-:-Mv2hICC45aKBWmQz9jk:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 08:09 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1528)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 11:49 UTC, merged