rpma: Undocummented struct rpma_conn_cfg * defualt values
pmem/rpma pull request #1537
Opened 2022-02-03 08:48 UTC by Patryk717

Ref: #978

2022-02-03 08:50 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-02-03 09:05 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1537#-MuypC5W7ZFq4hPNE7Mb:-MuypC5X41lAkeepOIDE:b-aqseo3) (no related file):*
The CI builds failed, please check it locally before pushing it out

---


<!-- Sent from Reviewable.io -->

2022-02-03 11:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1537#-MuzKYW7BSCTAgCXL-h0):*
There has to be exactly one empty line  between commit's title and body.



_Code quote:_
```
- ce19957: rpma: Undocummented struct rpma_conn_cfg * defualt values
  Ref: #978
```
___
*[src/include/librpma.h, line 1212 at r1](https://reviewable.io/reviews/pmem/rpma/1537#-MuzKsRB5pppXvQniVIK:-MuzKsRB5pppXvQniVIL:b-ypnqr4) ([raw file](https://github.com/pmem/rpma/blob/ce199579111b31ec6eb770175a992e7fbbd0382d/src/include/librpma.h#L1212)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_new() creates a new connection configuration object.
>  * when no *cfg is provided the default is used instead: https://pmem.io/rpma/manpages/master/rpma_conn_req_new.3
> ```

What  does `*cfg` mean here?



_Code quote:_
```objc
*cfg
```
___
*[src/include/librpma.h, line 1213 at r1](https://reviewable.io/reviews/pmem/rpma/1537#-MuzKytFApJZbKqyXlgl:-MuzKytFApJZbKqyXlgm:bd22io6) ([raw file](https://github.com/pmem/rpma/blob/ce199579111b31ec6eb770175a992e7fbbd0382d/src/include/librpma.h#L1213)):*
> ```objc
>  * rpma_conn_cfg_new() creates a new connection configuration object.
>  * when no *cfg is provided the default is used instead: https://pmem.io/rpma/manpages/master/rpma_conn_req_new.3
>  * when struct rpma_conn_cfg * is not modified it has the default values: https://pmem.io/rpma/manpages/master/rpma_conn_cfg_new.3  
> ```

This comment does not make sense here - The cfg is created here, not modified.



_Code quote:_
```objc
 * when struct rpma_conn_cfg * is not modified it has the default values: https://pmem.io/rpma/manpages/master/rpma_conn_cfg_new.3···
```


<!-- Sent from Reviewable.io -->

2022-02-04 07:46 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1537#-MuzKYW7BSCTAgCXL-h0):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There has to be exactly one empty line  between commit's title and body.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1212 at r1](https://reviewable.io/reviews/pmem/rpma/1537#-MuzKsRB5pppXvQniVIK:-Mv2gO2l5YAYSAWER4d3:bc9mzc3) ([raw file](https://github.com/pmem/rpma/blob/ce199579111b31ec6eb770175a992e7fbbd0382d/src/include/librpma.h#L1212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What  does `*cfg` mean here?
</blockquote></details>

this is my mistake
___
*[src/include/librpma.h, line 1213 at r1](https://reviewable.io/reviews/pmem/rpma/1537#-MuzKytFApJZbKqyXlgl:-Mv2gRUk4RCSlMbT5vrC:b2y89t2) ([raw file](https://github.com/pmem/rpma/blob/ce199579111b31ec6eb770175a992e7fbbd0382d/src/include/librpma.h#L1213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This comment does not make sense here - The cfg is created here, not modified.
</blockquote></details>

sure this is my mistake


<!-- Sent from Reviewable.io -->

2022-02-04 07:47 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1537#-MuypC5W7ZFq4hPNE7Mb:-Mv2gt3k3zZn5jfqU7Bn:b1f1yhc) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The CI builds failed, please check it locally before pushing it out
</blockquote></details>

The CI builds now work

---


<!-- Sent from Reviewable.io -->

2022-02-04 11:43 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 6 unresolved discussions (waiting on @Patryk717)

___
*[src/include/librpma.h, line 1211 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3WLS3C6nhMjMHXTyb:-Mv3WLS3C6nhMjMHXTyc:b-o5i0oh) ([raw file](https://github.com/pmem/rpma/blob/589ad2182a967cb8e4b3dc2c034106a33e4d6418/src/include/librpma.h#L1211)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_cfg_new() creates a new connection configuration object.
> ```

`rpma_conn_cfg_new() creates a new connection configuration object and fills it with the default values: ...` - please list the default values here.



_Code quote:_
```objc
rpma_conn_cfg_new() creates a new connection configuration object.
```
___
*[src/include/librpma.h, line 1275 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3XWVzC4xRlkonicDP:-Mv3XWVzC4xRlkonicDQ:b71gdwj) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1275)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_timeout() sets the connection establishment timeout.
>  * If timeout is not specified, it defaults to 1000.
> ```

`It this function is not called, the timeout has the default value (1000) set by rpma_conn_cfg_new(3).`



_Code quote:_
```objc
If timeout is not specified, it defaults to 1000.
```
___
*[src/include/librpma.h, line 1335 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Xy3B775zTT8Qt4-A:-Mv3Xy3B775zTT8Qt4-B:bo8jln5) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1335)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_cq_size() sets the CQ size for the connection.
>  * If cq_size not specified, it defaults to 10.
> ```

.
(change as above)



_Code quote:_
```objc
If cq_size not specified, it defaults to 10.
```
___
*[src/include/librpma.h, line 1397 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Y0L--mTEhH7oTIgX:-Mv3Y0L--mTEhH7oTIgY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1397)):*
> ```objc
>  * rpma_conn_cfg_set_rcq_size() sets the receive CQ size for the connection.
>  * Please see the rpma_conn_get_rcq() for details about the receive CQ.
>  * If rcq_size not specified, it defaults to 0.
> ```

.
___
*[src/include/librpma.h, line 1459 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Y10A28LaxrvxsUgx:-Mv3Y10BAdJQJj290yxf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1459)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_sq_size() sets the SQ size for the connection.
>  * If sq_size not specified, it defaults to 10.
> ```

.
___
*[src/include/librpma.h, line 1520 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Y1VkDzTM8V2Jg2V3:-Mv3Y1VkDzTM8V2Jg2V4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1520)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_rq_size() sets the RQ size for the connection.
>  * If rq_size not specified, it defaults to 10.
> ```

.


<!-- Sent from Reviewable.io -->

2022-02-04 12:37 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1211 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3WLS3C6nhMjMHXTyb:-Mv3hEHlE6LFhwKs3ZeQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/589ad2182a967cb8e4b3dc2c034106a33e4d6418/src/include/librpma.h#L1211)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_cfg_new() creates a new connection configuration object and fills it with the default values: ...` - please list the default values here.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1275 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3XWVzC4xRlkonicDP:-Mv3hUb628RQoSdWyXPi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1275)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`It this function is not called, the timeout has the default value (1000) set by rpma_conn_cfg_new(3).`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1335 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Xy3B775zTT8Qt4-A:-Mv3hWhi1EHzba0CnEuE:bb7f2mf) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1335)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
(change as above)
</blockquote></details>

done
___
*[src/include/librpma.h, line 1397 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Y0L--mTEhH7oTIgX:-Mv3iyXzEZP2ifpJKlL4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1397)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1459 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Y10A28LaxrvxsUgx:-Mv3j-y_215rtkyT06Uw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1459)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1520 at r2](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3Y1VkDzTM8V2Jg2V3:-Mv3j5SV-3FoUMep1wyw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91b1be67f6194b946482f4c383dcf0dd2a50debf/src/include/librpma.h#L1520)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 13:21 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 6 unresolved discussions (waiting on @Patryk717)

___
*[src/include/librpma.h, line 1280 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3riRcA1rAHjGddF7L:-Mv3riRcA1rAHjGddF7M:buervio) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1280)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_timeout() sets the connection establishment timeout.
>  * It this function is not called, the timeout has the default value (1000) set by rpma_conn_cfg_new(3).
> ```

If ...



_Code quote:_
```objc
It 
```
___
*[src/include/librpma.h, line 1340 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rme367ieBNBX16Y6:-Mv3rme367ieBNBX16Y7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1340)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_cq_size() sets the CQ size for the connection.
>  * It this function is not called, the cq_size has the default value (10) set by rpma_conn_cfg_new(3).
> ```

.
___
*[src/include/librpma.h, line 1402 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rozMDDtQYJjxuywp:-Mv3rozMDDtQYJjxuywq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1402)):*
> ```objc
>  * rpma_conn_cfg_set_rcq_size() sets the receive CQ size for the connection.
>  * Please see the rpma_conn_get_rcq() for details about the receive CQ.
>  * It this function is not called, the rcq_size has the default value (0) set by rpma_conn_cfg_new(3).
> ```

.
___
*[src/include/librpma.h, line 1464 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rsPpBPJd2JqF0Ccw:-Mv3rsPpBPJd2JqF0Ccx:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1464)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_sq_size() sets the SQ size for the connection.
>  * It this function is not called, the sq_size has the default value (10) set by rpma_conn_cfg_new(3).
> ```

.
___
*[src/include/librpma.h, line 1525 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rvzj-ZNyET4zHT39:-Mv3rvzj-ZNyET4zHT3A:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1525)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_rq_size() sets the RQ size for the connection.
>  * It this function is not called, the rq_size has the default value (10) set by rpma_conn_cfg_new(3).
> ```

.
___
*[src/include/librpma.h, line 1955 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3sKL22BCmAzrhjLGq:-Mv3sKL22BCmAzrhjLGr:blfiiqb) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1955)):*
> ```objc
>  * The rpma_conn_req_new() function returns 0 on success or a negative
>  * error code on failure. rpma_conn_req_new() does not set
>  * if cfg is not given it has default values
> ```

1) Do not insert a new sentence in the middle of another one.
2) Please change it to:
```
If cfg is NULL, then the default values are used - see rpma_conn_cfg_new(3) for more details.
```



_Code quote:_
```objc
if cfg is not given it has default values
```


<!-- Sent from Reviewable.io -->

2022-02-04 13:34 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1280 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3riRcA1rAHjGddF7L:-Mv3wFr12y58NEAIb0EV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1280)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

If ...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1340 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rme367ieBNBX16Y6:-Mv3wFHP-84OgqlRXYZT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1340)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1402 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rozMDDtQYJjxuywp:-Mv3wEmN6cHQJoyz-hPe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1402)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1464 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rsPpBPJd2JqF0Ccw:-Mv3wEJ6E4wQi-pmCmU_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1464)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1525 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3rvzj-ZNyET4zHT39:-Mv3wDq4EqFJWFTkOhmL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1525)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1955 at r3](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3sKL22BCmAzrhjLGq:-Mv3wDOoBC7ZpzD2XwOl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c4d46d68cb8fab91c314bc10e0cf512da7ef62/src/include/librpma.h#L1955)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) Do not insert a new sentence in the middle of another one.
2) Please change it to:
```
If cfg is NULL, then the default values are used - see rpma_conn_cfg_new(3) for more details.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 13:36 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[src/include/librpma.h, line 1212 at r4](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3w6zJ8LL9GJs3HbNU:-Mv3w6zJ8LL9GJs3HbNV:b-bq8xyd) ([raw file](https://github.com/pmem/rpma/blob/cf06bcacf7f37c3bb167852b620a45cebb4c7d42/src/include/librpma.h#L1212)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_new() creates a new connection configuration
>  * object and fills it with the default values:
> ```

Please move `object` to the previous line as it was before.



_Code quote:_
```objc
object
```


<!-- Sent from Reviewable.io -->

2022-02-04 13:45 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 1212 at r4](https://reviewable.io/reviews/pmem/rpma/1537#-Mv3w6zJ8LL9GJs3HbNU:-Mv3yuuRCEvk5wn0GoLw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf06bcacf7f37c3bb167852b620a45cebb4c7d42/src/include/librpma.h#L1212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move `object` to the previous line as it was before.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 13:51 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-04 14:09 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/pmem/rpma/1537#-Mv4-Wz93Vmk2t1mRSE9):*
```
rpma: document default values of struct rpma_conn_cfg

Ref: #978 
```



_Code quote:_
```
rpma: Undocummented struct rpma_conn_cfg * defualt values
```


<!-- Sent from Reviewable.io -->

2022-02-04 14:26 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/pmem/rpma/1537#-Mv4-Wz93Vmk2t1mRSE9):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
rpma: document default values of struct rpma_conn_cfg

Ref: #978 
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 14:34 UTC, ldorau approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-07 12:38 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-07 12:39 UTC, grom72 requested changes
:goat:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537#-:-MvJBTng8mhmSQUhb35U:bnd2vnu)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1537#-MvJBQ-l7dXtmyi_eKyr:-MvJBQ-l7dXtmyi_eKys:bb2rzra) (no related file):*
Shall we add this to CHANGELOG?

---


<!-- Sent from Reviewable.io -->

2022-02-07 13:05 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

___
*[src/include/librpma.h, line 1213 at r7](https://reviewable.io/reviews/pmem/rpma/1537#-MvJH3d33UL9qCle8byc:-MvJH3d33UL9qCle8byd:b-bpkmwc) ([raw file](https://github.com/pmem/rpma/blob/de617041621f95d0176d0954f949a81c40ad4b1c/src/include/librpma.h#L1213)):*
> ```objc
>  * rpma_conn_cfg_new() creates a new connection configuration object
>  * and fills it with the default values:
>  * .timeout_ms = 1000
> ```

 - timeout_ms = 1000
...


<!-- Sent from Reviewable.io -->

2022-02-07 13:25 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-07 13:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[src/include/librpma.h, line 1213 at r7](https://reviewable.io/reviews/pmem/rpma/1537#-MvJH3d33UL9qCle8byc:-MvJQopgBAIB9_KPhego:b-6py4k) ([raw file](https://github.com/pmem/rpma/blob/de617041621f95d0176d0954f949a81c40ad4b1c/src/include/librpma.h#L1213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk What do you mean?
</blockquote></details>

Something like this?
```
 * - .timeout_ms = 1000
 * - .cq_size = 10
 * - .rcq_size = 0
 * - .sq_size = 10
 * - .rq_size = 10
```



_Code quote:_
```objc
 * .timeout_ms = 1000
 * .cq_size = 10
 * .rcq_size = 0
 * .sq_size = 10
 * .rq_size = 10
```


<!-- Sent from Reviewable.io -->

2022-02-07 13:52 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[src/include/librpma.h, line 1213 at r7](https://reviewable.io/reviews/pmem/rpma/1537#-MvJH3d33UL9qCle8byc:-MvJS3hABqi50x4mG2lt:b-tuik1l) ([raw file](https://github.com/pmem/rpma/blob/de617041621f95d0176d0954f949a81c40ad4b1c/src/include/librpma.h#L1213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Something like this?
```
 * - .timeout_ms = 1000
 * - .cq_size = 10
 * - .rcq_size = 0
 * - .sq_size = 10
 * - .rq_size = 10
```
</blockquote></details>

Exactly


<!-- Sent from Reviewable.io -->

2022-02-07 13:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[src/include/librpma.h, line 1213 at r7](https://reviewable.io/reviews/pmem/rpma/1537#-MvJH3d33UL9qCle8byc:-MvJS_Me6YKoAOf2E0kM:b32wtd) ([raw file](https://github.com/pmem/rpma/blob/de617041621f95d0176d0954f949a81c40ad4b1c/src/include/librpma.h#L1213)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Exactly
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2022-02-07 13:56 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-07 14:01 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1537#-MvJBQ-l7dXtmyi_eKyr:-MvJUEUc6zEOsoPePVYX:bh857ma) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, @patryk717 please add the following line:
```
- Documented default values of struct rpma_conn_cfg.
```
after the line:
```
- Example (#12) for separate receive completion queue (RCQ).
```

so it should look like:
```
...
## [Unreleased]
### Added
- Example (#12) for separate receive completion queue (RCQ).
- Documented default values of struct rpma_conn_cfg.

- APIs:
  - rpma_cq_get_wc - receive one or more completions

...
```

</blockquote></details>

`- Documented` **the** `default values of struct rpma_conn_cfg.`

---


<!-- Sent from Reviewable.io -->

2022-02-07 14:11 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-07 14:49 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1537#-MvJBQ-l7dXtmyi_eKyr:-MvJdrA40I6Yu9iazAA_:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`- Documented` **the** `default values of struct rpma_conn_cfg.`
</blockquote></details>

Done.

---
___
*[src/include/librpma.h, line 1213 at r7](https://reviewable.io/reviews/pmem/rpma/1537#-MvJH3d33UL9qCle8byc:-MvJeDuQ0s15a12KVdvd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/de617041621f95d0176d0954f949a81c40ad4b1c/src/include/librpma.h#L1213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 14:51 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 14:52 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537#-:-MvJf1F36vw6c1kLLidx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 14:52 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 14:54 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1537#-:-MvJfYsdB8N-uQ2uDRgl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-02-07 14:55 UTC, merged