examples: delete completion_get() appearing before completion_wait()
pmem/rpma pull request #1540
Opened 2022-02-03 13:00 UTC by osalyk

2022-02-03 13:09 UTC, ldorau requested changes
> Reviewed 6 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-MuzgGIs8b9J0rO-ZYKK:-MuzgGIt4fVY4i3csdO4:bhj9ho9) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L5)):*
> ```C
> 
> /*
>  * messages-ping-pong-common.c -- a common declarations for the 08 example
> ```

definitions, code or functions ?
Declarations are in headers.



_Code quote:_
```C
declarations
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-MuzgghJ9SGrZI0-oaBz:-MuzgghJ9SGrZI0-oaC-:b-fhlo7o) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L20)):*
> ```C
> 	int ret;
> 
> 	/* prepare completions, get one and validate it */
> ```

outdated comment



_Code quote:_
```C
/* prepare completions, get one and validate it */
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-Muzgk4T6Y-zOhhLnRV6:-Muzgk4T6Y-zOhhLnRV7:b-magnj1) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L23)):*
> ```C
> 	if ((ret = rpma_cq_wait(cq)))
> 		return ret;
> 	if ((ret = rpma_cq_get_wc(cq, 1, &wc, NULL)))
> ```

one empty line in between please



_Code quote:_
```C
		return ret;
	if ((ret = rpma_cq_get_wc(cq, 1, &wc, NULL)))
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-Muzgwky-2FRhDc9VmA3:-Muzgwky-2FRhDc9VmA4:btmg0dx) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L42)):*
> ```C
> 				PRIXPTR " != 0x%" PRIXPTR
> 				" [wc.wr_id] || %" PRIu32
> 				" != %ld [wc.byte_len])\n",
> ```

Could you try to use less and longer lines here, please?



_Code quote:_
```C
		if (wc.wr_id != (uintptr_t)recv ||
				wc.byte_len != MSG_SIZE) {
			(void) fprintf(stderr,
				"received completion is not as expected (0x%"
				PRIXPTR " != 0x%" PRIXPTR
				" [wc.wr_id] || %" PRIu32
				" != %ld [wc.byte_len])\n",
				wc.wr_id, (uintptr_t)recv,
				wc.byte_len, MSG_SIZE);
```


<!-- Sent from Reviewable.io -->

2022-02-03 13:13 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1540#-MuzhoEtAP3aJkPVZUrp):*
rpma_cq_get_wc()



_Code quote:_
```
completion_get
```
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1540#-MuzhqymCXD8Vs2nXSgZ):*
rpma_cq_wait()



_Code quote:_
```
completion_wait
```


<!-- Sent from Reviewable.io -->

2022-02-03 13:23 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1540#-MuzhoEtAP3aJkPVZUrp):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma_cq_get_wc()
</blockquote></details>

Done.
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1540#-MuzhqymCXD8Vs2nXSgZ):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma_cq_wait()
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-MuzgGIs8b9J0rO-ZYKK:-Muzi-pe-Q10paUXF1Mo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

definitions, code or functions ?
Declarations are in headers.
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-MuzgghJ9SGrZI0-oaBz:-MuziBPY6ocdDcq2IiMe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

outdated comment
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-Muzgk4T6Y-zOhhLnRV6:-MuziDPn0rcne7_FX-ke:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one empty line in between please
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1540#-Muzgwky-2FRhDc9VmA3:-Muzj5Lu6cNKQWb3-IXB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f0dbae1220b25987bd12908d108dc6e12fe04710/examples/08-messages-ping-pong/messages-ping-pong-common.c#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you try to use less and longer lines here, please?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 13:23 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 13:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1540#-MuzhqymCXD8Vs2nXSgZ):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

rpma_cq_wait (not rpma_cq__wait)


<!-- Sent from Reviewable.io -->

2022-02-03 13:27 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1540#-MuzhqymCXD8Vs2nXSgZ):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma_cq_wait (not rpma_cq__wait)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 13:29 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[-- commits, line 2 at r5](https://reviewable.io/reviews/pmem/rpma/1540#-Muzlb9sAqykP15rpvWh):*
Could you add:
Ref: #1541 
here?



_Code quote:_
```
examples: delete rpma_cq_get_wc() appearing before rpma_cq_wait()
```


<!-- Sent from Reviewable.io -->

2022-02-03 13:33 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r5](https://reviewable.io/reviews/pmem/rpma/1540#-Muzlb9sAqykP15rpvWh):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you add:
Ref: #1541 
here?

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 13:36 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540#-:-Muzn7xB5ue0QflBfa3t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-03 14:38 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/client.c, line 125 at r7](https://reviewable.io/reviews/pmem/rpma/1540#-Mv--zrb4gyM-8uDt6Dd:-Mv--zrb4gyM-8uDt6De:b-5lnddh) ([raw file](https://github.com/pmem/rpma/blob/a7d7ed90a327693d789dbf89cb5e2701e4801500/examples/08-messages-ping-pong/client.c#L125)):*
> ```C
> 				&recv_cmpl);
> 			if (ret)
> 				goto err_conn_disconnect;
> ```

The previous `if` should stay, but only `|| !ret);` should be added:
```
		} while (!send_cmpl || !recv_cmpl || !ret);

		if (ret)
			break;
```



_Code quote:_
```C
			if (ret)
				goto err_conn_disconnect;
		} while (!send_cmpl || !recv_cmpl);
```
___
*[examples/08-messages-ping-pong/server.c, line 119 at r7](https://reviewable.io/reviews/pmem/rpma/1540#-Mv-0IiU4eAOddoY7d2h:-Mv-0IiU4eAOddoY7d2i:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a7d7ed90a327693d789dbf89cb5e2701e4801500/examples/08-messages-ping-pong/server.c#L119)):*
> ```C
> 			ret = get_wc_and_validate(cq, recv, &send_cmpl,
> 				&recv_cmpl);
> 			if (ret)
> ```

.



_Code quote:_
```C
			if (ret)
				goto err_conn_disconnect;
		} while (!send_cmpl || !recv_cmpl);
```


<!-- Sent from Reviewable.io -->

2022-02-03 14:53 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/08-messages-ping-pong/client.c, line 125 at r7](https://reviewable.io/reviews/pmem/rpma/1540#-Mv--zrb4gyM-8uDt6Dd:-Mv-3efaE1v-X53yNA3a:b-qxuh7u) ([raw file](https://github.com/pmem/rpma/blob/a7d7ed90a327693d789dbf89cb5e2701e4801500/examples/08-messages-ping-pong/client.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The previous `if` should stay, but only `|| !ret);` should be added:
```
		} while (!send_cmpl || !recv_cmpl || !ret);

		if (ret)
			break;
```
</blockquote></details>

Sorry, the correct one is:
```
} while (!ret && (!send_cmpl || !recv_cmpl));
```
___
*[examples/08-messages-ping-pong/server.c, line 119 at r7](https://reviewable.io/reviews/pmem/rpma/1540#-Mv-0IiU4eAOddoY7d2h:-Mv-3kbp7KiJt3Mc3elO:b-qxuh7u) ([raw file](https://github.com/pmem/rpma/blob/a7d7ed90a327693d789dbf89cb5e2701e4801500/examples/08-messages-ping-pong/server.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Sorry, the correct one is:
```
} while (!ret && (!send_cmpl || !recv_cmpl));
```


<!-- Sent from Reviewable.io -->

2022-02-03 16:10 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/client.c, line 125 at r7](https://reviewable.io/reviews/pmem/rpma/1540#-Mv--zrb4gyM-8uDt6Dd:-Mv-LEXP3wuFJXh0Dk7z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a7d7ed90a327693d789dbf89cb5e2701e4801500/examples/08-messages-ping-pong/client.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Sorry, the correct one is:
```
} while (!ret && (!send_cmpl || !recv_cmpl));
```
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/server.c, line 119 at r7](https://reviewable.io/reviews/pmem/rpma/1540#-Mv-0IiU4eAOddoY7d2h:-Mv-LFNG2wLRyr6JUcje:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a7d7ed90a327693d789dbf89cb5e2701e4801500/examples/08-messages-ping-pong/server.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Sorry, the correct one is:
```
} while (!ret && (!send_cmpl || !recv_cmpl));
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 08:08 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 08:50 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.h, line 19 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2rYxwA575LCvDz5K7:-Mv2rYxxBgw51WlaXGxg:bm7xggv) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.h#L19)):*
> ```objc
> #define I_M_DONE	(uint64_t)UINT64_MAX
> 
> /* Number of entries expected (send, recv) */
> ```

/* the maximum number of completions expected (1 of send + 1 of receive) */

`MAX_WC` or `MAX_N_WC` ?



_Code quote:_
```objc
Number of entries expected (send, recv)
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.h, line 20 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2rzUD53VRso742uZx:-Mv2rzUD53VRso742uZy:b-smkzet) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.h#L20)):*
> ```objc
> 
> /* Number of entries expected (send, recv) */
> #define NUM_ENTRIES	2
> ```

It should be defined in *.c because it is used only there.



_Code quote:_
```objc
#define NUM_ENTRIES	2
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.h, line 20 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2staV4FSnl-d52ZDW:-Mv2staV4FSnl-d52ZDX:b-506dcu) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.h#L20)):*
> ```objc
> 
> /* Number of entries expected (send, recv) */
> #define NUM_ENTRIES	2
> ```

`MAX_WC` or `MAX_N_WC` ?



_Code quote:_
```objc
NUM_ENTRIES
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 38 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2sMOAE2g6Ea4s0coy:-Mv2sMOAE2g6Ea4s0coz:b-wepcpp) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L38)):*
> ```C
> 		*recv_cmpl = 1;
> 	}
> 	return 0;
> ```

add one empty line, please



_Code quote:_
```C
	}
	return 0;
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 53 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2sbXX2FBDAD6kTVTa:-Mv2sbXX2FBDAD6kTVTb:b-7f05fw) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L53)):*
> ```C
> 		return ret;
> 
> 	/* get two next completion (send, recv) */
> ```

... completion**s** at most (1 of send + 1 of recv)



_Code quote:_
```C
completion (send, recv)
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 55 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2v4lY6Inw1S-_Gwns:-Mv2v4lY6Inw1S-_Gwnt:b332zi) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L55)):*
> ```C
> 	/* get two next completion (send, recv) */
> 	if ((ret = rpma_cq_get_wc(cq, NUM_ENTRIES, wc, &num_entries_got))) {
> 		if (ret == RPMA_E_NO_COMPLETION)
> ```

```
/* lack of completions is not an error here */
```



_Code quote:_
```C
if (ret == RPMA_E_NO_COMPLETION)
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 62 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2vIA56WQuFeO2Ls89:-Mv2vIA56WQuFeO2Ls8A:bdptjph) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L62)):*
> ```C
> 	/* validate received completions */
> 	for (int i = 0; i < num_entries_got; i++) {
> 		ret = verify_wc(&wc[i], recv, send_cmpl, recv_cmpl);
> ```

`{ }` are not needed here



_Code quote:_
```C
	for (int i = 0; i < num_entries_got; i++) {


		ret = verify_wc(&wc[i], recv, send_cmpl, recv_cmpl);
	}
```


<!-- Sent from Reviewable.io -->

2022-02-04 08:58 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: 4 of 6 files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.h, line 19 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2rYxwA575LCvDz5K7:-Mv2w-uh6szwB2YKrH_Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.h#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

/* the maximum number of completions expected (1 of send + 1 of receive) */

`MAX_WC` or `MAX_N_WC` ?
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.h, line 20 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2rzUD53VRso742uZx:-Mv2w70MDl9FT_et_ZlF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.h#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be defined in *.c because it is used only there.
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.h, line 20 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2staV4FSnl-d52ZDW:-Mv2w8dc8gPXVlufe2GA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.h#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`MAX_WC` or `MAX_N_WC` ?
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 38 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2sMOAE2g6Ea4s0coy:-Mv2wGnz1IQQ5CqLSqws:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

add one empty line, please
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 53 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2sbXX2FBDAD6kTVTa:-Mv2wSBiBoZkgUcBiNOk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... completion**s** at most (1 of send + 1 of recv)
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 55 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2v4lY6Inw1S-_Gwns:-Mv2wYf52NtpRiGf2b2w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
/* lack of completions is not an error here */
```
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 62 at r10](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2vIA56WQuFeO2Ls89:-Mv2wbx-2loPNmwNOUkL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b109e19bed145613fbd7dbae711bc69a0c7d11/examples/08-messages-ping-pong/messages-ping-pong-common.c#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`{ }` are not needed here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 09:04 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 09:07 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 17 at r11](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2ynKq-VQeKaB0yC1N:-Mv2ynKr6y0_sDnMyVAP:b-o6tll4) ([raw file](https://github.com/pmem/rpma/blob/a37a13039897830b6fc86e90415312e1a0bfd852/examples/08-messages-ping-pong/messages-ping-pong-common.c#L17)):*
> ```C
> 
> static int
> verify_wc(struct ibv_wc *wc, uint64_t *recv,
> ```

The better name would be `validate_wc`, because the outer function is `get_wc_and_validate`.



_Code quote:_
```C
verify_wc
```


<!-- Sent from Reviewable.io -->

2022-02-04 09:09 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 17 at r11](https://reviewable.io/reviews/pmem/rpma/1540#-Mv2ynKq-VQeKaB0yC1N:-Mv2zcuFAUjZ3gxfRfLN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a37a13039897830b6fc86e90415312e1a0bfd852/examples/08-messages-ping-pong/messages-ping-pong-common.c#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The better name would be `validate_wc`, because the outer function is `get_wc_and_validate`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 09:21 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540#-:-Mv31QqBBOstjcKqz_S9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 11:27 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 50 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TY4922oO5NV8__nN:-Mv3TY4922oO5NV8__nO:b-u1efqi) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L50)):*
> ```C
> {
> 	struct ibv_wc wc[MAX_N_WC];
> 	int num_entries_got;
> ```

`num_got` - lines will not have to be broken



_Code quote:_
```C
num_entries_got
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 56 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TfW64-06YxcBv9yj:-Mv3TfW64-06YxcBv9yk:bpspk79) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L56)):*
> ```C
> 		/* wait for the completion to be ready */
> 		if ((ret = rpma_cq_wait(cq)))
> 			break;
> ```

return ret;



_Code quote:_
```C
break;
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 60 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TpHHE5IAA8E692Ju:-Mv3TpHHE5IAA8E692Jv:byw38vj) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L60)):*
> ```C
> 		/* get two next completions at most (1 of send + 1 of recv) */
> 		if ((ret = rpma_cq_get_wc(cq, MAX_N_WC, wc,
> 				&num_entries_got))) {
> ```

in one line with `num_got`



_Code quote:_
```C
		if ((ret = rpma_cq_get_wc(cq, MAX_N_WC, wc,
				&num_entries_got))) {
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 64 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TvVf3EcZyBBMHHoO:-Mv3TvVf3EcZyBBMHHoP:b-p0vqfx) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L64)):*
> ```C
> 			if (ret == RPMA_E_NO_COMPLETION)
> 				ret = 0;
> 			break;
> ```

```
			if (ret == RPMA_E_NO_COMPLETION)
				continue;
			return ret;
```



_Code quote:_
```C
			if (ret == RPMA_E_NO_COMPLETION)
				ret = 0;
			break;
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 70 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3U8mf0mwnTNu0UorZ:-Mv3U8mf0mwnTNu0Uor_:b6vzhdp) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L70)):*
> ```C
> 		for (int i = 0; i < num_entries_got; i++) {
> 			if ((ret = validate_wc(&wc[i], recv, send_cmpl,
> 					recv_cmpl)))
> ```

Not broken lines
```
			ret = validate_wc(&wc[i], recv, send_cmpl, recv_cmpl);
			if (ret)
				return ret;
```



_Code quote:_
```C
			if ((ret = validate_wc(&wc[i], recv, send_cmpl,
					recv_cmpl)))
				break;
```
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 75 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3UGXo90Q0-Bph5xrv:-Mv3UGXo90Q0-Bph5xrw:b10h7oz) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L75)):*
> ```C
> 	} while (ret == 0 && (*send_cmpl == 0 || *recv_cmpl == 0));
> 
> 	return ret;
> ```

Simpler condition:

```
	} while (*send_cmpl == 0 || *recv_cmpl == 0);

	return 0;
```



_Code quote:_
```C
	} while (ret == 0 && (*send_cmpl == 0 || *recv_cmpl == 0));

	return ret;
```


<!-- Sent from Reviewable.io -->

2022-02-04 11:28 UTC, ldorau requested changes
> Reviewed 2 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-04 11:33 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 50 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TY4922oO5NV8__nN:-Mv3UmaNEQZQUnE7eM09:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`num_got` - lines will not have to be broken
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 56 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TfW64-06YxcBv9yj:-Mv3Us1d1DRUgAUgyQgE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

return ret;
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 60 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TpHHE5IAA8E692Ju:-Mv3Ut1o-XqneLlY8FGc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

in one line with `num_got`
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 64 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3TvVf3EcZyBBMHHoO:-Mv3V1GZ2A8hOoM9uUAw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
			if (ret == RPMA_E_NO_COMPLETION)
				continue;
			return ret;
```
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 70 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3U8mf0mwnTNu0UorZ:-Mv3VFeB6zixDAqKdAlR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L70)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not broken lines
```
			ret = validate_wc(&wc[i], recv, send_cmpl, recv_cmpl);
			if (ret)
				return ret;
```
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 75 at r13](https://reviewable.io/reviews/pmem/rpma/1540#-Mv3UGXo90Q0-Bph5xrv:-Mv3VWFM-V3V7Oaz8i6P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/067739cf353d4cb2def2a68a2e38759f8a0dc894/examples/08-messages-ping-pong/messages-ping-pong-common.c#L75)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Simpler condition:

```
	} while (*send_cmpl == 0 || *recv_cmpl == 0);

	return 0;
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-04 11:45 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 10:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 62 at r14](https://reviewable.io/reviews/pmem/rpma/1540#-MvIkHzYBGri3WUT58yY:-MvIkHzYBGri3WUT58yZ:b-h6urwi) ([raw file](https://github.com/pmem/rpma/blob/64bc1a204e3ef564df6862ff2aa9da7c81e92111/examples/08-messages-ping-pong/messages-ping-pong-common.c#L62)):*
> ```C
> 			/* lack of completions is not an error here */
> 			if (ret == RPMA_E_NO_COMPLETION)
> 				continue;
> ```

```
		/* get two next completions at most (1 of send + 1 of recv) */
		ret = rpma_cq_get_wc(cq, MAX_N_WC, wc, &num_got);
		/* lack of completions is not an error here */
		if (ret && ret != RPMA_E_NO_COMPLETION)
			return ret;
```



_Code quote:_
```C
		/* get two next completions at most (1 of send + 1 of recv) */
		if ((ret = rpma_cq_get_wc(cq, MAX_N_WC, wc, &num_got))) {
			/* lack of completions is not an error here */
			if (ret == RPMA_E_NO_COMPLETION)
				continue;
			return ret;
		}
```


<!-- Sent from Reviewable.io -->

2022-02-07 11:07 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 62 at r14](https://reviewable.io/reviews/pmem/rpma/1540#-MvIkHzYBGri3WUT58yY:-MvIrOQ984EwpqUvQ_RU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64bc1a204e3ef564df6862ff2aa9da7c81e92111/examples/08-messages-ping-pong/messages-ping-pong-common.c#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
		/* get two next completions at most (1 of send + 1 of recv) */
		ret = rpma_cq_get_wc(cq, MAX_N_WC, wc, &num_got);
		/* lack of completions is not an error here */
		if (ret && ret != RPMA_E_NO_COMPLETION)
			return ret;
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 11:08 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:19 UTC, grom72 requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 17 at r15](https://reviewable.io/reviews/pmem/rpma/1540#-MvItSCu7zlurXqc5se4:-MvItSCu7zlurXqc5se5:btowy4o) ([raw file](https://github.com/pmem/rpma/blob/fa5a2422e0f0e0f76f68beafa8ff5ae3e477eba8/examples/08-messages-ping-pong/messages-ping-pong-common.c#L17)):*
> ```C
> 
> static int
> validate_wc(struct ibv_wc *wc, uint64_t *recv,
> ```

I do not see any value from a separate function with 4 (four) parameters.
This code could be placed directly into the main loop of  ```get_wc_and_validate```



_Code quote:_
```C
validate_wc
```


<!-- Sent from Reviewable.io -->

2022-02-07 11:20 UTC, grom72 requested changes
> Reviewed 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 46 at r15](https://reviewable.io/reviews/pmem/rpma/1540#-MvIuCXl-DHnOGM4LpC6:-MvIuCXl-DHnOGM4LpC7:b-5syxrk) ([raw file](https://github.com/pmem/rpma/blob/fa5a2422e0f0e0f76f68beafa8ff5ae3e477eba8/examples/08-messages-ping-pong/messages-ping-pong-common.c#L46)):*
> ```C
> 
> int
> get_wc_and_validate(struct rpma_cq *cq, uint64_t *recv,
> ```

```wait_and_process_completions```



_Code quote:_
```C
get_wc_and_validate
```


<!-- Sent from Reviewable.io -->

2022-02-07 11:23 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r13, 1 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:29 UTC, grom72 reviewed
:goat:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540#-:-MvIwUPK-q3C69v_AjVW:bdycps0)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:31 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 17 at r15](https://reviewable.io/reviews/pmem/rpma/1540#-MvItSCu7zlurXqc5se4:-MvIw8OsBMsajP0gz3Cr:bk3y519) ([raw file](https://github.com/pmem/rpma/blob/fa5a2422e0f0e0f76f68beafa8ff5ae3e477eba8/examples/08-messages-ping-pong/messages-ping-pong-common.c#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I do not see any value from a separate function with 4 (four) parameters.
This code could be placed directly into the main loop of  ```get_wc_and_validate```

</blockquote></details>

The values are following: 
1) there is less nested code,
2) lines can be broken less times,
3) the code is more clear and simpler.

Try to inline it and you will see how many times this line will be broken more:
```
			(void) fprintf(stderr,
				"received completion is not as expected (0x%"
				PRIXPTR " != 0x%" PRIXPTR " [wc.wr_id] || %"
				PRIu32 " != %ld [wc.byte_len])\n", wc->wr_id,
				(uintptr_t)recv, wc->byte_len, MSG_SIZE);
```
It is broken 4 times already.

I am for the current version with two separate functions.


<!-- Sent from Reviewable.io -->

2022-02-07 11:33 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 46 at r15](https://reviewable.io/reviews/pmem/rpma/1540#-MvIuCXl-DHnOGM4LpC6:-MvIxH179EKCKSOnZKBR:b32v57) ([raw file](https://github.com/pmem/rpma/blob/fa5a2422e0f0e0f76f68beafa8ff5ae3e477eba8/examples/08-messages-ping-pong/messages-ping-pong-common.c#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```wait_and_process_completions```
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-02-07 11:41 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540#-:-MvIzLar8PfL2IVxdY2s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:42 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/08-messages-ping-pong/client.c, line 120 at r16](https://reviewable.io/reviews/pmem/rpma/1540#-MvIz8sf9NLhv-lsNeey:-MvIz8sf9NLhv-lsNeez:b-i7f1ki) ([raw file](https://github.com/pmem/rpma/blob/b9078da8dc6f660ab94e86bb97cd6ea56eb05bdd/examples/08-messages-ping-pong/client.c#L120)):*
> ```C
> 		int recv_cmpl = 0;
> 
> 		/* get completion and process it */
> ```

get completions and process them



_Code quote:_
```C
get completion and process it
```
___
*[examples/08-messages-ping-pong/server.c, line 115 at r16](https://reviewable.io/reviews/pmem/rpma/1540#-MvIzNXd-CYjcrfjYdwt:-MvIzNXd-CYjcrfjYdwu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b9078da8dc6f660ab94e86bb97cd6ea56eb05bdd/examples/08-messages-ping-pong/server.c#L115)):*
> ```C
> 
> 	while (1) {
> 		/* get completion and process it */
> ```

.



_Code quote:_
```C
/* get completion and process it */
```


<!-- Sent from Reviewable.io -->

2022-02-07 11:42 UTC, ldorau reviewed
> Reviewed 2 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:43 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:43 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/client.c, line 120 at r16](https://reviewable.io/reviews/pmem/rpma/1540#-MvIz8sf9NLhv-lsNeey:-MvIzmcf2hJmKAYNeYeP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b9078da8dc6f660ab94e86bb97cd6ea56eb05bdd/examples/08-messages-ping-pong/client.c#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get completions and process them
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/messages-ping-pong-common.c, line 46 at r15](https://reviewable.io/reviews/pmem/rpma/1540#-MvIuCXl-DHnOGM4LpC6:-MvIzAxy368Jv05EZfFM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fa5a2422e0f0e0f76f68beafa8ff5ae3e477eba8/examples/08-messages-ping-pong/messages-ping-pong-common.c#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/server.c, line 115 at r16](https://reviewable.io/reviews/pmem/rpma/1540#-MvIzNXd-CYjcrfjYdwt:-MvIznf63Uhhk6L19l1r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b9078da8dc6f660ab94e86bb97cd6ea56eb05bdd/examples/08-messages-ping-pong/server.c#L115)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-07 11:44 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1540)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-02-07 11:58 UTC, merged