test: unit tests for rpma_atomic_write
pmem/rpma pull request #1601
Opened 2022-03-01 17:12 UTC by haichangsi

ref #1595

2022-03-02 08:26 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8j-2S5dGCZLBIa_PS:-Mx8j-2S5dGCZLBIa_PT:b-1jfy00) (no related file):*
Unit tests for `rpma_mr_atomic_write()` are missing.

---


<!-- Sent from Reviewable.io -->

2022-03-02 08:33 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tests/unit/conn/conn-atomic_write.c, line 27 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8kTHV6wGoP_0AnpG4:-Mx8kTHV6wGoP_0AnpG5:b-ok01nc) ([raw file](https://github.com/pmem/rpma/blob/6604703d5ab59687d040ae88fd5b330ef9a2c3f3/tests/unit/conn/conn-atomic_write.c#L27)):*
> ```C
> 			MOCK_OFFSET_ALIGNED, Mock_src,
> 			MOCK_FLAGS, MOCK_OP_CONTEXT);
> 	/* verify the results */
> ```

Add one empty line in between, please.



_Code quote:_
```C
			MOCK_FLAGS, MOCK_OP_CONTEXT);
	/* verify the results */
```
___
*[tests/unit/conn/conn-atomic_write.c, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8kZJJ5L_yPusr1tw0:-Mx8kZJJ5L_yPusr1tw1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6604703d5ab59687d040ae88fd5b330ef9a2c3f3/tests/unit/conn/conn-atomic_write.c#L40)):*
> ```C
> 	int ret = rpma_atomic_write(MOCK_CONN, NULL,
> 			MOCK_OFFSET_ALIGNED, Mock_src,
> 			MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

.



_Code quote:_
```C
			MOCK_FLAGS, MOCK_OP_CONTEXT);
	/* verify the results */
```
___
*[tests/unit/conn/conn-atomic_write.c, line 145 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8kllMAVwoU3JsJC3z:-Mx8kllMAVwoU3JsJC4-:b6lnour) ([raw file](https://github.com/pmem/rpma/blob/6604703d5ab59687d040ae88fd5b330ef9a2c3f3/tests/unit/conn/conn-atomic_write.c#L145)):*
> ```C
> 
> 
> static const struct CMUnitTest tests_atomic_write[] = {
> ```

Only one empty line in between, please.



_Code quote:_
```C
}


static const struct CMUnitTest tests_atomic_write[] = {
```
___
*[tests/unit/conn/conn-atomic_write.c, line 157 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8kqPx1wvHiPqydEzR:-Mx8kqPx1wvHiPqydEzS:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6604703d5ab59687d040ae88fd5b330ef9a2c3f3/tests/unit/conn/conn-atomic_write.c#L157)):*
> ```C
> 		setup__conn_new, teardown__conn_delete),
> 	cmocka_unit_test(NULL)
> };
> ```

.



_Code quote:_
```C
};


int
```


<!-- Sent from Reviewable.io -->

2022-03-02 08:33 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-02 08:51 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8ojmqDXi2365WuJWO):*
test: add unit tests for rpma_atomic_write()



_Code quote:_
```
test: unit tests for rpma_atomic_write
```
___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8oo-zBHMAXiTiLeYN):*
Ref: #1595



_Code quote:_
```
ref #1595
```


<!-- Sent from Reviewable.io -->

2022-03-04 08:06 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r3, 2 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-04 09:11 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 27 at r5](https://reviewable.io/reviews/pmem/rpma/1601#-MxJ1i33AjLqDZFKC6QB:-MxJ1i33AjLqDZFKC6QC:baayw6x) ([raw file](https://github.com/pmem/rpma/blob/b0972ffc8cbfd8e3dd7378c90d9f53d130be7356/tests/unit/mr/mr-atomic_write.c#L27)):*
> ```C
>  */
> static void
> atomic_write__failed_E_NOSUPP(void **mrs_ptr)
> ```

You are writing unit tests for `rpma_mr_atomic_write()` - first please read carefully the code of this function:

https://github.com/ldorau/rpma/blob/review-haichangsi-atomic_write/src/mr.c#L193

Can it fail with `RPMA_E_NOSUPP` ?
___
*[tests/unit/mr/mr-atomic_write.c, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1601#-MxJB8x-1-Mdkt2jLy_S:-MxJB8x-1-Mdkt2jLy_T:byaib4k) ([raw file](https://github.com/pmem/rpma/blob/b0972ffc8cbfd8e3dd7378c90d9f53d130be7356/tests/unit/mr/mr-atomic_write.c#L54)):*
> ```C
> 	args.qp = MOCK_QP;
> 	args.opcode = IBV_WR_RDMA_WRITE;
> 	args.send_flags = IBV_SEND_SIGNALED; /* RPMA_F_COMPLETION_ON_ERROR */
> ```

You are passing `RPMA_F_COMPLETION_ON_ERROR` to `rpma_mr_atomic_write()`, so what value of `wr->send_flags` should you expect? - please read carefully the code of `rpma_mr_atomic_write()`:

https://github.com/ldorau/rpma/blob/review-haichangsi-atomic_write/src/mr.c#L219-L221



_Code quote:_
```C
args.send_flags = IBV_SEND_SIGNALED; /* RPMA_F_COMPLETION_ON_ERROR */
```


<!-- Sent from Reviewable.io -->

2022-03-04 13:16 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[-- commits, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1601#-Mx8oo-zBHMAXiTiLeYN):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ref: #1595
</blockquote></details>

Please remove it at all.


<!-- Sent from Reviewable.io -->

2022-03-06 20:29 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 24 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxVuqAT-tJgRnkGv6b9:-MxVuqAT-tJgRnkGv6bA:b-xoi228) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/mr/mr-atomic_write.c#L24)):*
> ```C
> /*
>  * atomic_write__COMPL_ON_ERROR_failed_E_PROVIDER -
>  * rpma_mr_atomic_write failed with RPMA_E_PROVIDER
> ```

There is missing an analogous test for `RPMA_F_COMPLETION_ON_SUCCESS`.



_Code quote:_
```C
 * atomic_write__COMPL_ON_ERROR_failed_E_PROVIDER -
 * rpma_mr_atomic_write failed with RPMA_E_PROVIDER
 * when send_flags == IBV_SEND_SIGNALED
 * for RPMA_F_COMPLETION_ON_ERROR
 */
static void
atomic_write__COMPL_ON_ERROR_failed_E_PROVIDER(void **mrs_ptr)
```


<!-- Sent from Reviewable.io -->

2022-03-07 07:53 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1601#-MxYMXNt6KvA4aVLvsia:-MxYMXNuEIL4b9qUT81H:b-7yt9dn) (no related file):*
Rebase it onto the new version of #1595 , please

---


<!-- Sent from Reviewable.io -->

2022-03-07 09:44 UTC, grom72 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tests/unit/common/mocks-rpma-mr.c, line 83 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxYPUZKEqFKmQ1naR6o:-MxYPUZKEqFKmQ1naR6p:bj5lu1q) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/common/mocks-rpma-mr.c#L83)):*
> ```C
> 	assert_non_null(qp);
> 	assert_int_not_equal(flags, 0);
> 	assert_true(src != NULL && dst != NULL);
> ```

```
assert_non_null(src);
assert_non_null(dst);
```



_Code quote:_
```C
	assert_true(src != NULL && dst != NULL);
```


<!-- Sent from Reviewable.io -->

2022-03-07 09:57 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 66 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxYnlKqA0LdYmoZiqJK:-MxYnlKr5shxKu3UxQ_9:bm6123k) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/mr/mr-atomic_write.c#L66)):*
> ```C
> 	args.opcode = IBV_WR_RDMA_WRITE;
> 	args.send_flags = (IBV_SEND_INLINE | IBV_SEND_FENCE)
> 				| IBV_SEND_SIGNALED;
> ```

Shall we have separate tests w/ and w/o IBV_SEND_SIGNALED?



_Code quote:_
```C
IBV_SEND_SIGNALED
```


<!-- Sent from Reviewable.io -->

2022-03-07 12:01 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1601#-MxYMXNt6KvA4aVLvsia:-MxZFG1E59q_6OdNYP77:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase it onto the new version of #1595 , please
</blockquote></details>

Done.

---
___
*[tests/unit/common/mocks-rpma-mr.c, line 83 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxYPUZKEqFKmQ1naR6o:-MxZDlFBCtUgTYoHMMAN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/common/mocks-rpma-mr.c#L83)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
assert_non_null(src);
assert_non_null(dst);
```
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 27 at r5](https://reviewable.io/reviews/pmem/rpma/1601#-MxJ1i33AjLqDZFKC6QB:-MxO5BK6BIq0InizyCk_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b0972ffc8cbfd8e3dd7378c90d9f53d130be7356/tests/unit/mr/mr-atomic_write.c#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You are writing unit tests for `rpma_mr_atomic_write()` - first please read carefully the code of this function:

https://github.com/ldorau/rpma/blob/review-haichangsi-atomic_write/src/mr.c#L193

Can it fail with `RPMA_E_NOSUPP` ?
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1601#-MxJB8x-1-Mdkt2jLy_S:-MxO2utu8SVxviY4N7S3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b0972ffc8cbfd8e3dd7378c90d9f53d130be7356/tests/unit/mr/mr-atomic_write.c#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You are passing `RPMA_F_COMPLETION_ON_ERROR` to `rpma_mr_atomic_write()`, so what value of `wr->send_flags` should you expect? - please read carefully the code of `rpma_mr_atomic_write()`:

https://github.com/ldorau/rpma/blob/review-haichangsi-atomic_write/src/mr.c#L219-L221
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 24 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxVuqAT-tJgRnkGv6b9:-MxZFIDgAyLY7bGDho2j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/mr/mr-atomic_write.c#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is missing an analogous test for `RPMA_F_COMPLETION_ON_SUCCESS`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 12:05 UTC, ldorau requested changes
> Reviewed 1 of 5 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 56 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZGFcr-9kVsFGQ4x8i:-MxZGFcr-9kVsFGQ4x8j:bjmkqtt) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L56)):*
> ```C
>  * atomic_write__COMPL_ON_SUCCESS_failed_E_PROVIDER -
>  * rpma_mr_atomic_write failed with RPMA_E_PROVIDER
>  * when send_flags == (IBV_SEND_INLINE | IBV_SEND_FENCE)
> ```

brackets are redundant



_Code quote:_
```C
(IBV_SEND_INLINE | IBV_SEND_FENCE)
```
___
*[tests/unit/mr/mr-atomic_write.c, line 70 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZGKPA0MDEiGUO4av7:-MxZGKPA0MDEiGUO4av8:bjmkqtt) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L70)):*
> ```C
> 	args.opcode = IBV_WR_RDMA_WRITE;
> 	/* RPMA_F_COMPLETION_ON_SUCCESS */
> 	args.send_flags = (IBV_SEND_INLINE | IBV_SEND_FENCE)
> ```

brackets are redundant



_Code quote:_
```C
 (IBV_SEND_INLINE | IBV_SEND_FENCE)
```


<!-- Sent from Reviewable.io -->

2022-03-07 12:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 58 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZIRsn-Yzoowv7UhuS:-MxZIRsn-Yzoowv7UhuT:bx1akdt) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L58)):*
> ```C
>  * when send_flags == (IBV_SEND_INLINE | IBV_SEND_FENCE)
>  *				| IBV_SEND_SIGNALED
>  * for RPMA_F_COMPLETION_ON_SUCCESS
> ```

RPMA_F_COMPLETION_ALWAYS



_Code quote:_
```C
RPMA_F_COMPLETION_ON_SUCCESS
```
___
*[tests/unit/mr/mr-atomic_write.c, line 108 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZIV0pCsrcZpFNRNjZ:-MxZIV0pCsrcZpFNRNj_:bx1akdt) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L108)):*
> ```C
> 	/* run test */
> 	int ret = rpma_mr_atomic_write(MOCK_QP, mrs->remote, MOCK_DST_OFFSET,
> 			Mock_src, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

RPMA_F_COMPLETION_ALWAYS



_Code quote:_
```C
MOCK_FLAGS
```


<!-- Sent from Reviewable.io -->

2022-03-07 12:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 69 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZIcyj8ApbAF_aYaC9:-MxZIcyj8ApbAF_aYaCA:bx1akdt) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L69)):*
> ```C
> 	args.qp = MOCK_QP;
> 	args.opcode = IBV_WR_RDMA_WRITE;
> 	/* RPMA_F_COMPLETION_ON_SUCCESS */
> ```

RPMA_F_COMPLETION_ALWAYS



_Code quote:_
```C
RPMA_F_COMPLETION_ON_SUCCESS
```


<!-- Sent from Reviewable.io -->

2022-03-07 12:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 90 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZK77lEzDGdKey0rbA:-MxZK77mCHBde5pLwcTf:b-dvuj1s) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L90)):*
> ```C
>  */
> static void
> atomic_write__success(void **mrs_ptr)
> ```

Please add analogous one with `RPMA_F_COMPLETION_ON_ERROR`, so
1) `atomic_write__success_COMPLETION_ON_ERROR`
2) `atomic_write__success_COMPLETION_ALWAYS`



_Code quote:_
```C
/*
 * atomic_write__success - happy day scenario
 */
static void
atomic_write__success(void **mrs_ptr)
```


<!-- Sent from Reviewable.io -->

2022-03-07 12:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 66 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxYnlKqA0LdYmoZiqJK:-MxZKTQhAc-wXe7F5IMG:b-m1jcvv) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/mr/mr-atomic_write.c#L66)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we have separate tests w/ and w/o IBV_SEND_SIGNALED?
</blockquote></details>

Yes, @haichangsi :
1) atomic_write__success_COMPLETION_ON_ERROR
2) atomic_write__success_COMPLETION_ALWAYS


<!-- Sent from Reviewable.io -->

2022-03-07 12:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 87 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZKi5t3PRZ6v2ZIPdY:-MxZKi5t3PRZ6v2ZIPdZ:br0nl2e) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L87)):*
> ```C
> 
> /*
>  * atomic_write__success - happy day scenario
> ```

atomic_write__success_COMPLETION_ALWAYS



_Code quote:_
```C
atomic_write__success
```
___
*[tests/unit/mr/mr-atomic_write.c, line 90 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZKj_31SWjney4D9xf:-MxZKj_31SWjney4D9xg:br0nl2e) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L90)):*
> ```C
>  */
> static void
> atomic_write__success(void **mrs_ptr)
> ```

atomic_write__success_COMPLETION_ALWAYS



_Code quote:_
```C
atomic_write__success
```


<!-- Sent from Reviewable.io -->

2022-03-07 13:12 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-07 14:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1601#-MxZjjSP5CJC9q3TqF0m:-MxZjjSQ5bfyKW8GjVPH:bw0615o) (no related file):*
Please rebase onto the current #1595.

---


<!-- Sent from Reviewable.io -->

2022-03-07 14:31 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/common/mocks-rpma-mr.c, line 83 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxYPUZKEqFKmQ1naR6o:-MxZmVQw7NEE0j7sB-0b:b-68i0ga) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/common/mocks-rpma-mr.c#L83)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72 issue fixed, please resolve
___
*[tests/unit/mr/mr-atomic_write.c, line 66 at r6](https://reviewable.io/reviews/pmem/rpma/1601#-MxYnlKqA0LdYmoZiqJK:-MxZmbMt2ZhT9bDI_R2E:b-68i0ga) ([raw file](https://github.com/pmem/rpma/blob/5a83f4e590279466e88d4ef4b16121cafeac1948/tests/unit/mr/mr-atomic_write.c#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, @haichangsi :
1) atomic_write__success_COMPLETION_ON_ERROR
2) atomic_write__success_COMPLETION_ALWAYS
</blockquote></details>

@grom72 issue fixed, please resolve


<!-- Sent from Reviewable.io -->

2022-03-07 14:39 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 176 at r9](https://reviewable.io/reviews/pmem/rpma/1601#-MxZoJhbD6hZLH5FJrcu:-MxZoJhbD6hZLH5FJrcv:be56s4s) ([raw file](https://github.com/pmem/rpma/blob/a333294db8b99891289b6c569de810b28b47072f/tests/unit/mr/mr-atomic_write.c#L176)):*
> ```C
> 			teardown__mr_local_and_remote),
> 	cmocka_unit_test_setup_teardown(
> 			atomic_write__success_COMPLETION_ALWAYS,
> ```

Please rename `atomic_write__success_COMPLETION_ALWAYS` to `atomic_write__COMPLETION_ALWAYS_success`



_Code quote:_
```C
atomic_write__success_COMPLETION_ALWAYS
```
___
*[tests/unit/mr/mr-atomic_write.c, line 180 at r9](https://reviewable.io/reviews/pmem/rpma/1601#-MxZoUnG8ZctIjgvEUTW:-MxZoUnG8ZctIjgvEUTX:b893ojw) ([raw file](https://github.com/pmem/rpma/blob/a333294db8b99891289b6c569de810b28b47072f/tests/unit/mr/mr-atomic_write.c#L180)):*
> ```C
> 			teardown__mr_local_and_remote),
> 	cmocka_unit_test_setup_teardown(
> 			atomic_write__success_COMPLETION_ON_ERROR,
> ```

Please rename `atomic_write__success_COMPLETION_ON_ERROR` to `atomic_write__COMPLETION_ON_ERROR_success`



_Code quote:_
```C
atomic_write__success_COMPLETION_ON_ERROR
```


<!-- Sent from Reviewable.io -->

2022-03-07 15:40 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-07 21:08 UTC, ldorau reviewed
> Reviewed 4 of 8 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-07 21:11 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/mr/mr-atomic_write.c, line 56 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZGFcr-9kVsFGQ4x8i:-MxZQqDo6uClGVonFt93:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

brackets are redundant
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 58 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZIRsn-Yzoowv7UhuS:-MxZQpn46PpmRyeiyCoI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

RPMA_F_COMPLETION_ALWAYS
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 69 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZIcyj8ApbAF_aYaC9:-MxZQtx_EzCJzRyju9Z3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

RPMA_F_COMPLETION_ALWAYS
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 70 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZGKPA0MDEiGUO4av7:-MxZQuDY0Hf8qadoojdW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L70)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

brackets are redundant
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 87 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZKi5t3PRZ6v2ZIPdY:-MxZRKq29XoXDhSjPeha:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L87)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

atomic_write__success_COMPLETION_ALWAYS
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 90 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZKj_31SWjney4D9xf:-MxZRH_c6sKGgj8kM7qp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

atomic_write__success_COMPLETION_ALWAYS
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 108 at r8](https://reviewable.io/reviews/pmem/rpma/1601#-MxZIV0pCsrcZpFNRNjZ:-MxZRBm13sUcUbJV5Sj3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c7f09487dd6fa23922c7cdefbb520c63ed63667/tests/unit/mr/mr-atomic_write.c#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

RPMA_F_COMPLETION_ALWAYS
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 176 at r9](https://reviewable.io/reviews/pmem/rpma/1601#-MxZoJhbD6hZLH5FJrcu:-MxaD2beBzeHzdKlI2R3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a333294db8b99891289b6c569de810b28b47072f/tests/unit/mr/mr-atomic_write.c#L176)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rename `atomic_write__success_COMPLETION_ALWAYS` to `atomic_write__COMPLETION_ALWAYS_success`
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-atomic_write.c, line 180 at r9](https://reviewable.io/reviews/pmem/rpma/1601#-MxZoUnG8ZctIjgvEUTW:-MxaD2sr6V8oLUzpGcoZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a333294db8b99891289b6c569de810b28b47072f/tests/unit/mr/mr-atomic_write.c#L180)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rename `atomic_write__success_COMPLETION_ON_ERROR` to `atomic_write__COMPLETION_ON_ERROR_success`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 21:22 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/unit/mr/mr-atomic_write.c, line 56 at r13](https://reviewable.io/reviews/pmem/rpma/1601#-MxaFYLi2pl3CiaKND6F:-MxaFYLi2pl3CiaKND6G:bjmkqtt) ([raw file](https://github.com/pmem/rpma/blob/37e3b0710115db228e04388412bae96e41c642fb/tests/unit/mr/mr-atomic_write.c#L56)):*
> ```C
>  * atomic_write__COMPL_ON_SUCCESS_failed_E_PROVIDER -
>  * rpma_mr_atomic_write failed with RPMA_E_PROVIDER
>  * when send_flags == (IBV_SEND_INLINE | IBV_SEND_FENCE)
> ```

brackets are redundant



_Code quote:_
```C
 (IBV_SEND_INLINE | IBV_SEND_FENCE)
```


<!-- Sent from Reviewable.io -->

2022-03-07 21:35 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601#-:-MxaIkm_6JqDMjA_EW9V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-07 21:37 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/mr/mr-atomic_write.c, line 56 at r13](https://reviewable.io/reviews/pmem/rpma/1601#-MxaFYLi2pl3CiaKND6F:-MxaJFML9RNI9GTu9VEG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/37e3b0710115db228e04388412bae96e41c642fb/tests/unit/mr/mr-atomic_write.c#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

brackets are redundant
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-07 21:38 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-08 07:07 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 8 files at r10, 3 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601#-:-MxcLg1yCNfuzwEl69vf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-08 07:07 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-08 07:18 UTC, Patryk717 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601#-:-MxcO51n82K4wRZTr7QM:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-08 09:35 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 4 of 8 files at r10, 3 of 4 files at r11, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601#-:-MxcsaGD-MnAq9JqJkzL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-08 09:59 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1601)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-08 10:00 UTC, merged