test: add the rpma_mr_remote_from_descriptor multithreaded test
pmem/rpma pull request #1630
Opened 2022-03-23 11:37 UTC by haichangsi

2022-03-23 11:52 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-23 12:04 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[tests/multithreaded/mr/CMakeLists.txt, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1630#-MyqePfmBytg2mCFTVtV:-MyqePfmBytg2mCFTVtW:b-fg72tb) ([raw file](https://github.com/pmem/rpma/blob/1b821682f2189ee6d41e9c3393c519f74024bc03/tests/multithreaded/mr/CMakeLists.txt#L17)):*
> ```CMake
> 	SRCS rpma_mr_reg.c)
> add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
> 	SRCS rpma_mr_remote_from_descriptor.c)
> ```

```
add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c)
```



_Code quote:_
```CMake
add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
	SRCS rpma_mr_remote_from_descriptor.c)
add_multithreaded(NAME mr BIN server_rpma_mr_remote_from_descriptor
	SRCS server_rpma_mr_remote_from_descriptor.c)
```


<!-- Sent from Reviewable.io -->

2022-03-23 12:09 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/mr/CMakeLists.txt, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1630#-MyqePfmBytg2mCFTVtV:-MyqfZVN7kp7AQAofNya:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1b821682f2189ee6d41e9c3393c519f74024bc03/tests/multithreaded/mr/CMakeLists.txt#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-23 12:15 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-23 12:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-Myqhjdq0QSVIhx2wGHC:-Myqhjdq0QSVIhx2wGHD:bqvnuy2) (no related file):*
The `multithreaded-mr-rpma_mr_remote_from_descriptor_0_none` test fails.

---


<!-- Sent from Reviewable.io -->

2022-03-23 12:22 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-Myqhjdq0QSVIhx2wGHC:-MyqiZiX-E6XEGYJDVnA:bv418c2) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The `multithreaded-mr-rpma_mr_remote_from_descriptor_0_none` test fails.
</blockquote></details>

```
The following tests FAILED:
	130 - multithreaded-mr-rpma_mr_remote_from_descriptor_0_none (Failed)
	131 - multithreaded-mr-rpma_mr_remote_from_descriptor_0_drd (Failed)
	132 - multithreaded-mr-rpma_mr_remote_from_descriptor_0_helgrind (Failed)
```

---


<!-- Sent from Reviewable.io -->

2022-03-23 14:22 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr742hAsaP33CCvGZ8:-Myr742hAsaP33CCvGZ9:b-od2pju) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L30)):*
> ```C
> 	struct rpma_peer *peer;
> 	struct rpma_conn *conn;
> 	struct rpma_mr_remote **mr_ptr;
> ```

`struct rpma_mr_remote *mr_ptr;`



_Code quote:_
```C
struct rpma_mr_remote **mr_ptr;
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr7AC235YB7-vg1Xsm:-Myr7AC235YB7-vg1Xsn:b-d50hs9) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L115)):*
> ```C
> 
> 	ret = rpma_mr_remote_from_descriptor(&dst_data->descriptors[0],
> 			dst_data->mr_desc_size, pr->mr_ptr);
> ```

`&pr->mr_ptr` - you should pass here the variable via reference to store the output value in it.



_Code quote:_
```C
pr->mr_ptr
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr8S0f2-0J69oRVJrD:-Myr8S0f2-0J69oRVJrE:bbswvo9) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L153)):*
> ```C
> 	}
> 
> 	if ((ret = rpma_mr_remote_get_size(mr_ptr, &mr_size))) {
> ```

The tested function (`rpma_mr_remote_from_descriptor`) is the only API call that can be used in the `thread` function.
You are to verify if `rpma_mr_remote_from_descriptor` works well, so you have to check if a content of the `struct rpma_mr_remote` structure returned by this function is the same as you should have stored in `prestate_init`.



_Code quote:_
```C
	if ((ret = rpma_mr_remote_get_size(mr_ptr, &mr_size))) {
		MTT_RPMA_ERR(result, "rpma_mr_remote_get_size", ret);
	};

	if ((ret = rpma_mr_remote_get_size(*pr->mr_ptr, &pr_mr_size))) {
		MTT_RPMA_ERR(result, "rpma_mr_remote_get_size", ret);
	};
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 216 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr3uUm5ucHgAOBBEZW:-Myr3uUm5ucHgAOBBEZX:b-r8qiul) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L216)):*
> ```C
>  */
> int server_main(char *addr, unsigned port,
> 		struct rpma_conn_private_data *pdata_exp);
> ```

It should not be needed. `char *addr, unsigned port,` is enough.



_Code quote:_
```C
struct rpma_conn_private_data *pdata_exp
```
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 92 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr4UZH7JhBJbXJ9DgP:-Myr4UZH7JhBJbXJ9DgQ:b-r8qiul) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L92)):*
> ```C
> int
> server_main(char *addr, unsigned port,
> 		struct rpma_conn_private_data *pdata_exp)
> ```

It should not be needed. `char *addr, unsigned port,` is enough.



_Code quote:_
```C
		struct rpma_conn_private_data *pdata_exp)
```
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 125 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr58bL5o1xkgS17hKn:-Myr58bL5o1xkgS17hKo:b-unzx7g) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L125)):*
> ```C
> 		goto err_peer_delete;
> 	}
> 	pdata_exp->ptr = (void *)data;
> ```

You have to store the memory region's descriptor in the private data like in https://github.com/pmem/rpma/blob/master/examples/02-read-to-volatile/server.c#L85-L101.



_Code quote:_
```C
	pdata_exp->ptr = (void *)data;
	pdata_exp->len = sizeof(data);
```


<!-- Sent from Reviewable.io -->

2022-03-23 21:09 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr8S0f2-0J69oRVJrD:-Mys_dVSBl_GiAGqQsmz:b-bgsb7z) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The tested function (`rpma_mr_remote_from_descriptor`) is the only API call that can be used in the `thread` function.
You are to verify if `rpma_mr_remote_from_descriptor` works well, it returns a pointer, so the only thing you can check is to verify if the pointer is the same as stored in `prestate_init`.
</blockquote></details>

I meant you have to check if a content of the `struct rpma_mr_remote` structure returned by this function is the same as you should have stored in `prestate_init` of course ...


<!-- Sent from Reviewable.io -->

2022-03-23 21:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr8S0f2-0J69oRVJrD:-Mysefx-2anxQQpluMYB:b-5tp46t) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant you have to check if a content of the `struct rpma_mr_remote` structure returned by this function is the same as you should have stored in `prestate_init` of course ...
</blockquote></details>

Ah, I forgot that `struct rpma_mr_remote`is not public ... so you should store the pointer and the size in `prestate_init ` and call only `rpma_mr_remote_from_descriptor()` and `memcpy()` here with the stored pointer and size.


<!-- Sent from Reviewable.io -->

2022-03-23 21:31 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr742hAsaP33CCvGZ8:-MysbOhzB3hGbm1mvvrV:b-qc2tid) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`struct rpma_mr_remote *mr_ptr;`
</blockquote></details>

You have to store the pointer and the size here.


<!-- Sent from Reviewable.io -->

2022-03-23 22:03 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-MysncLBBI5P2LFgqhKO:-MysncLBBI5P2LFgqhKP:b-sjr3re) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L70)):*
> ```C
> 			goto err_peer_delete;
> 		}
> ```

`rpma_conn_req_connect` is missing here.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 157 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-MysnWcM2Kop3_aepR2N:-MysnWcM2Kop3_aepR2O:b-mbaqwo) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L157)):*
> ```C
> 	};
> 
> 	if ((ret = rpma_mr_remote_get_size(*pr->mr_ptr, &pr_mr_size))) {
> ```

`(pr->mr_ptr,`



_Code quote:_
```C
(*pr->mr_ptr,
```


<!-- Sent from Reviewable.io -->

2022-03-23 22:05 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 10 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-MysnjU57LZRiN6aHFVB:-MysnjU57LZRiN6aHFVC:beghz3n) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L72)):*
> ```C
> 
> 		/* wait for the connection to establish */
> 		ret = rpma_conn_next_event(pr->conn, &conn_event);
> ```

`pr->conn` is never set and it always equals NULL, so the client never can connect.



_Code quote:_
```C
pr->conn
```


<!-- Sent from Reviewable.io -->

2022-03-24 10:03 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 10 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 125 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr58bL5o1xkgS17hKn:-MyvNM14Bz3O-UuV1zUR:bhopp1v) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You have to store the memory region's descriptor in the private data like in https://github.com/pmem/rpma/blob/master/examples/02-read-to-volatile/server.c#L85-L101.
</blockquote></details>

Even https://github.com/pmem/rpma/blob/master/examples/02-read-to-volatile/server.c#L69-L101


<!-- Sent from Reviewable.io -->

2022-03-28 06:38 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 2 of 5 files reviewed, 11 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tests/multithreaded/common/utils.c, line 1 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEEotiAhNE8rOENN_w:-MzEEotiAhNE8rOENN_x:b-87crdh) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/common/utils.c#L1)):*
> ```C
> /* SPDX-License-Identifier: BSD-3-Clause */
> ```

`// SPDX-License-Identifier: BSD-3-Clause`



_Code quote:_
```C
/* SPDX-License-Identifier: BSD-3-Clause */
```


<!-- Sent from Reviewable.io -->

2022-03-28 06:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 2 of 5 files reviewed, 13 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tests/multithreaded/common/utils.c, line 9 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEHZ2C0gGc-sFEwbev:-MzEHZ2C0gGc-sFEwbew:b69dmjf) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/common/utils.c#L9)):*
> ```C
> 
> #include <stdio.h>
> #include <unistd.h>
> ```

```c
#include <stdlib.h>
#include <string.h>
```
is missing here.



_Code quote:_
```C
#include <stdio.h>
#include <unistd.h>
```
___
*[tests/multithreaded/mr/CMakeLists.txt, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEG6EKAxJM1ogSzupa:-MzEG6EKAxJM1ogSzupb:b-bnfyjq) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/CMakeLists.txt#L17)):*
> ```CMake
> 	SRCS rpma_mr_reg.c)
> add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
> 	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c)
> ```

```
add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c
		../common/utils.c)
```



_Code quote:_
```CMake
add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c)
```


<!-- Sent from Reviewable.io -->

2022-03-28 06:55 UTC, ldorau reviewed
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-28 09:39 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEsxEE8UKu2tYH6q8Y:-MzEsxEFCo2d7ctfgYA4:b-j4y04t) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L26)):*
> ```C
> 
> 	/* the expected value of the private data */
> 	struct rpma_conn_private_data pdata_exp;
> ```

You have to store `struct common_data dst_data;` instead of `struct rpma_conn_private_data pdata_exp;` here, because the private will be freed when the connection is closed.



_Code quote:_
```C
	/* the expected value of the private data */
	struct rpma_conn_private_data pdata_exp;
```


<!-- Sent from Reviewable.io -->

2022-03-28 10:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEsxEE8UKu2tYH6q8Y:-MzEz5guE1v_nShEW1Wn:b-brgkrh) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You have to store `struct common_data dst_data;` instead of `struct rpma_conn_private_data pdata_exp;` here, because the private will be freed when the connection is closed.
</blockquote></details>

No, it is OK, just `return` is missing at the end of `prestate_init()` :-)
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEyJRw8EpV1rVIKwzM:-MzEyJRxDXsbO9MP3rIQ:bpb3s4r) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L121)):*
> ```C
> 			dst_data->mr_desc_size, &pr->mr_ptr);
> 	if (ret)
> 		goto err_conn_disconnect;
> ```

```c
MTT_RPMA_ERR(tr, "rpma_mr_remote_from_descriptor", ret);
```



_Code quote:_
```C
	if (ret)
		goto err_conn_disconnect;
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 124 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEzH5s0JPdGHoYqLwe:-MzEzH5s0JPdGHoYqLwf:bhea9d3) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L124)):*
> ```C
> 
> 	if ((ret = rpma_mr_remote_get_size(pr->mr_ptr, &pr->mr_size))) {
> 		MTT_RPMA_ERR(tr, "rpma_mr_remote_get_size", ret);
> ```

`{ }` brackets are redundant here.



_Code quote:_
```C
	if ((ret = rpma_mr_remote_get_size(pr->mr_ptr, &pr->mr_size))) {
		MTT_RPMA_ERR(tr, "rpma_mr_remote_get_size", ret);
	};
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 126 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEyuKE0lWQYdsyHOxZ:-MzEyuKE0lWQYdsyHOx_:b-uqo25x) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L126)):*
> ```C
> 		MTT_RPMA_ERR(tr, "rpma_mr_remote_get_size", ret);
> 	};
> ```

`return` is missing here :-)


<!-- Sent from Reviewable.io -->

2022-03-28 10:09 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 124 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEzH5s0JPdGHoYqLwe:-MzF-19_5Tmxywizef9w:bubvity) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`{ }` brackets are redundant here.
</blockquote></details>

No, they are not, `goto err_conn_disconnect;` is missing here :-)


<!-- Sent from Reviewable.io -->

2022-03-29 08:27 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tests/multithreaded/common/utils.c, line 1 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEEotiAhNE8rOENN_w:-MzJimm-CKZlmE-E7MjN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/common/utils.c#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`// SPDX-License-Identifier: BSD-3-Clause`
</blockquote></details>

Done.
___
*[tests/multithreaded/common/utils.c, line 9 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEHZ2C0gGc-sFEwbev:-MzJj-0d4OCIzGra0z4C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/common/utils.c#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
#include <stdlib.h>
#include <string.h>
```
is missing here.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/CMakeLists.txt, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEG6EKAxJM1ogSzupa:-MzJif5z8sUFZDCQ4v1G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/CMakeLists.txt#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c
		../common/utils.c)
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr742hAsaP33CCvGZ8:-MyrEq_F2XtyuosPSpmz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`struct rpma_mr_remote *mr_ptr;`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-MysncLBBI5P2LFgqhKO:-Mz-LrI-3wri6eFOEqzm:b-al4w8g) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L70)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_req_connect` is missing here.
</blockquote></details>

oh.. right, done
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-MysnjU57LZRiN6aHFVB:-Mz-PEZ9EkIpBTqYsE4w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L72)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`pr->conn` is never set and it always equals NULL, so the client never can connect.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr7AC235YB7-vg1Xsm:-MyrElzN645JPgJ_KdMV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L115)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`&pr->mr_ptr` - you should pass here the variable via reference to store the output value in it.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr8S0f2-0J69oRVJrD:-Mz-lIos4fanRznimFOH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, I forgot that `struct rpma_mr_remote`is not public ... so you should store the pointer and the size in `prestate_init ` and call only `rpma_mr_remote_from_descriptor()` and `memcpy()` here with the stored pointer and size.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 157 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-MysnWcM2Kop3_aepR2N:-Mz-lJtK7QI4nn0HVslp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`(pr->mr_ptr,`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 216 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr3uUm5ucHgAOBBEZW:-MyrLqnMDoJz-htkrS_r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L216)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should not be needed. `char *addr, unsigned port,` is enough.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEyJRw8EpV1rVIKwzM:-MzJjuHL9KU5l1NsymKO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L121)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
MTT_RPMA_ERR(tr, "rpma_mr_remote_from_descriptor", ret);
```

</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 124 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEzH5s0JPdGHoYqLwe:-MzJk0PF8gXc0Or9q2lM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, they are not, `goto err_conn_disconnect;` is missing here :-)
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 126 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEyuKE0lWQYdsyHOxZ:-MzJk2TLDqeDV-VgQdXX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`return` is missing here :-)
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 92 at r2](https://reviewable.io/reviews/pmem/rpma/1630#-Myr4UZH7JhBJbXJ9DgP:-Mz-lhUC2BeDSFnMZGhL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/feed2667a12a640420faf3160b7ffe67f775b233/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should not be needed. `char *addr, unsigned port,` is enough.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-29 08:33 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEyJRw8EpV1rVIKwzM:-MzJnRBX9tweWXO52oid:b1yl2dv) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L121)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But where are brackets ???


<!-- Sent from Reviewable.io -->

2022-03-29 10:51 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/1630#-MzEyJRw8EpV1rVIKwzM:-MzKIIBh25R8LsPFMshm:b-ljo57k) ([raw file](https://github.com/pmem/rpma/blob/41bd53923c119eb96e6eaeab0bd37336c7c33ec8/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L121)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But where are brackets ???
</blockquote></details>

Sorry, done.


<!-- Sent from Reviewable.io -->

2022-03-29 11:19 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-29 11:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/common/utils.h, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKV9vd9HMjxg-8mSnC:-MzKV9ve0URTQ1BsGx4b:b7lbw84) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/common/utils.h#L21)):*
> ```objc
> 
> /*
>  * malloc_aligned -- allocate an aligned chunk of memory
> ```

Please remove it - it is used only in *.c files.



_Code quote:_
```objc
/*
 * malloc_aligned -- allocate an aligned chunk of memory
 */
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKVP3xEujtSmdObsMP:-MzKVP3xEujtSmdObsMQ:b-i75e0g) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L30)):*
> ```C
> 
> 
> static void
> ```

Redundant empty line (there should be only one empty line in between).



_Code quote:_
```C
};


static void
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 167 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKViiABBpRIgeF90wm:-MzKViiABBpRIgeF90wn:b-kj5tgh) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L167)):*
> ```C
> 
> 	if (memcmp(mr_ptr, pr->mr_ptr, pr->mr_size) != 0)
> 		MTT_ERR_MSG(result, "Wrong content of the mr_remote", -1);
> ```

Redundant empty line



_Code quote:_
```C
		MTT_ERR_MSG(result, "Wrong content of the mr_remote", -1);

}
```


<!-- Sent from Reviewable.io -->

2022-03-29 11:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 40 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKWxSUE42rK0CLp3Hm:-MzKWxSUE42rK0CLp3Hn:b-1zb3l6) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L40)):*
> ```C
> 	int ret;
> 
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> ```

[BEGIN] Please check if those parts of code are identical:
https://github.com/pmem/rpma/blob/master/tests/multithreaded/conn/rpma_conn_get_private_data.c#L41-L112
and -  if they are  - move them to a common file.



_Code quote:_
```C
	if ((ret = rpma_utils_get_ibv_context(pr->addr,
			RPMA_UTIL_IBV_CONTEXT_LOCAL, &ibv_ctx))) {
		MTT_RPMA_ERR(tr, "rpma_utils_get_ibv_context", ret);
		return;
	}
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 100 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKX-yF6i6iLpSRfZIr:-MzKX-yF6i6iLpSRfZIs:b-y358s8) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L100)):*
> ```C
> 	} while (retry < MAX_CONN_RETRY);
> 
> 	/* get the connection private data */
> ```

[END] Please check if those parts of code are identical:
https://github.com/pmem/rpma/blob/master/tests/multithreaded/conn/rpma_conn_get_private_data.c#L41-L112
and -  if they are  - move them to a common file.



_Code quote:_
```C
	/* get the connection private data */
	ret = rpma_conn_get_private_data(pr->conn, &pr->pdata_exp);
	if (ret) {
		MTT_RPMA_ERR(tr, "rpma_conn_get_private_data", ret);
		goto err_conn_delete;
	} else if (pr->pdata_exp.ptr == NULL) {
		MTT_ERR_MSG(tr,
			"The server has not provided the connection's private data",
			-1);
		goto err_conn_delete;
	}
```


<!-- Sent from Reviewable.io -->

2022-03-30 19:49 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/utils.h, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKV9vd9HMjxg-8mSnC:-MzPwf9W4vIwf60eCuDH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/common/utils.h#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please remove it - it is used only in *.c files.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKVP3xEujtSmdObsMP:-MzPwnzH-1tGuAaY7t5Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Redundant empty line (there should be only one empty line in between).
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 40 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKWxSUE42rK0CLp3Hm:-MzRN3G5-P1Qy15xLYMl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

[BEGIN] Please check if those parts of code are identical:
https://github.com/pmem/rpma/blob/master/tests/multithreaded/conn/rpma_conn_get_private_data.c#L41-L112
and -  if they are  - move them to a common file.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 100 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKX-yF6i6iLpSRfZIr:-MzRG-5LEpQUhvaN8NDz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L100)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

[END] Please check if those parts of code are identical:
https://github.com/pmem/rpma/blob/master/tests/multithreaded/conn/rpma_conn_get_private_data.c#L41-L112
and -  if they are  - move them to a common file.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 167 at r5](https://reviewable.io/reviews/pmem/rpma/1630#-MzKViiABBpRIgeF90wm:-MzRG-c374mh2WQm3fRM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc8eb6109be4c380a72082689f02464552fce775/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L167)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Redundant empty line
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-31 08:23 UTC, ldorau requested changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-MzU35mz0S01coHmYF3W:-MzU35mz0S01coHmYF3X:b-l7mh0k) (no related file):*
Please rebase on top of https://github.com/pmem/rpma/pull/1635

---
___
*[tests/multithreaded/common/utils.h, line 20 at r6](https://reviewable.io/reviews/pmem/rpma/1630#-MzU3POv37plv627owdB:-MzU3POv37plv627owdC:b-cy88f0) ([raw file](https://github.com/pmem/rpma/blob/693f39e0130368cb528b150dcb681f51b4361f22/tests/multithreaded/common/utils.h#L20)):*
> ```objc
> };
> 
> struct prestate {
> ```

Do not move it here, it should stay in the test, because it is test-specific.



_Code quote:_
```objc
struct prestate {
```


<!-- Sent from Reviewable.io -->

2022-04-01 10:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-MzU35mz0S01coHmYF3W:-MzZdxhqChbjgA0mlNHb:b-as7sxr) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase on top of https://github.com/pmem/rpma/pull/1635
</blockquote></details>

#1635 has been merged, rebase on the master

---


<!-- Sent from Reviewable.io -->

2022-04-03 19:22 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-MzU35mz0S01coHmYF3W:-MzksDUM124dpSbRZ-Xl:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

#1635 has been merged, rebase on the master
</blockquote></details>

Done.

---
___
*[tests/multithreaded/common/utils.h, line 20 at r6](https://reviewable.io/reviews/pmem/rpma/1630#-MzU3POv37plv627owdB:-MzksG942MdmI5smBfpo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/693f39e0130368cb528b150dcb681f51b4361f22/tests/multithreaded/common/utils.h#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do not move it here, it should stay in the test, because it is test-specific.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-04 06:54 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r7, 7 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/common/mtt.c, line 2 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJ6BT7uF9yH0j_LNd:-MznJ6BT7uF9yH0j_LNe:b-of8zyy) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

`Copyright 2021-2022`



_Code quote:_
```C
Copyright 2021, 
```
___
*[tests/multithreaded/common/mtt.c, line 9 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJWR24NrNJBZPJ_W-:-MznJWR24NrNJBZPJ_W0:b-gn4e0i) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt.c#L9)):*
> ```C
> 
> #include <assert.h>
> #include <unistd.h>
> ```

Why have you added? Why is it needed?



_Code quote:_
```C
#include <unistd.h>
```
___
*[tests/multithreaded/common/mtt_connect.h, line 34 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJt0y5ykfZwpRJoHu:-MznJt0y5ykfZwpRJoHv:b-3idkjb) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.h#L34)):*
> ```objc
> 		struct rpma_peer **peer_ptr);
> 
> #endif /* MTT_CONNECT_H */
> ```

It has to be always at the end of a header file.



_Code quote:_
```objc
#endif /* MTT_CONNECT_H */
```
___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKL8oEB4jkHJJ0AMP:-MznKL8oEB4jkHJJ0AMQ:b-8skeu7) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
> ```C
>  */
> void *
> malloc_aligned(size_t size)
> ```

It has nothing common with connection. It should stay at `mtt_utils.c` as it was before.



_Code quote:_
```C
 * malloc_aligned -- allocate an aligned chunk of memory
 */
void *
malloc_aligned(size_t size)
```
___
*[tests/multithreaded/mr/CMakeLists.txt, line 18 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKb0NB6oqjYkRwm8e:-MznKb0NB6oqjYkRwm8f:bdp8g43) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/mr/CMakeLists.txt#L18)):*
> ```CMake
> add_multithreaded(NAME mr BIN rpma_mr_remote_from_descriptor
> 	SRCS rpma_mr_remote_from_descriptor.c server_rpma_mr_remote_from_descriptor.c
> 		../common/mtt_connect.c)
> ```

`../common/mtt_connect.c ../common/mtt_utils.c)`



_Code quote:_
```CMake
../common/mtt_connect.c)
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 34 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKqQy-ws-FMXnYrLX:-MznKqQy-ws-FMXnYrLY:b-5ebgcf) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L34)):*
> ```C
> 	struct prestate *pr = (struct prestate *)prestate;
> 
> 	(void) mtt_client_connect(tr, pr->addr, pr->port, &pr->peer,
> ```

The result of `mtt_client_connect` cannot be ignored in this `prestate_init` - if the process of connection fails, the rest will not work ...



_Code quote:_
```C
	(void) mtt_client_connect(tr, pr->addr, pr->port, &pr->peer,
		&pr->conn, &pr->pdata);
```
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 34 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznLZ_z8lyEm2ptJg-m:-MznLZ_z8lyEm2ptJg-n:b-nbkds3) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L34)):*
> ```C
> 	struct rpma_mr_local *mr = NULL;
> 
> 	/* configure logging thresholds to see more details */
> ```

There is a common function for this code.



_Code quote:_
```C
	/* configure logging thresholds to see more details */
	rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_LEVEL_INFO);
	rpma_log_set_threshold(RPMA_LOG_THRESHOLD_AUX, RPMA_LOG_LEVEL_INFO);

	/* lookup an ibv_context via the address */
	if ((ret = rpma_utils_get_ibv_context(addr,
			RPMA_UTIL_IBV_CONTEXT_LOCAL, &ibv_ctx))) {
		SERVER_RPMA_ERR("rpma_utils_get_ibv_context", ret);
		return ret;
	}

	/* create a new peer object */
	if ((ret = rpma_peer_new(ibv_ctx, &peer))) {
		SERVER_RPMA_ERR("rpma_peer_new", ret);
		return ret;
	}

	MTT_PORT_INIT;
	MTT_PORT_SET(port, 0);

	/* start a listening endpoint at addr:port */
	if ((ret = rpma_ep_listen(peer, addr, MTT_PORT_STR, &ep))) {
		SERVER_RPMA_ERR("rpma_ep_listen", ret);
		goto err_peer_delete;
	}
```


<!-- Sent from Reviewable.io -->

2022-04-04 07:13 UTC, grom72 requested changes
> Reviewed 2 of 4 files at r7, 6 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/common/mtt.c, line 9 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJoe3Ev1BLgy7TDSM:-MznJoe4090Dj3nOTmn4:bmke1xc) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt.c#L9)):*
> ```C
> 
> #include <assert.h>
> #include <unistd.h>
> ```

what is the purpose of this include?



_Code quote:_
```C
#include <unistd.h>
```
___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-MznKzB30P9iZbgQ1oBu:bfsovu) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
> ```C
>  */
> void *
> malloc_aligned(size_t size)
> ```

why do not we use ``mtt_malloc_aligned``?



_Code quote:_
```C
malloc_aligned
```


<!-- Sent from Reviewable.io -->

2022-04-04 09:07 UTC, grom72 reviewed
> Reviewed 1 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-04 10:58 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-MzoDI9h7ftscO3e9Ur0:b-xwf88d) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why do not we use ``mtt_malloc_aligned``?
</blockquote></details>

Of course, it should be `mtt_malloc_aligned`


<!-- Sent from Reviewable.io -->

2022-04-04 13:44 UTC, ldorau requested changes
> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 39 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzonoKjEd82_8JutIjt:-MzonoKjEd82_8JutIju:br6g28o) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L39)):*
> ```C
> 	ret = mtt_client_connect(tr, pr->addr, pr->port, &pr->peer,
> 		&pr->conn, &pr->pdata);
> 	if(ret)
> ```

`if (ret)`



_Code quote:_
```C
if(ret)
```
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 64 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzooB9U-zqdrOB0xaZ7:-MzooB9VBGuTC5pXjIet:b-82n56l) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L64)):*
> ```C
> 
> err_conn_disconnect:
> 	(void) rpma_conn_disconnect(pr->conn);
> ```

`mtt_client_err_disconnect`



_Code quote:_
```C
 rpma_conn_disconnect(
```
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 96 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzooTNy6uY8qYEL-s5G:-MzooTNy6uY8qYEL-s5H:bfa0brv) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L96)):*
> ```C
> err_ep_shutdown:
> 	/* shutdown the endpoint */
> 	(void) rpma_ep_shutdown(&ep);
> ```

`mtt_server_shutdown`



_Code quote:_
```C
	/* shutdown the endpoint */
	(void) rpma_ep_shutdown(&ep);


	/* delete the peer object */
	(void) rpma_peer_delete(&peer);
```


<!-- Sent from Reviewable.io -->

2022-04-05 07:58 UTC, grom72 requested changes
> Reviewed 2 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-MzpilxK-GFTwQaShk5p:b-vnuare) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Of course, it should be `mtt_malloc_aligned`
</blockquote></details>

@ldorau  It should not. 
We need either a separate mechanism for  ``mtt_result`` for the child process or just a way to handle ``NULL`` pointer in ``mtt_malloc_aligned``


<!-- Sent from Reviewable.io -->

2022-04-05 08:13 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-MzsltbG61L5nxtGe2Mt:b-c9hzed) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau  It should not. 
We need either a separate mechanism for  ``mtt_result`` for the child process or just a way to handle ``NULL`` pointer in ``mtt_malloc_aligned``

</blockquote></details>

Ah, @grom72 I thought you meant only renaming this `malloc_aligned` to `mtt_malloc_aligned`. I forgot we already have the separate `mtt_malloc_aligned` function ...
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 43 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-Mzslmre9k7ZEtRldYJa:-Mzslmre9k7ZEtRldYJb:b-ar6jot) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L43)):*
> ```C
> 	if (mr_ptr == NULL) {
> 		ret = -1;
> 		goto err_ep_shutdown;
> ```

err_server_shutdown



_Code quote:_
```C
err_ep_shutdown
```
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 96 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzooTNy6uY8qYEL-s5G:-Mzslatv8WdqKRQtP6sm:bkm7hz3) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L96)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`mtt_server_shutdown`
</blockquote></details>

```c
err_server_shutdown:
        mtt_server_shutdown(...)
```


<!-- Sent from Reviewable.io -->

2022-04-05 08:19 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-Mzsn4iD1yzJ9zugJwuN:byw7odu) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, @grom72 I thought you meant only renaming this `malloc_aligned` to `mtt_malloc_aligned`. I forgot we already have the separate `mtt_malloc_aligned` function ...
</blockquote></details>

Yes, I think we need anyhow some synchronization mechanism between the main and child process. We do not have any system mechanism to indicate issues/errors in case of child process failures.


<!-- Sent from Reviewable.io -->

2022-04-05 10:04 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-MztAN-J8eewB1tVFy4V:b-3rb2pn) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Yes, I think we need anyhow some synchronization mechanism between the main and child process. We do not have any system mechanism to indicate issues/errors in case of child process failures.
</blockquote></details>

Having https://github.com/pmem/rpma/pull/1642 we can use the already existing `mtt_malloc_aligned` and get rid of `mtt_utils.c` and `mtt_utils.h`.


<!-- Sent from Reviewable.io -->

2022-04-05 10:36 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-MztHvg0Dp9D5akgFLyN:byeavz6) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Having https://github.com/pmem/rpma/pull/1642 we can use the already existing `mtt_malloc_aligned` and get rid of `mtt_utils.c` and `mtt_utils.h`.
</blockquote></details>

Indicating issues/errors in case of child process failures is a separate problem to be solved in a separate PR.


<!-- Sent from Reviewable.io -->

2022-04-05 11:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-Mzt_w51DPRVlmavRF3B:-Mzt_w52B7ablJIbH3qM:b-ujmq67) (no related file):*
Rebase please

---


<!-- Sent from Reviewable.io -->

2022-04-05 12:00 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-Mzta08eBh9kcv8axdmP:b3cn2ba) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Indicating issues/errors in case of child process failures is a separate problem to be solved in a separate PR.
</blockquote></details>

#1642 has been merged, please use already existing `mtt_malloc_aligned()` and get rid of `mtt_utils.c` and `mtt_utils.h`.


<!-- Sent from Reviewable.io -->

2022-04-05 13:03 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-07 14:32 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-MzoochB0zkU8ruplbnD:-N-3PRKUEcMqV4tXNOTi:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds fail
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1630#-Mzt_w51DPRVlmavRF3B:-N-3PRgVCFlOq602yzNt:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
___
*[tests/multithreaded/common/mtt.c, line 2 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJ6BT7uF9yH0j_LNd:-Mzo-arW3n2KUnYhCujS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt.c#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Copyright 2021-2022`
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 9 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJWR24NrNJBZPJ_W-:-MznqFm8BcAjVdSmrEXx:b935dgi) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt.c#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you added? Why is it needed?
</blockquote></details>

It was needed for malloc_aligned function. Wrong file, sorry. Done.
___
*[tests/multithreaded/common/mtt.c, line 9 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJoe3Ev1BLgy7TDSM:-MznqVNW-YAr4pnjxRkN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt.c#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what is the purpose of this include?
</blockquote></details>

.
___
*[tests/multithreaded/common/mtt_connect.h, line 34 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznJt0y5ykfZwpRJoHu:-Mzo-cE26bcNNnoyy0Nr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.h#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has to be always at the end of a header file.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKL8oEB4jkHJJ0AMP:-Mzo-d6A6dk90x676Zls:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has nothing common with connection. It should stay at `mtt_utils.c` as it was before.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt_connect.c, line 293 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKzB30P9iZbgQ1oBt:-N-3P0tH3MMfdn2FuypO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/common/mtt_connect.c#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

#1642 has been merged, please use already existing `mtt_malloc_aligned()` and get rid of `mtt_utils.c` and `mtt_utils.h`.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/CMakeLists.txt, line 18 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKb0NB6oqjYkRwm8e:-MznvKV5BDLd35xlyAcD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/mr/CMakeLists.txt#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`../common/mtt_connect.c ../common/mtt_utils.c)`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 34 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznKqQy-ws-FMXnYrLX:-Mzny7hwABsAEUKhaIKY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The result of `mtt_client_connect` cannot be ignored in this `prestate_init` - if the process of connection fails, the rest will not work ...
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 39 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzonoKjEd82_8JutIjt:-Mzp1KLo1zQmpXNyztgT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`if (ret)`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 64 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzooB9U-zqdrOB0xaZ7:-Mzp1IMi0Wl5JFl69vVY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`mtt_client_err_disconnect`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 34 at r8](https://reviewable.io/reviews/pmem/rpma/1630#-MznLZ_z8lyEm2ptJg-m:-Mzo-_9t9AftfBjpkipH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2875aec9bd0162f1bd17aa6ab0a1b1278254c5ac/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is a common function for this code.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 43 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-Mzslmre9k7ZEtRldYJa:-N-2t8hcBj3Z36hQ9sPK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

err_server_shutdown
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c, line 96 at r9](https://reviewable.io/reviews/pmem/rpma/1630#-MzooTNy6uY8qYEL-s5G:-Mzp0qpdESEms2r8tikr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/af64f3e2a077bf6f5ab03dedb625c77e84980449/tests/multithreaded/mr/server_rpma_mr_remote_from_descriptor.c#L96)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`mtt_server_shutdown`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 06:25 UTC, ldorau requested changes
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.h, line 36 at r10](https://reviewable.io/reviews/pmem/rpma/1630#-N-6pkVt68r2fhcTCVW2:-N-6pkVt68r2fhcTCVW3:b-bj8uui) ([raw file](https://github.com/pmem/rpma/blob/a88cb446c2461eb688ca61c513f71d12fbedecec/tests/multithreaded/common/mtt_connect.h#L36)):*
> ```objc
> struct common_data {
> 	uint16_t data_offset;	/* user data offset */
> 	uint8_t mr_desc_size;	/* size of mr_desc in descriptors[] */
> ```

Please move it just after `#define DESCRIPTORS_MAX_SIZE 24`



_Code quote:_
```objc
struct common_data {
	uint16_t data_offset;	/* user data offset */
	uint8_t mr_desc_size;	/* size of mr_desc in descriptors[] */
	uint8_t pcfg_desc_size;	/* size of pcfg_desc in descriptors[] */
	/* buffer containing mr_desc and pcfg_desc */
	char descriptors[DESCRIPTORS_MAX_SIZE];
};
```


<!-- Sent from Reviewable.io -->

2022-04-08 07:56 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt_connect.h, line 36 at r10](https://reviewable.io/reviews/pmem/rpma/1630#-N-6pkVt68r2fhcTCVW2:-N-7ABTT5zYhcMU75eX8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a88cb446c2461eb688ca61c513f71d12fbedecec/tests/multithreaded/common/mtt_connect.h#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move it just after `#define DESCRIPTORS_MAX_SIZE 24`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 09:08 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-08 09:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/multithreaded/common/mtt_connect.c, line 10 at r11](https://reviewable.io/reviews/pmem/rpma/1630#-N-7QlsBBlP7MAczzTBR:-N-7QlsBBlP7MAczzTBS:b2q4abi) ([raw file](https://github.com/pmem/rpma/blob/982172c624506e2ab2cd7e5224aa00b0111e2b78/tests/multithreaded/common/mtt_connect.c#L10)):*
> ```C
> #include <stdlib.h>
> #include <librpma.h>
> #include <unistd.h>
> ```

It seems it is not needed now.



_Code quote:_
```C
#include <unistd.h>
```


<!-- Sent from Reviewable.io -->

2022-04-08 10:18 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt_connect.c, line 10 at r11](https://reviewable.io/reviews/pmem/rpma/1630#-N-7QlsBBlP7MAczzTBR:-N-7fhmFBPQ7QU6ObYgo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/982172c624506e2ab2cd7e5224aa00b0111e2b78/tests/multithreaded/common/mtt_connect.c#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems it is not needed now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 12:43 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 80 at r12](https://reviewable.io/reviews/pmem/rpma/1630#-N-8Bg_9EXhmVSIY2sti:-N-8Bg_9EXhmVSIY2stj:b-kpljha) ([raw file](https://github.com/pmem/rpma/blob/11eeabbdb589b1e9d03d17b7c01c479a166ae0d5/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L80)):*
> ```C
> 				dst_data->mr_desc_size, &mr_ptr);
> 
> 	if (ret) {
> ```

Please remove the empty line in between.



_Code quote:_
```C
				dst_data->mr_desc_size, &mr_ptr);

	if (ret) {
```


<!-- Sent from Reviewable.io -->

2022-04-10 22:01 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c, line 80 at r12](https://reviewable.io/reviews/pmem/rpma/1630#-N-8Bg_9EXhmVSIY2sti:-N-KUpry-4Q0P0n_FxXF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/11eeabbdb589b1e9d03d17b7c01c479a166ae0d5/tests/multithreaded/mr/rpma_mr_remote_from_descriptor.c#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please remove the empty line in between.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 07:00 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630#-:-N-MQ5rkClf1ZIe7uTgi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-11 07:44 UTC, grom72 approved these changes
> Reviewed 3 of 7 files at r10, 1 of 1 files at r11, 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-11 11:33 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-11 11:40 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-11 11:40 UTC, merged