examples: add libpmem2 to example 03
pmem/rpma pull request #1631
Opened 2022-03-25 08:59 UTC by haichangsi

2022-03-25 09:00 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-03-25 09:07 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/1631#-Mz-JQRtBbs7LJyX7gyo:-Mz-JQRtBbs7LJyX7gyp:b-o63u9l) ([raw file](https://github.com/pmem/rpma/blob/eb8c78725b6a402014aa0e5b0d4e50a0bb1f0249/examples/03-read-to-persistent/client.c#L158)):*
> ```C
> 						PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 			(void) fprintf("fio: pmem2_config_set_required_store_granularity()"
> 					"failed: %s\n", pmem2_errormsg());
> ```

Please do not break long string messages, but place them as the first token in the line:
```c
			(void) fprintf(
					"fio: pmem2_config_set_required_store_granularity() failed: %s\n",
					pmem2_errormsg());
```



_Code quote:_
```C
			(void) fprintf("fio: pmem2_config_set_required_store_granularity()"
					"failed: %s\n", pmem2_errormsg());
```


<!-- Sent from Reviewable.io -->

2022-03-25 09:22 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1631#-Mz-NY6b060xqntqr3Bi:-Mz-NY6b060xqntqr3Bj:bd5mzuy) ([raw file](https://github.com/pmem/rpma/blob/eb8c78725b6a402014aa0e5b0d4e50a0bb1f0249/examples/03-read-to-persistent/client.c#L157)):*
> ```C
> 		if (pmem2_config_set_required_store_granularity(cfg,
> 						PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 			(void) fprintf("fio: pmem2_config_set_required_store_granularity()"
> ```

It is NOT fio :-D



_Code quote:_
```C
"fio: 
```


<!-- Sent from Reviewable.io -->

2022-03-25 10:04 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[examples/03-read-to-persistent/client.c, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/1631#-Mz-WxcCDCixpXkBulkd:-Mz-WxcCDCixpXkBulke:b6jid0j) ([raw file](https://github.com/pmem/rpma/blob/eb8c78725b6a402014aa0e5b0d4e50a0bb1f0249/examples/03-read-to-persistent/client.c#L173)):*
> ```C
> 		 * At the beginning of the persistent memory, a signature is
> 		 * stored which marks its content as valid. So the length
> 		 * of the mapped memory has to be at least of the length of
> ```

Duplicated code.
Please add pmem_map() and pmem_unmap() functions specific for libpmem and libpmem2 and include only one of them.



_Code quote:_
```C
		/*
		 * At the beginning of the persistent memory, a signature is
		 * stored which marks its content as valid. So the length
		 * of the mapped memory has to be at least of the length of
		 * the signature to convey any meaningful content and be usable
		 * as a persistent store.
		 */
		if (mr_size < SIGNATURE_LEN) {
			(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
					path, mr_size, SIGNATURE_LEN);
			goto err_map_delete;
		}
		data_offset = SIGNATURE_LEN;

		/*
		 * The space under the offset is intended for storing the hello
		 * structure. So the total space is assumed to be at least
		 * 1 KiB + offset of the string contents.
		 */
		if (mr_size - data_offset < sizeof(struct hello_t)) {
			fprintf(stderr, "%s too small (%zu < %zu)\n",
					path, mr_size, sizeof(struct hello_t));
			goto err_map_delete;
		}

		hello = (struct hello_t *)((uintptr_t)mr_ptr + data_offset);

		/* Get libpmem2 persist function from pmem2_map */
		persist = pmem2_get_persist_fn(map);

		/*
		 * If the signature is not in place the persistent content has
		 * to be initialized and persisted.
		 */
		if (strncmp(mr_ptr, SIGNATURE_STR, SIGNATURE_LEN) != 0) {
			/* write an initial value and persist it */
			write_hello_str(hello, en);
			persist(hello, sizeof(struct hello_t));
			/* write the signature to mark the content as valid */
			memcpy(mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
			persist(mr_ptr, SIGNATURE_LEN);
		}
```


<!-- Sent from Reviewable.io -->

2022-03-28 10:20 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzF0oiy58I8SF1iBq_G:-MzF0oiy58I8SF1iBq_H:brnw24o) (no related file):*
Shall we follow a similar solution template used for fio with persist function pointer?

Shall we organize `ifdef`s in the following way:

```
#ifdef USE_LIBPMEM
/* common part for libpmem and libpmem2 */
#ifdef USE_LIBPMEM2
/* private pmem2 part */
#else
/* private pmem part */
#endif
#else
/* non pmem part if needed */
#endif
```

---


<!-- Sent from Reviewable.io -->

2022-03-28 10:52 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-03-29 12:22 UTC, ldorau requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[examples/03-read-to-persistent/client.c, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbhzz5eq8YcFWq4jo:-MzKbhzz5eq8YcFWq4jp:brdwt3q) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client.c#L149)):*
> ```C
> 	 */
> 	translate(hello);
> #ifdef USE_LIBPMEM2
> ```

Do it like in fio, please - no ifdef around persist.



_Code quote:_
```C
#ifdef USE_LIBPMEM2
		mem->persist(hello, sizeof(struct hello_t));
#elif USE_LIBPMEM
	if (*mem->is_pmem) {
		pmem_persist(hello, sizeof(struct hello_t));
	}
#endif
```
___
*[examples/03-read-to-persistent/client.c, line 168 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbZk813gyVkmdFjcS:-MzKbZk813gyVkmdFjcT:b-9d8rty) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client.c#L168)):*
> ```C
> 
> err_free:
> #ifdef USE_LIBPMEM
> ```

`pmem_unmap` should be different for libpmem2



_Code quote:_
```C
#ifdef USE_LIBPMEM
	if (*mem->is_pmem) {
		pmem_unmap(mr_ptr, mr_size);
		mr_ptr = NULL;
	}
#endif
```
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbupl3D-NKN95YnsL:-MzKbupl3D-NKN95YnsM:b-s112eh) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem2_map_file.h#L66)):*
> ```objc
> 		mem->mr_ptr = pmem2_map_get_address(map);
> 
> 		/*
> ```

Still duplicated code.



_Code quote:_
```objc
		/*
		 * At the beginning of the persistent memory, a signature is
		 * stored which marks its content as valid. So the length
		 * of the mapped memory has to be at least of the length of
		 * the signature to convey any meaningful content and be usable
		 * as a persistent store.
		 */
		if (mem->mr_size < SIGNATURE_LEN) {
			(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
					path, mem->mr_size, SIGNATURE_LEN);
			goto err_map_delete;
		}
		*mem->data_offset = SIGNATURE_LEN;

		/*
		 * The space under the offset is intended for storing the hello
		 * structure. So the total space is assumed to be at least
		 * 1 KiB + offset of the string contents.
		 */
		if (
		*mem->mr_size - *mem->data_offset < sizeof(struct hello_t)) {
			fprintf(stderr, "%s too small (%zu < %zu)\n", path,
				*mem->mr_size, sizeof(struct hello_t));
			goto err_map_delete;
		}

		mem->hello = (struct hello_t *)
				((uintptr_t)mem->mr_ptr + *mem->data_offset);

		/* Get libpmem2 persist function from pmem2_map */
		persist = pmem2_get_persist_fn(map);
		mem->persist = persist;

		/*
		 * If the signature is not in place the persistent content has
		 * to be initialized and persisted.
		 */
		if (strncmp(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN) != 0) {
			/* write an initial value and persist it */
			write_hello_str(mem->hello, en);
			persist(mem->hello, sizeof(struct hello_t));
			/* write the signature to mark the content as valid */
			memcpy(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
			persist(mem->mr_ptr, SIGNATURE_LEN);
		}
```
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbzRAC31Vd2IqViss:-MzKbzRAC31Vd2IqVist:b-s112eh) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem_map_file.h#L43)):*
> ```objc
> 		*mem->is_pmem = is_pmem;
> 
> 		/*
> ```

Still duplicated code.



_Code quote:_
```objc
		/*
		 * At the beginning of the persistent memory, a signature is
		 * stored which marks its content as valid. So the length
		 * of the mapped memory has to be at least of the length of
		 * the signature to convey any meaningful content and be usable
		 * as a persistent store.
		 */
		if (*mem->mr_size < SIGNATURE_LEN) {
			(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
					path, *mem->mr_size, SIGNATURE_LEN);
			(void) pmem_unmap(mem->mr_ptr, *mem->mr_size);
			return -1;
		}
		*mem->data_offset = SIGNATURE_LEN;

		/*
		 * The space under the offset is intended for storing the hello
		 * structure. So the total space is assumed to be at least
		 * 1 KiB + offset of the string contents.
		 */
		if (
		*mem->mr_size - *mem->data_offset < sizeof(struct hello_t)) {
			fprintf(stderr, "%s too small (%zu < %zu)\n",
				path, *mem->mr_size, sizeof(struct hello_t));
			(void) pmem_unmap(mem->mr_ptr, *mem->mr_size);
			return -1;
		}

		mem->hello = (struct hello_t *)
				((uintptr_t)mem->mr_ptr + *mem->data_offset);

		/*
		 * If the signature is not in place the persistent content has
		 * to be initialized and persisted.
		 */
		if (strncmp(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN) != 0) {
			/* write an initial value and persist it */
			write_hello_str(mem->hello, en);
			pmem_persist(mem->hello, sizeof(struct hello_t));
			/* write the signature to mark the content as valid */
			memcpy(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
			pmem_persist(mem->mr_ptr, SIGNATURE_LEN);
		}
```


<!-- Sent from Reviewable.io -->

2022-03-29 12:22 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-MzKcDGeDRhmvKE7xL7H:b-gvf1ra) (no related file):*
Builds fail.

---


<!-- Sent from Reviewable.io -->

2022-03-29 12:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi)

___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcdQx5HGq7fhxn5fL:-MzKcdQx5HGq7fhxn5fM:b23lxp7) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem2_map_file.h#L51)):*
> ```objc
> 				PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 			(void) fprintf(stderr,
> 				"pmem2_config_set_required_store_granularity()failed: %s\n",
> ```

`() failed`- a space is missing



_Code quote:_
```objc
()failed
```


<!-- Sent from Reviewable.io -->

2022-03-29 12:27 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbupl3D-NKN95YnsL:-MzKd6Re6FVGS3ZwF1Sb:bty72n6) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem2_map_file.h#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Still duplicated code.
</blockquote></details>

This part of code should be left in client.c.
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbzRAC31Vd2IqViss:-MzKdAmm-2MzDrZnQA24:bty72n6) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem_map_file.h#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Still duplicated code.
</blockquote></details>

This part of code should be left in client.c.


<!-- Sent from Reviewable.io -->

2022-04-10 21:52 UTC, haichangsi reviewed
This is only a part for the client, after the approval I am gonna push the second part for server. I plan on moving client_pmem_map_file in the pr including adding similar changes to other examples.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631#-:-N-KSP13-BfNuOQ7jsx_:b-nppofc)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzF0oiy58I8SF1iBq_G:-N-KRqw361H-mkXk4X6O:b-b861dn) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we follow a similar solution template used for fio with persist function pointer?

Shall we organize `ifdef`s in the following way:

```
#ifdef USE_LIBPMEM
/* common part for libpmem and libpmem2 */
#ifdef USE_LIBPMEM2
/* private pmem2 part */
#else
/* private pmem part */
#endif
#else
/* non pmem part if needed */
#endif
```

</blockquote></details>

Tell me what do you think about the option I pushed if it is wrong I will change it. Thanks.

---
___
*[examples/03-read-to-persistent/client.c, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbhzz5eq8YcFWq4jo:-N-KSNNC3cMRZXy7Xz1i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client.c#L149)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do it like in fio, please - no ifdef around persist.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 168 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbZk813gyVkmdFjcS:-N-KSG8ICr_IifrkhpyQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client.c#L168)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`pmem_unmap` should be different for libpmem2
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcdQx5HGq7fhxn5fL:-N-KSHGj12x1X7iL855n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem2_map_file.h#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`() failed`- a space is missing
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbupl3D-NKN95YnsL:-N-KSIGc3XXK94aEL84P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem2_map_file.h#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This part of code should be left in client.c.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1631#-MzKbzRAC31Vd2IqViss:-N-KRpbA18-fkJ2rCK8v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6075a09834832437dadf2a09f3e18e3d0840987/examples/03-read-to-persistent/client_pmem_map_file.h#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This part of code should be left in client.c.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 11:45 UTC, grom72 requested changes
> Reviewed 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1631#-N-NQN8B8o36v0JQLSj4:-N-NQN8B8o36v0JQLSj5:b-upzjla) ([raw file](https://github.com/pmem/rpma/blob/4756a49f51b44770916c0fde28a3ea07f829f11b/examples/03-read-to-persistent/client.c#L17)):*
> ```C
> 
> 
> #ifdef USE_LIBPMEM2
> ```

```
#ifdef USE_LIBPMEM2
#include "client_pmem2_map_file.h"
#define USE_PMEM 1
#elif USE_LIBPMEM
#include "client_pmem_map_file.h"
#define USE_PMEM 1
#esle 
#undef USE_PMEM 
#endif /* USE_LIBPMEM2 */

#ifdef USE_PMEM
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
#else
#define USAGE_STR "usage: %s <server_address> <port>\n"
#endif /* USE_PMEM */
```
Use ``#ifdef USE_PMEM`` instead of  ``#if defined USE_LIBPMEM2 || defined USE_LIBPMEM`` in the rest of the file



_Code quote:_
```C
#ifdef USE_LIBPMEM2
#include <libpmem2.h>
#include "client_pmem2_map_file.h"
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
#elif USE_LIBPMEM
#include <libpmem.h>
#include "client_pmem_map_file.h"
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
#else
#define USAGE_STR "usage: %s <server_address> <port>\n"
#endif /* USE_LIBPMEM */
```
___
*[examples/03-read-to-persistent/client.c, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1631#-N-NPOAwDC8zMCDjmC2P:-N-NPOAwDC8zMCDjmC2Q:b-xk3ww3) ([raw file](https://github.com/pmem/rpma/blob/4756a49f51b44770916c0fde28a3ea07f829f11b/examples/03-read-to-persistent/client.c#L18)):*
> ```C
> 
> #ifdef USE_LIBPMEM2
> #include <libpmem2.h>
> ```

redundant #include



_Code quote:_
```C
#include <libpmem2.h>
```
___
*[examples/03-read-to-persistent/client.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1631#-N-NPSYc1_BSsDHIia5B:-N-NPSYc1_BSsDHIia5C:b-xk3ww3) ([raw file](https://github.com/pmem/rpma/blob/4756a49f51b44770916c0fde28a3ea07f829f11b/examples/03-read-to-persistent/client.c#L22)):*
> ```C
> #define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
> #elif USE_LIBPMEM
> #include <libpmem.h>
> ```

redundant #include



_Code quote:_
```C
#include <libpmem.h>
```


<!-- Sent from Reviewable.io -->

2022-04-13 05:14 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-21 07:18 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-21 08:19 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 2 of 5 files reviewed, 9 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[examples/03-read-to-persistent/client.c, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AB2A9E453CIJUr_a2:-N0AB2A9E453CIJUr_a3:b-w4f7rw) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L68)):*
> ```C
> 
> 	/* resources - memory region */
> 	void *mr_ptr = NULL;
> ```

You can just define `struct example_mem mem;` here instead of these 3 lines and use `mem` always and everywhere.
You will not have to have pointers inside `mem` then.



_Code quote:_
```C
	void *mr_ptr = NULL;
	size_t mr_size = 0;
	size_t data_offset = 0;
```


<!-- Sent from Reviewable.io -->

2022-04-21 08:20 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 2 of 5 files reviewed, 11 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[examples/03-read-to-persistent/client.c, line 95 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ACHE746tH4rCPxYzI:-N0ACHE746tH4rCPxYzJ:b6tr03q) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L95)):*
> ```C
> 		(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
> 				path, *mem.mr_size, SIGNATURE_LEN);
> 		goto err_free;
> ```

`ret = -1;` is missing here



_Code quote:_
```C
		(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
				path, *mem.mr_size, SIGNATURE_LEN);
		goto err_free;
```
___
*[examples/03-read-to-persistent/client.c, line 107 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ACNw70I-157hRTWhE:-N0ACNw70I-157hRTWhF:b6tr03q) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L107)):*
> ```C
> 	*mem.mr_size - *mem.data_offset < sizeof(struct hello_t)) {
> 		fprintf(stderr, "%s too small (%zu < %zu)\n", path,
> 			*mem.mr_size, sizeof(struct hello_t));
> ```

`ret = -1;` is missing here



_Code quote:_
```C
		fprintf(stderr, "%s too small (%zu < %zu)\n", path,
			*mem.mr_size, sizeof(struct hello_t));
		goto err_free;
```


<!-- Sent from Reviewable.io -->

2022-04-21 08:27 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 2 of 5 files reviewed, 19 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADY9NBSVV904gsfoI:-N0ADY9NBSVV904gsfoJ:bnrqyqe) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L5)):*
> ```objc
> 
> /*
>  * client_pmem2_map_file.c -- a function to map PMem using libpmem2
> ```

It really should be *.c file - please rename it.



_Code quote:_
```objc
client_pmem2_map_file.c 
```
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADel67QDTrty8RWkB:-N0ADel67QDTrty8RWkC:b1ndbbq) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L21)):*
> ```objc
> #include "hello.h"
> 
> static int client_pmem_map_file(char *path, int argc,
> ```

We use the following coding style everywhere:
```c
static int
client_pmem_map_file(char *path, int argc, struct example_mem *mem)
```



_Code quote:_
```objc
static int client_pmem_map_file(char *path, int argc,
			struct example_mem *mem)
```
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ACed9DaSFpNFFUkkm:-N0ACed9DaSFpNFFUkkn:bz2ns0m) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L30)):*
> ```objc
> 	pmem2_persist_fn persist;
> 
> 	if (argc >= 4) {
> ```

Where does this `if` ends? Please check indentation.



_Code quote:_
```objc
if (argc >= 4) {
```
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 80 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AD6640kBTWEFaq-gs:-N0AD6640kBTWEFaq-gt:b4xrp75) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L80)):*
> ```objc
> 
> err_map_delete:
> 		pmem2_map_delete(&map);
> ```

Wrong indentation



_Code quote:_
```objc
err_map_delete:
		pmem2_map_delete(&map);
err_config_delete:
		pmem2_config_delete(&cfg);
err_source_delete:
		pmem2_source_delete(&src);
err_close:
		close(fd);

		return -1;
```
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 91 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADu-r9TfXBhq_QV8h:-N0ADu-r9TfXBhq_QV8i:bfoxbxp) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L91)):*
> ```objc
> }
> 
> static void client_pmem_unmap_file(struct example_mem *mem)
> ```

```c
static void
client_pmem_unmap_file(struct example_mem *mem)
```



_Code quote:_
```objc
static void client_pmem_unmap_file(struct example_mem *mem)
```
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADQj_0LCDyMZTv9O5:-N0ADQj_0LCDyMZTv9O6:bnrqyqe) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem_map_file.h#L5)):*
> ```objc
> 
> /*
>  * client_pmem_map_file.c -- a function to map PMem using libpmem
> ```

It really should be *.c file - please rename it.



_Code quote:_
```objc
client_pmem_map_file.c
```
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 18 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADGVr2U8JSyJ-o50X:-N0ADGVr2U8JSyJ-o50Y:b1ndbbq) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem_map_file.h#L18)):*
> ```objc
> #include "hello.h"
> 
> static int client_pmem_map_file(char *path, int argc,
> ```

We use the following coding style everywhere:
```c
static int
client_pmem_map_file(char *path, int argc, struct example_mem *mem)
```



_Code quote:_
```objc
static int client_pmem_map_file(char *path, int argc,
			struct example_mem *mem)
```
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 48 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADznH1_IhlqLmk0li:-N0ADznH1_IhlqLmk0lj:bfoxbxp) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem_map_file.h#L48)):*
> ```objc
> }
> 
> static void client_pmem_unmap_file(struct example_mem *mem)
> ```

```c
static void
client_pmem_unmap_file(struct example_mem *mem)
```



_Code quote:_
```objc
static void client_pmem_unmap_file(struct example_mem *mem)
```


<!-- Sent from Reviewable.io -->

2022-04-21 08:34 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 2 of 5 files reviewed, 20 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[examples/03-read-to-persistent/client.c, line 105 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AFSgi2bGjhakUTxif:-N0AFSgi2bGjhakUTxig:batv3ox) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L105)):*
> ```C
> 	 */
> 	if (
> 	*mem.mr_size - *mem.data_offset < sizeof(struct hello_t)) {
> ```

wrong indentation



_Code quote:_
```C
	if (
	*mem.mr_size - *mem.data_offset < sizeof(struct hello_t)) {
```


<!-- Sent from Reviewable.io -->

2022-04-22 21:11 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 1 of 7 files reviewed, 20 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1631#-N-NQN8B8o36v0JQLSj4:-N0I4lvo7JqdemCPPYb9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4756a49f51b44770916c0fde28a3ea07f829f11b/examples/03-read-to-persistent/client.c#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
#ifdef USE_LIBPMEM2
#include "client_pmem2_map_file.h"
#define USE_PMEM 1
#elif USE_LIBPMEM
#include "client_pmem_map_file.h"
#define USE_PMEM 1
#esle 
#undef USE_PMEM 
#endif /* USE_LIBPMEM2 */

#ifdef USE_PMEM
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
#else
#define USAGE_STR "usage: %s <server_address> <port>\n"
#endif /* USE_PMEM */
```
Use ``#ifdef USE_PMEM`` instead of  ``#if defined USE_LIBPMEM2 || defined USE_LIBPMEM`` in the rest of the file
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1631#-N-NPOAwDC8zMCDjmC2P:-N0-vxx8Cga9SH1zHOlc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4756a49f51b44770916c0fde28a3ea07f829f11b/examples/03-read-to-persistent/client.c#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant #include
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1631#-N-NPSYc1_BSsDHIia5B:-N0-vyHG0wbGBc1_1BaI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4756a49f51b44770916c0fde28a3ea07f829f11b/examples/03-read-to-persistent/client.c#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant #include
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AB2A9E453CIJUr_a2:-N0DFMOKCnE_Ge-1YGXK:b-adp02q) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L68)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You can just define `struct example_mem mem;` here instead of these 3 lines and use `mem` always and everywhere.
You will not have to have pointers inside `mem` then.
</blockquote></details>

As you suggested some time ago I wanted to make one shared structure for every client in every example, same situation for every server.
___
*[examples/03-read-to-persistent/client.c, line 95 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ACHE746tH4rCPxYzI:-N0DFeMnAIVw0fMERqHa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L95)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`ret = -1;` is missing here
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 105 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AFSgi2bGjhakUTxif:-N0DGVoo1Qh8YrGhXcH4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L105)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 107 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ACNw70I-157hRTWhE:-N0DGWPV36UQnBmTwWaZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`ret = -1;` is missing here
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADY9NBSVV904gsfoI:-N0I4nqc8fNnCajZDNac:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It really should be *.c file - please rename it.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADel67QDTrty8RWkB:-N0DH8WW8uD8olexcAL0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use the following coding style everywhere:
```c
static int
client_pmem_map_file(char *path, int argc, struct example_mem *mem)
```

</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ACed9DaSFpNFFUkkm:-N0DHDMsEmKVz4GvNJUt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Where does this `if` ends? Please check indentation.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 80 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AD6640kBTWEFaq-gs:-N0DHLiEAlKDkzF8Prbc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wrong indentation
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem2_map_file.h, line 91 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADu-r9TfXBhq_QV8h:-N0DHMvW6Xd2yQweeXWO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem2_map_file.h#L91)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
static void
client_pmem_unmap_file(struct example_mem *mem)
```
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADQj_0LCDyMZTv9O5:-N0I4oa0AtqOW__llJ-v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem_map_file.h#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It really should be *.c file - please rename it.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 18 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADGVr2U8JSyJ-o50X:-N0DHU9o-RIVOH76hQen:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem_map_file.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use the following coding style everywhere:
```c
static int
client_pmem_map_file(char *path, int argc, struct example_mem *mem)
```

</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client_pmem_map_file.h, line 48 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0ADznH1_IhlqLmk0li:-N0DHUxM6pdbtxmCJZ39:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client_pmem_map_file.h#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockq [...]

2022-04-22 21:13 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 1 of 7 files reviewed, 20 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0AB2A9E453CIJUr_a2:-N0I6VoD5rW_Poem6Dk4:bu9typo) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/03-read-to-persistent/client.c#L68)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

As you suggested some time ago I wanted to make one shared structure for every client in every example, same situation for every server.
</blockquote></details>

You meant initialize, that is an old comment, sorry. Done.
___
*[examples/common/common-example.h, line 20 at r5](https://reviewable.io/reviews/pmem/rpma/1631#-N0A9d1W1q1nN6YsvAgN:-N0I6fpT-ZuBWdrHxLUH:b8qulmr) ([raw file](https://github.com/pmem/rpma/blob/3f9ac4265a6798d8bee382a8bf2e1da578f0747f/examples/common/common-example.h#L20)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

> As you suggested some time ago I wanted to make one shared structure for every client in every example, same situation for every server.
It was the easiest way for m

</blockquote></details>

Also old comment, sorry. Done.


<!-- Sent from Reviewable.io -->

2022-04-23 11:44 UTC, grom72 requested changes
> Reviewed 2 of 6 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 4 of 7 files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0LDLeICKZjxAEzXEtA:-N0LDLeJ3ncaFmaW2bVl:bqhno8i) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client.c#L17)):*
> ```C
> #include "hello.h"
> 
> #if defined USE_LIBPMEM2 || USE_LIBPMEM
> ```

Now we can move this 
``#define USE_PMEM 1``
to  ``"client_pmem_map_file.h"``



_Code quote:_
```C
#if defined USE_LIBPMEM2 || USE_LIBPMEM
#define USE_PMEM 1
#else
#undef USE_PMEM
#endif /* USE_LIBPMEM2 */
```


<!-- Sent from Reviewable.io -->

2022-04-23 11:45 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 5 of 7 files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-25 13:46 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 5 of 7 files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/03-read-to-persistent/client_pmem_map_file.c` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0Vww6l-ohxihHk4FFX:-N0Vww6l-ohxihHk4FFY:bpc0l00) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.c#L15)):*
> ```C
> #include "common-conn.h"
> #include "client_pmem_map_file.h"
> #include "hello.h"
> ```

You have to test all three possible configurations:

```
In file included from rpma/examples/03-read-to-persistent/client_pmem_map_file.c:15:
rpma/examples/common/hello.h:24:20: error: ‘hello_str’ defined but not used [-Werror=unused-variable]
   24 | static const char *hello_str[] = {
      |                    ^~~~~~~~~
```



_Code quote:_
```C
#include "hello.h"
```


<!-- Sent from Reviewable.io -->

2022-04-25 14:03 UTC, ldorau requested changes
> Reviewed 4 of 6 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/CMakeLists.txt` line 113 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0W0vS3DKsMetE1jiXs:-N0W0vS3DKsMetE1jiXt:b-aw2zsr) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/CMakeLists.txt#L113)):*
> ```CMake
> add_example(NAME 03-read-to-persistent BIN server USE_LIBIBVERBS USE_LIBPMEM_IF_FOUND
> 	SRCS 03-read-to-persistent/server.c common/common-conn.c)
> if (LIBPMEM2_FOUND)
> ```

You have to test all these three possible configurations separately - to check if they build correctly.



_Code quote:_
```CMake
if (LIBPMEM2_FOUND)
	add_example(NAME 03-read-to-persistent BIN client USE_LIBPMEM_IF_FOUND
		SRCS 03-read-to-persistent/client.c common/common-conn.c
		03-read-to-persistent/client_pmem2_map_file.c)
elseif(LIBPMEM_FOUND)
	add_example(NAME 03-read-to-persistent BIN client USE_LIBPMEM_IF_FOUND
		SRCS 03-read-to-persistent/client.c common/common-conn.c
		03-read-to-persistent/client_pmem_map_file.c)
else()
	add_example(NAME 03-read-to-persistent BIN client USE_LIBPMEM_IF_FOUND
		SRCS 03-read-to-persistent/client.c common/common-conn.c)
endif()
```
___
*[`examples/03-read-to-persistent/client_pmem_map_file.h` line 13 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0W0a-e0uzFJYXT2DI4:-N0W0a-e0uzFJYXT2DI5:b-yjm9ay) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.h#L13)):*
> ```objc
> #include "common-example.h"
> 
> int
> ```

It should be in one line in header files.



_Code quote:_
```objc
int
client_pmem_map_file(char *path, int argc, struct example_mem *mem);
```
___
*[`examples/03-read-to-persistent/client_pmem_map_file.h` line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0W0fdY-gL4aS4__SoN:-N0W0fdY-gL4aS4__SoO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.h#L17)):*
> ```objc
> 
> void
> client_pmem_unmap_file(struct example_mem *mem);
> ```

.



_Code quote:_
```objc
void
client_pmem_unmap_file(struct example_mem *mem);
```


<!-- Sent from Reviewable.io -->

2022-04-26 08:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/03-read-to-persistent/client_pmem_map_file.c` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0Vww6l-ohxihHk4FFX:-N0Zz9fO6I1VA1pj2cyr:bhf5cwn) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.c#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You have to test all three possible configurations:

```
In file included from rpma/examples/03-read-to-persistent/client_pmem_map_file.c:15:
rpma/examples/common/hello.h:24:20: error: ‘hello_str’ defined but not used [-Werror=unused-variable]
   24 | static const char *hello_str[] = {
      |                    ^~~~~~~~~
```
</blockquote></details>

@haichangsi please just remove `#include "hello.h"`



_Code quote:_
```C
#include "hello.h"
```


<!-- Sent from Reviewable.io -->

2022-04-26 12:44 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/03-read-to-persistent/client.c` line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0LDLeICKZjxAEzXEtA:-N0_VvcK6poPAqfnAGFV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client.c#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Now we can move this 
``#define USE_PMEM 1``
to  ``"client_pmem_map_file.h"``
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/client_pmem_map_file.h` line 13 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0W0a-e0uzFJYXT2DI4:-N0_VwXG1C_YoydrJzF8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.h#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be in one line in header files.
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/client_pmem_map_file.h` line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0W0fdY-gL4aS4__SoN:-N0_Vx8b84Je5o1Tk8EE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/client_pmem_map_file.c` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1631#-N0Vww6l-ohxihHk4FFX:-N0_W5Uz5tgtlw4LXSRt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2b3396682f38fa97c0665ac6fd46b159a83888ae/examples/03-read-to-persistent/client_pmem_map_file.c#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi please just remove `#include "hello.h"`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-26 12:49 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-26 12:54 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-N0_viXT-9AFM22F4Y9F:bkrzoul) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds fail.
</blockquote></details>

@haichangsi please verify corectness of `examples/03-read-to-persistent/CMakeLists.txt`
The **standalone** `compilation of example: 03-read-to-persistent` failed

---


<!-- Sent from Reviewable.io -->

2022-04-26 18:59 UTC, grom72 requested changes
> Reviewed 1 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[`examples/common/common-conn.h` line 13 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bDp60E0LdYfZsDRvq:-N0bDp60E0LdYfZsDRvr:b-vnmcwb) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-conn.h#L13)):*
> ```objc
> #include <string.h>
> #include <librpma.h>
> ```

#include "client_pmem_map_file.h" /* for USE_PMEM */



_Code quote (from examples/03-read-to-persistent/client_pmem_map_file.c):_
```C
#include "client_pmem_map_file.h"
```
___
*[`examples/common/common-conn.h` line 14 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bD99F-BJFr0c7G1_d:-N0bD99F-BJFr0c7G1_e:b-78jpif) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-conn.h#L14)):*
> ```objc
> #include <librpma.h>
> 
> #if defined USE_LIBPMEM || USE_LIBPMEM2
> ```

``#if defined USE_PMEM``



_Suggestion:_
```objc
#if defined USE_LIBPMEM || USE_LIBPMEM2
```
___
*[`examples/common/common-example.h` line 5 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bEIueCt3qpsevVXkG:-N0bEIueCt3qpsevVXkH:bbhv2k9) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-example.h#L5)):*
> ```objc
> 
> /*
>  * common-example.h -- a common structure used for mapping PMem for examples
> ```

@ldorau  would it be better to use "main" structure name as file name: ``example_mem.h``



_Code quote:_
```objc
common-example.h
```


<!-- Sent from Reviewable.io -->

2022-04-27 08:06 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/common/common-conn.h` line 13 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bDp60E0LdYfZsDRvq:-N0e17gB4SG_cwUagtB0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-conn.h#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

#include "client_pmem_map_file.h" /* for USE_PMEM */
</blockquote></details>

Done.
___
*[`examples/common/common-conn.h` line 14 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bD99F-BJFr0c7G1_d:-N0e18A3AoD1mL0YHYJV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-conn.h#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``#if defined USE_PMEM``
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 10:00 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/common/common-example.h` line 5 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bEIueCt3qpsevVXkG:-N0eSXkK7894b6jSTV9W:bedo6ib) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-example.h#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau  would it be better to use "main" structure name as file name: ``example_mem.h``
</blockquote></details>

I would name it `common-pmem.h`, because it is "*a common structure used for mapping PMem for examples*".


<!-- Sent from Reviewable.io -->

2022-04-29 13:30 UTC, grom72 reviewed
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-05 11:13 UTC, grom72 requested changes
> Reviewed 1 of 3 files at r8, 7 of 7 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 44 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IvDWlBQojKS90iBeC:-N1IvDWlBQojKS90iBeD:undefined) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/03-read-to-persistent/CMakeLists.txt#L44)):*
> ```CMake
> 		set(srcs ${srcs} ../common/client_pmem2_map_file.c)
> 	elseif (LIBPMEM_FOUND)
> 		set(srcs ${srcs} ../common/client_pmem2_map_file.c)
> ```





_Suggestion:_
```CMake
set(srcs ${srcs} ../common/client_pmem_map_file.c)
```
___
*[`examples/common/common-conn.h` line 18 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IudwC-2jkJBkWDtgF:-N1IudwC-2jkJBkWDtgG:undefined) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L18)):*
> ```objc
> #else
> #undef USE_PMEM
> #endif /* USE_LIBPMEM2 */
> ```





_Suggestion:_
```objc
#endif /* USE_LIBPMEM2 || USE_LIBPMEM */
```


<!-- Sent from Reviewable.io -->

2022-05-05 11:19 UTC, ldorau requested changes
> Reviewed 5 of 7 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/common/common-conn.h` line 15 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IsrpJDg4E1y2a54Eh:-N1IsrpKDYKC046OvaBx:b-gzp5y4) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L15)):*
> ```objc
> 
> #if defined USE_LIBPMEM2 || USE_LIBPMEM
> #define USE_PMEM 1
> ```

Why isn't it located in `common-pmem.h`?



_Code quote:_
```objc
#if defined USE_LIBPMEM2 || USE_LIBPMEM
#define USE_PMEM 1
#else
#undef USE_PMEM
#endif /* USE_LIBPMEM2 */
```


<!-- Sent from Reviewable.io -->

2022-05-05 11:19 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 66 at r10](https://reviewable.io/reviews/pmem/rpma/1631#-N0fImllECbsqUAhhuuU:-N1IrhNE7tf3TAYADVOm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b3f0c60b2fccb58a7f3fa935a8ae66b353c03d6/examples/03-read-to-persistent/CMakeLists.txt#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move it to `add_example`, please
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 44 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IvDWlBQojKS90iBeC:-N1IwIsSCFgs5vsT5Wbd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/03-read-to-persistent/CMakeLists.txt#L44)):*
> ```CMake
> 		set(srcs ${srcs} ../common/client_pmem2_map_file.c)
> 	elseif (LIBPMEM_FOUND)
> 		set(srcs ${srcs} ../common/client_pmem2_map_file.c)
> ```

Done.
___
*[`examples/common/common-conn.h` line 18 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IudwC-2jkJBkWDtgF:-N1IwZRg2uKT_oQGnifc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L18)):*
> ```objc
> #else
> #undef USE_PMEM
> #endif /* USE_LIBPMEM2 */
> ```

Done.
___
*[`examples/common/common-example.h` line 5 at r8](https://reviewable.io/reviews/pmem/rpma/1631#-N0bEIueCt3qpsevVXkG:-N1Irdsn2G8SF5cOgRu0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9832727eb5880fd2c25a8c9a79d84a0192692f64/examples/common/common-example.h#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-05 11:22 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`examples/common/common-conn.h` line 15 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IsrpJDg4E1y2a54Eh:-N1Iwk0x0ayZjhgSQXmY:bbixcou) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why isn't it located in `common-pmem.h`?
</blockquote></details>

There was a problem with redefinition, @osalyk  suggested moving #define SIGNATURE_STR "RPMA_EXAMPLE_SIG"
#define SIGNATURE_LEN (strlen(SIGNATURE_STR) + 1) outside #ifdef USE_PMEM but before my changes it was also in #ifdef so I decided to check out another way of handling this issue, is it wrong?


<!-- Sent from Reviewable.io -->

2022-05-05 11:22 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-05 11:22 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 5 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-05 11:23 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`examples/common/common-conn.h` line 15 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IsrpJDg4E1y2a54Eh:-N1IxU9_9KPzlsFYquoS:b5debln) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L15)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

There was a problem with redefinition, @osalyk  suggested moving #define SIGNATURE_STR "RPMA_EXAMPLE_SIG"
#define SIGNATURE_LEN (strlen(SIGNATURE_STR) + 1) outside #ifdef USE_PMEM but before my changes it was also in #ifdef so I decided to check out another way of handling this issue, is it wrong?
</blockquote></details>

It is pmem-specific, so it should be located in `common-pmem.h`


<!-- Sent from Reviewable.io -->

2022-05-05 11:28 UTC, grom72 requested changes
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`examples/common/common-conn.h` line 15 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IsrpJDg4E1y2a54Eh:-N1IxuJS-l6jd6LBglXc:b-runkad) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is pmem-specific, so it should be located in `common-pmem.h`
</blockquote></details>

@haichangsi it is enough to ensure that ``common-pmem.h`` is included before ``common-conn.h``



_Code quote:_
```objc
#define SIGNATURE_STR "RPMA_EXAMPLE_SIG"
#define SIGNATURE_LEN (strlen(SIGNATURE_STR) + 1)
```
___
*[`examples/common/common-pmem.h` line 10 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IyMhW6pNphwwzdi3P:-N1IyMhW6pNphwwzdi3Q:undefined) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-pmem.h#L10)):*
> ```objc
> #include <stddef.h>
> 
> #ifdef USE_LIBPMEM2
> ```





_Suggestion:_
```objc
#ifdef USE_LIBPMEM2
#include <libpmem2.h>
#define USE_PMEM 1
#elif USE_LIBPMEM
#include <libpmem.h>
#define USE_PMEM 1
#else
#ifdef USE_PMEM
#undef USE_PMEM
#endif /* USE_PMEM */
#endif /* USE_LIBPMEM2 */
```


<!-- Sent from Reviewable.io -->

2022-05-05 11:33 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 7 of 8 files reviewed, 9 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`examples/common/client_pmem2_map_file.c` line 18 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzhinDNTRlMpciAjn:-N1IzhinDNTRlMpciAjo:b45h) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L18)):*
> ```C
> #include "common-conn.h"
> 
> int
> ```





_Suggestion:_
```C
#ifdef USE_PMEM
int
client_pmem_map_file(char *path, int argc, struct example_mem *mem)
```
___
*[`examples/common/client_pmem2_map_file.c` line 90 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IznEoD68ZMssggfhc:-N1IznEoD68ZMssggfhd:b-cc00lz) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L90)):*
> ```C
> 	(void) pmem2_map_delete(&mem->map);
> 	mem->mr_ptr = NULL;
> }
> ```

#endif /* USE_PMEM */



_Code quote:_
```C
}
```
___
*[`examples/common/client_pmem_map_file.c` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzF68EztsrEh0VmX9:-N1IzF68EztsrEh0VmXA:undefined) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L12)):*
> ```C
> #include <stdlib.h>
> #include <stdio.h>
> #include "common-conn.h"
> ```





_Suggestion:_
```C
#include "common-pmem.h"
#include "common-conn.h"
#include "client_pmem_map_file.h"
```
___
*[`examples/common/client_pmem_map_file.c` line 15 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzJxPBdzohTrqP8VD:-N1IzJxPBdzohTrqP8VE:b45h) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L15)):*
> ```C
> #include "client_pmem_map_file.h"
> 
> int
> ```





_Suggestion:_
```C
#ifdef USE_PMEM
int
client_pmem_map_file(char *path, int argc, struct example_mem *mem)
```
___
*[`examples/common/client_pmem_map_file.c` line 50 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzZwmDJoyElbgsbuR:-N1IzZwmDJoyElbgsbuS:undefined) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L50)):*
> ```C
> 		mem->mr_ptr = NULL;
> 	}
> }
> ```





_Suggestion:_
```C
}
#endif /* USE_PMEM */
```


<!-- Sent from Reviewable.io -->

2022-05-05 11:34 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r12, 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-05 11:55 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-05 11:58 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 10 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/common/common-conn.h` line 15 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IsrpJDg4E1y2a54Eh:-N1J4AsIEuMcXSAW0A5Y:bb664j5) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@haichangsi it is enough to ensure that ``common-pmem.h`` is included before ``common-conn.h``
</blockquote></details>

Please move it to `common-pmem.h`
___
*[`examples/common/common-conn.h` line 20 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J4HhW4qghiRjtCckU:-N1J4HhW4qghiRjtCckV:b-qisgf1) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-conn.h#L20)):*
> ```objc
> #endif /* USE_LIBPMEM2 || USE_LIBPMEM */
> 
> #if defined USE_PMEM
> ```

`#ifdef USE_PMEM`



_Code quote:_
```objc
#if defined USE_PMEM
```
___
*[`examples/common/common-conn.h` line 35 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J4NmX2nUDX2_wfMG9:-N1J4NmX2nUDX2_wfMGA:b-1zdpf7) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-conn.h#L35)):*
> ```objc
> #define NO_PMEM_MSG \
> 	"The example is unable to use libpmem. If unintended please check the build log. Using DRAM instead.\n"
> #endif
> ```

`#endif /* USE_PMEM */`



_Code quote:_
```objc
#endif
```


<!-- Sent from Reviewable.io -->

2022-05-05 12:02 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`examples/common/common-pmem.h` line 10 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IyMhW6pNphwwzdi3P:-N1J4ndn0R8hxbL7Wqyv:b-xvs81v) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-pmem.h#L10)):*
> ```objc
> #include <stddef.h>
> 
> #ifdef USE_LIBPMEM2
> ```

No, IMHO it is unreadable - too many nested ifdefs.
This should be the whole `common-pmem.h` (w/o copyright):

```c
/*
 * common-pmem.h -- common PMem definitions
 */

#ifndef EXAMPLES_COMMON_PMEM
#define EXAMPLES_COMMON_PMEM

#if defined USE_LIBPMEM2
#include <libpmem2.h>
#elif defined USE_LIBPMEM
#include <libpmem.h>
#endif

#if defined USE_LIBPMEM2 || defined USE_LIBPMEM
#define USE_PMEM 1
#else
#undef USE_PMEM
#endif /* USE_LIBPMEM2 || USE_LIBPMEM */

#endif /* EXAMPLES_COMMON_PMEM */
```


<!-- Sent from Reviewable.io -->

2022-05-05 12:05 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-N1J5ZUp3ejyvdjyCPdO:bymlhle) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Please rename all `client_pmem_*` to `cpmem_*` (remove the `client_` prefix).

---
___
*[`examples/common/client_pmem2_map_file.c` line 18 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzhinDNTRlMpciAjn:-N1J5kot36lUy1YIJ7SC:b-3iy1cn) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L18)):*
> ```C
> #include "common-conn.h"
> 
> int
> ```

Please no. We have split the code to separate files to remove ifdefs, so please do not add them again. It is OK now.
___
*[`examples/common/client_pmem2_map_file.c` line 90 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IznEoD68ZMssggfhc:-N1J62cJ4X6tH-Fg0XI9:b-3iy1cn) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L90)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

#endif /* USE_PMEM */
</blockquote></details>

Please no. We have split the code to separate files to remove ifdefs, so please do not add them again. It is OK now.
___
*[`examples/common/client_pmem_map_file.c` line 15 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzJxPBdzohTrqP8VD:-N1J68Nh6hAnEfOBWhFx:b-3iy1cn) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L15)):*
> ```C
> #include "client_pmem_map_file.h"
> 
> int
> ```

Please no. We have split the code to separate files to remove ifdefs, so please do not add them again. It is OK now.
___
*[`examples/common/client_pmem_map_file.c` line 50 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzZwmDJoyElbgsbuR:-N1J69Zh6QqhvjIQLWuv:b-3iy1cn) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L50)):*
> ```C
> 		mem->mr_ptr = NULL;
> 	}
> }
> ```

Please no. We have split the code to separate files to remove ifdefs, so please do not add them again. It is OK now.


<!-- Sent from Reviewable.io -->

2022-05-05 12:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`examples/common/common-pmem.h` line 16 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J8Nkw936HrL143OEr:-N1J8Nkw936HrL143OEs:bb27abf) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-pmem.h#L16)):*
> ```objc
> #endif
> 
> typedef void (*persist_fn)(const void *ptr, size_t size);
> ```

Move it to `client_pmem_map_file.h`



_Code quote:_
```objc
typedef void (*persist_fn)(const void *ptr, size_t size);

struct example_mem {
	/* memory buffer */
	char *mr_ptr;
	/* size of the mapped persistent memory */
	size_t mr_size;
	size_t data_offset;
	int is_pmem;
	persist_fn persist;

#ifdef USE_LIBPMEM2
	/* libpmem2 structure used for mapping PMem */
	struct pmem2_map *map;
#endif
```


<!-- Sent from Reviewable.io -->

2022-05-05 12:21 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`examples/common/client_pmem2_map_file.c` line 11 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9PGLEBP8HVG_TOxx:-N1J9PGLEBP8HVG_TOxy:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L11)):*
> ```C
> 
> #include <fcntl.h>
> #include <librpma.h>
> ```

Not needed.



_Code quote:_
```C
#include <librpma.h>

#include <stdlib.h>
```
___
*[`examples/common/client_pmem2_map_file.c` line 16 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9Svk1qHnAudjXPAv:-N1J9Svk1qHnAudjXPAw:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L16)):*
> ```C
> #include <unistd.h>
> #include "client_pmem_map_file.h"
> #include "common-conn.h"
> ```

Not needed.



_Code quote:_
```C
#include "common-conn.h"
```
___
*[`examples/common/client_pmem_map_file.c` line 10 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9XlJ82DJ5Sx5fsGb:-N1J9XlJ82DJ5Sx5fsGc:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L10)):*
> ```C
>  */
> 
> #include <stdlib.h>
> ```

Not needed.



_Code quote:_
```C
#include <stdlib.h>
```
___
*[`examples/common/client_pmem_map_file.c` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9_h664B5A1_-iTZO:-N1J9_h664B5A1_-iTZP:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L12)):*
> ```C
> #include <stdlib.h>
> #include <stdio.h>
> #include "common-conn.h"
> ```

Not needed.



_Code quote:_
```C
#include "common-conn.h"
```
___
*[`examples/common/client_pmem_map_file.c` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzF68EztsrEh0VmX9:-N1J9bAJDGwkfwwhVhAV:b9gfx0y) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L12)):*
> ```C
> #include <stdlib.h>
> #include <stdio.h>
> #include "common-conn.h"
> ```

No, not needed.


<!-- Sent from Reviewable.io -->

2022-05-05 12:21 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-05 13:51 UTC, grom72 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-06 09:07 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 11 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-N1NbvuR0_wEmM7O-lnV:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rename all `client_pmem_*` to `cpmem_*` (remove the `client_` prefix).
</blockquote></details>

Done.

---
___
*[`examples/common/common-conn.h` line 15 at r11](https://reviewable.io/reviews/pmem/rpma/1631#-N1IsrpJDg4E1y2a54Eh:-N1J5_kVDoGdG4KtjoUf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1194211d2f7f55e64f2139e5f48532748165fbcc/examples/common/common-conn.h#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move it to `common-pmem.h`
</blockquote></details>

Done.
___
*[`examples/common/common-conn.h` line 20 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J4HhW4qghiRjtCckU:-N1J5HSK8sKXbV1amT2B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-conn.h#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`#ifdef USE_PMEM`
</blockquote></details>

Done.
___
*[`examples/common/common-conn.h` line 35 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J4NmX2nUDX2_wfMG9:-N1J5Sc72y1ChoBkRPaF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-conn.h#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`#endif /* USE_PMEM */`
</blockquote></details>

Done.
___
*[`examples/common/client_pmem2_map_file.c` line 11 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9PGLEBP8HVG_TOxx:-N1NUWGB0B-klq4m4Qi4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`examples/common/client_pmem2_map_file.c` line 16 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9Svk1qHnAudjXPAv:-N1NUW030o6MWzWueTL_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem2_map_file.c#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`examples/common/client_pmem_map_file.h` line 10 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J85Mb96lazMuvMFa6:-N1N_dH_Aeo_1C21WpiJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.h#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
#ifndef EXAMPLES_COMMON_PMEM_MAP_FILE
#define EXAMPLES_COMMON_PMEM_MAP_FILE

...

#endif /* EXAMPLES_COMMON_PMEM_MAP_FILE */
```
</blockquote></details>

Done.
___
*[`examples/common/client_pmem_map_file.c` line 10 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9XlJ82DJ5Sx5fsGb:-N1NW36eEA3MXC8UgZyZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`examples/common/client_pmem_map_file.c` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IzF68EztsrEh0VmX9:-N1J4WKp9LRPx83ut-CX:bobp26) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L12)):*
> ```C
> #include <stdlib.h>
> #include <stdio.h>
> #include "common-conn.h"
> ```

It is included in "client_pmem_map_file.h"
___
*[`examples/common/client_pmem_map_file.c` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J9_h664B5A1_-iTZO:-N1NW7fY8l5Vt-Tuw-HZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/client_pmem_map_file.c#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem.h` line 10 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1IyMhW6pNphwwzdi3P:-N1J56wK31bc-Wk0Pf38:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-pmem.h#L10)):*
> ```objc
> #include <stddef.h>
> 
> #ifdef USE_LIBPMEM2
> ```

Done.
___
*[`examples/common/common-pmem.h` line 16 at r13](https://reviewable.io/reviews/pmem/rpma/1631#-N1J8Nkw936HrL143OEr:-N1NX2WTDRYTGKg-zCJQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e2553c14401d80d9f15733011a840c69b8affc/examples/common/common-pmem.h#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move it to `client_pmem_map_file.h`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-06 11:16 UTC, ldorau requested changes
> Reviewed 9 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`examples/common/cpmem_map_file.h` line 35 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O49QL75YInvyGIuJ3:-N1O49QM2w5hx0woRECb:bp456lq) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L35)):*
> ```objc
> int client_pmem_map_file(char *path, int argc, struct example_mem *mem);
> 
> void client_pmem_unmap_file(struct example_mem *mem);
> ```

Add empty line in between, please.



_Code quote:_
```objc
void client_pmem_unmap_file(struct example_mem *mem);
#endif /* EXAMPLES_COMMON_PMEM_MAP_FILE */
```


<!-- Sent from Reviewable.io -->

2022-05-06 11:24 UTC, grom72 requested changes
> Reviewed 5 of 9 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 12 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-N1O42g6DOCzAhXb5RNj:b-z188yv) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Excuse me, there was a typo, I meant `pmem_` not `cpmem_` ...
</blockquote></details>

+1 and rename ``client_pmem_map_file.h`` to ``common-pmem_map_file.h``

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-N1O51xh1Pc8QGI7e1Fk:-N1O51xh1Pc8QGI7e1Fl:be5ark) (no related file):*
@ldorau  - I think we need a separate PR to clean up all common files' names and common structures. Now it is the very dirty solution.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5opQ55CJAcAP3uTs:-N1O5opQ55CJAcAP3uTt:b-t0dcga) (no related file):*
The first ``#ifndef`` in *.h files shall follow the file name.

---
___
*[`examples/common/common-conn.h` line 8 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5Zn69cbJPBH1yCp_:-N1O5Zn69cbJPBH1yCpa:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L8)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON
> ```





_Suggestion:_
```objc
#ifndef COMMON_CONN_H
```
___
*[`examples/common/common-conn.h` line 9 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5f1M-MOTB7rvFHac:-N1O5f1M-MOTB7rvFHad:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L9)):*
> ```objc
> 
> #ifndef EXAMPLES_COMMON
> #define EXAMPLES_COMMON
> ```

.



_Code quote:_
```objc
#define EXAMPLES_COMMON
```
___
*[`examples/common/common-conn.h` line 13 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O347k9P8LL3n3wTwX:-N1O347k9P8LL3n3wTwY:b-6zjuyw) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L13)):*
> ```objc
> #include "common-pmem.h"
> #include <string.h>
> #include <librpma.h>
> ```

The first system includes then internal



_Suggestion:_
```objc
#include <string.h>
#include <librpma.h>

#include "common-pmem.h"
```
___
*[`examples/common/common-conn.h` line 74 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5iG156uQb3hgazC6:-N1O5iG156uQb3hgazC7:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L74)):*
> ```objc
> int common_disconnect_and_wait_for_conn_close(struct rpma_conn **conn_ptr);
> 
> #endif /* EXAMPLES_COMMON */
> ```





_Suggestion:_
```objc
COMMON_CONN_H
```
___
*[`examples/common/cpmem_map_file.h` line 5 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O6A4G2R4CaOicFYxl:-N1O6A4H5emxvlB3vYbE:b45h) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L5)):*
> ```objc
> 
> /*
>  * client_pmem_map_file.h -- a header file for both client_pmem_map_file.c
> ```





_Suggestion:_
```objc
common-pmem_map_file.h
```
___
*[`examples/common/cpmem_map_file.h` line 11 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O6EhI1a6ovMdwDn8O:-N1O6EhI1a6ovMdwDn8P:b-chqzmj) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L11)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON_PMEM_MAP_FILE
> ```

Follow file name



_Code quote:_
```objc
EXAMPLES_COMMON_PMEM_MAP_FILE
```
___
*[`examples/common/client_pmem_map_file.c` line 5 at r12](https://reviewable.io/reviews/pmem/rpma/1631#-N1O6Iyi0z-0-CoBMDKx:-N1O6Iyi0z-0-CoBMDKy:undefined) ([raw file](https://github.com/pmem/rpma/blob/b61a6ac8a0a6892a6b31d20ecd1e4ba479b685b0/examples/common/client_pmem_map_file.c#L5)):*
> ```C
> 
> /*
>  * client_pmem_map_file.c -- a function to map PMem using libpmem
> ```





_Suggestion:_
```C
common-pmem_map_file.c
```
___
*[`examples/common/common-pmem.h` line 11 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O3PA16uv1v0YO5rWE:-N1O3PA16uv1v0YO5rWF:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L11)):*
> ```objc
> #define EXAMPLES_COMMON_PMEM
> 
> #if defined USE_LIBPMEM2
> ```





_Suggestion:_
```objc
#ifdef USE_LIBPMEM2
```


<!-- Sent from Reviewable.io -->

2022-05-06 11:39 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-N1O9Y-m-Zl7qA9iweaO:bk7qc9k) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1 and rename ``client_pmem_map_file.h`` to ``common-pmem_map_file.h``
</blockquote></details>

@grom72 Do you want to rename *.c files either?

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-N1O51xh1Pc8QGI7e1Fk:-N1O9KHkByynStexpXIX:bbcfuu) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau  - I think we need a separate PR to clean up all common files' names and common structures. Now it is the very dirty solution.
</blockquote></details>

@grom72 OK, but it is not an issue of this PR, so please resolve this issue here.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5opQ55CJAcAP3uTs:-N1O9T-W0ewuONI15jjq:b-e9q1ec) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The first ``#ifndef`` in *.h files shall follow the file name.
</blockquote></details>

(in capital letters)

---


<!-- Sent from Reviewable.io -->

2022-05-06 12:51 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: all files reviewed, 17 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/common/cpmem_map_file.h` line 11 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPl3q2CmltKEu_BmI:-N1OPl3q2CmltKEu_BmJ:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L11)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON_PMEM_MAP_FILE
> ```





_Suggestion:_
```objc
COMMON_PMEM_MAP_FILE_H
```
___
*[`examples/common/cpmem_map_file.h` line 12 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPofGATCwimF50_6D:-N1OPofGATCwimF50_6E:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L12)):*
> ```objc
> 
> #ifndef EXAMPLES_COMMON_PMEM_MAP_FILE
> #define EXAMPLES_COMMON_PMEM_MAP_FILE
> ```





_Suggestion:_
```objc
COMMON_PMEM_MAP_FILE_H
```
___
*[`examples/common/cpmem_map_file.h` line 36 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPr3v1uenOJH7Tj9c:-N1OPr3v1uenOJH7Tj9d:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L36)):*
> ```objc
> 
> void client_pmem_unmap_file(struct example_mem *mem);
> #endif /* EXAMPLES_COMMON_PMEM_MAP_FILE */
> ```





_Suggestion:_
```objc
COMMON_PMEM_MAP_FILE_H
```
___
*[`examples/common/common-pmem.h` line 8 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPbwe11QVtHLgZH-_:-N1OPbwe11QVtHLgZH-a:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L8)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON_PMEM
> ```





_Suggestion:_
```objc
COMMON_PMEM_H
```
___
*[`examples/common/common-pmem.h` line 9 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPewF-uF7UzP1jYRi:-N1OPewF-uF7UzP1jYRj:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L9)):*
> ```objc
> 
> #ifndef EXAMPLES_COMMON_PMEM
> #define EXAMPLES_COMMON_PMEM
> ```





_Suggestion:_
```objc
COMMON_PMEM_H
```
___
*[`examples/common/common-pmem.h` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPgsW4vUm3YqLtwBT:-N1OPgsW4vUm3YqLtwBU:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L23)):*
> ```objc
> #endif /* USE_LIBPMEM2 || USE_LIBPMEM */
> 
> #endif /* EXAMPLES_COMMON_PMEM */
> ```





_Suggestion:_
```objc
COMMON_PMEM_H
```
___
*[`examples/common/cpmem2_map_file.c` line 5 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OQ-kZ4_d-K-6T53e_:-N1OQ-kZ4_d-K-6T53ea:undefined) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem2_map_file.c#L5)):*
> ```C
> 
> /*
>  * client_pmem2_map_file.c -- a function to map PMem using libpmem2
> ```





_Suggestion:_
```C
common-pmem2_map_file.c
```


<!-- Sent from Reviewable.io -->

2022-05-09 07:44 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: 1 of 9 files reviewed, 17 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1631#-MzKcDGd9VQU5KcR7eLY:-N1biJ_u34DLL8SguMxf:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, so @haichangsi please rename also *.c files
</blockquote></details>

Done.

---
___
*[`examples/common/common-conn.h` line 8 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5Zn69cbJPBH1yCp_:-N1bibpL8KYyHvrqrG_h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L8)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON
> ```

Done.
___
*[`examples/common/common-conn.h` line 9 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5f1M-MOTB7rvFHac:-N1bicjv8FplRoTwWEl1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-conn.h` line 13 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O347k9P8LL3n3wTwX:-N1bilJX9R-nI9WuYChV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The first system includes then internal
</blockquote></details>

Done.
___
*[`examples/common/common-conn.h` line 74 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O5iG156uQb3hgazC6:-N1bim8k36sC8atLMMDc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-conn.h#L74)):*
> ```objc
> int common_disconnect_and_wait_for_conn_close(struct rpma_conn **conn_ptr);
> 
> #endif /* EXAMPLES_COMMON */
> ```

Done.
___
*[`examples/common/cpmem_map_file.h` line 5 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O6A4G2R4CaOicFYxl:-N1bjFGY9YfLz2CWdgbN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L5)):*
> ```objc
> 
> /*
>  * client_pmem_map_file.h -- a header file for both client_pmem_map_file.c
> ```

Done.
___
*[`examples/common/cpmem_map_file.h` line 11 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O6EhI1a6ovMdwDn8O:-N1bjanp-cO91wMpdkdC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Follow file name
</blockquote></details>

Done.
___
*[`examples/common/cpmem_map_file.h` line 11 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPl3q2CmltKEu_BmI:-N1bjuaD2UlAyMZJ2Wzm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L11)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON_PMEM_MAP_FILE
> ```

Done.
___
*[`examples/common/cpmem_map_file.h` line 12 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPofGATCwimF50_6D:-N1bjvq4D-5Gw8Azia9B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L12)):*
> ```objc
> 
> #ifndef EXAMPLES_COMMON_PMEM_MAP_FILE
> #define EXAMPLES_COMMON_PMEM_MAP_FILE
> ```

Done.
___
*[`examples/common/cpmem_map_file.h` line 35 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O49QL75YInvyGIuJ3:-N1bkI9b2jGHhQwTZBYA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add empty line in between, please.
</blockquote></details>

Done.
___
*[`examples/common/cpmem_map_file.h` line 36 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPr3v1uenOJH7Tj9c:-N1bkJ4ZAGkGab-evuGo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem_map_file.h#L36)):*
> ```objc
> 
> void client_pmem_unmap_file(struct example_mem *mem);
> #endif /* EXAMPLES_COMMON_PMEM_MAP_FILE */
> ```

Done.
___
*[`examples/common/client_pmem_map_file.c` line 5 at r12](https://reviewable.io/reviews/pmem/rpma/1631#-N1O6Iyi0z-0-CoBMDKx:-N1bkRJF0uyYrHvXWW0W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b61a6ac8a0a6892a6b31d20ecd1e4ba479b685b0/examples/common/client_pmem_map_file.c#L5)):*
> ```C
> 
> /*
>  * client_pmem_map_file.c -- a function to map PMem using libpmem
> ```

Done.
___
*[`examples/common/common-pmem.h` line 8 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPbwe11QVtHLgZH-_:-N1biunb2Hrb1EUF75ES:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L8)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_COMMON_PMEM
> ```

Done.
___
*[`examples/common/common-pmem.h` line 9 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPewF-uF7UzP1jYRi:-N1biv6Z7VKepAWn3rWN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L9)):*
> ```objc
> 
> #ifndef EXAMPLES_COMMON_PMEM
> #define EXAMPLES_COMMON_PMEM
> ```

Done.
___
*[`examples/common/common-pmem.h` line 11 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1O3PA16uv1v0YO5rWE:-N1bizEm9h5el3RHrYRD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L11)):*
> ```objc
> #define EXAMPLES_COMMON_PMEM
> 
> #if defined USE_LIBPMEM2
> ```

Done.
___
*[`examples/common/common-pmem.h` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OPgsW4vUm3YqLtwBT:-N1bj-YF-cP19F5yOVs-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/common-pmem.h#L23)):*
> ```objc
> #endif /* USE_LIBPMEM2 || USE_LIBPMEM */
> 
> #endif /* EXAMPLES_COMMON_PMEM */
> ```

Done.
___
*[`examples/common/cpmem2_map_file.c` line 5 at r14](https://reviewable.io/reviews/pmem/rpma/1631#-N1OQ-kZ4_d-K-6T53e_:-N1bjEd84Q-ks7sDA-cd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f3aa5f5560397b53cd0771c3c92e2b9f3f33c82/examples/common/cpmem2_map_file.c#L5)):*
> ```C
> 
> /*
>  * client_pmem2_map_file.c -- a function to map PMem using libpmem2
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-05-09 08:32 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631#-:-N1bwf96EdRY7idw0nhg:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-09 09:08 UTC, ldorau approved these changes
> Reviewed 8 of 8 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-09 20:10 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1631#-:-N1eRY7O0ddICDefMiNZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-09 20:11 UTC, merged