rpma: add shared completion channel
pmem/rpma pull request #1637
Opened 2022-04-04 09:13 UTC by ldorau

Add the common completion channel, shared between CQ and RCQ.

Missing:
- [ ] Write documentation for rpma_conn_cfg_get_compl_channel() in librpma.h
- [ ] Write documentation for rpma_conn_cfg_set_compl_channel() in librpma.h
- [ ] Write documentation for rpma_conn_get_compl_fd() in librpma.h
- [ ] Write documentation for rpma_conn_wait() in librpma.h
- [ ] Update documentation for rpma_cq_wait() in librpma.h
- [ ] Complete unit tests and the mock for rpma_cq_new()
- [ ] Complete unit tests for rpma_cq_wait()
- [ ] Complete unit tests for rpma_conn_req_from_id()
- [ ] Complete unit tests and the mock for rpma_conn_new()
- [ ] Write unit tests for rpma_conn_cfg_set_compl_channel()
- [ ] Write unit tests for rpma_conn_cfg_get_compl_channel()
- [ ] Write unit tests for rpma_comp_channel_new()
- [ ] Write unit tests for rpma_comp_channel_destroy()
- [ ] Write unit tests for rpma_conn_get_compl_fd()
- [ ] Write unit tests for rpma_conn_wait()
- [ ] Fix example 09 to use the common completion channel
- [ ] Fix example 12 to use the common completion channel
- [ ] Finish CHANGELOG
- [ ] Fix and remove all "XXXXXX"

2022-04-04 09:16 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 0 of 21 files reviewed, 1 unresolved discussion

___
*[src/cq.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1637#-Mznr-kdCcHAOPsE4_ne:-Mznr-kdCcHAOPsE4_nf:bdrhu52) ([raw file](https://github.com/pmem/rpma/blob/fe2be45651784df456c4f57514c42264b644e349/src/cq.c#L49)):*
> ```C
>  */
> int
> rpma_comp_channel_new(struct ibv_context *ibv_ctx,
> ```

`rpma_comp_channel_new` and `rpma_comp_channel_new` should be moved to a separate file `comp_channel.c`



_Code quote:_
```C
rpma_comp_channel_new(struct ibv_context *ibv_ctx,
		struct ibv_comp_channel **channel_ptr)
```


<!-- Sent from Reviewable.io -->

2022-04-04 09:39 UTC, grom72 reviewed
> Reviewed 4 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 4 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-04 09:39 UTC, grom72 reviewed
> Reviewed 4 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 6 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-04 10:15 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 6 of 27 files reviewed, all discussions resolved (waiting on @grom72)

___
*[src/cq.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1637#-Mznr-kdCcHAOPsE4_ne:-Mzo3fxt7H2o26poEHcU:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/fe2be45651784df456c4f57514c42264b644e349/src/cq.c#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_comp_channel_new` and `rpma_comp_channel_new` should be moved to a separate file `comp_channel.c`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-04-05 09:15 UTC, grom72 reviewed
> Reviewed 1 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 5 of 29 files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-07 09:26 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 5 of 29 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/rpma_err.c, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1637#-N-2L5k-8PYO4WXUCBMq:-N-2L5k-8PYO4WXUCBMr:b-mhrwgn) ([raw file](https://github.com/pmem/rpma/blob/8ef0f18d84acb02ba3bd3e936dc475a7633444a3/src/rpma_err.c#L37)):*
> ```C
> 		return "Temporary error, try again";
> 	case RPMA_E_SHARED_CHANNEL:
> 		return "Completion channel is shared";
> ```

Or maybe `Completion channel cannot be shared` ?



_Code quote:_
```C
"Completion channel is shared"
```


<!-- Sent from Reviewable.io -->

2022-04-07 17:08 UTC, grom72 requested changes
> Reviewed 3 of 21 files at r1, 4 of 13 files at r3, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 13 of 29 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/comp_channel.c, line 19 at r5](https://reviewable.io/reviews/pmem/rpma/1637#-N-3zeDVDVJ-dt21SEkB:-N-3zeDVDVJ-dt21SEkC:bcx4qpd) ([raw file](https://github.com/pmem/rpma/blob/af97b548e731c2f4ff135b4a9b7ceb3e71aacbae/src/comp_channel.c#L19)):*
> ```C
>  */
> int
> rpma_comp_channel_new(struct ibv_context *ibv_ctx,
> ```

shall we have also ``struct rpma_comp_channel`` instead of raw `` struct ibv_comp_channel`` ?



_Code quote:_
```C
rpma_comp_channel_new
```


<!-- Sent from Reviewable.io -->

2022-04-08 12:36 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 12 of 29 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/comp_channel.c, line 19 at r5](https://reviewable.io/reviews/pmem/rpma/1637#-N-3zeDVDVJ-dt21SEkB:-N-8ACs92K8K3BjKNSdL:b-3oxnwh) ([raw file](https://github.com/pmem/rpma/blob/af97b548e731c2f4ff135b4a9b7ceb3e71aacbae/src/comp_channel.c#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we have also ``struct rpma_comp_channel`` instead of raw `` struct ibv_comp_channel`` ?
</blockquote></details>

I think we shall not. It is redundant.


<!-- Sent from Reviewable.io -->

2022-04-08 12:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 10 of 29 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/comp_channel.c, line 19 at r5](https://reviewable.io/reviews/pmem/rpma/1637#-N-3zeDVDVJ-dt21SEkB:-N-8EQAX9c6SJEVviUW-:b-yjhlb8) ([raw file](https://github.com/pmem/rpma/blob/af97b548e731c2f4ff135b4a9b7ceb3e71aacbae/src/comp_channel.c#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think we shall not. It is redundant.
</blockquote></details>

Functions renamed


<!-- Sent from Reviewable.io -->

2022-04-08 12:55 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 10 of 29 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/rpma_err.c, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/1637#-N-2L5k-8PYO4WXUCBMq:-N-8EYe5B6MNsbC2mIn0:bno969i) ([raw file](https://github.com/pmem/rpma/blob/8ef0f18d84acb02ba3bd3e936dc475a7633444a3/src/rpma_err.c#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or maybe `Completion channel cannot be shared` ?
</blockquote></details>

It is OK now.


<!-- Sent from Reviewable.io -->

2022-04-08 19:51 UTC, grom72 requested changes
> Reviewed 1 of 13 files at r3, 2 of 4 files at r4, 4 of 5 files at r6, 2 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 19 of 29 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/comp_channel.c, line 19 at r7](https://reviewable.io/reviews/pmem/rpma/1637#-N-9hSMjEDr_zumUtFnY:-N-9hSMjEDr_zumUtFnZ:b6dgzbn) ([raw file](https://github.com/pmem/rpma/blob/046e44f10442b02ee1f0779eae3c8ea9f4f29de8/src/comp_channel.c#L19)):*
> ```C
>  */
> int
> rpma_ibv_comp_channel_create(struct ibv_context *ibv_ctx,
> ```

@ldorau , how do you find the name ``rpma_ibv_create_comp_channel`` as an extension to ``ibv_create_comp_channel``



_Code quote:_
```C
rpma_ibv_comp_channel_create
```
___
*[src/comp_channel.c, line 39 at r7](https://reviewable.io/reviews/pmem/rpma/1637#-N-9hvfhD7G5GeBE4q_f:-N-9hvfhD7G5GeBE4q_g:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/046e44f10442b02ee1f0779eae3c8ea9f4f29de8/src/comp_channel.c#L39)):*
> ```C
>  */
> int
> rpma_ibv_comp_channel_destroy(struct ibv_comp_channel *channel)
> ```

.



_Code quote:_
```C
rpma_ibv_comp_channel_destroy
```


<!-- Sent from Reviewable.io -->

2022-04-11 05:41 UTC, grom72 requested changes
> Reviewed 1 of 21 files at r1, 3 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 23 of 29 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/comp_channel.h, line 5 at r7](https://reviewable.io/reviews/pmem/rpma/1637#-N-Ika4y8tcCgWxSIJOQ:-N-Ika4y8tcCgWxSIJOR:bbyeehr) ([raw file](https://github.com/pmem/rpma/blob/046e44f10442b02ee1f0779eae3c8ea9f4f29de8/src/comp_channel.h#L5)):*
> ```objc
> 
> /*
>  * comp_channel.h -- librpma completion channel related internal definitions
> ```

I propose to move these two functions to ``conn.h`` to avoid the impression that librpma has its own completion channel-related structure.

It should work as conn_req.c includes ""conn.h" 



_Code quote:_
```objc
comp_channel.h
```


<!-- Sent from Reviewable.io -->

2022-04-11 05:47 UTC, grom72 approved these changes
> Reviewed 2 of 21 files at r1, 1 of 13 files at r3, 1 of 4 files at r4, 2 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-11 07:47 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-11 08:50 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637)* status: 20 of 30 files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

___
*[src/comp_channel.h, line 5 at r7](https://reviewable.io/reviews/pmem/rpma/1637#-N-Ika4y8tcCgWxSIJOQ:-N-Mnbt01cbY0nwKXyAU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/046e44f10442b02ee1f0779eae3c8ea9f4f29de8/src/comp_channel.h#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I propose to move these two functions to ``conn.h`` to avoid the impression that librpma has its own completion channel-related structure.

It should work as conn_req.c includes ""conn.h" 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 09:34 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637#-:-N-MyP_30Eo3dGSMFEMT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-11 09:55 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 21 files at r1, 4 of 13 files at r3, 3 of 4 files at r4, 2 of 7 files at r7, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1637#-:-N-N204b2GtTYTXhWiuP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-04-11 10:13 UTC, merged