rpma: add doc + ut for rpma_conn_wait()
pmem/rpma pull request #1655
Opened 2022-04-13 12:17 UTC by osalyk

- [ ] #1654

2022-04-13 12:32 UTC, grom72 requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-Xu5zK6A--LkE4kSxx:b-j99ipy) (no related file):*
do we have test for configuration where shared channel is enabled, but no RCQ?

---


<!-- Sent from Reviewable.io -->

2022-04-13 13:34 UTC, ldorau requested changes
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Y7UAX7oN3Fr2W92ib:-N-Y7UAX7oN3Fr2W92ic:bk84ajf) (no related file):*
Rebase on https://github.com/pmem/rpma/pull/1654

---


<!-- Sent from Reviewable.io -->

2022-04-13 18:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-ZEFjYD3yumFq3Mewx:-N-ZEFjYD3yumFq3Mewy:bhz9iq9) (no related file):*
It does not build with  #1654 nor without  #1654 ...

---


<!-- Sent from Reviewable.io -->

2022-04-14 07:02 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-as7Tk1x8UugWY7HqV:byfdhsb) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we have test for configuration where shared channel is enabled, but no RCQ?
</blockquote></details>

This case will not improve code coverage

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Y7UAX7oN3Fr2W92ib:-N-arkB-6ukwCEM_Ccec:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase on https://github.com/pmem/rpma/pull/1654
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-ZEFjYD3yumFq3Mewx:-N-arkV-5qTlEAsT22VL:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does not build with  #1654 nor without  #1654 ...
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-04-14 07:57 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 2163 at r4](https://reviewable.io/reviews/pmem/rpma/1655#-N-b2z__AAFvImRprb0E:-N-b2z__AAFvImRprb0F:bb7cwpb) ([raw file](https://github.com/pmem/rpma/blob/427f9ca9d37a959348146fec02ab2a5daf4ffce5/src/include/librpma.h#L2163)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_wait() waits for a completion event on the shared completion
>  * channel from CQ or RCQ, ack it and return a CQ that caused the event
> ```

acks



_Code quote:_
```objc
ack
```
___
*[src/include/librpma.h, line 2163 at r4](https://reviewable.io/reviews/pmem/rpma/1655#-N-b30TH4wmX-TZyUdAo:-N-b30TI0Gq3YqNNBBnq:b-hbrjoi) ([raw file](https://github.com/pmem/rpma/blob/427f9ca9d37a959348146fec02ab2a5daf4ffce5/src/include/librpma.h#L2163)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_wait() waits for a completion event on the shared completion
>  * channel from CQ or RCQ, ack it and return a CQ that caused the event
> ```

returns



_Code quote:_
```objc
return
```
___
*[src/include/librpma.h, line 2180 at r4](https://reviewable.io/reviews/pmem/rpma/1655#-N-b3QjpEre0v0pWM_GU:-N-b3QjpEre0v0pWM_GV:bibxdte) ([raw file](https://github.com/pmem/rpma/blob/427f9ca9d37a959348146fec02ab2a5daf4ffce5/src/include/librpma.h#L2180)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_conn_req_new(3), librpma(7) and https://pmem.io/rpma/
> ```

@grom72 Maybe add `rpma_cq_wait(3)` here?



_Code quote:_
```objc
 * SEE ALSO
 * rpma_conn_req_new(3), librpma(7) and https://pmem.io/rpma/
```


<!-- Sent from Reviewable.io -->

2022-04-14 09:06 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[src/include/librpma.h, line 2163 at r4](https://reviewable.io/reviews/pmem/rpma/1655#-N-b2z__AAFvImRprb0E:-N-b8Alb8u0chdALlusd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/427f9ca9d37a959348146fec02ab2a5daf4ffce5/src/include/librpma.h#L2163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

acks
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2163 at r4](https://reviewable.io/reviews/pmem/rpma/1655#-N-b30TH4wmX-TZyUdAo:-N-b8CpLBbPr93ybyVZ9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/427f9ca9d37a959348146fec02ab2a5daf4ffce5/src/include/librpma.h#L2163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

returns
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 09:13 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-14 10:53 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 2180 at r4](https://reviewable.io/reviews/pmem/rpma/1655#-N-b3QjpEre0v0pWM_GU:-N-bhBc4BSh8G2HJ1sxW:b5bykrr) ([raw file](https://github.com/pmem/rpma/blob/427f9ca9d37a959348146fec02ab2a5daf4ffce5/src/include/librpma.h#L2180)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 Maybe add `rpma_cq_wait(3)` here?
</blockquote></details>

Not needed, discussed offline.


<!-- Sent from Reviewable.io -->

2022-04-14 11:53 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/conn/conn-wait.c, line 99 at r5](https://reviewable.io/reviews/pmem/rpma/1655#-N-bu9toBRyDG8LzQF87:-N-bu9tpCad46PwmH7RP:b4ov8oy) ([raw file](https://github.com/pmem/rpma/blob/b33dd90158badfe8c186a26f22b60e0f4fb4ab3f/tests/unit/conn/conn-wait.c#L99)):*
> ```C
> 	will_return(ibv_get_cq_event, MOCK_IBV_CQ);
> 	expect_value(rpma_cq_get_ibv_cq, cq, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_get_ibv_cq, MOCK_ERRNO);
> ```

The return value has to be of the `struct ibv_cq *` type, not errno. Read carefully the mock of `rpma_cq_get_ibv_cq()`.



_Code quote:_
```C
MOCK_ERRNO
```
___
*[tests/unit/conn/conn-wait.c, line 101 at r5](https://reviewable.io/reviews/pmem/rpma/1655#-N-buQ8U4Sx0rKdy1Enh:-N-buQ8U4Sx0rKdy1Eni:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b33dd90158badfe8c186a26f22b60e0f4fb4ab3f/tests/unit/conn/conn-wait.c#L101)):*
> ```C
> 	will_return(rpma_cq_get_ibv_cq, MOCK_ERRNO);
> 	expect_value(rpma_cq_get_ibv_cq, cq, MOCK_RPMA_RCQ);
> 	will_return(rpma_cq_get_ibv_cq, MOCK_ERRNO);
> ```

.



_Code quote:_
```C
MOCK_ERRNO
```
___
*[tests/unit/conn/conn-wait.c, line 155 at r5](https://reviewable.io/reviews/pmem/rpma/1655#-N-buoa61RPkshq-TQIt:-N-buoa61RPkshq-TQIu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b33dd90158badfe8c186a26f22b60e0f4fb4ab3f/tests/unit/conn/conn-wait.c#L155)):*
> ```C
> 	will_return(ibv_get_cq_event, MOCK_IBV_RCQ);
> 	expect_value(rpma_cq_get_ibv_cq, cq, MOCK_RPMA_CQ);
> 	will_return(rpma_cq_get_ibv_cq, MOCK_ERRNO);
> ```

.



_Code quote:_
```C
MOCK_ERRNO
```


<!-- Sent from Reviewable.io -->

2022-04-14 12:22 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-04-14 12:55 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/unit/conn/conn-wait.c, line 99 at r5](https://reviewable.io/reviews/pmem/rpma/1655#-N-bu9toBRyDG8LzQF87:-N-bvT9Y3MrwejmuLUOA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b33dd90158badfe8c186a26f22b60e0f4fb4ab3f/tests/unit/conn/conn-wait.c#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The return value has to be of the `struct ibv_cq *` type, not errno. Read carefully the mock of `rpma_cq_get_ibv_cq()`.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-wait.c, line 101 at r5](https://reviewable.io/reviews/pmem/rpma/1655#-N-buQ8U4Sx0rKdy1Enh:-N-c7dbp9mf_x4Fql4Qq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b33dd90158badfe8c186a26f22b60e0f4fb4ab3f/tests/unit/conn/conn-wait.c#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-wait.c, line 155 at r5](https://reviewable.io/reviews/pmem/rpma/1655#-N-buoa61RPkshq-TQIt:-N-c7gzM7fCCN1WRwaZv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b33dd90158badfe8c186a26f22b60e0f4fb4ab3f/tests/unit/conn/conn-wait.c#L155)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 13:08 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/conn/conn-wait.c, line 97 at r6](https://reviewable.io/reviews/pmem/rpma/1655#-N-cAUhPBL1XggEcRXz8:-N-cAUhPBL1XggEcRXz9:b5x984i) ([raw file](https://github.com/pmem/rpma/blob/45e8fd89e52ae3baded0ddd3b5b2db6dac3dfa8b/tests/unit/conn/conn-wait.c#L97)):*
> ```C
> 	expect_value(ibv_get_cq_event, channel, MOCK_COMP_CHANNEL);
> 	will_return(ibv_get_cq_event, MOCK_OK);
> 	will_return(ibv_get_cq_event, MOCK_IBV_RCQ);
> ```

`MOCK_IBV_CQ_UNKNOWN` - please use names consistent with logic of `ibv_get_cq_event`



_Code quote:_
```C
MOCK_IBV_RCQ
```
___
*[tests/unit/conn/conn-wait.c, line 101 at r6](https://reviewable.io/reviews/pmem/rpma/1655#-N-cARVL62DmgwmoqxL2:-N-cARVM7L9vXcWVYCtj:b-fwfbjd) ([raw file](https://github.com/pmem/rpma/blob/45e8fd89e52ae3baded0ddd3b5b2db6dac3dfa8b/tests/unit/conn/conn-wait.c#L101)):*
> ```C
> 	will_return(rpma_cq_get_ibv_cq, MOCK_IBV_CQ);
> 	expect_value(rpma_cq_get_ibv_cq, cq, MOCK_RPMA_RCQ);
> 	will_return(rpma_cq_get_ibv_cq, MOCK_IBV_CQ);
> ```

`MOCK_IBV_RCQ` - please use names consistent with logic of `ibv_get_cq_event`



_Code quote:_
```C
MOCK_IBV_CQ
```


<!-- Sent from Reviewable.io -->

2022-04-14 13:46 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/unit/conn/conn-wait.c, line 97 at r6](https://reviewable.io/reviews/pmem/rpma/1655#-N-cAUhPBL1XggEcRXz8:-N-cJOhh0kGNpux5PvUu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e8fd89e52ae3baded0ddd3b5b2db6dac3dfa8b/tests/unit/conn/conn-wait.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`MOCK_IBV_CQ_UNKNOWN` - please use names consistent with logic of `ibv_get_cq_event`
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-wait.c, line 101 at r6](https://reviewable.io/reviews/pmem/rpma/1655#-N-cARVL62DmgwmoqxL2:-N-cJTJxCfJT-f3RyMs7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45e8fd89e52ae3baded0ddd3b5b2db6dac3dfa8b/tests/unit/conn/conn-wait.c#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`MOCK_IBV_RCQ` - please use names consistent with logic of `ibv_get_cq_event`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 14:01 UTC, ldorau approved these changes
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-14 14:02 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655#-:-N-cN_cf05VPi_i3X6ad:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-cNLbm7iidukKWGM03:bd21ryc) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This case will not improve code coverage
</blockquote></details>

@grom72 I'm afraid it is not possible, RCQ is required to have shared completion channel.

---


<!-- Sent from Reviewable.io -->

2022-04-14 14:27 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-cSbiV4MnbO-hiC3et:bwp7lgq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 I'm afraid it is not possible, RCQ is required to have shared completion channel.
</blockquote></details>

@ldorau is there any condition preventing this?

---


<!-- Sent from Reviewable.io -->

2022-04-14 14:30 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 2178 at r8](https://reviewable.io/reviews/pmem/rpma/1655#-N-cTb3u1n82b6a6Ma5W:-N-cTb3u1n82b6a6Ma5X:b-w4tbph) ([raw file](https://github.com/pmem/rpma/blob/0e75b2534c3e42dd2d059d5683c1f998e32a5bf6/src/include/librpma.h#L2178)):*
> ```objc
>  * - RPMA_E_UNKNOWN - ibv_get_cq_event(3) returned unknown CQ
>  * - RPMA_E_PROVIDER - ibv_req_notify_cq(3) failed
>  *
> ```

What about the situation when this function is called but completion is on cq level?



_Code quote:_
```objc
RPMA_E_PROVIDER
```


<!-- Sent from Reviewable.io -->

2022-04-14 14:31 UTC, grom72 reviewed
> Reviewed 4 of 6 files at r3, 2 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-04-14 14:33 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-cUP6-AtRCxmcENaDp:b7t1gxk) (no related file):*
>  is there any condition preventing this?
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/1qPj7YEaO5MfcVEvaU3W4gtW/image.png)

---


<!-- Sent from Reviewable.io -->

2022-04-14 14:50 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-cWqVx0FngZt4LrRZT:b-ngiqwu) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

>  is there any condition preventing this?
![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/1qPj7YEaO5MfcVEvaU3W4gtW/image.png)

</blockquote></details>

Is it documented anywhere?

---


<!-- Sent from Reviewable.io -->

2022-04-14 16:06 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-cjJnlC_xrHA2fc0rC:b-aohf09) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it documented anywhere?
</blockquote></details>

Not yet, this PR is not done yet.

---


<!-- Sent from Reviewable.io -->

2022-04-14 21:22 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-dwq4V0v9iA3fRp19Z:b-b16jht) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, this PR is not done yet.
</blockquote></details>

@grom72 @osalyk 
It should be possible - RCQ should not be required to have shared completion channel:
https://github.com/pmem/rpma/pull/1663

---


<!-- Sent from Reviewable.io -->

2022-04-15 06:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1655#-N-Xu5zK6A--LkE4kSxw:-N-fd-dAA5uoCsYAWkIL:b4putsz) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 @osalyk 
It should be possible - RCQ should not be required to have shared completion channel:
https://github.com/pmem/rpma/pull/1663
</blockquote></details>

:ok_hand: 

---
___
*[src/include/librpma.h, line 2178 at r8](https://reviewable.io/reviews/pmem/rpma/1655#-N-cTb3u1n82b6a6Ma5W:-N-fscGu0AcXm3dYHL4c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0e75b2534c3e42dd2d059d5683c1f998e32a5bf6/src/include/librpma.h#L2178)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What about the situation when this function is called but completion is on cq level?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-15 07:19 UTC, grom72 requested changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/conn.c, line 221 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g4ifr8Aq3aZx71bbN:-N-g4ifr8Aq3aZx71bbO:b5bavg7) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/conn.c#L221)):*
> ```C
> 
> 	if (conn->channel == NULL)
> 		return RPMA_E_NOT_SHARED_CHNL;
> ```

RPMA_E_NOT_SHARED_CHANNEL



_Code quote:_
```C
RPMA_E_NOT_SHARED_CHNL
```
___
*[src/include/librpma.h, line 2175 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g4UKL8EPwqmEe7rnt:-N-g4UKL8EPwqmEe7rnu:b5bavg7) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/include/librpma.h#L2175)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn or cq or is_rcq are NULL
>  * - RPMA_E_NOT_SHARED_CHNL - completion channel is NULL
> ```

RPMA_E_NOT_SHARED_CHANNEL



_Code quote:_
```objc
RPMA_E_NOT_SHARED_CHNL
```


<!-- Sent from Reviewable.io -->

2022-04-15 07:20 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/conn/conn-wait.c, line 74 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g4u-u3aHutlkZXDX0:-N-g4u-vDrw1NLn021Lu:b5bavg7) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L74)):*
> ```C
> 
> 	/* verify the results */
> 	assert_int_equal(ret, RPMA_E_NOT_SHARED_CHNL);
> ```

RPMA_E_NOT_SHARED_CHANNEL



_Code quote:_
```C
RPMA_E_NOT_SHARED_CHNL
```


<!-- Sent from Reviewable.io -->

2022-04-15 07:22 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/conn.c, line 217 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g5JWWA8kz2lznVOnH:-N-g5JWWA8kz2lznVOnI:bymcqdi) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/conn.c#L217)):*
> ```C
> rpma_conn_wait(struct rpma_conn *conn, struct rpma_cq **cq, bool *is_rcq)
> {
> 	if (conn == NULL || cq == NULL || is_rcq == NULL)
> ```

is_rcq is optional



_Code quote:_
```C
 || is_rcq == NULL
```
___
*[src/include/librpma.h, line 2174 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g5PfJ68f9zT72Zjja:-N-g5PfJ68f9zT72Zjjb:bymcqdi) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/include/librpma.h#L2174)):*
> ```objc
>  * rpma_conn_wait() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - conn or cq or is_rcq are NULL
> ```

is_rcq is optional



_Code quote:_
```objc
is_rcq are NULL
```


<!-- Sent from Reviewable.io -->

2022-04-15 07:23 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/conn.c, line 217 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g5JWWA8kz2lznVOnH:-N-g5b0EAa4wQTcf7-E6:bv4r85z) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/conn.c#L217)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is_rcq is optional
</blockquote></details>

Please, see
```
		if (is_rcq)
			*is_rcq = false;
```
below.


<!-- Sent from Reviewable.io -->

2022-04-15 07:30 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/conn/conn-wait.c, line 61 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g6a7u1LInGZCUAlWH:-N-g6a7u1LInGZCUAlWI:biay5ea) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L61)):*
> ```C
> 
> /*
>  * wait__channel_NULL - NULL conn->channel is invalid
> ```

channel_not_shared



_Code quote:_
```C
channel_NULL
```
___
*[tests/unit/conn/conn-wait.c, line 64 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g6dbr-dlvlzN-gHY9:-N-g6dbr-dlvlzN-gHYA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L64)):*
> ```C
>  */
> static void
> wait__channel_NULL(void **cstate_ptr)
> ```

.



_Code quote:_
```C
channel_NULL
```
___
*[tests/unit/conn/conn-wait.c, line 160 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g6pvi-WEKc_rBj6wG:-N-g6pvi-WEKc_rBj6wH:b-f54t84) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L160)):*
> ```C
>  */
> static void
> wait__success(void **cstate_ptr)
> ```

A "success" test is missing, for is_rcq with a NULL value.



_Code quote:_
```C
wait__success
```


<!-- Sent from Reviewable.io -->

2022-04-15 08:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[src/conn.c, line 217 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g5JWWA8kz2lznVOnH:-N-gH-wZCJOkbun6SUPA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/conn.c#L217)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please, see
```
		if (is_rcq)
			*is_rcq = false;
```
below.
</blockquote></details>

Done.
___
*[src/conn.c, line 221 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g4ifr8Aq3aZx71bbN:-N-gHAAZ5ZqPmipOnI01:bqdbzje) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/conn.c#L221)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

RPMA_E_NOT_SHARED_CHANNEL
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/38100205/ss6H8QTX1r0y2x5AcsT4sUom/image.png)
Your proposal will be too long
___
*[src/include/librpma.h, line 2174 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g5PfJ68f9zT72Zjja:-N-gHPdhBq_NVqcsDVel:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/include/librpma.h#L2174)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is_rcq is optional
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2175 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g4UKL8EPwqmEe7rnt:-N-gHQiu4dvI54F805re:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/src/include/librpma.h#L2175)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

RPMA_E_NOT_SHARED_CHANNEL
</blockquote></details>

.
___
*[tests/unit/conn/conn-wait.c, line 61 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g6a7u1LInGZCUAlWH:-N-gHg2a7qjaCUUK82f1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

channel_not_shared
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-wait.c, line 64 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g6dbr-dlvlzN-gHY9:-N-gHgXY0uKuK-Y25DcU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tests/unit/conn/conn-wait.c, line 74 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g4u-u3aHutlkZXDX0:-N-gHhfN11BHNlkT6zp1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L74)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

RPMA_E_NOT_SHARED_CHANNEL
</blockquote></details>

.
___
*[tests/unit/conn/conn-wait.c, line 160 at r9](https://reviewable.io/reviews/pmem/rpma/1655#-N-g6pvi-WEKc_rBj6wG:-N-gICFx7R34X4IzSYU9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/547ff467f2cf285967cd382bb8d71ce947e9749a/tests/unit/conn/conn-wait.c#L160)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

A "success" test is missing, for is_rcq with a NULL value.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-15 08:53 UTC, ldorau reviewed
> Reviewed 3 of 6 files at r9, 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-15 09:09 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655#-:-N-gJaS_-mDEot7zsA55:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-04-15 09:10 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-04-15 09:10 UTC, merged

2022-04-15 09:13 UTC, grom72 approved these changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1655)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->