examples: fix a compiler error about undeclared variable
pmem/rpma pull request #1657
Opened 2022-04-13 14:14 UTC by yangx-jy

Undeclared IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE and IBV_ADVISE_MR_FLAG_FLUSH
on old libibverbs broke the compilation of examples.  Fix the issue by
defining them internally.

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1657)

2022-04-13 14:16 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1657#-N-YGqz-3bfoT1HBGITL):*
What Linux distros/versions do you want to fix?



_Code quote:_
```
on old libibverbs
```


<!-- Sent from Reviewable.io -->

2022-04-13 18:25 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1657#-N-YGqz-3bfoT1HBGITL):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Please see the detailed error:
```
[ 91%] Building C object examples/CMakeFiles/example-04-write-to-persistent-server.dir/04-write-to-persistent/server.c.o
/root/rpma/examples/04-write-to-persistent/server.c: In function ‘main’:
/root/rpma/examples/04-write-to-persistent/server.c:163:4: error: ‘IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE’ undeclared (first use in this function)
  163 |    IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE,
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/rpma/examples/04-write-to-persistent/server.c:163:4: note: each undeclared identifier is reported only once for each function it appears in
/root/rpma/examples/04-write-to-persistent/server.c:164:4: error: ‘IBV_ADVISE_MR_FLAG_FLUSH’ undeclared (first use in this function)
  164 |    IBV_ADVISE_MR_FLAG_FLUSH);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [examples/CMakeFiles/example-04-write-to-persistent-server.dir/build.make:83: examples/CMakeFiles/example-04-write-to-persistent-server.dir/04-write-to-persistent/server.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4402: examples/CMakeFiles/example-04-write-to-persistent-server.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```
</blockquote></details>

We have intentionally dropped support for OSes that do not support `IBV_ADVISE_MR_FLAG_FLUSH` and `IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE`: https://github.com/pmem/rpma/commit/99c0b8e83cd64f719fff55a2dd4e12bc92a80a9d and https://github.com/pmem/rpma/commit/cabb2def20336dde432ce718c343fd206a26c220

Those macros are used only in examples, so you can just skip compiling examples:
```sh
[/rpma/build] $ cmake .. -DBUILD_EXAMPLES=OFF && make
```
or define them by yourself as you want ...
___
*[examples/common/common-conn.h, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1657#-N-Z91gqBpr8Jtx8d6n6:-N-Z91gqBpr8Jtx8d6n7:b-sf3vhp) ([raw file](https://github.com/pmem/rpma/blob/6888579b94ca9b88aa1be2a0da7b6a9abd5d320a/examples/common/common-conn.h#L32)):*
> ```objc
> 
> #ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
> #define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 1
> ```

... Adding such definitions could cause that those examples would not work or would work in a wrong way on some OSes.

I am afraid we cannot do that.  @grom72 what do you think?



_Code quote:_
```objc
#ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 1
#endif

#ifndef IBV_ADVISE_MR_FLAG_FLUSH
#define IBV_ADVISE_MR_FLAG_FLUSH 1
#endif
```


<!-- Sent from Reviewable.io -->

2022-04-14 05:54 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1657#-N-YGqz-3bfoT1HBGITL):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We have intentionally dropped support for OSes that do not support `IBV_ADVISE_MR_FLAG_FLUSH` and `IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE`: https://github.com/pmem/rpma/commit/99c0b8e83cd64f719fff55a2dd4e12bc92a80a9d and https://github.com/pmem/rpma/commit/cabb2def20336dde432ce718c343fd206a26c220

Those macros are used only in examples, so you can just skip compiling examples:
```sh
[/rpma/build] $ cmake .. -DBUILD_EXAMPLES=OFF && make
```
or define them by yourself as you want ...



</blockquote></details>

Fedora EOL date is 26 May 2020. It is almost two years from today. I do see any added value to supporting such an old system.

https://endoflife.date/fedora

If we want to support old OSes it will be better to disable rpma_mr_advice() fully, for example, by undefining ``IBV_ADVISE_MR_SUPPORTED``. 
Then we could create private definitions of missing ``IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE`` and ``IBV_ADVISE_MR_FLAG_FLUSH`` as we know they never will be used.

@ldorau macros are used in examples only, but they are part of librpma API, so we have to either support it or not. 

It seems that we have to be very careful to use libibverbs definitions as a part of librpma public API. My fault :(. 
___
*[examples/common/common-conn.h, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1657#-N-Z91gqBpr8Jtx8d6n6:-N-aat4N2NAuq4QdRnNP:b-apayz0) ([raw file](https://github.com/pmem/rpma/blob/6888579b94ca9b88aa1be2a0da7b6a9abd5d320a/examples/common/common-conn.h#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... Adding such definitions could cause that those examples would not work or would work in a wrong way on some OSes.

I am afraid we cannot do that.  @grom72 what do you think?


</blockquote></details>

See my comment above.


<!-- Sent from Reviewable.io -->

2022-04-14 07:42 UTC, yangx-jy commented
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1657#-N-YGqz-3bfoT1HBGITL):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Fedora EOL date is 26 May 2020. It is almost two years from today. I do see any added value to supporting such an old system.

https://endoflife.date/fedora

If we want to support old OSes it will be better to disable rpma_mr_advice() fully, for example, by undefining ``IBV_ADVISE_MR_SUPPORTED``. 
Then we could create private definitions of missing ``IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE`` and ``IBV_ADVISE_MR_FLAG_FLUSH`` as we know they never will be used.

@ldorau macros are used in examples only, but they are part of librpma API, so we have to either support it or not. 

It seems that we have to be very careful to use libibverbs definitions as a part of librpma public API. My fault :(. 
</blockquote></details>

I also don't think fedora30 is too old.

Agreed. these macros and `ibv_advise_mr()` are introduced at the same time so these internal definitions just fix the compiler error and never will be used.

Do you want to add these internal definitions in librpma.h?


<!-- Sent from Reviewable.io -->

2022-04-15 10:13 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1657#-N-YGqz-3bfoT1HBGITL):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I also don't think fedora30 is too old.

Agreed. these macros and `ibv_advise_mr()` are introduced at the same time so these internal definitions just fix the compiler error and never will be used.

Do you want to add these internal definitions in librpma.h?
</blockquote></details>

The proper solution will be to exclude `rpma_mr_advise()` from librpma.h if it is not fully supported by OS/ibverbs/compilers.
The same flag/macro can be used for all examples and additionally, we should port this solution to the Fio engine.

But finally, it is clearly stated in `https://github.com/pmem/rpma/blob/master/INSTALL.md` that librpma is supported for Fedora >32


<!-- Sent from Reviewable.io -->

2022-04-22 13:06 UTC, grom72 reviewed
It is not only a problem of examples but also an end-users application as well.
I think the best way will be to undefine rpma_mr_advise() in librpma.h if any above-mentioned macro is undefined.
```
#ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
#define  rpma_mr_advise(mt, offset, len, advice, flags) (RPMA_E_NOSUPP)
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0
#ifndef IBV_ADVISE_MR_FLAG_FLUSH
#define IBV_ADVISE_MR_FLAG_FLUSH 0
#else
#ifndef IBV_ADVISE_MR_FLAG_FLUSH
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0
#define IBV_ADVISE_MR_FLAG_FLUSH 0
#else 
int rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len, int advice, uint32_t flags);
#endif
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0GGHwgDgJAiHhCQvvm:b53ads5)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-25 07:12 UTC, yangx-jy commented
Hi @grom72 @ldorau 

Yes, this problem can be caused by both examples and end-user applications.
To be honest, it's hard to remove the definition of rpma_mr_advise when  IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE is not defined.
So I try to do the following change on my v2 patch set.
1) define advice and flags internally in librpma.h when they are undefined.
2) update description about when rpma_mr_advise(3) will return RPMA_E_NOSUPP.
3) continue running examples when rpma_mr_advise(3) returns RPMA_E_NOSUPP.

With this patch set, I think we can revert commit 99c0b8e and cabb2de





<!-- Sent from Reviewable.io -->

2022-04-25 10:09 UTC, grom72 requested changes
Hi @yangx-jy  

We could keep new (dummy) definitions in librpma.h but we must disable rpma_mr_advice() fully:

```
#ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0
#define RPMA_SKIP_MR_ADVICE 1
#endif
#ifndef IBV_ADVISE_MR_FLAG_FLUSH
#define IBV_ADVISE_MR_FLAG_FLUSH 0
#define RPMA_SKIP_MR_ADVICE 1
#endif
...
etc.
...
```

```
...
int
rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len,
		int advice, uint32_t flags)
{
#ifdef IBV_ADVISE_MR_SUPPORTED && !defined RPMA_SKIP_MR_ADVICE
...
```

> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0V5ooq5PWgy2PT-lS-:buvcq9j)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/include/librpma.h` line 1170 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBFlP0ZztAWOJzBK8:-N0VBFlP0ZztAWOJzBK9:b-p4unif) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1170)):*
> ```objc
> 
> #ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
> #define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE	1
> ```

Dummy (``0``) value:
``#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE	0``



_Code quote:_
```objc
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE	1
```
___
*[`src/include/librpma.h` line 1174 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBKUo7j9P1mqE3fwP:-N0VBKUo7j9P1mqE3fwQ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1174)):*
> ```objc
> 
> #ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT
> #define IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT	2
> ```

.



_Code quote:_
```objc
#define IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT	2
```
___
*[`src/include/librpma.h` line 1178 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBM1X-mcD8X5Hp4c8:-N0VBM1X-mcD8X5Hp4c9:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1178)):*
> ```objc
> 
> #ifndef IBV_ADVISE_MR_FLAG_FLUSH
> #define IBV_ADVISE_MR_FLAG_FLUSH	1
> ```

.



_Code quote:_
```objc
#define IBV_ADVISE_MR_FLAG_FLUSH	1
```


<!-- Sent from Reviewable.io -->

2022-04-25 14:53 UTC, yangx-jy commented
Hi @grom72 

First, we don't need to define both IBV_ADVISE_MR_SUPPORTED and RPMA_SKIP_MR_ADVICE(IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE ) macros because they are introcuded by the same commit b341e606265f

Second, the following change has the same effect as the original logic:
```
int
rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len,
		int advice, uint32_t flags)
{
#ifdef IBV_ADVISE_MR_SUPPORTED && !defined RPMA_SKIP_MR_ADVICE
```
The original logic is:
```
int
rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len,
                int advice, uint32_t flags)
{
#ifdef IBV_ADVISE_MR_SUPPORTED
```

Third, we want to disable rpma_mr_advise() fullly when IBV_ADVISE_MR_SUPPORTED or RPMA_SKIP_MR_ADVICE is defined.
However, it's hard to disable/drop the mannual of rpma_mr_advise() by IBV_ADVISE_MR_SUPPORTED or RPMA_SKIP_MR_ADVICE in this condition.





<!-- Sent from Reviewable.io -->

2022-04-25 17:35 UTC, grom72 reviewed
That means that instead of ``RPMA_SKIP_MR_ADVICE`` we have to undefine ``IBV_ADVISE_MR_SUPPORTED`` in librpma.h:
```
#ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0xFFFF
#ifdef IBV_ADVISE_MR_SUPPORTED
#undef IBV_ADVISE_MR_SUPPORTED
#endif
#endif
#ifndef IBV_ADVISE_MR_FLAG_FLUSH
#define IBV_ADVISE_MR_FLAG_FLUSH 0xFFFF
#ifdef IBV_ADVISE_MR_SUPPORTED
#undef IBV_ADVISE_MR_SUPPORTED
#endif
#endif
...
etc.
...
```
but additionally, we have to detect the situation when rpma_mr_advise() is called with flags that are not properly defined.
```
int
rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len,
                int advice, uint32_t flags)
{
#ifdef IBV_ADVISE_MR_SUPPORTED
        if (0xFFFF == flags & 0xFFFF) 
                return RPMA_E_NOSUPP;
...
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0WkXyA-5xVEzL8j12q:by2y9xh)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-04-26 02:00 UTC, yangx-jy commented
Hi @grom72

Why not set advise/flags argument to the correct value when they are undefined and then let rpma_mr_advise() check if  ibv_advise_mr()/advise/flags is not supported inside?  In this method, current implementation of rpma_mr_advise() is good and we don't need to care when rpma_mr_advise() is called with unsupported argument.

I think we still keep the original logic that always provides rpma_mr_advise() and returns RPMA_E_NOSUPP due to unsupported ibv_advise_mr()/advise/flags argument. Right?





<!-- Sent from Reviewable.io -->

2022-04-26 04:10 UTC, grom72 reviewed
How can we check inside rpma_mr_advice() that flags are defined locally (in librpma.h)?
I refer to a comment from @ldorau that we should not use these flags when they are not officially available.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0Z2VBt1ybtoVsEKgUz:bswc90n)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-04-26 05:56 UTC, yangx-jy commented
I think rpma_mr_advise() and ibv_advise_mr() can check if these local definitions (in librpma.h) are supported by libibverbs and provider driver successfully.

Commit b341e606265f added ibv_advise_mr(), two advise arguments (i.e. IBV_ADVISE_MR_ADVICE_PREFETCH, IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE) and a flag argument (i.e. IBV_ADVISE_MR_FLAG_FLUSH) for libibverbs.

IBV_ADVISE_MR_SUPPORTED is used to check if ibv_advise_mr() is supported by libibverbs. When ibv_advise_mr() is not supported by libibverbs, both IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE and IBV_ADVISE_MR_FLAG_FLUSH are not defined as well.  So rpma_mr_advise() always outputs "ibv_advise_mr() is not supported by libibverbs" and returns RPMA_E_NOSUPP

When IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE, IBV_ADVISE_MR_FLAG_FLUSH and ibv_advise_mr() are supported by libibverbs but they are not supported by provider dirver(e.g. rxe), rpma_mr_advise() outputs "ibv_advise_mr() with errno" and returns RPMA_E_NOSUPP.


When IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE, IBV_ADVISE_MR_FLAG_FLUSH and ibv_advise_mr() are supported by libibverbs and  provider dirver(e.g. mlx5) but IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT is not supported, rpma_mr_advise() outputs "ibv_advise_mr() with errno" and returns RPMA_E_NOSUPP.





<!-- Sent from Reviewable.io -->

2022-04-26 07:32 UTC, grom72 reviewed
1) How can ``ibv_advise_mr()`` detect that it does not support ``IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT``?
It is just a bit in the flag attribute. 
2) We cannot expect ``ibv_advise_me()`` to behave properly with ``IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT`` defined in ``librpma.h`` with a random value.
3) The solution must be fully transparent from a user's application perspective. No changes to build scripts due to some features of old Fedora 30. 
If we know that Fedora 30 does not support these flags we have to:
- inform the user about that. (``#warning ...``)
- disable ibv_advise_mr() fully as we cannot say anything about its behavior when undefined values are used for flags parameters initialization

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0ZiBXB2hvK7TJLwfSK:beeltwy)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-04-26 08:40 UTC, yangx-jy commented
> How can ibv_advise_mr() detect that it does not support IBV_ADVISE_MR_ADVICE_PREFETCH_NO_FAULT?
It is checked by mlx5 kernel driver. Please the kernel commit:
```
commit 677cf51f71c97bcf98852aa2077d7289bc73e3b3
Author: Yishai Hadas <yishaih@nvidia.com>
Date:   Wed Sep 30 19:38:27 2020 +0300

    RDMA/mlx5: Extend advice MR to support non faulting mode
```

How about defining RPMA_XXX advise and flags arguments and convert them to IBV_XXX in rpma_mr_advise()?





<!-- Sent from Reviewable.io -->

2022-04-26 15:07 UTC, grom72 reviewed
We have already discussed internally an option to define RPMA_XXX but decided to abandon it as it does not add any new value in this particular case.
As you see from other areas we are going to make librpma lighter and lighter.
Q: do we really need to support Fedora 30?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0aP45I5kzhJMt0qgRY:bb0zlvf)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-04-27 01:48 UTC, yangx-jy commented
I hope librpma can be supported and used on as many as  distributions.
I don't want a minor point make the whole librpma not work on older distributions.( In other words, the whole librpma except rpma_advise_mr() works normally on older distributions).





<!-- Sent from Reviewable.io -->

2022-04-27 05:56 UTC, grom72 requested changes
Therefore, I suggest disableing``rpma_mr_advice()`` - ``return RPMA_E_NOSUPP;`` when any flag that is needed for ibv_mr_advice is missing.
We have to do it in such a way that if somebody instal binary librpma package on the OS that does not have a proper version of libibverbs then rpma_mr_advice() will behave properly. See my comment above with flags set to ``0xFFFF``:

```
/* librpma.h */
...
#ifndef IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0xFFFF
#endif
#ifndef IBV_ADVISE_MR_FLAG_FLUSH
#define IBV_ADVISE_MR_FLAG_FLUSH 0xFFFF
#endif
...
etc.
...
```
and
```
int
rpma_mr_advise(struct rpma_mr_local *mr, size_t offset, size_t len,
                int advice, uint32_t flags)
{
#ifdef IBV_ADVISE_MR_SUPPORTED
        if (0xFFFF == flags & 0xFFFF) 
                return RPMA_E_NOSUPP;
...
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0dWk4C154Yo5gKKsqA:b-rffcww)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/mr.c` line 569 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0dZW7h2ymzwcKMLp-s:-N0dZW7i9tvFFETy_kSP:b-3kuhtk) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/mr.c#L569)):*
> ```C
> 		int advice, uint32_t flags)
> {
> #ifdef IBV_ADVISE_MR_SUPPORTED
> ```

```
if (! (0xFFFFFFFF ^ flags) )
	return RPMA_E_NOSUPP;
```
___
*[`src/include/librpma.h` line 1170 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBFlP0ZztAWOJzBK8:-N0dZBCT-jeCV3yC951q:b-rxtyhz) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1170)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Dummy (``0``) value:
``#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE	0``
</blockquote></details>

```
/* 
 * Disable the ibv_mr_advice() function with dummy (0xFFFF) flags when incomplete flags' definition is detected.
 */
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0xFFFFFFFF
```
___
*[`src/include/librpma.h` line 1174 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBKUo7j9P1mqE3fwP:-N0dZDnT9wyjN5och1Uv:b-1i2gzu) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1174)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

```
#define IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE 0xFFFFFFFF
```
___
*[`src/include/librpma.h` line 1178 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBM1X-mcD8X5Hp4c8:-N0dZHuZ-YXE1pfyCt9w:b-t0bqay) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1178)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

#define IBV_ADVISE_MR_FLAG_FLUSH	0xFFFF


<!-- Sent from Reviewable.io -->

2022-04-27 10:24 UTC, ldorau requested changes
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/mr.c` line 569 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0dZW7h2ymzwcKMLp-s:-N0eY4Gb1DDfhT4NCu5-:b-mtmhs5) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/mr.c#L569)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
if (! (0xFFFFFFFF ^ flags) )
	return RPMA_E_NOSUPP;
```
</blockquote></details>

Yes, `#ifdef IBV_ADVISE_MR_SUPPORTED` will not be needed when missing flags are defined as `0xFFFFFFFF`



_Code quote:_
```C
#ifdef IBV_ADVISE_MR_SUPPORTED
```
___
*[`src/include/librpma.h` line 1178 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBM1X-mcD8X5Hp4c8:-N0eXSp_8LlXWkmnrqng:bn0f8ct) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1178)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

#define IBV_ADVISE_MR_FLAG_FLUSH	0xFFFF
</blockquote></details>

0xFFFFFFFF


<!-- Sent from Reviewable.io -->

2022-04-27 13:06 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/mr.c` line 569 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0dZW7h2ymzwcKMLp-s:-N0f6qci687LpwopHrwk:bjywu9e) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/mr.c#L569)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, `#ifdef IBV_ADVISE_MR_SUPPORTED` will not be needed when missing flags are defined as `0xFFFFFFFF`
</blockquote></details>

``IBV_ADVISE_MR_SUPPORTED`` is set by the CMake script if ibv_mr_advice() is not supported.
The proposed condition will cover situations where ibv_mr_advice() is available but with a limited range of flags.
___
*[`src/include/librpma.h` line 1178 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBM1X-mcD8X5Hp4c8:-N0f7Jz69zO8zO6qe-gh:b-ocki96) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1178)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

0xFFFFFFFF
</blockquote></details>

#define IBV_ADVISE_MR_FLAG_FLUSH	0xFFFFFFFF


<!-- Sent from Reviewable.io -->

2022-04-27 13:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/mr.c` line 569 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0dZW7h2ymzwcKMLp-s:-N0f971-ER2PLsgl12Kx:b-rz0fws) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/mr.c#L569)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``IBV_ADVISE_MR_SUPPORTED`` is set by the CMake script if ibv_mr_advice() is not supported.
Proposed condition will cover situation where ibv_mr_advice() is available but wit limited range of flags.
</blockquote></details>

Ah, right, my mistake.
___
*[`src/include/librpma.h` line 1178 at r4](https://reviewable.io/reviews/pmem/rpma/1657#-N0VBM1X-mcD8X5Hp4c8:-N0f8_ez-JBcSyoO2Zf2:bni3k2e) ([raw file](https://github.com/pmem/rpma/blob/02a489ee5db09cde4f2226a2db953578f83173e8/src/include/librpma.h#L1178)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

#define IBV_ADVISE_MR_FLAG_FLUSH	0xFFFFFFFF
</blockquote></details>

That's exactly what I meant.


<!-- Sent from Reviewable.io -->

2022-05-16 14:35 UTC, yangx-jy commented
Hi @grom72 @ldorau 

After thinking about it again, I don't think this solution is better.  When these arguments and function are not supported, we should make `rpma_mr_advise()` handle them completely by itself or not call `rpma_mr_advise()` directly. I prefer to define RPMA_XXX macros or make application not use `rpma_mr_advise()` by checking IBV_ADVISE_MR_SUPPORTED macro.





<!-- Sent from Reviewable.io -->

2022-07-12 06:26 UTC, grom72 reviewed
Hi @yangx-jy 
please take a look at #1905.
It is @ldorau proposal on how to handle missing ``IBV_ADVICE_*`` on old OSes.
As I already mentioned Fedora 30 passed EOL more than 2 years ago.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N6l3pGnD_sNBNEBdXKn:b-3j2ao9)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-07-19 07:08 UTC, ldorau reviewed
@yangx-jy Could you review #1905 please ?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1657#-:-N0eXYF06kyHvqVTZzDF:bvk2qg1)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-07-20 15:36 UTC, yangx-jy commented
Cool. I will review it tomorrow.  Thanks for your reminder.





<!-- Sent from Reviewable.io -->

2022-07-21 12:02 UTC, closed without merging