rpma: fix memory leak in error handling of rpma_conn_req_connect()
pmem/rpma pull request #1689
Opened 2022-04-22 07:22 UTC by ldorau

It fixes the following memory leak:
```
==43181== HEAP SUMMARY:
==43181==     in use at exit: 36,788 bytes in 92 blocks
==43181==   total heap usage: 457 allocs, 365 frees,
==43181==                     540,985 bytes allocated
==43181==
==43181== 24 bytes in 1 blocks are definitely lost
==43181== in loss record 6 of 22
==43181==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/\
==43181==       valgrind/vgpreload_memcheck-amd64-linux.so)
==43181==    by 0x4852BFF: rpma_cq_new (cq.c:92)
==43181==    by 0x485108D: rpma_conn_req_from_id (conn_req.c:107)
==43181==    by 0x48521AB: rpma_conn_req_new (conn_req.c:434)
==43181==    by 0x1094BB: main (client.c:67)
==43181==
==43181== LEAK SUMMARY:
==43181==    definitely lost: 24 bytes in 1 blocks
==43181==    indirectly lost: 0 bytes in 0 blocks
==43181==      possibly lost: 0 bytes in 0 blocks
==43181==    still reachable: 33,788 bytes in 87 blocks
==43181==         suppressed: 2,976 bytes in 4 blocks
```

2022-04-22 08:37 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1689#-N0FPgvYAik2NEFg-pd7:-N0FPgvYAik2NEFg-pd8:b3h6ku1) (no related file):*
Check https://app.circleci.com/pipelines/github/ldorau/rpma/3122/workflows/a8909f3b-25ea-4606-a04c-b0e230c1c3c7/jobs/3137

---


<!-- Sent from Reviewable.io -->

2022-04-22 12:09 UTC, grom72 requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/conn_req.c, line 419 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G9VUd3YO-tT4Hdzet:-N0G9VUd3YO-tT4Hdzeu:b-ghsgt) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L419)):*
> ```C
> 	const struct rpma_conn_private_data *pdata, struct rpma_conn **conn_ptr)
> {
> 	if (req_ptr == NULL || conn_ptr == NULL)
> ```

```
	if (req_ptr == NULL || (*req_ptr) == NULL || conn_ptr == NULL)
```



_Code quote:_
```C
	if (req_ptr == NULL || conn_ptr == NULL)
```
___
*[src/conn_req.c, line 422 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G8UPe2h1KvLODAesm:-N0G8UPe2h1KvLODAesn:bds0wkj) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L422)):*
> ```C
> 		return RPMA_E_INVAL;
> 
> 	struct rpma_conn_req *req = *req_ptr;
> ```

Do we need ``*req``?



_Suggestion:_
```C
struct rpma_conn_req *req = *req_ptr;
```
___
*[src/conn_req.c, line 423 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G8tGpCBZ2I9mVnSbk:-N0G8tGq738S5e8o6Iyo:b-sx84ma) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L423)):*
> ```C
> 
> 	struct rpma_conn_req *req = *req_ptr;
> 	if (req == NULL)
> ```

obsolete



_Suggestion:_
```C
	if (req == NULL)
		return RPMA_E_INVAL;
```
___
*[src/conn_req.c, line 442 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G9K2F-IIh_u1GAOyT:-N0G9K2GBeYB6mV7fLqB:b97ywfm) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L442)):*
> ```C
> 	int ret = 0;
> 
> 	if (req->edata)
> ```

	if ((*req_ptr)->edata)



_Code quote:_
```C
	if (req->edata)
```
___
*[src/conn_req.c, line 469 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0GA0kG3W55rT2PiCp2:-N0GA0kG3W55rT2PiCp3:bhesn3n) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L469)):*
> ```C
> 		return RPMA_E_INVAL;
> 
> 	struct rpma_conn_req *req = *req_ptr;
> ```

see comments above about ``rpma_conn_req_connect``



_Code quote:_
```C
struct rpma_conn_req *req = *req_ptr;
```


<!-- Sent from Reviewable.io -->

2022-04-25 09:42 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[`src/conn_req.c` line 419 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G9VUd3YO-tT4Hdzet:-N0V4VH-7hsJvv0NJzPi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L419)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
	if (req_ptr == NULL || (*req_ptr) == NULL || conn_ptr == NULL)
```
</blockquote></details>

Done.



_Code quote:_
```C
rpma_conn_req_connect(struct rpma_conn_req **req_ptr,
```
___
*[`src/conn_req.c` line 422 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G8UPe2h1KvLODAesm:-N0V4Vsg-2le-dNel_em:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L422)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need ``*req``?
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 423 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G8tGpCBZ2I9mVnSbk:-N0V4WMn86UYjulBvA-n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L423)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

obsolete
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 442 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0G9K2F-IIh_u1GAOyT:-N0V4Wuz1xMPSl0Ddkyq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L442)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

	if ((*req_ptr)->edata)
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 469 at r2](https://reviewable.io/reviews/pmem/rpma/1689#-N0GA0kG3W55rT2PiCp2:-N0V5CpZ3TSht4viBoPX:bz9knv5) ([raw file](https://github.com/pmem/rpma/blob/4d12a26a35cfbfcff68d107cff8c88d4e9776ba0/src/conn_req.c#L469)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

see comments above about ``rpma_conn_req_connect``
</blockquote></details>

`req` is needed in `rpma_conn_req_delete` - it is used many times and it is more clear now.



_Code quote:_
```C
rpma_conn_req_delete(struct rpma_conn_req **req_ptr)
```


<!-- Sent from Reviewable.io -->

2022-04-25 10:20 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/conn_req.c` line 181 at r3](https://reviewable.io/reviews/pmem/rpma/1689#-N0VD7NT2bF9Dbfwva6h:-N0VD7NT2bF9Dbfwva6i:b-dy2nz1) ([raw file](https://github.com/pmem/rpma/blob/8232da768e76c65085e66767cca01a5b4e469654/src/conn_req.c#L181)):*
> ```C
>  *
>  * ASSUMPTIONS
>  * - req_ptr != NULL && conn_param != NULL && conn_ptr != NULL
> ```

* - req_ptr != NULL && *req_ptr != NULL && conn_param != NULL && conn_ptr != NULL



_Code quote:_
```C
* - req_ptr != NULL && conn_param != NULL && conn_ptr != NULL
```
___
*[`src/conn_req.c` line 224 at r3](https://reviewable.io/reviews/pmem/rpma/1689#-N0VDFrO70Z1YVLXRWX6:-N0VDFrO70Z1YVLXRWX7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8232da768e76c65085e66767cca01a5b4e469654/src/conn_req.c#L224)):*
> ```C
>  *
>  * ASSUMPTIONS
>  * - req_ptr != NULL && conn_param != NULL && conn_ptr != NULL
> ```

.



_Code quote:_
```C
 * - req_ptr != NULL && conn_param != NULL && conn_ptr != NULL
```
___
*[`src/conn_req.c` line 419 at r3](https://reviewable.io/reviews/pmem/rpma/1689#-N0VDU10-uY4XCi4bMtQ:-N0VDU10-uY4XCi4bMtR:buadgnn) ([raw file](https://github.com/pmem/rpma/blob/8232da768e76c65085e66767cca01a5b4e469654/src/conn_req.c#L419)):*
> ```C
> 	const struct rpma_conn_private_data *pdata, struct rpma_conn **conn_ptr)
> {
> 	if (req_ptr == NULL || *req_ptr == NULL || conn_ptr == NULL)
> ```

Do we have UT for this: (``*req_ptr == NULL``)?
What if line above will look like this:
```
	if (req_ptr == NULL ||
		 *req_ptr == NULL ||
		 conn_ptr == NULL)
```



_Suggestion:_
```C
	if (req_ptr == NULL || *req_ptr == NULL || conn_ptr == NULL)
```


<!-- Sent from Reviewable.io -->

2022-04-25 11:02 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[`src/conn_req.c` line 181 at r3](https://reviewable.io/reviews/pmem/rpma/1689#-N0VD7NT2bF9Dbfwva6h:-N0VN40sB582Mw7T99B6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8232da768e76c65085e66767cca01a5b4e469654/src/conn_req.c#L181)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

* - req_ptr != NULL && *req_ptr != NULL && conn_param != NULL && conn_ptr != NULL
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 224 at r3](https://reviewable.io/reviews/pmem/rpma/1689#-N0VDFrO70Z1YVLXRWX6:-N0VN3PF20O9z0Txk-18:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8232da768e76c65085e66767cca01a5b4e469654/src/conn_req.c#L224)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 419 at r3](https://reviewable.io/reviews/pmem/rpma/1689#-N0VDU10-uY4XCi4bMtQ:-N0VNdYb52BskbWnBBUL:bhs5okx) ([raw file](https://github.com/pmem/rpma/blob/8232da768e76c65085e66767cca01a5b4e469654/src/conn_req.c#L419)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we have UT for this: (``*req_ptr == NULL``)?
What if line above will look like this:
```
	if (req_ptr == NULL ||
		 *req_ptr == NULL ||
		 conn_ptr == NULL)
```
</blockquote></details>

1) Yes, we have
2) Why? What is the difference?



_Code quote:_
```C
rpma_conn_req_connect(struct rpma_conn_req **req_ptr,
```


<!-- Sent from Reviewable.io -->

2022-04-25 12:01 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689#-:-N0VaL7WDxmqqoYoj9Mb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-26 07:55 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1689#-N0FPgvYAik2NEFg-pd7:-N0Zr_GR3Yxnvye6Ua1a:b-lsuxs3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Check https://app.circleci.com/pipelines/github/ldorau/rpma/3122/workflows/a8909f3b-25ea-4606-a04c-b0e230c1c3c7/jobs/3137
</blockquote></details>

Fixed by the 2nd commit "rpma: set req->edata to NULL in rpma_conn_req_accept()"



_Code quote (from -- commits):_
```
rpma: set req->edata to NULL in rpma_conn_req_accept()
```

---


<!-- Sent from Reviewable.io -->

2022-04-26 09:06 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689#-:-N0_6qy24kUV4ClXIlg8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-26 12:11 UTC, grom72 requested changes
<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689#-:-N0_lSTDEm-QY5d4l9J7:b8b79qu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_req.c` line 443 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_lXBe1Wy2h3Etiagr:-N0_lXBe1Wy2h3Etiags:bldo58j) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L443)):*
> ```C
> 		ret = rpma_conn_req_connect_active(req_ptr, &conn_param, conn_ptr);
> 
> 	if (ret) {
> ```

Is this part of code lead to next memory leak?



_Code quote:_
```C
	if (ret) {
		rpma_conn_req_delete(req_ptr);
		return ret;
	}
```


<!-- Sent from Reviewable.io -->

2022-04-26 12:17 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_req.c` line 443 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_lXBe1Wy2h3Etiagr:-N0_nKQ75e73UdByUxSe:b-cjb9b3) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L443)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is this part of code lead to next memory leak?
</blockquote></details>

It fixes this memory leak.


<!-- Sent from Reviewable.io -->

2022-04-26 12:39 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`src/conn_req.c` line 184 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_ruOaEI4AObq5_qCC:-N0_ruOb3HaOZHXDXOrG:b-rfiuxk) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L184)):*
> ```C
>  */
> static int
> rpma_conn_req_accept(struct rpma_conn_req **req_ptr,
> ```

Is it still needed? I mean "a pointer to pointer" 



_Code quote:_
```C
**req_ptr
```
___
*[`src/conn_req.c` line 227 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_rY5b2mkhDkFj_0Tb:-N0_rY5b2mkhDkFj_0Tc:b-rfiuxk) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L227)):*
> ```C
>  */
> static int
> rpma_conn_req_connect_active(struct rpma_conn_req **req_ptr,
> ```

Is it still needed? I mean "a pointer to pointer" 



_Code quote:_
```C
**req_ptr
```
___
*[`src/conn_req.c` line 443 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_lXBe1Wy2h3Etiagr:-N0_qCnC9YYsw864jTj5:byrb3vh) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L443)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It fixes this memory leak.
</blockquote></details>

But it is open another one so the question is: is it a proper fix?


<!-- Sent from Reviewable.io -->

2022-04-26 12:51 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/conn_req.c` line 184 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_ruOaEI4AObq5_qCC:-N0_v-yC6R2lUMKQeKr9:b-yifx5n) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it still needed? I mean "a pointer to pointer" 
</blockquote></details>

Yes, it is. It always was and it still is. Nothing has changed.
___
*[`src/conn_req.c` line 227 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_rY5b2mkhDkFj_0Tb:-N0_vEnz5kd30ND0zynr:b-yifx5n) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L227)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it still needed? I mean "a pointer to pointer" 
</blockquote></details>

Yes, it is. It always was and it still is. Nothing has changed.
___
*[`src/conn_req.c` line 443 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_lXBe1Wy2h3Etiagr:-N0_vJzy18Vmgy2SDQ7_:b-dfw7aq) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L443)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But it is open another one so the question is: is it a proper fix?
</blockquote></details>

Yes, it is an open question.


<!-- Sent from Reviewable.io -->

2022-04-26 15:04 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/conn_req.c` line 184 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_ruOaEI4AObq5_qCC:-N0aNILB4VnWQ30ewjFJ:b9nd7xl) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L184)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it is. It always was and it still is. Nothing has changed.
</blockquote></details>

It was ``rpma_conn_req_accept(struct rpma_conn_req *req ... `` originaly.



_Suggestion:_
```C
rpma_conn_req_accept(struct rpma_conn_req **req_ptr
```
___
*[`src/conn_req.c` line 227 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_rY5b2mkhDkFj_0Tb:-N0aO74p2EE--VYwA_S5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L227)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it is. It always was and it still is. Nothing has changed.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-04-26 19:42 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/conn_req.c` line 184 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_ruOaEI4AObq5_qCC:-N0bMxVk5T7r7UoXibj8:b78glrb) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It was ``rpma_conn_req_accept(struct rpma_conn_req *req ... `` originaly.
</blockquote></details>

Yes, originally yes, of course, but this fix requires this change. I meant: this fix always required it. "always" and "still" meant: "from the beginning of this PR". 
___
*[`src/conn_req.c` line 227 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_rY5b2mkhDkFj_0Tb:-N0bNOVy3Wc-riR7qS2V:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L227)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-04-26 20:23 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/conn_req.c` line 184 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_ruOaEI4AObq5_qCC:-N0bWou4DtxWGpmKkWNr:b-p8iw7h) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L184)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, originally yes, of course, but this fix requires this change. I meant: this fix always required it. "always" and "still" meant: "from the beginning of this PR". 
</blockquote></details>

I mean we do not change the value of  ``*req_ptr`` so the function definition can be as follow:
```
static int
rpma_conn_req_accept(struct rpma_conn_req *ptr, 
	struct rdma_conn_param *conn_param, struct rpma_conn **conn_ptr)
```



_Suggestion:_
```C
static int
rpma_conn_req_accept(struct rpma_conn_req **req_ptr,
	struct rdma_conn_param *conn_param, struct rpma_conn **conn_ptr)
```


<!-- Sent from Reviewable.io -->

2022-04-27 09:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1689)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/conn_req.c` line 184 at r6](https://reviewable.io/reviews/pmem/rpma/1689#-N0_ruOaEI4AObq5_qCC:-N0eROF50h-nVxjsLBcn:bpkrn2t) ([raw file](https://github.com/pmem/rpma/blob/ae104e8149660c69728f1ca71c09b189fecd728d/src/conn_req.c#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I mean we do not change the value of  ``*req_ptr`` so the function definition can be as follow:
```
static int
rpma_conn_req_accept(struct rpma_conn_req *ptr, 
	struct rdma_conn_param *conn_param, struct rpma_conn **conn_ptr)
```
</blockquote></details>

Yes, you are right.


<!-- Sent from Reviewable.io -->

2022-04-27 11:07 UTC, ldorau commented
Wrong fix

2022-04-27 11:07 UTC, closed without merging