test: change type of arguments of setup__peer() and teardown__peer()
pmem/rpma pull request #1693
Opened 2022-04-22 10:59 UTC by ldorau

Use `struct peer_prestate` as an argument in both `setup__peer()`
and `teardown__peer()` instead of `in_out`.

2022-04-22 12:14 UTC, grom72 requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/unit/peer/peer-common.c, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1693#-N0GBGSO1Rn-nnd6uehQ:-N0GBGSO1Rn-nnd6uehR:btsoosk) ([raw file](https://github.com/pmem/rpma/blob/085e177016f3d8027ca16a9f604cfb1ba563fd55/tests/unit/peer/peer-common.c#L26)):*
> ```C
>  */
> int
> setup__peer(void **cstate_ptr)
> ```

Do we need both ``setup__peer`` and ``setup__peer_prestates``



_Code quote:_
```C
setup__peer_prestates
```
___
*[tests/unit/peer/peer-common.c, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1693#-N0GBT8u16Gw_Sb445BU:-N0GBT8u16Gw_Sb445BV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/085e177016f3d8027ca16a9f604cfb1ba563fd55/tests/unit/peer/peer-common.c#L53)):*
> ```C
>  */
> int
> teardown__peer(void **cstate_ptr)
> ```

.



_Code quote:_
```C
teardown__peer
```


<!-- Sent from Reviewable.io -->

2022-04-22 12:18 UTC, grom72 reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-22 12:18 UTC, grom72 reviewed
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-22 16:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/unit/peer/peer-common.c, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1693#-N0GBGSO1Rn-nnd6uehQ:-N0H4PXo6hBUVqy7loqk:b-pkie6n) ([raw file](https://github.com/pmem/rpma/blob/085e177016f3d8027ca16a9f604cfb1ba563fd55/tests/unit/peer/peer-common.c#L26)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need both ``setup__peer`` and ``setup__peer_prestates``
</blockquote></details>

No, not now, removed.
___
*[tests/unit/peer/peer-common.c, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1693#-N0GBT8u16Gw_Sb445BU:-N0H4Ssy4UG3F2yEYjGK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/085e177016f3d8027ca16a9f604cfb1ba563fd55/tests/unit/peer/peer-common.c#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-04-22 18:23 UTC, grom72 requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/peer/peer-common.c, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1693#-N0HVLeb6cdIMHMPlXYc:-N0HVLeb6cdIMHMPlXYd:bepdmfl) ([raw file](https://github.com/pmem/rpma/blob/69b608218ce07c8868d9d9f88ad9a9123e4b6a1f/tests/unit/peer/peer-common.c#L57)):*
> ```C
> {
> 	struct prestate *prestate = *pprestate;
> ```

Do not we need this here:
```
	if (cstate->peer == NULL)
		return 0;
```


<!-- Sent from Reviewable.io -->

2022-04-22 18:24 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/peer/peer-common.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1693#-N0HVtrc-X1Xk_hlIPdH:-N0HVtrc-X1Xk_hlIPdI:b-78ngwx) ([raw file](https://github.com/pmem/rpma/blob/69b608218ce07c8868d9d9f88ad9a9123e4b6a1f/tests/unit/peer/peer-common.c#L18)):*
> ```C
> #include "test-common.h"
> 
> struct prestate prestate_OdpCapable = {0, 0, 0, MOCK_ODP_CAPABLE, NULL};
> ```

Would it be better to have is_odp_capable as the first field in the ``struct prestate ``?



_Code quote:_
```C
0, 0, 0, MOCK_ODP_CAPABLE, NULL
```


<!-- Sent from Reviewable.io -->

2022-04-23 08:59 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/unit/peer/peer-common.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1693#-N0HVtrc-X1Xk_hlIPdH:-N0KdQBI-CrcWODnoIpK:bbudz10) ([raw file](https://github.com/pmem/rpma/blob/69b608218ce07c8868d9d9f88ad9a9123e4b6a1f/tests/unit/peer/peer-common.c#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would it be better to have is_odp_capable as the first field in the ``struct prestate ``?
</blockquote></details>

No, it does not matter.



_Code quote:_
```C
struct prestate prestate_OdpCapable 
```
___
*[tests/unit/peer/peer-common.c, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1693#-N0HVLeb6cdIMHMPlXYc:-N0KcVigCQl263hn3EEo:b-3ozjnu) ([raw file](https://github.com/pmem/rpma/blob/69b608218ce07c8868d9d9f88ad9a9123e4b6a1f/tests/unit/peer/peer-common.c#L57)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do not we need this here:
```
	if (cstate->peer == NULL)
		return 0;
```
</blockquote></details>

No, we don't.


<!-- Sent from Reviewable.io -->

2022-04-23 11:37 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/peer/peer-common.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1693#-N0HVtrc-X1Xk_hlIPdH:-N0LC36e4Is2dyj7V3Wn:baytc5e) ([raw file](https://github.com/pmem/rpma/blob/69b608218ce07c8868d9d9f88ad9a9123e4b6a1f/tests/unit/peer/peer-common.c#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it does not matter.
</blockquote></details>

It is better/easier/more userfriendly to keep ``0`` after meaningful values in such a place.


<!-- Sent from Reviewable.io -->

2022-04-23 11:38 UTC, grom72 approved these changes
:goat:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693#-:-N0LCaV6B6kbQbAzeGDX:bnd2vnu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-25 06:28 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/peer/peer-common.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1693#-N0HVtrc-X1Xk_hlIPdH:-N0UNiGPD7HB-UZ9sDSy:bwal8dt) ([raw file](https://github.com/pmem/rpma/blob/69b608218ce07c8868d9d9f88ad9a9123e4b6a1f/tests/unit/peer/peer-common.c#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It is better/easier/more userfriendly to keep ``0`` after meaningful values in such a place.
</blockquote></details>

I just do not want to edit and change all other constant values of this structure in all other files:
https://github.com/pmem/rpma/blob/master/tests/unit/peer/peer-mr_reg.c#L22-L72


<!-- Sent from Reviewable.io -->

2022-04-25 08:25 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1693#-:-N0Uos1g09U32WRojrad:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-25 08:40 UTC, merged