rpma: ack the connection request event in rpma_conn_req_from_cm_event
pmem/rpma pull request #1703
Opened 2022-04-27 09:05 UTC by ldorau

ACK the connection request event and free it
in `rpma_conn_req_from_cm_event()` and do not pass it
to the connection request. Use `is_passive` instead of `edata`
to distinguish between active and passive side.

2022-04-27 11:32 UTC, grom72 requested changes
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[`src/conn_req.c` line 321 at r2](https://reviewable.io/reviews/pmem/rpma/1703#-N0ejGjOBCU8SIeYrA0v:-N0ejGjOBCU8SIeYrA0w:bbsbvuo) ([raw file](https://github.com/pmem/rpma/blob/3a66d013cb74a1f6b04cbb2c11fd40795467f43b/src/conn_req.c#L321)):*
> ```C
>  */
> int
> rpma_conn_req_from_cm_event(struct rpma_peer *peer,
> ```

rdma_ack_cm_event() must be called on all execution paths (including error ones).



_Code quote:_
```C
rpma_conn_req_from_cm_event
```
___
*[`src/conn_req.c` line 325 at r2](https://reviewable.io/reviews/pmem/rpma/1703#-N0em-Js0OvyPxf11JNF:-N0em-Js0OvyPxf11JNG:b45h) ([raw file](https://github.com/pmem/rpma/blob/3a66d013cb74a1f6b04cbb2c11fd40795467f43b/src/conn_req.c#L325)):*
> ```C
> 		struct rpma_conn_req **req_ptr)
> {
> 	if (peer == NULL || edata == NULL || req_ptr == NULL)
> ```





_Suggestion:_
```C
	if (edata == NULL)
		return RPMA_E_INVAL;
	
	if (peer == NULL || req_ptr == NULL ||
		edata->event != RDMA_CM_EVENT_CONNECT_REQUES) {
		ret = RPMA_E_INVAL;
		goto err_ack_cm_event;
	}
```
___
*[`src/conn_req.c` line 333 at r2](https://reviewable.io/reviews/pmem/rpma/1703#-N0emByGB6DH8-yHrP_L:-N0emByGB6DH8-yHrP_M:undefined) ([raw file](https://github.com/pmem/rpma/blob/3a66d013cb74a1f6b04cbb2c11fd40795467f43b/src/conn_req.c#L333)):*
> ```C
> 	struct rpma_conn_req *req = NULL;
> 	int ret = rpma_conn_req_from_id(peer, edata->id, cfg, &req);
> 	if (ret)
> ```





_Suggestion:_
```C
	if (ret)
		goto err_ack_cm_event;
```
___
*[`src/conn_req.c` line 355 at r2](https://reviewable.io/reviews/pmem/rpma/1703#-N0emRkQ9pFUnWJlGDnb:-N0emRkQ9pFUnWJlGDnc:undefined) ([raw file](https://github.com/pmem/rpma/blob/3a66d013cb74a1f6b04cbb2c11fd40795467f43b/src/conn_req.c#L355)):*
> ```C
> 	(void) rpma_conn_req_delete(&req);
> 
> 	return ret;
> ```





_Suggestion:_
```C
err_ack_cm_event:
	if (rdma_ack_cm_event(edata)) {
		RPMA_LOG_ERROR_WITH_ERRNO(errno, "rdma_ack_cm_event()");
	}

	return ret;
```


<!-- Sent from Reviewable.io -->

2022-04-27 14:55 UTC, grom72 requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`src/conn_req.c` line 347 at r3](https://reviewable.io/reviews/pmem/rpma/1703#-N0fVKJ76MoR8tVwqtqn:-N0fVKJ76MoR8tVwqtqo:b8uplig) ([raw file](https://github.com/pmem/rpma/blob/dadc174ed450f626b4e64979cb4813175b791a4f/src/conn_req.c#L347)):*
> ```C
> 	if (rdma_ack_cm_event(edata)) {
> 		RPMA_LOG_ERROR_WITH_ERRNO(errno, "rdma_ack_cm_event()");
> 		ret = RPMA_E_PROVIDER;
> ```

to disable the  rdma_ack_cm_event() in the error handling section



_Suggestion:_
```C
		edata = NULL;
		ret = RPMA_E_PROVIDER;
		goto err_conn_req_delete;
```
___
*[`src/conn_req.c` line 360 at r3](https://reviewable.io/reviews/pmem/rpma/1703#-N0fVd0E96I5jy3IVpQI:-N0fVd0E96I5jy3IVpQJ:undefined) ([raw file](https://github.com/pmem/rpma/blob/dadc174ed450f626b4e64979cb4813175b791a4f/src/conn_req.c#L360)):*
> ```C
> 
> err_ack_cm_event:
> 	if (rdma_ack_cm_event(edata))
> ```





_Suggestion:_
```C
	if (NULL != edata)
		if (rdma_ack_cm_event(edata))
			RPMA_LOG_ERROR_WITH_ERRNO(errno, "rdma_ack_cm_event()");
```


<!-- Sent from Reviewable.io -->

2022-04-28 06:02 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`src/conn_req.c` line 347 at r3](https://reviewable.io/reviews/pmem/rpma/1703#-N0fVKJ76MoR8tVwqtqn:-N0ikp0pEvVD9AoATYFu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dadc174ed450f626b4e64979cb4813175b791a4f/src/conn_req.c#L347)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

to disable the  rdma_ack_cm_event() in the error handling section
</blockquote></details>

Done.



_Code quote:_
```C
RPMA_LOG_ERROR_WITH_ERRNO(errno, "rdma_ack_cm_event()");
```
___
*[`src/conn_req.c` line 360 at r3](https://reviewable.io/reviews/pmem/rpma/1703#-N0fVd0E96I5jy3IVpQI:-N0ikpiK7sV1Sjro2P9R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dadc174ed450f626b4e64979cb4813175b791a4f/src/conn_req.c#L360)):*
> ```C
> 
> err_ack_cm_event:
> 	if (rdma_ack_cm_event(edata))
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-04-28 07:10 UTC, grom72 approved these changes
:goat: 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703#-:-N0j-PoI2t2tG2YznkwY:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_req.c` line 331 at r4](https://reviewable.io/reviews/pmem/rpma/1703#-N0iz6LL3FOF7wuuH85z:-N0iz6LL3FOF7wuuH86-:b-ldgdoj) ([raw file](https://github.com/pmem/rpma/blob/84dbc90e2f8f0f9d81f83bd4e22b1db75c06f3aa/src/conn_req.c#L331)):*
> ```C
> 
> 	if (peer == NULL || req_ptr == NULL || edata->event != RDMA_CM_EVENT_CONNECT_REQUEST) {
> 		ret = RPMA_E_INVAL;
> ```

@ldorau - final tuning proposal 
- keep parameters validation separate (without access to goto labels) from the main code.



_Suggestion:_
```C
		if (rdma_ack_cm_event(edata))
			RPMA_LOG_ERROR_WITH_ERRNO(errno, "rdma_ack_cm_event()");
		return RPMA_E_INVAL;
```


<!-- Sent from Reviewable.io -->

2022-04-28 07:46 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_req.c` line 331 at r4](https://reviewable.io/reviews/pmem/rpma/1703#-N0iz6LL3FOF7wuuH85z:-N0j7WhEEV5W-VG73yjg:buamfru) ([raw file](https://github.com/pmem/rpma/blob/84dbc90e2f8f0f9d81f83bd4e22b1db75c06f3aa/src/conn_req.c#L331)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau - final tuning proposal 
- keep parameters validation separate (without access to goto labels) from the main code.
</blockquote></details>

Why? It results in duplicated code.


<!-- Sent from Reviewable.io -->

2022-04-28 08:45 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703#-:-N0jL8yGCXDZTScci-op:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-10 08:11 UTC, grom72 approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-10 08:55 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-10 10:22 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 5 files at r1, 1 of 3 files at r6, 3 of 5 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703#-:-N1hUVgA9Xf_Ft19LF9f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-10 10:26 UTC, grom72 requested changes
> Reviewed 1 of 5 files at r7, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_req.c` line 323 at r6](https://reviewable.io/reviews/pmem/rpma/1703#-N1hVC-iAFn8DsBff8rL:-N1hVC-iAFn8DsBff8rM:undefined) ([raw file](https://github.com/pmem/rpma/blob/92d69fc07363c77e2fbb594992dd65f17256dc33/src/conn_req.c#L323)):*
> ```C
> int
> rpma_conn_req_from_cm_event(struct rpma_peer *peer,
> 		struct rdma_cm_event *edata, const struct rpma_conn_cfg *cfg,
> ```





_Suggestion:_
```C
event
```


<!-- Sent from Reviewable.io -->

2022-05-10 10:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_req.c` line 323 at r6](https://reviewable.io/reviews/pmem/rpma/1703#-N1hVC-iAFn8DsBff8rL:-N1hVtB73n3lxn8M8igf:b-fwel1v) ([raw file](https://github.com/pmem/rpma/blob/92d69fc07363c77e2fbb594992dd65f17256dc33/src/conn_req.c#L323)):*
> ```C
> int
> rpma_conn_req_from_cm_event(struct rpma_peer *peer,
> 		struct rdma_cm_event *edata, const struct rpma_conn_cfg *cfg,
> ```

So you will have `event->event` instead of `edata->event` below. Is it OK for you?



_Code quote:_
```C
edata->event
```


<!-- Sent from Reviewable.io -->

2022-05-10 10:43 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_req.c` line 323 at r6](https://reviewable.io/reviews/pmem/rpma/1703#-N1hVC-iAFn8DsBff8rL:-N1hZGqN6NCjk2frxquD:bb7s9zc) ([raw file](https://github.com/pmem/rpma/blob/92d69fc07363c77e2fbb594992dd65f17256dc33/src/conn_req.c#L323)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So you will have `event->event` instead of `edata->event` below. Is it OK for you?
</blockquote></details>

yes


<!-- Sent from Reviewable.io -->

2022-05-10 10:44 UTC, grom72 reviewed
> Reviewed 2 of 5 files at r7, 1 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-10 11:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_req.c` line 323 at r6](https://reviewable.io/reviews/pmem/rpma/1703#-N1hVC-iAFn8DsBff8rL:-N1hjhexATFrQvCvS7xg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/92d69fc07363c77e2fbb594992dd65f17256dc33/src/conn_req.c#L323)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-10 11:40 UTC, osalyk approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-05-10 12:38 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1703#-:-N1hydpX7z7iAU7zGT7a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-10 12:39 UTC, merged