test: move rpma_peer_new() out of mtt_client_connect()
pmem/rpma pull request #1710
Opened 2022-04-28 09:37 UTC by ldorau

Move `rpma_peer_new()` out of `mtt_client_connect()`
in order to enable creating multiple connections for one peer.

2022-04-28 09:53 UTC, grom72 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1710)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/multithreaded/common/mtt_connect.c` line 145 at r1](https://reviewable.io/reviews/pmem/rpma/1710#-N0j_QF44gU6LUUYPmiQ:-N0j_QF44gU6LUUYPmiR:undefined) ([raw file](https://github.com/pmem/rpma/blob/b11bd2224cc31aff62e5da05730a4b42610c5937/tests/multithreaded/common/mtt_connect.c#L145)):*
> ```C
> 
> /*
>  * mtt_client_connect -- connect with the server and get the private data
> ```





_Suggestion:_
```C
mtt_client_peer_new -- XXX
```


<!-- Sent from Reviewable.io -->

2022-04-28 09:53 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1710)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-28 10:57 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1710)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tests/multithreaded/common/mtt_connect.c` line 145 at r1](https://reviewable.io/reviews/pmem/rpma/1710#-N0j_QF44gU6LUUYPmiQ:-N0joOxm8ntfFgCdFFi1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b11bd2224cc31aff62e5da05730a4b42610c5937/tests/multithreaded/common/mtt_connect.c#L145)):*
> ```C
> 
> /*
>  * mtt_client_connect -- connect with the server and get the private data
> ```

Done.



_Code quote:_
```C
mtt_client_peer_new(struct mtt_result *tr, char *addr, struct rpma_peer **peer_ptr)
```


<!-- Sent from Reviewable.io -->

2022-04-29 06:43 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1710#-:-N0o2oNt5N54nrzvOFGa:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-04-29 09:11 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1710#-:-N0o_lTd0EDyx8iu238S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-04-29 09:13 UTC, merged