rpma: add fault injection also inside functions
pmem/rpma pull request #1736
Opened 2022-05-12 12:51 UTC by ldorau

Requires:
- [ ] #1734 
- [ ] #1735

2022-05-12 13:38 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736#-:-N1sUO6k01mh6LAL7XX1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-12 20:15 UTC, grom72 requested changes
> Reviewed 6 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: all files reviewed, 30 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1736#-N1tfnOHAiJhZdkQHV8W:-N1tfnOHAiJhZdkQHV8X:b-9u6mip) (no related file):*
I suggest returning ``RPMA_E_PROVIDER`` instead of ``RPMA_E_FAULT_INJECTION`` for fault injection related to ``rdma_*`` and ``ibv_*``. This behavior will more closely resemble the actual control flow.

___
___
*[`src/conn_req.c` line 201 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tggKM732gM0Bz934O:-N1tggKM732gM0Bz934P:bam770i) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L201)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

This fault injection should simulate the fault of  ``rdma_accept``. The first rdma function call after fault injection point.



_Suggestion:_
```C
RPMA_E_PROVIDER
```
___
*[`src/conn_req.c` line 264 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1thkM5-K0YHxVYvTNh:-N1thkM5-K0YHxVYvTNi:b-5w5v9l) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L264)):*
> ```C
> 		goto err_conn_new;
> 
> 	if (rdma_connect(req->id, conn_param)) {
> ```

Fault injection before the ``rdma_`` function call.
We can not inject fault after proper ``rdma_`` function call as it may cause unpredictable behavior of RDMA HW.



_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		(void) rpma_conn_delete(&conn);
	});
	if (rdma_connect(req->id, conn_param)) {
		RPMA_LOG_ERROR_WITH_ERRNO(errno, "rdma_connect()");
		(void) rpma_conn_delete(&conn);
		return RPMA_E_PROVIDER;
	}
```
___
*[`src/conn_req.c` line 403 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tiSIZ6ZWU15XcyR4b:-N1tiSIZ6ZWU15XcyR4c:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L403)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_PROVIDER
```
___
*[`src/conn_req.c` line 420 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1ti_BWCgETmTVs-YEj:-N1ti_BX-XZZ-Djju-Vh:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L420)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_PROVIDER
```
___
*[`src/cq.c` line 75 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tiqI79bxXjYzBNtK2:-N1tiqI79bxXjYzBNtK3:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L75)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
ret = RPMA_E_PROVIDER;
```
___
*[`src/cq.c` line 92 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tj0w60DG4QyNLeawe:-N1tj0w60DG4QyNLeawf:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L92)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_PROVIDER
```
___
*[`src/cq.c` line 163 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tjN0WAlJ041HFP0Ga:-N1tjN0WAlJ041HFP0Gb:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L163)):*
> ```C
> 	*cq_ptr = NULL;
> 
> 	RPMA_FAULT_INJECTION();
> ```





_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_PROVIDER;
	});
```
___
*[`src/cq.c` line 222 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tjXy3ApS0b6aY2NW6:-N1tjXy3ApS0b6aY2NW7:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L222)):*
> ```C
> 	ibv_ack_cq_events(cq->cq, 1 /* # of CQ events */);
> 
> 	RPMA_FAULT_INJECTION();
> ```





_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_PROVIDER;
	});
```
___
*[`src/cq.c` line 267 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tjgY-7by_nDSWS_IG:-N1tjgY-7by_nDSWS_IH:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L267)):*
> ```C
> 		return RPMA_E_UNKNOWN;
> 	}
> 	RPMA_FAULT_INJECTION();
> ```





_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_NO_COMPLETION;
	});
	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_PROVIDER;
	});
	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_UNKNOWN;
	});
```
___
*[`src/debug.h` line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tmpg50dsis8p4eEQq:-N1tmpg50dsis8p4eEQr:b-6n6dyv) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/debug.h#L25)):*
> ```objc
> #define RPMA_FAULT_INJECTION(exit_code) \
> 	do { \
> 		int value = 0; \
> ```

Maybe we extend fault injection with a return value.
I conclude that instead of ``RPMA_E_FAULT_INJECTION`` we should return an error that is in the scope of documented function return values. 



_Suggestion:_
```objc
#define RPMA_FAULT_INJECTION(ret_val, ...) \
	do { \
		int value = 0; \
		if (rpma_fault_injection(&value)) { \
			RPMA_LOG_ALWAYS("[#%i] [FAULT INJECTION]", value); \
			{ ##__VA_ARGS__; } \
			return ret_val; \
		} \
		if (value) \
			RPMA_LOG_ALWAYS("[#%i]", value); \
	} while (0)
```
___
*[`src/ep.c` line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tcMow23f43KBjBTsU:-N1tcMow23f43KBjBTsV:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L63)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
ret = RPMA_E_PROVIDER
```
___
*[`src/ep.c` line 83 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tdqza38nOhTi9tkA8:-N1tdqza38nOhTi9tkA9:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L83)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_PROVIDER
```
___
*[`src/ep.c` line 193 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tmI5J6Va39AMBdbtC:-N1tm2vdEiTmZZ4rpShu:b1apvve) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L193)):*
> ```C
> 	int ret = 0;
> 	struct rdma_cm_event *event = NULL;
> ```

	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_PROVIDER;
	});
___
*[`src/ep.c` line 205 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tlGJECfcYCAbBFs61:-N1tlGJECfcYCAbBFs62:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L205)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_INVAL
```
___
*[`src/ep.c` line 223 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1teGNT2o8dLJC9MCxJ:-N1teGNT2o8dLJC9MCxK:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L223)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_PROVIDER
```
___
*[`src/ep.c` line 236 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1teRtODbYLnUaXhvPv:-N1teRtP-fBtZ4F_AC4Z:b-sx84ma) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L236)):*
> ```C
> 	}
> 
> 	RPMA_FAULT_INJECTION(
> ```

obsolete
___
*[`src/mr.c` line 74 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1toFMq7Z4iffmdQrtz:-N1toFMr-QBefXWj9u4Z:b-sx84ma) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/mr.c#L74)):*
> ```C
> {
> 	RPMA_DEBUG_TRACE;
> 	RPMA_FAULT_INJECTION();
> ```

obsolete
___
*[`src/mr.c` line 109 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tf75c484oCfVvU2pW:-N1tf75c484oCfVvU2pX:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/mr.c#L109)):*
> ```C
> 
> 	struct i [...]

2022-05-13 06:57 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: all files reviewed, 31 unresolved discussions (waiting on @ldorau)

___
*[`src/conn.c` line 67 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1w140RDcaB7e00gqEw:-N1w140S4GDgBaNViA4T:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L67)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
RPMA_E_PROVIDER
```


<!-- Sent from Reviewable.io -->

2022-05-13 08:57 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: all files reviewed, 35 unresolved discussions (waiting on @ldorau)

___
*[`src/conn.c` line 275 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1wXk1wCfVbqn6LgnOt:-N1wXk1wCfVbqn6LgnOu:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L275)):*
> ```C
> 
> 	/* request for the next event on the CQ channel */
> 	RPMA_FAULT_INJECTION(
> ```





_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_PROVIDER;
		*cq = NULL;
	});
```
___
*[`src/conn.c` line 389 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1waAFhEGNpMAQ03aA9:-N1waAFhEGNpMAQ03aAA:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L389)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		ret = RPMA_E_PROVIDER;
		goto err_destroy_comp_channel;
	});
```
___
*[`src/conn.c` line 403 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1waUAEBK2Yd1Vtfrpx:-N1waUAEBK2Yd1Vtfrpy:undefined) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L403)):*
> ```C
> 		RPMA_FAULT_INJECTION(
> 		{
> 			ret = RPMA_E_FAULT_INJECT;
> ```





_Suggestion:_
```C
			ret = RPMA_E_PROVIDER;
```


<!-- Sent from Reviewable.io -->

2022-05-13 08:58 UTC, grom72 reviewed
> Reviewed 2 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: all files reviewed, 35 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-13 09:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: 0 of 17 files reviewed, 35 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1736#-N1tfnOHAiJhZdkQHV8W:-N1wMdrO47ktMM21JzPx:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I suggest returning ``RPMA_E_PROVIDER`` instead of ``RPMA_E_FAULT_INJECTION`` for fault injection related to ``rdma_*`` and ``ibv_*``. This behavior will more closely resemble the actual control flow.
</blockquote></details>

Done.

---
___
*[`src/conn.c` line 67 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1w140RDcaB7e00gqEw:-N1wCz9k7wgbrNNryVmO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L67)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/conn_req.c` line 201 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tggKM732gM0Bz934O:-N1wDO2lCP-eHdIGsWGN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L201)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This fault injection should simulate the fault of  ``rdma_accept``. The first rdma function call after fault injection point.
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 264 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1thkM5-K0YHxVYvTNh:-N1wEDP95DY3nHn7ykwf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L264)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Fault injection before the ``rdma_`` function call.
We can not inject fault after proper ``rdma_`` function call as it may cause unpredictable behavior of RDMA HW.
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 403 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tiSIZ6ZWU15XcyR4b:-N1wEr2W4BY_MgcSZtu5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L403)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/conn_req.c` line 420 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1ti_BWCgETmTVs-YEj:-N1wF4Iu007VpSUVBa9S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn_req.c#L420)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/cq.c` line 75 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tiqI79bxXjYzBNtK2:-N1wFIGK6Ew8g-6TA5PM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L75)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/cq.c` line 92 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tj0w60DG4QyNLeawe:-N1wFJuf2F7np40DDbAl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L92)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/cq.c` line 163 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tjN0WAlJ041HFP0Ga:-N1wFeFn2YUeVnvlubHI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L163)):*
> ```C
> 	*cq_ptr = NULL;
> 
> 	RPMA_FAULT_INJECTION();
> ```

Done.
___
*[`src/cq.c` line 222 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tjXy3ApS0b6aY2NW6:-N1wFrdqA0sTvMW-LkKz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L222)):*
> ```C
> 	ibv_ack_cq_events(cq->cq, 1 /* # of CQ events */);
> 
> 	RPMA_FAULT_INJECTION();
> ```

Done.
___
*[`src/cq.c` line 267 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tjgY-7by_nDSWS_IG:-N1wGpBK0Mhye6seweRx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/cq.c#L267)):*
> ```C
> 		return RPMA_E_UNKNOWN;
> 	}
> 	RPMA_FAULT_INJECTION();
> ```

Done.
___
*[`src/debug.h` line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tmpg50dsis8p4eEQq:-N1wLKWvAWyeqx2fhMrQ:b-25zcsw) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/debug.h#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Maybe we extend fault injection with a return value.
I conclude that instead of ``RPMA_E_FAULT_INJECTION`` we should return an error that is in the scope of documented function return values. 

</blockquote></details>

`__VA_ARGS__` cannot be used:

```c
error: pasting "{" and "{" does not give a valid preprocessing token
   28 |                         { ##__VA_ARGS__; } /* exit code */ \
      |                         ^
```

It has to be like that:
```c
#define RPMA_FAULT_INJECTION(ret_val, exit_code) \
```
___
*[`src/ep.c` line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tcMow23f43KBjBTsU:-N1wLPQc5OPb2FhCSL4D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L63)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/ep.c` line 83 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tdqza38nOhTi9tkA8:-N1wMCr66GJHADiilNTN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L83)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/ep.c` line 193 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tmI5J6Va39AMBdbtC:-N1wNBBA-dn-ya7zAMDW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L193)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

	RPMA_FAULT_INJECTION(
	{
		ret_fi = RPMA_E_PROVIDER;
	});

</blockquote></details>

Done.
___
*[`src/ep.c` line 205 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tlGJECfcYCAbBFs61:-N1wMGdnEqObQO9kswQo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L205)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/ep.c` line 223 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1teGNT2o8dLJC9MCxJ:-N1wMK4l0yAhIwrPhG2R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L223)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/ep.c` line 236 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1teRtODbYLnUaXhvPv:-N1wQhET16Aep7rzr1rI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/ep.c#L236)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

obsolete
</blockquote></details>

Done.
___
*[`src/mr.c` line 74 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1toFMq7Z4iffmdQrtz:-N1wRjRM6sfmSK4rZWPJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/mr.c#L74)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

obsolete
</blockquote></details>

Done.
___
*[`src/mr.c` line 109 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tf75c484oCfVvU2pW:-N1wRoOmCbUE0-zm1Qxb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/mr.c#L109)):*
> ```C
> 
> 	struct ibv_send_wr *bad_wr;
> 	RPMA_FAULT_INJECTION();
> ```

Done.
___
*[`src/mr.c` line 182 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1tfQ3J6xmlSlDZiEa2:-N1wSuYlCvEVG52fDLWc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1 [...]

2022-05-13 09:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: 0 of 17 files reviewed, 35 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`src/conn.c` line 190 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1wWjDsCLbolutgoLyY:-N1wic5T8ImY4y0uebyO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L190)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/conn.c` line 275 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1wXk1wCfVbqn6LgnOt:-N1wiDcJABV-biRKH3gl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L275)):*
> ```C
> 
> 	/* request for the next event on the CQ channel */
> 	RPMA_FAULT_INJECTION(
> ```

Done.
___
*[`src/conn.c` line 389 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1waAFhEGNpMAQ03aA9:-N1wiHHnDb8guvDwOqPP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L389)):*
> ```C
> 	RPMA_FAULT_INJECTION(
> 	{
> 		ret = RPMA_E_FAULT_INJECT;
> ```

Done.
___
*[`src/conn.c` line 403 at r3](https://reviewable.io/reviews/pmem/rpma/1736#-N1waUAEBK2Yd1Vtfrpx:-N1wiJS54D5WW57oPRob:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdbefffec0eed34adef01434d8e1fcffbb2c7af2/src/conn.c#L403)):*
> ```C
> 		RPMA_FAULT_INJECTION(
> 		{
> 			ret = RPMA_E_FAULT_INJECT;
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 09:51 UTC, grom72 approved these changes
> Reviewed 14 of 17 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-13 09:52 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`src/debug.h` line 27 at r7](https://reviewable.io/reviews/pmem/rpma/1736#-N1wp8m78HZ9vxmBwqfI:-N1wp8m86DnkogMxUAV7:undefined) ([raw file](https://github.com/pmem/rpma/blob/56e194d9d7275d0fb22ab6aab665e2ceda6ca09d/src/debug.h#L27)):*
> ```objc
> 		int value = 0; \
> 		if (rpma_fault_injection(&value)) { \
> 			RPMA_LOG_ALWAYS("[#%i] [FAULT INJECTION]", value); \
> ```





_Suggestion:_
```objc
RPMA_LOG_ALWAYS("[#%i] [FAULT INJECTION: \"%s\"]", value, rpma_err_2str(ret_val)); \
```


<!-- Sent from Reviewable.io -->

2022-05-13 11:17 UTC, osalyk approved these changes
> Reviewed 15 of 17 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-13 11:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`src/debug.h` line 27 at r7](https://reviewable.io/reviews/pmem/rpma/1736#-N1wp8m78HZ9vxmBwqfI:-N1x8R7uDdinFMIfA5H-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/56e194d9d7275d0fb22ab6aab665e2ceda6ca09d/src/debug.h#L27)):*
> ```objc
> 		int value = 0; \
> 		if (rpma_fault_injection(&value)) { \
> 			RPMA_LOG_ALWAYS("[#%i] [FAULT INJECTION]", value); \
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-05-13 12:12 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736#-:-N1xKO868t_Dzt4WQK3Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-05-13 13:04 UTC, osalyk approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1736)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-05-16 11:03 UTC, merged