examples: add common-client_pmem_signature_check
pmem/rpma pull request #1791
Opened 2022-05-30 13:57 UTC by haichangsi

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/1791)

2022-05-31 07:25 UTC, grom72 requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1791#-N3Nz-n4A4zFLJ-uTqwa:-N3Nz-n4A4zFLJ-uTqwb:bqbx3hn) (no related file):*
@haichangsi - let me propose a few changes:
- extend ``client_pmem_map_file`` with new parameter ``min_size``
-  check mapped memory size against min_size and return an error if not ok
-  rename ``client_pmem_signature_check`` to client_map_file_with_signature_check
- call ``client_pmem_map_file`` inside ``client_map_file_with_signature_check``

___


<!-- Sent from Reviewable.io -->

2022-06-08 22:32 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1791#-N3Nz-n4A4zFLJ-uTqwa:-N44RZitCaVpI_2yMTfM:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@haichangsi - let me propose a few changes:
- extend ``client_pmem_map_file`` with new parameter ``min_size``
-  check mapped memory size against min_size and return an error if not ok
-  rename ``client_pmem_signature_check`` to client_map_file_with_signature_check
- call ``client_pmem_map_file`` inside ``client_map_file_with_signature_check``
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-06-09 10:50 UTC, grom72 requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[`examples/03-read-to-persistent/server.c` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46WVb784SP6S7rhlDY:-N46WVb784SP6S7rhlDZ:undefined) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L53)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		if (client_pmem_map_file(pmem_path, &mem, SIGNATURE_LEN))
> ```





_Suggestion:_
```C
		if (client_pmem_map_file(pmem_path, &mem, SIGNATURE_LEN + KILOBYTE))
```
___
*[`examples/03-read-to-persistent/server.c` line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46Vjyx5ml4Dkzl9wK7:-N46Vjyx5ml4Dkzl9wK8:b-64uha2) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L61)):*
> ```C
> 		 * of the mapped memory has to be at least of the length of
> 		 * the signature to convey any meaningful content and be usable
> 		 * as a persistent store.
> ```

redundant code. This should be done inside ``client_pmem_map_file``
___
*[`examples/03-read-to-persistent/server.c` line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46WgHY6fKSnSMsywGs:-N46WgHY6fKSnSMsywGt:b-lp83j4) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L73)):*
> ```C
> 		/*
> 		 * All of the space under the offset is intended for
> 		 * the string contents. Space is assumed to be at least 1 KiB.
> ```

Should be done inside ``client_pmem_map_file``


<!-- Sent from Reviewable.io -->

2022-06-13 09:25 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[`examples/03-read-to-persistent/server.c` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46WVb784SP6S7rhlDY:-N4RNJHv61RvKZaGiN6L:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L53)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		if (client_pmem_map_file(pmem_path, &mem, SIGNATURE_LEN))
> ```

Done.
___
*[`examples/03-read-to-persistent/server.c` line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46Vjyx5ml4Dkzl9wK7:-N4RN5kB5m8ht6B92uAa:b5ocacc) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant code. This should be done inside ``client_pmem_map_file``
</blockquote></details>

as we discussed I should start only with clients and create probably separate file for servers unless something's changed 
___
*[`examples/03-read-to-persistent/server.c` line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46WgHY6fKSnSMsywGs:-N4RNFfA9z3s7C0kTu9l:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L73)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Should be done inside ``client_pmem_map_file``
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-06-13 12:17 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1791#-N3Nz-n4A4zFLJ-uTqwa:-N4RsZxa-I19xwtN-1IT:b-5fexhk) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It seems that ``struct example_mem mem;`` is common for server and client
I propose to make ``client_pmem_signature_check()`` a common function for both side:

```
/* size is used only on server side when no initiation with write_hello_str is required */
int
pmem_signature_check(char *path, size_t size, struct example_mem *mem) {

...
size_t min_size = size;
if (min_size == 0)
    min_size = sizeof(struct hello_t);
if (client_pmem_map_file(path, mem, SIGNATURE_LEN+min_size))
{
exit -1
}
...
	if (strncmp(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN) != 0) {
if (size == 0) {
		/* write an initial value and persist it */
		write_hello_str(hello, en);
		mem->persist(hello, sizeof(struct hello_t));
} else {
			/* write an initial empty string and persist it */
			((char *)mem.mr_ptr + mem.data_offset)[0] = '\0';
			mem.persist(mem.mr_ptr, 1);
}
		/* write the signature to mark the content as valid */
		memcpy(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
		mem->persist(mem->mr_ptr, SIGNATURE_LEN);
	}
```



_Code quote (from examples/03-read-to-persistent/server.c):_
```C
struct example_mem mem;
```

___
___
*[`examples/03-read-to-persistent/server.c` line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46Vjyx5ml4Dkzl9wK7:-N4RrYqKCUk8ff5RcaB-:b5wqzmq) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L61)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

as we discussed I should start only with clients and create probably separate file for servers unless something's changed 
</blockquote></details>

but you have already used ``client_pme_map_file``
___
*[`examples/03-read-to-persistent/server.c` line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1791#-N46WgHY6fKSnSMsywGs:-N4Rrn8y4BLYEl6EApzU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/94707239be1ae8c8a92888ed30ade3445d4fee8e/examples/03-read-to-persistent/server.c#L73)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`examples/common/common-client_map_file_with_signature_check.c` line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1791#-N4Rxglh4lLhAFDcIvAs:-N4Rxgli7qhUbppYORN_:b393ecq) ([raw file](https://github.com/pmem/rpma/blob/4b9e811fc6f8cd7baf811a4f258caa361fa1c59a/examples/common/common-client_map_file_with_signature_check.c#L15)):*
> ```C
> 
> int
> client_pmem_signature_check(char *path, struct hello_t *hello, struct example_mem *mem)
> ```

do we need this anywhere?


<!-- Sent from Reviewable.io -->

2022-06-15 11:23 UTC, grom72 requested changes
> Reviewed 5 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/03-read-to-persistent/client.c` line 52 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b2F4w0qnYX2Y0msKk:-N4b2F4w0qnYX2Y0msKl:undefined) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/03-read-to-persistent/client.c#L52)):*
> ```C
> 		char *path = argv[3];
> 
> 		ret = pmem_signature_check(path, hello, &mem,
> ```





_Suggestion:_
```C
		ret = pmem_signature_check(path, &hello, &mem, sizeof(struct hello_t));
```
___
*[`examples/common/common-map_file_with_signature_check.h` line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b2UQU-m3tptF1qNq4:-N4b2UQU-m3tptF1qNq5:undefined) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.h#L18)):*
> ```objc
> #include "common-hello.h"
> 
> int pmem_signature_check(char *path, struct hello_t *hello, struct example_mem *mem, size_t size);
> ```





_Suggestion:_
```objc
int pmem_signature_check(char *path, struct hello_t **hello, struct example_mem *mem, size_t size);
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b1W-N2LAQKXoao2OL:-N4b1W-N2LAQKXoao2OM:b1hz7ja) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L16)):*
> ```C
> /* size is used only on server side when no initiation with write_hello_str is required */
> int
> pmem_signature_check(char *path, struct hello_t *hello, struct example_mem *mem, size_t size)
> ```

if we use only pointer we do not see pointer value outside this function



_Suggestion:_
```C
pmem_signature_check(char *path, struct hello_t **hello, struct example_mem *mem, size_t size)
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b2l265BVW28ZWiKBc:-N4b2l275w--h1Y11t3o:brcwwhq) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L16)):*
> ```C
> /* size is used only on server side when no initiation with write_hello_str is required */
> int
> pmem_signature_check(char *path, struct hello_t *hello, struct example_mem *mem, size_t size)
> ```

Parameters order:
inputs,
outputs



_Suggestion:_
```C
pmem_signature_check(char *path,  size_t size, struct example_mem *mem, struct hello_t **hello)
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 23 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b5GNv5h5rKu7uXOud:-N4b5GNv5h5rKu7uXOue:bpl18oc) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L23)):*
> ```C
> 		min_size = sizeof(struct hello_t);
> 
> 	if (client_pmem_map_file(path, mem, SIGNATURE_LEN+min_size))
> ```

compilation blocker :(
https://github.com/haichangsi/rpma/actions/runs/2501650236



_Suggestion:_
```C
SIGNATURE_LEN + min_size
```


<!-- Sent from Reviewable.io -->

2022-06-20 06:59 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-20 07:06 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 23 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b5GNv5h5rKu7uXOud:-N4zvgte3FXVcwP-Vczz:b236kpp) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

compilation blocker :(
https://github.com/haichangsi/rpma/actions/runs/2501650236

</blockquote></details>

Please run cstyle locally:
```
rpma/examples/common/common-map_file_with_signature_check.c:23: missing space around + operator
```


<!-- Sent from Reviewable.io -->

2022-06-20 07:11 UTC, ldorau reviewed
> Reviewed 2 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-20 09:25 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[`examples/03-read-to-persistent/client.c` line 52 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b2F4w0qnYX2Y0msKk:-N5-KYhZ9hcytjFWasYf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/03-read-to-persistent/client.c#L52)):*
> ```C
> 		char *path = argv[3];
> 
> 		ret = pmem_signature_check(path, hello, &mem,
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.h` line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b2UQU-m3tptF1qNq4:-N5-KYJvAX9hInHu_hoG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.h#L18)):*
> ```objc
> #include "common-hello.h"
> 
> int pmem_signature_check(char *path, struct hello_t *hello, struct example_mem *mem, size_t size);
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b2l265BVW28ZWiKBc:-N5-L4k0CoLZ5TdFM4we:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Parameters order:
inputs,
outputs
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b1W-N2LAQKXoao2OL:-N5-QTqH3TZPFXbiHFoe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

if we use only pointer we do not see pointer value outside this function
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 23 at r4](https://reviewable.io/reviews/pmem/rpma/1791#-N4b5GNv5h5rKu7uXOud:-N5-QTFR9VZAPI5g9eLt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc58d7b9b9e94b1623878802a22635efb984e2af/examples/common/common-map_file_with_signature_check.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please run cstyle locally:
```
rpma/examples/common/common-map_file_with_signature_check.c:23: missing space around + operator
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-20 20:38 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 22 unresolved discussions (waiting on @haichangsi)

___
*[`examples/03-read-to-persistent/client.c` line 52 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51oijlEAkX3RHWL4uq:-N51oijlEAkX3RHWL4ur:bnfer51) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/03-read-to-persistent/client.c#L52)):*
> ```C
> 		char *path = argv[3];
> 
> 		ret = pmem_signature_check(path, sizeof(struct hello_t), &mem, &hello);
> ```

Let's assign a ``hello`` pointer outside ``pmem_signature_check``



_Suggestion:_
```C
pmem_signature_check(path, sizeof(struct hello_t), &mem);
```
___
*[`examples/03-read-to-persistent/client.c` line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51nPLW-8qYj8xVROxU:-N51nPLW-8qYj8xVROxV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/03-read-to-persistent/client.c#L54)):*
> ```C
> 		ret = pmem_signature_check(path, sizeof(struct hello_t), &mem, &hello);
> 		if (ret)
> 			goto err_free;
> ```

.



_Suggestion:_
```C
		if (ret)
			goto err_free;
		hello = (uintptr_t)mem->mr_ptr + mem->data_offset
```
___
*[`examples/03-read-to-persistent/server.c` line 55 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51owtn8352r7oIaw8S:-N51owtn8352r7oIaw8T:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/03-read-to-persistent/server.c#L55)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = pmem_signature_check(pmem_path, 0, &mem, NULL);
> ```

.



_Suggestion:_
```C
pmem_signature_check(pmem_path, 0, &mem);
```
___
*[`examples/common/common-pmem2_map_file.c` line 7 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51pQl9Ew41HkCnkL3c:-N51pQl9Ew41HkCnkL3d:b32vmt) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem2_map_file.c#L7)):*
> ```C
>  * common-pmem2_map_file.c -- a function to map PMem using libpmem2
>  *
>  * Please see README.md for a detailed description of this example.
> ```

??



_Code quote:_
```C
* Please see README.md for a detailed description of this example.
```
___
*[`examples/common/common-pmem2_map_file.c` line 16 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51m9WL-oA8XDPoJN3z:-N51m9WL-oA8XDPoJN4-:undefined) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem2_map_file.c#L16)):*
> ```C
> 
> int
> client_pmem_map_file(char *path, struct example_mem *mem, size_t min_size)
> ```





_Suggestion:_
```C
common_pmem_map_file(char *path, size_t min_size, struct example_mem *mem)
```
___
*[`examples/common/common-pmem_map_file.h` line 8 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51mLio2hX07wpS7dp1:-N51mLio2hX07wpS7dp2:bg2q83h) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.h#L8)):*
> ```objc
>  * and common-pmem2_map_file.c
>  *
>  * Please see README.md for a detailed description of this example.
> ```

To be replaced by pmem_map_file documentation



_Code quote:_
```objc
 * Please see README.md for a detailed description of this example.
```
___
*[`examples/common/common-pmem_map_file.h` line 33 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51UxXV4m4fbr7AWS6y:-N51UxXV4m4fbr7AWS6z:undefined) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.h#L33)):*
> ```objc
> };
> 
> int client_pmem_map_file(char *path, struct example_mem *mem, size_t min_size);
> ```





_Suggestion:_
```objc
common_pmem_map_file
```
___
*[`examples/common/common-pmem_map_file.h` line 33 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51mGUk3SBbkBLeD4Mo:-N51mGUk3SBbkBLeD4Mp:undefined) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.h#L33)):*
> ```objc
> };
> 
> int client_pmem_map_file(char *path, struct example_mem *mem, size_t min_size);
> ```





_Suggestion:_
```objc
int client_pmem_map_file(char *path, size_t min_size, struct example_mem *mem);
```
___
*[`examples/common/common-pmem_map_file.h` line 35 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51Uowd7X6t-EOWX7Fa:-N51Uowd7X6t-EOWX7Fb:b-xrhezb) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.h#L35)):*
> ```objc
> int client_pmem_map_file(char *path, struct example_mem *mem, size_t min_size);
> 
> void client_pmem_unmap_file(struct example_mem *mem);
> ```

it is no longer client specific



_Suggestion:_
```objc
common_pmem_unmap_file
```
___
*[`examples/common/common-pmem_map_file.c` line 7 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51lLRW4zOn7yiTRRTG:-N51lLRW4zOn7yiTRRTH:b-mwfni8) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.c#L7)):*
> ```C
>  * common-pmem_map_file.c -- a function to map PMem using libpmem
>  *
>  * Please see README.md for a detailed description of this example.
> ```

No context for this info.



_Code quote:_
```C
Please see README.md for a detailed description of this example.
```
___
*[`examples/common/common-pmem_map_file.c` line 14 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51VII5B3wC_zWAVa7A:-N51VII5B3wC_zWAVa7B:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.c#L14)):*
> ```C
> 
> int
> client_pmem_map_file(char *path, struct example_mem *mem, size_t min_size)
> ```

.



_Suggestion:_
```C
common_pmem_map_file
```
___
*[`examples/common/common-pmem_map_file.c` line 14 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51lyAaD7p1maMoMyxi:-N51lyAb2z8YCCPPPjRk:b-44m6qu) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.c#L14)):*
> ```C
> 
> int
> client_pmem_map_file(char *path, struct example_mem *mem, size_t min_size)
> ```

input, output



_Suggestion:_
```C
common_pmem_map_file(char *path, size_t min_size, struct example_mem *mem)
```
___
*[`examples/common/common-pmem_map_file.c` line 48 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51VND4-3IwPFOhMwV-:-N51VND4-3IwPFOhMwV0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.c#L48)):*
> ```C
> 
> void
> client_pmem_unmap_file(struct example_mem *mem)
> ```

.



_Suggestion:_
```C
common_pmem_unmap_file
```
___
*[`examples/common/common-pmem_map_file.c` line 52 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51lVucB5PJr6BCFNmg:-N51lVucB5PJr6BCFNmh:b45h) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-pmem_map_file.c#L52)):*
> ```C
> 	if (mem->is_pmem) {
> 		(void) pmem_unmap(mem->mr_ptr, mem->mr_size);
> 		mem->mr_ptr = NULL;
> ```





_Suggestion:_
```C
mem->mr_ptr = NULL;
mem->is_pmem = 0;
```
___
*[`examples/common/common-map_file_with_signature_check.h` line 7 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51pX3pDiaSNR_bHBnt:-N51pX3pDiaSNR_bHBnu:b32vmt) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-map_file_with_signature_check.h#L7)):*
> ```objc
>  * common-client_pmem_signature_check.h -- a header file for common-client_pmem_signature_check.c
>  *
>  * Please see README.md for a detailed description of this example.
> ```

??



_Code quote:_
```objc
 * Please see README.md for a detailed description of this example.
```
___
*[`examples/common/common-map_file_with_signature_check.h` line 18 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51nrBX848k9CH_Jxpo:-N51nrBX848k9CH_Jxpp:bidnrm5) ([raw file](https://github.co [...]

2022-06-20 20:55 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 23 unresolved discussions (waiting on @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 7 at r5](https://reviewable.io/reviews/pmem/rpma/1791#-N51pTgB-h9ex0Cm6f6T:-N51pTgB-h9ex0Cm6f6U:b3y1v3h) ([raw file](https://github.com/pmem/rpma/blob/2091537571542f782e11dab4f59884dd299c49d4/examples/common/common-map_file_with_signature_check.c#L7)):*
> ```C
>  * common-client_pmem_signature_check.c -- a function to check pmem signature
>  *
>  * Please see README.md for a detailed description of this example.
> ```

To be replaced



_Code quote:_
```C
 * Please see README.md for a detailed description of this example.
```


<!-- Sent from Reviewable.io -->

2022-06-21 08:18 UTC, grom72 requested changes
> Reviewed 7 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`CMakeLists.txt` line 106 at r6](https://reviewable.io/reviews/pmem/rpma/1791#-N54Kb_fDVdeMHtQwQ4T:-N54Kb_fDVdeMHtQwQ4U:bb2ekkm) ([raw file](https://github.com/pmem/rpma/blob/d1622b6b9e7c45153b083619ef570d2abe260879/CMakeLists.txt#L106)):*
> ```CMake
> endif()
> 
> # pkg_check_modules(LIBPMEM libpmem>=${LIBPMEM_REQUIRED_VERSION})
> ```

why ``#``



_Code quote:_
```CMake
# pkg_check_modules(LIBPMEM libpmem>=${LIBPMEM_REQUIRED_VERSION})
if(NOT LIBPMEM_FOUND)
	# find_package(LIBPMEM ${LIBPMEM_REQUIRED_VERSION})
	if(NOT LIBPMEM_FOUND)
		message(WARNING "Since libpmem is missing, the libpmem-based examples will be unable to use PMem. They will be using DRAM instead.")
	endif()
endif()
```
___
*[`CMakeLists.txt` line 114 at r6](https://reviewable.io/reviews/pmem/rpma/1791#-N54KfnhC0MOMhUNwK-Q:-N54KfnhC0MOMhUNwK-R:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d1622b6b9e7c45153b083619ef570d2abe260879/CMakeLists.txt#L114)):*
> ```CMake
> endif()
> 
> # pkg_check_modules(LIBPMEM2 libpmem2>=${LIBPMEM2_REQUIRED_VERSION})
> ```

.



_Code quote:_
```CMake
# pkg_check_modules(LIBPMEM2 libpmem2>=${LIBPMEM2_REQUIRED_VERSION})
if(NOT LIBPMEM2_FOUND)
	# find_package(LIBPMEM2 ${LIBPMEM2_REQUIRED_VERSION})
	if(NOT LIBPMEM2_FOUND)
		message(WARNING "Since libpmem2 is missing, the libpmem2-based examples will be unable to use PMem. They will be using DRAM instead.")
	endif()
endif()
```


<!-- Sent from Reviewable.io -->

2022-06-21 08:20 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`CMakeLists.txt` line 106 at r6](https://reviewable.io/reviews/pmem/rpma/1791#-N54Kb_fDVdeMHtQwQ4T:-N54LMQm5wFUX62HVAMk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d1622b6b9e7c45153b083619ef570d2abe260879/CMakeLists.txt#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why ``#``
</blockquote></details>

Done.
___
*[`CMakeLists.txt` line 114 at r6](https://reviewable.io/reviews/pmem/rpma/1791#-N54KfnhC0MOMhUNwK-Q:-N54LMkUE2om-oN5Ii3I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d1622b6b9e7c45153b083619ef570d2abe260879/CMakeLists.txt#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-21 08:31 UTC, ldorau reviewed
> Reviewed 1 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/common/common-pmem_map_file.h` line 16 at r6](https://reviewable.io/reviews/pmem/rpma/1791#-N54L8WFB5t1Z2VuCFz8:-N54NRVL34_Hd6cKOoLa:b32v57) ([raw file](https://github.com/pmem/rpma/blob/d1622b6b9e7c45153b083619ef570d2abe260879/examples/common/common-pmem_map_file.h#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau , @osalyk 
Shall we rename this to ``struct common_mem``?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-06-21 08:37 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[`examples/common/common-pmem_map_file.h` line 16 at r6](https://reviewable.io/reviews/pmem/rpma/1791#-N54L8WFB5t1Z2VuCFz8:-N54PEAcC4TMF22X6lpx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d1622b6b9e7c45153b083619ef570d2abe260879/examples/common/common-pmem_map_file.h#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-21 08:43 UTC, ldorau requested changes
> Reviewed 1 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 3 of 10 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1791#-N54OWnZCvwFCwec0U-n:-N54OWn_4om-A2q5fVRN:brhxvje) ([raw file](https://github.com/pmem/rpma/blob/615546958015991de12e9cedbe4543db25cc885a/examples/common/common-map_file_with_signature_check.h#L14)):*
> ```objc
> #include <stdio.h>
> #include "common-conn.h"
> #include "common-pmem_map_file.h"
> ```

Are they all needed here?



_Code quote:_
```objc
#include <stdio.h>
#include "common-conn.h"
#include "common-pmem_map_file.h"
#include "common-hello.h"
```
___
*[`examples/common/common-map_file_with_signature_check.h` line 20 at r7](https://reviewable.io/reviews/pmem/rpma/1791#-N54O6ItESKdpfPSSy6q:-N54O6ItESKdpfPSSy6r:btb9aat) ([raw file](https://github.com/pmem/rpma/blob/615546958015991de12e9cedbe4543db25cc885a/examples/common/common-map_file_with_signature_check.h#L20)):*
> ```objc
> 
> 
> #endif /* COMMON_MAP_FILE_WITH_SIGNATURE_CHECK_H */
> ```

one empty line too many



_Code quote:_
```objc
int common_pmem_signature_check(char *path, size_t size, struct example_mem *mem);


#endif /* COMMON_MAP_FILE_WITH_SIGNATURE_CHECK_H */
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 14 at r8](https://reviewable.io/reviews/pmem/rpma/1791#-N54QKRQ1a8s98NRTR0E:-N54QKRQ1a8s98NRTR0F:b-oog9ev) ([raw file](https://github.com/pmem/rpma/blob/0f7392f700aeb89c09556af3951098fa73ef03b0/examples/common/common-map_file_with_signature_check.c#L14)):*
> ```C
> /* size is used only on server side when no initiation with write_hello_str is required */
> int
> common_pmem_signature_check(char *path, size_t size, struct common_mem *mem)
> ```

`common_pmem_map_file_with_signature_check`



_Code quote:_
```C
common_pmem_signature_check
```


<!-- Sent from Reviewable.io -->

2022-06-21 08:43 UTC, ldorau reviewed
> Reviewed 1 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 4 of 10 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 08:50 UTC, ldorau reviewed
> Reviewed 1 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 08:50 UTC, grom72 reviewed
> Reviewed 2 of 7 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 09:01 UTC, grom72 approved these changes
> Reviewed 4 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 09:39 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1791#-N54OWnZCvwFCwec0U-n:-N54YlOJ-VGLHWJB7XIn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/615546958015991de12e9cedbe4543db25cc885a/examples/common/common-map_file_with_signature_check.h#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Are they all needed here?
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.h` line 20 at r7](https://reviewable.io/reviews/pmem/rpma/1791#-N54O6ItESKdpfPSSy6q:-N54YnLN0qjnTG8EDWC-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/615546958015991de12e9cedbe4543db25cc885a/examples/common/common-map_file_with_signature_check.h#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one empty line too many
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 14 at r8](https://reviewable.io/reviews/pmem/rpma/1791#-N54QKRQ1a8s98NRTR0E:-N54cDwVB-Y7PEhYL0OW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f7392f700aeb89c09556af3951098fa73ef03b0/examples/common/common-map_file_with_signature_check.c#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-21 09:55 UTC, grom72 approved these changes
> Reviewed 2 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 09:56 UTC, grom72 approved these changes
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791#-:-N54g92JAEvz6WY1OYGR:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 09:56 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-21 10:29 UTC, osalyk approved these changes
> Reviewed 2 of 6 files at r4, 3 of 7 files at r8, 2 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-21 10:42 UTC, ldorau requested changes
> Reviewed 2 of 7 files at r8, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`examples/03-read-to-persistent/client.c` line 53 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54hb872LEPZxopZ2nZ:-N54hb88BZqURyp_m-vZ:b45pj5u) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/03-read-to-persistent/client.c#L53)):*
> ```C
> 
> 		ret = common_pmem_map_file_with_signature_check(path,
> 			sizeof(struct hello_t), &mem);
> ```

in one line, please



_Code quote:_
```C
		ret = common_pmem_map_file_with_signature_check(path,
			sizeof(struct hello_t), &mem);
```
___
*[`examples/common/common-pmem2_map_file.c` line 20 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54jysbA2TEwKh1N8an:-N54jysbA2TEwKh1N8ao:b-7h6hmf) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem2_map_file.c#L20)):*
> ```C
> 	struct pmem2_map *map = NULL;
> 	struct pmem2_source *src = NULL;
> 	pmem2_persist_fn persist;
> ```

Not needed, see below



_Code quote:_
```C
pmem2_persist_fn persist;
```
___
*[`examples/common/common-pmem2_map_file.c` line 55 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kZAy0ZSxTtTS85ga:-N54kZAy0ZSxTtTS85gb:b-i32gpo) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem2_map_file.c#L55)):*
> ```C
> 
> 	if (pmem2_map_get_size(map) < min_size) {
> 		(void) fprintf(stderr,
> ```

in one line



_Code quote:_
```C
		(void) fprintf(stderr,
			"mapped size for (%s) is too small: %s\n",
```
___
*[`examples/common/common-pmem2_map_file.c` line 74 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kB9-A04tsfko6bQJ:-N54kB9-A04tsfko6bQK:blqadar) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem2_map_file.c#L74)):*
> ```C
> 	/* Get libpmem2 persist function from pmem2_map */
> 	persist = pmem2_get_persist_fn(map);
> 	mem->persist = persist;
> ```

The intermediate variable is not needed:

```
	mem->persist = pmem2_get_persist_fn(map);
```



_Code quote:_
```C
	persist = pmem2_get_persist_fn(map);
	mem->persist = persist;
```
___
*[`examples/common/common-pmem_map_file.c` line 48 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kgcMBgYgIi8O6yO2:-N54kgcMBgYgIi8O6yO3:bm8q4r6) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem_map_file.c#L48)):*
> ```C
> common_pmem_unmap_file(struct common_mem *mem)
> {
> 	if (mem->is_pmem) {
> ```

Not needed - it is checked outside of this function



_Code quote:_
```C
if (mem->is_pmem) {
```


<!-- Sent from Reviewable.io -->

2022-06-21 11:06 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1791#-N54umN984Xkv5vtTYv6:-N54umN984Xkv5vtTYv7:b-9fm59r) (no related file):*
@haichangsi  what side of connection requires memory configuration with initial value?



_Code quote (from examples/03-read-to-persistent/server.c):_
```C
0
```

___
___
*[`examples/03-read-to-persistent/client.c` line 148 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54wCwz3q29FShRyfPf:-N54wCwz3q29FShRyfPg:undefined) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/03-read-to-persistent/client.c#L148)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```





_Suggestion:_
```C
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);
	} else
```
___
*[`examples/03-read-to-persistent/server.c` line 201 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54uXqP-DwnhlUd_jbV:-N54uXqP-DwnhlUd_jbW:undefined) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/03-read-to-persistent/server.c#L201)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```





_Suggestion:_
```C
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);
	} else
```


<!-- Sent from Reviewable.io -->

2022-06-21 12:28 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 9 of 10 files reviewed, 8 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-22 07:56 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/03-read-to-persistent/client.c` line 53 at r12](https://reviewable.io/reviews/pmem/rpma/1791#-N59OXehAAXPSHbLmuFH:-N59OXehAAXPSHbLmuFI:b-sbjcvp) ([raw file](https://github.com/pmem/rpma/blob/4eeaefdc70e6998c832abc69092e9c64954cbf84/examples/03-read-to-persistent/client.c#L53)):*
> ```C
> 
> 		ret = common_pmem_map_file_with_signature_check(path,
> 			sizeof(struct hello_t), &mem);
> ```

The client does not need to provide any size as it uses ``struct hello_t``



_Suggestion:_
```C
		ret = common_pmem_map_file_with_signature_check(path, 0 , &mem);
```
___
*[`examples/03-read-to-persistent/server.c` line 55 at r12](https://reviewable.io/reviews/pmem/rpma/1791#-N59OqLH4KVQrSR05uwx:-N59OqLH4KVQrSR05uwy:b-ti7xcm) ([raw file](https://github.com/pmem/rpma/blob/4eeaefdc70e6998c832abc69092e9c64954cbf84/examples/03-read-to-persistent/server.c#L55)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = common_pmem_map_file_with_signature_check(pmem_path, 0, &mem);
> ```

The server must provide the size explicitly.



_Suggestion:_
```C
		/*
		 * All of the space under the offset is intended for
		 * the string contents. Space is assumed to be at least 1 KiB.
		 */
ret = common_pmem_map_file_with_signature_check(pmem_path, KILOBYTE, &mem);
```


<!-- Sent from Reviewable.io -->

2022-06-22 09:04 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 5 of 10 files reviewed, 11 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1791#-N54umN984Xkv5vtTYv6:-N59YlBwCDk5modwaCjC:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@haichangsi  what side of connection requires memory configuration with initial value?
</blockquote></details>

Done.

___
___
*[`examples/03-read-to-persistent/client.c` line 53 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54hb872LEPZxopZ2nZ:-N59XR3X0zwzo-0gITxN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/03-read-to-persistent/client.c#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

in one line, please
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/client.c` line 148 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54wCwz3q29FShRyfPf:-N59e0Fk9F-9kNXJetXs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/03-read-to-persistent/client.c#L148)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```

Done.
___
*[`examples/03-read-to-persistent/client.c` line 53 at r12](https://reviewable.io/reviews/pmem/rpma/1791#-N59OXehAAXPSHbLmuFH:-N59XRN8AjAQ6_mu8Ung:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4eeaefdc70e6998c832abc69092e9c64954cbf84/examples/03-read-to-persistent/client.c#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The client does not need to provide any size as it uses ``struct hello_t``
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/server.c` line 201 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54uXqP-DwnhlUd_jbV:-N59e1-I67je5FoxKFT8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/03-read-to-persistent/server.c#L201)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```

Done.
___
*[`examples/03-read-to-persistent/server.c` line 55 at r12](https://reviewable.io/reviews/pmem/rpma/1791#-N59OqLH4KVQrSR05uwx:-N59Y1J1CPBQ63rGXrg_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4eeaefdc70e6998c832abc69092e9c64954cbf84/examples/03-read-to-persistent/server.c#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The server must provide the size explicitly.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 20 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54jysbA2TEwKh1N8an:-N59Y_az2Ts39Ik5wIKn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem2_map_file.c#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed, see below
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 55 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kZAy0ZSxTtTS85ga:-N59YQbz1YFuzf89SWmO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem2_map_file.c#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

in one line
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 74 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kB9-A04tsfko6bQJ:-N59YZe5EZOYa00lT6Uw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem2_map_file.c#L74)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The intermediate variable is not needed:

```
	mem->persist = pmem2_get_persist_fn(map);
```
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.c` line 48 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kgcMBgYgIi8O6yO2:-N59YiZ62HnsJnA3P6fh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem_map_file.c#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed - it is checked outside of this function
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 59 at r12](https://reviewable.io/reviews/pmem/rpma/1791#-N55NSE313tvx6vwp_J9:-N59Y3Ka93AuxQi0Xala:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4eeaefdc70e6998c832abc69092e9c64954cbf84/examples/common/common-map_file_with_signature_check.c#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

original logic was correct
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-22 10:03 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r13, 3 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`examples/common/common-pmem_map_file.c` line 48 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kgcMBgYgIi8O6yO2:-N59r3rD5wFOC_D7ePN2:boi9i4) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem_map_file.c#L48)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@ldorau what is in a situation where somebody will call this function twice?
I think we should not make any assumption about ``mem`` content verification outside the function.


<!-- Sent from Reviewable.io -->

2022-06-22 11:14 UTC, grom72 approved these changes
> Reviewed 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-22 11:33 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`examples/common/common-pmem2_map_file.c` line 88 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5AAx3y4JYSz6rEzR-A:-N5AAx3y4JYSz6rEzR-B:b-4flc1q) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L88)):*
> ```C
> common_pmem_unmap_file(struct common_mem *mem)
> {
> 	(void) pmem2_map_delete(&mem->map);
> ```

And then:
```c
	if (mem->map) {
		(void) pmem2_map_delete(&mem->map);
		mem->mr_ptr = NULL;
		mem->is_pmem = 0;
	}
```



_Code quote:_
```C
	(void) pmem2_map_delete(&mem->map);
	mem->mr_ptr = NULL;
	mem->is_pmem = 0;
```
___
*[`examples/common/common-pmem_map_file.c` line 48 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kgcMBgYgIi8O6yO2:-N5A98puEwbqNX-cKprJ:b-hq1yt) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem_map_file.c#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau what is in a situation where somebody will call this function twice?
I think we should not make any assumption about ``mem`` content verification outside the function.
</blockquote></details>

OK, but IMHO `if (mem->mr_ptr) {` would be better in this case.


<!-- Sent from Reviewable.io -->

2022-06-22 11:45 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`examples/common/common-pmem2_map_file.c` line 55 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5ADV3r6eyejOUf6ZpG:-N5ADV3r6eyejOUf6ZpH:b-hx4t05) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L55)):*
> ```C
> 	if (pmem2_map_get_size(map) < min_size) {
> 		(void) fprintf(stderr, "mapped size for (%s) is too small: %s\n",
> 			path, pmem2_errormsg());
> ```

Shall we remove mapping in case of an error?



_Suggestion:_
```C
			path, pmem2_errormsg());
		(void) pmem2_map_delete(map);
		goto err_config_delete;
```
___
*[`examples/common/common-pmem_map_file.c` line 25 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5AD19S9aJqKCyGPee3:-N5AD19S9aJqKCyGPee4:biu4x6a) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L25)):*
> ```C
> 	}
> 
> 	if (mem->mr_size < min_size) {
> ```

Shall we unmapped if the size is too small?



_Suggestion:_
```C
	if (mem->mr_size < min_size) {
		(void) fprintf(stderr,
			"mapped size for %s is too small\n", path);
		(void) pmem_unmap(mem->mr_ptr, mem->mr_size);
		return -1;
	}
```


<!-- Sent from Reviewable.io -->

2022-06-23 06:03 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1791#-N5E7b7x0OF1yxs7shnh:-N5E7b7yB-MRyu2mVLjS:bd9zoda) (no related file):*
@haichangsi By the way, a few "one line" fixes - because we may not come back here soon ...

___
___
*[`examples/common/common-pmem2_map_file.c` line 27 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E7nHL2yuPuL34l0Jn:-N5E7nHL2yuPuL34l0Jo:b-2or7gt) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L27)):*
> ```C
> 
> 	if (pmem2_source_from_fd(&src, fd) != 0) {
> 		(void) fprintf(stderr,
> ```

one line



_Code quote:_
```C
		(void) fprintf(stderr,
			"pmem2_source_from_fd() failed\n");
```
___
*[`examples/common/common-pmem2_map_file.c` line 34 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8BjU6uYXxYyoiqv6:-N5E8BjU6uYXxYyoiqv7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L34)):*
> ```C
> 	if (pmem2_config_new(&cfg) != 0) {
> 		(void) fprintf(stderr,
> 			"pmem2_config_new() failed\n");
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
			"pmem2_config_new() failed\n");
```
___
*[`examples/common/common-pmem2_map_file.c` line 38 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8J3tAUaHaYEp4dHt:-N5E8J3tAUaHaYEp4dHu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L38)):*
> ```C
> 	}
> 
> 	if (pmem2_config_set_required_store_granularity(cfg,
> ```

.



_Code quote:_
```C
	if (pmem2_config_set_required_store_granularity(cfg,
			PMEM2_GRANULARITY_CACHE_LINE) != 0) {
```
___
*[`examples/common/common-pmem2_map_file.c` line 41 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8Urv5nGk_l2up7FF:-N5E8Urv5nGk_l2up7FG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L41)):*
> ```C
> 			PMEM2_GRANULARITY_CACHE_LINE) != 0) {
> 		(void) fprintf(stderr,
> 			"pmem2_config_set_required_store_granularity() failed: %s\n",
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
			"pmem2_config_set_required_store_granularity() failed: %s\n",
```
___
*[`examples/common/common-pmem2_map_file.c` line 48 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8anA7OTwwjJESiJl:-N5E8anA7OTwwjJESiJm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L48)):*
> ```C
> 	if (pmem2_map_new(&map, cfg, src) != 0) {
> 		(void) fprintf(stderr,
> 			"pmem2_map_new(%s) failed: %s\n",
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
			"pmem2_map_new(%s) failed: %s\n",
			path, pmem2_errormsg());
```
___
*[`examples/common/common-pmem2_map_file.c` line 55 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5ADV3r6eyejOUf6ZpG:-N5E8dD4Cj7Yg6LrGRSb:bbnqyo) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we remove mapping in case of an error?
</blockquote></details>

Yes, of course.
___
*[`examples/common/common-pmem_map_file.c` line 48 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kgcMBgYgIi8O6yO2:-N5E6F0H1tnb2mtdhFb3:bb3k8gd) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem_map_file.c#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

only ``mem->is_pmem`` is an indication of proper mapped PMem see: ``common_pmem_map_file``:
```
int
common_pmem_map_file(char *path, size_t min_size, struct common_mem *mem)
{
	mem->is_pmem = 0;
...
	if (mem->is_pmem)
		mem->persist = pmem_persist;
	return 0;
}

```
</blockquote></details>

OK, @haichangsi please revert `if (mem->is_pmem) {` here (a security check just in case - to not unmap it twice)
___
*[`examples/common/common-pmem_map_file.c` line 20 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8okh5Ago-NdgjfZL:-N5E8okh5Ago-NdgjfZM:b-2or7gt) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L20)):*
> ```C
> 			0 /* mode */, &mem->mr_size, &mem->is_pmem);
> 	if (mem->mr_ptr == NULL) {
> 		(void) fprintf(stderr,
> ```

one line



_Code quote:_
```C
		(void) fprintf(stderr,
			"pmem_map_file() for %s failed\n", path);
```
___
*[`examples/common/common-pmem_map_file.c` line 25 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5AD19S9aJqKCyGPee3:-N5E8ubp1xDTJDaNYOmY:b-4klk5u) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we unmapped if the size is too small?
</blockquote></details>

Yes, of course
___
*[`examples/common/common-pmem_map_file.c` line 26 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8zeK8kmIPvogtqj6:-N5E8zeK8kmIPvogtqj7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L26)):*
> ```C
> 
> 	if (mem->mr_size < min_size) {
> 		(void) fprintf(stderr,
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
			"mapped size for %s is too small\n", path);
```
___
*[`examples/common/common-pmem_map_file.c` line 33 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E90c6DPLKVgpQ_EKh:-N5E90c6DPLKVgpQ_EKi:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L33)):*
> ```C
> 	/* pmem is expected */
> 	if (!mem->is_pmem) {
> 		(void) fprintf(stderr, "%s is not an actual PMEM\n",
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr, "%s is not an actual PMEM\n",
			path);
```


<!-- Sent from Reviewable.io -->

2022-06-23 06:21 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 12 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-23 08:43 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 12 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/common/common-pmem2_map_file.c` line 27 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E7nHL2yuPuL34l0Jn:-N5EgQM63x6kFhZGjPI0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one line
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 34 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8BjU6uYXxYyoiqv6:-N5EgQi19yNAkzPt9RoA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 38 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8J3tAUaHaYEp4dHt:-N5EgWQTCRta95fi5eWe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 41 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8Urv5nGk_l2up7FF:-N5EgWui8JwQJHTYfJtd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 48 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8anA7OTwwjJESiJl:-N5EgcNx5ynb7V9OsZUG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 55 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5ADV3r6eyejOUf6ZpG:-N5EgxYjBd_eN_Kww9rR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, of course.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem2_map_file.c` line 88 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5AAx3y4JYSz6rEzR-A:-N5EhHIP73rDBmoJkYRg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem2_map_file.c#L88)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

And then:
```c
	if (mem->map) {
		(void) pmem2_map_delete(&mem->map);
		mem->mr_ptr = NULL;
		mem->is_pmem = 0;
	}
```

</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.c` line 48 at r11](https://reviewable.io/reviews/pmem/rpma/1791#-N54kgcMBgYgIi8O6yO2:-N5EhuZV1jeIliiT3ujH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/382e597decf2a412d6d29f746c645c959d6dd1be/examples/common/common-pmem_map_file.c#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, @haichangsi please revert `if (mem->is_pmem) {` here (a security check just in case - to not unmap it twice)
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.c` line 20 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8okh5Ago-NdgjfZL:-N5EhOoQ-Z__p7oIYDfv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one line
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.c` line 25 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5AD19S9aJqKCyGPee3:-N5EhZlJE8vR6fGNYoA6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, of course
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.c` line 26 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E8zeK8kmIPvogtqj6:-N5EhalY5RnKmD0kfmjW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.c` line 33 at r14](https://reviewable.io/reviews/pmem/rpma/1791#-N5E90c6DPLKVgpQ_EKh:-N5Eha_c5r93H53AJbZC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7e9ac0a72eb82121aac33c98fd5a3e182b74b76/examples/common/common-pmem_map_file.c#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-23 09:17 UTC, grom72 approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 12 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-23 09:36 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-23 09:40 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r13, 2 of 4 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791#-:-N5EvoSL8W_gOqaWh66w:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-23 10:11 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 48 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5F-HOK1shaneN3V-Hg:-N5F-HOL-qXkJcJIDByY:b-4n7hdo) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L48)):*
> ```C
> 		fprintf(stderr, "%s too small (%zu < %zu)\n", path,
> 			mem->mr_size, sizeof(struct hello_t));
> 		return -1;
> ```

First you ask for `SIGNATURE_LEN + min_size` of memory:
```c
if (common_pmem_map_file(path, SIGNATURE_LEN + min_size, mem))
```
but then you check for only `SIGNATURE_LEN`:
```c
if (mem->mr_size < SIGNATURE_LEN) {
```
and later for `SIGNATURE_LEN + sizeof(struct hello_t)`:
```c
if (mem->mr_size - mem->data_offset < sizeof(struct hello_t)) {
```

so the first check for only `SIGNATURE_LEN`is redundant.

IMHO you should check only for exactly the value you have asked for (`SIGNATURE_LEN + min_size`), any other does not make any sense.



_Code quote:_
```C
	if (mem->mr_size < SIGNATURE_LEN) {
		(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
				path, mem->mr_size, SIGNATURE_LEN);
		return -1;
	}
	mem->data_offset = SIGNATURE_LEN;

	/*
	 * The space under the offset is intended for storing the hello
	 * structure. So the total space is assumed to be at least
	 * 1 KiB + offset of the string contents.
	 */
	if (mem->mr_size - mem->data_offset < sizeof(struct hello_t)) {
		fprintf(stderr, "%s too small (%zu < %zu)\n", path,
			mem->mr_size, sizeof(struct hello_t));
		return -1;
	}
```


<!-- Sent from Reviewable.io -->

2022-06-23 10:50 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 58 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5F9dlX36-QZHrcV1TR:-N5F9dlX36-QZHrcV1TS:b-qmlooh) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L58)):*
> ```C
> 		if (size == 0) {
> 			/* write an initial value and persist it */
> 			write_hello_str((struct hello_t *)((uintptr_t)mem->mr_ptr
> ```

1) `mem->mr_ptr` is of `char *` type - you do not need to cast it
2) in one line, please



_Code quote:_
```C
(uintptr_t)mem->mr_ptr
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 60 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAEn3Bncs4SzAzec8:-N5FAEn3Bncs4SzAzec9:b-li7xpk) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L60)):*
> ```C
> 			write_hello_str((struct hello_t *)((uintptr_t)mem->mr_ptr
> 				+ mem->data_offset), en);
> 			mem->persist((struct hello_t *)((uintptr_t)mem->mr_ptr + mem->data_offset),
> ```

1) The `persist` function does not take `(struct hello_t *)` as the first argument.
2) in one line please



_Code quote:_
```C
mem->persist((struct hello_t *)(
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 64 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAdIL2uyZ-8LGnA-k:-N5FAdIL2uyZ-8LGnA-l:b-vvl88g) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L64)):*
> ```C
> 		} else {
> 			/* write an initial empty string and persist it */
> 			((char *)mem->mr_ptr + mem->data_offset)[0] = '\0';
> ```

`mem->mr_ptr` is already of `char *` type



_Code quote:_
```C
(char *)mem->mr_ptr
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 65 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAl6bEs6wVFJpYtle:-N5FAl6bEs6wVFJpYtlf:b-x4qgv0) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L65)):*
> ```C
> 			/* write an initial empty string and persist it */
> 			((char *)mem->mr_ptr + mem->data_offset)[0] = '\0';
> 			mem->persist(mem->mr_ptr, 1);
> ```

What address have you changed above?



_Code quote:_
```C
mem->persist(mem->mr_ptr, 1);
```


<!-- Sent from Reviewable.io -->

2022-06-23 11:07 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 48 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5F-HOK1shaneN3V-Hg:-N5FCMn03JCbnZcGQEOv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

First you ask for `SIGNATURE_LEN + min_size` of memory:
```c
if (common_pmem_map_file(path, SIGNATURE_LEN + min_size, mem))
```
but then you check for only `SIGNATURE_LEN`:
```c
if (mem->mr_size < SIGNATURE_LEN) {
```
and later for `SIGNATURE_LEN + sizeof(struct hello_t)`:
```c
if (mem->mr_size - mem->data_offset < sizeof(struct hello_t)) {
```

so the first check for only `SIGNATURE_LEN`is redundant.

IMHO you should check only for exactly the value you have asked for (`SIGNATURE_LEN + min_size`), any other does not make any sense.

</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 58 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5F9dlX36-QZHrcV1TR:-N5FD2uD9k6WeiVTnbUK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) `mem->mr_ptr` is of `char *` type - you do not need to cast it
2) in one line, please
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 60 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAEn3Bncs4SzAzec8:-N5FDlWf1NmBQWDZ_3G4:b7ss08c) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) The `persist` function does not take `(struct hello_t *)` as the first argument.
2) in one line please
</blockquote></details>

1. https://github.com/pmem/rpma/blob/master/examples/03-read-to-persistent/client.c#L92. Do you mean without casting?
___
*[`examples/common/common-map_file_with_signature_check.c` line 64 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAdIL2uyZ-8LGnA-k:-N5FE0B57K7_ZXcuGe6B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`mem->mr_ptr` is already of `char *` type
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 65 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAl6bEs6wVFJpYtle:-N5FEOrnEEf8wPP1kpst:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What address have you changed above?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-23 11:20 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 26 at r16](https://reviewable.io/reviews/pmem/rpma/1791#-N5FGx5z0uX77rgXhWx5:-N5FGx5z0uX77rgXhWx6:br84ipx) ([raw file](https://github.com/pmem/rpma/blob/da468a880dfe8721e253539de533e163a686c960/examples/common/common-map_file_with_signature_check.c#L26)):*
> ```C
> 		return -1;
> 
> 	/*
> ```

	/*
	 * At the beginning of the persistent memory, a signature is
	 * stored which marks its content as valid. So the total space is assumed to be at least SIGNATURE_LEN + the size expected by the user.
	 */



_Suggestion:_
```C
	/*

	 * The space under the offset is intended for storing the hello
	 * structure. So the total space is assumed to be at least
	 * 1 KiB + offset of the string contents.
	 */
```


<!-- Sent from Reviewable.io -->

2022-06-23 12:50 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 60 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAEn3Bncs4SzAzec8:-N5FaNcV0U6c_QN7kNHb:b-4lkp6v) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L60)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

1. https://github.com/pmem/rpma/blob/master/examples/03-read-to-persistent/client.c#L92. Do you mean without casting?
</blockquote></details>

Yes, no casting needed here.
___
*[`examples/common/common-map_file_with_signature_check.c` line 29 at r16](https://reviewable.io/reviews/pmem/rpma/1791#-N5FZnm-DEe7i5wEwEW9:-N5FZnm0DYIKh9b_GEQ2:bsiyxns) ([raw file](https://github.com/pmem/rpma/blob/da468a880dfe8721e253539de533e163a686c960/examples/common/common-map_file_with_signature_check.c#L29)):*
> ```C
> 	 * The space under the offset is intended for storing the hello
> 	 * structure. So the total space is assumed to be at least
> 	 * 1 KiB + offset of the string contents.
> ```

It is not true:

" * So the total space is assumed to be at least **1 KiB + offset** of the string contents."



_Code quote:_
```C
	 * structure. So the total space is assumed to be at least
	 * 1 KiB + offset of the string contents.
```


<!-- Sent from Reviewable.io -->

2022-06-23 14:42 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 60 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAEn3Bncs4SzAzec8:-N5G-Jm736JlNUaOglqG:b43mlti) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, no casting needed here.
</blockquote></details>

 In client: warning: assignment to ‘struct hello_t *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
   55 |                 hello = mem.mr_ptr + mem.data_offset;
So I thought it should be the same way here. Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 26 at r16](https://reviewable.io/reviews/pmem/rpma/1791#-N5FGx5z0uX77rgXhWx5:-N5FyGVoEjBc1RMq5wep:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da468a880dfe8721e253539de533e163a686c960/examples/common/common-map_file_with_signature_check.c#L26)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

	/*
	 * At the beginning of the persistent memory, a signature is
	 * stored which marks its content as valid. So the total space is assumed to be at least SIGNATURE_LEN + the size expected by the user.
	 */

</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 29 at r16](https://reviewable.io/reviews/pmem/rpma/1791#-N5FZnm-DEe7i5wEwEW9:-N5FzlCz0tg1QlnFU-ai:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da468a880dfe8721e253539de533e163a686c960/examples/common/common-map_file_with_signature_check.c#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not true:

" * So the total space is assumed to be at least **1 KiB + offset** of the string contents."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-23 18:28 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 28 at r17](https://reviewable.io/reviews/pmem/rpma/1791#-N5GoNJX-lrY3Hd8RjCu:-N5GoNJYEQlvYrPs3a3k:b-z88y1g) ([raw file](https://github.com/pmem/rpma/blob/c7cf3d461d2e72d187dd9e45df17cb3f98bcbc9b/examples/common/common-map_file_with_signature_check.c#L28)):*
> ```C
> 	/*
> 	 * At the beginning of the persistent memory, a signature is
> 	 * stored which marks its content as valid. So the total space is assumed to be at least
> ```

Can you adjust this comment to the actual line limit (100 characters)?



_Code quote:_
```C
	 * At the beginning of the persistent memory, a signature is
	 * stored which marks its content as valid. So the total space is assumed to be at least
	 * SIGNATURE_LEN + the size expected by the user.
```


<!-- Sent from Reviewable.io -->

2022-06-24 10:47 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 28 at r17](https://reviewable.io/reviews/pmem/rpma/1791#-N5GoNJX-lrY3Hd8RjCu:-N5KJPigDLfkWWZYhVwp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c7cf3d461d2e72d187dd9e45df17cb3f98bcbc9b/examples/common/common-map_file_with_signature_check.c#L28)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can you adjust this comment to the actual line limit (100 characters)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-24 11:12 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 60 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAEn3Bncs4SzAzec8:-N5KPMCPEVCnQMyFCn52:bflyp24) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L60)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

 In client: warning: assignment to ‘struct hello_t *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
   55 |                 hello = mem.mr_ptr + mem.data_offset;
So I thought it should be the same way here. Done.

</blockquote></details>

What OS? I have tried and I cannot see this issue:
https://github.com/ldorau/rpma/runs/7039673449


<!-- Sent from Reviewable.io -->

2022-06-24 11:16 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`examples/common/common-map_file_with_signature_check.c` line 60 at r15](https://reviewable.io/reviews/pmem/rpma/1791#-N5FAEn3Bncs4SzAzec8:-N5KQEFD0PGVnnTSRo1R:bno969i) ([raw file](https://github.com/pmem/rpma/blob/bae6e44bb93df75d36a8f5084d0189e9ff725232/examples/common/common-map_file_with_signature_check.c#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What OS? I have tried and I cannot see this issue:
https://github.com/ldorau/rpma/runs/7039673449
</blockquote></details>

It is OK now.


<!-- Sent from Reviewable.io -->

2022-06-24 11:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/common/common-map_file_with_signature_check.c` line 32 at r18](https://reviewable.io/reviews/pmem/rpma/1791#-N5KT2-k07fTG__nkdLW:-N5KT2-k07fTG__nkdLX:b-rueqyv) ([raw file](https://github.com/pmem/rpma/blob/969bd8e4a3421b484cb01fff39caef073c2ceddd/examples/common/common-map_file_with_signature_check.c#L32)):*
> ```C
> 	 */
> 	if (mem->mr_size < SIGNATURE_LEN + min_size) {
> 		(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
> ```

`has too small size`



_Code quote:_
```C
too small
```


<!-- Sent from Reviewable.io -->

2022-06-24 11:30 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 32 at r18](https://reviewable.io/reviews/pmem/rpma/1791#-N5KT2-k07fTG__nkdLW:-N5KTdOo0U22v5y-uwoF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/969bd8e4a3421b484cb01fff39caef073c2ceddd/examples/common/common-map_file_with_signature_check.c#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`has too small size`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-24 11:31 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791#-:-N5KTtQ86z8vHfX-HHzn:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-06-24 12:31 UTC, osalyk approved these changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-06-27 09:54 UTC, osalyk approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-27 10:34 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-27 10:35 UTC, merged