common: documentation of running unit and multithreaded tests
pmem/rpma pull request #1818
Opened 2022-06-09 07:41 UTC by osalyk

2022-06-09 07:44 UTC, grom72 requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46PoZC1CqE1HJND6RQ:-N46PoZC1CqE1HJND6RR:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L17)):*
> ```Markdown
> 
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
> ```





_Suggestion:_
```Markdown
$ cd build
$ rm -rf
$ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
$ make test
$ ctest
```
___
*[`DEVELOPMENT.md` line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46Q-uS5CeFOKSssPYQ:-N46Q-uS5CeFOKSssPYR:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L34)):*
> ```Markdown
> - turn on building the multi-threaded tests and run them
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> ```





_Suggestion:_
```Markdown
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
```


<!-- Sent from Reviewable.io -->

2022-06-09 07:48 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46QimdAd-zxngDHb--:-N46QimdAd-zxngDHb-0:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L39)):*
> ```CMake
> 
> option(BUILD_EXAMPLES "build examples" ON)
> option(BUILD_TESTS "build tests" ON)
> ```





_Suggestion:_
```CMake
option(BUILD_TESTS "build tests" OFF)
```


<!-- Sent from Reviewable.io -->

2022-06-09 07:55 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 1 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1818#-N46RfFq5XKjJwyG5ETe:-N46RfFrAKbspyKHuXn9:b-apk8ua) (no related file):*
It seems that some mtt tests should be disabled while TESTS_RDMA_CONNECTION=OFF:
```
The following tests FAILED:
         88 - multithreaded-conn-rpma_conn_get_private_data_0_none (Failed)
         89 - multithreaded-conn-rpma_conn_req_new_0_none (Failed)
         90 - multithreaded-conn-rpma_read_0_none (Failed)
         91 - multithreaded-conn-rpma_write_0_none (Failed)
         92 - multithreaded-conn-rpma_write_read_0_none (Failed)
         93 - multithreaded-conn-rpma_send_0_none (Failed)
         94 - multithreaded-ep-rpma_ep_get_fd_0_none (Failed)
         95 - multithreaded-ep-rpma_ep_listen_0_none (Failed)
         97 - multithreaded-mr-rpma_mr_get_descriptor_0_none (Failed)
         98 - multithreaded-mr-rpma_mr_get_ptr_0_none (Failed)
         99 - multithreaded-mr-rpma_mr_get_size_0_none (Failed)
        100 - multithreaded-mr-rpma_mr_reg_0_none (Failed)
        101 - multithreaded-mr-rpma_mr_remote_from_descriptor_0_none (Failed)
```

___
___
*[`CMakeLists.txt` line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46S3Ud66TeEMZXONPN:-N46S3Ud66TeEMZXONPO:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L55)):*
> ```CMake
> option(TESTS_USE_VALGRIND_PMEMCHECK "enable tests with valgrind pmemcheck (if found)" OFF)
> option(TESTS_LONG "enable long running tests" OFF)
> option(TEST_PYTHON_TOOLS "run tests for Python tools" ON)
> ```





_Suggestion:_
```CMake
option(TEST_PYTHON_TOOLS "run tests for Python tools" OFF)
```
___
*[`DEVELOPMENT.md` line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46RQ-K7K7ucpxuX4HS:-N46RQ-LCypovuXh4Xle:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L18)):*
> ```Markdown
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
> $ make test
> ```





_Suggestion:_
```Markdown
$ make
$ make test
```
``ctest`` command can be used instead of ``make test``
```
___
*[`.circleci/config.yml` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SNUV5-chvBE64Q6y:-N46SNUV5-chvBE64Q6z:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/.circleci/config.yml#L23)):*
> ```YAML
>             mkdir build
>             cd build
>             RPMA_TESTING_IP="will_be_set_later" cmake .. -DTESTS_USE_VALGRIND=ON -DTESTS_RDMA_CONNECTION=ON
> ```





_Suggestion:_
```YAML
RPMA_TESTING_IP="will_be_set_later" cmake .. -DBUILD_TESTS=ON -DTESTS_USE_VALGRIND=ON -DTESTS_RDMA_CONNECTION=ON
```


<!-- Sent from Reviewable.io -->

2022-06-09 08:00 UTC, grom72 requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46TSLXAXhrYcFP10q5:-N46TSLXAXhrYcFP10q6:b-j75f3f) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L24)):*
> ```Markdown
> ## Run multi-threaded tests
> 
> To run multithreaded tests we need configured RDMA-capable network interface.
> ```

some mt tests do not require RDMA interafce



_Suggestion:_
```Markdown
To run all multithreaded
```
___
*[`DEVELOPMENT.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46T5Xx9LwAIU62sU0y:-N46T5Xx9LwAIU62sU0z:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L46)):*
> ```Markdown
> ```
> - turn on building the multi-threaded tests and run them
> ```shell
> ```





_Suggestion:_
```Markdown
```shell
$ cd build
```
___
*[`DEVELOPMENT.md` line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SpX_3WZRYlBMLDRl:-N46SpX_3WZRYlBMLDRm:undefined) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L48)):*
> ```Markdown
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> $ make test
> ```





_Suggestion:_
```Markdown
$ make
$ make test
```
___
*[`DEVELOPMENT.md` line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SvCh-KXszQ_wuvaJ:-N46SvCh-KXszQ_wuvaK:b-jrs2bi) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L49)):*
> ```Markdown
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> $ make test
> $ ctest
> ```

redundant with ``make test``


<!-- Sent from Reviewable.io -->

2022-06-09 10:02 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 2 of 4 files reviewed, 11 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1818#-N46RfFq5XKjJwyG5ETe:-N46tOHo8r2rKxODvtcE:b-dsbj2f) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It seems that some mtt tests should be disabled while TESTS_RDMA_CONNECTION=OFF:
```
The following tests FAILED:
         88 - multithreaded-conn-rpma_conn_get_private_data_0_none (Failed)
         89 - multithreaded-conn-rpma_conn_req_new_0_none (Failed)
         90 - multithreaded-conn-rpma_read_0_none (Failed)
         91 - multithreaded-conn-rpma_write_0_none (Failed)
         92 - multithreaded-conn-rpma_write_read_0_none (Failed)
         93 - multithreaded-conn-rpma_send_0_none (Failed)
         94 - multithreaded-ep-rpma_ep_get_fd_0_none (Failed)
         95 - multithreaded-ep-rpma_ep_listen_0_none (Failed)
         97 - multithreaded-mr-rpma_mr_get_descriptor_0_none (Failed)
         98 - multithreaded-mr-rpma_mr_get_ptr_0_none (Failed)
         99 - multithreaded-mr-rpma_mr_get_size_0_none (Failed)
        100 - multithreaded-mr-rpma_mr_reg_0_none (Failed)
        101 - multithreaded-mr-rpma_mr_remote_from_descriptor_0_none (Failed)
```
</blockquote></details>

All multithreaded tests are disabled
https://github.com/pmem/rpma/blob/master/tests/CMakeLists.txt#L49

___
___
*[`CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46QimdAd-zxngDHb--:-N46tcrJ1t32H9PEecPt:be8ewew) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L39)):*
> ```CMake
> 
> option(BUILD_EXAMPLES "build examples" ON)
> option(BUILD_TESTS "build tests" ON)
> ```

This change should not apply to this PR
___
*[`CMakeLists.txt` line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46S3Ud66TeEMZXONPN:-N46tdiFERwvx1D7MlJT:be8ewew) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L55)):*
> ```CMake
> option(TESTS_USE_VALGRIND_PMEMCHECK "enable tests with valgrind pmemcheck (if found)" OFF)
> option(TESTS_LONG "enable long running tests" OFF)
> option(TEST_PYTHON_TOOLS "run tests for Python tools" ON)
> ```

This change should not apply to this PR
___
*[`DEVELOPMENT.md` line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46PoZC1CqE1HJND6RQ:-N46tom90ZTU8O-gNaKn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L17)):*
> ```Markdown
> 
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
> ```

Done.
___
*[`DEVELOPMENT.md` line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46RQ-K7K7ucpxuX4HS:-N46u1LZ-DfzBZvsEktJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L18)):*
> ```Markdown
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
> $ make test
> ```

Done.
___
*[`DEVELOPMENT.md` line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46Q-uS5CeFOKSssPYQ:-N46u7LwB361f-BwNpyC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L34)):*
> ```Markdown
> - turn on building the multi-threaded tests and run them
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> ```

Done.
___
*[`DEVELOPMENT.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46T5Xx9LwAIU62sU0y:-N46uF9q9nIPzKnmLaeZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L46)):*
> ```Markdown
> ```
> - turn on building the multi-threaded tests and run them
> ```shell
> ```

Done.
___
*[`DEVELOPMENT.md` line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SpX_3WZRYlBMLDRl:-N46uFak0PYb6xGaL3lu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L48)):*
> ```Markdown
> ```shell
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> $ make test
> ```

Done.
___
*[`DEVELOPMENT.md` line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SvCh-KXszQ_wuvaJ:-N46uGSB9ybzjRSgbwdB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/DEVELOPMENT.md#L49)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant with ``make test``
</blockquote></details>

Done.
___
*[`.circleci/config.yml` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SNUV5-chvBE64Q6y:-N46uLFP5RfvdIMI3epo:be8ewew) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/.circleci/config.yml#L23)):*
> ```YAML
>             mkdir build
>             cd build
>             RPMA_TESTING_IP="will_be_set_later" cmake .. -DTESTS_USE_VALGRIND=ON -DTESTS_RDMA_CONNECTION=ON
> ```

This change should not apply to this PR


<!-- Sent from Reviewable.io -->

2022-06-09 11:03 UTC, grom72 requested changes
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46QimdAd-zxngDHb--:-N475hcmB_6deRytw1Nb:b5e6dz4) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L39)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This change should not apply to this PR
</blockquote></details>

What about this: ''cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..''



_Code quote (from DEVELOPMENT.md):_
```Markdown
cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
```


<!-- Sent from Reviewable.io -->

2022-06-09 11:05 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46QimdAd-zxngDHb--:-N477ejvA_i-S5CYxy-D:b-79g9y3) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What about this: ''cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..''
</blockquote></details>

If the default configuration sets BUILD_TESTS to 1 there is no point to set it manually


<!-- Sent from Reviewable.io -->

2022-06-09 11:51 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46QimdAd-zxngDHb--:-N47I7k84CxoWFKep0dB:b-7upi84) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L39)):*
> If the default configuration sets BUILD_TESTS to 1 there is no point to set it manually

That's right.
___
*[`DEVELOPMENT.md` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1818#-N47IHbK-tGTTn_xpUjs:-N47IHbK-tGTTn_xpUjt:bqxvhoz) ([raw file](https://github.com/pmem/rpma/blob/e83e14293c4d05341cf7e8f57b2a5e4613f36d5f/DEVELOPMENT.md#L19)):*
> ```Markdown
> $ cd build
> $ rm -rf
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
> ```

It is turned on by default.



_Code quote:_
```Markdown
-DBUILD_TESTS=ON
```
___
*[`DEVELOPMENT.md` line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1818#-N47IM124zo1qoHTEWw7:-N47IM124zo1qoHTEWw8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e83e14293c4d05341cf7e8f57b2a5e4613f36d5f/DEVELOPMENT.md#L39)):*
> ```Markdown
> $ cd build
> $ rm -rf
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> ```

.



_Code quote:_
```Markdown
-DBUILD_TESTS=ON
```
___
*[`DEVELOPMENT.md` line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1818#-N47INaO7gDLL62obzHe:-N47INaP1tYzzGecvrsj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e83e14293c4d05341cf7e8f57b2a5e4613f36d5f/DEVELOPMENT.md#L55)):*
> ```Markdown
> $ cd build
> $ rm -rf
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DTESTS_RDMA_CONNECTION=ON ..
> ```

.



_Code quote:_
```Markdown
-DBUILD_TESTS=ON
```
___
*[`.circleci/config.yml` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SNUV5-chvBE64Q6y:-N47IS2h6xVnV5rKiqOI:bno969i) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/.circleci/config.yml#L23)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This change should not apply to this PR
</blockquote></details>

It is OK now.


<!-- Sent from Reviewable.io -->

2022-06-09 12:06 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46QimdAd-zxngDHb--:-N47KVxK4ojoTPyEg73B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/CMakeLists.txt#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> If the default configuration sets BUILD_TESTS to 1 there is no point to set it manually

That's right.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1818#-N47IHbK-tGTTn_xpUjs:-N47KAub9Epbs2TPCeUV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e83e14293c4d05341cf7e8f57b2a5e4613f36d5f/DEVELOPMENT.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is turned on by default.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1818#-N47IM124zo1qoHTEWw7:-N47KEQU2hanaZHz02dX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e83e14293c4d05341cf7e8f57b2a5e4613f36d5f/DEVELOPMENT.md#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1818#-N47INaO7gDLL62obzHe:-N47KGc6-sZMO5HTuGqq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e83e14293c4d05341cf7e8f57b2a5e4613f36d5f/DEVELOPMENT.md#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`.circleci/config.yml` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1818#-N46SNUV5-chvBE64Q6y:-N47KTTZ511XBC_W6xLb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68609d2ad6cd5adbf40aab11b3d44a861fa32f02/.circleci/config.yml#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is OK now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 12:08 UTC, grom72 requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MC230_dD_IPdnkpU:-N47MC230_dD_IPdnkpV:b-52f67u) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L15)):*
> ```Markdown
> 
> The unit tests are written using the cmocka framework, for more information please see [cmocka](https://cmocka.org/).
> ```

Please see ./test/unit/ directory for examples


<!-- Sent from Reviewable.io -->

2022-06-09 12:08 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-09 12:09 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-09 12:11 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MC230_dD_IPdnkpU:-N47NBFDEtgNV73G6nve:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please see ./test/unit/ directory for examples
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 12:14 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MuuKBUi0Rl5KDv6_:-N47MuuKBUi0Rl5KDv6a:bsioia4) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L20)):*
> ```Markdown
> ```shell
> $ cd build
> $ rm -rf
> ```

What is it for?



_Code quote:_
```Markdown
rm -rf
```
___
*[`DEVELOPMENT.md` line 21 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MhEmCqf4xkacbSUp:-N47MhEn6K7s_nCJxaoX:bwtrhvc) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L21)):*
> ```Markdown
> $ cd build
> $ rm -rf
> $ cmake; make -j${nproc}; make test
> ```

```sh
$ cmake ..
$ make -j${nproc}
$ make test
```



_Code quote:_
```Markdown
cmake; make -j${nproc}; make test
```
___
*[`DEVELOPMENT.md` line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MzbXD-L_AsJnM4C3:-N47MzbXD-L_AsJnM4C4:b3kre) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L38)):*
> ```Markdown
> ```shell
> $ cd build
> $ rm -rf
> ```

?



_Code quote:_
```Markdown
 rm -rf
```
___
*[`DEVELOPMENT.md` line 40 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NNA647sAqLnngJ8m:-N47NNA647sAqLnngJ8n:b-z6afo5) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L40)):*
> ```Markdown
> $ rm -rf
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DTESTS_USE_VALGRIND=ON ..
> $ make
> ```

```sh
$ make -j${nproc}
```



_Code quote:_
```Markdown
$ make
```
___
*[`DEVELOPMENT.md` line 54 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NX3r5qdF0bEJCM0c:-N47NX3r5qdF0bEJCM0d:b3kre) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L54)):*
> ```Markdown
> ```shell
> $ cd build
> $ rm -rf
> ```

?



_Code quote:_
```Markdown
$ rm -rf
```
___
*[`DEVELOPMENT.md` line 56 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NVau7XCLSWr7t7r7:-N47NVau7XCLSWr7t7r8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L56)):*
> ```Markdown
> $ rm -rf
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DTESTS_USE_VALGRIND=ON ..
> $ make
> ```

.



_Code quote:_
```Markdown
$ make
```


<!-- Sent from Reviewable.io -->

2022-06-09 12:15 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 23 at r5](https://reviewable.io/reviews/pmem/rpma/1818#-N47O-0BCOMPDr9m3pvh:-N47O-0BCOMPDr9m3pvi:b-zes8cb) ([raw file](https://github.com/pmem/rpma/blob/bd7eaa07d7523107eab8e287b68a1329615e6697/DEVELOPMENT.md#L23)):*
> ```Markdown
> $ cd build
> $ rm -rf
> $ cmake ..; make -j${nproc}; make test
> ```

Why in one line? It is less readable.



_Code quote:_
```Markdown
$ cmake ..; make -j${nproc}; make test
```


<!-- Sent from Reviewable.io -->

2022-06-09 12:18 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MuuKBUi0Rl5KDv6_:-N47OGum2afjvbTofUsT:b-dqbhiz) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is it for?
</blockquote></details>

@grom72 suggestion
___
*[`DEVELOPMENT.md` line 21 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MhEmCqf4xkacbSUp:-N47OSz77bN7mmFSjm61:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```sh
$ cmake ..
$ make -j${nproc}
$ make test
```

</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MzbXD-L_AsJnM4C3:-N47Oa8S47Msp0rSdyuZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

.
___
*[`DEVELOPMENT.md` line 40 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NNA647sAqLnngJ8m:-N47Oezk3KVH6_ateoz5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```sh
$ make -j${nproc}
```

</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 54 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NX3r5qdF0bEJCM0c:-N47OffeBBSsev5vU40A:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

.
___
*[`DEVELOPMENT.md` line 56 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NVau7XCLSWr7t7r7:-N47Ogbm5tNM-CEn4grR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 23 at r5](https://reviewable.io/reviews/pmem/rpma/1818#-N47O-0BCOMPDr9m3pvh:-N47OYT9B-YT99jkgFta:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bd7eaa07d7523107eab8e287b68a1329615e6697/DEVELOPMENT.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why in one line? It is less readable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 12:34 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MuuKBUi0Rl5KDv6_:-N47RuoYBchYrQe22TMJ:b-ofb841) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L20)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

@grom72 suggestion
</blockquote></details>

OK, but what does it do? :-D
___
*[`DEVELOPMENT.md` line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MzbXD-L_AsJnM4C3:-N47S9Dk20PuqDZuY5Se:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L38)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`DEVELOPMENT.md` line 54 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NX3r5qdF0bEJCM0c:-N47SB4SC9dLLwd1ncqW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L54)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-06-09 17:11 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-10 06:06 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MuuKBUi0Rl5KDv6_:-N4BC_N735nc5GYXOIjI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk please remove it
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47MzbXD-L_AsJnM4C3:-N4BCkJYA2nZYkbI7eaw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk please remove it
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 54 at r3](https://reviewable.io/reviews/pmem/rpma/1818#-N47NX3r5qdF0bEJCM0c:-N4BCyWzCqND84ORRGWj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d81b7d88432e7ee5cc48688306ca2698b3816076/DEVELOPMENT.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk please remove it
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 14 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47aYI1EQzcDV_YAL1W:-N4BCYX128iUmDe7sDHH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

One of the basic principles of delivering new functionality to a library is to deliver it simultaneously as the unit tests to ensure that the new features behave correctly.
You have to expect that code that degrades test coverage will not go through the review process unless it is explicitly marked as a draft.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 34 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47cHigEs5nkdQLCxgE:-N4BCiZyAxDSz6GHbig5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L34)):*
> ```Markdown
> 
> ### Run multi-threaded tests on SoftRoCE:
> - configure SoftRoCE with tools/config_softroce.sh script
> ```

Done.
___
*[`DEVELOPMENT.md` line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47cslo1NF-kO5V6w0A:-N4BCu_kAY8sr1wCRtxc:bta66vs) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can we use this address for MT tests? It does not work for me :(.
</blockquote></details>

This is an example, you have to specify what you set.


<!-- Sent from Reviewable.io -->

2022-06-10 06:14 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47cslo1NF-kO5V6w0A:-N4BEhkDDglPrf0wi9Wl:bz0kwbq) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This is an example, you have to specify what you set.
</blockquote></details>

``192.168.1.72`` looks more similar to what people may use. They will NEVER use 127.0.0.1


<!-- Sent from Reviewable.io -->

2022-06-10 06:46 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47cslo1NF-kO5V6w0A:-N4BM7CI1lBY1ffuRwfT:bjnduyr) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``192.168.1.72`` looks more similar to what people may use. They will NEVER use 127.0.0.1
</blockquote></details>

`$ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here`



_Code quote:_
```Markdown
$ export RPMA_TESTING_IP=127.0.0.0
```
___
*[`DEVELOPMENT.md` line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BIla621nMC_0guB0_:-N4BIla621nMC_0guB0a:be85tzv) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L14)):*
> ```Markdown
> ## Run unit tests
> 
> One of the basic principles of delivering new functionality to a library is to deliver it simultaneously as the unit tests to ensure that the new features behave correctly.
> ```

simultaneously with the unit tests



_Code quote:_
```Markdown
simultaneously as the unit tests
```
___
*[`DEVELOPMENT.md` line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BK3zH9KsStIH36dJu:-N4BK3zH9KsStIH36dJv:buvqj3b) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L14)):*
> ```Markdown
> ## Run unit tests
> 
> One of the basic principles of delivering new functionality to a library is to deliver it simultaneously as the unit tests to ensure that the new features behave correctly.
> ```

a new functionality



_Code quote:_
```Markdown
new functionality
```
___
*[`DEVELOPMENT.md` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BIzB_9V6xVaCJH_FO:-N4BIzB_9V6xVaCJH_FP:b-crpw66) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L15)):*
> ```Markdown
> 
> One of the basic principles of delivering new functionality to a library is to deliver it simultaneously as the unit tests to ensure that the new features behave correctly.
> You have to expect that code that degrades test coverage will not go through the review process unless it is explicitly marked as a draft.
> ```

the test coverage



_Code quote:_
```Markdown
test coverage
```
___
*[`DEVELOPMENT.md` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJ8k49xHfBd014IQT:-N4BJ8k5-7V2CQPG8-HR:bb7mg7q) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L15)):*
> ```Markdown
> 
> One of the basic principles of delivering new functionality to a library is to deliver it simultaneously as the unit tests to ensure that the new features behave correctly.
> You have to expect that code that degrades test coverage will not go through the review process unless it is explicitly marked as a draft.
> ```

pass



_Code quote:_
```Markdown
go through
```
___
*[`DEVELOPMENT.md` line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJMrT7XvpK4pmXLM3:-N4BJMrT7XvpK4pmXLM4:b1nkzy7) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L17)):*
> ```Markdown
> You have to expect that code that degrades test coverage will not go through the review process unless it is explicitly marked as a draft.
> 
> The unit tests are written using the cmocka framework, for more information please see [cmocka](https://cmocka.org/).
> ```

The unit tests are implemented using the [cmocka](https://cmocka.org/) framework.



_Code quote:_
```Markdown
The unit tests are written using the cmocka framework, for more information please see [cmocka](https://cmocka.org/).
```
___
*[`DEVELOPMENT.md` line 19 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJ_t25mn-NiDnUqyb:-N4BJ_t25mn-NiDnUqyc:b-eglxqt) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L19)):*
> ```Markdown
> The unit tests are written using the cmocka framework, for more information please see [cmocka](https://cmocka.org/).
> 
> Please see ``./tests/unit/`` directory for examples
> ```

the ``./tests/unit/`` directory 



_Code quote:_
```Markdown
``./tests/unit/`` directory 
```
___
*[`DEVELOPMENT.md` line 19 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJsWO1oJrAL-ypo8G:-N4BJsWO1oJrAL-ypo8H:b-igwhuq) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L19)):*
> ```Markdown
> The unit tests are written using the cmocka framework, for more information please see [cmocka](https://cmocka.org/).
> 
> Please see ``./tests/unit/`` directory for examples
> ```

All unit tests are located in the ``./tests/unit/`` directory.



_Code quote:_
```Markdown
Please see ``./tests/unit/`` directory for examples
```
___
*[`DEVELOPMENT.md` line 21 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKHmN2EuiiEUKdu6t:-N4BKHmN2EuiiEUKdu6u:bcy3wa4) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L21)):*
> ```Markdown
> Please see ``./tests/unit/`` directory for examples
> 
> To run unit tests you need to:
> ```

you need to issue the following commands:



_Code quote:_
```Markdown
you need to:
```
___
*[`DEVELOPMENT.md` line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLIScArfg1zBC-2ON:-N4BLIScArfg1zBC-2OO:b-t4fht5) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L23)):*
> ```Markdown
> To run unit tests you need to:
> 
> ```shell
> ```

AFAIR we have used ```sh so far ... 



_Code quote:_
```Markdown
```shell
```
___
*[`DEVELOPMENT.md` line 29 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BK_XP7usyH8sgZW3S:-N4BK_XP7usyH8sgZW3T:b-61wf4k) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L29)):*
> ```Markdown
> $ make test
> ```
> ``ctest`` command can be used instead of ``make test``
> ```

The ``ctest`` command



_Code quote:_
```Markdown
``ctest`` command
```
___
*[`DEVELOPMENT.md` line 33 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKhKJ4ErJpgQzPkLJ:-N4BKhKJ4ErJpgQzPkLK:bhg2dtu) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L33)):*
> ```Markdown
> ## Run multi-threaded tests
> 
> To run all multithreaded tests we need configured RDMA-capable network interface.
> ```

multi-threaded



_Code quote:_
```Markdown
multithreaded
```
___
*[`DEVELOPMENT.md` line 33 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKksf5nOebCl3063R:-N4BKksf5nOebCl3063S:b91r3s2) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L33)):*
> ```Markdown
> ## Run multi-threaded tests
> 
> To run all multithreaded tests we need configured RDMA-capable network interface.
> ```

a configured



_Code quote:_
```Markdown
configured
```
___
*[`DEVELOPMENT.md` line 33 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKqClEXCZndGeozFS:-N4BKqClEXCZndGeozFT:ba1lybd) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L33)):*
> ```Markdown
> ## Run multi-threaded tests
> 
> To run all multithreaded tests we need configured RDMA-capable network interface.
> ```

a configured RDMA-capable network interface is needed.



_Code quote:_
```Markdown
we need configured RDMA-capable network interface.
```
___
*[`DEVELOPMENT.md` line 36 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLXuVEMmOTexUER5R:-N4BLXuVEMmOTexUER5S:bxrtu3j) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L36)):*
> ```Markdown
> 
> ### Run multi- [...]

2022-06-10 07:04 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47cslo1NF-kO5V6w0A:-N4BQBGpAIkgHnFGRUF1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`$ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here`
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BIla621nMC_0guB0_:-N4BNF4nA58q9dlzjvOO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

simultaneously with the unit tests
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BK3zH9KsStIH36dJu:-N4BNP3jCGzaukehyHc0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a new functionality
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BIzB_9V6xVaCJH_FO:-N4BNT1F-pL2W9nfgHLN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the test coverage
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 15 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJ8k49xHfBd014IQT:-N4BNWkX-w_Yz-qrrAfG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

pass
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 17 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJMrT7XvpK4pmXLM3:-N4BOwSQ1fxdhHK0zfuR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The unit tests are implemented using the [cmocka](https://cmocka.org/) framework.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 19 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJ_t25mn-NiDnUqyb:-N4BP2kL7vpADJezMaWb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the ``./tests/unit/`` directory 
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 19 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BJsWO1oJrAL-ypo8G:-N4BP7GI67ckB7Em8j1q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All unit tests are located in the ``./tests/unit/`` directory.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 21 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKHmN2EuiiEUKdu6t:-N4BPFJy2F6mNPns2ntw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

you need to issue the following commands:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLIScArfg1zBC-2ON:-N4BPMND41G8l-gx5K47:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

AFAIR we have used ```sh so far ... 
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 29 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BK_XP7usyH8sgZW3S:-N4BPPqsB5ora4NtORFx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The ``ctest`` command
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 33 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKhKJ4ErJpgQzPkLJ:-N4BPSrY59xnvrFmY9SZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

multi-threaded
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 33 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKksf5nOebCl3063R:-N4BPUaEEoN0zHJetDO2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a configured
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 33 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BKqClEXCZndGeozFS:-N4BPXu_5MzSppuAV5eb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a configured RDMA-capable network interface is needed.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 36 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLXuVEMmOTexUER5R:-N4BPe8U3WZ-znqBJdT3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

usimg the ...
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 37 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLceYA50jS4qw0aAZ:-N4BPt8g5CB43XPOxqAd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

set the `RPMA_TESTING_IP` environment variable
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 48 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLqulEo0bf8Pi1CNf:-N4BQ-Kx3OvDYonfRJfv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The ``ctest`` command
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 52 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLwHy9qy9sWc_5Mqw:-N4BQ3XDBxKHdOgMDf_G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

set the `RPMA_TESTING_IP` environment variable
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 07:12 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLceYA50jS4qw0aAZ:-N4BRp6U7lVQZHTr_D0A:b-964h55) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe
```
`RPMA_TESTING_IP`
```
?
___
*[`DEVELOPMENT.md` line 52 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLwHy9qy9sWc_5Mqw:-N4BS1PV1USX4aOCbHb7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L52)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-06-10 07:16 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 37 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLceYA50jS4qw0aAZ:-N4BT49PDcgGTpbd0Wx9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe
```
`RPMA_TESTING_IP`
```
?
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 52 at r7](https://reviewable.io/reviews/pmem/rpma/1818#-N4BLwHy9qy9sWc_5Mqw:-N4BTEW56-StkaKTk3fK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a33d3dc0bd46107cb04e064e940565943f294c78/DEVELOPMENT.md#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 07:27 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2022-06-10 08:15 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`DEVELOPMENT.md` line 53 at r6](https://reviewable.io/reviews/pmem/rpma/1818#-N47cslo1NF-kO5V6w0A:-N4Bfdk54GiW7A-v8-9t:bhcj54j) ([raw file](https://github.com/pmem/rpma/blob/6691539299cee200c24769f9895773bb79b27d46/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72 ping


<!-- Sent from Reviewable.io -->

2022-06-10 08:36 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-10 09:33 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-10 10:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`DEVELOPMENT.md` line 26 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C4nm72wLlhW8MYu4L:-N4C4nm72wLlhW8MYu4M:b-zaebms) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L26)):*
> ```Markdown
> $ cd build
> $ cmake ..
> $ make -j${nproc}
> ```

`$(nproc)` instead of `${nproc}` - it is not a variable but a command.



_Code quote:_
```Markdown
${nproc}
```
___
*[`DEVELOPMENT.md` line 45 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C4zoT4GV9q2HH-jvE:-N4C4zoT4GV9q2HH-jvF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L45)):*
> ```Markdown
> $ cd build
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DTESTS_USE_VALGRIND=ON ..
> $ make -j${nproc}
> ```

.



_Code quote:_
```Markdown
$ make -j${nproc}
```
___
*[`DEVELOPMENT.md` line 60 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C509s3KM13vr26Ql9:-N4C509s3KM13vr26QlA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L60)):*
> ```Markdown
> $ cd build
> $ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DTESTS_USE_VALGRIND=ON ..
> $ make -j${nproc}
> ```

.



_Code quote:_
```Markdown
 make -j${nproc}
```


<!-- Sent from Reviewable.io -->

2022-06-10 10:11 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[`DEVELOPMENT.md` line 36 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5BhrCBCnhfpofnHR:-N4C5BhrCBCnhfpofnHS:bz5ows6) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L36)):*
> ```Markdown
> 
> ### Run multi-threaded tests on SoftRoCE:
> - configure SoftRoCE using the tools/config_softroce.sh script or `make config_softroce`
> ```

```
`tools/config_softroce.sh`
```



_Code quote:_
```Markdown
tools/config_softroce.sh
```


<!-- Sent from Reviewable.io -->

2022-06-10 10:14 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5OXb8xWvmSiKbZZL:-N4C5OXb8xWvmSiKbZZM:b-fvdk4n) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L37)):*
> ```Markdown
> ### Run multi-threaded tests on SoftRoCE:
> - configure SoftRoCE using the tools/config_softroce.sh script or `make config_softroce`
> - set the `RPMA_TESTING_IP` environment variable
> ```

variable:



_Code quote:_
```Markdown
variable
```
___
*[`DEVELOPMENT.md` line 41 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5RQICev8-eMdoUbM:-N4C5RQICev8-eMdoUbN:bixbsys) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L41)):*
> ```Markdown
> $ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
> ```
> - turn on building the multi-threaded tests and run them
> ```

run them:



_Code quote:_
```Markdown
run them
```
___
*[`DEVELOPMENT.md` line 41 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5s-b46JWKSE6a9or:-N4C5s-b46JWKSE6a9os:b5mqqpd) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L41)):*
> ```Markdown
> $ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
> ```
> - turn on building the multi-threaded tests and run them
> ```

building the multi-threaded tests with valgrind support enabled



_Code quote:_
```Markdown
building the multi-threaded tests
```
___
*[`DEVELOPMENT.md` line 52 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5W2a5Su9cozOGc8U:-N4C5W2a5Su9cozOGc8V:b-fvdk4n) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L52)):*
> ```Markdown
> ### Run multi-threaded tests on RDMA HW:
> - configure RDMA HW
> - set the `RPMA_TESTING_IP` environment variable
> ```

variable:



_Code quote:_
```Markdown
variable
```
___
*[`DEVELOPMENT.md` line 56 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5Y5G2Al1OFUW_6dK:-N4C5Y5G2Al1OFUW_6dL:bixbsys) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L56)):*
> ```Markdown
> $ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
> ```
> - turn on building the multi-threaded tests and run them
> ```

run them:



_Code quote:_
```Markdown
run them
```
___
*[`DEVELOPMENT.md` line 56 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5zeJE8xv4fKexZMA:-N4C5zeJE8xv4fKexZMB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L56)):*
> ```Markdown
> $ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
> ```
> - turn on building the multi-threaded tests and run them
> ```

.



_Code quote:_
```Markdown
building the multi-threaded tests
```


<!-- Sent from Reviewable.io -->

2022-06-10 10:39 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[`DEVELOPMENT.md` line 26 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C4nm72wLlhW8MYu4L:-N4CAzd23Nxrz07BaSQ9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`$(nproc)` instead of `${nproc}` - it is not a variable but a command.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 36 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5BhrCBCnhfpofnHR:-N4CB3mFB30FNYkwB14v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
`tools/config_softroce.sh`
```

</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 37 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5OXb8xWvmSiKbZZL:-N4CB5Jy7D_lfjumvvdo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

variable:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 41 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5RQICev8-eMdoUbM:-N4CB7LV2kylRoMqbeGf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

run them:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 41 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5s-b46JWKSE6a9or:-N4CBEbo2NJs1Q59a7Rd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

building the multi-threaded tests with valgrind support enabled
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 45 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C4zoT4GV9q2HH-jvE:-N4CBHH249q8rm1GAb5b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 52 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5W2a5Su9cozOGc8U:-N4CBLZZE6dHccGSMaN_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

variable:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 56 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5Y5G2Al1OFUW_6dK:-N4CBS1M94TlkqNyEqkH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

run them:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 56 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C5zeJE8xv4fKexZMA:-N4CBSY70XNEWE51K0zB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 60 at r10](https://reviewable.io/reviews/pmem/rpma/1818#-N4C509s3KM13vr26Ql9:-N4CBVmF5zQx90VyUiey:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/78ebc5fed7d48a192a39bb91f76c4b841c8448c3/DEVELOPMENT.md#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 11:05 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`DEVELOPMENT.md` line 41 at r11](https://reviewable.io/reviews/pmem/rpma/1818#-N4CHSF81pLbP3FPtp5f:-N4CHSF81pLbP3FPtp5g:bwmpbn8) ([raw file](https://github.com/pmem/rpma/blob/ef9845323830fc5e8f96ac3fdd68f5e8bfff1c97/DEVELOPMENT.md#L41)):*
> ```Markdown
> $ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
> ```
> - turn on building building the multi-threaded tests with valgrind support enabled and run them:
> ```

only one building ;-)



_Code quote:_
```Markdown
building building
```
___
*[`DEVELOPMENT.md` line 56 at r11](https://reviewable.io/reviews/pmem/rpma/1818#-N4CHaSN0FUAEbjnHVBU:-N4CHaSN0FUAEbjnHVBV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ef9845323830fc5e8f96ac3fdd68f5e8bfff1c97/DEVELOPMENT.md#L56)):*
> ```Markdown
> $ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
> ```
> - turn on building building the multi-threaded tests with valgrind support enabled and run them:
> ```

.



_Code quote:_
```Markdown
building building
```


<!-- Sent from Reviewable.io -->

2022-06-10 11:07 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`DEVELOPMENT.md` line 41 at r11](https://reviewable.io/reviews/pmem/rpma/1818#-N4CHSF81pLbP3FPtp5f:-N4CHwTE6jzzl7og5JZt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ef9845323830fc5e8f96ac3fdd68f5e8bfff1c97/DEVELOPMENT.md#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

only one building ;-)
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 56 at r11](https://reviewable.io/reviews/pmem/rpma/1818#-N4CHaSN0FUAEbjnHVBU:-N4CHx_b81cjqpackssR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ef9845323830fc5e8f96ac3fdd68f5e8bfff1c97/DEVELOPMENT.md#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 11:40 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818#-:-N4CPeGt1n-YNGimiGjj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-13 06:50 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 19 at r12](https://reviewable.io/reviews/pmem/rpma/1818#-N4DOvXmDfaKcTkygoYb:-N4QoZomD2S3cbHX8UFE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a0d8e8982f23461c13930e78e9114da4837c80a/DEVELOPMENT.md#L19)):*
> ```Markdown
> The unit tests are implemented using the [cmocka](https://cmocka.org/) framework.
> 
> All unit tests are located in the `./tests/unit/` directory.
> ```

Done.
___
*[`DEVELOPMENT.md` line 21 at r12](https://reviewable.io/reviews/pmem/rpma/1818#-N4DPGD8DwYOzg4ity4A:-N4Qoj67EL3-BxginKUL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a0d8e8982f23461c13930e78e9114da4837c80a/DEVELOPMENT.md#L21)):*
> ```Markdown
> All unit tests are located in the `./tests/unit/` directory.
> 
> To run unit tests you need to issue the following commands:
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 07:53 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-06-13 09:12 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818#-:-N4RKZ7F5ur6UcCUV21N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-13 09:19 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1818)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-13 09:19 UTC, merged