common: documentation of building, installing and testing
pmem/rpma pull request #1825
Opened 2022-06-10 10:33 UTC by haichangsi

2022-06-10 11:47 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-06-10 12:00 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi)

___
*[`CONTRIBUTING.md` line 120 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CRoBr-zRuynyuJI-3:-N4CRoBr-zRuynyuJI-4:b-hx99h3) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/CONTRIBUTING.md#L120)):*
> ```Markdown
> ```
> ## Coverage
> Keep in mind that only PRs with 100% coverage can be merged and reviewed. Please check [DEVELOPMENT.md file](DEVELOPMENT.md) to see how to run all unit tests.
> ```

Please remove: " and reviewed"



_Code quote:_
```Markdown
 and reviewed
```
___
*[`DEVELOPMENT.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSLG27IXriIIRVspP:-N4CSLG34zzkBQDuDqvA:bc2fhiv) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L5)):*
> ```Markdown
> 
> Here is a list of the most interesting options
> provided out of the box by CMake.
> ```

In one line with `:` at the end.



_Code quote:_
```Markdown
Here is a list of the most interesting options
provided out of the box by CMake.
```
___
*[`DEVELOPMENT.md` line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CRxeE9UW-y3o9DfrB:-N4CRxeE9UW-y3o9DfrC:bgpt4t0) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L30)):*
> ```Markdown
> CMake options can be changed with `-D` option e.g.:
> 
> ```shell
> ```

```sh in all places, please
```




_Code quote:_
```Markdown
```shell
```
___
*[`DEVELOPMENT.md` line 36 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS5ee4K_rxpjsolbl:-N4CS5ee4K_rxpjsolbm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L36)):*
> ```Markdown
> You can browse and edit CMake options using `cmake-gui` or `ccmake` e.g.:
> 
> ```shell
> ```

.



_Code quote:_
```Markdown
```shell
```
___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4CS7K84ydiSBxn8ESf:bqmqhah) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
> ```Markdown
> 
> ```shell
> $ ccmake .
> ```

`ccmake ..`



_Code quote:_
```Markdown
ccmake .
```
___
*[`DEVELOPMENT.md` line 48 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTevW30Ar88IpJbYU:-N4CTev_DgyuzHUgo0ze:b-fc67mm) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L48)):*
> ```Markdown
> 
> The librpma library can be found in the `build/src` directory.
> After the compilation, the librpma library binaries can be found in the `build/src` directory.
> ```

1) Duplicated
2) It is not about testing - wrong place for this information.



_Code quote:_
```Markdown
The librpma library can be found in the `build/src` directory.
After the compilation, the librpma library binaries can be found in the `build/src` directory.
```
___
*[`DEVELOPMENT.md` line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTsZS0AJUYlbW-wYW:-N4CTsZS0AJUYlbW-wYX:bhiqryw) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L49)):*
> ```Markdown
> The librpma library can be found in the `build/src` directory.
> After the compilation, the librpma library binaries can be found in the `build/src` directory.
> Additionally, you can run the examples in `build/examples/*`.
> ```

It is not about testing - wrong place for this information.



_Code quote:_
```Markdown
Additionally, you can run the examples in `build/examples/*`.
```
___
*[`DEVELOPMENT.md` line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTuf-6J3phL2ESK_c:-N4CTuf-6J3phL2ESK_d:b-j4ezei) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L50)):*
> ```Markdown
> After the compilation, the librpma library binaries can be found in the `build/src` directory.
> Additionally, you can run the examples in `build/examples/*`.
> ## Run unit and multi-threaded tests on SoftRoCE
> ```

Add one empty line in between, please



_Code quote:_
```Markdown
Additionally, you can run the examples in `build/examples/*`.
## Run unit and multi-threaded tests on SoftRoCE
```
___
*[`INSTALL.md` line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS_no5NNHIBGhluLB:-N4CS_no5NNHIBGhluLC:b7hyoa4) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L77)):*
> ```Markdown
> CMAKE_INSTALL_PREFIX must be set to a destination were packages will be installed
> 
> Before installing it is neccessary to run all unit tests first. In order to do it you can issue this command.
> ```

It is necessary to run all unit tests before installation.



_Code quote:_
```Markdown
Before installing it is neccessary to run all unit tests first. 
```
___
*[`INSTALL.md` line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSjHC76q4xXaMLTw-:-N4CSjHC76q4xXaMLTw0:b-f21d9k) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L77)):*
> ```Markdown
> CMAKE_INSTALL_PREFIX must be set to a destination were packages will be installed
> 
> Before installing it is neccessary to run all unit tests first. In order to do it you can issue this command.
> ```

`the following command:`



_Code quote:_
```Markdown
this command.
```
___
*[`INSTALL.md` line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSnmWCjWm5Zua8MnQ:-N4CSnmWCjWm5Zua8MnR:b-7u21ps) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L78)):*
> ```Markdown
> 
> Before installing it is neccessary to run all unit tests first. In order to do it you can issue this command.
> ```
> ```

```sh
```




_Code quote:_
```Markdown
```
```
___
*[`INSTALL.md` line 81 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSrl0EUTi0UzSLGue:-N4CSrl0EUTi0UzSLGuf:b-ksjw1z) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L81)):*
> ```Markdown
> $ make test
> ```
> The `ctest` command can be used instead of `make test`..
> ```

One dot at the end.



_Code quote:_
```Markdown
make test`..
```
___
*[`INSTALL.md` line 92 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CT5NK40FCf-4PJimu:-N4CT5NL2QnBgukMEF_J:bm6ksim) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L92)):*
> ```Markdown
> 
> 
> ## Development
> ```

`## Testing` as it was before or change the links below.



_Code quote:_
```Markdown
## Development
```
___
*[`README.md` line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTHon9Z-Onc_1Yh2n:-N4CTHon9Z-Onc_1Yh2o:b-9vo2ic) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/README.md#L15)):*
> ```Markdown
> 
> If you want to install this library please check out
> [INSTALL.md file](INSTALL.md).
> ```

In one line, please.



_Code quote:_
```Markdown
If you want to install this library please check out
[INSTALL.md file](INSTALL.md).
```


<!-- Sent from Reviewable.io -->

2022-06-10 12:08 UTC, osalyk requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`DEVELOPMENT.md` line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CVLmw1LHihCCkPuIL:-N4CVLmw1LHihCCkPuIM:bx2ba79) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L22)):*
> ```Markdown
> | TESTS_USE_VALGRIND | Enable tests with valgrind | ON/OFF | ON |
> | TEST_DIR | Working directory for tests | *dir path* | ./build/test |
> | TEST_PYTHON_TOOLS | Enable testing Python tools | ON/OFF | ON |
> ```

Please check all options, for sure 'TESTS_RDMA_CONNECTION' is missing



_Code quote:_
```Markdown
| Name | Description | Values | Default |
| - | - | - | - |
| BUILD_DOC | Build the documentation | ON/OFF | ON |
| BUILD_EXAMPLES | Build the examples | ON/OFF | ON |
| BUILD_TESTS | Build the tests | ON/OFF | ON |
| CHECK_CSTYLE | Check code style of C sources | ON/OFF | OFF |
| CMAKE_BUILD_TYPE | Choose the type of build | None/Debug/Release/RelWithDebInfo | Debug |
| CMAKE_INSTALL_PREFIX | Install path prefix, prepended onto install directories | *dir path* | /usr/local |
| COVERAGE | Run coverage test | ON/OFF | OFF |
| DEVELOPER_MODE | Enable developer checks | ON/OFF | OFF |
| TESTS_LONG | Enable long running tests | ON/OFF | OFF |
| TESTS_USE_FAULT_INJECTION | Run tests with fault injection | ON/OFF | OFF |
| TESTS_USE_FORCED_PMEM | Run tests with PMEM_IS_PMEM_FORCE=1 | ON/OFF | OFF |
| TESTS_USE_VALGRIND | Enable tests with valgrind | ON/OFF | ON |
| TEST_DIR | Working directory for tests | *dir path* | ./build/test |
| TEST_PYTHON_TOOLS | Enable testing Python tools | ON/OFF | ON |
| TRACE_TESTS | More verbose test outputs | ON/OFF | OFF |
| USE_ASAN | Enable AddressSanitizer | ON/OFF | OFF |
| USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
```
___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4CV_ByDibuD7P9rENR:b-20xrjp) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`ccmake ..`
</blockquote></details>

is fine
___
*[`DEVELOPMENT.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CW3Xr1tzT2Ju28aVy:-N4CW3Xr1tzT2Ju28aVz:b-du1rhe) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L53)):*
> ```Markdown
> 
> One of the basic principles of delivering a new functionality to a library is to deliver it simultaneously with the unit tests to ensure that the new features behave correctly.
> You have to expect that code that degrades the test coverage will not pass the review process unless it is explicitly marked as a draft.
> ```

It seems to me that this is more fitting for part CONTRIBUTING.md



_Code quote:_
```Markdown
One of the basic principles of delivering a new functionality to a library is to deliver it simultaneously with the unit tests to ensure that the new features behave correctly.
You have to expect that code that degrades the test coverage will not pass the review process unless it is explicitly marked as a draft.
```


<!-- Sent from Reviewable.io -->

2022-06-10 12:14 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4CXAT-0u6dKJ9aueZw:b-dobk4m) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

is fine
</blockquote></details>

`ccmake` has to be run exactly like `cmake`. We run `cmake`  from the build subdir.


<!-- Sent from Reviewable.io -->

2022-06-10 12:16 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4CXYyjDy_4eIvQQBtc:b-addnmt) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`ccmake` has to be run exactly like `cmake`. We run `cmake`  from the build subdir.
</blockquote></details>

And what's more `cmake` has to be run first - before `ccmake`, so if we run `cmake ..`, we have to run also `ccmake ..`.


<!-- Sent from Reviewable.io -->

2022-06-10 12:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4CYXbu2dOV9Rep_fzO:b-sm14d0) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

And what's more `cmake` has to be run first - before `ccmake`, so if we run `cmake ..`, we have to run also `ccmake ..`.
</blockquote></details>

`ccmake <path-to-source>`
`ccmake <path-to-existing-build>`

`cmake .` also works


<!-- Sent from Reviewable.io -->

2022-06-10 12:31 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4Ca8Fr7btehIr7amLV:b-ox8r9) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it works, of course, but it creates many CMake cache files and dirs in the current directory, so it pollutes the main directory of the library. In many projects running CMake in the main directory is explicitly forbidden in CMake scripts. We do not have this, but encouraging users to run cmake in the main directory is a bad practice.  That's why we create the `build` subdirectory and we run all cmake and ccmake commands inside the `build` subdirectory.
</blockquote></details>

You convinced me, thanks for the explanation :+1: 


<!-- Sent from Reviewable.io -->

2022-06-10 12:54 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4CfZhX484PkaLKulMS:b-zf8nwl) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

You convinced me, thanks for the explanation :+1: 
</blockquote></details>

Ufff ... ;-)


<!-- Sent from Reviewable.io -->

2022-06-10 16:28 UTC, grom72 approved these changes
> Reviewed 1 of 4 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4DQxTS7QdcMkz3epur:b32v57) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ufff ... ;-)
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-06-13 07:54 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4R2UnmDFde5xlUuXcl:b9d0v4k) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

... and please rebase.


<!-- Sent from Reviewable.io -->

2022-06-13 09:13 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-13 09:13 UTC, grom72 approved these changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 16 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-13 09:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 17 unresolved discussions (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1825#-N4ROFD263OyH87_KQNk:-N4ROFD3AR97aeAm8mWS:b-ni3tmb) (no related file):*
Rebase please.

___


<!-- Sent from Reviewable.io -->

2022-06-13 10:00 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 17 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1825#-N4ROFD263OyH87_KQNk:-N4RUYNP0kjoPVUqa8Mr:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please.
</blockquote></details>

Done.

___
___
*[`CONTRIBUTING.md` line 120 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CRoBr-zRuynyuJI-3:-N4RNkl81AnzTxQaEL0v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/CONTRIBUTING.md#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please remove: " and reviewed"
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSLG27IXriIIRVspP:-N4RNwe5859jwIlZBhr5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In one line with `:` at the end.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CVLmw1LHihCCkPuIL:-N4RR8hM42DMZyEPvFVb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L22)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please check all options, for sure 'TESTS_RDMA_CONNECTION' is missing
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CRxeE9UW-y3o9DfrB:-N4RRrHLD7tqoObwaHnV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```sh in all places, please
```

</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 36 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS5ee4K_rxpjsolbl:-N4RRrkh5kpaJWAh4Eb6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 37 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS7K84ydiSBxn8ESe:-N4RUZP3ETVtWZm-ezLo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... and please rebase.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 48 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTevW30Ar88IpJbYU:-N4RSNDz3VTEcin6Xg26:b-wnbld7) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) Duplicated
2) It is not about testing - wrong place for this information.
</blockquote></details>

moved to building inside INSTALL.md
___
*[`DEVELOPMENT.md` line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTsZS0AJUYlbW-wYW:-N4RSRcG5uttsD8s-X72:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not about testing - wrong place for this information.
</blockquote></details>

.
___
*[`DEVELOPMENT.md` line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTuf-6J3phL2ESK_c:-N4RSMQp4qD6vOiZ5g-l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add one empty line in between, please
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CW3Xr1tzT2Ju28aVy:-N4RTpTr3Ecrf6_BztIc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It seems to me that this is more fitting for part CONTRIBUTING.md
</blockquote></details>

Done.
___
*[`INSTALL.md` line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CS_no5NNHIBGhluLB:-N4RU3Kt5yewAmEmIGkE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is necessary to run all unit tests before installation.
</blockquote></details>

Done.
___
*[`INSTALL.md` line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSjHC76q4xXaMLTw-:-N4RU6uoB8YynpzKesbB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the following command:`
</blockquote></details>

Done.
___
*[`INSTALL.md` line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSnmWCjWm5Zua8MnQ:-N4RUFeW9i7hVwcG08S1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```sh
```

</blockquote></details>

Done.
___
*[`INSTALL.md` line 81 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CSrl0EUTi0UzSLGue:-N4RUFEW7sWU2mmgiaCJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

One dot at the end.
</blockquote></details>

Done.
___
*[`INSTALL.md` line 92 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CT5NK40FCf-4PJimu:-N4RUQqJ9HI-QgFkHuNm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/INSTALL.md#L92)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`## Testing` as it was before or change the links below.
</blockquote></details>

Done.
___
*[`README.md` line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CTHon9Z-Onc_1Yh2n:-N4RUXMa7_YrrLZrZ_zC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/README.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In one line, please.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 10:04 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 3 of 7 files reviewed, 17 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1825#-N4ROFD263OyH87_KQNk:-N4RWQbv9YiLajOEddpV:b-8nlap4) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.

___


<!-- Sent from Reviewable.io -->

2022-06-13 10:06 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 0 of 7 files reviewed, 17 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1825#-N4ROFD263OyH87_KQNk:-N4RWk345xFcbwRGDnFi:b701wh7) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

I know, my fault, done now 

___


<!-- Sent from Reviewable.io -->

2022-06-13 10:07 UTC, ldorau reviewed
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 3 of 7 files reviewed, 16 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-06-13 10:34 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 4 of 7 files reviewed, 13 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`INSTALL.md` line 60 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4Rbjen1GQqbZq3Pxjp:-N4Rbjen1GQqbZq3Pxjq:b-2b390f) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L60)):*
> ```Markdown
> Additionally, you can run the examples in `build/examples/*`.
> 
> ```shell
> ```

please fix also this one



_Code quote:_
```Markdown
```shell
```


<!-- Sent from Reviewable.io -->

2022-06-13 11:05 UTC, grom72 requested changes
> Reviewed 3 of 4 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4RigABB51B44xrLkCY:bvn9sa7) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
> ```Markdown
> ## CMake standard options
> 
> Here is a list of the most interesting options provided out of the box by CMake:
> ```

Do we have any place where all options are described?



_Code quote:_
```Markdown
the most interesting options
```


<!-- Sent from Reviewable.io -->

2022-06-13 11:12 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 19 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 2 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RizS8Dvci8uttQ5FB:-N4RizS8Dvci8uttQ5FC:b-xckb2w) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L2)):*
> ```Markdown
> # DEVELOPMENT ENVIRONMENT SETTINGS
> ## CMake standard options
> ```

Add one empty line in between



_Code quote:_
```Markdown
# DEVELOPMENT ENVIRONMENT SETTINGS
## CMake standard options
```
___
*[`DEVELOPMENT.md` line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4Riifu7KsGuVTuw8HS:-N4Riifu7KsGuVTuw8HT:b-xckb2w) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L30)):*
> ```Markdown
> | USE_ASAN | Enable AddressSanitizer | ON/OFF | OFF |
> | USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
> ## Configuring CMake options
> ```

Add one empty line in between



_Code quote:_
```Markdown
| USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
## Configuring CMake options
```
___
*[`INSTALL.md` line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjmwiC9pqXuBeuqPq:-N4RjmwiC9pqXuBeuqPr:b8uxktz) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L54)):*
> ```Markdown
> First, you have to create a `build` directory.
> From there you have to prepare the compilation using CMake.
> The final build step is just a `make` command.
> ```

```
... command:

```sh
$ mkdir build
$ cd build
$ cmake ..
$ make -j
\```

```



_Code quote:_
```Markdown
command.
```
___
*[`INSTALL.md` line 57 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjEEW1xN_c4eysFag:-N4RjEEW1xN_c4eysFah:b-czyz7f) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L57)):*
> ```Markdown
> 
> The librpma library can be found in the `build/src` directory.
> After the compilation, the librpma library binaries can be found in the `build/src` directory.
> ```

Duplicated, it is enough:
```
When the librpma library has been successfully built, the binaries of the library can be found in the `build/src` directory.
```



_Code quote:_
```Markdown
The librpma library can be found in the `build/src` directory.
After the compilation, the librpma library binaries can be found in the `build/src` directory.
```
___
*[`INSTALL.md` line 60 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjvmC82EeekkAPRwm:-N4RjvmC82EeekkAPRwn:b-60llug) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L60)):*
> ```Markdown
> Additionally, you can run the examples in `build/examples/*`.
> 
> ```shell
> ```

Please move it above.



_Code quote:_
```Markdown
```shell
$ mkdir build && cd build
$ cmake ..
$ make -j
```
```
___
*[`INSTALL.md` line 61 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjMrYCM0MDW1ms06W:-N4RjMrYCM0MDW1ms06X:b-o0myfu) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L61)):*
> ```Markdown
> 
> ```shell
> $ mkdir build && cd build
> ```

```sh
$ mkdir build
$ cd build
```



_Code quote:_
```Markdown
$ mkdir build && cd build
```


<!-- Sent from Reviewable.io -->

2022-06-13 11:13 UTC, osalyk requested changes
> Reviewed 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`DEVELOPMENT.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CW3Xr1tzT2Ju28aVy:-N4RjiFV60yT1-0ZB1e1:b22j4jr) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove here
___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4Rk3JmDRvmjLAGyhNF:b-vovbr7) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we have any place where all options are described?
</blockquote></details>

CMakeLists.txt 
In my opinion, this table is more readable.


<!-- Sent from Reviewable.io -->

2022-06-13 11:28 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`DEVELOPMENT.md` line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4Rn0EG-MlgH_jZN86z:-N4Rn0EG-MlgH_jZN87-:b-kyk7la) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L30)):*
> ```Markdown
> | USE_ASAN | Enable AddressSanitizer | ON/OFF | OFF |
> | USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
> ## Configuring CMake options
> ```

```
## Configuring CMake options

CMake creates many cache files and subdirectories in the directory where it is run, so it is recommended to run all CMake-related commands (like `cmake` and `ccmake`)  in a separate newly created subdirectory usually called `build`:

```sh
$ mkdir build
$ cd build
$ cmake ..
\```

CMake options can be changed with `-D` option e.g.:
...

```



_Code quote:_
```Markdown
## Configuring CMake options
```


<!-- Sent from Reviewable.io -->

2022-06-13 11:42 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1825#-N4CW3Xr1tzT2Ju28aVy:-N4RqY-sDNt_8KUGwluk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65676b6d3f4679d3ad8018795cace8c8100a17fa/DEVELOPMENT.md#L53)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Remove here
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 2 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RizS8Dvci8uttQ5FB:-N4RqEXy0c8k3d-UROe_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add one empty line in between
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4Riifu7KsGuVTuw8HS:-N4RqKJ0BntzwcYaDhFk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add one empty line in between
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 30 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4Rn0EG-MlgH_jZN86z:-N4RqTn2-DCePCEkKsrI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
## Configuring CMake options

CMake creates many cache files and subdirectories in the directory where it is run, so it is recommended to run all CMake-related commands (like `cmake` and `ccmake`)  in a separate newly created subdirectory usually called `build`:

```sh
$ mkdir build
$ cd build
$ cmake ..
\```

CMake options can be changed with `-D` option e.g.:
...

```

</blockquote></details>

Done.
___
*[`INSTALL.md` line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjmwiC9pqXuBeuqPq:-N4RqjdW8C-4xX0LTBF6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
... command:

```sh
$ mkdir build
$ cd build
$ cmake ..
$ make -j
\```

```
</blockquote></details>

Done.
___
*[`INSTALL.md` line 57 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjEEW1xN_c4eysFag:-N4Rqul08gyg8c9dqR0l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Duplicated, it is enough:
```
When the librpma library has been successfully built, the binaries of the library can be found in the `build/src` directory.
```

</blockquote></details>

Done.
___
*[`INSTALL.md` line 60 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4Rbjen1GQqbZq3Pxjp:-N4Rqwri3WxqD7L_cxVI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

please fix also this one
</blockquote></details>

Done.
___
*[`INSTALL.md` line 60 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjvmC82EeekkAPRwm:-N4Rr-Ep00qKtgv4Mnou:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move it above.
</blockquote></details>

Done.
___
*[`INSTALL.md` line 61 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RjMrYCM0MDW1ms06W:-N4Rr1pv-3c7YgU-bXx2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```sh
$ mkdir build
$ cd build
```

</blockquote></details>

Done.
___
*[`INSTALL.md` line 85 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RmG-hD7ZadzY-iqNZ:-N4RrC5a5JG1c0uzBBsL:bco6tqr) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L85)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have focused on the grammar and missed the context...

This is not true, please remove it (running all unit tests is not needed before the installation).
</blockquote></details>

Maybe this is not the best word but if I understood @osalyk correctly it is highly recommended and should be mentioned here. Maybe not 'neccessary' but 'highly recommended'?


<!-- Sent from Reviewable.io -->

2022-06-13 12:19 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 5 of 7 files reviewed, 11 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`INSTALL.md` line 85 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RmG-hD7ZadzY-iqNZ:-N4S-2UHBK1mneUqB9lz:b-vxr7m4) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L85)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Maybe this is not the best word but if I understood @osalyk correctly it is highly recommended and should be mentioned here. Maybe not 'neccessary' but 'highly recommended'?
</blockquote></details>

I agree with @haichangsi and @osalyk. It is not needed but this is the last chance to check (before installation) if the library has been complied properly.


<!-- Sent from Reviewable.io -->

2022-06-13 12:20 UTC, grom72 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 5 of 7 files reviewed, 11 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4S-Y-x4gpjxdpnYo3y:bz5hhj9) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

CMakeLists.txt 
In my opinion, this table is more readable.
</blockquote></details>

How to get the list of all options in an easy way?


<!-- Sent from Reviewable.io -->

2022-06-13 12:27 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4S0xol75bupsqI_4tH:b-f2hs6r) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

How to get the list of all options in an easy way?
</blockquote></details>

`cmake .. -LH`
___
*[`DEVELOPMENT.md` line 40 at r6](https://reviewable.io/reviews/pmem/rpma/1825#-N4Rzfw27R1Pw-KuE7iV:-N4Rzfw27R1Pw-KuE7iW:b-gblb6) ([raw file](https://github.com/pmem/rpma/blob/71a23fd3a64cea962864d70a592991b051fb1d3d/DEVELOPMENT.md#L40)):*
> ```Markdown
> $ cd build
> $ cmake ..
> \```
> ```

No backslash here. I had to add that, so that Reviewable did not covert 3 backticks into MD.



_Code quote:_
```Markdown
\```
```
___
*[`INSTALL.md` line 85 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RmG-hD7ZadzY-iqNZ:-N4S039M1RTAnG7uW7O3:ba4zx5h) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/INSTALL.md#L85)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I agree with @haichangsi and @osalyk. It is not needed but this is the last chance to check (before installation) if the library has been complied properly.
</blockquote></details>

OK, so `It is recommended to run ...`



_Code quote:_
```Markdown
It is neccessary to run 
```
___
*[`INSTALL.md` line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1825#-N4S-ak72eqO30RbDVv4:-N4S-ak72eqO30RbDVv5:b4uo3yh) ([raw file](https://github.com/pmem/rpma/blob/71a23fd3a64cea962864d70a592991b051fb1d3d/INSTALL.md#L54)):*
> ```Markdown
> First, you have to create a `build` directory.
> From there you have to prepare the compilation using CMake.
> The final build step is just a `make` command.
> ```

the `make` command:



_Code quote:_
```Markdown
a `make` command.
```


<!-- Sent from Reviewable.io -->

2022-06-13 13:00 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4S8DD_DAvBtBi2Y_cK:br02050) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`cmake .. -LH`
</blockquote></details>

I agree with Oksana. It is very readable. Should I add "cmake .. -LH" option also?
___
*[`DEVELOPMENT.md` line 40 at r6](https://reviewable.io/reviews/pmem/rpma/1825#-N4Rzfw27R1Pw-KuE7iV:-N4S83t66hyWPOJIRQCU:b-45md5l) ([raw file](https://github.com/pmem/rpma/blob/71a23fd3a64cea962864d70a592991b051fb1d3d/DEVELOPMENT.md#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No backslash here. I had to add that, so that Reviewable did not covert 3 backticks into MD.
</blockquote></details>

I did ctrl+z and my deletion has been cancelled. Done.
___
*[`INSTALL.md` line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1825#-N4S-ak72eqO30RbDVv4:-N4S8Tkk1iBZjSTj78ol:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/71a23fd3a64cea962864d70a592991b051fb1d3d/INSTALL.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the `make` command:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 13:03 UTC, grom72 requested changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4S8Bjq6joo4bUimNDv:b-ebosna) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I agree with Oksana. It is very readable. Should I add "cmake .. -LH" option also?
</blockquote></details>

I mean all usable options ;). The ``cmake .. -LH`` shows all including many system options. I do not think we need ``cmake .. -LH``


<!-- Sent from Reviewable.io -->

2022-06-13 13:21 UTC, osalyk approved these changes
> Reviewed 1 of 4 files at r4, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-06-13 13:34 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`INSTALL.md` line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1825#-N4S-ak72eqO30RbDVv4:-N4SGLiY0kcAOliWCnTq:bfn8865) ([raw file](https://github.com/pmem/rpma/blob/71a23fd3a64cea962864d70a592991b051fb1d3d/INSTALL.md#L54)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not all yet, please replace `.` with `:`.



_Code quote:_
```Markdown
command.
```


<!-- Sent from Reviewable.io -->

2022-06-13 14:32 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 4 at r5](https://reviewable.io/reviews/pmem/rpma/1825#-N4RigABB51B44xrLkCX:-N4STPH86WsC-Ly_O3im:bcce9cr) ([raw file](https://github.com/pmem/rpma/blob/733c1b76817964f9fa71e9a5e00694f0e1daf700/DEVELOPMENT.md#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I mean all usable options ;). The ``cmake .. -LH`` shows all including many system options. I do not think we need ``cmake .. -LH``
</blockquote></details>

Done then, thanks ;)
___
*[`INSTALL.md` line 54 at r6](https://reviewable.io/reviews/pmem/rpma/1825#-N4S-ak72eqO30RbDVv4:-N4STW7X7F6U4II49fF1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/71a23fd3a64cea962864d70a592991b051fb1d3d/INSTALL.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not all yet, please replace `.` with `:`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 14:34 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-06-13 14:34 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825#-:-N4SUGW014GdksXWXBOR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-06-13 15:23 UTC, grom72 requested changes
> Reviewed 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`DEVELOPMENT.md` line 19 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4S_wzU02hQijYNPeJa:-N4S_wzU02hQijYNPeJb:b-jou0pz) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L19)):*
> ```Markdown
> | DEBUG_FAULT_INJECTION | Enable fault injection | ON/OFF | OFF |
> | DEVELOPER_MODE | Enable developer checks | ON/OFF | OFF |
> | TESTS_LONG | Enable long running tests | ON/OFF | OFF |
> ```

do we use it?



_Code quote:_
```Markdown
TESTS_LONG
```
___
*[`DEVELOPMENT.md` line 21 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sc76X4wFF6lR0_hor:-N4Sc76X4wFF6lR0_hos:bdms16t) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L21)):*
> ```Markdown
> | TESTS_LONG | Enable long running tests | ON/OFF | OFF |
> | TESTS_NO_FORTIFY_SOURCE | Enable tests that do not pass when -D_FORTIFY_SOURCE=2 flag set | ON/OFF | OFF |
> | TESTS_USE_FAULT_INJECTION | Run tests with fault injection | ON/OFF | OFF |
> ```

where is it used?



_Code quote:_
```Markdown
TESTS_USE_FAULT_INJECTION
```
___
*[`DEVELOPMENT.md` line 23 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sa3orAXTJ10NdP_fW:-N4Sa3orAXTJ10NdP_fX:undefined) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L23)):*
> ```Markdown
> | TESTS_USE_FAULT_INJECTION | Run tests with fault injection | ON/OFF | OFF |
> | TESTS_USE_FORCED_PMEM | Run tests with PMEM_IS_PMEM_FORCE=1 | ON/OFF | OFF |
> | TESTS_USE_VALGRIND | Enable tests with valgrind | ON/OFF | ON |
> ```





_Suggestion:_
```Markdown
| TESTS_USE_VALGRIND | Enable tests with Valgrind | ON/OFF | OFF |
```
___
*[`DEVELOPMENT.md` line 27 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sa8wpDyoak-GASiV4:-N4Sa8wpDyoak-GASiV5:b-61xycg) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L27)):*
> ```Markdown
> | TEST_RDMA_CONNECTION | Enable tests that require a configured RDMA-capable network interface | ON/OFF | OFF |
> | TEST_DIR | Working directory for tests | *dir path* | ./build/test |
> | TEST_PYTHON_TOOLS | Enable testing Python tools | ON/OFF | ON |
> ```

Do we need this in the default build?



_Suggestion:_
```Markdown
| TEST_PYTHON_TOOLS | Enable testing Python tools | ON/OFF | OFF |
```
___
*[`DEVELOPMENT.md` line 31 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4SaRmj2gbNvpTd72rj:-N4SaRmj2gbNvpTd72rk:b-cwy5er) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L31)):*
> ```Markdown
> | USE_ASAN | Enable AddressSanitizer | ON/OFF | OFF |
> | USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
> ```

Use ``cmake -LAH ..`` to see al available options.


<!-- Sent from Reviewable.io -->

2022-06-13 21:21 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-14 05:54 UTC, osalyk reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-14 08:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`DEVELOPMENT.md` line 21 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sc76X4wFF6lR0_hor:-N4WHSv1B740FV9Eok-E:bo5zzh9) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

where is it used?
</blockquote></details>

Nowhere, unused, should be removed.


<!-- Sent from Reviewable.io -->

2022-06-14 08:47 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 19 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4S_wzU02hQijYNPeJa:-N4WNikw61Qewf2ijIV_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we use it?
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 21 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sc76X4wFF6lR0_hor:-N4WNgEoC_qlWeLIxnn1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Nowhere, unused, should be removed.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 23 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sa3orAXTJ10NdP_fW:-N4WNnmQB3tsNWkdrPPr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L23)):*
> ```Markdown
> | TESTS_USE_FAULT_INJECTION | Run tests with fault injection | ON/OFF | OFF |
> | TESTS_USE_FORCED_PMEM | Run tests with PMEM_IS_PMEM_FORCE=1 | ON/OFF | OFF |
> | TESTS_USE_VALGRIND | Enable tests with valgrind | ON/OFF | ON |
> ```

Done.
___
*[`DEVELOPMENT.md` line 27 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4Sa8wpDyoak-GASiV4:-N4WNsM--KAhDFR_6ENT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this in the default build?
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 31 at r8](https://reviewable.io/reviews/pmem/rpma/1825#-N4SaRmj2gbNvpTd72rj:-N4WO9xU-1vwIVMzttZa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ebada767eb7ffcb3462ccf01f7fd45250c485dec/DEVELOPMENT.md#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Use ``cmake -LAH ..`` to see al available options.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 08:59 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-06-14 09:00 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825#-:-N4WRGsg0g685njYTD85:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-14 09:00 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-14 09:00 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1825)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-14 09:00 UTC, merged