tools: Multi-fio.md
pmem/rpma pull request #1879
Opened 2022-06-27 09:37 UTC by Patryk717

2022-06-28 08:15 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-06-29 08:43 UTC, ldorau reviewed
Preview: https://github.com/Patryk717/rpma/blob/Multi-fio/tools/perf/jak_sie_ma_nazwac_ten_plik.md

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879#-:-N5icAvh7Gn60Pq50BSF:bq82ofq)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-06-29 08:46 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/jak_sie_ma_nazwac_ten_plik.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1879#-N5ibSt57g2E72ExEsEp:-N5ibSt57g2E72ExEsEq:bm6l9jj) ([raw file](https://github.com/pmem/rpma/blob/28a634499b56ed5d002274b4806f96cc3d418e65/tools/perf/jak_sie_ma_nazwac_ten_plik.md#L5)):*
> ```Markdown
> When we want to run the benchmark in Multi Coneection, we have to make changes to the cod:
> - file fio.py
> - librpma_aof_hw-client.fio
> ```

do we need aof?


<!-- Sent from Reviewable.io -->

2022-06-29 10:38 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/jak_sie_ma_nazwac_ten_plik.md` line 1 at r2](https://reviewable.io/reviews/pmem/rpma/1879#-N5idzg9BuuR-TKustBn:-N5idzgA6h9DcPUpaUQV:b-exagge) ([raw file](https://github.com/pmem/rpma/blob/28a634499b56ed5d002274b4806f96cc3d418e65/tools/perf/jak_sie_ma_nazwac_ten_plik.md#L1)):*
> ```Markdown
> # jak_sie_ma_nazwac_ten_plik
> ```

multiply_connection_benchmark



_Code quote:_
```Markdown
jak_sie_ma_nazwac_ten_plik
```
___
*[`tools/perf/jak_sie_ma_nazwac_ten_plik.md` line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1879#-N5id8Rg-OtOV8Ga38XY:-N5id8Rg-OtOV8Ga38XZ:undefined) ([raw file](https://github.com/pmem/rpma/blob/28a634499b56ed5d002274b4806f96cc3d418e65/tools/perf/jak_sie_ma_nazwac_ten_plik.md#L16)):*
> ```Markdown
> 
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client and remove 'serverip' from global, 'serverip' add to server,
> ```





_Suggestion:_
```Markdown
client section ``[client]``
```


<!-- Sent from Reviewable.io -->

2022-06-29 10:45 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-06-29 11:07 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N5j84Z90iPQQW8ejaV3:-N5j84ZA8WfxFstwE_9P:bxm9f1s) (no related file):*
Please fix formatting so that https://github.com/Patryk717/rpma/blob/Multi-fio/tools/perf/jak_sie_ma_nazwac_ten_plik.md looks good.

___


<!-- Sent from Reviewable.io -->

2022-06-29 14:08 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @haichangsi and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-06-29 14:12 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @Patryk717)

___
*[`tools/perf/jak_sie_ma_nazwac_ten_plik.md` line 1 at r2](https://reviewable.io/reviews/pmem/rpma/1879#-N5idzg9BuuR-TKustBn:-N5jSvyz5caJUSbs_qsv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28a634499b56ed5d002274b4806f96cc3d418e65/tools/perf/jak_sie_ma_nazwac_ten_plik.md#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

multiply_connection_benchmark
</blockquote></details>

Done.
___
*[`tools/perf/jak_sie_ma_nazwac_ten_plik.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1879#-N5ibSt57g2E72ExEsEp:-N5jn1XQ5tj_N2jJad_A:bkwvyc4) ([raw file](https://github.com/pmem/rpma/blob/28a634499b56ed5d002274b4806f96cc3d418e65/tools/perf/jak_sie_ma_nazwac_ten_plik.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we need aof?
</blockquote></details>

currently not



_Code quote:_
```Markdown
- librpma_aof_hw-client.fio
- librpma_aof_hw-server.fio
- librpma_aof_sw-client.fio
- librpma_aof_sw-server.fio
```
___
*[`tools/perf/jak_sie_ma_nazwac_ten_plik.md` line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1879#-N5id8Rg-OtOV8Ga38XY:-N5jTuWuERl7xf8VAzCe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28a634499b56ed5d002274b4806f96cc3d418e65/tools/perf/jak_sie_ma_nazwac_ten_plik.md#L16)):*
> ```Markdown
> 
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client and remove 'serverip' from global, 'serverip' add to server,
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-06-30 05:33 UTC, ldorau requested changes
Preview: https://github.com/Patryk717/rpma/blob/Multi-fio/tools/perf/multiply_connection_benchmark.md

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879#-:-N5n5LJjDCuqJqUNjatV:b4fbhpc)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N5j84Z90iPQQW8ejaV3:-N5n5Ic46meWhyMXMjLN:b8y0a1s) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

please use git rename instead of adding a new file
</blockquote></details>

The same for: https://github.com/Patryk717/rpma/blob/Multi-fio/tools/perf/multiply_connection_benchmark.md

___


<!-- Sent from Reviewable.io -->

2022-07-01 11:43 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @grom72 and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N5tZD5j-PAangNcbuxM:-N5tZD5j-PAangNcbuxN:bjzuxt8) (no related file):*
Maybe it could be a better option to describe it more like in steps: 'Then, After' etc. if it matters because now it is more like "we add, we add, we add".

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tQCdR6VSrrl3HDciM:-N5tQCdR6VSrrl3HDciN:bfzawji) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L17)):*
> ```Markdown
> 
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client section ``[client]`` and remove 'serverip' from global, 'serverip' add to server,
> ```

For every '*client.fio' file from the '/rpma/tools/perf/fio_jobs' folder we add 2 client sections [client], remove 'serverip' variable from [global] section and add 'serverip' variable 
 to [server] section.
___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tRrVP2dgfleJ3OO-X:-N5tRrVQ4_IQhGeuIcu3:badlint) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L18)):*
> ```Markdown
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client section ``[client]`` and remove 'serverip' from global, 'serverip' add to server,
> Which 'global' we remote 'server ip' and we add it in  'client' nr 1 and 2
> ```

I am not sure what do you want to say here. Maybe 'In [global] section we use remote 'serverip'. We have to add it in client 1 and client 2'?
___
*[`tools/perf/multiply_connection_benchmark.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tSb2M83fWWhoaoT2L:-N5tSb2M83fWWhoaoT2M:b58ut9o) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L20)):*
> ```Markdown
> Which 'global' we remote 'server ip' and we add it in  'client' nr 1 and 2
> 
> Examplary file librpma_aof_hw-client.fio
> ```

Exemplary
___
*[`tools/perf/multiply_connection_benchmark.md` line 31 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tSuwTEqcdsmZfQsky:-N5tSuwTEqcdsmZfQskz:bmtioaz) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L31)):*
> ```Markdown
> $ percentile_list=99.0:99.9:99.99:99.999
> 
> $ # The client will get a remote memory region description after establishing
> ```

descriptor?
___
*[`tools/perf/multiply_connection_benchmark.md` line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tT0yj5yKJeJoXrDVM:-N5tT0yj5yKJeJoXrDVN:b-srv84d) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L61)):*
> ```Markdown
> '''
> 
> For every file  '*server.fio' from the folder 'rpma/tools/perf/fio_jobs' we add 2 server and remove 'serverip' from global, 'serverip' add to server, we need add 'filename2'
> ```

For every '*server.fio' file from the 'rpma/tools/perf/fio_jobs' folder we add 2 server sections [server], remove 'serverip' from [global] section and add 'serverip' to [server] section.  We also need to add 'filename2'



_Code quote:_
```Markdown
For every file  '*server.fio' from the folder 'rpma/tools/perf/fio_jobs' we add 2 server and remove 'serverip' from global, 'serverip' add to server, we need add 'filename2'
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 62 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tTQJ3EzJabRpSQNVE:-N5tTQJ3EzJabRpSQNVF:bfcbp2m) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L62)):*
> ```Markdown
> 
> For every file  '*server.fio' from the folder 'rpma/tools/perf/fio_jobs' we add 2 server and remove 'serverip' from global, 'serverip' add to server, we need add 'filename2'
> Example file librpma_aof_hw-server.fio
> ```

Example file or Exemplery file, I would choose one
___
*[`tools/perf/multiply_connection_benchmark.md` line 68 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tThly8xobJ40_68Yu:-N5tThly8xobJ40_68Yv:b-wlr2aa) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L68)):*
> ```Markdown
> $ ioengine=librpma_aof_server
> $ create_serialize=0 # (required) forces specific initiation sequence
> $ kb_base=1000 # turn on the straight units handling (non-compatibility mode)
> ```

turns on
___
*[`tools/perf/multiply_connection_benchmark.md` line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tTsSbE7zxB5uscLCs:-N5tTsSbE7zxB5uscLCt:b-niwwbd) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L73)):*
> ```Markdown
> 
> $ # The server side spawns one thread for each expected connection from
> $ # the client-side, opens and registers the range dedicated for this thread
> ```

client side
___
*[`tools/perf/multiply_connection_benchmark.md` line 77 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tU4UU31p-gGjdNmwl:-N5tU4UU31p-gGjdNmwm:b-1kaoiu) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L77)):*
> ```Markdown
> $ # Each of the server threads accepts a connection on the dedicated port
> $ # (different for each and every working thread), accepts and executes flush
> $ # requests, and sends back a flush response for each of the requests.
> ```

no coma
___
*[`tools/perf/multiply_connection_benchmark.md` line 101 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tUzqUBQ9QsXQQvCbh:-N5tUzqUBQ9QsXQQvCbi:b-vuhw4x) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L101)):*
> ```Markdown
> '''
> 
> In the file 'fio.py' we add to condition if - 'filename2' , which we added earlier
> ```

In the 'fio.py' file we append env of 'filename2' variable in the if condition.
___
*[`tools/perf/multiply_connection_benchmark.md` line 117 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tXXfe3XgpKxRPrrwq:-N5tXXfe3XgpKxRPrrwr:b-d0e831) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L117)):*
> ```Markdown
> '''
> 
> At pmem we create 2 namespaces in 1 region
> ```

We create 2 namespaces in 1 region in PMem.
___
*[`tools/perf/multiply_connection_benchmark.md` line 119 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tXhel0UItM5IAmaEK:-N5tXhemEyMuzPAh6vhs:bqk0rus) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L119)):*
> ```Markdown
> At pmem we create 2 namespaces in 1 region
> 
> Finally we have to add in the file 'config.json' our /dev/daxa
> ```

Finally we have to add our '/dev/dax' in the 'config.json' file.


<!-- Sent from Reviewable.io -->

2022-07-04 11:46 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tSb2M83fWWhoaoT2L:-N6811Ft3AugfPBq7-1s:b-7at9k8) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L20)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Exemplary
</blockquote></details>

Let's focus on standard RPMA benchmarking files (no _aof_)



_Code quote:_
```Markdown
librpma_aof_client
```


<!-- Sent from Reviewable.io -->

2022-07-04 18:02 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N5kbt1LC_PjEJ9CQO5X:-N67oEzg2rzlbkNGgnWK:bnhfrzu) (no related file):*
>  https://github.com/Patryk717/rpma/blob/Multi-fio/tools/perf/multiply_connection_benchmark.md

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 6 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5kbYTl5_IY_aoZ3spe:-N67px0RD-oF2RpD-mla:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tQCdR6VSrrl3HDciM:-N67qrqX3c4pDWkddNoz:bd6rkzp) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L17)):*
> In [global] section we use remote 'serverip'. We have to add it in client 1 and client 2
___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tRrVP2dgfleJ3OO-X:-N69JQ4hCoTprK0rmTaU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I am not sure what do you want to say here. Maybe 'In [global] section we use remote 'serverip'. We have to add it in client 1 and client 2'?
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5kbbcd6bNJFgv0eIJt:-N69JTxzE9zicvCwhH3l:b-cvm7k) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do you change this particular file?
</blockquote></details>

i change file
___
*[`tools/perf/multiply_connection_benchmark.md` line 20 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tSb2M83fWWhoaoT2L:-N69L1EJ0RBO-_eJEXx-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's focus on standard RPMA benchmarking files (no _aof_)
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 31 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tSuwTEqcdsmZfQsky:-N69L25p6OJXncjzHh8S:b-cvm7k) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L31)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

descriptor?
</blockquote></details>

i change file
___
*[`tools/perf/multiply_connection_benchmark.md` line 68 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tThly8xobJ40_68Yu:-N69LQJq-2-CpkS23ZpU:b-cvm7k) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L68)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

turns on
</blockquote></details>

i change file
___
*[`tools/perf/multiply_connection_benchmark.md` line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tTsSbE7zxB5uscLCs:-N69LTQx6lbib0ACJXtM:b-cvm7k) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L73)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

client side
</blockquote></details>

i change file
___
*[`tools/perf/multiply_connection_benchmark.md` line 77 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tU4UU31p-gGjdNmwl:-N69LUhk1wUuvB7mHk0n:b-cvm7k) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L77)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

no coma
</blockquote></details>

i change file
___
*[`tools/perf/multiply_connection_benchmark.md` line 101 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tUzqUBQ9QsXQQvCbh:-N69LgrUBmWRI-SyKEDH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L101)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

In the 'fio.py' file we append env of 'filename2' variable in the if condition.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 117 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tXXfe3XgpKxRPrrwq:-N69LkgRCc0n_d7iUo7S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L117)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

We create 2 namespaces in 1 region in PMem.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 119 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tXhel0UItM5IAmaEK:-N69LllaDHpq1lgvR_Go:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L119)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Finally we have to add our '/dev/dax' in the 'config.json' file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-04 18:03 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 16 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tT0yj5yKJeJoXrDVM:-N69NKc_8EkwyhmHNNAV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L61)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

For every '*server.fio' file from the 'rpma/tools/perf/fio_jobs' folder we add 2 server sections [server], remove 'serverip' from [global] section and add 'serverip' to [server] section.  We also need to add 'filename2'
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 62 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tTQJ3EzJabRpSQNVE:-N69NLj76l2XUR97VOtz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L62)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Example file or Exemplery file, I would choose one
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 07:10 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N6CAkrq6dh_3-zoqTqq:-N6CAkrq6dh_3-zoqTqr:byxy0eh) (no related file):*
Do we need to modify ``fio.py`` if we assume that the user will provide the pmem path in ``server.fio`` file?

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 1 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C8Ijl0IAlr5h6IQgt:-N6C8Ijl0IAlr5h6IQgu:undefined) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L1)):*
> ```Markdown
> # multiply_connection_benchmark
> ```





_Suggestion:_
```Markdown
# RPMA benchmark in multilink configuration
The RPMA performance analysis runtime environment allows tests to be carried out in a configuration of multiple parallel connections between nodes
To execute such a benchmark, changes must be applied to the following configuration files:
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C9QA70VpIdavGnuZm:-N6C9QA70VpIdavGnuZn:undefined) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client section ``[client]`` and remove 'serverip' from global, 'serverip' add to server,
> ```





_Suggestion:_
```Markdown
'*client.fio' file 
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C9UoJ8hfc-bK-QDOn:-N6C9UoJ8hfc-bK-QDOo:undefined) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client section ``[client]`` and remove 'serverip' from global, 'serverip' add to server,
> ```





_Suggestion:_
```Markdown
we add 2nd client
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C9vDKE9vJX4LNgB4f:-N6C9vDKE9vJX4LNgB4g:b1zbmn9) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L16)):*
> ```Markdown
> Examplary file librpma_apm-client.fio
> 
> '''sh
> ```

Different apostrophe 



_Suggestion:_
```Markdown
```sh
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 54 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6CA3XX6MciTmHyIn13:-N6CA3XX6MciTmHyIn14:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L54)):*
> ```Markdown
> $ time_based
> $ runtime=${runtime}
> '''
> ```

.



_Suggestion:_
```Markdown
```
```


<!-- Sent from Reviewable.io -->

2022-07-05 07:15 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N6CAkrq6dh_3-zoqTqq:-N6CCQsIAnvqRgtZcwzE:b2nhswy) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need to modify ``fio.py`` if we assume that the user will provide the pmem path in ``server.fio`` file?
</blockquote></details>

Yes

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C9vDKE9vJX4LNgB4f:-N6CCbBS6obn7muiZc84:b-mv8ups) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Different apostrophe 
</blockquote></details>

Yes now i know :D
___
*[`tools/perf/multiply_connection_benchmark.md` line 54 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6CA3XX6MciTmHyIn13:-N6CCg3CArSa03cOaycf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 07:49 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 1 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C8Ijl0IAlr5h6IQgt:-N6CJnnv8Qxu9HH6-6Ob:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L1)):*
> ```Markdown
> # multiply_connection_benchmark
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C9QA70VpIdavGnuZm:-N6CJry07LWQw-eMlix9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client section ``[client]`` and remove 'serverip' from global, 'serverip' add to server,
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C9UoJ8hfc-bK-QDOn:-N6CKRAqEJ8ZyrrDVjM-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> For every file '*client.fio' from the folder '/rpma/tools/perf/fio_jobs' we add 2 client section ``[client]`` and remove 'serverip' from global, 'serverip' add to server,
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 08:10 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tRrVP2dgfleJ3OO-X:-N6CNTJ30OAzuhskBOJ1:bhslr7y) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It is still here
___
*[`tools/perf/multiply_connection_benchmark.md` line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tT0yj5yKJeJoXrDVM:-N6COARs6Q6LFAwpmIXZ:b-bajka) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L61)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet
___
*[`tools/perf/multiply_connection_benchmark.md` line 62 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tTQJ3EzJabRpSQNVE:-N6COCGp0_1OzGytLAL5:b-2ky9s7) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L62)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No no, I mean you used "Exemplary" before so you have to do it consistently. Choose "exemplary" fe
___
*[`tools/perf/multiply_connection_benchmark.md` line 101 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tUzqUBQ9QsXQQvCbh:-N6COs3UBPVk5ojHUNcD:b-ny3jln) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L101)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sorry, of THE 'filename2' ...
___
*[`tools/perf/multiply_connection_benchmark.md` line 117 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tXXfe3XgpKxRPrrwq:-N6CP0V0Bf1ULQfPxx5V:b-bajka) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L117)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r6](https://reviewable.io/reviews/pmem/rpma/1879#-N6CNCss36ItR5Tn-APu:-N6CNCss36ItR5Tn-APv:b-376j2f) ([raw file](https://github.com/pmem/rpma/blob/477999eb76a56a1fa647509fa46335706b8f5fb1/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> For every `*client.fio` file from the folder `/rpma/tools/perf/fio_jobs` we add 2nd client section `[client]` and remove `serveri` from global, `serverip` add to server,
> ```

... ,remove 'serverip' from global and add it to the server section


<!-- Sent from Reviewable.io -->

2022-07-05 10:18 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tRrVP2dgfleJ3OO-X:-N6Cq62z1_kyVTX5ErsZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

It is still here
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 61 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tT0yj5yKJeJoXrDVM:-N6Cqtpn5ir0wTQImBhm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L61)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

not yet
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 62 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tTQJ3EzJabRpSQNVE:-N6CrS4jELPSlKekUXdA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L62)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

No no, I mean you used "Exemplary" before so you have to do it consistently. Choose "exemplary" fe
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 101 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tUzqUBQ9QsXQQvCbh:-N6CrU2hBtEPjiMwUA_H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L101)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

sorry, of THE 'filename2' ...
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 117 at r3](https://reviewable.io/reviews/pmem/rpma/1879#-N5tXXfe3XgpKxRPrrwq:-N6Cqlyz6bhss4gQoNfr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9b93ccebf5a8c58750ee55218e2e501631bc871c/tools/perf/multiply_connection_benchmark.md#L117)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

not yet
</blockquote></details>

Done.



_Code quote:_
```Markdown
We have to reduce the number of threads·
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r6](https://reviewable.io/reviews/pmem/rpma/1879#-N6CNCss36ItR5Tn-APu:-N6Cqs9uE_1xsYRI11G7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/477999eb76a56a1fa647509fa46335706b8f5fb1/tools/perf/multiply_connection_benchmark.md#L11)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

... ,remove 'serverip' from global and add it to the server section
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 09:16 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N6DMsvsBk5p2hsoTapN:-N6HWAqL-n6F7y5ls7KP:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

In order to have better readability, we should have the original passage and the amended passage each time
</blockquote></details>

Done.

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 3 at r8](https://reviewable.io/reviews/pmem/rpma/1879#-N6DM2JcC_1RvvzQ9TRm:-N6HmrkJCrW9OwBBk1Xx:bvwbo01) ([raw file](https://github.com/pmem/rpma/blob/336e3649b52b2bdf79207108e2e5d9a6fa22b69c/tools/perf/multiply_connection_benchmark.md#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I can not follow what you want to say.
</blockquote></details>

this is file list to change if we want run benchamrk in multi connection
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r8](https://reviewable.io/reviews/pmem/rpma/1879#-N6DKxNa6p4W7oaWeQdf:-N6Hn-K49l4WmjkC2O6y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/336e3649b52b2bdf79207108e2e5d9a6fa22b69c/tools/perf/multiply_connection_benchmark.md#L26)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

You should explain why one of the addresses is hardcoded and the other is taken from a variable.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 07:03 UTC, grom72 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 1 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C8Ijl0IAlr5h6IQgt:-N6MOmYP0VVYoEtNi80j:b-g4jafb) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L1)):*
> The RPMA performance analysis runtime environment allows tests to be carried out in a configuration of multiple parallel connections between nodes
> To execute such a benchmark, changes must be applied to the following configuration files:
___
*[`tools/perf/multiply_connection_benchmark.md` line 3 at r11](https://reviewable.io/reviews/pmem/rpma/1879#-N6MOo80CqB3i32ySwmc:-N6MOo80CqB3i32ySwmd:b-hbxv3y) ([raw file](https://github.com/pmem/rpma/blob/a75159024deb762d2af1acd69359c10ff4db0bfe/tools/perf/multiply_connection_benchmark.md#L3)):*
> ```Markdown
> # RPMA benchmark in multilink configuration
> 
> When we want to run the benchmark in Multi Connection, we have to make changes to the cod:
> ```

what does ``cod`` mean?



_Code quote:_
```Markdown
 cod
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r11](https://reviewable.io/reviews/pmem/rpma/1879#-N6MP3C13Hai025g9Jm0:-N6MP3C13Hai025g9Jm1:undefined) ([raw file](https://github.com/pmem/rpma/blob/a75159024deb762d2af1acd69359c10ff4db0bfe/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> Our tool is not adapted to `double-benchmarking` that's why we have to add one `IP address` in the `config.json` (e.g. **192.168.101.4**) file which is used by `*client.fio` and `*server.fio`. 
> ```





_Suggestion:_
```Markdown
`IP address`  (e.g. **192.168.101.4**) in the `config.json`
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r11](https://reviewable.io/reviews/pmem/rpma/1879#-N6MPN1V80FiBBd9bDlz:-N6MPN1V80FiBBd9bDm-:undefined) ([raw file](https://github.com/pmem/rpma/blob/a75159024deb762d2af1acd69359c10ff4db0bfe/tools/perf/multiply_connection_benchmark.md#L14)):*
> ```Markdown
> Moreover we have to hardcode **`another`** (e.g. **192.168.102.4**) `IP address` in these files.
> 
> For every `*client.fio` file from the folder `/rpma/tools/perf/fio_jobs` we add 2nd client section `[client]` and remove `serverip` from `[global]`, `serverip` add it in `[client]` nr 1 and 2nd
> ```





_Suggestion:_
```Markdown
For every `*client.fio` file from the folder `/rpma/tools/perf/fio_jobs` `serverip` from `[global]` section shall be moved to the `[client]` section:
....
...
...
```
[global]
...
# serverip=${serverip} #comment out or removed from [global] section
...

[client]
...
serverip=${serverip} # ${serverip} is used only by the first client
...
```
Additionally, we have to create a new separate client section with a statically set server IP:
```
[client]
sync=${sync}
numjobs=${numjobs}
group_reporting=1
iodepth=${iodepth}
readwrite=${readwrite}
rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
blocksize=${blocksize}
ramp_time=${ramp_time}
time_based
runtime=${runtime}
serverip=192.168.102.4
```
```


<!-- Sent from Reviewable.io -->

2022-07-07 07:32 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-07 07:56 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 1 at r4](https://reviewable.io/reviews/pmem/rpma/1879#-N6C8Ijl0IAlr5h6IQgt:-N6MeJSkCkrQfAw4oZ28:b-8bb6nj) ([raw file](https://github.com/pmem/rpma/blob/70b925f8b7e7e875285e1b667a57bcaca3ad77bb/tools/perf/multiply_connection_benchmark.md#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> The RPMA performance analysis runtime environment allows tests to be carried out in a configuration of multiple parallel connections between nodes
> To execute such a benchmark, changes must be applied to the following configuration files:

</blockquote></details>

now done
___
*[`tools/perf/multiply_connection_benchmark.md` line 3 at r11](https://reviewable.io/reviews/pmem/rpma/1879#-N6MOo80CqB3i32ySwmc:-N6McxKZ2aDAD6P9EK5G:b-7qlas7) ([raw file](https://github.com/pmem/rpma/blob/a75159024deb762d2af1acd69359c10ff4db0bfe/tools/perf/multiply_connection_benchmark.md#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what does ``cod`` mean?
</blockquote></details>

file
___
*[`tools/perf/multiply_connection_benchmark.md` line 11 at r11](https://reviewable.io/reviews/pmem/rpma/1879#-N6MP3C13Hai025g9Jm0:-N6MdCOZ1aJXSbMfHzMw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a75159024deb762d2af1acd69359c10ff4db0bfe/tools/perf/multiply_connection_benchmark.md#L11)):*
> ```Markdown
> - config.json
> 
> Our tool is not adapted to `double-benchmarking` that's why we have to add one `IP address` in the `config.json` (e.g. **192.168.101.4**) file which is used by `*client.fio` and `*server.fio`. 
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r11](https://reviewable.io/reviews/pmem/rpma/1879#-N6MPN1V80FiBBd9bDlz:-N6MdrNB8Z1XJO6qJb7D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a75159024deb762d2af1acd69359c10ff4db0bfe/tools/perf/multiply_connection_benchmark.md#L14)):*
> ```Markdown
> Moreover we have to hardcode **`another`** (e.g. **192.168.102.4**) `IP address` in these files.
> 
> For every `*client.fio` file from the folder `/rpma/tools/perf/fio_jobs` we add 2nd client section `[client]` and remove `serverip` from `[global]`, `serverip` add it in `[client]` nr 1 and 2nd
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-07 11:09 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 82 at r12](https://reviewable.io/reviews/pmem/rpma/1879#-N6NEQKEDU3e9CrOXIKr:-N6NEQKEDU3e9CrOXIKs:b-bg3ium) ([raw file](https://github.com/pmem/rpma/blob/6e9dad97790b99471621c946b5a3b9c9281f191d/tools/perf/multiply_connection_benchmark.md#L82)):*
> ```Markdown
> ```sh
> "REMOTE_PMEM_PATH_2": "/dev/dax0.1"
> ```
> ```

missing an empty line at the end of the file



_Code quote:_
```Markdown
```
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 3 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NF7I_DP5urZIqP_8F:-N6NF7I_DP5urZIqP_8G:b-5zbm86) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L3)):*
> ```Markdown
> # RPMA benchmark in multilink configuration
> 
> The RPMA performance analysis runtime environment allows tests to be carried out in a configuration of multiple parallel connections between nodes
> ```

fullstop is missing



_Suggestion:_
```Markdown
nodes.
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 5 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NFC9M2fWCWiDxeLKM:-N6NFC9M2fWCWiDxeLKN:undefined) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L5)):*
> ```Markdown
> The RPMA performance analysis runtime environment allows tests to be carried out in a configuration of multiple parallel connections between nodes
> To execute such a benchmark, changes must be applied to the following configuration files:
> - file fio.py
> ```





_Suggestion:_
```Markdown
fio.py
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NFYZ43coStasx_Gsx:-N6NFYZ43coStasx_Gsy:b-9i9e93) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L12)):*
> ```Markdown
> - config.json
> 
> Our tool is not adapted to `double-benchmarking` that's why we have to add one `IP address` (e.g. **192.168.101.4**) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> ```

I do not understand what you want to say.



_Code quote:_
```Markdown
Our tool is not adapted to `double-benchmarking` that's why we have to add one `IP address` (e.g. **192.168.101.4**) in the `config.json` file which is used by `*client.fio` and `*server.fio`.·
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NFkVa64W89hTIYNxe:-N6NFkVa64W89hTIYNxf:b2eckna) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L26)):*
> ```Markdown
> ...
> ```
> Additionally, we have to create a new separate client section with a statically set server IP:
> ```

explicitly



_Code quote:_
```Markdown
statically
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 42 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NFqFh2cZ5OsOJLvNg:-N6NFqFh2cZ5OsOJLvNh:b-desk1t) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L42)):*
> ```Markdown
> ```
> 
> For every file  `*server.fio` from the folder `rpma/tools/perf/fio_jobs` we add 2 `[server]` and remove `serverip` from `[global]`, `serverip` add to `[server]`, we need add `filenam1` and `filename2`
> ```

Follow the text as it is written for client files.

A separate section about IP PMem configuration



_Code quote:_
```Markdown
For every file  `*server.fio` from the folder `rpma/tools/perf/fio_jobs` we add 2 `[server]` and remove `serverip` from `[global]`, `serverip` add to `[server]`, we need add `filenam1` and `filename2`
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 53 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NGBcu1D5u2LGB6k1g:-N6NGBcu1D5u2LGB6k1h:bb76j83) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L53)):*
> ```Markdown
> filename=${filename2}
> ```
> In the `/rpma/tools/perf/lib/benchmark/runner/fio.py` file we append env of `filename2` variable in the if condition.
> ```

We??



_Code quote:_
```Markdown
we append
```


<!-- Sent from Reviewable.io -->

2022-07-07 13:05 UTC, osalyk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 18 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 61 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Nk6io4IJnSgfFwO8T:-N6Nk6io4IJnSgfFwO8U:byz2nqe) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L61)):*
> ```Markdown
> size=100MiB
> serverip=192.168.102.4
> filename=${filename1}
> ```

filename2



_Suggestion:_
```Markdown
filename=${filename2}
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 82 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Nkgx4A0nlQtzUGxm7:-N6Nkgx4A0nlQtzUGxm8:b6urnen) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L82)):*
> ```Markdown
>             args.append('--filename={}'.format(pmem_path))
>         else:
>             args.append('--filename_format={}.\\$jobnum'.format(pmem_path))
> ```

You have to check if it will work for FSDAX or write that FSDAX is not supported


<!-- Sent from Reviewable.io -->

2022-07-07 13:36 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 86 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Nrywf2mxLMyFHeU-X:-N6Nrywf2mxLMyFHeU-Y:undefined) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L86)):*
> ```Markdown
> We recommend reducing the number of threads.
> ```sh
> __THREADS_VALUES = [1, 2, 4, 8, 12, 16, 32, 64]
> ```





_Suggestion:_
```Markdown
# __THREADS_VALUES = [1, 2, 4, 8, 12, 16, 32, 64]
```


<!-- Sent from Reviewable.io -->

2022-07-08 07:00 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 20 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 15 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Rb5Qp1LAdVs5ls0TG:-N6Rb5Qp1LAdVs5ls0TH:b-zfpfx8) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L15)):*
> ```Markdown
> Moreover we have to hardcode **`another`** (e.g. **192.168.102.4**) `IP address` in these files.
> 
> For every `*client.fio` file from the folder `/rpma/tools/perf/fio_jobs` `serverip` from `[global]` section shall be moved to the `[client]` section:
> ```

Information about the removal of the [cpuio] section is missing.


<!-- Sent from Reviewable.io -->

2022-07-08 10:07 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-11 10:34 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N5tZD5j-PAangNcbuxM:-N6goYqUBoEenbyDAExI:b-896fix) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Maybe it could be a better option to describe it more like in steps: 'Then, After' etc. if it matters because now it is more like "we add, we add, we add".
</blockquote></details>

Done.

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 15 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Rb5Qp1LAdVs5ls0TG:-N6gob9g7PZLz_6VWQs5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L15)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Information about the removal of the [cpuio] section is missing.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 61 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Nk6io4IJnSgfFwO8T:-N6gobnU1_l7BPIsU2fT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L61)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

filename2
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 82 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Nkgx4A0nlQtzUGxm7:-N6goVih6C9XA7SKQzhQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L82)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

You have to check if it will work for FSDAX or write that FSDAX is not supported
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 86 at r14](https://reviewable.io/reviews/pmem/rpma/1879#-N6Nrywf2mxLMyFHeU-X:-N6goWq58KZAJerP2R5X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b91aea73f64e54b245ff77ef5e5498eeca433f8/tools/perf/multiply_connection_benchmark.md#L86)):*
> ```Markdown
> We recommend reducing the number of threads.
> ```sh
> __THREADS_VALUES = [1, 2, 4, 8, 12, 16, 32, 64]
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 10:55 UTC, osalyk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 6 at r15](https://reviewable.io/reviews/pmem/rpma/1879#-N6gsCb467nt1PCC4RS1:-N6gsCb467nt1PCC4RS2:undefined) ([raw file](https://github.com/pmem/rpma/blob/8d7823ed89ce9bab0c7131dcb1b9c9fd1e65de85/tools/perf/multiply_connection_benchmark.md#L6)):*
> ```Markdown
> To execute such a benchmark, changes must be applied.
> 
> ## Secend adres ip
> ```





_Suggestion:_
```Markdown
Second ip address
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 56 at r15](https://reviewable.io/reviews/pmem/rpma/1879#-N6gsfpG9bEGz4kOhXyU:-N6gsfpG9bEGz4kOhXyV:undefined) ([raw file](https://github.com/pmem/rpma/blob/8d7823ed89ce9bab0c7131dcb1b9c9fd1e65de85/tools/perf/multiply_connection_benchmark.md#L56)):*
> ```Markdown
> serverip=192.168.102.4
> ```
> ## Secend persisten memory 
> ```





_Suggestion:_
```Markdown
Second filename
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 57 at r15](https://reviewable.io/reviews/pmem/rpma/1879#-N6gspkj3XiAnn4IKFNZ:-N6gspkj3XiAnn4IKFN_:undefined) ([raw file](https://github.com/pmem/rpma/blob/8d7823ed89ce9bab0c7131dcb1b9c9fd1e65de85/tools/perf/multiply_connection_benchmark.md#L57)):*
> ```Markdown
> ```
> ## Secend persisten memory 
> Fsdax is not supported at the moment.
> ```





_Suggestion:_
```Markdown
**Note**: file system DAX is not supported.
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 97 at r15](https://reviewable.io/reviews/pmem/rpma/1879#-N6gtWMP-1PVZcYUc9oi:-N6gtWMP-1PVZcYUc9oj:undefined) ([raw file](https://github.com/pmem/rpma/blob/8d7823ed89ce9bab0c7131dcb1b9c9fd1e65de85/tools/perf/multiply_connection_benchmark.md#L97)):*
> ```Markdown
> ```
> 
> ## Removed cpuio from the server
> ```





_Suggestion:_
```Markdown
Removed [cpuio] section from the server
```


<!-- Sent from Reviewable.io -->

2022-07-11 13:36 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 21 unresolved discussions (waiting on @haichangsi, @ldorau, @osalyk, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-11 17:32 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEVCz4QG95IrBTNdd:-N6iJD486RRQnuMuPNPj:b-yvundt) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

strange format
</blockquote></details>

to pay special attention
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEXGi0SM2SbVIwmZL:-N6iJEjKDty1sFKsUZMl:b1e8yj8) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why is it bold?
</blockquote></details>

to pay special attention this is other ip 


<!-- Sent from Reviewable.io -->

2022-07-12 06:48 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 21 unresolved discussions (waiting on @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEVCz4QG95IrBTNdd:-N6l2uBD9cHdoM1XFrK0:b-53c058) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

to pay special attention
</blockquote></details>

not needed IMHO
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEXGi0SM2SbVIwmZL:-N6l2rmwBpVGXpl711hn:bd539ox) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

to pay special attention this is other ip 
</blockquote></details>

other than what?


<!-- Sent from Reviewable.io -->

2022-07-12 06:48 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 21 unresolved discussions (waiting on @haichangsi, @ldorau, @osalyk, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-12 07:31 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEVCz4QG95IrBTNdd:-N6lHiCd-qc0e-b1GDr6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

not needed IMHO
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEXGi0SM2SbVIwmZL:-N6lIyMA5aRylRhfye5Q:bepl4nc) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

other than what?
</blockquote></details>

in config.json you give ip from mellanox, then you give other ip from mellanox to files fio_jobs


<!-- Sent from Reviewable.io -->

2022-07-12 11:35 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 19 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1879#-N6lugf39O92ucE2oYOe:-N6mBFxIBgTAXpLO5y2g:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please correct all headers
</blockquote></details>

Done.

___
___
*[`tools/perf/multiply_connection_benchmark.md` line 5 at r17](https://reviewable.io/reviews/pmem/rpma/1879#-N6ltXHn-KnyypTF-ukG:-N6mAT_n4a17KiIwr60E:b-7rl0jd) ([raw file](https://github.com/pmem/rpma/blob/bc7654ba289f818af0da9a111064b0334a64d986/tools/perf/multiply_connection_benchmark.md#L5)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Modification of job files
</blockquote></details>

done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 6 at r17](https://reviewable.io/reviews/pmem/rpma/1879#-N6ltnw75c26HCoC5XLq:-N6mAgGm2NGKMQjMFul7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bc7654ba289f818af0da9a111064b0334a64d986/tools/perf/multiply_connection_benchmark.md#L6)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Adding second IP address
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 53 at r17](https://reviewable.io/reviews/pmem/rpma/1879#-N6luDEx1tXKZ9s1qidC:-N6mBBE8BMg-bAScD06F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bc7654ba289f818af0da9a111064b0334a64d986/tools/perf/multiply_connection_benchmark.md#L53)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

### Adding second {filename} parameter
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 12:04 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEXGi0SM2SbVIwmZL:-N6mHWVb2m33lHY9E4Rz:b-1hsw12) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

in config.json you give ip from mellanox, then you give other ip from mellanox to files fio_jobs
</blockquote></details>

In such case we need an introduction that we have one IP in Jason file and we have to configure another in fio file
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHPqJ5712cWj8k6sV:-N6mHPqJ5712cWj8k6sW:b-vevs7u) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ### Adding second IP address
> We have to add one `IP address` (e.g. **192.168.101.4**) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> Moreover we have to hardcode another (e.g. **192.168.102.4**) `IP address` in these files.
> ```

bold is also not needed here it is just an IP address



_Code quote:_
```Markdown
**192.168.102.4**
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 35 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHhqd6gAMXRF9HMIf:-N6mHhqd6gAMXRF9HMIg:undefined) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L35)):*
> ```Markdown
> serverip=192.168.102.4
> ```
> For every `*server.fio` file from the folder [fio_jobs](./tools/perf/fio_jobs) `serverip` from `[global]` section shall be moved to the `[server]` section: 
> ```





_Suggestion:_
```Markdown
Fio jobs files
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 87 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHpkA6v_cFAskpm9w:-N6mHpkA6v_cFAskpm9x:b3kra) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L87)):*
> ```Markdown
> ```
> ## Adding second {filename} parameter
> For every `*server.fio` file from the folder [fio_jobs](./tools/perf/fio_jobs) you have to add `filename`
> ```

;



_Code quote:_
```Markdown
fio_jobs
```


<!-- Sent from Reviewable.io -->

2022-07-12 19:04 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 21 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 12 at r13](https://reviewable.io/reviews/pmem/rpma/1879#-N6NFYZ43coStasx_Gsx:-N6nmoYVALT2qE9OpyEA:b28opqh) ([raw file](https://github.com/pmem/rpma/blob/786ae200d310eb5bb9100353a039974a28b065b7/tools/perf/multiply_connection_benchmark.md#L12)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I do not understand what you want to say.
</blockquote></details>

Additionally, you have to encode a different `IP address` than in config.json (e.g. 192.168.102.4).
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r16](https://reviewable.io/reviews/pmem/rpma/1879#-N6hEXGi0SM2SbVIwmZL:-N6nmpjq9TufBtDO-BeT:b28opqh) ([raw file](https://github.com/pmem/rpma/blob/f5e3ca897443f28f05fe870ff6e1ea41fadc08c2/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

In such case we need an introduction that we have one IP in Jason file and we have to configure another in fio file
</blockquote></details>

Additionally, you have to encode a different `IP address` than in config.json (e.g. 192.168.102.4).
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHPqJ5712cWj8k6sV:-N6nlutSERzFMQtc8Lwx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

bold is also not needed here it is just an IP address
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 35 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHhqd6gAMXRF9HMIf:-N6mTLeyEJUXLjLNKswF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L35)):*
> ```Markdown
> serverip=192.168.102.4
> ```
> For every `*server.fio` file from the folder [fio_jobs](./tools/perf/fio_jobs) `serverip` from `[global]` section shall be moved to the `[server]` section: 
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 87 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHpkA6v_cFAskpm9w:-N6mTA_e96nE7sZ-jJ3C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L87)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

;
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 19:40 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 22 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 35 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHhqd6gAMXRF9HMIf:-N6nueHc4YG3AhmrnXi2:blyekot) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L35)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I can not see it.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r19](https://reviewable.io/reviews/pmem/rpma/1879#-N6nupQsD_uI6nKlhRuK:-N6nupQsD_uI6nKlhRuL:undefined) ([raw file](https://github.com/pmem/rpma/blob/cb7d2157615f6999fa42c7a164885bf0c5f29b2c/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> ## Modification of job files
> ### Adding second IP address
> We have to add one `IP address` (e.g. 192.168.101.4) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> ```





_Suggestion:_
```Markdown
 define
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r19](https://reviewable.io/reviews/pmem/rpma/1879#-N6nv1x---UwIkTVQKHN:-N6nv1x---UwIkTVQKHO:undefined) ([raw file](https://github.com/pmem/rpma/blob/cb7d2157615f6999fa42c7a164885bf0c5f29b2c/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> ## Modification of job files
> ### Adding second IP address
> We have to add one `IP address` (e.g. 192.168.101.4) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> ```





_Suggestion:_
```Markdown
`*client.fio` and `*server.fio` (`${serverip}`).
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r19](https://reviewable.io/reviews/pmem/rpma/1879#-N6nuOfv4lTg6yOyjOLB:-N6nuOfw-RBOyB25gL-m:b2pn4qj) ([raw file](https://github.com/pmem/rpma/blob/cb7d2157615f6999fa42c7a164885bf0c5f29b2c/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ### Adding second IP address
> We have to add one `IP address` (e.g. 192.168.101.4) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> Additionally, you have to encode a different `IP address` than in config.json (e.g. 192.168.102.4).
> ```

``we have to add `` is above but here is ``you have to``



_Code quote:_
```Markdown
you have
```


<!-- Sent from Reviewable.io -->

2022-07-12 20:13 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 22 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 35 at r18](https://reviewable.io/reviews/pmem/rpma/1879#-N6mHhqd6gAMXRF9HMIf:-N6o16Ha9MDkswVvVjxx:b-ey509y) ([raw file](https://github.com/pmem/rpma/blob/91c0e7ffd557fc087414372f4fe13ba57b274df7/tools/perf/multiply_connection_benchmark.md#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I can not see it.
</blockquote></details>

sorry now Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r19](https://reviewable.io/reviews/pmem/rpma/1879#-N6nv1x---UwIkTVQKHN:-N6o1J4Z7sg6LNxKNkHf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cb7d2157615f6999fa42c7a164885bf0c5f29b2c/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> ## Modification of job files
> ### Adding second IP address
> We have to add one `IP address` (e.g. 192.168.101.4) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r19](https://reviewable.io/reviews/pmem/rpma/1879#-N6nupQsD_uI6nKlhRuK:-N6o1PxJ6ZwQmjx_wpxM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cb7d2157615f6999fa42c7a164885bf0c5f29b2c/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> ## Modification of job files
> ### Adding second IP address
> We have to add one `IP address` (e.g. 192.168.101.4) in the `config.json` file which is used by `*client.fio` and `*server.fio`. 
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r19](https://reviewable.io/reviews/pmem/rpma/1879#-N6nuOfv4lTg6yOyjOLB:-N6o1jTw8HzAkPfmOkRZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cb7d2157615f6999fa42c7a164885bf0c5f29b2c/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``we have to add `` is above but here is ``you have to``
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 08:20 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 28 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r20](https://reviewable.io/reviews/pmem/rpma/1879#-N6qHQiv0Z_nQJZjowNz:-N6qbEGX-wvkexc_wFmA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34eaff24b0c37e2898e7f66e9ba0cb35817838e6/tools/perf/multiply_connection_benchmark.md#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Too many ` ` sections in one sentence
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 54 at r20](https://reviewable.io/reviews/pmem/rpma/1879#-N6qImUn7XuRC4pDjH5H:-N6qbZVp1PhhlMfmDfxT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34eaff24b0c37e2898e7f66e9ba0cb35817838e6/tools/perf/multiply_connection_benchmark.md#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Header level 3
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 62 at r20](https://reviewable.io/reviews/pmem/rpma/1879#-N6qItoO7iTJPDVlNiL9:-N6qb_3n5rnj4KSq62pY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34eaff24b0c37e2898e7f66e9ba0cb35817838e6/tools/perf/multiply_connection_benchmark.md#L62)):*
> ```Markdown
> # numjobs=${cores_per_socket}
> ```
> # Modification Runner
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 64 at r20](https://reviewable.io/reviews/pmem/rpma/1879#-N6qJUQH86CtaTxSkdJP:-N6qbbfjBkglqdeB3tbQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34eaff24b0c37e2898e7f66e9ba0cb35817838e6/tools/perf/multiply_connection_benchmark.md#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Filesystem-DAX
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 64 at r20](https://reviewable.io/reviews/pmem/rpma/1879#-N6qJNYp0BiA9TLviE4g:-N6qdI_rDEySKIp7os5I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34eaff24b0c37e2898e7f66e9ba0cb35817838e6/tools/perf/multiply_connection_benchmark.md#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

New line is missing
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 12:09 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 26 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rJ3Eg2F9UyqxxWedC:-N6rJ3Eg2F9UyqxxWedD:undefined) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ## Memory Setup
> We create 2 namespaces in 1 region in PMem.
> Finally we have to add our `/dev/dax` in the *config.json* file.
> ```





_Suggestion:_
```Markdown
the second
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rJ6TM4Gu6-r8amNVo:-N6rJ6TM4Gu6-r8amNVp:b32wxs) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ## Memory Setup
> We create 2 namespaces in 1 region in PMem.
> Finally we have to add our `/dev/dax` in the *config.json* file.
> ```

to



_Code quote:_
```Markdown
in
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rJEQ51QVpP7NF7-vf:-N6rJEQ51QVpP7NF7-vg:undefined) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ## Memory Setup
> We create 2 namespaces in 1 region in PMem.
> Finally we have to add our `/dev/dax` in the *config.json* file.
> ```





_Suggestion:_
```Markdown
Finally, we
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rJZxQ-tn5lCUdyERH:-N6rJZxRBnwyN0hU8HnY:b-m9qx56) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ## Memory Setup
> We create 2 namespaces in 1 region in PMem.
> Finally we have to add our `/dev/dax` in the *config.json* file.
> ```

we or you try to use only one form 



_Code quote:_
```Markdown
we
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 15 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rKHjDCBsbPar3wVsY:-N6rKHjDCBsbPar3wVsZ:bxs7w48) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L15)):*
> ```Markdown
> ### Adding second IP address
> You have to define one **IP address** (e.g. 192.168.101.4) in the *config.json* file which is used by *client.fio* and *server.fio* (**${serverip}**).
> Additionally, in *client.fio* and *server.fio* you have to encode a different IP address than in *config.json* (e.g. 192.168.102.4).
> ```

Move this sentence next to the example as shown below.



_Suggestion:_
```Markdown
You have to define one **IP address** (e.g. 192.168.101.4) in the *config.json* file which is used by *client.fio* and *server.fio* (**${serverip}**).
For every *client.fio* and *server.fio* file from the folder [Fio jobs files](./tools/perf/fio_jobs/) serverip from `[global]` section shall be moved to the `[client]` or `[server]` section:

```
[global]
...
# serverip=${serverip} #comment out or removed from [global] section
...
[client] or [server]
...
serverip=${serverip} # ${serverip} is used only by the first client or server
...
```
Additionally, in *client.fio* and *server.fio* you have to encode a different IP address than in *config.json* (e.g. 192.168.102.4).
Additionally, we have to create a new separate `[client]` or `[server]` section with a explicitly set **server IP**:
```
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 51 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rJVoN4B2lvVRLuz6u:-N6rJVoN4B2lvVRLuz6v:b-st7jz0) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L51)):*
> ```Markdown
> ```
> ### Adding second {filename} parameter
> For every *server.fio* file from the folder [Fio jobs files](./tools/perf/fio_jobs/) you have to add **filename**
> ```

link does not work



_Code quote:_
```Markdown
(./tools/perf/fio_jobs/)
```


<!-- Sent from Reviewable.io -->

2022-07-13 14:34 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 17 unresolved discussions (waiting on @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r24](https://reviewable.io/reviews/pmem/rpma/1879#-N6rJ6TM4Gu6-r8amNVo:-N6ryCe7ArLnwQAnU2cF:b32w12) ([raw file](https://github.com/pmem/rpma/blob/1fa20d7f375e04116b0d765b981a2451398c7417/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No


<!-- Sent from Reviewable.io -->

2022-07-14 12:03 UTC, osalyk requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r25](https://reviewable.io/reviews/pmem/rpma/1879#-N6w_Ips5nz96asZAbyG:-N6w_Ips5nz96asZAbyH:b-v4jg9m) ([raw file](https://github.com/pmem/rpma/blob/eaad385fd98471b5a093d26bf6738ad8117e4edc/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> 
> ## Memory Setup
> You create 2 namespaces in 1 region in PMem.
> ```

Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to Device DAX.



_Code quote:_
```Markdown
You create 2 namespaces in 1 region in PMem.
Finally, you have in add the second `/dev/dax` in the *config.json* file.
```


<!-- Sent from Reviewable.io -->

2022-07-18 10:23 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 13 unresolved discussions (waiting on @grom72, @haichangsi, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-18 13:11 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 13 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GME0D0tvmvvf4zYp5:-N7GME0D0tvmvvf4zYp6:bfh9o6n) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> 
> ## Memory Setup
> Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to Device DAX.
> ```

to the 



_Code quote:_
```Markdown
to Device DAX.
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 12 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNoBy44oJXdWq2OPi:-N7GNoBy44oJXdWq2OPj:blc2965) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L12)):*
> ```Markdown
> ```
> ## Modification of job files
> ### Adding second IP address
> ```

Adding a second



_Code quote:_
```Markdown
Adding second
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMXUPCAgRFYJbvY4t:-N7GMXUPCAgRFYJbvY4u:b-bhf6bz) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L14)):*
> ```Markdown
> ### Adding second IP address
> You have to define one **IP address** (e.g. 192.168.101.4) in the *config.json* file which is used by *client.fio* and *server.fio* (**${serverip}**).
> For every *client.fio* and *server.fio* file from the folder [Fio jobs files](./fio_jobs) serverip from `[global]` section shall be moved to the `[client]` or `[server]` section:
> ```

[Fio jobs files](./fio_jobs) folder



_Code quote:_
```Markdown
folder [Fio jobs files](./fio_jobs)
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7GMqmH0eSHChB_PnRx:b6t0245) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
> ```Markdown
> [global]
> ...
> # serverip=${serverip} #comment out or removed from [global] section
> ```

# comment out or remove from the [global] section



_Code quote:_
```Markdown
#comment out or removed from [global] section
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNFk_-_2rltPLl_3G:-N7GNFkaACxK9-2Rfi2E:b-f1yitb) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L26)):*
> ```Markdown
> ```
> Additionally, in *client.fio* and *server.fio* you have to encode a different IP address than in *config.json* (e.g. 192.168.102.4).
> Additionally, we have to create a new separate `[client]` or `[server]` section with a explicitly set **server IP**:
> ```

You have to create a new separate `[client]` or `[server]` section with a explicitly set **server IP** as well:
*note for you only (Additionally used twice and in one sentence you used YOU and right after that WE)



_Code quote:_
```Markdown
Additionally, we have to create a new separate `[client]` or `[server]` section with a explicitly set **server IP**:
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 49 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNjli5D6T5c92CGWp:-N7GNjli5D6T5c92CGWq:blc2965) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L49)):*
> ```Markdown
> serverip=192.168.102.4
> ```
> ### Adding second {filename} parameter
> ```

Adding a second



_Code quote:_
```Markdown
 Adding second 
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 50 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GO7XNAuyiZeZMhb63:-N7GO7XNAuyiZeZMhb64:bxwx1xe) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L50)):*
> ```Markdown
> ```
> ### Adding second {filename} parameter
> For every *server.fio* file from the folder [Fio jobs files](./fio_jobs) you have to add **filename**
> ```

[Fio jobs files](./fio_jobs) folder you have to add a **filename**



_Code quote:_
```Markdown
folder [Fio jobs files](./fio_jobs) you have to add **filename**
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 56 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GPNotAyfVsCVlPMup:-N7GPNotAyfVsCVlPMuq:b4eucnl) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L56)):*
> ```Markdown
> filename=${filename1}
> ```
> Additionally, we have to create a new separate `[server]` ( if you haven't created before ) section with a **filename**:
> ```

Additionally, you have to create a new separate `[server]` section with a **filename** ( if you haven't done that before ) :



_Code quote:_
```Markdown
Additionally, we have to create a new separate `[server]` ( if you haven't created before ) section with a **filename**:
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 66 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GOQEyBhmroF35sjwM:-N7GOQEyBhmroF35sjwN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L66)):*
> ```Markdown
> ```
> ### Removed [cpuio] section from the server
> For every *server.fio* file from the folder [Fio jobs files](./fio_jobs) you need to remove the `[cpuio]`
> ```

.



_Code quote:_
```Markdown
folder [Fio jobs files](./fio_jobs)
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 77 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GOYtF8uWbFbVcp9pG:-N7GOYtF8uWbFbVcp9pH:bx2c0uw) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L77)):*
> ```Markdown
> 
> **Note**: File System DAX is not supported.
> In the [fio.py](./lib/benchmark/runner/fio.py) file you need to add env of **filename2** variable in the if condition.
> ```

of the **filename2**



_Code quote:_
```Markdown
of **filename2**
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 88 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GQgneEosjcU5uzLFw:-N7GQgneEosjcU5uzLFx:b-2sowzi) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L88)):*
> ```Markdown
>             env.append('filename2={}'.format(self.__config['REMOTE_PMEM_PATH_2']))
> ```
> Below is the code that we have based on
> ```

Maybe only: 'The code that we have based on'. It is pretty obvious that it is placed below. @grom72  @ldorau @osalyk 



_Code quote:_
```Markdown
Below is the code that we have based on
```


<!-- Sent from Reviewable.io -->

2022-07-18 14:01 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 13 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r25](https://reviewable.io/reviews/pmem/rpma/1879#-N6w_Ips5nz96asZAbyG:-N7F9niKEmgwWyUSZB7B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaad385fd98471b5a093d26bf6738ad8117e4edc/tools/perf/multiply_connection_benchmark.md#L7)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to Device DAX.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r25](https://reviewable.io/reviews/pmem/rpma/1879#-N6w3nMJ8E5HuSlcZYoK:-N7F9arY4b5UuqrONiWG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaad385fd98471b5a093d26bf6738ad8117e4edc/tools/perf/multiply_connection_benchmark.md#L8)):*
> ```Markdown
> ## Memory Setup
> You create 2 namespaces in 1 region in PMem.
> Finally, you have in add the second `/dev/dax` in the *config.json* file.
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GME0D0tvmvvf4zYp5:-N7GYXQm3Y571jnY3FhB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L7)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

to the 
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 12 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNoBy44oJXdWq2OPi:-N7GYaYl8Sh_oW5dcajj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L12)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Adding a second
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMXUPCAgRFYJbvY4t:-N7GZOl66osgp6cCNlBr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L14)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

[Fio jobs files](./fio_jobs) folder
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7GZaYKA6ZG4U09iJ69:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

# comment out or remove from the [global] section
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNFk_-_2rltPLl_3G:-N7GZxvJ8vtYfoE14wFl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L26)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

You have to create a new separate `[client]` or `[server]` section with a explicitly set **server IP** as well:
*note for you only (Additionally used twice and in one sentence you used YOU and right after that WE)
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 49 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNjli5D6T5c92CGWp:-N7G_0QmCnO3YXeFub1d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L49)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Adding a second
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 50 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GO7XNAuyiZeZMhb63:-N7G_H9A5wPiVEoktqfK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L50)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

[Fio jobs files](./fio_jobs) folder you have to add a **filename**
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 56 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GPNotAyfVsCVlPMup:-N7G_MlACT5gGGxqzVWX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L56)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Additionally, you have to create a new separate `[server]` section with a **filename** ( if you haven't done that before ) :
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 66 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GOQEyBhmroF35sjwM:-N7G_Ua87OQZ4lVZRKPe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L66)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 77 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GOYtF8uWbFbVcp9pG:-N7G_Y3yB714wqDQ1M92:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L77)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

of the **filename2**
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 88 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GQgneEosjcU5uzLFw:-N7GbEnh2RFN1Xt4onR_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L88)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Maybe only: 'The code that we have based on'. It is pretty obvious that it is placed below. @grom72  @ldorau @osalyk 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-18 16:32 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7H8OKRBJNfZdsgr41A:bdmy4e1) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

missing space after #, removed -> remove
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNFk_-_2rltPLl_3G:-N7H8bGb1aEU6EPgQfge:b-ptcquu) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L26)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

my bad, AN explicitly
___
*[`tools/perf/multiply_connection_benchmark.md` line 50 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GO7XNAuyiZeZMhb63:-N7H8DNvCixEEweTqVnO:bso096) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L50)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

add a **filename**


<!-- Sent from Reviewable.io -->

2022-07-18 21:10 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7I8HhV1A0ujdjNY9V9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

missing space after #, removed -> remove
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GNFk_-_2rltPLl_3G:-N7I8PoG2ViI8iWEVFm-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L26)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

my bad, AN explicitly
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 50 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GO7XNAuyiZeZMhb63:-N7I5s_LDvxN4kuJDYvU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L50)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

add a **filename**
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 88 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GQgneEosjcU5uzLFw:-N7I7CZR2q-t0-HypPln:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L88)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

maybe add "... is following:"
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 57 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbhL58dyzbIojCjbT:-N7I6AnODhzH7Uvgn2uk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No `sh` here - it is not a shell snippet.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 78 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbnRBAKhWCpzBhrID:-N7I6EPG8d0qqvwLnXl2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

python
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 81 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7Gc-t33k3xUQzr-WUm:-N7I6NAb5qZARwzfd5FG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 89 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7Gbr078PwXbfqKWkwO:-N7I7EXr8THI3whUkKy_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

python
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 93 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbwYW0bTqNF2Fw2Ka:-N7I7P2m33q9YXzWJW28:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 100 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbuKn1rwK03tuqbxT:-N7I840EAuGFKg31li2P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L100)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

python
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 06:17 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 13 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 8 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbVUC5ly75UUJpcZE:-N7K5Tme6nri3TycnfoF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

json
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 06:21 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72, @haichangsi, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 88 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GQgneEosjcU5uzLFw:-N7K63L8Df4f5mEmkp_D:b-eawedy) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L88)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`.` -> `:`
___
*[`tools/perf/multiply_connection_benchmark.md` line 81 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7Gc-t33k3xUQzr-WUm:-N7K67IaCq5q23v5zXja:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L81)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.
___
*[`tools/perf/multiply_connection_benchmark.md` line 93 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbwYW0bTqNF2Fw2Ka:-N7K6ILXAJR3qCrpikJe:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L93)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.


<!-- Sent from Reviewable.io -->

2022-07-19 06:28 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 88 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GQgneEosjcU5uzLFw:-N7K7BVr36EWH35WTqjl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L88)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`.` -> `:`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 81 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7Gc-t33k3xUQzr-WUm:-N7K8BcY1CSMfXckCOYT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 93 at r27](https://reviewable.io/reviews/pmem/rpma/1879#-N7GbwYW0bTqNF2Fw2Ka:-N7K8AF2BhQMamfUrE9q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9750b2a1620206d88d63835737edc0212508cee1/tools/perf/multiply_connection_benchmark.md#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 06:34 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-19 06:35 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r30, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-19 08:15 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7KWJG74L8Y6bGWYa3V:bedjfse) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

removed -> remove


<!-- Sent from Reviewable.io -->

2022-07-19 08:21 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7KXxqO02hjgc-H4lLu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

removed -> remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 08:24 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, @osalyk, and @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7KYIhnBbtcPimmMdXC:b-hvvapd) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

now a space is missing #comment out -> # comment out


<!-- Sent from Reviewable.io -->

2022-07-19 08:26 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 18 at r26](https://reviewable.io/reviews/pmem/rpma/1879#-N7GMqmH0eSHChB_PnRw:-N7KZEoR69P2mfm6PZ4Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85fe97cf45ef262bfb230cd32492980792b38d1e/tools/perf/multiply_connection_benchmark.md#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

now a space is missing #comment out -> # comment out
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 08:27 UTC, haichangsi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879#-:-N7KZFmY2RnMiuNND4tb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-21 11:48 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r31](https://reviewable.io/reviews/pmem/rpma/1879#-N7V_09I9z1CjPEeqgUk:-N7V_09I9z1CjPEeqgUl:undefined) ([raw file](https://github.com/pmem/rpma/blob/c13ef129fecfcba09d704164d1ae9ce69a74f1ea/tools/perf/multiply_connection_benchmark.md#L14)):*
> ```Markdown
> ### Adding a second IP address
> You have to define one **IP address** (e.g. 192.168.101.4) in the *config.json* file which is used by *client.fio* and *server.fio* (**${serverip}**).
> For every *client.fio* and *server.fio* file from the [Fio jobs files](./fio_jobs) folder serverip from `[global]` section shall be moved to the `[client]` or `[server]` section:
> ```





_Suggestion:_
```Markdown
**serverip**
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r31](https://reviewable.io/reviews/pmem/rpma/1879#-N7V_COC3sSx6LBc2JV7:-N7V_COC3sSx6LBc2JV8:undefined) ([raw file](https://github.com/pmem/rpma/blob/c13ef129fecfcba09d704164d1ae9ce69a74f1ea/tools/perf/multiply_connection_benchmark.md#L26)):*
> ```Markdown
> ```
> Additionally, in *client.fio* and *server.fio* you have to encode a different IP address than in *config.json* (e.g. 192.168.102.4).
> You have to create a new separate `[client]` or `[server]` section with an explicitly set **server IP** as well:
> ```





_Suggestion:_
```Markdown
**serverip**
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 76 at r31](https://reviewable.io/reviews/pmem/rpma/1879#-N7V_Va84XA4v3wAP2zh:-N7V_Va84XA4v3wAP2zi:b-byfdrb) ([raw file](https://github.com/pmem/rpma/blob/c13ef129fecfcba09d704164d1ae9ce69a74f1ea/tools/perf/multiply_connection_benchmark.md#L76)):*
> ```Markdown
> ### Second filename
> 
> **Note**: File System DAX is not supported.
> ```

New line


<!-- Sent from Reviewable.io -->

2022-07-21 11:53 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-22 12:44 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-22 13:16 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r32](https://reviewable.io/reviews/pmem/rpma/1879#-N7a26ma809YbmThFSAU:-N7a26ma809YbmThFSAV:undefined) ([raw file](https://github.com/pmem/rpma/blob/0d4c754f672ce3ce111e65d2cfd912251d65eca9/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> 
> ## Memory Setup
> Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to the Device DAX.
> ```





_Suggestion:_
```Markdown
*config.json*
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r32](https://reviewable.io/reviews/pmem/rpma/1879#-N7a2BaEAoRXn5L3B9F5:-N7a2BaEAoRXn5L3B9F6:undefined) ([raw file](https://github.com/pmem/rpma/blob/0d4c754f672ce3ce111e65d2cfd912251d65eca9/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> 
> ## Memory Setup
> Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to the Device DAX.
> ```





_Suggestion:_
```Markdown
**REMOTE_PMEM_PATH_2**
```


<!-- Sent from Reviewable.io -->

2022-07-25 08:46 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r31](https://reviewable.io/reviews/pmem/rpma/1879#-N7V_09I9z1CjPEeqgUk:-N7_Yk0PB5KbJQaqhHsi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c13ef129fecfcba09d704164d1ae9ce69a74f1ea/tools/perf/multiply_connection_benchmark.md#L14)):*
> ```Markdown
> ### Adding a second IP address
> You have to define one **IP address** (e.g. 192.168.101.4) in the *config.json* file which is used by *client.fio* and *server.fio* (**${serverip}**).
> For every *client.fio* and *server.fio* file from the [Fio jobs files](./fio_jobs) folder serverip from `[global]` section shall be moved to the `[client]` or `[server]` section:
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 26 at r31](https://reviewable.io/reviews/pmem/rpma/1879#-N7V_COC3sSx6LBc2JV7:-N7_Ywzj7EdTWIpRdgSS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c13ef129fecfcba09d704164d1ae9ce69a74f1ea/tools/perf/multiply_connection_benchmark.md#L26)):*
> ```Markdown
> ```
> Additionally, in *client.fio* and *server.fio* you have to encode a different IP address than in *config.json* (e.g. 192.168.102.4).
> You have to create a new separate `[client]` or `[server]` section with an explicitly set **server IP** as well:
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 76 at r31](https://reviewable.io/reviews/pmem/rpma/1879#-N7V_Va84XA4v3wAP2zh:-N7_Z4jn7GYm6tqxEYjO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c13ef129fecfcba09d704164d1ae9ce69a74f1ea/tools/perf/multiply_connection_benchmark.md#L76)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r32](https://reviewable.io/reviews/pmem/rpma/1879#-N7a26ma809YbmThFSAU:-N7oXBYQ0rxJwKFLXTBi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d4c754f672ce3ce111e65d2cfd912251d65eca9/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> 
> ## Memory Setup
> Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to the Device DAX.
> ```

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r32](https://reviewable.io/reviews/pmem/rpma/1879#-N7a2BaEAoRXn5L3B9F5:-N7oXM6Q16Jvi791WeSF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d4c754f672ce3ce111e65d2cfd912251d65eca9/tools/perf/multiply_connection_benchmark.md#L7)):*
> ```Markdown
> 
> ## Memory Setup
> Prepare an additional Device DAX on an RPMA target. Then, in the config.json file, add a new parameter REMOTE_PMEM_PATH_2 and assign it the path to the Device DAX.
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-25 10:14 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879#-:-N7oqLWqCTrIBhxEEjlf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-26 06:22 UTC, Patryk717 reviewed
@ldorau ?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879#-:-N7t9ulDEwrg1WG5ij0E:b87va4p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-27 06:26 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 15 unresolved discussions (waiting on @ldorau)

___
*[`tools/perf/multiply_connection_benchmark.md` line 1 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ubnD47sQ5H3K2r1_r:-N7yJ6ZH67Yv6LLM7_R3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the multi-link
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 3 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7uc2ZeDRMONmQvdrQP:-N7yJDcs2VHHJacwe-KO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the configuration of ...
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 7 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7uc9Y3BON7Fhq-rHkC:-N7yJIyEEKvAPWAfCmAl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the RPMA target
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 12 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ucMAb9fpt501_t3q0:-N7yJMvt5ZpgHMAKJZiS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the second
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ucns5EFc9Hg_JxXKB:-N7yJZml6vZ3NO8DysgO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the **serverip** parameter`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ucsfW-VdvDttiYFBy:-N7yJ_U_D13t2Q0Kob8G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

from the `[global]` section
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 14 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ucwCgD52_bKcDMwME:-N7yJdezB1qouOMUud7K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or the `[server]` section
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 25 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ud4o6AZN9mjhwgjpa:-N7yJsuACzjbEvCB6VTK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`in the *client.fio* and the *server.fio* files`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 25 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7udIxM04jl-0dChnnJ:-N7yJxCrA9wg9eIrUcTv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`in the *config.json* file`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 49 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7udcsFAk-YnmJy4P57:-N7yK-yq8DY2_XSXlmR7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the second
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 50 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7udt1mDFsnBq0S5aBU:-N7yK9pD1RyCGlnQ58_K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`a **filename** parameter`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 56 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7udz3BEs71MBZzxMYp:-N7yKDiL7FwuADxjlv6Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`a **filename** parameter`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 65 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ue5t-6jnw6E9SZMST:-N7yKHxkBLMk8Qpruym1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the [cpuio] section`
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 66 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ue9CiAKoBMI0AViEc:-N7yKLTv8dSaTd3025-N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the `[cpuio]` section
</blockquote></details>

Done.
___
*[`tools/perf/multiply_connection_benchmark.md` line 74 at r33](https://reviewable.io/reviews/pmem/rpma/1879#-N7ueFd42KepcxNBtNaQ:-N7yKXsU8IvcFbHNtNTj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ae0f14a73290d2e4624a0b7be77c938fe49bd6a/tools/perf/multiply_connection_benchmark.md#L74)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The second filename
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-27 09:45 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r34, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

___
*[`tools/perf/multiply_connection_benchmark.md` line 50 at r34](https://reviewable.io/reviews/pmem/rpma/1879#-N7z1sav-P59ZQWV59qy:-N7z1sav-P59ZQWV59qz:bx1svdw) ([raw file](https://github.com/pmem/rpma/blob/b03f5159073d769175980747ac7f1842d31a6660/tools/perf/multiply_connection_benchmark.md#L50)):*
> ```Markdown
> ```
> ### Adding the second {filename} parameter
> For every *server.fio* file from the [Fio jobs files](./fio_jobs) folder you have to add a **filename** parameter
> ```

the **filename** parameter



_Code quote:_
```Markdown
a **filename** parameter
```
___
*[`tools/perf/multiply_connection_benchmark.md` line 56 at r34](https://reviewable.io/reviews/pmem/rpma/1879#-N7z1ypSA8FLKsuZHUrU:-N7z1ypSA8FLKsuZHUrV:bx1svdw) ([raw file](https://github.com/pmem/rpma/blob/b03f5159073d769175980747ac7f1842d31a6660/tools/perf/multiply_connection_benchmark.md#L56)):*
> ```Markdown
> filename=${filename1}
> ```
> Additionally, you have to create a new separate `[server]` section with a **filename** parameter ( if you haven't done that before ) :
> ```

the **filename** parameter



_Code quote:_
```Markdown
a **filename** parameter
```


<!-- Sent from Reviewable.io -->

2022-07-27 09:59 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r35, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-27 10:00 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1879#-:-N7z5Jgu8dunR9Mr8jwX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-27 10:00 UTC, merged