test: rename multithreaded tests prefix to "mtt-"
pmem/rpma pull request #1908
Opened 2022-07-01 10:55 UTC by grom72

Use shorter multithreaded tests prefix "mtt-", unified with unit tests prefix "ut-"

e.g.
$ ctest
...
 74/169 Test  #74: ut-utils-ibv_context_is_odp_capable_0_none .............................   Passed    0.03 sec
        Start  75: ut-log_default-init-fini_0_none
 75/169 Test  #75: ut-log_default-init-fini_0_none ........................................   Passed    0.03 sec
        Start  76: ut-log_default-function_0_none
 76/169 Test  #76: ut-log_default-function_0_none .........................................   Passed    0.03 sec
        Start  77: mtt-conn_cfg-get_cq_size_0_none
 77/169 Test  #77: mtt-conn_cfg-get_cq_size_0_none ..............................   Passed    0.03 sec
...

2022-07-01 11:45 UTC, haichangsi reviewed
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-07-01 11:45 UTC, haichangsi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908#-:-N5t_81y1LJX2d7zUtpW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-07-01 13:01 UTC, osalyk requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1908#-N5tqTaX12WMnlpJZvvO:-N5tqTaX12WMnlpJZvvP:bl5kkic) (no related file):*
Please correct the number of commits

___


<!-- Sent from Reviewable.io -->

2022-07-04 10:32 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1908#-N5tqTaX12WMnlpJZvvO:-N67l4CF-s1YrMBRNAHA:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please correct the number of commits
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-07-04 10:41 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908#-:-N67n4Ws2Fhtk3pr9E2l:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-06 09:58 UTC, Patryk717 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908#-:-N6HwZ8D7ss4tfT3ESLX:bg7igkv)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-07 05:47 UTC, osalyk approved these changes
> Reviewed 1 of 1 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1908)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-07-07 05:48 UTC, merged