examples: add common-pmem_map_file and signature_check to example09
pmem/rpma pull request #1909
Opened 2022-07-01 10:58 UTC by haichangsi

2022-07-01 11:41 UTC, grom72 requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYHFS1ud8nfv0UCx5:-N5tYHFS1ud8nfv0UCx6:b8n70fy) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L43)):*
> ```CMake
> link_directories(${LIBRPMA_LIBRARY_DIRS})
> 
> function(add_example name)
> ```

have not we talked already to move this function to a common location?



_Code quote:_
```CMake
function(add_example name)
```
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 301 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYPiV13eAVfMOlEDX:-N5tYPiV13eAVfMOlEDY:undefined) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/client.c#L301)):*
> ```C
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> ```





_Suggestion:_
```C
#ifdef USE_PMEM
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);
	} else
#endif /* USE_PMEM */
```
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 244 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYqQ49MLNM7XaFzw6:-N5tYqQ49MLNM7XaFzw7:undefined) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/server.c#L244)):*
> ```C
> #else
> 	(void) printf(
> 			"At this point, persist function should be called if libpmem2 or libpmem will be in use\n");
> ```





_Suggestion:_
```C
persistent memory
```


<!-- Sent from Reviewable.io -->

2022-07-01 11:41 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-01 12:58 UTC, osalyk requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYHFS1ud8nfv0UCx5:-N5tngds7MqBoovaT4RO:b4cclp3) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L43)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

have not we talked already to move this function to a common location?
</blockquote></details>

+1 add_example_with_pmem()
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 134 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5to7N9CnMwjp-RG5YG:-N5to7N9CnMwjp-RG5YH:b3w6vox) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/client.c#L134)):*
> ```C
> 	if ((ret = rpma_mr_reg(peer, msg_ptr, KILOBYTE,
> 			RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV,
> 			&msg_mr))) {
> ```

if ((ret = rpma_mr_reg(peer, msg_ptr, KILOBYTE, RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV,
			&msg_mr))) {

Please correct all similar cases



_Code quote:_
```C
	if ((ret = rpma_mr_reg(peer, msg_ptr, KILOBYTE,
			RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV,
			&msg_mr))) {
```


<!-- Sent from Reviewable.io -->

2022-07-04 11:47 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-05 07:05 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYHFS1ud8nfv0UCx5:-N6C4-g57yOQ9NnXZ7rR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L43)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

+1 add_example_with_pmem()
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 134 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5to7N9CnMwjp-RG5YG:-N6C5kJV7ZH9eEwp33iM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/client.c#L134)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

if ((ret = rpma_mr_reg(peer, msg_ptr, KILOBYTE, RPMA_MR_USAGE_SEND | RPMA_MR_USAGE_RECV,
			&msg_mr))) {

Please correct all similar cases
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 301 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYPiV13eAVfMOlEDX:-N6C5l6XBftycsLOqs8t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/client.c#L301)):*
> ```C
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> ```

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 244 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYqQ49MLNM7XaFzw6:-N6C5w8L5ttjnhhmRqR1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/server.c#L244)):*
> ```C
> #else
> 	(void) printf(
> 			"At this point, persist function should be called if libpmem2 or libpmem will be in use\n");
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-05 07:17 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1909#-N5tYHFS1ud8nfv0UCx5:-N6CCw0-2fMPZvDlKpKO:b-hly75m) ([raw file](https://github.com/pmem/rpma/blob/aad50beab802776f0404e5f3972a3943017c5129/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L43)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

no, you are wrong, as we discussed with @ldorau in this example we use libprotobuf so I had to leave it the way it is 


<!-- Sent from Reviewable.io -->

2022-07-05 07:59 UTC, haichangsi reviewed
Ref: #1791

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909#-:-N6CMkfn46escP1f6jwO:bljg8d)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-05 12:46 UTC, grom72 requested changes
> Reviewed 2 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 44 at r5](https://reviewable.io/reviews/pmem/rpma/1909#-N6DOLsG267Mxx-kfKi8:-N6DOLsG267Mxx-kfKi9:b-b4szco) ([raw file](https://github.com/pmem/rpma/blob/71734ce411fd90a6e1892e3e9b29c81ec3e7acf3/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L44)):*
> ```CMake
> link_directories(${LIBRPMA_LIBRARY_DIRS})
> 
> add_example_with_pmem(server server.c GPSPM_flush.pb-c.c ../common/common-conn.c)
> ```

what about ``options USE_LIBPROTOBUFC``?



_Suggestion:_
```CMake
add_example_with_pmem(server server.c GPSPM_flush.pb-c.c ../common/common-conn.c USE_LIBPROTOBUFC)
add_example_with_pmem(client client.c GPSPM_flush.pb-c.c ../common/common-conn.c USE_LIBPROTOBUFC)
```


<!-- Sent from Reviewable.io -->

2022-07-05 13:46 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-05 13:46 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-06 07:25 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 44 at r5](https://reviewable.io/reviews/pmem/rpma/1909#-N6DOLsG267Mxx-kfKi8:-N6HOPRg-ifZtACmG1ga:b-c4j8lh) ([raw file](https://github.com/pmem/rpma/blob/71734ce411fd90a6e1892e3e9b29c81ec3e7acf3/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about ``options USE_LIBPROTOBUFC``?
</blockquote></details>

It is a bigger problem, I've tried many solutions on the second branch, none of them works


<!-- Sent from Reviewable.io -->

2022-07-07 06:43 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 44 at r5](https://reviewable.io/reviews/pmem/rpma/1909#-N6DOLsG267Mxx-kfKi8:-N6HdV7PCQrQCs0v-k8_:b-iduufy) ([raw file](https://github.com/pmem/rpma/blob/71734ce411fd90a6e1892e3e9b29c81ec3e7acf3/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L44)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

It is a bigger problem, I've tried many solutions on the second branch, none of them works
</blockquote></details>

Let's move to intersprint


<!-- Sent from Reviewable.io -->

2022-07-18 10:53 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-18 10:54 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 44 at r6](https://reviewable.io/reviews/pmem/rpma/1909#-N7Fw5CG0MHHpVTjJzoY:-N7FwH5N9gbFDJJsSm19:bbjabq0) ([raw file](https://github.com/pmem/rpma/blob/4a18687de9a483dd100586e5ce653ec3a09e9f5d/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`USE_LIBPROTOBUFC` is not a source file
</blockquote></details>

It seems that `add_example_with_pmem()` should be fixed.



_Code quote:_
```CMake
add_example_with_pmem
```


<!-- Sent from Reviewable.io -->

2022-07-19 10:18 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 44 at r6](https://reviewable.io/reviews/pmem/rpma/1909#-N7Fw5CG0MHHpVTjJzoY:-N7KxilXAMr74ZEautTS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4a18687de9a483dd100586e5ce653ec3a09e9f5d/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems that `add_example_with_pmem()` should be fixed.
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/CMakeLists.txt` line 45 at r6](https://reviewable.io/reviews/pmem/rpma/1909#-N7FwAHk5ku-5p_1mmIf:-N7KxjB047wTd1oDSXj6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4a18687de9a483dd100586e5ce653ec3a09e9f5d/examples/09-flush-to-persistent-GPSPM/CMakeLists.txt#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 10:31 UTC, grom72 approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-07-19 11:38 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r3, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1909#-N7LEaLA9KCIB7dQ0aac:-N7LEaLB9lWvs2KoU0-m:b1u5h6g) (no related file):*
The first commit does not build:
https://github.com/ldorau/rpma/actions/runs/2697237557

Each and every commit has to build correctly.
You should not submit one commit with bugs and the next one with fixes. 
Squash them please.

___


<!-- Sent from Reviewable.io -->

2022-07-19 11:54 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1909#-N7LEaLA9KCIB7dQ0aac:-N7LIH7e4rBgBgohhcGv:b-zfurtq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The first commit does not build:
https://github.com/ldorau/rpma/actions/runs/2697237557

Each and every commit has to build correctly.
You should not submit one commit with bugs and the next one with fixes. 
Squash them please.
</blockquote></details>

I know. In the beggining it was like that:
1st one - changes to both client and server (bulding correctly)
2nd - cmake changes (now also building correctly)
Maybe during this whole process sth has changed. Sorry. Done.

___


<!-- Sent from Reviewable.io -->

2022-07-19 12:09 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 4 at r8](https://reviewable.io/reviews/pmem/rpma/1909#-N7LM9tP7kNVwAa8KwaQ):*
use capital letters



_Code quote:_
```
use_libprotobufc
```


<!-- Sent from Reviewable.io -->

2022-07-19 12:11 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[`-- commits` line 4 at r8](https://reviewable.io/reviews/pmem/rpma/1909#-N7LM9tP7kNVwAa8KwaQ):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

use capital letters
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-19 12:11 UTC, ldorau approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1909)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-19 12:36 UTC, merged