rpma: make conn_cfg ... thread safe
pmem/rpma pull request #1913
Opened 2022-07-05 07:32 UTC by haichangsi

2022-07-05 12:24 UTC, osalyk approved these changes
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-05 12:55 UTC, grom72 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6DQAMhAf9vyaA5IaR-:b-uuvskr) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
> ```C
> 	atomic_init(&(*cfg_ptr)->timeout_ms,
> 		atomic_load_explicit(&Conn_cfg_default.timeout_ms, __ATOMIC_SEQ_CST));
> 	(*cfg_ptr)->rcq_size = RPMA_DEFAULT_RCQ_SIZE;
> ```

what about ``rcq_size``?



_Code quote:_
```C
(*cfg_ptr)->rcq_size = RPMA_DEFAULT_RCQ_SIZE;
```
___
*[`src/conn_cfg.c` line 136 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQX7RCUk5gv7afJ9B:-N6DQX7RCUk5gv7afJ9C:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L136)):*
> ```C
> 		atomic_load_explicit(&Conn_cfg_default.timeout_ms, __ATOMIC_SEQ_CST));
> 	(*cfg_ptr)->rcq_size = RPMA_DEFAULT_RCQ_SIZE;
> 	(*cfg_ptr)->shared_comp_channel = RPMA_DEFAULT_SHARED_COMPL_CHANNEL;
> ```

.



_Code quote:_
```C
(*cfg_ptr)->shared_comp_channel = RPMA_DEFAULT_SHARED_COMPL_CHANNEL;
```


<!-- Sent from Reviewable.io -->

2022-07-05 13:46 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-06 08:41 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1913#-N6DJbijBSxEwduNKsh3:-N6HePpd3aTo4utFQkxI:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

What about CHANGELOG.md?  :wink: 
</blockquote></details>

Done.

___
___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6HeZk--GeAOgV98egb:b-8nomtv) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about ``rcq_size``?
</blockquote></details>

I discussed this with @osalyk, maybe I was not precise enough. I thought if there is no mt tests and suppression then it is left to be done
___
*[`src/conn_cfg.c` line 136 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQX7RCUk5gv7afJ9B:-N6Hexa33yq4ov2lB8mw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L136)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2022-07-06 09:14 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6HmVfa4DgBA3x8R16p:b-4c9ten) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I discussed this with @osalyk, maybe I was not precise enough. I thought if there is no mt tests and suppression then it is left to be done
</blockquote></details>

Nevermind. Done.


<!-- Sent from Reviewable.io -->

2022-07-06 14:51 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-07 07:15 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-07 08:39 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`CHANGELOG.md` line 22 at r4](https://reviewable.io/reviews/pmem/rpma/1913#-N6HsZB13gcVbrYqq-TD:-N6Mo0Y1CUuIW-0VppGd:b-stydlq) ([raw file](https://github.com/pmem/rpma/blob/824a54caf40c035b2e1593d1b89aa9de152617a0/CHANGELOG.md#L22)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

cmpl_channel
</blockquote></details>

rcq also, Done
___
*[`CHANGELOG.md` line 23 at r4](https://reviewable.io/reviews/pmem/rpma/1913#-N6HsNU42vENym5SIXJf:-N6MnTIQ2SW57Uho66Wb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/824a54caf40c035b2e1593d1b89aa9de152617a0/CHANGELOG.md#L23)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Add ### Removed section
</blockquote></details>

Done.
___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6MmgAI0dPYV-IoanrG:bwmh6w3) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

So, perhaps we need more MT tests ... to cover also ``rcq_size`` and ``shared_comp_channel``
</blockquote></details>

Yes, I can do it


<!-- Sent from Reviewable.io -->

2022-07-07 09:34 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-07 11:14 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-07 11:30 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6NQFPi9SgY9kHh2kkY:b89fiw) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Are you going to extend this PR or do you create a new one?
</blockquote></details>

Create a new one probably, do you want me to do it in this sprint?


<!-- Sent from Reviewable.io -->

2022-07-07 12:17 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6N_r2rDuwJR4RVyXeN:b7alrxq) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Create a new one probably, do you want me to do it in this sprint?
</blockquote></details>

I propose to add tests in this PR


<!-- Sent from Reviewable.io -->

2022-07-07 13:07 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6NlNcdA6X7l0tJXwF0:b32v57) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I propose to add tests in this PR
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-07-08 08:38 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1913#-N6N_uw_CPUiObSNIdlv:-N6RxKKa5QYbMH7HoPAz:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

___
___
*[`src/conn_cfg.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1913#-N6DQAMhAf9vyaA5IaQz:-N6RxKzB8h5oFMEQhMdm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9494dba109e109aee82295401ebfe3b0e1574d6d/src/conn_cfg.c#L135)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-08 09:26 UTC, osalyk requested changes
> Reviewed 3 of 7 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 24 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S6niuAKlBu4g0kYAD:-N6S6niuAKlBu4g0kYAE:brc182s) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L24)):*
> ```C
> 		(struct rpma_conn_cfg_common_prestate *)prestate;
> 	int ret;
> 	bool shared = true;
> ```

define the value in the header, like RPMA_CONN_CFG_COMMON_Q_SIZE_EXP
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c` line 31 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S78Cc05h2eF-nMwpr:-N6S78Cc05h2eF-nMwps:b-2or7gt) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c#L31)):*
> ```C
> 
> 	if (shared != true)
> 		MTT_ERR(tr, "rq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP",
> ```

one line



_Code quote:_
```C
		MTT_ERR(tr, "rq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP",
				EINVAL);
```
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rcq_size.c` line 31 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S7FBM2iO0mGE3ELmo:-N6S7FBM2iO0mGE3ELmp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rcq_size.c#L31)):*
> ```C
> 
> 	if (rcq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP)
> 		MTT_ERR(tr, "rcq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP",
> ```

.



_Code quote:_
```C
		MTT_ERR(tr, "rcq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP",
				EINVAL);
```
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c` line 37 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S7Mht9LCRtTrl0VAt:-N6S7Mhu3SLyQYlwnIe7:bejuszd) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c#L37)):*
> ```C
> 	}
> 
> 	if (shared != true)
> ```

use define



_Code quote:_
```C
shared != true
```


<!-- Sent from Reviewable.io -->

2022-07-08 12:49 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 2 of 21 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 24 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S6niuAKlBu4g0kYAD:-N6SjHzw9wvWMfDMwvKe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L24)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

define the value in the header, like RPMA_CONN_CFG_COMMON_Q_SIZE_EXP
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 117 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S5DgA2XA4WSCQkMKr:-N6SjHQ73DWKUAgvhN2_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L117)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@haichangsi can you try to move the `` main ()`` function to two separate files``conn_cfg_common_set/get`` and remove it from all other files?
and modify CMakeFile.txt to link proper ``conn_cfg_common_set/get``

or as an alternative
have to macros in conn_cfg_common.h:
```
#define MAIN_GET (thread ) \
int \
main(int argc, char *argv[]) \
{ \
	struct mtt_args args = {0}; \

	if (mtt_parse_args(argc, argv, &args)) \
		return -1; \

	struct rpma_conn_cfg_common_prestate prestate = {NULL}; \

	struct mtt_test test = { \
			&prestate, \
			rpma_conn_cfg_common_prestate_init, \
			NULL, \
			NULL, \
			thread, \
			NULL, \
			NULL, \
			rpma_conn_cfg_common_prestate_fini \
	}; \

	return mtt_run(&test, args.threads_num); \
} \
```
```
#define MAIN_SET (thread ) \
int \
main(int argc, char *argv[]) \
{ \
	struct mtt_args args = {0}; \

	if (mtt_parse_args(argc, argv, &args)) \
		return -1; \

	struct rpma_conn_cfg_common_prestate prestate = {NULL}; \

	struct mtt_test test = { \
			&prestate, \
			rpma_conn_cfg_common_prestate_init, \
			NULL, \
			rpma_conn_cfg_common_init, \
			thread, \
			rpma_conn_cfg_common_fini, \
			NULL, \
			rpma_conn_cfg_common_prestate_fini \
	}; \

	return mtt_run(&test, args.threads_num); \
} \
```
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c` line 31 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S78Cc05h2eF-nMwpr:-N6SjPh--J3IOb6xS2VM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c#L31)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

one line
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rcq_size.c` line 31 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S7FBM2iO0mGE3ELmo:-N6SjVx9-lzj3vcDI879:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_rcq_size.c#L31)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c` line 37 at r7](https://reviewable.io/reviews/pmem/rpma/1913#-N6S7Mht9LCRtTrl0VAt:-N6SkO0d93KMZOryha6q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d251f68f44f29e3d0c3f98704964bf0995120a75/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

use define
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-08 12:57 UTC, grom72 approved these changes
> Reviewed 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-08 15:09 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 77 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TLkjT-Pw5vFZrhVCp:-N6TLkjT-Pw5vFZrhVCq:b-it25da) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L77)):*
> ```C
> 
> /*
>  * rpma_conn_cfg_common_init -- allocate state and create a new connection
> ```

It seems to be no longer needed.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 105 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TLqdAEU6fXM1CgBRu:-N6TLqdBEmue0MZ1fqPY:b-it25da) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L105)):*
> ```C
>  */
> void rpma_conn_cfg_common_fini(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *tr)
> ```

It seems to be no longer needed.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c` line 27 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TKb6uChW3WODWevoJ:-N6TKb6uChW3WODWevoK:bsyw0pt) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c#L27)):*
> ```C
> 			rpma_conn_cfg_common_prestate_init,
> 			NULL,
> 			rpma_conn_cfg_common_init,
> ```

Do we need ``rpma_conn_cfg_common_init`` at all?
It seems that we use only ``prestate*`` in all ``thread``  functions.

If this is true then we could have only one ``main()`` function and move it to ``rpma_conn_cfg_common.c``.



_Suggestion:_
```C
NULL
```
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c` line 29 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TKyLECFDT62yUgcrN:-N6TKyLECFDT62yUgcrO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c#L29)):*
> ```C
> 			rpma_conn_cfg_common_init,
> 			thread,
> 			rpma_conn_cfg_common_fini,
> ```

.



_Suggestion:_
```C
NULL,
```


<!-- Sent from Reviewable.io -->

2022-07-11 06:39 UTC, osalyk requested changes
> Reviewed 2 of 7 files at r6, 19 of 19 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c` line 31 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6fy0e09FdbuCLe0jDX:-N6fy0e09FdbuCLe0jDY:b3kre) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c#L31)):*
> ```C
> 
> 	if (shared != true)
> 		MTT_ERR(tr, "rq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP", EINVAL);
> ```

?



_Code quote:_
```C
"rq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP"
```
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c` line 37 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6fyUex9tWxS0WMWSWQ:-N6fyUex9tWxS0WMWSWR:b-3dk3l2) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c#L37)):*
> ```C
> 	if (shared != RPMA_CONN_CFG_COMMON_SHARED)
> 		MTT_ERR_MSG(tr, "Invaild completion channel's value: %d instead of %d", -1,
> 			shared, true);
> ```

Use RPMA_CONN_CFG_COMMON_SHARED



_Suggestion:_
```C
RPMA_CONN_CFG_COMMON_SHARED
```


<!-- Sent from Reviewable.io -->

2022-07-11 09:32 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 77 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TLkjT-Pw5vFZrhVCp:-N6gXsdeAEcVgd6Sh1dT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L77)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It seems to be no longer needed.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c` line 105 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TLqdAEU6fXM1CgBRu:-N6gXzl_3M7gH5TwQYBb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.c#L105)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It seems to be no longer needed.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c` line 27 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TKb6uChW3WODWevoJ:-N6gVBp65NscsC89ZT9o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need ``rpma_conn_cfg_common_init`` at all?
It seems that we use only ``prestate*`` in all ``thread``  functions.

If this is true then we could have only one ``main()`` function and move it to ``rpma_conn_cfg_common.c``.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c` line 29 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6TKyLECFDT62yUgcrN:-N6gVCKz2VzUul-L8uNJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_common_set.c#L29)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c` line 31 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6fy0e09FdbuCLe0jDX:-N6gXlkI-K39PH0noBNO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c#L31)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c` line 37 at r8](https://reviewable.io/reviews/pmem/rpma/1913#-N6fyUex9tWxS0WMWSWQ:-N6gXmr37vUE5QsIeSW2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01ac108c1a00e39e7df61b269150545b7986671a/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Use RPMA_CONN_CFG_COMMON_SHARED
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-11 11:51 UTC, grom72 requested changes
> Reviewed 2 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 18 of 21 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c` line 30 at r9](https://reviewable.io/reviews/pmem/rpma/1913#-N6h4jQD5u0SvxHUC3zi:-N6h4jQD5u0SvxHUC3zj:bgpw8ir) ([raw file](https://github.com/pmem/rpma/blob/9cee4459c34e39069e892d6a22b0e938c66ccefe/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c#L30)):*
> ```C
> 	}
> 
> 	if (shared != RPMA_CONN_CFG_COMMON_SHARED)
> ```

``shared != true `` seems to be more clear for the code reader but if you want I would suggest ``RPMA_CONN_CFG_COMMON_IS_SHARED``



_Code quote:_
```C
shared != RPMA_CONN_CFG_COMMON_SHARED
```


<!-- Sent from Reviewable.io -->

2022-07-11 11:51 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 18 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c` line 37 at r9](https://reviewable.io/reviews/pmem/rpma/1913#-N6h5TRlApPNmbqxJfqH:-N6h5TRlApPNmbqxJfqI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9cee4459c34e39069e892d6a22b0e938c66ccefe/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c#L37)):*
> ```C
> 	if (shared != RPMA_CONN_CFG_COMMON_SHARED)
> 		MTT_ERR_MSG(tr, "Invaild completion channel's value: %d instead of %d", -1,
> 			shared, RPMA_CONN_CFG_COMMON_SHARED);
> ```

.



_Code quote:_
```C
RPMA_CONN_CFG_COMMON_SHARED
```


<!-- Sent from Reviewable.io -->

2022-07-11 11:52 UTC, grom72 reviewed
> Reviewed 2 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-11 11:52 UTC, grom72 reviewed
> Reviewed 1 of 5 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-13 09:38 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: 14 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c` line 30 at r9](https://reviewable.io/reviews/pmem/rpma/1913#-N6h4jQD5u0SvxHUC3zi:-N6qorFh3cUbfUw_WQf-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cee4459c34e39069e892d6a22b0e938c66ccefe/tests/multithreaded/conn_cfg/rpma_conn_cfg_get_compl_channel.c#L30)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``shared != true `` seems to be more clear for the code reader but if you want I would suggest ``RPMA_CONN_CFG_COMMON_IS_SHARED``
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c` line 37 at r9](https://reviewable.io/reviews/pmem/rpma/1913#-N6h5TRlApPNmbqxJfqH:-N6qotI-4-Jb2-qSyjbO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cee4459c34e39069e892d6a22b0e938c66ccefe/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_compl_channel.c#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 10:08 UTC, osalyk approved these changes
> Reviewed 1 of 5 files at r9, 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-07-13 11:23 UTC, grom72 requested changes
> Reviewed 2 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 1 at r10](https://reviewable.io/reviews/pmem/rpma/1913#-N6rI94HCMPAEMnhksGj):*
Please squash into one commit


<!-- Sent from Reviewable.io -->

2022-07-13 11:54 UTC, grom72 approved these changes
> Reviewed 4 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-13 11:55 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1913#-:-N6rPOCy-qRROqCKUOqZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-13 12:24 UTC, merged