doc: add docker to documentations
pmem/rpma pull request #1921
Opened 2022-07-11 09:04 UTC by Patryk717

2022-07-11 10:14 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @osalyk and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6gkBbhDw91_eiYzWxT:-N6gkBbhDw91_eiYzWxU:b34p92n) (no related file):*
BENCHMARKING.md file is missing

___
___
*[`DEVELOPMENT.md` line 106 at r1](https://reviewable.io/reviews/pmem/rpma/1921#-N6gfMW_BqTlv_iG9YxG:-N6gfMWaD-elZcntTA3n:bqq9rr4) ([raw file](https://github.com/pmem/rpma/blob/6175ed924ea89b64cc40694931e8a7610fb20994/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Before running the tests, make sure you have all the packages needed to configure exaples `rpma/utils/docker/images/`
> ```

Make sure you have the required libraries installed (see EXAMPLES_DEPS section in `rpma/utils/docker/images/` files)



_Code quote:_
```Markdown
 Before running the tests, make sure you have all the packages needed to configure exaples `rpma/utils/docker/images/`
```
___
*[`INSTALL.md` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1921#-N6gg4Qh4mERTZZw7lB9:-N6gg4Qi4kWGMxPNaM5v:bwaxh8d) ([raw file](https://github.com/pmem/rpma/blob/6175ed924ea89b64cc40694931e8a7610fb20994/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> If you want exact packages go to `rpma/utils/docker/images/`
> ```

**Note**: 



_Code quote:_
```Markdown
If you want exact packages go to `rpma/utils/docker/images/`
```


<!-- Sent from Reviewable.io -->

2022-07-12 06:46 UTC, osalyk requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[`DEVELOPMENT.md` line 122 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l3zdu-OoAnC81S5Pr:-N6l3zdu-OoAnC81S5Ps:b3kr4) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/DEVELOPMENT.md#L122)):*
> ```Markdown
> ```
> 
> 4. Set the `RPMA_TESTING_IP` environment variable to an IP address of this interface:
> ```

5



_Suggestion:_
```Markdown
5. Set the `RPMA_TESTING_IP` environment variable to an IP address of this interface:
```
___
*[`INSTALL.md` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1921#-N6gg4Qh4mERTZZw7lB9:-N6l8dzxCZuHDWG847zQ:bio3lbb) ([raw file](https://github.com/pmem/rpma/blob/6175ed924ea89b64cc40694931e8a7610fb20994/INSTALL.md#L6)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

done.
</blockquote></details>

\*\*Note**: To make sure you have all the components you need, you can use our [docker scripts](./utils/docker/images/).
___
*[`INSTALL.md` line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8jGt2OAfEoXXGfOn:-N6l8jGuA-0WaBu30ysf:b-qe9xhx) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L7)):*
> ```Markdown
> ### Common requirements
> *Note*: If you want exact packages go to `rpma/utils/docker/images/`
> In order to build librpma, you need to have installed several components:
> ```

Add empty line
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8qWWACm1G4l37GeR:-N6l8qWWACm1G4l37GeS:b-voflou) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: You can check the required packages here `rpma/utils/docker/images/`
> ```

\+ section name



_Code quote:_
```Markdown
*Note*: You can check the required packages here `rpma/utils/docker/images/`
```


<!-- Sent from Reviewable.io -->

2022-07-12 06:47 UTC, grom72 requested changes
> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 13 unresolved discussions (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6gkBbhDw91_eiYzWxT:-N6l4sZZC3-l4U2_QYDs:b9q4ziq) (no related file):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Could you add direct links to all files?

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6l5EkDDhIby-I4DxsX:-N6l5EkDDhIby-I4DxsY:b-pdrgbz) (no related file):*
@ldorau @osalyk - this PR must wait until we adjust all Docker files to a new layout.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6l5T5u8VdbRcGLx4gO:-N6l5T5u8VdbRcGLx4gP:b-y6i5fd) (no related file):*
@patryk717 - please add dependencies (at least #1916)  and you can prepare a separate draft PR as placement for all other expected changes
this PR (branch ``add_docker``) should have already modified Ubuntu22.04 Docker file

___
___
*[`DEVELOPMENT.md` line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l56iRDj1QL_ezqQgV:-N6l56iRDj1QL_ezqQgW:bncfiyh) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Make sure you have the required libraries installed (see EXAMPLES_DEPS section in rpma/utils/docker/images/ files)
> ```

It should be a link



_Code quote:_
```Markdown
rpma/utils/docker/images
```
___
*[`DEVELOPMENT.md` line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l6Tj21KNZ7qRt7ZYY:-N6l6Tj21KNZ7qRt7ZYZ:undefined) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Make sure you have the required libraries installed (see EXAMPLES_DEPS section in rpma/utils/docker/images/ files)
> ```





_Suggestion:_
```Markdown
ENV EXAMPLES_DEPS
```
___
*[`INSTALL.md` line 6 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l5shP1d7mrCqIt5W7:-N6l5shP1d7mrCqIt5W8:bb7k22n) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> *Note*: If you want exact packages go to `rpma/utils/docker/images/`
> ```

link



_Code quote:_
```Markdown
rpma/utils/docker/images/
```
___
*[`INSTALL.md` line 6 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8Nui7KYu7tMYLEcK:-N6l8Nui7KYu7tMYLEcL:b45h) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> *Note*: If you want exact packages go to `rpma/utils/docker/images/`
> ```





_Suggestion:_
```Markdown
Please check `rpma/utils/docker/images/*` to see exact packages names for supported OS'es.
```
___
*[`INSTALL.md` line 6 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8lG-BHioWQSJOfKt:-N6l8lG-BHioWQSJOfKu:b2nghhb) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> *Note*: If you want exact packages go to `rpma/utils/docker/images/`
> ```

I propose to move this section after the first bullet list. (Before ` In order to build the documentation` header



_Code quote:_
```Markdown
*Note*:
```
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l61iG3Spvy8PHVXco:-N6l61iG3Spvy8PHVXcp:b-mb0lag) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: You can check the required packages here `rpma/utils/docker/images/`
> ```

Please add references to sections as you did in the case of ``EXAMPLES_DEPS``



_Code quote:_
```Markdown
*Note*: You can check the required packages here `rpma/utils/docker/images/`
```
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l9Dzf1fRRh5z0Twd-:-N6l9Dzf1fRRh5z0Twd0:b-kik66z) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: You can check the required packages here `rpma/utils/docker/images/`
> ```

Please check ... as I propose above already.



_Suggestion:_
```Markdown
Please check
```


<!-- Sent from Reviewable.io -->

2022-07-12 08:09 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 0 of 3 files reviewed, 13 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6gkBbhDw91_eiYzWxT:-N6lS3is-CpyyWD8WGRY:bp3wyy0) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Could you add direct links to all files?
</blockquote></details>

sorry idk how 

___
___
*[`DEVELOPMENT.md` line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l56iRDj1QL_ezqQgV:-N6lJsX91cE9Q-vHj_vu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/DEVELOPMENT.md#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It should be a link
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 106 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l6Tj21KNZ7qRt7ZYY:-N6lJuQUAylB7MDTcChR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Make sure you have the required libraries installed (see EXAMPLES_DEPS section in rpma/utils/docker/images/ files)
> ```

Done.
___
*[`DEVELOPMENT.md` line 122 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l3zdu-OoAnC81S5Pr:-N6lKDhbA6W7X9clVLQG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/DEVELOPMENT.md#L122)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

5
</blockquote></details>

Done.
___
*[`INSTALL.md` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1921#-N6gg4Qh4mERTZZw7lB9:-N6lKg8i0izMnuTyHgDh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6175ed924ea89b64cc40694931e8a7610fb20994/INSTALL.md#L6)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

\*\*Note**: To make sure you have all the components you need, you can use our [docker scripts](./utils/docker/images/).
</blockquote></details>

Done.
___
*[`INSTALL.md` line 6 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l5shP1d7mrCqIt5W7:-N6lKglxDKXf1A1FkPLP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

link
</blockquote></details>

Done.
___
*[`INSTALL.md` line 6 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8Nui7KYu7tMYLEcK:-N6lKyOg89DzzCK9i9aq:b-pzbzpm) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> *Note*: If you want exact packages go to `rpma/utils/docker/images/`
> ```

**Note**: To make sure you have all the components you need, you can use our docker scripts. ?
___
*[`INSTALL.md` line 6 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8lG-BHioWQSJOfKt:-N6lKu7D0CaoY-fo3B0a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I propose to move this section after the first bullet list. (Before ` In order to build the documentation` header
</blockquote></details>

Done.
___
*[`INSTALL.md` line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8jGt2OAfEoXXGfOn:-N6lKnnG7utb4Ytz1HIR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/INSTALL.md#L7)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Add empty line
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l9Dzf1fRRh5z0Twd-:-N6lLCBd8xAlsoNukwzF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please check ... as I propose above already.
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l8qWWACm1G4l37GeR:-N6lRct1-nbRn57Ml0D-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

\+ section name
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6l61iG3Spvy8PHVXco:-N6lRdLG5xPWiHKNodZ5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please add references to sections as you did in the case of ``EXAMPLES_DEPS``
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 08:23 UTC, grom72 requested changes
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1921#-N6lU7PL7uycBLVcWMUA:-N6lU7PL7uycBLVcWMUB:b-o7ohkk) ([raw file](https://github.com/pmem/rpma/blob/b81156138fd1ef5751ff1e93e51f8ca5f56cc1e6/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: Please check the required packages see [EXAMPLES_DEPS](./utils/docker/images/)
> ```

please use the same semantic for all references`ENV EXAMPLES_DEPS [images](./........)



_Code quote:_
```Markdown
EXAMPLES_DEPS
```
___
*[`tools/perf/BENCHMARKING.md` line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1921#-N6lUd4t7ThIL0S3_-qW:-N6lUd4t7ThIL0S3_-qX:bmp3lmd) ([raw file](https://github.com/pmem/rpma/blob/b81156138fd1ef5751ff1e93e51f8ca5f56cc1e6/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: Please check the required packages see [EXAMPLES_DEPS](./utils/docker/images/)
> ```

What does it mean?



_Code quote:_
```Markdown
Please check the required packages see 
```


<!-- Sent from Reviewable.io -->

2022-07-12 09:53 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 1 of 3 files reviewed, 12 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1921#-N6lU7PL7uycBLVcWMUA:-N6lot_u6YgpH_8AFfjd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b81156138fd1ef5751ff1e93e51f8ca5f56cc1e6/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

please use the same semantic for all references`ENV EXAMPLES_DEPS [images](./........)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 11:02 UTC, osalyk requested changes
> Reviewed 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1921#-N6m3pUi3eEyt-yylRzu:-N6m3pUj6pj1aawTH5_W:b3kre) ([raw file](https://github.com/pmem/rpma/blob/11c687cc1c20bfbccc441ab3f88ee29417ba10ba/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: Please check the required packages (see ENV EXAMPLES_DEPS section in [images](./utils/docker/images/) files)
> ```

?



_Code quote:_
```Markdown
EXAMPLES_DEPS
```


<!-- Sent from Reviewable.io -->

2022-07-12 11:30 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 2 of 3 files reviewed, 9 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1921#-N6m3pUi3eEyt-yylRzu:-N6m9zCs-lxR9Ulnbcc9:b1oasgb) ([raw file](https://github.com/pmem/rpma/blob/11c687cc1c20bfbccc441ab3f88ee29417ba10ba/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

i delete this @grom72 said 'please use the same semantic for all references`ENV EXAMPLES_DEPS images' and i copy paste


<!-- Sent from Reviewable.io -->

2022-07-12 12:00 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-12 12:00 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-12 12:49 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6l5T5u8VdbRcGLx4gO:-N6mS8413WZnwL27-0dc:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@patryk717 - please add dependencies (at least #1916)  and you can prepare a separate draft PR as placement for all other expected changes
this PR (branch ``add_docker``) should have already modified Ubuntu22.04 Docker file
</blockquote></details>

Done.

___
___
*[`DEVELOPMENT.md` line 106 at r5](https://reviewable.io/reviews/pmem/rpma/1921#-N6mFluu3dvJPP5H3mlO:-N6mR3PCDpSsDNrOzLsH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ba140a0b0280cf7ffdc130487a8aaeb42077d9b3/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Make sure you have the required libraries installed (see ENV EXAMPLES_DEPS section in [images](./utils/docker/images/) files)
> ```

Done.
___
*[`INSTALL.md` line 6 at r5](https://reviewable.io/reviews/pmem/rpma/1921#-N6mF5Uv5raAZz1G8JY_:-N6mRAsvDTss5ily939g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ba140a0b0280cf7ffdc130487a8aaeb42077d9b3/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> **Note**: To make sure you have all the components you need, you can use our [docker scripts](./utils/docker/images/)
> ```

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6mFMO-81bkkJ8aeUik:-N6mRcrS7NsEZrc0TBo4:b-9lphoz) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: You can check the required packages here `rpma/utils/docker/images/`
> ```

section ... ?


<!-- Sent from Reviewable.io -->

2022-07-12 19:11 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6mGbfP6nmF32GfjzCm:-N6nnar44KGfMdGPSTj6:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think this is the best way to refer to Dockerfiles:
``To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images/)`` optionally extended by a particular section i.e.:``ENV EXAMPLES_DEPS``
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1921#-N6m_eU6DBdUYkEwsD8g:-N6nnZkK8s6_3UpcQGIO:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please mark all addressed comments with the word ``Done`` to indicate review author that she/he can confirm the correctness of the modification. Otherwise nobody will take a look at your fixes.
</blockquote></details>

Done.

___
___
*[`tools/perf/BENCHMARKING.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1921#-N6mFMO-81bkkJ8aeUik:-N6mRcrS7NsEZrc0TBo4:b-7rl0jd) ([raw file](https://github.com/pmem/rpma/blob/e42356c1b3492452416fb0fd77e15855b05b6bad/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: You can check the required packages here `rpma/utils/docker/images/`
> ```

done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1921#-N6m3pUi3eEyt-yylRzu:-N6nnSFG4ew2Og9BP2XP:b-7rl0jd) ([raw file](https://github.com/pmem/rpma/blob/11c687cc1c20bfbccc441ab3f88ee29417ba10ba/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

i delete this @grom72 said 'please use the same semantic for all references`ENV EXAMPLES_DEPS images' and i copy paste
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-07-12 19:43 UTC, grom72 requested changes
> Reviewed 2 of 3 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r8](https://reviewable.io/reviews/pmem/rpma/1921#-N6nvll70MNiEU6DOsOl:-N6nvll70MNiEU6DOsOm:bo3eelk) ([raw file](https://github.com/pmem/rpma/blob/23de45918167d8836cd0111f1c80fe65c1829bd6/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images) (section ...)
> ```

What does it mean?
Please refer to exact ENV



_Code quote:_
```Markdown
(section ...)
```


<!-- Sent from Reviewable.io -->

2022-07-12 19:43 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-12 20:07 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r8](https://reviewable.io/reviews/pmem/rpma/1921#-N6nvll70MNiEU6DOsOl:-N6o0RF771Owk4GcKPaE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/23de45918167d8836cd0111f1c80fe65c1829bd6/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What does it mean?
Please refer to exact ENV
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 07:00 UTC, osalyk requested changes
> Reviewed 1 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1921#-N6m3pUi3eEyt-yylRzu:-N6qLlpUCWBVlxbNIAxF:bxkwasp) ([raw file](https://github.com/pmem/rpma/blob/11c687cc1c20bfbccc441ab3f88ee29417ba10ba/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

done.
</blockquote></details>

and ENV TOOLS_DEPS



_Code quote (from utils/docker/images/Dockerfile.ubuntu-22.04):_
```
ENV TOOLS_DEPS
```


<!-- Sent from Reviewable.io -->

2022-07-13 07:08 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`tools/perf/BENCHMARKING.md` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1921#-N6m3pUi3eEyt-yylRzu:-N6qNls02fJngXsDB9qy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/11c687cc1c20bfbccc441ab3f88ee29417ba10ba/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

and ENV TOOLS_DEPS
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 08:01 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r10](https://reviewable.io/reviews/pmem/rpma/1921#-N6qZQnVCSt4g4VqTJ2r:-N6qZQnVCSt4g4VqTJ2s:undefined) ([raw file](https://github.com/pmem/rpma/blob/43b81069217558c8643d038033952726c0780542/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images/)
> ```





_Suggestion:_
```Markdown
support yourself with
```
___
*[`tools/perf/BENCHMARKING.md` line 17 at r10](https://reviewable.io/reviews/pmem/rpma/1921#-N6qZfbKBRe2ofdAQqzI:-N6qZfbKBRe2ofdAQqzJ:undefined) ([raw file](https://github.com/pmem/rpma/blob/43b81069217558c8643d038033952726c0780542/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images) (ENV TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
> ```





_Suggestion:_
```Markdown
can support yourself with
```
___
*[`tools/perf/BENCHMARKING.md` line 17 at r10](https://reviewable.io/reviews/pmem/rpma/1921#-N6qZxTuAOA1RapDQLsV:-N6qZxTuAOA1RapDQLsW:undefined) ([raw file](https://github.com/pmem/rpma/blob/43b81069217558c8643d038033952726c0780542/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images) (ENV TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
> ```





_Suggestion:_
```Markdown
can support yourself with
```


<!-- Sent from Reviewable.io -->

2022-07-13 08:07 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r10](https://reviewable.io/reviews/pmem/rpma/1921#-N6qZQnVCSt4g4VqTJ2r:-N6qaAl7EWtvK9fKGdyP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/43b81069217558c8643d038033952726c0780542/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images/)
> ```

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r10](https://reviewable.io/reviews/pmem/rpma/1921#-N6qZfbKBRe2ofdAQqzI:-N6q_w3CBdSIbY1KATCz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/43b81069217558c8643d038033952726c0780542/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images) (ENV TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
> ```

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r10](https://reviewable.io/reviews/pmem/rpma/1921#-N6qZxTuAOA1RapDQLsV:-N6qa9KcEaoMZ7X6AyOR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/43b81069217558c8643d038033952726c0780542/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: To make sure you have all the components you need, you can use our [Dockerfiles](./utils/docker/images) (ENV TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 09:14 UTC, grom72 requested changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qp_il8UNt_K7nJNJR:-N6qp_il8UNt_K7nJNJS:b4ifamk) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/)
> ```

(ENV ... section)
___
*[`INSTALL.md` line 6 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qpUdF5lNAkG_rq9tA:-N6qpKVcCQdWCWyT1f-r:bif6qbp) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> **Note**: To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/)
> ```

(ENV ... and ENV ... sections)


<!-- Sent from Reviewable.io -->

2022-07-13 10:21 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qp_il8UNt_K7nJNJR:-N6r40bC1v47YyRHwRBE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/DEVELOPMENT.md#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

(ENV ... section)
</blockquote></details>

Done.
___
*[`INSTALL.md` line 6 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qpUdF5lNAkG_rq9tA:-N6r41B01JAJZeItQaBj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/INSTALL.md#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

(ENV ... and ENV ... sections)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 11:26 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qp_il8UNt_K7nJNJR:-N6rIgksBJ0hR1PeAmLV:b-kfqqvn) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/DEVELOPMENT.md#L106)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wrong section
___
*[`INSTALL.md` line 6 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qpUdF5lNAkG_rq9tA:-N6rIdUP75UfcyhrvpQe:b-kfqqvn) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/INSTALL.md#L6)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Wrong section


<!-- Sent from Reviewable.io -->

2022-07-13 11:26 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-13 11:26 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-13 12:37 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qp_il8UNt_K7nJNJR:-N6rZ1521U_pIfBFRB17:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/DEVELOPMENT.md#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Wrong section
</blockquote></details>

Done.



_Code quote (from INSTALL.md):_
```Markdown
(ENV TOOLS_DEPS sections)
```
___
*[`INSTALL.md` line 6 at r11](https://reviewable.io/reviews/pmem/rpma/1921#-N6qpUdF5lNAkG_rq9tA:-N6rZ1jcBz4mC5-daA_i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b85042beb444a8ca094b76338846a8df9dfb3417/INSTALL.md#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Wrong section
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 13:17 UTC, osalyk requested changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r13](https://reviewable.io/reviews/pmem/rpma/1921#-N6rgznz1nRrLlH5qCr7:-N6rgznz1nRrLlH5qCr8:undefined) ([raw file](https://github.com/pmem/rpma/blob/8ed37029d925d60eed60d40145d34bee1bb30d40/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV EXAMPLES_DEPS sections)
> ```





_Suggestion:_
```Markdown
ENV EXAMPLES_DEPS section
```
___
*[`INSTALL.md` line 6 at r13](https://reviewable.io/reviews/pmem/rpma/1921#-N6rh4c54t09ujJWkImV:-N6rh4c54t09ujJWkImW:bsr1lr3) ([raw file](https://github.com/pmem/rpma/blob/8ed37029d925d60eed60d40145d34bee1bb30d40/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> **Note**: To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV RPMA_DEPS sections)
> ```

ENV BASE_DEPS and ENV RPMA_DEPS sections



_Code quote:_
```Markdown
ENV RPMA_DEPS sections
```


<!-- Sent from Reviewable.io -->

2022-07-13 14:29 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-14 07:14 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r13](https://reviewable.io/reviews/pmem/rpma/1921#-N6rgznz1nRrLlH5qCr7:-N6vYldvBOs3b0I-Kv00:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ed37029d925d60eed60d40145d34bee1bb30d40/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV EXAMPLES_DEPS sections)
> ```

Done.
___
*[`INSTALL.md` line 6 at r13](https://reviewable.io/reviews/pmem/rpma/1921#-N6rh4c54t09ujJWkImV:-N6vYmtw8kmI9VklIsOs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ed37029d925d60eed60d40145d34bee1bb30d40/INSTALL.md#L6)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

ENV BASE_DEPS and ENV RPMA_DEPS sections
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 09:37 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-14 12:12 UTC, osalyk approved these changes
> Reviewed 1 of 4 files at r6, 1 of 3 files at r11, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-18 13:45 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r6, 1 of 3 files at r11, 2 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 5 unresolved discussions (waiting on @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GJ22CB6JgDPI6b-IY:-N7GJ22CB6JgDPI6b-IZ:b-lmjht) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV EXAMPLES_DEPS section)
> ```

Make sure you have all needed packages installed (they are listed in [Dockerfiles](./utils/docker/images/) (see the EXAMPLES_DEPS section)



_Code quote:_
```Markdown
To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV EXAMPLES_DEPS section)
```
___
*[`INSTALL.md` line 6 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GJd6e65LvDiZHCShD:-N7GJd6e65LvDiZHCShE:b-y83dzl) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/INSTALL.md#L6)):*
> ```Markdown
> 
> ### Common requirements
> **Note**: To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV BASE_DEPS and ENV RPMA_DEPS sections)
> ```

Change it to the following and move it to the end of this section:

```
**Note**: To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the BASE_DEPS and ENV RPMA_DEPS sections)
```



_Code quote:_
```Markdown
To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images/) (ENV BASE_DEPS and ENV RPMA_DEPS sections)
```
___
*[`INSTALL.md` line 16 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GYHxeCnDNYR7niz-l:-N7GYHxeCnDNYR7niz-m:bhx9wwi) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/INSTALL.md#L16)):*
> ```Markdown
> - librdmacm-dev(el)
> - libcmocka-dev(el) == 1.1.5-26-g672c5ce (please see [our docker script](./utils/docker/images/install-cmocka.sh) to install the verified revision)
> ```

Move it here with one empty line before and after.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GJyb44wDnszEY3aF_:-N7GJyb44wDnszEY3aFa:bkpv0tx) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - numactl
>  - pciutils (needed by ddio.sh, required only in case of the Cascade Lake platforms)
> *Note*: To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images) (ENV TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
> ```

To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)



_Code quote:_
```Markdown
To make sure you have all the components you need, you can support yourself with [Dockerfiles](./utils/docker/images) (ENV TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
```


<!-- Sent from Reviewable.io -->

2022-07-18 14:07 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GJ22CB6JgDPI6b-IY:-N7GbeTX8CZAdhLE0eHj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/DEVELOPMENT.md#L106)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Make sure you have all needed packages installed (they are listed in [Dockerfiles](./utils/docker/images/) (see the EXAMPLES_DEPS section)
</blockquote></details>

Done.
___
*[`INSTALL.md` line 6 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GJd6e65LvDiZHCShD:-N7Gc6b2D5isULr9qFt5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/INSTALL.md#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Change it to the following and move it to the end of this section:

```
**Note**: To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the BASE_DEPS and ENV RPMA_DEPS sections)
```

</blockquote></details>

Done.
___
*[`INSTALL.md` line 16 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GYHxeCnDNYR7niz-l:-N7Gc8L16FR-V9amJtQQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/INSTALL.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move it here with one empty line before and after.
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 17 at r14](https://reviewable.io/reviews/pmem/rpma/1921#-N7GJyb44wDnszEY3aF_:-N7GcOc672oFAHM3X3wv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/709716cb8abf2e0f4c121907b875442f0bff9858/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the TOOLS_PYTHON_DEPS and ENV TOOLS_DEPS sections)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-18 14:13 UTC, ldorau approved these changes
> Reviewed 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-19 08:12 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921#-:-N7KVtOP1WUIqesABDN4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-19 08:12 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-19 08:15 UTC, grom72 requested changes
<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> Reviewed 1 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921#-:-N7KWCwM4Ez5OQCjgPVo:b8b79qu)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r16](https://reviewable.io/reviews/pmem/rpma/1921#-N7KWOJKEVio_HHWfXrt:-N7KWOJKEVio_HHWfXru:undefined) ([raw file](https://github.com/pmem/rpma/blob/b2f2ca87253275613664732762c13e3de0a6c8be/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Make sure you have all needed packages installed (they are listed in [Dockerfiles](./utils/docker/images/) (see the EXAMPLES_DEPS section)
> ```





_Suggestion:_
```Markdown
1. Make sure you have all the needed packages installed. To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the EXAMPLES_DEPS section)
```


<!-- Sent from Reviewable.io -->

2022-07-19 08:45 UTC, grom72 approved these changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-19 08:58 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[`DEVELOPMENT.md` line 106 at r17](https://reviewable.io/reviews/pmem/rpma/1921#-N7KeyFKDRpXNkR3Bup-:-N7KeyFKDRpXNkR3Bup0:undefined) ([raw file](https://github.com/pmem/rpma/blob/0975e40a8dcd0487466061b489b0ed75ac9662af/DEVELOPMENT.md#L106)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. Make sure you have all the needed packages installed. To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the EXAMPLES_DEPS section)
> ```





_Suggestion:_
```Markdown
1. Make sure you have all needed packages installed (you can support yourself with [Dockerfiles](./utils/docker/images/) (see the EXAMPLES_DEPS section)).
```


<!-- Sent from Reviewable.io -->

2022-07-19 08:58 UTC, grom72 reviewed
> Reviewed 2 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-07-19 09:04 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-07-19 09:04 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1921#-:-N7Kgtu19WqMHmuQXq_b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-07-19 09:10 UTC, merged