test: add srq_cfg MT tests
pmem/rpma pull request #1958
Opened 2022-07-28 11:51 UTC by osalyk

- [ ] #1616

2022-07-28 11:59 UTC, haichangsi reviewed
What about ... :D

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958#-:-N83f5zq-t6Pil-1Yvi0:b-o20bju)* status: 0 of 64 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-28 12:57 UTC, osalyk reviewed
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958#-:-N83sYUT0E__Sr-ftPXO:b-896fix)* status: 0 of 65 files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-28 13:18 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 0 of 65 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-07-28 13:19 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 1 of 65 files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-29 09:28 UTC, ldorau requested changes
> Reviewed 8 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 9 of 65 files reviewed, 5 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/CMakeLists.txt` line 13 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88FiW-3cNuKIunv74C:-N88FiW-3cNuKIunv74D:bp6sn78) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/CMakeLists.txt#L13)):*
> ```CMake
> add_subdirectory(mr)
> add_subdirectory(peer)
> add_subdirectory(utils)
> ```

Keep alphabetical order, please.



_Code quote:_
```CMake
add_subdirectory(peer)
add_subdirectory(utils)
add_subdirectory(srq_cfg)
```
___
*[`tests/multithreaded/srq_cfg/CMakeLists.txt` line 9 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88FvIN-7_5n2_3Qj6f:-N88FvIN-7_5n2_3Qj6g:b-pgou3p) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/CMakeLists.txt#L9)):*
> ```CMake
> 
> add_multithreaded(NAME srq_cfg BIN get_rq_size
> 	SRCS rpma_srq_cfg_get_rq_size.c rpma_srq_cfg_common.c rpma_srq_cfg_common_get.c)
> ```

`get_rcq_size` should be before `get_rq_size`



_Code quote:_
```CMake
add_multithreaded(NAME srq_cfg BIN get_rq_size
	SRCS rpma_srq_cfg_get_rq_size.c rpma_srq_cfg_common.c rpma_srq_cfg_common_get.c)
add_multithreaded(NAME srq_cfg BIN get_rcq_size
```
___
*[`tests/multithreaded/srq_cfg/CMakeLists.txt` line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88G0MX1JONcvKRCYw8:-N88G0MX1JONcvKRCYw9:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/CMakeLists.txt#L15)):*
> ```CMake
> 	SRCS rpma_srq_cfg_new.c)
> add_multithreaded(NAME srq_cfg BIN set_rq_size
> 	SRCS rpma_srq_cfg_set_rq_size.c rpma_srq_cfg_common.c rpma_srq_cfg_common_set.c)
> ```

.



_Code quote:_
```CMake
add_multithreaded(NAME srq_cfg BIN set_rq_size
	SRCS rpma_srq_cfg_set_rq_size.c rpma_srq_cfg_common.c rpma_srq_cfg_common_set.c)
add_multithreaded(NAME srq_cfg BIN set_rcq_size
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_get.c` line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88Gaj8-FbIbvVI3cmo:-N88Gaj8-FbIbvVI3cmp:b2cvopo) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_get.c#L11)):*
> ```C
> #include "rpma_srq_cfg_common.h"
> 
> void thread(unsigned id, void *prestate, void *state, struct mtt_result *tr);
> ```

It should go to `rpma_srq_cfg_common.h`



_Code quote:_
```C
void thread(unsigned id, void *prestate, void *state, struct mtt_result *tr);
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c` line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88Gm_ZCJPGgFN9a1Xz:-N88Gm_ZCJPGgFN9a1Y-:ball0z0) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c#L11)):*
> ```C
> #include "rpma_srq_cfg_common.h"
> 
> void thread(unsigned id, void *prestate, void *state, struct mtt_result *tr);
> ```

Move it to `rpma_srq_cfg_common.h`



_Code quote:_
```C
void thread(unsigned id, void *prestate, void *state, struct mtt_result *tr);
```


<!-- Sent from Reviewable.io -->

2022-07-29 09:31 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 9 of 65 files reviewed, 6 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c` line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88Htzk-2PE38GCwlnv:-N88Htzk-2PE38GCwlnw:b-jnivb0) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c#L5)):*
> ```C
> 
> /*
>  * rpma_srq_cfg_common_set.c -- common main function for all srq_cfg set mt tests
> ```

Not needed - it is the same as `rpma_srq_cfg_common_get.c`



_Code quote:_
```C
rpma_srq_cfg_common_set.c
```


<!-- Sent from Reviewable.io -->

2022-07-29 09:34 UTC, ldorau requested changes
> Reviewed 53 of 53 files at r1, 3 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c` line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88Htzk-2PE38GCwlnv:-N88I-K52AFEF4-91V4k:buugsfa) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed - it is the same as `rpma_srq_cfg_common_get.c`
</blockquote></details>

I mean the whole file is not needed - it is the same as `rpma_srq_cfg_common_get.c`.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c` line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88IHuc7Q1YcRGfQjpb:-N88IHuc7Q1YcRGfQjpc:b-q0l2oe) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c#L26)):*
> ```C
> 	int ret;
> 
> 	if ((ret = rpma_srq_cfg_get_rcq_size(pr->cfg_ptr, &rcq_size))) {
> ```

It should be test for `rpma_srq_cfg_set_rcq_size` not for `get_`



_Code quote:_
```C
rpma_srq_cfg_get_rcq_size
```


<!-- Sent from Reviewable.io -->

2022-07-29 09:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 93 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88J-i011zz7LxNOYxe:-N88J-i011zz7LxNOYxf:b2nnx19) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L93)):*
> ```C
> 		return;
> 
> 	if (srq_cfg_get_all(pr->cfg_exp, &cfg_exp_vals, tr))
> ```

This is a test for `_new()` only, not for `_get()s`, so `_get()s`should not be called in `thread()`.



_Code quote:_
```C
	if (srq_cfg_get_all(st->cfg, &cfg_vals, tr))
		return;

	if (srq_cfg_get_all(pr->cfg_exp, &cfg_exp_vals, tr))
		return;
```


<!-- Sent from Reviewable.io -->

2022-07-29 09:53 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`tests/multithreaded/CMakeLists.txt` line 13 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88FiW-3cNuKIunv74C:-N88IiGG2QChO8tfBHFv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/CMakeLists.txt#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Keep alphabetical order, please.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/CMakeLists.txt` line 9 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88FvIN-7_5n2_3Qj6f:-N88J29s8GflamrtgG7A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/CMakeLists.txt#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`get_rcq_size` should be before `get_rq_size`
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/CMakeLists.txt` line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88G0MX1JONcvKRCYw8:-N88J31T34BJDR0uaEcc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/CMakeLists.txt#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_get.c` line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88Gaj8-FbIbvVI3cmo:-N88JZepCeZexPCm1axS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_get.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should go to `rpma_srq_cfg_common.h`
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c` line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88Htzk-2PE38GCwlnv:-N88KVTG4K8CognzpDxx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I mean the whole file is not needed - it is the same as `rpma_srq_cfg_common_get.c`.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 93 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88J-i011zz7LxNOYxe:-N88MxAd619wJO-j1Wci:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This is a test for `_new()` only, not for `_get()s`, so `_get()s`should not be called in `thread()`.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c` line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1958#-N88IHuc7Q1YcRGfQjpb:-N88LHfD-UtA0TmpRgiz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f608144109d868d94fcfdaf65fbdd1405fdb945/tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be test for `rpma_srq_cfg_set_rcq_size` not for `get_`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-29 10:25 UTC, ldorau reviewed
> Reviewed 2 of 14 files at r4, 12 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 65 of 66 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)



<!-- Sent from Reviewable.io -->

2022-07-29 11:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 65 of 66 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 33 at r5](https://reviewable.io/reviews/pmem/rpma/1958#-N88jdwvBUsNUlIPFgnQ:-N88jdwvBUsNUlIPFgnR:b-tnzgi3) ([raw file](https://github.com/pmem/rpma/blob/a3015f62db1f06cd87b66496f7aa01a893c6899a/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L33)):*
> ```C
> 
> /*
>  * thread -- create a new srq configuration object and check its default values
> ```

create a new srq configuration object



_Code quote:_
```C
create a new srq configuration object and check its default values
```


<!-- Sent from Reviewable.io -->

2022-07-29 11:43 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 65 of 66 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 33 at r5](https://reviewable.io/reviews/pmem/rpma/1958#-N88jdwvBUsNUlIPFgnQ:-N88l5t4A08PDZTRPUbC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a3015f62db1f06cd87b66496f7aa01a893c6899a/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

create a new srq configuration object
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-29 11:48 UTC, ldorau approved these changes
As regards the following MT tests:

```
  - rpma_srq_cfg_new
  - rpma_srq_cfg_get_rcq_size
  - rpma_srq_cfg_get_rq_size
  - rpma_srq_cfg_set_rcq_size
  - rpma_srq_cfg_set_rq_size
```

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958#-:-N88mEmP2cweFJbw1ZkB:b-qe0mjl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-07-29 11:49 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-N88mUGSAP0B7PHiaRuR:-N88mUGSAP0B7PHiaRuS:bdd2au6) (no related file):*
Waiting for https://github.com/pmem/rpma/pull/1616 to be merged

___


<!-- Sent from Reviewable.io -->

2022-07-29 14:08 UTC, haichangsi reviewed
> Reviewed 1 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rcq_size.c` line 15 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N88tPsO5yk0BYUynuwz:-N88tPsPCrTEOi6DyMk2:b-9tmm98) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rcq_size.c#L15)):*
> ```C
> 
> /*
>  * thread -- get srq configured rcq size and check if its value is as expected
> ```

get the srq



_Code quote:_
```C
get srq 
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rq_size.c` line 15 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N89GskyAp7QbZv4KFTQ:-N89GskzA9R6h09VExpZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rq_size.c#L15)):*
> ```C
> 
> /*
>  * thread -- get srq configured rq size and check if its value is as expected
> ```

.



_Code quote:_
```C
get srq
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 18 at r5](https://reviewable.io/reviews/pmem/rpma/1958#-N88hQJT9KsZobYXFWXI:-N88hQJT9KsZobYXFWXJ:bvbs65w) ([raw file](https://github.com/pmem/rpma/blob/a3015f62db1f06cd87b66496f7aa01a893c6899a/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L18)):*
> ```C
> 
> /*
>  * init -- allocate state
> ```

allocate a state



_Code quote:_
```C
allocate state
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 48 at r5](https://reviewable.io/reviews/pmem/rpma/1958#-N88h1PK4V3Gxh9nojHd:-N88h1PL9TPXry93mMe7:bleszfh) ([raw file](https://github.com/pmem/rpma/blob/a3015f62db1f06cd87b66496f7aa01a893c6899a/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L48)):*
> ```C
> 
> /*
>  * fini -- free the srq configuration object and free the state
> ```

maybe 'free the srq configuration object and the state' ?



_Code quote:_
```C
free the srq configuration object and free the state
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c` line 17 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N88sxj13wcZghSiFbez:-N88sxj28x99_ognH1PL:b-bad7zm) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c#L17)):*
> ```C
> 
> /*
>  * thread -- set srq establishment rcq size and check if its value is as expected
> ```

set the rcq



_Code quote:_
```C
set srq
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rq_size.c` line 15 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N88t0dpDb4N6huGOSiu:-N88t0dpDb4N6huGOSiv:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rq_size.c#L15)):*
> ```C
> 
> /*
>  * thread -- set srq establishment rq size and check if its value is as expected
> ```

.



_Code quote:_
```C
set srq
```


<!-- Sent from Reviewable.io -->

2022-07-29 15:21 UTC, Patryk717 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958#-:-N89Y5BU370pg-5aOZJE:bdycpsm)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-07-29 16:56 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 61 of 66 files reviewed, 7 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rcq_size.c` line 15 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N88tPsO5yk0BYUynuwz:-N89reuqEN2-Z2IBWVF7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rcq_size.c#L15)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

get the srq
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rq_size.c` line 15 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N89GskyAp7QbZv4KFTQ:-N89rkd78FHj4wszQM-y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_get_rq_size.c#L15)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 18 at r5](https://reviewable.io/reviews/pmem/rpma/1958#-N88hQJT9KsZobYXFWXI:-N89rtuu9WmsRRNWdVWp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a3015f62db1f06cd87b66496f7aa01a893c6899a/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L18)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

allocate a state
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 48 at r5](https://reviewable.io/reviews/pmem/rpma/1958#-N88h1PK4V3Gxh9nojHd:-N89rzWUD-bX2A0niRKG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a3015f62db1f06cd87b66496f7aa01a893c6899a/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L48)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

maybe 'free the srq configuration object and the state' ?
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c` line 17 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N88sxj13wcZghSiFbez:-N89s4Pj4TF8aLX0lCp9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rcq_size.c#L17)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

set the rcq
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rq_size.c` line 15 at r6](https://reviewable.io/reviews/pmem/rpma/1958#-N88t0dpDb4N6huGOSiu:-N89s9JED6OD91n11ND8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/545c69ea109b99cbb3627308ab64247948ae8295/tests/multithreaded/srq_cfg/rpma_srq_cfg_set_rq_size.c#L15)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-01 06:13 UTC, ldorau reviewed
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-08-08 08:28 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`-- commits` line 28 at r7](https://reviewable.io/reviews/pmem/rpma/1958#-N8wZP-FC5YA4Ym87lYR):*
`test: add rpma_srq_cfg MT tests`



_Code quote:_
```
test: add srq_cfg MT tests
```


<!-- Sent from Reviewable.io -->

2022-08-08 12:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-N8xPNWq8DvqCU8135QY:-N8xPNWr30YstDpXqW_V:b-ujmq67) (no related file):*
Rebase please

___


<!-- Sent from Reviewable.io -->

2022-08-18 06:42 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-N8xPNWq8DvqCU8135QY:-N9jezUABRkMc1i67KMH:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___
___
*[`-- commits` line 28 at r7](https://reviewable.io/reviews/pmem/rpma/1958#-N8wZP-FC5YA4Ym87lYR):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`test: add rpma_srq_cfg MT tests`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 05:39 UTC, ldorau approved these changes
> Reviewed 54 of 54 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-22 07:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-NA3UnhD2sWxuYV4e2Mr:-NA3UnhD2sWxuYV4e2Ms:b-ujmq67) (no related file):*
Rebase please

___


<!-- Sent from Reviewable.io -->

2022-08-22 07:43 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: 64 of 66 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-NA3UnhD2sWxuYV4e2Mr:-NA3VVQOE4a0WkDjI3Ng:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-08-22 07:51 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-22 09:55 UTC, grom72 requested changes
> Reviewed 3 of 13 files at r5, 3 of 5 files at r7, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common.h` line 12 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3yXgaAnRxW4_2ypWZ:-NA3yXgaAnRxW4_2ypW_:undefined) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_common.h#L12)):*
> ```objc
> 
> /* the expected queue size */
> #define RPMA_SRQ_CFG_COMMON_Q_SIZE_EXP 20
> ```


___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 51 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3vmdiEQrou9XNeJ8N:-NA3vmdiEQrou9XNeJ8O:b-cur719) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L51)):*
> ```C
>  */
> static void
> fini(unsigned id, void *prestate, void **state_ptr, struct mtt_result *tr)
> ```

seq_fini



_Code quote:_
```C
fini
```
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 77 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3wAO6CrKg25y2xCp2:-NA3wAO6CrKg25y2xCp3:b45h) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L77)):*
> ```C
> 			init,
> 			thread,
> 			fini,
> ```





_Suggestion:_
```C
			NULL,
			seq_fini,
```


<!-- Sent from Reviewable.io -->

2022-08-22 09:56 UTC, grom72 reviewed
> Reviewed 2 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-08-22 10:02 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set_get.c` line 12 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3zzLhAaZZxwq63uZK:-NA3zzLhAaZZxwq63uZL:b-p9ibfe) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set_get.c#L12)):*
> ```C
> 
> int
> main(int argc, char *argv[])
> ```

can be moved to ``rpma_srq_cfg_common.c`` and ``rpma_srq_cfg_common_set_get.c`` can be removed from CMakeFiles.txt



_Code quote:_
```C
int
main(int argc, char *argv[])
```


<!-- Sent from Reviewable.io -->

2022-08-22 11:15 UTC, osalyk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common.h` line 12 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3yXgaAnRxW4_2ypWZ:-NA4FXkv3vy5iO9usnQy:bb76mu4) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_common.h#L12)):*
> ```objc
> 
> /* the expected queue size */
> #define RPMA_SRQ_CFG_COMMON_Q_SIZE_EXP 20
> ```

Why?
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set_get.c` line 12 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3zzLhAaZZxwq63uZK:-NA4Ei_E738RGQKGfrjG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_common_set_get.c#L12)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

can be moved to ``rpma_srq_cfg_common.c`` and ``rpma_srq_cfg_common_set_get.c`` can be removed from CMakeFiles.txt
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 51 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3vmdiEQrou9XNeJ8N:-NA4F1Br6xRA3NRQMcWs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L51)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

seq_fini
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c` line 77 at r9](https://reviewable.io/reviews/pmem/rpma/1958#-NA3wAO6CrKg25y2xCp2:-NA4F2-lBNu8lpiSp3zt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f6b847e537ed78205d5d2ee4e6adfd3045cb3bc/tests/multithreaded/srq_cfg/rpma_srq_cfg_new.c#L77)):*
> ```C
> 			init,
> 			thread,
> 			fini,
> ```

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 11:54 UTC, ldorau reviewed
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-22 11:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-NA4PNMnB8b_o5U9GYYd:-NA4PNMnB8b_o5U9GYYe:bbw5wqh) (no related file):*
Please restart the CircleCI build.

___


<!-- Sent from Reviewable.io -->

2022-08-22 12:14 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1958#-NA4PNMnB8b_o5U9GYYd:-NA4TMz74yiRsRG8KHHb:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please restart the CircleCI build.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-08-22 16:33 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958#-:-NA5OnLP4L8F82XX_oiD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-23 05:54 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1958)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-23 05:54 UTC, merged