common: Add package to Dockerfile
pmem/rpma pull request #1965
Opened 2022-08-02 06:17 UTC by Patryk717

2022-08-02 07:57 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-02 09:14 UTC, ldorau requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8SpPMI5940z4GO2RSc):*
common: add missing packages to Dockerfiles



_Code quote:_
```
common: Add package to Dockerfile
```


<!-- Sent from Reviewable.io -->

2022-08-02 10:03 UTC, ldorau requested changes
> Reviewed 16 of 17 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`utils/docker/images/Dockerfile.fedora-32` line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-EFREQiquNdXnW_f:-N8T-EFREQiquNdXnW_g:b-bgq80r) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.fedora-32#L43)):*
> ```
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel \
> 	libpmem2-devel \
> ```

`Error: Unable to find a match: libpmem2-devel`
https://github.com/ldorau/rpma/runs/7628324082?check_suite_focus=true



_Code quote:_
```
libpmem2-devel 
```
___
*[`utils/docker/images/Dockerfile.fedora-33` line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-I_OB0KWtzn7CXjQ:-N8T-I_OB0KWtzn7CXjR:b-bgq80r) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.fedora-33#L43)):*
> ```
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel \
> 	libpmem2-devel \
> ```

`Error: Unable to find a match: libpmem2-devel`
https://github.com/ldorau/rpma/runs/7628324082?check_suite_focus=true



_Code quote:_
```
libpmem2-devel
```
___
*[`utils/docker/images/Dockerfile.vzlinux-latest` line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-aF3009DW_6nve4U:-N8T-aF3009DW_6nve4V:b-gy73zu) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.vzlinux-latest#L50)):*
> ```
> # examples deps ('libprotobuf-c-dev' is required only for example 9)
> ENV EXAMPLES_DEPS "\
> 	libpmem-dev \
> ```

`Error: Unable to find a match: libpmem-dev libpmem2-dev libprotobuf-c-dev`
https://github.com/ldorau/rpma/runs/7628325005?check_suite_focus=true



_Code quote:_
```
	libpmem-dev \
	libpmem2-dev \
	libprotobuf-c-dev"
```
___
*[`utils/docker/images/Dockerfile.rockylinux-8.4` line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-R_X1L9Jq1bMWu-6:-N8T-R_X1L9Jq1bMWu-7:b80rz2i) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.rockylinux-8.4#L47)):*
> ```Roff
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel \
> 	libpmem2-devel \
> ```

`Error: Unable to find a match: libpmem2-devel libprotobuf-c-devel`
https://github.com/ldorau/rpma/runs/7628324880?check_suite_focus=true



_Code quote:_
```Roff
	libpmem2-devel \
	libprotobuf-c-devel"
```
___
*[`utils/docker/images/Dockerfile.ubuntu-20.04` line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T--tv5Ypm5BhzcitB:-N8T--tv5Ypm5BhzcitC:bj7fxf1) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.ubuntu-20.04#L49)):*
> ```
> ENV EXAMPLES_DEPS "\
> 	libpmem-dev \
> 	libpmem2-dev \
> ```

`E: Unable to locate package libpmem2-dev`
https://github.com/ldorau/rpma/runs/7628323844?check_suite_focus=true



_Code quote:_
```
libpmem2-dev \
```


<!-- Sent from Reviewable.io -->

2022-08-03 07:32 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: 12 of 17 files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8SpPMI5940z4GO2RSc):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

common: add missing packages to Dockerfiles
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.fedora-32` line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-EFREQiquNdXnW_f:-N8XaDXh-H0rvJavSHoD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.fedora-32#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Error: Unable to find a match: libpmem2-devel`
https://github.com/ldorau/rpma/runs/7628324082?check_suite_focus=true
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.fedora-33` line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-I_OB0KWtzn7CXjQ:-N8XaCiJ4b7ovz060ob6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.fedora-33#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Error: Unable to find a match: libpmem2-devel`
https://github.com/ldorau/rpma/runs/7628324082?check_suite_focus=true
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.vzlinux-latest` line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-aF3009DW_6nve4U:-N8XbH5v3MHc4DgbUae0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.vzlinux-latest#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Error: Unable to find a match: libpmem-dev libpmem2-dev libprotobuf-c-dev`
https://github.com/ldorau/rpma/runs/7628325005?check_suite_focus=true
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.rockylinux-8.4` line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T-R_X1L9Jq1bMWu-6:-N8Xaii54HWkZ4U9XEws:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.rockylinux-8.4#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Error: Unable to find a match: libpmem2-devel libprotobuf-c-devel`
https://github.com/ldorau/rpma/runs/7628324880?check_suite_focus=true
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-20.04` line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8T--tv5Ypm5BhzcitB:-N8XayCP1SoMe3Mn75f1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70fc96722caf93c5f6acfc31a4a5816165b34a51/utils/docker/images/Dockerfile.ubuntu-20.04#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`E: Unable to locate package libpmem2-dev`
https://github.com/ldorau/rpma/runs/7628323844?check_suite_focus=true
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 09:36 UTC, ldorau requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8SpPMI5940z4GO2RSc):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet:

Add -> add
Dockerfile -> Dockerfiles
___
*[`utils/docker/images/Dockerfile.fedora-32` line 42 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y2_c83lxf00Xxujx1:-N8Y2_c9-izfItl5Kgbm:b-3oejhw) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.fedora-32#L42)):*
> ```
> # examples deps ('protobuf-c-devel' is required only for example 9)
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel \
> ```

`libpmem` is installed within PMDK



_Code quote:_
```
libpmem-devel
```
___
*[`utils/docker/images/Dockerfile.fedora-32` line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Xwovk0Tl6p22ArpKa:-N8XwovlEfmrM9DiNA_k:b-halbcv) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.fedora-32#L43)):*
> ```
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel \
> 	Protobuf-c-devel"
> ```

`Error: Unable to find a match: Protobuf-c-devel`
see: https://github.com/ldorau/rpma/runs/7648435465?check_suite_focus=true



_Code quote:_
```
Protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.rockylinux-8.4` line 46 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y2qoV3Hz6DEEtWQyG:-N8Y2qoV3Hz6DEEtWQyH:b-3oejhw) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.rockylinux-8.4#L46)):*
> ```Roff
> # examples deps
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel"
> ```

`libpmem` is installed within PMDK



_Code quote:_
```Roff
libpmem-devel
```
___
*[`utils/docker/images/Dockerfile.ubuntu-20.04` line 48 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y2uL6B3PfKRZtPy9I:-N8Y2uL6B3PfKRZtPy9J:b-3oejhw) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.ubuntu-20.04#L48)):*
> ```
> # examples deps ('libprotobuf-c-dev' is required only for example 9)
> ENV EXAMPLES_DEPS "\
> 	libpmem-dev \
> ```

`libpmem` is installed within PMDK



_Code quote:_
```
libpmem-dev
```


<!-- Sent from Reviewable.io -->

2022-08-03 09:43 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-21.10` line 12 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y4YLM9qHQrZ91al-9:-N8Y4YLM9qHQrZ91al-A:b598fuy) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.ubuntu-21.10#L12)):*
> ```
> 
> # Pull base image
> FROM ubuntu:21.10
> ```

Ubuntu 21.10 is EOL, do not change this file



_Code quote:_
```
FROM ubuntu:21.10
```


<!-- Sent from Reviewable.io -->

2022-08-03 11:57 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1965#-N8YZMPaCnCIMABKifqn:-N8YZMPaCnCIMABKifqo:b-ujmq67) (no related file):*
Rebase please

___


<!-- Sent from Reviewable.io -->

2022-08-03 12:02 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: 14 of 17 files reviewed, 7 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1965#-N8SpPMI5940z4GO2RSc):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet:

Add -> add
Dockerfile -> Dockerfiles
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.fedora-32` line 42 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y2_c83lxf00Xxujx1:-N8YBwi3-Kz5kPXodPBV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.fedora-32#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libpmem` is installed within PMDK
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.rockylinux-8.4` line 46 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y2qoV3Hz6DEEtWQyG:-N8YC59u3JZABsBxxjVo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.rockylinux-8.4#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libpmem` is installed within PMDK
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-20.04` line 48 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y2uL6B3PfKRZtPy9I:-N8YCA8k9K1NlB37aCuy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.ubuntu-20.04#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libpmem` is installed within PMDK
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-21.10` line 12 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y4YLM9qHQrZ91al-9:-N8Y_Ena5XEC-23FYYHf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.ubuntu-21.10#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ubuntu 21.10 is EOL, do not change this file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-03 12:59 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-21.10` line 12 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y4YLM9qHQrZ91al-9:-N8YmMZe1QTPoPM9N166:bjbm23m) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.ubuntu-21.10#L12)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, it is still modified.


<!-- Sent from Reviewable.io -->

2022-08-04 11:53 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1965#-N8YZMPaCnCIMABKifqn:-N8ch4cc3CC0x3d59v4U:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___
___
*[`utils/docker/images/Dockerfile.fedora-32` line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Xwovk0Tl6p22ArpKa:-N8cgTvG4gZJHDyYzYa-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.fedora-32#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Error: Unable to find a match: Protobuf-c-devel`
see: https://github.com/ldorau/rpma/runs/7648435465?check_suite_focus=true
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-21.10` line 12 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Y4YLM9qHQrZ91al-9:-N8_4zWB3iErEaOd56bi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.ubuntu-21.10#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, it is still modified.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-04 11:58 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @Patryk717)

___
*[`utils/docker/images/Dockerfile.fedora-32` line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1965#-N8Xwovk0Tl6p22ArpKa:-N8ciDdB-vhex1NpGzK5:br7sr4m) ([raw file](https://github.com/pmem/rpma/blob/88a9163362f087ffaf3d1cf42d89c5a55c997416/utils/docker/images/Dockerfile.fedora-32#L43)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet


<!-- Sent from Reviewable.io -->

2022-08-04 12:04 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-04 13:50 UTC, ldorau approved these changes
It builds correctly now: https://github.com/ldorau/rpma/actions/runs/2796475345

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965#-:-N8d6kpp1U24RLw9rEpT:b21ccfu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-05 08:11 UTC, haichangsi reviewed
> Reviewed 10 of 17 files at r1, 1 of 1 files at r2, 2 of 5 files at r3, 2 of 3 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[`utils/docker/images/Dockerfile.centos-7` line 42 at r6](https://reviewable.io/reviews/pmem/rpma/1965#-N8h1gUfEfpLtIyARH6I:-N8h1gUg86pdOoMdKFxt:bnrabqw) ([raw file](https://github.com/pmem/rpma/blob/4c2d2cf547c9f8a20b3cab31fa4e0a0767d3e8de/utils/docker/images/Dockerfile.centos-7#L42)):*
> ```
> 	rdma-core-devel"
> 
> # examples deps ('protobuf-c-devel' is required only for example 9)
> ```

and 9s if it matters 



_Code quote:_
```
for example 9
```


<!-- Sent from Reviewable.io -->

2022-08-05 08:38 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`utils/docker/images/Dockerfile.centos-7` line 42 at r6](https://reviewable.io/reviews/pmem/rpma/1965#-N8h1gUfEfpLtIyARH6I:-N8h8vVh54KtV4dDh8GD:b-u4su1b) ([raw file](https://github.com/pmem/rpma/blob/4c2d2cf547c9f8a20b3cab31fa4e0a0767d3e8de/utils/docker/images/Dockerfile.centos-7#L42)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

and 9s if it matters 
</blockquote></details>

`for examples 9 and 9s`



_Code quote:_
```
for example 9
```


<!-- Sent from Reviewable.io -->

2022-08-05 09:46 UTC, ldorau requested changes
> Reviewed 15 of 15 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 11 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`utils/docker/images/Dockerfile.debian-10` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hNsKI4wGF97OeosLR:-N8hNsKI4wGF97OeosLS:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-10#L46)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.debian-11` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hO0H30lao8JFWQQhY:-N8hO0H30lao8JFWQQhZ:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-11#L46)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
'protobuf-c-devel'
```
___
*[`utils/docker/images/Dockerfile.debian-experimental` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hO4Rx4tWd9lyv6h6z:-N8hO4Rx4tWd9lyv6h7-:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-experimental#L43)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.debian-stable` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hO6Sw3yPgxMunAb3S:-N8hO6Sw3yPgxMunAb3T:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-stable#L46)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.debian-testing` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOAnz4dXGVAwXYxRw:-N8hOAnz4dXGVAwXYxRx:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-testing#L43)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.opensuse-leap-latest` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOK7ZBfWNwtA-VCUY:-N8hOK7_DzVNfCtoRxX_:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.opensuse-leap-latest#L43)):*
> ```
> 	rdma-core-devel"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.opensuse-tumbleweed-latest` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOMPv9UCXeaW-SK-5:-N8hOMPv9UCXeaW-SK-6:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L43)):*
> ```
> 	rdma-core-devel"
> 	
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.ubuntu-rolling` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOOVf1ODPE1hFOGXD:-N8hOOVf1ODPE1hFOGXE:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.ubuntu-rolling#L46)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.ubuntu-20.04` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hLz-1BiU9P99sYuqT:-N8hLz-220AEagJGRO2i:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.ubuntu-20.04#L46)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 49 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hM1D603XTUDDCrqEm:-N8hM1D603XTUDDCrqEn:bk06ze5) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.ubuntu-22.04#L49)):*
> ```
> 	pandoc"
> 
> # examples deps ('protobuf-c-devel' is required only for examples 9 and 9s)
> ```

`libprotobuf-c-dev`



_Code quote:_
```
protobuf-c-devel
```


<!-- Sent from Reviewable.io -->

2022-08-05 10:02 UTC, Patryk717 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: 9 of 19 files reviewed, 11 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`utils/docker/images/Dockerfile.centos-7` line 42 at r6](https://reviewable.io/reviews/pmem/rpma/1965#-N8h1gUfEfpLtIyARH6I:-N8hRiPv76x9s17VjAut:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4c2d2cf547c9f8a20b3cab31fa4e0a0767d3e8de/utils/docker/images/Dockerfile.centos-7#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`for examples 9 and 9s`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.debian-10` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hNsKI4wGF97OeosLR:-N8hRivX8jvTi3fYam8z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-10#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.debian-11` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hO0H30lao8JFWQQhY:-N8hRkX4EEZxD6gZCB8L:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-11#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.debian-experimental` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hO4Rx4tWd9lyv6h6z:-N8hRl5tBZH7w0PXmFPe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-experimental#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.debian-stable` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hO6Sw3yPgxMunAb3S:-N8hRlcZ5n0JYBS1Pjjd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-stable#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.debian-testing` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOAnz4dXGVAwXYxRw:-N8hRmO58iniVH5nsYTK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.debian-testing#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.opensuse-leap-latest` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOK7ZBfWNwtA-VCUY:-N8hS5Hr9IBl6T35mbXO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.opensuse-leap-latest#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.opensuse-tumbleweed-latest` line 43 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOMPv9UCXeaW-SK-5:-N8hS7BQ1BdwdjD7ZCBo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-rolling` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hOOVf1ODPE1hFOGXD:-N8hS7ia2K4W9RX55o2r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.ubuntu-rolling#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-20.04` line 46 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hLz-1BiU9P99sYuqT:-N8hRgjI6YEPpdgKsdaR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.ubuntu-20.04#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 49 at r7](https://reviewable.io/reviews/pmem/rpma/1965#-N8hM1D603XTUDDCrqEm:-N8hRhF-EfhkSyxR0SSS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4f0dd6de56c32b92551489d22d2886c1790ef32/utils/docker/images/Dockerfile.ubuntu-22.04#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`libprotobuf-c-dev`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-05 10:05 UTC, ldorau approved these changes
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-08-05 10:18 UTC, haichangsi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 15 files at r7, 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965#-:-N8hVoSW8fXyWOWk0n7W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-05 10:18 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-05 10:19 UTC, merged

2022-08-05 10:23 UTC, ldorau commented
It works: https://github.com/ldorau/rpma/actions/runs/2802850286