examples: add example08s - simple-messages-ping-pong-with-srq
pmem/rpma pull request #1981
Opened 2022-08-10 11:33 UTC by haichangsi

2022-08-10 11:44 UTC, ldorau requested changes
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96YfzK04kVTJpe1CU7):*
I would call this example `08srq-simple-messages-ping-pong-with-srq`, because `s` is used for shared completion channel, so it would be:

`example: add 08srq-simple-messages-ping-pong-with-srq example`



_Code quote:_
```
examples: add example08s - simple-messages-ping-pong-with-srq
```
___
*[`examples/CMakeLists.txt` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96Z8WrBrObKwNqZfcf:-N96Z8Ws2BC4bT_kkDIc:b-9exg3c) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/CMakeLists.txt#L148)):*
> ```CMake
> add_example(NAME 08-messages-ping-pong BIN client
> 	SRCS 08-messages-ping-pong/client.c common/common-messages-ping-pong.c common/common-utils.c)
> add_example(NAME 08s-simple-messages-ping-pong-with-srq BIN server
> ```

I would call this example `08srq-simple-messages-ping-pong-with-srq`, because `s` is used for shared completion channel.



_Code quote:_
```CMake
08s-simple-messages-ping-pong-with-srq
```
___
*[`examples/CMakeLists.txt` line 150 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZBTWBubGmWGLCK-r:-N96ZBTWBubGmWGLCK-s:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/CMakeLists.txt#L150)):*
> ```CMake
> add_example(NAME 08s-simple-messages-ping-pong-with-srq BIN server
> 	SRCS 08s-simple-messages-ping-pong-with-srq/server.c common/common-messages-ping-pong.c)
> add_example(NAME 08s-simple-messages-ping-pong-with-srq BIN client
> ```

.



_Code quote:_
```CMake
08s-simple-messages-ping-pong-with-srq
```
___
*[`examples/run-all-examples.sh` line 284 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZGB_0yxKFXLiFFP4:-N96ZGB_0yxKFXLiFFP5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/run-all-examples.sh#L284)):*
> ```Shell
> 		start_client $VLD_CCMD $DIR/client $IP_ADDRESS $PORT $WORDS
> 		;;
> 	08-messages-ping-pong|08s-simple-messages-ping-pong-with-srq)
> ```

.



_Code quote:_
```Shell
08s-simple-messages-ping-pong-with-srq
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZS-X3ekSfgLDH9ho:-N96ZS-X3ekSfgLDH9hp:b-4zblrm) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/CMakeLists.txt#L46)):*
> ```CMake
> 
> add_example(server server.c ../common/common-conn.c ../common/common-messages-ping-pong.c)
> add_example(client client.c ../common/common-conn.c ../common/common-messages-ping-pong.c ../common/common-utils.c ../common/common-utils.c)
> ```

doubled



_Code quote:_
```CMake
../common/common-utils.c ../common/common-utils.c
```


<!-- Sent from Reviewable.io -->

2022-08-10 11:45 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96Zlhn0fsb_7pFEutY:-N96Zlhn0fsb_7pFEutZ:bj2juu6) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L21)):*
> ```C
> #include "common-epoll.h"
> 
> #define USAGE_STR "usage: %s <server_address> <port> [<timeout>]\n"
> ```

Is it used?



_Code quote:_
```C
 [<timeout>]
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZbLpAcot7s4BNozm:-N96ZbLpAcot7s4BNozn:b-g2d1qe) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L23)):*
> ```C
> #define USAGE_STR "usage: %s <server_address> <port> [<timeout>]\n"
> 
> static int num_clients = 1;
> ```

Not needed - there will be always only 1 client.



_Code quote:_
```C
static int num_clients = 1;
```


<!-- Sent from Reviewable.io -->

2022-08-10 12:32 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: 5 of 8 files reviewed, 16 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96dEQK5cuzZY1Irq-G:-N96dEQK5cuzZY1Irq-H:b-5hpbpa) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L45)):*
> ```C
> 	/* prepare memory */
> 	struct rpma_mr_local *recv_mr, *send_mr;
> 	size_t size = MSG_SIZE;
> ```

`size` is not needed, use `MSG_SIZE` instead.



_Code quote:_
```C
size_t size = MSG_SIZE;
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96dZpn2PaUEWjcwHaM:-N96dZpn2PaUEWjcwHaN:bezhr1h) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L65)):*
> ```C
> 	int num_got = 0;
> 	uint32_t qp_num;
> 	struct ibv_wc wc[MAX_N_WC];
> ```

Why is it of size `MAX_N_WC`?



_Code quote:_
```C
MAX_N_WC
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 113 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96dy1U5wcN-VQdTFXA:-N96dy1U5wcN-VQdTFXB:bt3z5ab) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L113)):*
> ```C
> 		goto err_conn_disconnect;
> 
> 	/* get the receive CQ of rpma_srq object */
> ```

`of the rpma_srq object`



_Code quote:_
```C
of rpma_srq object
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96e41r7gS_2SdFCMk2:-N96e41r7gS_2SdFCMk3:bjla6jo) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L118)):*
> ```C
> 
> 
> 	/* IBV_WC_SEND completion in the first round is not present */
> ```

When is it present?



_Code quote:_
```C
/* IBV_WC_SEND completion in the first round is not present */
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 119 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96eZWK-91eOBd-pwZg:-N96eZWK-91eOBd-pwZh:b-e4x91g) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L119)):*
> ```C
> 
> 	/* IBV_WC_SEND completion in the first round is not present */
> 	int send_cmpl = 1;
> ```

Why is it initialized to `1` ? Is it needed in this place?



_Code quote:_
```C
int send_cmpl = 1;
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 124 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96gWg-7V-OPugKYjT8:-N96gWg-7V-OPugKYjT9:b-m6zxhf) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L124)):*
> ```C
> 	while (1) {
> 		do {
> 			/* wait for the completion to be ready */
> ```

`the receive completion`



_Code quote:_
```C
the completion
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96gjLi0sTwE215FeWN:-N96gjLi0sTwE215FeWO:b-le6nql) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L138)):*
> ```C
> 
> 			/* validate received completions */
> 			for (int i = 0; i < num_got; i++) {
> ```

You expect only one completion, so the `for` loop is not needed.



_Code quote:_
```C
			/* validate received completions */
			for (int i = 0; i < num_got; i++) {
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 146 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96gv9JByxwI9fY-7BD:-N96gv9JByxwI9fY-7BE:bb0ml8d) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L146)):*
> ```C
> 		} while (recv_cmpl == 0);
> 
> 			if (*recv == I_M_DONE)
> ```

Wrong indentation.



_Code quote:_
```C
			if (*recv == I_M_DONE)
				break;

			if (qp_num != wc->qp_num) {
				ret = -1;
				(void) printf("qp_num (%" PRIu32 ") != wc->qp_num (%" PRIu32 ")",
					qp_num, wc->qp_num);
				break;
			}

			/* print the received old value of the client's counter */
			(void) printf("Value received: %" PRIu64 "\n", *recv);

			*send = *recv + 1;

			/* prepare a receive for the client's request */
			if ((ret = rpma_srq_recv(srq, recv_mr, 0, MSG_SIZE, recv)))
				break;

			/* send the new value to the client */
			(void) printf("Value sent: %" PRIu64 "\n", *send);

			/* send a message to the client */
			if ((ret = rpma_send(conn, send_mr, 0, MSG_SIZE,
					RPMA_F_COMPLETION_ON_ERROR, NULL)))
				break;
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 151 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96h47CBshmDt29vQN4:-N96h47CBshmDt29vQN5:b-8smp4b) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L151)):*
> ```C
> 			if (qp_num != wc->qp_num) {
> 				ret = -1;
> 				(void) printf("qp_num (%" PRIu32 ") != wc->qp_num (%" PRIu32 ")",
> ```

`(void) fprintf(stderr, "`



_Code quote:_
```C
(void) printf("
```


<!-- Sent from Reviewable.io -->

2022-08-10 12:32 UTC, ldorau reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: 6 of 8 files reviewed, 16 unresolved discussions (waiting on @haichangsi and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-10 12:40 UTC, ldorau requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: 7 of 8 files reviewed, 18 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08s-simple-messages-ping-pong-with-srq/README.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96kzKy4vyVSSBkcZ_6:-N96kzKy4vyVSSBkcZ_7:bf8mzp6) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/README.md#L8)):*
> ```Markdown
> When a new connection request appears it is accepted. The client sends to
> the server its current counter value. When the server receives the message
> from the client, its content is incremented and send back to the client. When
> ```

An info about SRQ is missing .
What is a difference between 08 and 08srq examples?



_Code quote:_
```Markdown
The messages ping pong example implements two parts of the messaging process:
- The server starts a listening endpoint and waits for an incoming connection.
When a new connection request appears it is accepted. The client sends to
the server its current counter value. When the server receives the message
from the client, its content is incremented and send back to the client. When
the server receives the I_M_DONE message it waits for disconnection.
- The client connects to the server and sends to it its current counter value.
When the client gets the new value from the server it repeats the process
for the configured number of rounds. When it is quitting, it send the I_M_DONE
message and disconnects.
```


<!-- Sent from Reviewable.io -->

2022-08-10 12:41 UTC, ldorau reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 18 unresolved discussions (waiting on @haichangsi and @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-10 13:12 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 20 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 126 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96sP6N6l7Ri0AZW7nc:-N96sP6N6l7Ri0AZW7nd:b-byb9gd) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L126)):*
> ```C
> 			/* wait for the completion to be ready */
> 			if ((ret = rpma_cq_wait(rcq)))
> 				break;
> ```

It is an error, `break` is not enough here.



_Code quote:_
```C
break;
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 135 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96sU_o5-KLp4nSe37a:-N96sU_o5-KLp4nSe37b:b-byb9gd) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L135)):*
> ```C
> 				/* lack of completion is not an error */
> 				if (ret != RPMA_E_NO_COMPLETION)
> 					break;
> ```

It is an error, `break` is not enough here.



_Code quote:_
```C
break;
```


<!-- Sent from Reviewable.io -->

2022-08-10 13:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 19 unresolved discussions (waiting on @haichangsi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1981#-N96jmGS0gQwTmKVQ9Qf:-N96uz_g-A2ZPNQMKezc:br3p7r7) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The integration tests fail:
https://app.circleci.com/pipelines/github/ldorau/rpma/4930/workflows/253627cb-5e96-4799-8b22-0c5352aec3d7/jobs/5029

</blockquote></details>

It will probably pass when you fix all other issues.

___


<!-- Sent from Reviewable.io -->

2022-08-10 14:49 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 19 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96YfzK04kVTJpe1CU7):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I would call this example `08srq-simple-messages-ping-pong-with-srq`, because `s` is used for shared completion channel, so it would be:

`example: add 08srq-simple-messages-ping-pong-with-srq example`
</blockquote></details>

Done.
___
*[`examples/CMakeLists.txt` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96Z8WrBrObKwNqZfcf:-N96wrGmDkOJmVHFRpgk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/CMakeLists.txt#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I would call this example `08srq-simple-messages-ping-pong-with-srq`, because `s` is used for shared completion channel.
</blockquote></details>

Done.
___
*[`examples/CMakeLists.txt` line 150 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZBTWBubGmWGLCK-r:-N96wrgB99kEssTt3NyT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/CMakeLists.txt#L150)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 284 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZGB_0yxKFXLiFFP4:-N96wsPjC7iAxMUvp5U2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/run-all-examples.sh#L284)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZS-X3ekSfgLDH9ho:-N96wxIF-7BDm0C6UVLi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/CMakeLists.txt#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

doubled
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/README.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96kzKy4vyVSSBkcZ_6:-N974kTm8feXea44BTs2:b-jhqrit) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/README.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

An info about SRQ is missing .
What is a difference between 08 and 08srq examples?
</blockquote></details>

I mentioned it the same way as it is in the exmaple13. Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96Zlhn0fsb_7pFEutY:-N973b_K0Y_vxc6oxFWy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Is it used?
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96ZbLpAcot7s4BNozm:-N973thu3af0iycPeY9r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed - there will be always only 1 client.
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96dEQK5cuzZY1Irq-G:-N96xOo85xyKeZ_lWDZN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`size` is not needed, use `MSG_SIZE` instead.
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96dZpn2PaUEWjcwHaM:-N96xyqT5ZtPS7amLtP2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why is it of size `MAX_N_WC`?
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 113 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96dy1U5wcN-VQdTFXA:-N96xZ0kEqQ3ORLJcJuE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`of the rpma_srq object`
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96e41r7gS_2SdFCMk2:-N972NOzAnKOjsmCpVOr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L118)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

When is it present?
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 119 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96eZWK-91eOBd-pwZg:-N972Nbb68Q4rQ60-1rR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why is it initialized to `1` ? Is it needed in this place?
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 124 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96gWg-7V-OPugKYjT8:-N972TUT6FEhq_SwYAiJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the receive completion`
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 126 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96sP6N6l7Ri0AZW7nc:-N972_XvAkM3y0eYJO-T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is an error, `break` is not enough here.
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 135 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96sU_o5-KLp4nSe37a:-N972cy121KvUGmtow2W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/server.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is an error, `break` is not enough here.
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/server.c` line 138 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96gjLi0sTwE215FeWN:-N972eLC0v0Ge6_xs8P4:b-896fix) ([raw file](https://github.com/pmem/rpma/b [...]

2022-08-11 07:04 UTC, ldorau requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96YfzK04kVTJpe1CU7):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.

`example: add 08srq-simple-messages-ping-pong-with-srq example`
___
*[`CHANGELOG.md` line 34 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9Admg0-47-LRFpCbWF:-N9Admg0-47-LRFpCbWG:b-pb2qq2) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/CHANGELOG.md#L34)):*
> ```Markdown
> - examples:
>   - 13-messages-ping-pong-with-srq - a multi-connection example for shared RQ with ping-pong messages
>   - 08srq-simple-messages-ping-pong-with-srq - a single-connection example for shared RQ with ping-pong messages
> ```

one line above - before example 13



_Code quote:_
```Markdown
  - 08srq-simple-messages-ping-pong-with-srq - a single-connection example for shared RQ with ping-pong messages
```
___
*[`examples/08s-simple-messages-ping-pong-with-srq/README.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96kzKy4vyVSSBkcZ_6:-N9AeSskEwkbpYEmcrzr:bl58yla) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/README.md#L8)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I mentioned it the same way as it is in the exmaple13. Done.
</blockquote></details>

You should mention it is a single-connection example.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AeQ4dC4hv8HYXYd0S:-N9AeQ4dC4hv8HYXYd0T:b-2oyv64) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L9)):*
> ```Markdown
> the server its current counter value. When the server receives the message
> from the client, its content is incremented and send back to the client. When
> the server receives the I_M_DONE message it it disconnects.
> ```

one `it`



_Code quote:_
```Markdown
it it
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AfhaI7Sm4WLWUmSl6:-N9AfhaI7Sm4WLWUmSl7:b3gcs1y) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L131)):*
> ```C
> 					goto err_conn_disconnect;
> 
> 			/* the IBV_WC_SEND completion is never present */
> ```

`the IBV_WC_SEND completion can be received only in case of an error`



_Code quote:_
```C
the IBV_WC_SEND completion is never present
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AhRvl5u6Fa4rtfBx4:-N9AhRvl5u6Fa4rtfBx5:b-kqeifi) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L135)):*
> ```C
> 
> 			/* validate the received completion */
> 			ret = validate_wc(&wc, recv, &send_cmpl, &recv_cmpl);
> ```

What if `num_got ==  0`? 



_Code quote:_
```C
ret = validate_wc(&wc, recv, &send_cmpl, &recv_cmpl);
```


<!-- Sent from Reviewable.io -->

2022-08-11 07:32 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AfhaI7Sm4WLWUmSl6:-N9AoOGcDBFKiY9b71wg:bijjvsp) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the IBV_WC_SEND completion can be received only in case of an error`
</blockquote></details>

`the IBV_WC_SEND completion can be received only in case of a failure of rpma_send()`


<!-- Sent from Reviewable.io -->

2022-08-11 07:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AfhaI7Sm4WLWUmSl6:-N9ApNOaEyCNs-lTwYS_:bl35e4v) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the IBV_WC_SEND completion can be received only in case of a failure of rpma_send()`
</blockquote></details>

```c
int send_cmpl; /* not used */
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AhRvl5u6Fa4rtfBx4:-N9ApX3g8-swCYkXxhT9:b4uy5p5) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What if `num_got ==  0`? 
</blockquote></details>

```c
if (num_got) {
	/* validate the received completion */
	int send_cmpl; /* not used */
	ret = validate_wc(&wc, recv, &send_cmpl, &recv_cmpl);
	if (ret)
		goto err_conn_disconnect;
}

```


<!-- Sent from Reviewable.io -->

2022-08-11 07:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 165 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9Aq1Nu1i9S2n3MYhyB:-N9Aq1Nu1i9S2n3MYhyC:bevs79q) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L165)):*
> ```C
> 
> 		/* send a message to the client */
> 		if ((ret = rpma_send(conn, send_mr, 0, MSG_SIZE,
> ```

```c
		ret = rpma_send(conn, send_mr, 0, MSG_SIZE, RPMA_F_COMPLETION_ON_ERROR, NULL);
		if (ret)
			break;
```
looks better - it fits into one line.



_Code quote:_
```C
		if ((ret = rpma_send(conn, send_mr, 0, MSG_SIZE,
				RPMA_F_COMPLETION_ON_ERROR, NULL)))
			break;
```


<!-- Sent from Reviewable.io -->

2022-08-11 07:52 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 147 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9Asj5Y1ZE75xjDhjp5:-N9Asj5Y1ZE75xjDhjp6:b-k8qvlu) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L147)):*
> ```C
> 		if (qp_num != wc.qp_num) {
> 			ret = -1;
> 			(void) fprintf(stderr, "qp_num (%" PRIu32 ") != wc->qp_num (%" PRIu32 ")",
> ```

```c
	(void) fprintf(stderr,
		"Error: number of QP (qp_num) in the received completion "
		"(%" PRIu32 ") differs from the one of the connection "
		"(%" PRIu32 ")\n",
		wc.qp_num, qp_num);
```

is more clear.



_Code quote:_
```C
			(void) fprintf(stderr, "qp_num (%" PRIu32 ") != wc->qp_num (%" PRIu32 ")",
				qp_num, wc.qp_num);
```


<!-- Sent from Reviewable.io -->

2022-08-11 08:46 UTC, haichangsi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96YfzK04kVTJpe1CU7):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.

`example: add 08srq-simple-messages-ping-pong-with-srq example`
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 34 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9Admg0-47-LRFpCbWF:-N9B-93c5EAwwgZ_FqJi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/CHANGELOG.md#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one line above - before example 13
</blockquote></details>

Done.
___
*[`examples/08s-simple-messages-ping-pong-with-srq/README.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1981#-N96kzKy4vyVSSBkcZ_6:-N9B1nox01KuHc_voTuf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/788684b68f08f12b809da986572bb718087bfe9b/examples/08s-simple-messages-ping-pong-with-srq/README.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You should mention it is a single-connection example.
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AeQ4dC4hv8HYXYd0S:-N9B1teC0zjkDlIX5Cpp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one `it`
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AfhaI7Sm4WLWUmSl6:-N9B2mtN7coHcfFiabRO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
int send_cmpl; /* not used */
```

</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 135 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9AhRvl5u6Fa4rtfBx4:-N9B3ZCJEDJW4GWIiz77:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
if (num_got) {
	/* validate the received completion */
	int send_cmpl; /* not used */
	ret = validate_wc(&wc, recv, &send_cmpl, &recv_cmpl);
	if (ret)
		goto err_conn_disconnect;
}

```
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 147 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9Asj5Y1ZE75xjDhjp5:-N9B3nxi4Uvdpo-YFtz0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L147)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
	(void) fprintf(stderr,
		"Error: number of QP (qp_num) in the received completion "
		"(%" PRIu32 ") differs from the one of the connection "
		"(%" PRIu32 ")\n",
		wc.qp_num, qp_num);
```

is more clear.
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 165 at r2](https://reviewable.io/reviews/pmem/rpma/1981#-N9Aq1Nu1i9S2n3MYhyB:-N9B400X3WzzCY9JUmdv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/567ab40a2649c2e9609f72edf40d2f71e8e9cdaf/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L165)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
		ret = rpma_send(conn, send_mr, 0, MSG_SIZE, RPMA_F_COMPLETION_ON_ERROR, NULL);
		if (ret)
			break;
```
looks better - it fits into one line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-11 08:48 UTC, ldorau approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-11 09:06 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1981#-N96jmGS0gQwTmKVQ9Qf:-N9B8n271Ta-adcrPMk6:b-3wvic9) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It will probably pass when you fix all other issues.
</blockquote></details>

The integration tests pass now:
https://app.circleci.com/pipelines/github/ldorau/rpma/4943/workflows/ef1eb7b2-2e65-4daf-9c71-ba9632899c0f/jobs/5042

___


<!-- Sent from Reviewable.io -->

2022-08-11 09:06 UTC, ldorau approved these changes
The integration tests pass:
https://app.circleci.com/pipelines/github/ldorau/rpma/4943/workflows/ef1eb7b2-2e65-4daf-9c71-ba9632899c0f/jobs/5042

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981#-:-N9B8wjoApaBGrPKfWvD:bjvqvrx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-11 09:06 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1981#-:-N9B8zUK3TLJxZc4c82_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)



<!-- Sent from Reviewable.io -->

2022-08-11 09:07 UTC, merged