examples: expand 08srq-simple-messages-ping-pong-with-srq
pmem/rpma pull request #1985
Opened 2022-08-15 09:00 UTC by yangx-jy

expand 08srq-simple-messages-ping-pong-with-srq so that it can
get receive completions by one of the following CQs:
- the main CQ of the rpma_conn object
- the separate receive CQ of the rpma_conn object
- the separate receive CQ of the rpma_srq object

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

2022-08-22 05:35 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-08-22 07:03 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-08-22 10:56 UTC, grom72 requested changes
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4AwvNAqIegxM2039E:-NA4AwvNAqIegxM2039F:bmkxkcv) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L21)):*
> ```C
> #include "common-utils.h"
> 
> #define USAGE_STR	"usage: %s <server_address> <port> <separate_receive_CQ>\n"
> ```

My proposal is to keep (for simplicity) this parameter optional



_Suggestion:_
```C
[<separate_receive_CQ>]
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4B8feBEE-8gPYl1RH:-NA4B8feBEE-8gPYl1RI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L28)):*
> ```C
> {
> 	/* validate parameters */
> 	if (argc < 4) {
> ```

.



_Suggestion:_
```C
3
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4BBIR3jfcDAKrM8Iz:-NA4BBIR3jfcDAKrM8J-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L42)):*
> ```C
> 	int ret;
> 
> 	/* validate the separate_receive_CQ parameter */
> ```

.



_Suggestion:_
```C
	/* validate the separate_receive_CQ parameter */
	uint64_t separate_receive_CQ = 0;
	if (argc > 3)
		separate_receive_CQ = strtoul_noerror(argv[3])
	if (separate_receive_CQ < 0 || separate_receive_CQ > 2) {
		(void) fprintf(stderr,
				"<separate_receive_CQ> should be one of 0, 1 and 2 (%s given)\n",
				argv[3]);
		return -1;
	}
```


<!-- Sent from Reviewable.io -->

2022-08-22 10:56 UTC, grom72 reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-22 10:57 UTC, grom72 requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4Bhwg-h9rTYKyV78W:-NA4Bhwg-h9rTYKyV78X:bmkxkcv) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L18)):*
> ```Markdown
> 
> ```bash
> [user@server]$ ./server $server_address $port $separate_receive_CQ
> ```

My proposal is to keep (for simplicity) this parameter optional



_Suggestion:_
```Markdown
[user@server]$ ./server $server_address $port [$separate_receive_CQ]
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4Bo0F0-anutQLClcA:-NA4Bo0F0-anutQLClcB:undefined) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L21)):*
> ```Markdown
> ```
> **Note** The following values of separate_receive_CQ are available:
> - 0 - got receive completions by the main CQ of rpma_conn object
> ```





_Suggestion:_
```Markdown
- 0 (or missing) - got receive completions by the main CQ of rpma_conn object
```


<!-- Sent from Reviewable.io -->

2022-08-22 10:58 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1985#-NA4C0gY3d-rq_v51X3I:-NA4C0gY3d-rq_v51X3J:b-bprarg) (no related file):*
@ldorau Shall we somehow extend integration tests?

___


<!-- Sent from Reviewable.io -->

2022-08-22 11:55 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1985#-NA4C0gY3d-rq_v51X3I:-NA4P-Lv2lEdxsv0x8Ve:b32w12) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau Shall we somehow extend integration tests?
</blockquote></details>

No

___


<!-- Sent from Reviewable.io -->

2022-08-22 13:39 UTC, ldorau requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4lSKi2tqgkiF_Ld6w:-NA4lSKi2tqgkiF_Ld6x:b2ni3ap) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L21)):*
> ```Markdown
> ```
> **Note** The following values of separate_receive_CQ are available:
> - 0 - got receive completions by the main CQ of rpma_conn object
> ```

get



_Code quote:_
```Markdown
got
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4lU6O5QbR1xNzKkqY:-NA4lU6O5QbR1xNzKkqZ:b2ni3ap) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L22)):*
> ```Markdown
> **Note** The following values of separate_receive_CQ are available:
> - 0 - got receive completions by the main CQ of rpma_conn object
> - 1 - got receive completions by the separate receive CQ of rpma_conn object
> ```

get



_Code quote:_
```Markdown
got
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4lVXP8UP_wafHcGhp:-NA4lVXP8UP_wafHcGhq:b2ni3ap) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L23)):*
> ```Markdown
> - 0 - got receive completions by the main CQ of rpma_conn object
> - 1 - got receive completions by the separate receive CQ of rpma_conn object
> - 2 - got receive completions by the separate receive CQ of rpma_srq object
> ```

get



_Code quote:_
```Markdown
got
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4loZt5DTmVMlrGapG:-NA4loZt5DTmVMlrGapH:b32wtk) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L46)):*
> ```C
> 	if (separate_receive_CQ < 0 || separate_receive_CQ > 2) {
> 		(void) fprintf(stderr,
> 				"<separate_receive_CQ> should be one of 0, 1 and 2 (%s given)\n",
> ```

or



_Code quote:_
```C
and
```


<!-- Sent from Reviewable.io -->

2022-08-22 14:00 UTC, ldorau reviewed
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-22 16:30 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA5Mk4TDitNrKyAEcgq:-NA5Mk4TDitNrKyAEcgr:b5rmk0t) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L21)):*
> ```C
> #include "common-utils.h"
> 
> #define USAGE_STR	"usage: %s <server_address> <port> <separate_receive_CQ>\n"
> ```

we should change the logic of the last parameter:
- by default, we should use the most straightforward (simple) path with the default configuration - we do not need any parameter for that (just the original execution path from the original 08_srq example
- next, we should be able to use a separate receive completion queue - ``r``
- finally, we should be able to use the main connection CQ - ``m``



_Suggestion:_
```C
[m|r]
```


<!-- Sent from Reviewable.io -->

2022-08-23 03:34 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4lSKi2tqgkiF_Ld6w:-NA7k65b7BFXxOpieilq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4lU6O5QbR1xNzKkqY:-NA7k6PI7W7Bjtf0QYKo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4lVXP8UP_wafHcGhp:-NA7k6ebBlPvMPvo_IKf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA5Mk4TDitNrKyAEcgq:-NA7k95D49srkSitoxxz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we should change the logic of the last parameter:
- by default, we should use the most straightforward (simple) path with the default configuration - we do not need any parameter for that (just the original execution path from the original 08_srq example
- next, we should be able to use a separate receive completion queue - ``r``
- finally, we should be able to use the main connection CQ - ``m``
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1985#-NA4loZt5DTmVMlrGapG:-NA7kDXaEfd_h1MTc9NO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e036c511adef8b9c201fc42c9632c96a075689b/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 05:20 UTC, grom72 approved these changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-08-23 06:09 UTC, ldorau reviewed
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-23 06:13 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 89 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8GjR8-mIsx7fEICTR:-NA8GjR8-mIsx7fEICTS:b9zsm00) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L89)):*
> ```C
> 		goto err_free_send;
> 
> 	if ((ret = rpma_srq_cfg_new(&srq_cfg)))
> ```

srq_cfg is not needed in the default execution path



_Suggestion:_
```C
	if (rcq_flag == 's') {
		/* create a shared RQ object */
		if ((ret = rpma_srq_new(peer, NULL, &srq)))
			goto err_peer_delete;
	} else {
		if ((ret = rpma_srq_cfg_new(&srq_cfg)))
			goto err_peer_delete;
		if ((ret = rpma_srq_cfg_set_rcq_size(srq_cfg, 0)))
			goto err_srq_cfg_delete;
		/* create a shared RQ object with given configuration */
		if ((ret = rpma_srq_new(peer, srq_cfg, &srq)))
			goto err_srq_cfg_delete;
	}
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8K1Ro5gpIdIA5AYBa:-NA8K1Ro5gpIdIA5AYBb:b8ojal3) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L105)):*
> ```C
> 		goto err_srq_delete;
> 
> 	if (rcq_flag == 'r') {
> ```

I know that the default value is 0 but to be more specific let's explicitly disable RCQ on the connection level



_Suggestion:_
```C
	if (rcq_flag == 'r') {
		if ((ret = rpma_conn_cfg_set_rcq_size(conn_cfg, RCQ_SIZE)))
			goto err_conn_cfg_delete;
	} else {
		if ((ret = rpma_conn_cfg_set_rcq_size(conn_cfg, 0)))
			goto err_conn_cfg_delete;
	}
```


<!-- Sent from Reviewable.io -->

2022-08-23 06:16 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 151 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8Kev06NhkzM5inOGm:-NA8Kev06NhkzM5inOGn:bf3s2b8) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L151)):*
> ```C
> 			ret = rpma_conn_get_rcq(conn, &rcq);
> 			break;
> 		default:
> ```

Increase code readability.



_Suggestion:_
```C
		case 's':
		default:
			/* get the separate receive CQ of the rpma_srq object */
			ret = rpma_srq_get_rcq(srq, &rcq);
			break;
```


<!-- Sent from Reviewable.io -->

2022-08-23 06:23 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 6 unresolved discussions (waiting on @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8LJ4p1HdfKjRuWC6x:-NA8LJ4p1HdfKjRuWC6y:b-cja6mz) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L21)):*
> ```Markdown
> ```
> **Note** The third parameter can be one of the following values:
> - unspecified - get receive completions by the separate receive CQ of rpma_srq object
> ```

Do not use implementation-specific description - ``rpma_srq``



_Suggestion:_
```Markdown
- unspecified - get receive completions by the CQ of the shared RQ
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8LtrlBMibjYKLQZGq:-NA8LtrlBMibjYKLQZGr:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L22)):*
> ```Markdown
> **Note** The third parameter can be one of the following values:
> - unspecified - get receive completions by the separate receive CQ of rpma_srq object
> - m - get receive completions by the main CQ of rpma_conn object
> ```

.



_Suggestion:_
```Markdown
- m - get receive completions by the main CQ of a connection
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 23 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8MdZ74J518AokjCfI:-NA8MdZ8BtcVED0ft4g7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L23)):*
> ```Markdown
> - unspecified - get receive completions by the separate receive CQ of rpma_srq object
> - m - get receive completions by the main CQ of rpma_conn object
> - r - get receive completions by the separate receive CQ of rpma_conn object
> ```

.



_Suggestion:_
```Markdown
- r - get receive completions by the separate receive CQ of a connection
```


<!-- Sent from Reviewable.io -->

2022-08-23 06:49 UTC, ldorau reviewed
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 6 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-23 07:10 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 6 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-23 07:12 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8LJ4p1HdfKjRuWC6x:-NA8VgpnEvuAbmCfVfsP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do not use implementation-specific description - ``rpma_srq``
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8LtrlBMibjYKLQZGq:-NA8VhJn8kBBTjNVt0E_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/README.md` line 23 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8MdZ74J518AokjCfI:-NA8Vhpo3SRDfYhRVA92:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/README.md#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 89 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8GjR8-mIsx7fEICTR:-NA8RV6C5soQXGmXMDLM:b8ckzr5) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L89)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

srq_cfg is not needed in the default execution path
</blockquote></details>

It seems not cleaner and simpler.  It is another way to call `rpma_srq_new()` by passing the  explicit  configuration.
I designed the logic on purpose because  `rpma_srq_new()` with the `NULL` configuration has been designed in example-13.
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8K1Ro5gpIdIA5AYBa:-NA8Wc7k23aZ9CAIZPZd:bsdf8ai) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L105)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I know that the default value is 0 but to be more specific let's explicitly disable RCQ on the connection level
</blockquote></details>

Is it ok to add the following comment  to explain the default behavior?
```
/* The default receive CQ size of the connection is 0 when rcq_flag is not 'r'. */
```
___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 151 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8Kev06NhkzM5inOGm:-NA8WbaX-p3z4CXXkmN1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L151)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Increase code readability.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 07:36 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-08-23 08:09 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985#-:-NA8jyVfDwBzIutB925A:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/08srq-simple-messages-ping-pong-with-srq/server.c` line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1985#-NA8K1Ro5gpIdIA5AYBa:-NA8jcFI7PS4OZojFTUk:b-bfdrrw) ([raw file](https://github.com/pmem/rpma/blob/b49bf03443f8578da48fe77397e6edaaaa0ddb3f/examples/08srq-simple-messages-ping-pong-with-srq/server.c#L105)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Is it ok to add the following comment  to explain the default behavior?
```
/* The default receive CQ size of the connection is 0 when rcq_flag is not 'r'. */
```
</blockquote></details>

Yes, it will be ok.


<!-- Sent from Reviewable.io -->

2022-08-23 08:10 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-23 09:22 UTC, osalyk approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985#-:-NA9-gDm3xEc8yAxfGoo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-23 09:35 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1985#-:-NA92dQ7BFmakvcx30bl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-08-23 09:35 UTC, merged