examples: do not use 0 size when mapping PMem
pmem/rpma pull request #2048
Opened 2022-10-25 09:06 UTC by ldorau

Do not use 0 size when mapping PMem.
A size of PMem should be set explicitly.

Add the write_hello flag to write the initial value and persist it.

2022-10-25 09:23 UTC, grom72 requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.c` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDQeeg-lmI-13_rkCs:-NFDQeeg-lmI-13_rkCt:b9di357) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L26)):*
> ```C
> 	 * by the user.
> 	 */
> 	size_t min_size = SIGNATURE_LEN + size;
> ```

``min_size`` is not needed  we can use a modified ``size`` instead



_Suggestion:_
```C
	size += SIGNATURE_LEN;
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDQyXF5qxK5B_hG3Jw:-NFDQyXF5qxK5B_hG3Jx:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L32)):*
> ```C
> 		return -1;
> 
> 	if (mem->mr_size < min_size) {
> ```

.



_Suggestion:_
```C
	if (mem->mr_size < size) {
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 34 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDR8Rw9rUlbYfyJ529:-NFDR8Rw9rUlbYfyJ52A:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L34)):*
> ```C
> 	if (mem->mr_size < min_size) {
> 		(void) fprintf(stderr, "%s has too small size (%zu < %zu)\n",
> 				path, mem->mr_size, min_size);
> ```

.



_Suggestion:_
```C
				path, mem->mr_size, size);
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 38 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDQ-ZC-1KuvbOpdiji:-NFDQ-ZC-1KuvbOpdijj:b-n20vgy) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L38)):*
> ```C
> 	}
> 
> 	/*
> ```

The signature should be persisted after memory initialization is completed.
There is no reason to initialize memory if already been initialized before.



_Suggestion:_
```C
	/*
	 * If the signature is not in place the persistent content has
	 * to be initialized and persisted.
	 */
	if (strncmp(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN) != 0) {

	if (write_hello) {
		/* write the initial value and persist it */
		write_hello_str((struct hello_t *)(mem->mr_ptr + mem->data_offset), en);
		mem->persist(mem->mr_ptr + mem->data_offset, sizeof(struct hello_t));
	} else {
		/* write an initial empty string and persist it */
		(mem->mr_ptr + mem->data_offset)[0] = '\0';
		mem->persist(mem->mr_ptr + mem->data_offset, 1);
	}
		/* write the signature to mark the content as valid */
		memcpy(mem->mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
		mem->persist(mem->mr_ptr, SIGNATURE_LEN);
	}
```


<!-- Sent from Reviewable.io -->

2022-10-25 09:36 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[`examples/common/common-map_file_with_signature_check.c` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDQeeg-lmI-13_rkCs:-NFDUpzAE9zYT2DNz_bk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L26)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``min_size`` is not needed  we can use a modified ``size`` instead
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDQyXF5qxK5B_hG3Jw:-NFDUrAx7TW76ZtIh1nO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 34 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDR8Rw9rUlbYfyJ529:-NFDUk7J2pHdgHE-zzXz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L34)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 38 at r1](https://reviewable.io/reviews/pmem/rpma/2048#-NFDQ-ZC-1KuvbOpdiji:-NFDUnzC4kgQwNyNsdW6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/917b0d252d4884f8a3d17a692ef43e4905efd86f/examples/common/common-map_file_with_signature_check.c#L38)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The signature should be persisted after memory initialization is completed.
There is no reason to initialize memory if already been initialized before.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-25 10:05 UTC, grom72 approved these changes
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-25 10:42 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r4](https://reviewable.io/reviews/pmem/rpma/2048#-NFDi9tp4FkUSgtKEIi_:-NFDi9tp4FkUSgtKEIia:undefined) ([raw file](https://github.com/pmem/rpma/blob/298b43a304717b10448158c8a42b8bb4b357d65b/examples/common/common-map_file_with_signature_check.h#L14)):*
> ```objc
> #include "common-pmem_map_file.h"
> 
> typedef void (*init_func_t)(struct common_mem *mem);
> ```





_Suggestion:_
```objc
common_init_func_t
```
___
*[`examples/common/common-map_file_with_signature_check.h` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/2048#-NFDjAYiDKl9-mKD6WNe:-NFDjAYiDKl9-mKD6WNf:b-22vv9u) ([raw file](https://github.com/pmem/rpma/blob/298b43a304717b10448158c8a42b8bb4b357d65b/examples/common/common-map_file_with_signature_check.h#L16)):*
> ```objc
> typedef void (*init_func_t)(struct common_mem *mem);
> 
> void init_hello(struct common_mem *mem);
> ```

Shouldn't we move this to ``common-hello.c``?
The dependency between ``common-map_file_with_signature_check`` and ``write_hello_str`` is unnecessary



_Code quote:_
```objc
void init_hello(struct common_mem *mem);
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/2048#-NFDiKNH6_qLapmlFl7p:-NFDiKNH6_qLapmlFl7q:b-22vv9u) ([raw file](https://github.com/pmem/rpma/blob/298b43a304717b10448158c8a42b8bb4b357d65b/examples/common/common-map_file_with_signature_check.c#L17)):*
> ```C
> init_hello(struct common_mem *mem)
> {
> 	/* write the initial hello string and persist it */
> ```

Shouldn't we move this to ``common-hello.c``?
The dependency between ``common-map_file_with_signature_check`` and ``write_hello_str`` is unnecessary



_Code quote:_
```C
void
init_hello(struct common_mem *mem)
{
	/* write the initial hello string and persist it */
	write_hello_str((struct hello_t *)(mem->mr_ptr + mem->data_offset), en);
	mem->persist(mem->mr_ptr + mem->data_offset, HELLO_T_SIZE);
}
```


<!-- Sent from Reviewable.io -->

2022-10-25 10:43 UTC, grom72 reviewed
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-25 11:19 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r4](https://reviewable.io/reviews/pmem/rpma/2048#-NFDi9tp4FkUSgtKEIi_:-NFDrRIf6y9sKUCuH2ht:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/298b43a304717b10448158c8a42b8bb4b357d65b/examples/common/common-map_file_with_signature_check.h#L14)):*
> ```objc
> #include "common-pmem_map_file.h"
> 
> typedef void (*init_func_t)(struct common_mem *mem);
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.h` line 16 at r4](https://reviewable.io/reviews/pmem/rpma/2048#-NFDjAYiDKl9-mKD6WNe:-NFDrRu4-zus2DUgeidU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/298b43a304717b10448158c8a42b8bb4b357d65b/examples/common/common-map_file_with_signature_check.h#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shouldn't we move this to ``common-hello.c``?
The dependency between ``common-map_file_with_signature_check`` and ``write_hello_str`` is unnecessary
</blockquote></details>

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 17 at r4](https://reviewable.io/reviews/pmem/rpma/2048#-NFDiKNH6_qLapmlFl7p:-NFDrUW_3R4sK-G2oUyg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/298b43a304717b10448158c8a42b8bb4b357d65b/examples/common/common-map_file_with_signature_check.c#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shouldn't we move this to ``common-hello.c``?
The dependency between ``common-map_file_with_signature_check`` and ``write_hello_str`` is unnecessary
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-25 11:28 UTC, grom72 requested changes
> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: 13 of 15 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDsBBN0cyVJo7uiZl2:-NFDsBBN0cyVJo7uiZl3:undefined) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-map_file_with_signature_check.h#L14)):*
> ```objc
> #include "common-pmem_map_file.h"
> 
> typedef int (*init_func_t)(char *pmem_data, size_t size);
> ```





_Suggestion:_
```objc
common_init_func_t
```


<!-- Sent from Reviewable.io -->

2022-10-25 11:37 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: 14 of 15 files reviewed, 7 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-25 11:37 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-25 11:50 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[`examples/common/common-hello.h` line 25 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDuIdS66PZhxYDpIf0:-NFDyPb5ETj38wAbBYcP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-hello.h#L25)):*
> ```objc
> void write_hello_str(struct hello_t *hello, enum lang_t lang);
> void translate(struct hello_t *hello);
> int init_hello(char *pmem_data, size_t size);
> ```

Done.
___
*[`examples/common/common-hello.c` line 35 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDuFx35LClXPnHwpTC:-NFDyRMqB02MybBFzPn3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-hello.c#L35)):*
> ```C
> }
> 
> int
> ```

Done.
___
*[`examples/common/common-hello.c` line 46 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDu3m_9aJY8WM6C5QE:-NFDySCn5kkunUZv9UeC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-hello.c#L46)):*
> ```C
> 	write_hello_str((struct hello_t *)pmem_data, en);
> 
> 	return 0;
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDsBBN0cyVJo7uiZl2:-NFDyTvu2J67vzVcLcIP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-map_file_with_signature_check.h#L14)):*
> ```objc
> #include "common-pmem_map_file.h"
> 
> typedef int (*init_func_t)(char *pmem_data, size_t size);
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.h` line 14 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDuQho6fK6lPgXEmhL:-NFDyVXz99fw4w6LtXv5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-map_file_with_signature_check.h#L14)):*
> ```objc
> #include "common-pmem_map_file.h"
> 
> typedef int (*init_func_t)(char *pmem_data, size_t size);
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 46 at r5](https://reviewable.io/reviews/pmem/rpma/2048#-NFDu96d-g9qdtWUkgL1:-NFDyXYc1GBMnQErK7eg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72a30e8ae2a8246c8b5ed8a35a7389b634fab78f/examples/common/common-map_file_with_signature_check.c#L46)):*
> ```C
> 		if (init_pmem) {
> 			/* write the initial hello string and persist it */
> 			if ((*init_pmem)(pmem_data, size - SIGNATURE_LEN)) {
> ```

Done.
___
*[`examples/common/common-map_file_with_signature_check.c` line 10 at r6](https://reviewable.io/reviews/pmem/rpma/2048#-NFDvI30Cg1tM8J3cNqo:-NFDye61-u2y1FXxypgI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fa09c8a4c4f057bdcfb0fe9ae5611a5856941ef8/examples/common/common-map_file_with_signature_check.c#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

No longer needed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-25 11:53 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048#-:-NFDzR54DOjwQnCLvT4h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-26 08:23 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-26 08:37 UTC, haichangsi reviewed
> Reviewed 1 of 1 files at r3, 10 of 12 files at r4, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-26 08:38 UTC, haichangsi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2048#-:-NFIRCEXE9kmixBQefJo:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-10-26 09:30 UTC, merged