examples: do not overwrite the previous errors
pmem/rpma pull request #2061
Opened 2022-10-31 14:06 UTC by ldorau

Do not overwrite the previous errors (ret = -1)
set when `(wc.status != IBV_WC_SUCCESS)` or `(wc.opcode != IBV_WC_RDMA_READ)`.

2022-10-31 17:00 UTC, grom72 requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2061#-NFiyu-12ETdf36EB4vr:-NFiyu-12ETdf36EB4vs:bp9v2dw) (no related file):*
In general, I think that we should use ``RPMA_E_UNKNOWN`` instead of ``-1``

___
___
*[`examples/03-read-to-persistent/server.c` line 185 at r1](https://reviewable.io/reviews/pmem/rpma/2061#-NFixXmt4VosIWUh5wu3:-NFixXmt4VosIWUh5wu4:bvo49pf) ([raw file](https://github.com/pmem/rpma/blob/006433b85b0162871fccd303ff652acbec4bfb5a/examples/03-read-to-persistent/server.c#L185)):*
> ```C
> 	 * structure.
> 	 */
> 	ret |= common_disconnect_and_wait_for_conn_close(&conn);
> ```

we should not overwrite the previous errors



_Suggestion:_
```C
	int ret1 = common_disconnect_and_wait_for_conn_close(&conn);
	if (ret == 0)
		ret = ret1;
```


<!-- Sent from Reviewable.io -->

2022-10-31 19:17 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-11-02 08:15 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2061#-NFiyu-12ETdf36EB4vr:-NFrP1MkDAOXk1ma6i8l:bnzn4w7) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

In general, I think that we should use ``RPMA_E_UNKNOWN`` instead of ``-1``
</blockquote></details>

Do you want to change it in all examples?

___
___
*[`examples/03-read-to-persistent/server.c` line 185 at r1](https://reviewable.io/reviews/pmem/rpma/2061#-NFixXmt4VosIWUh5wu3:-NFrOo6_9hlwlfff8Nw1:bbef9nu) ([raw file](https://github.com/pmem/rpma/blob/006433b85b0162871fccd303ff652acbec4bfb5a/examples/03-read-to-persistent/server.c#L185)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we should not overwrite the previous errors
</blockquote></details>

Look into `common_disconnect_and_wait_for_conn_close()` :-D
```c
int
common_disconnect_and_wait_for_conn_close(struct rpma_conn **conn_ptr)
{
	int ret = 0;

	ret |= rpma_conn_disconnect(*conn_ptr);
	if (ret == 0)
		ret |= common_wait_for_conn_close_verbose(*conn_ptr);

	ret |= rpma_conn_delete(conn_ptr);

	return ret;
}
```


<!-- Sent from Reviewable.io -->

2022-11-02 08:17 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`examples/03-read-to-persistent/server.c` line 185 at r1](https://reviewable.io/reviews/pmem/rpma/2061#-NFixXmt4VosIWUh5wu3:-NFrPNeI1V_bVvU2aewS:b-rj166x) ([raw file](https://github.com/pmem/rpma/blob/006433b85b0162871fccd303ff652acbec4bfb5a/examples/03-read-to-persistent/server.c#L185)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Look into `common_disconnect_and_wait_for_conn_close()` :-D
```c
int
common_disconnect_and_wait_for_conn_close(struct rpma_conn **conn_ptr)
{
	int ret = 0;

	ret |= rpma_conn_disconnect(*conn_ptr);
	if (ret == 0)
		ret |= common_wait_for_conn_close_verbose(*conn_ptr);

	ret |= rpma_conn_delete(conn_ptr);

	return ret;
}
```
</blockquote></details>

I have seen it and I do not like it either.


<!-- Sent from Reviewable.io -->

2022-11-02 08:34 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2061#-NFiyu-12ETdf36EB4vr:-NFrTFYO8SvB0EOCqG2G:b-h1t6wi) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do you want to change it in all examples?
</blockquote></details>

This could be a good solution. 

___


<!-- Sent from Reviewable.io -->

2022-11-02 09:02 UTC, haichangsi reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-11-02 10:02 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2061#-NFiyu-12ETdf36EB4vr:-NFrmelg4b2Zpo4HxIew:b-31je6) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This could be a good solution. 
</blockquote></details>

... in a separate PR.

___
___
*[`examples/03-read-to-persistent/server.c` line 185 at r1](https://reviewable.io/reviews/pmem/rpma/2061#-NFixXmt4VosIWUh5wu3:-NFrmcAO-FbDQ9K-5joQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/006433b85b0162871fccd303ff652acbec4bfb5a/examples/03-read-to-persistent/server.c#L185)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I have seen it and I do not like it either.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 10:03 UTC, osalyk approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)



<!-- Sent from Reviewable.io -->

2022-11-02 10:24 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061#-:-NFrrfM02g7iwloitnDf:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi and @osalyk)



<!-- Sent from Reviewable.io -->

2022-11-02 10:24 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-11-02 10:24 UTC, osalyk approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2061)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)



<!-- Sent from Reviewable.io -->

2022-11-02 10:31 UTC, merged