rpma: replace rdma_create_qp() with rdma_create_qp_ex()
pmem/rpma pull request #2084
Opened 2022-11-21 05:51 UTC by yangx-jy

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

2022-11-21 07:03 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-11-21 09:15 UTC, haichangsi reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-11-22 11:02 UTC, grom72 requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`src/peer.c` line 191 at r4](https://reviewable.io/reviews/pmem/rpma/2084#-NHTzj0Z1OxXrbRXn2ES:-NHTzeWG2QZjZGfcHhXj:b-5u485m) ([raw file](https://github.com/pmem/rpma/blob/eadf278dfaaa5f0cffc6f1acbb5b12b907ca2bd6/src/peer.c#L191)):*
> ```C
> 	qp_init_attr.comp_mask = IBV_QP_INIT_ATTR_PD;
> 	qp_init_attr.pd = peer->pd;
> ```

Shall we explicitly set ``qp_init_attr.send_ops_flags`` to 0 and later extend implementation with new capabilities?



_Suggestion:_
```C
qp_init_attr.send_ops_flags = 0;
```


<!-- Sent from Reviewable.io -->

2022-11-22 14:42 UTC, yangx-jy commented
*[`src/peer.c` line 191 at r4](https://reviewable.io/reviews/pmem/rpma/2084#-NHTzj0Z1OxXrbRXn2ES:-NHUk34g3_ZBcc27pFor:b-2h5jof) ([raw file](https://github.com/pmem/rpma/blob/eadf278dfaaa5f0cffc6f1acbb5b12b907ca2bd6/src/peer.c#L191)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we explicitly set ``qp_init_attr.send_ops_flags`` to 0 and later extend implementation with new capabilities?
</blockquote></details>

I prefer to set `qp_init_attr.send_ops_flags` to 0 when checking and introducing new libibverbs APIs because it is a new member of `struct ibv_qp_init_attr_ex`.  On old libibverbs, setting `qp_init_attr.send_ops_flags` to 0 will throw the following error:
```
/rpma/src/peer.c: In function 'rpma_peer_setup_qp':
/rpma/src/peer.c:193:14: error: 'struct ibv_qp_init_attr_ex' has no member named 'send_ops_flags'
  qp_init_attr.send_ops_flags = 0;
```
`qp_init_attr.send_ops_flags` was added by the following commit since 2018.
https://github.com/linux-rdma/rdma-core/commit/58ef962809865fe58ef166e97788cc12ce8d4ecc


<!-- Sent from Reviewable.io -->

2022-11-22 14:42 UTC, ldorau reviewed
It builds correctly on all OSes: https://github.com/ldorau/rpma/actions/runs/3523334644

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084#-:-NHUmYRj7IisnWlDDO0b:bz9j9g7)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-11-25 12:57 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084#-:-NHirNaT5N8uktFlEQtK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-11-28 14:43 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084#-:-NHygLex-RwtyPIv2RGD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-11-28 14:43 UTC, ldorau approved these changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2084)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-11-28 14:45 UTC, merged