Introduce libibverbs atomic write
pmem/rpma pull request #2085
Opened 2022-12-08 06:51 UTC by yangx-jy

This feature is based on my atomic write patch sets:
kernel: [[PATCH v7 0/8] RDMA/rxe: Add atomic write operation] (it has been merged into rdma for-next branch)
rdma-core: https://github.com/linux-rdma/rdma-core/pull/1179 (it has been merged into rdma-core master)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pmem/rpma/2085)

2022-12-08 08:24 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 9 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-12-10 09:08 UTC, yangx-jy commented
@ldorau @grom72 

The whole libibverbs atomic write patch set has been merged into kernel and rdma-core repo.  I think it is time to review this PR. ^_^

Best Regards,
Xiao Yang

2022-12-13 12:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJAMyht1bnlxYNUwJ9m:b3zm38) (no related file):*
The `07-atomic-write` example fails with the `unexpected wc.wr_id value (0x0 != 0xF01D)` error.

___


<!-- Sent from Reviewable.io -->

2022-12-13 12:10 UTC, ldorau reviewed
The code coverage is OK: https://app.codecov.io/gh/pmem/rpma/pull/2085

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085#-:-NJANj4y2xKFd3M3ugfg:b-l93cbj)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-12-13 12:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJATu7E69fgQOiwEWJa:b-ejhboc) (no related file):*
On Mellanox ConnectX-5 RNIC (Mellanox Technologies MT27800 Family) all examples fail with the following error:
```
Dec 13 13:33:41.367207 [1374172] *ERROR* peer.c: 208: rpma_peer_setup_qp: rdma_create_qp_ex(max_send_wr=10, max_recv_wr=10, max_send/recv_sge=1, max_inline_data=8, qp_type=IBV_QPT_RC, sq_sig_all=0) failed: Operation not supported
```

___


<!-- Sent from Reviewable.io -->

2022-12-13 12:45 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJAW58GCvYF3aDImoHN:b-za37rp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The `07-atomic-write` example fails with the `unexpected wc.wr_id value (0x0 != 0xF01D)` error.
</blockquote></details>

(tested on SoftRoCE)

___


<!-- Sent from Reviewable.io -->

2022-12-13 13:39 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ldorau and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJAgTWL4ZaVLDhVgt8q:b-35hvpm) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

On Mellanox ConnectX-5 RNIC (Mellanox Technologies MT27800 Family) all examples fail with the following error:
```
Dec 13 13:33:41.367207 [1374172] *ERROR* peer.c: 208: rpma_peer_setup_qp: rdma_create_qp_ex(max_send_wr=10, max_recv_wr=10, max_send/recv_sge=1, max_inline_data=8, qp_type=IBV_QPT_RC, sq_sig_all=0) failed: Operation not supported
```

</blockquote></details>

To use the atomic__write operation to conditions must be fulfilled:
- libibverbs must support `ibv_wr_atomic_write()`
- RDMA driver must support this operation
The first item is checked by ``function(is_ibv_wr_atomic_write_supported var)``.
The second condition must be verified during `peer` setup and later appropriate API shall be used (new one or legacy one)

___


<!-- Sent from Reviewable.io -->

2022-12-13 15:42 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJB8VUs93WHvqvmq8pg:b-29bdp) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

To use the atomic__write operation to conditions must be fulfilled:
- libibverbs must support `ibv_wr_atomic_write()`
- RDMA driver must support this operation
The first item is checked by ``function(is_ibv_wr_atomic_write_supported var)``.
The second condition must be verified during `peer` setup and later appropriate API shall be used (new one or legacy one)
</blockquote></details>

OK, thanks @grom72 !

___


<!-- Sent from Reviewable.io -->

2022-12-13 16:11 UTC, grom72 approved these changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-12-14 10:37 UTC, ldorau reviewed
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-12-15 07:45 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJJcazz-LYtiItFZ0sv:b-3zcd0a) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(tested on SoftRoCE)
</blockquote></details>

@ldorau 

It seems that your kernel doesn't support atomic write operation (Did you apply my kernel patch set into your kernel?).  In this case, a completion with IB_WC_LOC_QP_OP_ERR was always generated.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJJfFLFC8Z3a2NQw6Tk:b-6a1q63) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, thanks @grom72 !
</blockquote></details>

The above error indicated that Mellanox-5 provider (rdma-core/providers/mlx5/*) doesn't support atomic write operation.

Perhaps we need to check the atomic write support for both libibverbs and driver.

___


<!-- Sent from Reviewable.io -->

2022-12-15 08:37 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJJumuC5f-RQGE8aybW:bugtctf) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

It seems that your kernel doesn't support atomic write operation (Did you apply my kernel patch set into your kernel?).  In this case, a completion with IB_WC_LOC_QP_OP_ERR was always generated.

</blockquote></details>

What version of kernel is required?

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJJvTz3A8pyW8DeJKa2:b81ow5g) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

The above error indicated that Mellanox-5 provider (rdma-core/providers/mlx5/*) doesn't support atomic write operation.

Perhaps we need to check the atomic write support for both libibverbs and driver.
</blockquote></details>

Yes, we have to check the atomic write support for both libibverbs and driver.

___


<!-- Sent from Reviewable.io -->

2022-12-15 09:08 UTC, yangx-jy commented
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What version of kernel is required?
</blockquote></details>

There is no released kernel version supporting atomic write for now.
You have to build the latest kernel source from main line and then verify this PR.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git




<!-- Sent from Reviewable.io -->

2022-12-15 09:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJK8mQ628dIgPFqyur6:buf1z7x) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

There is no released kernel version supporting atomic write for now.
You have to build the latest kernel source from main line and then verify this PR.
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
</blockquote></details>

What version of kernel is it going to be released in?

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJK86NkA8_o4JCVTsam:b-mj9y57) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, we have to check the atomic write support for both libibverbs and driver.
</blockquote></details>

So please add checking if there is the support for the atomic write in the driver.

___


<!-- Sent from Reviewable.io -->

2022-12-15 10:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJKK4rO-_DZNqKuM4xf:b-dze7y) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What version of kernel is it going to be released in?
</blockquote></details>

1. What version of kernel is it going to be released in?
2. What exactly patches are required?

___


<!-- Sent from Reviewable.io -->

2022-12-15 14:41 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJLCvu7C_DmVB47OyDr:b-8ypd2v) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1. What version of kernel is it going to be released in?
2. What exactly patches are required?

</blockquote></details>

I have built **linux kernel 6.1** with the following patches applied:
```
4cd9f1d320f9 RDMA/rxe: Enable atomic write capability for rxe device
3aec427bb149 RDMA/rxe: Implement atomic write completion
034e285f8b99 RDMA/rxe: Make responder support atomic write on RC service
abb633cf2804 RDMA/rxe: Make requester support atomic write on RC service
5c7af6c79384 RDMA/rxe: Extend rxe packet format to support atomic write
c2d939002934 RDMA/rxe: Extend rxe user ABI to support atomic write
3ff81e827b8d RDMA: Extend RDMA kernel ABI to support atomic write
efa2afc3969e RDMA: Extend RDMA user ABI to support atomic write
```

and now **all** examples **fail** with the following error (on SoftRoCE):
```
*ERROR* peer.c: 203: rpma_peer_setup_qp: rdma_create_qp_ex(max_send_wr=10, max_recv_wr=10, max_send/recv_sge=1, max_inline_data=8, qp_type=IBV_QPT_RC, sq_sig_all=0) failed: Operation not supported
```

___


<!-- Sent from Reviewable.io -->

2022-12-15 14:53 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJLFaa0B-gxiEGn9mWF:b-um25qq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have built **linux kernel 6.1** with the following patches applied:
```
4cd9f1d320f9 RDMA/rxe: Enable atomic write capability for rxe device
3aec427bb149 RDMA/rxe: Implement atomic write completion
034e285f8b99 RDMA/rxe: Make responder support atomic write on RC service
abb633cf2804 RDMA/rxe: Make requester support atomic write on RC service
5c7af6c79384 RDMA/rxe: Extend rxe packet format to support atomic write
c2d939002934 RDMA/rxe: Extend rxe user ABI to support atomic write
3ff81e827b8d RDMA: Extend RDMA kernel ABI to support atomic write
efa2afc3969e RDMA: Extend RDMA user ABI to support atomic write
```

and now **all** examples **fail** with the following error (on SoftRoCE):
```
*ERROR* peer.c: 203: rpma_peer_setup_qp: rdma_create_qp_ex(max_send_wr=10, max_recv_wr=10, max_send/recv_sge=1, max_inline_data=8, qp_type=IBV_QPT_RC, sq_sig_all=0) failed: Operation not supported
```
</blockquote></details>

No, it was my mistake. Something was wrong with the build or the environment.

I have double-checked and I confirm that this PR with **linux kernel 6.1** and the following patches applied:
```
4cd9f1d320f9 RDMA/rxe: Enable atomic write capability for rxe device
3aec427bb149 RDMA/rxe: Implement atomic write completion
034e285f8b99 RDMA/rxe: Make responder support atomic write on RC service
abb633cf2804 RDMA/rxe: Make requester support atomic write on RC service
5c7af6c79384 RDMA/rxe: Extend rxe packet format to support atomic write
c2d939002934 RDMA/rxe: Extend rxe user ABI to support atomic write
3ff81e827b8d RDMA: Extend RDMA kernel ABI to support atomic write
efa2afc3969e RDMA: Extend RDMA user ABI to support atomic write
```

**WORKS FINE** :-)

___


<!-- Sent from Reviewable.io -->

2022-12-15 14:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJLGvH94OqoIIzjS9iQ:b-fximc4) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it was my mistake. Something was wrong with the build or the environment.

I have double-checked and I confirm that this PR with **linux kernel 6.1** and the following patches applied:
```
4cd9f1d320f9 RDMA/rxe: Enable atomic write capability for rxe device
3aec427bb149 RDMA/rxe: Implement atomic write completion
034e285f8b99 RDMA/rxe: Make responder support atomic write on RC service
abb633cf2804 RDMA/rxe: Make requester support atomic write on RC service
5c7af6c79384 RDMA/rxe: Extend rxe packet format to support atomic write
c2d939002934 RDMA/rxe: Extend rxe user ABI to support atomic write
3ff81e827b8d RDMA: Extend RDMA kernel ABI to support atomic write
efa2afc3969e RDMA: Extend RDMA user ABI to support atomic write
```

**WORKS FINE** :-)

</blockquote></details>

(only on SoftRoCE of course)

___


<!-- Sent from Reviewable.io -->

2022-12-16 09:02 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJAMyhs2uxSVb19GYUC:-NJP9qTa3jZ2MQ2JY7kv:btojbfq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(only on SoftRoCE of course)
</blockquote></details>

Great.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJP4B909TzAnW92STtn:b-e2z5dm) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So please add checking if there is the support for the atomic write in the driver.
</blockquote></details>

I added `rpma_utils_ibv_context_is_atomic_write_capable()` to check if kernel supports native atomic write.
In this case, I think the atomic write example can work well on all environment.

___


<!-- Sent from Reviewable.io -->

2022-12-16 09:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NJATu7E69fgQOiwEWJ_:-NJPK8j--XEhmvYiSeTD:bbijf6e) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I added `rpma_utils_ibv_context_is_atomic_write_capable()` to check if kernel supports native atomic write.
In this case, I think the atomic write example can work well on all environment.
</blockquote></details>

It works now :-) Thanks!

___


<!-- Sent from Reviewable.io -->

2022-12-16 09:49 UTC, ldorau reviewed
> Reviewed 2 of 9 files at r2, 2 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 4 of 21 files reviewed, all discussions resolved (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-12-16 10:59 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 4 of 21 files reviewed, 2 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/peer.c` line 36 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Yty5b6jnykHJiaS:-NJP_Yty5b6jnykHJiaT:bu72sca) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L36)):*
> ```C
> 	int is_odp_supported; /* is On-Demand Paging supported */
> 
> 	int is_atomic_write_supported; /* is atomic write supported */
> ```

``is_atomic_write_supported_natively``
or
``is_atomic_write_supported_by_ibv_device``



_Code quote:_
```C
is_atomic_write_supported
```
___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJP_Hkz2-QDMSInQWYt:b-szo9cl) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
> ```C
> 	peer->pd = pd;
> 	peer->is_odp_supported = is_odp_supported;
> 	peer->is_atomic_write_supported = is_atomic_write_supported;
> ```

Please add RPMA_LOG_INFO message when native atomic write is not supported



_Code quote:_
```C
peer->is_atomic_write_supported = is_atomic_write_supported;
```


<!-- Sent from Reviewable.io -->

2022-12-16 11:01 UTC, grom72 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 4 of 21 files reviewed, 2 unresolved discussions (waiting on @ldorau and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-12-17 07:09 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 4 of 23 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/peer.c` line 36 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Yty5b6jnykHJiaS:-NJTuM953TlEmWsMueOk:buxyrw5) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``is_atomic_write_supported_natively``
or
``is_atomic_write_supported_by_ibv_device``
</blockquote></details>

Done. Used is_native_atomic_write_supported instead.
___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJTuRA8-nmFu5XRHf0a:bspklh9) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please add RPMA_LOG_INFO message when native atomic write is not supported
</blockquote></details>

Done.  Add RPMA_LOG_INFO().


<!-- Sent from Reviewable.io -->

2022-12-19 09:22 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 5 of 23 files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2022-12-19 09:57 UTC, ldorau requested changes
> Reviewed 2 of 19 files at r3, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 9 of 23 files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/peer.c` line 306 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdnve6AN-jNII0-0u7:-NJdnve6AN-jNII0-0u8:b-y21y1e) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L306)):*
> ```C
> 		return RPMA_E_INVAL;
> 
> 	ret = rpma_utils_ibv_context_is_atomic_write_capable(ibv_ctx,
> ```

`RPMA_FAULT_INJECTION(RPMA_E_PROVIDER, {});` should be added before the `rpma_utils_ibv_context_is_atomic_write_capable(()` call, because it can fail with `RPMA_E_PROVIDER`.
___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJdm-xj925a7-8EG8C3:b-mjt982) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
> ```C
> 	*peer_ptr = peer;
> 
> 	RPMA_LOG_INFO("new rpma_peer_new(is_native_atomic_write_supported=%s)",
> ```

Why `"new ...` ? What does it mean here?



_Code quote:_
```C
"new rpma_peer_new(
```
___
*[`src/utils.h` line 2 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdnOGE2BrIh5yy8TzR:-NJdnOGE2BrIh5yy8TzS:b6smx8) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/utils.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright (c) 2022, Fujitsu */
> ```

Are they both needed ?



_Code quote:_
```objc
/* Copyright (c) 2022, Fujitsu */
/* Copyright (c) 2022 Fujitsu Limited */
```


<!-- Sent from Reviewable.io -->

2022-12-19 10:24 UTC, ldorau reviewed
> Reviewed 4 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 13 of 23 files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-12-20 02:50 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 12 of 23 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/peer.c` line 306 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdnve6AN-jNII0-0u7:-NJhNhR14RElYWTCYlCV:bkm8gie) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L306)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`RPMA_FAULT_INJECTION(RPMA_E_PROVIDER, {});` should be added before the `rpma_utils_ibv_context_is_atomic_write_capable(()` call, because it can fail with `RPMA_E_PROVIDER`.
</blockquote></details>

@ldorau 

Is it necessary to add `RPMA_FAULT_INJECTION(RPMA_E_PROVIDER, {});` here?
In my opinion, `RPMA_FAULT_INJECTION(RPMA_E_PROVIDER, {});` has been added in `rpma_utils_ibv_context_is_atomic_write_capable()`
___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJhOTEZDKngKn5BSZ11:bqi19ab) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why `"new ...` ? What does it mean here?
</blockquote></details>

Done. Sorry, the correct one is `RPMA_LOG_INFO("new rpma_peer(is_native_atomic_write_supported=%s)"` and it means that new struct rpma_peer with is_native_atomic_write_supported=%s member.

I referred to the usage of RPMA_LOG_INFO() in other places:
```
src/mr.c:       RPMA_LOG_INFO("new rpma_mr_remote(raddr=0x%" PRIx64 ", size=%" PRIu64
src/peer_cfg.c: RPMA_LOG_INFO("new rpma_peer_cfg(direct_write_to_pmem=%s)",
```
___
*[`src/utils.h` line 2 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdnOGE2BrIh5yy8TzR:-NJhPi2R4fbpS3JJi6Dk:bytb90h) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/utils.h#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Are they both needed ?
</blockquote></details>

Done.  I have removed the first one.


<!-- Sent from Reviewable.io -->

2022-12-20 08:46 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 13 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/peer.c` line 306 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdnve6AN-jNII0-0u7:-NJidzIY4Yeg7Z9qhdcD:b-4z4see) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L306)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

Is it necessary to add `RPMA_FAULT_INJECTION(RPMA_E_PROVIDER, {});` here?
In my opinion, `RPMA_FAULT_INJECTION(RPMA_E_PROVIDER, {});` has been added in `rpma_utils_ibv_context_is_atomic_write_capable()`
</blockquote></details>

You are right. I haven't realized it is our internal function.
___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJifEeJDInZW66QF9pO:b-p0htvq) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done. Sorry, the correct one is `RPMA_LOG_INFO("new rpma_peer(is_native_atomic_write_supported=%s)"` and it means that new struct rpma_peer with is_native_atomic_write_supported=%s member.

I referred to the usage of RPMA_LOG_INFO() in other places:
```
src/mr.c:       RPMA_LOG_INFO("new rpma_mr_remote(raddr=0x%" PRIx64 ", size=%" PRIu64
src/peer_cfg.c: RPMA_LOG_INFO("new rpma_peer_cfg(direct_write_to_pmem=%s)",
```
</blockquote></details>

@grom72 what do you think about all those messages?
For me they looks like functions now. IMHO they should use curly braces and the `struct` keyword:
```c
	RPMA_LOG_INFO("new struct rpma_mr_remote {raddr=0x%" PRIx64 ", size=%" PRIu64
			", rkey=0x%" PRIx32 ", usage=0x%" PRIx8 "}",
			raddr, size, rkey, usage);

	RPMA_LOG_INFO("new struct rpma_peer_cfg {direct_write_to_pmem=%s}",
			SUPPORTED2STR(cfg->direct_write_to_pmem));

	RPMA_LOG_INFO("new struct rpma_peer {is_native_atomic_write_supported=%s}",
			SUPPORTED2STR(is_native_atomic_write_supported));
```
 


<!-- Sent from Reviewable.io -->

2022-12-20 08:55 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJiiuw018lk5IKa5aCh:b6ldhkd) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.  Add RPMA_LOG_INFO().
</blockquote></details>

We do not need this message in the future.
It is only needed when we can not use native atomic write.
A message should be more informative, not saying anything about implementation details but giving a clear WARNING message to the user:
"Native atomic write is not supported - ordinary RDMA write will be used instead."


<!-- Sent from Reviewable.io -->

2022-12-20 08:57 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJijmHy-r7fB17RasjM:bc63ums) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 what do you think about all those messages?
For me they looks like functions now. IMHO they should use curly braces and the `struct` keyword:
```c
	RPMA_LOG_INFO("new struct rpma_mr_remote {raddr=0x%" PRIx64 ", size=%" PRIu64
			", rkey=0x%" PRIx32 ", usage=0x%" PRIx8 "}",
			raddr, size, rkey, usage);

	RPMA_LOG_INFO("new struct rpma_peer_cfg {direct_write_to_pmem=%s}",
			SUPPORTED2STR(cfg->direct_write_to_pmem));

	RPMA_LOG_INFO("new struct rpma_peer {is_native_atomic_write_supported=%s}",
			SUPPORTED2STR(is_native_atomic_write_supported));
```
 
</blockquote></details>

The first one could be a LOG_DEBUG.
The second one is about configuration structure and perhaps should be rephrased to something more user-friendly. (See my comment above)
The this one I have already commented above.


<!-- Sent from Reviewable.io -->

2022-12-20 09:16 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJio-gK7u5rZfNx2mSj:bbiypdl) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The first one could be a LOG_DEBUG.
The second one is about configuration structure and perhaps should be rephrased to something more user-friendly. (See my comment above)
The this one I have already commented above.
</blockquote></details>

I agree with @ldorau to use ``struct rpma_XXX { ... }``



_Code quote:_
```C
new rpma_peer(is_native_atomic_write_supported=%s)
```


<!-- Sent from Reviewable.io -->

2022-12-20 09:30 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJiqubS3J9IM5qeH3uA:b-qycns0) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We do not need this message in the future.
It is only needed when we can not use native atomic write.
A message should be more informative, not saying anything about implementation details but giving a clear WARNING message to the user:
"Native atomic write is not supported - ordinary RDMA write will be used instead."

</blockquote></details>

I agree with @grom72 . It should look like that:
```c
	if (!is_native_atomic_write_supported)
		RPMA_LOG_INFO(
			"Native atomic write is not supported - ordinary RDMA write will be used instead.");
```
___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJirFvdBHDX8b7iLZyJ:bclczqq) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I agree with @ldorau to use ``struct rpma_XXX { ... }``
</blockquote></details>

@yangx-jy see a comment above. Please fix only this one message. The rest I will fix in a separate PR.


<!-- Sent from Reviewable.io -->

2022-12-20 09:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/peer.c` line 353 at r4](https://reviewable.io/reviews/pmem/rpma/2085#-NJdm-xj925a7-8EG8C2:-NJiuqLP0IbWaH2QMRBM:b-8jo3vn) ([raw file](https://github.com/pmem/rpma/blob/f20a691a2b49fb65dff72b510e3846c939053699/src/peer.c#L353)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy see a comment above. Please fix only this one message. The rest I will fix in a separate PR.
</blockquote></details>

See: https://github.com/pmem/rpma/pull/2086


<!-- Sent from Reviewable.io -->

2022-12-20 09:48 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJivZ7UEFyCZL-AE2UR:b-amt63s) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I agree with @grom72 . It should look like that:
```c
	if (!is_native_atomic_write_supported)
		RPMA_LOG_INFO(
			"Native atomic write is not supported - ordinary RDMA write will be used instead.");
```

</blockquote></details>

Or even better (see #2086):
```c
	if (!is_native_atomic_write_supported)
		RPMA_LOG_INFO(
			"INFO: native atomic write is not supported - ordinary RDMA write will be used instead.");
```


<!-- Sent from Reviewable.io -->

2022-12-20 09:58 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJixpcp3tvN2Mv9w0-r:b-1xldb7) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or even better (see #2086):
```c
	if (!is_native_atomic_write_supported)
		RPMA_LOG_INFO(
			"INFO: native atomic write is not supported - ordinary RDMA write will be used instead.");
```
</blockquote></details>

OK, I will update the message as you suggested.


<!-- Sent from Reviewable.io -->

2022-12-20 10:00 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJiyYU2Dz9-lES9duYR:brujzsz) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

OK, I will update the message as you suggested.
</blockquote></details>

OK, thanks!


<!-- Sent from Reviewable.io -->

2022-12-20 10:39 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 10 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`src/peer.c` line 350 at r3](https://reviewable.io/reviews/pmem/rpma/2085#-NJP_Hky6Xl7SDxscScc:-NJj5-Jw82X8p5O44-X8:b8yulrs) ([raw file](https://github.com/pmem/rpma/blob/fe5d109529f91bf0132f19e7b33c26665bd422f6/src/peer.c#L350)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, thanks!
</blockquote></details>

Done. Remove the "INFO:" prefix because `RPMA_LOG_INFO()` has the similar prefix as below:
```
Dec 20 18:38:33.551924 [1356] *INFO*  peer.c: 312: rpma_peer_new: Native atomic write is not supported - ordinary RDMA write will be used instead.
```


<!-- Sent from Reviewable.io -->

2022-12-21 07:34 UTC, ldorau requested changes
> Reviewed 8 of 19 files at r3, 3 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

___
*[`tests/unit/utils/CMakeLists.txt` line 34 at r6](https://reviewable.io/reviews/pmem/rpma/2085#-NJna2QZ8sDwY7WhwMUR:-NJna2QZ8sDwY7WhwMUS:b-mfi84c) ([raw file](https://github.com/pmem/rpma/blob/8ec5bbed9b2bbb8681d6dea31458f9ae973ef8af/tests/unit/utils/CMakeLists.txt#L34)):*
> ```CMake
> 	${LIBRPMA_SOURCE_DIR}/utils.c)
> 
> add_test_generic(NAME ut-utils-get_ibv_context TRACERS none)
> ```

Why haven't you used `add_test_utils()` for the `ut-utils-get_ibv_context` test?



_Code quote:_
```CMake
build_test_src(UNIT NAME ut-utils-get_ibv_context SRCS
	utils-get_ibv_context.c
	utils-common.c
	${TEST_UNIT_COMMON_DIR}/mocks-ibverbs.c
	${TEST_UNIT_COMMON_DIR}/mocks-rpma-log.c
	${LIBRPMA_SOURCE_DIR}/rpma_err.c
	${LIBRPMA_SOURCE_DIR}/utils.c)


add_test_generic(NAME ut-utils-get_ibv_context TRACERS none)
```


<!-- Sent from Reviewable.io -->

2022-12-21 08:22 UTC, yangx-jy commented
*[`tests/unit/utils/CMakeLists.txt` line 34 at r6](https://reviewable.io/reviews/pmem/rpma/2085#-NJna2QZ8sDwY7WhwMUR:-NJnjqcc69TxQ2FaWMqz:blj0say) ([raw file](https://github.com/pmem/rpma/blob/8ec5bbed9b2bbb8681d6dea31458f9ae973ef8af/tests/unit/utils/CMakeLists.txt#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why haven't you used `add_test_utils()` for the `ut-utils-get_ibv_context` test?
</blockquote></details>

 The `ut-utils-get_ibv_context` test depends on the mock functions which are defined in utils-common.c, but these same mock functions are defined differently in `mocks-rdma_cm.c` and `mocks-rpma-info.c`.  In this case, I didn't use `add_test_utils()` for for the `ut-utils-get_ibv_context` test.


<!-- Sent from Reviewable.io -->

2022-12-21 10:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

___
*[`tests/unit/utils/CMakeLists.txt` line 34 at r6](https://reviewable.io/reviews/pmem/rpma/2085#-NJna2QZ8sDwY7WhwMUR:-NJoCH7V3i6tcRcvTwIj:b1nqgir) ([raw file](https://github.com/pmem/rpma/blob/8ec5bbed9b2bbb8681d6dea31458f9ae973ef8af/tests/unit/utils/CMakeLists.txt#L34)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

 The `ut-utils-get_ibv_context` test depends on the mock functions which are defined in utils-common.c, but these same mock functions are defined differently in `mocks-rdma_cm.c` and `mocks-rpma-info.c`.  In this case, I didn't use `add_test_utils()` for for the `ut-utils-get_ibv_context` test.
</blockquote></details>

I see. Maybe something like that will be more clear and readable?
https://github.com/ldorau/rpma/blob/test-utils-tests/tests/unit/utils/CMakeLists.txt


<!-- Sent from Reviewable.io -->

2022-12-21 13:56 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`tests/unit/utils/CMakeLists.txt` line 34 at r6](https://reviewable.io/reviews/pmem/rpma/2085#-NJna2QZ8sDwY7WhwMUR:-NJoxBe4A16DwdkGFZoU:b-xpg62x) ([raw file](https://github.com/pmem/rpma/blob/8ec5bbed9b2bbb8681d6dea31458f9ae973ef8af/tests/unit/utils/CMakeLists.txt#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I see. Maybe something like that will be more clear and readable?
https://github.com/ldorau/rpma/blob/test-utils-tests/tests/unit/utils/CMakeLists.txt
</blockquote></details>

@ldorau, I tried to use the unified `add_test_utils()` by the following design:
```
function(add_test_utils name)
        set(src_name utils-${name})
        set(name ut-${src_name})

        if(${name} STREQUAL "ut-utils-get_ibv_context")
                set(src_dependencies utils-common.c)
        else()
                set(src_dependencies
                        ${TEST_UNIT_COMMON_DIR}/mocks-rdma_cm.c
                        ${TEST_UNIT_COMMON_DIR}/mocks-rpma-info.c)
        endif()

        build_test_src(UNIT NAME ${name} SRCS
                ${src_name}.c
                ${src_dependencies}
                ${TEST_UNIT_COMMON_DIR}/mocks-ibverbs.c
                ${TEST_UNIT_COMMON_DIR}/mocks-rpma-log.c
                ${LIBRPMA_SOURCE_DIR}/rpma_err.c
                ${LIBRPMA_SOURCE_DIR}/utils.c)

        add_test_generic(NAME ${name} TRACERS none)
endfunction()

add_test_utils(conn_event_2str)
add_test_utils(get_ibv_context)
add_test_utils(ibv_context_is_atomic_write_capable)

if(ON_DEMAND_PAGING_SUPPORTED)
        add_test_utils(ibv_context_is_odp_capable)
endif()
``` 


<!-- Sent from Reviewable.io -->

2022-12-29 13:40 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2022-12-30 09:45 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

___
*[`tests/unit/utils/CMakeLists.txt` line 34 at r6](https://reviewable.io/reviews/pmem/rpma/2085#-NJna2QZ8sDwY7WhwMUR:-NKXPyQr2-uLdr_72dmv:b-58y1yg) ([raw file](https://github.com/pmem/rpma/blob/8ec5bbed9b2bbb8681d6dea31458f9ae973ef8af/tests/unit/utils/CMakeLists.txt#L34)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau, I tried to use the unified `add_test_utils()` by the following design:
```
function(add_test_utils name)
        set(src_name utils-${name})
        set(name ut-${src_name})

        if(${name} STREQUAL "ut-utils-get_ibv_context")
                set(src_dependencies utils-common.c)
        else()
                set(src_dependencies
                        ${TEST_UNIT_COMMON_DIR}/mocks-rdma_cm.c
                        ${TEST_UNIT_COMMON_DIR}/mocks-rpma-info.c)
        endif()

        build_test_src(UNIT NAME ${name} SRCS
                ${src_name}.c
                ${src_dependencies}
                ${TEST_UNIT_COMMON_DIR}/mocks-ibverbs.c
                ${TEST_UNIT_COMMON_DIR}/mocks-rpma-log.c
                ${LIBRPMA_SOURCE_DIR}/rpma_err.c
                ${LIBRPMA_SOURCE_DIR}/utils.c)

        add_test_generic(NAME ${name} TRACERS none)
endfunction()

add_test_utils(conn_event_2str)
add_test_utils(get_ibv_context)
add_test_utils(ibv_context_is_atomic_write_capable)

if(ON_DEMAND_PAGING_SUPPORTED)
        add_test_utils(ibv_context_is_odp_capable)
endif()
``` 
</blockquote></details>

Looks good. Thanks!


<!-- Sent from Reviewable.io -->

2022-12-30 09:48 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085#-:-NKXQkUECz5tkxYnW4ID:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-12-30 10:39 UTC, grom72 requested changes
> Reviewed 2 of 9 files at r2, 1 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

___
*[`src/utils.h` line 13 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXbLD37-RXKoaSKePq:-NKXbLD43hG7WKVeL-8x:b-9essl0) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/src/utils.h#L13)):*
> ```objc
> #include "librpma.h"
> 
> #define RPMA_ATOMIC_WRITE_CAP_FLAG	(1UL << 40)
> ```

Not needed as we should use libibverbs const.



_Code quote:_
```objc
#define RPMA_ATOMIC_WRITE_CAP_FLAG	(1UL << 40)
```
___
*[`src/utils.c` line 42 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXXXC_BGcrwQ79iqzU:-NKXXXC_BGcrwQ79iqzV:bs3bqt0) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/src/utils.c#L42)):*
> ```C
> 
> 	/* check whether native atomic write is supported in kernel */
> 	if (attr.device_cap_flags_ex & RPMA_ATOMIC_WRITE_CAP_FLAG)
> ```

We should use here the flag defined by libibverbs.



_Suggestion:_
```C
IB_UVERBS_DEVICE_ATOMIC_WRITE
```


<!-- Sent from Reviewable.io -->

2022-12-30 11:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/utils.c` line 42 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXXXC_BGcrwQ79iqzU:-NKXjL5eCEDm7L4_Nk-M:b-3dyd0w) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/src/utils.c#L42)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should use here the flag defined by libibverbs.
</blockquote></details>

And this constant `IB_UVERBS_DEVICE_ATOMIC_WRITE` should be checked in the CMake script checking support


<!-- Sent from Reviewable.io -->

2022-12-30 11:22 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`cmake/functions.cmake` line 298 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXlAQv3Qd32ROh3RTi:-NKXlAQw-Y1INKy7tX1A:bqfs8kf) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/cmake/functions.cmake#L298)):*
> ```CMake
> 		/* check if ibv_wr_atomic_write() is defined */
> 		int main() {
> 			return !ibv_wr_atomic_write;
> ```

Please check also for `IB_UVERBS_DEVICE_ATOMIC_WRITE`


<!-- Sent from Reviewable.io -->

2022-12-31 11:40 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 19 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`cmake/functions.cmake` line 298 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXlAQv3Qd32ROh3RTi:-NKbxsqJBw7LnJV8AcUf:b-uhmz66) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/cmake/functions.cmake#L298)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please check also for `IB_UVERBS_DEVICE_ATOMIC_WRITE`
</blockquote></details>

Done. I also check IBV_QP_EX_WITH_ATOMIC_WRITE which is used by rdma_create_qp_ex().
___
*[`src/utils.h` line 13 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXbLD37-RXKoaSKePq:-NKbyb-U1QkFFbaT4YV8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/src/utils.h#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Not needed as we should use libibverbs const.
</blockquote></details>

Done.
___
*[`src/utils.c` line 42 at r7](https://reviewable.io/reviews/pmem/rpma/2085#-NKXXXC_BGcrwQ79iqzU:-NKbyf2s3-fAeOk6DSX8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5630242f529d1c4a4ee3bfc0f717c31ef4e710dc/src/utils.c#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

And this constant `IB_UVERBS_DEVICE_ATOMIC_WRITE` should be checked in the CMake script checking support
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-02 07:09 UTC, ldorau approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2023-01-02 11:12 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKmAbmm6sk_gnedsBYG:-NKmAbmn5qAkLyl30WCO:blm8r93) (no related file):*
Please update CHANGELOG.md

___


<!-- Sent from Reviewable.io -->

2023-01-02 20:26 UTC, grom72 requested changes
> Reviewed 2 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKo8kor4oF-OcALlJo-:-NKo8kor4oF-OcALlJo0:bge49jj) (no related file):*
``mtt-mr-rpma_mr_remote_from_descriptor_0_none`` fails all the time for this PR:

236/295 Test #236: mtt-mr-rpma_mr_remote_from_descriptor_0_none .................***Failed    0.03 sec

https://app.circleci.com/pipelines/github/pmem/rpma

___


<!-- Sent from Reviewable.io -->

2023-01-03 03:43 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKmAbmm6sk_gnedsBYG:-NKpgpmb3RvHc9YwXw-s:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please update CHANGELOG.md
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKo8kor4oF-OcALlJo-:-NKpguTICm7xpmyIeNQJ:b-cpgsdf) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``mtt-mr-rpma_mr_remote_from_descriptor_0_none`` fails all the time for this PR:

236/295 Test #236: mtt-mr-rpma_mr_remote_from_descriptor_0_none .................***Failed    0.03 sec

https://app.circleci.com/pipelines/github/pmem/rpma

</blockquote></details>

It seems not be caused by this PR, all unit tests passed on my environment:
```
...
235/295 Test #235: mtt-mr-rpma_mr_reg_0_helgrind ................................   Passed    1.09 sec
        Start 236: mtt-mr-rpma_mr_remote_from_descriptor_0_none
236/295 Test #236: mtt-mr-rpma_mr_remote_from_descriptor_0_none .................   Passed    0.15 sec
        Start 237: mtt-mr-rpma_mr_remote_from_descriptor_0_memcheck
237/295 Test #237: mtt-mr-rpma_mr_remote_from_descriptor_0_memcheck .............   Passed    3.05 sec
...
293/295 Test #293: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_memcheck ...   Passed    2.37 sec
        Start 294: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_drd
294/295 Test #294: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_drd ........   Passed    1.19 sec
        Start 295: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_helgrind
295/295 Test #295: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_helgrind ...   Passed    1.16 sec

100% tests passed, 0 tests failed out of 295

Total Test time (real) = 271.63 sec
```
Did I miss something?

___


<!-- Sent from Reviewable.io -->

2023-01-03 08:55 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKo8kor4oF-OcALlJo-:-NKqpWKlAhlanbQq3YPd:b-z37r9y) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It seems not be caused by this PR, all unit tests passed on my environment:
```
...
235/295 Test #235: mtt-mr-rpma_mr_reg_0_helgrind ................................   Passed    1.09 sec
        Start 236: mtt-mr-rpma_mr_remote_from_descriptor_0_none
236/295 Test #236: mtt-mr-rpma_mr_remote_from_descriptor_0_none .................   Passed    0.15 sec
        Start 237: mtt-mr-rpma_mr_remote_from_descriptor_0_memcheck
237/295 Test #237: mtt-mr-rpma_mr_remote_from_descriptor_0_memcheck .............   Passed    3.05 sec
...
293/295 Test #293: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_memcheck ...   Passed    2.37 sec
        Start 294: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_drd
294/295 Test #294: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_drd ........   Passed    1.19 sec
        Start 295: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_helgrind
295/295 Test #295: mtt-utils-rpma_utils_ibv_context_is_odp_capable_0_helgrind ...   Passed    1.16 sec

100% tests passed, 0 tests failed out of 295

Total Test time (real) = 271.63 sec
```
Did I miss something?
</blockquote></details>

These errors have nothing to do with this PR. They occurs only on Circle CI.

___
___
*[`CHANGELOG.md` line 21 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqmUoL466MValGvk1e:-NKqmUoL466MValGvk1f:b-imz5v3) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L21)):*
> ```Markdown
> - one suppression for Memcheck on Ubuntu 22.04
> - CI Coverity build run once a day over the night
> - check if libibverbs supports native atomic write
> ```

checking ...

(The section "Added" contains "things" (nouns) that have been added)



_Code quote:_
```Markdown
check if libibverbs supports native atomic write
```
___
*[`CHANGELOG.md` line 23 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqnIAX0OKtBVIA6yH3:-NKqnIAX0OKtBVIA6yH4:bo2xwfy) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L23)):*
> ```Markdown
> - check if libibverbs supports native atomic write
> - internal APIs:
>   - rpma_utils_ibv_context_is_atomic_write_capable() - check if kernel supports native atomic write
> ```

checks if kernel ...



_Code quote:_
```Markdown
check if kernel
```
___
*[`CHANGELOG.md` line 45 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqo2HjByTA5DOijmw7:-NKqo2HjByTA5DOijmw8:b-9se7tr) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L45)):*
> ```Markdown
> - call rpma_utils_ibv_context_is_atomic_write_capable() in rpma_peer_new()
> - enable native atomic write in rpma_peer_setup_qp() if both kernel and libibverbs support it
> - use native atomic write in rpma_mr_atomic_write() if the created QP supports it
> ```

```
- rpma_utils_ibv_context_is_atomic_write_capable() called in rpma_peer_new()
- native atomic write enabled in rpma_peer_setup_qp() if both kernel and libibverbs support it
- native atomic write used in rpma_mr_atomic_write() if the created QP supports it
```

(The section "Changed" contains things that **were/have been changed** - please use Past/Present Perfect Tense)



_Code quote:_
```Markdown
- call rpma_utils_ibv_context_is_atomic_write_capable() in rpma_peer_new()
- enable native atomic write in rpma_peer_setup_qp() if both kernel and libibverbs support it
- use native atomic write in rpma_mr_atomic_write() if the created QP supports it
```


<!-- Sent from Reviewable.io -->

2023-01-03 09:53 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKo8kor4oF-OcALlJo-:-NKr219F2qF6k5Du2tFV:b-607qfj) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

These errors have nothing to do with this PR. They occurs only on Circle CI.
</blockquote></details>

This is the fix for this issue: https://github.com/pmem/rpma/pull/2087

___


<!-- Sent from Reviewable.io -->

2023-01-03 10:51 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKrFK6w4GpyFZZ8ZXQA:-NKrFK6x9FJgMoEN-sK2:b-jcstpa) (no related file):*
The https://github.com/pmem/rpma/pull/2087 fix merged - rebase please.

___


<!-- Sent from Reviewable.io -->

2023-01-03 11:54 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 23 of 24 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKo8kor4oF-OcALlJo-:-NKrTu6bAymYy1PjE-4v:b-89q77k) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This is the fix for this issue: https://github.com/pmem/rpma/pull/2087
</blockquote></details>

Cool.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKrFK6w4GpyFZZ8ZXQA:-NKrTwAk8yFz6-0Ryb8b:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The https://github.com/pmem/rpma/pull/2087 fix merged - rebase please.
</blockquote></details>

Done.

___
___
*[`CHANGELOG.md` line 21 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqmUoL466MValGvk1e:-NKrTxXdEwrqA9C3dk2r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

checking ...

(The section "Added" contains "things" (nouns) that have been added)
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 23 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqnIAX0OKtBVIA6yH3:-NKrTxor4y4LJCABMiYe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

checks if kernel ...
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 45 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqo2HjByTA5DOijmw7:-NKrTyIj2A5qbjQ39ZMG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
- rpma_utils_ibv_context_is_atomic_write_capable() called in rpma_peer_new()
- native atomic write enabled in rpma_peer_setup_qp() if both kernel and libibverbs support it
- native atomic write used in rpma_mr_atomic_write() if the created QP supports it
```

(The section "Changed" contains things that **were/have been changed** - please use Past/Present Perfect Tense)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 12:00 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`CHANGELOG.md` line 21 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqmUoL466MValGvk1e:-NKrUhXc-r_xGFyHBqSN:b99hds1) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L21)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"**a** check if libibverbs supports native atomic write"
or
"**a** check for the native atomic write support **in** libibverbs"



_Code quote:_
```Markdown
check if libibverbs supports native atomic write
```


<!-- Sent from Reviewable.io -->

2023-01-03 12:08 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`CHANGELOG.md` line 21 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqmUoL466MValGvk1e:-NKrX3YZ8dWcjtD5QIIv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

"**a** check if libibverbs supports native atomic write"
or
"**a** check for the native atomic write support **in** libibverbs"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-03 12:14 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2085#-NKo8kor4oF-OcALlJo-:-NKrYQZ6AcK04HQ_L6wE:bg7igkv) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Cool.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

___
___
*[`CHANGELOG.md` line 21 at r9](https://reviewable.io/reviews/pmem/rpma/2085#-NKqmUoL466MValGvk1e:-NKrYMGC3zB7ACudL4K4:b-ucfknh) ([raw file](https://github.com/pmem/rpma/blob/7a53e068c7ac88725868ae252b7375cf6abe4065/CHANGELOG.md#L21)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2023-01-03 12:15 UTC, merged

2023-01-03 13:44 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2085#-:-NKrs3W26NOhFflmjsf0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->