common: rename atomic write macro and function
pmem/rpma pull request #2103
Opened 2023-01-28 04:59 UTC by yangx-jy

Both IBV_WR_ATOMIC_WRITE_SUPPORTED and is_ibv_wr_atomic_write_supported() are used to check if libibverbs supports the whole native atomic write instead of ibv_wr_atomic_write() so rename them to the following names: 1) IBV_WR_ATOMIC_WRITE_SUPPORTED => IBV_ATOMIC_WRITE_SUPPORTED 2) is_ibv_wr_atomic_write_supported() => is_ibv_atomic_write_supported()

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

2023-01-30 10:43 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103#-:-NN1GTjpECTrTGQNfQSc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-01-31 15:46 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103#-:-NN7VPug5zkvp6bsoMPX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-01 06:53 UTC, grom72 requested changes
<img class="emoji" title=":lgtm_cancel:" alt=":lgtm_cancel:" align="absmiddle" src="https://reviewable.io/lgtm_cancel.png" height="20" width="61"/> 

> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103#-:-NNAjVAD4aDZjiMp-V9O:b8b79qu)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2103#-NNAjlTZBs_eOTIeUtYc:-NNAjlTZBs_eOTIeUtYd:b-g2r3qm) (no related file):*
Shall we avoid using ``IBV_`` prefix, which is widely used by libibverbs?



_Code quote (from cmake/functions.cmake):_
```CMake
IBV_
```

___


<!-- Sent from Reviewable.io -->

2023-02-01 07:15 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2103#-NNAjlTZBs_eOTIeUtYc:-NNAobOs2Rs4WHAHDeX3:bvswi1a) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we avoid using ``IBV_`` prefix, which is widely used by libibverbs?
</blockquote></details>

Do you want to remove the prefix or use another one?
The prefix means that libibverbs supports native `atomic write` so I prefer to use it.

___


<!-- Sent from Reviewable.io -->

2023-02-01 14:19 UTC, yangx-jy commented
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The problem that I want to avoid in the future is the situation when libibverbs.h will also use such define ...
</blockquote></details>

How about `ATOMIC_WRITE_SUPPORTED`？




<!-- Sent from Reviewable.io -->

2023-02-03 16:44 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2103#-NNAjlTZBs_eOTIeUtYc:-NNN9N1sCoiubvlfJRUn:byh6v2d) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

How about `ATOMIC_WRITE_SUPPORTED`？
</blockquote></details>

RPMA_NATIVE_ATOMIC_WRITE_SUPPORTED?

___


<!-- Sent from Reviewable.io -->

2023-02-03 17:11 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2103#-NNAjlTZBs_eOTIeUtYc:-NNNFeTL7RUFJUETbAbo:b-8fx2u7) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

RPMA_NATIVE_ATOMIC_WRITE_SUPPORTED?
</blockquote></details>

:+1: 

___


<!-- Sent from Reviewable.io -->

2023-02-06 03:41 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2103#-NNAjlTZBs_eOTIeUtYc:-NNZnSUh2yPpctOuiUxF:bsuv9sn) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done, I decided to use NATIVE_ATOMIC_WRITE_SUPPORTED instead because all of macros never use the RPMA prefix.

___


<!-- Sent from Reviewable.io -->

2023-02-06 07:00 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103#-:-NN_Wdg6EzSEYN9B_UFK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-06 07:43 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2103#-:-NN_fR8p6oP2IA5tvVZG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-06 07:45 UTC, merged