Introduce libibverbs flush
pmem/rpma pull request #2104
Opened 2023-02-02 08:18 UTC by yangx-jy

The whole libibverbs flush patch sets have been merged into kernel and rdma-core repo. I think it is time to discuss this PR. ^_^
kernel:        https://lore.kernel.org/linux-rdma/20221206130201.30986-1-lizhijian@fujitsu.com/
rdma-core: https://github.com/linux-rdma/rdma-core/pull/1181 
                   https://github.com/linux-rdma/rdma-core/pull/1307 (This is the PR that fixes a bug)

@grom72 @ldorau 
This PR can be built with BUILD_TESTS=OFF because I have not  written the related unit tests.  In this case, I hope we can discuss the logic about this PR first.

Best Regards,
Xiao Yang

2023-02-06 07:21 UTC, yangx-jy commented
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NNZrODq1TSu0A7h_NrH:b-z5v4fy) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

flush selection should be transparent for the application.
it is internal librpma decision what type of flush shall be used
</blockquote></details>

@grom72 

In my opinion, native flush can ensure that the data is written into PMEM as GPSPM flush does so that it doesn't need to check `pcfg->direct_write_to_pmem`.  I try to make server know if librpma supports native flush by `rpma_utils_ibv_context_is_flush_capable()` and then avoid setting `argv[4]` when librpma supports native flush. 
Do you have any suggestions about it?


<!-- Sent from Reviewable.io -->

2023-02-07 08:47 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 0 of 21 files reviewed, 3 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-07 09:17 UTC, ldorau reviewed
> Reviewed 4 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 4 of 21 files reviewed, 3 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-07 09:34 UTC, ldorau commented
Please add the temporary commit https://github.com/ldorau/rpma/commit/616070d9afcb889fad2b8388b374023a7b3dbeae to disable building the tests.

2023-02-07 09:47 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 4 of 21 files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/include/librpma.h` line 1763 at r2](https://reviewable.io/reviews/pmem/rpma/2104#-NNfGGbp8vF9wxbm28w_:-NNfGGbp8vF9wxbm28wa:b-921rw7) ([raw file](https://github.com/pmem/rpma/blob/170781ae97c3e3661f0f1c1d71e37932aa455d2c/src/include/librpma.h#L1763)):*
> ```objc
> 
> /** 3
>  * rpma_conn_get_direct_write_to_pmem - check if connection supports direct write to PMEM
> ```

We use `PMem` here - please replace all occurrences.



_Code quote:_
```objc
PMEM
```
___
*[`src/include/librpma.h` line 1773 at r2](https://reviewable.io/reviews/pmem/rpma/2104#-NNfFgZOBxsmIg8SAOoJ:-NNfFgZP4Qij-QWvTsB2:b-pqo76c) ([raw file](https://github.com/pmem/rpma/blob/170781ae97c3e3661f0f1c1d71e37932aa455d2c/src/include/librpma.h#L1773)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_get_direct_write_to_pmem() checks the support of the direct write to PMEM
> ```

Maybe ` * rpma_conn_get_direct_write_to_pmem() checks if the connection supports the direct write to PMem.` ?
@grom72 ?



_Code quote:_
```objc
 * rpma_conn_get_direct_write_to_pmem() checks the support of the direct write to PMEM
 * on connection.
```


<!-- Sent from Reviewable.io -->

2023-02-07 09:47 UTC, ldorau reviewed
> Reviewed 1 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 5 of 21 files reviewed, 5 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-07 11:57 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 5 of 21 files reviewed, 5 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NNfhjOf16Xg-SVDDwnK:b-hwphbr) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 

In my opinion, native flush can ensure that the data is written into PMEM as GPSPM flush does so that it doesn't need to check `pcfg->direct_write_to_pmem`.  I try to make server know if librpma supports native flush by `rpma_utils_ibv_context_is_flush_capable()` and then avoid setting `argv[4]` when librpma supports native flush. 
Do you have any suggestions about it?

</blockquote></details>

Native flush support only informs about local RNIC capabilities.
It does not know anything about remote capabilities, which should be delivered (if needed) in a similar way as ``direct_write_to_pmem`` is.


<!-- Sent from Reviewable.io -->

2023-02-07 12:02 UTC, ldorau reviewed
> Reviewed 7 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 12 of 21 files reviewed, 5 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-07 12:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 12 of 21 files reviewed, 6 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NNfvNLF4MqTsTkm0CMA:-NNfvNLF4MqTsTkm0CMB:bumd3wr) (no related file):*
Please add the temporary commit ldorau@616070d to disable building the tests.

___


<!-- Sent from Reviewable.io -->

2023-02-08 02:20 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 9 of 23 files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NNfvNLF4MqTsTkm0CMA:-NNigBJa25u-o-DWURSF:b-wl337v) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the temporary commit ldorau@616070d to disable building the tests.
</blockquote></details>

Done.  Disable building the tests for both github action and circleci.

___
___
*[`src/conn.c` line 568 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLLOd5BMvqYWoGME1:-NNigC_4C2rPApJl5nqu:b-9pbgq0) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/src/conn.c#L568)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should not change the logic here, we should provide a new ``flush`` with ``_execute`` and ``_delete`` functions.
See existing APM solution.
</blockquote></details>

Done.  Provided `rpma_native_flush_new()` and `rpma_native_flush_execute()`.
___
*[`src/peer.c` line 67 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGHT_I4tuJtSvAx7vH:-NNigQkJ0yg1nYAn8Arc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/src/peer.c#L67)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please avoid ``goto`` except in an error situation.
</blockquote></details>

Done.
___
*[`src/include/librpma.h` line 1763 at r2](https://reviewable.io/reviews/pmem/rpma/2104#-NNfGGbp8vF9wxbm28w_:-NNiiG08D_88U60imsB1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/170781ae97c3e3661f0f1c1d71e37932aa455d2c/src/include/librpma.h#L1763)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We use `PMem` here - please replace all occurrences.
</blockquote></details>

Done.
___
*[`src/include/librpma.h` line 1773 at r2](https://reviewable.io/reviews/pmem/rpma/2104#-NNfFgZOBxsmIg8SAOoJ:-NNiiFJG0o79n5_0Wwm8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/170781ae97c3e3661f0f1c1d71e37932aa455d2c/src/include/librpma.h#L1773)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe ` * rpma_conn_get_direct_write_to_pmem() checks if the connection supports the direct write to PMem.` ?
@grom72 ?
</blockquote></details>

Done.
___
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NNil-kv9ethrRDzubfg:b-jg4pv9) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Native flush support only informs about local RNIC capabilities.
It does not know anything about remote capabilities, which should be delivered (if needed) in a similar way as ``direct_write_to_pmem`` is.
</blockquote></details>

Please review the following logic of my implementation.
1) `conn->direct_write_to_pmem` will be set to true by default when native flush is supported.
2) You can query the value of `conn->direct_write_to_pmem` by `rpma_conn_get_direct_write_to_pmem()`.
3) `pcfg->direct_write_to_pmem` on 05-flush-to-persistent/server can be passed to 05-flush-to-persistent/client during connection establishment but it will be ignored if `conn->direct_write_to_pmem` has been true.


<!-- Sent from Reviewable.io -->

2023-02-08 07:27 UTC, ldorau reviewed
> Reviewed 2 of 6 files at r4, 1 of 1 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 13 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2023-02-08 07:28 UTC, ldorau reviewed
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 14 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2023-02-13 08:11 UTC, grom72 requested changes
> Reviewed 2 of 21 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 15 of 23 files reviewed, 2 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/conn.c` line 98 at r7](https://reviewable.io/reviews/pmem/rpma/2104#-NO8iwigExYV1iFZVOZh:-NO8iwigExYV1iFZVOZi:b-ptnirg) ([raw file](https://github.com/pmem/rpma/blob/9cfbfe953ff47e204890c95ffb3467a07975e6ba/src/conn.c#L98)):*
> ```C
> 	conn->flush = flush;
> 	/* set direct_write_to_pmem to ture by default when native flush is supported */
> 	conn->direct_write_to_pmem = is_native_flush_supported;
> ```

I can not agree with this assumption.
``qpx->wr_flush`` says only that the local RDMA HW Interface supports native flush operation (provide a handler for that), but it does not say anything about the remote side.
Please take a look at ``rpma_conn_apply_remote_peer_cfg``.  
When having native flush support, the only thing that change is calling ``flush`` instead of ``read``, but the rest of the logic stays the same.
It is related to how the flush can be implemented on RDMA HW with existing PCIe specs where there is no PCIe.Flush read defined yet, but PCIe.Read is used for flushing the PCIe bus's buffers.
``direct_write_to_pmem`` is a target platform configuration-driven parameter and can not be easily detected by the RDMA HW itself.. 



_Code quote:_
```C
	conn->direct_write_to_pmem = is_native_flush_supported;
```
___
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NO8n1tY8YZkT__-D38W:bj0butk) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Please review the following logic of my implementation.
1) `conn->direct_write_to_pmem` will be set to true by default when native flush is supported.
2) You can query the value of `conn->direct_write_to_pmem` by `rpma_conn_get_direct_write_to_pmem()`.
3) `pcfg->direct_write_to_pmem` on 05-flush-to-persistent/server can be passed to 05-flush-to-persistent/client during connection establishment but it will be ignored if `conn->direct_write_to_pmem` has been true.
</blockquote></details>

We can not assume that when RNIC supports a flush, it also supports flush to perisstency.


<!-- Sent from Reviewable.io -->

2023-02-13 08:12 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 15 of 23 files reviewed, 3 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`examples/05-flush-to-persistent/client.c` line 125 at r2](https://reviewable.io/reviews/pmem/rpma/2104#-NO8pAjBCOaXFgTU_duT:-NO8pAjBCOaXFgTU_duU:bk7m4su) ([raw file](https://github.com/pmem/rpma/blob/170781ae97c3e3661f0f1c1d71e37932aa455d2c/examples/05-flush-to-persistent/client.c#L125)):*
> ```C
> 		goto err_mr_dereg;
> 
> 	/* ignore the remote peer configuration when connection supports direct write to PMEM. */
> ```

We can not ignore remote configuration.



_Code quote:_
```C
ignore the remote peer configuration when connection supports direct write to PMEM
```


<!-- Sent from Reviewable.io -->

2023-02-13 12:59 UTC, yangx-jy commented
*[`src/conn.c` line 98 at r7](https://reviewable.io/reviews/pmem/rpma/2104#-NO8iwigExYV1iFZVOZh:-NO9kVBGDgthCUb2u9Ij:b1xpd7p) ([raw file](https://github.com/pmem/rpma/blob/9cfbfe953ff47e204890c95ffb3467a07975e6ba/src/conn.c#L98)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I can not agree with this assumption.
``qpx->wr_flush`` says only that the local RDMA HW Interface supports native flush operation (provide a handler for that), but it does not say anything about the remote side.
Please take a look at ``rpma_conn_apply_remote_peer_cfg``.  
When having native flush support, the only thing that change is calling ``flush`` instead of ``read``, but the rest of the logic stays the same.
It is related to how the flush can be implemented on RDMA HW with existing PCIe specs where there is no PCIe.Flush read defined yet, but PCIe.Read is used for flushing the PCIe bus's buffers.
``direct_write_to_pmem`` is a target platform configuration-driven parameter and can not be easily detected by the RDMA HW itself.. 
</blockquote></details>

Right, it's not a good solution.  But I think we should get the support of `native flush` on remote side and then pass it to the local side, because `native flush` actually does the flush operation like `GPSPM mode flush`.

How about the following logic:
1) Add the internal API `rpma_peer_get_is_native_flush_supported()`.
```
int rpma_peer_get_is_native_flush_supported(struct rpma_peer *peer)
{
        return peer->is_native_flush_supported;
}
```
2) Extend `rpma_peer_cfg_new()` to accept `struct rpma_peer *peer` argument.
```
int rpma_peer_cfg_new(struct rpma_peer *peer, struct rpma_peer_cfg **pcfg_ptr)
{
       ...

       int is_native_flush_supported = rpma_peer_is_native_flush_supported(peer);

       ...

       /* set default values */

#ifdef ATOMIC_OPERATIONS_SUPPORTED
        atomic_init(&cfg->direct_write_to_pmem, is_native_flush_supported);
#else
       cfg->direct_write_to_pmem = is_native_flush_supported;
#endif /* ATOMIC_OPERATIONS_SUPPORTED */
       *pcfg_ptr = cfg;
        return 0;
}
```
3) Take use of new `rpma_peer_cfg_new()` in `05-flush-to-persistent/server` and ignore the fifth argument if the default direct_write_to_pmem is true.


<!-- Sent from Reviewable.io -->

2023-02-13 13:15 UTC, yangx-jy commented
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NO9tW-EATEWzM0Y7j9u:btkzbeo) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We can not assume that when RNIC supports a flush, it also supports flush to perisstency.
</blockquote></details>

If RNIC supports native flush, it means that kernel on remote side will call `CLWB/SFENCE` instruction to flush data when the perisstency flush request is received.


<!-- Sent from Reviewable.io -->

2023-02-16 06:36 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 8 of 27 files reviewed, 6 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NONpSID71kaxmOQwU5x:b-mte03h) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

If RNIC supports native flush, it means that kernel on remote side will call `CLWB/SFENCE` instruction to flush data when the perisstency flush request is received.
</blockquote></details>

This is valid only for SoftRoCE. It is not valid for RNIC when communication is on the PCIe bus only.
___
*[`src/conn.c` line 98 at r7](https://reviewable.io/reviews/pmem/rpma/2104#-NO8iwigExYV1iFZVOZh:-NONv6z1Clho-fJrymQ3:b-x88f6w) ([raw file](https://github.com/pmem/rpma/blob/9cfbfe953ff47e204890c95ffb3467a07975e6ba/src/conn.c#L98)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Right, it's not a good solution.  But I think we should get the support of `native flush` on remote side and then pass it to the local side, because `native flush` actually does the flush operation like `GPSPM mode flush`.

How about the following logic:
1) Add the internal API `rpma_peer_get_is_native_flush_supported()`.
```
int rpma_peer_get_is_native_flush_supported(struct rpma_peer *peer)
{
        return peer->is_native_flush_supported;
}
```
2) Extend `rpma_peer_cfg_new()` to accept `struct rpma_peer *peer` argument.
```
int rpma_peer_cfg_new(struct rpma_peer *peer, struct rpma_peer_cfg **pcfg_ptr)
{
       ...

       int is_native_flush_supported = rpma_peer_is_native_flush_supported(peer);

       ...

       /* set default values */

#ifdef ATOMIC_OPERATIONS_SUPPORTED
        atomic_init(&cfg->direct_write_to_pmem, is_native_flush_supported);
#else
       cfg->direct_write_to_pmem = is_native_flush_supported;
#endif /* ATOMIC_OPERATIONS_SUPPORTED */
       *pcfg_ptr = cfg;
        return 0;
}
```
3) Take use of new `rpma_peer_cfg_new()` in `05-flush-to-persistent/server` and ignore the fifth argument if the default direct_write_to_pmem is true.
</blockquote></details>

Once again
RDMA native flush w/ HW <> GPSMP flush as in case of GPSM CPU cache is involved but it is not true in case of HW.
We do not need to inform about remote flush support. It will be rejected by remote RNIC in the worst case but only if we have incompatible RNIC on both sides of the connection.


<!-- Sent from Reviewable.io -->

2023-02-16 09:04 UTC, yangx-jy commented
*[`src/conn.c` line 98 at r7](https://reviewable.io/reviews/pmem/rpma/2104#-NO8iwigExYV1iFZVOZh:-NOOPRE7-U9zTOvzuiSE:bfgalte) ([raw file](https://github.com/pmem/rpma/blob/9cfbfe953ff47e204890c95ffb3467a07975e6ba/src/conn.c#L98)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Once again
RDMA native flush w/ HW <> GPSMP flush as in case of GPSM CPU cache is involved but it is not true in case of HW.
We do not need to inform about remote flush support. It will be rejected by remote RNIC in the worst case but only if we have incompatible RNIC on both sides of the connection.
</blockquote></details>

OK, I see.  Let's drop the 7th and 8th patches.  In other words, let's still make application decide the information of remote flush support.


<!-- Sent from Reviewable.io -->

2023-02-16 09:23 UTC, yangx-jy commented
*[`examples/05-flush-to-persistent/client.c` line 125 at r2](https://reviewable.io/reviews/pmem/rpma/2104#-NO8pAjBCOaXFgTU_duT:-NOOVFmv-BUSyb3YleR1:b-6upbsn) ([raw file](https://github.com/pmem/rpma/blob/170781ae97c3e3661f0f1c1d71e37932aa455d2c/examples/05-flush-to-persistent/client.c#L125)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We can not ignore remote configuration.
</blockquote></details>

@grom72 @ldorau 

After dropping the 7th and 8th patches, I hope you can continue reviewing the remaining patches.

Thanks a lot.
Xiao Yang


<!-- Sent from Reviewable.io -->

2023-02-16 09:40 UTC, ldorau reviewed
> Reviewed 1 of 21 files at r2, 3 of 11 files at r8, 2 of 14 files at r9, 6 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 20 of 27 files reviewed, 6 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-17 06:10 UTC, yangx-jy commented
*[`examples/05-flush-to-persistent/server.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/2104#-NNGLosG6A4__nkcIifN:-NOSzPs360zUXVLv2Xbk:b-g0krn9) ([raw file](https://github.com/pmem/rpma/blob/cfce2f73f4e71980f354f99b5988b360cbff8212/examples/05-flush-to-persistent/server.c#L72)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This is valid only for SoftRoCE. It is not valid for RNIC when communication is on the PCIe bus only.
</blockquote></details>

@grom72 @ldorau 

I have added unit tests for NO.2~NO.4 patches and will add other unit tests next week.

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2023-02-21 07:32 UTC, grom72 requested changes
> Reviewed 1 of 7 files at r10, 1 of 11 files at r11, 16 of 19 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 31 of 34 files reviewed, 4 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/utils.c` line 74 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOmnYsk13s9D6thUysU:-NOmnYslEF6DQ1quXysq:b-vmdcoj) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L74)):*
> ```C
> 	if ((attr.device_cap_flags_ex & IB_UVERBS_DEVICE_FLUSH_GLOBAL) &&
> 			(attr.device_cap_flags_ex & IB_UVERBS_DEVICE_FLUSH_PERSISTENT))
> 		*is_flush_capable = 1;
> ```

To avoid ``is_flush_capable`` in case of error



_Suggestion:_
```C
#ifdef NATIVE_FLUSH_SUPPORTED
	/* query an RDMA device's attributes */
	struct ibv_device_attr_ex attr = {{{0}}};
	errno = ibv_query_device_ex(ibv_ctx, NULL /* input */, &attr);
	if (errno) {
		RPMA_LOG_ERROR_WITH_ERRNO(errno, "ibv_query_device_ex(attr={0})");
		return RPMA_E_PROVIDER;
	}

	/* check whether both global visibility and persistence are supported in kernel */
	if ((attr.device_cap_flags_ex & IB_UVERBS_DEVICE_FLUSH_GLOBAL) &&
			(attr.device_cap_flags_ex & IB_UVERBS_DEVICE_FLUSH_PERSISTENT))
		*is_flush_capable = 1;
	else
#endif
		*is_flush_capable = 0;
```


<!-- Sent from Reviewable.io -->

2023-02-21 11:42 UTC, janekmi reviewed
> Reviewed 2 of 21 files at r2, 4 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 33 of 34 files reviewed, 6 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/utils.h` line 34 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnj-HcB5KianCHmZRp:-NOnj-HcB5KianCHmZRq:b-pflgz5) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.h#L34)):*
> ```objc
>  * ibv_ctx != NULL && is_flush_capable != NULL
>  */
> int rpma_utils_ibv_context_is_flush_capable(struct ibv_context *ibv_ctx, int *is_flush_capable);
> ```

This line is a little bit too long.
___
*[`src/utils.c` line 51 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnUjb57E7BgqwvFFAm:-NOnUjb62ptdLUHVKhrp:b-lt1s5m) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L51)):*
> ```C
>  * rpma_utils_ibv_context_is_flush_capable -- query the extended device
>  * context's capabilities and check if kernel supports both of native flush
>  * types(Global visibility and Persistence).
> ```

You missed a space. :grin: 
___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NOnkclG90s5WI_QwueR:b-vuqofv) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
> ```C
> 		.device_cap_flags_ex = 0, /* flush attributes are not set */
> 	};
> 	will_return(ibv_query_device_ex_mock, &attr);
> ```

This mock is under an ifdef right now:

```
#ifdef ON_DEMAND_PAGING_SUPPORTED
int ibv_query_device_ex_mock(struct ibv_context *ibv_ctx,
		const struct ibv_query_device_ex_input *input,
		struct ibv_device_attr_ex *attr,
		size_t attr_size);
#endif
```

I think you should extend the condition:

```
#if defined(ON_DEMAND_PAGING_SUPPORTED) || defined(NATIVE_FLUSH_SUPPORTED)
```

Please apply to both `mocks-ibverbs.h` and `mocks-ibverbs.c`.
___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 67 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnlhrF9VLg9QEWGM8z:-NOnlhrF9VLg9QEWGM9-:bqy9a2r) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L67)):*
> ```C
> 		/* flush attributes are set */
> 		.device_cap_flags_ex = IB_UVERBS_DEVICE_FLUSH_GLOBAL |
> 				IB_UVERBS_DEVICE_FLUSH_PERSISTENT,
> ```

I think you missed a case when only one of these attributes is set.
Probably two cases for each of the attributes.


<!-- Sent from Reviewable.io -->

2023-02-21 12:08 UTC, janekmi reviewed
> Reviewed 7 of 19 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 33 of 34 files reviewed, 8 unresolved discussions (waiting on @ldorau and @yangx-jy)

___
*[`src/peer.c` line 49 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnrbhw7suutCLaep0u:-NOnrbhw7suutCLaep0v:b-9ilyp3) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/peer.c#L49)):*
> ```C
>  */
> static int
> rpma_peer_usage2access(struct rpma_peer *peer, int usage)
> ```

It is a little bit odd that this function does not have a unit test. I recognize it is a little bit special but still.
___
*[`tests/unit/peer/peer-new.c` line 211 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnoFbh7FW5-Vmmw83z:-NOnoFbh7FW5-Vmmw84-:b927c0z) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/peer/peer-new.c#L211)):*
> ```C
> 
> 	/* verify the results */
> 	assert_int_equal(ret, RPMA_E_PROVIDER);
> ```

Can you remind me why we do not validate the `MOCK_ERRNO` value even though it is configured in the test? :thinking: 


<!-- Sent from Reviewable.io -->

2023-02-21 13:31 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 33 of 34 files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[`src/utils.h` line 34 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnj-HcB5KianCHmZRp:-NOo9hJTDbx-7qnwMgHs:b42t9wi) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.h#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line is a little bit too long.
</blockquote></details>

It is OK. It is 96 characters long, while the limit is 100 now.



_Code quote:_
```objc
int rpma_utils_ibv_context_is_flush_capable(struct ibv_context *ibv_ctx, int *is_flush_capable);
```
___
*[`src/utils.c` line 51 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnUjb57E7BgqwvFFAm:-NOoA0Ba63zTPOASjpim:b-2poj4n) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You missed a space. :grin: 
</blockquote></details>

Here: `types(Global`



_Code quote:_
```C
types(Global
```


<!-- Sent from Reviewable.io -->

2023-02-21 13:41 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 33 of 34 files reviewed, 9 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NOoBpdC2VZ7s7uziE1z:-NOoBpdC2VZ7s7uziE2-:b-d3z1up) (no related file):*
@yangx-jy Since you are adding unit tests now, you should turn on building the tests again (remove the `common: disable building tests temporarily` commit), in order to fix the compilation errors first:

```
Consolidate compiler generated dependencies of target ut-conn-apply_remote_peer_cfg
[  2%] Building C object tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/__/common/mocks-rdma_cm.c.o
/home/ldorau/work/rpma/tests/unit/common/mocks-rdma_cm.c:303:1: error: conflicting types for ‘rdma_getaddrinfo’; have ‘int(char *, char *, struct rdma_addrinfo *, struct rdma_addrinfo **)’
  303 | rdma_getaddrinfo(char *node, char *port,
      | ^~~~~~~~~~~~~~~~
In file included from /home/ldorau/work/rpma/tests/unit/common/mocks-rdma_cm.c:9:
/usr/include/rdma/rdma_cma.h:748:5: note: previous declaration of ‘rdma_getaddrinfo’ with type ‘int(const char *, const char *, const struct rdma_addrinfo *, struct rdma_addrinfo **)’
  748 | int rdma_getaddrinfo(const char *node, const char *service,
      |     ^~~~~~~~~~~~~~~~
make[2]: *** [tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/build.make:118: tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/__/common/mocks-rdma_cm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1576: tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```

___


<!-- Sent from Reviewable.io -->

2023-02-22 05:56 UTC, yangx-jy reviewed
I'm so glad to see you again. ^_^
I have updated all unit tests for this PR.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104#-:-NOrBNQiD15HmYqM9xXA:b-9cyys3)* status: 23 of 44 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NOoBpdC2VZ7s7uziE1z:-NOrBakK4WmKXhYewlCV:b-58qykz) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy Since you are adding unit tests now, you should turn on building the tests again (remove the `common: disable building tests temporarily` commit), in order to fix the compilation errors first:

```
Consolidate compiler generated dependencies of target ut-conn-apply_remote_peer_cfg
[  2%] Building C object tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/__/common/mocks-rdma_cm.c.o
/home/ldorau/work/rpma/tests/unit/common/mocks-rdma_cm.c:303:1: error: conflicting types for ‘rdma_getaddrinfo’; have ‘int(char *, char *, struct rdma_addrinfo *, struct rdma_addrinfo **)’
  303 | rdma_getaddrinfo(char *node, char *port,
      | ^~~~~~~~~~~~~~~~
In file included from /home/ldorau/work/rpma/tests/unit/common/mocks-rdma_cm.c:9:
/usr/include/rdma/rdma_cma.h:748:5: note: previous declaration of ‘rdma_getaddrinfo’ with type ‘int(const char *, const char *, const struct rdma_addrinfo *, struct rdma_addrinfo **)’
  748 | int rdma_getaddrinfo(const char *node, const char *service,
      |     ^~~~~~~~~~~~~~~~
make[2]: *** [tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/build.make:118: tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/__/common/mocks-rdma_cm.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1576: tests/unit/conn/CMakeFiles/ut-conn-apply_remote_peer_cfg.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

```
</blockquote></details>

Done. I have updated all unit tests for this PR. ^_^

___
___
*[`src/conn.c` line 3 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnuC6qBCicmuQK5r8K:-NOrBfpl9UdPXG6_5fLV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/conn.c#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To be exact you should use `2021,2023`. 😉
</blockquote></details>

Done.
___
*[`src/mr.c` line 406 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOoP7yHAGo3y5ZSe_qo:-NOrBhpP7fiWsWotYz5B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/mr.c#L406)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

else if
</blockquote></details>

Done.
___
*[`src/mr.c` line 415 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOoQIJuDk1WNRLYbitQ:-NOrdulO9wC0y7qR7RbY:b39u8bz) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/mr.c#L415)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nitpick: I can't find in the spec this function actually returns an errno code on error. Just this funny piece of information:

> If a failure is detected during operation, for instance due to an invalid argument, then ibv_wr_complete() will **return failure** and the entire posting will be aborted.

Can you point me to a piece of code showing it is at least plausible this function returns an errno code?
</blockquote></details>

Let's look at the rxe code in rdma-core.
`ibv_wr_complete()` calls `post_send_db()` to do a doorbell and `ibv_post_send()` does the same operation at the end.
The return value (errno) comes from post_send_db().
```
providers/rxe/rxe.c:
static int wr_complete(struct ibv_qp_ex *ibqp)
{
        int ret;
        struct rxe_qp *qp = container_of(ibqp, struct rxe_qp, vqp.qp_ex);

        if (qp->err) {
                pthread_spin_unlock(&qp->sq.lock);
                return qp->err;
        }

        store_producer_index(qp->sq.queue, qp->cur_index);
        ret = post_send_db(&qp->vqp.qp);

        pthread_spin_unlock(&qp->sq.lock);
        return ret;
}
...
static int rxe_post_send(struct ibv_qp *ibqp,
                         struct ibv_send_wr *wr_list,
                         struct ibv_send_wr **bad_wr)
{
        int rc = 0;
        int err;
        struct rxe_qp *qp = to_rqp(ibqp);
        struct rxe_wq *sq = &qp->sq;

        if (!bad_wr)
                return EINVAL;

        *bad_wr = NULL;

        if (!sq || !wr_list || !sq->queue)
                return EINVAL;

        pthread_spin_lock(&sq->lock);

        while (wr_list) {
                rc = post_one_send(qp, sq, wr_list);
                if (rc) {
                        *bad_wr = wr_list;
                        break;
                }

                wr_list = wr_list->next;
        }

        pthread_spin_unlock(&sq->lock);

        err =  post_send_db(ibqp);
        return err ? err : rc;
}
```
___
*[`src/peer.c` line 49 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnrbhw7suutCLaep0u:-NOrBq_U-FXD1Y0firni:b-f3fop2) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/peer.c#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is a little bit odd that this function does not have a unit test. I recognize it is a little bit special but still.
</blockquote></details>

As lukasz said, the limit is 100 now so it is OK.
___
*[`src/utils.c` line 51 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnUjb57E7BgqwvFFAm:-NOrF88tDDM7czL_AMrS:b8d1ald) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Here: `types(Global`
</blockquote></details>

Do you mean that I should add a space between `types` and `(`?
I also think it is OK here.
___
*[`src/utils.c` line 74 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOmnYsk13s9D6thUysU:-NOrFUzk2pyi9Kg8udSv:b-3who0o) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L74)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

To avoid ``is_flush_capable`` in case of error
</blockquote></details>

I think it is not needed because it has been set at the beginning of `rpma_utils_ibv_context_is_flush_capable()`
___
*[`tests/unit/common/mocks-rpma-utils.h` line 3 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnthQb0xc33obJtdDH:-NOrZKya8kB4o1FpgrpO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/common/mocks-rpma-utils.h#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

2022-2023
</blockquote></details>

Done.
___
*[`tests/unit/peer/peer-new.c` line 211 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnoFbh7FW5-Vmmw83z:-NOraQ_q8KR6q9kwS_rc:b-cdgdot) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/peer/peer-new.c#L211)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you remind me why we do not validate the `MOCK_ERRNO` value even though it is configured in the test? :thinking: 
</blockquote></details>

In my mind, errno is used in log so we just validate the return value, right?
___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NOrZRdJCUn1_4g9j3Xy:b-m5rzic) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This mock is under an ifdef right now:

```
#ifdef ON_DEMAND_PAGING_SUPPORTED
int ibv_query_devic [...]

2023-02-22 09:20 UTC, ldorau reviewed
> Reviewed 1 of 11 files at r11, 2 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 25 of 44 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`src/utils.c` line 51 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnUjb57E7BgqwvFFAm:-NOsPi3u6o6o2Nv8kOpH:b-mysxgz) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L51)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Do you mean that I should add a space between `types` and `(`?
I also think it is OK here.
</blockquote></details>

I suppose that @janekmi meant  a space between `types` and `(`.


<!-- Sent from Reviewable.io -->

2023-02-25 06:23 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 24 of 44 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[`src/mr.c` line 406 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOoP7yHAGo3y5ZSe_qo:-NP6EFO2-k9OhzhUT3ln:bubqx1p) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/mr.c#L406)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I used the ternary operator instead.
___
*[`src/utils.c` line 51 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnUjb57E7BgqwvFFAm:-NP5MEDZA5NvoLQSDdlQ:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/utils.c#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I suppose that @janekmi meant  a space between `types` and `(`.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-25 17:47 UTC, janekmi reviewed
> Reviewed 2 of 21 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 25 of 44 files reviewed, 5 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[`src/mr.c` line 406 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOoP7yHAGo3y5ZSe_qo:-NP8cmsC0_tn_Pq991AH:b-tvppek) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/mr.c#L406)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I used the ternary operator instead.
</blockquote></details>

TBH, In my opinion, this kind of condition makes it harder to follow. Can we agree on using a switch-case instead?


<!-- Sent from Reviewable.io -->

2023-02-26 00:20 UTC, janekmi reviewed
> Reviewed 11 of 21 files at r13, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 38 of 44 files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`src/peer.c` line 49 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnrbhw7suutCLaep0u:-NP8gD6h6cq-tjrPizuE:bp73bph) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/peer.c#L49)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

As lukasz said, the limit is 100 now so it is OK.
</blockquote></details>

If you mean the length of a line limit I guess this comment is related to something else than I asked about. 😅
___
*[`tests/unit/peer/peer-new.c` line 211 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnoFbh7FW5-Vmmw83z:-NPA4wMrBGgakTvfFE9F:bnhtqu4) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/peer/peer-new.c#L211)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

In my mind, errno is used in log so we just validate the return value, right?
</blockquote></details>

You are right. Thanks!


<!-- Sent from Reviewable.io -->

2023-02-26 00:26 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 38 of 44 files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NP8esI-2vCum_K4A0LF:bp5pq1n) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Why do I need to extend the condition?  Sorry, it is not clear for me.
</blockquote></details>

Maybe I am wrong, but in case `ON_DEMAND_PAGING_SUPPORTED == false` and `NATIVE_FLUSH_SUPPORTED == true` I guess this code would not compile.

Because this code will try to configure a mock which is excluded from the source. Is this correct?


<!-- Sent from Reviewable.io -->

2023-02-26 00:48 UTC, janekmi reviewed
> Reviewed 2 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 40 of 44 files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-26 13:44 UTC, janekmi reviewed
> Reviewed 1 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 41 of 44 files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-26 14:22 UTC, janekmi reviewed
> Reviewed 1 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 42 of 44 files reviewed, 7 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NPD0X-p8CkonirwuSHU:bw7glle) (no related file):*
What will be tested heavily depends on what will be detected in the system on build time. Did we make sure that we build all sensible combinations of supported/unsupported features so all the unit tests are covered by the CI?

___
___
*[`tests/unit/mr/mr-flush.c` line 51 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPCz9Jn0ykI7gigyPXD:-NPCz9Jn0ykI7gigyPXE:bntlwv3) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/mr/mr-flush.c#L51)):*
> ```C
>  */
> static void
> flush__COMPL_ON_ERROR_failed_E_PROVIDER(void **mrs_ptr)
> ```

These pairs are chosen arbitrarily or there is some undisclosed wisdom behind them?

|FLUSH_TYPE|COMPLETION|result|
|---|---|---|
|VISIBILITY |ON_ERROR |E_PROVIDER|
|PERSISTENT|ALWAYS|E_PROVIDER|
|VISIBILITY|ALWAYS|👍|
|PERSISTENT|ON_ERROR|👍|
___
*[`tests/unit/peer/peer-mr_reg.c` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPD4iUbAKTCUI19OtVn:-NPD4iUbAKTCUI19OtVo:b5m9r4j) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/peer/peer-mr_reg.c#L23)):*
> ```C
> 
> static struct prestate prestates[] = {
> 	/* 0-1) non-iWARP and iWARP are the same */
> ```

Can somebody explain to me in what sense "non-iWARP and iWARP are the same"?


<!-- Sent from Reviewable.io -->

2023-02-26 14:24 UTC, janekmi reviewed
> Reviewed 1 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 43 of 44 files reviewed, 6 unresolved discussions (waiting on @grom72 and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-02-27 07:08 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 39 of 44 files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NPGe0u_40F87UaBbRwW:b7z3u5t) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What will be tested heavily depends on what will be detected in the system on build time. Did we make sure that we build all sensible combinations of supported/unsupported features so all the unit tests are covered by the CI?
</blockquote></details>

It's my fault, I didn't cover the combination (ON_DEMAND_PAGING_SUPPORTED is not defined and NATIVE_ATOMIC_WRITE_SUPPORTED /NATIVE_FLUSH_SUPPORTED is defined).  I will add the combination on my local test environment.

___
___
*[`src/mr.c` line 406 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOoP7yHAGo3y5ZSe_qo:-NPGSZCtE-xZov5AKxgU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/mr.c#L406)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH, In my opinion, this kind of condition makes it harder to follow. Can we agree on using a switch-case instead?
</blockquote></details>

Done.
___
*[`src/peer.c` line 49 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnrbhw7suutCLaep0u:-NPGS_lRCRIbJOUE9TXR:be55uqg) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/src/peer.c#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If you mean the length of a line limit I guess this comment is related to something else than I asked about. 😅
</blockquote></details>

Sorry, I added the wrong answer to the comment. ^_^
It's OK because the code logic of `rpma_peer_usage2access()` has been tested by `tests/unit/peer/peer-mr_reg.c`.
If you want to factor out unit tests for `rpma_peer_usage2access()`, we can do it by a separate patch.
___
*[`tests/unit/mr/mr-flush.c` line 51 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPCz9Jn0ykI7gigyPXD:-NPGYQ8uAD8_kAUpZdiS:b-an462y) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/mr/mr-flush.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These pairs are chosen arbitrarily or there is some undisclosed wisdom behind them?

|FLUSH_TYPE|COMPLETION|result|
|---|---|---|
|VISIBILITY |ON_ERROR |E_PROVIDER|
|PERSISTENT|ALWAYS|E_PROVIDER|
|VISIBILITY|ALWAYS|👍|
|PERSISTENT|ON_ERROR|👍|
</blockquote></details>

I just wanted to cover all logic of code by adding fewer unit tests.
Do you mean that we should add all combinations for flush type, completion flags and results? like this:
```
VISIBILITY	ON_ERROR	E_PROVIDER
VISIBILITY	ALWAYS	        E_PROVIDER
PERSISTENT	ON_ERROR	E_PROVIDER
PERSISTENT	ALWAYS	        E_PROVIDER
VISIBILITY	ON_ERROR	OK
VISIBILITY	ALWAYS	        OK
PERSISTENT	ON_ERROR	OK
PERSISTENT	ALWAYS	        OK
```
___
*[`tests/unit/peer/peer-mr_reg.c` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPD4iUbAKTCUI19OtVn:-NPGcgUY8X_2lDpy2ztc:b-ol08dc) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/peer/peer-mr_reg.c#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can somebody explain to me in what sense "non-iWARP and iWARP are the same"?
</blockquote></details>

You can refer to the conversion of `RPMA_MR_USAGE_READ_DST`.
It will be converted to different IBV_XXX macros (e.g. IBV_ACCESS_LOCAL_WRITE based on IB、IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_WRITE based on IWRAP).
___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NPGXDchBXAakZRx51jr:b5h6kji) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe I am wrong, but in case `ON_DEMAND_PAGING_SUPPORTED == false` and `NATIVE_FLUSH_SUPPORTED == true` I guess this code would not compile.

Because this code will try to configure a mock which is excluded from the source. Is this correct?
</blockquote></details>

Done.  Sorry, you are correct. I didn't run all unit tests when ON_DEMAND_PAGING_SUPPORTED is not defined and NATIVE_ATOMIC_WRITE_SUPPORTED /NATIVE_FLUSH_SUPPORTED is defined.


<!-- Sent from Reviewable.io -->

2023-02-27 08:31 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 39 of 44 files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`tests/unit/peer/peer-mr_reg.c` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPD4iUbAKTCUI19OtVn:-NPGtdsp7z-kX-nBq_XE:b-xulq4n) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/peer/peer-mr_reg.c#L23)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

You can refer to the conversion of `RPMA_MR_USAGE_READ_DST`.
It will be converted to different IBV_XXX macros (e.g. IBV_ACCESS_LOCAL_WRITE based on IB、IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_WRITE based on IWRAP).
</blockquote></details>

@janekmi  It's a misleading and invalid mental shortcut ;-) I agree it makes no sense :-)
I meant here: "the values of the prestate for indexes 0-1 for both non-iWARP (IBV_TRANSPORT_IB) and iWARP (IBV_TRANSPORT_IWARP) are the same".

See: https://github.com/pmem/rpma/pull/2107



_Code quote:_
```C
non-iWARP and iWARP are the same
```


<!-- Sent from Reviewable.io -->

2023-02-27 11:31 UTC, grom72 reviewed
> Reviewed 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 43 of 44 files reviewed, 5 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2023-02-27 11:32 UTC, grom72 approved these changes
> Reviewed 1 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2023-02-27 12:28 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NPHpigg4GMk1MNQuhYZ:b25uz8q) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.  Sorry, you are correct. I didn't run all unit tests when ON_DEMAND_PAGING_SUPPORTED is not defined and NATIVE_ATOMIC_WRITE_SUPPORTED /NATIVE_FLUSH_SUPPORTED is defined.
</blockquote></details>

Fixed by https://github.com/pmem/rpma/pull/2106


<!-- Sent from Reviewable.io -->

2023-02-28 13:07 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @janekmi and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPN6bTM08pJKnoxr0CZ:-NPN6bTM08pJKnoxr0C_:b-oaa2tz) (no related file):*
This PR should not be merged until the CI is updated to support both native atomic write and native flush (see https://github.com/pmem/rpma/pull/2108). Currently the new code is not built on the CI.

___


<!-- Sent from Reviewable.io -->

2023-03-06 07:45 UTC, grom72 reviewed
> Reviewed 3 of 4 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 45 files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[`tests/unit/mr/mr-flush.c` line 51 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPCz9Jn0ykI7gigyPXD:-NPps4pjEjc2OM-P7Ubr:bb77ufg) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/mr/mr-flush.c#L51)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I just wanted to cover all logic of code by adding fewer unit tests.
Do you mean that we should add all combinations for flush type, completion flags and results? like this:
```
VISIBILITY	ON_ERROR	E_PROVIDER
VISIBILITY	ALWAYS	        E_PROVIDER
PERSISTENT	ON_ERROR	E_PROVIDER
PERSISTENT	ALWAYS	        E_PROVIDER
VISIBILITY	ON_ERROR	OK
VISIBILITY	ALWAYS	        OK
PERSISTENT	ON_ERROR	OK
PERSISTENT	ALWAYS	        OK
```
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2023-03-06 07:46 UTC, grom72 approved these changes
> Reviewed 1 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-06 12:22 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[`tests/unit/peer/peer-mr_reg.c` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPD4iUbAKTCUI19OtVn:-NPqrkHi6sQ6KNN1-zSP:b-9jmk4c) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/peer/peer-mr_reg.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi  It's a misleading and invalid mental shortcut ;-) I agree it makes no sense :-)
I meant here: "the values of the prestate for indexes 0-1 for both non-iWARP (IBV_TRANSPORT_IB) and iWARP (IBV_TRANSPORT_IWARP) are the same".

See: https://github.com/pmem/rpma/pull/2107
</blockquote></details>

@janekmi Fixed on master by https://github.com/pmem/rpma/pull/2107 (merged)


<!-- Sent from Reviewable.io -->

2023-03-07 04:50 UTC, yangx-jy commented
*[`tests/unit/mr/mr-flush.c` line 51 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPCz9Jn0ykI7gigyPXD:-NPuOtco9fvtWmESUdi4:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/mr/mr-flush.c#L51)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-13 11:16 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 42 of 45 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPN6bTM08pJKnoxr0CZ:-NQPfsbFAvtzkSgQdQMO:bwpo9dp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This PR should not be merged until the CI is updated to support both native atomic write and native flush (see https://github.com/pmem/rpma/pull/2108). Currently the new code is not built on the CI.
</blockquote></details>

https://github.com/pmem/rpma/pull/2119 has just been merged.

Rebase please.

___


<!-- Sent from Reviewable.io -->

2023-03-13 11:25 UTC, grom72 approved these changes
> Reviewed 2 of 3 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-13 11:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 45 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPN6bTM08pJKnoxr0CZ:-NQPmvsjCOnVCzOdjEt_:bb6un1j) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/pull/2119 has just been merged.

Rebase please.
</blockquote></details>

Done

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NQPPWYS8uaczSy8iMOY:-NQPmywz0LFmxIrOM0Ev:b-y3hu8d) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds fail with rdma-core v45: https://github.com/ldorau/rpma/actions/runs/4403442903
</blockquote></details>

Works now

___


<!-- Sent from Reviewable.io -->

2023-03-13 11:48 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 45 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`tests/unit/peer/peer-mr_reg.c` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPD4iUbAKTCUI19OtVn:-NQPnF0G75j4Zf_cHwLD:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/peer/peer-mr_reg.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi Fixed on master by https://github.com/pmem/rpma/pull/2107 (merged)
</blockquote></details>

Done
___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NQPnIYo1fBn_oAQQm3C:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Fixed by https://github.com/pmem/rpma/pull/2106
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-03-13 11:57 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 45 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`tests/unit/peer/peer-mr_reg.c` line 23 at r14](https://reviewable.io/reviews/pmem/rpma/2104#-NPD4iUbAKTCUI19OtVn:-NQPpEQt9H8Orxg8dXjd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/055145d7cbc12a89762ae0ae34a9967c7ec66816/tests/unit/peer/peer-mr_reg.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`tests/unit/utils/utils-ibv_context_is_flush_capable.c` line 26 at r12](https://reviewable.io/reviews/pmem/rpma/2104#-NOnkclG90s5WI_QwueQ:-NQPpDSb26FV2zBNlFuT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eb57bdd361844a59f30ad491f6ca8c5065e6cab1/tests/unit/utils/utils-ibv_context_is_flush_capable.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-13 12:01 UTC, ldorau approved these changes

2023-03-13 12:52 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 45 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQQ0rU16fipuSCzPW4S:by07wad) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It's my fault, I didn't cover the combination (ON_DEMAND_PAGING_SUPPORTED is not defined and NATIVE_ATOMIC_WRITE_SUPPORTED /NATIVE_FLUSH_SUPPORTED is defined).  I will add the combination on my local test environment.
</blockquote></details>

Yes, this has to be fixed too. See: https://github.com/pmem/rpma/pull/2122

___


<!-- Sent from Reviewable.io -->

2023-03-13 12:55 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 45 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQQ1MHfBeH8vHpvT5UF:bd3k53w) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, this has to be fixed too. See: https://github.com/pmem/rpma/pull/2122
</blockquote></details>

Builds fail in this case: https://github.com/pmem/rpma/actions/runs/4405090883/jobs/7715541372

___


<!-- Sent from Reviewable.io -->

2023-03-13 13:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 42 of 45 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[`CHANGELOG.md` line 13 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQFPQG4TytThJLWEq5:-NQQFPQG4TytThJLWEq6:b-5b6b5x) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/CHANGELOG.md#L13)):*
> ```Markdown
> ### Added
> - native atomic write support (required support in the kernel and in an RNIC's driver)
> - native flush support (required support in the kernel and in an RNIC's driver)
> ```

All changes in this file should always be added only in the "Unreleased" section. See: https://github.com/pmem/rpma/pull/2124/files


<!-- Sent from Reviewable.io -->

2023-03-13 14:01 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 42 of 45 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQQGQeYDOcdWcW-FFMq:bi63o1f) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds fail in this case: https://github.com/pmem/rpma/actions/runs/4405090883/jobs/7715541372
</blockquote></details>

Could you confirm if #2123 can fix the compiler error?

___
___
*[`CHANGELOG.md` line 13 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQFPQG4TytThJLWEq5:-NQQGd-j5ZtdDe4unnql:biuouh2) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/CHANGELOG.md#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All changes in this file should always be added only in the "Unreleased" section. See: https://github.com/pmem/rpma/pull/2124/files
</blockquote></details>

OK, I will update it as soon as possible.


<!-- Sent from Reviewable.io -->

2023-03-13 14:12 UTC, janekmi reviewed
> Reviewed 1 of 4 files at r15, 3 of 4 files at r17, 1 of 3 files at r18, 1 of 1 files at r20, 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[`tests/unit/mr/mr-flush.c` line 95 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQIbuz-nlL1C0R7BVm:-NQQIbuz-nlL1C0R7BVn:bg4y7pf) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/tests/unit/mr/mr-flush.c#L95)):*
> ```C
> 		assert_int_equal(ret, RPMA_E_PROVIDER);
> 	}
> }
> ```

These two cases are basically the same:

- flush__COMPL_ON_ERROR_failed_E_PROVIDER
- flush__COMPL_ON_SUCCESS_failed_E_PROVIDER

Can we cover both of them by introducing another for-loop? :thinking: 
___
*[`tests/unit/mr/mr-flush.c` line 139 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQIwdP6ALL3OnmUHBy:-NQQIwdP6ALL3OnmUHBz:b55pvq6) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/tests/unit/mr/mr-flush.c#L139)):*
> ```C
> 		assert_int_equal(ret, MOCK_OK);
> 	}
> }
> ```

The same question for these two cases:

- flush__COMPLETION_ON_ERROR_success
- flush__COMPLETION_ALWAYS_success


<!-- Sent from Reviewable.io -->

2023-03-13 14:21 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQQLHwhDCMDPzG_IrKe:b-yhymnq) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Could you confirm if #2123 can fix the compiler error?
</blockquote></details>

There is still an error: https://github.com/ldorau/rpma/actions/runs/4405938979/jobs/7717494188

___
___
*[`CHANGELOG.md` line 13 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQFPQG4TytThJLWEq5:-NQQL2Kn8oBLnNH9CVZ0:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/CHANGELOG.md#L13)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

OK, I will update it as soon as possible.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2023-03-13 14:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQQLQJU8FDFgxFoE4oq:b-324z6x) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is still an error: https://github.com/ldorau/rpma/actions/runs/4405938979/jobs/7717494188
</blockquote></details>

@yangx-jy NOTICE that this error occurs on master, not on this PR.

___


<!-- Sent from Reviewable.io -->

2023-03-13 15:11 UTC, yangx-jy commented
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy NOTICE that this error occurs on master, not on this PR.
</blockquote></details>

Please see #2122 




<!-- Sent from Reviewable.io -->

2023-03-13 16:21 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 43 of 45 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[`CHANGELOG.md` line 13 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQFPQG4TytThJLWEq5:-NQQlaeM1XcIerwkpF7D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/CHANGELOG.md#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.
___
*[`tests/unit/mr/mr-flush.c` line 95 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQIbuz-nlL1C0R7BVm:-NQQld0i9nh8e0c7HQaj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/tests/unit/mr/mr-flush.c#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two cases are basically the same:

- flush__COMPL_ON_ERROR_failed_E_PROVIDER
- flush__COMPL_ON_SUCCESS_failed_E_PROVIDER

Can we cover both of them by introducing another for-loop? :thinking: 
</blockquote></details>

Done.
___
*[`tests/unit/mr/mr-flush.c` line 139 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQIwdP6ALL3OnmUHBy:-NQQleZm1hpsfL_Qzaxf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/tests/unit/mr/mr-flush.c#L139)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The same question for these two cases:

- flush__COMPLETION_ON_ERROR_success
- flush__COMPLETION_ALWAYS_success
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 08:31 UTC, ldorau requested changes
> Reviewed 2 of 21 files at r13, 3 of 4 files at r23.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 46 files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQUEUix9gWLbS4GYu1g:b-tx1shs) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Please see #2122 
</blockquote></details>

OK. https://github.com/pmem/rpma/pull/2122 and https://github.com/pmem/rpma/pull/2125 should be merged before this PR

___
___
*[`CHANGELOG.md` line 16 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDFcBCnfhtCygfqCe:-NQUDFcBCnfhtCygfqCf:bq35g5r) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L16)):*
> ```Markdown
>   and native flush) on Ubuntu-latest and Fedora-latest CIs
> - internal APIs:
>   - rpma_utils_ibv_context_is_flush_capable() - checks if kernel supports native flush
> ```

the native flush



_Code quote:_
```Markdown
native flush
```
___
*[`CHANGELOG.md` line 17 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDKdL3PjirZ-acSc4:-NQUDKdL3PjirZ-acSc5:b-u9z19) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L17)):*
> ```Markdown
> - internal APIs:
>   - rpma_utils_ibv_context_is_flush_capable() - checks if kernel supports native flush
> - a option for cmake to disable support for native flush in libibverbs
> ```

an option



_Code quote:_
```Markdown
a option
```
___
*[`CHANGELOG.md` line 17 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDP-089LrKh9-Xrhr:-NQUDP-089LrKh9-Xrhs:bq35g5r) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L17)):*
> ```Markdown
> - internal APIs:
>   - rpma_utils_ibv_context_is_flush_capable() - checks if kernel supports native flush
> - a option for cmake to disable support for native flush in libibverbs
> ```

the native flush



_Code quote:_
```Markdown
native flush
```
___
*[`CHANGELOG.md` line 32 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUD_JF40KkFOTxT94M:-NQUD_JF40KkFOTxT94N:bq35g5r) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L32)):*
> ```Markdown
>   required for Rocky Linux 8 and 9 and verify if the installation succeeded
> - rpma_peer_new() to check the native flush support in kernel
> - rpma_peer_setup_qp() to enable native flush if both kernel and libibverbs supported it
> ```

the native flush



_Code quote:_
```Markdown
native flush
```
___
*[`CHANGELOG.md` line 32 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDdUh8iYW_fezonjb:-NQUDdUh8iYW_fezonjc:b4v29ey) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L32)):*
> ```Markdown
>   required for Rocky Linux 8 and 9 and verify if the installation succeeded
> - rpma_peer_new() to check the native flush support in kernel
> - rpma_peer_setup_qp() to enable native flush if both kernel and libibverbs supported it
> ```

support



_Code quote:_
```Markdown
supported
```
___
*[`CHANGELOG.md` line 33 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDrPIDt6OqmvRTfUF:-NQUDrPIDt6OqmvRTfUG:b3v4ev4) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L33)):*
> ```Markdown
> - rpma_peer_new() to check the native flush support in kernel
> - rpma_peer_setup_qp() to enable native flush if both kernel and libibverbs supported it
> - rpma_peer_usage2access() to return native access flags if both kernel and libibverbs supported native flush
> ```

support the native flush



_Code quote:_
```Markdown
supported native flush
```
___
*[`CHANGELOG.md` line 34 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDxcrEegGujxZh7kK:-NQUDxcrEegGujxZh7kL:bq35g5r) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L34)):*
> ```Markdown
> - rpma_peer_setup_qp() to enable native flush if both kernel and libibverbs supported it
> - rpma_peer_usage2access() to return native access flags if both kernel and libibverbs supported native flush
> - rpma_flush() to use native flush if the created QP supported it
> ```

the native flush



_Code quote:_
```Markdown
native flush
```
___
*[`CHANGELOG.md` line 34 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUE-Ul42Gp1f-QQHUA:-NQUE-Ul42Gp1f-QQHUB:b8oq009) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L34)):*
> ```Markdown
> - rpma_peer_setup_qp() to enable native flush if both kernel and libibverbs supported it
> - rpma_peer_usage2access() to return native access flags if both kernel and libibverbs supported native flush
> - rpma_flush() to use native flush if the created QP supported it
> ```

supports



_Code quote:_
```Markdown
supported
```


<!-- Sent from Reviewable.io -->

2023-03-14 08:44 UTC, ldorau reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 46 files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-14 09:02 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 46 files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQULq0gDOZ4jmht4yP1:b-tv8b59) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK. https://github.com/pmem/rpma/pull/2122 and https://github.com/pmem/rpma/pull/2125 should be merged before this PR
</blockquote></details>

#2122 and #2125 are merged.

Rebase please.

___


<!-- Sent from Reviewable.io -->

2023-03-14 09:28 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 44 of 46 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[`utils/docker/run-build.sh` line 165 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQURc1D7kKgIPZdLYZ8:-NQURc1D7kKgIPZdLYZ9:buv6ggn) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/utils/docker/run-build.sh#L165)):*
> ```Shell
> rm -rf $WORKDIR/build
> 
> echo
> ```

Please move it here: https://github.com/pmem/rpma/blob/main/utils/docker/run-build.sh#L235


<!-- Sent from Reviewable.io -->

2023-03-14 09:28 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r23.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 45 of 46 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-14 09:46 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 38 of 46 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2104#-NPD0X-p8CkonirwuSHT:-NQUToXDCOfxw_K_qQWW:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

#2122 and #2125 are merged.

Rebase please.

</blockquote></details>

Done.

___
___
*[`CHANGELOG.md` line 16 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDFcBCnfhtCygfqCe:-NQUU6ka3ZMZaLGRQ9Gx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the native flush
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 17 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDKdL3PjirZ-acSc4:-NQUUBF66WuxwTuyjyBn:b9ww2un) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

an option
</blockquote></details>

Done. Use the `BUILD_FORCE_NATIVE_FLUSH_NOT_SUPPORTED CMake option`.
___
*[`CHANGELOG.md` line 17 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDP-089LrKh9-Xrhr:-NQUVqNGEIk41T-N3Wk7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the native flush
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 32 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUD_JF40KkFOTxT94M:-NQUUORU-jGCvbb_573m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the native flush
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 32 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDdUh8iYW_fezonjb:-NQUUPRz00EImqwWAPP_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

support
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 33 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDrPIDt6OqmvRTfUF:-NQUUR5zEbmpZIFD5QiS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

support the native flush
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 34 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUDxcrEegGujxZh7kK:-NQUUSfFEGD_YUqzWoyr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the native flush
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 34 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQUE-Ul42Gp1f-QQHUA:-NQUUTtyBiwlKNsGCIUb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/CHANGELOG.md#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

supports
</blockquote></details>

Done.
___
*[`utils/docker/run-build.sh` line 165 at r23](https://reviewable.io/reviews/pmem/rpma/2104#-NQURc1D7kKgIPZdLYZ8:-NQUUVgiDKbzBTgjNra4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eaf7fb5ebc40243b7c7421659b43630390ef4a37/utils/docker/run-build.sh#L165)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please move it here: https://github.com/pmem/rpma/blob/main/utils/docker/run-build.sh#L235
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-14 09:52 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r19, 7 of 7 files at r24, 3 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 45 of 46 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2023-03-14 09:54 UTC, ldorau approved these changes

2023-03-14 09:56 UTC, ldorau approved these changes
> Reviewed 1 of 19 files at r12, 2 of 21 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 45 of 46 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2023-03-14 10:11 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104)* status: 45 of 46 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[`tests/unit/mr/mr-flush.c` line 139 at r21](https://reviewable.io/reviews/pmem/rpma/2104#-NQQIwdP6ALL3OnmUHBy:-NQUaWU-E4MJnyCZSH2N:b-3p17t8) ([raw file](https://github.com/pmem/rpma/blob/0208220355989df2fe5d601f4767ac7abcf3bad5/tests/unit/mr/mr-flush.c#L139)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi ping


<!-- Sent from Reviewable.io -->

2023-03-14 10:34 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 11 files at r8, 1 of 21 files at r13, 1 of 2 files at r21, 1 of 2 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104#-:-NQUfoN4DW0RljEqzw8b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2023-03-14 10:40 UTC, janekmi reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r22, 1 of 3 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104#-:-NQUhBqGCNwnKV9X47_a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-14 10:44 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 8 of 19 files at r12, 8 of 21 files at r13, 1 of 2 files at r14, 1 of 4 files at r15, 2 of 4 files at r17, 1 of 3 files at r18, 1 of 2 files at r21, 1 of 2 files at r22.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2104#-:-NQUi5wO5ZrFeQXDighG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-14 10:45 UTC, merged