common: use _CFLAGS and _LDFLAGS of libraries
pmem/rpma pull request #2116
Opened 2023-03-09 14:53 UTC by ldorau

Use:
- LIBIBVERBS_CFLAGS, LIBIBVERBS_LDFLAGS,
- LIBRDMACM_CFLAGS and LIBRDMACM_LDFLAGS
in order to be able to locate libibverbs and librdmacm
when they are installed from sources in a non-default location.

2023-03-09 14:58 UTC, grom72 approved these changes
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2023-03-09 14:58 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2023-03-09 18:21 UTC, osalyk requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`cmake/functions.cmake` line 226 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ6aLYEBAOuUuhH0tRw:-NQ6aLYEBAOuUuhH0tRx:b-rkunj) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/cmake/functions.cmake#L226)):*
> ```CMake
> 	if(C_HAS_Werror_discarded_qualifiers)
> 		set(CMAKE_REQUIRED_FLAGS "${DISCARDED_QUALIFIERS_FLAG};${CMAKE_REQUIRED_FLAGS}")
> 		set(CMAKE_REQUIRED_LIBRARIES "${LIBRDMACM_LDFLAGS};${LIBRDMACM_LIBRARIES};${CMAKE_REQUIRED_LIBRARIES}")
> ```

Shouldn't the ${LIBRDMACM_LDFLAGS} variable be higher up?



_Suggestion:_
```CMake
		set(CMAKE_REQUIRED_FLAGS "${LIBRDMACM_LDFLAGS};${DISCARDED_QUALIFIERS_FLAG};${CMAKE_REQUIRED_FLAGS}")
		set(CMAKE_REQUIRED_LIBRARIES "${LIBRDMACM_LIBRARIES};${CMAKE_REQUIRED_LIBRARIES}")
```


<!-- Sent from Reviewable.io -->

2023-03-10 03:33 UTC, yangx-jy commented
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQ8YvLT3a83qKqVFROB:bas5z7o) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
> ```CMake
> 	target_link_libraries(${name}
> 		rpma
> 		${LIBIBVERBS_LDFLAGS} ${LIBIBVERBS_LIBRARIES}
> ```

@ldorau 

Is it necessary to add `${LIBIBVERBS_LDFLAGS}` here?
If `${LIBIBVERBS_LIBRARIES}` is defined, it means that `cmake` can find the ibverbs library by searching the default path.
In my opinion, we just need to set CMAKE_PREFIX_PATH to point the location as `FindLIBRDMACM.cmake` and `FindLIBIBVERBS.cmake` describe.


<!-- Sent from Reviewable.io -->

2023-03-10 05:59 UTC, osalyk approved these changes
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`cmake/functions.cmake` line 226 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ6aLYEBAOuUuhH0tRw:-NQ958yD9LaGWEpUe4PQ:bimj6gk) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/cmake/functions.cmake#L226)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it is OK -`${LIBRDMACM_LDFLAGS}` should be in `CMAKE_REQUIRED_LIBRARIES`

For example `libibverbs.pc` contains:
LD_FLAGS = `-L${libdir} -libverbs -Wl,-rpath,${libdir}`
CFLAGS = `-I${includedir}`
</blockquote></details>

Thanks for explaining


<!-- Sent from Reviewable.io -->

2023-03-10 09:23 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQ9imxIAj6qbSUi5VXr:b-y09yzw) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

Is it necessary to add `${LIBIBVERBS_LDFLAGS}` here?
If `${LIBIBVERBS_LIBRARIES}` is defined, it means that `cmake` can find the ibverbs library by searching the default path.
In my opinion, we just need to set CMAKE_PREFIX_PATH to point the location as `FindLIBRDMACM.cmake` and `FindLIBIBVERBS.cmake` describe.
</blockquote></details>

Yes, it is necessary in case when rdma-core is installed in a non-default path.
See the example below:

```
###########################################################
### Testing standalone compilation of example: 02-read-to-volatile
### (with librpma installed from RELEASE packages)
###########################################################
-- The C compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'librpma'
--   Found librpma, version 1.2.0
-- Checking for module 'libibverbs'
--   Found libibverbs, version 1.14.44.0
-- Configuring done (0.7s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/rpma_example_build
[ 16%] Building C object CMakeFiles/server.dir/server.c.o
[ 33%] Building C object CMakeFiles/server.dir/rpma/examples/common/common-conn.c.o
[ 50%] Linking C executable server
/usr/bin/ld: cannot find -libverbs: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/server.dir/build.make:113: server] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/server.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

rdma-core is installed in `/rdma-core/build/`. CMake can find it using PkgConfig, because `PKG_CONFIG_PATH=/rdma-core/build/lib/pkgconfig` is set to point the *.pc file, but a linker has to have the `-L` flag set with the path to the library to be able to find it when it is installed in a non-default path. That's why it's necessary to use LD_FLAGS defined in the *.pc file.

For example in `libibverbs.pc`:
```
Libs: -L${libdir} -libverbs -Wl,-rpath,${libdir}
```

See also the manual of gcc:
```
$ man gcc
[...]
-l library
           Search the library named library when linking.
           [...]
           The linker searches a standard list of directories for the library.  The directories searched include several standard system directories plus any that you specify with -L.
```

and:
https://stackoverflow.com/questions/1904990/what-is-the-difference-between-ld-library-path-and-l-at-link-time


<!-- Sent from Reviewable.io -->

2023-03-10 12:44 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116#-:-NQAYAcGC4699jvpgdYL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2023-03-10 13:41 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAjDzfCxo-UqeCRG8D:b-z94egz) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

I think these flags (LIBIBVERBS_CFLAGS, LIBIBVERBS_LDFLAGS, etc.) have the same effect as LD_LIBRARY_PATH and CPATH.
Could you tell me why you want to provide two ways to do the same thing? I am not sure that I understand it correctly. ^_^
</blockquote></details>

I wish it had the same effect. Unfortunately it does not (at least in case of LD_LIBRARY_PATH and LD_PATH). A linker requires to have the paths set via the `-L` flag as the manual of gcc says (quoted above).


<!-- Sent from Reviewable.io -->

2023-03-10 13:45 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAl3_lCwAv5nPo_cz9:b-c6f5nr) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I wish it had the same effect. Unfortunately it does not (at least in case of LD_LIBRARY_PATH and LD_PATH). A linker requires to have the paths set via the `-L` flag as the manual of gcc says (quoted above).
</blockquote></details>

See the build without those flags: https://github.com/ldorau/rpma/actions/runs/4385097711/jobs/7677371418


<!-- Sent from Reviewable.io -->

2023-03-10 13:52 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAmnGTEIJG4CKLxRyl:b-tpwtnk) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See the build without those flags: https://github.com/ldorau/rpma/actions/runs/4385097711/jobs/7677371418
</blockquote></details>

The above build has failed. You can check the result and the source code of this branch.


<!-- Sent from Reviewable.io -->

2023-03-10 14:26 UTC, yangx-jy commented
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAt8d0ES2F1movWIjY:b-v7hqps) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The above build has failed. You can check the result and the source code of this branch.
</blockquote></details>

Could you check if we can fix the compiler error by adding the following setting?
```
ENV LIBRARY_PATH "/rdma-core/build/lib"
```


<!-- Sent from Reviewable.io -->

2023-03-10 14:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAv7BACpyUEPHvU7Pf:b7or8g0) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Could you check if we can fix the compiler error by adding the following setting?
```
ENV LIBRARY_PATH "/rdma-core/build/lib"
```
</blockquote></details>

It is already there: 
https://github.com/ldorau/rpma/blob/temp-fix-551001/utils/docker/images/Dockerfile.ubuntu-rdma-core-44#L98


<!-- Sent from Reviewable.io -->

2023-03-10 14:32 UTC, yangx-jy commented
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAviCJCxhYJ9wOGK7t:b-zcz5z1) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is already there: 
https://github.com/ldorau/rpma/blob/temp-fix-551001/utils/docker/images/Dockerfile.ubuntu-rdma-core-44#L98
</blockquote></details>

They are different. `LIBRARY_PATH` is used by cc/gcc, `LD_LIBRARY_PATH` is used by ldd.


<!-- Sent from Reviewable.io -->

2023-03-10 14:50 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQAxBO6BKs5fHynaQiT:b-mg1z7m) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, I did not notice it was different. I am checking ....
</blockquote></details>

Right, `LIBRARY_PATH` works :-) 
https://github.com/ldorau/rpma/actions/runs/4385534646

But there is another problem now.  When `LIBRARY_PATH` is set, pkg-config does not work as expected on Fedora and it does not print the correct `-L` path ...


<!-- Sent from Reviewable.io -->

2023-03-10 14:50 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQB-57-9A_RXF77pNAa:bsrx5it) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right, `LIBRARY_PATH` works :-) 
https://github.com/ldorau/rpma/actions/runs/4385534646

But there is another problem now.  When `LIBRARY_PATH` is set, pkg-config does not work as expected on Fedora and it does not print the correct `-L` path ...
</blockquote></details>

On Fedora:
```
+ LPATH=-L/rdma-core/build/lib
++ pkg-config --libs-only-L libibverbs
+ IB_LPATH=
++ pkg-config --libs-only-L librdmacm
+ CM_LPATH=
+ [[ '' == *\-\L\/\r\d\m\a\-\c\o\r\e\/\b\u\i\l\d\/\l\i\b* ]]
+ [[ '' == *\-\L\/\r\d\m\a\-\c\o\r\e\/\b\u\i\l\d\/\l\i\b* ]]
+ RDMA_CORE_INSTALLED_FROM_SOURCES=NO
```

and on Ubuntu:

```
+ LPATH=-L/rdma-core/build/lib
++ pkg-config --libs-only-L libibverbs
+ IB_LPATH=-L/rdma-core/build/lib
++ pkg-config --libs-only-L librdmacm
+ CM_LPATH=-L/rdma-core/build/lib
+ [[ -L/rdma-core/build/lib == *\-\L\/\r\d\m\a\-\c\o\r\e\/\b\u\i\l\d\/\l\i\b* ]]
+ RDMA_CORE_INSTALLED_FROM_SOURCES=YES
```


<!-- Sent from Reviewable.io -->

2023-03-10 14:53 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQB-cXFEaXapJXq5cMg:b-cywyzg) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

On Fedora:
```
+ LPATH=-L/rdma-core/build/lib
++ pkg-config --libs-only-L libibverbs
+ IB_LPATH=
++ pkg-config --libs-only-L librdmacm
+ CM_LPATH=
+ [[ '' == *\-\L\/\r\d\m\a\-\c\o\r\e\/\b\u\i\l\d\/\l\i\b* ]]
+ [[ '' == *\-\L\/\r\d\m\a\-\c\o\r\e\/\b\u\i\l\d\/\l\i\b* ]]
+ RDMA_CORE_INSTALLED_FROM_SOURCES=NO
```

and on Ubuntu:

```
+ LPATH=-L/rdma-core/build/lib
++ pkg-config --libs-only-L libibverbs
+ IB_LPATH=-L/rdma-core/build/lib
++ pkg-config --libs-only-L librdmacm
+ CM_LPATH=-L/rdma-core/build/lib
+ [[ -L/rdma-core/build/lib == *\-\L\/\r\d\m\a\-\c\o\r\e\/\b\u\i\l\d\/\l\i\b* ]]
+ RDMA_CORE_INSTALLED_FROM_SOURCES=YES
```

</blockquote></details>

So we can check if `LIBRARY_PATH` is set ;-)


<!-- Sent from Reviewable.io -->

2023-03-10 14:58 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2116)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/02-read-to-volatile/CMakeLists.txt` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2116#-NQ8YvLT3a83qKqVFROA:-NQB0iRu49e-ehx5bAnf:b-9y4njf) ([raw file](https://github.com/pmem/rpma/blob/9632c1729615c5ad8dd49f23f3039d0f413aeb8b/examples/02-read-to-volatile/CMakeLists.txt#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So we can check if `LIBRARY_PATH` is set ;-)
</blockquote></details>

OK, it will work :-) Thanks a lot! I am changing the PRs ...


<!-- Sent from Reviewable.io -->

2023-03-10 15:17 UTC, ldorau commented
Setting:
```
ENV LIBRARY_PATH "/rdma-core/build/lib"
```
in Dockerfiles makes this PR not needed :-) Thanks @yangx-jy !

2023-03-10 15:17 UTC, closed without merging