rpma: add more details to RPMA_LOG_ERROR_WITH_ERRNO() logs [WIP]
pmem/rpma pull request #290
Opened 2020-08-24 10:31 UTC by ldorau

2020-08-24 13:55 UTC, ldorau reviewed
Code coverage is OK now (100% ;-))

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290#-:-MFVk7BeDjCpSAKrSMP_:b-xvxyby)* status: 0 of 12 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-25 06:33 UTC, grom72 reviewed
Several general comments:
1)
every log entry shall be designed/created in such a way that librpma users get as much information as possible to diagnose the problem as soon as problem occurs without the need to re-run an application.
in such a situation the sequence of RPMA_LOG_DEBUG, RPMA_LOG_ERROR does not work as the application must be rerun with DEBUG level enabled to get full diagnostic information.
> if (Rpma_provider_error) {
> 		RPMA_LOG_DEBUG("ibv_req_notify_cq(solicited_only=0");
> 		RPMA_LOG_ERROR_WITH_ERRNO("ibv_req_notify_cq",
> ```

2)
I do not see an added value to print const argument, rather we should show parameters delivered from an application like addr, port, etc
We could use DEBUG level (or INFO level) for that purpose but we should also combine this information to ERROR message.

3)
DEBUG level should be used to help people to understand how an error situation has been achieved, it should guide end-user through a sequence of library calls from public API to place where the error occurs.

4) 
Log messages shall focus on end-user input analysis rather than our own code verification (this is done in UT/IT)
We should help end-user to identify places where librpma or libibverbs/librdmacm are used in an improper way resulting with an error situation. 

5) 
Performance shall not be strictly considered in error case as this is a rare situation so we could have more code for error message preparation

6)
I suggest to extend ERRNO macro:
#define RPMA_LOG_ERROR_WITH_ERRNO_EXTENDED(func, e, format, ...) \
	RPMA_LOG_ERROR(RPMA_LOG_ERRNO_FMT format, \
			func, strerror(e), ##__VA_ARGS__)
to put complete diagnostic information in one macro call

> Reviewed 8 of 8 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290#-:-MFZ5aYrA6ztR0vFJunG:bv0v9h6)* status: all files reviewed, 26 unresolved discussions (waiting on @ldorau)

___
*[src/conn.c, line 416 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZ9Y-iC8-lBzfdmikn:-MFZ9Y-iC8-lBzfdmiko:b-hhvm56) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn.c#L416)):*
> ```
> RPMA_LOG_DEBUG
> ```
does not help to understand error situation
___
*[src/conn.c, line 445 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZ9d5F9eLXWNJQrQB1:-MFZ9d5F9eLXWNJQrQB2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn.c#L445)):*
> ```C
> 		/* XXX ibv_poll_cq() may return only -1; no errno provided */
> 		Rpma_provider_error = result;
> 		RPMA_LOG_DEBUG("ibv_poll_cq(num_entries=1");
> ```

.
___
*[src/conn_req.c, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZA61sD4IuPuZPw_E7:-MFZA61sD4IuPuZPw_E8:bn4zysi) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L70)):*
> ```
> RPMA_DEFAULT_Q_SIZE
> ```
does not help to understand error situation
this will change if we have here conn_parameters with user-defined queue size
___
*[src/conn_req.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZARMU0UpUeXCVi_bu:-MFZARMU0UpUeXCVi_bv:brlc3lr) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L80)):*
> ```
> DEBUG
> ```
does not help
___
*[src/conn_req.c, line 253 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZAfb7DzfGH3WcOHag:-MFZAfb7DzfGH3WcOHah:brlc3lr) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L253)):*
> ```
> DEBUG
> ```
does not help
___
*[src/conn_req.c, line 363 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZAkJn-0O2bAk5qpG1:-MFZAkJoDntc2vrDN_wf:bb6axsl) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L363)):*
> ```C
> 	if (rdma_create_id(NULL, &id, NULL, RDMA_PS_TCP)) {
> 		Rpma_provider_error = errno;
> 		RPMA_LOG_DEBUG(
> ```

in this case only RDMA_PC_TCP might have some diagnostic value, but I rather prefer to put this into API documentation than report this value here
___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MFZB7I5E2WHGU7RpXCb:bbyzdsb) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
> ```
> RPMA_DEFAULT_TIMEOUT
> ```
1) can we use some preprocessing to convert this value to a string and avoid %i as this is const value?

2) can we combine this into the ERROR message below?
___
*[src/ep.c, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZC9Hp5b4DNSnehlEf:-MFZC9Hp5b4DNSnehlEg:b-dko5x1) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/ep.c#L79)):*
> ```
> RPMA_LOG_DEBUG
> ```
const, could be added to ERROR, but how does it help?
___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFZCm1nEgG09wdlEsXD:b-l5pemi) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
> ```
> _SC_PAGESIZE
> ```
preprocess to show actual value of _SC_PAGESIZE ?
___
*[src/info.c, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZD2-F1XNhRoMYuzZN:-MFZD2-F1XNhRoMYuzZO:b-8l705a) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L54)):*
> ```
> RPMA_LOG_DEBUG
> ```
to be combined into one LOG_ERROR message.
we do not need to think about performance or syslog overloading - this is an error situation so the application will be hurt anyway so let's give  some favor to and user and provider full information for the first time
___
*[src/info.c, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDhUY1DBS-_OTse9r:-MFZDhUY1DBS-_OTse9s:b-w1z6e1) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L115)):*
> ```
> RPMA_LOG_DEBUG
> ```
as above
___
*[src/info.c, line 119 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDnFG6Be81v1QB6i8:-MFZDnFG6Be81v1QB6i9:bln20gz) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L119)):*
> ```
> RPMA_DEFAULT_TIMEOUT
> ```
is const let's preproces it
___
*[src/info.c, line 140 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDvPq8V7TJf1XlBHS:-MFZDvPq8V7TJf1XlBHT:byyjjqk) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L140)):*
> ```
> DEBUG
> ```
combine with ERROR message
___
*[src/mr.c, line 117 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEDu_BGXnojIP4-2i:-MFZEDu_BGXnojIP4-2j:b7cdb3q) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/mr.c#L117)):*
> ```
> RPMA_LOG_DEBUG
> ```
.
___
*[src/mr.c, line 164 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEGLE0-5IJ1eVl0hb:-MFZEGLE0-5IJ1eVl0hc:bdsqhdw) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/mr.c#L164)):*
> ```
> RPMA_LOG_DEBUG
> ```
RPMA_LOG_ERROR_WITH_ERRNO_EXTENDED
___
*[src/peer.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEJ259SG5C6oGmp40:-MFZEJ259SG5C6oGmp41:bdsqhdw) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L63)):*
> ```
> RPMA_LOG_DEBUG
> ```
RPMA_LOG_ERROR_WITH_ERRNO_EXTENDED
___
*[src/peer.c, line 104 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEL3g-vrJiUP4muh1:-MFZEL3g-vrJiUP4muh2:b7cdb3q) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L104)):*
> ```
> RPMA_LOG_DEBUG
> ```
.
___
*[src/peer.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZF8-cA9pTRcWWt7vN:-MFZF8-cA9pTRcWWt7vO:b-l7htxd) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L106)):*
> ```
> "errno != EOPNOTSUPP
> ```
hmm repetition of what RPMA_LOG_ERROR_WITH_ERRNO will show in next line
here we  [...]

2020-08-25 09:43 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 26 unresolved discussions (waiting on @grom72)

___
*[src/conn.c, line 416 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZ9Y-iC8-lBzfdmikn:-MFZkd3x4cJ57L1CnR5t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn.c#L416)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
does not help to understand error situation
</blockquote></details>

Done.
___
*[src/conn.c, line 445 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZ9d5F9eLXWNJQrQB1:-MFZkh2L4WUif5JrHR-z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn.c#L445)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/conn_req.c, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZA61sD4IuPuZPw_E7:-MFZkobQ9Xo5nQJoOR9h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L70)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_DEFAULT_Q_SIZE
> ```
does not help to understand error situation
this will change if we have here conn_parameters with user-defined queue size
</blockquote></details>

Done.
___
*[src/conn_req.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZARMU0UpUeXCVi_bu:-MFZksJUDu3LHyeu6JUy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> DEBUG
> ```
does not help
</blockquote></details>

Done.
___
*[src/conn_req.c, line 253 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZAfb7DzfGH3WcOHag:-MFZl-Bm5YKdmUXGIwvx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L253)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> DEBUG
> ```
does not help
</blockquote></details>

Done.
___
*[src/conn_req.c, line 363 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZAkJn-0O2bAk5qpG1:-MFZm8sC5RTbDrQIyX1Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L363)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

in this case only RDMA_PC_TCP might have some diagnostic value, but I rather prefer to put this into API documentation than report this value here
</blockquote></details>

Done.
___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MFZmRbQAu6w4rb-qXnD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_DEFAULT_TIMEOUT
> ```
1) can we use some preprocessing to convert this value to a string and avoid %i as this is const value?

2) can we combine this into the ERROR message below?
</blockquote></details>

Done.
___
*[src/ep.c, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZC9Hp5b4DNSnehlEf:-MFZm_wF9M8aGd_2EUTB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/ep.c#L79)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
const, could be added to ERROR, but how does it help?
</blockquote></details>

Done.
___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFZmn7Z1oCdST0TTdrp:b-ydrzh2) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> _SC_PAGESIZE
> ```
preprocess to show actual value of _SC_PAGESIZE ?
</blockquote></details>

Why? What is it needed for?
___
*[src/info.c, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZD2-F1XNhRoMYuzZN:-MFZoC7A1ixFJW51cs3-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
to be combined into one LOG_ERROR message.
we do not need to think about performance or syslog overloading - this is an error situation so the application will be hurt anyway so let's give  some favor to and user and provider full information for the first time
</blockquote></details>

Done.
___
*[src/info.c, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDhUY1DBS-_OTse9r:-MFZrRVVEItPeuVv0rDm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L115)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
as above
</blockquote></details>

Done.
___
*[src/info.c, line 119 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDnFG6Be81v1QB6i8:-MFZrSb66nQeR1U7a5BU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L119)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_DEFAULT_TIMEOUT
> ```
is const let's preproces it
</blockquote></details>

Done.
___
*[src/info.c, line 140 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDvPq8V7TJf1XlBHS:-MFZro197WHDJKtB9b3u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L140)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> DEBUG
> ```
combine with ERROR message
</blockquote></details>

Done.
___
*[src/mr.c, line 117 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEDu_BGXnojIP4-2i:-MFZwBY80e0QMwTSa0qm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/mr.c#L117)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
.
</blockquote></details>

Done.
___
*[src/mr.c, line 164 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEGLE0-5IJ1eVl0hb:-MFZwC8PA5Ezf_rRURVr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/mr.c#L164)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
RPMA_LOG_ERROR_WITH_ERRNO_EXTENDED
</blockquote></details>

Done.
___
*[src/peer.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEJ259SG5C6oGmp40:-MFZwWsE0_f75N-Y4l99:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L63)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
RPMA_LOG_ERROR_WITH_ERRNO_EXTENDED
</blockquote></details>

Done.
___
*[src/peer.c, line 104 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZEL3g-vrJiUP4muh1:-MFZwnn3AXRzTIkAX6eK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L104)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DEBUG
> ```
.
</blockquote></details>

Done.
___
*[src/peer.c, line 106 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZF8-cA9pTRcWWt7vN:-MFZxufnCqbyvSmT1jbd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L106)):*
<details><summary><i [...]

2020-08-25 13:42 UTC, janekmi requested changes
> Reviewed 1 of 8 files at r1, 6 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 10 of 13 files reviewed, 30 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MF_gsEq8Z3ANUm3BKpF:bp6vtcw) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```c

/* src/common.h */

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

/* ... */

RPMA_LOG_ERROR_WITH_ERRNO("string " STR(RPMA_DEFAULT_TIMEOUT));
```
___
*[src/ep.c, line 62 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_hziu2_JEhW1_-9uH:-MF_hziu2_JEhW1_-9uI:bkuxqy2) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/ep.c#L62)):*
> ```C
> 		Rpma_provider_error = errno;
> 		RPMA_LOG_DEBUG(
> 			"rdma_create_id(channel!=NULL, context=NULL, ps=RDMA_PS_TCP)");
> ```

No value. I agree with @grom72 we can document some of this. Other does convey any information to the user.
___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MF_nZVf8jgQlz9b7bnB:b-w8cnou) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? What is it needed for?
</blockquote></details>

No. The constant name is a lot more meaningful and documented.
___
*[src/info.c, line 119 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDnFG6Be81v1QB6i8:-MF_ok2L5dKuOcAx8qmO:b2nhky0) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No.
___
*[src/info.c, line 55 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_oKxO5XcaSTviDptJ:-MF_oKxO5XcaSTviDptK:bb7mqkm) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L55)):*
> ```C
> 		Rpma_provider_error = errno;
> 		RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error,
> 			"rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP)",
> ```

port
___
*[src/info.c, line 55 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_oVbH7va7xAqskA4U:-MF_oVbH7va7xAqskA4V:b-wyw32) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L55)):*
> ```C
> 		Rpma_provider_error = errno;
> 		RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error,
> 			"rdma_getaddrinfo(node=%s, service=%s, ai_flags=%s ai_qp_type=IBV_QPT_RC, ai_port_space=RDMA_PS_TCP)",
> ```

ai_flags=%s **,** ai_qp_type=...
___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_pDBqCEKd8RX6rWTm:-MF_pDBqCEKd8RX6rWTn:byw3itj) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
> ```objc
> 
> #define RPMA_LOG_ERROR_WITH_ERRNO_EXT(e, format, ...) \
> 	RPMA_LOG_ERROR(format "\nError: %s", ##__VA_ARGS__, strerror(e))
> ```

Can we combine both of these?
If not:
- Please make the naming and order of arguments the same e.g. `e, format`.


<!-- Sent from Reviewable.io -->

2020-08-25 14:08 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r2, 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 12 of 13 files reviewed, 36 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/rpma.c, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZFvpg0Uqcij62O0DC:-MF_rqwfAhg6wuSFy9ih:be8eofl) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/rpma.c#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Consequently: we can document it. No value.
___
*[src/rpma.c, line 95 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZIkiy-8C7t_NZ9X5s:-MF_sOLr7mk1AvXuIy14:b-nnisdj) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/rpma.c#L95)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we can drop here most of these braces. The end user will understand a single pair of braces as well.
___
*[tests/unit/mr/mr-common.h, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZJTi54BOngrkSpbhd:-MF_wVvxBjK36FWVIq2m:b2nm4if) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/tests/unit/mr/mr-common.h#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

It seems not needed here.
___
*[tests/unit/mr/mr-read.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wL9d6YP9cQlzSnzr:-MF_wL9d6YP9cQlzSnzs:bhkuwvd) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L25)):*
> ```C
>  */
> static void
> read__failed_E_PROVIDER_COMPL_ON_SUCCESS(void **mrs_ptr)
> ```

According to the error I have pointed below probably this name also have to be changed.
___
*[tests/unit/mr/mr-read.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wU--BexWUdHqZLLD:-MF_wU--BexWUdHqZLLE:b-53xcfs) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L33)):*
> ```C
> 	args.qp = MOCK_QP;
> 	args.opcode = IBV_WR_RDMA_READ;
> 	args.send_flags = RPMA_F_COMPLETION_ON_SUCCESS;
> ```

IBV_SEND_SIGNALED?
___
*[tests/unit/mr/mr-read.c, line 41 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_w7L99a_fyeMx7aL9:-MF_w7LABJvVnOhw5lDn:biukoua) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L41)):*
> ```C
> 	int ret = rpma_mr_read(MOCK_QP, mrs->local, MOCK_DST_OFFSET,
> 				mrs->remote, MOCK_SRC_OFFSET,
> 				MOCK_LEN, RPMA_F_COMPLETION_ON_SUCCESS,
> ```

Either RPMA_F_COMPLETION_ON_ERROR or RPMA_F_COMPLETION_ALWAYS. Only these two are available in the public header.
___
*[tests/unit/mr/mr-write.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_weHa14RU5dE67ATV:-MF_weHa14RU5dE67ATW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L25)):*
> ```C
>  */
> static void
> write__failed_E_PROVIDER_COMPL_ON_SUCCESS(void **mrs_ptr)
> ```

.
___
*[tests/unit/mr/mr-write.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wcO51MY8ADg6RCRn:-MF_wcO51MY8ADg6RCRo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L33)):*
> ```C
> 	args.qp = MOCK_QP;
> 	args.opcode = IBV_WR_RDMA_WRITE;
> 	args.send_flags = RPMA_F_COMPLETION_ON_SUCCESS;
> ```

.
___
*[tests/unit/mr/mr-write.c, line 41 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wdKU1cIjchl9EZXM:-MF_wdKU1cIjchl9EZXN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L41)):*
> ```C
> 	int ret = rpma_mr_write(MOCK_QP, mrs->remote, MOCK_DST_OFFSET,
> 				mrs->local, MOCK_SRC_OFFSET,
> 				MOCK_LEN, RPMA_F_COMPLETION_ON_SUCCESS,
> ```

.


<!-- Sent from Reviewable.io -->

2020-08-25 14:18 UTC, janekmi requested changes
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 37 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/peer.c, line 123 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZFgRwB2CvSb5_cGFu:-MF_yJH26V43pZXy_fFq:btfmyt5) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```c
*ibv_mr = ibv_reg_mr(peer->pd, addr, length, RPMA_IBV_ACCESS(access | IBV_ACCESS_ON_DEMAND);
/* ... */
RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr(args, acccess=%i|IBV_ACCESS_ON_DEMAND)", args, access);
```
___
*[src/peer.c, line 106 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wx-S85G_vzYIHGGZ:-MF_wx-S85G_vzYIHGG_:b-mspgrw) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/peer.c#L106)):*
> ```C
> 			(!peer->is_odp_supported) ? "peer" : "RNIC");
> 		return RPMA_E_PROVIDER;
> 	}
> ```

To give a precise log message you have to rework this if-statement a bit e.g.

```c
if (Rpma_provider_error != EOPNOTSUPP)
    RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr");

if (!peer->is_odp_supported)
     RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr(args?): peer does not support On-Demand Paging");
```


<!-- Sent from Reviewable.io -->

2020-08-25 15:09 UTC, grom72 reviewed
> Reviewed 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MF_Eaxd5l7IkY6OeQKR:b-6aekno) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? What is it needed for?
</blockquote></details>

what does it mean for end-user?  can we use flush? not? why?
___
*[src/info.c, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZD2-F1XNhRoMYuzZN:-MF_BM-Z0W9RhxTNu1mP:b32vhw) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:)
___
*[src/info.c, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDhUY1DBS-_OTse9r:-MF_BVpq3FQETaj3vnPY:b-9xfdso) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L115)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

actual value of the timeout would be more informative
___
*[src/info.c, line 114 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_G-KxAU5B-Wxiy4l8:-MF_G-KxAU5B-Wxiy4l9:b87nyl5) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L114)):*
> ```
> timeout_ms=RPMA_DEFAULT_TIMEOUT)", 
> ```
timeout_ms=%i)", RPMA_DEFAULT_TIMEOUT,
___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_CMoA0vg1X4ARmqSo:-MF_CMoBCnKPmJ536ve8:b4rdwi9) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
> ```
> RPMA_LOG_ERROR(format "\nError: %s", ##__VA_ARGS__, strerror(e))
> ```
shall we make this more similar to RPMA_LOG_ERROR_WITH_ERRNO?
I like format:
function_name failed: errno. <extended information about parameters>


<!-- Sent from Reviewable.io -->

2020-08-25 15:39 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFa9qxt36fxtX5ZiyNP:bxj6nbk) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what does it mean for end-user?  can we use flush? not? why?
</blockquote></details>

shall we use text from comment above to be more informative? - we could redirect to man page:
https://man7.org/linux/man-pages/man3/sysconf.3.html
but here we use only one case:
~~       *  On error, -1 is returned and errno is set to indicate the cause of
          the error (for example, EINVAL, indicating that name is invalid).~~

       *  If name corresponds to a maximum or minimum limit, and that limit
          is indeterminate, -1 is returned and errno is not changed.  (To
          distinguish an indeterminate limit from an error, set errno to
          zero before the call, and then check whether errno is nonzero when
          -1 is returned.)

       *  If name corresponds to an option, a positive value is returned if
          the option is supported, and -1 is returned if the option is not
          supported.

       *  Otherwise, the current value of the option or limit is returned.
          This value will not be more restrictive than the corresponding
          value that was described to the application in <unistd.h> or
          <limits.h> when the application was compiled.

So this means that we could get either 0 or something above 0 here.
no way to get -1 and EINVAL
from code analysis we could get ENOSYS 
  /* The only possible error is ENOSYS.  */
  if (!INTERNAL_SYSCALL_ERROR_P (result, err))

Macro: int ENOSYS
“Function not implemented.” This indicates that the function called is not implemented at all, either in the C library itself or in the operating system. When you get this error, you can be sure that this particular function will always fail with ENOSYS unless you install a new version of the C library or the operating system.
___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_CMoA0vg1X4ARmqSo:-MFaG1qiD1VMFRI7khIJ:bv2i73w) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_ERROR(format "\nError: %s", ##__VA_ARGS__, strerror(e))
> ```
shall we make this more similar to RPMA_LOG_ERROR_WITH_ERRNO?
I like format:
function_name failed: errno. <extended information about parameters>

</blockquote></details>

as @janekmi write above - we should keep the same structure for these two macros
___
*[src/peer.c, line 123 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZFgRwB2CvSb5_cGFu:-MFaGM4V7TuPYMZaMcEy:b-8bsxva) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
*ibv_mr = ibv_reg_mr(peer->pd, addr, length, RPMA_IBV_ACCESS(access | IBV_ACCESS_ON_DEMAND);
/* ... */
RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr(args, acccess=%i|IBV_ACCESS_ON_DEMAND)", args, access);
```
</blockquote></details>

anyhow as this is tricky part for many customers we have to be more informative here


<!-- Sent from Reviewable.io -->

2020-08-25 15:41 UTC, grom72 reviewed
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 20 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MFaGkbU14WisNTsha3L:b-mva36) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c

/* src/common.h */

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

/* ... */

RPMA_LOG_ERROR_WITH_ERRNO("string " STR(RPMA_DEFAULT_TIMEOUT));
```
</blockquote></details>

@janekmi - thank you for recalling


<!-- Sent from Reviewable.io -->

2020-08-26 06:27 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MFdM4Zf-PgvUBSnEdnA:bbdw379) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@janekmi - thank you for recalling
</blockquote></details>

Why is it supposed to be better than the current one?
___
*[src/ep.c, line 62 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_hziu2_JEhW1_-9uH:-MFdNafR5wiTXduYVrXp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/ep.c#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No value. I agree with @grom72 we can document some of this. Other does convey any information to the user.
</blockquote></details>

Done.
___
*[src/info.c, line 119 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZDnFG6Be81v1QB6i8:-MFdQxEaBIbq5bkWTeDe:bdw0p2k) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/info.c#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No.
</blockquote></details>

actual value of the timeout is more informative
___
*[src/info.c, line 55 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_oKxO5XcaSTviDptJ:-MFdLQewCwsKJszTxs3B:b-jm7iyw) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

port
</blockquote></details>

No, manual of rdma_getaddrinfo says:
```
SYNOPSIS
       #include <rdma/rdma_cma.h>

       int rdma_getaddrinfo (const char *node, const char *service, const struct rdma_addrinfo *hints, struct rdma_addrinfo **res);
```
___
*[src/info.c, line 55 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_oVbH7va7xAqskA4U:-MFdNrYCADQb2Vp0mLpt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ai_flags=%s **,** ai_qp_type=...
</blockquote></details>

Done.
___
*[src/info.c, line 114 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_G-KxAU5B-Wxiy4l8:-MFdOFJL4CGYvjxpOoym:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> timeout_ms=RPMA_DEFAULT_TIMEOUT)", 
> ```
timeout_ms=%i)", RPMA_DEFAULT_TIMEOUT,
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-26 06:51 UTC, janekmi reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MFdTay80mwpGV1Ofccd:b-fl5yda) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why is it supposed to be better than the current one?
</blockquote></details>

`RPMA_DEFAULT_TIMEOUT` is defined in conn_req.h so the end user has no idea what it is.
___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFdV_bJ4Ol-0EBfBIHA:bf8925) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we use text from comment above to be more informative? - we could redirect to man page:
https://man7.org/linux/man-pages/man3/sysconf.3.html
but here we use only one case:
~~       *  On error, -1 is returned and errno is set to indicate the cause of
          the error (for example, EINVAL, indicating that name is invalid).~~

       *  If name corresponds to a maximum or minimum limit, and that limit
          is indeterminate, -1 is returned and errno is not changed.  (To
          distinguish an indeterminate limit from an error, set errno to
          zero before the call, and then check whether errno is nonzero when
          -1 is returned.)

       *  If name corresponds to an option, a positive value is returned if
          the option is supported, and -1 is returned if the option is not
          supported.

       *  Otherwise, the current value of the option or limit is returned.
          This value will not be more restrictive than the corresponding
          value that was described to the application in <unistd.h> or
          <limits.h> when the application was compiled.

So this means that we could get either 0 or something above 0 here.
no way to get -1 and EINVAL
from code analysis we could get ENOSYS 
  /* The only possible error is ENOSYS.  */
  if (!INTERNAL_SYSCALL_ERROR_P (result, err))

Macro: int ENOSYS
“Function not implemented.” This indicates that the function called is not implemented at all, either in the C library itself or in the operating system. When you get this error, you can be sure that this particular function will always fail with ENOSYS unless you install a new version of the C library or the operating system.

</blockquote></details>

What is your point?
___
*[src/info.c, line 55 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_oKxO5XcaSTviDptJ:-MFdTvXuAEJgB5OYukcG:b-68ozwg) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/info.c#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, manual of rdma_getaddrinfo says:
```
SYNOPSIS
       #include <rdma/rdma_cma.h>

       int rdma_getaddrinfo (const char *node, const char *service, const struct rdma_addrinfo *hints, struct rdma_addrinfo **res);
```
</blockquote></details>

You are right. Too many ports and services lately. ;-)
___
*[src/peer.c, line 123 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZFgRwB2CvSb5_cGFu:-MFdVwdD5-VpN8yCAqe_:blnfqcx) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/peer.c#L123)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

anyhow as this is tricky part for many customers we have to be more informative here
</blockquote></details>

Ok. But please try to be as consistent with other messages as possible e.g.:

```c
RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr(args, acccess=%i|IBV_ACCESS_ON_DEMAND): The memory registration with On-Demand Paging (FSDAX) support failed", args, access);
```

I think FSDAX should be the second information (I will add even a question mark) since no FSDAX is ever mentioned in any memory registration documentation. And we have no idea at this point if the memory is really a PMem. 9/10 probably it will be this case but still.


<!-- Sent from Reviewable.io -->

2020-08-26 10:35 UTC, grom72 reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFeJA6k2ngDKQPtw-KS:b-ioaysg) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is your point?
</blockquote></details>

What can end-user do with this information? How can this information help to solve the problem? 


<!-- Sent from Reviewable.io -->

2020-08-26 12:16 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFegdAl0qWoqrG9Szum:b3mo01q) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What can end-user do with this information? How can this information help to solve the problem? 
</blockquote></details>

let use fatal for this error message :goat: 


<!-- Sent from Reviewable.io -->

2020-08-26 12:17 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFegn0w2rj4qBjG8E_s:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

let use fatal for this error message :goat: 
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2020-08-26 15:32 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/conn_req.c, line 380 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZB7I5E2WHGU7RpXCa:-MFfLEBk5iK__BcZILeX:blmdbtj) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/conn_req.c#L380)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`RPMA_DEFAULT_TIMEOUT` is defined in conn_req.h so the end user has no idea what it is.
</blockquote></details>

OK, Done.
___
*[src/flush.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZCm1m4u7e_fgCN-FF:-MFfM_y84gdyGlaV6vqs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/src/flush.c#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[src/peer.c, line 106 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wx-S85G_vzYIHGGZ:-MFfOXLH4aN_v3lrDB7e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/peer.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To give a precise log message you have to rework this if-statement a bit e.g.

```c
if (Rpma_provider_error != EOPNOTSUPP)
    RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr");

if (!peer->is_odp_supported)
     RPMA_LOG_ERROR_WITH_ERRNO_EXT(Rpma_provider_error, "ibv_reg_mr(args?): peer does not support On-Demand Paging");
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-26 19:30 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 2 of 12 files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/mr/mr-common.h, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/290#-MFZJTi54BOngrkSpbhd:-MFgCpMhDhj9xOCOezTW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40fabd4861dca7dfa73de0e362cc0da54a3d46bc/tests/unit/mr/mr-common.h#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems not needed here.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-read.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wL9d6YP9cQlzSnzr:-MFgDIx2BvavuGhzZTxm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

According to the error I have pointed below probably this name also have to be changed.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-read.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wU--BexWUdHqZLLD:-MFgE8sAELTVIVRAJJdf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

IBV_SEND_SIGNALED?
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-read.c, line 41 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_w7L99a_fyeMx7aL9:-MFgDJWH3t3huVgoBA8X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Either RPMA_F_COMPLETION_ON_ERROR or RPMA_F_COMPLETION_ALWAYS. Only these two are available in the public header.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-write.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_weHa14RU5dE67ATV:-MFgDKTB36Hd9lfcXFTO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-write.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wcO51MY8ADg6RCRn:-MFgDLLd4PLOKZAc-ilP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-write.c, line 41 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wdKU1cIjchl9EZXM:-MFgDLu1C6VuMxXVOWsO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-26 19:54 UTC, grom72 reviewed
> Reviewed 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2020-08-26 20:07 UTC, janekmi requested changes
> Reviewed 11 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[src/conn_req.c, line 375 at r5](https://reviewable.io/reviews/pmem/rpma/290#-MFgKBDa2fbEPQYwlsmv:-MFgKBDa2fbEPQYwlsmw:bcm9lih) ([raw file](https://github.com/pmem/rpma/blob/2665b0ba31bae3b1742959c1eadb135e52e1a10c/src/conn_req.c#L375)):*
> ```C
> 		Rpma_provider_error = errno;
> 		RPMA_LOG_ERROR_WITH_ERRNO(
> 			"rdma_resolve_route(timeout_ms="\
> ```

I believe you do not have to end the line with `\` character.
___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_pDBqCEKd8RX6rWTm:-MFgKgMUAtErfNp-SeOS:b-g4fbq1) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we combine both of these?
If not:
- Please make the naming and order of arguments the same e.g. `e, format`.
</blockquote></details>

Oh no... please. Either both of these can be replaced with a single one or just leave them separately.
___
*[src/peer.c, line 101 at r5](https://reviewable.io/reviews/pmem/rpma/290#-MFgLE4j0ZEJ-qSNlWs3:-MFgLE4j0ZEJ-qSNlWs4:b-d7nnvz) ([raw file](https://github.com/pmem/rpma/blob/2665b0ba31bae3b1742959c1eadb135e52e1a10c/src/peer.c#L101)):*
> ```C
> 	Rpma_provider_error = errno;
> 
> 	if (Rpma_provider_error != EOPNOTSUPP || (!peer->is_odp_supported)) {
> ```

I think the outermost if-statement is redundant.
___
*[tests/unit/mr/mr-read.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_wL9d6YP9cQlzSnzr:-MFgMBKs3jRF-ZjwZdol:b-gcp16r) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-read.c#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

**Discussing**: I'm not sure if we are on the same page with the concept but... at least in my opinon, the name should follow the rule action + conditions + result. So the name will be something like: `read__COMPL_ALWAYS_failed_E_PROVIDER`.
___
*[tests/unit/mr/mr-write.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_weHa14RU5dE67ATV:-MFgMtJ14_BnGZvYzzW6:b8jlnd0) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/tests/unit/mr/mr-write.c#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

**Disucussing**: .


<!-- Sent from Reviewable.io -->

2020-08-26 20:13 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/conn_req.c, line 375 at r5](https://reviewable.io/reviews/pmem/rpma/290#-MFgKBDa2fbEPQYwlsmv:-MFgOoaoCzCrZvPxx_Tf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2665b0ba31bae3b1742959c1eadb135e52e1a10c/src/conn_req.c#L375)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe you do not have to end the line with `\` character.
</blockquote></details>

Done.
___
*[src/peer.c, line 101 at r5](https://reviewable.io/reviews/pmem/rpma/290#-MFgLE4j0ZEJ-qSNlWs3:-MFgNkkY4pjwZurPXyLC:b48nyu7) ([raw file](https://github.com/pmem/rpma/blob/2665b0ba31bae3b1742959c1eadb135e52e1a10c/src/peer.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the outermost if-statement is redundant.
</blockquote></details>

No, there is `return RPMA_E_PROVIDER;` inside.


<!-- Sent from Reviewable.io -->

2020-08-26 20:24 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_pDBqCEKd8RX6rWTm:-MFgR5g90L-0OzIcJDzd:b-f37klz) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Oh no... please. Either both of these can be replaced with a single one or just leave them separately.
</blockquote></details>

Of course :-D It is just WIP late in night ;-)


<!-- Sent from Reviewable.io -->

2020-08-26 20:36 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_pDBqCEKd8RX6rWTm:-MFgTflQ9xjRq1weybkr:b1ugsn0) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Of course :-D It is just WIP late in night ;-)
</blockquote></details>

I will finish it tomorrow - I will let you now ;-) 


<!-- Sent from Reviewable.io -->

2020-08-26 20:43 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_pDBqCEKd8RX6rWTm:-MFgV-nrBdrlg9S0V1lN:b4pdy9h) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I will finish it tomorrow - I will let you now ;-) 
</blockquote></details>

Uff... ;-)
___
*[src/peer.c, line 101 at r5](https://reviewable.io/reviews/pmem/rpma/290#-MFgLE4j0ZEJ-qSNlWs3:-MFgVLYcAy6F5ZVZkS-t:b-k38tx6) ([raw file](https://github.com/pmem/rpma/blob/2665b0ba31bae3b1742959c1eadb135e52e1a10c/src/peer.c#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, there is `return RPMA_E_PROVIDER;` inside.
</blockquote></details>

You are right but... I think it will be better to append the return to both of these cases than repeating the conditions.


<!-- Sent from Reviewable.io -->

2020-08-26 20:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/peer.c, line 101 at r5](https://reviewable.io/reviews/pmem/rpma/290#-MFgLE4j0ZEJ-qSNlWs3:-MFgWeGI1ryQPgFv2h7t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2665b0ba31bae3b1742959c1eadb135e52e1a10c/src/peer.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are right but... I think it will be better to append the return to both of these cases than repeating the conditions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-27 06:47 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: 6 of 14 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_pDBqCEKd8RX6rWTm:-MFieqjDDKAf2ICzSAa9:bna53eo) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Uff... ;-)
</blockquote></details>

Done.

@janekmi
___
*[src/log_internal.h, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/290#-MF_CMoA0vg1X4ARmqSo:-MFiexj92wFn-igliT8Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f3302d3b27b05927573c003347c65cb5c25014b/src/log_internal.h#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

as @janekmi write above - we should keep the same structure for these two macros
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-08-27 09:06 UTC, grom72 reviewed
:goat: 

> Reviewed 2 of 4 files at r6, 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290#-:-MFj9crr3v77A7XyIa_C:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-08-28 17:43 UTC, janekmi requested changes
> Reviewed 8 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/log_internal.h, line 60 at r7](https://reviewable.io/reviews/pmem/rpma/290#-MFq87Qm3maegm_DPcI1:-MFq87Qm3maegm_DPcI2:b-xdz1su) ([raw file](https://github.com/pmem/rpma/blob/242ed3a87fb52128865289894d1edc56280be2b7/src/log_internal.h#L60)):*
> ```objc
> 			strerror(e)); \
> 	} \
> } while (0)
> ```

I think it can be a lot shorter e.g.:

```c
/*
 * 'f' stands here for function or format where the latter may accept additional
 * arguments.
 */
#define RPMA_LOG_ERROR_WITH_ERRNO(e, f, ...) \
	RPMA_LOG_ERROR(f " failed: %s", ##__VA_ARGS__, strerror(e));
```
___
*[src/peer.c, line 109 at r7](https://reviewable.io/reviews/pmem/rpma/290#-MFq9GjP48TrHyUCKH6C:-MFq9GjP48TrHyUCKH6D:bvl8ow4) ([raw file](https://github.com/pmem/rpma/blob/242ed3a87fb52128865289894d1edc56280be2b7/src/peer.c#L109)):*
> ```C
> 	if (!peer->is_odp_supported) {
> 		RPMA_LOG_ERROR_WITH_ERRNO(Rpma_provider_error,
> 			"Error: peer does not support On-Demand Paging\n"
> ```

I'm not sure we should go with these "Error" prefixes.
For sure I'm voting for replacing '\n' with ' '.
___
*[src/peer.c, line 125 at r7](https://reviewable.io/reviews/pmem/rpma/290#-MFq9Z1JDZEY0C3ags2e:-MFq9Z1JDZEY0C3ags2f:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/242ed3a87fb52128865289894d1edc56280be2b7/src/peer.c#L125)):*
> ```C
> 		Rpma_provider_error = errno;
> 		RPMA_LOG_ERROR_WITH_ERRNO(Rpma_provider_error,
> 			"Error: memory registration with On-Demand Paging (maybe FSDAX?) support failed\n"
> ```

.


<!-- Sent from Reviewable.io -->

2020-08-31 07:24 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/290#-:-MG2OooSD5sekEVkTJZ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-08-31 07:26 UTC, merged