examples: add atomic_write example
pmem/rpma pull request #318
Opened 2020-08-31 10:34 UTC by osalyk

2020-08-31 11:46 UTC, grom72 reviewed
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 3 of 5 files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Jz4f-a2fJ80K2ALU:-MG3Jz4f-a2fJ80K2ALV:b-b34qn7) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L69)):*
> ```
> ret = client_peer_via_address(addr, &peer);
> 	if (ret)
> 		goto err_free;
> ```
if( ret = client_peer_via_address(addr, &peer) )
	goto err_free;
@janekmi can we make this example shorter?
ret is used only to provide proper exit code
___
*[examples/07-atomic-write/client.c, line 128 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KcAQ16nq3TXjdgHS:-MG3KcAQ16nq3TXjdgHT:brwdmjl) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L128)):*
> ```
> goto err_conn_disconnect;
> ```
undefined behavour - what will be ret value here?
___
*[examples/07-atomic-write/client.c, line 140 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3J3CH01Ik1l1bZST6:-MG3J3CH01Ik1l1bZST7:b-ezmnuk) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L140)):*
> ```
> ret = rpma_flush(conn, dst_mr, dst_offset, 8,
> 				RPMA_FLUSH_TYPE_PERSISTENT,
> 				RPMA_F_COMPLETION_ALWAYS, FLUSH_ID);
> ```
if(rpma_flush(conn, dst_mr, dst_offset, 8,
				RPMA_FLUSH_TYPE_PERSISTENT,
				RPMA_F_COMPLETION_ALWAYS, FLUSH_ID)
    break;

and in a similar way in all similar places in the loop
with logging enabled we do not need to get ret value and interpreter it - if any of called function failed we goto/break to proper location but ret value is documented by rpmalog
___
*[examples/07-atomic-write/client.c, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3HXgC6IMF5bZNRZjR:-MG3HXgDAgG8KJvQw0Z2:bklag1x) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L165)):*
> ```
> if (cmpl.op_status != IBV_WC_SUCCESS) {
> 			(void) fprintf(stderr, "rpma_read failed with %d\n",
> 					cmpl.op_status);
> ```
rpma_read or rpam_flush?
___
*[examples/07-atomic-write/client.c, line 167 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Hede1wGcMlYTiOct:-MG3Hede1wGcMlYTiOcu:b6o3mp6) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L167)):*
> ```
> goto err_conn_disconnect;
> ```
I prefer to brake the loop instead of goto
goto is an exceptional jump, but in this case, everything is under control - we could not execute any further read/write/flush operation so we just closing the connection as in normal situation
___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KGyt3cHM9G4zLkPD:-MG3KGyt3cHM9G4zLkPE:brp62bj) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L190)):*
> ```
> return ret;
> ```
return ret ? -2 : 0 
there is no point to push internal API call retvalue to end user (shell)
___
*[examples/07-atomic-write/README.md, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3FepH20sCEJe1QAI9:-MG3FepH20sCEJe1QAIA:bahiqiv) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/README.md#L13)):*
> ```
> For flushing the posted write, it reads eight bytes from the same remote buffer
> to a local read-after-write DRAM buffer.
> ```
??
BTW what is the purpose of this example? I do see nothing about atomic write
___
*[examples/07-atomic-write/server.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GBDd79qR4asAwjp4:-MG3GBDd79qR4asAwjp5:b-adn96l) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L28)):*
> ```
> 1048576
> ```
?? is it 1MiB?
___
*[examples/07-atomic-write/server.c, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GQt--KZMyFgW-kyn:-MG3GQt--KZMyFgW-kyo:b-m745r1) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L61)):*
> ```
> uint64_t used; /* offset data */
> ```
I would propose putting this at the front of the header to avoid any padding data to align the used field.
___
*[examples/07-atomic-write/server.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3H-Em53UXOWmwuYO2:-MG3H-Em53UXOWmwuYO3:b9bu66m) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L131)):*
> ```C
> 	if (ret)
> 		goto err_mr_dereg;
> ```

worth to add here cyclic polling of data.data_offset and show it when it is changed before client has finished connection
to achieve this let's add a small delay between every client attempts to write data to the server


<!-- Sent from Reviewable.io -->

2020-08-31 11:49 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 140 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3J3CH01Ik1l1bZST6:-MG3LGoS0wHSAMCgI3Ni:b-ito7rz) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L140)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ret = rpma_flush(conn, dst_mr, dst_offset, 8,
> 				RPMA_FLUSH_TYPE_PERSISTENT,
> 				RPMA_F_COMPLETION_ALWAYS, FLUSH_ID);
> ```
if(rpma_flush(conn, dst_mr, dst_offset, 8,
				RPMA_FLUSH_TYPE_PERSISTENT,
				RPMA_F_COMPLETION_ALWAYS, FLUSH_ID)
    break;

and in a similar way in all similar places in the loop
with logging enabled we do not need to get ret value and interpreter it - if any of called function failed we goto/break to proper location but ret value is documented by rpmalog
</blockquote></details>

ignore this, I see we need ret at the end of main function


<!-- Sent from Reviewable.io -->

2020-08-31 11:50 UTC, grom72 reviewed
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/README.md, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3FepH20sCEJe1QAI9:-MG3L_jLAkh0IByz_L-A:b-uymrfk) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/README.md#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> For flushing the posted write, it reads eight bytes from the same remote buffer
> to a local read-after-write DRAM buffer.
> ```
??
BTW what is the purpose of this example? I do see nothing about atomic write
</blockquote></details>

We should very precisely document it.


<!-- Sent from Reviewable.io -->

2020-08-31 12:31 UTC, janekmi reviewed
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 36 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/client.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KKxh2TS2HbEwpllz:-MG3KKxh2TS2HbEwplm-:b2nhrub) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L44)):*
> ```C
> 	void *mr_ptr = NULL;
> 	size_t mr_size = 0;
> 	// size_t data_offset = 0;
> ```

XXX
___
*[examples/07-atomic-write/client.c, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KWq1BrG5clJd_Tgv:-MG3KWq1BrG5clJd_Tgw:b-vhwqcz) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L46)):*
> ```C
> 	// size_t data_offset = 0;
> 	enum rpma_mr_plt mr_plt = RPMA_MR_PLT_VOLATILE;
> 	struct rpma_mr_remote *dst_mr = NULL;
> ```

remote_mr? It is sometimes used as a source sometimes as a destination.
___
*[examples/07-atomic-write/client.c, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Kf1c9P8TjFa1ha8O:-MG3Kf1c9P8TjFa1ha8P:b-ic20y8) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L48)):*
> ```C
> 	struct rpma_mr_remote *dst_mr = NULL;
> 	size_t dst_size = 0;
> 	size_t dst_offset = 0;
> ```

Accordingly to the comment above.
___
*[examples/07-atomic-write/client.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KjR58G3SEp8cE9tH:-MG3KjR58G3SEp8cE9tI:b83rj90) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L49)):*
> ```C
> 	size_t dst_size = 0;
> 	size_t dst_offset = 0;
> 	struct rpma_mr_local *src_mr = NULL;
> ```

mr? local_mr? Up to you.
___
*[examples/07-atomic-write/client.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KqrKEOvBl03Sbj3A:-MG3KqrKEOvBl03Sbj3B:bmohoip) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L52)):*
> ```C
> 	struct rpma_completion cmpl;
> 
> 	/* if no pmem support or it is not provided */
> ```

```c
/* prepare memory */
mr_ptr = malloc_alligned(KILOBYTE);
/* ... */
```

This side of the connection does not use PMem at all.
Note: No `if` needed.
___
*[examples/07-atomic-write/client.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3LDy00z7WXGGL1cXD:-MG3LDy00z7WXGGL1cXE:b-vjni9j) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L59)):*
> ```C
> 
> 		mr_size = KILOBYTE;
> 		mr_plt = RPMA_MR_PLT_VOLATILE;
> ```

These two can be done where the variables are defined.
___
*[examples/07-atomic-write/client.c, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Jz4f-a2fJ80K2ALU:-MG3LQn28x89J5NZKDTd:b98myn0) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L69)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ret = client_peer_via_address(addr, &peer);
> 	if (ret)
> 		goto err_free;
> ```
if( ret = client_peer_via_address(addr, &peer) )
	goto err_free;
@janekmi can we make this example shorter?
ret is used only to provide proper exit code
</blockquote></details>

This is a valid construction. If you do not like these extra lines per each `if`, I think we can solve it this way.
@osalyk  would you mind apply this construction to all similar cases?
___
*[examples/07-atomic-write/client.c, line 78 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3LpSp4EHDVgbolZK8:-MG3LpSp4EHDVgbolZK9:by4lknj) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L78)):*
> ```C
> 		goto err_peer_delete;
> 
> 	/* register the memory RDMA write */
> ```

e.g. register the memory for the remote log manipulation
___
*[examples/07-atomic-write/client.c, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3UOE7DbDoudv-OPgZ:-MG3UOE7DbDoudv-OPg_:b-lr5dwi) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L83)):*
> ```C
> 			mr_plt, &src_mr);
> 	if (ret)
> 		goto err_mr_dereg;
> ```

goto err_conn_disconnect;
___
*[examples/07-atomic-write/client.c, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3UVXT9Y0Ofky0_bTI:-MG3UVXT9Y0Ofky0_bTJ:b-ogx0uo) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L89)):*
> ```C
> 	ret = rpma_conn_get_private_data(conn, &pdata);
> 	if (ret != 0 || pdata.len < sizeof(struct common_data))
> 		goto err_conn_disconnect;
> ```

goto err_mr_dereg;
___
*[examples/07-atomic-write/client.c, line 96 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MPHUAuY6mOBhV6JE:-MG3MPHUAuY6mOBhV6JF:b-1eu6f3) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L96)):*
> ```C
> 	 */
> 	struct common_data *dst_data = pdata.ptr;
> 	dst_offset = dst_data->data_offset;
> ```

used_value_offset?
___
*[examples/07-atomic-write/client.c, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3U_6eBZcpjbFpahTs:-MG3U_6eBZcpjbFpahTt:b-ogx0uo) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L99)):*
> ```C
> 	ret = rpma_mr_remote_from_descriptor(&dst_data->desc, &dst_mr);
> 	if (ret)
> 		goto err_conn_disconnect;
> ```

goto err_mr_dereg;
___
*[examples/07-atomic-write/client.c, line 105 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MYDb1dkq10341ARO:-MG3MYDb1dkq10341ARP:b-iyxy88) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L105)):*
> ```C
> 	if (ret)
> 		goto err_mr_remote_delete;
> ```

```/* read the used value */```
___
*[examples/07-atomic-write/client.c, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3McA-9kjdKHahy_t8:-MG3McA-9kjdKHahy_t9:b-ex1j82) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L107)):*
> ```C
> 
> 	ret = rpma_read(conn, src_mr, 0, dst_mr, dst_offset,
> 			8, RPMA_F_COMPLETION_ALWAYS, NULL);
> ```

8 -> sizeof(uint64_t)
___
*[examples/07-atomic-write/client.c, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3UdPQAnoXtQujGomN:-MG3UdPQAnoXtQujGomO:bt3xbnj) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L109)):*
> ```C
> 			8, RPMA_F_COMPLETION_ALWAYS, NULL);
> 	if (ret)
> 		goto err_conn_disconnect;
> ```

goto err_mr_remote_delete;
___
*[examples/07-atomic-write/client.c, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MlCN15ZPVKSfqu6C:-MG3MlCN15ZPVKSfqu6D:bkt3bbj) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L111)):*
> ```C
> 		goto err_conn_disconnect;
> 
> 	uint64_t log_data_offset = *(uint64_t *)mr_ptr;
> ```

used_offset?
___
*[examples/07-atomic-write/client.c, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MvaE1vWVapHLKdyx:-MG3MvaE1vWVapHLKdyy:b32vk6) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L115)):*
> ```C
> 	printf("used value: %lu\n", log_data_offset);
> 
> 	if (dst_size < log_data_offset) {
> ```

<=
___
*[examples/07-atomic-write/client.c, line 117 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3N5bM-df7TdGPkESg:-MG3N5bM-df7TdGPkESh:bur35i) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L117)):*
> ```C
> 	if (dst [...]

2020-08-31 13:04 UTC, janekmi reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 40 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/server.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GBDd79qR4asAwjp4:-MG3YL9Y3z0nlJIv-WmC:by976ar) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L28)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 1048576
> ```
?? is it 1MiB?
</blockquote></details>

Since effectively it is only a number of characters it does not have to be a power of 2. I recommend e.g. 10k or 100k.
___
*[examples/07-atomic-write/server.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3ZF5t82xGd-0n16SV:-MG3ZF5t82xGd-0n16SW:b1g8txn) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L56)):*
> ```C
> 
> #ifdef USE_LIBPMEM
> 	/* log structure in libpmem */
> ```

I see now why it is still WiP. ;-)
___
*[examples/07-atomic-write/server.c, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GQt--KZMyFgW-kyn:-MG3ZP4E3G2Bbw9FtKCg:b-dtfsqr) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> uint64_t used; /* offset data */
> ```
I would propose putting this at the front of the header to avoid any padding data to align the used field.
</blockquote></details>

I believe, alignment, in this case, does not hurt us.
___
*[examples/07-atomic-write/server.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3ZhBY7C62sfF1T80T:-MG3ZhBY7C62sfF1T80U:b7h9af2) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L67)):*
> ```C
> 	struct log_header header;
> 	char data[LOG_DATA_SIZE];
> };
> ```

Please move these structures outside of the function.
___
*[examples/07-atomic-write/server.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Zyq91O5bvmEDZNwC:-MG3Zyq91O5bvmEDZNwD:b-tojqz0) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L79)):*
> ```C
> 	header->used = offsetof(struct log, data);
> 
> 	data_offset = offsetof(struct log_header, used);
> ```

used_value_offset? I'm trying to match the names here to the ones I want to see on the client's side.
___
*[examples/07-atomic-write/server.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3H-Em53UXOWmwuYO2:-MG3_nYz46wX5GWao74Q:b-td2ljd) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

worth to add here cyclic polling of data.data_offset and show it when it is changed before client has finished connection
to achieve this let's add a small delay between every client attempts to write data to the server
</blockquote></details>

Nice touch. But... would you mind to add it later e.g. on Friday? x-D
___
*[examples/07-atomic-write/server.c, line 141 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3a6JB3MX2QdEpBvW1:-MG3a6JC93elGd0Syogi:b5w13z1) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L141)):*
> ```C
> 
> 	printf("used: %lu\ndata_offset: %lu\n", log->header.used,
> 			data.data_offset);
> ```

Please print all the strings added / or present in the log. If you will have any issues with this please let me know.


<!-- Sent from Reviewable.io -->

2020-08-31 13:36 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 40 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/07-atomic-write/client.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3g7XuC7Dbnz1IVB_0:-MG3g7Xv8WBtFkjB78i0:b-ja9e9q) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L56)):*
> ```C
> 		mr_ptr = malloc_aligned(KILOBYTE);
> 		if (mr_ptr == NULL)
> 			return -1;
> ```

why do we use here return -1 instead of exit(-1)?
___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KGyt3cHM9G4zLkPD:-MG3be0uDINfmqPX_Yjq:b-qcka7a) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What internal API call you mean?
</blockquote></details>

main() can either succeed or fail. We already use -1 to indicate errors in initial checks. I do not see any additional value to propagate librpma errors outside main()
___
*[examples/07-atomic-write/server.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GBDd79qR4asAwjp4:-MG3iALv3KaVQ9Ppl7gQ:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since effectively it is only a number of characters it does not have to be a power of 2. I recommend e.g. 10k or 100k.
</blockquote></details>

Done
___
*[examples/07-atomic-write/server.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3H-Em53UXOWmwuYO2:-MG3ida80S4Stj2LS04L:b8zvn9) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L131)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nice touch. But... would you mind to add it later e.g. on Friday? x-D
</blockquote></details>

This is the key of atomicity - we check the value and we either see old or new one.


<!-- Sent from Reviewable.io -->

2020-09-01 05:42 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 40 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KGyt3cHM9G4zLkPD:-MG7Atkv6cZG_20FYDeu:b-7gvtfq) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

main() can either succeed or fail. We already use -1 to indicate errors in initial checks. I do not see any additional value to propagate librpma errors outside main()
</blockquote></details>

After the offline exchange, I like your idea. @osalyk if you want to see how it look like in practice please see #312.
___
*[examples/07-atomic-write/server.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3H-Em53UXOWmwuYO2:-MG7AeMc9FlCKig_zq0f:b-agmq3u) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This is the key of atomicity - we check the value and we either see old or new one.
</blockquote></details>

Since you insist... what stop condition do you propose?


<!-- Sent from Reviewable.io -->

2020-09-01 07:05 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 2 of 5 files reviewed, 40 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KKxh2TS2HbEwpllz:-MG75ghFEFgw0wVaQl2i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

XXX
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KWq1BrG5clJd_Tgv:-MG765QiEpkaLtTOeU81:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

remote_mr? It is sometimes used as a source sometimes as a destination.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Kf1c9P8TjFa1ha8O:-MG76I_35x_W5f3VfQrT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Accordingly to the comment above.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KjR58G3SEp8cE9tH:-MG76Vjo4NubI0k31xc3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

mr? local_mr? Up to you.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3KqrKEOvBl03Sbj3A:-MG76ftQBy3KWjGN2JJY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* prepare memory */
mr_ptr = malloc_alligned(KILOBYTE);
/* ... */
```

This side of the connection does not use PMem at all.
Note: No `if` needed.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3g7XuC7Dbnz1IVB_0:-MG76uWV1TL5zIe5kEye:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L56)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why do we use here return -1 instead of exit(-1)?
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3LDy00z7WXGGL1cXD:-MG77Lxt9E-UW1RWBI2k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two can be done where the variables are defined.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3Jz4f-a2fJ80K2ALU:-MG785Ww74KRSX0Bt4kd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is a valid construction. If you do not like these extra lines per each `if`, I think we can solve it this way.
@osalyk  would you mind apply this construction to all similar cases?
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 78 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3LpSp4EHDVgbolZK8:-MG78O8bAJFJTC5RCn1C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

e.g. register the memory for the remote log manipulation
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3UOE7DbDoudv-OPgZ:-MG78V9VAwDBfgcdfCjF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L83)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

goto err_conn_disconnect;
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3UVXT9Y0Ofky0_bTI:-MG78cHX1FZG9uGZxr8k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

goto err_mr_dereg;
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 96 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MPHUAuY6mOBhV6JE:-MG78x1KAqHnBsTLwqTr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L96)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

used_value_offset?
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3U_6eBZcpjbFpahTs:-MG793Zk7f_Qa2tg40DE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

goto err_mr_dereg;
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 105 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MYDb1dkq10341ARO:-MG79CCUD8BaazJ2-mbS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L105)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```/* read the used value */```
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3McA-9kjdKHahy_t8:-MG79ItZDJiUGQ3yNuOJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

8 -> sizeof(uint64_t)
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3UdPQAnoXtQujGomN:-MG79VnD34Z2Xer-b8z2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

goto err_mr_remote_delete;
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MlCN15ZPVKSfqu6C:-MG7BndgADGGtyUIh6TJ:b1mcm8b) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L111)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

used_offset?
</blockquote></details>

used_value?
___
*[examples/07-atomic-write/client.c, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3MvaE1vWVapHLKdyx:-MG7CArP1lYMcCgElQKY:b-896fix) ([raw file](ht [...]

2020-09-01 07:05 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 2 of 5 files reviewed, 40 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3HXgC6IMF5bZNRZjR:-MG7U3i62KIP3hUM5pT4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L165)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm voting for flush. ;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-01 07:43 UTC, janekmi reviewed
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 21 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/07-atomic-write/client.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3g7XuC7Dbnz1IVB_0:-MG7XvKb2X-gbmC_VIQm:b1o4f1c) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L56)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Because we are in the main function. No need to call an extra function to exit from the process. Please revert.
___
*[examples/07-atomic-write/client.c, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bdoiAczMOozAxT77:-MG7bdoiAczMOozAxT78:bap9vn9) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L16)):*
> ```C
> #include <stdio.h>
> 
> #define USAGE_STR "usage: %s <server_address> <port> <word1> [word2] [..]\n"
> ```

`[<word2>]`
___
*[examples/07-atomic-write/client.c, line 52 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7Xp__AAJ7t4erHVtj:-MG7Xp__AAJ7t4erHVtk:b7xdm0m) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L52)):*
> ```C
> 
> 	/* prepare memory */
> 	if (mr_ptr == NULL) {
> ```

This `if` is not needed.
___
*[examples/07-atomic-write/client.c, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7_Qqb2Vqvgqk98krM:-MG7_Qqb2Vqvgqk98krN:bp8fzyp) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L127)):*
> ```C
> 		if ((ret = rpma_flush(conn, remote_mr, used_offset,
> 				sizeof(uint64_t), RPMA_FLUSH_TYPE_PERSISTENT,
> 				RPMA_F_COMPLETION_ON_ERROR, FLUSH_ID)))
> ```

FLUSH_ID -> NULL
___
*[examples/07-atomic-write/client.c, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7_aDID2IxjtXn7iCK:-MG7_aDID2IxjtXn7iCL:b-uvaxyr) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L142)):*
> ```C
> 				RPMA_F_COMPLETION_ALWAYS, FLUSH_ID)))
> 			break;
> ```

`rpma_conn_prepare_completions()` is missing here.
___
*[examples/07-atomic-write/README.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bEta6MUm2cwZkreh:-MG7bEta6MUm2cwZkrei:b-9xgovx) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/README.md#L9)):*
> ```Markdown
> a RDMA write. After the connection is established the server waits for the client to disconnect.
> - The client, if provided (and capable of), prepares a local persistent memory
> (including its contents) and registers it as a writing source.
> ```

Client won't prepare PMem.
___
*[examples/07-atomic-write/README.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bPOGERfEsk_tvcKh:-MG7bPOGERfEsk_tvcKi:b-920kl9) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/README.md#L14)):*
> ```Markdown
> To update the log header we make an atomic write.
> 
> **Note**: If either server or client does not have a pmem path (or it is not
> ```

~~or client~~
___
*[examples/07-atomic-write/README.md, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bUJ6C7ZsMkpFDejR:-MG7bUJ6C7ZsMkpFDejS:bnx7hi0) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/README.md#L28)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<word1>] [<word2>] [<...>]
> ```

The word1 is not optional.
___
*[examples/07-atomic-write/server.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GBDd79qR4asAwjp4:-MG7a0Vx8-eGGVtc0Kbl:b-761nt9) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L28)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I should be more precise: 100k == 100000.
___
*[examples/07-atomic-write/server.c, line 138 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7aeuSBJQ4HZXNaOvO:-MG7aeuSBJQ4HZXNaOvP:b45ge3b) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/server.c#L138)):*
> ```C
> 	/* print log structure */
> 	printf("header->signature: %s\nheader->used: %lu\nlog->data:\n",
> 			log->header.signature, log->header.used);
> ```

I think it is not necessary.
___
*[examples/07-atomic-write/server.c, line 141 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7aoW2AiAwdgo8zZx_:-MG7aoW2AiAwdgo8zZxa:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/server.c#L141)):*
> ```C
> 	char *ptr = log->data;
> 	do {
> 	ptr += printf("%s\n", ptr);
> ```

Indentation.
___
*[examples/07-atomic-write/server.c, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7atGi3QZ3lopYi_pL:-MG7atGi3QZ3lopYi_pM:bxbllo) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/server.c#L142)):*
> ```C
> 	do {
> 	ptr += printf("%s\n", ptr);
> 	} while (*ptr);
> ```

`used` is not needed for the stop condition?


<!-- Sent from Reviewable.io -->

2020-09-01 07:54 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/07-atomic-write/client.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3g7XuC7Dbnz1IVB_0:-MG7cKML--dRWCpAKHSO:b-f31q5m) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Because we are in the main function. No need to call an extra function to exit from the process. Please revert.
</blockquote></details>

But fee lines above we use exit() ...
___
*[examples/07-atomic-write/server.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3H-Em53UXOWmwuYO2:-MG7cdW-DKeo-BYQPCPR:b1qdhmv) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L131)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since you insist... what stop condition do you propose?
</blockquote></details>

Let's fix it next sprint:
- connection events fd as non-blocking
- we poll both: the value and connection_events channel.


<!-- Sent from Reviewable.io -->

2020-09-01 08:00 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/07-atomic-write/README.md, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3FepH20sCEJe1QAI9:-MG7fKuI8NQ63zLkcc8A:b3im079) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/README.md#L13)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Shall we put here more information about log structure itself rather than RPMEM operations which is already described in other examples?


<!-- Sent from Reviewable.io -->

2020-09-01 10:03 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 2 of 5 files reviewed, 14 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3g7XuC7Dbnz1IVB_0:-MG7m4hV-PdVWlMIb-CM:bp3aow6) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/client.c#L56)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But fee lines above we use exit() ...
</blockquote></details>

Reverted.
___
*[examples/07-atomic-write/client.c, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bdoiAczMOozAxT77:-MG7lLQQEa65hVG4BDBD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`[<word2>]`
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 52 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7Xp__AAJ7t4erHVtj:-MG7lSAiCdRVjDro4qJX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This `if` is not needed.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 127 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7_Qqb2Vqvgqk98krM:-MG7mCap651e_yu8UyUl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

FLUSH_ID -> NULL
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7_aDID2IxjtXn7iCK:-MG7oW2eE_aOKSTUhwDg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/client.c#L142)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_conn_prepare_completions()` is missing here.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/README.md, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3FepH20sCEJe1QAI9:-MG868SVB12BVrYLQWXe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/README.md#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we put here more information about log structure itself rather than RPMEM operations which is already described in other examples?
</blockquote></details>

Done.
___
*[examples/07-atomic-write/README.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bEta6MUm2cwZkreh:-MG7vHCY3i2fagDgg0qQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/README.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Client won't prepare PMem.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/README.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bPOGERfEsk_tvcKh:-MG7vMmT6sP_1pQiDoXh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/README.md#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~or client~~
</blockquote></details>

Done.
___
*[examples/07-atomic-write/README.md, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7bUJ6C7ZsMkpFDejR:-MG7vYdd2IZlpSuHulEs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/README.md#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The word1 is not optional.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/318#-MG3GBDd79qR4asAwjp4:-MG837Fm0MdPm9VNxQjj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b479efe0f2a54fb3242933820632f514b4839e91/examples/07-atomic-write/server.c#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I should be more precise: 100k == 100000.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 138 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7aeuSBJQ4HZXNaOvO:-MG7uqIN4Fj8pyaQsHPF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/server.c#L138)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it is not necessary.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 141 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7aoW2AiAwdgo8zZx_:-MG7pGfw3JQLEOvJ1SrE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/server.c#L141)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/318#-MG7atGi3QZ3lopYi_pL:-MG7rXug3Ge6DZK8IcrI:b-wtpjt4) ([raw file](https://github.com/pmem/rpma/blob/937f9c50ec604ec496967a3c519e7de5bb457c4a/examples/07-atomic-write/server.c#L142)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`used` is not needed for the stop condition?
</blockquote></details>

I don't think so.


<!-- Sent from Reviewable.io -->

2020-09-01 15:33 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 19 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/client.c, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG99Lvl-_z38kuUK-gO:-MG99Lvl-_z38kuUK-gP:bialepp) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/client.c#L29)):*
> ```C
> 	if (argc < 4) {
> 		fprintf(stderr, USAGE_STR, argv[0]);
> 		exit(-1);
> ```

@grom72 is right. Please put a `return -1` here.
___
*[examples/07-atomic-write/server.c, line 28 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG99e488McL6FfxgK4G:-MG99e488McL6FfxgK4H:b-7d1o9v) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L28)):*
> ```C
> #define LOG_HDR_SIGNATURE "LOG"
> #define LOG_SIGNATURE_SIZE 8
> #define LOG_DATA_SIZE 100000 /* 100k B */
> ```

~~B~~
___
*[examples/07-atomic-write/server.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9DTcK37w4DnqvXefV:-MG9DTcK37w4DnqvXefW:bvs182i) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L33)):*
> ```C
> struct log_header {
> 	char signature[LOG_SIGNATURE_SIZE];
> 	uint64_t used; /* offset data */
> ```

```c
/* last written data (note the field is aligned to RPMA_ATOMIC_WRITE_ALIGNMENT) */
```
___
*[examples/07-atomic-write/server.c, line 40 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9E1gQ7uK4LcJrEsow:-MG9E1gQ7uK4LcJrEsox:bh9h156) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L40)):*
> ```C
> 	struct log_header header;
> 	char data[LOG_DATA_SIZE];
> };
> ```

I think for the sake of simplicity you can `data` field to `log_header` structure and rename it as the `log`.
I do not see why we need here two structures.
___
*[examples/07-atomic-write/server.c, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG99sAj9bsv3UGzt2_j:-MG99sAj9bsv3UGzt2_k:b-9bkwop) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L48)):*
> ```C
> 	if (argc < 3) {
> 		fprintf(stderr, USAGE_STR, argv[0]);
> 		exit(-1);
> ```

`return -1`
___
*[examples/07-atomic-write/server.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9ETroDSYZ8tQZgKw2:-MG9ETroDSYZ8tQZgKw3:bfr5hxs) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L63)):*
> ```C
> 	void *mr_ptr = NULL;
> 	size_t mr_size = 0;
> 	size_t data_offset = 0;
> ```

Not used?
___
*[examples/07-atomic-write/server.c, line 92 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9E_Uf2Nq6ptFc2-lK:-MG9E_Uf2Nq6ptFc2-lL:bydqkjs) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L92)):*
> ```C
> 		 * as a persistent store.
> 		 */
> 		if (mr_size < SIGNATURE_LEN) {
> ```

LOG_SIGNATURE_SIZE
___
*[examples/07-atomic-write/server.c, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9Ee1A9YBr6MBi6ZX1:-MG9Ee1A9YBr6MBi6ZX2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L94)):*
> ```C
> 		if (mr_size < SIGNATURE_LEN) {
> 			(void) fprintf(stderr, "%s too small (%zu < %zu)\n",
> 					path, mr_size, SIGNATURE_LEN);
> ```

.
___
*[examples/07-atomic-write/server.c, line 98 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9EdH8C0CzYaSzo73E:-MG9EdH8C0CzYaSzo73F:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L98)):*
> ```C
> 			return -1;
> 		}
> 		data_offset = SIGNATURE_LEN;
> ```

.
___
*[examples/07-atomic-write/server.c, line 119 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9AB7E3JTQe7BG1oII:-MG9AB7E3JTQe7BG1oIJ:b-ay0nep) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L119)):*
> ```C
> 			char *ch = (char *)mr_ptr + data_offset;
> 			ch[0] = '\0';
> 			pmem_persist(ch, 1);
> ```

We do not have to initialize any string here. We have to initialize `used` e.g.:
```c
struct log *log = mr_ptr;
log->used = offsetof(struct log, data);
pmem_persist(&log->used, sizeof(uint64_t));
```
___
*[examples/07-atomic-write/server.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9Ei2K-dmwXtVMotHW:-MG9Ei2K-dmwXtVMotHX:b1465t2) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L121)):*
> ```C
> 			pmem_persist(ch, 1);
> 			/* write the signature to mark the content as valid */
> 			memcpy(mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
> ```

LOG_HDR_SIGNATURE, LOG_SIGNATURE_SIZE
___
*[examples/07-atomic-write/server.c, line 122 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9EkuaDFpp_Apyl2JK:-MG9EkuaDFpp_Apyl2JL:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L122)):*
> ```C
> 			/* write the signature to mark the content as valid */
> 			memcpy(mr_ptr, SIGNATURE_STR, SIGNATURE_LEN);
> 			pmem_persist(mr_ptr, SIGNATURE_LEN);
> ```

.
___
*[examples/07-atomic-write/server.c, line 143 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9FL3-4F4YJ7-6Yd6z:-MG9FL3-4F4YJ7-6Yd7-:bfz9l1y) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L143)):*
> ```C
> 	struct log_header *header = &log->header;
> 	strncpy(header->signature, LOG_HDR_SIGNATURE,
> 			LOG_SIGNATURE_SIZE);
> ```

The signature is already initialized for pmem. For DRAM, the signature is meaningless.
___
*[examples/07-atomic-write/server.c, line 144 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9Febx8IGgZUtAleuj:-MG9Febx8IGgZUtAleuk:b6zgjt8) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L144)):*
> ```C
> 	strncpy(header->signature, LOG_HDR_SIGNATURE,
> 			LOG_SIGNATURE_SIZE);
> 	header->used = offsetof(struct log, data);
> ```

This is already done for pmem. For DRAM, please move it to the if above.
___
*[examples/07-atomic-write/server.c, line 146 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GCERCs8ZgzJ0rT90:-MG9GCERCs8ZgzJ0rT91:bx1z2p5) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L146)):*
> ```C
> 	header->used = offsetof(struct log, data);
> 
> 	used_offset = offsetof(struct log_header, used);
> ```

This can be done on the definition point.
___
*[examples/07-atomic-write/server.c, line 171 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GY3f6uOrKT3NpdVy:-MG9GY3f6uOrKT3NpdVz:b-givhdt) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L171)):*
> ```C
> 	/* calculate data for the client write */
> 	struct common_data data;
> 	data.data_offset = used_offset;
> ```

Maybe the variable is not needed for a single assignment.
___
*[examples/07-atomic-write/server.c, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GwGr4eFpKXimgdTM:-MG9GwGr4eFpKXimgdTN:byd1jvw) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L198)):*
> ```C
> 	do {
> 		ptr += printf("%s\n", ptr);
> 	} while (*ptr);
> ```

According to [printf(3)](https://linux.die.net/man/3/printf), the return value of `printf` does not include the null byte so...
`*ptr` after the first round will point the null-byte. The log itself does not know where it ends...
In my opinion, it should look as follows:

```c
do {
    ptr += printf("%s\n", ptr) + 1;

 [...]

2020-09-01 15:49 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 21 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/README.md, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9LK-P6LHNlZgzolCQ:-MG9LK-P6LHNlZgzolCR:b-2mxv8k) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/README.md#L23)):*
> ```Markdown
> - The client, prepares a local memory (including its contents) and registers it as a writing source.
> After the connection is established the client receives the server's memory regions registered
> as a writing destination. The client reads the offset under which it can write data. It saves the data and then updates value of the field used with rpma_write_atomic.
> ```

# My proposition is as follows:

The atomic write example shows a simple remote log manipulation where two
parts of the process are implemented:
- The server, if provided (and capable of), prepares a local persistent memory.
The memory is filled with an initial log state. The simplest log structure
looks as follow:

```c
struct log {
	char signature[LOG_SIGNATURE_SIZE];
	/* last written data (note the field is aligned to RPMA_ATOMIC_WRITE_ALIGNMENT) */
	uint64_t used;
	char data[]
};
```

The client along with the exposed memory descriptor receives an offset of
the `used` field. Which is enough to read the current state of the log and
perform an append. After the connection is established the server waits for
the client to disconnect.
- The client, after the connection is established, receives the server's
memory descriptor and the `used` offset. The client reads the `used` value.
Having that, the client writes and flushes the new data at the end of the log.
Without waiting for both operations completions the client can perform
an atomic write of the new `used` value and flush it. The client has to wait
for the last flush completion before appending another entry to the log.
When the client is done it simply disconnects from the server.
___
*[examples/07-atomic-write/README.md, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9LyDa-NZ6L-OvGMJH:-MG9LyDa-NZ6L-OvGMJI:bp9txvu) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/README.md#L25)):*
> ```Markdown
> as a writing destination. The client reads the offset under which it can write data. It saves the data and then updates value of the field used with rpma_write_atomic.
> 
> **Note**: If either server does not have a pmem path (or it is not
> ```

~~either~~


<!-- Sent from Reviewable.io -->

2020-09-02 06:40 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/07-atomic-write/server.c, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GwGr4eFpKXimgdTM:-MGCX00H2LjjsRW1dfyi:b-vyt6ii) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L198)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

According to [printf(3)](https://linux.die.net/man/3/printf), the return value of `printf` does not include the null byte so...
`*ptr` after the first round will point the null-byte. The log itself does not know where it ends...
In my opinion, it should look as follows:

```c
do {
    ptr += printf("%s\n", ptr) + 1;

/* current offset < the last written data offset */
} while (ptr - log < log->used);
```
</blockquote></details>

```
char *log_data_tail = log + log->used;
do {
      if (*ptr)
          putc( *ptr, stdout );
     else
         putc(' ',stdout);
    ptr++;
} while (ptr < log_data_tail);
```


<!-- Sent from Reviewable.io -->

2020-09-02 06:43 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/07-atomic-write/server.c, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GwGr4eFpKXimgdTM:-MGCYGZZC0P6aXOrIIxR:bl06mbg) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L198)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
char *log_data_tail = log + log->used;
do {
      if (*ptr)
          putc( *ptr, stdout );
     else
         putc(' ',stdout);
    ptr++;
} while (ptr < log_data_tail);
```
</blockquote></details>

log + log->used or log->data + log->used?


<!-- Sent from Reviewable.io -->

2020-09-02 06:51 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 2 of 5 files reviewed, 20 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 29 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG99Lvl-_z38kuUK-gO:-MGCCBCx5LMm4C7GvLNB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/client.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@grom72 is right. Please put a `return -1` here.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/README.md, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9LK-P6LHNlZgzolCQ:-MGCDAW2BnHiVeGxI4Db:bjf4yu7) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/README.md#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

# My proposition is as follows:

The atomic write example shows a simple remote log manipulation where two
parts of the process are implemented:
- The server, if provided (and capable of), prepares a local persistent memory.
The memory is filled with an initial log state. The simplest log structure
looks as follow:

```c
struct log {
	char signature[LOG_SIGNATURE_SIZE];
	/* last written data (note the field is aligned to RPMA_ATOMIC_WRITE_ALIGNMENT) */
	uint64_t used;
	char data[]
};
```

The client along with the exposed memory descriptor receives an offset of
the `used` field. Which is enough to read the current state of the log and
perform an append. After the connection is established the server waits for
the client to disconnect.
- The client, after the connection is established, receives the server's
memory descriptor and the `used` offset. The client reads the `used` value.
Having that, the client writes and flushes the new data at the end of the log.
Without waiting for both operations completions the client can perform
an atomic write of the new `used` value and flush it. The client has to wait
for the last flush completion before appending another entry to the log.
When the client is done it simply disconnects from the server.
</blockquote></details>

Looks much better, thanks.
___
*[examples/07-atomic-write/README.md, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9LyDa-NZ6L-OvGMJH:-MGCDHG95kmhg-iIm6yi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/README.md#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~either~~
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 28 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG99e488McL6FfxgK4G:-MGC_9HQBZ5EjvHFhjyE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~B~~
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9DTcK37w4DnqvXefV:-MGCDVsK4oMtqz2R0SS0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* last written data (note the field is aligned to RPMA_ATOMIC_WRITE_ALIGNMENT) */
```
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 40 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9E1gQ7uK4LcJrEsow:-MGCDadM-lB-3EqcyVj8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think for the sake of simplicity you can `data` field to `log_header` structure and rename it as the `log`.
I do not see why we need here two structures.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG99sAj9bsv3UGzt2_j:-MGCDePR2EQGvEOQz_hy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`return -1`
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9ETroDSYZ8tQZgKw2:-MGCLH2n6zIZ0HwjgEDb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 92 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9E_Uf2Nq6ptFc2-lK:-MGCECMZE7Lvf1opr310:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

LOG_SIGNATURE_SIZE
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9Ee1A9YBr6MBi6ZX1:-MGCEMo7-ZIggVcGX29L:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 98 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9EdH8C0CzYaSzo73E:-MGCERDO9FiNSIGOEbAm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 119 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9AB7E3JTQe7BG1oII:-MGCFOoxEm6PV-c7cHRO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We do not have to initialize any string here. We have to initialize `used` e.g.:
```c
struct log *log = mr_ptr;
log->used = offsetof(struct log, data);
pmem_persist(&log->used, sizeof(uint64_t));
```
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9Ei2K-dmwXtVMotHW:-MGCFeA05LgvBipBUSi5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L121)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

LOG_HDR_SIGNATURE, LOG_SIGNATURE_SIZE
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 122 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9EkuaDFpp_Apyl2JK:-MGCFfAREWmcFV71Fa1-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 143 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9FL3-4F4YJ7-6Yd6z:-MGCY_AR6DvKt18AF2Me:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L143)):*
<details><summary><i>Previously, ja [...]

2020-09-02 08:55 UTC, grom72 reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 19 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/server.c, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GwGr4eFpKXimgdTM:-MGD-w6PBiB7lME5Xcj7:bfpoila) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L198)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

my fault - is it possible that log is empty - in such case, we should have wither while() { } loop or only be executed when log->used >0


<!-- Sent from Reviewable.io -->

2020-09-02 09:21 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/server.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9ETroDSYZ8tQZgKw2:-MGD5q4T-mo0zyR0gmmC:b-sqpqd9) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L63)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`data_offset` is still not used.
___
*[examples/07-atomic-write/server.c, line 195 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGD6_Qb7xic7063AuSZ:-MGD6_Qb7xic7063AuS_:b2nhvbc) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/server.c#L195)):*
> ```C
> 			putc(*ptr, stdout);
> 		else
> 			putc(' ', stdout);
> ```

\n?


<!-- Sent from Reviewable.io -->

2020-09-02 09:43 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGDBkX_C-xFbUFPNRuZ:-MGDBkXaAg6WHTwCfQyR:bybou4q) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/client.c#L99)):*
> ```C
> 			sizeof(uint64_t), RPMA_F_COMPLETION_ALWAYS, NULL)))
> 		goto err_mr_remote_delete;
> ```

You have to wait for completion before accessing the read value.


<!-- Sent from Reviewable.io -->

2020-09-02 09:46 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 119 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGDCKNx02DmwA_bQLyC:-MGDCKNx02DmwA_bQLyD:bg3am2c) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/client.c#L119)):*
> ```C
> 			break;
> 
> 		if ((ret = rpma_flush(conn, remote_mr, used_offset,
> ```

used_value


<!-- Sent from Reviewable.io -->

2020-09-02 09:50 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/server.c, line 190 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGDDLar5nIpdYn5XJj1:-MGDDLar5nIpdYn5XJj2:b-w3xcsl) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/server.c#L190)):*
> ```C
> 	/* print the saved data */
> 	char *ptr = log->data;
> 	char *log_data_tail = log->data + log->used;
> ```

`(char *)log + log->used`


<!-- Sent from Reviewable.io -->

2020-09-02 09:59 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGDBkX_C-xFbUFPNRuZ:-MGDFQG72xB4Fr5T-7qO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/client.c#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to wait for completion before accessing the read value.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 119 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGDCKNx02DmwA_bQLyC:-MGDE6kx382MBUjaETZR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/client.c#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

used_value
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9ETroDSYZ8tQZgKw2:-MGDADJ20tF_KBXt8AjU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`data_offset` is still not used.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/318#-MG9GwGr4eFpKXimgdTM:-MGD8j474LQojkaaTpev:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a331dfd987d37cf5d20e2a133617c24c7c87d4b/examples/07-atomic-write/server.c#L198)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

my fault - is it possible that log is empty - in such case, we should have wither while() { } loop or only be executed when log->used >0
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 190 at r4](https://reviewable.io/reviews/pmem/rpma/318#-MGDDLar5nIpdYn5XJj1:-MGDDvop9fgMrmTInJBI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1dc350edbdc4e3bdb7175764955ce5cea13eb9c3/examples/07-atomic-write/server.c#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`(char *)log + log->used`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-02 10:11 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/client.c, line 106 at r5](https://reviewable.io/reviews/pmem/rpma/318#-MGDI-hX1ca6glX9-1Py:-MGDI-hY5NkQJtH9NTRC:bfohid2) ([raw file](https://github.com/pmem/rpma/blob/5ece62737ef889068fbf68c5324a06e027c9f0d5/examples/07-atomic-write/client.c#L106)):*
> ```C
> 	if ((ret = rpma_conn_next_completion(conn, &cmpl)))
> 		goto err_mr_remote_delete;
> ```

I have forgot:
```
if (cmpl.op_status != IBV_WC_SUCCESS) {
			(void) fprintf(stderr, "rpma_flush failed with %d\n",
					cmpl.op_status);
			break;
		}
```

or similar. ;-)


<!-- Sent from Reviewable.io -->

2020-09-02 10:16 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/server.c, line 113 at r5](https://reviewable.io/reviews/pmem/rpma/318#-MGDJHf2DkRS4hVwTN9L:-MGDJHf2DkRS4hVwTN9M:b-85dbfa) ([raw file](https://github.com/pmem/rpma/blob/5ece62737ef889068fbf68c5324a06e027c9f0d5/examples/07-atomic-write/server.c#L113)):*
> ```C
> 		 * to be initialized and persisted.
> 		 */
> 		if (strncmp(mr_ptr, SIGNATURE_STR, SIGNATURE_LEN) != 0) {
> ```

LOG_*


<!-- Sent from Reviewable.io -->

2020-09-02 10:25 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-02 10:27 UTC, grom72 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318#-:-MGDLmpwAeryRU0jPrV1:bdycpsm)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-02 10:27 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 106 at r5](https://reviewable.io/reviews/pmem/rpma/318#-MGDI-hX1ca6glX9-1Py:-MGDK70K2pfbB-NHGYaD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ece62737ef889068fbf68c5324a06e027c9f0d5/examples/07-atomic-write/client.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have forgot:
```
if (cmpl.op_status != IBV_WC_SUCCESS) {
			(void) fprintf(stderr, "rpma_flush failed with %d\n",
					cmpl.op_status);
			break;
		}
```

or similar. ;-)
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 113 at r5](https://reviewable.io/reviews/pmem/rpma/318#-MGDJHf2DkRS4hVwTN9L:-MGDJooK9op1ugX0WYb1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ece62737ef889068fbf68c5324a06e027c9f0d5/examples/07-atomic-write/server.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

LOG_*
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-02 10:30 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-02 10:42 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/318#-:-MGDPIbK0Sj-GuyQLkCg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/rpma/318#-MGDPCt7DrvcwvNy3ZqJ:-MGDIkJnAOEc53wN3HQY:b-lcvcje) (no related file):*
FYI The example works fine on FSDAX, DevDAX and DRAM.

---


<!-- Sent from Reviewable.io -->

2020-09-02 10:43 UTC, merged