examples: make sure the server's process is finished
pmem/rpma pull request #333
Opened 2020-09-02 12:33 UTC by ldorau

Make sure the server's process is finished,
before starting a new one.

2020-09-02 13:44 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/333)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/333#-MGE2gVR30JCI1V7a3Z0:-MGE2gVS9-0NnyfsxliL:b-esyx49) ([raw file](https://github.com/pmem/rpma/blob/dd13307a63fed04e1685c1e1a63ff9601e0fd296/examples/run-all-on-SoftRoCE.sh#L73)):*
> ```Shell
> 		kill $PID
> 		sleep 1
> 		kill -9 $PID 2>/dev/null
> ```

Why you are killing it two times?
Why not verify if it is killed and... fail otherwise?


<!-- Sent from Reviewable.io -->

2020-09-02 13:46 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/333)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/333#-MGE2gVR30JCI1V7a3Z0:-MGE3Q86Ar5Fw-zBOBw0:b-k6nwrz) ([raw file](https://github.com/pmem/rpma/blob/dd13307a63fed04e1685c1e1a63ff9601e0fd296/examples/run-all-on-SoftRoCE.sh#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why you are killing it two times?
Why not verify if it is killed and... fail otherwise?
</blockquote></details>

1st - SIGTERM
2nd - SIGKILL


<!-- Sent from Reviewable.io -->

2020-09-02 14:20 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/333#-:-MGEBAkx3VQZTMhejB-T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-03 06:19 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/333#-:-MGHbktS-0u-DvAyLRxh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-03 06:26 UTC, merged