common: redundant error message removed
pmem/rpma pull request #360
Opened 2020-09-04 16:23 UTC by grom72

Librpma already provide WARNING when the result is != IBV_WC_SUCCESS
Here a high level message is only needed.

2020-09-07 05:46 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/08-messages-ping-pong/client.c, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/360#-MGb3Ynp1r_hQPd0e5Vv:-MGb3Ynp1r_hQPd0e5Vw:b2zgz3f) ([raw file](https://github.com/pmem/rpma/blob/19bcd6c82fa19853871e970b866ec3f270af675f/examples/08-messages-ping-pong/client.c#L129)):*
> ```C
> 					cmpl.op == RPMA_OP_SEND ? "send msg":
> 					cmpl.op == RPMA_OP_RECV ? "post recv":
> 					"execute unknown operation");
> ```

1) s/`Client will shutdown.`/`Shutting down the client.`/g
2) Please do not use abbreviations from the code:
    a) s/`Could not send msg`/`Could not send a message`/g
    b) s/`Could not post recv`/`Could not post a receive`/g ??? - However I am not sure `Could not post a receive`is a correct sentence in English ...
3) `Could not execute AN unknown operation` - IMHO it sounds very strange (unknown operation???)

Maybe the original messages (ibv_wc_status_str(cmpl.op_status)) are more clear ?


<!-- Sent from Reviewable.io -->

2020-09-07 07:23 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/client.c, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/360#-MGb3Ynp1r_hQPd0e5Vv:-MGbP4Yb2gQLjEx30exU:bdkfbg8) ([raw file](https://github.com/pmem/rpma/blob/19bcd6c82fa19853871e970b866ec3f270af675f/examples/08-messages-ping-pong/client.c#L129)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) s/`Client will shutdown.`/`Shutting down the client.`/g
2) Please do not use abbreviations from the code:
    a) s/`Could not send msg`/`Could not send a message`/g
    b) s/`Could not post recv`/`Could not post a receive`/g ??? - However I am not sure `Could not post a receive`is a correct sentence in English ...
3) `Could not execute AN unknown operation` - IMHO it sounds very strange (unknown operation???)

Maybe the original messages (ibv_wc_status_str(cmpl.op_status)) are more clear ?
</blockquote></details>

Done.
- original message ibv_wc_status_str(...) is in the log. No point to repeat it here


<!-- Sent from Reviewable.io -->

2020-09-07 07:49 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[examples/08-messages-ping-pong/client.c, line 126 at r2](https://reviewable.io/reviews/pmem/rpma/360#-MGbXX0b8bo9xIi7cyub:-MGbXX0b8bo9xIi7cyuc:b-xhv5p2) ([raw file](https://github.com/pmem/rpma/blob/25ad596a5613d53d06990e1f404a8e215921d31f/examples/08-messages-ping-pong/client.c#L126)):*
> ```
> Client will shutdown due to unsuccessful operation completion.\n"
> ```

`"Shutting down the client due to unsuccessful completion of an operation.\n"`


<!-- Sent from Reviewable.io -->

2020-09-07 07:49 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-09-07 07:55 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/08-messages-ping-pong/client.c, line 126 at r2](https://reviewable.io/reviews/pmem/rpma/360#-MGbXX0b8bo9xIi7cyub:-MGbZ3xy0yl0TGpmj_T8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/25ad596a5613d53d06990e1f404a8e215921d31f/examples/08-messages-ping-pong/client.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Client will shutdown due to unsuccessful operation completion.\n"
> ```

`"Shutting down the client due to unsuccessful completion of an operation.\n"`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 15:49 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/08-messages-ping-pong/client.c, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/360#-MGnYd18DDiof8DkgVbq:-MGnYd18DDiof8DkgVbr:b-h076r5) ([raw file](https://github.com/pmem/rpma/blob/efdab817549071640833a261fb6715beb38b47b7/examples/08-messages-ping-pong/client.c#L126)):*
> ```C
> 
> 				(void) fprintf(stderr,
> 					"Shutting down the client due to unsuccessful completion of an operation.\n");
> ```

Shutting down the client due to **the** unsuccessful completion of an operation.


<!-- Sent from Reviewable.io -->

2020-09-10 05:45 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[examples/08-messages-ping-pong/client.c, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/360#-MGnYd18DDiof8DkgVbq:-MGqY1DzBU5sJdJPmbPv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/efdab817549071640833a261fb6715beb38b47b7/examples/08-messages-ping-pong/client.c#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Shutting down the client due to **the** unsuccessful completion of an operation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-10 07:04 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/08-messages-ping-pong/client.c, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/360#-MGnYd18DDiof8DkgVbq:-MGqozbjB7IoJN2tmiEd:bjzotj5) ([raw file](https://github.com/pmem/rpma/blob/efdab817549071640833a261fb6715beb38b47b7/examples/08-messages-ping-pong/client.c#L126)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Our English is becoming almost perfect ;-)


<!-- Sent from Reviewable.io -->

2020-09-10 07:04 UTC, ldorau reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360#-:-MGqp8JG6JO08kRLGdWj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-10 07:05 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/08-messages-ping-pong/client.c, line 126 at r4](https://reviewable.io/reviews/pmem/rpma/360#-MGnYd18DDiof8DkgVbq:-MGqpDExDyJkcMNxPgI8:b-o3gp68) ([raw file](https://github.com/pmem/rpma/blob/efdab817549071640833a261fb6715beb38b47b7/examples/08-messages-ping-pong/client.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Our English is becoming almost perfect ;-)
</blockquote></details>

In this sentence not almost, just perfect ;-)


<!-- Sent from Reviewable.io -->

2020-09-10 10:08 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-10 10:08 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/360#-:-MGrU9qP8EiRBoXVibhD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-10 10:08 UTC, merged