examples: fix non null terminated string
pmem/rpma pull request #371
Opened 2020-09-08 05:59 UTC by osalyk

Forced by the static analyzer which has pointed out
that strncpy *theoretically* may not null-terminate the output string.

2020-09-08 15:13 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/06-multiple-connections/client.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/371#-MGiGoN40pfVa7TlJzRv:-MGiGoN5719QTNI2ijfK:b2ngv06) ([raw file](https://github.com/pmem/rpma/blob/1a089ab936c3185466836e7f906ad1f3978063e2/examples/06-multiple-connections/client.c#L90)):*
> ```C
> 	srand(seed % UINT_MAX);
> 	const char *name = Names[(long unsigned int)rand() % NAMES_NUM];
> 	(void) strncpy((char *)mr_ptr, name, MAX_NAME_SIZE);
> ```

-1?


<!-- Sent from Reviewable.io -->

2020-09-09 06:04 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/06-multiple-connections/client.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/371#-MGiGoN40pfVa7TlJzRv:-MGlSW2eERPrelGkNCtp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a089ab936c3185466836e7f906ad1f3978063e2/examples/06-multiple-connections/client.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

-1?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-09 12:37 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/06-multiple-connections/client.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/371#-MGiGoN40pfVa7TlJzRv:-MGmrYWnC2eVX8pT1BpQ:b-83og3x) ([raw file](https://github.com/pmem/rpma/blob/1a089ab936c3185466836e7f906ad1f3978063e2/examples/06-multiple-connections/client.c#L90)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope.


<!-- Sent from Reviewable.io -->

2020-09-10 05:31 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/06-multiple-connections/client.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/371#-MGiGoN40pfVa7TlJzRv:-MGqUfbzBB7AEBBMheWR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a089ab936c3185466836e7f906ad1f3978063e2/examples/06-multiple-connections/client.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-10 05:41 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-10 08:02 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371#-:-MGr1Cs63uPcYZagXRUV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-10 10:51 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/371#-:-MGrd24q91DsJ3pIJgTi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-10 11:08 UTC, merged