common: fix checking signature of rdma_getaddrinfo()
pmem/rpma pull request #395
Opened 2020-09-11 12:08 UTC by ldorau

Older compilers may not support the '-Werror=discarded-qualifiers' flag.
In this case a signature of rdma_getaddrinfo() has to be verified
by grepping the 'rdma_cma.h' header file.

2020-09-12 10:37 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/functions.cmake, line 178 at r1](https://reviewable.io/reviews/pmem/rpma/395#-MH0sAkc5h1MFbbhoF_X:-MH0rcxi9ifa6imfc484:bfvu5za) ([raw file](https://github.com/pmem/rpma/blob/d5bde64bdb920b43bd968d77528ae2966b6e2d97/cmake/functions.cmake#L178)):*
> ```CMake
> 		endif()
> 		return()
> 	endif()
> ```

I recommend the following order:
1. CHECK_C_COMPILER_FLAG
2. if C_HAS_Werror_discarded_qualifiers then
    - CHECK_C_SOURCE_COMPILES
    - return
3. file (REGEX) as a fallback

This way, the function will be easier to follow. We are doing a simple thing if it is possible or fallback to a hackier way if it is necessary.


<!-- Sent from Reviewable.io -->

2020-09-12 10:37 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2020-09-14 07:39 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/functions.cmake, line 178 at r1](https://reviewable.io/reviews/pmem/rpma/395#-MH0sAkc5h1MFbbhoF_X:-MHAYUkK45QUELZUt9vR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d5bde64bdb920b43bd968d77528ae2966b6e2d97/cmake/functions.cmake#L178)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend the following order:
1. CHECK_C_COMPILER_FLAG
2. if C_HAS_Werror_discarded_qualifiers then
    - CHECK_C_SOURCE_COMPILES
    - return
3. file (REGEX) as a fallback

This way, the function will be easier to follow. We are doing a simple thing if it is possible or fallback to a hackier way if it is necessary.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-16 21:41 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395#-:-MHNrMeV2-4xRsJosrbu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-16 21:47 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/functions.cmake, line 205 at r2](https://reviewable.io/reviews/pmem/rpma/395#-MHNsZ_5Eccg4EvCLNte:-MHNsKBx2EFRFYtztHx1:b-f65xmo) ([raw file](https://github.com/pmem/rpma/blob/e8b47b9a4539be2bbdf65e2ad2e1c3ac903fac49/cmake/functions.cmake#L205)):*
> ```CMake
> 	if(CORRECT_SIGNATURE_FOUND)
> 		message(NOTICE "-- Performing Test SIGNATURE_OK_RDMA_GETADDRINFO - Success")
> 		set(SIGNATURE_OK_RDMA_GETADDRINFO 1 PARENT_SCOPE)
> ```

`set(var 1 PARENT_SCOPE)`?


<!-- Sent from Reviewable.io -->

2020-09-17 05:52 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/functions.cmake, line 205 at r2](https://reviewable.io/reviews/pmem/rpma/395#-MHNsZ_5Eccg4EvCLNte:-MHPbK-r3yJuz1Pvk2xo:b3usw62) ([raw file](https://github.com/pmem/rpma/blob/e8b47b9a4539be2bbdf65e2ad2e1c3ac903fac49/cmake/functions.cmake#L205)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`set(var 1 PARENT_SCOPE)`?
</blockquote></details>

Yes, it should be like that, but for unknown reason it does not work :-( I have tested it many times ...


<!-- Sent from Reviewable.io -->

2020-09-17 11:43 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395#-:-MHQs5pe7lDPB9pkCGEM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-17 12:30 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/functions.cmake, line 205 at r2](https://reviewable.io/reviews/pmem/rpma/395#-MHNsZ_5Eccg4EvCLNte:-MHR1hjz5LsNd3_k9WA5:b-r7fjxg) ([raw file](https://github.com/pmem/rpma/blob/e8b47b9a4539be2bbdf65e2ad2e1c3ac903fac49/cmake/functions.cmake#L205)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it should be like that, but for unknown reason it does not work :-( I have tested it many times ...
</blockquote></details>

Please give at least a XXX comment.


<!-- Sent from Reviewable.io -->

2020-09-17 12:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/functions.cmake, line 205 at r2](https://reviewable.io/reviews/pmem/rpma/395#-MHNsZ_5Eccg4EvCLNte:-MHR2a6D1scVDy67ZRtn:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/e8b47b9a4539be2bbdf65e2ad2e1c3ac903fac49/cmake/functions.cmake#L205)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please give at least a XXX comment.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2020-09-17 12:36 UTC, janekmi approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/395)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-18 21:02 UTC, merged