rpma: remove rpma_mr_descriptor structure
pmem/rpma pull request #404
Opened 2020-09-15 06:34 UTC by osalyk

- [ ] improve tests
- [ ] improve examples

2020-09-15 06:39 UTC, ldorau reviewed
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 4 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-15 09:19 UTC, ldorau reviewed
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 403 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG21mB9vLoBy4QMTMW:-MHG21mCANn-JNMjIlYD:b5oc6t5) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L403)):*
> ```
> get a descriptor size of memory region
> ```

`get size of a memory region descriptor`
___
*[src/mr.c, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2gZV03Uezjsk2Vz7:-MHG2gZV03Uezjsk2Vz8:b-nj065q) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L407)):*
> ```
> int
> rpma_mr_get_descriptor_size(struct rpma_mr_local *mr,
> 		void *desc, size_t *desc_size)
> ```

```
int
rpma_mr_get_descriptor_size(size_t *desc_size)
```
___
*[src/mr.c, line 410 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2a4kBVAE0TpiUyNM:-MHG2a4kBVAE0TpiUyNN:bjhc66y) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L410)):*
> ```
> if (mr == NULL || desc == NULL)
> 		return RPMA_E_INVAL;
> ```

Unnecessary, `mr` and `desc` are not used
___
*[src/mr.c, line 412 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2J828EaQisrlHlOd:-MHG2J828EaQisrlHlOe:b8no248) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L412)):*
> ```C
> 		return RPMA_E_INVAL;
> 
> 	*desc_size = (2 * sizeof(uint64_t)) + sizeof(uint32_t);
> ```

`... +  + sizeof(uint8_t);`
___
*[src/include/librpma.h, line 353 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHFvteK5li84-yBVDMG:-MHFvteK5li84-yBVDMH:b-7h28da) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L353)):*
> ```
>  *	int rpma_mr_get_descriptor(struct rpma_mr_local *mr,
>  *		void *desc);
> ```

in one line
___
*[src/include/librpma.h, line 397 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG28M8BaFmxZzAXOwE:-MHG28M8BaFmxZzAXOwF:b23x4c6) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L397)):*
> ```objc
> 
> /** 3
>  * rpma_mr_get_descriptor_size - get a descriptor size of memory region
> ```

`get size of a memory region descriptor`
___
*[src/include/librpma.h, line 404 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2qvk91Rx8n_fI4uv:-MHG2qvk91Rx8n_fI4uw:b5qwciw) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L404)):*
> ```
>  *	int rpma_mr_get_descriptor_size(struct rpma_mr_local *mr,
>  *		void *desc, size_t desc_size);
> ```

```
 *	int rpma_mr_get_descriptor_size(size_t *desc_size);
```
___
*[src/include/librpma.h, line 412 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2vvSBzl3FNLK0ixT:-MHG2vvSBzl3FNLK0ixU:b-h84nu8) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L412)):*
> ```
> int rpma_mr_get_descriptor_size(struct rpma_mr_local *mr,
> 		void *desc, size_t *desc_size);
> ```

```
int rpma_mr_get_descriptor_size(size_t *desc_size);
```


<!-- Sent from Reviewable.io -->

2020-09-15 09:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG3CTV6UtvuAHq8PHH:-MHG3CTW7biqWZo7BIRn:biv8fdb) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L407)):*
> ```
>  * rpma_mr_get_descriptor_size() can fail with the following error:
>  *
>  * - RPMA_E_INVAL - mr or desc is NULL
> ```

```
 * rpma_mr_get_descriptor_size() cannot fail
```


<!-- Sent from Reviewable.io -->

2020-09-15 09:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 361 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG3hhq3E7Kv8a2FhIx:-MHG3hhq3E7Kv8a2FhIy:bgyegyh) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L361)):*
> ```
> RPMA_LOG_ERROR(
> 			"incompatible size : %i != %i",
> 			desc_size, full_size);
> ```

```
RPMA_LOG_ERROR(
			"incorrect size of the descriptor: %i (should be: %i)",
			desc_size, full_size);

```


<!-- Sent from Reviewable.io -->

2020-09-15 09:32 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 11 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 356 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG5uG155PIpMUN1wtX:-MHG5uG155PIpMUN1wtY:b-nps00c) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L356)):*
> ```
>  = sizeof(raddr) + sizeof(size) + sizeof(rkey);
> ```

```
 = 2 * sizeof(uint64_t) + sizeof(uint32_t) + sizeof(uint8_t);
```


<!-- Sent from Reviewable.io -->

2020-09-15 09:47 UTC, grom72 reviewed
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tests/integration/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG8xxI9knNfdTEEW6q:-MHG8xxJEOv1AFhkugD4:bqdsuis) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/tests/integration/CMakeLists.txt#L7)):*
> ```CMake
> 
> add_subdirectory(example-01-connection)
> #add_subdirectory(example-02-read-to-volatile)
> ```

I suggest marking all these temporary changes "#" additionally with XXX to remember that there is some work to be done here


<!-- Sent from Reviewable.io -->

2020-09-15 10:17 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 13 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 358 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHGG5Vy9J2Pq8WFXsuV:-MHGG5Vy9J2Pq8WFXsuW:b-hcp4mp) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L358)):*
> ```
> if (desc_size != full_size) {
> ```

if (desc_size < full_size) {
___
*[src/mr.c, line 361 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG3hhq3E7Kv8a2FhIx:-MHGG0mU1GhZRz5INey6:b-wbgsyf) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L361)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_ERROR(
> 			"incompatible size : %i != %i",
> 			desc_size, full_size);
> ```

```
RPMA_LOG_ERROR(
			"incorrect size of the descriptor: %i (should be: %i)",
			desc_size, full_size);

```
</blockquote></details>

`"incorrect size of the descriptor: %i bytes (should be at least %i bytes)",`


<!-- Sent from Reviewable.io -->

2020-09-15 10:21 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG3CTV6UtvuAHq8PHH:-MHGHApq73GGmYCGGWOl:bwxj78o) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L407)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * rpma_mr_get_descriptor_size() can fail with the following error:
>  *
>  * - RPMA_E_INVAL - mr or desc is NULL
> ```

```
 * rpma_mr_get_descriptor_size() cannot fail
```
</blockquote></details>

Oh no, it can :-)


<!-- Sent from Reviewable.io -->

2020-09-15 10:22 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 13 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHGHIvI9kfdUcS-1UjA:-MHGHIvI9kfdUcS-1UjB:bbfhf5v) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L409)):*
> ```
>  mr or desc is NULL
> ```

`desc_size is NULL`


<!-- Sent from Reviewable.io -->

2020-09-15 14:21 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 3 of 9 files reviewed, 13 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/mr.c, line 356 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG5uG155PIpMUN1wtX:-MHG7yiw8CNs43Sh85Tn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L356)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  = sizeof(raddr) + sizeof(size) + sizeof(rkey);
> ```

```
 = 2 * sizeof(uint64_t) + sizeof(uint32_t) + sizeof(uint8_t);
```
</blockquote></details>

Done.
___
*[src/mr.c, line 358 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHGG5Vy9J2Pq8WFXsuV:-MHGMiS1AnA6wMBTLNqc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L358)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if (desc_size != full_size) {
> ```

if (desc_size < full_size) {
</blockquote></details>

Done.
___
*[src/mr.c, line 361 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG3hhq3E7Kv8a2FhIx:-MHGMQDc3u1JENJpKfMi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L361)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`"incorrect size of the descriptor: %i bytes (should be at least %i bytes)",`
</blockquote></details>

Done.
___
*[src/mr.c, line 403 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG21mB9vLoBy4QMTMW:-MHG8I-02bnR4iCHTsFd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L403)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> get a descriptor size of memory region
> ```

`get size of a memory region descriptor`
</blockquote></details>

Done.
___
*[src/mr.c, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2gZV03Uezjsk2Vz7:-MHGDVTlBPzVZSdfv_aB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L407)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> int
> rpma_mr_get_descriptor_size(struct rpma_mr_local *mr,
> 		void *desc, size_t *desc_size)
> ```

```
int
rpma_mr_get_descriptor_size(size_t *desc_size)
```
</blockquote></details>

Done.
___
*[src/mr.c, line 410 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2a4kBVAE0TpiUyNM:-MHGDWds88s3xLWEvAOI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L410)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if (mr == NULL || desc == NULL)
> 		return RPMA_E_INVAL;
> ```

Unnecessary, `mr` and `desc` are not used
</blockquote></details>

Done.
___
*[src/mr.c, line 412 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2J828EaQisrlHlOd:-MHG97_Q4RyShTgN6kgr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L412)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`... +  + sizeof(uint8_t);`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 353 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHFvteK5li84-yBVDMG:-MHG9EQ8501u4zZQ4svW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L353)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  *	int rpma_mr_get_descriptor(struct rpma_mr_local *mr,
>  *		void *desc);
> ```

in one line
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 397 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG28M8BaFmxZzAXOwE:-MHG9JFiDpTjl1uTYUY5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L397)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`get size of a memory region descriptor`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 404 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2qvk91Rx8n_fI4uv:-MHGMlt09yvq_mr-bHPT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L404)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  *	int rpma_mr_get_descriptor_size(struct rpma_mr_local *mr,
>  *		void *desc, size_t desc_size);
> ```

```
 *	int rpma_mr_get_descriptor_size(size_t *desc_size);
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG3CTV6UtvuAHq8PHH:-MHGDiw_-vkkZucgLVnR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L407)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Oh no, it can :-)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHGHIvI9kfdUcS-1UjA:-MHGMe8NAPQ5wIwrU_Yk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L409)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  mr or desc is NULL
> ```

`desc_size is NULL`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 412 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2vvSBzl3FNLK0ixT:-MHGDk7fBABMyRUJ1Gkr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L412)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> int rpma_mr_get_descriptor_size(struct rpma_mr_local *mr,
> 		void *desc, size_t *desc_size);
> ```

```
int rpma_mr_get_descriptor_size(size_t *desc_size);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-16 06:12 UTC, ldorau reviewed
> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/mr.c, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2gZV03Uezjsk2Vz7:-MHKUGwS1XYn6vZHZRM-:bjdv3zn) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L407)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72 rightly pointed out that the `struct rpma_mr_local *mr` structure will be needed as an argument in the future when we use protobuffer-c, so please revert this change (sorry for misleading you).
___
*[src/mr.c, line 410 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2a4kBVAE0TpiUyNM:-MHKV123CC178U1XVLm_:b-7zbg8s) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L410)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`mr` will be needed
___
*[src/include/librpma.h, line 404 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2qvk91Rx8n_fI4uv:-MHKVDf-D1iNUG6Iq7iw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L404)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[src/include/librpma.h, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHGHIvI9kfdUcS-1UjA:-MHKVH0N-qNRj6wewY7e:b-w6cba0) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L409)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

mr or desc_size
___
*[src/include/librpma.h, line 412 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2vvSBzl3FNLK0ixT:-MHKVMIJ6r6UUAgL80tc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/include/librpma.h#L412)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[tests/unit/mr/mr-common.c, line 141 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKVgxR-W3YIrpys1kK:-MHKVgxR-W3YIrpys1kL:bot3zwu) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-common.c#L141)):*
> ```
> /* get size */
> ```

`/* get size of the descriptor */`
___
*[tests/unit/mr/mr-descriptor.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKW4f-DViwflDHTBRv:-MHKW4f-DViwflDHTBRw:bfuncuq) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L72)):*
> ```C
> remote_from_descriptor__desc_NULL(void **unused)
> {
> 	/* run test */
> ```

Please add here (before `/* run test */`)

```
        /* get size of the descriptor */
	size_t desc_size;
	int ret = rpma_mr_get_descriptor_size(&desc_size);

	/* verify the results */
	assert_int_equal(ret, MOCK_OK);
```

and use `desc_size` instead of `MR_DESC_SIZE`.
___
*[tests/unit/mr/mr-descriptor.c, line 89 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWldbAdjQEEU37PWD:-MHKWldbAdjQEEU37PWE:bnuj90y) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L89)):*
> ```
> MR_DESC_SIZE
> ```

.
___
*[tests/unit/mr/mr-descriptor.c, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWjdsDWD_iY549994:-MHKWjdsDWD_iY549995:bjjup7c) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L103)):*
> ```
>  MR_DESC_SIZE
> ```

.
___
*[tests/unit/mr/mr-descriptor.c, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWgghCDsGVETAR4LZ:-MHKWgghCDsGVETAR4L_:bnuj90y) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L136)):*
> ```
> MR_DESC_SIZE
> ```

.
___
*[tests/unit/mr/mr-descriptor.c, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWeNI01t-MeZcgd16:-MHKWeNI01t-MeZcgd17:bnuj90y) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L149)):*
> ```
> MR_DESC_SIZE
> ```

.
___
*[tests/unit/mr/mr-descriptor.c, line 158 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKX0l6B7YWkCWbLkzW:-MHKX0l6B7YWkCWbLkzX:b-me3noq) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L158)):*
> ```
> MR_DESC_SIZE,
> ```

.


<!-- Sent from Reviewable.io -->

2020-09-16 06:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/mr/mr-descriptor.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKW4f-DViwflDHTBRv:-MHKaHa64SBpJN-D1n6q:b-mup9rx) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L72)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add here (before `/* run test */`)

```
        /* get size of the descriptor */
	size_t desc_size;
	int ret = rpma_mr_get_descriptor_size(&desc_size);

	/* verify the results */
	assert_int_equal(ret, MOCK_OK);
```

and use `desc_size` instead of `MR_DESC_SIZE`.
</blockquote></details>

Exceuse me, it is rather not a good idea, don't do that ;-)
Instead of that, please move the tests:

```
	/* rpma_mr_get_descriptor_size() unit test */
	cmocka_unit_test(get_descriptor_size__desc_size_NULL),
	cmocka_unit_test(get_descriptor_size__success),
```

to the beginning of all tests. The `get_descriptor_size__success` test verifies if `rpma_mr_get_descriptor_size()` returns the correct size `MR_DESC_SIZE`, so we can use it in all other places.
___
*[tests/unit/mr/mr-descriptor.c, line 406 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKbNGf9h8BHG9uEitM:-MHKbNGg4EgzZxpElWLJ:bnq9bl4) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L406)):*
> ```
> /* rpma_mr_get_descriptor_size() unit test */
> 	cmocka_unit_test(get_descriptor_size__desc_size_NULL),
> 	cmocka_unit_test(get_descriptor_size__success),
> ```

Please move it to the beginning of all tests (they should be the first ones).


<!-- Sent from Reviewable.io -->

2020-09-16 12:34 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 3 of 21 files reviewed, 8 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[src/mr.c, line 407 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2gZV03Uezjsk2Vz7:-MHLoc_gBnbLX19G9mNK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L407)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 rightly pointed out that the `struct rpma_mr_local *mr` structure will be needed as an argument in the future when we use protobuffer-c, so please revert this change (sorry for misleading you).
</blockquote></details>

Done.
___
*[src/mr.c, line 410 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG2a4kBVAE0TpiUyNM:-MHLoeba15xuvjVupKZy:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/src/mr.c#L410)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`mr` will be needed
</blockquote></details>

.
___
*[tests/integration/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG8xxI9knNfdTEEW6q:-MHLoztt9y0xlnicNm7C:b-8xc72a) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/tests/integration/CMakeLists.txt#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I suggest marking all these temporary changes "#" additionally with XXX to remember that there is some work to be done here
</blockquote></details>

Most of the changes are now ready.
___
*[tests/unit/mr/mr-common.c, line 141 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKVgxR-W3YIrpys1kK:-MHLpA2VD62VEgXvxY3t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-common.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* get size */
> ```

`/* get size of the descriptor */`
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-descriptor.c, line 89 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWldbAdjQEEU37PWD:-MHLppxQ8w2wRVB2izG2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MR_DESC_SIZE
> ```

.
</blockquote></details>

.
___
*[tests/unit/mr/mr-descriptor.c, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWjdsDWD_iY549994:-MHLpr0j2nhuSbdHvIlG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L103)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  MR_DESC_SIZE
> ```

.
</blockquote></details>

.
___
*[tests/unit/mr/mr-descriptor.c, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWgghCDsGVETAR4LZ:-MHLprk18idlAlZFTyCv:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MR_DESC_SIZE
> ```

.
</blockquote></details>

.
___
*[tests/unit/mr/mr-descriptor.c, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKWeNI01t-MeZcgd16:-MHLpsyF8CTXRWwMNIgr:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L149)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MR_DESC_SIZE
> ```

.
</blockquote></details>

.
___
*[tests/unit/mr/mr-descriptor.c, line 158 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKX0l6B7YWkCWbLkzW:-MHLptjpBLq1f5fhBJ79:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MR_DESC_SIZE,
> ```

.
</blockquote></details>

.
___
*[tests/unit/mr/mr-descriptor.c, line 406 at r2](https://reviewable.io/reviews/pmem/rpma/404#-MHKbNGf9h8BHG9uEitM:-MHLpvlv8ToBpt5UE4P9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8a98a7c7e326f4bbf445b7f1b195675eda67a27/tests/unit/mr/mr-descriptor.c#L406)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* rpma_mr_get_descriptor_size() unit test */
> 	cmocka_unit_test(get_descriptor_size__desc_size_NULL),
> 	cmocka_unit_test(get_descriptor_size__success),
> ```

Please move it to the beginning of all tests (they should be the first ones).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-16 13:29 UTC, ldorau reviewed
> Reviewed 8 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 9 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2020-09-16 20:09 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 9 of 21 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/404#-MHNXH8G1tehDMVqtjw1:-MHNXH8H6WnLsD6qUVHQ:buiwtai) (no related file):*
You can now rebase.

---


<!-- Sent from Reviewable.io -->

2020-09-16 21:29 UTC, janekmi reviewed
> Reviewed 2 of 6 files at r1, 1 of 7 files at r2, 18 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 22 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/03-read-to-persistent/client.c, line 160 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjZck7XS_WElV4jmI:-MHNjZck7XS_WElV4jmJ:b-en47u4) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L160)):*
> ```C
> 
> 	/* calculate data for the server read */
> 	struct common_data data;
> ```

```c
struct common_data *data;
size_t desc_size;
```
___
*[examples/03-read-to-persistent/client.c, line 181 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjd_22oVdcv8P_2av:-MHNjd_22oVdcv8P_2aw:b-mi53gg) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L181)):*
> ```C
> 
> 	/* get the memory region's descriptor */
> 	ret = rpma_mr_get_descriptor(mr, &data.mr_desc);
> ```

At this point, you do not have `data` allocated. First, we have to get the descriptor size.
___
*[examples/03-read-to-persistent/client.c, line 185 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNfVyy8yLV-I771aQb:-MHNfVyy8yLV-I771aQc:b-fzu3vt) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L185)):*
> ```C
> 		goto err_peer_delete;
> 
> 	/* get size */
> ```

... decriptor ...
___
*[examples/03-read-to-persistent/client.c, line 186 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjt035NKWeWBnLCy6:-MHNjt035NKWeWBnLCy7:bgpqz4v) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L186)):*
> ```C
> 
> 	/* get size */
> 	ret = rpma_mr_get_descriptor_size(mr, &data.desc_size);
> ```

~~data.~~
___
*[examples/03-read-to-persistent/client.c, line 189 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjwqV1DvrsNQiiTI5:-MHNjwqW3oWFL73-ZwbU:bfctuq1) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L189)):*
> ```C
> 	if (ret)
> 		goto err_peer_delete;
> ```

```c
data = malloc(sizeof(struct common_data) + desc_size);
data->pcfg_desc_size = 0;
data->mr_desc_size = desc_size;
data.data_offset = /* ... */;

ret = rpma_mr_get_descriptor(mr, data.descs);
/* ... */
```
___
*[examples/03-read-to-persistent/server.c, line 161 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNmXlrEzTlxxma983t:-MHNmXlrEzTlxxma983u:bcuuzz4) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/server.c#L161)):*
> ```C
> 	struct common_data *src_data = pdata.ptr;
> 
> 	src_data->mr_desc = malloc(src_data->desc_size);
> ```

Nope. Please see example 02.
___
*[examples/04-write-to-persistent/client.c, line 218 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnSQ7254I7ZR21mU-:-MHNnSQ7254I7ZR21mU0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/04-write-to-persistent/client.c#L218)):*
> ```C
> 	dst_offset = dst_data->data_offset;
> 
> 	dst_data->mr_desc = malloc(dst_data->desc_size);
> ```

.
___
*[examples/04-write-to-persistent/server.c, line 155 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnkOP6V5tJfUzWNXM:-MHNnkOP6V5tJfUzWNXN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/04-write-to-persistent/server.c#L155)):*
> ```C
> 
> 	/* get the memory region's descriptor */
> 	ret = rpma_mr_get_descriptor(mr, &data.mr_desc);
> ```

.
___
*[examples/05-flush-to-persistent/client.c, line 221 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnlxr2n7nV-ClYXS9:-MHNnlxr2n7nV-ClYXSA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/05-flush-to-persistent/client.c#L221)):*
> ```C
> 	dst_offset = dst_data->data_offset;
> 
> 	dst_data->mr_desc = malloc(dst_data->desc_size);
> ```

.
___
*[examples/05-flush-to-persistent/server.c, line 183 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnntvDntGoYIDDmy-:-MHNnntvDntGoYIDDmy0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/05-flush-to-persistent/server.c#L183)):*
> ```C
> 
> 	/* get the memory region's descriptor */
> 	ret = rpma_mr_get_descriptor(mr, &data.mr_desc);
> ```

.
___
*[examples/06-multiple-connections/client.c, line 113 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnyx9C-3kBRcZ_QA2:-MHNnyx9C-3kBRcZ_QA3:b-gnspri) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/06-multiple-connections/client.c#L113)):*
> ```C
> 
> 	/* receive the memory region's descriptor */
> 	ret = rpma_mr_get_descriptor(mr, &desc);
> ```

SIGSEGV?
___
*[examples/06-multiple-connections/server.c, line 271 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNo8-JCtKagm-cCWNv:-MHNo8-JCtKagm-cCWNw:bv3kuds) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/06-multiple-connections/server.c#L271)):*
> ```C
> 	//	return -1;
> 	// }
> 	desc = pdata.ptr;
> ```

void *desc = pdata.ptr;
___
*[examples/07-atomic-write/client.c, line 101 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNoVIu2w1xImGNAwXs:-MHNoVIu2w1xImGNAwXt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/07-atomic-write/client.c#L101)):*
> ```C
> 	used_offset = dst_data->data_offset;
> 
> 	dst_data->mr_desc = malloc(dst_data->desc_size);
> ```

.
___
*[examples/07-atomic-write/server.c, line 169 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNoaX7-3nh_9YaFQmi:-MHNoaX7-3nh_9YaFQmj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/07-atomic-write/server.c#L169)):*
> ```C
> 
> 	/* get the memory region's descriptor */
> 	if ((ret = rpma_mr_get_descriptor(mr, &data.mr_desc)))
> ```

.
___
*[examples/07-atomic-write/server.c, line 172 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNoXoh-rQ__Yw2OPoY:-MHNoXoh-rQ__Yw2OPoZ:b-k2njf0) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/07-atomic-write/server.c#L172)):*
> ```C
> 		goto err_mr_dereg;
> 
> 	/* get size */
> ```

... descriptor ...
___
*[examples/common/common-conn.h, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNigVuCLhOcE1bk2F2:-MHNigVuCLhOcE1bk2F3:b-dkilr0) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/common/common-conn.h#L25)):*
> ```objc
> 	void *mr_desc;
> 	size_t desc_size;
> 	size_t data_offset;
> ```

In my opinion, you do the following:

```c
struct common_data {
    size_t pcfg_desc_size;
    size_t mr_desc_size;
    size_t data_offset;
    char descs[];
}
```

Where you will have to store in some cases both pcfg_desc and mr_desc.
___
*[src/mr.c, line 357 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNbVIk0HDMn6TKtfor:-MHNYG1WDTPJqy8W_Hku:bgpssy1) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/src/mr.c#L357)):*
> ```C
> 
> 	size_t full_size = 2 * sizeof(uint64_t) + sizeof(uint32_t)
> 			+ sizeof(uint8_t);
> ```

```c
#define RPMA_MR_DESC_SIZE (/* ... */)
```
___
*[src/mr.c, line 412 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNbf0d6IixUIVT-yCy:-MHNbf0d6IixUIVT-yCz:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/src/mr.c#L412)):*
> ```C
> 		return RPMA_E_INVAL;
> 
> 	*desc_size = 2 * sizeof(uint64_t) + sizeof(uint32_t) + sizeof(uint8_t);
> ```

.
___
*[tests/unit/mr/mr-descriptor.c, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNd5m01nq8mXkYDupR:-MHNd5m01nq8mXkYDupS:bdlz7cb) ([raw file](https://github.com/pme [...]

2020-09-17 07:51 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 3 of 21 files reviewed, 22 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/404#-MHNXH8G1tehDMVqtjw1:-MHP_L8U8zkj7INHGvo2:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can now rebase.
</blockquote></details>

Done.

---
___
*[src/mr.c, line 357 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNbVIk0HDMn6TKtfor:-MHPZvWJ3IzoU-QlQ9_-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/src/mr.c#L357)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
#define RPMA_MR_DESC_SIZE (/* ... */)
```
</blockquote></details>

Done.
___
*[src/mr.c, line 412 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNbf0d6IixUIVT-yCy:-MHP_5KT88dGlQYO39xZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/src/mr.c#L412)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-descriptor.c, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNd5m01nq8mXkYDupR:-MHP_JM9ERmhs7B1zamF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/tests/unit/mr/mr-descriptor.c#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

mr_get_descriptor_size()?
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-descriptor.c, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNd2LB8MQTGxKanyuV:-MHP_K8-1aAaFdkt-YLO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/tests/unit/mr/mr-descriptor.c#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it should stay where it is. ;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-17 07:57 UTC, ldorau reviewed
> Reviewed 5 of 19 files at r4, 13 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 22 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 09:14 UTC, grom72 reviewed
> Reviewed 2 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 22 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 12:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 7 of 23 files reviewed, 22 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 160 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjZck7XS_WElV4jmI:-MHR-k5AE8UCe1jeoGr_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L160)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
struct common_data *data;
size_t desc_size;
```
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 181 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjd_22oVdcv8P_2av:-MHR-kz5B_pid9s1_gyJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L181)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

At this point, you do not have `data` allocated. First, we have to get the descriptor size.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 185 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNfVyy8yLV-I771aQb:-MHR-noCD4tqFOaUnVbb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L185)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... decriptor ...
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 186 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjt035NKWeWBnLCy6:-MHR-oZ331Yua0K8WbfB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L186)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~data.~~
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 189 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNjwqV1DvrsNQiiTI5:-MHR-pRd9lV4SA2lxxDZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/client.c#L189)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
data = malloc(sizeof(struct common_data) + desc_size);
data->pcfg_desc_size = 0;
data->mr_desc_size = desc_size;
data.data_offset = /* ... */;

ret = rpma_mr_get_descriptor(mr, data.descs);
/* ... */
```
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 161 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNmXlrEzTlxxma983t:-MHR-q971nwLsto-jOTZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/03-read-to-persistent/server.c#L161)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope. Please see example 02.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/client.c, line 218 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnSQ7254I7ZR21mU-:-MHR-rGc-LTdmWCL23ol:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/04-write-to-persistent/client.c#L218)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/server.c, line 155 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnkOP6V5tJfUzWNXM:-MHR-rwx2e37BUM-2I1P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/04-write-to-persistent/server.c#L155)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/client.c, line 221 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnlxr2n7nV-ClYXS9:-MHR-sgu2kis-gpix0B_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/05-flush-to-persistent/client.c#L221)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 183 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnntvDntGoYIDDmy-:-MHR-tZFCSgfjulOA3DM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/05-flush-to-persistent/server.c#L183)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/client.c, line 113 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNnyx9C-3kBRcZ_QA2:-MHR-uILATmht66OG48G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/06-multiple-connections/client.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

SIGSEGV?
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 271 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNo8-JCtKagm-cCWNv:-MHR-vF25cbsP7g_kBA8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/06-multiple-connections/server.c#L271)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

void *desc = pdata.ptr;
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 101 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNoVIu2w1xImGNAwXs:-MHR-vxO7wVsNb1rSy5N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/07-atomic-write/client.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 169 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNoaX7-3nh_9YaFQmi:-MHR-wZpBOaovxAhF6Kb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/07-atomic-write/server.c#L169)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 172 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNoXoh-rQ__Yw2OPoY:-MHR-xEOCIhTgdrHpqmP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/07-atomic-write/server.c#L172)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... descriptor ...
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNigVuCLhOcE1bk2F2:-MHR-xxZ9n4yoYXwNHyk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/common/common-conn.h#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In my opinion, you do the following:

```c
struct common_data {
    size_t pcfg_desc_size;
    size_t mr_desc_size;
    size_t data_offset;
    char descs[];
}
```

Where you will have to store in some cases both pcfg_desc and mr_desc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-17 12:53 UTC, grom72 reviewed
> Reviewed 1 of 7 files at r2, 1 of 20 files at r3, 4 of 19 files at r4, 4 of 15 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 11 of 23 files reviewed, 22 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/common/common-conn.h, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/404#-MHNigVuCLhOcE1bk2F2:-MHR68DF0Qrl6F2xY6kL:b-3emi1s) ([raw file](https://github.com/pmem/rpma/blob/774e99d56afce82f553d1c7e86a3c84664359818/examples/common/common-conn.h#L25)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

if not too late I suggest putting pcfg_desc_size as first in the descriptors area as in this case we are able to add several mr_desc - but we could leave this for the next sprint and/or for the time when protobuf-c will be introduced


<!-- Sent from Reviewable.io -->

2020-09-17 12:54 UTC, janekmi requested changes
> Reviewed 4 of 19 files at r4, 1 of 14 files at r6, 14 of 15 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 25 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/02-read-to-volatile/client.c, line 98 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4KVa02trbM5rorv9:-MHR4KVa02trbM5rorvA:blj116r) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/client.c#L98)):*
> ```C
> 	 */
> 	struct common_data *dst_data = pdata.ptr;
> 	if (dst_data->mr_desc_size > 0) {
> ```

This if is not needed here. We have no other way to work if this size is <= 0. Just use it.
___
*[examples/02-read-to-volatile/server.c, line 91 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4kQG1waRoKUNlQj1:-MHR4kQG1waRoKUNlQj2:buf4ow3) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/server.c#L91)):*
> ```C
> 	/* calculate data for the client write */
> 	size_t data_size = sizeof(struct common_data) + mr_desc_size;
> 	struct common_data *data = malloc(data_size);
> ```

malloc is not needed here.
___
*[examples/02-read-to-volatile/server.c, line 106 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4dXf4_YzuFqKL_-q:-MHR4dXf4_YzuFqKL_-r:b-kztfzw) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/server.c#L106)):*
> ```C
> 	struct rpma_conn_private_data pdata;
> 	pdata.ptr = data;
> 	pdata.len = data_size;
> ```

We can just use `sizeof(struct common_data)`.
___
*[examples/02-read-to-volatile/server.c, line 128 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4zNSDhi8eHruU-tZ:-MHR4zNSDhi8eHruU-t_:b2qd504) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/server.c#L128)):*
> ```C
> 
> err_free_data:
> 	free(data);
> ```

So we do not this also.
___
*[examples/03-read-to-persistent/client.c, line 177 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5GiH13mQNk-s0c2u:-MHR5GiI0GdS7fhnHuCp:b-fi7ppu) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/03-read-to-persistent/client.c#L177)):*
> ```C
> 
> 	/* get size of the memory region's descriptor */
> 	size_t mr_desc_size;
> ```

Since we do not need this value for malloc we can just do this directly to data.mr_desc_size.
___
*[examples/03-read-to-persistent/client.c, line 187 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5TYR-dv8XlOo1u3S:-MHR5TYR-dv8XlOo1u3T:b-6pjzz0) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/03-read-to-persistent/client.c#L187)):*
> ```C
> 	data.data_offset = data_offset + offsetof(struct hello_t, str);
> 	data.mr_desc_size = mr_desc_size;
> 	size_t mr_desc_offset = 0;
> ```

Move this next to `rpma_mr_get_descriptor()`.
___
*[examples/03-read-to-persistent/server.c, line 160 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5lrGD8koeaRePKgQ:-MHR5lrGD8koeaRePKgR:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/03-read-to-persistent/server.c#L160)):*
> ```C
> 
> 	struct common_data *src_data = pdata.ptr;
> 	if (src_data->mr_desc_size > 0) {
> ```

.
___
*[examples/04-write-to-persistent/client.c, line 217 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5pYZ04329zDwbCra:-MHR5pYZ04329zDwbCrb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/client.c#L217)):*
> ```C
> 	struct common_data *dst_data = pdata.ptr;
> 	dst_offset = dst_data->data_offset;
> 	if (dst_data->mr_desc_size > 0) {
> ```

.
___
*[examples/04-write-to-persistent/server.c, line 160 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5v-F2Oec7p0FJ4yW:-MHR5v-F2Oec7p0FJ4yX:b-48q3mb) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/server.c#L160)):*
> ```C
> 
> 	data.data_offset = data_offset;
> 	data.mr_desc_size = mr_desc_size;
> ```

You can read this value directly to data.mr_desc_size.
___
*[examples/04-write-to-persistent/server.c, line 161 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5yz976J6RgUgYf1p:-MHR5yz976J6RgUgYf1q:b-k6dntw) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/server.c#L161)):*
> ```C
> 	data.data_offset = data_offset;
> 	data.mr_desc_size = mr_desc_size;
> 	size_t mr_desc_offset = 0;
> ```

Move two lines below.
___
*[examples/05-flush-to-persistent/client.c, line 204 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR62khALue4YEBEpao:-MHR62khALue4YEBEpap:b-plc3b9) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/client.c#L204)):*
> ```C
> 	 */
> 	struct common_data *dst_data = pdata.ptr;
> 	if (dst_data->pcfg_desc_size > 0) {
> ```

Drop this if.
___
*[examples/05-flush-to-persistent/client.c, line 226 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6G7HEeU__yrsXFca:-MHR6G7HEeU__yrsXFcb:b-plc3b9) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/client.c#L226)):*
> ```C
> 	 */
> 	dst_offset = dst_data->data_offset;
> 	if (dst_data->mr_desc_size > 0) {
> ```

Drop this if.
___
*[examples/05-flush-to-persistent/server.c, line 174 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6QrqD47RdC1pDq0_:-MHR6QrqD47RdC1pDq0a:bqqjy2p) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/server.c#L174)):*
> ```C
> 
> 	/* get size of the memory region's descriptor */
> 	size_t mr_desc_size;
> ```

Directly to common_data?
___
*[examples/05-flush-to-persistent/server.c, line 180 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6T5M7I_qCZFMigF6:-MHR6T5M7I_qCZFMigF7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/server.c#L180)):*
> ```C
> 
> 	/* get size of the peer config descriptor */
> 	size_t pcfg_desc_size;
> ```

.
___
*[examples/06-multiple-connections/client.c, line 106 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6brK3RjMlMT48aBL:-MHR6brK3RjMlMT48aBM:bnfqvsq) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/client.c#L106)):*
> ```C
> 		goto err_mr_dereg;
> 
> 	/* calculate data for the client write */
> ```

This comment is now meaningless.
___
*[examples/06-multiple-connections/client.c, line 109 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6gpz8nUqyfG71s97:-MHR6gpz8nUqyfG71s98:b-t2xkvh) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/client.c#L109)):*
> ```C
> 	struct common_data data;
> 
> 	data.mr_desc_size = mr_desc_size;
> ```

Read directly.
___
*[examples/06-multiple-connections/client.c, line 110 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6jefEtC2FjrhwUM7:-MHR6jefEtC2FjrhwUM8:b-g1tull) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/client.c#L110)):*
> ```C
> 
> 	data.mr_desc_size = mr_desc_size;
> 	size_t mr_desc_offset = 0;
> ```

Two lines below.
___
*[examples/06-multiple-connections/server.c, line 274 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6qHVC_b9I0VH_RoY:-MHR6qHVC_b9I0VH_RoZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/server.c#L274)):*
> ```C
> 
> 	struct common_data *dst_data = pdata.ptr;
> 	if (dst_data->mr_desc_size > 0) {
> ```

.
___
*[examples/07-atomic-write/client.c, line 100 at r8](https://reviewable.io [...]

2020-09-17 12:54 UTC, grom72 reviewed
> Reviewed 6 of 15 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 25 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 13:13 UTC, ldorau reviewed
> Reviewed 1 of 14 files at r6, 1 of 15 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 25 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 13:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 26 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/common/common-conn.h, line 25 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHRFEja9ppUOw_XdJkA:-MHRFEja9ppUOw_XdJkB:boyytu2) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/common/common-conn.h#L25)):*
> ```
> 24
> ```

define + comment why 


<!-- Sent from Reviewable.io -->

2020-09-17 13:35 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 27 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/07-atomic-write/server.c, line 203 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHRGaFoCh2ayXZ6IIhl:-MHRGaFoCh2ayXZ6IIhm:b-4spryh) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/07-atomic-write/server.c#L203)):*
> ```C
> 	char *log_data_tail = (char *)log + log->used;
> 	while (ptr < log_data_tail) {
> 		if (*ptr)
> ```

I have SIGSEGV here:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555567b6 in main (argc=3, argv=0x7fffffffe348) at /home/ldorau/work/rpma/examples/07-atomic-write/server.c:203
203                     if (*ptr)
(gdb) bt
#0  0x00005555555567b6 in main (argc=3, argv=0x7fffffffe348) at /home/ldorau/work/rpma/examples/07-atomic-write/server.c:203
(gdb) 
```


<!-- Sent from Reviewable.io -->

2020-09-17 13:51 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 7 of 23 files reviewed, 27 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[examples/02-read-to-volatile/client.c, line 98 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4KVa02trbM5rorv9:-MHRFSv66KG48TPf8kFD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/client.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This if is not needed here. We have no other way to work if this size is <= 0. Just use it.
</blockquote></details>

Done.
___
*[examples/02-read-to-volatile/server.c, line 91 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4kQG1waRoKUNlQj1:-MHRFVq1A7UKRSa3t3DD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/server.c#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

malloc is not needed here.
</blockquote></details>

Done.
___
*[examples/02-read-to-volatile/server.c, line 106 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4dXf4_YzuFqKL_-q:-MHRFb0U56zup-kUlDGa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/server.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can just use `sizeof(struct common_data)`.
</blockquote></details>

Done.
___
*[examples/02-read-to-volatile/server.c, line 128 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR4zNSDhi8eHruU-tZ:-MHRFdSM3VeF5Wj_Sf6a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/02-read-to-volatile/server.c#L128)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So we do not this also.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 177 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5GiH13mQNk-s0c2u:-MHRH1Qn-CKzrkPNL8n6:by164rp) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/03-read-to-persistent/client.c#L177)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since we do not need this value for malloc we can just do this directly to data.mr_desc_size.
</blockquote></details>

incompatible data types
___
*[examples/03-read-to-persistent/client.c, line 187 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5TYR-dv8XlOo1u3S:-MHRHGKHC2Ja9xX1qpAR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/03-read-to-persistent/client.c#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Move this next to `rpma_mr_get_descriptor()`.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 160 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5lrGD8koeaRePKgQ:-MHRHHkv9DNNBbmDgKMG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/03-read-to-persistent/server.c#L160)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/client.c, line 217 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5pYZ04329zDwbCra:-MHRHIfv4dpNBQ44BsE4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/client.c#L217)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/server.c, line 160 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5v-F2Oec7p0FJ4yW:-MHRHWO-6z2n4ScKxjQT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/server.c#L160)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can read this value directly to data.mr_desc_size.
</blockquote></details>

.
___
*[examples/04-write-to-persistent/server.c, line 161 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5yz976J6RgUgYf1p:-MHRHXoP-Rxe2kdO-Tli:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/server.c#L161)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Move two lines below.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/client.c, line 204 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR62khALue4YEBEpao:-MHRHYu51DT0sNdk32gY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/client.c#L204)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Drop this if.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/client.c, line 226 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6G7HEeU__yrsXFca:-MHRHZj02AXCP5U2aS25:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/client.c#L226)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Drop this if.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 174 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6QrqD47RdC1pDq0_:-MHRH_w25l4O8jgsOSOC:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/server.c#L174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Directly to common_data?
</blockquote></details>

.
___
*[examples/05-flush-to-persistent/server.c, line 180 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6T5M7I_qCZFMigF6:-MHRHg_tCi6X2k_LYbGR:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/05-flush-to-persistent/server.c#L180)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[examples/06-multiple-connections/client.c, line 106 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6brK3RjMlMT48aBL:-MHRHsc_CCs8UCwgL2RS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/client.c#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment is now meaningless.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/client.c, line 109 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6gpz8nUqyfG71s97:-MHRHtTr3Uj1T-OxAWJX:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/client.c#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Read directly.
</blockquote></details>

.
___
*[examples/06-multiple-connections/client.c, line 110 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6jefEtC2FjrhwUM7:-MHRHwub4XA-Nyl1nxju:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/06-multiple-connections/client.c#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Two lines below.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 274 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR6qHVC_b9I0VH_RoY:-MHRHylZ7oUWuku5SfKW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870 [...]

2020-09-17 14:01 UTC, ldorau reviewed
> Reviewed 1 of 15 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 8 of 23 files reviewed, 26 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 14:47 UTC, janekmi requested changes
> Reviewed 1 of 16 files at r9, 15 of 15 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/04-write-to-persistent/client.c, line 217 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5pYZ04329zDwbCra:-MHRWX_E4pB_yS8MtY4f:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/client.c#L217)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.


<!-- Sent from Reviewable.io -->

2020-09-17 14:51 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/04-write-to-persistent/client.c, line 217 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHR5pYZ04329zDwbCra:-MHRY9CiChAEJVtOOkdH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/04-write-to-persistent/client.c#L217)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-17 14:55 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404#-:-MHRZ57h1yxqaMYv_crP:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 15:57 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/02-read-to-volatile/client.c, line 98 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRm1tP3Jbkez-KzvMA:-MHRm1tQ6vnMtob2E3TA:brl9o6j) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/client.c#L98)):*
> ```
> mr_desc_offset
> ```
obsolete 


<!-- Sent from Reviewable.io -->

2020-09-17 16:21 UTC, grom72 reviewed
> Reviewed 1 of 16 files at r9, 13 of 15 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 19 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/02-read-to-volatile/server.c, line 94 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRmddeA0Sc__LtDnLb:-MHRmddeA0Sc__LtDnLc:bu8tj3q) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/server.c#L94)):*
> ```
> size_t mr_desc_offset = 0;
> ```
we do not need this variable at all 
___
*[examples/03-read-to-persistent/client.c, line 189 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRnhueCBUWoDhWzW1F:-MHRnhueCBUWoDhWzW1G:bczrjyg) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/03-read-to-persistent/client.c#L189)):*
> ```
> size_t mr_desc_offset = 0;
> ```
.
___
*[examples/03-read-to-persistent/server.c, line 160 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRr7OJB3SJ4jMgOL0T:-MHRr7OJB3SJ4jMgOL0U:b-55zpou) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/03-read-to-persistent/server.c#L160)):*
> ```
> mr_desc_offset
> ```
.
___
*[examples/04-write-to-persistent/client.c, line 218 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRnlDp7VZ_e7zJcR02:-MHRnlDp7VZ_e7zJcR03:bczrjyg) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/04-write-to-persistent/client.c#L218)):*
> ```
> size_t mr_desc_offset = 0;
> ```
.
___
*[examples/04-write-to-persistent/server.c, line 163 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRoGVc2SeJgPDlt6lj:-MHRoGVc2SeJgPDlt6lk:bczrjyg) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/04-write-to-persistent/server.c#L163)):*
> ```
> size_t mr_desc_offset = 0;
> ```
.
___
*[examples/05-flush-to-persistent/client.c, line 204 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRoN9T8etIPdvYFcGG:-MHRoN9T8etIPdvYFcGH:b-tlkkmj) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/05-flush-to-persistent/client.c#L204)):*
> ```
>  pcfg_desc_offset
> ```
not needed
___
*[examples/05-flush-to-persistent/server.c, line 193 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRod84EXOYROLr47B3:-MHRod84EXOYROLr47B4:bbjhd0n) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/05-flush-to-persistent/server.c#L193)):*
> ```
> mr_desc_offset
> ```
obsolete variable
___
*[examples/05-flush-to-persistent/server.c, line 200 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRogS1Afjy4kAV8PB1:-MHRogS20mzITDLQDvrE:blaw46u) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/05-flush-to-persistent/server.c#L200)):*
> ```
> pcfg_desc_offset
> ```
obsolete variable
___
*[examples/06-multiple-connections/client.c, line 111 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrDHa9s6HYlacZOtZ:-MHRrDHa9s6HYlacZOt_:bczrjyg) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/06-multiple-connections/client.c#L111)):*
> ```
> size_t mr_desc_offset = 0;
> ```
.
___
*[examples/06-multiple-connections/server.c, line 274 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrLfU6V-O_ERDMfCP:-MHRrLfU6V-O_ERDMfCQ:b-55zpou) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/06-multiple-connections/server.c#L274)):*
> ```
> mr_desc_offset
> ```
.
___
*[examples/07-atomic-write/client.c, line 100 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrOOn2vm-uFgDJwIA:-MHRrOOn2vm-uFgDJwIB:b-55zpou) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/client.c#L100)):*
> ```
> mr_desc_offset
> ```
.
___
*[examples/07-atomic-write/server.c, line 176 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrVtY7bo4cimNV94R:-MHRrVtY7bo4cimNV94S:b-gi0eh1) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L176)):*
> ```
>  mr_desc_offset
> ```
obsolete
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 229 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrZpv5KXmoeJlaRTR:-MHRrZpv5KXmoeJlaRTS:bcch82d) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/09-flush-to-persistent-GPSPM/client.c#L229)):*
> ```
> mr_desc_offset
> ```
obsolete
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 193 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrecxAik98tGCgFGe:-MHRrecxAik98tGCgFGf:bcch82d) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/09-flush-to-persistent-GPSPM/server.c#L193)):*
> ```
> mr_desc_offset
> ```
obsolete
___
*[examples/common/common-conn.h, line 24 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRp4O-5B9SbzTd6Tzn:-MHRp4O-5B9SbzTd6Tzo:b-2xwz35) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/common/common-conn.h#L24)):*
> ```
> data_offset
> ```
documentation missing
___
*[examples/common/common-conn.h, line 28 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRoyLS8bkzdYhJoxaQ:-MHRoyLS8bkzdYhJoxaR:bsw95pc) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/common/common-conn.h#L28)):*
> ```
> DESCRIPTORS_LEN
> ```
MAX_DESCRIPTORS_SPACE_SIZE?
___
*[tests/integration/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG8xxI9knNfdTEEW6q:-MHRqWrQ7CfaIQGkx0d1:b-vh4cpc) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/tests/integration/CMakeLists.txt#L7)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Most of the changes are now ready.
</blockquote></details>

any comment could help


<!-- Sent from Reviewable.io -->

2020-09-17 18:15 UTC, grom72 reviewed
> Reviewed 1 of 15 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 19 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-17 20:21 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 24 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/07-atomic-write/client.c, line 99 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSgNtqC39Dyym9OCuD:-MHSgNtqC39Dyym9OCuE:bezzo4y) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/client.c#L99)):*
> ```
> data_offset
> ```
Not set on the serer side 
___
*[examples/07-atomic-write/server.c, line 131 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSb7wnAlKla_ftFxwm:-MHSb7wo97fTz7TCBowC:bshhvau) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L131)):*
> ```
> sizeof(char) * LOG_DATA_SIZE)
> ```
what is the purpose of this part? if struct log already contains data part:
struct log {
	char signature[LOG_SIGNATURE_SIZE];
	/* last written data (aligned to RPMA_ATOMIC_WRITE_ALIGNMENT) */
	uint64_t used;
	***char data[LOG_DATA_SIZE];***
};
___
*[examples/07-atomic-write/server.c, line 165 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSc3Dq3rv86AvIkScG:-MHSc3Dq3rv86AvIkScH:b-l02j96) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L165)):*
> ```
> size_t mr_desc_size;
> ```
obsolete - data.mr_desc_size can be used directly
___
*[examples/07-atomic-write/server.c, line 174 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHShRgA1gX7-75MB8Pv:-MHShRgA1gX7-75MB8Pw:bioxmcb) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L174)):*
> ```C
> 
> 	data.mr_desc_size = mr_desc_size;
> ```

@ldorau  your SIGSEGV seems to be initiated here:
data.data_offset is not set on the server-side but expected on the client side.
The client uses random value as initial offset and that cause memory fault 
___
*[examples/07-atomic-write/server.c, line 178 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSMPux4iDz-WUmiZFZ:-MHSMPux4iDz-WUmiZF_:b-55zpos) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L178)):*
> ```
> mr_desc_offset
> ```
0


<!-- Sent from Reviewable.io -->

2020-09-17 21:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 24 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-18 06:50 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 24 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/02-read-to-volatile/client.c, line 98 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRm1tP3Jbkez-KzvMA:-MHUyFQVAZ38szyx29o9:bwm8c5t) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/client.c#L98)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mr_desc_offset
> ```
obsolete 
</blockquote></details>

Otherwise you need a good comment here.


<!-- Sent from Reviewable.io -->

2020-09-18 07:18 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 7 of 23 files reviewed, 24 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/02-read-to-volatile/client.c, line 98 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRm1tP3Jbkez-KzvMA:-MHV1lkZ7aaHVyGy0Gnd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/client.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Otherwise you need a good comment here.
</blockquote></details>

Done.
___
*[examples/02-read-to-volatile/server.c, line 94 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRmddeA0Sc__LtDnLb:-MHUuX8k-jfZy3lxaIyg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/server.c#L94)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size_t mr_desc_offset = 0;
> ```
we do not need this variable at all 
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 189 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRnhueCBUWoDhWzW1F:-MHUudLX5Gy605QthCe2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/03-read-to-persistent/client.c#L189)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size_t mr_desc_offset = 0;
> ```
.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 160 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRr7OJB3SJ4jMgOL0T:-MHUulTE7YJobXQLsxuS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/03-read-to-persistent/server.c#L160)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mr_desc_offset
> ```
.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/client.c, line 218 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRnlDp7VZ_e7zJcR02:-MHV1mnm15nr04HiU5Wd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/04-write-to-persistent/client.c#L218)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size_t mr_desc_offset = 0;
> ```
.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/server.c, line 163 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRoGVc2SeJgPDlt6lj:-MHUuw2M25zM0cT1qF_B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/04-write-to-persistent/server.c#L163)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size_t mr_desc_offset = 0;
> ```
.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/client.c, line 204 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRoN9T8etIPdvYFcGG:-MHUv2DCAcoVKNrFDPS6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/05-flush-to-persistent/client.c#L204)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  pcfg_desc_offset
> ```
not needed
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 193 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRod84EXOYROLr47B3:-MHUwBcGB1EAfoUNiucz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/05-flush-to-persistent/server.c#L193)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mr_desc_offset
> ```
obsolete variable
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 200 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRogS1Afjy4kAV8PB1:-MHUwCbODwsDksUTaEI7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/05-flush-to-persistent/server.c#L200)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> pcfg_desc_offset
> ```
obsolete variable
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/client.c, line 111 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrDHa9s6HYlacZOtZ:-MHUwHOs8-RsZfF99JP8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/06-multiple-connections/client.c#L111)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size_t mr_desc_offset = 0;
> ```
.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 274 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrLfU6V-O_ERDMfCP:-MHUwQ9RBnANuecPV1Jy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/06-multiple-connections/server.c#L274)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mr_desc_offset
> ```
.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 99 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSgNtqC39Dyym9OCuD:-MHUwcUyANs1QOY3ohT5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/client.c#L99)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> data_offset
> ```
Not set on the serer side 
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 100 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRrOOn2vm-uFgDJwIA:-MHUwd9X4JRrIVnIBXKf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/client.c#L100)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mr_desc_offset
> ```
.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 203 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHRGaFoCh2ayXZ6IIhl:-MHV1y9YCIPmEkr5UYFr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/07-atomic-write/server.c#L203)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have SIGSEGV here:
```
Program received signal SIGSEGV, Segmentation fault.
0x00005555555567b6 in main (argc=3, argv=0x7fffffffe348) at /home/ldorau/work/rpma/examples/07-atomic-write/server.c:203
203                     if (*ptr)
(gdb) bt
#0  0x00005555555567b6 in main (argc=3, argv=0x7fffffffe348) at /home/ldorau/work/rpma/examples/07-atomic-write/server.c:203
(gdb) 
```
</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 131 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSb7wnAlKla_ftFxwm:-MHV402N9lHjfIl-9-VM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> sizeof(char) * LOG_DATA_SIZE)
> ```
what is the purpose of this part? if struct log already contains data part:
struct log {
	char signature[LOG_SIGNATURE_SIZE];
	/* last written data (aligned to RPMA_ATOMIC_WRITE_ALIGNMENT) */
	uint64_t used;
	***char data[LOG_DATA_SIZE];***
};

</blockquote></details>

Done.
___
*[examples/07-atomic-write/server.c, line 165 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHSc3Dq3rv86AvIkScG:-MHUx2iUEYvqHazCfYKX:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L165)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrot [...]

2020-09-18 12:10 UTC, grom72 reviewed
> Reviewed 1 of 16 files at r12, 14 of 15 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2020-09-18 12:11 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404#-:-MHW6zKNEqGvhwv9uMnz:bnfp4nl)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2020-09-18 20:01 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/integration/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG8xxI9knNfdTEEW6q:-MHXnPgtE2UQ-oFOWdDi:b-6b2dr4) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/tests/integration/CMakeLists.txt#L7)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why cannot it be fixed in this PR? IMHO it should be ...


<!-- Sent from Reviewable.io -->

2020-09-18 20:57 UTC, ldorau reviewed
> Reviewed 1 of 15 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/server.c, line 203 at r8](https://reviewable.io/reviews/pmem/rpma/404#-MHRGaFoCh2ayXZ6IIhl:-MHY-8xPCfWkqx6AEOoC:b-l4stmi) ([raw file](https://github.com/pmem/rpma/blob/dc870b2c141835b75234a947b63c089e9b12cc0b/examples/07-atomic-write/server.c#L203)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It works now.
___
*[examples/07-atomic-write/server.c, line 174 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHShRgA1gX7-75MB8Pv:-MHY-VpV4kE5Z6X_0Caw:b-l4stmi) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/07-atomic-write/server.c#L174)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It works now.


<!-- Sent from Reviewable.io -->

2020-09-18 20:59 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/02-read-to-volatile/client.c, line 98 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRm1tP3Jbkez-KzvMA:-MHY-mS51uCjah3gB-UM:b-1jcc4i) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/client.c#L98)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72 ?


<!-- Sent from Reviewable.io -->

2020-09-21 05:46 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/02-read-to-volatile/client.c, line 98 at r11](https://reviewable.io/reviews/pmem/rpma/404#-MHRm1tP3Jbkez-KzvMA:-MHjApefBtmZnBeOdhCb:b-azjp4g) ([raw file](https://github.com/pmem/rpma/blob/bad0e2cde4770a8fea8cd2c4fe80cc1fa52bfc37/examples/02-read-to-volatile/client.c#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 ?
</blockquote></details>

The comment concerned the mr_desc_offset variable


<!-- Sent from Reviewable.io -->

2020-09-21 10:35 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 7 of 24 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/integration/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG8xxI9knNfdTEEW6q:-MHkDtpl3yMk-krWGPLC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/tests/integration/CMakeLists.txt#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk Why cannot it be fixed in this PR?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-21 11:13 UTC, ldorau requested changes
> Reviewed 1 of 18 files at r14, 13 of 15 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 20 of 24 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/05-flush-to-persistent/server.c, line 196 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkKoxXEnnRjEVPP6pV:-MHkKoxY8UT2Zczkes-Y:b-l99efb) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/examples/05-flush-to-persistent/server.c#L196)):*
> ```C
> 		goto err_mr_dereg;
> 
> 	/* get the peer's configuration descriptor */
> ```

```
	/* 
	 * Get the peer's configuration descriptor.
	 * The pcfg_desc descriptor is saved in the `descriptors[]` array
	 * just after the  mr_desc descriptor.
	 */
```
___
*[examples/common/common-conn.h, line 21 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkLbU-3piw0qMIGLGF:-MHkLbU-3piw0qMIGLGG:b1vsrnk) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/examples/common/common-conn.h#L21)):*
> ```
> MAX_DESCRIPTORS_SPACE_SIZE
> ```

`DESCRIPTORS_MAX_SIZE`
___
*[examples/common/common-conn.h, line 21 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkLoI3CeUwfjn4-Tjk:-MHkLoI3CeUwfjn4-Tjl:b-wbntuw) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/examples/common/common-conn.h#L21)):*
> ```
> /* data limit on rdma_connect() */
> ```

```
/* limited by the maximum length of the private data for rdma_connect() in case of RDMA_PS_TCP (56 bytes) */
```


<!-- Sent from Reviewable.io -->

2020-09-21 11:18 UTC, ldorau requested changes
> Reviewed 1 of 16 files at r9, 2 of 18 files at r14, 1 of 15 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[tests/integration/common/mocks.h, line 33 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkMeAI-7ceKeJ7xlHy:-MHkMeAI-7ceKeJ7xlHz:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/tests/integration/common/mocks.h#L33)):*
> ```objc
> #define MOCK_OK			0
> 
> #define MAX_DESCRIPTORS_SPACE_SIZE 24	/* data limit on rdma_connect() */
> ```

.
___
*[tests/integration/common/mocks.h, line 40 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkMezr00h5_n8l3hqV:-MHkMezr00h5_n8l3hqW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/tests/integration/common/mocks.h#L40)):*
> ```objc
> 	uint8_t pcfg_desc_size;	/* size of pcfg_desc in descriptors[] */
> 	/* buffer containing mr_desc and pcfg_desc */
> 	char descriptors[MAX_DESCRIPTORS_SPACE_SIZE];
> ```

.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 150 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkNVBt4gGkEyWsIEhO:-MHkNVBuEwrurTG66iuh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L150)):*
> ```C
> 	/* configure mocks for rpma_conn_next_event() */
> 	struct common_data data;
> 	data.mr_desc_size = MAX_DESCRIPTORS_SPACE_SIZE;
> ```

.


<!-- Sent from Reviewable.io -->

2020-09-21 11:20 UTC, ldorau reviewed
> Reviewed 1 of 15 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-21 11:24 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/05-flush-to-persistent/server.c, line 196 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkKoxXEnnRjEVPP6pV:-MHkNHlh4LvjfauuLZ6k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/examples/05-flush-to-persistent/server.c#L196)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
	/* 
	 * Get the peer's configuration descriptor.
	 * The pcfg_desc descriptor is saved in the `descriptors[]` array
	 * just after the  mr_desc descriptor.
	 */
```
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 21 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkLbU-3piw0qMIGLGF:-MHkNbsbDmVMwm5SBZCD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/examples/common/common-conn.h#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MAX_DESCRIPTORS_SPACE_SIZE
> ```

`DESCRIPTORS_MAX_SIZE`
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 21 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkLoI3CeUwfjn4-Tjk:-MHkO61s6DUj57wI8aGv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/examples/common/common-conn.h#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* data limit on rdma_connect() */
> ```

```
/* limited by the maximum length of the private data for rdma_connect() in case of RDMA_PS_TCP (56 bytes) */
```

</blockquote></details>

Done.
___
*[tests/integration/common/mocks.h, line 33 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkMeAI-7ceKeJ7xlHy:-MHkO7EIEzc53AE5C9XJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/tests/integration/common/mocks.h#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/common/mocks.h, line 40 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkMezr00h5_n8l3hqV:-MHkO8-O-JI97DXd5olB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/tests/integration/common/mocks.h#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 150 at r15](https://reviewable.io/reviews/pmem/rpma/404#-MHkNVBt4gGkEyWsIEhO:-MHkO9-HBWUFzrLTxavT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8956ffe416c5408faea92b7514881772a4aa884b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L150)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-21 11:35 UTC, grom72 reviewed
> Reviewed 1 of 17 files at r16, 15 of 15 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 23 of 24 files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tests/integration/common/mocks.h, line 37 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkRYAZ25vrA0pw8DQf:-MHkRYAZ25vrA0pw8DQg:b-qvvay6) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/tests/integration/common/mocks.h#L37)):*
> ```
> 24
> ```
why not 56?


<!-- Sent from Reviewable.io -->

2020-09-21 11:35 UTC, grom72 reviewed
> Reviewed 1 of 17 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-21 11:56 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/integration/common/mocks.h, line 37 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkRYAZ25vrA0pw8DQf:-MHkVrYpDNqtPXwaQuGt:b-qzvlo4) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/tests/integration/common/mocks.h#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 24
> ```
why not 56?

</blockquote></details>

The maximum length of private data is 56 .
This means that the whole common_data structure can have 56.


<!-- Sent from Reviewable.io -->

2020-09-21 12:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/05-flush-to-persistent/server.c, line 199 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkanKs5jFakeEC127N:-MHkanKs5jFakeEC127O:b5rgl5j) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/examples/05-flush-to-persistent/server.c#L199)):*
> ```
>  the  mr_desc
> ```

`the mr_desc` (two spaces)
___
*[examples/common/common-conn.h, line 23 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkb8uH4Ddg_CovWybu:-MHkb8uH4Ddg_CovWybv:b-kpyk0q) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/examples/common/common-conn.h#L23)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> /*
>  * limited by the maximum length of the private data
>  * for rdma_connect() in case of RDMA_PS_TCP (56 bytes)
>  */
> ```
</details>


Multi-line comments should be full sentences:

```
/*
 * Limited by the maximum length of the private data
 * for rdma_connect() in case of RDMA_PS_TCP (56 bytes).
 */
```
___
*[tests/integration/common/mocks.h, line 34 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkbL-d5Mct8jcJN7A-:-MHkbL-d5Mct8jcJN7A0:bfapucx) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/tests/integration/common/mocks.h#L34)):*
> ```objc
> 
> /*
>  * limited by the maximum length of the private data
> ```

Limited ... .
___
*[tests/integration/common/mocks.h, line 37 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkRYAZ25vrA0pw8DQf:-MHkbltTDatszMyohy73:bo0pbb6) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/tests/integration/common/mocks.h#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

The maximum length of private data is 56 .
This means that the whole common_data structure can have 56.
</blockquote></details>

It is OK


<!-- Sent from Reviewable.io -->

2020-09-21 12:53 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: 8 of 24 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/05-flush-to-persistent/server.c, line 199 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkanKs5jFakeEC127N:-MHkhpoy5jsvxomWTdR8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/examples/05-flush-to-persistent/server.c#L199)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  the  mr_desc
> ```

`the mr_desc` (two spaces)
</blockquote></details>

Done.
___
*[examples/common/common-conn.h, line 23 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkb8uH4Ddg_CovWybu:-MHkhxuiCEPeXJm7Curi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/examples/common/common-conn.h#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /*
>  * limited by the maximum length of the private data
>  * for rdma_connect() in case of RDMA_PS_TCP (56 bytes)
>  */
> ```

Multi-line comments should be full sentences:

```
/*
 * Limited by the maximum length of the private data
 * for rdma_connect() in case of RDMA_PS_TCP (56 bytes).
 */
```
</blockquote></details>

Done.
___
*[tests/integration/common/mocks.h, line 34 at r17](https://reviewable.io/reviews/pmem/rpma/404#-MHkbL-d5Mct8jcJN7A-:-MHki40AB63JHhbDiihd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/481e3a6257e697b9240158e386af144cd320642a/tests/integration/common/mocks.h#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Limited ... .
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-21 12:56 UTC, ldorau approved these changes
> Reviewed 1 of 16 files at r18, 15 of 15 files at r19.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-21 13:53 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404#-:-MHkwEJm5kBPYx1bYNz3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-21 18:25 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/integration/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/404#-MHG8xxI9knNfdTEEW6q:-MHluCrDENQTmFGlWW5p:b-6k4u8q) ([raw file](https://github.com/pmem/rpma/blob/e7c42e31248b9d3a5afc6a0adc9e5992969565f8/tests/integration/CMakeLists.txt#L7)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK, it is fixed, thanks!


<!-- Sent from Reviewable.io -->

2020-09-21 18:26 UTC, ldorau approved these changes
> Reviewed 1 of 17 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-21 18:26 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/404#-:-MHlujxs913BhJXaeuhI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-21 18:29 UTC, merged