rpma: avoid silent shutdown in case of unknown comunication event
pmem/rpma pull request #415
Opened 2020-09-21 07:55 UTC by grom72

There is no message when connection could not be properly established on a client side  (server close it just after accepting)

2020-09-21 09:11 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/conn.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/415#-MHjv2Ue1OQeH2wWFNqS:-MHjv2Ue1OQeH2wWFNqT:b-9wnar6) ([raw file](https://github.com/pmem/rpma/blob/343e1506d7f622a8710543b4a45eca78efeb38fb/src/conn.c#L190)):*
> ```C
> 			// RPMA_LOG_WARNING("%s: %s",
> 			//	rpma_utils_conn_event_2str(*event),
> 			//	cm_erdma_event_str( cm_event));
> ```

Please use the following multi-line comment style:

```
/*
 * Full sentence
 * with full stop at the end.
 */
```


<!-- Sent from Reviewable.io -->

2020-09-22 05:39 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/conn.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/415#-MHjv2Ue1OQeH2wWFNqS:-MHoJi4S37ibcBpZrv3c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/343e1506d7f622a8710543b4a45eca78efeb38fb/src/conn.c#L190)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please use the following multi-line comment style:

```
/*
 * Full sentence
 * with full stop at the end.
 */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-22 05:57 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 05:59 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/utils/utils-conn_event_2str.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/415#-MHoODhl5l_ug92y6IEZ:-MHoODhl5l_ug92y6IE_:b-s3jla5) ([raw file](https://github.com/pmem/rpma/blob/62f88c70d50ba32442f8445b26a1595259dc34a3/tests/unit/utils/utils-conn_event_2str.c#L63)):*
> ```C
> {
> 	assert_string_equal(rpma_utils_conn_event_2str(RPMA_E_UNKNOWN),
> 	"Unsupported connection event");
> ```

wrong alignment, tabs missing


<!-- Sent from Reviewable.io -->

2020-09-22 06:12 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/utils/utils-conn_event_2str.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/415#-MHoODhl5l_ug92y6IEZ:-MHoRAs61oZwXf8M1w1r:b-x9ba83) ([raw file](https://github.com/pmem/rpma/blob/62f88c70d50ba32442f8445b26a1595259dc34a3/tests/unit/utils/utils-conn_event_2str.c#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong alignment, tabs missing
</blockquote></details>

Like this?


<!-- Sent from Reviewable.io -->

2020-09-22 07:06 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/unit/utils/utils-conn_event_2str.c, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/415#-MHoODhl5l_ug92y6IEZ:-MHocZVO3f6Nea3Lmokb:b-hay9re) ([raw file](https://github.com/pmem/rpma/blob/62f88c70d50ba32442f8445b26a1595259dc34a3/tests/unit/utils/utils-conn_event_2str.c#L63)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Like this?
</blockquote></details>

Yes, it is a continuation of the previous line.


<!-- Sent from Reviewable.io -->

2020-09-22 07:07 UTC, ldorau reviewed
@osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415#-:-MHocj-W1j3Tx9HC4t3o:bqeplii)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 08:23 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415#-:-MHou8os5CWr6CCb5wB7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 08:48 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 08:48 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/415#-:-MHp--Dw9Rz0ZvZvKvTo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-22 08:56 UTC, merged