doc: improve the documentation to rpma_conn... functions
pmem/rpma pull request #428
Opened 2020-09-23 07:52 UTC by osalyk

2020-09-24 11:47 UTC, ldorau commented
Please rebase

2020-09-24 11:53 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: all files reviewed, 20 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 509 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwWHi5JwOX6VolTto:-MHzwWHjD-m6578g7x0M:b-9unw59) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L509)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_cfg_delete() delete the connection configuration object.
> ```

deletes
___
*[src/include/librpma.h, line 535 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzweyt7wZ8fsmG-F_n:-MHzweyt7wZ8fsmG-F_o:b61f2w7) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L535)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Sets connection establishment timeout.
> ```

`rpma_conn_cfg_set_timeout() sets the ... `
___
*[src/include/librpma.h, line 560 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwq1n1Atb_G1ypdoP:-MHzwq1n1Atb_G1ypdoQ:b2rqz41) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L560)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Gets connection establishment timeout.
> ```

`rpma_conn_cfg_get_timeout() gets the ...`
___
*[src/include/librpma.h, line 586 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwvKu-dRR4n6we5tJ:-MHzwvKv3OmAn4joo-_V:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L586)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Sets CQ size for the connection.
> ```

.
___
*[src/include/librpma.h, line 611 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwxIp3Hns98HMNeeg:-MHzwxIp3Hns98HMNeeh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L611)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Gets CQ size for the connection.
> ```

.
___
*[src/include/librpma.h, line 637 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwyuY9-kcIfNO_xoZ:-MHzwyuY9-kcIfNO_xo_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L637)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Sets SQ size for the connection.
> ```

.
___
*[src/include/librpma.h, line 662 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwzxiBzWiHJvmldpZ:-MHzwzxj3SiyjB2-8DtJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L662)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Gets SQ size for the connection.
> ```

.
___
*[src/include/librpma.h, line 688 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx17QByvd60S_-9uo:-MHzx17QByvd60S_-9up:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L688)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Sets RQ size for the connection.
> ```

.
___
*[src/include/librpma.h, line 713 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx26c8X__ggv2Etf0:-MHzx26c8X__ggv2Etf1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L713)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Gets RQ size for the connection.
> ```

.
___
*[src/include/librpma.h, line 742 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx3-z-_oocQJIxZzj:-MHzx3-z-_oocQJIxZzk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L742)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Get an event file descriptor of the connection.
> ```

.
___
*[src/include/librpma.h, line 782 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx8KEBzKCywJjtwqF:-MHzx8KEBzKCywJjtwqG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L782)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Obtain the next event from the connection.
> ```

.
___
*[src/include/librpma.h, line 820 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxC5I6tzQs1ZnHToa:-MHzxC5I6tzQs1ZnHTob:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L820)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Return const string representation of RPMA_CONN_* enums.
> ```

.
___
*[src/include/librpma.h, line 849 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxMFG7D-gstILvdD3:-MHzxMFG7D-gstILvdD4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L849)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Obtain a pointer to the private data given by the other side
> ```

.
___
*[src/include/librpma.h, line 878 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxO6sBEF-LwUl9sPB:-MHzxO6sBEF-LwUl9sPC:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L878)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Apply remote peer cfg for the connection.
> ```

.
___
*[src/include/librpma.h, line 904 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxOzu7wJ9ju2y2WKk:-MHzxOzv0ao75wqY5fnu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L904)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the RPMA connection disconnection process.
> ```

.
___
*[src/include/librpma.h, line 929 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxQN1-nXA1UpAM8Yu:-MHzxQN1-nXA1UpAM8Yv:b-9unw59) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L929)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_delete() delete already closed connection.
> ```

deletes
___
*[src/include/librpma.h, line 960 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxRta7RxZZJBwUgpy:-MHzxRta7RxZZJBwUgpz:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L960)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Create a new outgoing connection request object using reliable,
> ```

.
___
*[src/include/librpma.h, line 991 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxStm1whEc0uqtVIC:-MHzxStm1whEc0uqtVID:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L991)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Delete the connection request both incoming and outgoing.
> ```

.
___
*[src/include/librpma.h, line 1024 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxVfT462SnG8PPTU7:-MHzxVfT462SnG8PPTU8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L1024)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Connect the connection requests both incoming and outgoing.
> ```

.
___
*[src/include/librpma.h, line 1062 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxYrk4K7tvil5T9cP:-MHzxYrk4K7tvil5T9cQ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L1062)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the receive operation. It prepares a buffer for a message
> ```

.


<!-- Sent from Reviewable.io -->

2020-09-24 13:21 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: 0 of 1 files reviewed, 20 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 509 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwWHi5JwOX6VolTto:-MI-DHm53eGUXhbcLVmn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L509)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

deletes
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 535 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzweyt7wZ8fsmG-F_n:-MI-DNeD53nSE3COerSm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L535)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_cfg_set_timeout() sets the ... `
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 560 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwq1n1Atb_G1ypdoP:-MI-DSllC8xl0FGjNzM_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L560)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_cfg_get_timeout() gets the ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 586 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwvKu-dRR4n6we5tJ:-MI-DXEK0gYtOKu7Xczf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L586)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 611 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwxIp3Hns98HMNeeg:-MI-DaxBBhcnulkdwkhp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L611)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 637 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwyuY9-kcIfNO_xoZ:-MI-DfIeEZvW_WTeYlQn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L637)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 662 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwzxiBzWiHJvmldpZ:-MI-DkFX8CHEjIqRl-KB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L662)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 688 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx17QByvd60S_-9uo:-MI-DnqjDKwv5peGXGBV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L688)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 713 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx26c8X__ggv2Etf0:-MI-Dr6Y5MY5BXSP4Hm8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L713)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 742 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx3-z-_oocQJIxZzj:-MI-Dub3CTFB_tC0-dJ9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L742)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 782 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx8KEBzKCywJjtwqF:-MI-DzfB4HsrEkViQtT_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L782)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 820 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxC5I6tzQs1ZnHToa:-MI-E3Ar4nol5k4y3cRs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L820)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 849 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxMFG7D-gstILvdD3:-MI-EIveAXIzFY3JYE3M:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L849)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 878 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxO6sBEF-LwUl9sPB:-MI-EVer08eTp3KeTTNK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L878)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 904 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxOzu7wJ9ju2y2WKk:-MI-EZpv9YR8p5tfxKgk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L904)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 929 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxQN1-nXA1UpAM8Yu:-MI-EcVN5OlxTGHfqRS8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L929)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

deletes
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 960 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxRta7RxZZJBwUgpy:-MI-Eh2i84ZYUs3fnFl2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L960)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 991 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxStm1whEc0uqtVIC:-MI-El8RBsCKrRBLN76k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L991)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1024 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxVfT462SnG8PPTU7:-MI-EwUC8Sb1hGBYjKhZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L1024)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1062 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxYrk4K7tvil5T9cP:-MI-F2XTEmonlsShOC1W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L1062)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-24 13:33 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 535 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzweyt7wZ8fsmG-F_n:-MI-HCR18kvSb7JR4wyl:b-b5vlkp) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L535)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

sets THE
___
*[src/include/librpma.h, line 560 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwq1n1Atb_G1ypdoP:-MI-HF4t2nZT32_sDCKU:b-1vt0fh) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L560)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

gets THE
___
*[src/include/librpma.h, line 586 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwvKu-dRR4n6we5tJ:-MI-HJZK1UnS58Ni108Q:b-oi8mpc) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L586)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the CQ ...
___
*[src/include/librpma.h, line 611 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwxIp3Hns98HMNeeg:-MI-HM2G0BQZ9eZ0PxKE:b-k7322m) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L611)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the CQ
___
*[src/include/librpma.h, line 637 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwyuY9-kcIfNO_xoZ:-MI-HNjR7nf0DdMdc2Tv:b-gxioe8) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L637)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the SQ ...
___
*[src/include/librpma.h, line 662 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzwzxiBzWiHJvmldpZ:-MI-HPMm1KcmgXEIFffv:b-k731ou) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L662)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the SQ
___
*[src/include/librpma.h, line 688 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx17QByvd60S_-9uo:-MI-HRoMB49JhYXHuNWg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L688)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[src/include/librpma.h, line 713 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzx26c8X__ggv2Etf0:-MI-HSiR7a665Hr_wt8c:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L713)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.
___
*[src/include/librpma.h, line 878 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzxO6sBEF-LwUl9sPB:-MI-HeBcBjC6lOqFEAIH:b-677e9r) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L878)):*
> ```
> applys remote peer cfg for the connection
> ```

applies the remote peer configuration to the connection
___
*[src/include/librpma.h, line 868 at r2](https://reviewable.io/reviews/pmem/rpma/428#-MI-HpLy82pYHZV80qVC:-MI-HpLy82pYHZV80qVD:b79gr8l) ([raw file](https://github.com/pmem/rpma/blob/b50214d06c9a6511acc48d7c41145bce72c786f0/src/include/librpma.h#L868)):*
> ```
> for
> ```

to
___
*[src/include/librpma.h, line 986 at r2](https://reviewable.io/reviews/pmem/rpma/428#-MI-IB4A5IxKo7QLiF7K:-MI-IB4A5IxKo7QLiF7L:bhgeoni) ([raw file](https://github.com/pmem/rpma/blob/b50214d06c9a6511acc48d7c41145bce72c786f0/src/include/librpma.h#L986)):*
> ```
>  request
> ```

 requests
___
*[src/include/librpma.h, line 996 at r2](https://reviewable.io/reviews/pmem/rpma/428#-MI-I52U48_utqaCWIfr:-MI-I52U48_utqaCWIfs:brlvth0) ([raw file](https://github.com/pmem/rpma/blob/b50214d06c9a6511acc48d7c41145bce72c786f0/src/include/librpma.h#L996)):*
> ```
> request
> ```

requests


<!-- Sent from Reviewable.io -->

2020-09-24 14:15 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 535 at r1](https://reviewable.io/reviews/pmem/rpma/428#-MHzweyt7wZ8fsmG-F_n:-MI-RqVc1vzpk7WE6tME:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72e85070cc0982f5b40f44a33d8a67d983fd4c61/src/include/librpma.h#L535)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

sets THE
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 868 at r2](https://reviewable.io/reviews/pmem/rpma/428#-MI-HpLy82pYHZV80qVC:-MI-SNX9DH0Pj_bUWlac:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b50214d06c9a6511acc48d7c41145bce72c786f0/src/include/librpma.h#L868)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> for
> ```

to
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 986 at r2](https://reviewable.io/reviews/pmem/rpma/428#-MI-IB4A5IxKo7QLiF7K:-MI-Seeg32uC9om1vjTP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b50214d06c9a6511acc48d7c41145bce72c786f0/src/include/librpma.h#L986)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  request
> ```

 requests
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 996 at r2](https://reviewable.io/reviews/pmem/rpma/428#-MI-I52U48_utqaCWIfr:-MI-ShfoBvQb165vMZIa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b50214d06c9a6511acc48d7c41145bce72c786f0/src/include/librpma.h#L996)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> request
> ```

requests
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-24 16:23 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 07:22 UTC, ldorau approved these changes
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428#-:-MI37ynP7fGBdlmOyw7X:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 09:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 890 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3Vhzt4DT_DRoFgRfz:-MI3Vhzt4DT_DRoFgRg-:bc6fozq) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L890)):*
> ```
>  * DESCRIPTION
>  * rpma_utils_conn_event_2str() returns const string representation
>  * of RPMA_CONN_* enums.
> ```

rpma_utils_conn_event_2str() converts RPMA_CONN_* enum to the const string representation.
___
*[src/include/librpma.h, line 894 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3VMfq15rvFd_gmOQV:-MI3VMfq15rvFd_gmOQW:b-hu9nut) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L894)):*
> ```
>  * The rpma_utils_conn_event_2str() const string representation
>  * of RPMA_CONN_* enums.
> ```

 The rpma_utils_conn_event_2str() **function returns the** const string representation
 of RPMA_CONN_* enums.
___
*[src/include/librpma.h, line 919 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3W48s-snmX_i0B-WQ:-MI3W48s-snmX_i0B-WR:b-vekwsx) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L919)):*
> ```
> obtains a pointer
> ```

obtains THE pointer
___
*[src/include/librpma.h, line 975 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3WKtqAKJoAyS8CppK:-MI3WKtqAKJoAyS8CppL:bkh9tay) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L975)):*
> ```
> initializes the RPMA connection disconnection process.
> ```

initializes disconnecting of the RPMA connection process.


<!-- Sent from Reviewable.io -->

2020-09-25 09:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 890 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3Vhzt4DT_DRoFgRfz:-MI3YkvFCIr0xxH8JgrH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L890)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * DESCRIPTION
>  * rpma_utils_conn_event_2str() returns const string representation
>  * of RPMA_CONN_* enums.
> ```

rpma_utils_conn_event_2str() converts RPMA_CONN_* enum to the const string representation.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 894 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3VMfq15rvFd_gmOQV:-MI3YvsJ6W4g4gOiMyIn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L894)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * The rpma_utils_conn_event_2str() const string representation
>  * of RPMA_CONN_* enums.
> ```

 The rpma_utils_conn_event_2str() **function returns the** const string representation
 of RPMA_CONN_* enums.

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 919 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3W48s-snmX_i0B-WQ:-MI3Z1GD7ULcwhyBt6cH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L919)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> obtains a pointer
> ```

obtains THE pointer
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 975 at r3](https://reviewable.io/reviews/pmem/rpma/428#-MI3WKtqAKJoAyS8CppK:-MI3ZEaaAGOzzAedq_JX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c7bd03663d681023496b17ff4bbb7b9894191523/src/include/librpma.h#L975)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> initializes the RPMA connection disconnection process.
> ```

initializes disconnecting of the RPMA connection process.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-25 09:37 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428#-:-MI3btl_5CQzDT8kKOH0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 12:36 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 874 at r5](https://reviewable.io/reviews/pmem/rpma/428#-MI4DqbzCa6SMld85Rgh:-MI4DqbzCa6SMld85Rgi:b9shp7d) ([raw file](https://github.com/pmem/rpma/blob/644bed061a69ee49a0bc638ee045e8ab723e1cfa/src/include/librpma.h#L874)):*
> ```
> RPMA_CONN_LOST
> ```
___
*[src/include/librpma.h, line 998 at r5](https://reviewable.io/reviews/pmem/rpma/428#-MI4EK2sE0C9E76ggRy2:-MI4EK2sE0C9E76ggRy3:b-4z4mq4) ([raw file](https://github.com/pmem/rpma/blob/644bed061a69ee49a0bc638ee045e8ab723e1cfa/src/include/librpma.h#L998)):*
> ```
> initializes
> ```
initiates
___
*[src/include/librpma.h, line 1021 at r5](https://reviewable.io/reviews/pmem/rpma/428#-MI4Eajh4isxTtl1TwfI:-MI4Eajh4isxTtl1TwfJ:by6j2k2) ([raw file](https://github.com/pmem/rpma/blob/644bed061a69ee49a0bc638ee045e8ab723e1cfa/src/include/librpma.h#L1021)):*
> ```
> conn
> ```
conn_ptr


<!-- Sent from Reviewable.io -->

2020-09-25 12:57 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428#-:-MI4KmXb4BfG71vFumq-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 15:52 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/428)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-25 16:11 UTC, merged