common: add nightly build on other Linux distros on GHA
pmem/rpma pull request #470
Opened 2020-09-28 14:24 UTC by ldorau

2020-10-05 15:43 UTC, janekmi requested changes
> Reviewed 10 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: 10 of 30 files reviewed, 5 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIt7g-BAOXUZGe3Iiah:-MIt7g-C-ZuVz4mJROsd:bvl3epn) (no related file):*
At some point, we should move forward to Ubuntu 20.4. Won't you think? ;-)

---
___
*[utils/docker/images/Dockerfile.fedora-31, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItQdrtBiaeGdBZWIIO:-MItQdruB5G1RAfPz4SI:b-cy0wr9) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-31#L43)):*
> ```
> 	graphviz \
> 	libunwind-devel \
> 	pandoc \
> ```

It is either RPMA_DEP or DOC_UPDATE_DEP?
___
*[utils/docker/images/Dockerfile.fedora-latest, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItGRTTCQEa9UkVnZU1:-MItGRTTCQEa9UkVnZU2:b-jtki5e) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-latest#L29)):*
> ```
> 	pkg-config \
> 	rpm-build \
> 	sudo \
> ```

Srsly it is not a default? x-D
___
*[utils/docker/images/Dockerfile.ubuntu-16.04, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItG4rSD6WKHWNsUTJm:-MItG4rSD6WKHWNsUTJn:bqwzyjd) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.ubuntu-16.04#L57)):*
> ```
> ENV EXAMPLES_DEPS "\
> 	$NDCTL_DEPS \
> 	$PMDK_DEPS"
> ```

https://packages.ubuntu.com/xenial/libprotobuf-c-dev ?
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIt8Oo0ELwQFY8AEyuD:-MIt8Oo0ELwQFY8AEyuE:b-elcuy2) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.ubuntu-18.04#L35)):*
> ```
> 
> ENV EXAMPLES_DEPS "\
> 	libpmem-dev"
> ```

No libprotobuf here?

Ref: https://packages.ubuntu.com/bionic/libprotobuf-c-dev


<!-- Sent from Reviewable.io -->

2020-10-05 19:43 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: 10 of 30 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.fedora-latest, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItGRTTCQEa9UkVnZU1:-MIuH3Pe3XHLX5lSdG9l:b-7b7m70) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-latest#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Srsly it is not a default? x-D
</blockquote></details>

No, it is not the default.


<!-- Sent from Reviewable.io -->

2020-10-06 06:28 UTC, grom72 reviewed
> Reviewed 29 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIt7g-BAOXUZGe3Iiah:-MIwYVvgBKt57vqzkguf:bmeyrwp) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

At some point, we should move forward to Ubuntu 20.4. Won't you think? ;-)
</blockquote></details>

:+1: 

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIw_D159lmAdI5Gq9QY:-MIw_D161ApgMdo-7c7C:beripjw) (no related file):*
It would be beneficial to convert long sections common for each distribution into one bash script that could also be easily used when creating dev env manually.
<details><summary><i alt="summary">Quoted 36 lines of code…</i></summary>

> ```
> # Update all packages
> RUN dnf update -y
> # base deps
> ENV BASE_DEPS "\
> 	gcc \
> 	git \
> 	make \
> 	patch \
> 	pkg-config \
> 	rpm-build \
> 	sudo \
> 	which"
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel"
> # RPMA deps
> ENV RPMA_DEPS "\
> 	cmake \
> 	file \
> 	gawk \
> 	groff \
> 	graphviz \
> 	libunwind-devel \
> 	libibverbs-devel \
> 	librdmacm-devel"
> #	txt2man is installed from git repo now
> # doc update deps
> ENV DOC_UPDATE_DEPS "\
> 	pandoc \
> 	hub"
> # Install all required packages
> RUN dnf install -y \
> 	$BASE_DEPS \
> 	$EXAMPLES_DEPS \
> 	$RPMA_DEPS \
> 	$DOC_UPDATE_DEPS \
> && dnf clean all
> ```
</details>


---
___
*[utils/docker/images/Dockerfile.debian-latest, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIwZ0K89VHo13hK6LR7:-MIwZ0K97TnUfptUQkjU:bzczibq) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.debian-latest#L40)):*
> ```
> #txt2man is installed from git repo now
> ```
to be removed from all docker files
___
*[utils/docker/images/Dockerfile.debian-stable, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIwZ9bM67ZEEsTIkOGO:-MIwZ9bM67ZEEsTIkOGP:bnj77b4) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.debian-stable#L46)):*
> ```
> #txt2man is installed from git repo now
> ```
.
___
*[utils/docker/images/Dockerfile.fedora-26, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIw_h721dZDDJQYMzL-:-MIw_h721dZDDJQYMzL0:bbkuz3l) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-26#L52)):*
<details><summary><i alt="summary">Quoted 36 lines of code…</i></summary>

> ```
> # Update all packages
> RUN dnf update -y
> # base deps
> ENV BASE_DEPS "\
> 	gcc \
> 	git \
> 	make \
> 	patch \
> 	pkg-config \
> 	rpm-build \
> 	sudo \
> 	which"
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel"
> # RPMA deps
> ENV RPMA_DEPS "\
> 	cmake \
> 	file \
> 	gawk \
> 	groff \
> 	graphviz \
> 	libunwind-devel \
> 	libibverbs-devel \
> 	librdmacm-devel"
> #	txt2man is installed from git repo now
> # doc update deps
> ENV DOC_UPDATE_DEPS "\
> 	pandoc \
> 	hub"
> # Install all required packages
> RUN dnf install -y \
> 	$BASE_DEPS \
> 	$EXAMPLES_DEPS \
> 	$RPMA_DEPS \
> 	$DOC_UPDATE_DEPS \
> && dnf clean all
> ```
</details>

___
*[utils/docker/images/Dockerfile.fedora-26, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIwZITaCvWj2AnGY8-l:-MIwZITaCvWj2AnGY8-m:b-jpg0qv) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-26#L59)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> # Install cmocka
> COPY install-cmocka.sh install-cmocka.sh
> RUN ./install-cmocka.sh
> # Install txt2man
> COPY install-txt2man.sh install-txt2man.sh
> RUN ./install-txt2man.sh
> ```
</details>

this is common for all docker files - can we have a common script that does this sequence 
COPY install-custom-env.sh install-custom-env.sh
RUN ./install-custom-env.sh


<!-- Sent from Reviewable.io -->

2020-10-06 07:36 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIw_D159lmAdI5Gq9QY:-MIwpbDm3cJ6XSxV0cGB:b3q6h78) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It would be beneficial to convert long sections common for each distribution into one bash script that could also be easily used when creating dev env manually.
> ```
> # Update all packages
> RUN dnf update -y
> # base deps
> ENV BASE_DEPS "\
> 	gcc \
> 	git \
> 	make \
> 	patch \
> 	pkg-config \
> 	rpm-build \
> 	sudo \
> 	which"
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel"
> # RPMA deps
> ENV RPMA_DEPS "\
> 	cmake \
> 	file \
> 	gawk \
> 	groff \
> 	graphviz \
> 	libunwind-devel \
> 	libibverbs-devel \
> 	librdmacm-devel"
> #	txt2man is installed from git repo now
> # doc update deps
> ENV DOC_UPDATE_DEPS "\
> 	pandoc \
> 	hub"
> # Install all required packages
> RUN dnf install -y \
> 	$BASE_DEPS \
> 	$EXAMPLES_DEPS \
> 	$RPMA_DEPS \
> 	$DOC_UPDATE_DEPS \
> && dnf clean all
> ```
</blockquote></details>

:+1:  at some point. Yes. Please do not change this for the sake of this PR.

---


<!-- Sent from Reviewable.io -->

2020-10-06 11:29 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: 7 of 30 files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIt7g-BAOXUZGe3Iiah:-MIx0I-G5mKfh1if-GKF:bokvyz1) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Yes, of course. BTW, 19.10 is already EOL and 20.04 is already tested in this PR as `latest`:
https://hub.docker.com/_/ubuntu

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIw_D159lmAdI5Gq9QY:-MIx0QZtBZu4E7ClBprL:b-dzjtvk) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1:  at some point. Yes. Please do not change this for the sake of this PR.
</blockquote></details>

No, it should not be converted in Dockerfiles. Dockerfiles should be built from many small steps.

---
___
*[utils/docker/images/Dockerfile.debian-stable, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIwZ9bM67ZEEsTIkOGO:-MIx1hqF3JDt-aAnxszI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.debian-stable#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #txt2man is installed from git repo now
> ```
.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.fedora-26, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIw_h721dZDDJQYMzL-:-MIx0ACxBJKOEz7EI3pu:b2nh8oq) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-26#L52)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> # Update all packages
> RUN dnf update -y
> # base deps
> ENV BASE_DEPS "\
> 	gcc \
> 	git \
> 	make \
> 	patch \
> 	pkg-config \
> 	rpm-build \
> 	sudo \
> 	which"
> ENV EXAMPLES_DEPS "\
> 	libpmem-devel"
> # RPMA deps
> ENV RPMA_DEPS "\
> 	cmake \
> 	file \
> 	gawk \
> 	groff \
> 	graphviz \
> 	libunwind-devel \
> 	libibverbs-devel \
> 	librdmacm-devel"
> #	txt2man is installed from git repo now
> # doc update deps
> ENV DOC_UPDATE_DEPS "\
> 	pandoc \
> 	hub"
> # Install all required packages
> RUN dnf install -y \
> 	$BASE_DEPS \
> 	$EXAMPLES_DEPS \
> 	$RPMA_DEPS \
> 	$DOC_UPDATE_DEPS \
> && dnf clean all
> ```

</blockquote></details>

???
___
*[utils/docker/images/Dockerfile.fedora-26, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIwZITaCvWj2AnGY8-l:-MIx1kQv0nWJuqBvleYF:b1sgj78) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-26#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> # Install cmocka
> COPY install-cmocka.sh install-cmocka.sh
> RUN ./install-cmocka.sh
> # Install txt2man
> COPY install-txt2man.sh install-txt2man.sh
> RUN ./install-txt2man.sh
> ```
this is common for all docker files - can we have a common script that does this sequence 
COPY install-custom-env.sh install-custom-env.sh
RUN ./install-custom-env.sh
</blockquote></details>

No, that is the way it has to be done in Dockerfiles:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
https://docs.docker.com/engine/reference/builder/#copy
https://docs.docker.com/engine/reference/builder/#run
___
*[utils/docker/images/Dockerfile.fedora-31, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItQdrtBiaeGdBZWIIO:-MIwSUvy9to0REd48Ftv:b-euxobc) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-31#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is either RPMA_DEP or DOC_UPDATE_DEP?
</blockquote></details>

IMHO 'pandoc' is a `RPMA_DEP` - it is required to generate markdown documentation regardless of the `AUTO_DOC_UPDATE` settings. The only `DOC_UPDATE_DEP` is `hub`. I will fix that.
___
*[utils/docker/images/Dockerfile.ubuntu-16.04, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItG4rSD6WKHWNsUTJm:-MIxQWLT3nit5rZbJJQY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.ubuntu-16.04#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

https://packages.ubuntu.com/xenial/libprotobuf-c-dev ?
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIt8Oo0ELwQFY8AEyuD:-MIxQX9i0W7AoD-s7Oc6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.ubuntu-18.04#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No libprotobuf here?

Ref: https://packages.ubuntu.com/bionic/libprotobuf-c-dev
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-latest, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MIwZ0K89VHo13hK6LR7:-MIx6kOv--20d_5x5lvM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.debian-latest#L40)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #txt2man is installed from git repo now
> ```
to be removed from all docker files
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-06 11:42 UTC, ldorau commented
All builds are tested in https://github.com/pmem/rpma/pull/400

2020-10-07 06:28 UTC, grom72 reviewed
> Reviewed 1 of 23 files at r2, 2 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: 6 of 30 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIt7g-BAOXUZGe3Iiah:-MJ0j_HO2bByseWZXQBg:bcf4jtp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, of course. BTW, 19.10 is already EOL and 20.04 is already tested in this PR as `latest`:
https://hub.docker.com/_/ubuntu

</blockquote></details>

Shall we remove 19.10?

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIw_D159lmAdI5Gq9QY:-MJ0jICG6mgcVNZjz9GY:b-ak9dwu) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it should not be converted in Dockerfiles. Dockerfiles should be built from many small steps.
</blockquote></details>

My point is that we have the same sections in all Fedora, all Centos, etc - do we need to maintain them separately?

---


<!-- Sent from Reviewable.io -->

2020-10-07 06:30 UTC, grom72 reviewed
> Reviewed 24 of 26 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-07 06:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIt7g-BAOXUZGe3Iiah:-MJ0klQw9ERMFauEK1Ud:b32w12) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we remove 19.10?
</blockquote></details>

No

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIw_D159lmAdI5Gq9QY:-MJ0krZa3Q3MjSYhFJJc:b-1gys4p) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

My point is that we have the same sections in all Fedora, all Centos, etc - do we need to maintain them separately?
</blockquote></details>

Yes, we have to.

---


<!-- Sent from Reviewable.io -->

2020-10-07 06:35 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIt7g-BAOXUZGe3Iiah:-MJ0l2tY7K66iQYzkAte:bob5dnd) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No
</blockquote></details>

Regular builds of rpma and pmdk still are run on 19.10

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/470#-MIw_D159lmAdI5Gq9QY:-MJ0lF5D2LRrdLDV7_Ha:bl64g42) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, we have to.
</blockquote></details>

That is the way Dockerfiles work.

---


<!-- Sent from Reviewable.io -->

2020-10-07 06:37 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/images/Dockerfile.fedora-31, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItQdrtBiaeGdBZWIIO:-MJ0ljqZEbbVAvCPHLGd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-31#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO 'pandoc' is a `RPMA_DEP` - it is required to generate markdown documentation regardless of the `AUTO_DOC_UPDATE` settings. The only `DOC_UPDATE_DEP` is `hub`. I will fix that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-08 13:15 UTC, grom72 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470#-:-MJ7LRnS5DdebEy5SN3V:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-12 18:58 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/images/Dockerfile.fedora-31, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MItQdrtBiaeGdBZWIIO:-MJTAJM59tN6KDcx3xyf:b-3p17t8) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.fedora-31#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi ping


<!-- Sent from Reviewable.io -->

2020-10-15 04:51 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470#-:-MJeaOU782kpjdeBoTRL:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-15 06:38 UTC, ldorau reviewed
@janekmi I have added CentOS 7.6 to the matrix of the nightly build.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470#-:-MJeyYhr3ihvXu2l-LW9:b-e2a49a)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-19 17:45 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-21 17:33 UTC, grom72 reviewed
> Reviewed 24 of 24 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-22 08:10 UTC, lukaszstolarczuk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[.github/workflows/nightly.yml, line 7 at r7](https://reviewable.io/reviews/pmem/rpma/470#-MKEJ8NR92FjdJSLvDXO:-MKEJ8NR92FjdJSLvDXP:b-sfmzci) ([raw file](https://github.com/pmem/rpma/blob/a8ed0cdebd3901d428cc73ae21392015d731c37e/.github/workflows/nightly.yml#L7)):*
> ```YAML
> on:
>   schedule:
>     # run this job at 00:00 UTC every day
> ```

this comment is kind of duplicated
___
*[.github/workflows/nightly.yml, line 19 at r7](https://reviewable.io/reviews/pmem/rpma/470#-MKEJDSQ0Hle5qv0HGC0:-MKEJDSQ0Hle5qv0HGC1:b-hu7h53) ([raw file](https://github.com/pmem/rpma/blob/a8ed0cdebd3901d428cc73ae21392015d731c37e/.github/workflows/nightly.yml#L19)):*
> ```YAML
>     WORKDIR:                 utils/docker
>     TYPE:                    normal
>     PUSH_IMAGE:              1
> ```

do you want to push image from both jobs (clang and gcc)?
___
*[utils/docker/images/Dockerfile.ubuntu-20.10, line 67 at r7](https://reviewable.io/reviews/pmem/rpma/470#-MKEKnCB8oknHh34MWFH:-MKEKnCC5I0j_kRe4I03:b-bv52qn) ([raw file](https://github.com/pmem/rpma/blob/a8ed0cdebd3901d428cc73ae21392015d731c37e/utils/docker/images/Dockerfile.ubuntu-20.10#L67)):*
> ```
> COPY download-scripts.sh download-scripts.sh
> COPY 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch
> RUN ./download-scripts.sh
> ```

I'm guessing you don't run coverage on these builds, so you don't need to download this script


<!-- Sent from Reviewable.io -->

2020-10-22 08:53 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: 22 of 31 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @lukaszstolarczuk)

___
*[.github/workflows/nightly.yml, line 7 at r7](https://reviewable.io/reviews/pmem/rpma/470#-MKEJ8NR92FjdJSLvDXO:-MKEUzNC6aiqSH7RCFfY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8ed0cdebd3901d428cc73ae21392015d731c37e/.github/workflows/nightly.yml#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this comment is kind of duplicated
</blockquote></details>

Done.
___
*[.github/workflows/nightly.yml, line 19 at r7](https://reviewable.io/reviews/pmem/rpma/470#-MKEJDSQ0Hle5qv0HGC0:-MKEV-RX4pmUtzAqV5-_:bs9wrh8) ([raw file](https://github.com/pmem/rpma/blob/a8ed0cdebd3901d428cc73ae21392015d731c37e/.github/workflows/nightly.yml#L19)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do you want to push image from both jobs (clang and gcc)?
</blockquote></details>

No, done
___
*[utils/docker/images/Dockerfile.ubuntu-20.10, line 67 at r7](https://reviewable.io/reviews/pmem/rpma/470#-MKEKnCB8oknHh34MWFH:-MKEVel8BC6EQ9YE_e7J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8ed0cdebd3901d428cc73ae21392015d731c37e/utils/docker/images/Dockerfile.ubuntu-20.10#L67)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm guessing you don't run coverage on these builds, so you don't need to download this script
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-22 09:19 UTC, ldorau commented
All builds are tested in #400

2020-10-22 15:59 UTC, grom72 reviewed
> Reviewed 8 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-28 15:52 UTC, janekmi requested changes
> Reviewed 1 of 30 files at r1, 1 of 26 files at r3, 2 of 24 files at r6, 5 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.ubuntu-16.04, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjtrHq2oVF1DE2s025:-MKjtrHq2oVF1DE2s026:bd9m5re) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-16.04#L70)):*
> ```
> 	libibverbs-dev \
> 	librdmacm-dev \
> 	libunwind-dev"
> ```

No pandoc?
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MKjtdPK53s8_PnXykxt:-MKjtdPK53s8_PnXykxu:b-qmduyr) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.ubuntu-18.04#L67)):*
> ```
> COPY download-scripts.sh download-scripts.sh
> COPY 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch
> RUN ./download-scripts.sh
> ```

Why mate?
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 48 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjt_zM6I50-D1xEl-A:-MKjt_zM6I50-D1xEl-B:bd9m5re) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-18.04#L48)):*
> ```
> 	libibverbs-dev \
> 	librdmacm-dev \
> 	libunwind-dev"
> ```

No pandoc?
___
*[utils/docker/images/Dockerfile.ubuntu-20.04, line 68 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjtHsp-qEnEQ9amgAo:-MKjtHsp-qEnEQ9amgAp:bfwlck1) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-20.04#L68)):*
> ```
> COPY download-scripts.sh download-scripts.sh
> COPY 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch 0001-fix-generating-gcov-files-and-turn-off-verbose-log.patch
> RUN ./download-scripts.sh
> ```

Why this part is only in this image?
___
*[utils/docker/images/Dockerfile.ubuntu-20.10, line 47 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjt6ro2hL08VQ7r9t4:-MKjt6rp02z70tdTgRQ3:b-kiy072) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-20.10#L47)):*
> ```
> 	libibverbs-dev \
> 	librdmacm-dev \
> 	libunwind-dev"
> ```

Why no pandoc?


<!-- Sent from Reviewable.io -->

2020-10-28 15:54 UTC, janekmi reviewed
> Reviewed 3 of 26 files at r3, 5 of 24 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2020-10-28 16:00 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[utils/docker/images/Dockerfile.ubuntu-20.04, line 68 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjtHsp-qEnEQ9amgAo:-MKjvAp9EOgBQl1xV3zZ:bq4j21w) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-20.04#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why this part is only in this image?
</blockquote></details>

Because only this image is used to measure the code coverage


<!-- Sent from Reviewable.io -->

2020-10-28 16:01 UTC, janekmi requested changes
> Reviewed 5 of 24 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 65 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjv74L002YmAAOOT8k:-MKjv74L002YmAAOOT8l:b-fanfnx) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.archlinux-base-latest#L65)):*
> ```
> RUN echo $USERPASS >> $PFILE
> RUN passwd $USER < $PFILE
> RUN rm -f $PFILE
> ```

What is going on here?
___
*[utils/docker/images/Dockerfile.centos-8, line 34 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjw0wz0U8DrhUSTYL-:-MKjw0wz0U8DrhUSTYL0:b-kwng6g) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.centos-8#L34)):*
> ```
> # RPMA deps
> ENV RPMA_DEPS "\
> 	cmake \
> ```

cmake3?


<!-- Sent from Reviewable.io -->

2020-10-28 16:05 UTC, janekmi requested changes
> Reviewed 4 of 24 files at r6, 3 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 27 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjxE0X7CtTt7AUJZSn:-MKjxE0X7CtTt7AUJZSo:bzdby9v) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L27)):*
> ```
> 	git \
> 	make \
> 	pkgconf-pkg-config \
> ```

Srsly?


<!-- Sent from Reviewable.io -->

2020-10-28 21:12 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470)* status: 20 of 31 files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[utils/docker/images/Dockerfile.archlinux-base-latest, line 65 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjv74L002YmAAOOT8k:-MKl-efcCDmTn1zeVTvT:bhby7mw) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.archlinux-base-latest#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is going on here?
</blockquote></details>

It is setting the password for the $USER user:

```
$  passwd $USER < $PFILE
```

That is the only way I have found working in Dockerfile on Arch Linux .
___
*[utils/docker/images/Dockerfile.centos-8, line 34 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjw0wz0U8DrhUSTYL-:-MKkzgiR58RlUOsqEpUx:bjp4wpt) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.centos-8#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cmake3?
</blockquote></details>

No, cmake is OK in case of CentOS 8
___
*[utils/docker/images/Dockerfile.opensuse-tumbleweed-latest, line 27 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjxE0X7CtTt7AUJZSn:-MKl-8kP1M5wxC2-WqyN:b8mu3e7) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.opensuse-tumbleweed-latest#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Srsly?
</blockquote></details>

Yes :-)

```
 (104/146) Installing: pkgconf-pkg-config-1.7.3-2.2.x86_64 [......done]
```
___
*[utils/docker/images/Dockerfile.ubuntu-16.04, line 70 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjtrHq2oVF1DE2s025:-MKl-EDT0tU5VnS5C2UB:b-omlmb6) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-16.04#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No pandoc?
</blockquote></details>

It already is in PMDK_DEPS, but I have added it also here.
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/470#-MKjtdPK53s8_PnXykxt:-MKl-SLsBZ75tE78pPW8:bevhia6) ([raw file](https://github.com/pmem/rpma/blob/f9855fe9234ea19bf774af368fe01a466657003e/utils/docker/images/Dockerfile.ubuntu-18.04#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why mate?
</blockquote></details>

What why?
___
*[utils/docker/images/Dockerfile.ubuntu-18.04, line 48 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjt_zM6I50-D1xEl-A:-MKl-Hh17J6Lea_GwEwy:b-41oa8a) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-18.04#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No pandoc?
</blockquote></details>

I missed it, added.
___
*[utils/docker/images/Dockerfile.ubuntu-20.10, line 47 at r9](https://reviewable.io/reviews/pmem/rpma/470#-MKjt6ro2hL08VQ7r9t4:-MKl-MRJ9zJeGVl9NJEG:b-41oa8a) ([raw file](https://github.com/pmem/rpma/blob/3e9cb9366f6f147e5c381d9cdf99331039569850/utils/docker/images/Dockerfile.ubuntu-20.10#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why no pandoc?
</blockquote></details>

I missed it, added.


<!-- Sent from Reviewable.io -->

2020-10-29 15:51 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 12 of 12 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/470#-:-MKp2VMR4LVKEzOHJCCy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-29 15:52 UTC, merged