doc: add the missing documentation
pmem/rpma pull request #507
Opened 2020-09-30 15:25 UTC by osalyk

2020-09-30 17:17 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 637 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUkyZR873BB2vjnDaE:-MIUkyZR873BB2vjnDaF:bd30u76) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L637)):*
> ```objc
>  *	#define RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT	(1 << 5)
>  *	#define RPMA_MR_USAGE_SEND			(1 << 6)
>  *	#define RPMA_MR_USAGE_RECV			(1 << 7)
> ```

It conveys hardly any information and looks ugly as hell...

Read more below.
___
*[src/include/librpma.h, line 645 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUmYzj0a2Cdkvx9z-q:-MIUmYzk-AcD5n22m1LJ:bpdfawt) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L645)):*
> ```objc
>  * rpma_mr_reg() registers a memory region and creates a local memory
>  * registration object. The usege parameter specifies the operation
>  * that can be performed on a given memory region.
> ```

... region which should be expressed as bitwise-inclusive or of the following:

- RPMA_XXX - xxx
- ...
___
*[src/include/librpma.h, line 1743 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUs5KE5WU2gDIXDlpU:-MIUs5KE5WU2gDIXDlpV:b-em2szj) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1743)):*
> ```objc
>  *	#define RPMA_F_COMPLETION_ON_ERROR (1 << 0)
>  *	#define RPMA_F_COMPLETION_ALWAYS (1 << 1 | RPMA_F_COMPLETION_ON_ERROR)
>  *
> ```

Same here. Looks very bad and conveys nothing.
___
*[src/include/librpma.h, line 1790 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsC406VPOapWcOFTS:-MIUsC406VPOapWcOFTT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1790)):*
> ```objc
>  *	#define RPMA_F_COMPLETION_ON_ERROR (1 << 0)
>  *	#define RPMA_F_COMPLETION_ALWAYS (1 << 1 | RPMA_F_COMPLETION_ON_ERROR)
>  *
> ```

.
___
*[src/include/librpma.h, line 1841 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsGIb1rZKBN0Ea-b5:-MIUsGIb1rZKBN0Ea-b6:b2kxtu3) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1841)):*
> ```objc
>  *	#define RPMA_F_COMPLETION_ON_ERROR (1 << 0)
>  *	#define RPMA_F_COMPLETION_ALWAYS (1 << 1 | RPMA_F_COMPLETION_ON_ERROR)
>  *
> ```

To be removed.
___
*[src/include/librpma.h, line 1904 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsJHb7Yt4jLUd1y1j:-MIUsJHb7Yt4jLUd1y1k:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1904)):*
> ```objc
>  *	#define RPMA_F_COMPLETION_ON_ERROR (1 << 0)
>  *	#define RPMA_F_COMPLETION_ALWAYS (1 << 1 | RPMA_F_COMPLETION_ON_ERROR)
>  *
> ```

.
___
*[src/include/librpma.h, line 1957 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsLhe5w8648K7VDtS:-MIUsLhe5w8648K7VDtT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1957)):*
> ```objc
>  *	#define RPMA_F_COMPLETION_ON_ERROR (1 << 0)
>  *	#define RPMA_F_COMPLETION_ALWAYS (1 << 1 | RPMA_F_COMPLETION_ON_ERROR)
>  *
> ```

.
___
*[src/include/librpma.h, line 1967 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsMnq5Te37oRpS9cg:-MIUsMnq5Te37oRpS9ch:b-2hwdw7) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1967)):*
> ```objc
>  * The attribute flags set the completion notification indicator:
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * -RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
> ```

you are missing space after `-`
___
*[src/include/librpma.h, line 2000 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsS0M0VIMjW-vsZUt:-MIUsS0M0VIMjW-vsZUu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2000)):*
> ```objc
>  *	#define RPMA_F_COMPLETION_ON_ERROR (1 << 0)
>  *	#define RPMA_F_COMPLETION_ALWAYS (1 << 1 | RPMA_F_COMPLETION_ON_ERROR)
>  *
> ```

.
___
*[src/include/librpma.h, line 2020 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsQpOEPdtjFxwcGRs:-MIUsQpOEPdtjFxwcGRt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2020)):*
> ```objc
>  * The attribute flags set the completion notification indicator:
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * -RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
> ```

.
___
*[src/include/librpma.h, line 2137 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIV04MDCuOA_f-IMakR:-MIV04MDCuOA_f-IMakS:bmaob0n) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2137)):*
> ```objc
>  *		RPMA_OP_SEND,
>  *		RPMA_OP_RECV,
>  *	};
> ```

Leave just an `enum rpma_op;`.
___
*[src/include/librpma.h, line 2147 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIV0Bxy7ljrGeLSrY-2:-MIV0Bxy7ljrGeLSrY-3:bij3gy8) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2147)):*
> ```objc
>  * error. All operations posted with the **RPMA_F_COMPLETION_ALWAYS** flag will
>  * also generate a completion on success.
>  *
> ```

Add a list with descriptions here.


<!-- Sent from Reviewable.io -->

2020-09-30 18:09 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 637 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUkyZR873BB2vjnDaE:-MIV6l1nAK3Q8gBhWpBJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L637)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It conveys hardly any information and looks ugly as hell...

Read more below.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 645 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUmYzj0a2Cdkvx9z-q:-MIV6lnmCNf1kxBv1EYz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L645)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... region which should be expressed as bitwise-inclusive or of the following:

- RPMA_XXX - xxx
- ...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1743 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUs5KE5WU2gDIXDlpU:-MIV6wKO7BIW-t9xItp_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1743)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. Looks very bad and conveys nothing.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1790 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsC406VPOapWcOFTS:-MIV71pC0MpajzVssZRR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1790)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1841 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsGIb1rZKBN0Ea-b5:-MIV7VhZEWWAIV-TMuP-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1841)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To be removed.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1904 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsJHb7Yt4jLUd1y1j:-MIV7_fu3rnD9GU37ay-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1904)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1957 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsLhe5w8648K7VDtS:-MIV7dHT6KYtFpDa3l8B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1957)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1967 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsMnq5Te37oRpS9cg:-MIV7hR92GodtVlgvd4D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1967)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

you are missing space after `-`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2000 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsS0M0VIMjW-vsZUt:-MIV7kfO1nONQp9UVQip:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2000)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2020 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIUsQpOEPdtjFxwcGRs:-MIV82hz6Gb5kvauvYi_:b4hsy6d) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2020)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

that's the description
___
*[src/include/librpma.h, line 2137 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIV04MDCuOA_f-IMakR:-MIV8JuD8QDwTjqwHacl:b60fkpo) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Leave just an `enum rpma_op;`.
</blockquote></details>

All enums were entered in this way.
___
*[src/include/librpma.h, line 2147 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIV0Bxy7ljrGeLSrY-2:-MIV9LF5-fqLkee0p0Jf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2147)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Add a list with descriptions here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-30 18:12 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/include/librpma.h, line 1920 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIVBimN0xSDxly39xXy:-MIVBimN0xSDxly39xXz:bcxniu2) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1920)):*
> ```
> -
> ```
[space] is missing
___
*[src/include/librpma.h, line 668 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVCHO5C0xIgQcsXwxm:-MIVCHO5C0xIgQcsXwxn:brreb37) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L668)):*
> ```
> RPMA_MR_USAGE_READ_SRC
> ```
RPMA_MR_USAGE_READ_SRC - memory used as source for read operation
...


<!-- Sent from Reviewable.io -->

2020-09-30 18:19 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/include/librpma.h, line 1878 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVCrwA76SSKhQyKUQ2:-MIVCrwB8zofeQh8z3bi:b-ikzdu2) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L1878)):*
> ```
> -
> ```
- +[space]
___
*[src/include/librpma.h, line 2033 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVE3tC7P4qgB6kWDgm:-MIVE3tC7P4qgB6kWDgn:bvqoa77) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L2033)):*
> ```
> -
> ```
+[space]
___
*[src/include/librpma.h, line 2161 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVECdV-pT-F6A_qmGa:-MIVECdV-pT-F6A_qmGb:bcv3oh7) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L2161)):*
> ```
> RPMA_OP_READ
> ```
RPMA_OP_READ - RMA read operation
...


<!-- Sent from Reviewable.io -->

2020-09-30 18:19 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2020-09-30 18:29 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 1920 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIVBimN0xSDxly39xXy:-MIVE0Ou70g1cCYaXnjy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L1920)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> -
> ```
[space] is missing
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 668 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVCHO5C0xIgQcsXwxm:-MIVFvjdCLVnRk5lxux8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L668)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_MR_USAGE_READ_SRC
> ```
RPMA_MR_USAGE_READ_SRC - memory used as source for read operation
...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1878 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVCrwA76SSKhQyKUQ2:-MIVG0cCDyPTUCS8saJ7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L1878)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> -
> ```
- +[space]
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2033 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVE3tC7P4qgB6kWDgm:-MIVG5ve5rW5nBy6HgY3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L2033)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> -
> ```
+[space]
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2161 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVECdV-pT-F6A_qmGa:-MIVGQ-T5hTBSlXUGhp8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L2161)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_OP_READ
> ```
RPMA_OP_READ - RMA read operation
...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-09-30 18:41 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 2161 at r2](https://reviewable.io/reviews/pmem/rpma/507#-MIVECdV-pT-F6A_qmGa:-MIVJ5z70RtGWPbjSLur:b-7d1dw5) ([raw file](https://github.com/pmem/rpma/blob/ca03cb7ef5af599a107ad998b404a1184c44c4ad/src/include/librpma.h#L2161)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

~~P~~
___
*[src/include/librpma.h, line 301 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJLzY4Q-2mwrnGTpo:-MIVJLzZBqLKkhuWXMi4:b-k9thyt) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L301)):*
> ```objc
>  *
>  * SEE ALSO
>  * librpma(7), rpma_peer_new(3), rpma_utils_ibv_context_is_odp_capable(3) and
> ```

man.7 should go after all man.3 but before the webpage.


<!-- Sent from Reviewable.io -->

2020-09-30 18:42 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 2147 at r1](https://reviewable.io/reviews/pmem/rpma/507#-MIV0Bxy7ljrGeLSrY-2:-MIVItqE4_xH6sycYrBA:btpx1w2) ([raw file](https://github.com/pmem/rpma/blob/2576d9dcbee52c8162540bd1f02fc7ae49fc40ff/src/include/librpma.h#L2147)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

RMA operation are Read/write/flus other are just send/receive (without RPMA in description
___
*[src/include/librpma.h, line 2183 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJ9gR0FK2aaP5hIyn:-MIVJ9gR0FK2aaP5hIyo:b-yi8fvp) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2183)):*
> ```objc
>  * SEE ALSO
>  * librpma(7), rpma_conn_get_completion_fd(3), rpma_conn_prepare_completions(3),
>  * rpma_conn_req_connect(3) and https://pmem.io/rpma/
> ```

@janekmi szhall we also refere here to all operation read/write/send/recv/flush/...


<!-- Sent from Reviewable.io -->

2020-09-30 18:43 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 2165 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJleT7Ofrc0qSzAga:-MIVJleT7Ofrc0qSzAgb:b-slq6jm) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2165)):*
> ```
> RPMA
> ```
not used in case of send/recv


<!-- Sent from Reviewable.io -->

2020-09-30 18:48 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 2165 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJleT7Ofrc0qSzAga:-MIVKW8e67Nu-Di6LD-M:b9hz2ut) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2165)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA
> ```
not used in case of send/recv
</blockquote></details>

- Messaging send operation?
- Messaging recv operation?
___
*[src/include/librpma.h, line 2183 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJ9gR0FK2aaP5hIyn:-MIVKkiyD7xOksuLNOVz:b-jmpfp) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2183)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@janekmi szhall we also refere here to all operation read/write/send/recv/flush/...
</blockquote></details>

We can but I'm not zealot about this. ;-)
We will have librpma(7) reference will hopefully say a lot about the completions and where are they come from.


<!-- Sent from Reviewable.io -->

2020-09-30 18:50 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 665 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJoUV3tbQJIf6PvOG:-MIVJoUV3tbQJIf6PvOH:bcd1tg) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L665)):*
> ```
> the operation
> ```

the operationS
___
*[src/include/librpma.h, line 666 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJtIB9HiVhOuWUPjm:-MIVJtIB9HiVhOuWUPjn:bs6lckx) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L666)):*
> ```
> on a given
> ```

on the given
___
*[src/include/librpma.h, line 667 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVK24M5bJ_Qa-3hiED:-MIVK24M5bJ_Qa-3hiEE:b-esna43) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L667)):*
> ```
> or
> ```

`'OR'`
___
*[src/include/librpma.h, line 668 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVK8jHBUWgXYzdORx9:-MIVK8jHBUWgXYzdORxA:b-3envrp) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L668)):*
> ```
> as source for read operation
> ```

as A source OF THE read operation
___
*[src/include/librpma.h, line 669 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVKaJR3DmD8DO9QJQM:-MIVKaJR3DmD8DO9QJQN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L669)):*
> ```objc
>  * as bitwise-inclusive or of the following:
>  * - RPMA_MR_USAGE_READ_SRC - memory used as source for read operation
>  * - RPMA_MR_USAGE_READ_DST - memory used as destination for read operation
> ```

.
___
*[src/include/librpma.h, line 670 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVKbYLBQTYh6dQFaLb:-MIVKbYLBQTYh6dQFaLc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L670)):*
> ```objc
>  * - RPMA_MR_USAGE_READ_SRC - memory used as source for read operation
>  * - RPMA_MR_USAGE_READ_DST - memory used as destination for read operation
>  * - RPMA_MR_USAGE_WRITE_SRC - memory used as source for write operation
> ```

.
___
*[src/include/librpma.h, line 671 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVKcU9-BYIFxE3mH9l:-MIVKcU9-BYIFxE3mH9m:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L671)):*
> ```objc
>  * - RPMA_MR_USAGE_READ_DST - memory used as destination for read operation
>  * - RPMA_MR_USAGE_WRITE_SRC - memory used as source for write operation
>  * - RPMA_MR_USAGE_WRITE_DST - memory used as destination for write operation
> ```

.
___
*[src/include/librpma.h, line 1788 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVLKYu1pyrSszUV7Cc:-MIVLKYu1pyrSszUV7Cd:bt2o2pr) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1788)):*
> ```
> generate operation completion on error
> ```

generate the completion on error
___
*[src/include/librpma.h, line 1789 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVLOfKANaCNgDIEslR:-MIVLOfKANaCNgDIEslS:bwp2we8) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1789)):*
> ```
> generate operation completion regardless
>  * of its result
> ```

generate the completion regardless of result of the operation
___
*[src/include/librpma.h, line 1833 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVLY18-kvTBlNBS-qn:-MIVLY18-kvTBlNBS-qo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1833)):*
> ```objc
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

.


<!-- Sent from Reviewable.io -->

2020-09-30 18:55 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[src/include/librpma.h, line 301 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJLzY4Q-2mwrnGTpo:-MIVMHonDL7jP28UuTk-:bl525a5) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L301)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

man.7 should go after all man.3 but before the webpage.
</blockquote></details>

so every see also shall end with ", librpma(7) and https://pmem.io/rpma/"
___
*[src/include/librpma.h, line 2165 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJleT7Ofrc0qSzAga:-MIVMaqSBkexWvi9BKY0:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2165)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- Messaging send operation?
- Messaging recv operation?
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2020-09-30 18:56 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/include/librpma.h, line 2183 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJ9gR0FK2aaP5hIyn:-MIVMrgtAyG8oO5h7L73:b-3bnerr) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2183)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can but I'm not zealot about this. ;-)
We will have librpma(7) reference will hopefully say a lot about the completions and where are they come from.
</blockquote></details>

yes - but that function call creates contexts for this call


<!-- Sent from Reviewable.io -->

2020-09-30 19:00 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/include/librpma.h, line 1880 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNUePAC7yEXyRRuWY:-MIVNUePAC7yEXyRRuWZ:b-4zfibz) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1880)):*
> ```
> * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

please fix as above
___
*[src/include/librpma.h, line 1944 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNb8gBRD_h1BY1KtL:-MIVNb8hCh1US2PLRVkJ:b-9mulot) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1944)):*
> ```
>  - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

.
___
*[src/include/librpma.h, line 1986 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNe0y6h1ak1Dde__V:-MIVNe0y6h1ak1Dde__W:b-j5yb88) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1986)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>  * The attribute flags set the completion notification indicator:
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```
</details>


.
___
*[src/include/librpma.h, line 2035 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNggw83c7n29RmDnX:-MIVNggw83c7n29RmDnY:b-j5yb88) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2035)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>  * The attribute flags set the completion notification indicator:
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```
</details>


.


<!-- Sent from Reviewable.io -->

2020-09-30 19:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 17 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 301 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJLzY4Q-2mwrnGTpo:-MIVPm6s3mGORMgCjJIG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L301)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

so every see also shall end with ", librpma(7) and https://pmem.io/rpma/"
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 665 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJoUV3tbQJIf6PvOG:-MIVPymDDLP_u7lCE8bv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L665)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the operation
> ```

the operationS
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 666 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJtIB9HiVhOuWUPjm:-MIVQ6mb8NZziMJ94FuH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L666)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> on a given
> ```

on the given
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 667 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVK24M5bJ_Qa-3hiED:-MIVQBCxCQuSJt48LqIH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L667)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> or
> ```

`'OR'`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 668 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVK8jHBUWgXYzdORx9:-MIVQHJ0CGigf2NpiAEX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L668)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> as source for read operation
> ```

as A source OF THE read operation
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 669 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVKaJR3DmD8DO9QJQM:-MIVQMWJDhWczNaLFtxN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L669)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 670 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVKbYLBQTYh6dQFaLb:-MIVQSOw4FXsl0ByRPIz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L670)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 671 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVKcU9-BYIFxE3mH9l:-MIVQTDM9TTQL-NZC_-j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L671)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1788 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVLKYu1pyrSszUV7Cc:-MIVQ_zF84RozCYblf-3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1788)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> generate operation completion on error
> ```

generate the completion on error
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1789 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVLOfKANaCNgDIEslR:-MIVQdv38mrQURCTGgYC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1789)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> generate operation completion regardless
>  * of its result
> ```

generate the completion regardless of result of the operation

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1833 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVLY18-kvTBlNBS-qn:-MIVQoZZ4rYbqbuRHqBa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1833)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1880 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNUePAC7yEXyRRuWY:-MIVQpv-Dt95dPbSIMl2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1880)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

please fix as above
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1944 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNb8gBRD_h1BY1KtL:-MIVQqvv86qFf1WYWU9i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1944)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1986 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNe0y6h1ak1Dde__V:-MIVQs_F9oywC-kGBALJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L1986)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * The attribute flags set the completion notification indicator:
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2035 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVNggw83c7n29RmDnX:-MIVQtPM7desSB6WPN9u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2035)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * The attribute flags set the completion notification indicator:
>  * - RPMA_F_COMPLETION_ON_ERROR - generate operation completion on error
>  * - RPMA_F_COMPLETION_ALWAYS - generate operation completion regardless
>  * of its result
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2165 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJleT7Ofrc0qSzAga:-MIVR64F7KIkjj3CXazR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2165)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2183 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJ9gR0FK2aaP5hIyn:-MIVS2tY6E3mrtIWhUKB:b-7tfmjp) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L2183)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes - but t [...]

2020-09-30 19:26 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 667 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVK24M5bJ_Qa-3hiED:-MIVTi1qAfIXUTmiLA9t:b-1m2077) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L667)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

without '  '


<!-- Sent from Reviewable.io -->

2020-09-30 19:27 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: 0 of 1 files reviewed, 15 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 301 at r3](https://reviewable.io/reviews/pmem/rpma/507#-MIVJLzY4Q-2mwrnGTpo:-MIVTyPRC6BlGU2VynBF:b32wtd) ([raw file](https://github.com/pmem/rpma/blob/f2c44e03021da6a9cf0e446a1343b019888d1bed/src/include/librpma.h#L301)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2020-09-30 19:29 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-30 19:29 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-30 19:29 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507#-:-MIVUQ4IClwzBbUzJ2cf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-30 19:35 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507#-:-MIVVs6U6TJqUJ_TWi8G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-30 19:38 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-09-30 19:45 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-10-01 06:47 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/507#-:-MIXuUbK6X52Deah7FLa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-01 06:47 UTC, merged