integration test for 04-example-write-to-persistent
pmem/rpma pull request #566
Opened 2020-10-22 17:09 UTC by ewanglong

Signed-off-by: Wang,Long <long1.wang@intel.com>

There are two errors when testing 04-example-write-to-persistent as below log shown. 
[  ERROR   ] --- No entries for symbol __wrap_posix_memalign.
[  ERROR   ] --- 0xadd != 0xade

2020-10-23 09:33 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-MKJmcWG-OJGsSTqHAyg:-MKJmcWH7bh0-mTTggNS:b2cjd9a) (no related file):*
@ewanglong please add the "test: " prefix to the commit's subject:

```
$ cmake .. -DDEVELOPER_MODE=ON -DCHECK_CSTYLE=ON && make
Checking 245d7f5ba6695767604b491245e40447ef6cd789
FAIL: subject line in commit message does not contain valid area name
```

Please read: https://github.com/pmem/rpma/blob/master/CONTRIBUTING.md#commit-messages

---
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 428 at r1](https://reviewable.io/reviews/pmem/rpma/566#-MKJnTlf1_bONF3tZoh8:-MKJnTlf1_bONF3tZoh9:b-p7vd9g) ([raw file](https://github.com/pmem/rpma/blob/245d7f5ba6695767604b491245e40447ef6cd789/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L428)):*
> ```C
> 	return cmocka_run_group_tests(tests, NULL, NULL);
> }
> ```

```
tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c:428: last line in file is blank
```

Please remove this empty line.


<!-- Sent from Reviewable.io -->

2020-10-23 10:16 UTC, ldorau requested changes
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 282 at r1](https://reviewable.io/reviews/pmem/rpma/566#-MKJxOEh13YbPMbq-Ev9:-MKJxOEi4UERmFaDf2DI:b-dakyke) ([raw file](https://github.com/pmem/rpma/blob/245d7f5ba6695767604b491245e40447ef6cd789/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L282)):*
> ```
> , MOCK_DST_ADDR);
> ```

MOCK_SRC_ADDR


<!-- Sent from Reviewable.io -->

2020-10-23 11:03 UTC, ldorau reviewed
@ewanglong please fetch the current master and rebase this PR on the top of the current master (for the future: we write just "please rebase" in this case)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566#-:-MKK6Wee1LQEgO2KHbgM:beugcnm)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-10-23 12:33 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 296 at r1](https://reviewable.io/reviews/pmem/rpma/566#-MKKRM243Daa4DtCZwni:-MKKRM243Daa4DtCZwnj:b-eafq59) ([raw file](https://github.com/pmem/rpma/blob/245d7f5ba6695767604b491245e40447ef6cd789/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L296)):*
> ```
> MOCK_WRITE_LEN
> ```

`MOCK_SIZE`
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 297 at r1](https://reviewable.io/reviews/pmem/rpma/566#-MKKRTK30iWg6qVXCdxy:-MKKRTK30iWg6qVXCdxz:bctx6n9) ([raw file](https://github.com/pmem/rpma/blob/245d7f5ba6695767604b491245e40447ef6cd789/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L297)):*
> ```
> IBV_ACCESS_LOCAL_WRITE)
> ```

`IBV_ACCESS_REMOTE_WRITE | IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_READ`


<!-- Sent from Reviewable.io -->

2020-10-23 16:26 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-10-26 07:23 UTC, ewanglong commented
cmake .. -DDEVELOPER_MODE=ON -DCHECK_CSTYLE=ON && make
make cstlyle; make check-whitespace; make check-commits
all those check are passed but failed at this example-04 test itself.

2020-10-26 07:39 UTC, ldorau reviewed
@ewanglong please use Reviewable: https://reviewable.io/reviews/pmem/rpma/566#- 
and answer all issues.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566#-:-MKYqGXPBaZB2xXbi9KY:blnqnqq)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @ewanglong and @ldorau)



<!-- Sent from Reviewable.io -->

2020-10-26 09:39 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-26 10:14 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-MKZLSB-1doMVlKv10JT:-MKZLSB-1doMVlKv10JU:bnah6ko) (no related file):*
@ewanglong The current error:

```
[  ERROR   ] --- No entries for symbol __wrap_posix_memalign.
/rpma/tests/integration/common/mocks.c:711: error: Could not get value to mock function __wrap_posix_memalign
/rpma/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c:67: note: Previously returned mock value was declared here
```

means that the lines like the following are missing:

```
        struct posix_memalign_args allocated = {0};
        will_return(__wrap_posix_memalign, &allocated);
```

like in:
 https://github.com/pmem/rpma/blob/master/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L92. 

Please study the usage of the `allocated`  variable in this test.

---


<!-- Sent from Reviewable.io -->

2020-10-27 12:57 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 22 at r3](https://reviewable.io/reviews/pmem/rpma/566#-MKe7JbOAmsDF6uzEuFC:-MKe7JbOAmsDF6uzEuFD:bsql9ba) ([raw file](https://github.com/pmem/rpma/blob/1e3c13e7fd7c52bcdc307e5c07938c6150656bf9/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L22)):*
> ```C
> static const char msg[] = "Hello client!";
> 
> #define KILOBYTE 1024
> ```

There already is the define:

```
#define MOCK_SIZE		1024
```

in mocks.h
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 27 at r3](https://reviewable.io/reviews/pmem/rpma/566#-MKe6qTy7udbeE8FTFfj:-MKe6qTz5JQg1zwmhrSn:bn17aq5) ([raw file](https://github.com/pmem/rpma/blob/1e3c13e7fd7c52bcdc307e5c07938c6150656bf9/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L27)):*
It is not needed:
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> enum lang_t {en, es};
> struct hello_t {
> 	enum lang_t lang;
> 	char str[KILOBYTE];
> };
> ```
</details>


You can just add a define with the value of `sizeof(struct hello_t)`
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 179 at r3](https://reviewable.io/reviews/pmem/rpma/566#-MKe7Z8O7s3XCAFQ8BU7:-MKe7Z8O7s3XCAFQ8BU8:b-k1n25b) ([raw file](https://github.com/pmem/rpma/blob/1e3c13e7fd7c52bcdc307e5c07938c6150656bf9/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L179)):*
> ```
> sizeof(struct hello_t)
> ```

Replace it with a define, please.


<!-- Sent from Reviewable.io -->

2020-10-28 06:01 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 174 at r4](https://reviewable.io/reviews/pmem/rpma/566#-MKhn-ut6kGFeEyNIzSs:-MKhn-ut6kGFeEyNIzSt:br36d7e) ([raw file](https://github.com/pmem/rpma/blob/73d8b6e61e7b45f5ccac9fab978b7c0cccf59310/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L174)):*
> ```
>  1028)
> ```

Replace it with a define, please.


<!-- Sent from Reviewable.io -->

2020-10-28 06:25 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 22 at r4](https://reviewable.io/reviews/pmem/rpma/566#-MKhoxZF2jI-GGaTKk-R:-MKhoxZF2jI-GGaTKk-S:bskfxu5) ([raw file](https://github.com/pmem/rpma/blob/73d8b6e61e7b45f5ccac9fab978b7c0cccf59310/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L22)):*
It is not needed:

> ```
> #define KILOBYTE 1024
> ```

There already is the define:

```
#define MOCK_SIZE		1024
```

in mocks.h.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 137 at r4](https://reviewable.io/reviews/pmem/rpma/566#-MKhs26h78bMCaBc84h3:-MKhs26h78bMCaBc84h4:br1jhhj) ([raw file](https://github.com/pmem/rpma/blob/73d8b6e61e7b45f5ccac9fab978b7c0cccf59310/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L137)):*
> ```
> conn_raw
> ```

`conn_raw` is not a good name - it suggests it is a kind of a connection, but it contains only an allocated address ...


<!-- Sent from Reviewable.io -->

2020-10-28 06:59 UTC, ldorau reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-10-28 08:53 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-28 11:36 UTC, janekmi requested changes
> Reviewed 4 of 5 files at r1, 1 of 3 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[examples/04-write-to-persistent/client.c, line 27 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKiTV01-LrJNS5vkweu:-MKiTV01-LrJNS5vkwev:b-hvtibr) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/examples/04-write-to-persistent/client.c#L27)):*
> ```C
> #include "cmocka_alloc.h"
> #define main client_main
> #endif
> ```

Please move it just above the `main()`.
___
*[tests/integration/common/mocks.h, line 32 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKiyjw5DUUoRNoRV0iH:-MKiyjw5DUUoRNoRV0iI:b-cpesj8) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/tests/integration/common/mocks.h#L32)):*
> ```objc
> #define MOCK_MAX_INLINE_DATA	0 /* RPMA_MAX_INLINE_DATA */
> #define MOCK_SIZE		1024
> #define MOCK_HELLO_SIZE	1028
> ```

I think this should be moved to example-04-write-to-persistent.c and should be defined as:

```c
#define MOCK_HELLO_SIZE (sizeof(struct hello_t))
```

To do which you have to move this structure and all its dependants to a separate header file e.g. hello.h in the examples' directory.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 137 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKixJbd4ja8J2Ph0gEs:-MKixJbd4ja8J2Ph0gEt:bnb3mn2) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L137)):*
> ```C
> 	expect_value(ibv_reg_mr, access, IBV_ACCESS_LOCAL_WRITE);
> 	will_return(ibv_reg_mr, &allocated.ptr);
> 	will_return(ibv_reg_mr, MOCK_MR_CONN);
> ```

I think it will be better to call it `MOCK_MR_FLUSH`.
It took me a few minutes to sort out how this mr is related to the connection. xD


<!-- Sent from Reviewable.io -->

2020-10-28 11:57 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 131 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKj0u0WB3XcF3ntzJ1p:-MKj0u0WB3XcF3ntzJ1q:bdp6t63) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L131)):*
> ```C
> 	/* allocate memory for the rpma_flush_apm_new */
> 	struct posix_memalign_args allocated = {0};
> 	will_return(__wrap_posix_memalign, &allocated);
> ```

I think the issue you are facing is caused by you not taking into consideration the order of things that happen in the example.
Not the order is as follows:
- `posix_memalign` of the mr_ptr (the hello string) [1]
- `posix_memalign` read-after-write [2]
- `rpma_conn_req_connect` which
    - `posix_memalign` flush buffer [3]
    - `rpma_mr_reg` flush buffer [3]
- `rpma_mr_reg` of the mr_ptr (the hello string) [1]
- `rpma_mr_reg` read-after-write [2]

So you can NOT have a configuration like:
```c
posix_memalign [1]
rpma_mr_reg [1]
posix_memalign [2]
rpma_mr_reg [2]
posix_memalign [3]
rpma_mr_reg [3]
```

You have to do this as follows:
```c
posix_memalign [1]
posix_memalign [2]
posix_memalign [3]
rpma_mr_reg [3]
rpma_mr_reg [1]
rpma_mr_reg [2]
```
to match the order in which it is called.


<!-- Sent from Reviewable.io -->

2020-10-28 12:59 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-10-28 13:09 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 131 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKj0u0WB3XcF3ntzJ1p:-MKjIMKX7FaSKoLALX4l:b-wu788g) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L131)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the issue you are facing is caused by you not taking into consideration the order of things that happen in the example.
Not the order is as follows:
- `posix_memalign` of the mr_ptr (the hello string) [1]
- `posix_memalign` read-after-write [2]
- `rpma_conn_req_connect` which
    - `posix_memalign` flush buffer [3]
    - `rpma_mr_reg` flush buffer [3]
- `rpma_mr_reg` of the mr_ptr (the hello string) [1]
- `rpma_mr_reg` read-after-write [2]

So you can NOT have a configuration like:
```c
posix_memalign [1]
rpma_mr_reg [1]
posix_memalign [2]
rpma_mr_reg [2]
posix_memalign [3]
rpma_mr_reg [3]
```

You have to do this as follows:
```c
posix_memalign [1]
posix_memalign [2]
posix_memalign [3]
rpma_mr_reg [3]
rpma_mr_reg [1]
rpma_mr_reg [2]
```
to match the order in which it is called.
</blockquote></details>

@janekmi great explanation!

@ewanglong You can just debug and trace step by step the binary of this test (`tests/integration/example-04-write-to-persistent/example-04-write-to-persistent`)  using `cgdb` (to see the code) and check the order in which all functions are called in the server of the 04 example and configure all mocks exactly in the same order in your integration test.


<!-- Sent from Reviewable.io -->

2020-10-28 13:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-10-28 13:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 137 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKixJbd4ja8J2Ph0gEs:-MKjK9ipA2Fea0TXJ8xI:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be better to call it `MOCK_MR_FLUSH`.
It took me a few minutes to sort out how this mr is related to the connection. xD
</blockquote></details>

:+1: 


<!-- Sent from Reviewable.io -->

2020-10-30 06:43 UTC, ldorau requested changes
> Reviewed 5 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[examples/04-write-to-persistent/client.c, line 29 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKsE5Qx45oHqTl7sZGc:-MKsE5Qx45oHqTl7sZGd:bay9suv) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/client.c#L29)):*
> ```
> #define LANG_NUM(sizeof(hello_str) / sizeof(hello_str[0]))
> ```

It can also be moved to `hello.h`
___
*[examples/04-write-to-persistent/hello.h, line 8 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKsEfhHDtebIB_wa2_Z:-MKsEfhHDtebIB_wa2__:bul24od) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/hello.h#L8)):*
> ```objc
> 
> #define HELLO_STR_SIZE 1024
> ```

Please add here:

```
#define MOCK_HELLO_SIZE (sizeof(struct hello_t))
```


<!-- Sent from Reviewable.io -->

2020-10-30 06:44 UTC, ldorau reviewed
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-10-30 09:18 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[examples/04-write-to-persistent/hello.h, line 1 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKslAgb23xzVhMSGuex:-MKslAgcA_GTjQ7MDAnJ:b-bc70ho) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/hello.h#L1)):*
> ```objc
> #ifndef HELLO_H
> ```

There is the following error now:
```
Checking copyright headers of modified files only...
error: no BSD-3-Clause SPDX tag in file: /rpma/examples/04-write-to-persistent/hello.h
Error(s) in copyright headers found!
```

because all files (except of some exceptions) should start with:
1) BSD-3-Clause SPDX tag (which in case of header (*.h) files looks as below),
2) copyright notice
3) file's brief description

```
/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2020, Intel Corporation */

/*
 * hello.h -- >>> please write the description here <<<
 */
```


<!-- Sent from Reviewable.io -->

2020-11-02 09:11 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 7 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-ML7DI8b5yZY8XABp5O8:-ML7DI8cE1jpU9mChMGc:b-pok6aq) (no related file):*
All changes regarding `hello.h` should moved to a separate (the first) commit.

---


<!-- Sent from Reviewable.io -->

2020-11-02 09:11 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-03 07:51 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/integration/common/mocks.c, line 145 at r8](https://reviewable.io/reviews/pmem/rpma/566#-MLC4fq17p_miDe4KHkS:-MLC4fq26dpNvP6ACmjB:bmuwzct) ([raw file](https://github.com/pmem/rpma/blob/4963fc9589de369af1e4ecf201d67c44aa9c95d3/tests/integration/common/mocks.c#L145)):*
> ```
> 	assert_non_null(*pdst_addr);
> ```

It should stay as it was before:

```
	assert_int_equal(wr->sg_list->addr, *pdst_addr);
```


<!-- Sent from Reviewable.io -->

2020-11-03 08:08 UTC, ewanglong commented
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)_ status: 6 of 8 files reviewed, 8 unresolved discussions (waiting on @ewanglong and @ldorau)
> 
> _[tests/integration/common/mocks.c, line 145 at r8](https://reviewable.io/reviews/pmem/rpma/566#-MLC4fq17p_miDe4KHkS:-MLC4fq26dpNvP6ACmjB:bmuwzct) ([raw file](https://github.com/pmem/rpma/blob/4963fc9589de369af1e4ecf201d67c44aa9c95d3/tests/integration/common/mocks.c#L145)):_
> 
> > ```
> > 	assert_non_null(*pdst_addr);
> > ```
> 
> It should stay as it was before:
> 
> ```
> 	assert_int_equal(wr->sg_list->addr, *pdst_addr);
> ```
If so, since there was 4 bytes of offset when doing rpma_write in examples/04-write-to-persistent/client.c, how to handle it? 
	ret = rpma_write(conn, dst_mr, dst_offset, src_mr,
			(data_offset + offsetof(struct hello_t, str)), KILOBYTE,
			RPMA_F_COMPLETION_ON_ERROR, NULL);

Ever tried to change the configure by adding the offset too, but the zero value is returned then. So it still didn't work.
	will_return(ibv_post_send_mock, (uint64_t *)&mr_ptr.ptr + offsetof(struct hello_t, str));

2020-11-03 11:57 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 6 of 8 files reviewed, 9 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/integration/common/mocks.c, line 154 at r9](https://reviewable.io/reviews/pmem/rpma/566#-MLCwhO20xvnhNhI6wl3:-MLCwhO35M-z44KcQrgJ:b-mhhy7g) ([raw file](https://github.com/pmem/rpma/blob/53761f9e61d56bbdf2ee2eb3deaeca59e4efd43d/tests/integration/common/mocks.c#L154)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	if (wr->opcode == IBV_WR_RDMA_READ)
> 		memcpy((void *)wr->sg_list->addr,
> 			(void *)wr->wr.rdma.remote_addr, wr->sg_list->length);
> 	/* mock of RDMA write */
> 	else if (wr->opcode == IBV_WR_RDMA_WRITE)
> 		memcpy((void *)wr->wr.rdma.remote_addr,
> 			(void *)wr->sg_list->addr, wr->sg_list->length);
> ```
</details>


This change also is not needed. As you can see in src/mr.c, the call to `ibv_post_send()` looks exactly the same:

```
	int ret = ibv_post_send(qp, &wr, &bad_wr);
	if (ret) {
		RPMA_LOG_ERROR_WITH_ERRNO(ret,
			"ibv_post_send(src_addr=0x%x, rkey=0x%x, dst_addr=0x%x, length=%u, lkey=0x%x, wr_id=0x%x, opcode=IBV_WR_RDMA_READ, send_flags=%s)",
			wr.wr.rdma.remote_addr, wr.wr.rdma.rkey,
			sge.addr, sge.length, sge.lkey, wr.wr_id,
			(flags & RPMA_F_COMPLETION_ON_SUCCESS) ?
				"IBV_SEND_SIGNALED" : "0");
		return RPMA_E_PROVIDER;
	}
```

in `rpma_mr_read()` and in `rpma_mr_write()`:
- `wr->wr.rdma.remote_addr` is always the source address and
- `wr->sg_list->addr` is always the destination address.

Please revert this change too.


<!-- Sent from Reviewable.io -->

2020-11-03 11:57 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 7 of 8 files reviewed, 9 unresolved discussions (waiting on @ewanglong and @ldorau)



<!-- Sent from Reviewable.io -->

2020-11-03 12:13 UTC, ldorau requested changes
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/integration/common/mocks.c, line 145 at r8](https://reviewable.io/reviews/pmem/rpma/566#-MLC4fq17p_miDe4KHkS:-MLCzjDwC-y-JM2t0kqV:beokw2f) ([raw file](https://github.com/pmem/rpma/blob/4963fc9589de369af1e4ecf201d67c44aa9c95d3/tests/integration/common/mocks.c#L145)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

If so, since there was 4 bytes of offset when doing rpma_write in examples/04-write-to-persistent/client.c, how to handle it?  	ret = rpma_write(conn, dst_mr, dst_offset, src_mr, 			(data_offset + offsetof(struct hello_t, str)), KILOBYTE, 			RPMA_F_COMPLETION_ON_ERROR, NULL);

Ever tried to change the configure by adding the offset too, but the zero value is returned then. So it still didn't work. 	will_return(ibv_post_send_mock, (uint64_t *)&mr_ptr.ptr + offsetof(struct hello_t, str)); 
</blockquote></details>

How to handle it? @janekmi has described it in: https://github.com/pmem/rpma/pull/566#pullrequestreview-518583968

There should be the right `var` variable used in `will_return(ibv_reg_mr, &var.ptr);`:

```
	struct posix_memalign_args var = {0};
	will_return(__wrap_posix_memalign, &var);
	will_return(ibv_reg_mr, &var.ptr);
```

That's all.


<!-- Sent from Reviewable.io -->

2020-11-03 12:56 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 139 at r9](https://reviewable.io/reviews/pmem/rpma/566#-MLD4ExE2Lk7cmzXmARa:-MLD4ExFDvai_xCAU-7i:bj9o3ht) ([raw file](https://github.com/pmem/rpma/blob/53761f9e61d56bbdf2ee2eb3deaeca59e4efd43d/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L139)):*
> ```C
> 	will_return(rdma_migrate_id, MOCK_OK);
> 
> 	expect_value(rdma_connect, id, &Cm_id);
> ```

Wrong order, the mock of `__wrap_posix_memalign` should be configured here.


<!-- Sent from Reviewable.io -->

2020-11-03 16:02 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-03 16:04 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 139 at r9](https://reviewable.io/reviews/pmem/rpma/566#-MLD4ExE2Lk7cmzXmARa:-MLDqWn65bTBY26OLMBN:bno969i) ([raw file](https://github.com/pmem/rpma/blob/53761f9e61d56bbdf2ee2eb3deaeca59e4efd43d/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L139)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wrong order, the mock of `__wrap_posix_memalign` should be configured here.
</blockquote></details>

It is OK now.


<!-- Sent from Reviewable.io -->

2020-11-03 17:12 UTC, ldorau requested changes
> Reviewed 4 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong)

___
*[examples/04-write-to-persistent/hello.h, line 23 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE4Fhw7gmbpwiqiauZ:-MLE4Fhw7gmbpwiqiau_:b-sinb7y) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/hello.h#L23)):*
> ```
> #define HELLO_STR_OFFSET offsetof(struct hello_t, str)
> ```

It should be moved just after:

```
#define HELLO_STR_SIZE 1024
```
___
*[tests/integration/common/mocks.c, line 148 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE4VDxE9QXNv12J6DE:-MLE4VDxE9QXNv12J6DF:bbxycjf) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/tests/integration/common/mocks.c#L148)):*
> ```
> 	/* mock of RDMA read */
> ```

It can be removed as we discussed offline
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 20 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE44__BErbqQN3S28J:-MLE44__BErbqQN3S28K:b-uxhws1) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L20)):*
> ```
> #define MOCK_HELLO_SIZE (sizeof(struct hello_t))
> ```

It should be moved to hello.h
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 197 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE4s934tf6RVKnQUxj:-MLE4s934tf6RVKnQUxk:b-dhcode) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L197)):*
> ```
> 			MOCK_WRITE_ADDR);
> ```

It should be:

```
(char *)MOCK_WRITE_ADDR + MOCK_DATA_OFFSET);
```
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 198 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE50kV4GDWvs46wGm3:-MLE50kV4GDWvs46wGm4:b5t9280) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L198)):*
> ```
> (uint64_t *)&mr_ptr.ptr
> ```

It should be:

```
(uintptr_t)&mr_ptr.ptr
```


<!-- Sent from Reviewable.io -->

2020-11-03 21:06 UTC, janekmi requested changes
> Reviewed 1 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[examples/04-write-to-persistent/hello.h, line 8 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKsEfhHDtebIB_wa2_Z:-MLEulfbD7dYoSMgnPr5:b-fhkoxa) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/hello.h#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add here:

```
#define MOCK_HELLO_SIZE (sizeof(struct hello_t))
```

</blockquote></details>

I do not agree it is a good idea. This header is for the examples. Please do not mix test-related definitions here.
___
*[examples/04-write-to-persistent/hello.h, line 8 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLEvUkN5kS3iuA3fD8O:-MLEvUkN5kS3iuA3fD8P:b-kliv3q) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/hello.h#L8)):*
> ```objc
>  */
> 
> #ifndef HELLO_H
> ```

EXAMPLES_HELLO_H
___
*[examples/04-write-to-persistent/hello.h, line 12 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLEvYGb3Fy97IpZo66z:-MLEvYGc1969SMW6Tu0F:b-rmohhc) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/hello.h#L12)):*
> ```objc
> 
> #include <stdlib.h>
> #include <stdio.h>
> ```

I think these two are not needed for the definitions you have in this header.
___
*[examples/04-write-to-persistent/hello.h, line 23 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE4Fhw7gmbpwiqiauZ:-MLEv2CKDqSbT9pWAM-R:bs6h0xp) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/hello.h#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #define HELLO_STR_OFFSET offsetof(struct hello_t, str)
> ```

It should be moved just after:

```
#define HELLO_STR_SIZE 1024
```
</blockquote></details>

TBH I prefer having definitions using `offsetof()` after the structure they are using. It is easier for me to follow.
___
*[examples/04-write-to-persistent/hello.h, line 23 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLEvGph48Y3CiodyKRu:-MLEvGph48Y3CiodyKRv:b-nway1) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/hello.h#L23)):*
> ```objc
> };
> 
> #define HELLO_STR_OFFSET offsetof(struct hello_t, str)
> ```

I would like to have an empty line between the last definition and the following `#endif`.


<!-- Sent from Reviewable.io -->

2020-11-03 21:16 UTC, janekmi requested changes
> Reviewed 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 16 unresolved discussions (waiting on @ewanglong and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-ML7DI8b5yZY8XABp5O8:-MLExiWmDupYjmFrOnsS:bj69z0t) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All changes regarding `hello.h` should moved to a separate (the first) commit.
</blockquote></details>

Please keep these changes in two commits:
1. Introduce hello.h header in all of the examples
2. Add a new integration test

TBH you can even make a separate PR for 1. you want.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-MLExgFZ9cZm-TCew6sI:-MLExgFZ9cZm-TCew6sJ:b-u4y7o5) (no related file):*
Please note all of the following examples are using `struct hello_t` structure:
- 03-read-to-persistent
- 04-write-to-persistent
- 05-flush-to-persistent
- 09-flush-to-persistent-GPSPM

So you should:
1. Move hello.h to the common directory
2. Use it in all of the examples to remove the redundancy (which is possible only because you have created the header)

---
___
*[examples/04-write-to-persistent/client.c, line 29 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKsE5Qx45oHqTl7sZGc:-MLEvsS89HqhdH3K28nN:b32v57) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/client.c#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #define LANG_NUM(sizeof(hello_str) / sizeof(hello_str[0]))
> ```

It can also be moved to `hello.h`
</blockquote></details>

+1
___
*[examples/04-write-to-persistent/client.c, line 27 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLEvwIY-gQ8AKC1efKP:-MLEvwIY-gQ8AKC1efKQ:b-by0kp) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/client.c#L27)):*
> ```C
> 	[en] = "Hello world!",
> 	[es] = "¡Hola Mundo!"
> };
> ```

I think array also. The hello header without "Hola Mundo" seems incomplete. ;-)


<!-- Sent from Reviewable.io -->

2020-11-03 21:52 UTC, janekmi requested changes
> Reviewed 2 of 6 files at r6, 2 of 4 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 16 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/integration/common/mocks.c, line 145 at r8](https://reviewable.io/reviews/pmem/rpma/566#-MLC4fq17p_miDe4KHkS:-MLF20TZDO3CBnNL28Tj:bn4ngj2) ([raw file](https://github.com/pmem/rpma/blob/4963fc9589de369af1e4ecf201d67c44aa9c95d3/tests/integration/common/mocks.c#L145)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

How to handle it? @janekmi has described it in: https://github.com/pmem/rpma/pull/566#pullrequestreview-518583968

There should be the right `var` variable used in `will_return(ibv_reg_mr, &var.ptr);`:

```
	struct posix_memalign_args var = {0};
	will_return(__wrap_posix_memalign, &var);
	will_return(ibv_reg_mr, &var.ptr);
```

That's all.
</blockquote></details>

@ldorau I think your solution is valid as long as we assume the operation uses `offset == 0`.
But when `offset != 0` we have to use the technique proposed by @ewanglong.

@ewanglong do we use `offset != 0`?
___
*[tests/integration/common/mocks.c, line 20 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLEyo8z4Qn-Tq7fnLoa:-MLEyo9-B1tpTRrbr8fT:b22acxx) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/tests/integration/common/mocks.c#L20)):*
> ```C
> struct ibv_mr Ibv_mr;		/* mock IBV MR */
> struct ibv_mr Ibv_mr_raw; /* mock IBV MR RAW */
> struct ibv_mr Ibv_mr_flush; /* mock IBV MR FLUSH */
> ```

I think since we have two lines of outstanding length we can add tabs between a definition and the following comment e.g.:
```c
struct ibv_mr Ibv_mr_raw;\t/* mock IBV MR RAW */
```


<!-- Sent from Reviewable.io -->

2020-11-04 06:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 4 of 12 files reviewed, 14 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-ML7DI8b5yZY8XABp5O8:-MLGqiHV-DhAzOpOvjW1:b-8fx2u7) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please keep these changes in two commits:
1. Introduce hello.h header in all of the examples
2. Add a new integration test

TBH you can even make a separate PR for 1. you want.
</blockquote></details>

:+1: 

---
___
*[examples/04-write-to-persistent/client.c, line 29 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKsE5Qx45oHqTl7sZGc:-MLGqmHb84pB5V6Y9dfa:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/client.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

.
___
*[examples/04-write-to-persistent/hello.h, line 8 at r6](https://reviewable.io/reviews/pmem/rpma/566#-MKsEfhHDtebIB_wa2_Z:-MLGqG3h6jjOKMsqPGqy:b-31jhrs) ([raw file](https://github.com/pmem/rpma/blob/071a9b22205866eb364b1c5fad8bdf03d35a4e63/examples/04-write-to-persistent/hello.h#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not agree it is a good idea. This header is for the examples. Please do not mix test-related definitions here.
</blockquote></details>

OK, I thought this header will be used only for tests.
___
*[examples/04-write-to-persistent/hello.h, line 23 at r11](https://reviewable.io/reviews/pmem/rpma/566#-MLE4Fhw7gmbpwiqiauZ:-MLGq61J58B58GD0pXi4:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/ac2301411b4c5b714de481c58d14ba096fe0f2c6/examples/04-write-to-persistent/hello.h#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH I prefer having definitions using `offsetof()` after the structure they are using. It is easier for me to follow.
</blockquote></details>

OK
___
*[tests/integration/common/mocks.c, line 145 at r8](https://reviewable.io/reviews/pmem/rpma/566#-MLC4fq17p_miDe4KHkS:-MLGr14t5L7siOTizrU7:b3fknlj) ([raw file](https://github.com/pmem/rpma/blob/4963fc9589de369af1e4ecf201d67c44aa9c95d3/tests/integration/common/mocks.c#L145)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ldorau I think your solution is valid as long as we assume the operation uses `offset == 0`.
But when `offset != 0` we have to use the technique proposed by @ewanglong.

@ewanglong do we use `offset != 0`?
</blockquote></details>

@janekmi what `offset` do you mean? `src_offset` is used as `== 0` and `!= 0`


<!-- Sent from Reviewable.io -->

2020-11-04 06:12 UTC, ldorau requested changes
> Reviewed 9 of 9 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[examples/common/hello.h, line 32 at r12](https://reviewable.io/reviews/pmem/rpma/566#-MLGrvKf16OYNAOqRNhp:-MLGrvKgCaC5Llta35Zc:bnggbdi) ([raw file](https://github.com/pmem/rpma/blob/112915b1c3c5735852f49e83f1dc0ee28d9cc299/examples/common/hello.h#L32)):*
> ```
> #endif
> ```

```
#endif /* EXAMPLES_HELLO_H */
```
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 131 at r5](https://reviewable.io/reviews/pmem/rpma/566#-MKj0u0WB3XcF3ntzJ1p:-MLGsIbsBymF5XHGJmkI:bno969i) ([raw file](https://github.com/pmem/rpma/blob/96c6fccb5ccb36a0254566bd270a02ab91374fb8/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi great explanation!

@ewanglong You can just debug and trace step by step the binary of this test (`tests/integration/example-04-write-to-persistent/example-04-write-to-persistent`)  using `cgdb` (to see the code) and check the order in which all functions are called in the server of the 04 example and configure all mocks exactly in the same order in your integration test.
</blockquote></details>

It is OK now.


<!-- Sent from Reviewable.io -->

2020-11-04 06:38 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong)

___
*[examples/common/hello.h, line 23 at r13](https://reviewable.io/reviews/pmem/rpma/566#-MLGxrim4CavRCcjm0dM:-MLGxrim4CavRCcjm0dN:b-6wi641) ([raw file](https://github.com/pmem/rpma/blob/0704e38a50a8d6ee894fd35590210e33ab90e7e6/examples/common/hello.h#L23)):*
> ```
> ONLY_INC_HELLO_DEF
> ```

I would use "`RPMA_INTEGRATION_TEST`" instead - it is more clear IMHO.
___
*[examples/common/hello.h, line 30 at r13](https://reviewable.io/reviews/pmem/rpma/566#-MLGy5id9000HYx8iEc1:-MLGy5id9000HYx8iEc2:bc6hrg9) ([raw file](https://github.com/pmem/rpma/blob/0704e38a50a8d6ee894fd35590210e33ab90e7e6/examples/common/hello.h#L30)):*
> ```
> #endif
> ```

```
#endif /* RPMA_INTEGRATION_TEST */
```
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 16 at r13](https://reviewable.io/reviews/pmem/rpma/566#-MLGyM2g3WfOxvpTaV4w:-MLGyM2g3WfOxvpTaV4x:b-h0a53p) ([raw file](https://github.com/pmem/rpma/blob/0704e38a50a8d6ee894fd35590210e33ab90e7e6/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L16)):*
> ```
> ONLY_INC_HELLO_DEF
> ```

`RPMA_INTEGRATION_TEST`
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 18 at r13](https://reviewable.io/reviews/pmem/rpma/566#-MLGyPRcBIaV4XjU_rLL:-MLGyPRcBIaV4XjU_rLM:b-d9qlln) ([raw file](https://github.com/pmem/rpma/blob/0704e38a50a8d6ee894fd35590210e33ab90e7e6/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L18)):*
> ```
> #undef ONLY_INC_HELLO_DEF
> ```

I think `RPMA_INTEGRATION_TEST` does not have to be undefined.


<!-- Sent from Reviewable.io -->

2020-11-04 06:45 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong)

___
*[examples/common/hello.h, line 30 at r13](https://reviewable.io/reviews/pmem/rpma/566#-MLH-48i5FkrdNKRuKqh:-MLH-48j2BLyxvyiajGj:b-219zx0) ([raw file](https://github.com/pmem/rpma/blob/0704e38a50a8d6ee894fd35590210e33ab90e7e6/examples/common/hello.h#L30)):*
> ```
> #define LANG_NUM	(sizeof(hello_str) / sizeof(hello_str[0]))
> #endif
> ```

Add one empty line in between please:

```
#define LANG_NUM	(sizeof(hello_str) / sizeof(hello_str[0]))

#endif /* RPMA_INTEGRATION_TEST */
```


<!-- Sent from Reviewable.io -->

2020-11-04 08:00 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-04 08:01 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/566#-MLExgFZ9cZm-TCew6sI:-MLHGaOfDq_M3HoSzzN-:bno969i) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please note all of the following examples are using `struct hello_t` structure:
- 03-read-to-persistent
- 04-write-to-persistent
- 05-flush-to-persistent
- 09-flush-to-persistent-GPSPM

So you should:
1. Move hello.h to the common directory
2. Use it in all of the examples to remove the redundancy (which is possible only because you have created the header)
</blockquote></details>

It is OK now.

---


<!-- Sent from Reviewable.io -->

2020-11-04 09:18 UTC, janekmi requested changes
> Reviewed 7 of 9 files at r12, 1 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/common/hello.h, line 31 at r14](https://reviewable.io/reviews/pmem/rpma/566#-MLHWKo-0ucoLtG4iaNF:-MLHWKo-0ucoLtG4iaNG:b8rc8tv) ([raw file](https://github.com/pmem/rpma/blob/da6ec9874f2390c4c5cae346945e488adeee5c96/examples/common/hello.h#L31)):*
> ```objc
> #define LANG_NUM	(sizeof(hello_str) / sizeof(hello_str[0]))
> 
> #endif /* RPMA_INTEGRATION_TEST */
> ```

Why do you need this ifdef anyway?


<!-- Sent from Reviewable.io -->

2020-11-04 09:43 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 30 at r14](https://reviewable.io/reviews/pmem/rpma/566#-MLH_O2f6Wbs9xjkX0eb:-MLH_O2f6Wbs9xjkX0ec:bq0qgbw) ([raw file](https://github.com/pmem/rpma/blob/da6ec9874f2390c4c5cae346945e488adeee5c96/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L30)):*
> ```C
> /* global mocks */
> static struct rdma_cm_id Cm_id;		/* mock CM ID */
> static struct ibv_qp Ibv_qp;		/* mock IBV QP */
> ```

I think these two should be moved to mocks.c for both this integration test and integration test 02.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 59 at r14](https://reviewable.io/reviews/pmem/rpma/566#-MLH__wv0WIkE8yzBnKP:-MLH__wv0WIkE8yzBnKQ:bq0zjkd) ([raw file](https://github.com/pmem/rpma/blob/da6ec9874f2390c4c5cae346945e488adeee5c96/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L59)):*
> ```C
> 
> 	return 0;
> }
> ```

The same with this function. We should not create redundancy.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 145 at r14](https://reviewable.io/reviews/pmem/rpma/566#-MLHapBl6YTusG4_VqDm:-MLHapBl6YTusG4_VqDn:bbzay18) ([raw file](https://github.com/pmem/rpma/blob/da6ec9874f2390c4c5cae346945e488adeee5c96/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L145)):*
> ```C
> 	/* allocate memory for the rpma_flush_apm_new */
> 	struct posix_memalign_args allocated = {0};
> 	will_return(__wrap_posix_memalign, &allocated);
> ```

allocated -> flush?
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 228 at r14](https://reviewable.io/reviews/pmem/rpma/566#-MLHc__t7n7gyDZ1FRpA:-MLHc__t7n7gyDZ1FRpB:b-e4qh2g) ([raw file](https://github.com/pmem/rpma/blob/da6ec9874f2390c4c5cae346945e488adeee5c96/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L228)):*
> ```C
> 	will_return(ibv_post_send_mock, MOCK_READ_SRC_OFFSET);
> 	will_return(ibv_post_send_mock, MOCK_OK);
> ```

I think you should move these lines:
```c
	/* configure mocks for rpma_conn_completion_wait() */
	expect_value(ibv_get_cq_event, channel, MOCK_COMP_CHANNEL);
	will_return(ibv_get_cq_event, MOCK_OK);
	expect_value(ibv_ack_cq_events, cq, MOCK_CQ);
	will_return(ibv_req_notify_cq_mock, MOCK_OK);

	/* configure mock for rpma_conn_completion_get() */
	struct ibv_wc wc = {0};
	wc.opcode = IBV_WC_RDMA_READ;
	expect_value(ibv_poll_cq_mock, cq, &Ibv_cq);
	will_return(ibv_poll_cq_mock, 1);
	will_return(ibv_poll_cq_mock, &wc);
```

here. So then the order of configuration will mirror completely what the examples does.


<!-- Sent from Reviewable.io -->

2020-11-04 12:47 UTC, janekmi requested changes
> Reviewed 3 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/integration/common/mocks.h, line 82 at r15](https://reviewable.io/reviews/pmem/rpma/566#-MLIHX7--4E6s22g7rwQ:-MLIHX7--4E6s22g7rwR:b-qvls8q) ([raw file](https://github.com/pmem/rpma/blob/565ad9c669a1df975f5d8e60d60d96d04901d818/tests/integration/common/mocks.h#L82)):*
> ```objc
> int __wrap_fprintf(FILE *__restrict __stream,
> 		const char *__restrict __format, ...);
> int	create_descriptor(void *desc,
> ```

Please replace the tab after `int` with a space (` `).


<!-- Sent from Reviewable.io -->

2020-11-04 12:48 UTC, janekmi reviewed
> Reviewed 1 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-04 12:56 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 207 at r15](https://reviewable.io/reviews/pmem/rpma/566#-MLIJ1EnBXrunXqN7saX:-MLIJ1EnBXrunXqN7saY:bgn58ap) ([raw file](https://github.com/pmem/rpma/blob/565ad9c669a1df975f5d8e60d60d96d04901d818/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L207)):*
> ```C
> 	expect_value(rdma_ack_cm_event, event, &s_event);
> 	will_return(rdma_ack_cm_event, MOCK_OK);
> ```

Please move these lines here:
```c
	expect_value(ibv_dereg_mr, mr, MOCK_MR);
	will_return(ibv_dereg_mr, MOCK_OK);
```
and these:
```
	expect_value(ibv_dereg_mr, mr, MOCK_MR_RAW);
	will_return(ibv_dereg_mr, MOCK_OK);
```

You can prepend these lines with a comment like:
```c
/* deregister the memory region */
```
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 214 at r15](https://reviewable.io/reviews/pmem/rpma/566#-MLIJwF78EBBl7EjjhyN:-MLIJwF78EBBl7EjjhyO:b-9nrj7i) ([raw file](https://github.com/pmem/rpma/blob/565ad9c669a1df975f5d8e60d60d96d04901d818/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L214)):*
> ```C
> 	/* configure mocks for rpma_conn_delete() */
> 	expect_value(ibv_dereg_mr, mr, MOCK_MR);
> 	will_return(ibv_dereg_mr, MOCK_OK);
> ```

These two lines:
```c
	expect_value(ibv_dereg_mr, mr, MOCK_MR_FLUSH);
	will_return(ibv_dereg_mr, MOCK_OK);
```
should go here.


<!-- Sent from Reviewable.io -->

2020-11-04 13:08 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[examples/common/hello.h, line 31 at r14](https://reviewable.io/reviews/pmem/rpma/566#-MLHWKo-0ucoLtG4iaNF:-MLILugIAHDl6u3NE-bt:brg35gh) ([raw file](https://github.com/pmem/rpma/blob/da6ec9874f2390c4c5cae346945e488adeee5c96/examples/common/hello.h#L31)):*
> it avoided the compiling warning as error, definition but  not used in integration test
@ewanglong 

Ok... Let's be it.


<!-- Sent from Reviewable.io -->

2020-11-04 13:24 UTC, ldorau approved these changes
All distros passed: https://github.com/ldorau/rpma/actions/runs/345137675

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566#-:-MLIQT327Le99gUD1oD4:b-uakmth)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-04 13:28 UTC, ldorau approved these changes
> Reviewed 4 of 4 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-04 15:49 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 252 at r16](https://reviewable.io/reviews/pmem/rpma/566#-MLIsEim14aefZCvCJAk:-MLIsEim14aefZCvCJAl:b-so7nlt) ([raw file](https://github.com/pmem/rpma/blob/e796c956a2f297cd504a740c64dd018a56cb8b67/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L252)):*
> ```C
> void
> test_server__success(void **unused)
> {
> ```

`__wrap_posix_memalign` should be the first mock
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 302 at r16](https://reviewable.io/reviews/pmem/rpma/566#-MLIsddU6_wqzV0FRCkA:-MLIsddU6_wqzV0FRCkB:b-jpay0i) ([raw file](https://github.com/pmem/rpma/blob/e796c956a2f297cd504a740c64dd018a56cb8b67/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L302)):*
This should be moved to the beginning.

> ```
> 	/* configure mocks for ibv_reg_mr() */
> 	struct posix_memalign_args allocated = {0};
> 	will_return(__wrap_posix_memalign, &allocated);
> ```
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 370 at r16](https://reviewable.io/reviews/pmem/rpma/566#-MLIvq_GE803TEDKQoJA:-MLIvq_GE803TEDKQoJB:bv9car9) ([raw file](https://github.com/pmem/rpma/blob/e796c956a2f297cd504a740c64dd018a56cb8b67/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L370)):*
> ```
> 	/* configure mocks for rpma_conn_disconnect() */
> 	expect_value(rdma_disconnect, id, &Cm_id);
> 	will_return(rdma_disconnect, MOCK_OK);
> ```

This should be moved below the `rdma_ack_cm_event` below
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 381 at r16](https://reviewable.io/reviews/pmem/rpma/566#-MLIw3fG4v1MlsJTs5As:-MLIw3fG4v1MlsJTs5At:bh4j8a5) ([raw file](https://github.com/pmem/rpma/blob/e796c956a2f297cd504a740c64dd018a56cb8b67/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L381)):*
> ```
> 	will_return(rdma_ack_cm_event, MOCK_OK);
>
> 	/* configure mocks for rpma_conn_delete() */
> ```

The `rdma_disconnect` mock should be moved here in between those two lines
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 398 at r16](https://reviewable.io/reviews/pmem/rpma/566#-MLIwRKS3txZfEfKIaru:-MLIwRKS3txZfEfKIarv:b9i9h4b) ([raw file](https://github.com/pmem/rpma/blob/e796c956a2f297cd504a740c64dd018a56cb8b67/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L398)):*
> ```
> expect_value(rdma_destroy_event_channel, channel, MOCK_EVCH);
> ```

This should be moved 3 lines above just after `rdma_destroy_id.`


<!-- Sent from Reviewable.io -->

2020-11-05 06:59 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-05 08:40 UTC, ldorau approved these changes
@ewanglong Please rebase and resolve the conflicts

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566#-:-MLMZ4016PfSKBjMnWPG:b-aqti6g)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-05 09:27 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 221 at r17](https://reviewable.io/reviews/pmem/rpma/566#-MLMhNvI0psdBZjeOoPX:-MLMhNvJBjHyQ1Yd-iVp:b8q6huf) ([raw file](https://github.com/pmem/rpma/blob/29fdd1067d940714733806377cd4f64f5534106f/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L221)):*
> ```C
> 	/* deregister the memory region: flush buffer */
> 	expect_value(ibv_dereg_mr, mr, MOCK_MR_FLUSH);
> 	will_return(ibv_dereg_mr, MOCK_OK);
> ```

These two steps happen inside `rpma_conn_delete()` which is below.
It is not a separate API step.

Please join these two lines to the section below.


<!-- Sent from Reviewable.io -->

2020-11-05 10:33 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-05 10:34 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566#-:-MLMyDqu7Ul1-rVuoF_i:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-05 10:36 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/566#-:-MLMyaZG0tK02UtpJQiv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-05 10:36 UTC, merged