rpma: limit size of registered memory to 1K
pmem/rpma pull request #574
Opened 2020-11-04 06:33 UTC by grom72

SodtRoCE and probably CLV does not accept huge memory registration
Memory region size limited to 1024 bytes

2020-11-04 06:50 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[examples/03-read-to-persistent/client.c, line 136 at r1](https://reviewable.io/reviews/pmem/rpma/574#-MLH04NmCI-eYlocrJT4:-MLH04Nn4bWbp3M5avQ4:b-4v5cpz) ([raw file](https://github.com/pmem/rpma/blob/c03b379c7ffcf18bc9a07f24076041e3428f538c/examples/03-read-to-persistent/client.c#L136)):*
> ```
> 		}
> 		mr_size = KILOBYTE;
> ```

Add one empty line in between please
___
*[examples/03-read-to-persistent/server.c, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/574#-MLH0B602SQib_wy9tdi:-MLH0B602SQib_wy9tdj:b-hnmz5v) ([raw file](https://github.com/pmem/rpma/blob/c03b379c7ffcf18bc9a07f24076041e3428f538c/examples/03-read-to-persistent/server.c#L104)):*
> ```
> 		}
> 		dst_size = KILOBYTE;
> ```

Add one empty line in between please
___
*[examples/03-read-to-persistent/server.c, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/574#-MLH0GLKCU0tcPlj7VON:-MLH0GLKCU0tcPlj7VOO:b-y3bg4y) ([raw file](https://github.com/pmem/rpma/blob/c03b379c7ffcf18bc9a07f24076041e3428f538c/examples/03-read-to-persistent/server.c#L116)):*
> ```
> 	}
> 	/* RPMA resources */
> ```

Do not remove the empty line in between please


<!-- Sent from Reviewable.io -->

2020-11-04 07:33 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 136 at r1](https://reviewable.io/reviews/pmem/rpma/574#-MLH04NmCI-eYlocrJT4:-MLHA9c2CzC_Qz35ti5M:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c03b379c7ffcf18bc9a07f24076041e3428f538c/examples/03-read-to-persistent/client.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		}
> 		mr_size = KILOBYTE;
> ```

Add one empty line in between please
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/574#-MLH0B602SQib_wy9tdi:-MLHAC8pADboX5WdMurr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c03b379c7ffcf18bc9a07f24076041e3428f538c/examples/03-read-to-persistent/server.c#L104)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		}
> 		dst_size = KILOBYTE;
> ```

Add one empty line in between please
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/574#-MLH0GLKCU0tcPlj7VON:-MLHAD0o-Q-2j6HQj7oY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c03b379c7ffcf18bc9a07f24076041e3428f538c/examples/03-read-to-persistent/server.c#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	}
> 	/* RPMA resources */
> ```

Do not remove the empty line in between please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-04 07:52 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2020-11-04 07:59 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-04 07:59 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574#-:-MLHGCgA40LUjHQEyQgp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-04 08:08 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/03-read-to-persistent/client.c, line 137 at r2](https://reviewable.io/reviews/pmem/rpma/574#-MLHGP128YJSU7aIMhLQ:-MLHGP128YJSU7aIMhLR:b3upimi) ([raw file](https://github.com/pmem/rpma/blob/9378989a20f85951bcf34b367416dfd7e988917d/examples/03-read-to-persistent/client.c#L137)):*
> ```C
> 		}
> 
> 		mr_size = KILOBYTE;
> ```

`struct hello_t` is bigger than a kilobyte. Don't to mention the header.
Your change has to do a little bit more to address these concerns.
___
*[examples/03-read-to-persistent/server.c, line 169 at r2](https://reviewable.io/reviews/pmem/rpma/574#-MLHHvFP3OqFCGKUKKGS:-MLHHvFP3OqFCGKUKKGT:b-crzvhn) ([raw file](https://github.com/pmem/rpma/blob/9378989a20f85951bcf34b367416dfd7e988917d/examples/03-read-to-persistent/server.c#L169)):*
> ```C
> 
> 	ret = rpma_read(conn, dst_mr, dst_offset, src_mr, src_data->data_offset,
> 			(size_t)KILOBYTE - src_data->data_offset,
> ```

Here you use the exact size of the data from `struct hello_t`.
To this day it was a kilobyte. Probably you have to decrease it.


<!-- Sent from Reviewable.io -->

2020-11-04 13:22 UTC, grom72 reviewed
Let's wait for one more test with proper system limits

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574#-:-MLIPsvT-RqtZy4VJAS6:bspui42)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2020-11-05 05:45 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/03-read-to-persistent/client.c, line 137 at r2](https://reviewable.io/reviews/pmem/rpma/574#-MLHGP128YJSU7aIMhLQ:-MLLvvTg026OPxPsNQVT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9378989a20f85951bcf34b367416dfd7e988917d/examples/03-read-to-persistent/client.c#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`struct hello_t` is bigger than a kilobyte. Don't to mention the header.
Your change has to do a little bit more to address these concerns.
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 169 at r2](https://reviewable.io/reviews/pmem/rpma/574#-MLHHvFP3OqFCGKUKKGS:-MLLw2nPCnTTbpNhh5sh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9378989a20f85951bcf34b367416dfd7e988917d/examples/03-read-to-persistent/server.c#L169)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Here you use the exact size of the data from `struct hello_t`.
To this day it was a kilobyte. Probably you have to decrease it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 05:45 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/574)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-05 06:34 UTC, closed without merging

2020-11-05 06:35 UTC, grom72 commented
No issue after setup proper limits in /etc/security/limits.conf