test: valgrind test for all examples
pmem/rpma pull request #581
Opened 2020-11-13 08:13 UTC by ewanglong

2020-11-13 16:20 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-valgrind-on-SoftRoCE.sh, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/581#-MM1Ohce5Z8-XPnKbs1E:-MM1OhcfDtO1QboBo6Bq:b-5aavk) ([raw file](https://github.com/pmem/rpma/blob/e3aa14870ee052e4576f64d314d6c1f4cfaa727f/examples/run-all-valgrind-on-SoftRoCE.sh#L104)):*
> ```Shell
> 
> 	serrno=$(grep "ERROR SUMMARY:" ${VLD_SLOG_FILE} | grep -Eoh "[0-9]+ errors" | awk '{print $1}')
> 	if [ $serrno -gt 0 -o $cerrno -gt 0 ]; then
> ```

```
$ ./examples/run-all-valgrind-on-SoftRoCE.sh ./build/examples/ 
Running examples for IP address 192.168.43.2 and port 8765

*** Running valgrind example: 01-connection
Starting the server ...
Starting the client ...
Error: example 01-connection FAILED!
./examples/run-all-valgrind-on-SoftRoCE.sh: line 104: [: too many arguments
```
___
*[examples/run-all-valgrind-on-SoftRoCE.sh, line 117 at r1](https://reviewable.io/reviews/pmem/rpma/581#-MM1P27kElyxHn6PaSEq:-MM1P27l8_-Y4_krW2l8:b-qkrluh) ([raw file](https://github.com/pmem/rpma/blob/e3aa14870ee052e4576f64d314d6c1f4cfaa727f/examples/run-all-valgrind-on-SoftRoCE.sh#L117)):*
> ```
> run-all-on-SoftRoCE.sh
> ```

`run-all-valgrind-on-SoftRoCE.sh`


<!-- Sent from Reviewable.io -->

2020-11-16 08:55 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-valgrind-on-SoftRoCE.sh, line 146 at r2](https://reviewable.io/reviews/pmem/rpma/581#-MMFE2HW653FW54nLi7J:-MMFE2HW653FW54nLi7K:b-1am00m) ([raw file](https://github.com/pmem/rpma/blob/7c10536fe8bd6acef0458eddbe8229eb50a70ec6/examples/run-all-valgrind-on-SoftRoCE.sh#L146)):*
> ```Shell
> fi
> 
> echo "All examples for valgrind check succeeded"
> ```

This script is not so much different compared to `run-all-on-SoftRoCE.sh`.
Can we merge these two into a single script?
I don't like the idea of maintaining two very very similar scripts in the repo.
___
*[examples/valgrind.supp, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/581#-MMFCE6lAxFAN1sHPNol:-MMFCE6lAxFAN1sHPNom:bh100ej) ([raw file](https://github.com/pmem/rpma/blob/7c10536fe8bd6acef0458eddbe8229eb50a70ec6/examples/valgrind.supp#L8)):*
> ```
>    fun:ucma_init_device.part.0
>    fun:ucma_init_device
> }
> ```

This one is related to the issue we have already discussed offline.
What about the others? Can you provide an introduction?
Maybe in the form of a comment in the suppression file itself?
___
*[examples/valgrind.supp, line 108 at r2](https://reviewable.io/reviews/pmem/rpma/581#-MMFCpXo7qgO3TurRTiE:-MMFCpXp9LedE9nO3MMX:bimkmeo) ([raw file](https://github.com/pmem/rpma/blob/7c10536fe8bd6acef0458eddbe8229eb50a70ec6/examples/valgrind.supp#L108)):*
> ```
>    fun:write
>    fun:rdma_connect
> }
> ```

I think the name of this file provides too little information. I would like to see something like: `memcheck-librdmacm.supp`.


<!-- Sent from Reviewable.io -->

2020-11-16 11:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-valgrind-on-SoftRoCE.sh, line 146 at r2](https://reviewable.io/reviews/pmem/rpma/581#-MMFE2HW653FW54nLi7J:-MMFmmK-C7rODK1x2WVr:b-eouekx) ([raw file](https://github.com/pmem/rpma/blob/7c10536fe8bd6acef0458eddbe8229eb50a70ec6/examples/run-all-valgrind-on-SoftRoCE.sh#L146)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This script is not so much different compared to `run-all-on-SoftRoCE.sh`.
Can we merge these two into a single script?
I don't like the idea of maintaining two very very similar scripts in the repo.
</blockquote></details>

@janekmi good point


<!-- Sent from Reviewable.io -->

2020-11-16 11:24 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-valgrind-on-SoftRoCE.sh, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/581#-MMFn2h_2MqSPbwjVzut:-MMFn2h_2MqSPbwjVzuu:bk0xxo1) ([raw file](https://github.com/pmem/rpma/blob/7c10536fe8bd6acef0458eddbe8229eb50a70ec6/examples/run-all-valgrind-on-SoftRoCE.sh#L142)):*
> ```Shell
> 	echo "$N_FAILED example(s) for valgrind check failed:"
> 	echo "please check valgrind log under ${BIN_DIR} !"
> 	echo -e "$FAILED"
> ```

Something is wrong here, each test is counted and listed twice:

```
18 example(s) for valgrind check failed:
please check valgrind log under ./build/examples/ !
01-connection
01-connection
02-read-to-volatile
02-read-to-volatile
03-read-to-persistent
03-read-to-persistent
04-write-to-persistent
04-write-to-persistent
05-flush-to-persistent
05-flush-to-persistent
06-multiple-connections
06-multiple-connections
07-atomic-write
07-atomic-write
08-messages-ping-pong
08-messages-ping-pong
09-flush-to-persistent-GPSPM
09-flush-to-persistent-GPSPM
```


<!-- Sent from Reviewable.io -->

2020-11-18 11:20 UTC, ldorau reviewed
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2020-11-18 12:31 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-on-SoftRoCE.sh, line 6 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQBb5Z31mdz9CoaDev:-MMQBb5Z31mdz9CoaDew:bxban2g) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L6)):*
> ```Shell
> 
> #
> # run-all-on-SoftRoCE.sh - run all examples w/i or w/o valgrind on SoftRoCE
> ```

TBH I don't like making short words even shorter. I recommend either:
- add `(optionally with valgrind)` at the end OR
- leave it as it was.
___
*[examples/run-all-on-SoftRoCE.sh, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQCZ4LAo99pIcaig_X:-MMQCZ4M3pg6vXN7XIDo:b-r8tjyl) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L25)):*
> ```Shell
> 	VLD_CLOG="--log-file=${VLD_CLOG_FILE}"
> 	VLD_SCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_SLOG}"
> 	VLD_CCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_CLOG}"
> ```

```shell
	VLD_CMD="valgrind --leak-check=yes"
	VLD_SUPP_PATH=$(dirname $0)
	VLD_SUPP="--suppressions=${VLD_SUPP_PATH}/vld-memcheck.supp"
        # prepare the server command
	VLD_SLOG_FILE="${BIN_DIR}/valgrind-server.log"
	VLD_SLOG="--log-file=${VLD_SLOG_FILE}"
	VLD_SCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_SLOG}"
        # prepare the client command
	VLD_CLOG_FILE="${BIN_DIR}/valgrind-client.log"
	VLD_CLOG="--log-file=${VLD_CLOG_FILE}"
	VLD_CCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_CLOG}"
```
___
*[examples/run-all-on-SoftRoCE.sh, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQDHa97hPj1TcS-nBU:-MMQDHa97hPj1TcS-nBV:b7tfpgy) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L25)):*
> ```Shell
> 	VLD_CLOG="--log-file=${VLD_CLOG_FILE}"
> 	VLD_SCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_SLOG}"
> 	VLD_CCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_CLOG}"
> ```

```shell
VLD_MSG=" (under Valgrind)"
```
___
*[examples/run-all-on-SoftRoCE.sh, line 57 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQDS3Z9EbcEO2OhDxs:-MMQDS3Z9EbcEO2OhDxt:bqdh58p) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L57)):*
> ```Shell
> 	else
> 		echo "*** Running example: $EXAMPLE"
> 	fi
> ```

You can get rid of this if.
```shell
echo "*** Running example: $EXAMPLE$VLD_MSG"
```
___
*[examples/run-all-on-SoftRoCE.sh, line 99 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQDn7L5tI9_uttfqYj:-MMQDn7L5tI9_uttfqYk:bm7tyaj) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L99)):*
> ```Shell
> 		cerrno=$(grep "ERROR SUMMARY:" ${VLD_CLOG_FILE} | grep -Eoh "[0-9]+ errors" | awk '{print $1}')
> 		if [ $cerrno -gt 0 ]; then
> 			echo Error: example $EXAMPLE client by valgrind FAILED!
> ```

I prefer having strings in quotes if you don't mind.
___
*[examples/run-all-on-SoftRoCE.sh, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQJBMJCAeBDfj2KmhN:-MMQEVEk8tF-_AQ07obc:b1rakhb) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L117)):*
> ```Shell
> 	if [ x"$VLD_SCMD" != x"" ]; then
> 		serrno=$(grep "ERROR SUMMARY:" ${VLD_SLOG_FILE} | grep -Eoh "[0-9]+ errors" | awk '{print $1}')
> 		if [ $serrno -gt 0 -o $cerrno -gt 0 ]; then
> ```

It may be misleading to state the server has failed whereas the one to blame was the client.
I think it may be more useful to count here only the server errors.
___
*[examples/run-all-on-SoftRoCE.sh, line 118 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQEg383FPeBd7rqbD0:-MMQEg383FPeBd7rqbD1:bosg0g2) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L118)):*
> ```Shell
> 		serrno=$(grep "ERROR SUMMARY:" ${VLD_SLOG_FILE} | grep -Eoh "[0-9]+ errors" | awk '{print $1}')
> 		if [ $serrno -gt 0 -o $cerrno -gt 0 ]; then
> 			echo Error: example $EXAMPLE server by valgrind FAILED!
> ```

.

* (a single full stop in a comment) - please apply here what I have suggested for another similar line in this review.
___
*[examples/run-all-on-SoftRoCE.sh, line 163 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQK_5q7RGNE__5Pm4f:-MMQK_5q7RGNE__5Pm4g:b-b3v45o) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L163)):*
> ```Shell
> 
> 	if [ $N_CFAILED -gt 0 ]; then
> 		echo "$N_CFAILED example(s) client by valgrind failed:"
> ```

I believe the more common is "under valgrind".
___
*[examples/run-all-on-SoftRoCE.sh, line 184 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQKPTw2jRVlmw48sDu:-MMQKPTx2gE3sZGo_r3z:b-xgyfux) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L184)):*
> ```Shell
> 		exit 1
> 	fi
> fi
> ```

```shell
N_FAILED=0
FAILED=""
N_SFAILED=0
SFAILED=""
N_CFAILED=0
CFAILED=""

for srv in $(find $BIN_DIR -name server | sort); do
	DIR=$(dirname $srv)
	run_example $DIR
done

if [ $N_FAILED -gt 0 ]; then
	echo "$N_FAILED example(s) failed:"
	echo -e "$FAILED"
	err=1
fi

if [ $N_SFAILED -gt 0 ]; then
	echo "$N_SFAILED example(s) server under valgrind failed:"
	echo -e "$SFAILED"
	err=1
fi

if [ $N_CFAILED -gt 0 ]; then
	echo "$N_CFAILED example(s) client under valgrind failed:"
	echo -e "$CFAILED"
	err=1
fi

if [ $err -eq 1 ]; then
	exit 1
fi
```
___
*[examples/valgrind.supp, line 108 at r2](https://reviewable.io/reviews/pmem/rpma/581#-MMFCpXo7qgO3TurRTiE:-MMQAurD8u-9h7hMrBQN:bxwhn5g) ([raw file](https://github.com/pmem/rpma/blob/7c10536fe8bd6acef0458eddbe8229eb50a70ec6/examples/valgrind.supp#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the name of this file provides too little information. I would like to see something like: `memcheck-librdmacm.supp`.
</blockquote></details>

What `vld` stands for?


<!-- Sent from Reviewable.io -->

2020-11-19 10:43 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 15 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-on-SoftRoCE.sh, line 6 at r4](https://reviewable.io/reviews/pmem/rpma/581#-MMUlD1d0y6PCJTSVKFr:-MMUlD1d0y6PCJTSVKFs:bvhrlas) ([raw file](https://github.com/pmem/rpma/blob/24457cf561407af9d494e005fde7919a086100ac/examples/run-all-on-SoftRoCE.sh#L6)):*
> ```
> run all examples optionally with valgrind
> ```

`run all examples on SoftRoCE (optionally under valgrind)`
___
*[examples/run-all-on-SoftRoCE.sh, line 8 at r4](https://reviewable.io/reviews/pmem/rpma/581#-MMV3GCPCSlpHxZu0URy:-MMV3GCQ1lKujVuEF187:b38salh) ([raw file](https://github.com/pmem/rpma/blob/24457cf561407af9d494e005fde7919a086100ac/examples/run-all-on-SoftRoCE.sh#L8)):*
> ```
> <--valgrind>
> ```

`[--valgrind]` because `<...>` means mandatory and `[...]` mean optional, but there is one issue with that...
___
*[examples/run-all-on-SoftRoCE.sh, line 8 at r4](https://reviewable.io/reviews/pmem/rpma/581#-MMV4s96BAVeTT1ujcHe:-MMV4s96BAVeTT1ujcHf:b5pp02o) ([raw file](https://github.com/pmem/rpma/blob/24457cf561407af9d494e005fde7919a086100ac/examples/run-all-on-SoftRoCE.sh#L8)):*
> ```Shell
> # run-all-on-SoftRoCE.sh - run all examples optionally with valgrind
> #
> # Usage: run-all-on-SoftRoCE.sh <binary-examples-directory> [IP_address] [port] <--valgrind>
> ```

This is this one additional issue:
Currently `[IP_address]` and `[port]` are also optional, so if you want to use `--valgrind`they become mandatory, so there will be three possible usages:
1) `$ run-all-on-SoftRoCE.sh binary-examples-directory`
2) `$ run-all-on-SoftRoCE.sh binary-examples-directory IP_address port`
3) `$ run-all-on-SoftRoCE.sh binary-examples-directory IP_address port --valgrind`
___
*[examples/run-all-on-SoftRoCE.sh, line 135 at r4](https://reviewable.io/reviews/pmem/rpma/581#-MMV5TVw8esAcWWQha44:-MMV5TVw8esAcWWQha45:butqmdy) ([raw file](https://github.com/pmem/rpma/blob/24457cf561407af9d494e005fde7919a086100ac/examples/run-all-on-SoftRoCE.sh#L135)):*
> ```Shell
> if [ "$BIN_DIR" == "" ]; then
> 	echo "Error: missing required argument"
> 	echo "Usage: run-all-on-SoftRoCE.sh <binary-examples-directory> [IP_address] [port]"
> ```

`[--valgrind]`


<!-- Sent from Reviewable.io -->

2020-11-20 16:09 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-11-23 08:13 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MMo9GKzCGpvzZcDDFJk:-MMo9GL--BbVgyTam2Qh:b-r00iwz) (no related file):*
Reminder: create issues for all Valgrind memcheck issues identified in other projects.

---


<!-- Sent from Reviewable.io -->

2020-12-19 22:09 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-on-SoftRoCE.sh, line 10 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx24rB5bPMtbGEHDf4:-MOx24rC0WoxVorxV-Rt:b-f2w8k6) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L10)):*
> ```Shell
> # Usage: run-all-on-SoftRoCE.sh <binary-examples-directory> [IP_address] [port] [--valgrind]
> #        run-all-on-SoftRoCE.sh <binary-examples-directory> [IP_address] [--valgrind]
> #        run-all-on-SoftRoCE.sh <binary-examples-directory> [--valgrind] [IP_address] [port]
> ```

What are the differences between these three invocation schemas?


<!-- Sent from Reviewable.io -->

2020-12-19 22:16 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-on-SoftRoCE.sh, line 190 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx3_VR5KdpRFNBJ0Q0:-MOx3_VR5KdpRFNBJ0Q1:b-bte5zc) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L190)):*
> ```Shell
> else
> 	N_FAILED=0
> 	FAILED=""
> ```

You need these variables in both cases (for Valgrind and non-Valgrind runs).
___
*[examples/run-all-on-SoftRoCE.sh, line 201 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx3fpEBs_Qrn4QBGSa:-MOx3fpEBs_Qrn4QBGSb:b-5dyn57) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L201)):*
> ```Shell
> 		exit 1
> 	fi
> fi
> ```

I do not see why you need a case for Valgrind and non-Valgrind run?


<!-- Sent from Reviewable.io -->

2020-12-19 22:39 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-12-19 22:39 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[examples/memcheck-librdmacm.supp, line 8 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx92uHDauoJ17ZZfLx:-MOx92uHDauoJ17ZZfLy:b-n4scbc) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L8)):*
> ```
>    fun:ucma_init_device.part.0
>    fun:ucma_init_device
> }
> ```

```
{
   The array of ports, once it is allocated, is not freed
   Memcheck:Leak
   match-leak-kinds: possible
   fun:malloc
   ...
   fun:ucma_init_device
}
```


<!-- Sent from Reviewable.io -->

2020-12-19 23:24 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong)

___
*[examples/memcheck-librdmacm.supp, line 11 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxBiy03rV_1Jb-Ycz7:-MOxBiy03rV_1Jb-Ycz8:bn0bco7) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L11)):*
> ```
> 
> {
>    rdma-cm-leak-002
> ```

The list of devices, once it is created, is not freed
___
*[examples/memcheck-librdmacm.supp, line 26 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxEf-ZDAUOb7IPoH77:-MOxEf-ZDAUOb7IPoH78:b-dr3kby) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L26)):*
> ```
>    fun:verbs_init_context
>    fun:_verbs_init_and_alloc_context
> }
> ```

```
{
   Verbs devices, once they are opened, are never closed (RXE variant)
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   ...
   fun:rxe_alloc_context
   fun:verbs_open_device
   fun:ucma_init_device
}
```
___
*[examples/memcheck-librdmacm.supp, line 34 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxFTYZAchCWg9o_02Z:-MOxFTYZAchCWg9o_02_:b-ejmrhi) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L34)):*
> ```
>    fun:calloc
>    fun:_verbs_init_and_alloc_context
> }
> ```

I think we can merge this with the previous one. There are two calloc calls but the cause is the same. `...` accommodates for both of the callocs.
___
*[examples/memcheck-librdmacm.supp, line 92 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxFuiH1SJgshCS8hiv:-MOxFuiH1SJgshCS8hiw:bhlv3zq) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L92)):*
> ```
>    fun:strdup
>    obj:*/lib*/libnl-*.so*
> }
> ```

I do not know what rdma-cm-leak-005 up to 011 are about. I can not find them in the log you have provided.
Can you elaborate or point me to the right log?
___
*[examples/memcheck-librdmacm.supp, line 100 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxHeqR1BvZfb_ikRSf:-MOxHeqS8jI8HvIj291C:brxx6a2) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L100)):*
> ```
>    fun:write
>    fun:rdma_accept
> }
> ```

This is kinda strange. In my opinion, the buffer is initialized simply because `CMA_INIT_CMD(&cmd, sizeof cmd, ACCEPT);` zero it out. The only option is, the uninitialized data is written into the `cmd` buffer is by copying uninitialized data into it. Do we have any option for verbose output which will point out exactly the part of the buffer which is supposedly uninitialized?
___
*[examples/memcheck-librdmacm.supp, line 108 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxJLVv308f27uJ10SK:-MOxJLVv308f27uJ10SL:b-kx8amh) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L108)):*
> ```
>    fun:write
>    fun:rdma_connect
> }
> ```

The same here. `CMA_INIT_CMD` is in place. What is going on?


<!-- Sent from Reviewable.io -->

2021-01-04 02:46 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 10 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx24rB5bPMtbGEHDf4:-MQAFxQ-BaKRDFlTnqGy:bimgrqy) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What are the differences between these three invocation schemas?
</blockquote></details>

They adapted to following optional commands with sequence.
run-all-on-SoftRoCE.sh binary-examples-directory IP_address
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory IP_address --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory --valgrind IP_address
run-all-on-SoftRoCE.sh binary-examples-directory --valgrind IP_address port


<!-- Sent from Reviewable.io -->

2021-01-04 03:21 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 190 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx3_VR5KdpRFNBJ0Q0:-MQAO30J8W2GuYjNddqp:bkbmd19) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You need these variables in both cases (for Valgrind and non-Valgrind runs).
</blockquote></details>

For Valgrind case, N_FAILED is split into S(erver)FAILED and C(lient)FAILED. Do we need add them up, e.g. as below?
	N_FAILED=$(($N_SFAILED + N_CFAILED))
	if [ $N_FAILED -gt 0 ]; then
		echo "$N_FAILED example(s) failed:"
		echo -e "$FAILED"
		exit 1
	fi


<!-- Sent from Reviewable.io -->

2021-01-04 03:39 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 184 at r3](https://reviewable.io/reviews/pmem/rpma/581#-MMQKPTw2jRVlmw48sDu:-MQATR_v3gr02pG7an4o:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/9aa54633cf8492c3e140f984dac5c79c2dfd0a4f/examples/run-all-on-SoftRoCE.sh#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```shell
N_FAILED=0
FAILED=""
N_SFAILED=0
SFAILED=""
N_CFAILED=0
CFAILED=""

for srv in $(find $BIN_DIR -name server | sort); do
	DIR=$(dirname $srv)
	run_example $DIR
done

if [ $N_FAILED -gt 0 ]; then
	echo "$N_FAILED example(s) failed:"
	echo -e "$FAILED"
	err=1
fi

if [ $N_SFAILED -gt 0 ]; then
	echo "$N_SFAILED example(s) server under valgrind failed:"
	echo -e "$SFAILED"
	err=1
fi

if [ $N_CFAILED -gt 0 ]; then
	echo "$N_CFAILED example(s) client under valgrind failed:"
	echo -e "$CFAILED"
	err=1
fi

if [ $err -eq 1 ]; then
	exit 1
fi
```
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-01-04 06:27 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 92 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxFuiH1SJgshCS8hiv:-MQB3gQN1f2b7jYjvtQ_:b-h491uz) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not know what rdma-cm-leak-005 up to 011 are about. I can not find them in the log you have provided.
Can you elaborate or point me to the right log?
</blockquote></details>

Hi, as for those *.so* in bottom stack,  they are targeting release environment without functional symbols. So for rdma-cm-leak-001 ~  rdma-cm-leak-004, they are targeting debug environments.


<!-- Sent from Reviewable.io -->

2021-01-04 08:04 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 100 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxHeqR1BvZfb_ikRSf:-MQBPrD-9T6JXQQPDYsj:b-nxx7ji) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is kinda strange. In my opinion, the buffer is initialized simply because `CMA_INIT_CMD(&cmd, sizeof cmd, ACCEPT);` zero it out. The only option is, the uninitialized data is written into the `cmd` buffer is by copying uninitialized data into it. Do we have any option for verbose output which will point out exactly the part of the buffer which is supposedly uninitialized?
</blockquote></details>

Only full stack can be captured. Seems the  copied conn_param is uninitialized but not the cmd itself.
==736827== Syscall param write(buf) points to uninitialised byte(s)
==736827==    at 0x49625E7: write (in /usr/lib64/libc-2.31.so)
==736827==    by 0x4A6223C: rdma_accept (cma.c:1943)
==736827==    by 0x484CD31: rpma_conn_req_accept (conn_req.c:134)
==736827==    by 0x484D8EB: rpma_conn_req_connect (conn_req.c:427)
==736827==    by 0x40172F: server_accept_connection (common-conn.c:122)
==736827==    by 0x40149D: main (server.c:104)
==736827==  Address 0x1ffefffb88 is on thread 1's stack
==736827==  in frame #1, created by rdma_accept (cma.c:1901)


<!-- Sent from Reviewable.io -->

2021-01-04 08:06 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 108 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxJLVv308f27uJ10SK:-MQBQa0E50ZBpi_YjvNd:b-6cjlbq) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The same here. `CMA_INIT_CMD` is in place. What is going on?
</blockquote></details>

For write called by rdma_connect,
==738275== Syscall param write(buf) points to uninitialised byte(s)
==738275==    at 0x49625E7: write (in /usr/lib64/libc-2.31.so)
==738275==    by 0x4A61FEA: rdma_connect (cma.c:1812)
==738275==    by 0x484CF6F: rpma_conn_req_connect_active (conn_req.c:195)
==738275==    by 0x484D907: rpma_conn_req_connect (conn_req.c:429)
==738275==    by 0x40171E: client_connect (common-conn.c:77)
==738275==    by 0x401544: main (client.c:177)
==738275==  Address 0x1ffefffb63 is on thread 1's stack
==738275==  in frame #1, created by rdma_connect (cma.c:1779)


<!-- Sent from Reviewable.io -->

2021-01-04 08:49 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/memcheck-librdmacm.supp, line 34 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxFTYZAchCWg9o_02Z:-MQB_W0N6dJQYjyYAyLu:b-9dzzme) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can merge this with the previous one. There are two calloc calls but the cause is the same. `...` accommodates for both of the callocs.
</blockquote></details>

But the calloc is in different upmost call stack. How to merge it?


<!-- Sent from Reviewable.io -->

2021-01-04 14:28 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2021-01-04 16:08 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/memcheck-librdmacm.supp, line 8 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx92uHDauoJ17ZZfLx:-MQD4o2k5QhSsb5yO3eh:b-amvlch) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
{
   The array of ports, once it is allocated, is not freed
   Memcheck:Leak
   match-leak-kinds: possible
   fun:malloc
   ...
   fun:ucma_init_device
}
```
</blockquote></details>

I still recommend replacing `fun:ucma_init_device.part.0` with `...`.
___
*[examples/memcheck-librdmacm.supp, line 26 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxEf-ZDAUOb7IPoH77:-MQD55YI3CrQV_6Hatw1:bljfc6a) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
{
   Verbs devices, once they are opened, are never closed (RXE variant)
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   ...
   fun:rxe_alloc_context
   fun:verbs_open_device
   fun:ucma_init_device
}
```
</blockquote></details>

Please update the call stack also.
___
*[examples/memcheck-librdmacm.supp, line 34 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxFTYZAchCWg9o_02Z:-MQD6_c43ItV9tpxORf8:bfo8xre) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L34)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

But the calloc is in different upmost call stack. How to merge it?
</blockquote></details>

If I understand correctly if you will suppress as follows:
```
fun: calloc
...
fun: whatever
```

It should suppress both this:
```
fun: calloc
fun: whatever
```

and

```
fun: calloc
fun: xyz
fun: whatever
```
___
*[examples/memcheck-librdmacm.supp, line 92 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxFuiH1SJgshCS8hiv:-MQD7NRm63Vikw6FZZ8Q:b-5wow40) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L92)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Hi, as for those *.so* in bottom stack,  they are targeting release environment without functional symbols. So for rdma-cm-leak-001 ~  rdma-cm-leak-004, they are targeting debug environments.
</blockquote></details>

It seems too general to do anything useful. I think we should drop the release environments.


<!-- Sent from Reviewable.io -->

2021-01-04 16:27 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 10 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx24rB5bPMtbGEHDf4:-MQDCguu4hXJIPZuQqGZ:bdw1lr6) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L10)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

They adapted to following optional commands with sequence.
run-all-on-SoftRoCE.sh binary-examples-directory IP_address
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory IP_address --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory --valgrind IP_address
run-all-on-SoftRoCE.sh binary-examples-directory --valgrind IP_address port
</blockquote></details>

These:

```
run-all-on-SoftRoCE.sh binary-examples-directory IP_address
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory IP_address --valgrind
```
look like simply `port` and `--valgrind` are optional. We can do the same by e.g.:

```
run-all-on-SoftRoCE.sh binary-examples-directory IP_address [port] [--valgrind]
```
assuming `option` is required whereas `[option]` is optional.
___
*[examples/memcheck-librdmacm.supp, line 100 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxHeqR1BvZfb_ikRSf:-MQDCDO32lCVWXNryFhq:b7cc1hh) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L100)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Only full stack can be captured. Seems the  copied conn_param is uninitialized but not the cmd itself.
==736827== Syscall param write(buf) points to uninitialised byte(s)
==736827==    at 0x49625E7: write (in /usr/lib64/libc-2.31.so)
==736827==    by 0x4A6223C: rdma_accept (cma.c:1943)
==736827==    by 0x484CD31: rpma_conn_req_accept (conn_req.c:134)
==736827==    by 0x484D8EB: rpma_conn_req_connect (conn_req.c:427)
==736827==    by 0x40172F: server_accept_connection (common-conn.c:122)
==736827==    by 0x40149D: main (server.c:104)
==736827==  Address 0x1ffefffb88 is on thread 1's stack
==736827==  in frame #1, created by rdma_accept (cma.c:1901)
</blockquote></details>

As far as I'ma aware, `conn_param` is initialized. It is the same structure we use in the RPMA or it is somehow extended? Maybe it is not initialized by the rdma-core?


<!-- Sent from Reviewable.io -->

2021-01-04 16:28 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 10 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx24rB5bPMtbGEHDf4:-MQDDYoX6kN6rA1N28Rp:bt4b1if) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These:

```
run-all-on-SoftRoCE.sh binary-examples-directory IP_address
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port
run-all-on-SoftRoCE.sh binary-examples-directory IP_address port --valgrind
run-all-on-SoftRoCE.sh binary-examples-directory IP_address --valgrind
```
look like simply `port` and `--valgrind` are optional. We can do the same by e.g.:

```
run-all-on-SoftRoCE.sh binary-examples-directory IP_address [port] [--valgrind]
```
assuming `option` is required whereas `[option]` is optional.
</blockquote></details>

What is the difference between:
1. run-all-on-SoftRoCE.sh binary-examples-directory IP_address --valgrind
2. run-all-on-SoftRoCE.sh binary-examples-directory --valgrind IP_address

?


<!-- Sent from Reviewable.io -->

2021-01-04 16:30 UTC, janekmi reviewed
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-05 05:46 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 10 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx24rB5bPMtbGEHDf4:-MQG44DND_IYBXmClvFf:b-5kd1p4) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What is the difference between:
1. run-all-on-SoftRoCE.sh binary-examples-directory IP_address --valgrind
2. run-all-on-SoftRoCE.sh binary-examples-directory --valgrind IP_address

?
</blockquote></details>

They are different command arguments sequence.


<!-- Sent from Reviewable.io -->

2021-01-05 14:29 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 10 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOx24rB5bPMtbGEHDf4:-MQHwNhA1IfeysS0QulI:b-8y3i6m) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/run-all-on-SoftRoCE.sh#L10)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

They are different command arguments sequence.
</blockquote></details>

We do not have to be SO robust. We can agree to a single fixed order of arguments. ;-)
I think the `--valgrind` can be the last argument.
___
*[examples/memcheck-librdmacm.supp, line 26 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxEf-ZDAUOb7IPoH77:-MQHuOOp0yq5yfYu14M7:br84j5d) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please update the call stack also.
</blockquote></details>

Please take a look at my proposition one more time. :-)
___
*[examples/memcheck-librdmacm.supp, line 34 at r7](https://reviewable.io/reviews/pmem/rpma/581#-MQHuuO47D9a_GrI-2xd:-MQHuuO47D9a_GrI-2xe:bnlbf12) ([raw file](https://github.com/pmem/rpma/blob/e6df58405ff2f729595307137f6078301fd73e85/examples/memcheck-librdmacm.supp#L34)):*
> ```
>    fun:calloc
>    obj:*/lib*/libnl-*.so*
> }
> ```

Do you have a call stack for this?
___
*[examples/memcheck-librdmacm.supp, line 43 at r7](https://reviewable.io/reviews/pmem/rpma/581#-MQHvmDzEl9AyX8I8xpI:-MQHujeE4ZeWC5VnLICg:bnlbf12) ([raw file](https://github.com/pmem/rpma/blob/e6df58405ff2f729595307137f6078301fd73e85/examples/memcheck-librdmacm.supp#L43)):*
> ```
>    fun:strdup
>    obj:*/lib*/libnl-*.so*
> }
> ```

Do you have a call stack for this?


<!-- Sent from Reviewable.io -->

2021-01-06 02:14 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 34 at r7](https://reviewable.io/reviews/pmem/rpma/581#-MQHuuO47D9a_GrI-2xd:-MQKT5bACdF2b3V5xT-n:b3c7xbh) ([raw file](https://github.com/pmem/rpma/blob/e6df58405ff2f729595307137f6078301fd73e85/examples/memcheck-librdmacm.supp#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you have a call stack for this?
</blockquote></details>

Two call stacks are attached as below.
==1088029== 32 bytes in 1 blocks are possibly lost in loss record 19 of 46
==1088029==    at 0x483C975: calloc (vg_replace_malloc.c:762)
==1088029==    by 0x4D1D3C5: __trans_list_add (in /usr/lib64/libnl-3.so.200.26.0)
==1088029==    by 0x4C9E13C: ??? (in /usr/lib64/libnl-route-3.so.200.26.0)
==1088029==    by 0x40117E1: call_init.part.0 (in /usr/lib64/ld-2.31.so)
==1088029==    by 0x40118F0: _dl_init (in /usr/lib64/ld-2.31.so)
==1088029==    by 0x4002149: ??? (in /usr/lib64/ld-2.31.so)
==1088029==    by 0x2: ???
==1088029==    by 0x1FFF00021E: ???
==1088029==    by 0x1FFF00024D: ???
==1088029==    by 0x1FFF00025B: ???

==1090343== 5 bytes in 1 blocks are possibly lost in loss record 3 of 46
==1090343==    at 0x483A755: malloc (vg_replace_malloc.c:309)
==1090343==    by 0x4AB534E: strdup (in /usr/lib64/libc-2.31.so)
==1090343==    by 0x4D1D3D8: __trans_list_add (in /usr/lib64/libnl-3.so.200.26.0)
==1090343==    by 0x4C9E184: ??? (in /usr/lib64/libnl-route-3.so.200.26.0)
==1090343==    by 0x40117E1: call_init.part.0 (in /usr/lib64/ld-2.31.so)
==1090343==    by 0x40118F0: _dl_init (in /usr/lib64/ld-2.31.so)
==1090343==    by 0x4002149: ??? (in /usr/lib64/ld-2.31.so)
==1090343==    by 0x2: ???
==1090343==    by 0x1FFF00021E: ???
==1090343==    by 0x1FFF00024D: ???
==1090343==    by 0x1FFF00025B: ???


<!-- Sent from Reviewable.io -->

2021-01-06 02:21 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 26 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxEf-ZDAUOb7IPoH77:-MQKUe09-002YCz7APEc:b326wk) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please take a look at my proposition one more time. :-)
</blockquote></details>

Where this stask come from? In my side, there is no such report about the functions like rxe_alloc_context.


<!-- Sent from Reviewable.io -->

2021-01-08 09:06 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-08 09:11 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 26 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxEf-ZDAUOb7IPoH77:-MQWFpjI0bcQ9SdaOmOP:b-kdztu1) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L26)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Where this stask come from? In my side, there is no such report about the functions like rxe_alloc_context.
</blockquote></details>

```
==910351== 560 bytes in 1 blocks are possibly lost in loss record 5 of 14
==910351==    at 0x483C975: calloc (vg_replace_malloc.c:762)
==910351==    by 0x4A4A539: ??? (in /usr/lib64/libibverbs.so.1.9.30.0)
==910351==    by 0x4A4A6AE: _verbs_init_and_alloc_context (in /usr/lib64/libibverbs.so.1.9.30.0)
==910351==    by 0x485F407: rxe_alloc_context (rxe.c:873)
==910351==    by 0x4A4A72A: verbs_open_device (in /usr/lib64/libibverbs.so.1.9.30.0)
==910351==    by 0x4A60C9C: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A6149F: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A61638: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A63E38: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A645F2: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A64715: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x484E570: rpma_info_resolve_addr (info.c:113)
```


<!-- Sent from Reviewable.io -->

2021-01-08 11:28 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 34 at r7](https://reviewable.io/reviews/pmem/rpma/581#-MQHuuO47D9a_GrI-2xd:-MQWjw3ZA9dAVBJsm-Ey:b-rw9b0x) ([raw file](https://github.com/pmem/rpma/blob/e6df58405ff2f729595307137f6078301fd73e85/examples/memcheck-librdmacm.supp#L34)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Two call stacks are attached as below.
==1088029== 32 bytes in 1 blocks are possibly lost in loss record 19 of 46
==1088029==    at 0x483C975: calloc (vg_replace_malloc.c:762)
==1088029==    by 0x4D1D3C5: __trans_list_add (in /usr/lib64/libnl-3.so.200.26.0)
==1088029==    by 0x4C9E13C: ??? (in /usr/lib64/libnl-route-3.so.200.26.0)
==1088029==    by 0x40117E1: call_init.part.0 (in /usr/lib64/ld-2.31.so)
==1088029==    by 0x40118F0: _dl_init (in /usr/lib64/ld-2.31.so)
==1088029==    by 0x4002149: ??? (in /usr/lib64/ld-2.31.so)
==1088029==    by 0x2: ???
==1088029==    by 0x1FFF00021E: ???
==1088029==    by 0x1FFF00024D: ???
==1088029==    by 0x1FFF00025B: ???

==1090343== 5 bytes in 1 blocks are possibly lost in loss record 3 of 46
==1090343==    at 0x483A755: malloc (vg_replace_malloc.c:309)
==1090343==    by 0x4AB534E: strdup (in /usr/lib64/libc-2.31.so)
==1090343==    by 0x4D1D3D8: __trans_list_add (in /usr/lib64/libnl-3.so.200.26.0)
==1090343==    by 0x4C9E184: ??? (in /usr/lib64/libnl-route-3.so.200.26.0)
==1090343==    by 0x40117E1: call_init.part.0 (in /usr/lib64/ld-2.31.so)
==1090343==    by 0x40118F0: _dl_init (in /usr/lib64/ld-2.31.so)
==1090343==    by 0x4002149: ??? (in /usr/lib64/ld-2.31.so)
==1090343==    by 0x2: ???
==1090343==    by 0x1FFF00021E: ???
==1090343==    by 0x1FFF00024D: ???
==1090343==    by 0x1FFF00025B: ???



</blockquote></details>

1. Move this to a separate file: memcheck-libnl.supp
2. It is interesting this happens only for a single example (09)


<!-- Sent from Reviewable.io -->

2021-01-08 11:29 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 43 at r7](https://reviewable.io/reviews/pmem/rpma/581#-MQHvmDzEl9AyX8I8xpI:-MQWkPdjBRgdEfClHzyk:bn43j3r) ([raw file](https://github.com/pmem/rpma/blob/e6df58405ff2f729595307137f6078301fd73e85/examples/memcheck-librdmacm.supp#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you have a call stack for this?
</blockquote></details>

This also please move to memcheck-libnl.supp.


<!-- Sent from Reviewable.io -->

2021-01-08 11:31 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[examples/memcheck-librdmacm.supp, line 46 at r8](https://reviewable.io/reviews/pmem/rpma/581#-MQWkj8F9RXFVOFa67Y9:-MQWkj8F9RXFVOFa67YA:b-faqb6u) ([raw file](https://github.com/pmem/rpma/blob/a378adbd6f9000fc0950eb9544df092bd54aa4c0/examples/memcheck-librdmacm.supp#L46)):*
> ```
> 
> {
>    rdma-cm-param-001
> ```

XXX CMA_INIT_CMD() should initialize the whole buffer
___
*[examples/memcheck-librdmacm.supp, line 54 at r8](https://reviewable.io/reviews/pmem/rpma/581#-MQWkzHnB7k6MscwpemA:-MQWkzHnB7k6MscwpemB:b-faqb6u) ([raw file](https://github.com/pmem/rpma/blob/a378adbd6f9000fc0950eb9544df092bd54aa4c0/examples/memcheck-librdmacm.supp#L54)):*
> ```
> 
> {
>    rdma-cm-param-002
> ```

XXX CMA_INIT_CMD() should initialize the whole buffer


<!-- Sent from Reviewable.io -->

2021-01-11 07:28 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MQkL5rp2-qnhmWVOuX2:-MQkL5rp2-qnhmWVOuX3:b-9ikctm) (no related file):*
FAIL: commit message exceeds 72 chars per line (commit_len):

```
FAIL: commit message exceeds 72 chars per line (commit_len)
commit 9f356df0a15d39143ba188fba4377aa8d06fa15d
Author: Pawel Karczewski <pawel.karczewski@intel.com>
Date:   Tue Sep 15 10:44:40 2020 +0200
    common: Do not use valgiring by default
    
    As there is no valgrind tests yet so, to avoid cmake warning when valgrind is
    not found, this option should be off by default.
```

---


<!-- Sent from Reviewable.io -->

2021-01-11 07:34 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MQkL5rp2-qnhmWVOuX2:-MQkLj05CZWrZ7Yvxlt7:bo4864o) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

FAIL: commit message exceeds 72 chars per line (commit_len):

```
FAIL: commit message exceeds 72 chars per line (commit_len)
commit 9f356df0a15d39143ba188fba4377aa8d06fa15d
Author: Pawel Karczewski <pawel.karczewski@intel.com>
Date:   Tue Sep 15 10:44:40 2020 +0200
    common: Do not use valgiring by default
    
    As there is no valgrind tests yet so, to avoid cmake warning when valgrind is
    not found, this option should be off by default.
```
</blockquote></details>

Wow, it is a commit of another author, something is wrong here ... Sorry, this is my mistake.

---


<!-- Sent from Reviewable.io -->

2021-01-11 07:35 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MQkMXpiE3PbMBbl_N8u:-MQkMXpiE3PbMBbl_N8v:b-cxkqtq) (no related file):*
Please rebase this PR on top of the current master.

---


<!-- Sent from Reviewable.io -->

2021-01-11 08:59 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-on-SoftRoCE.sh, line 115 at r8](https://reviewable.io/reviews/pmem/rpma/581#-MQkeoRe6hHxgOsRQ490:-MQkeoRe6hHxgOsRQ491:byiza0c) ([raw file](https://github.com/pmem/rpma/blob/a378adbd6f9000fc0950eb9544df092bd54aa4c0/examples/run-all-on-SoftRoCE.sh#L115)):*
> ```
> cp ${
> ```

`mv ... `
___
*[examples/run-all-on-SoftRoCE.sh, line 134 at r8](https://reviewable.io/reviews/pmem/rpma/581#-MQkerPE8_B5hnrv9yb8:-MQkerPF-Yie8wihz5j8:b-uyq8ng) ([raw file](https://github.com/pmem/rpma/blob/a378adbd6f9000fc0950eb9544df092bd54aa4c0/examples/run-all-on-SoftRoCE.sh#L134)):*
> ```
> cp ${
> ```

`mv ...`


<!-- Sent from Reviewable.io -->

2021-01-11 15:13 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 26 at r5](https://reviewable.io/reviews/pmem/rpma/581#-MOxEf-ZDAUOb7IPoH77:-MQm-59MC9HFZ69esW_v:b-nszarn) ([raw file](https://github.com/pmem/rpma/blob/37e41137899f9acb3d2274160831adc61e4698b7/examples/memcheck-librdmacm.supp#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
==910351== 560 bytes in 1 blocks are possibly lost in loss record 5 of 14
==910351==    at 0x483C975: calloc (vg_replace_malloc.c:762)
==910351==    by 0x4A4A539: ??? (in /usr/lib64/libibverbs.so.1.9.30.0)
==910351==    by 0x4A4A6AE: _verbs_init_and_alloc_context (in /usr/lib64/libibverbs.so.1.9.30.0)
==910351==    by 0x485F407: rxe_alloc_context (rxe.c:873)
==910351==    by 0x4A4A72A: verbs_open_device (in /usr/lib64/libibverbs.so.1.9.30.0)
==910351==    by 0x4A60C9C: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A6149F: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A61638: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A63E38: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A645F2: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x4A64715: ??? (in /usr/lib64/librdmacm.so.1.2.30.0)
==910351==    by 0x484E570: rpma_info_resolve_addr (info.c:113)
```
</blockquote></details>

There is also thus leak as below.
==1175314== 608 bytes in 1 blocks are possibly lost in loss record 5 of 14
==1175314==    at 0x483C975: calloc (vg_replace_malloc.c:762)
==1175314==    by 0x4A49286: verbs_init_context (device.c:246)
==1175314==    by 0x4A493BA: _verbs_init_and_alloc_context (device.c:282)
==1175314==    by 0x485E407: rxe_alloc_context (rxe.c:874)
==1175314==    by 0x4A4943A: verbs_open_device (device.c:343)
==1175314==    by 0x4A5E419: ucma_init_device.part.0 (cma.c:437)
==1175314==    by 0x4A5EABF: ucma_init_device (cma.c:628)
==1175314==    by 0x4A5EABF: ucma_get_device (cma.c:631)
==1175314==    by 0x4A5EC18: ucma_query_addr (cma.c:888)
==1175314==    by 0x4A5ECCA: rdma_bind_addr2 (cma.c:1066)
==1175314==    by 0x484E65B: rpma_info_bind_addr (info.c:136)
==1175314==    by 0x48507A3: rpma_utils_get_ibv_context (rpma.c:53)
==1175314==    by 0x4012E0: main (server.c:45)

That's why I merged them into one suppression item as below.
{
   Verbs devices, once they are opened, are never closed (RXE variant)
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   ...
   fun:_verbs_init_and_alloc_context
}
___
*[examples/memcheck-librdmacm.supp, line 46 at r8](https://reviewable.io/reviews/pmem/rpma/581#-MQWkj8F9RXFVOFa67Y9:-MQkVw_VD5wWj9bZ6Jfi:b-4kvfzi) ([raw file](https://github.com/pmem/rpma/blob/a378adbd6f9000fc0950eb9544df092bd54aa4c0/examples/memcheck-librdmacm.supp#L46)):*
> XXX CMA_INIT_CMD() should initialize the whole buffer


<!-- Sent from Reviewable.io -->

2021-01-12 08:27 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 0 of 3 files reviewed, 11 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 26 at r9](https://reviewable.io/reviews/pmem/rpma/581#-MQph93-58PXLbQpwSDc:-MQph93-58PXLbQpwSDd:byikdy8) ([raw file](https://github.com/pmem/rpma/blob/f6bcd57e3976dfc69c05c889867acdbbba6d0235/examples/memcheck-librdmacm.supp#L26)):*
> ```
>    ...
>    fun:_verbs_init_and_alloc_context
>    fun:rxe_alloc_context
> ```

Got it. This line is missed in preivous commit.


<!-- Sent from Reviewable.io -->

2021-01-12 11:07 UTC, ldorau reviewed
> Reviewed 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 2 of 3 files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 26 at r9](https://reviewable.io/reviews/pmem/rpma/581#-MQph93-58PXLbQpwSDc:-MQq7Okc1I6sGH0GHryw:b4386ed) ([raw file](https://github.com/pmem/rpma/blob/f6bcd57e3976dfc69c05c889867acdbbba6d0235/examples/memcheck-librdmacm.supp#L26)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Got it. This line is missed in preivous commit.
</blockquote></details>

If you have added it, please resolve this issue.


<!-- Sent from Reviewable.io -->

2021-01-13 09:03 UTC, janekmi reviewed
> Reviewed 2 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-13 09:16 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MQkMXpiE3PbMBbl_N8u:-MQv0y3d1rHZ14rVeEiz:b2zm9xx) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase this PR on top of the current master.
</blockquote></details>

rebase done.

---


<!-- Sent from Reviewable.io -->

2021-01-13 10:20 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-13 10:56 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MQvNXR24MkaDUJiEejc:-MQvNXR37nxIPDqgMLxk:bifrvz) (no related file):*
All examples run under Valgrind fail for me for both rdma-core v30 and v33 (the current master).

---


<!-- Sent from Reviewable.io -->

2021-01-13 11:35 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[examples/memcheck-librdmacm.supp, line 28 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQvWOA1BEZ-5ryJ9GtW:-MQvWOA26jl1XztyLYsx:b-njvwj3) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/memcheck-librdmacm.supp#L28)):*
> ```
>    fun:rxe_alloc_context
>    fun:verbs_open_device
>    fun:ucma_init_device.part.0
> ```

`part.0` seems compiler-specific. I think it will be better to have here:

```
...
fun:ucma_init_device
```

instead of:

```
fun:ucma_init_device.part.0
```


<!-- Sent from Reviewable.io -->

2021-01-13 12:14 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[examples/run-all-on-SoftRoCE.sh, line 28 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQveedg1gcQ0XIdmcBP:-MQveedh1ALTGxY8SJXj:brm6l34) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/run-all-on-SoftRoCE.sh#L28)):*
> ```Shell
> fi
> 
> # valgrind test with suppression passed under rdma-core v33.0 debug libraries.
> ```

I think we will be better off with the message as I have proposed below.
Please remove so we won't have duplicated information.
___
*[examples/run-all-on-SoftRoCE.sh, line 42 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQvbrbj4MA9CFl5CwV0:-MQvbrbj4MA9CFl5CwV1:bsthpoj) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/run-all-on-SoftRoCE.sh#L42)):*
> ```Shell
> 	VLD_CLOG="--log-file=${VLD_CLOG_FILE}"
> 	VLD_CCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_CLOG}"
> 	VLD_MSG="(under Valgrind)"
> ```

```bash
echo "Running examples with Valgrind is tuned for rdma-core v33.0 debug build (EXPERIMENTAL)"
echo "It may fail for any other version and for the release build."
echo
```


<!-- Sent from Reviewable.io -->

2021-01-13 15:43 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-14 07:11 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-14 09:03 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 28 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQvWOA1BEZ-5ryJ9GtW:-MR-7d7xBFLhlhVP4Bha:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/memcheck-librdmacm.supp#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`part.0` seems compiler-specific. I think it will be better to have here:

```
...
fun:ucma_init_device
```

instead of:

```
fun:ucma_init_device.part.0
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 09:03 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 28 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQveedg1gcQ0XIdmcBP:-MR-7iul6fvtN7DgQpRr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/run-all-on-SoftRoCE.sh#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we will be better off with the message as I have proposed below.
Please remove so we won't have duplicated information.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 09:08 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MMo9GKzCGpvzZcDDFJk:-MR-8YJD3FaCpTMF2OdB:bjyw6p6) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Reminder: create issues for all Valgrind memcheck issues identified in other projects.
</blockquote></details>

can we merge it at first? Then tell the rdma-core community how to reproduce it based on our valgrind test.

---
___
*[examples/run-all-on-SoftRoCE.sh, line 42 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQvbrbj4MA9CFl5CwV0:-MR-7oDJ6gGRhKNk_lBh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/run-all-on-SoftRoCE.sh#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```bash
echo "Running examples with Valgrind is tuned for rdma-core v33.0 debug build (EXPERIMENTAL)"
echo "It may fail for any other version and for the release build."
echo
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-14 09:12 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 28 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQveedg1gcQ0XIdmcBP:-MR-9SaPA7vSIZjP0hQY:b-ldfbx6) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/run-all-on-SoftRoCE.sh#L28)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@ewanglong I think @janekmi meant to remove this comment "so we won't have duplicated information" - as he has written above.


<!-- Sent from Reviewable.io -->

2021-01-14 09:32 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 28 at r10](https://reviewable.io/reviews/pmem/rpma/581#-MQveedg1gcQ0XIdmcBP:-MR-EK1s1hMtXZnnp1bj:b-r390eg) ([raw file](https://github.com/pmem/rpma/blob/93282d1509a5bd92765dfa4011504dcd95c5d231/examples/run-all-on-SoftRoCE.sh#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@ewanglong I think @janekmi meant to remove this comment "so we won't have duplicated information" - as he has written above.
</blockquote></details>

okay. removed it.


<!-- Sent from Reviewable.io -->

2021-01-14 09:41 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-14 11:57 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/581#-MQvNXR24MkaDUJiEejc:-MR-ixgC7e3cTh_Tvgc6:b-nejepo) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All examples run under Valgrind fail for me for both rdma-core v30 and v33 (the current master).
</blockquote></details>

It appears that suppression files are very OS-and-OS-version-and-rdma-core-version-specific ;-)
On Fedora 31 with rdma-core v33 there is only 1 issue found :

```
==95641== 88 bytes in 1 blocks are possibly lost in loss record 18 of 27
==95641==    at 0x483BB1A: calloc (vg_replace_malloc.c:760)
==95641==    by 0x4A722F9: insert_cma_dev (cma.c:269)
==95641==    by 0x4A72591: sync_devices_list (cma.c:334)
==95641==    by 0x4A728FC: ucma_init (cma.c:406)
==95641==    by 0x4A714CF: rdma_getaddrinfo (addrinfo.c:247)
==95641==    by 0x484E3D7: rpma_info_new (info.c:53)
==95641==    by 0x4850719: rpma_utils_get_ibv_context (rpma.c:40)
==95641==    by 0x4012BD: main (client.c:45)
```

---
___
*[examples/run-all-on-SoftRoCE.sh, line 42 at r12](https://reviewable.io/reviews/pmem/rpma/581#-MR-ijzeCMkw6N9rlglx:-MR-ijzeCMkw6N9rlgly:b-glfzqi) ([raw file](https://github.com/pmem/rpma/blob/ae46362208a005ccf33d5f659b6cebf28e202945/examples/run-all-on-SoftRoCE.sh#L42)):*
> ```
> for rdma-core v33.0 debug build
> ```

`... for Fedora 32 and rdma-core v33.0 debug build ...`
___
*[examples/run-all-on-SoftRoCE.sh, line 43 at r12](https://reviewable.io/reviews/pmem/rpma/581#-MR-k3Un08UXx8-MdE6O:-MR-k3Un08UXx8-MdE6P:b-q0g2fv) ([raw file](https://github.com/pmem/rpma/blob/ae46362208a005ccf33d5f659b6cebf28e202945/examples/run-all-on-SoftRoCE.sh#L43)):*
> ```
> for any other version 
> ```

`... for any other OS, OS version, rdma-core version and for  ...`


<!-- Sent from Reviewable.io -->

2021-01-14 12:03 UTC, janekmi approved these changes
> Reviewed 1 of 2 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-15 02:11 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 42 at r12](https://reviewable.io/reviews/pmem/rpma/581#-MR-ijzeCMkw6N9rlglx:-MR2nwjy828uTJ2KmCbS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae46362208a005ccf33d5f659b6cebf28e202945/examples/run-all-on-SoftRoCE.sh#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> for rdma-core v33.0 debug build
> ```

`... for Fedora 32 and rdma-core v33.0 debug build ...`
</blockquote></details>

Done.
___
*[examples/run-all-on-SoftRoCE.sh, line 43 at r12](https://reviewable.io/reviews/pmem/rpma/581#-MR-k3Un08UXx8-MdE6O:-MR2nvjC9-GzBMN22-To:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae46362208a005ccf33d5f659b6cebf28e202945/examples/run-all-on-SoftRoCE.sh#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> for any other version 
> ```

`... for any other OS, OS version, rdma-core version and for  ...`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-15 07:00 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-15 07:00 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581#-:-MR3qAWVALxbwMYZhIXd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-15 07:02 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/581#-:-MR3qW6CDmJgkg0WQAYu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-15 07:02 UTC, merged