rpma: add rpma_conn_req_get_private_data() to public library API (WIP)
pmem/rpma pull request #646
Opened 2020-12-09 10:33 UTC by grom72

Currently, connection private data are not accessible before
the connection is established.
With this new API call server side (ep_listen) is able to pre-setup
connection using context delivered with incoming connection private data.

2020-12-09 12:13 UTC, ldorau reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72)

___
*[src/librpma.map, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6Nu6w01_EyK9F8bjH:-MO6Nu6w01_EyK9F8bjI:b-6b87ik) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/librpma.map#L34)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		rpma_conn_req_delete;
> 		rpma_conn_req_new;
> 		rpma_conn_req_recv;
> 		rpma_conn_req_get_private_data;
> ```
</details>


Wrong order
___
*[src/include/librpma.h, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6O14S32sOPxOd72FE:-MO6O14S32sOPxOd72FF:b-tpk362) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L332)):*
> ```
>  * - rpma_conn_req_delete()
>  * - rpma_conn_req_new()
>  * - rpma_conn_req_get_private_data
> ```

1) Wrong order
2) `rpma_conn_req_get_private_data()`
___
*[src/include/librpma.h, line 1965 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6OcTUDSKxUYL7nsG_:-MO6OcTVAd52n3h3ZtNy:b-4lvslo) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1965)):*
> ```
> In rpma
> ```

No `In` I suppose
___
*[src/include/librpma.h, line 1965 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6Oh1C-tqEYwDn0Igh:-MO6Oh1C-tqEYwDn0Igi:b-i7mf52) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1965)):*
> ```
> to connection
> ```

to the connection's
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6OvtR8Oly6USRIZIs:-MO6OvtR8Oly6USRIZIt:bm1izdm) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
> ```
> to server side configuration 
> ```

to the server's side configuration 
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6P-B5BakOf-fgpCOi:-MO6P-B5BakOf-fgpCOj:b-a8se7p) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
> ```
>  priory to 
> ```

What priory ? :-D
Maybe `prior to ` ? ;-)
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6PS-J8bBvm8qnT8HU:-MO6PS-J8bBvm8qnT8HV:b-4ivvco) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
> ```
> connection accept.
> ```

connection is accepted.
___
*[src/include/librpma.h, line 1979 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6PoF_7Hlbyou6Nb0U:-MO6PoF_7Hlbyou6Nb0V:b-hnsu6k) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1979)):*
> ```
> req_ptr
> ```

`req`


<!-- Sent from Reviewable.io -->

2020-12-09 13:28 UTC, grom72 reviewed
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: 2 of 4 files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6O14S32sOPxOd72FE:-MO6fdz1DZoRnhX8YWnJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L332)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - rpma_conn_req_delete()
>  * - rpma_conn_req_new()
>  * - rpma_conn_req_get_private_data
> ```

1) Wrong order
2) `rpma_conn_req_get_private_data()`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1965 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6OcTUDSKxUYL7nsG_:-MO6ff6v6BdYmSf4Nam8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1965)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> In rpma
> ```

No `In` I suppose
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1965 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6Oh1C-tqEYwDn0Igh:-MO6fgLV0F_tdfVN5oFP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1965)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to connection
> ```

to the connection's
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6OvtR8Oly6USRIZIs:-MO6fiAx7n6LnUJ4J8Hj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to server side configuration 
> ```

to the server's side configuration 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6P-B5BakOf-fgpCOi:-MO6ftUbEuyeon8Qbb4y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  priory to 
> ```

What priory ? :-D
Maybe `prior to ` ? ;-)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1979 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6PoF_7Hlbyou6Nb0U:-MO6fsxM1nESuxgxkkHP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1979)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> req_ptr
> ```

`req`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-09 13:28 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[src/librpma.map, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6Nu6w01_EyK9F8bjH:-MO6g7PS5g8PAlEevwPL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/librpma.map#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		rpma_conn_req_delete;
> 		rpma_conn_req_new;
> 		rpma_conn_req_recv;
> 		rpma_conn_req_get_private_data;
> ```

Wrong order
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6PS-J8bBvm8qnT8HU:-MO6g2cbBu-2lnIr5qyM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> connection accept.
> ```

connection is accepted.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-09 13:46 UTC, janekmi reviewed
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/646#-MO6jt-TDK9qNI8I6KEF:-MO6jt-TDK9qNI8I6KEG:b-mbdyyi) (no related file):*
Please add a note that private data after accepting the connection is invalidated or we have to redesign this part to do not free the private data from the connection request stage.

---
___
*[src/include/librpma.h, line 1969 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6P-B5BakOf-fgpCOi:-MO6iIrc193hVmgZ7DrL:bei8x2p) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L1969)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I got a flashback with `priory`. xD
___
*[src/include/librpma.h, line 1950 at r2](https://reviewable.io/reviews/pmem/rpma/646#-MO6hkHX8Jzr8QWetkUK:-MO6hkHX8Jzr8QWetkUL:b-pzlhh7) ([raw file](https://github.com/pmem/rpma/blob/3c5b562a373908e301d24e7bdba064c606781745/src/include/librpma.h#L1950)):*
> ```objc
> /** 3
>  * rpma_conn_req_get_private_data - get a pointer to the incoming connection's
>  * private data
> ```

Please verify it produces a correct manpage. I recall we have a problem with multiline comments in the first line.
___
*[src/include/librpma.h, line 1968 at r2](https://reviewable.io/reviews/pmem/rpma/646#-MO6iCkX1GC1-sLv8odc:-MO6iCkY2HOBJf8i1_4f:bsdpmz9) ([raw file](https://github.com/pmem/rpma/blob/3c5b562a373908e301d24e7bdba064c606781745/src/include/librpma.h#L1968)):*
> ```objc
>  * data before connection is established in opposite to
>  * rpma_conn_get_private_data(3) which can be used after connection is fully
>  * established. In this case connection private data could be used as an input
> ```

The first sentence seems duplicated.


<!-- Sent from Reviewable.io -->

2020-12-09 13:46 UTC, janekmi reviewed
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2020-12-09 14:16 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 1950 at r2](https://reviewable.io/reviews/pmem/rpma/646#-MO6hkHX8Jzr8QWetkUK:-MO6qLRg1w_0Ceng4auA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3c5b562a373908e301d24e7bdba064c606781745/src/include/librpma.h#L1950)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please verify it produces a correct manpage. I recall we have a problem with multiline comments in the first line.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1968 at r2](https://reviewable.io/reviews/pmem/rpma/646#-MO6iCkX1GC1-sLv8odc:-MO6qGTI3flgXbm85vOZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3c5b562a373908e301d24e7bdba064c606781745/src/include/librpma.h#L1968)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The first sentence seems duplicated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-09 14:16 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: 3 of 4 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/646#-MO6jt-TDK9qNI8I6KEF:-MO6r4ot0QzveTc7q636:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a note that private data after accepting the connection is invalidated or we have to redesign this part to do not free the private data from the connection request stage.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-12-09 14:16 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2020-12-09 15:06 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6O14S32sOPxOd72FE:-MO70VzI6Xy4x_67NQDo:b-ht8ve9) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L332)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`rpma_conn_req_get_private_data()` - brackets at the end
___
*[src/include/librpma.h, line 1962 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO70mDH6RMF4PhB5yu8:-MO70mDH6RMF4PhB5yu9:bk5jpke) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1962)):*
> ```
> before connection
> ```

before the connection
___
*[src/include/librpma.h, line 1966 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO70smj4MQr_C5JuBUE:-MO70smj4MQr_C5JuBUF:b-m6qbg0) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1966)):*
> ```
> pdata pointer
> ```

The pdata pointer
___
*[src/include/librpma.h, line 1966 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO710510p3hDdvPBvrA:-MO710510p3hDdvPBvrB:b6y99sg) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1966)):*
> ```
> after connection 
> ```

after the connection 
___
*[src/include/librpma.h, line 1968 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO717NHDqS-H9Lw_q8Y:-MO717NI4Mv4Dq8JHeCv:b-seya86) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1968)):*
> ```
> after connection
> ```

after the connection


<!-- Sent from Reviewable.io -->

2020-12-09 15:06 UTC, ldorau reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2020-12-10 07:15 UTC, lixiaoy1 commented on src/include/librpma.h
> +int rpma_conn_req_get_private_data(const struct rpma_conn_req *req,
Are you going to develop an example to show the usage? Is this interface used after rpma_ep_listen() and before server_accept_connection()?

2020-12-10 08:39 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/646#-MO6O14S32sOPxOd72FE:-MOAnIom9dW2wQ6_uGAr:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/6b4e6bcbf417abcf048482f19ea8f610ddf6e206/src/include/librpma.h#L332)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_req_get_private_data()` - brackets at the end
</blockquote></details>

Done
___
*[src/include/librpma.h, line 1962 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO70mDH6RMF4PhB5yu8:-MOAnMNoEfE1qMDX7nL_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1962)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> before connection
> ```

before the connection
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1966 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO70smj4MQr_C5JuBUE:-MOAnOa08UvIQNHHKOmy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1966)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> pdata pointer
> ```

The pdata pointer
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1966 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO710510p3hDdvPBvrA:-MOAnP5t7UToUFgEXZiv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1966)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> after connection 
> ```

after the connection 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1968 at r3](https://reviewable.io/reviews/pmem/rpma/646#-MO717NHDqS-H9Lw_q8Y:-MOAnRPe9zIIEmJGikTs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ba1fe5deab2c026cbb95eec9814be567fd99831/src/include/librpma.h#L1968)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> after connection
> ```

after the connection
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-10 09:12 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2020-12-10 09:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/646#-MOAvefJ5hrCuQ9nCnEa:-MOAvefJ5hrCuQ9nCnEb:b-z01q1b) (no related file):*
Unit tests are missing, `rpma_conn_req_get_private_data()` is not covered with tests:
https://app.codecov.io/gh/pmem/rpma/compare/646/tree/src/conn_req.c

---


<!-- Sent from Reviewable.io -->

2020-12-10 12:19 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/646#-MOAvefJ5hrCuQ9nCnEa:-MOB_9pR9RYQWSPje_87:b-1gh2l1) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Unit tests are missing, `rpma_conn_req_get_private_data()` is not covered with tests:
https://app.codecov.io/gh/pmem/rpma/compare/646/tree/src/conn_req.c
</blockquote></details>

yes it will be added in a separate PR

---


<!-- Sent from Reviewable.io -->

2020-12-10 13:07 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/646#-MOAvefJ5hrCuQ9nCnEa:-MOBkqEvD_aKqolTLLZm:b-htipwj) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes it will be added in a separate PR
</blockquote></details>

Why in a separate PR?

---


<!-- Sent from Reviewable.io -->

2021-01-04 13:58 UTC, grom72 reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-08 18:09 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/646)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-02-19 13:49 UTC, janekmi commented
To be replaced by another PR with tests etc. Please track the #736 issue for updates.

2021-02-19 13:49 UTC, closed without merging