test: add librmpa API's multithreaded test
pmem/rpma pull request #672
Opened 2020-12-16 08:41 UTC by ewanglong

2020-12-16 10:20 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 2 of 3 files reviewed, 11 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/672#-MOesWSE3jhsM6Is2opV:-MOesWSE3jhsM6Is2opW:bu2bkd5) (no related file):*
I would like to see this test under e.g.: tests/multithreaded
It is not an example.

---
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOex5ZaEFSOXGmcJTic:-MOex5ZaEFSOXGmcJTid:b-6gqy06) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L16)):*
> ```C
> #include <librpma.h>
> 
> typedef struct mtt_args {
> ```

I'm not sure we need a typedef here. I will simply go with `struct thread_args`.
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOexU8E-68xGLx7z6_I:-MOexU8E-68xGLx7z6_J:bcp53da) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L18)):*
> ```C
> typedef struct mtt_args {
> 	int ntd;
> 	char *addr;
> ```

Having a pointer here all of the threads will access the same memory. I think we will better off having here a:
```c
#define MAX_ADDR (4 * 4 -1)

/* ... */

char addr[MAX_ADDR];
```
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf-KQC-i-G50Bjqv-D:-MOf-KQC-i-G50Bjqv-E:b5buz20) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L23)):*
> ```C
> const char *api_name = "rpma_utils_get_ibv_context";
> 
> static void *con_thread(void *arg)
> ```

thread_main? What con_thread means?
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf06op1UT-KxXPKqpT:-MOf06oq3-YCpZIn3q5-:bic91nq) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L29)):*
> ```C
> 	mtt_args *p_mttargs = (mtt_args *)arg;
> 	int ntd = p_mttargs->ntd;
> 	char *addr = p_mttargs->addr;
> ```

I think we do not need these intermediate variables. Do you?
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf1btM1EjTJ6Z3Dgs1:-MOf1btM1EjTJ6Z3Dgs2:b-pbcuzz) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L38)):*
> ```C
> 			&dev);
> 	if (ret) {
> 		printf("-ERR thread #%d failed at %s: ret = %d\n",
> ```

```c
fprintf(stderr, "[thread #%d] %s failed: %s\n", args, api_name, rpma_err_2str(ret));
```
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf2m28AuEAnjxGNmE2:-MOf2m28AuEAnjxGNmE3:b-p2epnz) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L42)):*
> ```C
> 		abort();
> 	} else {
> 		printf("-OK thread #%d succeeded at %s!\n", ntd, api_name);
> ```

I think it is not needed. Drop it.
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOetqlBD3ZgteYfQitc:-MOetqlBD3ZgteYfQitd:blzk872) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L62)):*
> ```C
> 	/* parameters */
> 	int i;
> 	int tn = (int)strtoul(argv[1], NULL, 10);
> ```

tn -> thread_num

I do not like having too short variable names. The name should convey meaning.
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOeufV7-5hlO5t3GQeA:-MOeufV7-5hlO5t3GQeB:b-xoqef6) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L66)):*
> ```C
> 	int ret = 0;
> 
> 	pthread_t *p_tds = malloc(sizeof(pthread_t) * (long unsigned int)tn);
> ```

What p_tds stands for? Maybe go simply with `threads`?
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOezYcY3MJo6fqVFng0:-MOezYcY3MJo6fqVFng1:b-nt14hl) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L67)):*
> ```C
> 
> 	pthread_t *p_tds = malloc(sizeof(pthread_t) * (long unsigned int)tn);
> 	mtt_args *p_args = malloc(sizeof(mtt_args) * (long unsigned int)tn);
> ```

threads_args?
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOezbqIBzDeD401JWNR:-MOezbqIBzDeD401JWNS:b-berelk) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L71)):*
> ```C
> 	for (i = 0; i < tn; i++) {
> 		p_args[i].ntd = i;
> 		p_args[i].addr = addr;
> ```

`strcpy` will be needed here.


<!-- Sent from Reviewable.io -->

2020-12-16 10:28 UTC, janekmi requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf3LkL-3wOX1z_4MBH:-MOf3LkM-62HiVfIcWrJ:bhg46z1) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L75)):*
> ```C
> 				&p_args[i])) != 0) {
> 			printf("-ERR Can't start thread #%d: ret = %d\n",
> 					i, ret);
> ```

```c
fprintf(stderr, "Can not start a thread #%d: %s\n", i, strerror(ret));
```
___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf4fxnEzl3huxdANpo:-MOf4fxnEzl3huxdANpp:b-viiyox) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L83)):*
> ```C
> 		pthread_join(p_tds[i], NULL);
> 
> 	printf("-OK Pass multithreaded 01-%s!\n", api_name);
> ```

I think we will get a nice output from the ctest. No need to carve it on your own.


<!-- Sent from Reviewable.io -->

2020-12-16 10:40 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/672#-MOesWSE3jhsM6Is2opV:-MOf7cNI-GxzN8YD5pKY:b-gwedj7) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would like to see this test under e.g.: tests/multithreaded
It is not an example.
</blockquote></details>

I agree with @janekmi 

---


<!-- Sent from Reviewable.io -->

2020-12-16 14:09 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2020-12-16 14:10 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 13 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2020-12-16 15:21 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 14 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/672#-MOg7sqfB8McViQ9FuUd:-MOg7sqgDKAEs7xqw2Fg:b-lvpf86) (no related file):*
The builds failed.

---


<!-- Sent from Reviewable.io -->

2020-12-18 11:17 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2020-12-18 11:36 UTC, ldorau requested changes
I will add the review of `tests/multithreaded/CMakeLists.txt` later

2020-12-18 11:36 UTC, ldorau commented on tests/multithreaded/01-rpma_utils_get_ibv_context.c
> +	int ret = 0;
just `int ret;` 
`= 0` is not needed.

2020-12-18 11:36 UTC, ldorau commented on tests/multithreaded/01-rpma_utils_get_ibv_context.c
> +const char *api_name = "rpma_utils_get_ibv_context";
static

2020-12-18 11:36 UTC, ldorau commented on tests/multithreaded/01-rpma_utils_get_ibv_context.c
> + * 01-rpma_utils_get_ibv_context.c -- this API's multithreaded test
multi-threaded test for rpma_utils_get_ibv_context()

2020-12-18 11:36 UTC, ldorau commented on tests/multithreaded/01-rpma_utils_get_ibv_context.c
> +		abort();
Replace `abort()` with `exit -1;`, please - it is not a reason to abort.

2020-12-18 11:36 UTC, ldorau commented on tests/multithreaded/01-rpma_utils_get_ibv_context.c
> +	struct thread_args *p_args = malloc(sizeof(struct thread_args)
Add the error handling for those two `malloc()`, please.

2020-12-18 11:36 UTC, ldorau commented on tests/multithreaded/01-rpma_utils_get_ibv_context.c
> +			fprintf(stderr, "Can not start a thread #%d: %s\n",
`Cannot start the thread ...`

2020-12-18 11:38 UTC, ldorau reviewed
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 2 of 3 files reviewed, 20 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2020-12-19 00:40 UTC, janekmi requested changes
> Reviewed 1 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 2 of 3 files reviewed, 13 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsP6xYBXNtlZFoK2eW:-MOsP6xYBXNtlZFoK2eX:bnch6gr) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L5)):*
> ```C
> 
> /*
>  * multi-threaded test for rpma_utils_get_ibv_context()
> ```

1. I think we can follow here the unit test directory structure and file naming convention. So this one will go into multithreaded/utils/utils-get_ibv_context.c
2. Please keep either multithreaded or multi-threaded just for consistency.
3. We are writing here the name of the file first. So it should be:
```
utils-get_ibv_context -- multithreaded test for ...
```
___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 39 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsQMLyDVRbh0XiT6YZ:-MOsQMLyDVRbh0XiT6Y_:by92vm4) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L39)):*
> ```C
> 	if (ret) {
> 		fprintf(stderr, "[thread #%d] %s failed: %s\n",
> 		p_thread_args->thread_num, api_name, rpma_err_2str(ret));
> ```

Please indent this line more.
___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsQcjZExzPJ6HXdUJ9:-MOsQcjZExzPJ6HXdUJA:b-n5w8tk) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L69)):*
> ```C
> 	if (p_threads == NULL || p_args == NULL) {
> 		fprintf(stderr, "%s failed: %s\n",
> 			api_name, rpma_err_2str(RPMA_E_NOMEM));
> ```

```c
fprintf(stderr, "malloc failed");
```

Because you are validating both mallocs at once we can not assume errno still have a valid error code sadly.


<!-- Sent from Reviewable.io -->

2020-12-19 00:48 UTC, janekmi requested changes
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 23 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/CMakeLists.txt, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsRk578i-UeiVukjQ4:-MOsRk58EqyRDUrccBpP:b200jhc) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L23)):*
> ```CMake
> add_flag(-lpthread)
> 
> add_flag("-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2" RELEASE)
> ```

All the way up to here (included) seems unnecessary. Please take a lot at how it is done for the unit tests.
___
*[tests/multithreaded/CMakeLists.txt, line 27 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsRwGgBNznHcvpsYsd:-MOsRwGgBNznHcvpsYse:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L27)):*
> ```CMake
> include(${CMAKE_SOURCE_DIR}/cmake/functions.cmake)
> # set LIBRT_LIBRARIES if linking with librt is required
> check_if_librt_is_required()
> ```

Not needed.
___
*[tests/multithreaded/CMakeLists.txt, line 44 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSFWq0Sp01PhlGWA3:-MOsSFWq0Sp01PhlGWA4:bs4tgpc) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L44)):*
> ```CMake
> 		set(rpma_src_files "${file};${rpma_src_files}")
> 	endif()
> endforeach()
> ```

If we are linking the librpma library we do not need its C files, don't we?
___
*[tests/multithreaded/CMakeLists.txt, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSSCT1Va3SHMUXmAo:-MOsSSCT1Va3SHMUXmAp:b-sw0ecd) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L50)):*
> ```CMake
> 
> function(add_multithreaded)
> 	set(options USE_LIBPMEM_IF_FOUND USE_LIBIBVERBS USE_LIBPROTOBUFC)
> ```

I think only the libibverbs may stay here.
___
*[tests/multithreaded/CMakeLists.txt, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSZfG85nXl1BJRX8h:-MOsSZfG85nXl1BJRX8i:b15vn75) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L64)):*
> ```CMake
> 		message(STATUS "${target} skipped - no libprotobuf-c found")
> 		return()
> 	endif()
> ```

I do not expect such a test to appear any time soon.
___
*[tests/multithreaded/CMakeLists.txt, line 72 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSlqEEQajSy440Ix3:-MOsSlqEEQajSy440Ix4:bqqgjbp) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L72)):*
> ```CMake
> 		OUTPUT_NAME ${MULTITHREADED_BIN}
> 		RUNTIME_OUTPUT_DIRECTORY ${MULTITHREADED_NAME})
> 	target_link_libraries(${target} ${LIBRPMA_LIBRARIES} ${LIBRT_LIBRARIES})
> ```

Why librt?
___
*[tests/multithreaded/CMakeLists.txt, line 74 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSpU78DPIp9TObAkk:-MOsSpU78DPIp9TObAkl:b-43660v) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L74)):*
> ```CMake
> 	target_link_libraries(${target} ${LIBRPMA_LIBRARIES} ${LIBRT_LIBRARIES})
> 	target_include_directories(${target} PRIVATE common
> 		${LIBRPMA_SOURCE_DIR})
> ```

I bet we do not need this.
___
*[tests/multithreaded/CMakeLists.txt, line 82 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSu1zBbtcLmDw-zlJ:-MOsSu1zBbtcLmDw-zlK:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L82)):*
> ```CMake
> 		target_compile_definitions(${target}
> 			PRIVATE USE_LIBPMEM)
> 	endif()
> ```

Not needed.
___
*[tests/multithreaded/CMakeLists.txt, line 94 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsSwM_7iST-6M_-Wok:-MOsSwM_7iST-6M_-Wol:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L94)):*
> ```CMake
> 			PRIVATE ${LIBPROTOBUFC_INCLUDE_DIRS})
> 		target_link_libraries(${target} ${LIBPROTOBUFC_LIBRARIES})
> 	endif()
> ```

Not needed.
___
*[tests/multithreaded/CMakeLists.txt, line 98 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsT1kz9RYTznZCw4PO:-MOsT1kz9RYTznZCw4PP:b-eefnh3) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/CMakeLists.txt#L98)):*
> ```CMake
> 
> add_multithreaded(NAME 01-rpma_utils_get_ibv_context BIN 01-rpma_utils_get_ibv_context
> 	SRCS 01-rpma_utils_get_ibv_context.c)
> ```

I think you will need here USE_LIBIBVERBS. 


<!-- Sent from Reviewable.io -->

2020-12-28 09:51 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 15 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/CMakeLists.txt, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/672#-MPcgVQk2WqQOEv9cspC:-MPcgQ2D4_zdZTzClj59:b-ch2zug) ([raw file](https://github.com/pmem/rpma/blob/3e58b5ece71b24246f28afeb4f87bd3222481783/tests/multithreaded/CMakeLists.txt#L38)):*
> ```CMake
> 
> add_multithreaded(NAME utils BIN 01-rpma_utils_get_ibv_context
> 	SRCS utils/01-rpma_utils_get_ibv_context.c)
> ```

The definition of `add_multithreaded` should be in the tests/cmake/ctest_helpers.cmake.
Whereas using it should be moved e.g. tests/multithreaded/utils/CMakeLists.txt
___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MPcieHO5BvyWTxz2mRr:-MPcieHO5BvyWTxz2mRs:btpnt02) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L5)):*
> ```C
> 
> /*
>  * multi-threaded test for rpma_utils_get_ibv_context()
> ```

Please rename according to the tests naming convention: utils-get_ibv_context.c


<!-- Sent from Reviewable.io -->

2020-12-28 10:18 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 23 at r2](https://reviewable.io/reviews/pmem/rpma/672#-MOpFP_DB8jGSBWQJy_w-r2-23:-MPciCEeCkLtFsUtVwyC:b-siocgm) ([raw file](https://github.com/pmem/rpma/blob/8d49f30a33a8a1c192a702d31a945532cd7ed059/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

static
</blockquote></details>

I meant adding `static` (not replacing with `const`), so please use `static const` here.
___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/672#-MOpFP_DB8jGSBWQJy_w-r2-73:-MPcouUKE2AvMJg_IBbs:b8xtods) ([raw file](https://github.com/pmem/rpma/blob/8d49f30a33a8a1c192a702d31a945532cd7ed059/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Cannot start the thread ...`
</blockquote></details>

"Don’t use `can not` when you mean `cannot`." (https://www.grammarly.com/blog/cannot-or-can-not/)
... so please use `Cannot ...` (formal) or `Can't ...`(informal)
___
*[tests/multithreaded/utils/01-rpma_utils_get_ibv_context.c, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/672#-MPcjgPL5KReE5QOaX4l:-MPcjgPL5KReE5QOaX4m:b-c0v7si) ([raw file](https://github.com/pmem/rpma/blob/3e58b5ece71b24246f28afeb4f87bd3222481783/tests/multithreaded/utils/01-rpma_utils_get_ibv_context.c#L5)):*
> ```
>  ... for it.
> ```

`... for rpma_utils_get_ibv_context()`


<!-- Sent from Reviewable.io -->

2020-12-28 10:20 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-05 14:52 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 244 at r5](https://reviewable.io/reviews/pmem/rpma/672#-MQHxBqS3UKzGIgh2w4g:-MQHxBqS3UKzGIgh2w4h:b8n5v4r) ([raw file](https://github.com/pmem/rpma/blob/1d03ca76c2037c2b2463583213da96a3f61cc108/tests/cmake/ctest_helpers.cmake#L244)):*
> ```CMake
> 		target_link_libraries(${target} ${LIBIBVERBS_LIBRARIES})
> 	endif()
> endfunction()
> ```

EOL is missing.
___
*[tests/multithreaded/CMakeLists.txt, line 8 at r5](https://reviewable.io/reviews/pmem/rpma/672#-MQHzMYc5vsldOf8YTMN:-MQHzMYd5FW3BTBD_qwG:b82kk74) ([raw file](https://github.com/pmem/rpma/blob/1d03ca76c2037c2b2463583213da96a3f61cc108/tests/multithreaded/CMakeLists.txt#L8)):*
> ```CMake
> add_custom_target(multithreaded)
> include_directories(${LIBRPMA_INCLUDE_DIRS})
> link_directories(${LIBRPMA_LIBRARY_DIRS})
> ```

What is the `multithreaded` target for?
I think all three lines are for nothing.
___
*[tests/multithreaded/utils/01-rpma_utils_get_ibv_context.c, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/672#-MQI-TuO7J524k2iYxpo:-MQI-TuO7J524k2iYxpp:bu980y9) ([raw file](https://github.com/pmem/rpma/blob/1d03ca76c2037c2b2463583213da96a3f61cc108/tests/multithreaded/utils/01-rpma_utils_get_ibv_context.c#L5)):*
> ```C
> 
> /*
>  * 01-rpma_utils-get_ibv_context.c --
> ```

`01-rpma_utils-get_ibv_context.c` -> `utils-get_ibv_context.c`

1. in the comment here
2. rename the file itself


<!-- Sent from Reviewable.io -->

2021-01-08 11:40 UTC, janekmi requested changes
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 6 at r6](https://reviewable.io/reviews/pmem/rpma/672#-MQWmtJiDVsZ6v7BiAWz:-MQWmtJiDVsZ6v7BiAX-:b-huf4cg) ([raw file](https://github.com/pmem/rpma/blob/3a6c4d44df7a52218a601aaf39afdb52329f2666/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L6)):*
> ```C
> /*
>  * rpma_utils-get_ibv_context.c --
>  * multithreaded test for rpma_utils_get_ibv_context().
> ```

Please move it to the preceding line.


<!-- Sent from Reviewable.io -->

2021-01-08 11:50 UTC, janekmi requested changes
> Reviewed 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 233 at r6](https://reviewable.io/reviews/pmem/rpma/672#-MQWoo8PEAz0lxExCHv1:-MQWoo8PEAz0lxExCHv2:b-fbxbiu) ([raw file](https://github.com/pmem/rpma/blob/3a6c4d44df7a52218a601aaf39afdb52329f2666/tests/cmake/ctest_helpers.cmake#L233)):*
> ```CMake
> 
> 	prepend(srcs ${CMAKE_CURRENT_SOURCE_DIR} ${srcs})
> 	add_executable(${target} ${MULTITHREADED_SRCS})
> ```

```cmake
target_include_directories(${TEST_NAME} PRIVATE
	${LIBRPMA_INCLUDE_DIRS})
```
___
*[tests/multithreaded/utils/CMakeLists.txt, line 7 at r6](https://reviewable.io/reviews/pmem/rpma/672#-MQWowwaArSFnpFfkJRr:-MQWowwaArSFnpFfkJRs:b-o2lf9v) ([raw file](https://github.com/pmem/rpma/blob/3a6c4d44df7a52218a601aaf39afdb52329f2666/tests/multithreaded/utils/CMakeLists.txt#L7)):*
> ```CMake
> 
> include(../../cmake/ctest_helpers.cmake)
> include_directories(${LIBRPMA_INCLUDE_DIRS})
> ```

This line seems too general. I recommend removing it in favour of a small addendum I have proposed for `add_multithreaded()`.


<!-- Sent from Reviewable.io -->

2021-01-12 08:24 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 6 at r6](https://reviewable.io/reviews/pmem/rpma/672#-MQWmtJiDVsZ6v7BiAWz:-MQpfcRv48p87VVgmvaJ:b-n9nei6) ([raw file](https://github.com/pmem/rpma/blob/3a6c4d44df7a52218a601aaf39afdb52329f2666/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please move it to the preceding line.
</blockquote></details>

You mean put them like this " * rpma_utils-get_ibv_context.c -- multithreaded test for rpma_utils_get_ibv_context()." ? But it will exceed 80 characters and failed to check cstyle.


<!-- Sent from Reviewable.io -->

2021-01-12 08:40 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/cmake/ctest_helpers.cmake, line 233 at r6](https://reviewable.io/reviews/pmem/rpma/672#-MQWoo8PEAz0lxExCHv1:-MQpiX4B18mGfMgzkyb3:bh7fyfj) ([raw file](https://github.com/pmem/rpma/blob/3a6c4d44df7a52218a601aaf39afdb52329f2666/tests/cmake/ctest_helpers.cmake#L233)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```cmake
target_include_directories(${TEST_NAME} PRIVATE
	${LIBRPMA_INCLUDE_DIRS})
```
</blockquote></details>

I replaced TEST_NAME by target as corresponding to the current code.
	target_include_directories(${target} PRIVATE
			${LIBRPMA_INCLUDE_DIRS})


<!-- Sent from Reviewable.io -->

2021-01-13 12:00 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r6, 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-13 14:23 UTC, ldorau requested changes
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 4 of 5 files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/cmake/ctest_helpers.cmake, line 245 at r7](https://reviewable.io/reviews/pmem/rpma/672#-MQw6t1R4dXN4tisX01M:-MQw6t1S0qKhK8Kc-2uG:b72r6pv) ([raw file](https://github.com/pmem/rpma/blob/e1bb04daf7e874207c14b0a088592f7ca9cc8cf2/tests/cmake/ctest_helpers.cmake#L245)):*
> ```CMake
> 		target_link_libraries(${target} ${LIBIBVERBS_LIBRARIES})
> 	endif()
> endfunction()
> ```

`add_test_*()` is missing. The new tests are NOT added nor run ! 


<!-- Sent from Reviewable.io -->

2021-01-13 14:24 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-14 07:13 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/672#-MQzjQXjDC9RxGXw_sKf:-MQzjQXjDC9RxGXw_sKg:b-cke375) (no related file):*
The new tests are NOT RUN.

---


<!-- Sent from Reviewable.io -->

2021-01-15 09:00 UTC, ldorau reviewed
@ewanglong please respond "Done" to all fixed issues.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672#-:-MR4GR6rAXMEIs-m5Y6c:ba6sce4)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-15 09:03 UTC, janekmi reviewed
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-18 09:56 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake, line 18 at r8](https://reviewable.io/reviews/pmem/rpma/672#-MRJumAf81dFA_DdzgIE:-MRJumAg9aR3MTXS1Isg:b-536bkf) ([raw file](https://github.com/pmem/rpma/blob/0f1ac169234c07e536432d6d77782a65416d9478/tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake#L18)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> if("$ENV{RPMA_SOFT_ROCE_IP}" STREQUAL "")
> 	set(SOFT_ROCE_IP "127.0.0.1")
> else()
> 	set(SOFT_ROCE_IP $ENV{RPMA_SOFT_ROCE_IP})
> endif()
> execute(${TEST_EXECUTABLE} ${THREADS} ${SOFT_ROCE_IP})
> ```
</details>


(@janekmi @grom72 It requires https://github.com/pmem/rpma/pull/746 to work)


<!-- Sent from Reviewable.io -->

2021-01-18 10:02 UTC, ldorau commented
Reuires:
- [ ] #746

2021-01-19 01:58 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOetqlBD3ZgteYfQitc:-MRNLU6HABVa2r-4EHH1:bvzl7px) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

tn -> thread_num

I do not like having too short variable names. The name should convey meaning.
</blockquote></details>

Long names caused a few lines of code need be splitted into more lines, with respect to the 80 character c-stype checking. Then the code seems to be ugly arranged and  less readable. Can we have better rules?


<!-- Sent from Reviewable.io -->

2021-01-19 02:09 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOf4fxnEzl3huxdANpo:-MRNOb-h4WCRVRwh6Yie:b-4jlgqx) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L83)):*
> fprintf(stderr
Do you mean removing those frpint(stderr...) code?


<!-- Sent from Reviewable.io -->

2021-01-19 07:23 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOetqlBD3ZgteYfQitc:-MROVCWo9FPsXqmEvm-e:bg2pa7n) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L62)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Long names caused a few lines of code need be splitted into more lines, with respect to the 80 character c-stype checking. Then the code seems to be ugly arranged and  less readable. Can we have better rules?
</blockquote></details>

The limit of max 80 characters per line is used in all of pmem repos (or in most of them at least).
You can try to place declarations at the beginning, maybe like that will be OK?

```
pthread_t *p_threads;
...
p_threads = malloc(sizeof(pthread_t) * (unsigned int)thread_num);
```


<!-- Sent from Reviewable.io -->

2021-01-19 07:53 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOetqlBD3ZgteYfQitc:-MROcfIV3G-pNVdBvgws:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The limit of max 80 characters per line is used in all of pmem repos (or in most of them at least).
You can try to place declarations at the beginning, maybe like that will be OK?

```
pthread_t *p_threads;
...
p_threads = malloc(sizeof(pthread_t) * (unsigned int)thread_num);
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 07:54 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOezYcY3MJo6fqVFng0:-MROchsF5P0Sy5cqsgrQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

threads_args?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 07:54 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/01-rpma_utils_get_ibv_context.c, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/672#-MOsQcjZExzPJ6HXdUJ9:-MROclhz1lEEptragnJ2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf6711a6e647797d020481eacfff8c1a82e7a3b4/tests/multithreaded/01-rpma_utils_get_ibv_context.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
fprintf(stderr, "malloc failed");
```

Because you are validating both mallocs at once we can not assume errno still have a valid error code sadly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 07:54 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/672#-MOeufV7-5hlO5t3GQeA:-MROcot9ACzsoV8_H4pu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3c6723054ec865041ff974d20be50b58dab8d077/examples/100-thread-safe-test/01-rpma_utils_get_ibv_context.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What p_tds stands for? Maybe go simply with `threads`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-19 09:13 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-21 11:01 UTC, ldorau approved these changes
@ewanglong please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672#-:-MRZam1K1hnNZuq5wmsi:bzb7h4z)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-22 07:14 UTC, ewanglong reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672#-:-MRcwOKSCSBnhMKI7Del:bb6un1j)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)



<!-- Sent from Reviewable.io -->

2021-01-22 07:19 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/CMakeLists.txt, line 53 at r11](https://reviewable.io/reviews/pmem/rpma/672#-MRcxXhE4TNN62toh8Dr:-MRcxXhE4TNN62toh8Ds:b-vpeeif) ([raw file](https://github.com/pmem/rpma/blob/18b0bf14d62d4c765a79a5cc73cc58d9bc09356d/tests/CMakeLists.txt#L53)):*
> ```
> add_subdirectory(multithreaded)
> ```

It should be inside `if`:

```
if(TESTS_SOFT_ROCE)
	add_subdirectory(multithreaded)
endif()
```


<!-- Sent from Reviewable.io -->

2021-01-22 07:53 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/CMakeLists.txt, line 53 at r11](https://reviewable.io/reviews/pmem/rpma/672#-MRcxXhE4TNN62toh8Dr:-MRd4Ri94Czx3HRxIbhX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18b0bf14d62d4c765a79a5cc73cc58d9bc09356d/tests/CMakeLists.txt#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> add_subdirectory(multithreaded)
> ```

It should be inside `if`:

```
if(TESTS_SOFT_ROCE)
	add_subdirectory(multithreaded)
endif()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-22 08:27 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-22 14:43 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672#-:-MReY7hWDwPJjRCaj7bz:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake, line 10 at r12](https://reviewable.io/reviews/pmem/rpma/672#-MReWEJYDw-DQruTcr5n:-MReWEJYDw-DQruTcr5o:b-hzguni) ([raw file](https://github.com/pmem/rpma/blob/e311ea648d473926f61371a63dc77251e0af01b9/tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake#L10)):*
> ```
> set(THREADS 32)
> ```

Maybe number of threads should be configurable? @janekmi
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 51 at r12](https://reviewable.io/reviews/pmem/rpma/672#-MReXUg783yM6iDO0AJf:-MReXUg8Bnq6Jau3HIlK:bvrq6zi) ([raw file](https://github.com/pmem/rpma/blob/e311ea648d473926f61371a63dc77251e0af01b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L51)):*
> ```
> <thread_nums> 
> ```

`<thread_num>`


<!-- Sent from Reviewable.io -->

2021-01-22 15:44 UTC, janekmi requested changes
> Reviewed 2 of 2 files at r8, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake, line 1 at r12](https://reviewable.io/reviews/pmem/rpma/672#-MRekhfH8xIU5WRXDBuL:-MRekhfH8xIU5WRXDBuM:b-qn8epu) ([raw file](https://github.com/pmem/rpma/blob/e311ea648d473926f61371a63dc77251e0af01b9/tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake#L1)):*
> ```CMake
> #
> ```

This file should be simply named CMakeLists.txt.
___
*[tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake, line 10 at r12](https://reviewable.io/reviews/pmem/rpma/672#-MReWEJYDw-DQruTcr5n:-MRejhHU1FKRqIq-0J1D:b8pq4rk) ([raw file](https://github.com/pmem/rpma/blob/e311ea648d473926f61371a63dc77251e0af01b9/tests/multithreaded/utils/multithreaded-utils-rpma_utils_get_ibv_context_0.cmake#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> set(THREADS 32)
> ```

Maybe number of threads should be configurable? @janekmi
</blockquote></details>

Yeah. I think parts of this will be moved to common or made more configurable.
It is a good start as is anyway.
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 51 at r12](https://reviewable.io/reviews/pmem/rpma/672#-MReXUg783yM6iDO0AJf:-MRegSN18P61JqUtlF0M:b32v57) ([raw file](https://github.com/pmem/rpma/blob/e311ea648d473926f61371a63dc77251e0af01b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> <thread_nums> 
> ```

`<thread_num>`
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-01-22 15:53 UTC, janekmi reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-22 16:07 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 51 at r12](https://reviewable.io/reviews/pmem/rpma/672#-MReXUg783yM6iDO0AJf:-MReqIuLAHaeRQ4WNoat:b14lhxb) ([raw file](https://github.com/pmem/rpma/blob/e311ea648d473926f61371a63dc77251e0af01b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

This is the only thing keeping me from the merge. @ewanglong please submit a fix for this. xD


<!-- Sent from Reviewable.io -->

2021-01-22 16:08 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/672#-:-MReqYo9EjdRnCTDwKib:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-01-22 16:08 UTC, merged