Try to implement rpma send with immediate data
pmem/rpma pull request #713
Opened 2020-12-31 06:13 UTC by yangx-jy

2021-01-08 17:32 UTC, janekmi requested changes
> Reviewed 21 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: all files reviewed, 42 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/713#-MQXqgqk0FmGZUcgX-DP:-MQXqgqk0FmGZUcgX-DQ:bz06qag) (no related file):*
The first PR is obviously not `rpma: extend rpma_mr_read()` but `rpma: extend rpma_mr_send()`.

---
___
*[examples/run-all-on-SoftRoCE.sh, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwE-HELGfZi520j_W:-MQXwE-HELGfZi520j_X:b-rka7q) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/run-all-on-SoftRoCE.sh#L70)):*
> ```Shell
> 	10-send-with-imm)
> 		echo "Starting the client ..."
> 		$DIR/client $IP_ADDRESS $PORT "1st_word" "imm_data=1234"
> ```

Can we just assume the 4th argument is an immediate data?
___
*[examples/10-send-with-imm/CMakeLists.txt, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXw5RhBeIfh1vCydaQ:-MQXw5RhBeIfh1vCydaR:bhaeazs) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/CMakeLists.txt#L35)):*
> ```CMake
> 			${LIBRPMA_INCLUDE_DIRS}
> 			../common)
> 	target_link_libraries(example-${name} rpma ${LIBPMEM_LIBRARIES})
> ```

It seems you do not need libpmem here.
___
*[examples/10-send-with-imm/client.c, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwhnD0-frt5LShVqp:-MQXwhnD0-frt5LShVqq:b-8c15ii) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L19)):*
> ```C
> 
> #define USAGE_STR "usage: %s <server_address> <port> <word> " \
> 		"imm_data=<value>\n"
> ```

If we agree to have a plain argument here just `<imm>`.
___
*[examples/10-send-with-imm/client.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-al47DurFLwPshiG:-MQY-al47DurFLwPshiH:b32ve7) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L25)):*
> ```C
> {
> 	/* validate parameters */
> 	if (argc < 4) {
> ```

5?
___
*[examples/10-send-with-imm/client.c, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXy_CX1hLg7Mx71C7B:-MQXy_CX1hLg7Mx71C7C:b-4j2mzj) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L46)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	extra_name = strtok(argv[4], "=");
> 	extra_value = strtok(NULL, "=");
> 	if (strcmp(extra_name, "imm_data") || !extra_value) {
> 		fprintf(stderr, USAGE_STR, argv[0]);
> 		return -1;
> 	}
> ```
</details>


I don't see a point in having such complex params parsing. Why not just take the string value from the `argv[4]`?
___
*[examples/10-send-with-imm/client.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXyqQF9_MC-5g2jfIw:-MQXyqQF9_MC-5g2jfIx:bss0v5g) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L54)):*
> ```C
> 	}
> 
> 	if (data > UINT32_MAX) {
> ```

data -> imm?
___
*[examples/10-send-with-imm/client.c, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXytDM2RwOTrAtEwaU:-MQXytDM2RwOTrAtEwaV:b-mbxqdd) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L55)):*
> the provided immediate data is too big (%u > %u)\n
___
*[examples/10-send-with-imm/client.c, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXzNoK9Ha_zE3cNQWs:-MQXzNoK9Ha_zE3cNQWt:b-4jgi3a) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L85)):*
> ```C
> 	/* establish a new connection to a server listening at addr:port */
> 	struct rpma_conn_private_data pdata;
> 	pdata.ptr = &data;
> ```

/* send an immediate value for validation on the server side */
___
*[examples/10-send-with-imm/client.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-3ZR0tKpCRme08Ak:-MQY-3ZR0tKpCRme08Al:b1f1r8w) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L92)):*
> ```C
> 
> 	/* send a message with imm_data to the server */
> 	fprintf(stdout, "send value %s with imm_data %lu\n", word, data);
> ```

`%lu` is too big. I think `%u` is enough.
___
*[examples/10-send-with-imm/README.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwPff-OME9unnxUEB:-MQXwPff-OME9unnxUEC:bwajlqe) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/README.md#L7)):*
> ```Markdown
> - The client connects to the server and sends a message with imm_data
> to the server.
> - The server receives a message with imm_data from client.
> ```

... with the immediate data from the client. The immediate data is compared with an expected immediate data send by the client as the private data during establishing the connection.
___
*[examples/10-send-with-imm/README.md, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwZol1owwCi8LcmdE:-MQXwZom9HColEVv0fEp:b-up9c8w) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/README.md#L16)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port $word imm_data=$value
> ```

`$imm`
___
*[examples/10-send-with-imm/server.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-j0D1v0rL0_Vxagu:-MQY-j0D1v0rL0_Vxagv:bnpa329) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L25)):*
> ```C
> 	if (argc < 3) {
> 		fprintf(stderr, USAGE_STR, argv[0]);
> 		exit(-1);
> ```

`return -1` is enough.
___
*[examples/10-send-with-imm/server.c, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-xLpBBuSTEc6yXmC:-MQY-xLpBBuSTEc6yXmD:brzmy2u) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L74)):*
> get the expected immediate data value from the connection's private data
___
*[examples/10-send-with-imm/server.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0AtVEfcILs1bbuOE:-MQY0AtVEfcILs1bbuOF:b-uxoct4) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L79)):*
> ```C
> 	if (ret)
> 		goto err_conn_disconnect;
> 	uint32_t *data = pdata.ptr;
> ```

Please validate `pdata.len`.
___
*[examples/10-send-with-imm/server.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0GWG22Zg3OuHiWOS:-MQY0GWG22Zg3OuHiWOT:bypzfcw) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L84)):*
> ```C
> 	ret = rpma_recv(conn, recv_mr, 0, KILOBYTE, NULL);
> 	if (ret)
> 		goto err_conn_disconnect;
> ```

You have to post a RECV before accepting the connection. Please use `rpma_conn_req_recv()` in this case.
___
*[examples/10-send-with-imm/server.c, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0oSY8fcnsKLKiNTJ:-MQY0oSZ47iuWCyWSTfw:btmj510) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L97)):*
> ```C
> 	if (cmpl.op_status != IBV_WC_SUCCESS) {
> 		fprintf(stderr,
> 			"server got the unsuccessful completion of an operation\n");
> ```

~~server got~~
___
*[examples/10-send-with-imm/server.c, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0wWC7JlZeB-g2S82:-MQY0wWC7JlZeB-g2S83:b-o90bqs) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L97)):*
> ```C
> 	if (cmpl.op_status != IBV_WC_SUCCESS) {
> 		fprintf(stderr,
> 			"server got the unsuccessful completion of an operation\n");
> `` [...]

2021-01-11 07:20 UTC, ldorau reviewed
> Reviewed 4 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: all files reviewed, 42 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-01-12 05:12 UTC, yangx-jy commented
*[a discussion](https://reviewable.io/reviews/pmem/rpma/713#-MQXqgqk0FmGZUcgX-DP:-MQj064QBneE6bhej_Am:b-tnib4q) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The first PR is obviously not `rpma: extend rpma_mr_read()` but `rpma: extend rpma_mr_send()`.
</blockquote></details>

Sorry for the mistake, I will change it.

---


<!-- Sent from Reviewable.io -->

2021-01-12 05:14 UTC, yangx-jy commented
___
*[src/mr.h, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXhhsY6Mp8j3EC9sl5:-MQp0-QLEUA0lM7tKdO4:b-9carcq) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/mr.h#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add '... operation value`. At first, I thought you just have written a generic NOSUPP description. ;-)
</blockquote></details>

Could you give me a detailed example here?


<!-- Sent from Reviewable.io -->

2021-01-12 05:33 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 2331 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXoM5M3iqe0UIhkn-3:-MQp0L13Bvw4lL9AnVYZ:b-b2cci3) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/include/librpma.h#L2331)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A `wc_flags` field in the `struct ibv_wc` is of `int` type.
</blockquote></details>

The tye of wc_flags has been changed from int to unigned int since 2017, see the following patch:
https://github.com/linux-rdma/rdma-core/commit/8fe7f12f17239088ed0841e68abf3c02232db34f

By the way, the manpage is not updated so I send a patch to do it:
https://www.spinics.net/lists/linux-rdma/msg98897.html


<!-- Sent from Reviewable.io -->

2021-01-12 08:14 UTC, yangx-jy commented
___
*[examples/10-send-with-imm/server.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0GWG22Zg3OuHiWOS:-MQpeCRuAR2wZ6HCk81P:b-mrlytm) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to post a RECV before accepting the connection. Please use `rpma_conn_req_recv()` in this case.
</blockquote></details>

For this point,  is there any explanation? 


<!-- Sent from Reviewable.io -->

2021-01-12 08:19 UTC, yangx-jy commented
___
*[examples/10-send-with-imm/server.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0GWG22Zg3OuHiWOS:-MQpf2P-4Q0RSBjf1mnU:b-s7k60u) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L84)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

For this point,  is there any explanation? 
</blockquote></details>

I knew,  This step guarantees that data from client is not dropped when we have established connection but not created RQ. 


<!-- Sent from Reviewable.io -->

2021-01-12 13:44 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 3 of 21 files reviewed, 42 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @yangx-jy)

___
*[examples/run-all-on-SoftRoCE.sh, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwE-HELGfZi520j_W:-MQqOzTm5jZ1aHjRoHDU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/run-all-on-SoftRoCE.sh#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we just assume the 4th argument is an immediate data?
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/CMakeLists.txt, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXw5RhBeIfh1vCydaQ:-MQqP13R-hlOPauJ4wJb:bjtbtdr) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/CMakeLists.txt#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems you do not need libpmem here.
</blockquote></details>

Remove libpmem and add libibverbs because client and server use ibv_wc_status_str().
___
*[examples/10-send-with-imm/client.c, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwhnD0-frt5LShVqp:-MQqQ0Bv5TrOZXoWSII4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If we agree to have a plain argument here just `<imm>`.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-al47DurFLwPshiG:-MQqQFLB9aMD8D94-1y4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

5?
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXy_CX1hLg7Mx71C7B:-MQqQGxT39sL-yWpEhyV:bt1sv0n) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ```
> 	extra_name = strtok(argv[4], "=");
> 	extra_value = strtok(NULL, "=");
> 	if (strcmp(extra_name, "imm_data") || !extra_value) {
> 		fprintf(stderr, USAGE_STR, argv[0]);
> 		return -1;
> 	}
> ```

I don't see a point in having such complex params parsing. Why not just take the string value from the `argv[4]`?
</blockquote></details>

we can use argv[4] directly for now.
___
*[examples/10-send-with-imm/client.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXyqQF9_MC-5g2jfIw:-MQqQNus5UP3nizCVEis:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

data -> imm?
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXytDM2RwOTrAtEwaU:-MQqQTPw-qkdurCHIOKI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> the provided immediate data is too big (%u > %u)\n
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXzNoK9Ha_zE3cNQWs:-MQqQdQD0emklRgVlGhJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

/* send an immediate value for validation on the server side */
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-3ZR0tKpCRme08Ak:-MQqQhVq70KUK3NpPcHB:b-goagtk) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/client.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`%lu` is too big. I think `%u` is enough.
</blockquote></details>

changed data to (uint32_t)imm.
___
*[examples/10-send-with-imm/README.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwPff-OME9unnxUEB:-MQqS37r-iCNI9X-wXAu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/README.md#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... with the immediate data from the client. The immediate data is compared with an expected immediate data send by the client as the private data during establishing the connection.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/README.md, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXwZol1owwCi8LcmdE:-MQqUPs4Cg1HuIz5QBVn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/README.md#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`$imm`
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-j0D1v0rL0_Vxagu:-MQqUbjg24OKbnjP_wX5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`return -1` is enough.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY-xLpBBuSTEc6yXmC:-MQqV1_j93CS4mo2_hvS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> get the expected immediate data value from the connection's private data
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0AtVEfcILs1bbuOE:-MQqV3EZ3QS1BBhAM8Iw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please validate `pdata.len`.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0GWG22Zg3OuHiWOS:-MQqVG9x8q7CJbqgzE7m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L84)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I knew,  This step guarantees that data from client is not dropped when we have established connection but not created RQ. 
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQY0oSY8fcnsKLKiNTJ:-MQqVGuV9PCOQDYTi85T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/examples/10-send-with-imm/server.c#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~server got~~
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/713#-M [...]

2021-01-12 13:46 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 3 of 21 files reviewed, 42 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/common/mocks-ibverbs.c, line 255 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsA77-ggPMRKNTjv9:-MQqq3UACeHD6l2nb807:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/mocks-ibverbs.c#L255)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* XXX all wr fields should be validated to avoid posting uninitialized values */
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 261 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXrDOX9Aeo0xci80Vm:-MQqq9XA80QvdER6jmlz:b6fhbks) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/mocks-ibverbs.c#L261)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just add a comment.


<!-- Sent from Reviewable.io -->

2021-01-22 14:45 UTC, ldorau reviewed
> Reviewed 2 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 5 of 21 files reviewed, 42 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2021-01-22 14:55 UTC, ldorau reviewed
> Reviewed 2 of 21 files at r1, 3 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 8 of 21 files reviewed, 42 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-22 15:08 UTC, ldorau requested changes
> Reviewed 4 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 12 of 21 files reviewed, 45 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[examples/10-send-with-imm/README.md, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRebTj5A4_a15xRaLuG:-MRebTj5A4_a15xRaLuH:bb5ic0y) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/README.md#L7)):*
> ```
> client.  The
> ```

Please move `The` to the next line.
___
*[examples/10-send-with-imm/README.md, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRebaWR5C1hY947w1pA:-MRebaWR5C1hY947w1pB:b-987dzt) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/README.md#L8)):*
> ```
> with an expected
> ```

`with the expected`
___
*[src/mr.h, line 50 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MReaG6KD8krqVDt-GkV:-MReaG6KD8krqVDt-GkW:blyqt77) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/mr.h#L50)):*
> ```
> parament
> ```

1) What do you mean by `parament`?
2) Please add a space before the bracket: ` (`


<!-- Sent from Reviewable.io -->

2021-01-22 15:15 UTC, ldorau requested changes
> Reviewed 3 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 15 of 21 files reviewed, 45 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRedQUC2FnV58PG35kc:b7s2dm0) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

How about "#define MOCK_IMM_DATA           (uint32_t)1234"?
</blockquote></details>

I agree that a value should require 32 bits to be saved (so it should be just >= 2^31)  - `(uint32_t)1234` does not do that.


<!-- Sent from Reviewable.io -->

2021-01-22 15:17 UTC, ldorau reviewed
@yangx-jy Could you resolve all fixed issues in Reviewable?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713#-:-MReetsB3EKf4pg5YXU1:b-nk6p53)* status: 15 of 21 files reviewed, 45 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-01-22 16:33 UTC, janekmi requested changes
> Reviewed 4 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 16 of 21 files reviewed, 27 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRevAq66DAvFk7NhrT7:-MRevAq66DAvFk7NhrT8:buu5vuv) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/client.c#L77)):*
> ```C
> 	/*
> 	 * establish a new connection to a server and send an immediate
> 	 * data for valication on the sever side
> ```

valication -> validation
___
*[examples/10-send-with-imm/server.c, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRevjhaBlyBsF5iBuuS:-MRevjhaBlyBsF5iBuuT:b-p1ffgd) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/server.c#L73)):*
> ```C
> 		goto err_ep_shutdown;
> 
> 	/* prepare to receice a message with immediate data from the client */
> ```

receice -> receive


<!-- Sent from Reviewable.io -->

2021-01-22 19:48 UTC, janekmi requested changes
> Reviewed 14 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: all files reviewed, 16 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @yangx-jy)

___
*[examples/10-send-with-imm/server.c, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfcdYt2TggZl3GKcHx:-MRfcdYt2TggZl3GKcHy:bjxjfye) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/server.c#L93)):*
> ```C
> 	if (conn_event != RPMA_CONN_ESTABLISHED) {
> 		fprintf(stderr,
> 			"rpma_conn_next_event returned an unexptected event\n");
> ```

```ret = -1;```
___
*[examples/10-send-with-imm/server.c, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfbXh1DfXVCK_epcYM:-MRfbXh1DfXVCK_epcYN:b-k5bso5) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/server.c#L100)):*
> ```C
> 	struct rpma_conn_private_data pdata;
> 	ret = rpma_conn_get_private_data(conn, &pdata);
> 	if (ret || pdata.len < sizeof(uint32_t)) {
> ```

You can not validate both conditions at the same time. In this case, if `ret != 0` you will print a message about the connection's private data. Where while having an error on this API call you can not expect `pdata` to have any reasonable data.
You have to do something like:

```c
if (ret) {
    goto err_conn_disconnect;
} else if (pdata.len < sizoef(uint32_t)) {
    fprintf(stderr, /* ... */);
    ret = -1;
    goto err_conn_disconnect;
}
```
___
*[src/conn.c, line 421 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfYRw12gF2ambvqd2x:-MRfYRw12gF2ambvqd2y:b-xc4rof) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/conn.c#L421)):*
> ```C
> 			    src, offset, len,
> 			    flags, IBV_WR_SEND_WITH_IMM,
> 			    imm, op_context);
> ```

Please indent the wrapped lines by two tabs. No spaces.
___
*[src/mr.h, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXhhsY6Mp8j3EC9sl5:-MRfZ70yDT5IeBs2j4p7:b7ez34v) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/mr.h#L50)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

changed to unsupported operation parament(wr.opcode)
</blockquote></details>

I think I would go with:
```
- RPMA_E_NOSUPP - unsupported 'operation' argument
```
___
*[src/include/librpma.h, line 2331 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXoM5M3iqe0UIhkn-3:-MRfZc6R62Wew5iuwSbs:b-2b0eka) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/include/librpma.h#L2331)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Good job. Thank you for pointing it out.
___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRfONaT-JgUqh1X6MR7:buoturr) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I agree that a value should require 32 bits to be saved (so it should be just >= 2^31)  - `(uint32_t)1234` does not do that.
</blockquote></details>

e.g. `0xfedcba98`
___
*[tests/unit/conn/conn-send_with_imm.c, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_g5A1rnTrEy0kRjB:-MRf_g5BASVFIdHBywB4:b-sbxxsa) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/conn/conn-send_with_imm.c#L98)):*
> ```C
> 				MOCK_RPMA_MR_LOCAL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, MOCK_FLAGS, MOCK_IMM_DATA,
> 				MOCK_OP_CONTEXT);
> ```

Please indent by two tabs.
___
*[tests/unit/mr/mr-send.c, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_Jvq8Eweogd79Gq6:-MRf_Jvq8Eweogd79Gq7:b-sbxxsa) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/mr/mr-send.c#L33)):*
> ```C
> 	int ret = rpma_mr_send(MOCK_QP, mrs->local, MOCK_SRC_OFFSET,
> 				MOCK_LEN, RPMA_F_COMPLETION_ON_ERROR,
> 				MOCK_UNKNOWN_OP, 0, MOCK_OP_CONTEXT);
> ```

Please indent by two tabs.
___
*[tests/unit/mr/mr-send.c, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_EIW5ntXEHZDMeQ6:-MRf_EIW5ntXEHZDMeQ7:b-sbxxsa) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/mr/mr-send.c#L59)):*
> ```C
> 	int ret = rpma_mr_send(MOCK_QP, mrs->local, MOCK_SRC_OFFSET,
> 				MOCK_LEN, RPMA_F_COMPLETION_ON_ERROR,
> 				IBV_WR_SEND, 0, MOCK_OP_CONTEXT);
> ```

Please indent by two tabs.
___
*[tests/unit/mr/mr-send.c, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_7-jDeAGwEfeAR4H:-MRf_7-k2xNjJ-yTs9Uh:b-sbxxsa) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/mr/mr-send.c#L100)):*
> ```C
> 		int ret = rpma_mr_send(MOCK_QP, mrs->local, MOCK_SRC_OFFSET,
> 					MOCK_LEN, RPMA_F_COMPLETION_ALWAYS,
> 					opcodes[i], imms[i], MOCK_OP_CONTEXT);
> ```

Please indent by two tabs.


<!-- Sent from Reviewable.io -->

2021-01-25 06:49 UTC, yangx-jy reviewed
Sorry for the late reply.   I resolve them now.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713#-:-MRrbX9l12A6Lt3KX3iW:b-kn25en)* status: 12 of 21 files reviewed, 15 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/10-send-with-imm/client.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRevAq66DAvFk7NhrT7:-MRryFUk5mU2eztUXPMJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/client.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

valication -> validation
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/README.md, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRebTj5A4_a15xRaLuG:-MRryRWy39zibJlsQSTL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/README.md#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> client.  The
> ```

Please move `The` to the next line.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/README.md, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRebaWR5C1hY947w1pA:-MRryaJb6J1FCRh0TNpZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/README.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> with an expected
> ```

`with the expected`
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRevjhaBlyBsF5iBuuS:-MRrynLc8F_peuxLcZ0h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/server.c#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

receice -> receive
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfcdYt2TggZl3GKcHx:-MRryzJlD2d0y54AjYOf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/server.c#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```ret = -1;```
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfbXh1DfXVCK_epcYM:-MRs-GOYBlx26afo_noH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/examples/10-send-with-imm/server.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can not validate both conditions at the same time. In this case, if `ret != 0` you will print a message about the connection's private data. Where while having an error on this API call you can not expect `pdata` to have any reasonable data.
You have to do something like:

```c
if (ret) {
    goto err_conn_disconnect;
} else if (pdata.len < sizoef(uint32_t)) {
    fprintf(stderr, /* ... */);
    ret = -1;
    goto err_conn_disconnect;
}
```

</blockquote></details>

Done.
___
*[src/conn.c, line 539 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXvTWi9gtCUSsySdt6:-MRs7bxlD-ATlubBHBRo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/conn.c#L539)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Keep it for now.
</blockquote></details>

Done.
___
*[src/conn.c, line 421 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfYRw12gF2ambvqd2x:-MRs2H4L5y0zRapalib9:b-6jwi68) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/conn.c#L421)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please indent the wrapped lines by two tabs. No spaces.
</blockquote></details>

Hi @janekmi ,

I actually used tabs instead of spaces.  Is it OK?
___
*[src/mr.h, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXhhsY6Mp8j3EC9sl5:-MRs33ZE0zOmwfPL8in1:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/mr.h#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think I would go with:
```
- RPMA_E_NOSUPP - unsupported 'operation' argument
```
</blockquote></details>

Done
___
*[src/mr.h, line 50 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MReaG6KD8krqVDt-GkV:-MRs377Z65wF2OCRmPjp:b-z1r16p) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/mr.h#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> parament
> ```

1) What do you mean by `parament`?
2) Please add a space before the bracket: ` (`
</blockquote></details>

Change to "- RPMA_E_NOSUPP - unsupported 'operation' argument" as Jan suggested.
___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRs6eT13m9qWJzFzQXP:bsxgsbn) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

e.g. `0xfedcba98`
</blockquote></details>

Take use of 0xfffffffe
___
*[tests/unit/conn/conn-send_with_imm.c, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_g5A1rnTrEy0kRjB:-MRs6ud_6eg6hfqmiRvo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/conn/conn-send_with_imm.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please indent by two tabs.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-send.c, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_Jvq8Eweogd79Gq6:-MRs6uyw30zlo-xmwR5e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/mr/mr-send.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please indent by two tabs.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-send.c, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_EIW5ntXEHZDMeQ6:-MRs6vNZ9be3t9Ni2KnO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/mr/mr-send.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please indent by two tabs.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-send.c, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRf_7-jDeAGwEfeAR4H:-MRs6vvK3u4Pg3z-L4z-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/tests/unit/mr/mr-send.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please indent by two tabs.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-25 08:21 UTC, ldorau reviewed
> Reviewed 4 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 16 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRsc6gl9038lpDf2xQr:b-vsef8n) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Take use of 0xfffffffe
</blockquote></details>

Maybe 0xDeadBeaf or 0x12345678 ?


<!-- Sent from Reviewable.io -->

2021-01-25 08:28 UTC, yangx-jy commented
___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRsd3AXDcRDOoTINlcI:b-c3uxqo) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe 0xDeadBeaf or 0x12345678 ?
</blockquote></details>

Hi @ldorau ,

I perfer to enable the highest bit, so either 0xDeadBeaf or 0x87654321 is OK for me.
By the way, I can change it 0x87654321 if you want


<!-- Sent from Reviewable.io -->

2021-01-25 08:34 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 16 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRsfOLM-KAOUtni-HbA:b-r36yek) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau ,

I perfer to enable the highest bit, so either 0xDeadBeaf or 0x87654321 is OK for me.
By the way, I can change it 0x87654321 if you want
</blockquote></details>

0x87654321 is OK for me


<!-- Sent from Reviewable.io -->

2021-01-25 08:39 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 15 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/common/test-common.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXsdGs30xBCwqpWhmz:-MRsgiPr3JpW0bm3-VY6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/tests/unit/common/test-common.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

0x87654321 is OK for me
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-25 08:41 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 16 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)



<!-- Sent from Reviewable.io -->

2021-01-25 08:54 UTC, ldorau reviewed
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 17 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/conn.c, line 421 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfYRw12gF2ambvqd2x:-MRsjw8J2gVwrcTd_wMt:btg7gjc) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/conn.c#L421)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi ,

I actually used tabs instead of spaces.  Is it OK?
</blockquote></details>

There are 4 spaces in each of three above lines, but there should be no spaces at all.


<!-- Sent from Reviewable.io -->

2021-01-25 09:11 UTC, yangx-jy commented
___
*[src/conn.c, line 421 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfYRw12gF2ambvqd2x:-MRsmszA2akYjyFL2f6G:b5raeqc) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/conn.c#L421)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There are 4 spaces in each of three above lines, but there should be no spaces at all.
</blockquote></details>

Sorry, I read code in the wrong place.

Done.


<!-- Sent from Reviewable.io -->

2021-01-25 09:30 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 17 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-25 10:19 UTC, ldorau requested changes
> Reviewed 2 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 17 of 21 files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[tests/unit/conn/conn-completion_get.c, line 181 at r4](https://reviewable.io/reviews/pmem/rpma/713#-MRt1rG7ENdkKScA40Z_:-MRt1rG7ENdkKScA40Za:bv0wkh0) ([raw file](https://github.com/pmem/rpma/blob/f31a18327768336a4502cad23d703ca7802ffaf5/tests/unit/conn/conn-completion_get.c#L181)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
> 	enum ibv_wc_opcode opcodes[] = {
> 			IBV_WC_RDMA_READ,
> 			IBV_WC_RDMA_WRITE,
> 			IBV_WC_SEND,
> 			IBV_WC_RECV,
> 			IBV_WC_RECV
> 	};
> 	enum rpma_op ops[] = {
> 			RPMA_OP_READ,
> 			RPMA_OP_WRITE,
> 			RPMA_OP_SEND,
> 			RPMA_OP_RECV,
> 			RPMA_OP_RECV
> 	};
> 	unsigned flags[] = {
> 		0,
> 		0,
> 		0,
> 		0,
> 		IBV_WC_WITH_IMM
> 	};
> ```
</details>


Maybe I do not understand something, but shouldn't it be like that?

```
	enum ibv_wc_opcode opcodes[] = {
			IBV_WC_RDMA_READ,
			IBV_WC_RDMA_WRITE,
			IBV_WC_SEND,
			IBV_WC_SEND,
			IBV_WC_RECV
	};
	enum rpma_op ops[] = {
			RPMA_OP_READ,
			RPMA_OP_WRITE,
			RPMA_OP_SEND,
			RPMA_OP_SEND,
			RPMA_OP_RECV
	};
	unsigned flags[] = {
		0,
		0,
		0,
		IBV_WC_WITH_IMM,
		0
	};
```

e.g. the second send op with `IBV_WC_WITH_IMM` ?


<!-- Sent from Reviewable.io -->

2021-01-25 11:17 UTC, ldorau reviewed
> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-01-25 11:42 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[examples/run-all-on-SoftRoCE.sh, line 102 at r5](https://reviewable.io/reviews/pmem/rpma/713#-MRtLRA_7CxXXc06akop:-MRtLRAaA_sPS_66741H:bg2cpvb) ([raw file](https://github.com/pmem/rpma/blob/b42c7e04ebc22004aa59118ce9660e398adcc58a/examples/run-all-on-SoftRoCE.sh#L102)):*
> ```
> $VLD_SCMD
> ```

`$VLD_CCMD`


<!-- Sent from Reviewable.io -->

2021-01-25 11:53 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-01-25 13:33 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 13 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 102 at r5](https://reviewable.io/reviews/pmem/rpma/713#-MRtLRA_7CxXXc06akop:-MRtfkdf3L6k5sEVI_j1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b42c7e04ebc22004aa59118ce9660e398adcc58a/examples/run-all-on-SoftRoCE.sh#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> $VLD_SCMD
> ```

`$VLD_CCMD`
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-completion_get.c, line 181 at r4](https://reviewable.io/reviews/pmem/rpma/713#-MRt1rG7ENdkKScA40Z_:-MRtfsws4nkBeLuHWcp2:b-10yxuj) ([raw file](https://github.com/pmem/rpma/blob/f31a18327768336a4502cad23d703ca7802ffaf5/tests/unit/conn/conn-completion_get.c#L181)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	enum ibv_wc_opcode opcodes[] = {
> 			IBV_WC_RDMA_READ,
> 			IBV_WC_RDMA_WRITE,
> 			IBV_WC_SEND,
> 			IBV_WC_RECV,
> 			IBV_WC_RECV
> 	};
> 	enum rpma_op ops[] = {
> 			RPMA_OP_READ,
> 			RPMA_OP_WRITE,
> 			RPMA_OP_SEND,
> 			RPMA_OP_RECV,
> 			RPMA_OP_RECV
> 	};
> 	unsigned flags[] = {
> 		0,
> 		0,
> 		0,
> 		0,
> 		IBV_WC_WITH_IMM
> 	};
> ```

Maybe I do not understand something, but shouldn't it be like that?

```
	enum ibv_wc_opcode opcodes[] = {
			IBV_WC_RDMA_READ,
			IBV_WC_RDMA_WRITE,
			IBV_WC_SEND,
			IBV_WC_SEND,
			IBV_WC_RECV
	};
	enum rpma_op ops[] = {
			RPMA_OP_READ,
			RPMA_OP_WRITE,
			RPMA_OP_SEND,
			RPMA_OP_SEND,
			RPMA_OP_RECV
	};
	unsigned flags[] = {
		0,
		0,
		0,
		IBV_WC_WITH_IMM,
		0
	};
```

e.g. the second send op with `IBV_WC_WITH_IMM` ?
</blockquote></details>

Hi @ldorau 

For ibv_post_send() with IBV_WR_SEND_WITH_IMM, ibv_poll_cq() only gets the value of wc_flags(i.e. IBV_WC_WITH_IMM) but cannot get the vaule of imm_data.
For ibv_post_recv(), ibv_poll_cq() can get the value of wc_flags(i.e. IBV_WC_WITH_IMM) and the value of imm_data.
According to above behaviors, I test wc_flags and imm_data by recv opeartion.
I am not sure if it is an expected behavior, do you know this rule or behavior?
By the way, I will try to look into the kernel code tomorrow.


<!-- Sent from Reviewable.io -->

2021-01-25 15:25 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/unit/conn/conn-completion_get.c, line 181 at r4](https://reviewable.io/reviews/pmem/rpma/713#-MRt1rG7ENdkKScA40Z_:-MRu82tXB9AuHfqfGAkW:bucjrzo) ([raw file](https://github.com/pmem/rpma/blob/f31a18327768336a4502cad23d703ca7802ffaf5/tests/unit/conn/conn-completion_get.c#L181)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 

For ibv_post_send() with IBV_WR_SEND_WITH_IMM, ibv_poll_cq() only gets the value of wc_flags(i.e. IBV_WC_WITH_IMM) but cannot get the vaule of imm_data.
For ibv_post_recv(), ibv_poll_cq() can get the value of wc_flags(i.e. IBV_WC_WITH_IMM) and the value of imm_data.
According to above behaviors, I test wc_flags and imm_data by recv opeartion.
I am not sure if it is an expected behavior, do you know this rule or behavior?
By the way, I will try to look into the kernel code tomorrow.
</blockquote></details>

Ah, yes, of course, you are verifying the _completion_ of the RECV operation. I see now. All is OK.


<!-- Sent from Reviewable.io -->

2021-01-27 09:40 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-01-29 07:30 UTC, yangx-jy commented
___
*[tests/unit/conn/conn-completion_get.c, line 181 at r4](https://reviewable.io/reviews/pmem/rpma/713#-MRt1rG7ENdkKScA40Z_:-MSBzwuM-3g21G2fRndC:b-wx93r4) ([raw file](https://github.com/pmem/rpma/blob/f31a18327768336a4502cad23d703ca7802ffaf5/tests/unit/conn/conn-completion_get.c#L181)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, yes, of course, you are verifying the _completion_ of the RECV operation. I see now. All is OK.
</blockquote></details>

Hi @ldorau

According to the IB Architecture Specification, the value of imm_data can only be placed in the receive Completion Queue Element :
```
5.2.11 IMMEDIATE DATA EXTENDED TRANSPORT HEADER (ImmDt) - 4 BYTES
"Immediate Data (ImmDt) contains data that is placed in the receive
 Completion Queue Element (CQE). The ImmDt is only allowed in SEND or
 RDMA WRITE packets with Immediate Data."

```
I also confirm that kernel follows the rule, so I will add another check in rpma_conn_completion_get(), like this:
```
/*
 * The value of imm_data can only be placed in the receive Completion Queue Element.
 */
if ((cmpl->op == RPMA_OP_RECV) && (cmpl->flags & IBV_WC_WITH_IMM))
        cmpl->imm = ntohl(wc.imm_data);
```


<!-- Sent from Reviewable.io -->

2021-01-29 07:30 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/conn.c, line 421 at r2](https://reviewable.io/reviews/pmem/rpma/713#-MRfYRw12gF2ambvqd2x:-MSC2Ggf4bjbAVUElL4p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fba37496b50f749c88fcdc769f7e5670e3a1b1d2/src/conn.c#L421)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Sorry, I read code in the wrong place.

Done.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-01 09:30 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: 19 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-02 07:55 UTC, yangx-jy reviewed
Hi all,

I have resolved all the comments.  Could you review the patchset again?
By the way, I have written the new rpma_{write,write_atomic}_with_imm() and will send them after the patchset is merged.

Best Regards,
Xiao Yang

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713#-:-MSCBIkf96moccPKcGNr:b-voxhxz)* status: 19 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-02 08:19 UTC, ldorau commented
> I have resolved all the comments. Could you review the patchset again?
> 

Hi @yangx-jy, we have a lot of work to do until the Friday before the release of https://github.com/pmem/fio, so we probably won't be able to do it until Friday or Monday.

2021-02-02 08:25 UTC, yangx-jy reviewed
@ldorau 

Got it, thanks a lot for your explanation.
Don't worry, I will wait for you. 

Best Regards,
Xiao Yang

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713#-:-MSWpKC61UDZnnJ5Efa8:b-zfc2mo)* status: 19 of 21 files reviewed, 12 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-03 22:58 UTC, janekmi reviewed
> Reviewed 7 of 9 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-02-04 01:41 UTC, yangx-jy commented
___
*[src/conn.c, line 539 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXvTWi9gtCUSsySdt6:-MSefzIk9BwVFsU_gbPK:bymr0ds) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/conn.c#L539)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hi @janekmi 

1) Is there any detailed suggestion to improve the code?
2) Could we improve the code as a separate patch?

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-02-04 15:30 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713#-:-MShehvNEYo_Dju6QBtf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

___
*[src/conn.c, line 539 at r1](https://reviewable.io/reviews/pmem/rpma/713#-MQXvTWi9gtCUSsySdt6:-MShdQMw8zCUP6V7QPD2:b-hthfs8) ([raw file](https://github.com/pmem/rpma/blob/70830afd3ee1c0695d8adc8a0735975ee1de4bfd/src/conn.c#L539)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

1) Is there any detailed suggestion to improve the code?
2) Could we improve the code as a separate patch?

Best Regards,
Xiao Yang
</blockquote></details>

Sadly @grom72 (who is our architect) cannot discuss this topic with us currently.
Luckily, there is not much to discuss. I expect maybe a discussion about passing the whole `wc_flags` outside vs passing only information about the presence of the immediate data e.g. `bool imm_present`. So, not much of a difference implementation-wise.

@grom72 and I agreed to merge it as is and discuss it and optionally adjust it, hopefully, next week.


<!-- Sent from Reviewable.io -->

2021-02-04 21:21 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-04 21:21 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/713#-:-MSiuzbsDCnBrvilawsH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-04 21:22 UTC, merged

2021-02-05 03:01 UTC, yangx-jy commented
Hi @ldorau @janekmi @grom72 

Thanks a lot for reviewing the patchset.
In addtion,  thank @ldorau for fixing some compatible issues.

Best Regards,
Xiao Yang





<!-- Sent from Reviewable.io -->