test: add rpma_utils_ibv_context_is_odp_capable multithreaded test
pmem/rpma pull request #771
Opened 2021-01-26 09:56 UTC by ewanglong

2021-01-28 07:31 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MS6tiRd1dVD7fLYb8C8:-MS6tiRd1dVD7fLYb8C9:b-n6khor) (no related file):*
Please rebase

---
___
*[tests/cmake/ctest_helpers.cmake, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6miDn15IhlkMdxBJG:-MS6miDo0RKqEFFJV-yB:b-5enewv) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L202)):*
> ```
> 		elseif("${TEST_NAME}" MATCHES "multithreaded.*" AND "${TEST_CASE}" STREQUAL "0")
> 			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_case_${TEST_CASE}.cmake)
> ```


I suggest doing that in a more general way which can be used by many groups of tests (not only for `"multithreaded.*")` by adding the `GROUP_SCRIPT` option (of the boolean type) at the beginning of this function:

```
function(add_test_generic)
	set(options GROUP_SCRIPT)
	....
```

and replacing the above two lines with the following ones:

```
		elseif(TEST_GROUP_SCRIPT)
			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_case_${TEST_CASE}.cmake)
```

and you will have to add this `GROUP_SCRIPT` option in `function(add_multithreaded)`.
___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MS6r_tkD8dPCVFu5CQV:b-khgr6w) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
> ```
> add_test_generic(NAME ${target} CASE 0)
> ```

```
	add_test_generic(NAME ${target} GROUP_SCRIPT CASE ${TEST_CASE})
```


<!-- Sent from Reviewable.io -->

2021-01-28 08:36 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 193 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS77NWw3SQ2kpd6bLLL:-MS77NWw3SQ2kpd6bLLM:b-e3qsq2) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L193)):*
> ```CMake
> 
> function(add_test_generic)
> 	set(oneValueArgs NAME CASE SCRIPT)
> ```

`set(options GROUP_SCRIPT)` - see below
___
*[tests/cmake/ctest_helpers.cmake, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS77U-qDA9slLLR_Jbp:-MS77U-qDA9slLLR_Jbq:b9vx9gk) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L195)):*
> ```
> cmake_parse_arguments(TEST "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
> ```

```
	cmake_parse_arguments(TEST "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
```
___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MS76c6rBjtypP4Wxj-P:bxmji62) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> add_test_generic(NAME ${target} CASE 0)
> ```

```
	add_test_generic(NAME ${target} GROUP_SCRIPT CASE ${TEST_CASE})
```
</blockquote></details>

Rather:

```
add_test_generic(NAME ${target} GROUP_SCRIPT CASE ${MULTITHREADED_CASE})
```


<!-- Sent from Reviewable.io -->

2021-02-04 16:18 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MShp6w7D4umaEyk1cet:b-wdw533) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rather:

```
add_test_generic(NAME ${target} GROUP_SCRIPT CASE ${MULTITHREADED_CASE})
```

</blockquote></details>

A nifty idea. But I'm not sure what we want to achieve here.

@ewanglong can you elaborate on what the idea is? Why you need many "test cases" when rest of the PR suggests you are just adding another test?


<!-- Sent from Reviewable.io -->

2021-02-04 16:26 UTC, janekmi requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqvu72sJ0horgQX5L:-MShqvu72sJ0horgQX5M:b-v39iov) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L71)):*
> ```C
> 		fprintf(stderr, "get ibv context failed");
> 		exit(-1);
> 	}
> ```

I think it might be a good idea to call here once `rpma_utils_ibv_context_is_odp_capable()` synchronously and store the result in the thread's data e.g. `p_thread_args->is_odp_supported_exp` (where 'exp' stands for expected). So, later each of the threads will be able to validate if the result is not affected by calling the API concurrently.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqWCF6gCqnn0DLQJ7:-MShqWCF6gCqnn0DLQJ8:b-jtmejn) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L77)):*
> ```C
> 	if (p_threads == NULL) {
> 		fprintf(stderr, "malloc failed");
> 		exit(-1);
> ```

You have to handle this differently. Please see the #849.


<!-- Sent from Reviewable.io -->

2021-02-04 21:40 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MSiwpfu6or0xz1-RcFu:blgv8go) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A nifty idea. But I'm not sure what we want to achieve here.

@ewanglong can you elaborate on what the idea is? Why you need many "test cases" when rest of the PR suggests you are just adding another test?
</blockquote></details>

It is just how our cmake test framework works ... and here we want to have as few the same cmake test scripts as possible.


<!-- Sent from Reviewable.io -->

2021-02-04 23:36 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MSjOtMp9dHMVsxsViQ9:btvzjjx) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is just how our cmake test framework works ... and here we want to have as few the same cmake test scripts as possible.
</blockquote></details>

Do we have the same solution for our unit tests?


<!-- Sent from Reviewable.io -->

2021-02-05 02:34 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MSk17qvA3yro84NfhPP:b-32yohw) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we have the same solution for our unit tests?
</blockquote></details>

I considered some of cases are grouped together same script e.g run_case_0.cmake. For others, they may be ran by run_case_1.cmake, run_case_2.cmake etc.


<!-- Sent from Reviewable.io -->

2021-02-05 03:47 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6miDn15IhlkMdxBJG:-MSkIMfV88hak7Fjjdcw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L202)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		elseif("${TEST_NAME}" MATCHES "multithreaded.*" AND "${TEST_CASE}" STREQUAL "0")
> 			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_case_${TEST_CASE}.cmake)
> ```


I suggest doing that in a more general way which can be used by many groups of tests (not only for `"multithreaded.*")` by adding the `GROUP_SCRIPT` option (of the boolean type) at the beginning of this function:

```
function(add_test_generic)
	set(options GROUP_SCRIPT)
	....
```

and replacing the above two lines with the following ones:

```
		elseif(TEST_GROUP_SCRIPT)
			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_case_${TEST_CASE}.cmake)
```

and you will have to add this `GROUP_SCRIPT` option in `function(add_multithreaded)`.
</blockquote></details>

Done.
___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MSkIJ5v4GGj8kZc2veJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

I considered some of cases are grouped together same script e.g run_case_0.cmake. For others, they may be ran by run_case_1.cmake, run_case_2.cmake etc.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 03:47 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS77U-qDA9slLLR_Jbp:-MSkIOUD9-HqCNLXaT1H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L195)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> cmake_parse_arguments(TEST "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
> ```

```
	cmake_parse_arguments(TEST "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 03:47 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 193 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS77NWw3SQ2kpd6bLLL:-MSkIPGh3gxL4mg9SCdv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L193)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`set(options GROUP_SCRIPT)` - see below
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 03:48 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MS6tiRd1dVD7fLYb8C8:-MSkIREM3ntj--a8-Lbg:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-02-05 07:06 UTC, ldorau requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/cmake/ctest_helpers.cmake, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MS6r_tkD8dPCVFu5CQU:-MSl-FuLBxM_OPSGV4l_:b-xn77pg) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/cmake/ctest_helpers.cmake#L248)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi Yes, see this:

```
	if("${TEST_SCRIPT}" STREQUAL "")
		if("${TEST_CASE}" STREQUAL "")
			set(TEST_CASE "0")
			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../../cmake/run_default.cmake)
```
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqvu72sJ0horgQX5L:-MSl-b2zB070y_B8idq8:b32v57) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it might be a good idea to call here once `rpma_utils_ibv_context_is_odp_capable()` synchronously and store the result in the thread's data e.g. `p_thread_args->is_odp_supported_exp` (where 'exp' stands for expected). So, later each of the threads will be able to validate if the result is not affected by calling the API concurrently.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-02-05 07:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqWCF6gCqnn0DLQJ7:-MSl-rg71QVEWW3SOPQI:b32v57) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to handle this differently. Please see the #849.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-02-05 07:28 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqWCF6gCqnn0DLQJ7:-MSl4yqm6--o7rLtRH31:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 07:29 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqvu72sJ0horgQX5L:-MSl5-iQ4C4Wg-1rMFr5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 08:27 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/771#-MShqWCF6gCqnn0DLQJ7:-MSlHgUC6mCbi-Oys4Nk:b-970gsn) ([raw file](https://github.com/pmem/rpma/blob/abb892cbdd233217173ea6e5ac399ea7bc7064a3/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L77)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There was another bug in #849: `threads_args` and `p_threads` are not freed on success. Please fix it according to https://github.com/pmem/rpma/pull/857 .


<!-- Sent from Reviewable.io -->

2021-02-05 08:51 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 74 at r3](https://reviewable.io/reviews/pmem/rpma/771#-MSlMk238agAvxfYCUKS:-MSlMk238agAvxfYCUKT:bhkcgog) ([raw file](https://github.com/pmem/rpma/blob/814dc6ef118df2547574e0c415d2ce8e79107fd7/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L74)):*
> ```
> &dev);
> ```

4 tabs less, please  (then it will start below `addr` having tabs consisting of 8 spaces)
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 84 at r3](https://reviewable.io/reviews/pmem/rpma/771#-MSlNNZk6lCg6f1H7JSx:-MSlNNZk6lCg6f1H7JSy:b-gnakps) ([raw file](https://github.com/pmem/rpma/blob/814dc6ef118df2547574e0c415d2ce8e79107fd7/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L84)):*
> ```
> "check odp capability failed: %s\n");
> ```

one argument is missing here


<!-- Sent from Reviewable.io -->

2021-02-05 08:58 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 74 at r3](https://reviewable.io/reviews/pmem/rpma/771#-MSlMk238agAvxfYCUKS:-MSlPUlg3Z_qPGUPODYu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/814dc6ef118df2547574e0c415d2ce8e79107fd7/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L74)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> &dev);
> ```

4 tabs less, please  (then it will start below `addr` having tabs consisting of 8 spaces)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 08:58 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 84 at r3](https://reviewable.io/reviews/pmem/rpma/771#-MSlNNZk6lCg6f1H7JSx:-MSlPYtB0Qzxw1Mhr1Xm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/814dc6ef118df2547574e0c415d2ce8e79107fd7/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L84)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "check odp capability failed: %s\n");
> ```

one argument is missing here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 09:02 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 106 at r3](https://reviewable.io/reviews/pmem/rpma/771#-MSlOvi_8C9ZD7Fsz3q1:-MSlOvi_8C9ZD7Fsz3q2:b-56op0t) ([raw file](https://github.com/pmem/rpma/blob/814dc6ef118df2547574e0c415d2ce8e79107fd7/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L106)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	for (i = 0; i < thread_num; i++) {
> 		threads_args[i].thread_num = i;
> 		threads_args[i].dev = dev;
> 		threads_args[i].is_odp_supported_exp = is_odp_supported;
> 		if ((ret = pthread_create(&p_threads[i], NULL, thread_main,
> ```
</details>


The `threads_args` structure should be filled first in a separate loop:

```
	for (i = 0; i < thread_num; i++) {
		threads_args[i].thread_num = i;
		threads_args[i].dev = dev;
		threads_args[i].is_odp_supported_exp = is_odp_supported;
	}
```

and all threads should be started later in a separate loop:

```
	for (i = 0; i < thread_num; i++) {
		if ((ret = pthread_create(&p_threads[i], NULL, thread_main,
        ...
```


<!-- Sent from Reviewable.io -->

2021-02-05 09:04 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-05 09:05 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/771#-MSlR41z37D44jDKPyHf:-MSlR42-3y9IxWCFDaSU:bekcqa6) ([raw file](https://github.com/pmem/rpma/blob/47bb732370b09dcd15a3fc282f54e63f5a754622/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L125)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> 	return 0;
> err_free_threads_args:
> 	free(threads_args);
> err_free_p_threads:
> 	free(p_threads);
> 	return -1;
> ```
</details>


`threads_args` and `p_threads` are not freed on success. Please fix it according to #857 .


<!-- Sent from Reviewable.io -->

2021-02-05 09:17 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/771#-MSlR41z37D44jDKPyHf:-MSlTqQ_BkfHAjCUb6ew:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/47bb732370b09dcd15a3fc282f54e63f5a754622/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	return 0;
> err_free_threads_args:
> 	free(threads_args);
> err_free_p_threads:
> 	free(p_threads);
> 	return -1;
> ```

`threads_args` and `p_threads` are not freed on success. Please fix it according to #857 .
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-05 09:33 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 99 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSlXH_c8b-yQZt090jF:-MSlXH_c8b-yQZt090jG:b6bja43) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L99)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 	if (threads_args == NULL) {
> 		fprintf(stderr, "malloc failed");
> 		goto err_free_p_threads;
> 	}
> ```
</details>


`ret = -1;` is missing before `goto`


<!-- Sent from Reviewable.io -->

2021-02-05 10:14 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 120 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSlfnii6YwWo_fq-icu:-MSlfnii6YwWo_fq-icv:b90r0g9) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L120)):*
> ```
> ret = -1;
> ```

`break;` is missing at the end


<!-- Sent from Reviewable.io -->

2021-02-05 11:38 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 42 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSly2ll5_UYOauhH2k2:-MSly2ll5_UYOauhH2k3:boeb4i1) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L42)):*
> ```C
> 		exit(-1);
> 	} else if (p_thread_args->is_odp_supported_exp != is_odp_supported) {
> 		fprintf(stderr, "[thread #%d] %s is not expected: \
> ```

is not expected -> returned an unexpected value
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 42 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSlyCoO9y3k7rNTxPa1:-MSlyCoO9y3k7rNTxPa2:bns9hlw) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L42)):*
> ```C
> 		exit(-1);
> 	} else if (p_thread_args->is_odp_supported_exp != is_odp_supported) {
> 		fprintf(stderr, "[thread #%d] %s is not expected: \
> ```

You do not have to break strings. Just start the line with the string so it can be as long as required e.g.:

```c
} else if (p_thread_args->is_odp_supported_exp != is_odp_supported) {
    fprintf(stderr,
        "[thread #%d] %s is not expected: is_odp_supported = %d, is_odp_supported_exp = %d\n",
        p_thread_args->thread_num, api_name,
        is_odp_supported, p_thread_args->is_odp_supported_exp);
    exit(-1);
}
```


<!-- Sent from Reviewable.io -->

2021-02-05 11:49 UTC, janekmi reviewed
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-05 11:55 UTC, janekmi requested changes
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 203 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm0jXg6sHB-7_FW1cp:-MSm0jXg6sHB-7_FW1cq:bczk0m8) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L203)):*
> ```CMake
> 			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../../cmake/run_default.cmake)
> 		elseif(TEST_GROUP_SCRIPT)
> 			set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_case_${TEST_CASE}.cmake)
> ```

I would expect the `GROUP_SCRIPT` to have a default for a group e.g. `tests/multithreaded/run_group.cmake`
So this line would look like e.g.:

```cmake
set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_group.cmake)
```
___
*[tests/cmake/ctest_helpers.cmake, line 225 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm2-Uy38O4xtM84q4i:-MSm2-Uy38O4xtM84q4j:b-liug8v) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L225)):*
> ```CMake
> function(add_multithreaded)
> 	set(options USE_LIBIBVERBS)
> 	set(oneValueArgs NAME BIN CASE)
> ```

`CASE` is not needed.
___
*[tests/cmake/ctest_helpers.cmake, line 249 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm1wkjE1-Uf2MldtNI:-MSm1wkjE1-Uf2MldtNJ:b-ecahb7) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L249)):*
> ```CMake
> 	endif()
> 
> 	add_test_generic(NAME ${target} GROUP_SCRIPT CASE ${MULTITHREADED_CASE})
> ```

`CASE ...` is not needed here.
___
*[tests/multithreaded/utils/CMakeLists.txt, line 12 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm1KqC9_b1bWFwFq_i:-MSm1KqDAbWuaV-C1oEG:b-j8ihoz) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/CMakeLists.txt#L12)):*
> ```CMake
> 
> add_multithreaded(NAME utils BIN rpma_utils_get_ibv_context
> 	CASE 0
> ```

`CASE 0` does not introduce any new information and according to our plan, I do not expect to have multiple cases here.


<!-- Sent from Reviewable.io -->

2021-02-08 06:46 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 99 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSlXH_c8b-yQZt090jF:-MT-Nxj-EBlbjY67_YWy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (threads_args == NULL) {
> 		fprintf(stderr, "malloc failed");
> 		goto err_free_p_threads;
> 	}
> ```

`ret = -1;` is missing before `goto`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 06:46 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 120 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSlfnii6YwWo_fq-icu:-MT-O3Fd0uJy3IEzWLpc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ret = -1;
> ```

`break;` is missing at the end
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 06:50 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 42 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSlyCoO9y3k7rNTxPa1:-MT-Oyr0BhxsEN3JS5s8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not have to break strings. Just start the line with the string so it can be as long as required e.g.:

```c
} else if (p_thread_args->is_odp_supported_exp != is_odp_supported) {
    fprintf(stderr,
        "[thread #%d] %s is not expected: is_odp_supported = %d, is_odp_supported_exp = %d\n",
        p_thread_args->thread_num, api_name,
        is_odp_supported, p_thread_args->is_odp_supported_exp);
    exit(-1);
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 06:51 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 203 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm0jXg6sHB-7_FW1cp:-MT-P9Jf8pF2gr1Pukvs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L203)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would expect the `GROUP_SCRIPT` to have a default for a group e.g. `tests/multithreaded/run_group.cmake`
So this line would look like e.g.:

```cmake
set(cmake_script ${CMAKE_CURRENT_SOURCE_DIR}/../run_group.cmake)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 06:52 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 225 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm2-Uy38O4xtM84q4i:-MT-PLoi4oIVxkGOUWwd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L225)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`CASE` is not needed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-08 06:54 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 225 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm2-Uy38O4xtM84q4i:-MT-PcKHEf_DLXULZVj3:bk4w3m9) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L225)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

changed to add_test_generic(NAME ${target} GROUP_SCRIPT CASE 0). Otherwise there will be compile error by this line in funtion add_test_generic: 
	if("${TEST_TRACERS}" STREQUAL "")
		add_test_common(${TEST_NAME} none ${TEST_CASE} ${cmake_script})


<!-- Sent from Reviewable.io -->

2021-02-08 07:11 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 3 of 4 files reviewed, 8 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 42 at r6](https://reviewable.io/reviews/pmem/rpma/771#-MT-TP9pAb1pITiliR5e:-MT-TP9pAb1pITiliR5f:b9rjw3q) ([raw file](https://github.com/pmem/rpma/blob/7878d00c290430c0a3f502cf06ec618151e3393b/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L42)):*
> ```
> fprintf(stderr, "[thread #%d] %s returned an unexpected value: is_odp_supported = %d, is_odp_supported_exp = %d\n",
> ```

A long string has to begin a line:

```
fprintf(stderr,
        "[thread #%d] %s returned an unexpected value: is_odp_supported = %d, is_odp_supported_exp = %d\n",
```


<!-- Sent from Reviewable.io -->

2021-02-08 08:58 UTC, janekmi requested changes
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 57 at r7](https://reviewable.io/reviews/pmem/rpma/771#-MT-qmDq3sbVxOSqbmwE:-MT-qmDq3sbVxOSqbmwF:b-tu1781) ([raw file](https://github.com/pmem/rpma/blob/7156f630bfed2b1c7b024733f8e1ae3329401af5/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L57)):*
> ```C
> 	if (argc < 3) {
> 		fprintf(stderr, "usage: %s <thread_num> <addr>\n", argv[0]);
> 		exit(-1);
> ```

return -1
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 77 at r7](https://reviewable.io/reviews/pmem/rpma/771#-MT-qnYP7S1bkDHHgXxD:-MT-qnYP7S1bkDHHgXxE:b-tu1781) ([raw file](https://github.com/pmem/rpma/blob/7156f630bfed2b1c7b024733f8e1ae3329401af5/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L77)):*
> ```C
> 	if (ret) {
> 		fprintf(stderr, "get ibv context failed");
> 		exit(-1);
> ```

return -1
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 85 at r7](https://reviewable.io/reviews/pmem/rpma/771#-MT-qrtN6k_-iDy9fJAO:-MT-qrtN6k_-iDy9fJAP:b-tu1781) ([raw file](https://github.com/pmem/rpma/blob/7156f630bfed2b1c7b024733f8e1ae3329401af5/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L85)):*
> ```C
> 	if (ret) {
> 		fprintf(stderr, "check odp capability failed");
> 		exit(-1);
> ```

return -1
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 92 at r7](https://reviewable.io/reviews/pmem/rpma/771#-MT-qwyN785ll55xGP0S:-MT-qwyN785ll55xGP0T:b-tu1781) ([raw file](https://github.com/pmem/rpma/blob/7156f630bfed2b1c7b024733f8e1ae3329401af5/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L92)):*
> ```C
> 	if (p_threads == NULL) {
> 		fprintf(stderr, "malloc failed");
> 		exit(-1);
> ```

return -1


<!-- Sent from Reviewable.io -->

2021-02-08 09:08 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 225 at r5](https://reviewable.io/reviews/pmem/rpma/771#-MSm2-Uy38O4xtM84q4i:-MT-sy94EP-N79bTE8Q8:b-hrpfk5) ([raw file](https://github.com/pmem/rpma/blob/aea310adc96930798b9fa50f8bdf278fcb355f9f/tests/cmake/ctest_helpers.cmake#L225)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

changed to add_test_generic(NAME ${target} GROUP_SCRIPT CASE 0). Otherwise there will be compile error by this line in funtion add_test_generic: 
	if("${TEST_TRACERS}" STREQUAL "")
		add_test_common(${TEST_NAME} none ${TEST_CASE} ${cmake_script})
</blockquote></details>

It should not be needed, but the `GROUP_SCRIPT` option should be added in another way.
Let's do it in a separate PR:

https://github.com/pmem/rpma/pull/865


<!-- Sent from Reviewable.io -->

2021-02-08 09:10 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MT-txJoABRMacoGiCCu:-MT-txJoABRMacoGiCCv:b-t5pxq6) (no related file):*
https://github.com/pmem/rpma/pull/865 should be merged before this PR.

---


<!-- Sent from Reviewable.io -->

2021-02-08 09:12 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-08 09:50 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-08 13:35 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MT-txJoABRMacoGiCCu:-MT0qbVp4CpvYRp_EAE0:b-n229su) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/pull/865 should be merged before this PR.
</blockquote></details>

Merged. The feature is ready to be used.

---


<!-- Sent from Reviewable.io -->

2021-02-08 14:02 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MT-txJoABRMacoGiCCu:-MT0wlAeEo3OX2znzCOD:bzb7h4z) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Merged. The feature is ready to be used.
</blockquote></details>

@ewanglong please rebase

---


<!-- Sent from Reviewable.io -->

2021-02-08 14:07 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 249 at r9](https://reviewable.io/reviews/pmem/rpma/771#-MT0xl4Y7kfCRf2wjBQV:-MT0xl4ZBAqxQHPeoGjg:byut2y1) ([raw file](https://github.com/pmem/rpma/blob/d5109da678ae76f36a9e81a0a0b23db18baaaf4c/tests/cmake/ctest_helpers.cmake#L249)):*
> ```
> add_test_generic(NAME ${target} GROUP_SCRIPT CASE 0)
> ```

`CASE 0` should be removed now:

`add_test_generic(NAME ${target} GROUP_SCRIPT)`


<!-- Sent from Reviewable.io -->

2021-02-09 16:13 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MT-txJoABRMacoGiCCu:-MT6ZL4w3ZoNM3s-eyVm:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@ewanglong please rebase
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-02-09 16:13 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/cmake/ctest_helpers.cmake, line 249 at r9](https://reviewable.io/reviews/pmem/rpma/771#-MT0xl4Y7kfCRf2wjBQV:-MT6ZRenEpRT3iOEYqH9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d5109da678ae76f36a9e81a0a0b23db18baaaf4c/tests/cmake/ctest_helpers.cmake#L249)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> add_test_generic(NAME ${target} GROUP_SCRIPT CASE 0)
> ```

`CASE 0` should be removed now:

`add_test_generic(NAME ${target} GROUP_SCRIPT)`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 21:15 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MT-txJoABRMacoGiCCu:-MT7dFUG3TqM818R0M0y:b6ozjrk) (no related file):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is still a conflict.

---
___
*[tests/cmake/ctest_helpers.cmake, line 249 at r9](https://reviewable.io/reviews/pmem/rpma/771#-MT0xl4Y7kfCRf2wjBQV:-MT7dVX042h1drcYqZ3w:b-lzoogb) ([raw file](https://github.com/pmem/rpma/blob/d5109da678ae76f36a9e81a0a0b23db18baaaf4c/tests/cmake/ctest_helpers.cmake#L249)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet - `CASE 0` is still there.


<!-- Sent from Reviewable.io -->

2021-02-10 12:38 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-10 14:54 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tools/perf/README.md, line 1 at r13](https://reviewable.io/reviews/pmem/rpma/771#-MTBQj_K-3xNNj0Vj6ny:-MTBQj_K-3xNNj0Vj6nz:b-490jvm) ([raw file](https://github.com/pmem/rpma/blob/dde2dff87c2732a5f64921ca97283921b32b8308/tools/perf/README.md#L1)):*
> ```Markdown
> # librpma Benchmarking Tools
> ```

You have something messed up. This file should not be part of your PR.


<!-- Sent from Reviewable.io -->

2021-02-11 06:46 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tools/perf/README.md, line 1 at r13](https://reviewable.io/reviews/pmem/rpma/771#-MTBQj_K-3xNNj0Vj6ny:-MTEmqAF-7y0hPE3gtVb:bz9r9r9) ([raw file](https://github.com/pmem/rpma/blob/dde2dff87c2732a5f64921ca97283921b32b8308/tools/perf/README.md#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have something messed up. This file should not be part of your PR.
</blockquote></details>

@janekmi All is OK with this PR. This is GitHub which has messed something up here.

See @ewanglong's branch: https://github.com/ewanglong/rpma/commits/rpma-78-2 - all is OK.

I bet if this PR would be rebased again on top of the current master, all excessive files would disapprear from this review.


<!-- Sent from Reviewable.io -->

2021-02-11 06:52 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tools/perf/README.md, line 1 at r13](https://reviewable.io/reviews/pmem/rpma/771#-MTBQj_K-3xNNj0Vj6ny:-MTEr0L6-UGEBRJBnuUX:b-hzmp05) ([raw file](https://github.com/pmem/rpma/blob/dde2dff87c2732a5f64921ca97283921b32b8308/tools/perf/README.md#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Oh no, something is WRONG indeed. @ewanglong see this: https://github.com/pmem/rpma/pull/771/commits

Please rebase your PR again on top of the current master.
</blockquote></details>

After rebase all should be OK, like on my branch: https://github.com/ldorau/rpma/commits/review-ewanglong-rpma-78-2


<!-- Sent from Reviewable.io -->

2021-02-11 06:52 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-11 07:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MTF2T9B9z-XYZf4GrFC:-MTF2T9B9z-XYZf4GrFD:b4q9kul) (no related file):*
Please fetch the current master and rebase your PR again

---


<!-- Sent from Reviewable.io -->

2021-02-18 01:26 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/771#-MTF2T9B9z-XYZf4GrFC:-MTmjg_Y4JA2OGioL_d1:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fetch the current master and rebase your PR again
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-02-19 09:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 76 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbFy48kJKTX9V1JRN:-MTtbFy48kJKTX9V1JRO:bzao44h) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L76)):*
> ```
> "get ibv context failed"
> ```

`rpma_utils_get_ibv_context() failed`
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 84 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbLE11qWeooqwlsKs:-MTtbLE11qWeooqwlsKt:bqqf89t) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L84)):*
> ```
> "check odp capability failed"
> ```

`rpma_utils_ibv_context_is_odp_capable() failed`
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 91 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbeQL3aiXW1BHYhg7:-MTtbeQL3aiXW1BHYhg8:b-13dce2) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L91)):*
> ```
> malloc
> ```

`malloc()`
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 98 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbheL0fwkYq9hFRdJ:-MTtbheL0fwkYq9hFRdK:b-5tt4sh) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L98)):*
> ```
> malloc
> ```

.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 112 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbRmC4lWKZ9x3ankk:-MTtbRmC4lWKZ9x3ankl:b-lzxkvd) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L112)):*
> ```
> a thread
> ```

`the thread`


<!-- Sent from Reviewable.io -->

2021-02-19 11:08 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 2 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771#-:-MTty_5f4z5QbwFzq3GZ:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-19 11:11 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771#-:-MTtz4ci65bGenGXR5pm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 76 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbFy48kJKTX9V1JRN:-MTtyt4uE1oje7Bd7r82:b-h8mhej) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L76)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "get ibv context failed"
> ```

`rpma_utils_get_ibv_context() failed`
</blockquote></details>

Will be fixed in a separate PR
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 84 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbLE11qWeooqwlsKs:-MTtyyGh4p-r_BtiOC_A:b-h8mhej) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L84)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "check odp capability failed"
> ```

`rpma_utils_ibv_context_is_odp_capable() failed`
</blockquote></details>

Will be fixed in a separate PR
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 91 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbeQL3aiXW1BHYhg7:-MTtz-K-3X_auxBJYLzu:b-h8mhej) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L91)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> malloc
> ```

`malloc()`
</blockquote></details>

Will be fixed in a separate PR
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 98 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbheL0fwkYq9hFRdJ:-MTtz0rb6Z8I7Imyvtsz:b-h8mhej) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> malloc
> ```

.
</blockquote></details>

Will be fixed in a separate PR
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 112 at r14](https://reviewable.io/reviews/pmem/rpma/771#-MTtbRmC4lWKZ9x3ankk:-MTtz2Sl8SjDbIy_MK34:b-h8mhej) ([raw file](https://github.com/pmem/rpma/blob/82a7a852b5f88db3b87bbef82af505ab936b9a99/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a thread
> ```

`the thread`
</blockquote></details>

Will be fixed in a separate PR


<!-- Sent from Reviewable.io -->

2021-02-19 11:11 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/771)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-02-19 11:11 UTC, merged