tools: set default direct_write_to_pmem by $REMOTE_JOB_MEM_PATH
pmem/rpma pull request #845
Opened 2021-02-04 02:02 UTC by yangx-jy

1) For PMEM((apm & no-DDIO) or (gpspm & DDIO)), enable
   $REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM by default.
2) For DRAM, disable $REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM by default.

Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

2021-02-04 16:31 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/845)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/rpma_fio_bench.sh, line 132 at r2](https://reviewable.io/reviews/pmem/rpma/845#-MShrjLG3L_QdR_54qo0:-MShrjLG3L_QdR_54qo1:bbuz9b3) ([raw file](https://github.com/pmem/rpma/blob/b13569cb82985825e32614eaa5f62a7d366e388e/tools/rpma_fio_bench.sh#L132)):*
> ```Shell
> 	if [ -n "$REMOTE_JOB_MEM_PATH" ]; then
> 		REMOTE_JOB_DEST="$REMOTE_JOB_MEM_PATH"
> 		REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM=1
> ```

The required *Direct Write to PMem* value for GPSPM is **false** and it is expected to be run against PMem.
So it is not a correct condition.

What problem are you solving here?


<!-- Sent from Reviewable.io -->

2021-02-05 01:14 UTC, yangx-jy commented
___
*[tools/rpma_fio_bench.sh, line 132 at r2](https://reviewable.io/reviews/pmem/rpma/845#-MShrjLG3L_QdR_54qo0:-MSji0SsDDQhfohGc4Fr:bbt5j20) ([raw file](https://github.com/pmem/rpma/blob/b13569cb82985825e32614eaa5f62a7d366e388e/tools/rpma_fio_bench.sh#L132)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The required *Direct Write to PMem* value for GPSPM is **false** and it is expected to be run against PMem.
So it is not a correct condition.

What problem are you solving here?
</blockquote></details>

Hi @janekmi 

Could you explain why GPSPM requires direct_write_to_pmem=0?
In my understanding, GPSPM should support direct_write_to_pmem=1 when DDIO is turn on.
The implementation of GPSPM is not achieved so it only supports direct_write_to_pmem=0 for now, is it right?

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-02-05 10:31 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/845)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/rpma_fio_bench.sh, line 132 at r2](https://reviewable.io/reviews/pmem/rpma/845#-MShrjLG3L_QdR_54qo0:-MSlhxesDi-qRGR9pPDx:b-cikl1p) ([raw file](https://github.com/pmem/rpma/blob/b13569cb82985825e32614eaa5f62a7d366e388e/tools/rpma_fio_bench.sh#L132)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

Could you explain why GPSPM requires direct_write_to_pmem=0?
In my understanding, GPSPM should support direct_write_to_pmem=1 when DDIO is turn on.
The implementation of GPSPM is not achieved so it only supports direct_write_to_pmem=0 for now, is it right?

Best Regards,
Xiao Yang
</blockquote></details>

No. APM is the default, the most performant way of achieving remote persistency. But APM **requires** `direct_write_to_pmem=1`. GPSPM is the last resort when you can not configure your system so your configuration is `direct_write_to_pmem=0` so you have to use GPSPM.

You can run GPSPM with `direct_write_to_pmem=1` but it is like using a bike when you have a car. It is suboptimal and TBH I think it might perform even worse than when `direct_write_to_pmem=0`.

But the final argument is: if you have `direct_write_to_pmem=1` there is no reason to use GPSPM.


<!-- Sent from Reviewable.io -->

2021-02-05 16:35 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/845)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/rpma_fio_bench.sh, line 132 at r2](https://reviewable.io/reviews/pmem/rpma/845#-MShrjLG3L_QdR_54qo0:-MSn07ZxAua78Cd3Vvaz:bt6x0ft) ([raw file](https://github.com/pmem/rpma/blob/b13569cb82985825e32614eaa5f62a7d366e388e/tools/rpma_fio_bench.sh#L132)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No. APM is the default, the most performant way of achieving remote persistency. But APM **requires** `direct_write_to_pmem=1`. GPSPM is the last resort when you can not configure your system so your configuration is `direct_write_to_pmem=0` so you have to use GPSPM.

You can run GPSPM with `direct_write_to_pmem=1` but it is like using a bike when you have a car. It is suboptimal and TBH I think it might perform even worse than when `direct_write_to_pmem=0`.

But the final argument is: if you have `direct_write_to_pmem=1` there is no reason to use GPSPM.
</blockquote></details>

Hi @janekmi 

It is confused for me.

I know there are two remote replication methods (APM and GPSPM).
1) The first method (APM) writes data into remote pmem by disabled DDIO and dedicated RDMA read operation.  I think current rpma has achieved it.
2) The second method (GPSPM) writes data into remote pmem by enabled DDIO, dedicated RDMA send operation (including instructions -- CLWB/SFENCE)and RDMA receive operation (including ACK).
Is my understanding right?

I cannot understand the role of direct_write_to_pmem.  direct_write_to_pmem=1 indicates that we can enable and disable DDIO on system and direct_write_to_pmem=0 indicates that we cannot do it, right?
If  direct_write_to_pmem=0, how to make data written into PMEM by GPSPM method?

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-02-10 13:50 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/845)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/rpma_fio_bench.sh, line 132 at r2](https://reviewable.io/reviews/pmem/rpma/845#-MShrjLG3L_QdR_54qo0:-MTB9cKB8kohTwb5fcaF:bvhjfbd) ([raw file](https://github.com/pmem/rpma/blob/b13569cb82985825e32614eaa5f62a7d366e388e/tools/rpma_fio_bench.sh#L132)):*
> The first method (APM) writes data into remote pmem by disabled DDIO and dedicated RDMA read operation.  I think current rpma has achieved it.
> The second method (GPSPM) writes data into remote pmem by enabled DDIO, dedicated RDMA send operation (including instructions -- CLWB/SFENCE)and RDMA receive operation (including ACK).
> Is my understanding right?

You are correct.

>  direct_write_to_pmem=1 indicates that we can enable and disable DDIO on system and direct_write_to_pmem=0 indicates that we cannot do it, right?

Yes.

> If direct_write_to_pmem=0, how to make data written into PMEM by GPSPM method?

- `direct_write_to_pmem` is related to **the possibility of doing the direct write to PMem by using the RDMA only**  (no caches, no DDIO on the RDMA, DMA, PCIe paths).
- `direct_write_to_pmem` says nothing about the possibility of achieving the local PMem persistency by doing e.g. `pmem_persist()` which is **possible always regardless of the DDIO status**.

The second point is leveraged by the GPSPM mechanism. So the server-side (the system which is a recipient of the write to PMem) can always use e.g. `pmem_persist()` to push the data to the ADR domain and making it effectively persistent.


<!-- Sent from Reviewable.io -->

2021-02-12 09:04 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/845)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-19 11:14 UTC, janekmi commented
@yangx-jy if you will have any second thoughts on this topic, please let me know. Closing for now.

2021-02-19 11:14 UTC, closed without merging