Implement rpma write with immediate data
pmem/rpma pull request #856
Opened 2021-02-05 02:41 UTC by yangx-jy

2021-02-05 08:50 UTC, yangx-jy reviewed
Hi @grom72 @ldorau @janekmi

1) From IB spec, rdma's atomic operation doesn't support imm_data.
2) As @grom72 metioned, rpma will enhance write atomic by introducing rdma's atomic operation.

According to above reasons, is it wrong to support imm_data for current rpma_write_atomic()?
Perhaps, I should remove the related code which make rpma_write_atomic() support imm_data.

Best Regards,
Xiao Yang 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856#-:-MSlLODc7y8nhYMQf2Qa:bmbookc)* status: 0 of 22 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-05 14:01 UTC, janekmi requested changes
> Reviewed 3 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 3 of 22 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/856#-MSmUcXe6f-702zu8WSp:-MSmUcXe6f-702zu8WSq:bby76m4) (no related file):*
I have discussed this topic with @grom72. The native atomic write, when it will happen, won't have a variant with immediate. So we cannot have it in our API. @yangx-jy please remove the `rpma_write_atomic_with_imm()`.

---


<!-- Sent from Reviewable.io -->

2021-02-05 15:41 UTC, janekmi requested changes
> Reviewed 8 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 7 of 21 files reviewed, 4 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 343 at r1](https://reviewable.io/reviews/pmem/rpma/856#-MSmUwF8DV6-NIzIX_hQ:-MSmUwF8DV6-NIzIX_hR:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/940a0b470da00bc0125c25dad6a85e05fc4cd73a/src/conn.c#L343)):*
> ```C
> {
> 	if (conn == NULL || dst == NULL || src == NULL || flags == 0)
> 	return RPMA_E_INVAL;
> ```

Indentation.
___
*[src/conn.c, line 601 at r1](https://reviewable.io/reviews/pmem/rpma/856#-MSmp9tZ1w_HqRyuQnh-:-MSmp9tZ1w_HqRyuQnh0:b-nze496) ([raw file](https://github.com/pmem/rpma/blob/940a0b470da00bc0125c25dad6a85e05fc4cd73a/src/conn.c#L601)):*
> ```C
> 	 */
> 	if ((cmpl->op == RPMA_OP_RECV) ||
> 		(cmpl->op == RPMA_OP_RECV_RDMA_WITH_IMM)) {
> ```

I think with one more tab it looks better. Please consider.
___
*[src/conn.c, line 602 at r1](https://reviewable.io/reviews/pmem/rpma/856#-MSmpVpw6nEia945fZn3:-MSmpVpw6nEia945fZn4:b-z0kp7q) ([raw file](https://github.com/pmem/rpma/blob/940a0b470da00bc0125c25dad6a85e05fc4cd73a/src/conn.c#L602)):*
> ```C
> 	if ((cmpl->op == RPMA_OP_RECV) ||
> 		(cmpl->op == RPMA_OP_RECV_RDMA_WITH_IMM)) {
> 		if (cmpl->flags & IBV_WC_WITH_IMM)
> ```

You are sure it is expected for both `IBV_WC_RECV` and `IBV_WC_RECV_RDMA_WITH_IMM`?


<!-- Sent from Reviewable.io -->

2021-02-05 15:45 UTC, janekmi reviewed
> Reviewed 3 of 22 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 14 of 21 files reviewed, 4 unresolved discussions (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-05 15:47 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 14 of 21 files reviewed, 4 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 602 at r1](https://reviewable.io/reviews/pmem/rpma/856#-MSmpVpw6nEia945fZn3:-MSmrhFr8VdDLvnDZZv8:b-fhx3oo) ([raw file](https://github.com/pmem/rpma/blob/940a0b470da00bc0125c25dad6a85e05fc4cd73a/src/conn.c#L602)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are sure it is expected for both `IBV_WC_RECV` and `IBV_WC_RECV_RDMA_WITH_IMM`?
</blockquote></details>

Hi @janekmi 

For send with imm_data, IBV_WC_RECV is expected.
For rdma write with imm_data, IBV_WC_RECV_RDMA_WITH_IMM is expected.
Do you think the condition is not correct here?

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-02-05 15:54 UTC, janekmi reviewed
> Reviewed 1 of 22 files at r1, 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 16 of 21 files reviewed, 5 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 564 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmtKoZ9kw-0p6zWHZJ:-MSmtKoZ9kw-0p6zWHZK:b-1t3h17) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/src/conn.c#L564)):*
> ```C
> 		RPMA_LOG_ERROR("unsupported wc.opcode == %d", wc.opcode);
> 		return RPMA_E_NOSUPP;
> 	}
> ```

@grom72 @ldorau @osalyk This switch-case looks dumb. We have to reconsider its existence.


<!-- Sent from Reviewable.io -->

2021-02-05 15:57 UTC, janekmi reviewed
> Reviewed 1 of 22 files at r1, 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 19 of 21 files reviewed, 6 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[examples/11-write-with-imm/README.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmttLq95IDJeTpKkf0:-MSmttLq95IDJeTpKkf1:blfg2mk) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/README.md#L9)):*
> ```Markdown
> - The server receives a message with immediate data from client.
> The immediate data is compared with the expected immediate data sent
> by the client as the private data during establishing the connection.
> ```

Why not just transfer the same data via write and immediate?
It would be a nice twist compared to what we have done for send with immediate.


<!-- Sent from Reviewable.io -->

2021-02-05 16:13 UTC, janekmi requested changes
> Reviewed 1 of 22 files at r1, 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[examples/11-write-with-imm/client.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmwIj20j_FNPABm9yv:-MSmwIj20j_FNPABm9yw:b-but9ng) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright (c) 2020-2021 Fujitsu */
> ```

2021 only.
___
*[examples/11-write-with-imm/client.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmvtiRAr3VQ9yrGlOo:-MSmvtiRAr3VQ9yrGlOp:b-jt3xxy) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L72)):*
> ```C
> 
> 	/* register the memory */
> 	ret = rpma_mr_reg(peer, src, KILOBYTE, RPMA_MR_USAGE_SEND, &src_mr);
> ```

RPMA_MR_USAFE_WRITE_SRC?
___
*[examples/11-write-with-imm/client.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmuxLl5y_NaInWpEgw:-MSmuxLl5y_NaInWpEgx:b-lcv0lk) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L80)):*
> ```C
> 	 * data for validation on the sever side
> 	 */
> 	struct rpma_conn_private_data src_pdata;
> ```

Why not just `pdata` as for example no 10?
___
*[examples/11-write-with-imm/client.c, line 88 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmvEaE0RKxtEr8vm6D:-MSmvEaE0RKxtEr8vm6E:b-pfthn3) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L88)):*
> ```C
> 
> 	/* obtain the remote memory description */
> 	struct rpma_conn_private_data dst_pdata;
> ```

We can reuse the structure. No need for having another one.
___
*[examples/11-write-with-imm/client.c, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmw1YT61ZoKVrBXdRq:-MSmw1YT61ZoKVrBXdRr:by1bfih) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L136)):*
> ```C
> 		fprintf(stderr,
> 			"an unexpected type of operation (%d != %d)\n",
> 			cmpl.op, RPMA_OP_SEND);
> ```

RPMA_OP_WRITE
___
*[examples/11-write-with-imm/server.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmwLSx5goBtm_-w2Ek:-MSmwLSy6bQyDynaDqlM:b-8k883n) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/server.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright (c) 2020-2021 Fujitsu */
> ```

2021?
___
*[examples/11-write-with-imm/server.c, line 91 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmwfeg3azsIlEO5Nfc:-MSmwfeg3azsIlEO5Nfd:ba7grv7) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/server.c#L91)):*
> ```C
> 
> 	/* prepare to receive a message with immediate data from the client */
> 	ret = rpma_conn_req_recv(req, dst_mr, 0, KILOBYTE, NULL);
> ```

`dst_mr` is the write destination, not a receive. You have to post a Receive Request using another buffer. It can be very small since it does not will carry any data in this example.
___
*[examples/11-write-with-imm/server.c, line 170 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmx4Dz7C0wfR44oALg:-MSmx4Dz7C0wfR44oALh:b-dtu2h0) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/server.c#L170)):*
> ```C
> 		ret = -1;
> 	} else {
> 		printf("receive a value %s with immediate data %u\n", dst,
> ```

a value %s was written with immediate data %u


<!-- Sent from Reviewable.io -->

2021-02-05 16:15 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 13 unresolved discussions (waiting on @yangx-jy)

___
*[src/conn.c, line 602 at r1](https://reviewable.io/reviews/pmem/rpma/856#-MSmpVpw6nEia945fZn3:-MSmyCtoBzmYUnzuO3oy:b-kic65h) ([raw file](https://github.com/pmem/rpma/blob/940a0b470da00bc0125c25dad6a85e05fc4cd73a/src/conn.c#L602)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

For send with imm_data, IBV_WC_RECV is expected.
For rdma write with imm_data, IBV_WC_RECV_RDMA_WITH_IMM is expected.
Do you think the condition is not correct here?

Best Regards,
Xiao Yang
</blockquote></details>

I was thinking for a while because having `IBV_WC_RECV_RDMA_WITH_IMM` indicates the same what `IBV_WC_WITH_IMM` so the letter one seems redundant in this case. But the documentation seems to support your implementation.

I have to do a hands-on. ;-)


<!-- Sent from Reviewable.io -->

2021-02-06 08:09 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 15 of 21 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/856#-MSmUcXe6f-702zu8WSp:-MSqNKPG1GdRiiK88f_h:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have discussed this topic with @grom72. The native atomic write, when it will happen, won't have a variant with immediate. So we cannot have it in our API. @yangx-jy please remove the `rpma_write_atomic_with_imm()`.
</blockquote></details>

Done.

---
___
*[examples/11-write-with-imm/client.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmwIj20j_FNPABm9yv:-MSqNL5T04nI1eRo4uPX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

2021 only.
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/client.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmvtiRAr3VQ9yrGlOo:-MSqNLbT7TG11ErnfuYa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L72)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

RPMA_MR_USAFE_WRITE_SRC?
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/client.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmuxLl5y_NaInWpEgw:-MSqNOwM34y0hHxsS_bf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why not just `pdata` as for example no 10?
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/client.c, line 88 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmvEaE0RKxtEr8vm6D:-MSqNSd2B6E5TN_85op3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We can reuse the structure. No need for having another one.
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/client.c, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmw1YT61ZoKVrBXdRq:-MSqNTMg3eAjCKGmrVd8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/client.c#L136)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

RPMA_OP_WRITE
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/server.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmwLSx5goBtm_-w2Ek:-MSqNYYR3p1da9HLYa9D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/server.c#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

2021?
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/server.c, line 91 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmwfeg3azsIlEO5Nfc:-MSqN_Gb5QGcxlgtzirl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/server.c#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`dst_mr` is the write destination, not a receive. You have to post a Receive Request using another buffer. It can be very small since it does not will carry any data in this example.
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/server.c, line 170 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmx4Dz7C0wfR44oALg:-MSqN_uZ8Rls1eSy_dvi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/examples/11-write-with-imm/server.c#L170)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a value %s was written with immediate data %u
</blockquote></details>

Done.
___
*[src/conn.c, line 343 at r1](https://reviewable.io/reviews/pmem/rpma/856#-MSmUwF8DV6-NIzIX_hQ:-MSqNabR0X15QaDdwAbw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/940a0b470da00bc0125c25dad6a85e05fc4cd73a/src/conn.c#L343)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.
___
*[src/conn.c, line 564 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmtKoZ9kw-0p6zWHZJ:-MSqNeyq0ZQRZvsqhyLO:b-etg3ls) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/src/conn.c#L564)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@grom72 @ldorau @osalyk This switch-case looks dumb. We have to reconsider its existence.
</blockquote></details>

Is there any detailed change?


<!-- Sent from Reviewable.io -->

2021-02-08 13:14 UTC, janekmi reviewed
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 16 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/conn.c, line 564 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmtKoZ9kw-0p6zWHZJ:-MT0lY674g6xQXVE04vC:b1945zh) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/src/conn.c#L564)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Is there any detailed change?
</blockquote></details>

Not for now. It is potentially a big change. I'm not sure we want to do this. @yangx-jy  ignore for now.


<!-- Sent from Reviewable.io -->

2021-02-08 15:03 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 16 of 21 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/conn.c, line 564 at r2](https://reviewable.io/reviews/pmem/rpma/856#-MSmtKoZ9kw-0p6zWHZJ:-MT19qsJ8WHeETaaWOka:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/0ccfa34ab93c9b908188463aa9e4d161c9929c72/src/conn.c#L564)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not for now. It is potentially a big change. I'm not sure we want to do this. @yangx-jy  ignore for now.
</blockquote></details>

OK


<!-- Sent from Reviewable.io -->

2021-02-08 19:06 UTC, osalyk reviewed
> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[examples/11-write-with-imm/client.c, line 77 at r3](https://reviewable.io/reviews/pmem/rpma/856#-MT1XHAX2FPXt13qEulQ:-MT1XHAX2FPXt13qEulR:bm2qclb) ([raw file](https://github.com/pmem/rpma/blob/d66cf3cfc7ef26ecdf91e409a6b5786419b2febc/examples/11-write-with-imm/client.c#L77)):*
> ```C
> 
> 	/*
> 	 * establish a new connection to a server
> ```

This comment fits on one line.


<!-- Sent from Reviewable.io -->

2021-02-09 01:10 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 15 of 21 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/11-write-with-imm/client.c, line 77 at r3](https://reviewable.io/reviews/pmem/rpma/856#-MT1XHAX2FPXt13qEulQ:-MT3KmwlEbI--fTSd6qY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d66cf3cfc7ef26ecdf91e409a6b5786419b2febc/examples/11-write-with-imm/client.c#L77)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This comment fits on one line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-09 08:04 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856#-:-MT4oMlYB4YdZgeXHmZY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-09 12:30 UTC, janekmi reviewed
> Reviewed 1 of 6 files at r3, 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-09 12:31 UTC, janekmi requested changes
> Reviewed 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[examples/11-write-with-imm/README.md, line 7 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5lYyE8kxM7o2zizuO:-MT5lYyE8kxM7o2zizuP:b-2z0201) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/README.md#L7)):*
> ```Markdown
> - The client connects to the server and writes a message with immediate
> data to the server.
> - The server receives an immediate data from client.
> ```

**the** client
___
*[examples/11-write-with-imm/README.md, line 8 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5l_mb5tkyO9BL2z6B:-MT5l_mb5tkyO9BL2z6C:b-2z0201) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/README.md#L8)):*
> ```Markdown
> data to the server.
> - The server receives an immediate data from client.
> The immediate data has the same value as the message written by client
> ```

**the** client


<!-- Sent from Reviewable.io -->

2021-02-09 12:38 UTC, janekmi requested changes
> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[examples/11-write-with-imm/client.c, line 103 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5lxVi3W53up9eWtoa:-MT5lxVi3W53up9eWtob:b-es6r6k) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/client.c#L103)):*
> ```C
> 	memcpy(src, (uint32_t *)&imm, sizeof(uint32_t));
> 	fprintf(stdout, "write a value %u with immediate data %u\n",
> 		(uint32_t)imm, (uint32_t)imm);
> ```

I think you mean:

```c
	fprintf(stdout, "write a value %u with immediate data %u\n",
		src, (uint32_t)imm);
```


<!-- Sent from Reviewable.io -->

2021-02-09 14:50 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[examples/11-write-with-imm/client.c, line 103 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5lxVi3W53up9eWtoa:-MT6EqaMEMAUIcjCyH1A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/client.c#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you mean:

```c
	fprintf(stdout, "write a value %u with immediate data %u\n",
		src, (uint32_t)imm);
```
</blockquote></details>

Done.
___
*[examples/11-write-with-imm/README.md, line 7 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5lYyE8kxM7o2zizuO:-MT6ErcQ4XRrggSwa0-x:b84ugej) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/README.md#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**the** client
</blockquote></details>

Hi @janekmi 

The first letter is capitalized in many examples(e.g. example03-11):
```
git grep '\- The'
03-read-to-persistent/README.md:- The server, if provided (and capable of), prepares a local persistent memory
03-read-to-persistent/README.md:- The client, if provided (and capable of), prepares a local persistent memory
04-write-to-persistent/README.md:- The server, if provided (and capable of), prepares a local persistent memory
04-write-to-persistent/README.md:- The client, if provided (and capable of), prepares a local persistent memory
05-flush-to-persistent/README.md:- The server, if provided (and capable of), prepares a local persistent memory
05-flush-to-persistent/README.md:- The client, if provided (and capable of), prepares a local persistent memory
...
```
Should we update the first letter for all example?
By the way, it is ok for me to capitalize the first letter.

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-02-10 11:15 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 20 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[examples/11-write-with-imm/README.md, line 7 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5lYyE8kxM7o2zizuO:-MTAddM_6_mdlS-pn1mh:b-k6haid) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/README.md#L7)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

The first letter is capitalized in many examples(e.g. example03-11):
```
git grep '\- The'
03-read-to-persistent/README.md:- The server, if provided (and capable of), prepares a local persistent memory
03-read-to-persistent/README.md:- The client, if provided (and capable of), prepares a local persistent memory
04-write-to-persistent/README.md:- The server, if provided (and capable of), prepares a local persistent memory
04-write-to-persistent/README.md:- The client, if provided (and capable of), prepares a local persistent memory
05-flush-to-persistent/README.md:- The server, if provided (and capable of), prepares a local persistent memory
05-flush-to-persistent/README.md:- The client, if provided (and capable of), prepares a local persistent memory
...
```
Should we update the first letter for all example?
By the way, it is ok for me to capitalize the first letter.

Best Regards,
Xiao Yang
</blockquote></details>

I think @janekmi  is referring to the last word.


<!-- Sent from Reviewable.io -->

2021-02-10 12:51 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[examples/11-write-with-imm/README.md, line 7 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5lYyE8kxM7o2zizuO:-MTAz2_12Kn7acb152Hl:b-k0djkl) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/README.md#L7)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I think @janekmi  is referring to the last word.
</blockquote></details>

Sorry, I didn't read it carefully.  Done.
___
*[examples/11-write-with-imm/README.md, line 8 at r5](https://reviewable.io/reviews/pmem/rpma/856#-MT5l_mb5tkyO9BL2z6B:-MTAzFHZ9ldflKwi0ahJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8825b626b8a1cb4886934d6902b97182cb66d8b0/examples/11-write-with-imm/README.md#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**the** client
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 13:13 UTC, janekmi requested changes
> Reviewed 1 of 6 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

___
*[examples/11-write-with-imm/server.c, line 164 at r6](https://reviewable.io/reviews/pmem/rpma/856#-MTB3ai0DebXcMnPRwCw:-MTB3ai0DebXcMnPRwCx:b1624zx) ([raw file](https://github.com/pmem/rpma/blob/51850ba7e35da8b9923314c36ab4df48a21a43ce/examples/11-write-with-imm/server.c#L164)):*
> ```C
> 
> 	uint32_t exp_imm;
> 	memcpy(&exp_imm, dst, sizeof(uint32_t));
> ```

```c
uint32_t *exp_imm = (uint32_t)dst;
```

No need to make a copy.
___
*[examples/11-write-with-imm/server.c, line 176 at r6](https://reviewable.io/reviews/pmem/rpma/856#-MTB3By81Icor-dIF33n:-MTB3By81Icor-dIF33o:bb7qk9l) ([raw file](https://github.com/pmem/rpma/blob/51850ba7e35da8b9923314c36ab4df48a21a43ce/examples/11-write-with-imm/server.c#L176)):*
> ```C
> 
> err_conn_disconnect:
> 	common_wait_for_conn_close_and_disconnect(&conn);
> ```

void
___
*[examples/11-write-with-imm/server.c, line 179 at r6](https://reviewable.io/reviews/pmem/rpma/856#-MTB369n2sMs8O8D8TrV:-MTB369n2sMs8O8D8TrW:bb7qk9l) ([raw file](https://github.com/pmem/rpma/blob/51850ba7e35da8b9923314c36ab4df48a21a43ce/examples/11-write-with-imm/server.c#L179)):*
> ```C
> 
> err_ep_shutdown:
> 	rpma_ep_shutdown(&ep);
> ```

void
___
*[examples/11-write-with-imm/server.c, line 184 at r6](https://reviewable.io/reviews/pmem/rpma/856#-MTB30oG6HthkrrAKKne:-MTB30oG6HthkrrAKKnf:bq1tj5p) ([raw file](https://github.com/pmem/rpma/blob/51850ba7e35da8b9923314c36ab4df48a21a43ce/examples/11-write-with-imm/server.c#L184)):*
> ```C
> 	/* deregister the memory regions */
> 	rpma_mr_dereg(&recv_mr);
> 	rpma_mr_dereg(&dst_mr);
> ```

Because here you deliberately ignore the return value I recommend:

```c
	(void) rpma_mr_dereg(&recv_mr);
	(void) rpma_mr_dereg(&dst_mr);
```
___
*[examples/11-write-with-imm/server.c, line 188 at r6](https://reviewable.io/reviews/pmem/rpma/856#-MTB2q-e0F6D0fKV3PTO:-MTB2q-f4UR_3WL9qzJ0:b-1an9em) ([raw file](https://github.com/pmem/rpma/blob/51850ba7e35da8b9923314c36ab4df48a21a43ce/examples/11-write-with-imm/server.c#L188)):*
> ```C
> err_peer_delete:
> 	/* delete the peer object */
> 	rpma_peer_delete(&peer);
> ```

Because here you deliberately ignore the return value I recommend:
```c
(void) rpma_peer_delete(&peer);
```


<!-- Sent from Reviewable.io -->

2021-02-10 13:37 UTC, janekmi approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-10 13:37 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856#-:-MTB9IXt7NH4siTii2Ev:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-10 14:05 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856#-:-MTBF_o_A-rZhJR3VwlK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-10 14:10 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-10 14:10 UTC, merged