rpma: mmap() memory for rpma_mr_reg() in rpma_flush_apm_new()
pmem/rpma pull request #866
Opened 2021-02-09 14:03 UTC by ldorau

Missing
- [ ] commit's description

2021-02-09 15:04 UTC, ldorau commented
Ref: #751

2021-02-09 15:50 UTC, pbalcer approved these changes
:+1: but I'd wrap the `mmap` in some util function if you plan to allocate memory like that somewhere else.

2021-02-09 21:12 UTC, ldorau reviewed
@pbalcer We do not plan - as for now - in the library itself, only in a new example that will be added soon (an example dedicated for the fork() function).

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866#-:-MT7c4Fk5JwuBoQuNqtj:b-k1rh6p)* status: 0 of 15 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-10 08:01 UTC, grom72 reviewed
Shall we also fix malloc_aligned() in example/common/cpommon-conn.c? 
or in the context of @pbalcer 's suggestion shall we have common utils function in librpma API that is used in examples as well as in the library (flush_apm_new)?

> Reviewed 14 of 15 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866#-:-MT9wBurBwUj8zF2RscS:bkvxah4)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[src/flush.h, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9sL3A4A5MZRUjFD23:-MT9sL3B6srF5wPP2uGz:b9vr03) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/src/flush.h#L37)):*
> ```
> RPMA_E_INVAL
> ```
Is there any UT for RPMA_E_INVAL return value?
___
*[src/flush.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9udcVEK-PWXdUlEFn:-MT9udcVEK-PWXdUlEFo:b46nlme) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/src/flush.c#L78)):*
> ```
> munmap(raw, mmap_size);
> ```
(void) munmap(raw, mmap_size);
___
*[src/flush.c, line 85 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9uh0M4OryKlUrjYLm:-MT9uh0M4OryKlUrjYLn:b3aunmm) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/src/flush.c#L85)):*
> ```
> munmap(raw, mmap_size);
> ```
.
___
*[tests/unit/common/mocks-stdlib.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qlUPBE5a8j68W0ZJ:-MT9qlUPBE5a8j68W0ZK:bkv2mp9) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.h#L11)):*
> ```
> posix_memalign_args
> ```
do we need this?
___
*[tests/unit/common/mocks-stdlib.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qwtlA9TNaTi9IvVH:-MT9qwtlA9TNaTi9IvVI:b-baropm) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.c#L36)):*
> ```
> __wrap_posix_memalign
> ```
Is it still in use in any UT?
___
*[tests/unit/flush/flush-new.c, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9rFDLAA2MNhtJR3SM:-MT9rFDLAA2MNhtJR3SN:b-rmcia0) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/flush/flush-new.c#L57)):*
> ```
> posix_memalign_ENOMEM
> ```
mmap_ENOMEM


<!-- Sent from Reviewable.io -->

2021-02-10 09:58 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9udcVEK-PWXdUlEFn:-MTAIp4yB0l8X5qPM_Ga:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/src/flush.c#L78)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> munmap(raw, mmap_size);
> ```
(void) munmap(raw, mmap_size);
</blockquote></details>

Done.
___
*[src/flush.c, line 85 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9uh0M4OryKlUrjYLm:-MTAIpRO1YQky75HnYeQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/src/flush.c#L85)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> munmap(raw, mmap_size);
> ```
.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdlib.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qlUPBE5a8j68W0ZJ:-MTAIvMf7roeKGF9qN-z:b-m8bnx3) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.h#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> posix_memalign_args
> ```
do we need this?
</blockquote></details>

Yes, integration tests use it.
___
*[tests/unit/common/mocks-stdlib.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qwtlA9TNaTi9IvVH:-MTAJ-2EEzAvdZLTl4zn:b-m8bnx3) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.c#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> __wrap_posix_memalign
> ```
Is it still in use in any UT?
</blockquote></details>

Yes, integration tests use it.
___
*[tests/unit/flush/flush-new.c, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9rFDLAA2MNhtJR3SM:-MTAKyQH0CwD97TlXJ30:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/flush/flush-new.c#L57)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> posix_memalign_ENOMEM
> ```
mmap_ENOMEM
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 11:04 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 16 files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[src/flush.h, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9sL3A4A5MZRUjFD23:-MTAbFSQ5w2ZT7cljat5:b-8b11j9) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/src/flush.h#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_E_INVAL
> ```
Is there any UT for RPMA_E_INVAL return value?
</blockquote></details>

Added


<!-- Sent from Reviewable.io -->

2021-02-10 11:08 UTC, ldorau commented
@grom72 

> Shall we also fix malloc_aligned() in example/common/common-conn.c?
> or in the context of @pbalcer 's suggestion shall we have common utils function in librpma API that is used in examples as well as in the library (flush_apm_new)?
> 

1) `malloc_aligned()` in `example/common/common-conn.c` does not need any fix - those examples do not use fork()
2) We do not need any until function for `fork()` as for now.

2021-02-10 11:29 UTC, ldorau commented
Description added and undrafted.

2021-02-10 11:44 UTC, grom72 reviewed
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/common/mocks-stdlib.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qlUPBE5a8j68W0ZJ:-MTAjX9ZEo_wQgC5MQXu:b-du7rjj) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.h#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, integration tests use it.
</blockquote></details>

but there is a definition in tests/integration/common/mocks.h
This file is used only by UTs
___
*[tests/unit/common/mocks-stdlib.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qwtlA9TNaTi9IvVH:-MTAju28EXU4MZa8vv1P:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.c#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, integration tests use it.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-02-10 13:18 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/unit/common/mocks-stdlib.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qlUPBE5a8j68W0ZJ:-MTAzTrX8rXIB4IYFUfC:bp5ng2q) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.h#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but there is a definition in tests/integration/common/mocks.h
This file is used only by UTs
</blockquote></details>

You are right, removed
___
*[tests/unit/common/mocks-stdlib.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qwtlA9TNaTi9IvVH:-MTB4rwz7T5SIa5hLnzD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.c#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 13:22 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/866#-MTB5iaG6d2LEP91sSag:-MTB5iaG6d2LEP91sSah:b-sp1he8) (no related file):*
Unit tests for `rpma_flush_delete()` will be added

---


<!-- Sent from Reviewable.io -->

2021-02-10 13:25 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 14 of 16 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tests/unit/common/mocks-stdlib.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/866#-MT9qlUPBE5a8j68W0ZJ:-MTB6SkNANhlZdcwU9ee:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e04b4e1f81196ea15100a219b7073f65b760cbda/tests/unit/common/mocks-stdlib.h#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You are right, removed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 13:25 UTC, janekmi requested changes
> Reviewed 2 of 15 files at r1, 1 of 1 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.h, line 37 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB6BWgDhmZar1HYJZS:-MTB6BWgDhmZar1HYJZT:b-hqgmko) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.h#L37)):*
> ```objc
>  *
>  * - RPMA_E_PROVIDER - ibv_dereg_mr() failed
>  * - RPMA_E_INVAL - munmap() failed
> ```

This new error may be passed to the user level when it is called from `rpma_conn_delete()`. Please update the librpma.h accordingly.
___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTB5_iV4z5jCaUnvQZ5:b-sppbp9) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
> ```C
> 
> 	/* allocate memory for the read-after-write buffer (RAW) */
> 	void *raw = mmap(NULL, mmap_size, PROT_READ | PROT_WRITE,
> ```

PROT_READ is not enough?


<!-- Sent from Reviewable.io -->

2021-02-10 13:33 UTC, janekmi requested changes
> Reviewed 1 of 15 files at r1, 1 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/unit/common/mocks-stdlib.c, line 61 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB7yNR9RnZgmP0o6yi:-MTB7yNR9RnZgmP0o6yj:btksgll) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/unit/common/mocks-stdlib.c#L61)):*
> ```C
> 	(void) __len; /* unsused */
> 
> 	test_free(__addr);
> ```

It seems we can validate the addr and len here.
___
*[tests/unit/common/mocks-stdlib.c, line 63 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB7ILw7qFMsNF2wOfb:-MTB7ILw7qFMsNF2wOfc:b-8cnbrv) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/unit/common/mocks-stdlib.c#L63)):*
> ```C
> 	test_free(__addr);
> 
> 	return 0;
> ```

Do we have a negative scenario for `munmap()`?
___
*[tests/unit/flush/flush-new.c, line 57 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB7Yrw3e6GjIWLHsw_:-MTB7Yrx4WvtnBgAZdoE:b-lpdkjy) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/unit/flush/flush-new.c#L57)):*
> ```C
> 
> /*
>  * new__apm_mmap_ENOMEM -- malloc() fail with ENOMEM
> ```

malloc?


<!-- Sent from Reviewable.io -->

2021-02-10 13:34 UTC, janekmi requested changes
> Reviewed 2 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/integration/common/mocks.c, line 793 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8X7p6Q519MyKzcy5:-MTB8X7qAPAGhVPMXPoe:b-vzvhhj) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/common/mocks.c#L793)):*
> ```C
> 	(void) __len; /* unsused */
> 
> 	test_free(__addr);
> ```

Can we validate addr and len here?


<!-- Sent from Reviewable.io -->

2021-02-10 13:36 UTC, janekmi requested changes
> Reviewed 6 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 15 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTB8lyi3akiZTRGGtz_:b-2v6rdw) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
> ```C
> 	struct mmap_args allocated_raw = {0};
> 	will_return(__wrap_mmap, &allocated_raw);
> 	will_return(__wrap_mmap, &allocated_raw);
> ```

Why it is called twice?
___
*[tests/integration/example-01-connection/example-01-connection.c, line 250 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8nqU9Ml8XmxvBLPa:-MTB8nqU9Ml8XmxvBLPb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L250)):*
> ```C
> 	struct mmap_args allocated_raw = {0};
> 	will_return(__wrap_mmap, &allocated_raw);
> 	will_return(__wrap_mmap, &allocated_raw);
> ```

.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 112 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8sdl6Mxw0prHmgPw:-MTB8sdl6Mxw0prHmgPx:buqms7o) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L112)):*
> ```C
> 	struct mmap_args allocated_raw = {0};
> 	will_return(__wrap_mmap, &allocated_raw);
> 	will_return(__wrap_mmap, &allocated_raw);
> ```

Why twice?
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 310 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8uiJ4Ov-4nXVS8oL:-MTB8uiJ4Ov-4nXVS8oM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L310)):*
> ```C
> 	struct mmap_args allocated_raw = {0};
> 	will_return(__wrap_mmap, &allocated_raw);
> 	will_return(__wrap_mmap, &allocated_raw);
> ```

.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 116 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8wAHEFuO4qAYba_m:-MTB8wAHEFuO4qAYba_n:b-z463d0) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L116)):*
> ```C
> 	struct mmap_args flush = {0};
> 	will_return(__wrap_mmap, &flush);
> 	will_return(__wrap_mmap, &flush);
> ```

Twice?
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 347 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8wyP9lIVLq7gCms6:-MTB8wyP9lIVLq7gCms7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L347)):*
> ```C
> 	struct mmap_args allocated_raw = {0};
> 	will_return(__wrap_mmap, &allocated_raw);
> 	will_return(__wrap_mmap, &allocated_raw);
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-10 14:28 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 17 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/866#-MTB5iaG6d2LEP91sSag:-MTBKsc02og5cEkwZqvY:bqmjwcz) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Unit tests for `rpma_flush_delete()` will be added
</blockquote></details>

Added.

---


<!-- Sent from Reviewable.io -->

2021-02-10 14:28 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 17 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/flush/flush-new.c, line 57 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB7Yrw3e6GjIWLHsw_:-MTBL1Pg-OkgcbxcVdCW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/unit/flush/flush-new.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

malloc?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 14:32 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 17 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTBLghL4Pbk3ZPDN5or:b-fd6vj8) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

PROT_READ is not enough?
</blockquote></details>

No, `ibv_reg_mr()` requires `PROT_WRITE`.


<!-- Sent from Reviewable.io -->

2021-02-10 14:33 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 17 files reviewed, 14 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTBLvKs4cvw_qAspYbU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, `ibv_reg_mr()` requires `PROT_WRITE`.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdlib.c, line 63 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB7ILw7qFMsNF2wOfb:-MTBM5yM4G0q6q5ENGmg:bqwjzd8) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/unit/common/mocks-stdlib.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we have a negative scenario for `munmap()`?
</blockquote></details>

Yes - `delete__apm_munmap_E_INVAL`


<!-- Sent from Reviewable.io -->

2021-02-10 15:01 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTBSADo4IHBB74bFwWA:b-araet6) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It is interesting. Did you get this from documentation or by experience? What is the error in this case?


<!-- Sent from Reviewable.io -->

2021-02-10 15:17 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 8 of 19 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/flush.h, line 37 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB6BWgDhmZar1HYJZS:-MTBNvBW8BpDMc27NtjP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.h#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This new error may be passed to the user level when it is called from `rpma_conn_delete()`. Please update the librpma.h accordingly.
</blockquote></details>

Done.
___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTBMeskCEoTf7Z08X_c:b2koo86) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why it is called twice?
</blockquote></details>

cmocka needs it for unknown reason ... :-/
___
*[tests/unit/common/mocks-stdlib.c, line 61 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB7yNR9RnZgmP0o6yi:-MTBW1-tEriNWzAGbypT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/unit/common/mocks-stdlib.c#L61)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems we can validate the addr and len here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 16:05 UTC, janekmi requested changes
> Reviewed 11 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTBfI6iET5ieMNDPKwa:b-j4k39j) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

cmocka needs it for unknown reason ... :-/
</blockquote></details>

Can you set a breakpoint in the __wrap_mmap function and you see it being called twice?
___
*[tests/unit/flush/flush-common.h, line 27 at r7](https://reviewable.io/reviews/pmem/rpma/866#-MTBfuBl5qZo4QJWcIHL:-MTBfuBl5qZo4QJWcIHM:b-ovwawk) ([raw file](https://github.com/pmem/rpma/blob/11c9a6c1245805ef7a02ea2bb5a0a3f4b010ea19/tests/unit/flush/flush-common.h#L27)):*
> ```objc
> struct flush_test_state {
> 	struct rpma_flush *flush;
> 	struct mmap_args allocated_raw;
> ```

Good idea!


<!-- Sent from Reviewable.io -->

2021-02-10 18:16 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r6, 1 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-02-10 18:18 UTC, grom72 reviewed
> Reviewed 1 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-02-11 07:14 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTEvMkR8urGzi4pPL6O:bl1ept0) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you set a breakpoint in the __wrap_mmap function and you see it being called twice?
</blockquote></details>

I did it long ago :-) It is hit only once of course, but if there is only one line, cmocka doesn't seem to see it. Apparently I will have to debug cmocka later ....
___
*[tests/integration/example-01-connection/example-01-connection.c, line 250 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8nqU9Ml8XmxvBLPa:-MTEwEZ97DFBKo5sju6X:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L250)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 112 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8sdl6Mxw0prHmgPw:-MTEwG-g0jkWQ5DGok66:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why twice?
</blockquote></details>

.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 310 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8uiJ4Ov-4nXVS8oL:-MTEwGUjDBWjBsrAmwco:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L310)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 116 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8wAHEFuO4qAYba_m:-MTEwHpa6gsQaYnqO-5O:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Twice?
</blockquote></details>

.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 347 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8wyP9lIVLq7gCms6:-MTEwINp9p3Z9KFtAY93:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L347)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-02-11 08:40 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTFErrM2H6aKu1L8A7Z:b-x4zty1) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is interesting. Did you get this from documentation or by experience? What is the error in this case?
</blockquote></details>

From test - EINVAL
___
*[tests/integration/common/mocks.c, line 793 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8X7p6Q519MyKzcy5:-MTFDoOpCNP9Wjm9Yfvk:byvyago) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/common/mocks.c#L793)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we validate addr and len here?
</blockquote></details>

Yes. Done.


<!-- Sent from Reviewable.io -->

2021-02-11 08:48 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 19 files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFGOAe6ecOjQ9dfviR:b-p17sxi) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I did it long ago :-) It is hit only once of course, but if there is only one line, cmocka doesn't seem to see it. Apparently I will have to debug cmocka later ....
</blockquote></details>

When there is only one such line, I get the error:
```
[ RUN      ] test_client__success
[  ERROR   ] --- No entries for symbol __wrap_mmap.
tests/integration/common/mocks.c:775: error: Could not get value to mock function __wrap_mmap
tests/integration/example-01-connection/example-01-connection.c:96: note: Previously returned mock value was declared here
[  FAILED  ] test_client__success
```


<!-- Sent from Reviewable.io -->

2021-02-11 08:51 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 19 files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFHSNZ5eOraAON7vQO:bt3ulr7) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

When there is only one such line, I get the error:
```
[ RUN      ] test_client__success
[  ERROR   ] --- No entries for symbol __wrap_mmap.
tests/integration/common/mocks.c:775: error: Could not get value to mock function __wrap_mmap
tests/integration/example-01-connection/example-01-connection.c:96: note: Previously returned mock value was declared here
[  FAILED  ] test_client__success
```
</blockquote></details>

The same on CI: https://github.com/ldorau/rpma/runs/1877956647?check_suite_focus=true


<!-- Sent from Reviewable.io -->

2021-02-11 08:52 UTC, grom72 reviewed
> Reviewed 2 of 11 files at r7, 3 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 16 of 19 files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFHKL-3o23kMgg3rNG:bsvyn4m) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

When there is only one such line, I get the error:
```
[ RUN      ] test_client__success
[  ERROR   ] --- No entries for symbol __wrap_mmap.
tests/integration/common/mocks.c:775: error: Could not get value to mock function __wrap_mmap
tests/integration/example-01-connection/example-01-connection.c:96: note: Previously returned mock value was declared here
[  FAILED  ] test_client__success
```
</blockquote></details>

Does it mean that somebody else calls mmap()?


<!-- Sent from Reviewable.io -->

2021-02-11 08:52 UTC, grom72 reviewed
> Reviewed 1 of 11 files at r7, 3 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-11 08:55 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFIETV5ZNxg_j_HLuu:bpj4n1g) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Does it mean that somebody else calls mmap()?
</blockquote></details>

Maybe cmocka? :-)


<!-- Sent from Reviewable.io -->

2021-02-11 08:55 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFIM8b7g_J7VISgaO1:butlv5w) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe cmocka? :-)
</blockquote></details>

I will debug it.


<!-- Sent from Reviewable.io -->

2021-02-11 09:20 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFNxJE8sV5lrdSP1pE:b6pw41g) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I will debug it.
</blockquote></details>

What a blindness ... I already know ...


<!-- Sent from Reviewable.io -->

2021-02-11 09:50 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: 13 of 19 files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTFUiV_4Yt9A538kcx5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

From test - EINVAL
</blockquote></details>

Done.
___
*[tests/integration/example-01-connection/example-01-connection.c, line 97 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8lyi3akiZTRGGtzZ:-MTFUltO8OGGU2Pt6bBg:b-8cawab) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What a blindness ... I already know ...
</blockquote></details>

Fixed.

Done.
___
*[tests/integration/example-01-connection/example-01-connection.c, line 250 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8nqU9Ml8XmxvBLPa:-MTFUpb18BelDRTcpLTr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-01-connection/example-01-connection.c#L250)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 112 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8sdl6Mxw0prHmgPw:-MTFUrWVAddRe9kR-jTd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 310 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8uiJ4Ov-4nXVS8oL:-MTFUsZN7Je-WlHyntyC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L310)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 116 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8wAHEFuO4qAYba_m:-MTFUtVuAtNpMfOzEJQG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 347 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB8wyP9lIVLq7gCms6:-MTFUtv082PL8OlpqEMi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L347)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-11 09:54 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 6 files at r8, 6 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866#-:-MTFVksZ4jdQsRIhw0Hb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTFVXY1CxlTpPHMBf3W:bap4dan) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It looks like an undocumented feature. :thinking: 


<!-- Sent from Reviewable.io -->

2021-02-11 10:25 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[src/flush.c, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/866#-MTB5_iV4z5jCaUnvQZ4:-MTFbY3N5bahyMAyTu85:bu7s9fq) ([raw file](https://github.com/pmem/rpma/blob/e21b7b420ecf6f01f9dc9641c22d042230bea52b/src/flush.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It looks like an undocumented feature. :thinking: 
</blockquote></details>

In `rdma-core/libibverbs/cmd_ioctl.c` :

```
147│         if (ioctl(context->cmd_fd, RDMA_VERBS_IOCTL, &cmd->hdr))
148├───────────────> return errno;
```

returns `errno = 22 (EINVAL)`


<!-- Sent from Reviewable.io -->

2021-02-11 11:35 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/866#-:-MTFrtPZBAHn6M8va7wM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-02-11 11:40 UTC, merged