rpma: send 0B massage
pmem/rpma pull request #869
Opened 2021-02-10 07:39 UTC by osalyk

2021-02-10 12:59 UTC, janekmi requested changes
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @osalyk)

___
*[src/conn.c, line 401 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAzImKBixYzzUFyQ3E:-MTAzImKBixYzzUFyQ3F:b533h8f) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/src/conn.c#L401)):*
> ```C
>     int flags, const void *op_context)
> {
> 	if (conn == NULL || src == NULL || flags == 0)
> ```

I think the case where `src==NULL && (offset !=0  || len != 0)` is still invalid.
___
*[src/conn.c, line 418 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAzJGz9SNEIqgCa-J4:-MTAzJGz9SNEIqgCa-J5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/src/conn.c#L418)):*
> ```C
> 	int flags, uint32_t imm, const void *op_context)
> {
> 	if (conn == NULL || src == NULL || flags == 0)
> ```

.
___
*[src/mr.c, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAzsLA22Kjlec94wJ9:-MTAzsLA22Kjlec94wJA:b2o0yei) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/mr.c#L192)):*
> ```C
>  */
> int
> rpma_mr_send(struct ibv_qp *qp,
> ```

I think you should also update the assumption in the mr.h e.g.:

```c
/*
 * ASSUMPTIONS
 * - qp != NULL && flags != 0
 * - if src == NULL then offset == 0 && len == 0
 */
```
___
*[src/mr.c, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-O981ul2uTQzBnD_:-MTB-O981ul2uTQzBnDa:b-vaocg1) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/mr.c#L201)):*
> ```C
> 	/* source */
> 	if (src == NULL) {
> 		wr.num_sge = 0;
> ```

```c
wr.sg_list = NULL;
```
___
*[src/mr.c, line 203 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-Adx9e8Xgg8NyfcK:-MTB-AdyCH__0WbOqMEM:bp0a1ph) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/mr.c#L203)):*
> ```C
> 		wr.num_sge = 0;
> 	} else {
> 		struct ibv_sge sge;
> ```

This declaration should be outside of the if-statement.
___
*[src/include/librpma.h, line 2175 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAy0OM85d-o_QKZEoQ:-MTAy0OM85d-o_QKZEoR:bwldf68) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/include/librpma.h#L2175)):*
> ```objc
>  * rpma_send() initiates the send operation which transfers a message from
>  * the local memory to other side of the connection.
>  * To send a 0 byte message, set src to NULL.
> ```

... set src to NULL and offset and len to 0.
___
*[src/include/librpma.h, line 2217 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAyaoE1GjzxfoD813v:-MTAyaoE1GjzxfoD813w:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/include/librpma.h#L2217)):*
> ```objc
>  * rpma_send_with_imm() initiates the send operation with immediate data which
>  * transfers a message from the local memory to other side of the connection.
>  * To send a 0 byte message, set src to NULL.
> ```

.
___
*[tests/unit/common/mocks-rpma-mr.c, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAyiJz0q_lDvCJxbXR:-MTAyiJz0q_lDvCJxbXS:b-9adeol) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/tests/unit/common/mocks-rpma-mr.c#L113)):*
> ```C
> {
> 	assert_non_null(qp);
> 	assert_non_null(src);
> ```

check_expected?
___
*[tests/unit/conn/conn-send.c, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAylKSATGvi-3WEIW4:-MTAylKSATGvi-3WEIW5:b533h8f) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/tests/unit/conn/conn-send.c#L41)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, RPMA_E_INVAL);
> }
> ```

I think the case where `src==NULL && (offset !=0  || len != 0)` is still invalid.
___
*[tests/unit/conn/conn-send.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB0GDt6J_pDRX2LLeW:-MTB0GDt6J_pDRX2LLeX:b-2lmjr5) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/conn/conn-send.c#L52)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(NULL, NULL, MOCK_LOCAL_OFFSET,
> 			MOCK_LEN, 0, MOCK_OP_CONTEXT);
> ```

Either all NULL (src, offset and len) on none.
___
*[tests/unit/conn/conn-send.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB0M4A1fPiYntS5uP4:-MTB0M4A1fPiYntS5uP5:b-gt3ryy) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/conn/conn-send.c#L52)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(NULL, NULL, MOCK_LOCAL_OFFSET,
> 			MOCK_LEN, 0, MOCK_OP_CONTEXT);
> ```

Please add an error case where `src==NULL && (offset!=0 || len!= 0)`
___
*[tests/unit/conn/conn-send_with_imm.c, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAz5t07u64QMO-9PjY:-MTAz5t07u64QMO-9PjZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/tests/unit/conn/conn-send_with_imm.c#L43)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, RPMA_E_INVAL);
> }
> ```

.
___
*[tests/unit/mr/mr-send.c, line 126 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-dhWCJHkMSTC7MYE:-MTB-dhWCJHkMSTC7MYF:b-j3ppw9) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/mr/mr-send.c#L126)):*
> ```C
> 	for (int i = 0; i < n_values; i++) {
> 		/* configure mocks */
> 		struct ibv_post_send_mock_args args;
> ```

Please keep variable declarations outside of the if-statements and loops. They are fit the best at the beginning of the function.
___
*[tests/unit/mr/mr-send.c, line 139 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-x1sEFlWCaRIerEJ:-MTB-x1sEFlWCaRIerEK:bes0ot6) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/mr/mr-send.c#L139)):*
> ```C
> 		/* run test */
> 		int ret = rpma_mr_send(MOCK_QP, NULL, MOCK_SRC_OFFSET,
> 				MOCK_LEN, RPMA_F_COMPLETION_ALWAYS,
> ```

MOCK_SRC_OFFSET -> 0
MOCK_LEN -> 0


<!-- Sent from Reviewable.io -->

2021-02-10 13:02 UTC, janekmi reviewed
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 14 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-10 14:01 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: 3 of 10 files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[src/conn.c, line 401 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAzImKBixYzzUFyQ3E:-MTB4BO0-gN-455V119d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/src/conn.c#L401)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the case where `src==NULL && (offset !=0  || len != 0)` is still invalid.
</blockquote></details>

Done.
___
*[src/conn.c, line 418 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAzJGz9SNEIqgCa-J4:-MTB4GIf-ScxX48_bdJV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/src/conn.c#L418)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/mr.c, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAzsLA22Kjlec94wJ9:-MTB97S95ShUMYxu6qHM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/mr.c#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you should also update the assumption in the mr.h e.g.:

```c
/*
 * ASSUMPTIONS
 * - qp != NULL && flags != 0
 * - if src == NULL then offset == 0 && len == 0
 */
```
</blockquote></details>

Done.
___
*[src/mr.c, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-O981ul2uTQzBnD_:-MTB9Kd17zMVhkl02DJ0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/mr.c#L201)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
wr.sg_list = NULL;
```
</blockquote></details>

Done.
___
*[src/mr.c, line 203 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-Adx9e8Xgg8NyfcK:-MTB9Lwj2fXHQfR1jwTM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/mr.c#L203)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This declaration should be outside of the if-statement.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2175 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAy0OM85d-o_QKZEoQ:-MTB5cJHCa0MqDDPffjp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/include/librpma.h#L2175)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... set src to NULL and offset and len to 0.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2217 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAyaoE1GjzxfoD813v:-MTB5hBJ6qTBPO-DjIQC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/src/include/librpma.h#L2217)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-mr.c, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAyiJz0q_lDvCJxbXR:-MTB5qVY-0F74bvm5liJ:br4an42) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/tests/unit/common/mocks-rpma-mr.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

check_expected?
</blockquote></details>

Below.
___
*[tests/unit/conn/conn-send.c, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAylKSATGvi-3WEIW4:-MTBCsyZ-_DM4VXoqkLk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/tests/unit/conn/conn-send.c#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the case where `src==NULL && (offset !=0  || len != 0)` is still invalid.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB0GDt6J_pDRX2LLeW:-MTBDQ0V1TfK1PLYeh-f:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/conn/conn-send.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Either all NULL (src, offset and len) on none.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB0M4A1fPiYntS5uP4:-MTBDSLh4TDW6xUr3o6j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/conn/conn-send.c#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add an error case where `src==NULL && (offset!=0 || len!= 0)`
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send_with_imm.c, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTAz5t07u64QMO-9PjY:-MTBEMTX-PMJZBu_SUy3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/tests/unit/conn/conn-send_with_imm.c#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-send.c, line 126 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-dhWCJHkMSTC7MYE:-MTB6yJ17py3lYZYUDcp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/mr/mr-send.c#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please keep variable declarations outside of the if-statements and loops. They are fit the best at the beginning of the function.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-send.c, line 139 at r1](https://reviewable.io/reviews/pmem/rpma/869#-MTB-x1sEFlWCaRIerEJ:-MTB87TN6WgrkYA3SEeZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d0956d05fdcb5258c7e0f2d5d711adc193c902b/tests/unit/mr/mr-send.c#L139)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MOCK_SRC_OFFSET -> 0
MOCK_LEN -> 0
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-10 15:20 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: 3 of 10 files reviewed, 15 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/10-send-with-imm/client.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBVqZx4wbws4fFrOyw:-MTBVqZx4wbws4fFrOyx:b-r4993o) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/examples/10-send-with-imm/client.c#L36)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	char *word = argv[3];
> ```

Hi @osalyk 

Could we make the example support both zero message and non-zero message?
e.g.
If argv[3] is NULL, the example passes zero message with imm_data.
If argv[3] is not NULL, the example passes non-zero message with imm_data.

Best Regards,
Xiao Yang  


<!-- Sent from Reviewable.io -->

2021-02-10 16:00 UTC, janekmi requested changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[examples/10-send-with-imm/client.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBVqZx4wbws4fFrOyw:-MTBe5t9Aipem4JTWyYL:b-emm468) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/examples/10-send-with-imm/client.c#L36)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @osalyk 

Could we make the example support both zero message and non-zero message?
e.g.
If argv[3] is NULL, the example passes zero message with imm_data.
If argv[3] is not NULL, the example passes non-zero message with imm_data.

Best Regards,
Xiao Yang  
</blockquote></details>

Nifty. Why not. :thinking: 
___
*[tests/unit/conn/conn-send.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBebnN0x3XZgCHi_OD:-MTBebnN0x3XZgCHi_OE:bcb3nnw) ([raw file](https://github.com/pmem/rpma/blob/602344e7723f10a4ef07423b313e8a7ef113e661/tests/unit/conn/conn-send.c#L24)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(MOCK_CONN, NULL, MOCK_LOCAL_OFFSET,
> 			MOCK_LEN, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

NULL, 0, 0
___
*[tests/unit/conn/conn-send_with_imm.c, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBel3s0rlxPe6t5wGn:-MTBel3s0rlxPe6t5wGo:bb6gfpt) ([raw file](https://github.com/pmem/rpma/blob/602344e7723f10a4ef07423b313e8a7ef113e661/tests/unit/conn/conn-send_with_imm.c#L25)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send_with_imm(MOCK_CONN, NULL,
> 			MOCK_LOCAL_OFFSET, MOCK_LEN, MOCK_FLAGS,
> ```

0, 0


<!-- Sent from Reviewable.io -->

2021-02-10 16:45 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBVqZx4wbws4fFrOyw:-MTBpJOj19Dx_bq5cY3T:bcvjgzp) ([raw file](https://github.com/pmem/rpma/blob/516d3048e5259bba50f3ea98f7a8c1512670a4d0/examples/10-send-with-imm/client.c#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nifty. Why not. :thinking: 
</blockquote></details>

Good idea. Done.
___
*[tests/unit/conn/conn-send.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBebnN0x3XZgCHi_OD:-MTBireL9UuiZfLdId14:b819jg) ([raw file](https://github.com/pmem/rpma/blob/602344e7723f10a4ef07423b313e8a7ef113e661/tests/unit/conn/conn-send.c#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

NULL, 0, 0
</blockquote></details>

This is a negative case, please read the description.
___
*[tests/unit/conn/conn-send_with_imm.c, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/869#-MTBel3s0rlxPe6t5wGn:-MTBiwzSEAhtjpe24b57:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/602344e7723f10a4ef07423b313e8a7ef113e661/tests/unit/conn/conn-send_with_imm.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

0, 0
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-02-11 11:43 UTC, janekmi requested changes
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 37 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFqtnWCX4JZG-HPCgj:-MTFqtnWCX4JZG-HPCgk:bnuypu4) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L37)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	char *word;
> ```

= NULL;
___
*[examples/10-send-with-imm/client.c, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFr1wF2yonnn60kcET:-MTFr1wF2yonnn60kcEU:b-en3z5a) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L53)):*
> ```C
> 		return -1;
> 	}
> ```

Take this:

```c
	if (argc == 5)
		word = argv[4];
```

here.
___
*[examples/10-send-with-imm/client.c, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFrQo50Gy6Ok8D1k8d:-MTFrQo50Gy6Ok8D1k8e:b-fe926j) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L64)):*
> ```C
> 	char *send = malloc_aligned(KILOBYTE);
> 	if (!send)
> 		return -1;
> ```

No need for allocation if `word == NULL`.
___
*[examples/10-send-with-imm/client.c, line 104 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFrc3sA5afc-vILhX1:-MTFrc3sA5afc-vILhX2:b-a1ym5n) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L104)):*
> ```C
> 		ret = rpma_send_with_imm(conn, NULL, 0, 0,
> 			RPMA_F_COMPLETION_ALWAYS, (uint32_t)imm, NULL);
> 	}
> ```

I think we can make it simpler:

```c
len = 0;

if (word) {
     len = KILOBYTE;
     send = malloc_alligned(len);
     strcpy(send, word);

    fprintf(stdout, "send a values %s with immediate data %u\n", ...);
} else {
    fprintf(stdout, "send immediate data %u\n", ....);
}

/* ... */

ret = rpma_send_with_imm(conn, send_mr, 0, len, ...);
if (ret)
    /* ... */
```
___
*[examples/10-send-with-imm/server.c, line 151 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFtcPG-NQxprsEgZaF:-MTFtcPG-NQxprsEgZaG:bkvajyi) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/server.c#L151)):*
> ```C
> 		ret = -1;
> 	} else {
> 		printf("receive a value %s with immediate data %u\n", recv,
> ```

What will happen if recv is empty?
___
*[examples/10-send-with-imm/server.c, line 153 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFtWMB0k-c5nuUSmTv:-MTFtWMB0k-c5nuUSmTw:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/server.c#L153)):*
> ```C
> 		printf("receive a value %s with immediate data %u\n", recv,
> 			cmpl.imm);
> ```

Please remove.


<!-- Sent from Reviewable.io -->

2021-02-11 12:03 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[src/include/librpma.h, line 2219 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFyC5P67JR_5X5BEqs:-MTFyC5Q8utS7DtjNRdu:b-pc0vte) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/src/include/librpma.h#L2219)):*
> ```
> and offset and len
> ```

`and both offset and len ...`
___
*[src/include/librpma.h, line 2261 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFyGTX4lRBsGCdQqqt:-MTFyGTX4lRBsGCdQqqu:bz96hje) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/src/include/librpma.h#L2261)):*
> ```
> and offset and len to 0
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-11 12:06 UTC, ldorau reviewed
> Reviewed 4 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-11 12:22 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: 7 of 11 files reviewed, 9 unresolved discussions (waiting on @janekmi, @ldorau, and @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 37 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFqtnWCX4JZG-HPCgj:-MTFv2LhBSRQE-46I5oh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

= NULL;
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFr1wF2yonnn60kcET:-MTFv93YDx_ZTAXX3p57:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Take this:

```c
	if (argc == 5)
		word = argv[4];
```

here.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFrQo50Gy6Ok8D1k8d:-MTFvoXdCPNrrm2p5oQV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No need for allocation if `word == NULL`.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 104 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFrc3sA5afc-vILhX1:-MTFyO187cCM863DRXDr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/client.c#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can make it simpler:

```c
len = 0;

if (word) {
     len = KILOBYTE;
     send = malloc_alligned(len);
     strcpy(send, word);

    fprintf(stdout, "send a values %s with immediate data %u\n", ...);
} else {
    fprintf(stdout, "send immediate data %u\n", ....);
}

/* ... */

ret = rpma_send_with_imm(conn, send_mr, 0, len, ...);
if (ret)
    /* ... */
```
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 151 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFtcPG-NQxprsEgZaF:-MTFyZ970-KHBYCTTjZe:bpqibjy) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/server.c#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What will happen if recv is empty?
</blockquote></details>

Displays: receive a value  with immediate data 123
___
*[examples/10-send-with-imm/server.c, line 153 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFtWMB0k-c5nuUSmTv:-MTFypX61ePgHP4awm9P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/server.c#L153)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2219 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFyC5P67JR_5X5BEqs:-MTFz05qEE3lT0DFYRFG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/src/include/librpma.h#L2219)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> and offset and len
> ```

`and both offset and len ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2261 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFyGTX4lRBsGCdQqqt:-MTFz5UK03O5jYZtYtmZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/src/include/librpma.h#L2261)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> and offset and len to 0
> ```

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-11 13:08 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau, @osalyk, and @yangx-jy)

___
*[examples/10-send-with-imm/server.c, line 151 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFtcPG-NQxprsEgZaF:-MTGAGWU0S6ZF8dxMuDY:bvw2h94) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/server.c#L151)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Displays: receive a value  with immediate data 123
</blockquote></details>

TBH I think we can not rely on assumption that recv buffer without data will start from `\0`. I think we should verify the number of bytes received and if `cmpl.byte_len == 0` then `recv[0] = '\0';` so the print won't cause a SIGSEGV.

Additionally, I think it will be better to add `"%s"` so it will be present even if recv is empty.


<!-- Sent from Reviewable.io -->

2021-02-11 13:56 UTC, ldorau requested changes
> Reviewed 2 of 7 files at r2, 4 of 9 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/869#-MTGNDnE21UTtge0vm25:-MTGNDnE21UTtge0vm26:b-dnj6lh) ([raw file](https://github.com/pmem/rpma/blob/3f8bdc8af77a6934630ab922af08b4248ae7346f/examples/10-send-with-imm/client.c#L61)):*
> ```
> char *send;
> ```

`char *send = NULL;`
___
*[examples/10-send-with-imm/client.c, line 102 at r4](https://reviewable.io/reviews/pmem/rpma/869#-MTGLLdc3S-BvOW_J1J2:-MTGLLdc3S-BvOW_J1J3:b-toxuvb) ([raw file](https://github.com/pmem/rpma/blob/3f8bdc8af77a6934630ab922af08b4248ae7346f/examples/10-send-with-imm/client.c#L102)):*
> ```
> strcpy(send, word);
> ```

use `strncpy()` please
___
*[examples/10-send-with-imm/server.c, line 151 at r4](https://reviewable.io/reviews/pmem/rpma/869#-MTGLxiH2szL8u8HkRih:-MTGLxiH2szL8u8HkRii:b-tyjh61) ([raw file](https://github.com/pmem/rpma/blob/3f8bdc8af77a6934630ab922af08b4248ae7346f/examples/10-send-with-imm/server.c#L151)):*
> ```
> receive a value %s
> ```

`receiveD value '%s' `  (no 'a')


<!-- Sent from Reviewable.io -->

2021-02-11 14:13 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: 9 of 11 files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/869#-MTGNDnE21UTtge0vm25:-MTGOVy6DVlV2BDOjrIT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f8bdc8af77a6934630ab922af08b4248ae7346f/examples/10-send-with-imm/client.c#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> char *send;
> ```

`char *send = NULL;`
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/client.c, line 102 at r4](https://reviewable.io/reviews/pmem/rpma/869#-MTGLLdc3S-BvOW_J1J2:-MTGP0n93MXZaqSskNSv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f8bdc8af77a6934630ab922af08b4248ae7346f/examples/10-send-with-imm/client.c#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> strcpy(send, word);
> ```

use `strncpy()` please
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 151 at r3](https://reviewable.io/reviews/pmem/rpma/869#-MTFtcPG-NQxprsEgZaF:-MTGQ9-j5H2QxYWpU2LH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a80245027235bf38ae36bd00443191c950540da/examples/10-send-with-imm/server.c#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TBH I think we can not rely on assumption that recv buffer without data will start from `\0`. I think we should verify the number of bytes received and if `cmpl.byte_len == 0` then `recv[0] = '\0';` so the print won't cause a SIGSEGV.

Additionally, I think it will be better to add `"%s"` so it will be present even if recv is empty.
</blockquote></details>

Done.
___
*[examples/10-send-with-imm/server.c, line 151 at r4](https://reviewable.io/reviews/pmem/rpma/869#-MTGLxiH2szL8u8HkRih:-MTGPgRaBILeQxQ_nppr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f8bdc8af77a6934630ab922af08b4248ae7346f/examples/10-send-with-imm/server.c#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> receive a value %s
> ```

`receiveD value '%s' `  (no 'a')

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-11 14:26 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-11 14:26 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869#-:-MTGU8e1B1r89MekVRa3:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-11 16:04 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/869#-:-MTGpVyX3qFQVFw0Xx0Q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-02-11 16:04 UTC, merged