rpma: rpma_write/read 0B message
pmem/rpma pull request #882
Opened 2021-02-12 06:42 UTC by osalyk

2021-02-12 10:30 UTC, ldorau requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/882#-MTKmSYY5e2oQ9hwzirG:-MTKmSYZC9uTNMyT6qhU:b-d29q7k) (no related file):*
There are 8 lines not covered by unit tests:
https://codecov.io/gh/pmem/rpma/src/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c

---


<!-- Sent from Reviewable.io -->

2021-02-12 10:36 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/882#-MTKmSYY5e2oQ9hwzirG:-MTKnjwM1Kw7BOAkp7U9:bbo2ax7) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There are 8 lines not covered by unit tests:
https://codecov.io/gh/pmem/rpma/src/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c

</blockquote></details>

They are covered but codecov does not show it. (conn-read.c conn-write.c conn-write_with_imm.c)

---


<!-- Sent from Reviewable.io -->

2021-02-12 10:41 UTC, ldorau requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/include/librpma.h, line 1980 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKnmQj4lVYwOl-HNjm:-MTKnmQk5C2HZOIXQg0h:bt4cw3o) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L1980)):*
> ```
> dst_offset, and len
> ```

`dst_offset and len` (no comma before 'and')
___
*[src/include/librpma.h, line 1995 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKo9g26pacBl3tC2CS:-MTKo9g26pacBl3tC2CT:b7qd7nz) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L1995)):*
> ```
> src is NULL and dst is NULL or offsets or len != 0
> ```

1) It is  ambiguous
2) `offsets` ?
___
*[src/include/librpma.h, line 2026 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKoVy552bmcfaY333f:-MTKoVy552bmcfaY333g:b2eex2a) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2026)):*
> ```
> dst_offset, and len
> ```

.
___
*[src/include/librpma.h, line 2041 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKoXxBCA6PQTnVAidZ:-MTKoXxBCA6PQTnVAid_:brk7kyd) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2041)):*
> ```
>  * - RPMA_E_INVAL - src is NULL and dst is NULL or offsets or len != 0
> ```

.
___
*[src/include/librpma.h, line 2073 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKoaCLBdxCFIFMefXy:-MTKoaCLBdxCFIFMefXz:b-8ztv9q) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2073)):*
> ```
> dst_offset, and len 
> ```

.
___
*[src/include/librpma.h, line 2088 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKogh9Ba5oq5ARX5j8:-MTKogh9Ba5oq5ARX5j9:bwwa3hm) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2088)):*
> ```
> src is NULL and dst is NULL or offsets or len != 0
> ```

.
___
*[src/include/librpma.h, line 2243 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKozN774AIHq7s4_7w:-MTKozN774AIHq7s4_7x:b-o01dje) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2243)):*
> ```
> src is NULL and offset or len != 0
> ```

ambiguous
___
*[src/include/librpma.h, line 2286 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKp1XaAZuvAKa1N5bi:-MTKp1XaAZuvAKa1N5bj:b-1z7kf3) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2286)):*
> ```
>  * - RPMA_E_INVAL - src is NULL and offset or len != 0
> ```

ambiguous


<!-- Sent from Reviewable.io -->

2021-02-12 10:48 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/882#-MTKmSYY5e2oQ9hwzirG:-MTKqckw7pVU1YjMvy6n:b2kiar1) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

They are covered but codecov does not show it. (conn-read.c conn-write.c conn-write_with_imm.c)
</blockquote></details>

The same result is on my fork: https://codecov.io/gh/ldorau/rpma/src/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c

---


<!-- Sent from Reviewable.io -->

2021-02-12 10:57 UTC, ldorau requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 3 of 10 files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[src/mr.h, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKsgdv167UDmz7U16n:-MTKsgdw59CblCPAGsop:b-wulegy) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/mr.h#L32)):*
> ```
>  src != NULL 
> ```

To be removed I suppose


<!-- Sent from Reviewable.io -->

2021-02-12 11:02 UTC, ldorau requested changes
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 11 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 162 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKtoF7Dg2xeNaseRDN:-MTKtoF7Dg2xeNaseRDO:b2l7620) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/mr.c#L162)):*
> ```
> /* source */
> ```

move it below 'else'


<!-- Sent from Reviewable.io -->

2021-02-12 11:16 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 10 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/882#-MTKmSYY5e2oQ9hwzirG:-MTKx8gk5NwnZrysK5gv:bfy6ryl) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The same result is on my fork: https://codecov.io/gh/ldorau/rpma/src/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c
</blockquote></details>

Yes, that is codecov's error, all is OK.

---


<!-- Sent from Reviewable.io -->

2021-02-12 11:23 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 13 unresolved discussions (waiting on @osalyk)

___
*[src/conn.c, line 306 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKy_BtC_4dMsSakvHT:-MTKy_BtC_4dMsSakvHU:bceo1mo) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c#L306)):*
> ```
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 			(src == NULL && (dst != NULL || dst_offset != 0 ||
> 			src_offset != 0 || len != 0)))
> ```

The continuation line of the 'if' condition
should be indented by 4 spaces, not by tabs.

See: https://github.com/pmem/rpma/pull/884
___
*[src/conn.c, line 326 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKygdW5FtHI6AgnTpR:-MTKygdW5FtHI6AgnTpS:b-xfg4yh) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c#L326)):*
> ```
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 			(src == NULL && (dst != NULL || dst_offset != 0 ||
> 			src_offset != 0 || len != 0)))
> ```

.
___
*[src/conn.c, line 348 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKyijd8ptDM9F1FGkK:-MTKyijd8ptDM9F1FGkL:b-xfg4yh) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c#L348)):*
> ```
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 			(src == NULL && (dst != NULL || dst_offset != 0 ||
> 			src_offset != 0 || len != 0)))
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-12 11:29 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 14 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/882#-MTL-3Xj1YoiS5vAqGSu:-MTL-3Xj1YoiS5vAqGSv:b-n6khor) (no related file):*
Please rebase

---


<!-- Sent from Reviewable.io -->

2021-02-12 11:42 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 1 of 10 files reviewed, 14 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/882#-MTL-3Xj1YoiS5vAqGSu:-MTL0JZH05jYeDL4DvmW:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[src/conn.c, line 306 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKy_BtC_4dMsSakvHT:-MTL16UF64QRefFDQRYw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c#L306)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 			(src == NULL && (dst != NULL || dst_offset != 0 ||
> 			src_offset != 0 || len != 0)))
> ```

The continuation line of the 'if' condition
should be indented by 4 spaces, not by tabs.

See: https://github.com/pmem/rpma/pull/884
</blockquote></details>

Done.
___
*[src/conn.c, line 326 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKygdW5FtHI6AgnTpR:-MTL17FYEh0VtJJnNTr3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c#L326)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 			(src == NULL && (dst != NULL || dst_offset != 0 ||
> 			src_offset != 0 || len != 0)))
> ```

.
</blockquote></details>

Done.
___
*[src/conn.c, line 348 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKyijd8ptDM9F1FGkK:-MTL17ym3tgVcleVmdyV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/conn.c#L348)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 			(src == NULL && (dst != NULL || dst_offset != 0 ||
> 			src_offset != 0 || len != 0)))
> ```

.
</blockquote></details>

Done.
___
*[src/mr.h, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKsgdv167UDmz7U16n:-MTKxZjC-CjifLwPTTOw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/mr.h#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  src != NULL 
> ```

To be removed I suppose
</blockquote></details>

Done.
___
*[src/mr.c, line 162 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKtoF7Dg2xeNaseRDN:-MTL-A7S1wmOqtMcQeNq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/mr.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* source */
> ```

move it below 'else'
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1980 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKnmQj4lVYwOl-HNjm:-MTKqUig8UqQovQtzmEh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L1980)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dst_offset, and len
> ```

`dst_offset and len` (no comma before 'and')
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1995 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKo9g26pacBl3tC2CS:-MTL-d08AfXOL_V8Zs5C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L1995)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> src is NULL and dst is NULL or offsets or len != 0
> ```

1) It is  ambiguous
2) `offsets` ?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2026 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKoVy552bmcfaY333f:-MTL-kCoB9YNMNLz5KMC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2026)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dst_offset, and len
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2041 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKoXxBCA6PQTnVAidZ:-MTL-ubF2fILCYU0z-aA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2041)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - src is NULL and dst is NULL or offsets or len != 0
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2073 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKoaCLBdxCFIFMefXy:-MTL-vp-7_DwTKgKa_JZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2073)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dst_offset, and len 
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2088 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKogh9Ba5oq5ARX5j8:-MTL-wj17TBsfhQyX3et:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2088)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> src is NULL and dst is NULL or offsets or len != 0
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2243 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKozN774AIHq7s4_7w:-MTL0BOdEdFfASmShSEg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2243)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> src is NULL and offset or len != 0
> ```

ambiguous
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2286 at r1](https://reviewable.io/reviews/pmem/rpma/882#-MTKp1XaAZuvAKa1N5bi:-MTL0CXN3i79X_b70CQp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b8732398f3fa4e6a2879910cc01675f80225f6/src/include/librpma.h#L2286)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - src is NULL and offset or len != 0
> ```

ambiguous
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-12 11:54 UTC, ldorau requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1996 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL48-54Ew1_57po_LW:-MTL48-54Ew1_57po_LX:bq6u9ob) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L1996)):*
> ```
> dst is NULL
> ```

in NOT
___
*[src/include/librpma.h, line 1996 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4WpL1dOv3I6eLcga:-MTL4WpL1dOv3I6eLcgb:b-jjukvp) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L1996)):*
> ```
>  * - RPMA_E_INVAL - src is NULL and
>  * (dst is NULL or dst_offset, src_offset or len != 0)
> ```

Maybe indented with spaces under 'src' ?

```
 * - RPMA_E_INVAL - src is NULL and
 *                  (dst is NULL or dst_offset, src_offset or len != 0)
```
?
___
*[src/include/librpma.h, line 2043 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4EoOAhg0k-A9cN9n:-MTL4EoOAhg0k-A9cN9o:b-167jzp) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L2043)):*
> ```
> dst is NULL
> ```

.
___
*[src/include/librpma.h, line 2043 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4tXk5W8Kc4Xxsehn:-MTL4tXk5W8Kc4Xxseho:bain51g) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L2043)):*
> ```
>  * - RPMA_E_INVAL - src is NULL and
>  * (dst is NULL or dst_offset, src_offset or len != 0)
> ```

. ?
___
*[src/include/librpma.h, line 2091 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4HqD82ekZLiTqJvA:-MTL4HqD82ekZLiTqJvB:b-167jzp) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L2091)):*
> ```
> dst is NULL
> ```

.
___
*[src/include/librpma.h, line 2091 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4wjyEzeJ_v8g1dzw:-MTL4wjz-xL1QnDY_VHG:bain51g) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L2091)):*
> ```
>  * - RPMA_E_INVAL - src is NULL and
>  * (dst is NULL or dst_offset, src_offset or len != 0)
> ```

. ?


<!-- Sent from Reviewable.io -->

2021-02-12 12:04 UTC, ldorau reviewed
The Codecov Report is wrong - those six lines are hit. After adding `abort()`:

https://github.com/ldorau/rpma/blob/review-osalyk-empty-message/src/conn.c#L309 (and two more)

those 3 tests fail:

https://github.com/ldorau/rpma/runs/1886957354?check_suite_focus=true

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882#-:-MTL6fFOD8Ld01Qi57GK:bo0qnov)* status: 5 of 10 files reviewed, 6 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-12 12:14 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1996 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL48-54Ew1_57po_LW:-MTL6KYl3P9dy7NWUr9X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L1996)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dst is NULL
> ```

in NOT
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2043 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4EoOAhg0k-A9cN9n:-MTL8iMl-imkbkv3OJ26:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L2043)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dst is NULL
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2091 at r2](https://reviewable.io/reviews/pmem/rpma/882#-MTL4HqD82ekZLiTqJvA:-MTL8o-yALihN8kXN8jf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/12a11019efcedeb640f5e7c4ddd99dd16748ac4f/src/include/librpma.h#L2091)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dst is NULL
> ```

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-12 12:44 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-02-12 13:22 UTC, janekmi requested changes
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/mr.h, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLO6-N9m_SCeEuJe-Q:-MTLO6-N9m_SCeEuJe-R:b-at6hdk) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L18)):*
> ```objc
>  * ASSUMPTIONS
>  * - qp != NULL && dst != NULL && flags != 0
>  * - if src == NULL then dst == NULL && offset == 0 && len == 0
> ```

I would tell:

```c
/*
 * - qp != NULL && flags != 0
 * - if src == NULL || dst  == NULL then src == NULL && dst == NULL && offset = 0 && len == 0
 *   else src != NULL && dst != NULL
 */
```

Otherwise, I'm not sure if `dst == NULL && src != NULL` is correct or not.
___
*[src/mr.h, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLP4Fb3df2J4SFJjvj:-MTLP4Fb3df2J4SFJjvk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L33)):*
> ```objc
>  * ASSUMPTIONS
>  * - qp != NULL && dst != NULL && flags != 0
>  * - if src == NULL then dst == NULL && offset == 0 && len == 0
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-12 14:30 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/mr.h, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLO6-N9m_SCeEuJe-Q:-MTLcdZM2SnltBnpvn3F:b-cjlnsv) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would tell:

```c
/*
 * - qp != NULL && flags != 0
 * - if src == NULL || dst  == NULL then src == NULL && dst == NULL && offset = 0 && len == 0
 *   else src != NULL && dst != NULL
 */
```

Otherwise, I'm not sure if `dst == NULL && src != NULL` is correct or not.
</blockquote></details>

So maybe like that ?

```
/*
 * - qp != NULL && flags != 0
 * - (src != NULL && dst != NULL && len != 0) || (src == NULL && dst == NULL && offset = 0 && len == 0)
 */
```
___
*[src/mr.h, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLP4Fb3df2J4SFJjvj:-MTLdSVD823cg_1Q79OU:b2ngvc8) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

. ?


<!-- Sent from Reviewable.io -->

2021-02-12 14:30 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-12 14:33 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/mr.h, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLO6-N9m_SCeEuJe-Q:-MTLeGNx5sn_fcPUOHBl:b-hfuwc6) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So maybe like that ?

```
/*
 * - qp != NULL && flags != 0
 * - (src != NULL && dst != NULL && len != 0) || (src == NULL && dst == NULL && offset = 0 && len == 0)
 */
```

</blockquote></details>

I like the @ldorau idea.
___
*[src/mr.h, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLP4Fb3df2J4SFJjvj:-MTLeLmT08rQR28ywMUV:b4fznq) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

. ?
</blockquote></details>

+1 @ldorau 
___
*[src/include/librpma.h, line 1991 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLPK17BJA35sLvvXOP:-MTLPK17BJA35sLvvXOQ:bopvpsa) ([raw file](https://github.com/pmem/rpma/blob/74fc36171db1c16f262b1a67627d7a9287605125/src/include/librpma.h#L1991)):*
> ```objc
>  * rpma_read() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - conn, dst or src is NULL
> ```

```c
/*
 * - RPMA_E_INVAL - conn, dst or src is NULL
 * - RPMA_E_INVAL - dst != NULL and (src != NULL or src_offset != 0 or dst_offset != 0 or len != 0)
 * - RPMA_E_INVAL - src != NULL and (dst != NULL or src_offset != 0 or dst_offset != 0 or len != 0)
 * ...
 */
```
___
*[src/include/librpma.h, line 2043 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLR_I5DmN2ajEsvUhV:-MTLR_I5DmN2ajEsvUhW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/include/librpma.h#L2043)):*
> ```objc
>  * - RPMA_E_INVAL - flags are not set
>  * - RPMA_E_INVAL - src is NULL and
>  *                  (dst is not NULL or dst_offset, src_offset or len != 0)
> ```

.
___
*[src/include/librpma.h, line 2091 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLRfSo0z0f1D_n07at:-MTLRfSo0z0f1D_n07au:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/include/librpma.h#L2091)):*
> ```objc
>  * - RPMA_E_INVAL - flags are not set
>  * - RPMA_E_INVAL - src is NULL and
>  *                  (dst is not NULL or dst_offset, src_offset or len != 0)
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-12 15:17 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/mr.h, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLO6-N9m_SCeEuJe-Q:-MTLoH1U52yXaUveqaJl:b32wtd) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like the @ldorau idea.
</blockquote></details>

ok
___
*[src/mr.h, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLP4Fb3df2J4SFJjvj:-MTLoI9l4P_IQNOnVdwn:b32wtd) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1 @ldorau 
</blockquote></details>

ok


<!-- Sent from Reviewable.io -->

2021-02-12 15:25 UTC, janekmi requested changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[src/conn.c, line 306 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLpuwE9LkulUv13Jeo:-MTLpuwE9LkulUv13Jep:bqsar3e) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/conn.c#L306)):*
> ```C
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 	    (src == NULL && (dst != NULL || dst_offset != 0 ||
> 	    src_offset != 0 || len != 0)))
> ```

This condition is invalid. In the current implementation, you can not provide dst == NULL because it will fail.
___
*[src/conn.c, line 326 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLq5D5Bi2UMsRmUrQh:-MTLq5D5Bi2UMsRmUrQi:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/conn.c#L326)):*
> ```C
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 	    (src == NULL && (dst != NULL || dst_offset != 0 ||
> 	    src_offset != 0 || len != 0)))
> ```

.
___
*[src/conn.c, line 348 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLq6ApA5NyfbxDVF07:-MTLq6ApA5NyfbxDVF08:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/conn.c#L348)):*
> ```C
> 	if (conn == NULL || dst == NULL || flags == 0 ||
> 	    (src == NULL && (dst != NULL || dst_offset != 0 ||
> 	    src_offset != 0 || len != 0)))
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-12 15:35 UTC, janekmi requested changes
> Reviewed 6 of 10 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 14 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqLCH9q7MVithoJjk:-MTLqLCH9q7MVithoJjl:b-arktxm) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.c#L117)):*
> ```C
> 		/* source */
> 		wr.wr.rdma.remote_addr = src->raddr + src_offset;
> 		wr.wr.rdma.rkey = src->rkey;
> ```

I think it will be safer to set also these two values in the `src == NULL` path.
___
*[src/mr.c, line 176 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqZiGCUV0_sU8ZXVU:-MTLqZiGCUV0_sU8ZXVV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.c#L176)):*
> ```C
> 		/* destination */
> 		wr.wr.rdma.remote_addr = dst->raddr + dst_offset;
> 		wr.wr.rdma.rkey = dst->rkey;
> ```

.
___
*[src/mr.c, line 221 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqbnm0dsknQN2G_4l:-MTLqbnm0dsknQN2G_4m:b-bfd82k) ([raw file](https://github.com/pmem/rpma/blob/74fc36171db1c16f262b1a67627d7a9287605125/src/mr.c#L221)):*
> ```C
> 		sge.length = (uint32_t)len;
> 		sge.lkey = src->ibv_mr->lkey;
> ```

Why you don't like this new line?
___
*[tests/unit/common/mocks-rpma-mr.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqjsA7cKQa_bQZbnp:-MTLqjsA7cKQa_bQZbnq:b-7xlp0k) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/tests/unit/common/mocks-rpma-mr.c#L25)):*
> ```C
> {
> 	assert_non_null(qp);
> 	assert_non_null(dst);
> ```

This one also can be NULL.
___
*[tests/unit/common/mocks-rpma-mr.c, line 51 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqm0g7Hpw0qPNR3iG:-MTLqm0g7Hpw0qPNR3iH:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/tests/unit/common/mocks-rpma-mr.c#L51)):*
> ```C
> {
> 	assert_non_null(qp);
> 	assert_non_null(dst);
> ```

.
___
*[tests/unit/mr/mr-read.c, line 113 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLro9_14nZC3W_XFcM:-MTLro9a3clTUD_WkRFl:b-xtslzr) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/tests/unit/mr/mr-read.c#L113)):*
> ```C
> 	args.opcode = IBV_WR_RDMA_READ;
> 	args.send_flags = IBV_SEND_SIGNALED; /* for RPMA_F_COMPLETION_ALWAYS */
> 	args.wr_id = (uint64_t)MOCK_OP_CONTEXT;
> ```

I can not believe we do not verify both of these in the ibv_post_send_mock():

- wr.rdma.remote_addr
- wr.rdma.rkey


<!-- Sent from Reviewable.io -->

2021-02-12 16:14 UTC, osalyk reviewed
https://codecov.io/gh/osalyk/rpma/commit/f93d26ca219ac75ab5f6fa05ea937987c4022946/

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882#-:-MTLIY0Q4vapbIwndthp:bqru3xp)* status: 5 of 10 files reviewed, 14 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/conn.c, line 306 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLpuwE9LkulUv13Jeo:-MTLxFRm8_3u8_neiC9C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/conn.c#L306)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This condition is invalid. In the current implementation, you can not provide dst == NULL because it will fail.
</blockquote></details>

Done.
___
*[src/conn.c, line 326 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLq5D5Bi2UMsRmUrQh:-MTLxGEK7s5kHBBW4amq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/conn.c#L326)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/conn.c, line 348 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLq6ApA5NyfbxDVF07:-MTLxH5BAXF3WCGHlKYy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/conn.c#L348)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/mr.h, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLP4Fb3df2J4SFJjvj:-MTLtN4c5wai-vxafjRH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.
___
*[src/mr.c, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqLCH9q7MVithoJjk:-MTLz6IL629coGtAx7R2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.c#L117)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be safer to set also these two values in the `src == NULL` path.
</blockquote></details>

Done.
___
*[src/mr.c, line 176 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqZiGCUV0_sU8ZXVU:-MTLzHr8Alle3ZhZdfNg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.c#L176)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/mr.c, line 221 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqbnm0dsknQN2G_4l:-MTLxoaJ6G1ab9Sa75gG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/74fc36171db1c16f262b1a67627d7a9287605125/src/mr.c#L221)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why you don't like this new line?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1991 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLPK17BJA35sLvvXOP:-MTLvCub6T-ZZp8K2Dv9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/74fc36171db1c16f262b1a67627d7a9287605125/src/include/librpma.h#L1991)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/*
 * - RPMA_E_INVAL - conn, dst or src is NULL
 * - RPMA_E_INVAL - dst != NULL and (src != NULL or src_offset != 0 or dst_offset != 0 or len != 0)
 * - RPMA_E_INVAL - src != NULL and (dst != NULL or src_offset != 0 or dst_offset != 0 or len != 0)
 * ...
 */
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2043 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLR_I5DmN2ajEsvUhV:-MTLvEFm8cn5YpUL9m18:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/include/librpma.h#L2043)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2091 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLRfSo0z0f1D_n07at:-MTLvFZI8SOoYjqO0_3M:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/include/librpma.h#L2091)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-mr.c, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqjsA7cKQa_bQZbnp:-MTLvdPaDwBC9Bm8_4DP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/tests/unit/common/mocks-rpma-mr.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This one also can be NULL.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-mr.c, line 51 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLqm0g7Hpw0qPNR3iG:-MTLveIq3a7AE_a9D0UD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/tests/unit/common/mocks-rpma-mr.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-12 16:14 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 5 of 10 files reviewed, 14 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/mr.h, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLO6-N9m_SCeEuJe-Q:-MTM0P_v2LLKxpB8ZYUV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/src/mr.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-12 20:14 UTC, ldorau requested changes
> Reviewed 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 8 of 10 files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/include/librpma.h, line 1997 at r4](https://reviewable.io/reviews/pmem/rpma/882#-MTMr6Tf4z4Po-Vjj7ri:-MTMr6Tg1rCffApAD_1q:b-tkdkun) ([raw file](https://github.com/pmem/rpma/blob/72b9e46f4cc785904091adc4de260cf40d0dbd1c/src/include/librpma.h#L1997)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>  * - RPMA_E_INVAL - dst != NULL and (src != NULL or src_offset != 0
>  *                  or dst_offset != 0 or len != 0)
>  * - RPMA_E_INVAL - src != NULL and (dst != NULL or src_offset != 0
>  *                  or dst_offset != 0 or len != 0)
> ```
</details>


I would not mix two "conventions", but use only one of them:
1) "linguistic": and, or, is, equal ...
OR
2) "algebraic": &&, ||, ==, != ...

So in the lines above I would replace all 'and' with '&&' and all 'or' with '||'.
The same in the rest of this file.


<!-- Sent from Reviewable.io -->

2021-02-12 20:24 UTC, ldorau reviewed
Code coverage is OK now: https://codecov.io/gh/pmem/rpma/pull/882/tree :+1: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882#-:-MTMuYC15REQ5VMDheSD:bemkkxb)* status: 8 of 10 files reviewed, 15 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-12 20:26 UTC, ldorau reviewed
> Reviewed 2 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-15 14:42 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-15 14:44 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 1997 at r4](https://reviewable.io/reviews/pmem/rpma/882#-MTMr6Tf4z4Po-Vjj7ri:-MT_zkns9c6ljDZL-fc0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72b9e46f4cc785904091adc4de260cf40d0dbd1c/src/include/librpma.h#L1997)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - dst != NULL and (src != NULL or src_offset != 0
>  *                  or dst_offset != 0 or len != 0)
>  * - RPMA_E_INVAL - src != NULL and (dst != NULL or src_offset != 0
>  *                  or dst_offset != 0 or len != 0)
> ```

I would not mix two "conventions", but use only one of them:
1) "linguistic": and, or, is, equal ...
OR
2) "algebraic": &&, ||, ==, != ...

So in the lines above I would replace all 'and' with '&&' and all 'or' with '||'.
The same in the rest of this file.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-read.c, line 113 at r3](https://reviewable.io/reviews/pmem/rpma/882#-MTLro9_14nZC3W_XFcM:-MTa8WPeAjKdZvzn7OKM:ba3maik) ([raw file](https://github.com/pmem/rpma/blob/a2c096c049509422a0063012ec85c1924fec1113/tests/unit/mr/mr-read.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I can not believe we do not verify both of these in the ibv_post_send_mock():

- wr.rdma.remote_addr
- wr.rdma.rkey

</blockquote></details>

https://github.com/pmem/rpma/issues/889


<!-- Sent from Reviewable.io -->

2021-02-16 09:32 UTC, janekmi requested changes
> Reviewed 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/mr.c, line 130 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTe9wZiClaf_U4PnOGp:-MTe9wZj22VV1fyRM9_C:bmmhl4a) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/mr.c#L130)):*
> ```C
> 		wr.sg_list = &sge;
> 		wr.num_sge = 1;
> 	}
> ```

Can you please keep the order and descriptions of assignments in both cases the same?
___
*[src/mr.c, line 186 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeA62o1cAoR0PWL0MM:-MTeA62o1cAoR0PWL0MN:bfknrjr) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/mr.c#L186)):*
> ```C
> 		wr.wr.rdma.remote_addr = dst->raddr + dst_offset;
> 		wr.wr.rdma.rkey = dst->rkey;
> 	}
> ```

order .


<!-- Sent from Reviewable.io -->

2021-02-16 09:39 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[src/mr.c, line 130 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTe9wZiClaf_U4PnOGp:-MTeBgRy9acOagP3Gt84:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/mr.c#L130)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you please keep the order and descriptions of assignments in both cases the same?
</blockquote></details>

Done.
___
*[src/mr.c, line 186 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeA62o1cAoR0PWL0MM:-MTeC9eF-N1e43uDN24-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/mr.c#L186)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

order .
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 09:40 UTC, janekmi requested changes
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 9 of 10 files reviewed, 11 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/conn.c, line 306 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCOJv721xO4dUyiLR:-MTeCOJv721xO4dUyiLS:bmvsvkh) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L306)):*
> ```C
> 	if (conn == NULL || flags == 0 ||
> 	    ((src == NULL || dst == NULL) &&
> 	    (src != NULL || dst != NULL || dst_offset != 0 || src_offset != 0 ||
> ```

+1 space
___
*[src/conn.c, line 307 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCP_Y4ZwgsTlqfxA0:-MTeCP_ZEbA5vxldnkPQ:bchxt4u) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L307)):*
> ```C
> 	    ((src == NULL || dst == NULL) &&
> 	    (src != NULL || dst != NULL || dst_offset != 0 || src_offset != 0 ||
> 	    len != 0)))
> ```

+2 spaces?
___
*[src/conn.c, line 327 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCSOAA1Yr4HmOcy9O:-MTeCSOAA1Yr4HmOcy9P:bmvsvkh) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L327)):*
> ```C
> 	if (conn == NULL || flags == 0 ||
> 	    ((src == NULL || dst == NULL) &&
> 	    (src != NULL || dst != NULL || dst_offset != 0 || src_offset != 0 ||
> ```

+1 space
___
*[src/conn.c, line 328 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCTEtEvdIu3_W0uq5:-MTeCTEtEvdIu3_W0uq6:brwd40x) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L328)):*
> ```C
> 	    ((src == NULL || dst == NULL) &&
> 	    (src != NULL || dst != NULL || dst_offset != 0 || src_offset != 0 ||
> 	    len != 0)))
> ```

+2 spaces
___
*[src/conn.c, line 350 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCUZI99t1x-l30aHQ:-MTeCUZI99t1x-l30aHR:bmvsvkh) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L350)):*
> ```C
> 	if (conn == NULL || flags == 0 ||
> 	    ((src == NULL || dst == NULL) &&
> 	    (src != NULL || dst != NULL || dst_offset != 0 || src_offset != 0 ||
> ```

+1 space
___
*[src/conn.c, line 351 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCVdd7Dt2GHiGAkcj:-MTeCVdd7Dt2GHiGAkck:brwd40x) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L351)):*
> ```C
> 	    ((src == NULL || dst == NULL) &&
> 	    (src != NULL || dst != NULL || dst_offset != 0 || src_offset != 0 ||
> 	    len != 0)))
> ```

+2 spaces


<!-- Sent from Reviewable.io -->

2021-02-16 09:59 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: 9 of 10 files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/conn.c, line 306 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCOJv721xO4dUyiLR:-MTeDV-B5GDWU-l_YBNi:bk7f4fz) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L306)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1 space
</blockquote></details>

cstyle will fail
___
*[src/conn.c, line 307 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCP_Y4ZwgsTlqfxA0:-MTeDVngE0_9m6Prg3z1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L307)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+2 spaces?
</blockquote></details>

.
___
*[src/conn.c, line 327 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCSOAA1Yr4HmOcy9O:-MTeF86Q92XEXLhnZBFt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L327)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1 space
</blockquote></details>

.
___
*[src/conn.c, line 328 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCTEtEvdIu3_W0uq5:-MTeF8iD0NDtsc32pi42:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L328)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+2 spaces
</blockquote></details>

.
___
*[src/conn.c, line 350 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCUZI99t1x-l30aHQ:-MTeF9Gt-5y6RUMm0AOU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L350)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1 space
</blockquote></details>

.
___
*[src/conn.c, line 351 at r5](https://reviewable.io/reviews/pmem/rpma/882#-MTeCVdd7Dt2GHiGAkcj:-MTeF9iw48-0_iGBmjIy:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3957757dc6957486b6e2c58079bc48e057006708/src/conn.c#L351)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+2 spaces
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-02-16 10:10 UTC, ldorau reviewed
> Reviewed 5 of 10 files at r1, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-02-16 10:24 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1994 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMH40AaWDbQpbT3ff:-MTeMH40AaWDbQpbT3fg:b4t4c4h) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L1994)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst != NULL && (src != NULL || src_offset != 0
> ```

`dst == NULL && (src != NULL || ... )`
___
*[src/include/librpma.h, line 1996 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMNTJ0EnPQI5QxzNO:-MTeMNTJ0EnPQI5QxzNP:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L1996)):*
> ```objc
>  * - RPMA_E_INVAL - dst != NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src != NULL && (dst != NULL || src_offset != 0
> ```

.
___
*[src/include/librpma.h, line 2043 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMOXMD3xEJfD0ijce:-MTeMOXMD3xEJfD0ijcf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2043)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst != NULL && (src != NULL || src_offset != 0
> ```

.
___
*[src/include/librpma.h, line 2045 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMPRk3ODV3jtp61k6:-MTeMPRk3ODV3jtp61k7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2045)):*
> ```objc
>  * - RPMA_E_INVAL - dst != NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src != NULL && (dst != NULL || src_offset != 0
> ```

.
___
*[src/include/librpma.h, line 2093 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMRDC6syNVhW693v1:-MTeMRDC6syNVhW693v2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2093)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst != NULL && (src != NULL || src_offset != 0
> ```

.
___
*[src/include/librpma.h, line 2095 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMRe47_Qy7s1ZhzCX:-MTeMRe47_Qy7s1ZhzCY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2095)):*
> ```objc
>  * - RPMA_E_INVAL - dst != NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src != NULL && (dst != NULL || src_offset != 0
> ```

.


<!-- Sent from Reviewable.io -->

2021-02-16 10:26 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[src/mr.c, line 115 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMif56rOaxIMJJL7t:-MTeMif56rOaxIMJJL7u:bz1ym8) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/mr.c#L115)):*
> ```C
> 		wr.wr.rdma.remote_addr = 0;
> 		wr.wr.rdma.rkey = 0;
> ```

`/* destination */`?
___
*[src/mr.c, line 173 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMxJz8Wqu3eG9Iz0i:-MTeMxJz8Wqu3eG9Iz0j:b1i2tty) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/mr.c#L173)):*
> ```C
> 
> 		wr.sg_list = NULL;
> 		wr.num_sge = 0;
> ```

```c
/* source */
wr.sg_list = NULL;
wr.num_sge = 0;

/* destination */
wr.wr.rdma.remote_addr = 0;
wr.wr.rdma.rkey = 0;
```
___
*[src/mr.c, line 186 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMpFfDGkvl4Y5K_V2:-MTeMpFfDGkvl4Y5K_V3:btnm6rp) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/mr.c#L186)):*
> ```C
> 
> 		wr.sg_list = &sge;
> 		wr.num_sge = 1;
> ```

These two lines are a part of the source. Please put them where they were.


<!-- Sent from Reviewable.io -->

2021-02-16 10:36 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[src/mr.c, line 115 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMif56rOaxIMJJL7t:-MTeNqJ_Bb-aVV5I3mLD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/mr.c#L115)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* destination */`?
</blockquote></details>

Done.
___
*[src/mr.c, line 173 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMxJz8Wqu3eG9Iz0i:-MTeOB4eEYEsZgWTzLfP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/mr.c#L173)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* source */
wr.sg_list = NULL;
wr.num_sge = 0;

/* destination */
wr.wr.rdma.remote_addr = 0;
wr.wr.rdma.rkey = 0;
```

</blockquote></details>

Done.
___
*[src/mr.c, line 186 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMpFfDGkvl4Y5K_V2:-MTeODPv1fSdR-EOQFvL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/mr.c#L186)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two lines are a part of the source. Please put them where they were.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1994 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMH40AaWDbQpbT3ff:-MTeOQqZ3qVc3lDZpy2e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L1994)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`dst == NULL && (src != NULL || ... )`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1996 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMNTJ0EnPQI5QxzNO:-MTeORc2EQ0WsAN2JX_E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L1996)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2043 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMOXMD3xEJfD0ijce:-MTeOaTp9taq4l8cdloR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2043)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2045 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMPRk3ODV3jtp61k6:-MTeOb7t6lTl3uQ07gZp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2045)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2093 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMRDC6syNVhW693v1:-MTeOcAYAh9nf28B53Vy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2093)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2095 at r6](https://reviewable.io/reviews/pmem/rpma/882#-MTeMRe47_Qy7s1ZhzCX:-MTeOcqQA3pWj44iPogh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/944ba6464b01972fb87055b484ce4f885d0d0ca9/src/include/librpma.h#L2095)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-16 10:49 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882#-:-MTeSSRf005rOfDCjTGz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-16 15:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1998 at r7](https://reviewable.io/reviews/pmem/rpma/882#-MTfMWMg2p79qYNMjEgK:-MTfMWMg2p79qYNMjEgL:b72f1yq) ([raw file](https://github.com/pmem/rpma/blob/733d2f614e9c04a9d346df8d7cfbe04f3c034ad0/src/include/librpma.h#L1998)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - flags are not set
> ```
</details>


Replace:

```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - flags are not set
```

with:

```
 * - RPMA_E_INVAL - conn == NULL || flags == 0
```

So finally it will be:

```
 * - RPMA_E_INVAL - conn == NULL || flags == 0
 * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
 *                  || dst_offset != 0 || len != 0)
 * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
 *                  || dst_offset != 0 || len != 0)
 * - RPMA_E_PROVIDER - ibv_post_send(3) failed
```
___
*[src/include/librpma.h, line 2047 at r7](https://reviewable.io/reviews/pmem/rpma/882#-MTfN-rVAsQ3sc9cG76H:-MTfN-rVAsQ3sc9cG76I:bcuqwdi) ([raw file](https://github.com/pmem/rpma/blob/733d2f614e9c04a9d346df8d7cfbe04f3c034ad0/src/include/librpma.h#L2047)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - flags are not set
> ```
</details>


.
___
*[src/include/librpma.h, line 2097 at r7](https://reviewable.io/reviews/pmem/rpma/882#-MTfN3jD8Ban0zatEl-f:-MTfN3jD8Ban0zatEl-g:b-8r0tek) ([raw file](https://github.com/pmem/rpma/blob/733d2f614e9c04a9d346df8d7cfbe04f3c034ad0/src/include/librpma.h#L2097)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - flags are not set
> ```
</details>


.


<!-- Sent from Reviewable.io -->

2021-02-16 15:07 UTC, ldorau reviewed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-16 15:08 UTC, ldorau requested changes
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882#-:-MTfN_UG9lnY4u8ZLU9a:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-16 15:26 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1998 at r7](https://reviewable.io/reviews/pmem/rpma/882#-MTfMWMg2p79qYNMjEgK:-MTfREDh-uZMKscLoSRA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733d2f614e9c04a9d346df8d7cfbe04f3c034ad0/src/include/librpma.h#L1998)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - flags are not set
> ```

Replace:

```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - flags are not set
```

with:

```
 * - RPMA_E_INVAL - conn == NULL || flags == 0
```

So finally it will be:

```
 * - RPMA_E_INVAL - conn == NULL || flags == 0
 * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
 *                  || dst_offset != 0 || len != 0)
 * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
 *                  || dst_offset != 0 || len != 0)
 * - RPMA_E_PROVIDER - ibv_post_send(3) failed
```

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2047 at r7](https://reviewable.io/reviews/pmem/rpma/882#-MTfN-rVAsQ3sc9cG76H:-MTfRXf_11U1L1UmlpKw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733d2f614e9c04a9d346df8d7cfbe04f3c034ad0/src/include/librpma.h#L2047)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - flags are not set
> ```

.

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2097 at r7](https://reviewable.io/reviews/pmem/rpma/882#-MTfN3jD8Ban0zatEl-f:-MTfR_Wp2FOZJQ5QbRaw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/733d2f614e9c04a9d346df8d7cfbe04f3c034ad0/src/include/librpma.h#L2097)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - conn, dst or src is NULL
>  * - RPMA_E_INVAL - dst == NULL && (src != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - src == NULL && (dst != NULL || src_offset != 0
>  *                  || dst_offset != 0 || len != 0)
>  * - RPMA_E_INVAL - flags are not set
> ```

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 06:25 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-17 06:25 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/882#-:-MTie_-F9jhLrDqnNdJy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-17 06:26 UTC, merged