Try to enhance atomic write
pmem/rpma pull request #890
Opened 2021-02-16 09:25 UTC by yangx-jy

Implement rpma_write_atomic_cmp_swp() which is the atomic write operation based on the sequence of RDMA Read and RDMA Compare & Swap.

2021-02-17 05:37 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

___
*[examples/07-atomic-write/README.md, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiTTeR46E9g60zNhWy:-MTiTTeR46E9g60zNhWz:behiwrl) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/examples/07-atomic-write/README.md#L40)):*
> ```
> 8 bytes
> ```
aligned 8 bytes
___
*[src/include/librpma.h, line 2144 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiQJUO2-XasyiLBFHU:-MTiQJUO2-XasyiLBFHV:b4ijfqf) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2144)):*
> ```
>  * rpma_write_atomic_cmp_swp - initiate the atomic write operation
>  * based on the sequence of RDMA Read and RDMA Compare & Swap
> ```
* rpma_write_atomic_cmp_swp - initiate the RDMA Compare & Swap operation
___
*[src/include/librpma.h, line 2161 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiRfGyE7LRIbaB7j7a:-MTiRfGyE7LRIbaB7j7b:b-9w25qn) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2161)):*
> ```
>  * rpma_write_atomic_cmp_swp() initiates the atomic write operation based on
>  * the sequence of RDMA Read and RDMA Compare & Swap (transferring data from
> ```
.
___
*[src/include/librpma.h, line 2175 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiUHzPC5yo_9TKVYO3:-MTiUHzPC5yo_9TKVYO4:b-tmsqhx) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2175)):*
> ```
> rpma_write_atomic
> ```
rpma_write_atomic_cmp_swp


<!-- Sent from Reviewable.io -->

2021-02-17 06:41 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[examples/07-atomic-write/README.md, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiTTeR46E9g60zNhWy:-MTihXHz63xnMYWDHuj1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/examples/07-atomic-write/README.md#L40)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 8 bytes
> ```
aligned 8 bytes
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2144 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiQJUO2-XasyiLBFHU:-MTihZBp5NdunnYP3jSR:b-dwclge) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2144)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  * rpma_write_atomic_cmp_swp - initiate the atomic write operation
>  * based on the sequence of RDMA Read and RDMA Compare & Swap
> ```
* rpma_write_atomic_cmp_swp - initiate the RDMA Compare & Swap operation

</blockquote></details>

Hi @grom72 
 
I think the previous description seems better because we implement rpma atomic write by using RDMA Compare & Swap, is it right?
___
*[src/include/librpma.h, line 2161 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiRfGyE7LRIbaB7j7a:-MTii6LD4DgbiChFdArw:brhumzt) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2161)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  * rpma_write_atomic_cmp_swp() initiates the atomic write operation based on
>  * the sequence of RDMA Read and RDMA Compare & Swap (transferring data from
> ```
.
</blockquote></details>

Same here.
___
*[src/include/librpma.h, line 2175 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiUHzPC5yo_9TKVYO3:-MTihYdI35o-0NxC0lvA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2175)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_write_atomic
> ```
rpma_write_atomic_cmp_swp
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 09:11 UTC, osalyk reviewed
> Reviewed 1 of 18 files at r1, 17 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[src/include/librpma.h, line 852 at r3](https://reviewable.io/reviews/pmem/rpma/890#-MTjDtEm-auigOH6FKkf:-MTjDtEm-auigOH6FKkg:b3kre) ([raw file](https://github.com/pmem/rpma/blob/8be5cad745ac11dde2e44a96e8b165c751d2561a/src/include/librpma.h#L852)):*
> ```objc
>  * - RPMA_MR_USAGE_SEND - memory used for send operation
>  * - RPMA_MR_USAGE_RECV - memory used for receive operation
>  * the atomic operation
> ```

?
___
*[src/include/librpma.h, line 2141 at r3](https://reviewable.io/reviews/pmem/rpma/890#-MTjECKk9K77AmUO7szA:-MTjECKk9K77AmUO7szB:b-nc9bbq) ([raw file](https://github.com/pmem/rpma/blob/8be5cad745ac11dde2e44a96e8b165c751d2561a/src/include/librpma.h#L2141)):*
> ```objc
> 		struct rpma_mr_remote *dst, size_t dst_offset,
> 		const struct rpma_mr_local *src,  size_t src_offset,
> 		int flags, const void *op_context);
> ```

Please add new line.


<!-- Sent from Reviewable.io -->

2021-02-17 10:42 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 13 of 18 files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 852 at r3](https://reviewable.io/reviews/pmem/rpma/890#-MTjDtEm-auigOH6FKkf:-MTjYE3Q5juqgasL604K:b32n8ta) ([raw file](https://github.com/pmem/rpma/blob/8be5cad745ac11dde2e44a96e8b165c751d2561a/src/include/librpma.h#L852)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

?
</blockquote></details>

Removed it.
___
*[src/include/librpma.h, line 2141 at r3](https://reviewable.io/reviews/pmem/rpma/890#-MTjECKk9K77AmUO7szA:-MTj_IHm-0IHJDeuRZC_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be5cad745ac11dde2e44a96e8b165c751d2561a/src/include/librpma.h#L2141)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please add new line.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 22:44 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 13 of 18 files reviewed, 2 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[src/include/librpma.h, line 2144 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiQJUO2-XasyiLBFHU:-MTm83S01X3F9J-fBPbx:b7btu5u) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2144)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 
 
I think the previous description seems better because we implement rpma atomic write by using RDMA Compare & Swap, is it right?
</blockquote></details>

"new" atomic write is implemented by e sequence of RDMA Read followed by RDMA Compare&Swap.
Not "only" RDMA Compare&Swap alone.
___
*[src/include/librpma.h, line 2161 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiRfGyE7LRIbaB7j7a:-MTm8azb7D8S38ePKumz:blgt4o1) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2161)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

with the existing API design, we are not able to do a "new" atomic write in one API call - it must be executed  by two steps (API calls)
We read value first to have a proper argument for Compare operation. The new version of example 07 shows how it must be implemented properly. But in contrast, to the write-based solution, it is application's responsibility to read the value and use it later in cmp&swap operation.


<!-- Sent from Reviewable.io -->

2021-02-18 03:00 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 2144 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiQJUO2-XasyiLBFHU:-MTmk_-rBk0TLnUKFfYc:b-43q6f) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2144)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

"new" atomic write is implemented by e sequence of RDMA Read followed by RDMA Compare&Swap.
Not "only" RDMA Compare&Swap alone.
</blockquote></details>

Agreed.  "RDMA Read" is not needed here.
___
*[src/include/librpma.h, line 2161 at r1](https://reviewable.io/reviews/pmem/rpma/890#-MTiRfGyE7LRIbaB7j7a:-MTmjeA-5Fd94Q8qrRzj:bov5qtt) ([raw file](https://github.com/pmem/rpma/blob/5c6e229d248e6704095ad7286730a47e35ff0bef/src/include/librpma.h#L2161)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

with the existing API design, we are not able to do a "new" atomic write in one API call - it must be executed  by two steps (API calls)
We read value first to have a proper argument for Compare operation. The new version of example 07 shows how it must be implemented properly. But in contrast, to the write-based solution, it is application's responsibility to read the value and use it later in cmp&swap operation.
</blockquote></details>

Thanks for your detailed explanation, I also removed "RDMA Read" here.


<!-- Sent from Reviewable.io -->

2021-02-19 09:08 UTC, ldorau reviewed
> Reviewed 3 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 11 of 20 files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-02-19 12:15 UTC, janekmi requested changes
> Reviewed 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 13 of 20 files reviewed, 3 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTu6piS4JKqicHyLGhu:-MTu6piS4JKqicHyLGhv:bb7b46d) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
> ```C
> 
> /*
>  * rpma_mr_atomic_cmp_swp post an RDMA atomic from src to dst
> ```

`--`
___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuAurk63Lneu8C1sCb:-MTuAurlEI1s8dMYLrmA:b-rw5ken) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
> ```C
> 
> /*
>  * rpma_mr_atomic_cmp_swp post an RDMA atomic from src to dst
> ```

I think you have here a serious conceptual issue because you are not doing here a transfer from source to destination. The IBV_WR_ATOMIC_CMP_AND_SWP opcode performs practically two transfers:
- the original value is transferred back to the initiator and written to the scatter/gather buffer (named here as `src` which is practically the first destination buffer)
- the swap value is transferred to the target and written to the remote buffer (assuming the compare condition is met) so the remote buffer is the second destination buffer

FYI @grom72 we will have another interesting topic to be discussed when you will come back from vacation. ;-)
___
*[tests/unit/common/mocks-ibverbs.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTu5cpe90BFsHMyQ2Hj:-MTu5cpe90BFsHMyQ2Hk:b88uksf) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/tests/unit/common/mocks-ibverbs.c#L269)):*
> ```C
> 		assert_int_equal(wr->wr.atomic.compare_add, args->compare);
> 		assert_int_equal(wr->wr.atomic.swap, args->swap);
> 	}
> ```

else if


<!-- Sent from Reviewable.io -->

2021-02-19 12:24 UTC, yangx-jy commented
___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuAurk63Lneu8C1sCb:-MTuE-JmEi0aozbOzRl2:byjwp26) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you have here a serious conceptual issue because you are not doing here a transfer from source to destination. The IBV_WR_ATOMIC_CMP_AND_SWP opcode performs practically two transfers:
- the original value is transferred back to the initiator and written to the scatter/gather buffer (named here as `src` which is practically the first destination buffer)
- the swap value is transferred to the target and written to the remote buffer (assuming the compare condition is met) so the remote buffer is the second destination buffer

FYI @grom72 we will have another interesting topic to be discussed when you will come back from vacation. ;-)
</blockquote></details>

Hi @janekmi 

 I understood the behavior of IBV_WR_ATOMIC_CMP_AND_SWP opcode but the comment seems wrong and rough.  I will try to rewrite it.

I wonder what is another intersting topic.


<!-- Sent from Reviewable.io -->

2021-02-19 12:25 UTC, janekmi requested changes
> Reviewed 1 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 14 of 20 files reviewed, 7 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/mr.c, line 246 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuDR19ALF4vFL2-yZO:-MTuDR19ALF4vFL2-yZP:b-d9ad40) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L246)):*
> ```C
> 	struct ibv_sge sge;
> 
> 	/* source */
> ```

As I said, it is not a source. ;-)
___
*[src/mr.c, line 248 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuD0tI8cT3MrJ695B3:-MTuD0tI8cT3MrJ695B4:b-ko0r8v) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L248)):*
> ```C
> 	/* source */
> 	sge.addr = (uint64_t)((uintptr_t)src->ibv_mr->addr + src_offset);
> 	sge.length = (uint32_t)len;
> ```

It is enough to **assume** this buffer length > 64 bits and write here just 8 (standing for 8 bytes).
The assumption has to be forced by the upper layers.
___
*[src/mr.c, line 263 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuDk7_0eVIG7k1d0pN:-MTuDk7_0eVIG7k1d0pO:bhg7ev1) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L263)):*
> ```C
> 	wr.send_flags = (flags & RPMA_F_COMPLETION_ON_SUCCESS) ?
> 		IBV_SEND_SIGNALED : 0;
> 	wr.send_flags |= IBV_SEND_FENCE;
> ```

Please add a comment: `the fence is required to simulate the future atomic write semantics which will wait for the previous flushes to complete before being executed`
___
*[src/mr.c, line 263 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuEkn6CHrAyZ4eSYva:-MTuEkn6CHrAyZ4eSYvb:b-63v5h2) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L263)):*
> ```C
> 	wr.send_flags = (flags & RPMA_F_COMPLETION_ON_SUCCESS) ?
> 		IBV_SEND_SIGNALED : 0;
> 	wr.send_flags |= IBV_SEND_FENCE;
> ```

I suggest group these lines to at least partially resemble the construction of the WR in the `rpma_mr_write()` e.g.:

```c
	/* destination */
	wr.wr.atomic.remote_addr = dst->raddr + dst_offset;
	wr.wr.atomic.compare_add = compare;
	wr.wr.atomic.swap = swap;
	wr.wr.atomic.rkey = dst->rkey;

	wr.wr_id = (uint64_t)op_context;
	wr.next = NULL;

	wr.opcode = IBV_WR_ATOMIC_CMP_AND_SWP;

	wr.send_flags = (flags & RPMA_F_COMPLETION_ON_SUCCESS) ?
		IBV_SEND_SIGNALED : 0;
	wr.send_flags |= IBV_SEND_FENCE;
```


<!-- Sent from Reviewable.io -->

2021-02-19 12:47 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 14 of 20 files reviewed, 7 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuAurk63Lneu8C1sCb:-MTuFDYB6-PzinHhvnAP:b-25vjcl) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

 I understood the behavior of IBV_WR_ATOMIC_CMP_AND_SWP opcode but the comment seems wrong and rough.  I will try to rewrite it.

I wonder what is another intersting topic.
</blockquote></details>

It was not my intention to sound 'rough'. Sorry about that.

The atomic write implemented by the atomic compare and swap is another interesting topic for us. The idea of doing this was discussed from time to time between me and @grom72 but never in detail. Generally, the intention was to follow the `rpma_atomic_write()` semantics but with a slightly different internal implementation. But your pull request made me realize there is no obvious way of replacing one with another.

||the current atomic write|compare and swap|
|---|---|---|
|compare|no compare required|the user has to know what is replaced|
|source|a locally registered buffer|a non-registered single value|
|1st destination|IBV_ACCESS_LOCAL_WRITE 1)|IBV_ACCESS_REMOTE_ATOMIC|
|2nd destination|not applicable|a locally registered buffer|

1) because this access is so commonly used we probably forgot to add a dedicated RPMA_MR_USAGE_ATOMIC (or similar) which is needed for the compare and swap and might be needed for the future RDMA atomic write support? We have to discuss it separately.

I am very grateful @yangx-jy for your pull request. It forced me to think more about this idea. Even though it is a hard nut to crack.

I hope we will have an opportunity of discussing such interesting topics in the future directly @yangx-jy. :-)


<!-- Sent from Reviewable.io -->

2021-02-19 13:18 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 14 of 20 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuAurk63Lneu8C1sCb:-MTuN-pI1ABxKhcwbyl7:b-7ytdt2) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It was not my intention to sound 'rough'. Sorry about that.

The atomic write implemented by the atomic compare and swap is another interesting topic for us. The idea of doing this was discussed from time to time between me and @grom72 but never in detail. Generally, the intention was to follow the `rpma_atomic_write()` semantics but with a slightly different internal implementation. But your pull request made me realize there is no obvious way of replacing one with another.

||the current atomic write|compare and swap|
|---|---|---|
|compare|no compare required|the user has to know what is replaced|
|source|a locally registered buffer|a non-registered single value|
|1st destination|IBV_ACCESS_LOCAL_WRITE 1)|IBV_ACCESS_REMOTE_ATOMIC|
|2nd destination|not applicable|a locally registered buffer|

1) because this access is so commonly used we probably forgot to add a dedicated RPMA_MR_USAGE_ATOMIC (or similar) which is needed for the compare and swap and might be needed for the future RDMA atomic write support? We have to discuss it separately.

I am very grateful @yangx-jy for your pull request. It forced me to think more about this idea. Even though it is a hard nut to crack.

I hope we will have an opportunity of discussing such interesting topics in the future directly @yangx-jy. :-)
</blockquote></details>

Cool, very detailed explanation.

Yes, it is hard to unify the rpma_atomic_write() semantics because they have a big difference.
Do you agree to continue implementing rpma_atomic_write_cmp_swp based on RDMA Atomic?
___
*[src/mr.c, line 246 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuDR19ALF4vFL2-yZO:-MTuNhYR2dDWggAwZplt:b-g5rz0s) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L246)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

As I said, it is not a source. ;-)
</blockquote></details>

Do you want to use dst1 and dst2?
___
*[src/mr.c, line 248 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuD0tI8cT3MrJ695B3:-MTuPZAZ6aE9m8k1CkOu:b1cw37g) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is enough to **assume** this buffer length > 64 bits and write here just 8 (standing for 8 bytes).
The assumption has to be forced by the upper layers.
</blockquote></details>

How about passing (unit32_t)RPMA_ATOMIC_WRITE_ALIGNMENT to sge.length here because RDMA Atomic just uses three 8 btyes buffers(scatter/gather buffer, comapre value, swap value).


<!-- Sent from Reviewable.io -->

2021-02-19 13:52 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 14 of 20 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/mr.c, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuYypL4qQkET3uzenV:-MTuYypL4qQkET3uzenW:bwm0ffh) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L39)):*
> ```
> (9 * sizeof(uint8_t))
> ```

See: https://github.com/pmem/rpma/pull/901


<!-- Sent from Reviewable.io -->

2021-02-19 14:35 UTC, yangx-jy commented
___
*[src/mr.c, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuYypL4qQkET3uzenV:-MTugdi04cSCBFHy4a1V:boog5e8) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> (9 * sizeof(uint8_t))
> ```

See: https://github.com/pmem/rpma/pull/901
</blockquote></details>

Hi @ldorau 

Thanks for your reminder.
It seems all 8 bits have been used so I have to extend the size of the usage field to uint_16 in the rpma_mr_get_descriptor() and rpma_mr_remote_from_descriptor() functions, right?

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-02-19 14:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 14 of 20 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/mr.c, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuYypL4qQkET3uzenV:-MTuju8K7mcXmuZLHS1d:b-wegtoe) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L39)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 

Thanks for your reminder.
It seems all 8 bits have been used so I have to extend the size of the usage field to uint_16 in the rpma_mr_get_descriptor() and rpma_mr_remote_from_descriptor() functions, right?

Best Regards,
Xiao Yang
</blockquote></details>

Yes, that's right.
And rebase, please.


<!-- Sent from Reviewable.io -->

2021-02-22 09:16 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 10 of 22 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuYypL4qQkET3uzenV:-MU808Lt0u5GhsBxw-XQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, that's right.
And rebase, please.
</blockquote></details>

Done.
___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTu6piS4JKqicHyLGhu:-MU808w1DlZGknhEwRYl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`--`
</blockquote></details>

Done.
___
*[src/mr.c, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuAurk63Lneu8C1sCb:-MU80An13RBFH2t9buCe:bbouypx) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L234)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Cool, very detailed explanation.

Yes, it is hard to unify the rpma_atomic_write() semantics because they have a big difference.
Do you agree to continue implementing rpma_atomic_write_cmp_swp based on RDMA Atomic?

</blockquote></details>

I continue implementing rpma_atomic_write_cmp_swp based on RDMA Atomic.
___
*[src/mr.c, line 246 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuDR19ALF4vFL2-yZO:-MU80EVL7nCxgAOSl_ic:bk85dh) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L246)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Do you want to use dst1 and dst2?
</blockquote></details>

I use swap_dst and read_dst here.
___
*[src/mr.c, line 248 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuD0tI8cT3MrJ695B3:-MU80KEIEpBfX8oFBiga:bkgui32) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L248)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

How about passing (unit32_t)RPMA_ATOMIC_WRITE_ALIGNMENT to sge.length here because RDMA Atomic just uses three 8 btyes buffers(scatter/gather buffer, comapre value, swap value).
</blockquote></details>

Passing RPMA_ATOMIC_WRITE_ALIGNMENT to  sge.length directly.
___
*[src/mr.c, line 263 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuDk7_0eVIG7k1d0pN:-MU80Q0b0Qn7CcgY1q4Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L263)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a comment: `the fence is required to simulate the future atomic write semantics which will wait for the previous flushes to complete before being executed`
</blockquote></details>

Done.
___
*[src/mr.c, line 263 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTuEkn6CHrAyZ4eSYva:-MU80SDE0vcnscHSXWyw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/src/mr.c#L263)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I suggest group these lines to at least partially resemble the construction of the WR in the `rpma_mr_write()` e.g.:

```c
	/* destination */
	wr.wr.atomic.remote_addr = dst->raddr + dst_offset;
	wr.wr.atomic.compare_add = compare;
	wr.wr.atomic.swap = swap;
	wr.wr.atomic.rkey = dst->rkey;

	wr.wr_id = (uint64_t)op_context;
	wr.next = NULL;

	wr.opcode = IBV_WR_ATOMIC_CMP_AND_SWP;

	wr.send_flags = (flags & RPMA_F_COMPLETION_ON_SUCCESS) ?
		IBV_SEND_SIGNALED : 0;
	wr.send_flags |= IBV_SEND_FENCE;
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-ibverbs.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/890#-MTu5cpe90BFsHMyQ2Hj:-MU80VmN7bEp7-WY0fwh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/850c0b43e6ee02b74aff7d03368a25aae3ef8e12/tests/unit/common/mocks-ibverbs.c#L269)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

else if
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-23 07:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 10 of 22 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @osalyk, and @yangx-jy)

___
*[src/mr.c, line 41 at r5](https://reviewable.io/reviews/pmem/rpma/890#-MUCpVbw5kfk5AlqzjPK:-MUCpVbx9R16gwsX76M1:b-x83vdm) ([raw file](https://github.com/pmem/rpma/blob/dcbe33c0c24eed61555e797094cb4bc2afbbed57/src/mr.c#L41)):*
> ```
> ('uint8_t' as for now)
> ```

uint16_t


<!-- Sent from Reviewable.io -->

2021-02-23 08:05 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890)* status: 10 of 22 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 41 at r5](https://reviewable.io/reviews/pmem/rpma/890#-MUCpVbw5kfk5AlqzjPK:-MUCuniH7rMuaz5NvMmz:b83qvqw) ([raw file](https://github.com/pmem/rpma/blob/dcbe33c0c24eed61555e797094cb4bc2afbbed57/src/mr.c#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ('uint8_t' as for now)
> ```

uint16_t
</blockquote></details>

Sorry for the missing.  Done


<!-- Sent from Reviewable.io -->

2021-03-05 04:12 UTC, yangx-jy reviewed
@janekmi @grom72 

Thanks a lot for sharing your slide the day before yesterday.

As you mentioned, this heavy rpma_write_atomic_cmp_swp() is not suitable for rpma atomic write probably because:
1) rpma atomic write should be simple and light.
2) application only needs one method to do atomic write.

After thinking about it again, is it possible to implement  rpma_atomic_cmp_swap() based on RDMA atomic?  this implemention includes three operations(read, compare and swap) and it may be used to verify data in some circumstances.

Best Regards,
Xiao Yang

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890#-:-MV-Qbu-0U2p2BLXVE5l:b-m79xbc)* status: 10 of 22 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-03-08 12:59 UTC, janekmi reviewed
Hi @yangx-jy. For sure it can be done. This is what compare&swap is for in the first place. But we do not have such a requirement. It may sound too bureaucratic(?) but it is not a formalism from my side. Without having a requirement and a use-case to back it up we may define an API incapable of solving the very first use-case it may be suitable for.

Because of this, I propose to close the enhanced atomic write experiment as closed successfully. By 'successful' I mean you allowed to deeply analyse the compare&swap and proved it unsuitable for replacing the current atomic write implementation.

Regarding starting the experiment to provide the compare&swap on its own (not as an atomic write replacement) we need a use-case to back it up. Having it we can return to what you have done and validate the proposed API.

So for now I propose closing this PR and coming back to it as soon as the use-case will appear.

> Reviewed 1 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/890#-:-MVGrP3k3kb_stmVEEwD:b11o711)* status: 11 of 22 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-03-18 10:55 UTC, closed without merging