examples: zero the common_data data structure
pmem/rpma pull request #913
Opened 2021-02-26 15:15 UTC by ldorau

Zero the common_data data structure,
so that the whole 'descriptors' array:
   char descriptors[DESCRIPTORS_MAX_SIZE];
was initialized.

2021-02-26 15:18 UTC, ldorau commented
See: https://github.com/pmem/fio/pull/236

2021-02-26 15:18 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913#-:-MUTuwAt8Lpi1CBEQwpM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-02-27 21:34 UTC, ldorau commented
The suppression file has to be updated.

2021-03-01 13:54 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: 7 of 8 files reviewed, all discussions resolved

___
*[examples/memcheck-librdmacm.supp, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUi2fTTBeh48Htp3Yq-:-MUi2fTW5sxtAMUhG5my:b-vyiai3) ([raw file](https://github.com/pmem/rpma/blob/e2bd393781ac2dfd8cd50faa364e4015c7c5bdc2/examples/memcheck-librdmacm.supp#L37)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> {
>    XXX CMA_INIT_CMD() should initialize the whole buffer
>    Memcheck:Param
>    write(buf)
>    fun:write
>    fun:rdma_accept
> }
> ```
</details>


@ewanglong Could you verify if examples run under valgrind pass on this pull request's branch, please?


<!-- Sent from Reviewable.io -->

2021-03-02 12:38 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/memcheck-librdmacm.supp, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUmwYfwDLikmPBAKKXz:-MUmwYfwDLikmPBAKKY-:b-snjgpv) ([raw file](https://github.com/pmem/rpma/blob/f4ffa0ca32d2acaf3a87e6624612de346e142ce7/examples/memcheck-librdmacm.supp#L38)):*
> ```
>    fun:write
>    fun:rdma_connect
> }
> ```

I think this one should also be deleted because of your fix.


<!-- Sent from Reviewable.io -->

2021-03-02 13:37 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUmwYfwDLikmPBAKKXz:-MUn8YNPBZZyYt6XW-_7:bbpkwb4) ([raw file](https://github.com/pmem/rpma/blob/f4ffa0ca32d2acaf3a87e6624612de346e142ce7/examples/memcheck-librdmacm.supp#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this one should also be deleted because of your fix.
</blockquote></details>

I suppose so too, but unfortunately I cannot verify that :-( - I am just not sure, but are you?


<!-- Sent from Reviewable.io -->

2021-03-03 03:56 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUi2fTTBeh48Htp3Yq-:-MUqDcJZ5fKM5lqKHFAN:b51eo3) ([raw file](https://github.com/pmem/rpma/blob/e2bd393781ac2dfd8cd50faa364e4015c7c5bdc2/examples/memcheck-librdmacm.supp#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> {
>    XXX CMA_INIT_CMD() should initialize the whole buffer
>    Memcheck:Param
>    write(buf)
>    fun:write
>    fun:rdma_accept
> }
> ```

@ewanglong Could you verify if examples run under valgrind pass on this pull request's branch, please?
</blockquote></details>

Error: example 11-write-with-imm server (under Valgrind) FAILED!

==3229990== Syscall param write(buf) points to uninitialised byte(s)
==3229990==    at 0x49805E7: write (in /usr/lib64/libc-2.31.so)
==3229990==    by 0x4A6223C: rdma_accept (cma.c:1943)
==3229990==    by 0x484CF71: rpma_conn_req_accept (conn_req.c:134)
==3229990==    by 0x484DB26: rpma_conn_req_connect (conn_req.c:421)
==3229990==    by 0x4015AB: main (server.c:115)


<!-- Sent from Reviewable.io -->

2021-03-03 04:01 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUmwYfwDLikmPBAKKXz:-MUqEfPY9TyrrjEKtrEg:b51eo3) ([raw file](https://github.com/pmem/rpma/blob/f4ffa0ca32d2acaf3a87e6624612de346e142ce7/examples/memcheck-librdmacm.supp#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I suppose so too, but unfortunately I cannot verify that :-( - I am just not sure, but are you?
</blockquote></details>

Error: example 11-write-with-imm server (under Valgrind) FAILED!

==3229990== Syscall param write(buf) points to uninitialised byte(s)
==3229990==    at 0x49805E7: write (in /usr/lib64/libc-2.31.so)
==3229990==    by 0x4A6223C: rdma_accept (cma.c:1943)
==3229990==    by 0x484CF71: rpma_conn_req_accept (conn_req.c:134)
==3229990==    by 0x484DB26: rpma_conn_req_connect (conn_req.c:421)
==3229990==    by 0x4015AB: main (server.c:115)


<!-- Sent from Reviewable.io -->

2021-03-03 08:34 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUi2fTTBeh48Htp3Yq-:-MUrD7J01XanBTyvyLlq:bs6w1q) ([raw file](https://github.com/pmem/rpma/blob/e2bd393781ac2dfd8cd50faa364e4015c7c5bdc2/examples/memcheck-librdmacm.supp#L37)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Error: example 11-write-with-imm server (under Valgrind) FAILED!

==3229990== Syscall param write(buf) points to uninitialised byte(s)
==3229990==    at 0x49805E7: write (in /usr/lib64/libc-2.31.so)
==3229990==    by 0x4A6223C: rdma_accept (cma.c:1943)
==3229990==    by 0x484CF71: rpma_conn_req_accept (conn_req.c:134)
==3229990==    by 0x484DB26: rpma_conn_req_connect (conn_req.c:421)
==3229990==    by 0x4015AB: main (server.c:115)
</blockquote></details>

@ewanglong thanks !

It is very strange ... We were sure this PR fixes this issue ...
___
*[examples/memcheck-librdmacm.supp, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUmwYfwDLikmPBAKKXz:-MUrCZ2dA3rqYJPMuCDm:b-c6gg7m) ([raw file](https://github.com/pmem/rpma/blob/f4ffa0ca32d2acaf3a87e6624612de346e142ce7/examples/memcheck-librdmacm.supp#L38)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Error: example 11-write-with-imm server (under Valgrind) FAILED!

==3229990== Syscall param write(buf) points to uninitialised byte(s)
==3229990==    at 0x49805E7: write (in /usr/lib64/libc-2.31.so)
==3229990==    by 0x4A6223C: rdma_accept (cma.c:1943)
==3229990==    by 0x484CF71: rpma_conn_req_accept (conn_req.c:134)
==3229990==    by 0x484DB26: rpma_conn_req_connect (conn_req.c:421)
==3229990==    by 0x4015AB: main (server.c:115)
</blockquote></details>

@ewanglong thanks !

@janekmi What do you think about that? ;-)


<!-- Sent from Reviewable.io -->

2021-03-05 07:27 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[examples/memcheck-librdmacm.supp, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUmwYfwDLikmPBAKKXz:-MV0Givc5w4rQP7UpHo2:b-f3inyb) ([raw file](https://github.com/pmem/rpma/blob/f4ffa0ca32d2acaf3a87e6624612de346e142ce7/examples/memcheck-librdmacm.supp#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@ewanglong thanks !

@janekmi What do you think about that? ;-)
</blockquote></details>

I think we have to fix the process. It is utterly absurd to have a single instance where the test can be run. At some point probably @ewanglong will have to update his system. What we will do then? xD

@ldorau leave it as is. We have to plan bolder moves to fix this situation.


<!-- Sent from Reviewable.io -->

2021-03-05 07:53 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUi2fTTBeh48Htp3Yq-:-MV0MFKn3hRupwdyF17t:bp3aow6) ([raw file](https://github.com/pmem/rpma/blob/e2bd393781ac2dfd8cd50faa364e4015c7c5bdc2/examples/memcheck-librdmacm.supp#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@ewanglong thanks !

It is very strange ... We were sure this PR fixes this issue ...
</blockquote></details>

Reverted.
___
*[examples/memcheck-librdmacm.supp, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/913#-MUmwYfwDLikmPBAKKXz:-MV0N7ji0rxgBLHNEnKr:b-safc84) ([raw file](https://github.com/pmem/rpma/blob/f4ffa0ca32d2acaf3a87e6624612de346e142ce7/examples/memcheck-librdmacm.supp#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we have to fix the process. It is utterly absurd to have a single instance where the test can be run. At some point probably @ewanglong will have to update his system. What we will do then? xD

@ldorau leave it as is. We have to plan bolder moves to fix this situation.
</blockquote></details>

OK, so please resolve this issue.


<!-- Sent from Reviewable.io -->

2021-03-05 12:16 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913#-:-MV1JQns7Yl6DVboaoHJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-03-05 12:35 UTC, osalyk reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913#-:-MV1Ne05AsTVGQ9SLDYP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-03-05 12:51 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-03-05 12:51 UTC, merged