rpma: increase cq_size to one automatically if it is zero
pmem/rpma pull request #923
Opened 2021-03-09 03:30 UTC by yangx-jy

cq_size with zero value is invalid for ibv_create_cq().

Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

2021-03-18 11:15 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MW4-bMIAvgj6oh160Jp:bg7d7t0) (no related file):*
From the brief browsing of the documentation of ibv_create_cq() and its implementation it seems, there is no such limitation: `cqe == 0` is a valid value.

Ref: https://man7.org/linux/man-pages/man3/ibv_create_cq.3.html
Ref: https://github.com/linux-rdma/rdma-core/blob/master/libibverbs/verbs.c#L528

I guess you might have been misled by the invalid implementation present in the mlx5 provider which returns EINVAL in such a case, which is not coherent with the documentation.
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx5/verbs.c#L1152

On the other hand, e.g. mlx4 provider does `+ 1` and rounding up for you. So he allocating a bigger queue than you have requested but does not introduce an undocumented error.
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx4/verbs.c#L575
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx4/verbs.c#L522

---


<!-- Sent from Reviewable.io -->

2021-03-18 12:06 UTC, ldorau reviewed
@yangx-jy What is the reason for this change?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923#-:-MW4DMVm0cQgsjBde4-u:b43o0tz)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-03-19 11:12 UTC, ldorau approved these changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW9Ak8t6BFoL6y0j2S1:-MW9Ak8u6xepSLq2h6KF:b43o0tz) (no related file):*
@yangx-jy What is the reason for this change?

---


<!-- Sent from Reviewable.io -->

2021-03-22 06:25 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWMx1Hs9EGWvxyL6ezQ:bfhfovy) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

From the brief browsing of the documentation of ibv_create_cq() and its implementation it seems, there is no such limitation: `cqe == 0` is a valid value.

Ref: https://man7.org/linux/man-pages/man3/ibv_create_cq.3.html
Ref: https://github.com/linux-rdma/rdma-core/blob/master/libibverbs/verbs.c#L528

I guess you might have been misled by the invalid implementation present in the mlx5 provider which returns EINVAL in such a case, which is not coherent with the documentation.
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx5/verbs.c#L1152

On the other hand, e.g. mlx4 provider does `+ 1` and rounding up for you. So he allocating a bigger queue than you have requested but does not introduce an undocumented error.
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx4/verbs.c#L575
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx4/verbs.c#L522
</blockquote></details>

Hi @janekmi 

Sorry for the late reply.

I also didn't see the limitation(cqe == 0 is a valid value) in documentation currently, but both rdma-core's providers and kernel's drivers add a check for cqe == 0, for example:

a) For cqe == 0, mlx4 provider rounds up to 1 as you metioned and mlx4 driver returns EINVAL:
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx4/verbs.c#L522
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/hw/mlx4/cq.c#n188

b) For cqe == 0, mlx5 provider returns EINVAL and mlx5 driver rounds up to 1: 
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx5/verbs.c#L1152
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/hw/mlx5/cq.c#n956
By the way, I think it is redundant for mlx5 provider to return EINVAL when cqe == 0

c) For cqe == 0, softroce provider does nothing and softroce driver returns EINVAL: 
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/rxe/rxe.c#L288
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/sw/rxe/rxe_cq.c#n16

d) For cqe == 0, both cxgb4 provider and cxgb4 dirver return EINVAL: 
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/cxgb4/verbs.c#L178
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/hw/cxgb4/cq.c#n1011

I am not sure if it is an undocumented rule.

Best Regards
Xiao Yang

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW9Ak8t6BFoL6y0j2S1:-MWNNpCx5Y6VmZyHkFHi:ba2vawr) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy What is the reason for this change?
</blockquote></details>

Hi @ldorau 

Sorry for the late reply.

In librpma, I try to avoid that ibv_create_cq() with cqe == 0 returns EINVAL and triggers a kernel warning on softrroce:
```
# ./server 192.168.122.189 8765 &
[1] 112174
# Mar 22 13:57:33.793657 [112174] *NOTE*  ep.c:  92: rpma_ep_listen: Waiting for incoming connection on 192.168.122.189:8765

# ./client 192.168.122.189 8765
Mar 22 13:57:39.283985 [112175] *ERROR* conn_req.c:  73: rpma_conn_req_from_id: ibv_create_cq() failed: Invalid argument

# dmesg | grep cqe
[353272.974637] rdma_rxe: cqe(0) <= 0
```

You can reproduce the issue by running example02 with the following patch:
```
diff --git a/examples/common/common-conn.c b/examples/common/common-conn.c
index 9a12967..2f4dbb0 100644
--- a/examples/common/common-conn.c
+++ b/examples/common/common-conn.c
@@ -66,10 +66,21 @@ client_connect(struct rpma_peer *peer, const char *addr, const char *port,
                struct rpma_conn **conn_ptr)
 {
        struct rpma_conn_req *req = NULL;
+       struct rpma_conn_cfg *cfg = NULL;
        enum rpma_conn_event conn_event = RPMA_CONN_UNDEFINED;

+       if (rpma_conn_cfg_new(&cfg)) {
+               fprintf(stderr, "rpma_conn_cfg_new failed\n");
+               return -1;
+       }
+
+       if (rpma_conn_cfg_set_cq_size(cfg, 0)) {
+               fprintf(stderr, "rpma_conn_cfg_set_cq_size failed\n");
+               return -1;
+       }
+
        /* create a connection request */
-       int ret = rpma_conn_req_new(peer, addr, port, NULL, &req);
+       int ret = rpma_conn_req_new(peer, addr, port, cfg, &req);
        if (ret)
                return ret;
```

Best Regards,
Xiao Yang

---


<!-- Sent from Reviewable.io -->

2021-03-22 06:47 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWNfnABB4bHvQ0iceZ_:b7k4m2i) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

Sorry for the late reply.

I also didn't see the limitation(cqe == 0 is a valid value) in documentation currently, but both rdma-core's providers and kernel's drivers add a check for cqe == 0, for example:

a) For cqe == 0, mlx4 provider rounds up to 1 as you metioned and mlx4 driver returns EINVAL:
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx4/verbs.c#L522
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/hw/mlx4/cq.c#n188

b) For cqe == 0, mlx5 provider returns EINVAL and mlx5 driver rounds up to 1: 
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/mlx5/verbs.c#L1152
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/hw/mlx5/cq.c#n956
By the way, I think it is redundant for mlx5 provider to return EINVAL when cqe == 0

c) For cqe == 0, softroce provider does nothing and softroce driver returns EINVAL: 
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/rxe/rxe.c#L288
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/sw/rxe/rxe_cq.c#n16

d) For cqe == 0, both cxgb4 provider and cxgb4 dirver return EINVAL: 
Ref: https://github.com/linux-rdma/rdma-core/blob/master/providers/cxgb4/verbs.c#L178
Ref: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/infiniband/hw/cxgb4/cq.c#n1011

I am not sure if it is an undocumented rule.

Best Regards
Xiao Yang

</blockquote></details>

Shall we assume that we need a completion queue all the time with at least one element there?
In such case we should fix  ``` rpma_conn_cfg_set_cq_size ``` to reject value 0 as invalid one.

---


<!-- Sent from Reviewable.io -->

2021-03-22 07:06 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWNiskO7_4rtVA43mmR:bi5u0qc) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we assume that we need a completion queue all the time with at least one element there?
In such case we should fix  ``` rpma_conn_cfg_set_cq_size ``` to reject value 0 as invalid one.

</blockquote></details>

Hi @grom72 

Right, we have to create a completion queue all the time with at least one element.

We can fix the issue by two ways:
1) Increase cq_size to 1 automatically if cq_size == 0 as my patch did.
2) Make  rpma_conn_cfg_set_cq_size() reject q_size == 0 as @grom72 suggested.

Either of them is OK for me.

@janekmi @ldorau, do you like which one?

Best Regards,
Xiao Yang

---


<!-- Sent from Reviewable.io -->

2021-03-22 09:58 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWOMP5I38XMiYqPBYUD:bkwkb70) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

Right, we have to create a completion queue all the time with at least one element.

We can fix the issue by two ways:
1) Increase cq_size to 1 automatically if cq_size == 0 as my patch did.
2) Make  rpma_conn_cfg_set_cq_size() reject q_size == 0 as @grom72 suggested.

Either of them is OK for me.

@janekmi @ldorau, do you like which one?

Best Regards,
Xiao Yang
</blockquote></details>

But if we fix ```rpma_conn_cfg_set_cq_size``` we will not need to fix   ```rpma_conn_cfg_get_cqe``` at all.

---


<!-- Sent from Reviewable.io -->

2021-03-22 14:51 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWPPONL3WOir87fYrky:b-snitfo) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But if we fix ```rpma_conn_cfg_set_cq_size``` we will not need to fix   ```rpma_conn_cfg_get_cqe``` at all.
</blockquote></details>

@grom72 

Agreed.  We need to fix rpma_conn_cfg_set_cq_size or rpma_conn_cfg_get_cqe (not both of them).
But I am not sure which one is better.

Best Regards,
Xiao Yang

---


<!-- Sent from Reviewable.io -->

2021-03-25 18:28 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWecbdlC5YvAerrRwIC:btgfxw2) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 

Agreed.  We need to fix rpma_conn_cfg_set_cq_size or rpma_conn_cfg_get_cqe (not both of them).
But I am not sure which one is better.

Best Regards,
Xiao Yang
</blockquote></details>

Do we need to fix it at all?

For now, it is undocumented, but if we introduce the limitation explicitly we are closing the door which nobody asked us to close. What if RDMA/libibverbs standard tomorrow will introduce a new feature and will make use of this undocumented value in any other way, but since we have closed this door earlier we won't be able to follow the standard easily.

For me, it solves nobody's problem. And taking it on us may introduce additional problems. I see no value.

---


<!-- Sent from Reviewable.io -->

2021-03-26 14:03 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/923)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/923#-MW4-bMHEfVYdSSlDVmG:-MWipFqNCF2AXtQQ18Nw:bi12gtm) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we need to fix it at all?

For now, it is undocumented, but if we introduce the limitation explicitly we are closing the door which nobody asked us to close. What if RDMA/libibverbs standard tomorrow will introduce a new feature and will make use of this undocumented value in any other way, but since we have closed this door earlier we won't be able to follow the standard easily.

For me, it solves nobody's problem. And taking it on us may introduce additional problems. I see no value.
</blockquote></details>

Hi @janekmi

OK, I will close the PR for now.
I will repon it again in future when somebody reports the related issue.

Best Regards,
Xiao Yang

---


<!-- Sent from Reviewable.io -->

2021-03-26 14:05 UTC, closed without merging