tools: add cpuload option to server
pmem/rpma pull request #937
Opened 2021-03-15 14:40 UTC by osalyk

2021-03-15 14:47 UTC, janekmi reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqKmmW8uHq_z67NNkH:-MVqKmmW8uHq_z67NNkI:bp7q20r) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
> ```
> [cpuio]
> ioengine=cpuio
> cpuload=${cpuload}
> ```

EoL is missing.
___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqLTm63AN50MFDeG6n:-MVqLTm63AN50MFDeG6o:bq9l3mz) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
> ```
> [cpuio]
> ioengine=cpuio
> cpuload=${cpuload}
> ```

There is no way for the GPSPM server to run without `cpuio`.
___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqLZr9E59VPAKeS5tm:-MVqLZr9E59VPAKeS5tn:b-5wq0q2) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
> ```
> [cpuio]
> ioengine=cpuio
> cpuload=${cpuload}
> ```

There is no way for the APM server to run with `cpuio`.


<!-- Sent from Reviewable.io -->

2021-03-15 14:51 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqLTm63AN50MFDeG6n:-MVqMUl82BAP986fNpJZ:b-z5o11p) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

There is no way for the GPSPM server to run without `cpuio`.
</blockquote></details>

I think we may use `--section`: https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-section


<!-- Sent from Reviewable.io -->

2021-03-15 14:53 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqN4zP490npn4-Aul1:-MVqN4zP490npn4-Aul2:b39k8mf) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
> ```
> [cpuio]
> ioengine=cpuio
> cpuload=${cpuload}
> ```

Don't forget about `numjobs` for this section.


<!-- Sent from Reviewable.io -->

2021-03-15 15:25 UTC, janekmi reviewed
The general idea is as follows:

- lat(cpuload)
    bs=4096
    threads=1
    cpuload={0,25,75,100/99}
    - GPSPM no-busy-poll
    - APM no-busy-poll
    - GPSPM busy-poll
- bw(cpuload)
    bs=64KiB
    threads=1
    iodepht=2
    cpuload={0,25,75,100/99}
- bw-mt(cpuload)
    bs=4KiB
    threads=32
    iodepht=2
    cpuload={0,25,75,100/99}

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937#-:-MVqTH5C4GXD6VFiWkAi:b-79lppe)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTPRkAeKB5N8jCllp:-MVqTPRkAeKB5N8jCllq:bk5a6lc) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L20)):*
> ```Shell
> 	echo "Error: $1"
> 	echo
> 	echo "Usage: $0 <server_ip> all|apm|gpspm|aof_sw|aof_hw [all|read|randread|write|randwrite|rw|randrw] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|bw-cpu|lat|lat-cpu]"
> ```

We will have two bw(cpu) measurements. As for now, I think about naming them:
- bw-cpu (as you have named here) and
- bw-cpu-mt as the multithreaded variant of the bandwidth measurement
___
*[tools/perf/rpma_fio_bench.sh, line 217 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTr1t1DT8FjNzKB3z:-MVqTr1t1DT8FjNzKB4-:b3kr0) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L217)):*
> ```Shell
> 	bw-cpu)
> 		BUSY_WAIT_POLLING=0
> 		THREADS=24
> ```

1
___
*[tools/perf/rpma_fio_bench.sh, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTttO3ommafwU61ly:-MVqTttP1wnJ3-xpn86R:b-cgkcp7) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L220)):*
> ```Shell
> 		BLOCK_SIZE=4096
> 		DEPTH=2
> 		CPU_LOAD=(10 20 30 40 50)
> ```

To start off I think of five values slightly differently spread so: 0, 25, 50, 70, 100.
Please refer to the list above.
___
*[tools/perf/rpma_fio_bench.sh, line 239 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUTSV3FgW-BEjIF0T:-MVqUTSV3FgW-BEjIF0U:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L239)):*
> ```Shell
> 		BLOCK_SIZE=4096
> 		DEPTH=1
> 		CPU_LOAD=(10 20 30 40 50)
> ```

.


<!-- Sent from Reviewable.io -->

2021-03-15 15:31 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqVEis07uNxo_mIm_F:-MVqVEis07uNxo_mIm_G:bbnfpsm) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L20)):*
> ```Shell
> 	echo "Error: $1"
> 	echo
> 	echo "Usage: $0 <server_ip> all|apm|gpspm|aof_sw|aof_hw [all|read|randread|write|randwrite|rw|randrw] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|bw-cpu|lat|lat-cpu]"
> ```

I'm seriously thinking about making `busy_polling_wait` a part of either `apm|gpspm` or completely another argument.
This is because e.g. we would like to measure bw-bs for both modes of gpspm.
___
*[tools/perf/rpma_fio_bench.sh, line 400 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUnSuDjrgy9oYJGI7:-MVqUnSuDjrgy9oYJGI8:b-73d4js) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L400)):*
> ```Shell
> 		fi
> 
> 		echo "[mode: $PERSIST_MODE, op: $OP, size: $BS, threads: $TH, iodepth: $DP sync: $SYNC cpuload: $CPU]"
> ```

We are missing a few `,` here.
___
*[tools/perf/rpma_fio_bench.sh, line 493 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUyeyCvYNNhkEOT3K:-MVqUyeyCvYNNhkEOT3L:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L493)):*
> ```Shell
> 
> case $MODES in
> bw-bs|bw-dp-exp|bw-dp-lin|bw-th|bw-cpu|lat|lat-cpu)
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 496 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUz8gEx54FOFBAOnj:-MVqUz8gEx54FOFBAOnk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L496)):*
> ```Shell
> 	;;
> all)
> 	MODES="lat lat-cpu bw-bs bw-cpu bw-th bw-dp-lin bw-dp-exp"
> ```

.


<!-- Sent from Reviewable.io -->

2021-03-15 15:32 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 1 of 2 files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTttO3ommafwU61ly:-MVqW54H8nAo-sbCNHBl:bytpxf2) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L220)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To start off I think of five values slightly differently spread so: 0, 25, 50, 70, 100.
Please refer to the list above.
</blockquote></details>

70 -> 75. Sorry.


<!-- Sent from Reviewable.io -->

2021-03-16 08:24 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 0 of 3 files reviewed, 12 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTPRkAeKB5N8jCllp:-MVu6syd6OzoXLlsoq1r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We will have two bw(cpu) measurements. As for now, I think about naming them:
- bw-cpu (as you have named here) and
- bw-cpu-mt as the multithreaded variant of the bandwidth measurement
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqVEis07uNxo_mIm_F:-MVu6w5Q5pH_QHmKZvUT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm seriously thinking about making `busy_polling_wait` a part of either `apm|gpspm` or completely another argument.
This is because e.g. we would like to measure bw-bs for both modes of gpspm.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 217 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTr1t1DT8FjNzKB3z:-MVu6zdk2ITx57n1PyMP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L217)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqTttO3ommafwU61ly:-MVu77TF2HUplXXxTRV6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L220)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

70 -> 75. Sorry.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 239 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUTSV3FgW-BEjIF0T:-MVu7BND2MZM4hpB7YyZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L239)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 400 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUnSuDjrgy9oYJGI7:-MVu7DUHCOzN2eozr4Z1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L400)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We are missing a few `,` here.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 493 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUyeyCvYNNhkEOT3K:-MVu7F1aCZ74fawq9Jzt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L493)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 496 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqUz8gEx54FOFBAOnj:-MVu7Ffl6cKkvPrlRiyS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/rpma_fio_bench.sh#L496)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqKmmW8uHq_z67NNkH:-MVu7Hcn6qQBTBafBGne:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

EoL is missing.
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqLTm63AN50MFDeG6n:-MVu7IgP9ogWsQF6EkTs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we may use `--section`: https://fio.readthedocs.io/en/latest/fio_man.html#cmdoption-section
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqLZr9E59VPAKeS5tm:-MVu7JWv1ypR5eCheXHQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

There is no way for the APM server to run with `cpuio`.
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_gpspm-server.fio, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/937#-MVqN4zP490npn4-Aul1:-MVu7K6D4szyYd6Mm-Ph:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4922310d97ca9bbae759bcf32d9d61714647ef1/tools/perf/fio_jobs/librpma_gpspm-server.fio#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Don't forget about `numjobs` for this section.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 08:36 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: all files reviewed, 11 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 108 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu7Rr4AiJ8xY52Ui82:-MVu7Rr4AiJ8xY52Ui83:byqkww3) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L108)):*
> ```Shell
> 	usage "REMOTE_DIRECT_WRITE_TO_PMEM not set"
> elif [ -z "$BUSY_WAIT_POLLING" ]; then
> 	BUSY_WAIT_POLLING=1
> ```

It stops other arguments validation. You have to do it in the "normal" code, not during the argument validation.
___
*[tools/perf/rpma_fio_bench.sh, line 190 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu7wecDIX1Sq8xPD09:-MVu7wed16wrpcnEaWFg:bx5f5k4) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L190)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_dp${DEPTH}
> 		SYNC=0
> 		SECTION="--section server"
> ```

It is the section argument but I think it will be more comprehensible to name it according to its purpose e.g. 

```sh
CPULOAD="--section server" # no CPU load
```
___
*[tools/perf/rpma_fio_bench.sh, line 199 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu8M2A-tvN7zP4XtYT:-MVu8M2A-tvN7zP4XtYU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L199)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}
> 		SYNC=0
> 		SECTION="--section server"
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 208 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu8Mc-CRbQ9wr4HLHS:-MVu8Mc-CRbQ9wr4HLHT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L208)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}
> 		SYNC=0
> 		SECTION="--section server"
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 217 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu8NAu-CQ_pr_LTnh7:-MVu8NAu-CQ_pr_LTnh8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L217)):*
> ```Shell
> 		NAME_SUFFIX=bs${BLOCK_SIZE}_dp${DEPTH}
> 		SYNC=0
> 		SECTION="--section server"
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 227 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8Ud-72pPxMYnp_SS:-MVu8Ud-72pPxMYnp_ST:bl12gij) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L227)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}_dp${DEPTH}
> 		SYNC=0
> 		SECTION=""
> ```

```sh
CPULOAD="" # no section filtering so CPU load will be included
```
___
*[tools/perf/rpma_fio_bench.sh, line 237 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8WwC4hu5QO15cgcr:-MVu8WwC4hu5QO15cgcs:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L237)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}_dp${DEPTH}
> 		SYNC=0
> 		SECTION=""
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 246 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8Y1X2nY2mFMW7LH8:-MVu8Y1X2nY2mFMW7LH9:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L246)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_dp${DEPTH}
> 		SYNC=1
> 		SECTION="--section server"
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 256 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8ajbEaQp5uuGMUdi:-MVu8ajbEaQp5uuGMUdj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L256)):*
> ```Shell
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}_dp${DEPTH}
> 		SYNC=1
> 		SECTION=""
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 375 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu9Etv9730icJBJfzC:-MVu9EtwBVTFgDhjUyyH:b-1zvv85) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L375)):*
> ```Shell
> 			DP="${DEPTH}"
> 			CPU="${CPU_LOAD[${i}]}"
> 			;;
> ```

You can combine both bw-cpu* modes e.g.:

```sh
case $MODE in
bw-cpu|bw-cpu-mt)
    ;;
# or
bw-cpu*)
    ;;
esac
```
___
*[tools/perf/rpma_fio_bench.sh, line 410 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu9av65KZly2l_NrEf:-MVu9av65KZly2l_NrEg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L410)):*
> ```Shell
> 			sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 				$REMOTE_USER@$SERVER_IP "$ENV $REMOTE_TRACER \
> 				${REMOTE_FIO_PATH}fio $REMOTE_JOB_PATH $SECTION >> $LOG_ERR 2>&1" 2>>$LOG_ERR &
> ```

.


<!-- Sent from Reviewable.io -->

2021-03-16 08:40 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 42 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVuAnzL8_FUcE2oozXe:-MVuAnzL8_FUcE2oozXf:b-hmnma0) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L42)):*
> ```Shell
> 	echo "export REMOTE_JOB_PATH=/custom/jobs/path"
> 	echo "export REMOTE_JOB_MEM_PATH=/path/to/mem"
> 	echo "export BUSY_WAIT_POLLING=0/1"
> ```

This has to be part of the output file name.


<!-- Sent from Reviewable.io -->

2021-03-16 08:59 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 2 of 3 files reviewed, 12 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 108 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu7Rr4AiJ8xY52Ui82:-MVuBYuHAImnhXVJxx68:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It stops other arguments validation. You have to do it in the "normal" code, not during the argument validation.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 190 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu7wecDIX1Sq8xPD09:-MVuBqWe70gHUcj0szUp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is the section argument but I think it will be more comprehensible to name it according to its purpose e.g. 

```sh
CPULOAD="--section server" # no CPU load
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 199 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu8M2A-tvN7zP4XtYT:-MVuClDYB3QlD959GEHY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L199)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 208 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu8Mc-CRbQ9wr4HLHS:-MVuCm-v7HhmNzVk-NLw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L208)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 217 at r2](https://reviewable.io/reviews/pmem/rpma/937#-MVu8NAu-CQ_pr_LTnh7:-MVuCmp1CePn0zCw6EVT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb98d8c645dc81f746f41732cc194a2b0f321d9e/tools/perf/rpma_fio_bench.sh#L217)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 42 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVuAnzL8_FUcE2oozXe:-MVuFk8Y8w0Ur-VGFrEc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This has to be part of the output file name.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 227 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8Ud-72pPxMYnp_SS:-MVuCu6b3qzM1czf-Ii2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L227)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
CPULOAD="" # no section filtering so CPU load will be included
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 237 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8WwC4hu5QO15cgcr:-MVuCv0K9p87_yFU2eCW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L237)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 246 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8Y1X2nY2mFMW7LH8:-MVuCvg_1-iPCSHbVat-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L246)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 256 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu8ajbEaQp5uuGMUdi:-MVuCwbVBoFuIKg5aLhX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L256)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 375 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu9Etv9730icJBJfzC:-MVuD4XzAINDXIsw9E-a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L375)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can combine both bw-cpu* modes e.g.:

```sh
case $MODE in
bw-cpu|bw-cpu-mt)
    ;;
# or
bw-cpu*)
    ;;
esac
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 410 at r3](https://reviewable.io/reviews/pmem/rpma/937#-MVu9av65KZly2l_NrEf:-MVuDD0QDLW9cIeW3xJ-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f851f7ceebe5ea62f5975606c680d939203d5825/tools/perf/rpma_fio_bench.sh#L410)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 09:07 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 122 at r4](https://reviewable.io/reviews/pmem/rpma/937#-MVuGbjMBG-l7UeyATRb:-MVuGbjNEIwMxJwxLhKx:b357xnm) ([raw file](https://github.com/pmem/rpma/blob/182058517b24149838713c5ffc843f3ca10de782/tools/perf/rpma_fio_bench.sh#L122)):*
> ```Shell
> 
> if [ -z "$BUSY_WAIT_POLLING" ]; then
> 	BUSY_WAIT_POLLING=1
> ```

You are missing

```sh
fi
```
___
*[tools/perf/rpma_fio_bench.sh, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/937#-MVuGoQe4hwPi0uEH60e:-MVuGoQe4hwPi0uEH60f:b-rmogbg) ([raw file](https://github.com/pmem/rpma/blob/182058517b24149838713c5ffc843f3ca10de782/tools/perf/rpma_fio_bench.sh#L125)):*
> ```Shell
> 
> if [ "$BUSY_WAIT_POLLING" == "1" ]; then
> 	POLLING="use_get"
> ```

busy-wait
___
*[tools/perf/rpma_fio_bench.sh, line 127 at r4](https://reviewable.io/reviews/pmem/rpma/937#-MVuGpwu8K6pZKPcWHHx:-MVuGpwu8K6pZKPcWHHy:b1zy0ci) ([raw file](https://github.com/pmem/rpma/blob/182058517b24149838713c5ffc843f3ca10de782/tools/perf/rpma_fio_bench.sh#L127)):*
> ```Shell
> 	POLLING="use_get"
> else
> 	POLLING="use_wait"
> ```

no-busy-wait


<!-- Sent from Reviewable.io -->

2021-03-16 09:10 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 122 at r4](https://reviewable.io/reviews/pmem/rpma/937#-MVuGbjMBG-l7UeyATRb:-MVuHw7aBH2LYpOuD3Uv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/182058517b24149838713c5ffc843f3ca10de782/tools/perf/rpma_fio_bench.sh#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing

```sh
fi
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 125 at r4](https://reviewable.io/reviews/pmem/rpma/937#-MVuGoQe4hwPi0uEH60e:-MVuI61l3x18kTeMnppz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/182058517b24149838713c5ffc843f3ca10de782/tools/perf/rpma_fio_bench.sh#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

busy-wait
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 127 at r4](https://reviewable.io/reviews/pmem/rpma/937#-MVuGpwu8K6pZKPcWHHx:-MVuI6kVA-TxidMFdN6W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/182058517b24149838713c5ffc843f3ca10de782/tools/perf/rpma_fio_bench.sh#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

no-busy-wait
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-16 09:13 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937#-:-MVuIt1fE2vUVqYATJJ3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-03-16 09:20 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-03-16 09:20 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937#-:-MVuKbjIB6T_ymU16NT6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-03-16 09:28 UTC, janekmi approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/937)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-03-16 09:28 UTC, merged