test: add rpma_peer_cfg_from_descriptor & rpma_peer_cfg_set_direct_wr…
pmem/rpma pull request #961
Opened 2021-03-29 06:53 UTC by ewanglong

…ite_to_pmem multithreaded test

2021-04-01 21:50 UTC, janekmi requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXENxI06pUy0sC45erm:-MXENxI06pUy0sC45ern:by82u0y) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L16)):*
> ```C
> #include <librpma.h>
> 
> #define DIRECT_WRITE_TO_PMEM true
> ```

I'm not sure if it is not too much... but if you would like to stick with it please do a rename e.g.:

```c
#define DIRECT_WRITE_TO_PMEM_SUPPORTED true
```
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEMnnFAmdNbMOM_Tu5:-MXEMnnFAmdNbMOM_Tu6:b2bc065) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L26)):*
> ```C
> static const char *api_name = "rpma_peer_cfg_from_descriptor";
> 
> static void *thread_main(void *arg)
> ```

```c
static void *
thread_main(void *arg)
```
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEMxCj9XYNF8aGqcH0:-MXEMxCj9XYNF8aGqcH1:bmkufqw) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L39)):*
> ```C
> 	/* Create a remote peer configuration structure from input descriptor */
> 	ret = rpma_peer_cfg_from_descriptor(p_thread_args->desc,
> 			p_thread_args->desc_size, &pcfg);
> ```

I think we can go further and use the same copy of the descriptor for all `rpma_peer_cfg_from_descriptor()` in all threads.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXENNKX-MkW0YZpHvAv:-MXENNKY8LbKnhy-6b38:bi604c) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L47)):*
> ```C
> 	}
> 
> 	/* check if direct write to PMEM is expected(supported or not) */
> ```

```
/* check if the direct write to PMEM is as expected (supported or not) */
```
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXENcMh3ECn42RE7e28:-MXENcMh3ECn42RE7e29:b-tf1hvq) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L50)):*
> ```C
> 	ret = rpma_peer_cfg_get_direct_write_to_pmem(pcfg,
> 			&direct_write_to_pmem);
> 	if (ret || direct_write_to_pmem != DIRECT_WRITE_TO_PMEM) {
> ```

Please split these conditions. Otherwise, the error message is confusing.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXELlWi-G-HljhNCj1u:-MXELlWi-G-HljhNCj1v:b-2d4877) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L108)):*
> ```C
> 		threads_args[i].thread_num = i;
> 		threads_args[i].desc = (uint8_t *)(&direct_write_to_pmem);
> 		threads_args[i].desc_size = desc_size;
> ```

It is not a valid way of creating a descriptor. Please use `rpma_peer_cfg_get_descriptor ()` and `rpma_peer_cfg_get_descriptor_size()`.
___
*[tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEOVs_2PGQV5OrTRKD:-MXEOVs_2PGQV5OrTRKE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L16)):*
> ```C
> #include <librpma.h>
> 
> #define DIRECT_WRITE_TO_PMEM true
> ```

.
___
*[tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEOiV2AaNmDZFJG3xP:-MXEOiV2AaNmDZFJG3xQ:b-w8e1t3) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L47)):*
> ```C
> 	/* set direct write to PMEM supported */
> 	ret = rpma_peer_cfg_set_direct_write_to_pmem(pcfg,
> 				DIRECT_WRITE_TO_PMEM);
> ```

If you would like to test this API call for multi-threadability namely `rpma_peer_cfg_set_direct_write_to_pmem()` you should use the same `struct rpma_peer_cfg` in all threads. BUT I see no purpose in doing so. What result the end-user would expect if one would set the same variable/state from multiple threads at the same time? The result would be completely random. No value.

Sorry for saying this but this API call is one of those which won't be available for MT-use.


<!-- Sent from Reviewable.io -->

2021-04-06 08:04 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXENxI06pUy0sC45erm:-MXaCOJd6uM-6qixJ9ci:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure if it is not too much... but if you would like to stick with it please do a rename e.g.:

```c
#define DIRECT_WRITE_TO_PMEM_SUPPORTED true
```
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEMnnFAmdNbMOM_Tu5:-MXaCJ-l55vCYClv0Yyv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
static void *
thread_main(void *arg)
```
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEMxCj9XYNF8aGqcH0:-MXaCKKn3jCWD8EYQG3n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can go further and use the same copy of the descriptor for all `rpma_peer_cfg_from_descriptor()` in all threads.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXENNKX-MkW0YZpHvAv:-MXaCKzG2cxuxtiOEWK2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
/* check if the direct write to PMEM is as expected (supported or not) */
```
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXENcMh3ECn42RE7e28:-MXaCNf958zOzTvv29Wi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please split these conditions. Otherwise, the error message is confusing.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEOVs_2PGQV5OrTRKD:-MXaCQ_07dVdN3qZ6gyc:b2kre6p) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

remove this test.
___
*[tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXEOiV2AaNmDZFJG3xP:-MXaCTlV-Ur3LlgCoHz0:b-e1cl5x) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L47)):*
> remove this test.
remove this test.


<!-- Sent from Reviewable.io -->

2021-04-06 08:04 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 0 of 2 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/961#-MXELlWi-G-HljhNCj1u:-MX_v9VwAM7XUjSrHKrM:bs7wumb) ([raw file](https://github.com/pmem/rpma/blob/2d9a59087b5867073e6224f7590c52d960720dd5/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a valid way of creating a descriptor. Please use `rpma_peer_cfg_get_descriptor ()` and `rpma_peer_cfg_get_descriptor_size()`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-06 09:59 UTC, ldorau reviewed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-06 13:49 UTC, janekmi requested changes
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMGNG4fvXtUgr9VxP:-MXbMGNG4fvXtUgr9VxQ:b-6ix47f) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L17)):*
> ```C
> 
> #define DIRECT_WRITE_TO_PMEM_SUPPORTED true
> #define DESCRIPTORS_MAX_SIZE 24
> ```

I think this value is too well-fitted. ;-)
Please use something generic e.g. 512.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 49 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbLDR640CyUUNJ_oSw:-MXbLDR640CyUUNJ_oSx:b-pn11z) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L49)):*
> ```C
> 	}
> 
> 	/* check if the direct write to PMEM is as expected(supported or not) */
> ```

You are missing a space here: "... expected (supported..."
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbLpwK3uYcj1lMsq41:-MXbLpwK3uYcj1lMsq42:bie6tr8) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L117)):*
> ```C
> 	ret = rpma_peer_cfg_new(&pcfg);
> 	if (ret) {
> 		fprintf(stderr, "rpma_peer_cfg_new() failed");
> ```

Please add `\n` at the end of the string.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 126 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbLwuMD7ZyEATTx0q4:-MXbLwuMD7ZyEATTx0q5:bb7c4kz) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L126)):*
> ```C
> 	if (ret) {
> 		fprintf(stderr,
> 			"rpma_peer_cfg_set_direct_write_to_pmem() failed");
> ```

`\n`
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 127 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbR04F3dXzYPGI1B14:-MXbR04F3dXzYPGI1B15:b-mkpmtu) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L127)):*
> ```C
> 		fprintf(stderr,
> 			"rpma_peer_cfg_set_direct_write_to_pmem() failed");
> 		goto err_free_p_threads;
> ```

You have to have another case when you will call `rpma_conn_cfg_delete()`.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 134 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMBrO63P5vJZ9gpEl:-MXbMBrO63P5vJZ9gpEm:bb7c4kz) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L134)):*
> ```C
> 	ret = rpma_peer_cfg_get_descriptor_size(pcfg, &desc_size);
> 	if (ret) {
> 		fprintf(stderr, "rpma_peer_cfg_get_descriptor_size() failed");
> ```

`\n`
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 137 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMTRg6f584xHl3OlJ:-MXbMTRg6f584xHl3OlK:b-646q74) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L137)):*
> ```C
> 		goto err_free_p_threads;
> 	}
> ```

Please verify if `desc_size <= DESCRIPTORS_MAX_SIZE`.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 142 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMay10kDfAbxjB6S1:-MXbMay10kDfAbxjB6S2:b-7u4bs5) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L142)):*
> ```C
> 			&descriptors[0]);
> 	if (ret) {
> 		fprintf(stderr, "rpma_peer_cfg_get_descriptor() failed");
> ```

`\n`.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 148 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbN06o6GbLwTc6Lz8R:-MXbN06o6GbLwTc6Lz8S:by88mf1) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L148)):*
> ```C
> 	for (i = 0; i < thread_num; i++) {
> 		threads_args[i].thread_num = i;
> 		threads_args[i].desc = (uint8_t *)(&descriptors[0]);
> ```

`(void *)`?


<!-- Sent from Reviewable.io -->

2021-04-07 02:35 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMGNG4fvXtUgr9VxP:-MXeAj33CYqjUmz255Bx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this value is too well-fitted. ;-)
Please use something generic e.g. 512.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 49 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbLDR640CyUUNJ_oSw:-MXeAjdNB_-x5QvCA_PV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing a space here: "... expected (supported..."
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbLpwK3uYcj1lMsq41:-MXeAe529LWWLKzCtxlW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L117)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add `\n` at the end of the string.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 126 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbLwuMD7ZyEATTx0q4:-MXeAf9p-jpEewGTCn7d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`\n`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 127 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbR04F3dXzYPGI1B14:-MXeAfq37w5zNFgZ-5B1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to have another case when you will call `rpma_conn_cfg_delete()`.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 134 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMBrO63P5vJZ9gpEl:-MXeAgVL0_ARnTn6CfPn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L134)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`\n`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 137 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMTRg6f584xHl3OlJ:-MXeAhETDMlJWr1vFEOg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please verify if `desc_size <= DESCRIPTORS_MAX_SIZE`.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 142 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbMay10kDfAbxjB6S1:-MXeAhpl0vTy7aEtBuBV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L142)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`\n`.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 148 at r3](https://reviewable.io/reviews/pmem/rpma/961#-MXbN06o6GbLwTc6Lz8R:-MXeAiKn4lMwL2GLJGfo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1261383a0a42e2c4d3c88ab5a98744958420a7ac/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L148)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`(void *)`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 08:20 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 71 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfPHuoEdp2MjVky0jM:-MXfPHuoEdp2MjVky0jN:bf73wru) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L71)):*
> ```
> err_peer_cfg_delete:
> ```

unused and unneeded, remove it


<!-- Sent from Reviewable.io -->

2021-04-07 08:29 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 71 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfPHuoEdp2MjVky0jM:-MXfRsf814KWAh6oKtdq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> err_peer_cfg_delete:
> ```

unused and unneeded, remove it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 08:37 UTC, janekmi requested changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 184 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfQsA079T0kmNJ9qme:-MXfQsA079T0kmNJ9qmf:bj3jkut) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L184)):*
> ```C
> 		fprintf(stderr, "rpma_peer_cfg_delete failed: %s\n",
> 			rpma_err_2str(ret));
> 		exit(-1);
> ```

I believe `exit()` is not needed here. We can go to the end in this case.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 57 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfSv076NFBLf1tHawm:-MXfShcfDg_pJEiwmBtE:b-7ywbqf) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L57)):*
> ```C
> 	if (ret) {
> 		fprintf(stderr, "[thread #%d] \
> 			rpma_peer_cfg_get_direct_write_to_pmem failed: %s\n",
> ```

```c
fprintf(stderr,
    "[thread #%d] rpma_peer_cfg_get_direct_write_to_pmem failed: %s\n",
```

Please do not break string literals.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 65 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTFB3BpOWqQk0M2mp:-MXfTFB3BpOWqQk0M2mq:bbk6l3h) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L65)):*
> ```C
> 		fprintf(stderr, "[thread #%d] \
> 			rpma_peer_cfg_get_direct_write_to_pmem: \
> 			unexpected direct_write_to_pmem = %d\n",
> ```

Please do not break string literals.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 74 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTJrw2AZsVh5bj7rB:-MXfTJrw2AZsVh5bj7rC:b3m0guf) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L74)):*
> ```C
> 	if (ret) {
> 		fprintf(stderr, "[thread #%d] rpma_peer_cfg_delete \
> 			failed: %s\n", p_thread_args->thread_num,
> ```

```c
    fprintf(stderr,
        "[thread #%d] rpma_peer_cfg_delete failed: %s\n",
        p_thread_args->thread_num,
```
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 141 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTWST-mKxlyukCBp8:-MXfTWSUB0azpqFvDysl:b-u27489) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L141)):*
> ```C
> 	if (desc_size > DESCRIPTORS_MAX_SIZE) {
> 		fprintf(stderr, "rpma_peer_cfg_get_descriptor_size() return \
> 			desc_size > DESCRIPTORS_MAX_SIZE\n");
> ```

```c
fprintf(stderr,
    "rpma_peer_cfg_get_descriptor_size() return desc_size > DESCRIPTORS_MAX_SIZE\n");
```


<!-- Sent from Reviewable.io -->

2021-04-07 08:41 UTC, ldorau reviewed
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-07 08:57 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 184 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfQsA079T0kmNJ9qme:-MXfX5NU8dlQjiB-loY9:bwjclae) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I believe `exit()` is not needed here. We can go to the end in this case.
</blockquote></details>

exit(-1) helps this multithreaded process to exit with error. Otherwise in this condition, the test will pass without error report.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 57 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfSv076NFBLf1tHawm:-MXfXSW8DCTUX3toSY0b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
fprintf(stderr,
    "[thread #%d] rpma_peer_cfg_get_direct_write_to_pmem failed: %s\n",
```

Please do not break string literals.

</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 65 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTFB3BpOWqQk0M2mp:-MXfXXQx3waDsgxX1IEl:b-b5bzvx) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please do not break string literals.
</blockquote></details>

"[thread #%d] rpma_peer_cfg_get_direct_write_to_pmem:  unexpected direct_write_to_pmem = %d\n" will exceed the 80 characters limit. So change to as below:
		fprintf(stderr,
			"[thread #%d] rpma_peer_cfg_get_direct_write_to_pmem: \
			unexpected direct_write_to_pmem = %d\n",
			p_thread_args->thread_num, direct_write_to_pmem); 
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 74 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTJrw2AZsVh5bj7rB:-MXfXwrw-MhsmICMDmwj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
    fprintf(stderr,
        "[thread #%d] rpma_peer_cfg_delete failed: %s\n",
        p_thread_args->thread_num,
```

</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 141 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTWST-mKxlyukCBp8:-MXfXzcGBqOkoIgtOXI8:bd5aecs) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L141)):*
> "rpma_peer_cfg_get_descriptor_size() return desc_size > DESCRIPTORS_MAX_SIZE\n");
will exceed the 80 characters limit. So change to as below:
		fprintf(stderr,
			"rpma_peer_cfg_get_descriptor_size() return desc_size \
			> DESCRIPTORS_MAX_SIZE\n");


<!-- Sent from Reviewable.io -->

2021-04-07 09:24 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 65 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTFB3BpOWqQk0M2mp:-MXfcw2W4hQKPtX_XyQ6:b-5s80qr) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L65)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

"[thread #%d] rpma_peer_cfg_get_direct_write_to_pmem:  unexpected direct_write_to_pmem = %d\n" will exceed the 80 characters limit. So change to as below:
		fprintf(stderr,
			"[thread #%d] rpma_peer_cfg_get_direct_write_to_pmem: \
			unexpected direct_write_to_pmem = %d\n",
			p_thread_args->thread_num, direct_write_to_pmem); 
</blockquote></details>

String literals should not be broken. They can exceed 80 characters limit as long as they are the only token in the line.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 141 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTWST-mKxlyukCBp8:-MXfdKks9NXe-xixS2eh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L141)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

> "rpma_peer_cfg_get_descriptor_size() return desc_size > DESCRIPTORS_MAX_SIZE\n");
will exceed the 80 characters limit. So change to as below:
		fprintf(stderr,
			"rpma_peer_cfg_get_descriptor_size() return desc_size \
			> DESCRIPTORS_MAX_SIZE\n");
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-04-07 09:28 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 65 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTFB3BpOWqQk0M2mp:-MXfeE2oBTkWQWPy-1ZJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

String literals should not be broken. They can exceed 80 characters limit as long as they are the only token in the line.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 141 at r5](https://reviewable.io/reviews/pmem/rpma/961#-MXfTWST-mKxlyukCBp8:-MXfeFYl61xgqsHdsk6R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/72c31508f65d0ec2c86e73fc606958bf52d30e47/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-07 09:30 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 184 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfQsA079T0kmNJ9qme:-MXfemAr53iwuUMXH-CK:btl2qxp) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L184)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

exit(-1) helps this multithreaded process to exit with error. Otherwise in this condition, the test will pass without error report.
</blockquote></details>

No, it will not pass, it will return ret != 0


<!-- Sent from Reviewable.io -->

2021-04-07 09:38 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 184 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfQsA079T0kmNJ9qme:-MXffxGlAcWs0u0tWi6A:blvdt0c) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L184)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it will not pass, it will return ret != 0
</blockquote></details>

It's in sub-thread context. I did a small test as below part of code shown. It passed test. Or need write-back the thread return value into main thread and so on. But it seems not neat. 
...
  ret = -1;
  return ret;
}


<!-- Sent from Reviewable.io -->

2021-04-07 09:47 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 184 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfQsA079T0kmNJ9qme:-MXfiIeH6L9WdLg9M9Nv:befqzi9) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L184)):*
It is not sub-thread, it is the end of the `main()` function:
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> 	if (ret) {
> 		fprintf(stderr, "rpma_peer_cfg_delete failed: %s\n",
> 			rpma_err_2str(ret));
> 		exit(-1);
> 	}
>
> err_free_threads_args:
> 	free(threads_args);
>
> err_free_p_threads:
> 	free(p_threads);
>
> 	return ret;
> }
> ```
</details>



<!-- Sent from Reviewable.io -->

2021-04-07 09:51 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c, line 184 at r4](https://reviewable.io/reviews/pmem/rpma/961#-MXfQsA079T0kmNJ9qme:-MXfjWDm5pQiK4_-CRaD:b-l4fpfr) ([raw file](https://github.com/pmem/rpma/blob/e348723a09fc8f3e8da33300d0f47551868f5b54/tests/multithreaded/peer/rpma_peer_cfg_from_descriptor.c#L184)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not sub-thread, it is the end of the `main()` function:

> ```
> 	if (ret) {
> 		fprintf(stderr, "rpma_peer_cfg_delete failed: %s\n",
> 			rpma_err_2str(ret));
> 		exit(-1);
> 	}
>
> err_free_threads_args:
> 	free(threads_args);
>
> err_free_p_threads:
> 	free(p_threads);
>
> 	return ret;
> }
> ```

</blockquote></details>

Ok. Done.


<!-- Sent from Reviewable.io -->

2021-04-07 09:55 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-07 14:32 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961#-:-MXgjvYd2sRHZlAlJhYl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-07 14:33 UTC, janekmi requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/961#-MXgk1Y6-i_BAHqVVu6f:-MXgk1Y6-i_BAHqVVu6g:b-pu0brv) (no related file):*
Please fix the commit message and the PR title.

---


<!-- Sent from Reviewable.io -->

2021-04-07 14:41 UTC, ewanglong reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/961#-MXgk1Y6-i_BAHqVVu6f:-MXglnhZDCe-kRfgYhf-:blznec4) (no related file):*
> test: add rpma_peer_cfg_from_descriptor multithreaded test
is it not OK? I followed previous merged commit like "test: add rpma_peer_cfg_new multithreaded test"

---


<!-- Sent from Reviewable.io -->

2021-04-08 05:11 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961#-:-MXjtD43A3G3IWSlJ-Mh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/961#-MXgk1Y6-i_BAHqVVu6f:-MXjt8NZ4up4C2uK6gY5:bgmgmir) (no related file):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

> test: add rpma_peer_cfg_from_descriptor multithreaded test
is it not OK? I followed previous merged commit like "test: add rpma_peer_cfg_new multithreaded test"
</blockquote></details>

IMHO it is OK now

---


<!-- Sent from Reviewable.io -->

2021-04-08 05:36 UTC, ldorau approved these changes
The CircleCI build passes too: https://app.circleci.com/pipelines/github/ldorau/rpma/68/workflows/d285c94a-34bb-4892-99ca-7e682a36a15f/jobs/72

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961#-:-MXjyqZU6f5X62e0zzgA:bde6j0w)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-08 07:06 UTC, janekmi approved these changes
@ldorau :+1: 
@ewanglong <img class="emoji" title=":lgtm_strong:" alt=":lgtm_strong:" align="absmiddle" src="https://reviewable.io/lgtm_strong.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/961#-:-MXkIJj91ocF640zn40O:b-snnxqo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)



<!-- Sent from Reviewable.io -->

2021-04-08 07:06 UTC, merged