tools: separate the common part of the scripts for benchmarking
pmem/rpma pull request #974
Opened 2021-04-01 17:32 UTC by osalyk

- [ ] #973

2021-04-01 21:53 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/common.sh, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/974#-MXEQDX731AR9XmEqE2m:-MXEQDX731AR9XmEqE2n:b2nh59u) ([raw file](https://github.com/pmem/rpma/blob/5f790cdfa0fe274a0a3a7dc7be8543de9202c586/tools/perf/common.sh#L194)):*
> ```Shell
> if [ "$1" == "--set_ddio" ]; then
> 	set_ddio
> fi
> ```

;-)


<!-- Sent from Reviewable.io -->

2021-04-01 21:56 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/common.sh, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/974#-MXEQjzeAFNNhCOJP8uI:-MXEQjzeAFNNhCOJP8uJ:b-kfzcj9) ([raw file](https://github.com/pmem/rpma/blob/5f790cdfa0fe274a0a3a7dc7be8543de9202c586/tools/perf/common.sh#L8)):*
> ```Shell
> 
> #
> # common.sh -- a single-sided ib_read_lat/bw and Fio RPMA tool (EXPERIMENTAL)
> ```

`common.sh` sound too generic. Maybe `bench_common.sh`? Give it a thought.
___
*[tools/perf/ib_read.sh, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/974#-MXEQOoN3Jc5UjBTBrEN:-MXEQOoN3Jc5UjBTBrEO:bo695vy) ([raw file](https://github.com/pmem/rpma/blob/5f790cdfa0fe274a0a3a7dc7be8543de9202c586/tools/perf/ib_read.sh#L28)):*
> ```Shell
> 	echo "usage: $0 <server_ip> <all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat>"
> 	echo
> 	./common.sh --usage
> ```

You should include the common.sh and use functions from this module e.g.:

```sh
source ./common.sh

# ...

common_usage
```


<!-- Sent from Reviewable.io -->

2021-04-02 05:58 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/ib_read.sh, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/974#-MXEQOoN3Jc5UjBTBrEN:-MXG93Iv5yqtjgsLZATc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f790cdfa0fe274a0a3a7dc7be8543de9202c586/tools/perf/ib_read.sh#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You should include the common.sh and use functions from this module e.g.:

```sh
source ./common.sh

# ...

common_usage
```
</blockquote></details>

Done.
___
*[tools/perf/common.sh, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/974#-MXEQjzeAFNNhCOJP8uI:-MXG7dka6NeQ-EHG0q43:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f790cdfa0fe274a0a3a7dc7be8543de9202c586/tools/perf/common.sh#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`common.sh` sound too generic. Maybe `bench_common.sh`? Give it a thought.
</blockquote></details>

Done.
___
*[tools/perf/common.sh, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/974#-MXEQDX731AR9XmEqE2m:-MXG7sNTCufOeQ43PtSz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f790cdfa0fe274a0a3a7dc7be8543de9202c586/tools/perf/common.sh#L194)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

;-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-15 12:15 UTC, janekmi requested changes
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: all files reviewed, 28 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/ib_read.sh, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKAeZn50IYL2XxMAKP:-MYKAeZn50IYL2XxMAKQ:b-abw7lv) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L15)):*
> ```Shell
> #
> 
> source ./bench_common.sh
> ```

I have just realized we can make it even more resilient:

```sh
source $(dirname $0)/bench_common.sh
```

Otherwise, you can not run it from another directory e.g.:

```sh
$ ./perf/ib_read.sh
```
___
*[tools/perf/ib_read.sh, line 26 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKITnoCGnajff1R2bq:-MYKITnoCGnajff1R2br:bfnb55c) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L26)):*
> ```Shell
> if [ "$1" == "--env" ]; then
> 	show_environment
> 	exit 0
> ```

Since `show_environment` is always followed by `exit 0` maybe it should be a part of it? :thinking: 
___
*[tools/perf/ib_read.sh, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKIi8M82sb7BJDwkRb:-MYKIi8M82sb7BJDwkRc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L31)):*
> ```Shell
> if [ "$#" -lt 2 ]; then
> 	ib_usage "Too few arguments"
> 	exit 1
> ```

.
___
*[tools/perf/ib_read.sh, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKLTacDlpUS3mSvUP3:-MYKLTacDlpUS3mSvUP4:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L136)):*
> ```Shell
> 	*)
> 		ib_usage "Wrong mode: $MODE"
> 		exit 1
> ```

.
___
*[tools/perf/ib_read.sh, line 288 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKLeCE4OXD5CfHEAwN:-MYKLeCF3JowUfT1Rgo0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L288)):*
> ```Shell
> *)
> 	ib_usage "Wrong mode: $MODES"
> 	exit 1
> ```

.
___
*[tools/perf/report_bench.sh, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKICtS4ftBUU2WVX6y:-MYKICtT6NYblY04yAgR:brkm7ha) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/report_bench.sh#L57)):*
> ```Shell
> 		if [ "$REMOTE_DIRECT_WRITE_TO_PMEM" == "1" -o "$REMOTE_SUDO_NOPASSWD" == "1" ]; then
> 			for op in read randread; do
> 				./ib_read.sh $SERVER_IP $mode
> ```

Why do you want to run this test twice with the same command line?
___
*[tools/perf/rpma_fio_bench.sh, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKAyyY5q8veXV1iAnI:-MYKAyyY5q8veXV1iAnJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L14)):*
> ```Shell
> #
> 
> source ./bench_common.sh
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKDPp734JEuyD1mBar:-MYKDPp734JEuyD1mBas:bd5nkyh) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L16)):*
> ```Shell
> source ./bench_common.sh
> 
> TIMESTAMP=$(date +%y-%m-%d-%H%M%S)
> ```

This also can be a part of the common. It will be executed when you will do `source` and the variable should be just available as usual.
___
*[tools/perf/rpma_fio_bench.sh, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKDenJ074nSl6Fnx1v:-MYKDenJ074nSl6Fnx1w:bc0irgz) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L20)):*
> ```Shell
> if [ "$1" == "--env" ]; then
> 	show_environment
> 	exit 0
> ```

:clap: 
___
*[tools/perf/rpma_fio_bench.sh, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKE-1Y1EjlSnabjRd2:-MYKE-1Y1EjlSnabjRd3:b-vo2gxt) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L25)):*
> ```Shell
> if [ "$#" -lt 2 ] || [ "$#" -eq 2 -a "$2" != "all" ]; then
> 	rpma_usage "Too few arguments"
> 	exit 1
> ```

Not needed. `rpma_usage` already does it.
___
*[tools/perf/rpma_fio_bench.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKE3NC9P6Tof1F0Mmv:-MYKE3NC9P6Tof1F0Mmw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L30)):*
> ```Shell
> 	read|randread|rw|randrw)
> 		rpma_usage "The 'gpspm' mode does not support the '$3' operation for now."
> 		exit 1
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKE4Cq6dmUQTBGMLiT:-MYKE4Cq6dmUQTBGMLiU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L37)):*
> ```Shell
> 	read|randread|randwrite|rw|randrw)
> 		rpma_usage "The '$2' mode does not support the '$3' operation."
> 		exit 1
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 175 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKEfxD3n_PWciVnfwX:-MYKEfxD3n_PWciVnfwY:b-a2yfht) ([raw file](https://github.com/pmem/rpma/blob/00eb836c5a84a9c3067ddfe213c6989496ec6114/tools/perf/rpma_fio_bench.sh#L175)):*
> ```Shell
> 	case $PERSIST_MODE in
> 	apm|aof_hw)
> 		REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM=1
> ```

This is a part of this benchmark. Please keep it here.
___
*[tools/perf/rpma_fio_bench.sh, line 187 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKEljfAboQP_Dg12yp:-MYKEljfAboQP_Dg12yq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/00eb836c5a84a9c3067ddfe213c6989496ec6114/tools/perf/rpma_fio_bench.sh#L187)):*
> ```Shell
> 		;;
> 	gpspm|aof_sw)
> 		REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM=0
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 378 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKFFWWAIayEfp-Bv1K:-MYKFFWX-Db_EqdF8RsG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L378)):*
> ```Shell
> *)
> 	rpma_usage "Wrong persistency mode: $P_MODES"
> 	exit 1
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 390 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKFEcB1juK6wzgMzT7:-MYKFEcB1juK6wzgMzT8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L390)):*
> ```Shell
> *)
> 	rpma_usage "Wrong operation: $OPS"
> 	exit 1
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 402 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKFGnm3r1p6oDOYxaO:-MYKFGnm3r1p6oDOYxaP:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L402)):*
> ```Shell
> *)
> 	rpma_usage "Wrong mode: $MODES"
> 	exit 1
> ```

.
___
*[tools/perf/bench_common.sh, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYK9tK10h3_L49vIz-6:-MYK9tK10h3_L49vIz-7:b-db64yn) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/bench_common.sh#L8)):*
> ```Shell
> 
> #
> # bench_common.sh -- a single-sided ib_read_lat/bw and Fio RPMA tool (EXPERIMENTAL)
> ```

`... and Fio tools common (EXPERIMENTAL)`
___
*[tools/perf/bench_common.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKBf4ADG7diJcO7nAm:-MYKBf4ADG7diJcO7nAn:b8vlua9) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/bench_common.sh#L120)):*
> ```Shell
> 	echo "export DO_NOTHING=1 (create empty output files; do not run the actual execution)"
> 	echo "export DUMP_CMDS=1 (dump all commands that would be executed; do not run the actual execution)"
> }
> ```

I'm not exactly happy with how usage and env currently look like. It is a mess. Too much data conveys no meaning.
@osalyk can you give it a thought?

From the top of my head. I think it would be great e.g.:
- to get only req [...]

2021-04-15 14:05 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 0 of 4 files reviewed, 27 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/ib_read.sh, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKAeZn50IYL2XxMAKP:-MYKoVUz5spLnjRg5vEe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have just realized we can make it even more resilient:

```sh
source $(dirname $0)/bench_common.sh
```

Otherwise, you can not run it from another directory e.g.:

```sh
$ ./perf/ib_read.sh
```
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 26 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKITnoCGnajff1R2bq:-MYKhkhK8qq52qFhxGB4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since `show_environment` is always followed by `exit 0` maybe it should be a part of it? :thinking: 
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKIi8M82sb7BJDwkRb:-MYKi99T7sBk_GmTknxG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKLTacDlpUS3mSvUP3:-MYKiDkg4cB6okl6yrQI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L136)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 288 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKLeCE4OXD5CfHEAwN:-MYKiJazD5PSiEtf5mQg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/ib_read.sh#L288)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKICtS4ftBUU2WVX6y:-MYKiT5g2twnCX24h_By:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/report_bench.sh#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why do you want to run this test twice with the same command line?
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKAyyY5q8veXV1iAnI:-MYKiVJ-CDSUUA0d_eGB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKDPp734JEuyD1mBar:-MYKim4L6LQCFeNJTYKM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This also can be a part of the common. It will be executed when you will do `source` and the variable should be just available as usual.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKE-1Y1EjlSnabjRd2:-MYKixPPDcqQKnEeNOym:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed. `rpma_usage` already does it.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKE3NC9P6Tof1F0Mmv:-MYKiy0k0xhd9U3h39OU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKE4Cq6dmUQTBGMLiT:-MYKj4AS3EgjzhZyHtL2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 175 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKEfxD3n_PWciVnfwX:-MYKodK0BDiz72Ow958x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/00eb836c5a84a9c3067ddfe213c6989496ec6114/tools/perf/rpma_fio_bench.sh#L175)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is a part of this benchmark. Please keep it here.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 187 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKEljfAboQP_Dg12yp:-MYKodyA3GWtiy6nNHQt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/00eb836c5a84a9c3067ddfe213c6989496ec6114/tools/perf/rpma_fio_bench.sh#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 378 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKFFWWAIayEfp-Bv1K:-MYKjAli0whqcZPl_KoV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L378)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 390 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKFEcB1juK6wzgMzT7:-MYKjBT4BAVGgoYkaDO5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L390)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 402 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKFGnm3r1p6oDOYxaO:-MYKjC7_Ct9zvtUfVWx-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/rpma_fio_bench.sh#L402)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/bench_common.sh, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYK9tK10h3_L49vIz-6:-MYKXOss2nHiwEGmMRt8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/bench_common.sh#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`... and Fio tools common (EXPERIMENTAL)`
</blockquote></details>

Done.
___
*[tools/perf/bench_common.sh, line 122 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKJIWKCz0Y1toMFpxR:-MYKY2MX9n9iemfmuHgc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/bench_common.sh#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`check_env`? It is not much about the parameters per se.
</blockquote></details>

Done.
___
*[tools/perf/bench_common.sh, line 128 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKCbtR7l4A46Ea7NAP:-MYKoMGl [...]

2021-04-16 06:40 UTC, janekmi requested changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/ib_read.sh, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOJ2-ICxjcRw-bKtZd:-MYOJ2-ICxjcRw-bKtZe:bl2qcb) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L61)):*
0

And please give a good comment on why e.g.:
> By default, Direct Write to PMem is impossible due to DDIO=on which forces writing to cache instead of PMem directly. This test requires restoring the default settings.

FYI: @grom72 probably going to ICX and beyond we would have to come with a more fine-grained control here. Since DDIO=on, in this case, do not have to mean DIRECT_WRITE_TO_PMEM=0 (note eADR).
___
*[tools/perf/ib_read.sh, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOMsST2xwi037FmUH7:-MYOMsSUETdQclXQgpce:b8wvela) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L61)):*
> ```Shell
> 	MODE=$2
> 
> 	REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM=1
> ```

Please keep it close to `set_ddio`. Or if you think it should be set upfront, bring `set_ddio` here.
___
*[tools/perf/ib_read.sh, line 155 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONKSi94zm3-ufE04a:-MYONKSi94zm3-ufE04b:b-ad72wr) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L155)):*
> ```Shell
> 		echo "REMOTE_DIRECT_WRITE_TO_PMEM=$REMOTE_DIRECT_WRITE_TO_PMEM" >> $SERVER_DUMP
> 		echo >> $SERVER_DUMP
> 	fi
> ```

This part also seems common for both benchmarks. I think it can be incorporated into `set_ddio`.
___
*[tools/perf/ib_read.sh, line 229 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOO-na2EFM3H2_8lm1:-MYOO-na2EFM3H2_8lm2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L229)):*
> ```Shell
> 			if [ "x$REMOTE_CMD_PRE_SUBST" != "x" ]; then
> 				remote_command --pre
> 			fi
> ```

.
___
*[tools/perf/ib_read.sh, line 248 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOO0Z_E4jfRLUzlzgo:-MYOO0Z_E4jfRLUzlzgp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L248)):*
> ```Shell
> 			if [ "x$REMOTE_CMD_POST_SUBST" != "x" ]; then
> 				remote_command --post
> 			fi
> ```

.
___
*[tools/perf/report_bench.sh, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKICtS4ftBUU2WVX6y:-MYOKYoI9U11Ac5rnaLY:b-u6n7mh) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/report_bench.sh#L57)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This test requires the opposite value of DIRECT_WRITE_TO_PMEM. Please see my comments to ib_read.sh.
___
*[tools/perf/rpma_fio_bench.sh, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOOT1fD9imh3elbD-_:-MYOOT1fD9imh3elbD-a:bldri6q) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L198)):*
> ```Shell
> 	fi
> 
> 	set_ddio
> ```

Same here. I think `set_ddio` can be closer to setting the `REQUIRED_DIRECT_WRITE_TO_PMEM` also in this case. What do you think?
___
*[tools/perf/rpma_fio_bench.sh, line 203 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONf7k56Xcrse-HJk1:-MYONf7k56Xcrse-HJk2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L203)):*
> ```Shell
> 		echo "REMOTE_DIRECT_WRITE_TO_PMEM=$REMOTE_DIRECT_WRITE_TO_PMEM" >> $SERVER_DUMP
> 		echo >> $SERVER_DUMP
> 	fi
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 267 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONqmc6WBctnhLTXqd:-MYONqmc6WBctnhLTXqe:b1eka0d) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L267)):*
> ```Shell
> 			if [ "x$REMOTE_CMD_PRE_SUBST" != "x" ]; then
> 				remote_command --pre
> 			fi
> ```

The `if` around `remote_command` function calls should be a part of it.
___
*[tools/perf/rpma_fio_bench.sh, line 302 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONyFl4Bf7RY5bliQe:-MYONyFl4Bf7RY5bliQf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L302)):*
> ```Shell
> 			if [ "x$REMOTE_CMD_POST_SUBST" != "x" ]; then
> 				remote_command --post
> 			fi
> ```

.
___
*[tools/perf/bench_common.sh, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOLUIVCPHyldVoiTgY:-MYOLUIVCPHyldVoiTgZ:bwbug5a) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/bench_common.sh#L8)):*
> ```Shell
> 
> #
> # bench_common.sh -- a single-sided ib_read_lat/bw and Fio tools common (EXPERIMENTAL)
> ```

This line is too long. Please break and indent to `a single-sided` with spaces.


<!-- Sent from Reviewable.io -->

2021-04-16 09:49 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: all files reviewed, 13 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYP42dU2jPVx5J5Fp15:-MYP42dU2jPVx5J5Fp16:bel2umk) ([raw file](https://github.com/pmem/rpma/blob/cb33d7f5db8b05f7eb557e5c040481f7d822ea33/tools/perf/rpma_fio_bench.sh#L121)):*
<details><summary><i alt="summary">Quoted 12 lines of code…</i></summary>

> ```
> elif [ -z "$JOB_NUMA" ]; then
> 	usage "JOB_NUMA not set"
> elif [ -z "$REMOTE_USER" ]; then
> 	usage "REMOTE_USER not set"
> elif [ -z "$REMOTE_PASS" ]; then
> 	usage "REMOTE_PASS not set"
> elif [ -z "$REMOTE_JOB_NUMA" ]; then
> 	usage "REMOTE_JOB_NUMA not set"
> elif [ -z "$REMOTE_RNIC_PCIE_ROOT_PORT" -a "$REMOTE_SUDO_NOPASSWD" == "1" ]; then
> 	usage "REMOTE_RNIC_PCIE_ROOT_PORT not set"
> elif [ -z "$REMOTE_DIRECT_WRITE_TO_PMEM" -a "$REMOTE_SUDO_NOPASSWD" != "1" ]; then
> 	usage "REMOTE_DIRECT_WRITE_TO_PMEM not set"
> ```
</details>


I do not think it is a good idea to remove this code. It is very useful. It can be hard to figure out what variable is missing without this code.


<!-- Sent from Reviewable.io -->

2021-04-16 13:13 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: all files reviewed, 13 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYP42dU2jPVx5J5Fp15:-MYPo6Bn6dLZG5OcyTnC:b-xzkwr) ([raw file](https://github.com/pmem/rpma/blob/cb33d7f5db8b05f7eb557e5c040481f7d822ea33/tools/perf/rpma_fio_bench.sh#L121)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> elif [ -z "$JOB_NUMA" ]; then
> 	usage "JOB_NUMA not set"
> elif [ -z "$REMOTE_USER" ]; then
> 	usage "REMOTE_USER not set"
> elif [ -z "$REMOTE_PASS" ]; then
> 	usage "REMOTE_PASS not set"
> elif [ -z "$REMOTE_JOB_NUMA" ]; then
> 	usage "REMOTE_JOB_NUMA not set"
> elif [ -z "$REMOTE_RNIC_PCIE_ROOT_PORT" -a "$REMOTE_SUDO_NOPASSWD" == "1" ]; then
> 	usage "REMOTE_RNIC_PCIE_ROOT_PORT not set"
> elif [ -z "$REMOTE_DIRECT_WRITE_TO_PMEM" -a "$REMOTE_SUDO_NOPASSWD" != "1" ]; then
> 	usage "REMOTE_DIRECT_WRITE_TO_PMEM not set"
> ```

I do not think it is a good idea to remove this code. It is very useful. It can be hard to figure out what variable is missing without this code.
</blockquote></details>

It is now part of the `check_env` function.


<!-- Sent from Reviewable.io -->

2021-04-16 14:09 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: all files reviewed, 12 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYP42dU2jPVx5J5Fp15:-MYQ-t-80oH54Ha8Kh_Q:bqnpvto) ([raw file](https://github.com/pmem/rpma/blob/cb33d7f5db8b05f7eb557e5c040481f7d822ea33/tools/perf/rpma_fio_bench.sh#L121)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is now part of the `check_env` function.
</blockquote></details>

Ah, OK


<!-- Sent from Reviewable.io -->

2021-04-19 14:10 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/ib_read.sh, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOJ2-ICxjcRw-bKtZd:-MYe3SyU7fhq2oRHmqR1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L61)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

0

And please give a good comment on why e.g.:
> By default, Direct Write to PMem is impossible due to DDIO=on which forces writing to cache instead of PMem directly. This test requires restoring the default settings.

FYI: @grom72 probably going to ICX and beyond we would have to come with a more fine-grained control here. Since DDIO=on, in this case, do not have to mean DIRECT_WRITE_TO_PMEM=0 (note eADR).

</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 61 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOMsST2xwi037FmUH7:-MYe6JfI57VpN-msO7ks:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L61)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please keep it close to `set_ddio`. Or if you think it should be set upfront, bring `set_ddio` here.
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 155 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONKSi94zm3-ufE04a:-MYe71QPBFxs4NikSO42:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L155)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This part also seems common for both benchmarks. I think it can be incorporated into `set_ddio`.
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 229 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOO-na2EFM3H2_8lm1:-MYeSkUh3bOWipoYmuuv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L229)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 248 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOO0Z_E4jfRLUzlzgo:-MYeShjHEnn1wvJ4hig-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/ib_read.sh#L248)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKICtS4ftBUU2WVX6y:-MYe8YcxBnUBg3EVg9tx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/report_bench.sh#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This test requires the opposite value of DIRECT_WRITE_TO_PMEM. Please see my comments to ib_read.sh.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 198 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOOT1fD9imh3elbD-_:-MYe9BhB3VLjAs5S3Ntx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L198)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. I think `set_ddio` can be closer to setting the `REQUIRED_DIRECT_WRITE_TO_PMEM` also in this case. What do you think?
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 203 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONf7k56Xcrse-HJk1:-MYe9Qui9fjPnOAElwgr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L203)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 267 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONqmc6WBctnhLTXqd:-MYeSiZW6WIQndwSQmFy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L267)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The `if` around `remote_command` function calls should be a part of it.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 302 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYONyFl4Bf7RY5bliQe:-MYeSjIE1MBc_axaa8Ab:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/rpma_fio_bench.sh#L302)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/bench_common.sh, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/974#-MYOLUIVCPHyldVoiTgY:-MYe2zEuCyfQF37BIRAJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e26e9fa629792b2a64686a6442c9862bacea357/tools/perf/bench_common.sh#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line is too long. Please break and indent to `a single-sided` with spaces.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-20 04:46 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 1 of 4 files reviewed, 12 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)



<!-- Sent from Reviewable.io -->

2021-04-21 08:44 UTC, janekmi requested changes
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/ib_read.sh, line 150 at r5](https://reviewable.io/reviews/pmem/rpma/974#-MYn_SS90Aspc2Zx4sKv:-MYn_SS90Aspc2Zx4sKw:b-vc5rbg) ([raw file](https://github.com/pmem/rpma/blob/49f00de0f2edf7228675585c2acc0bfa703940aa/tools/perf/ib_read.sh#L150)):*
> ```Shell
> 	#By default, Direct Write to PMem is impossible due to DDIO=on
> 	#which forces writing to cache instead of PMem directly.
> 	#This test requires restoring the default settings.
> ```

You are missing space after the hash in all of these lines.
___
*[tools/perf/bench_common.sh, line 236 at r5](https://reviewable.io/reviews/pmem/rpma/974#-MYnZu9r7loim1jGND22:-MYnZu9r7loim1jGND23:b-jhy7qd) ([raw file](https://github.com/pmem/rpma/blob/49f00de0f2edf7228675585c2acc0bfa703940aa/tools/perf/bench_common.sh#L236)):*
> ```Shell
> 			;;
> 		esac
> ```

The if-condition above has to be replaced with something like:

```sh
if [ "x$REMOTE_CMD" != "x" ]; then
    return
fi
```


<!-- Sent from Reviewable.io -->

2021-04-21 08:54 UTC, osalyk reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/ib_read.sh, line 150 at r5](https://reviewable.io/reviews/pmem/rpma/974#-MYn_SS90Aspc2Zx4sKv:-MYnbrZ34WpdwwhjLeR5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/49f00de0f2edf7228675585c2acc0bfa703940aa/tools/perf/ib_read.sh#L150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing space after the hash in all of these lines.
</blockquote></details>

Done.
___
*[tools/perf/bench_common.sh, line 236 at r5](https://reviewable.io/reviews/pmem/rpma/974#-MYnZu9r7loim1jGND22:-MYncPs94_SFlCbl_iPc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/49f00de0f2edf7228675585c2acc0bfa703940aa/tools/perf/bench_common.sh#L236)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The if-condition above has to be replaced with something like:

```sh
if [ "x$REMOTE_CMD" != "x" ]; then
    return
fi
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-21 11:05 UTC, janekmi approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974#-:-MYo5mUC-hRKM7_tX187:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2021-04-26 10:14 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r4, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/974#-:-MZCf80lA6xoayVbgxuu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/bench_common.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/974#-MYKBf4ADG7diJcO7nAm:-MZCcZih698Tjw5ppTYv:be0o4ec) ([raw file](https://github.com/pmem/rpma/blob/9ba5c3807e4ee239afde2dde284254da58a415b6/tools/perf/bench_common.sh#L120)):*
> to get only required parameters right away but with an option how to list also optional or debug

Good idea.


<!-- Sent from Reviewable.io -->

2021-04-26 11:28 UTC, merged