rpma: refactor enum rpma_op
pmem/rpma pull request #979
Opened 2021-04-06 06:59 UTC by yangx-jy

2021-04-06 07:34 UTC, yangx-jy reviewed
Hi @ldorau @janekmi

Why does codecov/project report a failure?  I didn't find any obvious error.

Best Regards,
Xiao Yang

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979#-:-MXa4rqn1uH0lkfQSpdj:b-hgo3bx)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-06 09:56 UTC, ldorau commented
> Hi @ldorau @janekmi
> 
> Why does codecov/project report a failure? I didn't find any obvious error.
> 
> Best Regards,
> Xiao Yang
> 

Hi @yangx-jy all is OK with your PR as regards the Codecov Report. You have removed 14 lines of code that were hit by Codecov, so the coverage dropped by 0.01%  but it is OK, there is nothing to be fixed.

2021-04-06 23:48 UTC, yangx-jy reviewed
@ldorau 

Got it.  Thanks for your explanation.

Best Regards,
Xiao Yang

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979#-:-MXd_9xp5OBcjyNNchj0:b-ca56zl)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-04-17 10:22 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-MXq0_vl3S8-tf-5cibi:b-yh9637) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
> ```
> cmpl->op = (enum rpma_op)wc.opcode;
> ```
This way of `enum ibv_wc_opcode` to `enum rpma_op` is a tricky one.
What if abandon `enum rpma_op`


<!-- Sent from Reviewable.io -->

2021-04-19 01:38 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-MYbgjTq8wnT_itkmIRZ:bn1y6cl) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> cmpl->op = (enum rpma_op)wc.opcode;
> ```
This way of `enum ibv_wc_opcode` to `enum rpma_op` is a tricky one.
What if abandon `enum rpma_op`
</blockquote></details>

Hi @grom72 

@janekmi also suggested discarding  `enum rpma_op`, but in this case, we still have some problems as issue #976 metioned:
1) It is not clear for user to know which rpma operation is completed and all existing examples/upper applications have to be rewritten.
2) We cannot find a way to report RPMA_OP_FLUSH for now because it is hard to distinguish between real read and flush completion events.

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-04-30 08:20 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-MZWrBcg06flQKBKu4-S:byaqcnc) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

@janekmi also suggested discarding  `enum rpma_op`, but in this case, we still have some problems as issue #976 metioned:
1) It is not clear for user to know which rpma operation is completed and all existing examples/upper applications have to be rewritten.
2) We cannot find a way to report RPMA_OP_FLUSH for now because it is hard to distinguish between real read and flush completion events.

Best Regards,
Xiao Yang
</blockquote></details>

enum rpma_op originally has been designed to cover different implementation of the flush operation (either APM with read or GPSPM with send/receive). We have abandoned this approach as it brings big complexity to the library.


<!-- Sent from Reviewable.io -->

2021-04-30 08:32 UTC, yangx-jy commented
___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-MZWscLUEC-u-JHzuXQd:bsaoub0) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

enum rpma_op originally has been designed to cover different implementation of the flush operation (either APM with read or GPSPM with send/receive). We have abandoned this approach as it brings big complexity to the library.
</blockquote></details>

Hi @grom72 

It seems that both you and @janekmi agree to abandon `enum rpma_op`.
I will plan to use `enum ibv_wc_opcode` directly, is it OK?

Best Regards,
Xiao Yang


<!-- Sent from Reviewable.io -->

2021-08-23 19:15 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-M_dlmfP0Z4LafjtMmJZ:b-r155ta) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @grom72 

It seems that both you and @janekmi agree to abandon `enum rpma_op`.
I will plan to use `enum ibv_wc_opcode` directly, is it OK?

Best Regards,
Xiao Yang
</blockquote></details>

I'm OK with such a change.


<!-- Sent from Reviewable.io -->

2021-09-02 13:43 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-02 13:43 UTC, grom72 reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-09-07 05:20 UTC, yangx-jy commented
___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-Miyg14U3MO0IbgoeFUL:b-rst0a1) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I'm OK with such a change.
</blockquote></details>

@janekmi @ldorau 

Do you think so? I think we cannot find the better way to indicate the flush completion now.

BTW: I will update the PR by using `enum ibv_wc_opcode` diectly if you approve it.


<!-- Sent from Reviewable.io -->

2021-09-08 07:26 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-Mj3IFHk30Y-QhkYNjhY:b4qdvza) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@janekmi @ldorau 

Do you think so? I think we cannot find the better way to indicate the flush completion now.

BTW: I will update the PR by using `enum ibv_wc_opcode` diectly if you approve it.

</blockquote></details>

I agree with @grom72 


<!-- Sent from Reviewable.io -->

2021-09-08 07:27 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-Mj3IM7cDXM_lhR0LN8i:-Mj3IM7cDXM_lhR0LN8j:b-n6khor) (no related file):*
Please rebase

---


<!-- Sent from Reviewable.io -->

2021-09-08 07:41 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-Mj3LUP95B6GojQfJJ2F:b-y5gw66) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I agree with @grom72 
</blockquote></details>

@janekmi ??


<!-- Sent from Reviewable.io -->

2021-09-08 07:57 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-Mj3NWoB9r802fJ9QEAd:b-e0z003) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
> ```objc
> 	RPMA_OP_RECV = 1 << 7,
> 	RPMA_OP_RECV_RDMA_WITH_IMM,
> };
> ```

This is a not backward compatible change. I think it is not a good idea.

In my opinion, the easiest way to replace this enum in the near future with its libibverbs counterpart is by:

1. providing both values (we have to think about how to extend the rpma_completion structure though)
2. Updating all existing examples and software to use the new enum
3. Mark the old enum as deprecated
4. Stop using it with the 1.0 release


<!-- Sent from Reviewable.io -->

2021-09-17 09:19 UTC, yangx-jy commented
___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-Mjn0Ujc8zNcYVIjkGPO:bi7rq0w) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is a not backward compatible change. I think it is not a good idea.

In my opinion, the easiest way to replace this enum in the near future with its libibverbs counterpart is by:

1. providing both values (we have to think about how to extend the rpma_completion structure though)
2. Updating all existing examples and software to use the new enum
3. Mark the old enum as deprecated
4. Stop using it with the 1.0 release
</blockquote></details>

Hi @janekmi @grom72 @ldorau @osalyk  

I want to cleanup`enum rpma_op op` by the following steps:
------------------------------------------------------------------------------
1) add a new member `enum ibv_wc_opcode opcode`
2) Updating all existing examples
3) Mark the old `enum ibv_wc_opcode opcod` as deprecated and remove it.
-----------------------------------------------------------------------------
If you agreed, I will update the PR.


<!-- Sent from Reviewable.io -->

2021-09-27 11:15 UTC, grom72 reviewed
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-10-15 08:44 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-Mm26Z9Y8o8r45tV7cn5:b-gyb7zq) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi @grom72 @ldorau @osalyk  

I want to cleanup`enum rpma_op op` by the following steps:
------------------------------------------------------------------------------
1) add a new member `enum ibv_wc_opcode opcode`
2) Updating all existing examples
3) Mark the old `enum ibv_wc_opcode opcod` as deprecated and remove it.
-----------------------------------------------------------------------------
If you agreed, I will update the PR.

</blockquote></details>

Adding a new member breaks backward compatibility - just like in #1087 .


<!-- Sent from Reviewable.io -->

2021-10-15 08:45 UTC, ldorau reviewed
> Reviewed 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2021-10-15 13:51 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-Mm3D8oX7aDjbz7VHWt2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@janekmi ??
</blockquote></details>

.


<!-- Sent from Reviewable.io -->

2021-11-03 13:51 UTC, grom72 reviewed
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-01-10 08:01 UTC, grom72 requested changes
> Reviewed 10 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 10 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-Mt1zvXG-fePxAUGfyTw:bt7uzmg) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
> ```C
>  */
> int
> rpma_cq_get_wc(struct rpma_cq *cq, struct ibv_wc *wc)
> ```

Shall we extend this new API with the num_entries parameter?
polling more than one wc is recommended way to optimize completion handling.
@janekmi @ldorau what do you think?



_Code quote:_
```C
rpma_cq_get_wc(struct rpma_cq *cq, struct ibv_wc *wc)
```


<!-- Sent from Reviewable.io -->

2022-01-10 08:05 UTC, grom72 reviewed
> Reviewed 4 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-01-10 08:07 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-Mt20P0j6QsD00zEH0rf:b-8ahvt4) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we extend this new API with the num_entries parameter?
polling more than one wc is recommended way to optimize completion handling.
@janekmi @ldorau what do you think?
</blockquote></details>

I think the answer is: yes. But then we have to well document the return value which has to handle both error codes and the number of entries read from the CQ.


<!-- Sent from Reviewable.io -->

2022-01-10 11:18 UTC, yangx-jy commented
___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-Mt2h89k4mv1x3LAKAEz:b-a41pq7) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the answer is: yes. But then we have to well document the return value which has to handle both error codes and the number of entries read from the CQ.
</blockquote></details>

It's fine for me to extend `rpma_cq_get_wc()` with num_entries.
One question: is it necessary to check if num_entries > =1?


<!-- Sent from Reviewable.io -->

2022-01-11 10:08 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[src/conn.c, line 570 at r1](https://reviewable.io/reviews/pmem/rpma/979#-MXq0_vl3S8-tf-5cibh:-Mt7anIn-oLbCrO2B_mN:b-mj33dc) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/conn.c#L570)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

I propose to skip this as we are going to remove rpma_cq_get_completion.


<!-- Sent from Reviewable.io -->

2022-01-12 03:07 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-Mj3IM7cDXM_lhR0LN8i:-MtBEuCQ1oI1RNXP12eC:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-MtBEzdJB-A47q2K4wkk:b-33j7m4) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It's fine for me to extend `rpma_cq_get_wc()` with num_entries.
One question: is it necessary to check if num_entries > =1?
</blockquote></details>

I have update this PR as your suggestion.
___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-MtBF6FXC_g0waKt26G1:b-9wb4il) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Adding a new member breaks backward compatibility - just like in #1087 .
</blockquote></details>

Done. Drop this method.


<!-- Sent from Reviewable.io -->

2022-01-12 07:45 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-MtCEymX71_aTNn9z6eT:b-nkk09l) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I have update this PR as your suggestion.
</blockquote></details>

How do we know how many completions has been received?


<!-- Sent from Reviewable.io -->

2022-01-12 09:07 UTC, yangx-jy commented
___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-MtCXNhU5KqZ2MzcmOr3:bagnrqr) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

How do we know how many completions has been received?
</blockquote></details>

We can see the return value of `rpma_cq_get_wc`, do you have any different idea? 


<!-- Sent from Reviewable.io -->

2022-01-19 15:40 UTC, ldorau requested changes
> Reviewed 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-MtmrOEFDY0WT2KwPrDf:bf4pm0c) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

We can see the return value of `rpma_cq_get_wc`, do you have any different idea? 
</blockquote></details>

Hi, @yangx-jy , we have discussed it with @grom72 and we propose to add a new argument (`got_entries`?) to return a number of received completions. We do want to maintain the rule (obeyed by all the current API) that a return value different from zero always means an error. The new additional argument would not be needed if `num_entries == 1` and could be NULL in this case. It would be required for `num_entries > 1`:

```c
int
rpma_cq_get_wc(struct rpma_cq *cq, int num_entries, struct ibv_wc *wc,
		int *got_entries)
{
	if (cq == NULL || num_entries < 1 || wc == NULL)
		return RPMA_E_INVAL;

	if (num_entries > 1 && got_entries == NULL)
		return RPMA_E_INVAL;

	/* ... no changes here ... */

	if (got_entries)
		*got_entries = result;

	return 0;
}

```
___
*[src/include/librpma.h, line 2958 at r5](https://reviewable.io/reviews/pmem/rpma/979#-MtmwvUh8hroNLZql3Ak:-MtmwvUh8hroNLZql3Al:bsixqqo) ([raw file](https://github.com/pmem/rpma/blob/56bd5d96fc345cb2da522a5da41b1d6f41c39294/src/include/librpma.h#L2958)):*
> ```objc
>  * of ibv_wc structs. It receivces all completions if the number of entires
>  * in the specified CQ is fewer than num_entries. All operations generate
>  * completions on error. The operations posted with the RPMA_F_COMPLETION_ALWAYS
> ```

```
 * DESCRIPTION
 * rpma_cq_get_wc() polls the cq CQ for work completions and returns the first
 * num_entries (or all available completions if the CQ contains fewer than this
 * number) in the wc array exactly like ibv_poll_cq(3) does. The argument wc is
 * a pointer to an array of ibv_wc structs, as defined in <infiniband/verbs.h>.
 * A number of got completions is returned in the got_entries argument,
 * if it is not NULL. It can be NULL only if num_entries equals 1.
 * 
 * All operations generate ...
```



_Code quote:_
```objc
 * DESCRIPTION
 * rpma_cq_get_wc() receives num_entries completions of already posted
 * operations from the specified CQ to the wc which is a pointer to an array
 * of ibv_wc structs. It receivces all completions if the number of entires
 * in the specified CQ is fewer than num_entries. All operations generate
 * completions on error. The operations posted with the RPMA_F_COMPLETION_ALWAYS
 * flag also generate completions on success. Please see ibv_poll_cq(3)'s
 * manual for details about struct ibv_wc.
```


<!-- Sent from Reviewable.io -->

2022-01-20 05:40 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-Mtlblj32aIDQII8Hixp:b32v57) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Hi, @yangx-jy , we have discussed it with @grom72 and we propose to add a new argument (`got_entries`?) to return a number of received completions. We do want to maintain the rule (obeyed by all the current API) that a return value different from zero always means an error. The new additional argument would not be needed if `num_entries == 1` and could be NULL in this case. It would be required for `num_entries > 1`:

```c
int
rpma_cq_get_wc(struct rpma_cq *cq, int num_entries, struct ibv_wc *wc,
		int *got_entries)
{
	if (cq == NULL || num_entries < 1 || wc == NULL)
		return RPMA_E_INVAL;

	if (num_entries > 1 && got_entries == NULL)
		return RPMA_E_INVAL;

	/* ... no changes here ... */

	if (got_entries)
		*got_entries = result;

	return 0;
}

```

</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-01-20 08:13 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-MtqXvGn7YpTjq3V5Dio:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2958 at r5](https://reviewable.io/reviews/pmem/rpma/979#-MtmwvUh8hroNLZql3Ak:-MtqXwEZ7DNYFMjsUBYk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/56bd5d96fc345cb2da522a5da41b1d6f41c39294/src/include/librpma.h#L2958)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
 * DESCRIPTION
 * rpma_cq_get_wc() polls the cq CQ for work completions and returns the first
 * num_entries (or all available completions if the CQ contains fewer than this
 * number) in the wc array exactly like ibv_poll_cq(3) does. The argument wc is
 * a pointer to an array of ibv_wc structs, as defined in <infiniband/verbs.h>.
 * A number of got completions is returned in the got_entries argument,
 * if it is not NULL. It can be NULL only if num_entries equals 1.
 * 
 * All operations generate ...
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 08:56 UTC, ldorau requested changes
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 269 at r4](https://reviewable.io/reviews/pmem/rpma/979#-Mt1zvXF-Y_QdMQ-r9sl:-MtqeoZxBF8N2j7aWg1C:b-ucfknh) ([raw file](https://github.com/pmem/rpma/blob/e0dd6d02e8754b6de463675c0c697854384e3cae/src/cq.c#L269)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!
___
*[src/include/librpma.h, line 2973 at r6](https://reviewable.io/reviews/pmem/rpma/979#-MtqftiP-q9mpx_1X50o:-MtqftiP-q9mpx_1X50p:bp69txx) ([raw file](https://github.com/pmem/rpma/blob/e2005579d9b7719c4240e83d103837bed2387ae8/src/include/librpma.h#L2973)):*
> ```objc
>  * The rpma_cq_get_wc() function returns 0 on success or a negative error code
>  * on failure. On success, it saves all got completions and their number into
>  * the wc and got_entries. If the status of a completion is not equal to
> ```

... the wc and got_entries **respectively**.



_Code quote:_
```objc
the wc and got_entries
```
___
*[src/include/librpma.h, line 2980 at r6](https://reviewable.io/reviews/pmem/rpma/979#-MtqgmTcAvAIowhUHy09:-MtqgmTd7dF-oJOOOhqq:b-7tiexa) ([raw file](https://github.com/pmem/rpma/blob/e2005579d9b7719c4240e83d103837bed2387ae8/src/include/librpma.h#L2980)):*
> ```objc
>  * rpma_cq_get_wc() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - num_entries < 1, cq or wc is NULL
> ```

This case is missing here:
```
	if (num_entries > 1 && got_entries == NULL)
		return RPMA_E_INVAL;
```



_Code quote:_
```objc
 RPMA_E_INVAL - num_entries < 1, cq or wc is NULL
```


<!-- Sent from Reviewable.io -->

2022-01-20 09:15 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-get_wc.c, line 26 at r6](https://reviewable.io/reviews/pmem/rpma/979#-Mtql0miBFYNBLTE6Z7n:-Mtql0miBFYNBLTE6Z7o:bzgw442) ([raw file](https://github.com/pmem/rpma/blob/e2005579d9b7719c4240e83d103837bed2387ae8/tests/unit/cq/cq-get_wc.c#L26)):*
> ```C
> 	IBV_WC_RECV_RDMA_WITH_IMM
> };
> static unsigned flags[] = {
> ```

Please add one empty line in between.



_Code quote:_
```C
};
static unsigned flags[] = {
```
___
*[tests/unit/cq/cq-get_wc.c, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/979#-MtqkkyJ9vw02ZDT4E3L:-MtqkkyJ9vw02ZDT4E3M:ba2iw1n) ([raw file](https://github.com/pmem/rpma/blob/e2005579d9b7719c4240e83d103837bed2387ae8/tests/unit/cq/cq-get_wc.c#L35)):*
> ```C
> };
> 
> static int n_values = sizeof(opcodes) / sizeof(opcodes[0]);
> ```

`N_values` - we have a rule that global variables starts with a capital letter.



_Code quote:_
```C
static int n_values
```
___
*[tests/unit/cq/cq-get_wc.c, line 38 at r6](https://reviewable.io/reviews/pmem/rpma/979#-Mtql73BBm8ho62xoir-:-Mtql73BBm8ho62xoir0:b2n8yol) ([raw file](https://github.com/pmem/rpma/blob/e2005579d9b7719c4240e83d103837bed2387ae8/tests/unit/cq/cq-get_wc.c#L38)):*
> ```C
> 
> /*
>  * poll_cq -- poll_cq() mock
> ```

mock of ibv_poll_cq()



_Code quote:_
```C
poll_cq() mock
```


<!-- Sent from Reviewable.io -->

2022-01-20 09:16 UTC, ldorau reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-MtqlP1Q0hLr0fLE_uBC:brujztc) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done. Drop this method.
</blockquote></details>

OK, thanks.


<!-- Sent from Reviewable.io -->

2022-01-20 11:30 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-20 11:33 UTC, ldorau approved these changes
Can you convert this draft to normal pull request or do you want to add something more?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979#-:-MtrFmMA9StWAhK9I7DU:bwspldp)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-20 11:45 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 270 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrIPQtCDnSqSE2CYYs:-MtrIPQtCDnSqSE2CYYt:bbv3iwv) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/src/cq.c#L270)):*
> ```C
> int
> rpma_cq_get_wc(struct rpma_cq *cq, int num_entries, struct ibv_wc *wc,
> 		int *got_entries)
> ```

num_entries_got



_Code quote:_
```C
got_entries
```


<!-- Sent from Reviewable.io -->

2022-01-20 11:46 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[src/cq.c, line 270 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrIU_e0qCyZ2_u-mbc:-MtrIU_e0qCyZ2_u-mbd:bom7nlm) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/src/cq.c#L270)):*
> ```C
> int
> rpma_cq_get_wc(struct rpma_cq *cq, int num_entries, struct ibv_wc *wc,
> 		int *got_entries)
> ```

One minor change more - could you replace all `got_entries` with `num_entries_got` ? - it will be more clear.



_Code quote:_
```C
got_entries
```


<!-- Sent from Reviewable.io -->

2022-01-20 11:55 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-MtrK1ka2xK5rmBSP6hv:-MtrK1ka2xK5rmBSP6hw:bpmauxx) (no related file):*
do we have tests for rpma_cq_get_wc covering condition "request x but get y < x"?

---


<!-- Sent from Reviewable.io -->

2022-01-20 11:57 UTC, grom72 reviewed
> Reviewed 2 of 4 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-01-20 12:12 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-get_wc.c, line 241 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrOeFK3NaTzUCx99AK:-MtrOeFL1NLi3_NSxL8-:b3ch1ox) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/tests/unit/cq/cq-get_wc.c#L241)):*
> ```C
>  */
> static void
> get_wc__success_6(void **cq_ptr)
> ```

get_wc__success_all_opcodes



_Code quote:_
```C
get_wc__success_6
```


<!-- Sent from Reviewable.io -->

2022-01-20 12:37 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-MtrU-amDPhlqgISd0Y2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 13:33 UTC, ldorau requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-get_wc.c, line 241 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrOeFK3NaTzUCx99AK:-Mtrg0BX-tZCFkQxcxIg:bof8a1u) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/tests/unit/cq/cq-get_wc.c#L241)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

get_wc__success_all_opcodes
</blockquote></details>

all_opcode**s**
___
*[tests/unit/cq/cq-get_wc.c, line 264 at r8](https://reviewable.io/reviews/pmem/rpma/979#-MtrgIE51qvZf7oMmO5S:-MtrgIE51qvZf7oMmO5T:bns1tj8) ([raw file](https://github.com/pmem/rpma/blob/9ab0181925379c064af65e48eda22201450c3238/tests/unit/cq/cq-get_wc.c#L264)):*
> ```C
> 				 */
> 				orig_wc[j].wc_flags =
> 						(typeof(orig_wc[j].wc_flags))flags[j];
> ```

`/rpma/tests/unit/cq/cq-get_wc.c:264: line > 80 characters`


<!-- Sent from Reviewable.io -->

2022-01-20 13:48 UTC, ldorau requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @osalyk, and @yangx-jy)

___
*[tests/unit/cq/cq-get_wc.c, line 241 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrOeFK3NaTzUCx99AK:-MtrjeAj8dE2qu44mGtW:b-b1eia5) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/tests/unit/cq/cq-get_wc.c#L241)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

all_opcode**s**
</blockquote></details>

We meant: get_wc__success_all_opcode**s** (with `s` at the end)


<!-- Sent from Reviewable.io -->

2022-01-20 13:54 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-MtrK1ka2xK5rmBSP6hv:-MtrkXVC0O-iajxlqBhh:bc8rlmg) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we have tests for rpma_cq_get_wc covering condition "request x but get y < x"?
</blockquote></details>

Done. I add this test in get_wc__success_all_opcodes.

---
___
*[src/cq.c, line 270 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrIPQtCDnSqSE2CYYs:-MtrkfMx0gWTM1h5kZms:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/src/cq.c#L270)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

num_entries_got
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get_wc.c, line 241 at r7](https://reviewable.io/reviews/pmem/rpma/979#-MtrOeFK3NaTzUCx99AK:-Mtrkk0cB8Z80CBCUY4C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/11f5a47d14e65e55f8db9463b94a4fa2cb7c99e0/tests/unit/cq/cq-get_wc.c#L241)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We meant: get_wc__success_all_opcode**s** (with `s` at the end)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-20 14:03 UTC, yangx-jy commented
@grom72 @ldorau 

I also think the draft tag can be removed now.





<!-- Sent from Reviewable.io -->

2022-01-20 15:38 UTC, ldorau approved these changes
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-21 01:51 UTC, yangx-jy commented
When this PR is merged, I will make all examples use `rpma_cq_get_wc()` and mark `rpma_cq_get_completion()` as deprecated.





<!-- Sent from Reviewable.io -->

2022-01-21 08:26 UTC, ldorau commented
> When this PR is merged, I will make all examples use `rpma_cq_get_wc()` and mark `rpma_cq_get_completion()` as deprecated.

Great, thanks!

2022-01-21 08:29 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-21 09:03 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-21 09:06 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-21 09:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk and @yangx-jy)

___
*[tests/unit/cq/cq-get_wc.c, line 143 at r10](https://reviewable.io/reviews/pmem/rpma/979#-Mtvl6IvBqST1HNZ12G8:-Mtvl6Iw8dccC6XMF7gE:bk1ii85) ([raw file](https://github.com/pmem/rpma/blob/27aac948ad04d7c6587337516459f79fc635a169/tests/unit/cq/cq-get_wc.c#L143)):*
> ```C
> 
> /*
>  * get_wc__poll_cq_0 - ibv_poll_cq() returns 0 (no data)
> ```

Could you rename this function to `get_wc__poll_cq_no_data`, please?



_Code quote:_
```C
get_wc__poll_cq_0
```
___
*[tests/unit/cq/cq-get_wc.c, line 164 at r10](https://reviewable.io/reviews/pmem/rpma/979#-MtvlIKY1qZlPRxz0pha:-MtvlIKY1qZlPRxz0phb:b1fq84x) ([raw file](https://github.com/pmem/rpma/blob/27aac948ad04d7c6587337516459f79fc635a169/tests/unit/cq/cq-get_wc.c#L164)):*
> ```C
> 
> /*
>  * get_wc__poll_cq_3 - ibv_poll_cq() returns 3 (more then
> ```

Could you rename this function to `get_wc__poll_cq_more_data`, please?



_Code quote:_
```C
get_wc__poll_cq_3
```


<!-- Sent from Reviewable.io -->

2022-01-21 09:48 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/cq/cq-get_wc.c, line 143 at r10](https://reviewable.io/reviews/pmem/rpma/979#-Mtvl6IvBqST1HNZ12G8:-Mtw1NNL5Oc9o_ygzDeP:b-ucfknh) ([raw file](https://github.com/pmem/rpma/blob/27aac948ad04d7c6587337516459f79fc635a169/tests/unit/cq/cq-get_wc.c#L143)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you rename this function to `get_wc__poll_cq_no_data`, please?
</blockquote></details>

Thanks!
___
*[tests/unit/cq/cq-get_wc.c, line 164 at r10](https://reviewable.io/reviews/pmem/rpma/979#-MtvlIKY1qZlPRxz0pha:-Mtw1Op5AXGXAgXYS6Zy:b-ucfknh) ([raw file](https://github.com/pmem/rpma/blob/27aac948ad04d7c6587337516459f79fc635a169/tests/unit/cq/cq-get_wc.c#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you rename this function to `get_wc__poll_cq_more_data`, please?
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2022-01-21 10:28 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-24 09:31 UTC, grom72 requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-MuAQ0Hb2l9xOKE6-zXe:-MuAQ0Hb2l9xOKE6-zXf:b8f3s0z) (no related file):*
Let's wait until 0.10 is released but from a technical point of view no new issues ( :goat: )

---


<!-- Sent from Reviewable.io -->

2022-01-24 11:19 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @yangx-jy)



<!-- Sent from Reviewable.io -->

2022-01-24 21:06 UTC, ldorau requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-MuAQ0Hb2l9xOKE6-zXe:-MuCuBx65fC-8Pi2qjNj:br30aky) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's wait until 0.10 is released but from a technical point of view no new issues ( :goat: )
</blockquote></details>

librpma v0.10.0 has been released.

@yangx-jy please rebase on the current master.

---


<!-- Sent from Reviewable.io -->

2022-01-25 02:09 UTC, yangx-jy reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/979#-MuAQ0Hb2l9xOKE6-zXe:-MuDzh6DArbcrQGbSY2k:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

librpma v0.10.0 has been released.

@yangx-jy please rebase on the current master.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2022-01-25 07:35 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-25 09:16 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 2481 at r1](https://reviewable.io/reviews/pmem/rpma/979#-Mj3NWoB9r802fJ9QEAc:-MuFWJFOAlDj50CaBO9F:b-eapff3) ([raw file](https://github.com/pmem/rpma/blob/0b399f5365064eb4c712f1ac29a69bbeb8a272e5/src/include/librpma.h#L2481)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Resolved.


<!-- Sent from Reviewable.io -->

2022-01-25 09:18 UTC, grom72 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r8, 1 of 1 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979#-:-MuFWsVk9NxZ9Lkw1MUT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-25 09:18 UTC, grom72 approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-25 09:19 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/979)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)



<!-- Sent from Reviewable.io -->

2022-01-25 09:20 UTC, merged

2022-01-25 09:21 UTC, ldorau commented
@yangx-jy pull request merged