tests: introduce "framework" for MT tests
pmem/rpma pull request #981
Opened 2021-04-07 14:01 UTC by janekmi

2021-04-08 05:39 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-08 05:49 UTC, ldorau reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-08 05:53 UTC, ldorau requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_test.h, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk1Ika5ImJ8Y9gooim:-MXk1Ika5ImJ8Y9gooin:b-4z5bbk) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L34)):*
> ```
> in both context
> ```

contexts


<!-- Sent from Reviewable.io -->

2021-04-08 06:06 UTC, ldorau requested changes
Great! :goat: 

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981#-:-MXk4fam2evXZJTj_lWS:b-w62gy4)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_test.c, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk2dpJ4LDYPc97uGOv:-MXk2dpJ4LDYPc97uGOw:b73yclh) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.c#L55)):*
> ```
> run a provided
> ```

run the provided
___
*[tests/multithreaded/common/mt_test.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk3wIt0oxztM94nhYQ:-MXk3wIt0oxztM94nhYR:b5wb47e) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.c#L81)):*
> ```
> fprintf(stderr, "malloc failed\n");
> ```

Maybe: `"error: malloc() failed\n"`  ?
___
*[tests/multithreaded/common/mt_test.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk45U7-HUFeOtJrB68:-MXk45U7-HUFeOtJrB69:b-664a03) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.c#L87)):*
> ```
> fprintf(stderr, "malloc failed\n");
> ```

.


<!-- Sent from Reviewable.io -->

2021-04-08 07:19 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/mt_test.h, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk1Ika5ImJ8Y9gooim:-MXkJbzE7_SWmNRk0_vK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> in both context
> ```

contexts
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.c, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk2dpJ4LDYPc97uGOv:-MXkJfnu1kuCYOmle-wY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.c#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> run a provided
> ```

run the provided
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-08 07:20 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/common/mt_test.h, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk3tfU60TSBj4fC14e:-MXk3tfU60TSBj4fC14f:bit6usp) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L15)):*
> ```
> 	/* arguments coming from the command line */
> 	unsigned threads_num;
> 	char *addr;
> ```
can we have a separate structure for arguments only?
I expect that arg section will be extended in the future e.i. port, pmem, etc
___
*[tests/multithreaded/common/mt_test.h, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-LGe5cS6QQNKLwGA:-MXk-LGe5cS6QQNKLwGB:b-mljems) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L48)):*
> ```
> mt_test_thread_args_init
> ```
```mt_test_init```
___
*[tests/multithreaded/common/mt_test.h, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-XzGDWPuW-3K-eH8:-MXk-XzGDWPuW-3K-eH9:b-40vpvg) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L48)):*
> ```
> *args
> ```
```*state```?
___
*[tests/multithreaded/common/mt_test.h, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-qzQ-3ADMifc_DSs:-MXk-qzQ-3ADMifc_DSt:b-8dlk4w) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L50)):*
> ```
> mt_test_thread_args_fini
> ```
```mt_test_fini```
___
*[tests/multithreaded/common/mt_test.h, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-xbn2P1VC5DtwwwV:-MXk-xbn2P1VC5DtwwwW:b8ad5o2) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L51)):*
> ```
> mt_test_thread_func
> ```
```mt_run```


<!-- Sent from Reviewable.io -->

2021-04-08 07:41 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 2 of 4 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/common/mt_test.h, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-LGe5cS6QQNKLwGA:-MXkQRU891W-CyZWSIyp:b5i3bf) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_test_thread_args_init
> ```
```mt_test_init```
</blockquote></details>

```mt_test_thread_init```


<!-- Sent from Reviewable.io -->

2021-04-08 07:55 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 2 of 4 files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/common/mt_test.h, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXkRciYEFdh2SRQXxc3:-MXkRciYEFdh2SRQXxc4:b2x69hi) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L37)):*
> ```
> struct mt_test_thread_ret {
> 	char errmsg[MT_TEST_ERRMSG_MAX];
> };
> ```
___
*[tests/multithreaded/common/mt_test.h, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXkTZdnBIoMOc4AS3DQ:-MXkTZdnBIoMOc4AS3DR:b-c76r0v) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L41)):*
> ```
> MT_TEST_THREAD_RPMA_ERR
> ```
``` MT_TEST_THREAD_RPMA_EXIT_WITH_ERR```


<!-- Sent from Reviewable.io -->

2021-04-08 08:04 UTC, ldorau approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/common/mt_test.h, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXkTZdnBIoMOc4AS3DQ:-MXkV3iHAHdQpxSxEWVI:b-kw92x7) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L41)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> MT_TEST_THREAD_RPMA_ERR
> ```
``` MT_TEST_THREAD_RPMA_EXIT_WITH_ERR```
</blockquote></details>

@grom72 Isn't `MT_TEST_THREAD_RPMA_EXIT_WITH_ERR` a bit too long?


<!-- Sent from Reviewable.io -->

2021-04-08 08:05 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981#-:-MXkVokx-UdGpE_1eu_Y:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-08 08:40 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mt_test.h, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk3tfU60TSBj4fC14e:-MXkXrAvBhXU8kxSEimC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 	/* arguments coming from the command line */
> 	unsigned threads_num;
> 	char *addr;
> ```
can we have a separate structure for arguments only?
I expect that arg section will be extended in the future e.i. port, pmem, etc
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.h, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXkRciYEFdh2SRQXxc3:-MXkZ2Os0gINQkQT54ix:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct mt_test_thread_ret {
> 	char errmsg[MT_TEST_ERRMSG_MAX];
> };
> ```

</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.h, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXkTZdnBIoMOc4AS3DQ:-MXkZ3Uw864DCOmmAFrs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 Isn't `MT_TEST_THREAD_RPMA_EXIT_WITH_ERR` a bit too long?
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.h, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-LGe5cS6QQNKLwGA:-MXkZFYp9mTEev3fo2GM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```mt_test_thread_init```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.h, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-XzGDWPuW-3K-eH8:-MXk_P9Q8D8Gigheof_C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L48)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> *args
> ```
```*state```?
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.h, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-qzQ-3ADMifc_DSs:-MXk_Pr74K7iBTQijZRh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L50)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_test_thread_args_fini
> ```
```mt_test_fini```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_test.h, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/981#-MXk-xbn2P1VC5DtwwwV:-MXk_Ucr7Ph4LZNJ2N5m:bdbnlrr) ([raw file](https://github.com/pmem/rpma/blob/b8c4ba081c849b0a3dba1e9ba9b6af0fea91a2e5/tests/multithreaded/common/mt_test.h#L51)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_test_thread_func
> ```
```mt_run```
</blockquote></details>

Sorry. Reserved. I want to have a strict naming convention here so it will be as obvious as possible what you can do and what you can not e.g.:
- mt_run - the runner itself
- mt_test - a test in general
- mt_test_thread - a single thread within the test


<!-- Sent from Reviewable.io -->

2021-04-08 11:01 UTC, grom72 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981#-:-MXl8-JI4-VG5HEjpd5s:bdycpsm)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)



<!-- Sent from Reviewable.io -->

2021-04-08 12:07 UTC, osalyk reviewed
> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-08 13:13 UTC, ldorau reviewed
> Reviewed 2 of 4 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-08 13:36 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_run.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXleQXiBBEunI42TpJh:-MXleQXiBBEunI42TpJi:b-2k8gip) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L30)):*
> ```
> mt_run_thread_arg
> ```
```mt_thread_run_arg```
___
*[tests/multithreaded/common/mt_run.c, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXleKvI91Hg2rZJ_vq4:-MXleKvJ5QaCYwyIydao:bowae2n) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L31)):*
> ```
> thread_func
> ```
```test_func```
___
*[tests/multithreaded/common/mt_run.c, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXledyO9AFgXO3Y94lR:-MXledyO9AFgXO3Y94lS:b-qwend1) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L32)):*
> ```
> mt_test_thread_result
> ```
```mt_hread_result```
or
```mt_func_result```
___
*[tests/multithreaded/common/mt_run.c, line 34 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXl_RuH3DqIiz7zhl4f:-MXl_RuH3DqIiz7zhl4g:b-hs6hpn) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L34)):*
> ```
> char thread_args[]
> ```
```char *thread_args```
___
*[tests/multithreaded/common/mt_run.c, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlfFb67OaojYj9KlUE:-MXlfFb67OaojYj9KlUF:bvl4oi9) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L38)):*
> ```
> the test
> ```
the function under testing
___
*[tests/multithreaded/common/mt_run.c, line 41 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlaKZX7WafAIcxCUv8:-MXlaKZX7WafAIcxCUv9:bdd8ukn) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L41)):*
> ```
> mt_run_thread
> ```
```mt_tread_run
```
mt_*<object_name_><_operation>*
___
*[tests/multithreaded/common/mt_run.c, line 159 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlc65K9WYIzepuGzt5:-MXlc65K9WYIzepuGzt6:bs69ugu) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L159)):*
> ```
> mt_run_global_init
> ```
```mt_test_init```
___
*[tests/multithreaded/common/mt_run.c, line 192 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlc1Lw8vqm0u3Nfity:-MXlc1Lw8vqm0u3Nfitz:b-smwd0e) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L192)):*
> ```
> mt_run_global_fini
> ```
```mt_test_fini```
___
*[tests/multithreaded/common/mt_run.c, line 224 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlbwz95Iim-9__BRCb:-MXlbwzA1maovqniYA7W:b-tryoox) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L224)):*
> ```
> mt_run_test
> ```
```mt_test_run```
___
*[tests/multithreaded/common/mt_run.c, line 244 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXldris6sLHkb3yh6Nz:-MXldrit4ndYqnd4cUzK:b-24rquj) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L244)):*
> ```
> mt_run_state_init(&state);
> ```
what is the purpose of this call?


<!-- Sent from Reviewable.io -->

2021-04-08 13:45 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_run.h, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXliXxNCKGOMjapoo12:-MXliXxNCKGOMjapoo13:b-g00s9u) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.h#L13)):*
> ```
> mt_run_state
> ```
mt_test_state
___
*[tests/multithreaded/common/mt_run.h, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXliS-6837zYEEQfoUU:-MXliS-6837zYEEQfoUV:bkvh59s) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.h#L14)):*
> ```
> mt_test_cli
> ```
mt_test_args
___
*[tests/multithreaded/common/mt_run.c, line 41 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlaKZX7WafAIcxCUv8:-MXliKm59sj65E3xKCRn:b-qsrurb) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L41)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_thread
> ```
```mt_tread_run
```
mt_*<object_name_><_operation>*
</blockquote></details>

mt_thread_run
___
*[tests/multithreaded/common/mt_test.h, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlhxTD23sC8rDlIXyu:-MXlhxTE-MtC6qNDs8Lu:byozs0c) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_test.h#L38)):*
> ```
> mt_test_cli
> ```
```mt_test_args```
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXli4IM80Bg0bpOv_fF:-MXli4IM80Bg0bpOv_fG:b5gbfec) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L14)):*
> ```C
> struct thread_args {
> 	/* shared */
> 	char *addr;
> ```

is there any reason to have a separate arg structure for each thread?


<!-- Sent from Reviewable.io -->

2021-04-08 13:46 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_run.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXleQXiBBEunI42TpJh:-MXlisjSCuDeB_UQU-dZ:bll293z) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L30)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_thread_arg
> ```
```mt_thread_run_arg```
</blockquote></details>

mt_thread_args


<!-- Sent from Reviewable.io -->

2021-04-08 22:50 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 14 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/common/mt_run.c, line 34 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXl_RuH3DqIiz7zhl4f:-MXnUYN74X6zjWxuyMY2:b-bt5f52) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L34)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> char thread_args[]
> ```
```char *thread_args```
</blockquote></details>

I know it effectively might compile into the same assembler. But I haven't heard of using such a syntax to achieve the aim we have here. Have you?

Ref: https://en.wikipedia.org/wiki/Flexible_array_member
___
*[tests/multithreaded/common/mt_run.c, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlfFb67OaojYj9KlUE:-MXnV-BN8_WrBoYEob0V:b-ib470r) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L38)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> the test
> ```
the function under testing
</blockquote></details>

I would argue I do not run a function under testing but a test that might test a single API call but it might be required to do a lot more.
___
*[tests/multithreaded/common/mt_run.c, line 244 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXldris6sLHkb3yh6Nz:-MXnVv7b9qV46ws0RTbs:b97cj96) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L244)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_state_init(&state);
> ```
what is the purpose of this call?
</blockquote></details>

Initialize the `mt_run` state. In the vocabulary I have proposed here "run" is a noun. I think we have to discuss this problem in its entirety not case-by-case. I will write my argument soon. Stay tuned.
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXli4IM80Bg0bpOv_fF:-MXnWceI0VNAeTNdQBv0:bnefw2l) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is there any reason to have a separate arg structure for each thread?
</blockquote></details>

Yes. This way the test can decide autonomously what data will thread consume and adjust this structure to its needs. I see the structure in this particular test might seems not glorious in any way. But having such a structure in future tests will be a must so I see no reason to introduce any other mechanism just for this test.

What is your proposition?


<!-- Sent from Reviewable.io -->

2021-04-09 05:06 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 13 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/common/mt_run.c, line 244 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXldris6sLHkb3yh6Nz:-MXoyoaM7ATW106BxRYZ:biye80x) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L244)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Initialize the `mt_run` state. In the vocabulary I have proposed here "run" is a noun. I think we have to discuss this problem in its entirety not case-by-case. I will write my argument soon. Stay tuned.
</blockquote></details>

What is the difference between run and test?
Do we have a run that runs a test or do we have a test that runs itself? 
Or do we have a test spec that is used to describe test behavior while the test is running?
Or do we have an abstract class `Test` and we define subclasses that define particular tests? and this abstract class `Test` has an abstract method `Run` 
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXli4IM80Bg0bpOv_fF:-MXoyRBi3Q4p4l2MRKui:b-d1xv7u) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. This way the test can decide autonomously what data will thread consume and adjust this structure to its needs. I see the structure in this particular test might seems not glorious in any way. But having such a structure in future tests will be a must so I see no reason to introduce any other mechanism just for this test.

What is your proposition?
</blockquote></details>

Can we have here a private copy of an address - just for education purposes?
```char addr[3+3+3+3+3+1]```
and strncpy() in get_ibv_context__thread_init()


<!-- Sent from Reviewable.io -->

2021-04-09 05:11 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_run.c, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlfFb67OaojYj9KlUE:-MXp0dyf1e9whSZfL3tm:b94wii5) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would argue I do not run a function under testing but a test that might test a single API call but it might be required to do a lot more.
</blockquote></details>

So why we do not use here `mt_run_test`?
___
*[tests/multithreaded/common/mt_run.c, line 244 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXldris6sLHkb3yh6Nz:-MXp1L8o22k55GlV_Ou4:b-ydj05y) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L244)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is the difference between run and test?
Do we have a run that runs a test or do we have a test that runs itself? 
Or do we have a test spec that is used to describe test behavior while the test is running?
Or do we have an abstract class `Test` and we define subclasses that define particular tests? and this abstract class `Test` has an abstract method `Run` 
</blockquote></details>

I see I have a problem accepting the 'run' as a noun ... For some reason.


<!-- Sent from Reviewable.io -->

2021-04-09 05:55 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 15 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXli4IM80Bg0bpOv_fF:-MXp734FDuwCWsKW5IoS:b-vbwwy8) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can we have here a private copy of an address - just for education purposes?
```char addr[3+3+3+3+3+1]```
and strncpy() in get_ibv_context__thread_init()
</blockquote></details>

One more thought: 
How do we inform the thread_init() function (below) what is the thread that the data is prepared for?
SHall we have at least an argument telling what is the number of the thread?
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXp8VvH9taIrPZqXhY7:-MXp8VvH9taIrPZqXhY8:b-1awhwj) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L24)):*
> ```
> get_ibv_context__thread_init
> ```
`get_ibv_context__thread_args_init`
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 37 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXp94kYAe8aOVmb0f6g:-MXp94kYAe8aOVmb0f6h:b-bhb5sx) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L37)):*
> ```
> get_ibv_context__thread
> ```
or `get_ibv_context__test`?

We have a test that is run in parallel in many instances of threads.

But it could also be run as a stand-alone test without any thread framework.


<!-- Sent from Reviewable.io -->

2021-04-09 08:54 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 15 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXli4IM80Bg0bpOv_fF:-MXpo5vf1TFBiSRZ0qAy:b-ar7qh0) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L14)):*
> Can we have here a private copy of an address - just for education purposes?

No. The whole point is to test the most extreme circumstances from the MT point of view. So, when the user will ask if he has to have a separate copy of the address to assure MT-safety we can just take a look at the test or even better document these guidelines.

> SHall we have at least an argument telling what is the number of the thread?

Maybe, at some point. If I would anticipate too many possibly useful features you may ask what they are for. I want to introduce features when we will be sure they are needed.


<!-- Sent from Reviewable.io -->

2021-04-09 10:43 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 15 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXli4IM80Bg0bpOv_fF:-MXqDL-_45UzUuutS6-M:b-fow0ti) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Can we have here a private copy of an address - just for education purposes?

No. The whole point is to test the most extreme circumstances from the MT point of view. So, when the user will ask if he has to have a separate copy of the address to assure MT-safety we can just take a look at the test or even better document these guidelines.

> SHall we have at least an argument telling what is the number of the thread?

Maybe, at some point. If I would anticipate too many possibly useful features you may ask what they are for. I want to introduce features when we will be sure they are needed.
</blockquote></details>

so why we do not have here a generic solution where we have for every test a pointer to mt_test_cli ?


<!-- Sent from Reviewable.io -->

2021-04-12 00:20 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 16 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/981#-MY2Q5WwBkW5MJgngnpK:-MY2Q5WwBkW5MJgngnpL:b-xd6peo) (no related file):*
We probably will have this discussion offline but I will just dump my thoughts on this for reference.

I see the current state of implementation as follows:

- mt_run_
    - global_init/_fini (1)
    - state (2)
    - test - (3) I agree it is a little bit confusing knowing mt_test is a separate thing.
    - thread (4)
        - _arg (5)
- mt_test_
    - cli (6)
    - thread_result (7)

After @grom72 comments I think I am closer to the following structure:

- mt_test
    - global_init/_fini (1) - I do not like the idea of calling it mt_test_init/_fini since we would probably need a common user-provided constructor for a test which I want to reserve this name for
    - state (2) - as you proposed
    - run (3) - as you proposed
    - thread (4) - I think you would like this idea better than `mt_thread_run` you have proposed.
        - _args (5) - It is not what you have proposed (`mt_thread_args`) but without the 'run' part I think you may like this.
        - _result (7) - I do not like `mt_thread_result` OR `mt_func_result` because this structure is used directly by the test and I want to have a common `mt_test_*` prefix for all of the API
    - args (6) - as you proposed

In my proposition a test consists of a few elements/steps:
- args - argc + argv
- init - a common initialization function for the test (not part of this PR)
- thread_init_func - a function preparing a single thread called once for each of the threads
- thread_func - a function executed in all of the threads
- thread_fini_func - cleanup a single thread
- fini - a common cleanup function (not part of this PR)

---


<!-- Sent from Reviewable.io -->

2021-04-12 07:49 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 4 of 5 files reviewed, 22 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mt_run.c, line 106 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3yqeh1dJEPRHtCs3C:-MY3yqeh1dJEPRHtCs3D:b-ttgm36) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L106)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 			/*
> 			 * No matter if the threads have been unblocked
> 			 * successfully or not nothing more can be done.
> 			 */
> ```
</details>

threads should check condition after they unblocked
perhaps the solution could be to zero `mt_test_sync.threads_num_waiting` to indicate that no thread is waiting
___
*[tests/multithreaded/common/mt_run.c, line 151 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3s4zF5RD2yX0CPg3E:-MY3s4zF5RD2yX0CPg3F:b-bq7nsp) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L151)):*
> ```
> state->threads_num_to_join = state->args.threads_num;
> ```
`state->threads_num_to_join` should reflect the actual state as I propose below in `mt_run_test`.
___
*[tests/multithreaded/common/mt_run.c, line 152 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3t8dJ35Tdzeq3QyGO:-MY3t8dKDphRGz3S9P5V:b-ji8qjz) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L152)):*
> ```
> state->threads_num_to_fini = state->args.threads_num;
> ```
.
___
*[tests/multithreaded/common/mt_run.c, line 273 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3t-MW7Hvl2lG_6yZM:-MY3t-MW7Hvl2lG_6yZN:bu97rms) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L273)):*
> ```C
> 		}
> 	}
> ```

`state.threads_num_to_fini = i;`
___
*[tests/multithreaded/common/mt_run.c, line 289 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY40YRK1R_DD1TAwYsz:-MY40YRK1R_DD1TAwYt-:bagvev2) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L289)):*
> ```
> state.threads_num_to_join = i;
> ```
this line could be moved after the for() loop
___
*[tests/multithreaded/common/mt_run.c, line 293 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3q-kk3VxhB2x_bvPU:-MY3q-kk3VxhB2x_bvPV:b89uv82) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L293)):*
> ```C
> 		}
> 	}
> ```

`state.threads_num_to_join = i;`


<!-- Sent from Reviewable.io -->

2021-04-12 09:14 UTC, grom72 reviewed
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 22 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-12 13:56 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 22 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-12 14:16 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 0 of 7 files reviewed, 21 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tests/multithreaded/common/mt_run.h, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXliXxNCKGOMjapoo12:-MY5Odxi0Oxmn9T2uZm5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.h#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_state
> ```
mt_test_state
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.h, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXliS-6837zYEEQfoUU:-MY5Odbk7qoeqciaNZPP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.h#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_test_cli
> ```
mt_test_args
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 30 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXleQXiBBEunI42TpJh:-MY5Ohq1EeD1TakzlEJN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L30)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

mt_thread_args
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXleKvI91Hg2rZJ_vq4:-MY5OhZSDA6jfqQa6U15:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> thread_func
> ```
```test_func```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXledyO9AFgXO3Y94lR:-MY5Oi8aEhhzmc9MLxVi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_test_thread_result
> ```
```mt_hread_result```
or
```mt_func_result```


</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 38 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlfFb67OaojYj9KlUE:-MY5OiSJE5OwUOXJsVn0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L38)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

So why we do not use here `mt_run_test`?
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 41 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlaKZX7WafAIcxCUv8:-MY5OfZ52IO9kOA-GrV8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L41)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

mt_thread_run
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 106 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3yqeh1dJEPRHtCs3C:-MY5PYJl8XCOBxvc-hAo:bjgsz4x) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			/*
> 			 * No matter if the threads have been unblocked
> 			 * successfully or not nothing more can be done.
> 			 */
> ```
threads should check condition after they unblocked
perhaps the solution could be to zero `mt_test_sync.threads_num_waiting` to indicate that no thread is waiting
</blockquote></details>

No thread is waiting since all of them already have registered as waiting. Guaranteed by the mutex.
But if the `pthread_cond_broadcast()` has failed we can not do anything more about it.
We can terminate the test since we have to way to clean up for the test. Waiting also is risky since we have no guarantee to return from the `pthread_join()`. I'm not sure what is better in this case. Both seem awful.

I think I'm for termination. Done.
___
*[tests/multithreaded/common/mt_run.c, line 151 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3s4zF5RD2yX0CPg3E:-MY5Oj3LAno8iQD0OccE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L151)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> state->threads_num_to_join = state->args.threads_num;
> ```
`state->threads_num_to_join` should reflect the actual state as I propose below in `mt_run_test`.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 152 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3t8dJ35Tdzeq3QyGO:-MY5PLU9Co8kVIsrpvbP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L152)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> state->threads_num_to_fini = state->args.threads_num;
> ```
.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 159 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlc65K9WYIzepuGzt5:-MY5OgcQ8riONSt3gBfC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L159)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_global_init
> ```
```mt_test_init```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 192 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlc1Lw8vqm0u3Nfity:-MY5OgDG8zA74VZx7G90:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L192)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_global_fini
> ```
```mt_test_fini```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 224 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXlbwz95Iim-9__BRCb:-MY5OfwP6faU3Cz51a9q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L224)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mt_run_test
> ```
```mt_test_run```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 244 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MXldris6sLHkb3yh6Nz:-MY5OhAY83Jtq7akWux_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L244)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I see I have a problem accepting the 'run' as a noun ... For some reason.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 273 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY3t-MW7Hvl2lG_6yZM:-MY5OkeE0unn1oWhpLxJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad922de9e891662b28134a8126a48bb588c458f8/tests/multithreaded/common/mt_run.c#L273)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

`state.threads_num_to_fini = i;`
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mt_run.c, line 289 at r4](https://reviewable.io/reviews/pmem/rpma/981#-MY40YRK1R_DD1TAwYsz:-MY5QRwB-Sb5vAa3uqCB:b-896fix) ([raw file](https://github.com/ [...]

2021-04-12 14:41 UTC, ldorau reviewed
> Reviewed 4 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 1 of 4 files reviewed, 20 unresolved discussions (waiting on @grom72 and @ldorau)



<!-- Sent from Reviewable.io -->

2021-04-12 16:01 UTC, grom72 reviewed
> Reviewed 1 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 1 of 4 files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 279 at r5](https://reviewable.io/reviews/pmem/rpma/981#-MY5kSWtAZwsNOM5DeGy:-MY5kSWtAZwsNOM5DeGz:b-o6l2my) ([raw file](https://github.com/pmem/rpma/blob/650e7eca73776f7615dd67db197ef8356ac9fde4/tests/multithreaded/common/mtt.c#L279)):*
> ```
> threads_num
> ```
threads_num_to_join


<!-- Sent from Reviewable.io -->

2021-04-12 16:45 UTC, grom72 reviewed
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981#-:-MY5yJ8j-Wkxr2-K_x1J:bdycpsm)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 42 at r5](https://reviewable.io/reviews/pmem/rpma/981#-MY5xBODDHVCi0m5SIHO:-MY5xBODDHVCi0m5SIHP:bgcn9oj) ([raw file](https://github.com/pmem/rpma/blob/650e7eca73776f7615dd67db197ef8356ac9fde4/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L42)):*
> ```
> args
> ```
please define test specific prestate


<!-- Sent from Reviewable.io -->

2021-04-12 16:46 UTC, grom72 reviewed
> Reviewed 3 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-12 23:28 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/multithreaded/common/mtt.c, line 279 at r5](https://reviewable.io/reviews/pmem/rpma/981#-MY5kSWtAZwsNOM5DeGy:-MY7O3iI7r95SMCs6T6e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/650e7eca73776f7615dd67db197ef8356ac9fde4/tests/multithreaded/common/mtt.c#L279)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> threads_num
> ```
threads_num_to_join
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 42 at r5](https://reviewable.io/reviews/pmem/rpma/981#-MY5xBODDHVCi0m5SIHO:-MY7PLiM8lWAohKVunMB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/650e7eca73776f7615dd67db197ef8356ac9fde4/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L42)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> args
> ```
please define test specific prestate
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-13 05:47 UTC, ldorau approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981#-:-MY8lDfr0jH0Plu4ynE8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-04-13 05:49 UTC, grom72 reviewed
> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8jgcUADPuwfukAsqw:-MY8jgcV5QCH6-3xls5l:b-jmz2rt) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.h#L45)):*
> ```
> typedef int (*mtt_thread_seq_init)(void *prestate, void **state_ptr,
> 		unsigned id);
> ```
`typedef int (*mtt_thread_seq_init)(void *prestate, unsigned id, void **state_ptr);`
inputs and read-only first, output last
___
*[tests/multithreaded/common/mtt.h, line 47 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8jukzAT3AWUHx-xRh:-MY8jukzAT3AWUHx-xRi:b-gy77jz) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.h#L47)):*
> ```
> typedef void (*mtt_thread_init)(void *prestate, void **state_ptr,
> 		unsigned id, struct mtt_thread_result *tr);
> ```
.
___
*[tests/multithreaded/common/mtt.c, line 297 at r5](https://reviewable.io/reviews/pmem/rpma/981#-MY8jK8H2oSmdMm3Utua:-MY8jK8I3GA43hFtxasE:b5jjlpn) ([raw file](https://github.com/pmem/rpma/blob/650e7eca73776f7615dd67db197ef8356ac9fde4/tests/multithreaded/common/mtt.c#L297)):*
> ```
> global_
> ```
:1st_place_medal: 
___
*[tests/multithreaded/common/mtt.c, line 86 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8kAfWAlSMx5SqOLvN:-MY8kAfWAlSMx5SqOLvO:bylwt5p) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.c#L86)):*
> ```
> tr->ret == 0 ? tr : &tr_dummy
> ```
`tr->ret? &tr_dummy: tr


<!-- Sent from Reviewable.io -->

2021-04-13 05:50 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-13 06:34 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 45 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8jgcUADPuwfukAsqw:-MY8vlC0BtYVfCfR6k-C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.h#L45)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> typedef int (*mtt_thread_seq_init)(void *prestate, void **state_ptr,
> 		unsigned id);
> ```
`typedef int (*mtt_thread_seq_init)(void *prestate, unsigned id, void **state_ptr);`
inputs and read-only first, output last
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 47 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8jukzAT3AWUHx-xRh:-MY8vmro1tDIyY5u9Yyj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.h#L47)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> typedef void (*mtt_thread_init)(void *prestate, void **state_ptr,
> 		unsigned id, struct mtt_thread_result *tr);
> ```
.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 86 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8kAfWAlSMx5SqOLvN:-MY8vpcJBeNUzFcXLKOi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.c#L86)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> tr->ret == 0 ? tr : &tr_dummy
> ```
`tr->ret? &tr_dummy: tr
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-13 06:34 UTC, ldorau approved these changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-04-13 06:34 UTC, ldorau approved these changes
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)



<!-- Sent from Reviewable.io -->

2021-04-13 06:42 UTC, grom72 reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.c, line 86 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8kAfWAlSMx5SqOLvN:-MY8xoj136h-gHh7-03z:b-omuz5p) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

'tr->ret? &tr_dummy: tr'


<!-- Sent from Reviewable.io -->

2021-04-13 06:54 UTC, janekmi reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 86 at r6](https://reviewable.io/reviews/pmem/rpma/981#-MY8kAfWAlSMx5SqOLvN:-MY9-cOoAGTEeN3EMDpY:b-fn8mpi) ([raw file](https://github.com/pmem/rpma/blob/26f7e233c926fc8860e4e41205a3d0aa3c1d4080/tests/multithreaded/common/mtt.c#L86)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

'tr->ret? &tr_dummy: tr'
</blockquote></details>

:facepalm: 


<!-- Sent from Reviewable.io -->

2021-04-13 07:02 UTC, grom72 reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/981#-:-MY91TKV3SM8vt3xX5Bc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)



<!-- Sent from Reviewable.io -->

2021-04-13 07:03 UTC, merged